### ISSUE TITLE
Better validation of build task parameters

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-tasks#1003]
Right now getting a build to work from scratch usually takes multiple attempts to get them right, especially for builds that publish something to say, a test environment, or even worse production, this is not ideal.

I'd love to see additional validation for items like, some may show a warning, others an error.
- Wildcards in textboxes that don't support wildcards (`*`, `?`, `**`)
- In general, invalid characters in path, see: https://github.com/Microsoft/vso-agent-tasks/issues/996, looks like the code already knows what valid characters are, though I suspect there may be some cross platform difficulty here...
- use of `/**/`, where the wildcard expansion expects `\**\`
- use of build variables which are undefined `$(BuildConfiguration)` vs `$(Build.Configuration)`
- use of version control paths that do not (currently) exist with the `$/` notation in the latest version.
- highlighting paths which could be substituted by a Variable on a task page (I see many people using `$(Agent.BuildDirectory)\s\` where they could have used a better matching variable `$(Build.SourcesDirectory)` in this case.

And in addition to that, for an even better experience, this could be extended with:
- Intellisense/autocompletion for variable names with their default substitution if available
- Auto-rename build variables from the Variables page
- Visibility of unused build variables on the Variables page

**Comment by bryanmacfarlane** [comment]
We are tracking this on the back log as part of new build UX work.  Not specifically a task issue in this repo
