### ISSUE TITLE
[Feature request] Send mail task

### ISSUE THREAD

**Issue by henning-krause** [Microsoft/vsts-tasks#1010]
It would be nice to have a "Send mail" build activity out of the box

**Comment by ilovesoftware** [comment]
+1

**Comment by bryanmacfarlane** [comment]
@chrisrpatterson for thoughts.  First reaction is market place but if the mail needs to go through our system we may potentially need a cmd.  We also need to consider xplat.  Might not be feasible

A market place task which takes the smtp info would be the simplest option

**Comment by pascalberger** [comment]
FYI There exists already an extension in the marketplace for sending mails through SMTP: https://marketplace.visualstudio.com/items?itemName=rvo.SendEmailTask

**Comment by bryanmacfarlane** [comment]
use extension
