### ISSUE TITLE
Making variables set by commands sensitive and masked in logs

### ISSUE THREAD

**Issue by pksorensen** [Microsoft/vsts-tasks#1074]
I have a OauthBroker task that sets the oauth token as a varaible for later tasks by using commands 

"##vso[task.setvariable variable=testvar;]testvalue"

It would be a good addition if it could take a falg to set the varaible as sensitive and it would be masked in the logs. I noticed that most of the implementation was already there for it from some of the other tasks that are already masking sensitive data.

**Comment by chrisrpatterson** [comment]
That is good feedback.  We will look into adding this.

**Comment by s093294** [comment]
Looks like its been completed.  issecret=true;

**Comment by bryanmacfarlane** [comment]
Yes, it was.  We also have a set-secret command in the new lib if you're writing a task.  https://github.com/Microsoft/vsts-task-lib
