### ISSUE TITLE
Option to make a build partially successful on warnings

### ISSUE THREAD

**Issue by JamesNK** [Microsoft/vsts-tasks#1102]
I'd like an option to make a build partially successful, i.e. yellow instead of green, when the build has warnings.

**Comment by bryanmacfarlane** [comment]
Is this from a custom task or just in general?

also, specific build engines (like msbuild etc...) often have options to fail the build on warnings (and we fail if msbuild fails).

outside of that, we could as an option for the build (options tab) if that's what you're after

**Comment by JamesNK** [comment]
Just in general. It is a setting that could be applied to every task type. Or it could be a build level settings.

In my case I am specifically thinking of a Visual Studio Build task. I don't want the build to fail on warnings - I'd still like tests to run and a package to be created - but I want to make it obvious when looking at the list of builds that it was partially successful via the yellow icon.

**Comment by pascalberger** [comment]
:+1: for introducing a state which indicates warnings on a build. State should also be available through the REST API (for eg. build screens) and be set from any build task (eg. possible to set build to yellow if quality gate in sonar is yellow)

**Comment by bgavrilMS** [comment]
@pascalberger I logged https://jira.sonarsource.com/browse/TBSTFNP-42 to track your request related to the SonarQube quality gate influencing the outcome of a build. I have already made changes   to fail the build if the SQ quality gate fails - these should be available in 1-2 weeks.

**Comment by pascalberger** [comment]
Thanks @bgavrilMS! Already saw your PR for the build breaking. Great :clap:

**Comment by bryanmacfarlane** [comment]
It's well past 1 - 2 weeks.  re-open if actionable item in task

**Comment by JamesNK** [comment]
So how do I enable this?

**Comment by gravufo** [comment]
Any news on this? Is it doable?

**Comment by CEsystemLLC** [comment]
you can add a task with its control options set to "Continue on Error". Whenever this tasks fails, your build will be partially succeeded. 

Control options > 
Enabled (checked)

**Comment by CEsystemLLC** [comment]
in Build Tasks and the Publish Artifact blade

**Comment by gravufo** [comment]
@CEsystemLLC have you even read the issue? We're asking for a build to partially succeed when a task has warnings, not when it fails.

**Comment by mpoiron** [comment]
Has anything changed since this issue was closed ? The ability to quickly see these kinds of warning and even send notifications to the build requestor is invaluable.

**Comment by komoreka** [comment]
+1
