### ISSUE TITLE
Azure Powershell - Set workingFolder

### ISSUE THREAD

**Issue by jpoon** [Microsoft/vsts-tasks#1148]
Similar to the Powershell VSO Build Agent, can we set the `workingFolder` when instantiating Azure Powershell?

Use Case:
I am trying to download assets from Azure Blob storage to the build machines. From my build logs, the working directory is set to wherever Azure Powershell lives.

```
2016-01-27T20:16:32.1304033Z Found 5 blob(s)
2016-01-27T20:16:32.1414028Z Downloading to C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\default\tasks\AzurePowerShell\1.0.8\
```

Workaround:
Use $PSScriptRoot to figure out where my script is and go from there.

**Comment by yaananth** [comment]
currently no.

**Comment by bryanmacfarlane** [comment]
@ericsciple - let's add this.

**Comment by gregjhogan** [comment]
I just uploaded the entire task directory up to blob storage accidentally because of this.  $PSScriptRoot is a good work-around, but please add support.  Thanks!

**Comment by RoopeshNair** [comment]
Added it to backlog Feature: 649929

**Comment by jpoon** [comment]
@RoopeshNair What is backlog feature 649929? I presume this has been moved to a private VSTS. If that is the case, how can we (the public) be aware of what's going on with this issue?

**Comment by letmaik** [comment]
Just stumbled upon the same issue, extremely irritating. This should be fixed asap, and if not then there has to be a big fat warning about this behaviour.

**Comment by Anufriev** [comment]
Any updates?

**Comment by RoopeshNair** [comment]
Not at this point in time, we haven't been able to get to this. 

We do encourage contributions, if you are willing to help.
