### ISSUE TITLE
Fusion log while running tests

### ISSUE THREAD

**Issue by rosieks** [Microsoft/vsts-tasks#1168]
After switching from XAML builds to new build system I have trouble with loading correct version of NLog. It would be nice to have option to somehow enable fusion log while running VSTest task.

**Comment by bryanmacfarlane** [comment]
Can't you did this with a locally deployed agent to troubleshoot?

**Comment by atinb** [comment]
@rosieks 
Were you able to try out locally and debug?

**Comment by rosieks** [comment]
Yeah, I was able to do that locally and debug. But still, I think it would be nice to have such feature at build server.

**Comment by atinb** [comment]
I am not sure this should be a part of the vstest task. It would be better as a generic task that can enable/disable fusion logs. 
If you have an interest in contributing a task, see [here](https://www.visualstudio.com/en-us/docs/integrate/extensions/develop/add-build-task) for details. Thanks!
