### ISSUE TITLE
One or more of the steps defined in the build does not have an associated task definition

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vsts-tasks#1170]
For certain build definitions I receive from time to time the following error message:

```
One or more of the steps defined in the build does not have an associated task definition
```

Any idea what might be the cause of this? Unfortunately no log is written. Queuing a new build works most of the time. Mostly the error occurs for builds scheduled during the night.

**Comment by ericsciple** [comment]
Is this on a Windows agent or xplat? If Windows is it for the hosted agent or for an on-premises agent?

**Comment by pascalberger** [comment]
@ericsciple Windows on-prem

**Comment by ericsciple** [comment]
@pascalberger Looks like this is a server side exception when the task definition is missing. It's strange that queuing again would often workaround the issue. Without digging in, my guess would be cache related. Are you using VSTS or on-premises TFS?

@scottdallamura Heard of this before?

**Comment by pascalberger** [comment]
@ericsciple VSTS

**Comment by pascalberger** [comment]
@ericsciple @scottdallamura Any idea yet? Last night again out of 50 build configurations which are scheduled all at the same time (03:00 UTC+1) the first 28 failed with this error.

**Comment by pascalberger** [comment]
@ericsciple @scottdallamura This now starts to become the default behavior and its quite a nightmare to have to recheck all failed build definitions manually each morning. Any idea how to progress with this?

**Comment by scottdallamura** [comment]
@pascalberger Can you point me to one of the failed builds?

**Comment by pascalberger** [comment]
@scottdallamura Thank. Send you an email

**Comment by ericsciple** [comment]
@scottdallamura @pascalberger Checking in. Assuming this has been resolved?

**Comment by pascalberger** [comment]
Didn't heard back from @scottdallamura if this was fixed completely. It didn't happen again in our tenant for the last few days, but it also worked earlier for a few days before the error returned. Therefore I let @scottdallamura close this issue if he feels like this is properly fixed.

**Comment by bryanmacfarlane** [comment]
I believe this is fixed.  We fixed some cache issues.  If you see it again, re-open

**Comment by Vislor** [comment]
@ericsciple @bryanmacfarlane My organization gets this occasionally in on-premises TFS when CI builds are queued.  We have TFS2015 Update 2. Was there a fix released for this for on-premises?

**Comment by pcoombe** [comment]
Also seen this a few times, most recently today, with TFS 2015 Update 2.1.

**Comment by embix** [comment]
Just had this bug reproducible with onprem TFS 2015u3 for a batched ci build definition. I pushed 4 times, it failed 4 times - in fact I never had a successful ci build for that build definition.

When pushing (using ssh if that is of of any help) the ci build is triggered but fails with the "(X) One or more of the steps defined in the build does not have an associated task definition." issue. But when I go to any failed build in my browser and push "Queue new build" the same commit will be build as it is supposed to.

**Comment by blackwellops** [comment]
@embix I am able to re-create this as well. This is only a problem when using ssh. Can we get this issue re-opened or added to a new issue?

**Comment by wdrijfhout** [comment]
I'm using TFS 2015u3 with scheduled builds and having the same issues. As suggested I disabled ssh in the TFS Console.

**Comment by nimblejoe** [comment]
We have a number of users receiving this error as well for on-premise TFS2015 Update 3.  TFS Admins never see this dialogue, but other users see it intermittently and sometime often.

**Comment by ChuckkNorris** [comment]
Deleting the task from the build definition and re-adding it fixed it for me

**Comment by igorguga** [comment]
@ericsciple @scottdallamura did this problem was fixed?? I'm experiencing the same issue with scheduled builds in TFS 2015.3. After midnight more than 50 scheduled builds are queued, most of them fail with this error. If you run one of them manually it works.

**Comment by kriskoneru** [comment]
@ericsciple @pascalberger we are using on Prem TFS 2015 update 3. We are doing scheduled build every day in the morning. Everyday the build fails because of the same error. "One or more of the steps defined in the build does not have an associated task definition". Once again we queue the build the build runs fine. 

This became are on going behavior with the build. Can you please let me know what is the issue are any workaround.

**Comment by nimblejoe** [comment]
At one point we reached out to Microsoft since none of the other fixes we could find solved this problem.  They created a private fix for us at that time which solved our problem.  However, this same fix is supposed to be a part of TFS 2017 Update 1 and later.  So, if you have scoured the web and none of the other solutions have worked for you, consider updating to TFS 2017 Update 1 or later.

**Comment by pabrams** [comment]
I can reproduce this error consistently in TFS 2017 Update 3 by creating a template containing a task group, creating a new build definition from that template, and then trying to queue it.  The queue fails with this error.  I opened #7609 since all the other issues seem closed.
