### ISSUE TITLE
Unable to use Generic Tests with Test Agent Build Step

### ISSUE THREAD

**Issue by cp4r3z** [Microsoft/vsts-tasks#1202]
I have a simple Generic Test which I'm trying to run as part of our Continuous Integration.

I have tried multiple times to configure the Visual Studio Test using Test Agent to do this, but I'm failing.

Is this possible?

**Comment by bryanmacfarlane** [comment]
Running tests is possible.  can you provide any more details?  What is your definition?  Inputs?  When you say it's failing, what error?  What message?

**Comment by cp4r3z** [comment]
I've created a test based on this walkthrough:

https://msdn.microsoft.com/en-us/library/ms182626.aspx

However, I do not need a C# Unit Test. I only wish to run an exe and register a pass/fail using an exit code.

Therefore, I created a Generic Test and now in a Project have a Generic Test called Test1.GenericTest and a Unit Test called UnitTest1.cs  I can give you more information about the tests, but this is not the problem.

The problem is that the Test Agent runs the Unit Test but NOT the Generic Test.

My Test Agent is configured to run:
*\*test*.dll

I have also tried *\*.GenericTest and a few other things...

I shouldn't have said the word "failure" because there is no failure. The Unit Test completes and that's it. The Generic Test is never even attempted.

I'm starting to think that I've fundamentally misunderstood what is capable with the Test Agent.

Thanks in advance for any help you can provide!

**Comment by atinb** [comment]
Did you try giving **\*.generictest in the Test assembly field? Or if you want to run the Unit Test and the Generic test, something like **\test*.dll; **\*.generictest should work. 
Thanks!

**Comment by bryanmacfarlane** [comment]
@cp4r3z - did you try @atinb suggestion?

**Comment by cp4r3z** [comment]
@bryanmacfarlane - Yes, I tried that initially and again just now (using R2). We created a very simple generic test and then attempted to run them we get:

2016-05-23T20:25:22.6748347Z ##[warning]DistributedTests: Test run is aborted. Logging details of the run logs.
 
2016-05-23T20:25:22.8281240Z ##[warning]DistributedTests: New test run created.
 
2016-05-23T20:25:22.8301268Z ##[warning]Test Run queued for Project Collection Build Service.
 
2016-05-23T20:25:22.8311274Z ##[warning]DistributedTests: Test discovery started.
 
2016-05-23T20:25:22.8331396Z ##[warning]DistributedTests: Test Run Discovery Aborted . Test run id : 271
 
2016-05-23T20:25:22.8341370Z ##[warning]DistributedTests: UnExpected error occured during test execution. Try again.
 
2016-05-23T20:25:22.8358926Z ##[warning]DistributedTests: Error : No tests were discovered from the specified test sources
 
2016-05-23T20:25:22.8369000Z ##[warning]DistributedTests: Test run aborted. Test run id: 271
 
2016-05-23T20:25:22.8459049Z ##[error]The test run was aborted, failing the task.

**Comment by atinb** [comment]
@cp4r3z 
Unfortunately, running Generic tests is not possible at this time using Run Functional Tests task (formerly Visual Studio Test using Test Agent). You can run Generic tests using Visual Studio Test task.
Thanks!

**Comment by bearkat2173** [comment]
Hi atinb,
I am encountering this issue as well.  [The documentation](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/RunDistributedTests/README.md) says 

> You can run unit tests, integration tests, functional tests – any test that you can execute using vstest runner

So this is a bug?  If so, when will it be addressed?

I have the task added to my release definition, in order to run FitNesse tests after deployment of my application.  If I use the _Visual Studio Test_ task as you say, will that work to run the test from the deployment agent machine?  That would suffice as a short term solution until this issue is resolved.

**Comment by bearkat2173** [comment]
It does not appear that _Visual Studio Test_ task works for generic tests either; it uses vstest.console.exe, which only seems to support tests from dlls.

**Comment by acesiddhu** [comment]
For Visual studio test task you can try giving *.generictest in test assembly text box instead off dll. Generic test extension is .generictest

**Comment by bearkat2173** [comment]
That didn't work.  It still said it didn't find any tests.

**Comment by atinb** [comment]
I can confirm that vstest.console.exe can discover and run generic tests. I tested this out locally. Are you providing a runsettings file? Can you attach an image of the test task in your Build Definition? Thanks!
