### ISSUE TITLE
Hosted Build: 'jspm' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by benlaan** [Microsoft/vsts-tasks#1216]
I have a gulp task that calls 'jspm install'. This works fine on my machine, and on a custom agent - both have been configured with a global install of jspm., e.g.

`npm install jspm -g`

Of course, I can't do this on a hosted build, so I tried to add a demand for jspm. But I am informed this is not a valid demand.

How can I get this to work?

**Comment by patrickmichalina** [comment]
JSPM works fine for me on vsts build and release management. Any more details?

**Comment by mFingers** [comment]
Try running jspm through node:  http://stackoverflow.com/a/32765388/182875

**Comment by jtucker** [comment]
I use the NPM `postinstall` script to fire off a `jspm install`. Seems to be working well ATM.

**Comment by bryanmacfarlane** [comment]
closing with suggestions above.
