### ISSUE TITLE
Tag not fetched from Git Repo

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vsts-tasks#1218]
This is maybe not directly on issue with the tasks but more with the agent. We're using GitFlow and have pushed a master release containing tag to VSTS, which kicks off the build.

Latest commit on master is:
`201b3672ff4fe1c9e1fac0c1912998ca25948a48: Merge branch release/1.1.5`

This commit is tagged with 1.1.5.

The log for Get Sources mentions that it checks out this commit. Afterwards I run GitVersion to determine the version which requires the tag on the master commit to correctly determine the version. Unfortunately it seems like the latest tag was not fetched to the agent (everything up to `1.1.4` seems to be there, but not `1.1.5`).

Do you have any idea why tags sometimes are not fetched to the agent?

**Comment by ericsciple** [comment]
I think Ting knows offhand. If not I can dig in.

**Comment by TingluoHuang** [comment]
@pascalberger I believe this was the limitation of libgit2sharp. you won't get annotated tags. If you have access to the build machine, add "build.fetchtags = true" to system environment variable. it would fetch the annotated tags. In the coming release, we provide an option in agent to let it using git.exe to sync code. once that in place, this problem will be solved.

**Comment by pascalberger** [comment]
@TingluoHuang Thanks. Adding a environment variable named `build.fetchtags` with the value of `true` doesn't seem to help. In the above case it still only fetches tags up to `1.1.4` but not the recent `1.1.5`.

Btw. Clean repository is set to true

**Comment by pascalberger** [comment]
It seems to work if I set the `build.clean` variable to `all`. Is it expected behavior that tags are not fetched with the default cleaning behavior?

**Comment by ericsciple** [comment]
Clean checkbox on the repo tab only does git clean -fdx/reset --hard (assuming git.exe is in your PATH). Build.Clean=all will drop the entire build folder (and re-clone).

Setting a system env var may require rebooting the agent. You could double check whether it's set in the agent's context by looking for it as a system capability on the admin page for the agent.

**Comment by pascalberger** [comment]
Restarted the agent to make sure the he sees the env variable (they are shown in the agent page), but still tags are not fetched.

**Comment by TingluoHuang** [comment]
@pascalberger can you try to use git.exe do "git fetch --tags" on the source folder after the build finish, see whether you will get the tag you wanted?

**Comment by pascalberger** [comment]
@TingluoHuang Unfortunately I already have updated all build definitions already to use `Build.Clean=all` to get stuff working again for us. Therefore I'm no longer to replicate the old behavior  (which occurred only if repo was cloned, later tags were introduced and repo was cleaned with `git clean -fdx/reset --hard`) without doing a whole reproduction. 

Just running a build from an old commit still fetches all tags (even the ones newer than the commit). Which is another thing leading to trouble while depending on git tags to determine the version during build.

**Comment by c0bra** [comment]
Any updates on this issue?

**Comment by bryanmacfarlane** [comment]
New agent will support

https://github.com/Microsoft/vsts-agent

**Comment by bryanmacfarlane** [comment]
... new preview will drop in day or two

**Comment by maximpashuk** [comment]
I was able to fetch annotated tags when set variable 'build.fetchtags' to 'true' in build definition (TFS 2015.2).

**Comment by ericsciple** [comment]
I talked with @TingluoHuang. Support for prefering git.exe has been added: https://www.visualstudio.com/en-us/docs/build/scripts/git-commands#how-does-enabling-scripts-to-run-git-commands-affect-how-the-build-process-gets-build-sources

Also as mentioned previously, the new agent (currently in preview) always uses git (not LibGit2Sharp).

**Comment by ericsciple** [comment]
@pascalberger fyi

**Comment by pascalberger** [comment]
@ericsciple  Great, Thanks!
