### ISSUE TITLE
Upgrade AzureWebPowerShellDeployment Task to use Get-AzureRmWebApp

### ISSUE THREAD

**Issue by mitchdenny** [Microsoft/vsts-tasks#1239]
Hi there,

There is currently an issue with the ```AzureWebPowerShellDeployment``` task where deployment fails when debugging on the Azure Web App is enabled and the version is set to VS2015. The underlying issue comes from the use of the ```Get-AzureWebsite``` cmdlet which depends on the Azure Service Management SDK (.NET) which is missing an enumeration.

After some discussion with folks responsible for the PowerShell SDK and the underlying .NET SDK it appears that they aren't planning on pushing out an update that fixes the issue anytime soon and that we should consider using the ```Get-AzureRmWebApp``` cmdlet instead.

The ```Get-AzureRmWebApp``` cmdlet is not a 1-for-1 replacement of the ```Get-AzureWebsite``` cmdlet and the task would likely need to use the ```Get-AzureRmWebAppSlot``` cmdlet and other related cmdlets to maintain the interface defined by the task inputs.

The problem is that many users of the existing ```AzureWebPowerShellDeployment``` task define Azure connections in the admin services tab via a certificate as opposed to credentials. Unfortunately the ```Get-AzureRmWebApp``` cmdlet and RM cmdlets generally require credentials, not certificates, and so upgrading the script in the background would break a bunch of builds.

So the question is - what is the best approach here? Should the existing task be updated and accept a certain number of builds breaking (perhaps detect the issue in the script and provide a helpful error message), or implement a new set of Cmdlets which are virtually the same in function but use the newer PowerShell infrastructure.

**Comment by mitchdenny** [comment]
Here is a related discussion in the Azure PowerShell repo:
azure/azure-powershell#462

And the Azure SDK repo:
azure/azure-sdk-for-net#1255

**Comment by chrisrpatterson** [comment]
We are working on updating the experience around working with AzureRM based resources in a couple of ways.  First we are making it easier to configure a service principal by providing an OAuth experience to authorize VSTS to the target subscription and directory and then have us automatically generate a service principal for you.  

Second we will be creating new Tasks for working with WebApps and other resources that are specific to RM.  This will of course mean you need to change your definitions but given all of the sometimes subtle differences it is becoming very difficult for us to paste over in a single task.

**Comment by mxa0079** [comment]
This also raises another very relevant issue: Task versioning. I believe Tasks should be versioned like a Nuget package (but with support for SemVer 2.0 ;) and Build and Release definitions should understand the concept of Task versions. This will make it easier for the product group, and the community to manage breaking changes and fuel innovation.

**Comment by mitchdenny** [comment]
Thanks @chrisrpatterson. I think that approach with the tasks makes sense. Is some of the work for these tasks currently underway in the repo here? I also think that the OAuth flow for services will be really nice. Works excellently for GitHub right now.

**Comment by chrisrpatterson** [comment]
@mitchdenny the Oauth work is in progress right now and I expect the other work to start next sprint.

**Comment by kmkumaran** [comment]
Closing as there are no open questions pending.
