### ISSUE TITLE
Logging from Powershell-on-remote-machines

### ISSUE THREAD

**Issue by larserikfinholt** [Microsoft/vsts-tasks#1263]
Hi!

Write-Host is not supported in this task. ( https://github.com/Microsoft/vso-agent-tasks/issues/612 )

What should I use instead - tried with write-verbose and setting system.debug to true, and with write-output - noen of them works.

Found I could write a error or warning using: 

write-output "##vso[task.logissue type=warning;]This is a simple message"

But if I want a plain message - nothing but a write-host functionality - what should I write?

Thanks

Larsi

**Comment by chshrikh** [comment]
Hi Lars ,

If you want to log you can user write-verbose with -verbose option . e.g 

write-verbose "Sample log" -verbose

**Comment by larserikfinholt** [comment]
@chshrikh the output is present on the "logs" tab, but I want it to be visible also on the "Console" tab (the one with blue background) - write-verbose verbose did not fix that. Any other commands I may try?

**Comment by dixu99** [comment]
I set system.debug to true and used Write-Verbose with -verbose option. I still don't see any log written on log or console tab. Anything else I need to specify to get the message in my powershell output to log? 

Thanks,
Di

**Comment by chshrikh** [comment]
@larserikfinholt 

This is in our backlog . Team is working on it . As of now we are not supporting such logging system. We will get back once the experience is enabled

**Comment by chshrikh** [comment]
@dixu99  

Hi ,

Is it possible for you to share a sample from your script ?

Regards

**Comment by dixu99** [comment]
Something like this:

if(PerformAction) {
	Write-Verbose "Start app pool" -verbose
	ApplyAction
} else {
	Write-Verbose "No action required. App pool is already started" -verbose
}

**Comment by chshrikh** [comment]
@dixu99 

My apology for late reply . Is it possible for you to share the agent logs . 
You can drop a mail to RM_Customer_Queries at Microsoft dot com.

**Comment by chshrikh** [comment]
closing this issue . For any further assistance please mail to RM_Customer_Queries at Microsoft dot com.
