### ISSUE TITLE
No test coverage for NuGet tasks

### ISSUE THREAD

**Issue by vtbassmatt** [Microsoft/vsts-tasks#1285]

**Comment by atinb** [comment]
I believe this is about not having Unit tests for the Nuget tasks. @ericsciple : will this be you?

**Comment by ericsciple** [comment]
Packaging team owns that. Matt opened that issue when he was PM of that team. I'll send them an email, I can't find an appropriate owner in the assignee dropdown.

**Comment by zjrunner** [comment]
Keeping this open for a bit longer but untagging Dev15.  We have a lot of scenario tests we've written in a private vsts account, we're looking to see what value can be had from UTs given a majority of what is interesting to test here is versions of nuget and interactions with the repo, not the bits of code around the call to nuget.  Still looking to add something, but not blocking dev15 given our other tests.

**Comment by zjrunner** [comment]
#2677 integrated our L0s.  Our scenario tests are still outside the code here
