### ISSUE TITLE
VsTest build step throws exception

### ISSUE THREAD

**Issue by pjirsa** [Microsoft/vsts-tasks#1310]
Trying to execute a simple unit test that is using Newtonsoft.Json. Locally, my test is working. When the step executes in VSO, i get the following error:
```
System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by bryanmacfarlane** [comment]
Not sure that's an issue with the task - it's just running mstest.  If your tests depend on newtonsoft 6, are you acquiring via nuget?

**Comment by pjirsa** [comment]
My test project is using nuget to acquire Newtonsoft and the version specified is 8.0.2. Not sure why the error is referencing 6.0.0.0, which is not even a valid version.

**Comment by aydany** [comment]
We have the same issue: https://msecg.visualstudio.com/DefaultCollection/ECG/_build?_a=summary&favDefinitionId=58&buildId=2160

Building from the same commit fails with the above error. The same code from the same branch was built  and tested successfully on 3/1/2016.

Since no code changed, it would appear that the build environment changed, most likely an update of the test task or something else in VSO?

**Comment by FermJacob** [comment]
Are you using the Microsoft Unit Testing Framework?  It references Newtonsoft 6.  Try adding this into the app.config or web.config

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

**Comment by bryanmacfarlane** [comment]
@pjirsa - did @FermJacob suggestion work?

**Comment by FermJacob** [comment]
Yes it did.  Thanks for checking.
