### ISSUE TITLE
Add support for compressing PDBs

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/vsts-tasks#1314]
The "Index Sources & Publish Symbols" task does not support passing the /compress flag to symstore.exe.  It would be nice to have a "Compress" option in the "Advanced" section of the options.

**Comment by bryanmacfarlane** [comment]
@chrisrpatterson - thoughts?  Seems easy enough

**Comment by bryanmacfarlane** [comment]
Copying to our backlog for consideration.  Not tracking as an issue.
