### ISSUE TITLE
RoboCopyJob validates credentials unnecessarily

### ISSUE THREAD

**Issue by MattKotsenas** [Microsoft/vsts-tasks#1318]
`RoboCopyJob.ps1` always calls `Validate-Credential` in cc88506f09fcb10ad7616b571eadb792f94d2683, even if it is unnecessary. Just below is code to handle the `net use` in the case of no username / password:

```powershell
if($machineShare)
{
    $command = "net use `"$machineShare`""
    if($userName)
    {
        $command += " /user:`"$userName`" `'$password`'"
    }
    $command += " 2>&1"
    $dtl_mapOut = iex $command
...
```

This restricts the usefulness of the command as I *have* to authenticate even if anonymous access is permitted.

**Comment by kmkumaran** [comment]
Thanks for the feedback Matt. We will track this.

**Comment by bryanmacfarlane** [comment]
update?

**Comment by RoopeshNair** [comment]
We have added this to backlog. However it will be a while before we get there
