### ISSUE TITLE
[Question] Is there an easy way to identify the data source bindings and their respective data source names in task.json?

### ISSUE THREAD

**Issue by Stijnc** [Microsoft/vsts-tasks#1320]
the question relates to the following commit:
https://github.com/Microsoft/vso-agent-tasks/commit/8188a0275ffa303620b092fd9fb6fdf9de33a0bc

I started out with defining resource definitions and looked at several vso tasks as an example. Then I stumbled upon sourceDefinitions being replaced with dataSourceBindings.
Is there any documentation available on how to use these and the possible dataSourceNames?

my question relates to azure rm automation accounts and resource group names.
Where one would be a parameter to the accountname datasource.

Thanks in advance,
//Stijn

**Comment by ericsciple** [comment]
@yaananth IIRC you know the details of this stuff, correct?

**Comment by yaananth** [comment]
@ericsciple  I am not aware of any docs, roniga might know about it.

**Comment by bryanmacfarlane** [comment]
@roniga please comment

**Comment by roniga** [comment]
Adding Muthu @kmkumaran

**Comment by gregjhogan** [comment]
Any chance you can at least open-source this so we can utilize whatever currently exists in the absence of documentation?

I have already come across the following items that would be nice to have in a pickList:
* Azure SQL databases on an Azure SQL server
* Regions that a specific resource type is available
* List of resource groups with VNETs
* Names of VNETs in a selected resource group
* Names of subnets in a selected VNET

Thanks!

**Comment by KrishnaAdityaB** [comment]
@omeshp @GitHubSriramB can one of you comment on it?

**Comment by bryanmacfarlane** [comment]
RM added binding.  Waiting for comment and/or documentation pointer.

**Comment by GitHubSriramB** [comment]
@gregjhogan Datasource bindings for Azure endpoint (or for any other endpoint) can be obtained by querying the service endpoint type:
e.g.
https://fabfiber.visualstudio.com/defaultcollection/_apis/distributedtask/serviceendpointtypes?type=Azure
This will retrieve the details of Azure (Classic) endpoint type. The details will include the data sources supported by the endpoint type.

We are in the process of documenting details on the service endpoint REST APIs & how to customize service endpoints. We don't have anything to share with you as such right now.

**Comment by gregjhogan** [comment]
@GitHubSriramB thanks for the info!  I don't really care about classic (ASM) but it looks like ARM endpoint info can be found here: https://instance-name.visualstudio.com/defaultcollection/_apis/distributedtask/serviceendpointtypes?type=AzureRM

Thanks!

**Comment by asiffermann** [comment]
@GitHubSriramB thanks for the info! It's really valuable!

However, I can get informations on the 5 default service endpoint types (Azure, AzureRM, ServiceFabric, Chef and Jenkins) but I can't get anything for the GitHub endpoint, although I know it has some datasources exposed to list repos and branches.

Do you know another way to pull these informations on endpoint types not listed by the service you mentionned?
Thanks again!

**Comment by GitHubSriramB** [comment]
@asiffermann We currently don't support dataSources for GitHub endpoint. Will let you know in case we start to support them going forward.

**Comment by GitHubSriramB** [comment]
@asiffermann To clarify - we don't support datasources for any other endpoint type that isn't returned from the API.
