### ISSUE TITLE
Permission denied using a local pool agent

### ISSUE THREAD

**Issue by rtorras** [Microsoft/vsts-tasks#1328]
Hello,
This is the error that I have when I'm trying to release with my local agent. The same definition works like a charm with the Hosted agent.

The task "azure resource group deployment" works but it crashes in the "Azure File Copy" task.

I have compared both logs and the main difference is:
Local Agent -->  AzurePSCmdletsVersion= 1.0.4
Hosted Agent --> AzurePSCmdletsVersion= 1.0.0

That's the error that I've got:

Permission denied while trying to connect to the target machine 13.70.206.206 on the port:5986 via power shell remoting. Please check the following link for instructions: http://go.microsoft.com/fwlink/?LinkID=390236System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server 13.70.206.206 failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.

NOTE: I have check if I had access to the target machine from the Agent machine and I did.
      $so = New-PsSessionOption –SkipCACheck -SkipCNCheck
      Enter-PSSession -ComputerName "<name> " -Credential <login> -UseSSL -SessionOption $so

Any idea?

**Comment by pavanadepu2** [comment]
Can you please share both the logs from your local agent as well as from hosted. This will help in debugging the issue further. Also, please let me know is it possible to have a Skype call to check the issue directly.

**Comment by bryanmacfarlane** [comment]
Any update with logs?

**Comment by rtorras** [comment]
Hello,

I don't have much time for testing that again .
I will send you the logs if I can reproduce the error.

Cheers,
Ramon

2016-04-21 13:20 GMT+02:00 Bryan MacFarlane <notifications@github.com>:

**Comment by pavanadepu2** [comment]
Please feel free to reopen the issue whenever you have a repro ready.
