### ISSUE TITLE
Publish artifacts via logging command can't be consumed

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vsts-tasks#1341]
Hi all,

I'm trying to publish my artifact from my custom build task. If I choose to use the logging command, the upload succeeds, however the Release Manager fails in retrieving the artifacts. The error that is reported:

`Error: System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.Services.FileContainer.ContainerItemNotFoundException: The item XL Deploy in container 494976 could not be found.`

If I used the Publish-BuildArtifact cmdlet it all goes fine.

The command I'm using for the upload is the following:
`Write-Output ("##vso[artifact.upload artifacttype=Container;containerfolder=$folder;artifactname=XL Deploy;]$packageFullPath")`
meanwhile the cmdlet equivalent is:
`Publish-BuildArtifact "XL Deploy" $packageFullPath $folder`

Does anyone have a clue why the logging command upload fails to be retrieved?
I am testing using VSTS thus I suppose I have the latest available version of the agent.

Thanks,
Mario Majcica

**Comment by mmajcica** [comment]
Seems that they both fail in case the containerfolder and artifactname are not of the same value. It seems however to be the Release Manager problem only as in the build I can see the artifacts uploaded correctly.

**Comment by GitHubSriramB** [comment]
Hi Mario,

Apologies for the inconvenience. We will investigate why RM is not able to download the artifact. Will get back to you with our findings.

Thanks,
Sriram

**Comment by GitHubSriramB** [comment]
We have fixed this issue a while ago.
