### ISSUE TITLE
SuppressMessage SonarQube

### ISSUE THREAD

**Issue by ChatRoquette** [Microsoft/vsts-tasks#1369]
Hi, 
I created a vNext build with a SonarQube Step. 
But the attribute SuppressMessage in my code doesn't work in sonar (the rule already appears)

![capture](https://cloud.githubusercontent.com/assets/7831749/13634275/d5f8c536-e5f4-11e5-8f4f-9724cd297e03.PNG)

Any solution?

**Comment by bgavrilMS** [comment]
Adding @duncanpMS

**Comment by bgavrilMS** [comment]
What version of Visual Studio are using on the build agent and what is the SonarQube C# plugin version?
Next, if you click on the "..." button in your message you'll see some more details, including the rule ID. Can you confirm the ID is CA2227 ? I'm just wondering if this isn't some other rule that you are encountering, as rule authors sometimes create rules that are very similar.

**Comment by ChatRoquette** [comment]
Hi, 

Visual Studio 2015.
SonarQube 5.3.
C# plugin 4.5.
TFS 2015 Update 1.

The problem appears with other rules.


![capture](https://cloud.githubusercontent.com/assets/7831749/13636459/5702bb70-e602-11e5-9f05-55ae1c987ab8.PNG)

![capture2](https://cloud.githubusercontent.com/assets/7831749/13636463/5cf7ac34-e602-11e5-8837-27f8a4616780.PNG)

Thx

**Comment by dbolkensteyn** [comment]
Thanks @ChatRoquette - This is a bug of the SonarQube C# Plugin, and a ticket for it has been created: https://jira.sonarsource.com/browse/SONARCS-586

**Comment by ChatRoquette** [comment]
Thanks for your attention. 
Good luck !

**Comment by bryanmacfarlane** [comment]
Closing this task issue since it was a bug in the C# plugin
