### ISSUE TITLE
Can task.complete be used to fail a build?

### ISSUE THREAD

**Issue by tomkuijsten** [Microsoft/vsts-tasks#1378]
According to the documentation I should be able to fail a build task when using:

```ps1
Write-Host "##vso[task.complete result=Failed;]"
```

The build however, does not stop and will have the "succeeded" status. Am I not using it right, or do I misunderstand the usage of this command?

**Comment by leftler** [comment]
I also am running in to this same issue. From a console app I did

    Console.WriteLine("##vso[task.complete result=Failed]MyProject");

And it did not cause the step to fail.

**Comment by ericsciple** [comment]
Which task are you outputting this command from? And which platform (Windows or OSX/Linux?) There's a couple different task handlers built-in to the agent. It might be an issue in one of the specific handlers.

**Comment by tomkuijsten** [comment]
It's a powershell script on a Windows platform. It's a TFS 2015 update 1 installation.

**Comment by leftler** [comment]
My test was with a command line application, running on Windows 10, TFS 2015 Update 1 installation.

**Comment by bryanmacfarlane** [comment]
We should try and repro.  So, it's your cli and that cli wrote to stdout, correct?

**Comment by ericsciple** [comment]
It might be a limitation in Update 1. I'll track down when the command was added and update the documentation if required. Sorry, I lost track of this issue.

**Comment by ericsciple** [comment]
I just tested in Update 2 - it works. Based on the source code, *it looks* like it was in Update 1 as well. Trying to get an Update 1 environment setup now.

**Comment by ericsciple** [comment]
Welp. It doesn't seem to work in update 1 :)

I'll update the docs to clarify update 2.
