### ISSUE TITLE
Claims SCM endpoint not enabled for mobile app

### ISSUE THREAD

**Issue by kylebsm** [Microsoft/vsts-tasks#1437]
Error when using deployment script with azure-mobile.net site:
##[warning]Cannot update deployment status, SCM endpoint is not enabled for this website

The SCM endpoint for mobile apps has the structure `<site>.scm.azure-mobile.net`, and should support the same functionality as a azurewebsites.net, but the if statement does not account for that here:

`{ $_ -like '*.scm*azurewebsites.net*' }`

doing something like this seems to work fine:

`{ $_ -like '*.scm*azure*.net*' }`

**Comment by yaananth** [comment]
@RonniePitts

**Comment by RoopeshNair** [comment]
Thanks for reporting this, adding to backlog Feature: 649905
