### ISSUE TITLE
vNext Task "CopyFiles" - "Clean Target Folder" also deletes the security and properties of the target folder

### ISSUE THREAD

**Issue by gapla27** [Microsoft/vsts-tasks#1440]
When I use the option "Clean Target Folder" it cleans not only the target folder but it also deletes the security manually applied to the target folder before.

Description of the option in the UI : "Delete all existing files in target folder before copy"
Description of the option on MSDN (https://msdn.microsoft.com/en-us/Library/vs/alm/Build/steps/utility/copy-files) : Select this check box to delete all existing files in the target folder before beginning to copy.

There is no mention about deleting the security...

**Comment by rglos** [comment]
I'd also like to add that what I've experienced is that it deletes the target folder altogether.  Definitely don't want that.  Here's our example scenario:

Agent is running on a server
Needs to copy files from artifact to UNC path on network
Someone has taken time to create shared folder and permissions on it - this is the target folder
Now our task runs and deletes that folder thereby deleting permissions, and any other properties set on the folder object

Can we get the task to delete files and folders in the target folder and not delete and recreate the folder?

If it's going to implement 'Clean Target Folder' by deleting, it should better reflect that like, 'Delete and Recreate Target Folder'.

**Comment by jdholbrook81** [comment]
Hello, is there any progress on this issue? Looks like it was removed from the Dev15 label. Running into this issue with a release.

**Comment by ericsciple** [comment]
PR: https://github.com/Microsoft/vsts-tasks/pull/3535

**Comment by ericsciple** [comment]
In master. Will roll out with the next deployment. It should roll out to all accounts within 2-3 weeks.
