### ISSUE TITLE
curl was not found in the path

### ISSUE THREAD

**Issue by bipindas** [Microsoft/vsts-tasks#1464]
Hello,

The cUrl upload which has been working fine for the past 2 weeks has suddenly started failing causinng my release management process to fail. I get the following error messages.

##[error]curl was not found in the path. 
##[error]Task cURLUploader failed. This caused the job to fail. 

I am using the cUrl task to upload the web.config file after replacing tokens. This was working fine for the past 2 weeks. The same failure has happened on 2 different team projects. 

Thanks.

**Comment by bryanmacfarlane** [comment]
This should be fixed now.  Please reactivate if you continue to have issues.

**Comment by bipindas** [comment]
Thanks!
