### ISSUE TITLE
App.config file of unit-test projects file not always copied

### ISSUE THREAD

**Issue by Malone1988** [Microsoft/vsts-tasks#1478]
For some projects in our solution the app.config file is not copied in the testresults/out folder. this causes the test to fail, because we are using some of the settings. I am not sure why this is the case. Tried also comparing the different projects and its configuration, no clue.

**Comment by ericsciple** [comment]
Are you using the Copy Files task? Or is it an issue with your msbuild configuration? The MSBuild/VSBuild tasks just call msbuild. If you set system.debug to true you can see the command line that they invoke. Your best option might be to try to repro the issue locally. It sounds like an issue with your msbuild configuration, not with the tasks (which just call msbuild).

**Comment by Malone1988** [comment]
I am using the task "Visual Studio Test" and some tests fail because of a missing app.config. From within Visual Studio the tests can be run on my local machine without issues.

I ran it with the debug setting active. Here is the VSTest part of the protocoll:

> 2016-04-05T06:34:58.5182712Z Starting task: Test Assemblies **\*test*.dll;-:**\obj\**
> 2016-04-05T06:34:58.5182712Z Executing the powershell script: D:\Agents\agent_1\tasks\VSTest\1.0.34\VSTest.ps1
> 2016-04-05T06:34:58.5962712Z ##[debug]Entering script VSTest.ps1
> 2016-04-05T06:34:58.5962712Z ##[debug]vsTestVersion = 14.0
> 2016-04-05T06:34:58.5962712Z ##[debug]testAssembly = **\*test*.dll;-:**\obj\**
> 2016-04-05T06:34:58.5962712Z ##[debug]testFiltercriteria = 
> 2016-04-05T06:34:58.5962712Z ##[debug]runSettingsFile = D:\Agents\agent_1\_work\6\s\PRODUCTNAME\SharedFiles\Build.testsettings
> 2016-04-05T06:34:58.5962712Z ##[debug]codeCoverageEnabled = false
> 2016-04-05T06:34:58.5962712Z ##[debug]pathtoCustomTestAdapters = 
> 2016-04-05T06:34:58.5962712Z ##[debug]overrideTestrunParameters = 
> 2016-04-05T06:34:58.5962712Z ##[debug]otherConsoleOptions = 
> 2016-04-05T06:34:58.5962712Z ##[debug]testRunTitle = 
> 2016-04-05T06:34:58.5962712Z ##[debug]platform = 
> 2016-04-05T06:34:58.5962712Z ##[debug]configuration = 
> 2016-04-05T06:34:58.5962712Z ##[debug]publishRunAttachments = true
> 2016-04-05T06:34:58.5962712Z ##[debug]Loading module from path 'D:\Agents\agent_1\agent\worker\Modules\Microsoft.TeamFoundation.DistributedTask.Task.Internal\Microsoft.TeamFoundation.DistributedTask.Task.Internal.dll'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Add-BuildAttachment'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Convert-String'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Get-IndexedSourceFilePaths'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Get-JavaDevelopmentKitPath'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Get-MSBuildLocation'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Get-ServiceEndpoint'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Get-TfsClientCredentials'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Get-ToolPath'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Get-TaskVariable'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Get-VisualStudioPath'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Get-VssConnection'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Invoke-Ant'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Invoke-BatchScript'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Invoke-Maven'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Invoke-MSBuild'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Invoke-PublishSymbols'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Invoke-Tool'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Invoke-VSTest'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Publish-BuildArtifact'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Copy-BuildArtifact'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Add-BuildArtifactLink'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Register-XamarinLicense'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Unregister-XamarinLicense'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Get-X509Certificate'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Loading module from path 'D:\Agents\agent_1\agent\worker\Modules\Microsoft.TeamFoundation.DistributedTask.Task.Common\Microsoft.TeamFoundation.DistributedTask.Task.Common.dll'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Complete-Task'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Get-LocalizedString'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Set-TaskVariable'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Set-TaskProgress'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Add-TaskIssue'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Write-TaskDetail'.
> 2016-04-05T06:34:58.6118712Z ##[debug]Importing cmdlet 'Find-Files'.
> 2016-04-05T06:34:58.6274712Z ##[debug]Loading module from path 'D:\Agents\agent_1\agent\worker\Modules\Microsoft.TeamFoundation.DistributedTask.Task.TestResults\Microsoft.TeamFoundation.DistributedTask.Task.TestResults.dll'.
> 2016-04-05T06:34:58.6586712Z ##[debug]Importing cmdlet 'Publish-TestResults'.
> 2016-04-05T06:34:58.6586712Z ##[debug]Importing cmdlet 'Invoke-ResultPublisher'.
> 2016-04-05T06:34:58.6742712Z ##[debug]Pattern found in solution parameter. Calling Find-Files.
> 2016-04-05T06:34:58.6742712Z ##[debug]Calling Find-Files with pattern: **\*test*.dll;-:**\obj\**
> 2016-04-05T06:34:59.7038712Z ##[debug]Found files: A_LIST_OF_DLLS_CANT_POST_CONTAINS_PRODUCT_NAMES
> 2016-04-05T06:34:59.7038712Z ##[debug]Calling Invoke-VSTest for all test assemblies
> 2016-04-05T06:35:00.0002712Z Working folder: D:\Agents\agent_1\_work\6
> 2016-04-05T06:35:00.0002712Z Executing C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe "A_LIST_OF_DLLS_CANT_POST_CONTAINS_PRODUCT_NAMES"  /Settings:"D:\Agents\agent_1\_work\6\s\PRODUCTNAME\SharedFiles\Build.testsettings" /logger:trx
> 2016-04-05T06:35:00.2186712Z Microsoft (R) Test Execution Command Line Tool Version 14.0.25123.0
> 2016-04-05T06:35:00.2186712Z Copyright (c) Microsoft Corporation.  All rights reserved.
> 2016-04-05T06:35:00.4214712Z Starting test execution, please wait...
> HERE INSERT SOME FAILED TESTS WHICH CHECK SOME VALUE FROM THE CONFIG (CONCRET: CSLA SETTINGS)
