### ISSUE TITLE
Deploying a commit with message ending on backslash to an Azure web app fails ("The converted JSON string is in bad format.")

### ISSUE THREAD

**Issue by adriaanthomas** [Microsoft/vsts-tasks#1480]
Steps to reproduce:

1.  Create a build definition with a deployment to an Azure Web App, using the Azure Deployment task
2.  Create a commit with a message that ends on a backslash. In our case it was "PR 870: Added role check for remove button\" (this is a merge from a pull request, for a single commit with message "Added role check for remove button\")
3.  Run the build, it fails on the Azure deployment:

        Publish-AzureWebsiteProject -Name "my-azure-app" -Package "D:\work\6\s\dist\package.zip" -Slot "production" -Verbose -ErrorVariable publishAzureWebsiteError
        ##[debug][Start]    Publishing package D:\work\6\s\dist\package.zip
        ##[debug][Complete] Publishing package D:\work\6\s\dist\package.zip
        ##[error]The converted JSON string is in bad format.
        Updating deployment status
        ##[warning]Cannot update deployment status for my-azure-app - {"Message":"Repository could not be found."}

We were able to work around this by adding an (empty) commit without a backslash in the message, which built and deployed just fine. Trying to build for the commit with the backslash in the message fails again.

 As the Powershell task [appears to have finished](https://github.com/Azure/azure-powershell/blob/dev/src/ServiceManagement/Services/Commands/Websites/PublishAzureWebsiteProject.cs#L121), it looks like this is caused somewhere in the task instead (somewhere in [this block](https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/AzureWebPowerShellDeployment/Publish-AzureWebDeployment.ps1#L125)?).

**Comment by anaggar** [comment]
Let us know if you face this issue again we recently made change on 9thMarch for using build url / release url instead of using commit message for updating deployment history. Let us know if with updated task changes you face same error again. thanks anubhav

**Comment by codito** [comment]
@adriaanthomas this issue was fixed with b1527434cb69a. I can confirm it is already released with M98 deployment. Closing the issue, please reopen if you still see the issue.
