### ISSUE TITLE
xcode: publishing test artifacts is adding BUILD_SOURCEDIRECTORY to path, making it diffcult to 

### ISSUE THREAD

**Issue by kristoferreierson** [Microsoft/vsts-tasks#1481]
We have a Publish Test Artifacts job that translates pushes our unit/component tests into TFS.  It is: "$(Build.ArtifactStagingDirectory)/BuildGatesOutput/nunit_test_results.xml"

We see an error when running this on newer versions of the vso-agent-tasks.  It looks like the agent is prepending:  BUILD_SOURCEDIRECTORY to the path. This means TFS can't find the test results file.  

Here is an example: "(/Users/ecndevxecndevx/buildagent/_work/2/s//Users/ecndevxecndevx/buildagent/_work/2/a/BuildGatesOutput/nunit_test_results.xml): ENOENT: no such file or directory, open '/Users/ecndevxecndevx/buildagent/_work/2/s//Users/ecndevxecndevx/buildagent/_work/2/a/BuildGatesOutput/nunit_test_results.xml')"

The test results are usually going to be in the output/staging directory.  I would prefer if we don't assume that they are in the TFS root - now I need to change my task to use relative paths and assume that the output directory has an 'a' in it.

**Comment by nigurr** [comment]
Since the file module which we use to discover files is limited to Agent directory only, by default it's rooted to $BUILD_SOURCEDIRECTORY

**Comment by kristoferreierson** [comment]
If we need to use '../a' then you need to guarantee that you won't ever use any directory other than ../a for build output - otherwise you will break any customers scripts who rely on ../a, this is a poor user experience and will definitely block my team from adopting this.

Can you suggest a work around?

**Comment by nigurr** [comment]
Can you please lt

**Comment by kristoferreierson** [comment]
I think this was more broken by 1.0.25.

The test results are here: /Users/ecndevxecndevx/buildagent/_work/2/a/BuildGatesOutput//nunit_test_results.xml 
The agent is in:  /Users/ecndevxecndevx/buildagent/.

Let me know if you need more information.

More debugging info:

We copy the log file to a network share here: 
2016-04-13T17:42:12.295Z: /Users/ecndevxecndevx/buildagent/_work/2/a/BuildGatesOutput//nunit_test_results.xml -> /Volumes/ECNDEVX/IntuneDex_MAM_iOS/mam_dev/1604.82/BuildGatesOutput/nunit_test_results.xml

Which means that the file exists locally...But we see this:

The “Publish Test Results” Visual Studio step then attempts to publish the results from a file at ../a/BuildGatesOutput/nunit_test_results.xml .  Based on the fact that the copy command was successful against the file at that relative path, then the file had to exist there.  However, when the “Publish Test Results” Visual Studio step runs, it gets the following result:

2016-04-13T17:42:37.355Z:  
2016-04-13T17:42:37.357Z: Start: Results.Publish async Command
2016-04-13T17:42:37.357Z: [warning]Failed to publish test results: Could not read file (): ENOENT: no such file or directory, open ''
2016-04-13T17:42:37.357Z: End: Results.Publish async Command
2016-04-13T17:42:37.357Z:  

In the logs.

**Comment by kristoferreierson** [comment]
Ping - does this task work at all?  

What I did:
* Created a new build definition from scratch.
* Added a publish task execution object to publish the contents of nunit_test_results.xml

When I run the build, I still see:

2016-04-18T18:44:09.293Z:  
2016-04-18T18:44:09.294Z: Start: Results.Publish async Command
2016-04-18T18:44:09.294Z: [warning]Failed to publish test results: Could not read file (): ENOENT: no such file or directory, open ''
2016-04-18T18:44:09.294Z: End: Results.Publish async Command
2

Can you either provide a workaround or a date for a fix?  This is blocking out ability to get test reports.

**Comment by nigurr** [comment]
You are using Xplat agent? Can you please let me know agent version and Task version

**Comment by kristoferreierson** [comment]
Yes, I am using the xplat tools.

I am not sure how to find both of the versions -here are my guesses based on looking at the source.  Let me know if these are wrong. 

**Agent Version**: 0.5.10 ( from the package.json / vsoAgentInfo service Milestone: 1.999.0 )
**Task Version**: PublishTestResult - 1.0.25 (from the directory PublishTestResults and the log file).

Looking at the log file, this is the json sent down:

"testResultsFiles": "./nunit_test_results.xml",

I see this:

[2016-04-19T09:32:40.860Z] scriptrunner:> INPUT VAR: INPUT_TESTRESULTSFILES=/Users/ecndevxecndevx/buildagent/_work/2/s/nunit_test_results.xml

(this file exists locally, I confirmed via an ls)

Then this:

[2016-04-19T09:32:41.867Z] feedback:> qline: [warning]Failed to publish test results: Could not read file (): ENOENT: no such file or directory, open ''

Do you require a wildcard when looking for a test results file?

**Comment by bryanmacfarlane** [comment]
@nigurr can investigate.  let me know if you need anything from the xplat agent or help with testing.

**Comment by kristoferreierson** [comment]
ping - @nigurr @bryanmacfarlane  - is there anything you need from me?  I'd like to be able to turn off our Jenkins server and switch to VSO completely, but I really need the ability to be able to view and archive the reports.  If there is a work around that I can do, I am happy to do it.

**Comment by madhurig** [comment]
@kristoferreierson : Sorry for the issues you were facing. This was an issue in the node agent which we fixed some time back. You should not see this with the latest agent: https://github.com/Microsoft/vsts-agent
