### ISSUE TITLE
SVN externals checkbox defaults to "checked" even when saved as unchecked

### ISSUE THREAD

**Issue by tomkuijsten** [Microsoft/vsts-tasks#1491]
I'm using TFS 2015 update 2 on a Windows 2012 R2 server (although the issue was also in update 1).

I have a build definition with a svn repository. I'm using a mapping and I need the externals functionality. I deselected the "Ignore externals" option and saved the definition. I noticed that after the save, the checkbox is checked again. I checked the history and it actually did change the value. I thought it was some kind of refresh problem so I closed all browsers and re-opened the definition. Now something curious happens. When I press the "Edit" link, the Repository tab is immediately shown as Italic (which indicates that I changed something). When opening the repo tab, the "Ignore externals" is checked again and that's causing the "changed indication".

This is really a pain in the ... Every time someone alters the definition, this checkbox is checked again and should be deselected before someone presses the "Save" link.

**Comment by bryanmacfarlane** [comment]
Yash to investigate for QU3 and 99

**Comment by yaananth** [comment]
I can repro, this would be fixed in QU3/99.

**Comment by tomkuijsten** [comment]
Thanks for reproducing and fixing!

**Comment by BastiDD** [comment]
We are using TFS 2015 update 3 (Version 14.102.25423.0) on our build machine. The Bug is still present.

**Comment by tomkuijsten** [comment]
I can reproduce it as well in Update 3.

@yaananth can you confirm that the fix made it to update 3?

**Comment by yaananth** [comment]
sorry unfortunately I didn't port it to Sprint 99 (update3), the fix is in Sprint 100. Next release should have the fix.

**Comment by tomkuijsten** [comment]
Ah that explains a lot :) thanks for the info, we just wait for the next release.
