### ISSUE TITLE
Allow gMSA's in IISWebAppDeployment

### ISSUE THREAD

**Issue by cwoolum** [Microsoft/vsts-tasks#1498]
Hey All,

For the Identity of the Application Pool, the task currently requires a password if you enter a user name. This does not work if you use gMSA's for your Application pool. I'd like to remove the dependency on this. 

Is everyone fine with me submitting a pull request for this? Should there be an additional toggle to specify if the account is a gMSA and the make the password required based on that?

**Comment by mvvsubbu** [comment]
You can change existing custom account option and update help mark down to convey the message why it is optional.

**Comment by codito** [comment]
@cwoolum we're happy to take contributions. Please let us know if you need any additional information to start on this :) /cc:@mvvsubbu

**Comment by cwoolum** [comment]
I'd love to make the contribution! Im out of the country and away from a
computer so I'll probably be submitting a pull request in a couple weeks

**Comment by mvvsubbu** [comment]
Are you back ?? Planning to float PR?

**Comment by cwoolum** [comment]
Yes, started working on it a few days ago and I'm testing locally.

**Comment by cwoolum** [comment]
I've gotten it working and tested it. I am running into an issue where an error is thrown if I try to use a SSL certificate when deploying the app but I'm almost positive it is unrelated to my changes. I'll submit a PR tonight. I'll look into the SSL issue and submit a separate PR if necessary.

**Comment by cwoolum** [comment]
Added pull request #1634 that covers this functionality. Can you guys please review?

**Comment by cwoolum** [comment]
@mvvsubbu, will you be reviewing the pull request?

**Comment by mvvsubbu** [comment]
Added the support, it should be available with next VSTS deployment
