### ISSUE TITLE
SPNCreate.ps1 fails if $env:USERNAME has a space in the name

### ISSUE THREAD

**Issue by dwhathaway** [Microsoft/vsts-tasks#1503]
By default, the script expects taht $env:USERNAME doesn't have any spaces.  Usernames may have spaces in them (mine does).  The problem occurs on line #16.

$userName = $env:USERNAME

Change this line to read as follows:

$userName = $env:USERNAME -replace ' n','_'

**Comment by kmkumaran** [comment]
Similar issue is being addressed using https://github.com/Microsoft/vso-agent-tasks/pull/1505.

**Comment by codito** [comment]
Closed as duplicate of #1505
