### ISSUE TITLE
Invoke-VSTest not respecting WorkingFolder

### ISSUE THREAD

**Issue by mvpete** [Microsoft/vsts-tasks#1520]
Hi there,
I'm trying to run VSTest on a build server but I keep running into "Failed to set up the execution context to run the test". The test DLLs and CUT DLLs have dependencies, but I've ensured that they're all in the same location. I modified the VSTest.ps1 file to set the working folder to the folder I've output to and still get this error. 

If I run vstest from the console out of that working folder there are no problems running the tests. I can only conclude that when it's running from the shell script it isn't running out of that folder and is unable to resolve the dependencies.

**Comment by nigurr** [comment]
VsTest is just wrapper to invoke the vstest.console so there shouldn't be an issue.

Can you please send us your build log?
devops_tools at microsoft.com

**Comment by mvpete** [comment]
Unfortunately my email was rejected. I'm not authorized to send to that group (I sent from my work email). Also, given there may be proprietary information I'd rather not send the build logs.

**Comment by atinb** [comment]
@mvpete 
If you look at the Visual Studio test logs, you will see the command line that is being used to call into vstest.console.exe. Can you try that locally and see if you can repro or pinpoint the issue? Thanks!

**Comment by mvpete** [comment]
I suspect that this actually may be my issue. Looking at it again. Before I was able to run the tests with vstest.console.exe. However now I get the same results running from a command console.

**Comment by atinb** [comment]
@mvpete 
Were you able to figure this out? Can we close the issue? Thanks!

**Comment by mvpete** [comment]
Not yet. You can close the issue and when I find the root cause I can re-open or open another if it's not my own doing. Thanks again for looking into it!
