### ISSUE TITLE
Uploaded task is not listed in task list on Visual Studio Team Services

### ISSUE THREAD

**Issue by karlisf** [Microsoft/vsts-tasks#1529]
The uploaded task is not listed in the task list on Visual Studio Team Services. When task.json is edited and "Preview" is removed from "visibility" uploaded task is available in the task list.
See also for more details http://blog.heeresonline.com/2016/03/tfs-upload-task/

**Comment by bryanmacfarlane** [comment]
That's intended.  If your account is not enabled for preview tasks, you won't see preview tasks.
