### ISSUE TITLE
Is it possible to run .webtest as part of build/release?

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/vsts-tasks#1532]
I didn't find any step under the Test category (neither in any other) to run .webtest, such as simple ping.

**Comment by abatishchev** [comment]
@nigurr hi, any thoughts?

**Comment by atinb** [comment]
@abatishchev 
Sorry, but its currently not possible to run webtests. Adding this support is on the backlog
Thanks!

**Comment by rs38** [comment]
any update or workaround on this? @atinb
