### ISSUE TITLE
AzureFileCopy SAS token is not mark as secret

### ISSUE THREAD

**Issue by compulim** [Microsoft/vsts-tasks#1537]
https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/AzureFileCopy/AzureFileCopy.ps1#L140

Although I am not seeing the SAS token dumped in the log, but should we add `issecret=true` to mask the SAS token?

**Comment by KrishnaAdityaB** [comment]
@compulim Thanks for bringing it up. 
I will raise a PR

By the time this code was added, isSecret parameter was not available.
Azure #1099 
isSecret 2702329fa35a07381d34d36c20486e9fe210b0fa
