### ISSUE TITLE
Source Version is not set during manual build for SVN repository

### ISSUE THREAD

**Issue by tomkuijsten** [Microsoft/vsts-tasks#1542]
We are using SVN as repository and using powershell scripts as custom build steps. In these scripts I use ```$env:BUILD_SOURCEVERSION``` to rever to the SVN revision number. I noticed however, that this variable is only set when the build was triggered by a repository change and not when you queue a build manually. I didn't expect this kind of behavior. Is this how it is supposed to work or is this an error?

Environment details:
TFS 2015 (on premise) update 2
Windows 2012 update 2 server

**Comment by DavidStaheli** [comment]
Hi Tom.  Thanks for reporting this.  We are working on a fix and a workaround and will reply back soon.

**Comment by ericsciple** [comment]
I checked with @AlexRukhlin. This is fixed now.

**Comment by tomkuijsten** [comment]
Good to hear, thanks!

**Comment by vivuu1989** [comment]
May I know, How you could resolve the issue.
