### ISSUE TITLE
Tasks RunDistributedTests -  An exception occured in queue listener.

### ISSUE THREAD

**Issue by kardinal3000** [Microsoft/vsts-tasks#1549]
I have Test Plan - Test suite (Coded UI tests).  I specified machine group that consists of 3 tests machine and launch my test suite.
As result I see the execution of tests only one machine other machines doesn't have any action. 
I have checked log file  DTAExecutionHost.exe.log and found this exception on each machine where test doesn't run:

> \DTAExecutionHost, TestExecutionServiceCommandQueueListener.SendStopCommandToHandleException : An exception occured in queue listener. Microsoft.TeamFoundation.Test.WebApi.TestExecutionObjectNotFoundException: TestAgent 97 not found. Microsoft.VisualStudio.Services.WebApi.VssHttpClientBase.HandleResponse(HttpResponseMessage response)

looks like the parallelism doesn't work

**Comment by atinb** [comment]
Do you have your tests in 1 dll? If so, the parallelism today only works across dlls. We are working on distributing tests within dlls across machines and that should come shortly.

**Comment by kardinal3000** [comment]
Oh, thanks alot for your answer. That news was important for me. I glad to hear that you are working on it!
 I will looking forward update. You are doing a great job! )

**Comment by atinb** [comment]
Thanks! Will let you know when the functionality is live.

**Comment by skylock** [comment]
Any news on this feature ?

**Comment by kardinal3000** [comment]
As I can see the problem still exist

**Comment by bhojan** [comment]
Any updates on this issue

**Comment by nigurr** [comment]
How many number of test DLLs are present [associated with the test suite]?
Currently we distribute by number of test assemblies. If you happen to have single test dll, only one machine will be used for test execution.

We have added distribution by number of machines in TFS 2017. Please let me know if you still require any info
