### ISSUE TITLE
Task Run Functional Tests - Some of our tests need to run the applications elevated

### ISSUE THREAD

**Issue by madmaximillion** [Microsoft/vsts-tasks#1550]
Would it be possible to enable running tests elevated so that they are able to run applications under test elevated?
One reason for doing this is that our applications produce metrics and some are only produced when running as admin but the test process, running Un-elevated, cannot hook into an elevated process.

**Comment by ericsciple** [comment]
It is possible today. If the agent is run elevated, the tasks will run elevated. If you're running the agent interactively, it needs to be launched as elevated. If you're running as a Windows service, it needs to be configured to run as a service account that is admin on the box.

**Comment by madmaximillion** [comment]
Great, thanks @ericsciple!
