### ISSUE TITLE
Common.TestResultsDirectory variable not resolving correctly

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vsts-tasks#1558]
In my build task I tried to use the Common.TestResultsDirectory variable. On VSTS, once it is resolved, it translated into C:\a\1 instead of expected C:\a\1\TestResults. Is this the correct behavior? Is there another way to get the TestResults directory?

Thanks

**Comment by bgavrilMS** [comment]
Adding @duncanpMS

**Comment by ericsciple** [comment]
That is not the correct behavior. You are right, basically it should resolve to $(agent.builddirectory)\TestResults for a build job.

**Comment by ericsciple** [comment]
@mmajcica  I'm not able to reproduce this. In a hosted build, I've tried two different ways:
1) Cmdline Task
Tool=set
Arguments=common

```
COMMON_TESTRESULTSDIRECTORY=C:\a\1\TestResults
```

2) Cmdline task
Tool=echo
Arguments=$(Common.TestResultsDirectory)
```
C:\Windows\system32\cmd.exe /c "echo C:\a\1\TestResults"
C:\a\1\TestResults
```

**Comment by mmajcica** [comment]
Hi @ericsciple . I tested it again and it is working correctly. I'm sorry but seems that my script was not working correctly.

Thank you

**Comment by mmajcica** [comment]
I found out why I was lead to think this was the case.

In case of an input of type filePath, if user doesn't specify a value in the task (leaves the input field blank), once the script is invoked, a value for that field is passed and equals to Build.SourcesDirectory. @ericsciple  is this the correct behavior?

**Comment by ericsciple** [comment]
Yes, more specifically it resolves to the system.defaultworkingdirectory (sources directory in build, artifacts directory in release). That is something that is definitely missing from task author docs, and is something that is likely inconsistently documented in the tooltips of each task. I'll add a note to this related issue: https://github.com/Microsoft/vsts-tasks/issues/1747

**Comment by mmajcica** [comment]
@ericsciple  is there any way to understand if user hasn't specified any value? And btw, I became you documentation nightmare guy :)

**Comment by ericsciple** [comment]
lol, no, better docs are definitely needed in this area and is near on the backlog. It's good this came up, so it makes it into the list of things to covered on the first pass. The way to understand whether a value has been specified is to compare with system.defaultworkingdirectory (see pathSupplied function in the node lib). Granted, that won't work for all cases, although it's optimized for the common cases (esp when user specifies a "file", not a directory). The other way around the limitation (not needed for all scenarios) is to follow the pattern of the Shell Script task (check box + file path input). The rest of the script tasks (Batch, Command Line, PowerShell) are going to be switched over soon to follow that pattern.
