### ISSUE TITLE
To create custom category task

### ISSUE THREAD

**Issue by sergienko4** [Microsoft/vsts-tasks#1565]
Hi,
 I want to add custom category to tasks build.
![image](https://cloud.githubusercontent.com/assets/16467411/14700009/494f46d2-07a5-11e6-8e1d-93730f0456eb.png)

Can I ? If Do, how to do ?

**Comment by bryanmacfarlane** [comment]
It's a fixed list.  It's either a build task, a test task, a deployment task.  If it's none of those, it's by definition a utility

**Comment by sergienko4** [comment]
Is a possibility to add Custom category?

**Comment by bryanmacfarlane** [comment]
We currently plan on leaving it a fixed list.  Can you outline your scenario?  What task(s) are you creating and what category are you wanting to add?

**Comment by sergienko4** [comment]
I want to add new category named Experimental.
There I want to add tasks for test before update to the production

**Comment by gregjhogan** [comment]
I would also like to create a custom category.  I am creating a bunch of custom resource provisioning tasks, and I would like to put them in a category named "Provision".  Strangely, if I set the "category" in the task.json to "Provision" the task gets created, but the custom category obviously does not, and the task only shows up under the "All" category.

**Comment by bryanmacfarlane** [comment]
Experimental should be an attribute of the task that we render specially.  Not a category.  we should add that as a feature.
@gregjhogan - can you detail what you are provisioning?

**Comment by gregjhogan** [comment]
@bryanmacfarlane we are trying to make it significantly easier to provision some basic, commonly used Azure RM resource types (web apps, databases, storage accounts, service bus, app insights, etc...).  The idea I had to accomplish this goal is to create custom VSTS tasks that can be used in release management.  This accomplishes several things for us: a) fewer people need to learn ARM template syntax b) work around ARM template limitations (augment ARM templates with powershell commands when ARM templates fall short) c) prescribe certain parts of resource deployment (e.g. always turn on auditing and TDE encryption for Azure SQL DBs)

**Comment by bryanmacfarlane** [comment]
Those are a good fit for the Deploy category
