### ISSUE TITLE
Build/Release Visibility key in task.json is not honoured.

### ISSUE THREAD

**Issue by harshil93** [Microsoft/vsts-tasks#1570]
See the task Copy/Publish Build Artifact. In its task.json, its visibility is set to Build only but it is visible in Release also.

Same is the case with tasks where Visibility is set to Release but they show up in Build also.

**Comment by bryanmacfarlane** [comment]
we need this to work

**Comment by yaananth** [comment]
Will be fixed for M99.

**Comment by GitHubSriramB** [comment]
We decided to show *all* tasks within Release. So Release is not honoring the filter right now. As for this task, we fail the task with a specific error indicating it is not supported in Release. 

We don't anticipate tasks that can only work with Build going forward.
