### ISSUE TITLE
Task - Create Source Code Label For Deployed Build

### ISSUE THREAD

**Issue by mieliespoor** [Microsoft/vsts-tasks#1572]
During build you have the option to label the source. This specific build might not actually be released to production, so the specific label might not be valid at some point in future. It would be nice to be able to add a task to a specific environment to then create a label for the build being deployed - much like the Application Insights release annotation task.

Yes, one can argue that the build not released into production would ultimately be deleted via policy, but I would like the option to only have labels for releases into production. Manual labels would be created for specific purposes and their naming convention would be different to that of a Build/Release label.

**Comment by bryanmacfarlane** [comment]
Chris our PM should think through scenario ...

**Comment by bryanmacfarlane** [comment]
We won't add a task for this but the community can add as an extension and publish to the market place.
