### ISSUE TITLE
Resolve wildcards in Windows Machine File Copy task

### ISSUE THREAD

**Issue by jorrit** [Microsoft/vsts-tasks#1578]
I am trying out the new Release Management and I want to use the WM File Copy task to copy artifacts to a machine. However, my artifact names are dynamic and therefore I can't enter a proper source value. I know robocopy doesn't support wildcards, but it would be very useful if the task supports wildcards. Perhaps the PowerShell code can resolve the wildcards and call robocopy? Maybe the task can fail if more than 1 directory matches the wildcard.

**Comment by codito** [comment]
@jorrit are you using dynamic folder names in artifacts? Can you please share an example of directory structure of artifacts? Robocopy supports wildcards in filename, not on the folder name or path. /cc:@roopeshnair

**Comment by jorrit** [comment]
I am using the build number as part of the artifact name with the pattern `$(Build.BuildNumber)_$(BuildConfiguration)`, so my artifact name is something like `MyTool_1.0.0.0_Release`. The Release Manager source path becomes `$(System.DefaultWorkingDirectory)/MyTool/MyTool_1.0.0.0_Release`. However, the `1.0.0.0` part is of course dynamic, after I create a new build it should take `MyTool_1.0.0.1_Release`, etc.
I guess that using the build number in the artifact name is not standard behavior, but it works for me because in that way, when I download the artifact as zip file, I retain a reference to the build number without extra effort.

In any case, to improve the current situation, `WindowsMachineFileCopy.ps1` should be changed such that `Test-Path` is invoked with the `-LiteralPath` argument such that paths with wildcards are not considered valid.

**Comment by RoopeshNair** [comment]
@jorrit can you try using the system variable in the path, something like $(System.DefaultWorkingDirectory)/MyTool/$(Build.BuildNumber)_$(BuildConfiguration) 

Let us know if it doesn't work for you

**Comment by jorrit** [comment]
I know those variables are available in build definitions, but are those variables available in release management definitions as well?

**Comment by codito** [comment]
@jorrit yes, Build.BuildNumber is available if you have an artifacts source (build definition) linked to your release.

**Comment by jorrit** [comment]
Thanks, I think that answers my question for now.
