### ISSUE TITLE
.testsetting attachment douplication 

### ISSUE THREAD

**Issue by DZiso** [Microsoft/vsts-tasks#1579]
I am running Coded Ui Test during Releasemanagement, to better comprehend failing Testcases i activated the video log in the used testettings file.

This uploads the videolog once for the first dll executet on the pc,twice for the second dll and so on. 

![attachmentdouble](https://cloud.githubusercontent.com/assets/18616536/14744335/ae01eb1e-08a6-11e6-9372-6c94bf9400f4.PNG)

Same is Valid for SystemInformation.xml but not for the UITestActionLog.or personal attached file.

**Comment by atinb** [comment]
Thanks for reporting @DZiso. We will investigate

**Comment by acesiddhu** [comment]
@DZiso are you using Run functional test task or Visual studio test task?

**Comment by acesiddhu** [comment]
Also if you can share the testsetting file which you are using it will help. 
Thanks

**Comment by DZiso** [comment]
Run functional test task. I will be able to provide the testfile on monday.

**Comment by DZiso** [comment]
![image](https://cloud.githubusercontent.com/assets/18616536/14769299/70dda2c6-0a56-11e6-8cec-70d349dd5fb5.png)

![image](https://cloud.githubusercontent.com/assets/18616536/14769312/9ea46c12-0a56-11e6-9c94-335847b0c811.png)

Sample Project using a Server 2012 and TfsOnline: https://github.com/DZiso/Cuit-TestSettingDoublication.

I could not get Screen and Voice Recorder activated on my azure test infrastructure but the SystemInformation.xml still duplicates.

![image](https://cloud.githubusercontent.com/assets/18616536/14769389/620465ea-0a57-11e6-8e3d-fc03f2ff5333.png)


What i forgot to mention is that we are normally using a on premise Tfs 2015 Update 2

**Comment by vimegh** [comment]
@DZiso  Thanks for sharing the details. 

At present, Run Functional Test Task slices/groups tests to run per dll wise.This is as per design to run tests distributively.

As the project shared by you is having two DLLs hence, tests are being run in two groups resulting in two data collections files. We don’t merge these data collection files after run.

**Comment by DZiso** [comment]
Ah, so you upload the files to times for every testcase ? including the video logs ?

**Comment by vimegh** [comment]
Sorry @DZiso I misunderstood the case. We will check it out and will update this discussion.

**Comment by vimegh** [comment]
@DZiso I was able to reproduce the case. For some test cases, data collection files are also getting added by test agent as test result files, besides adding them as a data collection files, hence resulting in duplicate attachments with test case. We will work on resolving the issue and will update the thread accordingly.

**Comment by vimegh** [comment]
@DZiso Thanks for reporting the issue. It seems to me that this is a non blocking issue for you. We are marking this bug closed as of now, as we are not planning to fix it at present. Revamping of this part of code is due and we would be taking this up later with that.

**Comment by DZiso** [comment]
@vimegh  okay, no Problem, do you have a roadmap when you are planning on revisiting the part of the code or when this will make it to on Premise ?

**Comment by vimegh** [comment]
I don't have exact dates, but just for your information this bug will be backlogged internally and will be taken up later.
