### ISSUE TITLE
WindowsMachineFileCopy: required minimum agent version

### ISSUE THREAD

**Issue by bazauto** [Microsoft/vsts-tasks#1602]
We have the latest Update 2 version of the OnPrem TFS and agents. We have been trying to update the version of the WindowsMachineFileCopy task to include the fix for quoting of passwords that came in patch 26 of the task.

Is there a specific requirement for version 1.97.0 of the agent rather than the 1.95.0 that we have with our OnPrem TFS?

I have tried just changing the minimumAgentVersion to 1.95.0, it loads in and appears to work. But not sure if there will be any side effects later on and would prefer to run a version direct from the repo.

**Comment by bryanmacfarlane** [comment]
Muthu, what was the reason for tying to 1.97.0?

**Comment by KrishnaAdityaB** [comment]
@bazauto we fixed a bug between the two patches. If you changed the minimum agent version to 1.95.0, you wouldn't have the fix. No major changes apart from this fix.
As you haven't faced any problems till now - I guess you didn't have the scenario that will be effected.
