### ISSUE TITLE
Uploaded Summary Invisible To Some Team Members

### ISSUE THREAD

**Issue by rovinbhandari** [Microsoft/vsts-tasks#1603]
When the build uploads a custom summary using either `##vso[build.uploadsummary]$local_file` or `##vso[task.attachment type=Distributedtask.Core.Summary;name=Custom Summary;]$local_file` commands, the uploaded summary is visible to some team members while invisible to others. Not all team members have the same permissions and privileges but everyone can access the builds. Is it a bug? If not, what permissions determine the visibility of uploaded summary; and how to tweak those? 

Thanks!

**Comment by yaananth** [comment]
"View build" permissions is all we need.
I am able to reproduce where in some cases the markdown is not displayed.
This is has to do with bundling of javascripts, it's a UI bug.
Will fix this in M100.

**Comment by yaananth** [comment]
fixed, fix will be rolled out in next sprint.

**Comment by rovinbhandari** [comment]
Thanks for the quick turnaround! Is it possible to link here the pull request(s) which fix this issue?

**Comment by yaananth** [comment]
That is not a task fix, it's a fix for internal code, I don't think it's possible to link here.
