### ISSUE TITLE
Unexpected Exit Code 1 in Power Shell Task 

### ISSUE THREAD

**Issue by zechariahks** [Microsoft/vsts-tasks#1605]
Hi,

I am running simple Robocopy command in the powershell script. it works fine manually without any errors. But in VSO, I am getting exit code 1 error message after the script execution. Can some one help on this issue.

2016-04-28T20:33:09.6108297Z VERBOSE: Completed creating the bits drop folder H:\agent3\_work\1\a\EntitlementManagementService
2016-04-28T20:33:09.6528421Z ##[error]Process completed with exit code 1.

**Comment by ericsciple** [comment]
The task checks $lastexitcode and errors if it's not zero. IIRC 0-16 are success codes for robocopy.

**Comment by bryanmacfarlane** [comment]
@zechariahks - does that help?  Can you handle err code in your script>

**Comment by ericsciple** [comment]
**Correction**, it looks like [robocopy exit codes](http://ss64.com/nt/robocopy-exit.html) 0-7 indicate success. You can add this add this to the bottom of your script:
```powershell
if ($lastexitcode -lt 8) { $lastexitcode = 0 }
```

It doesn't look like we document that behavior of the task, and it doesn't feel intuitive to me. I'm not sure we have a good place to document it today on the task UI itself (we can add to the external msdn article). I wonder if exposing as an advanced checkbox would kill two birds with one stone? Or perhaps it's not particularly useful to turn off? @chrisrpatterson, thoughts?

**Comment by bryanmacfarlane** [comment]
We've discussed this before.  In cases where you need custom error handling in your task (0 == success is not sufficient) then handling in your task/ad-hoc script is the proper place to do it.

**Comment by pshelton-skype** [comment]
The correct code to supress the non-zero robocopy exit codes is:
```powershell
if ($lastexitcode -lt 8) { $global:lastexitcode = 0 }
```

**Comment by cawoodm** [comment]
Anyone know an equivalent "robocopy" command for Linux?
