### ISSUE TITLE
Marketplace Upload Failed for Tasks Extension 

### ISSUE THREAD

**Issue by IsmaelKP** [Microsoft/vsts-tasks#1619]
I am trying to upload private extension from vsts-tasks to my VSTS  Marketplace. I followed the tutorial https://www.visualstudio.com/en-us/integrate/extensions/get-started/node and upload my first extension which worked fine.

I wanted to install extension such as Chef CocoaPods etc. With the task.json found in the file I had several issues while packaging.
No publisher found, No targets version etc.. 
![tasksuploadfailed1](https://cloud.githubusercontent.com/assets/4320318/14978705/15af2d2e-111e-11e6-84c3-e5d07b80e70f.PNG)

I can imagine that the format changed so I did the change and manage to package the .vsix

When uploading I have the issue tasks.json was not found in contribution. I tried to find similar issue on stack but did not find. Do you have a clue on were the problem could come from ?

![tasksuploadfailed2](https://cloud.githubusercontent.com/assets/4320318/14978787/86d19546-111e-11e6-9302-6896263db586.PNG)

Regards,

**Comment by bryanmacfarlane** [comment]
Create an issue in the tfs-cli repo: https://github.com/Microsoft/tfs-cli

Also, just to confirm, you're not uploading tasks from this repo as extensions correct?  These are tasks that we publish (in the box).

**Comment by IsmaelKP** [comment]
Hi, thanks for replying. My issue is that some Tasks are not available anymore on the Build and Release "Add Tasks" panel. I thought that these tasks had to be upload as private extension this is the mail I received from the microsoft support

"Hi Ismael,

Chef task is still in preview. We plan to make it an extension and share it via the VSTS marketplace. However it will be a while before we can get to it. Until then, the workaround is to get the task from GIT Hub and upload it to your account with a different guid.

Regards"

What you are telling me is that I can upload my tasks from tfx-cli without having to package the extension.

**Comment by IsmaelKP** [comment]
I tried to upload the Tasks using your solution. following the video https://www.youtube.com/watch?v=u_4ZJcEE3S4&feature=youtu.be It worked but I am unable to see the tasks in the Build Task panel. I opened a ticket in the hub you mentionned.
