### ISSUE TITLE
AzureRMWebApp not deploying changes

### ISSUE THREAD

**Issue by avidanthony** [Microsoft/vsts-tasks#1625]
When using the AzureRMWebApp task, after some debugging I've found that MSDeploy command changes are not getting deployed, however when I run the same command from my workstation the MSDeploy command syncs correctly.

I first noticed with Hosted build agents that I could not get that AzureRMWebApp task to succeed. Then when I created my own build agent, I found that the task succeeded but my changes were not being deployed.

After verifying the correct build artifacts and release configurations, I went to the build agent and tried to run the generated command directly. It then tried to install Windows Features and failed saying the "the following feature could not be installed: .NET Framework 3.5 (includes .NET 2.0 and 3.0)." 

It would appear that the MSDeploy command being generated cannot run on hosted or non hosted agents.

**Comment by chshrikh** [comment]
Deployment team is looking into it

**Comment by avidanthony** [comment]
Some more information

As mentioned before, I was unable to get the task to work on a hosted agent. Here is what the log looks like 
![error with no message on hosted agent](https://cloud.githubusercontent.com/assets/4617837/15027255/baa23950-11f7-11e6-8eb6-2f131e1fe1a6.png)

I then provisioned my own agent for with the following sku
"imagePublisher": {
      "value": "MicrosoftVisualStudio",
    },
    "imageOffer": {
      "value": "VisualStudio",
    },
    "sku": {
      "value": "VS-2015-Ent-VSU2-AzureSDK-29-WS2012R2",
    },

The resulting machine is Windows Server 2012 R2

The task in Release Management now succeeds, but when you look at the logs you find MSDeploy doesn't actually deploy anything. I can verify my changes don't show up in the target website
![silent failure that shows green success when nonhosted agent does not have net 3 5](https://cloud.githubusercontent.com/assets/4617837/15027407/7849f830-11f8-11e6-86ff-20c1ea6a5b2b.png)

When I tried to run the command directly on that machine, I got this message and an empty result
![dotnet could not be installed](https://cloud.githubusercontent.com/assets/4617837/15026977/25bdf988-11f6-11e6-8456-27fe7d766085.png)

After installing the .NET framework feature, I was able to successfully run the task. and see results
![successful hosted agent after installing dotnet 3 5](https://cloud.githubusercontent.com/assets/4617837/15027397/6cd0b192-11f8-11e6-918d-99c14e507315.png)

So the issue appears that this task doesn't run correctly in hosted agents, and the default installation of VSO bits on a non-hosted agent does not include the .net 3.5 dependency needed for this to run successfully.

**Comment by rglos** [comment]
I have this exact issue using the Hosted agent as @avidanthony.  I will attempt to use a non-hosted agent and ensure it has .NET 3.5.

I came to use this task instead of the non-RM version because of the AppOffline issue we are getting that is getting reported in #1607

**Comment by chshrikh** [comment]
For hosted agent team is working to get it fixed .

**Comment by Ajay-MS** [comment]
@avidanthony  , @rglos  :  Above issue with hosted agent has been fixed. You can upload your webapp using this task and let me know if you still face any issue.

**Comment by avidanthony** [comment]
Awesome! I can see it working w/ the hosted agent!

![itworks](https://cloud.githubusercontent.com/assets/4617837/15195634/795dbe20-177d-11e6-8d96-112cecb6319f.png)
![itworks2](https://cloud.githubusercontent.com/assets/4617837/15195636/7a0a5590-177d-11e6-80f5-d53c3f97bc8b.png)
