### ISSUE TITLE
Xcode build plugin fails for apps that include watchkit

### ISSUE THREAD

**Issue by petevanc** [Microsoft/vsts-tasks#1633]
When building an iOS workspace that includes both app and watchkit output the -sdk parameter should not be specified when building with xcodebuild.

The Xcode Build plugin, however, does not allow the SDK field to be blank.

This suggests that the Xcode Build plugin cannot be used to build an iOS workspace that includes both an app and watchkit output.

**Comment by madhurig** [comment]
Fix is deployed to Team Services.

**Comment by maitines** [comment]
Sorry, but i think that not works yet.

2016-10-05T20:43:26.0571980Z xcodebuild: error: SDK "$(SDK)" cannot be located.
2016-10-05T20:43:26.0741570Z ##[error]Error: /usr/bin/xcodebuild failed with return code: 64

**Comment by madhurig** [comment]
@maitines: Please check the task inputs, It looks like you are passing $(SDK) to the Xcode task but that variable does not exist. You should be able to clear SDK input on the task and continue.

**Comment by maitines** [comment]
Now it seems that builds ok but at the end:

_** BUILD SUCCEEDED **
/usr/bin/xcrun -sdk PackageApplication -v /Users/XXXXXXXXXX/Development/iOS/myagent/_work/2/s/output/Release/Release-/build.dsym/build.sym/Release-watchos/AppWatch.app -o 
/Users/XXXXXXXXXX/Development/iOS/myagent/_work/2/s/output/Release/Release-/build.dsym/build.sym/Release-watchos/AppWatch.ipa

xcodebuild: error: SDK "null" cannot be located.
xcrun: error: unable to find utility "PackageApplication", not a developer tool or in PATH
Error: /usr/bin/xcrun failed with return code: 72_

**Comment by madhurig** [comment]
@maitines: Which version of Xcode are you using? Do you have access to your build server? You are getting the error from "Creating App Package" which is passing in the SDK version to the tool (even if not specified). In the next couple of weeks we will be switching from using xcrun for Xcode7 and 8 to xcodebuild for generating the packages. I will include a fix in that change. If you uncheck "Create App Package" in your task, your build will succeed. If you need to generate the IPA, I can provide a workaround for you.

**Comment by maitines** [comment]
I'm using xcode 8 and build server is my mac.
Now i'm compiling now unchecked Creating App Package but it takes about 20 minutes and now finish yet (the same app without apple watch builds ok in about 4 minutes), this is the last line in console:

CompileAssetCatalog output/Release/Release-/build.dsym/build.sym/Release-watchos/AppWatch.app TgWatch/Assets.xcassets
    cd /Users/XXXX/Development/iOS/myagent/_work/2/s
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/XXXX/.npm-packages/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin"
    /Applications/Xcode.app/Contents/Developer/usr/bin/actool --output-format human-readable-text --notices --warnings --export-dependency-info /Users/XXXX/Development/iOS/myagent/_work/2/s/output/Release/Release-/build.dsym/build.obj/trainingym.build/Release-watchos/TgWatch.build/assetcatalog_dependencies --output-partial-info-plist /Users/XXXX/Development/iOS/myagent/_work/2/s/output/Release/Release-/build.dsym/build.obj/trainingym.build/Release-watchos/TgWatch.build/assetcatalog_generated_info.plist --app-icon AppIcon --target-device watch --compress-pngs --enable-on-demand-resources NO --sticker-pack-identifier-prefix com.trainingym.trainingym.watchkitapp.sticker-pack. --minimum-deployment-target 2.2 --platform watchos --product-type com.apple.product-type.application.watchapp2 --compile /Users/XXXX/Development/iOS/myagent/_work/2/s/output/Release/Release-/build.dsym/build.sym/Release-watchos/AppWatch.app /Users/XXXX/Development/iO..

**Comment by madhurig** [comment]
I also found that xcrun does not support creating packages for "WatchKit". So once the new implementation to use xcodebuild for generating package is available on Team Services, you should be able to use that.

I notice that even sample watch kit projects take longer to build but what you are noticing seems drastic. The output from xcodebuild indicates it is taking time in CompileAssetCatalog. Are you doing something different with the WatchKit project assets?

**Comment by maitines** [comment]
No, it's the same process like other apps that builds ok.
Finally my local agent show a timeout and not build (i tried this preocess two times)

**Comment by madhurig** [comment]
@maitines: Can you share the full build log here or email it to me at madhurig at Microsoft dot com?
