### ISSUE TITLE
Nuget installer task does not work within Release

### ISSUE THREAD

**Issue by GitHubSriramB** [Microsoft/vsts-tasks#1636]
On Windows agent, task fails with following error:
##[error]System.Management.Automation.ParameterBindingValidationException: Cannot bind argument to parameter 'Path' because it is null.

**Comment by vtbassmatt** [comment]
Can you please share the full log and a screenshot of how you have the step configured? Thanks.

**Comment by vtbassmatt** [comment]
Fixed by #1635
