### ISSUE TITLE
[Understood: Solution Below]'Use of const in strict mode' Error

### ISSUE THREAD

**Issue by peder** [Microsoft/vsts-tasks#1639]
In the last week, I've started to see the following error, first on the `Gulp` task, but now on the `NPM` task:

```2016-05-05T16:01:42.2922697Z Set workingFolder to default: F:\agent_vsts_20160413\tasks\Npm\0.2.12
2016-05-05T16:01:42.6830778Z F:\agent_vsts_20160413\tasks\Npm\0.2.12\npmtask.js:3
2016-05-05T16:01:42.6830778Z const path = require('path');
2016-05-05T16:01:42.6830778Z ^^^^^
2016-05-05T16:01:42.6830778Z SyntaxError: Use of const in strict mode.
2016-05-05T16:01:42.6830778Z     at exports.runInThisContext (vm.js:73:16)
2016-05-05T16:01:42.6830778Z     at Module._compile (module.js:443:25)
2016-05-05T16:01:42.6830778Z     at Object.Module._extensions..js (module.js:478:10)
2016-05-05T16:01:42.6830778Z     at Module.load (module.js:355:32)
2016-05-05T16:01:42.6830778Z     at Function.Module._load (module.js:310:12)
2016-05-05T16:01:42.6830778Z     at Function.Module.runMain (module.js:501:10)
2016-05-05T16:01:42.6830778Z     at startup (node.js:129:16)
2016-05-05T16:01:42.6830778Z     at node.js:814:3```

I am using Node 6.0.0, but I also tried this with Node 4.4.3. I confirm the Node.js version with a PowerShell Script at the top of my Build definition: `node --version`.

Has anyone else come across this? Every StackOverflow post about this error is really old and always recommends upgrading Node, but that didn't help in my case. Do the Tasks run with a certain flag to execute in compatibility mode or something like that?

Is there a requirement to use a certain version of Node? I noticed the Hosted version is `0.12.x`. Should I downgrade to that version?

**Comment by peder** [comment]
If I manually open up `npmtask.js` and add the following: `console.log(process.version);`, I see that the version of Node.js that's executing is `v0.12.7`. Can I force these tasks to run under Node 6.0.0 or any version later than 0.12.7?

**Comment by peder** [comment]
Also, when looking in the diagnostics log, I see the following message: `Tasks require a new agent.  Upgrade your agent or node to 4.2.0 or later`

**Comment by peder** [comment]
After upgrading to Node 6.0.0, I restarted the `VSO Agent` Windows service and now it looks like I'm good to go. Don't forget, everyone, to restart your agents after any installations or other server changes.

**Comment by ericsciple** [comment]
Do you know what version your agent was? It should still be in the agent.old folder (`agent.old\vsoagent.exe /version`).

**Comment by ericsciple** [comment]
You updating to Node has nothing to do with it.  We carry our own node in the agent.  The agent should have auto updated and you shouldn't have to restart either.  Restarting papered over what the issue was and triggered it to auto update.

The guidance should not be to restart your agents after server changes.

Some questions:
- are you running a release or a build?
- check the agent.old folder for version

**Comment by ericsciple** [comment]
Also, which account are you on? i.e. ___.visualstudio.com

**Comment by bryanmacfarlane** [comment]
The previous sprint carried node5 in the agent and we have server code the triggers the agent to update.  obviously it didn't.  you restarting triggered it.  Eric's questions are interesting

**Comment by bryanmacfarlane** [comment]
@peder - details would help us narrow the real issue.  Thanks!

**Comment by peder** [comment]
Thanks all the comments. The previous agent version was `1.98.1`. It updated to `1.99.0`. This is off of tenaskainc.visualstudio.com, and the issue impacted both Builds and Releases (I had tried in both, in case the issue was specific to one type)

Also, I should mention that `PATH` changes are not reflected in the app until I restart the service, hence my recommendation to perform a restart if you do any installs (particularly those that would change the `PATH` variable)

Hope that helps. Thanks again.

**Comment by ericsciple** [comment]
Very strange. Can you run `agent.old\Worker\Handlers\Node\node.exe --version`

**Comment by peder** [comment]
v0.12.7

**Comment by peder** [comment]
If it helps, I had downloaded the .zip file with the Agent on April 13th.

**Comment by bryanmacfarlane** [comment]
OK.  We figured it out.  April 12th bumped agent version to 98.1 and 98.1 was patched on April14th.  So this affects anyone who runs their own agent, uses npm/gulp, and restarted their service or downloaded a new one between April 12th or 13th.

Workaround, restart your agent.

**Comment by peder** [comment]
I'm guessing this is a _very_ isolated problem, but I appreciate the quick yet thorough response.

**Comment by bryanmacfarlane** [comment]
Cool.  Thanks a bunch for helping us figure it out.  I'm going to leave active in case others need to see it.  We have one ring to go
