### ISSUE TITLE
IISWebAppDeployment Application Pool Password with $ character

### ISSUE THREAD

**Issue by vercellone** [Microsoft/vsts-tasks#1645]
$ characters followed by alphanumeric characters in the Application Pool Password ($appPoolPassword) are treated as variables that get replaced with empty string(s), and then the application pool doesn't start due to authentication failures.

**Comment by chshrikh** [comment]
Deployment team is checking this

**Comment by gregjhogan** [comment]
sounds very similar to #1417

**Comment by mvvsubbu** [comment]
We will be fixing this issue in the new extension for IIS Task https://github.com/Microsoft/vsts-rm-extensions

**Comment by mvvsubbu** [comment]
Fixed the issue with PR : https://github.com/Microsoft/vsts-rm-extensions/pull/19
