### ISSUE TITLE
Add support for binding boolean parameters to variables

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/vsts-tasks#1656]
If you create a task with a boolean input parameter, there appears to be no way to use that task in a build/release and bind the value to a variable.
This would be similar to making a pickList input parameter editable: `"EditableOptions": "true"`.
Thanks!

**Comment by ericsciple** [comment]
The workaround is to use a pick list with true/false.

**Comment by gregjhogan** [comment]
I didn't realize powershell automatically does `[bool]::Parse()` on `param() { [bool]$input }` powershell parameters.  So it seems like this is a great workaround because I can still have a bool param in my powershell script (even though it is a string input in task.json).  However, it isn't very discoverable, it would be nice if there was a button next to the checkbox that changed it to a text box.  Thanks!

**Comment by ericsciple** [comment]
On a side note, it sounds like you are using the legacy powershell task execution handler. Consider switching over to one of the new handlers where future investments are being made: https://github.com/Microsoft/vsts-task-lib/

The node handler runs everywhere, the powershell3 handler only runs on Windows.

**Comment by bryanmacfarlane** [comment]
https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/vsts-task-lib.md#taskgetBoolInput

Check out Xcode use xctool bool input:
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Xcode/task.json

https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Xcode/xcodebuild3.ts

**Comment by bryanmacfarlane** [comment]
Eric - since the task.json has support for bool type, perhaps ps3 lib has getBoolInput like the node lib?

**Comment by ericsciple** [comment]
It has it :)
```
-AsBool
```
https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/Commands.md#get-vstsinput

**Comment by gregjhogan** [comment]
Since task.json inputs are automatically mapped to `params() {...}` in a powershell script, and powershell already automatically converts a string to a bool param for you (see my earlier comment), I am not sure there is a need.  I feel like the only thing you need is a UI enhancement to support a variable being input.

**Comment by ericsciple** [comment]
The inputs aren't passed as params in the new execution handler. You're using the legacy, closed source handler.

**Comment by gregjhogan** [comment]
That seems unfortunate, it seems more intuitive to use params (and simpler, I don't need to load and learn how to use a custom ps module).  It is also easier to test and easier to re-use outside of VSTS tasks.  Also, I love typescript, but the simplicity of not having to compile anything is convenient, too, and I don't think cross platform task support gives me any benefit when building/deploying web apps targeting Azure PaaS offerings.  It also seems plausible that someday powershell runs on Linux.  If I stick with powershell (not sure if I will), these would be the reasons why.

I am sure there are situations where additional features are needed that are not supported by what I just described, but I have written a number of custom tasks and have yet to encounter a need for anything more complex, and I prefer to keep things as simple as possible when possible.

Since you call this handler legacy, do you already consider it deprecated?  Thanks!

**Comment by gregjhogan** [comment]
I am actually using the AzurePowerShell execution handler (I am using a service endpoint):
```javascript
  "execution": {
    "AzurePowerShell": {
      "target": "$(currentDirectory)\\provision.ps1",
      "argumentFormat": "",
      "workingDirectory": "$(currentDirectory)"
    }
  }
```

Is that considered legacy?  If yes, how do you specify the non-legacy equivalent?  Thanks!

**Comment by ericsciple** [comment]
I'm working on taking the mystery out of that handler. You can look at the AzurePowerShell task as the PowerShell3 handler equivalent. However, that task contains somewhat peculiar back-compat logic since it is used to run ad-hoc scripts. I'm going to switch over another one soon.

Testing is a bigger focus in the new libs. You can actually test your tasks end-to-end now without running an agent at all. Also the new libs have tracing built-in. By using them, you get some tracing added to your task.

These tasks have been converted over: [AzurePowerShell](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/AzurePowerShell), [MSBuild](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/MSBuild), [PublishSymbols](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/PublishSymbols), [VSBuild](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/VSBuild).

Many others have been converted to use the Node handler.

**Comment by gregjhogan** [comment]
Ah, at first I thought you were saying the PowerShell3 handler was the legacy handler.  Now things are making a lot more sense.  Thanks for the help, this looks really good now.

Back to the original issue, long-term it would be nice if there was a way (perhaps for other input types, too) where you could toggle between a checkbox and a control that allowed you to specify a variable.  It seems like everything behind the UI may work as-is. Thanks!

**Comment by bryanmacfarlane** [comment]
A few things on the subject ....

The lib has alot of benefits.  Most notably out of proc execution for reliability, isolation (diamond version conflicts) and testing.  Everything is through decoupled I/O (envvars and stdin/out).  [See here](https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/README.md).  All communication back is by writing ##vso commands back to stdout.

See here: https://www.youtube.com/watch?v=Ta2c3sUbJ18
And here: https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md

You don't have to do typescript.  You can write in javascript but you lose compile time checking (finds alot of bugs in invalid code in not hit arcs) and async await.  See [ShellScript how nice that is](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/ShellScript/shellscript.ts).  You also get the convenience of trying out changes on the fly with the javascript it produces but finally commit back.

**Comment by bryanmacfarlane** [comment]
Everything I pointed out above, allows us to write tests that test all arcs of the script (1) without the tools we're driving (tests xcode task on windows dev box) (2) no agent and (3) no service.

https://github.com/Microsoft/vsts-tasks/blob/master/docs/runningtests.md
https://github.com/Microsoft/vsts-tasks/blob/master/Tests/L0/Gulp/_suite.ts

**Comment by gregjhogan** [comment]
Thanks for sharing, it can be difficult understanding what is up-to-date and what is out-of-date, so that really helps!

**Comment by ericsciple** [comment]
Based on the original context it sounds like this issue can be closed. I don't think there is an issue here. Feel free to reopen or start a new issue if my interpretation is incorrect.
