### ISSUE TITLE
When visibleRule evaluates to false, default value should be saved

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/vsts-tasks#1658]
Tasks inputs that have a `visibleRule` seem to save the last selected value even when they are hidden.  Seems like they should revert to a default value on save when they are not visible. Then you don't have to duplicate the visibility rules in the task definition and in the code.

**Comment by ericsciple** [comment]
The current behavior can be useful when changing the behavior of a task - i.e. adding new inputs.

**Comment by gregjhogan** [comment]
Maybe I didn't explain myself very well because I am not sure how this is useful when adding new inputs to a task. My scenario is the following:
1. Add a build step where the visibility of some input can be toggled
2. Make the input visible (initially it has the default value)
3. Change the value to a non-default value
4. Change back to a state where the input you just changed is no longer visible
5. Save (at this point I wish it saved the default value, or nothing at all for the hidden input)

**Comment by bryanmacfarlane** [comment]
@chrisrpatterson to consider

**Comment by bryanmacfarlane** [comment]
This is not a task issue with the tasks in this repo.  This is a web UX issue.  We're rev'ing the UX designer next and tracking in that redo.
