### ISSUE TITLE
"SQL Server Database Deployment" Not Available in VSTS

### ISSUE THREAD

**Issue by peder** [Microsoft/vsts-tasks#1674]
In my "Add Tasks" window in a VSTS Build or Release Definition, I do not see the "SQL Server Database Deployment" Task. Is that Task not published to VSTS? I see the Azure one, but not the on-premise DACPAC Task.

**Comment by kmkumaran** [comment]
This task is currently in preview. The plan is to make it as an extension soon. If you would like to use this task in preview mode, kndly drop an email to rm_customer_queries on the domain microsoft dot com

**Comment by brettjacobson** [comment]
Will this task work on premises when released?

**Comment by FrenchKoyote** [comment]
Hi @kmkumaran 
I have same needs like @brettjacobson about deployment from VSTS to On Premise SQL server.
Does the On Premise SQL task is available now on VSTS?

Regards,
