### ISSUE TITLE
AzureRmWebAppDeployment Uploading

### ISSUE THREAD

**Issue by russelldyas** [Microsoft/vsts-tasks#1682]
I have uploaded AzureRmWebAppDeployment as custom task via VSTS.  However, it does not appear in the tasks list.

I tried to upload again and got a conflict error as been uploaded.  The error is  Failed Request: Conflict(409)

I did some research and same issue as here https://github.com/Microsoft/vsts-tasks/issues/465

I believe this is down to the task currently being in preview.  Can we get this enabled for our VSTS please?

From

Russell

**Comment by codito** [comment]
@russelldyas yes, the task is under preview. Can you please drop an email to rm_customer_queries on the domain microsoft dot com /cc:roopeshnair

**Comment by russelldyas** [comment]
Thank you I have emailed in requesting access.

From

Russell

**Comment by thatpaulschofield** [comment]
How did you manage to package the task? I keep getting the "No recognized targets found. Ensure that your manifest includes a target property. E.g. "targets":[{"id":"Microsoft.VisualStudio.Services"}],..." error when I run "tfx extension create --manifest-globs task.json"

**Comment by codito** [comment]
@thatpaulschofield are you on TFS on-premise? Which version? This task is already public for visualstudio.com accounts.
