### ISSUE TITLE
Error with Sonar PR bot feature

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vsts-tasks#1685]
I tried to enable the new PR bot feature of the Sonar tasks through setting `SQPullRequestBot` variable to true.

While running the build for a PR it does the Sonar analysis, but later fails with the following error:

```
2016-05-10T12:32:30.5089119Z Creating a discussion comment for the message at line 91 from /MySolution/BusinessServices/ViewModels/ReportViewModelService.cs
2016-05-10T12:32:30.5714457Z ##********[task.logissue type=error;]No changes found for /MySolution/BusinessServices/ViewModels/ReportViewModelService.cs
2016-05-10T12:32:30.5714457Z ##********[task.complete result=2;]
```
While the mentioned file contains changes in this PR.

**Comment by bgavrilMS** [comment]
Hi @pascalberger, thank you for trying this! Yes, we found and fixed the bug which you encounter. The actual fix is in the build agent, so you upgrade the build agent to 1.99.0 and try again? 

To check the version of your agents, please go to the Admin area and select Agent pools, then select your agent and look at "Capabilities". Agent.Version should be at 1.99.0. To upgrade your agent, right click on the build pool and select "Update all agents". The hosted agent should already be at 1.99.0.

**Comment by pascalberger** [comment]
Thanks @bgavrilMS. Updating the Agent fixed this.

**Comment by bgavrilMS** [comment]
Sure. Let us know if you have any feedback on the this feature. I just pushed a change that will enable this feature without setting that build variable to true (it will take ~3 weeks before it hits production though).

**Comment by pascalberger** [comment]
@bgavrilMS Sure, already did the first one: #1693 :)
