### ISSUE TITLE
NuGetInstaller - The property DirectoryName does not exist or was not found

### ISSUE THREAD

**Issue by stuartleeks** [Microsoft/vsts-tasks#1686]
If the "path to solution or packages.config" property of the NuGetInstaller task is set to a folder that exists then the NuGetInstaller task fails with the somewhat cryptic message "The property DirectoryName does not exist or was not found"

Digging into it, the message comes from [this line](
https://github.com/stuartleeks/vsts-tasks/blob/6b529834b37753f2737744fdcd6bbe9768ccf13f/Tasks/NuGetInstaller/NuGetInstaller.ps1#L137):

```posh
$slnFolder = $(Get-ItemProperty -Path $sf -Name 'DirectoryName').DirectoryName
````

The issue is that Get-ItemProperty finds the path, but because it is a directory it doesn't have a DirectoryName property

It would be more helpful if the error message gave a pointer to the problem and what to do about it.

**Comment by vtbassmatt** [comment]
#1687 should have fixed this. If not, you can reactivate.
