### ISSUE TITLE
DeleteFiles plugin fails if there are symlinks.

### ISSUE THREAD

**Issue by petevanc** [Microsoft/vsts-tasks#1688]
Variables
output_directory=$(Agent.BuildDirectory)/output
symlink_directory=$(output_directory)/test
symlink_source_file=$(Build.SourcesDirectory)/TestProjects/iOS/Rakefile
symlink_target_file=$(symlink_directory)/Rakefile

Command Line
Tool=/bin/bash
Arguments=-c "if [ -d $(output_directory) ]; then ls -FaR $(output_directory); else echo 'Directory not found $(output_directory)'; fi"

Delete Files
Source Folder=$(output_directory)
[logs_16327.zip](https://github.com/Microsoft/vsts-tasks/files/257918/logs_16327.zip)

Contents=**
Continue on error=true

Command Line
Tool=mkdir
Arguments=-pv $(symlink_directory)
Continue on error=true
[logs_16326.zip](https://github.com/Microsoft/vsts-tasks/files/257917/logs_16326.zip)

Command Line
Tool=ln
Arguments=-sFv $(symlink_source_file) $(symlink_target_file)

Delete Files
Source Folder=$(output_directory)
Contents=**

Command Line
Tool=/bin/bash
Arguments=-c "if [ -d $(output_directory) ]; then ls -FaR $(output_directory); else echo 'Directory not found $(output_directory)'; fi"
Always run=true

**Comment by ericsciple** [comment]
Copying comments from @chrisrpatterson from closed duplicate issue:
> The delete files task should delete any simlinks but not follow them.

**Comment by bryanmacfarlane** [comment]
This is fixed in 105.  We won't follow symlinks
