### ISSUE TITLE
Sonar PRCA comments twice on subsequent runs

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vsts-tasks#1693]
I've created a PR which run Sonar PRCA and found one new item, which it commented correctly in the PR.
Afterwards I changed some other stuff in the PR, without fixing this comment, pushed them. As a result a subsequent build was run, which again found this CA violation which the Sonar task again commented on the same line.

It would be nice if the task could check if it already added a comment for a certain violation and only add comments which don't already exist.

**Comment by bgavrilMS** [comment]
Oh, do you mean the same comment appeared twice on the same line? Is the comment identical (e.g. "Unused variable 'a'" is different from "Unused variable 'b'")

The expectations when you push another commit to the PR are:

- Do not add comments for existing issues
- If an issue no longer appears, it means it has been fixed, so mark it as "Resolved"

**Comment by pascalberger** [comment]
Yes, same issue on the same line:

![image](https://cloud.githubusercontent.com/assets/2190718/15179322/3c64d208-177b-11e6-9753-6a4514c49a69.png)

**Comment by bgavrilMS** [comment]
Thank you Pascal, I'm looking into it.

**Comment by bgavrilMS** [comment]
I couldn't get this to repro. I tried marking the message with "Won't Fix" and as well. I suspect this is because we only use the message content to do matching operations, which has a lot of limitations (you'd think we could use the line number as well, but code moves...). Are the 2 messages identical? It looks to me like they are but it's difficult to diff pics.

**Comment by pascalberger** [comment]
Yes, it seems like the same error also no changes between builds for this
file. Subsequent builds again added the comment. Any way to raise log level
to get some more infos?
Am 16.05.2016 14:56 schrieb "Bogdan Gavril" <notifications@github.com>:

**Comment by bgavrilMS** [comment]
You can set the build variable "system.debug" to "true" to get more detailed logs.

**Comment by bgavrilMS** [comment]
Hi Pascal, did you manage to repro this again, perhaps with a simpler message?
