### ISSUE TITLE
Sonar PRCA: Add link to Sonar rule page

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vsts-tasks#1694]
It would be helpful for developers if the comments added by the Sonar task contain a link to the rule page in Sonar, where is explained whats wrong (eg. https://nemo.sonarqube.org/coding_rules#rule_key=csharpsquid%3AS2757)

**Comment by bgavrilMS** [comment]
Thanks @pascalberger - that's a good suggestion. This is on the backlog, but currently the comments are in just text format so it would be ugly to add URLs like that. However md format will be supported soon and we'll revisit this.
