### ISSUE TITLE
Working directory is wrong for PowerShell/Batch/CmdLine tasks

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-tasks#1701]
Should default to the script directory, per the help markdown.

**Comment by baumerik** [comment]
with the new Agent the working folder is set correctly as default to the script directory but how could I configure the Root Directory as working dir? or should better be this as default?

**Comment by bryanmacfarlane** [comment]
We updated the help markdown to be root of repo for ps task.  We couldn't break compat
