### ISSUE TITLE
VsTest Version set to "Latest" get the warning for run test in parallel

### ISSUE THREAD

**Issue by dixu99** [Microsoft/vsts-tasks#1702]
Hi, 

our build agent has 2015 update 1 installed. In "Visual Studio Test" task, when we check "Run in Parallel" and set VSTest version to "Latest", we get a warning like this "##[warning]Install Visual Studio 2015 Update 1 or higher on your build agent machine to run the tests in parallel."

When we set VSTest version to "Visual Studio 2015", the IsVisualStudio2015Update1OrHigherInstalled function works correctly. No warning in the test output. 

Can you check if IsVisualStudio2015Update1OrHigherInstalled works as expected when with VSTest version set to "latest"? 

Thanks,
Di

**Comment by atinb** [comment]
@dixu99 
What version is the TFS server on? Can you download the Build agent from the TFS server and try again?
Thanks!

**Comment by bryanmacfarlane** [comment]
Agent should auto update itself on restart.

**Comment by atinb** [comment]
That is true for agents running as service. 
@dixu99 : is your agent running in interactive mode? If so, can you please try updating?
Thanks!

**Comment by dixu99** [comment]
We run the agent as service. I will restart the agent and try again. 

Thanks,
Di

**Comment by dixu99** [comment]
I restarted the agent, still getting the warning text when I set VsTest Version to "Latest". We are running TFS 2015 update 1. 

Thanks,
Di

**Comment by kaadhina** [comment]
Di,
What is the edition of visual studio (Enterprise/professional, etc.) that you have installed?
Can you take a look at this registry: HKLM/Software/Microsoft/VisualStudio and tell us what is the maximum version under that node?

**Comment by dixu99** [comment]
VS Enterprise edition. 2015 update 1. The maximum version listed in the registry is 14.0. 
There are two versions installed 12.0 and 14.0. 

This is the version of VsTest task used: 
2016-05-17T14:29:50.0853131Z Executing the powershell script: C:\agent\tasks\VSTest\1.0.29\VSTest.ps1

The following code are not in the Helpers.ps1 in 1.0.29. I think this might be the problem. 

	if ([string]::IsNullOrWhiteSpace($vsTestVersion)){
		$vsTestVersion = Locate-VSVersion
	}

We have TFS update 1 on-prem. Is 1.0.29 the version of this task went out with update 1?  
I can take the new version of task here and upload it to TFS. 

Thanks,
Di

**Comment by wizardbyte** [comment]
I believe the problem is in VSTest.ps1. I'm using version 1.0.30 and there is this bit of code in VSTest.ps1:

```
if($vsTestVersion -eq "latest")
{
    # null out vsTestVersion before passing to cmdlet so it will default to the latest on the machine.
    $vsTestVersion = $null
}
```

When using "latest" as your VSTest version then the value gets reset to null so that it defaults to the latest. This falls apart later when the run in parallel bit is checking if you have the right VS version available. and $vsTestVersion is null.

```
if($runInParallel -eq "True")
{
    $rightVSVersionAvailable = IsVisualStudio2015Update1OrHigherInstalled $vsTestVersion
    if(-Not $rightVSVersionAvailable)
    {
        Write-Warning (Get-LocalizedString -Key "Install Visual Studio 2015 Update 1 or higher on your build agent machine to run the tests in parallel.")
        $runInParallel = "false"
    }
}
``` 

I verified this by explicitly selecting Visual Studio 2015 as the VSTest version and it ran in parallel without the warning.

**Comment by xxMUROxx** [comment]
Same output if VS2017 is installed

**Comment by mfields3** [comment]
Is there a fix for this? Facing the exact same issue.

**Comment by bennett-elder** [comment]
Is there a fix for this? Facing the same issue with a build server that has only VS2017 installed. Would really like to be able to run tests in parallel despite not wanting to install VS2015 on a new machine.

**Comment by bennett-elder** [comment]
> Is there a fix for this? Facing the same issue with a build server that has only VS2017 installed. Would really like to be able to run tests in parallel despite not wanting to install VS2015 on a new machine.

Changing to v2 of the step defn (ts-based instead of ps-based) sidesteps this issue. I reckon that's why it hasn't been resolved in v1.
