### ISSUE TITLE
AzureRmWebAppDeployment folder deployment support

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/vsts-tasks#1704]
AzureRmWebAppDeployment currently exclusively supports deploying a package (-source:package=...).  Would you add support (or be open to a pull request) that adds contentPath support?  The simplest solution would rename the input param "package" to something more generic and use -source:package when it is a file and -source:contentPath when it is a folder.  An alternative would be a package vs. folder selector which toggles between showing a package input parameter and a folder input parameter.  Thanks!

**Comment by kmkumaran** [comment]
@gregjhogan, Thanks for the feedback. Yes. this is in our plans. We will soon enhance the task to start taking content path. Adding @RoopeshNair

**Comment by RoopeshNair** [comment]
We have this on our backlog. Please stay tuned
