### ISSUE TITLE
Unable to process logging event

### ISSUE THREAD

**Issue by tomap** [Microsoft/vsts-tasks#1723]
Hi,

I'm trying to update the buildnumber and get this error
Unable to process logging event:

`2016-05-13T16:17:05.9851134Z ##[warning]Unable to process logging event:  ##vso[build.updatebuildnumber]9086 on merge/V-9.0.305.10086 for Barthé on Agent-XXX-RD-BESSSS1`

Any idea on the issue?
I have agent version 1.99.0

Thank you

**Comment by ericsciple** [comment]
Is this the same problem as https://github.com/Microsoft/vsts-tasks/issues/1724?

**Comment by bryanmacfarlane** [comment]
Dupe
