### ISSUE TITLE
 Build tag is not added successfully.

### ISSUE THREAD

**Issue by tomap** [Microsoft/vsts-tasks#1724]
I'm using hosted agent and have created a .bat file with the following content:
echo ##vso[build.addbuildtag]addbuildTag4444545

When I run that, it works, the tag is properly added to the build, but I have this error message dispalyed in logs.

**Comment by TingluoHuang** [comment]
@tomap Can you add echo off in front of your .bat script?

**Comment by tomap** [comment]
Hi,
Ok, will do.
Is it a temporary fix, or just the way it is suppose to work?

Thank you

**Comment by ericsciple** [comment]
I talked to Ting yesterday. He said when he reproduced the issue, he found that the echo'd line ended with a space (which failed), and then the real line did not end with a space (which succeeded). He's going to update the error message to enclose the failed command in quotes, so at least it's more clear what's going on.

It raises an interesting side question whether spaces should be trimmed for that command or possibly all commands.

**Comment by ericsciple** [comment]
Note, another option would be to suppress echo for that one line in your batch script (prefix just that line with an ampersan).

**Comment by ericsciple** [comment]
~~amersan~~ I mean, at symbol.

**Comment by ericsciple** [comment]
@TingluoHuang fix this. Closing.
