### ISSUE TITLE
Add new task for running NUnit-Tests

### ISSUE THREAD

**Issue by apacha** [Microsoft/vsts-tasks#1725]
Running tests with Visual Studio Test is a great way to execute your tests. Given the right TestAdapters, you can run all different types of tests.
However, when building a Xamarin.iOS app on a Mac with the VSTS Build Agent, there simply is no vstest.console.exe available. 

It would be great if there was a task available, that allows to run nunit-tests via the nunit-console runner.

**Comment by atinb** [comment]
This is on our backlog, but no timeline as of now. I guess this is not blocking as you can run using ShellScript task and then upload results using Publish Test Results?
Thanks!

**Comment by apacha** [comment]
Great to hear. For now, running a ShellScript with nunit-console and Publish Test Results is fine. Thanks!

**Comment by atinb** [comment]
Thanks for confirming!

**Comment by LiohAu** [comment]
Just seen this, after I opened my own issue about the same topic, @apacha @atinb any of you can provide me a sample script that would run nunit tests from the command line (never did that before).

**Comment by wes566** [comment]
I too am trying to get nunit tests run on my mac build agent using terminal, with little success... any sample shell script would be wonderful.

**Comment by LiohAu** [comment]
@wes566 look at this capture : https://github.com/Microsoft/vsts-tasks/issues/1904#issuecomment-227664257

**Comment by atinb** [comment]
@LiohAu 
Thanks! :)
