### ISSUE TITLE
Sonar PRCA: Component is not in the expected format error

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vsts-tasks#1730]
For a certain project I get the following error while running Sonar PRCA:

```
2016-05-16T10:33:55.5812470Z ##********[task.logissue type=error;]Internal error: component NuGetPackage.Addins.SharePoint.Glimpse.Mvc:NuGetPackage.Addins.SharePoint.Glimpse.Mvc:BCB53900-68B7-45C1-B711-ADDFE3149395 is not in the expected format (expected 4 parts)
2016-05-16T10:33:55.5812470Z ##********[task.complete result=2;]
```

**Comment by pascalberger** [comment]
It seems like [this message](https://github.com/Microsoft/vsts-tasks/blob/f82b12dc5b52a056244f15f33e8c6000eb1ac9cc/Tasks/SonarQubePostTest/PRCA/ReportProcessor-Module.psm1#L133), which on hand side expects 4 parts separated by :, but on the other the GUID to be the third part. Is the 4 part check really correct?

**Comment by pascalberger** [comment]
Sonar version is 5.1.2. PRCA works fine for other projects. Special about this project is that it doesn't exist yet on Sonar (it's the PR for the initial version).

**Comment by bgavrilMS** [comment]
Hmm, I suspect this is more to do with the type of project. I’ll try to repro this using a SharePoint app.

Bogdan

**Comment by pascalberger** [comment]
This time no sharepoint project involved :) Just a normal class library.
Let me know what i can do to help with repro
Am 16.05.2016 14:52 schrieb "Bogdan Gavril" <notifications@github.com>:

**Comment by bgavrilMS** [comment]
Oh good, saves me from having to install Sharepoint extensibility ☺. Is there any way you can try the same with the latest SonarQube version? 5.1 is quite old and there were significant changes done in 5.2 and 5.3 – you’ll notice a lot of the task functionality if 5.3+. It’s still a bug of course, we are expecting PRCA to work with the current version and the LTS versions of SonarQube, and LTS is currently 4.x

Bogdan

**Comment by pascalberger** [comment]
Yes, we're planning to update to latest, but might take some time
Am 16.05.2016 17:01 schrieb "Bogdan Gavril" <notifications@github.com>:

**Comment by bgavrilMS** [comment]
One more question Pascal, what C# plugin version do you use?

**Comment by pascalberger** [comment]
C# plugin is 5.2

**Comment by bgavrilMS** [comment]
Hi Pascal, I think I have an understanding of where this is coming from. SonarQube produces a json file with all the issues. There's some rather tedious processing done to it to map an issue to the actual file it belongs to. I think we have a bug in that processing, and it may be related to issues found at the project level and not at the file level. 

To confirm, would it be possible to 

a. repro the bug
b. go to your agent build agent and locate the work directory. For example on my agent it is C:\agent\_work\11 - if there are more numbers there just pick one that was modified last. 
c. There should a sonar-report.json file in C:\agent\_work\11\.sonarqube\out\.sonar 

Could you pick it up and send it to me please? It should contain all the analysis issues and component names, so be sure to sanitize it if you think there are sensitive details. 

My email is bogdan . gavril @ microsoft . com (no spaces). 

Much (!) appreciated!

**Comment by pascalberger** [comment]
Sorry, the email address bounced (550 5.4.1 [x@microsoft.com]: Recipient address rejected: Access denied).

You can get the file content [here](https://gist.github.com/pascalberger/4e391ade3ba481d1c07422e4f7a21ead).

There’re for sure some project level issues reported.

**Comment by bgavrilMS** [comment]
Thank you Pascal. Sorry about the email error, I'll investigate why it's restricted. I confirm the bug comes from the fact that some issues are logged at assembly level and not at file level, such as fxcop:MarkAssembliesWithNeutralResourcesLanguage. We'll look at resolving this as soon as possible, probably by not trying to post them to the code review.

**Comment by pascalberger** [comment]
Thanks Bogdan! 

IMHO best would be to add these as normal discussion comments to the PR. And give comments the possibility to have a state (active, resolved, etc), like file comments. This would also be handy for general manual code review feedback, which is not specific to a line or file.

**Comment by bgavrilMS** [comment]
I'm not sure about the experience in this case Pascal. Since the issues are not tied to a specific file, where should they be added to? If I log them all in some well known place, like the first file in the review, you'd get overloaded with multiple messages referring to different assemblies.

**Comment by pascalberger** [comment]
I meant add a comment not specific to a file. This is currently already possible if you just enter a comment while being on the discussion page. The only point is that these types of comments don't support a state (active, resolved, etc) at the moment.

**Comment by bgavrilMS** [comment]
Thanks Pascal. That's good feedback. We'd like to get a quick bug fix as soon as possible so for now we'll ignore assembly issues. I have checked in a fix to master. 

Few analyzers produce them, I only know of FxCop for C# and FxCop is being deprecated and replace with Roslyn analyzers anyway. We are considering enhancing PRCA, maybe even as a standalone task, so there is a lot of opportunity to improve things.
