### ISSUE TITLE
CopyFiles doesn't exclude any files

### ISSUE THREAD

**Issue by jwhite** [Microsoft/vsts-tasks#1737]
I'm not that fluent with javascript so I can't fix this myself.

I seem to have a report that files are excluded from the copy but they are copied anyways.

Consider the following :

    // apply exclude filter
    for (var i: number = 0; i < excludeContents.length; i++) {
        var pattern = excludeContents[i];
        tl.debug('Exclude matching ' + pattern);

        // let minimatch do the actual filtering
        var matches: string[] = tl.match(files, pattern, matchOptions);
            
        tl.debug('Exclude matched ' + matches.length + ' files');
        files = [];
        for (var j: number = 0; j < matches.length; j++) {
            var matchPath = matches[j];
            files.push(matchPath);
        }
    }

It looks like the locally defined "files=[]" is not used anywhere and then it leaves scope.

**Comment by bryanmacfarlane** [comment]
files is declared well above that function so the observation is not correct.  

https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/CopyFiles/copyfiles.ts#L119
