### ISSUE TITLE
Higher level documentation on task development: Best practices etc...

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vsts-tasks#1747]
I do see that many things did changed since the agent version 1.95 when it comes to build task creation.

I was wondering if there is any document which sums all of the best practices about the creation of build tasks. Seems very hard to find some answers about build task development. At example:

1) PowerShellV3 execution is added. Structuring your ps file is different now. Modules are automatically available, parameters are retrieved in a different way, etc. Moreover it is using the new task library SDK. Is there a tool that will upload our task to TFS/VSTS like tfx cli that will automatically include the necessary modules in our task. Should they be included in the task itself? Etc.
2) TypeScript - Since when is it available? What are the best practices? Is it substituting our node.js scripts? Can they be run also on a non xplat agent? 

You made a lot of changes, improvements, but unfortunately there is not much documentation about it. We already spent consistent amount of time understanding the "old" way of doing things, digging into the tasks code as documentation and peaking into libraries. I was hoping that after such large changes, you will keep all of the developers in loop about new ways, so that we can adapt and make our tasks better. Maybe this is not the perfect place for such questions/rants, but I hope however to get some feedback.

Regards,
Mario

**Comment by ericsciple** [comment]
The docs are here: https://github.com/Microsoft/vsts-task-lib

**Comment by mmajcica** [comment]
@ericsciple obviously that is not enough and doesn't answer to any of my questions. I read that as soon it got available however it is just a list of the cmdlets available in the new sdk. Nothing else.

**Comment by ericsciple** [comment]
I think you have missed some pages.
https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/README.md
https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/Consuming.md
https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/ErrorsWarningsAndTaskResult.md
https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/TestingAndDebugging.md
https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/ReleaseNotes.md

The questions you have here look very similar to the conversation with you on [this issue](https://github.com/Microsoft/vsts-tasks/issues/1264) from Feb 19th.

**Comment by bryanmacfarlane** [comment]
We are adding docs.  I have work scheduled this next sprint to write the high level best practices doc.  What we have right now is an API reference.  We chose to start with that and open source our tasks to get started.  Agreed the higher level docs are needed.

**Comment by bryanmacfarlane** [comment]
I also want to have a "How do I" section with code snippets and pointers to usage in our tasks.

**Comment by mmajcica** [comment]
Hi @ericsciple ,

you are right, we already discussed it, but aside the API reference there is not much more and it didn't changed since then. Basic things as how to package the SDK inside your task, precedence of execution, development tooling, etc. are not covered.
It would be nice that also the community gets some more information about larger refactorings as this one. At the beginning we could learn from the source of the build tasks, but now, due to refactorings on the code base, it is not clear what is the right direction to take and often I end asking myself, why? It will be nice as @bryanmacfarlane points out to have a higher level overview on developement of build/release tasks, which will help us making a more standard and better quality tasks.

**Comment by ericsciple** [comment]
@mmajcica can you help me understand what is missing from https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/Consuming.md regarding how to package the SDK inside your task? That page is entirely about consuming the SDK within your task. There is even a section `Package the SDK with the task` that describes the folder layout.

For that specific question `how to package the SDK inside your task`, specifically what is missing from that document? I genuinely don't understand.

**Comment by mmajcica** [comment]
@ericsciple what is missing is a more detailed guidance on how to. In 'Package the SDK with the task', should we copy the files manually inside our task, the ones that the npm package we installed earlier brought in? You are talking there about the structure in which we should place a folder brought in. Don't we then lose version tracking for the SDK? Isn't there any tool or process that once we try to upload a task (or "compile") and it sees that we have a PowerShell3 execution item, installs this directly (like for dependencies on common modules in the task, when gulp copies the necessary)? You are assuming that who's reading that has a certain background, it may be great for you or people in your team, but for a wider public it may be confusing as it misses several things you do give for granted.
Just to point out, do not take this as an offence or attack at what you delivered. I appreciate what you are doing, especially it is very appreciated the fact that you take time to replay to my and others messages, even if not strictly relevant to the repository in question.
This is an invite for you to share a bit more of information so that you can make life of many a bit easier. It is not simple to cope with so many projects and information these days, and if we can get a bit of help with a more detailed explanations, we will be happier, quicker in delivering and at the end making a better product.

**Comment by ericsciple** [comment]
Per related issue #1558, would be good for high level docs to include an explanation of the filepath input (defaults to system.defaultworkingdirectory and what that means in build/release).

It might also be worthwhile to take a pass through the tasks and make sure they have a consistent tooltip regarding the default value for any file path inputs.

**Comment by ericsciple** [comment]
Also, guidance around how to use the filePath input (e.g. pathSupplied), what scenarios it's optimized for, and Shell Script task pattern when really really knowing whether it's supplied is necessary.

**Comment by ericsciple** [comment]
Also need a mapping of agent version to TFS version, per https://github.com/Microsoft/vsts-agent/issues/339

**Comment by bryanmacfarlane** [comment]
We've started docs for task dev in both ts with step by steps and ps3 lib.

https://github.com/Microsoft/vsts-task-lib

We will add more as we go.
