### ISSUE TITLE
Option to specify which build artifacts to acquire for a release

### ISSUE THREAD

**Issue by phatcher** [Microsoft/vsts-tasks#1749]
I've split the build artifacts into webs and tests as the size of the tests artifact has grown (lots of copies of EntityFramework for example).

We need the tests for the Dev/Test environments so we can perform integration testing, but this becomes less useful for Staging/Prod, but I'm still forced to download an extra 159 MB  each time, slowing the process down

So would be useful to specify the build artifacts that I want for a particular release

**Comment by zechariahks** [comment]
I guess this is already planned by VSTS team as per the user voice entry [here](https://visualstudio.uservoice.com/forums/330519-team-services/suggestions/13396200-only-download-artifacts-required-for-task-executio)

**Comment by bryanmacfarlane** [comment]
I don't believe this is an issue with any of the tasks in this repo.  Re-open if you believe it is.
