### ISSUE TITLE
Web Job deployment support in Azure Web App or Azure RM Web App deployment Tasks

### ISSUE THREAD

**Issue by zechariahks** [Microsoft/vsts-tasks#1752]
As of now, we don't have an option to create web job and configure it in the web App deployment tasks. Is there any plan to include it or should this be handled separately using powershell script? I would like to have a separate task or embed this in web app deployment. I can try creating a task for this.

**Comment by RoopeshNair** [comment]
Supporting webjobs is on our backlog. We are few sprints away from it. For now you need powershell task to accomplish it

**Comment by zechariahks** [comment]
Thank you for the update. We will continue using the powershell until this is implemented.

**Comment by codito** [comment]
Closing this issue since it is already on team's backlog. We will announce when it is available through release notes.

**Comment by kubal5003** [comment]
Can you let us know what is the status of this? Also if it's not ready what is the poweshell task to acomplish WebJob deployment?
