### ISSUE TITLE
Highlight Definition

### ISSUE THREAD

**Issue by simonikmoon** [Microsoft/vsts-tasks#1754]
Agent.NameAgent_15424_VS14AgentVersion:1.83.0_NetFx35Tools:C:/ProgramFiles(x86)\MicrosoftSDKs\\_NetFx35Tools_x64C:/ProgramFiles(x86)MicrosoftSDKs\\Agent.ComplerName150424-VS14Agent.OSWindows_NT

**Comment by bryanmacfarlane** [comment]
Not sure what you're posting here, but that's not an issue with any of the tasks in this repo.  Re-open if you believe it is (and specify which task you're having an issue with)
