### ISSUE TITLE
NuGet Publisher and Packager tasks should be cross-plat

### ISSUE THREAD

**Issue by tomgilder** [Microsoft/vsts-tasks#1756]
Currently the NuGet Publisher and Packager tasks are Windows-only. Would be nice if they were cross-plat.

**Comment by bryanmacfarlane** [comment]
@vtbassmatt can comment.  I believe it's on their radar.

I think it would be nice to be net core cross plat as well with no pre-reqs (not mono).  I think that would fit in nicely with our new xplat net core agent that's going into preview

https://github.com/Microsoft/vsts-agent

**Comment by vtbassmatt** [comment]
It's on our backlog, but I don't know when we'll get to it. For one thing, .Net Core doesn't do pack/push yet.

**Comment by zjrunner** [comment]
On our list for VSTS Packaging still, and closer given our movement of the tasks to node, but not a Dev15 deliverable so removing that tag.

**Comment by zjrunner** [comment]
Copied to our feature backlog (683676) to track with other updates.  We have other tasks to help/drive/fixup dotnet to work with credentialprovider and encrypted credentials, and then we have to figure out how dotnet.exe gets on the agents in a way that the ux decisions make sense to consumers of the common task.  On top of that we have to see if dotnet meets all our scenarios yet or if we'd only make NuGetInstaller xplat to start.  Likely this builds on new toolInstaller logic that will come at some point to the build tasks.
