### ISSUE TITLE
Unsupported build tasks fail silently 

### ISSUE THREAD

**Issue by tomgilder** [Microsoft/vsts-tasks#1757]
If you try to run a task on a build agent that doesn't support it, it fails silently with no output.

**Steps to reproduce:**
1. Create a PowerShell task that requires `"demands": [ "Cmd" ]` in task.json
2. Accidentally leave the demand out (oops)
3. Try to run the task on an OS X build agent

**Expected results:**
Error message that nothing can be executed

**Actual results:**
Silent failure

**Comment by ericsciple** [comment]
@tomgilder which x-plat agent did you experience the silent failure on? The [vso-agent](https://github.com/Microsoft/vso-agent) or the [vsts-agent](https://github.com/Microsoft/vsts-agent)?

**Comment by bryanmacfarlane** [comment]
@tomgilder - were you using the vso-agent (node) or the new vsts-agent that's in preview (better).  I believe the node one only printed to the console/service.  It should give good usable error to the web UI console/log.

@ericsciple - the root problem is it made it's way to an agent and it doesn't have a handler.  I want to make sure the error is "The system you are using is not capable or running: <handler name>".  Even though powershell demand was not in the task, we know the handler is able to be run.  We might want a mapping of handler name to user friendly name (ps3 --> powershell).  

So in this case, the nuget task would have landed on OSX and it would have said it can't run powershell based tasks.

At least that's what I hope happens.  I also want to make sure that the handlers in the new agent has prioritized arrays (like other did) with if defs for platforms.  In other words, OSX better not have ps3 handler in it's preference array.

**Comment by tomgilder** [comment]
@ericsciple @bryanmacfarlane I'm using a hosted macincloud.com build agent, so I assume that's the old vso-agent? 

VSTS says: Agent.Version: 1.999.0

Might be nice if the new agent outputs its version number :smile:

**Comment by bryanmacfarlane** [comment]
I think it advertises Agent.NpmVersion since that agent comes from npm and it doesn't support auto update.  1.999 is a way to bypass server sending update messages.

The new vsts-agent supports auto update across all platforms and therefore advertises version.

mac n cloud folks are currently in the progress of changing over

**Comment by bryanmacfarlane** [comment]
We're tracking this in the agent repo so closing this one

https://github.com/Microsoft/vsts-agent/issues/175
