### ISSUE TITLE
Deployment of app insights web test times out

### ISSUE THREAD

**Issue by philshur** [Microsoft/vsts-tasks#1763]
Since yesterday I don't seem to be able to deploy web tests in any ARM templates, it just seems to hang at this point, eventually times out & causes the deployment to fail.
I get the same issue attempting to deploy the template using powershell to my MSDN Azure account.
Seems I'm not the only one:
[https://social.msdn.microsoft.com/Forums/azure/en-US/6ec0d6b1-56cc-4115-9526-76fd75369770/appinisight-ping-rule-hanging-arm-based-webapp-deployment?forum=ApplicationInsights]

**Comment by RoopeshNair** [comment]
@philshur, are trying to use a specific task in VSTS? Azure Power Shell or Azure Resource Group deployment task? Does it work from command-line?
Please share the task details and logs

**Comment by philshur** [comment]
This problem seemed to go away all by itself.
