### ISSUE TITLE
Setting Credentials parameter on "PowerShell on Target Machine" task

### ISSUE THREAD

**Issue by phklemmensen** [Microsoft/vsts-tasks#1768]
I get the following error when trying to run the "PowerShell on Target Machine" task.
 
##[error]Cannot process command because of one or more missing mandatory parameters: Credential. For more info please refer to http://aka.ms/powershellontargetmachinesreadme

I would like to add that "Credential" parameter but I'm not really sure that it's possible.

**Comment by KrishnaAdityaB** [comment]
@phklemmensen 
Credentials need to be passed in the input fields _Admin Login_ and _Password_.
For security you can declare secure variables and use them with $(var_name) notation in these fields

**Comment by phklemmensen** [comment]
@KrishnaAdityaB 
Thanks for the quick answer.
I guess I must be using an older version of the task because those field are not available to me.

**Comment by KrishnaAdityaB** [comment]
@phklemmensen 
1. If you are using VSTS (visualstudio.com)
    a. If you are creating a new definition:
        you should get the latest UI with these fields.
    b. if you are viewing an old definition:
        please add a new task and delete the old one

2. if you are using on-premise TFS
    please share the TFS version and the scenario you are trying

**Comment by phklemmensen** [comment]
@KrishnaAdityaB 
We are using an on-premise TFS server (version number 14.0.24712.0 (Tfs2015.Update1))

I'm trying to use the  "PowerShell on Target Machine" task to run a PowerShell script located on a machine in a work group separate from the domain where the TFS build agent is running.

I've tried using HTTPS connection (but that currently fails with a certificate revocation check).
So now I'm trying to use plain HTTP connection (with the target machine added to TrustedHosts) but I can't currently do that as I am unable to add the -Credential parameter.

(I've also started to look into creating my own PowerShell script to execute the remote script, but I would really prefer to use the built-in)

**Comment by codito** [comment]
@phklemmensen it's bit surprising, per git history, with 2015 Update 1 you should see an input similar to following:
![remotepowershell input](http://vsts-deploy-guide.readthedocs.io/en/latest/assets/images/concepts-task-machine-input.png).

You may try using [machine group](http://vsts-deploy-guide.readthedocs.io/en/latest/target-machines/#using-machines-hub) with details of target machine. The name of machine group can be provided in `Machines` or `Machine Group` input in the task.

However kindly note that machine groups is not a secure option (please don't use for production machines) and this feature may be deprecated soon. Please consider moving to TFS Update 2 if possible.

**Comment by KrishnaAdityaB** [comment]
@phklemmensen 
I am thinking your build/release definition might be an old one created before update 1.
Can you open the definition and add the task freshly?

**Comment by phklemmensen** [comment]
The task looks like this (just added)

![image](https://cloud.githubusercontent.com/assets/6975783/15539935/ac4f5c9a-2285-11e6-893e-d42fc60259d0.png)

**Comment by phklemmensen** [comment]
@codito the machine group approach is what I am currently using

![image](https://cloud.githubusercontent.com/assets/6975783/15568422/2305f76c-232c-11e6-8103-c9b10bbafc3b.png)

the group is set up like this

![image](https://cloud.githubusercontent.com/assets/6975783/15568489/803d5b0a-232c-11e6-8a0e-c03e3fe5b2bf.png)

**Comment by phklemmensen** [comment]
I'm focusing all effort on geting the HTTPS solution to work so I'm closing this issue. Thank you very much for your help.
