### ISSUE TITLE
SqlServerDacpacDeployment successfully installer, however I cannot see it when then going to use it in the build agent editor

### ISSUE THREAD

**Issue by whit0489** [Microsoft/vsts-tasks#1772]
Does anyone now how you go about contacting the alias RM_Customer_Queries, I'm having issues when installing the SqlServerDacpacDeployment Task, It is reporting successfully installer, however I cannot see it when then going to use it in the build agent editor

**Comment by gregpakes** [comment]
I have the same issue.  Installed successfully into TFS - but task does not appear in the list of tasks.

**Comment by gregpakes** [comment]
I got this working by removing "Preview" from the "visibility" section in task.json.

**Comment by whit0489** [comment]
Thank you @gregpakes, that worked
