### ISSUE TITLE
DSC: Powershell on target machines fails with ParameterBindingException

### ISSUE THREAD

**Issue by sameer-kumar** [Microsoft/vsts-tasks#1784]
In my Release definition, I have a task for **Run PowerShell** on target machine. The powershell script is a DSC **Configuration** file with built-in resource. It used to work fine until I added 2 new mandatory string parameters. Now the task poops out and asks for missing parameters. Even though I specified those in **Script Arguments** section in the format as: 

`-ModulesSourcePath "$(ModulesPath)" -ProvidersSourcePath "$(ProvidersPath)"`

Here, _ModulesPath_ and _ProvidersPath_ are custom environment variables. Powershell task is also part of this environment.

Here is my configuration file:

```
Configuration DeploymentPreRequisites_Configuration
{
    param
    (
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [String]$ModulesSourcePath,

        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [String]$ProvidersSourcePath
    )

    Node ('localhost')
    {
        File CopyProvider
        {
            DestinationPath = "$env:ProgramFiles\PackageManagement\ProviderAssemblies\nuget"
            Checksum        = "ModifiedDate"
            Ensure          = "Present"
            Recurse         = $true
            SourcePath      = $ProvidersSourcePath
            Type            = "Directory"
            MatchSource     = $true
        }
    }
}

DeploymentPreRequisites_Configuration
```

Thanks for your help!

**Comment by codito** [comment]
With `system.debug` variable set to `true` in release definition, can you please check in the log if **Script Arguments** input is resolved correctly with `$(ModulesPath)` replaced as expected?

**Comment by sameer-kumar** [comment]
Yes, I verified and it's there. 
```
##[debug]scriptPath = C:\temp\somepath\Deploy\EnsureModulesAndResources.ps1
##[debug]scriptArguments = -ModulesSourcePath "<src-path>" -ProvidersSourcePath "<dest-path>"
```

**Comment by chshrikh** [comment]
@sameer-kumar  - The powershell on target machine task take the script argument, not the configuration arguments. The way which you are trying will work for a normal powershell script not for DSC script

Solution 1 - Make use of session variable 
Sample DSC script - 
##---------------------------------------------------------------------------------------------------------------
Configuration DeploymentPreRequisites_Configuration
{
    param
    (
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [String]$SourcePath,

        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [String]$DestinationPath
    )

    Node ('localhost')
    {
        File CopyDeploymentBits
        {
            Ensure = "Present"
            Type = "Directory"
            Recurse = $true
            SourcePath = $SourcePath
            DestinationPath = $DestinationPath
        }
    }
}

DeploymentPreRequisites_Configuration -SourcePath $src -DestinationPath $dest

##---------------------------------------------------------------------------------------------------------------

With Powershell On Target Machine task, in UI under deployment section please set the 'Session Variables' as -
$sr='c:\SrcBits',$dest='c:\DestBits'

Solution 2 - Make use of script parameters  
Sample DSC script - 
##---------------------------------------------------------------------------------------------------------------
param
(
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [String]$src,

    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [String]$dest
)

Configuration DeploymentPreRequisites_Configuration
{
    param
    (
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [String]$SourcePath,

        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [String]$DestinationPath
    )

    Node ('localhost')
    {
        File CopyDeploymentBits
        {
            Ensure = "Present"
            Type = "Directory"
            Recurse = $true
            SourcePath = $SourcePath
            DestinationPath = $DestinationPath
        }
    }
}

DeploymentPreRequisites_Configuration -SourcePath $src -DestinationPath $dest
##---------------------------------------------------------------------------------------------------------------

With Powershell On Target Machine task, in UI under deployment section please set the 'Script Arguments' as -
-src 'c:\SrcBits' -dest 'c:\ch-dets'

Regards
Deployment Team

**Comment by sameer-kumar** [comment]
Thanks for pointing me in right direction. It makes sense to me now. I have moved on with solution number 2. Now I'm getting below error:

`SourcePath must be specified if you want to configure the destination directory recursively. Make sure that SourcePath is a directory and that it is accessible.`

I have verified that **Source path** is a valid path on Agent machine and **Destination path** is a valid path on Target node. What I'm missing here?

**Comment by chshrikh** [comment]
@sameer-kumar - is it possible to share the script, also you can print the parameters you passed to script to debug it - like if you are passing args as --> -src 'C:\src' -dest 'c:\dest'
in script at bottom add these line - 
write-verbose "$src" -verbose
write-verbose "$dest" -verbose

**Comment by sameer-kumar** [comment]
```
param 
(
    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [String]$ModulesSourcePath,

    [Parameter(Mandatory)]
    [ValidateNotNullOrEmpty()]
    [String]$ProvidersSourcePath
)
Configuration DeploymentPreRequisites_Configuration
{
    param
    (
        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [String]$ModulesDirectory,

        [Parameter(Mandatory)]
        [ValidateNotNullOrEmpty()]
        [String]$ProvidersDirectory
    )

    Node ('localhost')
    {
        Write-Verbose "ModulesDirectory: $ModulesDirectory" -Verbose
        Write-Verbose "ProvidersDirectory: $ProvidersDirectory" -Verbose

        File CopyOneGetProvider
        {
            DestinationPath      = "$env:ProgramFiles\PackageManagement\ProviderAssemblies\nuget"
            Checksum             = "ModifiedDate"
            Ensure               = "Present"
            Recurse              = $true
            SourcePath           = $ProvidersDirectory
            Type                 = "Directory"
            MatchSource          = $true
        }
    }
}

DeploymentPreRequisites_Configuration -ModulesDirectory $ModulesSourcePath -ProvidersDirectory $ProvidersSourcePath 
```

Then from task UI of RM, I set script arguments
`-ModulesSourcePath '$(System.DefaultWorkingDirectory)\DevIT\drop\Release\Deploy\SharedArtifacts\Modules' -ProvidersSourcePath '$(System.DefaultWorkingDirectory)\DevIT\drop\Release\Deploy\SharedArtifacts\Providers\nuget'`

**Comment by codito** [comment]
@sameer-kumar the paths passed to DSC script are available on `Agent Machine`, they will not be available on the `Target Machine` by default. Copy the files to target machine with Windows Machine File Copy task and provide a local path in script arguments.

**Comment by sameer-kumar** [comment]
Can I specify a network file share for source path instead? If yes, what are the security considerations in that case? Or any other points I have to consider before doing so?

**Comment by codito** [comment]
Yes, network file share should work.

**Comment by sameer-kumar** [comment]
These are the errors I get when I specify a network share path:
```
SourcePath must be specified if you want to configure the destination directory recursively. Make sure that SourcePath is a directory and that it is accessible. CategoryInfo :InvalidArgument: (:) [], CimException FullyQualifiedErrorId :MI RESULT 4
The path cannot point to the root directory or to the root of a net share.
```

**Comment by codito** [comment]
@sameer-kumar when you specify network path, please ensure the share is accessible to `SYSTEM` user. See this stackoverflow [thread](http://serverfault.com/questions/568833/powershell-dsc-copy-from-network-share) for more info.

The simpler option is to use Windows File Copy task to copy the source locally and then provide a local path in DSC.
