### ISSUE TITLE
Stop show warning in vsbuild task.

### ISSUE THREAD

**Issue by ChatRoquette** [Microsoft/vsts-tasks#1795]
How do not display the warning for the vsbuild task ? 

I use Sonar and i will not see the warning like "2016-05-26T06:17:05.4286793Z ##[warning]Microsoft.Naming" in the consol build.

Thx

**Comment by bgavrilMS** [comment]
I don't think there's a way to output those warnings as non-warnings. SonarQube configures the C# compiler to use certain analyzers and those cause the compiler to report code analysis issues as warnings, which SonarQube then captures. 

Could you detail more about your scenario? Is this blocking you in any way?
