### ISSUE TITLE
Release 'Publish Build Artifacts' fails with 'Unable to find container for build'

### ISSUE THREAD

**Issue by sabiori** [Microsoft/vsts-tasks#1796]
Hi, I am trying to publish some test results from the release agent working folder using the task 'Publish Build Artifacts' that I put into my release definition, but it fails with:
##[error]Unable to find container for build: 88

I think 88 is the id of the build that triggered the release.

Interestingly, I have another 'Publish Build Artifacts' in my build definition and that works just fine.

Here is the task setup from my release definition
https://cloud.githubusercontent.com/assets/19437249/15373889/9c929e84-1d3f-11e6-9799-b9ea57103b79.png

And this is all the log output of the task:
Set workingFolder to default: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.99.0\tasks\PublishBuildArtifacts\1.0.30 
##[debug]loading inputs and endpoints 
##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION 
##[debug]loading INPUT_ARTIFACTNAME 
##[debug]loading INPUT_ARTIFACTTYPE 
##[debug]loading INPUT_PATHTOPUBLISH 
##[debug]loading INPUT_TARGETPATH
##[debug]loaded 5
##[debug]check path : C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.99.0\tasks\PublishBuildArtifacts\1.0.30\task.json 
##[debug]set resource file to: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.99.0\tasks\PublishBuildArtifacts\1.0.30\task.json 
##[debug]system.culture=en-US 
##[debug]PathtoPublish=C:\a\1196b1921\requirementsCoverage.html 
##[debug]check path : C:\a\1196b1921\requirementsCoverage.html 
##[debug]ArtifactName=ReqirementCoverage 
##[debug]ArtifactType=Container 
##[debug]TargetPath=\my\share\waverage.feature\waverage_plan_in_traderwebapp_2016_05_18.5 
##[error]Unable to find container for build: 88

Could you help me find out what the problem is?

Or in case this task is not supported in a release definition, is there a way around this? Something like using cUrl or powershell to attach the files to the release using the VSO Rest API?

**Comment by superboum** [comment]
I've currently the same problem : 

```
2016-05-27T20:13:10.1347652Z ##[error]Unable to find container for build: 4234
```
While writing this comment, I've carefully reread our logs and I've seen something strange :

```
 ##[debug]TargetPath=\\my\share\waverage.feature\waverage_plan_in_traderwebapp_2016_05_18.5 
```
And particularly `\\my\share`. I think with both use hosted agents for the build and private agents for the release. I guess that private agents don't upload their artifacts on VSTS but instead on a local machine, via SMB, we have to configure.

I'll try to find where we can change the target machine, and try to see if it changes something :)

**Comment by bryanmacfarlane** [comment]
I think that's a red-herring - the target path is only applicable if artifacttype is share.  if it's container, then it's uploaded to the server and that param is ignored.  If you select share in your tasks, that input will light up and you will have to change it to a valid share name.

Are you failing using this task in a release definition?

**Comment by superboum** [comment]
Yes, I'm failing using this task in a release definition. And it seems that @sabiori has also this problem in a release definition : 
>  Hi, I am trying to publish some test results from the release agent
 
I use "Publish Artifact" in build definitions without any problem

**Comment by bryanmacfarlane** [comment]
Thanks for comfirming.  There is no release agent - just one common agent but there's build and release definitions :)  

Sriram in RM should look into.  Not sure if Ashwini should also take a look since she handles test results.

**Comment by GitHubSriramB** [comment]
Publish Build Artifacts task isn't supported within Release. Unlike Build, RM doesn't store any artifacts along with the release. RM currently can only consume artifacts produced by Build.

**Comment by bryanmacfarlane** [comment]
Doesn't it make sense

**Comment by bryanmacfarlane** [comment]
accidentally closed ...

**Comment by AshwiniChalla** [comment]
You may use publish test results task.

**Comment by sabiori** [comment]
I tried to use 'Publish test results', but it limits me in the types of files I can upload. My release process is generating some html files (status reports) on the target machine after deployment which I would like to attach to the artifacts of the release, just like I can do with in a Build definition.

I think if the 'Publish Build Artifacts' is not supported in a release definition, then it should not appear in the list of tasks you can drag into the definition. 

Is there a VSTS REST API that I can use to upload stuff to the artefacts list of a release?

**Comment by mabead** [comment]
We have the same issue. In the steps of our release definition, we minimally want to attach deployment logs to the release for further troubleshooting in case of failure. I think that this is pretty basic. Jenkins has been supporting it for years, Team Build as well and VSTS build also. I don't see why it does not make sense in RM.

Before switching to RM, we also looked at the capabilities of VSTS RM by looking at the different tasks available. Now, I hear that the tasks that I see may not be available. That's very disappointing...  a basic feature is not there and we have a UI that his misleading in presenting the available capabilities.

What alternative are you proposing to manage log files generated during environment steps?

**Comment by GitHubSriramB** [comment]
We are adding support for uploading any file as part of task execution. This will be supported as a ##vso-command that tasks can invoke (passing the path of the file to upload as parameter). This command will be available to tasks irrespective of whether they run within Build or Release. The files uploaded this way can be downloaded as part of downloading the Build or Release logs.

Build artifacts are however very specific to Build. We do not feel it to be appropriate for Release to produce artifacts. Like I said before, artifacts are consumed by a Release (they get downloaded on the agent and get deployed using tasks). 

In general, we wanted all tasks that work within Build to work within Release as well. That's the reason we didn't hide certain tasks in Release. However "Publish Build Artifacts" and "Copy and Publish Build Artifacts" tasks are expected to work only within Build. These are exceptions rather than the rule. We will update these tasks to fail gracefully with appropriate message when used within Release. 

Hopefully these address your concern.

**Comment by sabiori** [comment]
Sounds good to me. 
It does not matter whether it is available through the artefacts or via the log files.
All I need is easy access to these files /per release/ from the release management website.

**Comment by mabead** [comment]
When you are saying:
> We are adding support for uploading any file as part of task execution. This will be supported as a ##vso-command that tasks can invoke (passing the path of the file to upload as parameter). This command will be available to tasks irrespective of whether they run within Build or Release.

What does a ##vso-command mean? Is it a [logging command](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md)? I guess not... Will we need to create our own VSTS task to invoke the ##vso-task? 

Note that our step that needs to attach some log files is a PowerShell step that invokes one of our script. Will our powershell script be able to call the ##vso-task?

Finally, do you have an ETA for this new capability?

**Comment by GitHubSriramB** [comment]
Yes. We are adding another logging command. This can be invoked from your powershell script like any other logging command we support.

We expect this to be ready in a couple of weeks time.

**Comment by GitHubSriramB** [comment]
We have the command available now
e.g. 
##vso[task.uploadfile]c:\Logs\file.log

**Comment by mabead** [comment]
In case anyone wonders: to view the uploaded file, you have to click on "Download all logs as zip". The uploaded file will be part of the zip.

**Comment by jshwei** [comment]
We also are looking for capabilities of publishing artifacts from release. The case is when we depend on multiple artifact sources, we usually want to massage the two artifact source together and then use the final artifact to deploy to clusters. Thus, we would like to be able to publish from release or otherwise we need to duplicate the massage for each environment

**Comment by GitHubSriramB** [comment]
@jshwei - we don't support publishing artifacts into release as of now. We are considering adding this support going forward. Thanks for explaining scenario where this could be useful.
