### ISSUE TITLE
HockeyApp task fails to upload ipa and dSYM on OSX

### ISSUE THREAD

**Issue by frankbuckley** [Microsoft/vsts-tasks#1797]
We have the [HockeyApp task](https://marketplace.visualstudio.com/items?itemName=ms.hockeyapp) configured to upload ipa and dSYM files from a Xamarin.iOS build in Visual Studio Team Services.

The build completes fine, but the HockeyApp task always results in:

`##[error]Failed to upload the package. Status code = 404, err =
`

We are using the latest vsts-agent version 2.101.0.

Have triple checked API key, etc. Logs indicate ipa and dSYM located OK.

Not sure if this is a HockeyApp or VSTS issue.

[Has been suggested this is a VSTS issue in the past](https://support.hockeyapp.net/discussions/problems/52717-404-error-after-vsts-upload).

**Comment by frankbuckley** [comment]
https://github.com/Microsoft/vsts-tasks/issues/1797

Also reported to HockeyApp: https://support.hockeyapp.net/discussions/problems/57383-vsts-hockeyapp-task-fails-with-404-error-uploading-ipa-and-dsym

**Comment by frankbuckley** [comment]
I have also checked with a Xamarin.Android project and get exactly the same error uploading the apk file.

**Comment by bryanmacfarlane** [comment]
Sriram, can you have someone investigate?

**Comment by frankbuckley** [comment]
**Resolved** - it turns out I was specifying Bundle/Package IDs where a HockeyApp App ID was required.

Not sure if instructions could be clearer? -

![2016-05-26_16-02-34](https://cloud.githubusercontent.com/assets/5655810/15579178/677ee816-235b-11e6-8bd8-8ad01b3fdef4.png)

and if error message when task runs could be more specific?

**Comment by madhurig** [comment]
I updated the string to clarify it is the App ID from HockeyApp, it will be available in the next release of the extension. We are tracking an improvement to be able to query the apps and show the App names in a drop down in the task.
