### ISSUE TITLE
Error in build: "nuget was not found in the path"

### ISSUE THREAD

**Issue by jsauvexamarin** [Microsoft/vsts-tasks#1799]
Error in build: "nuget was not found in the path".

Agent console output: 
https://gist.github.com/jsauvexamarin/aa399160fee2ec7ca62274ab1e67c753

I'm getting this error message both before and after using the `echo $PATH > .Path` command (to make $PATH available for services):
https://github.com/Microsoft/vsts-agent/blob/master/docs/start/nixsvc.md#user-content-using-your-path
(suggested by @bryanmacfarlane )

Agent version (for OS X):
https://github.com/Microsoft/vsts-agent/releases/tag/v2.101.0

Xamarin settings on build agent: 
https://gist.github.com/jsauvexamarin/36262b236800414862aae4cf9cbfff72

**Comment by jsauvexamarin** [comment]
I'm not sure why, but I'm no longer seeing this error message.

**Comment by yacaovsnc** [comment]
I am glad it works now.  This seems to be environment related.  Please reopen if you are still experiencing problems.  

Thanks!
