### ISSUE TITLE
"PowerShell on Target Machine" hangs 

### ISSUE THREAD

**Issue by phklemmensen** [Microsoft/vsts-tasks#1809]
As the last step in my automatic build and deploy I call a PowerShell script on the remote machine to install my website and update my database using web Deploy and our own program (based on DbUp).

When executing this script the PowerShell task hangs newer finishing the build. Is there a specific way that the remote script should be written to signal it is done?

**Comment by mvvsubbu** [comment]
Did you get it working?

**Comment by phklemmensen** [comment]
Hi
Sorry for the long delay. I figured out that the hang was caused by a command line program that was waiting for a user input (Console.ReadLIne specifically)
