### ISSUE TITLE
Testagent Deployment psRemotingexception

### ISSUE THREAD

**Issue by DZiso** [Microsoft/vsts-tasks#1821]
Hey,
we were having some updates on our infrastrukture and expanded our tests pcs and renamed the old ones.

On the same time the TFS got the update From 2 to  2.1.
We got everything up and running again, just the deploy test agent task does not work.

The machines are domainjoined & the used account is a domain account and administrator on the target machine. The credentials are entered in Test/machines/  and  stored in variables in the test task in the format domain\username

Powershell remote/ remote file copy tasks work on the same  target maschine/ buildserver.and with the same credentials.

What diagnostic informations can i help you ? 

The (german) Task log is attached

[2_TestAgent auf Group-B bereitstellen.txt](https://github.com/Microsoft/vsts-tasks/files/293683/2_TestAgent.auf.Group-B.bereitstellen.txt)

**Comment by acesiddhu** [comment]
Hi
Can you add system.debug variable in the definition with value true and then run it again and share the logs again? 
Also does the log say permission denied?
Thanks

**Comment by DZiso** [comment]
Found my issue, there was a space at the end of the username.

This runs with remotePowershell Task and CopyFilesToMachine Task, but not with the Deploy Test Agent Task.

**Comment by acesiddhu** [comment]
Thanks. Will close the thread. We have filled an issue internally to see how all the task behave the same way in such cases.
