### ISSUE TITLE
Capture the output in a variable

### ISSUE THREAD

**Issue by sameer-kumar** [Microsoft/vsts-tasks#1824]
I am using TFS 2015.2 (on-prem) Release Management and Azure automation tasks. 
Can I store a task output value in a variable so that it can be used with downstream tasks? For instance, I have an Azure PowerShell task to create a resource group in Azure. I need to capture the name of this newly created resource group in an output variable so that I can use it on following tasks like Azure Resource Group Deployment. 

Thanks for your help!

**Comment by ericsciple** [comment]
@sameer-kumar Refer https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md

Ctrl+F for all `##vso[task.setvariable]`
