### ISSUE TITLE
CleanTarget for AzureBlob File Copy

### ISSUE THREAD

**Issue by wilsonng** [Microsoft/vsts-tasks#1828]
Hi there, I'm using vso - was wondering if there're any way to clean the target container/ or target folder before copying AzureBlob (not VM) File Copy? thanks a lot!

![untitled](https://cloud.githubusercontent.com/assets/62343/15734982/b7948e76-2849-11e6-9a3c-b2e8913fcd94.png)

**Comment by mvvsubbu** [comment]
Currently this feature is not available, we are welcome for your contributions as well, if you can do it please send a PR. Otherwise we are adding to our backlog we will update you once it is done.

**Comment by RoopeshNair** [comment]
@wilsonng 

We have this on our backlog. However it will be a while before we get to it
