### ISSUE TITLE
Agent Stalling after running Karma test Suite (Hosted Agent)

### ISSUE THREAD

**Issue by RDalziel** [Microsoft/vsts-tasks#1829]
I have a bit of an odd problem where the agent seems to get stuck after it's run the karma test suite with phantomJS. (Note: SingleRun is set to true and this works fine locally)

Could this just be a prompt that is lingering after the task has been run and is not allowing for subsequent tasks to start?

![image](https://cloud.githubusercontent.com/assets/3485935/15737371/96c9dc74-289d-11e6-9289-03fefbfdf95d.png)

**Comment by allendm-msft** [comment]
@RDalziel could you log onto the build agent machine and try running `gulp test` from a commandline. We shouldnt be doing anything different.

**Comment by RDalziel** [comment]
This was on hosted agents, @allendm-msft 

I've since rolled back the version of phantom JS and it doesn't crash the build anymore. However i do just get intermittent failures when trying to run tests (I believe this may just be karma configuration related though).

I had hoped the later versions of Karma and PhantomJS would resolve the issue, and they did. But they have created this new issue.

**Comment by allendm-msft** [comment]
@RDalziel based on the current data it looks like a local issue. If you are using a stable version of your test framework then I would first dig deeper into the test code. Thats where we usually end up finding the true bugs when we see test flakiness.

If there is nothing actionable we should close this issue
