### ISSUE TITLE
PublishTestResults interprets times stamps wrong for xunit v2 results

### ISSUE THREAD

**Issue by fmuecke** [Microsoft/vsts-tasks#1830]
It seems like the timestamps/durations of the xunit v2 xml format are not interpreted correctly.

![vsts-publishresult-xunit](https://cloud.githubusercontent.com/assets/7921024/15737868/af78d9ae-28a8-11e6-8098-f271197c1e47.png)

I am using xunit v2.1 and PublishTestResults task v1.0.21.

Workaround: I could use the xunit visual studio runner adapter and use vstest directly. I still need to check if the problem exists, if xunit uses NUnit style reports.

**Comment by atinb** [comment]
Thanks for the report @fmuecke. We will take a look and get back to you

**Comment by vimegh** [comment]
@fmuecke Will it be possible for you to share the xunit v2 xml file generated for this scenario. It will help us understand what might be causing this issue. Thanks.

**Comment by fmuecke** [comment]
@vimegh I attached a sample file. It is from a xunit test run. The test run should have a duration of about 3 minutes (it contains two database setups - one for TSQL and one for oracle).
[DataLib.zip](https://github.com/Microsoft/vsts-tasks/files/309746/DataLib.zip)

**Comment by vimegh** [comment]
@fmuecke Thanks for sharing the xunit result file. I looked into it, and it seems to work fine in present version that is 1.0.28. I will check in version 1.0.21 and will update here, in the meanwhile It would be great if you can answer following questions:

1. What is the TFS version that you are using?
2. Is it an onprem installation?
3. Are you using xunit.console.exe to run tests? If yes, then are you running the Xunit tests in parallel (assembly level/collection level or all)? Can you share the arguments that you are passing?
4. Can you share a screenshot of Publish Test Result Task definition. I just want to know, if you are using merging test results?
5. If possible, can you also share the logs of the task.

Thanks.

**Comment by fmuecke** [comment]
@vimegh :

1. We are using Microsoft Visual Studio Team Foundation Server Version 14.95.25229.0 (2015 Update 2.1)
2. Yes, it's onprem
3. The tests are executed via the following commandline `xunit.runner.console.2.1.0\tools\xunit.console.exe -quiet -nologo -serialize CoreTests.dll -xml xunit2-Results.xml`
4. The parameters of the publish task are as follows
![publish_results](https://cloud.githubusercontent.com/assets/7921024/16042734/74cbea74-323c-11e6-8ec0-f01c1c0e475f.png)
5. I attached the full log files of a custom build, that reproduces this behaviour
[logs_5624.zip](https://github.com/Microsoft/vsts-tasks/files/313875/logs_5624.zip)

![publish_results2](https://cloud.githubusercontent.com/assets/7921024/16042834/04ed052a-323d-11e6-9f69-92c7d7d0d9ab.png)

**Comment by vimegh** [comment]
@fmuecke Just to update you, I tried reproducing the issue with the result file that you provided but was unable to do so, I am able to see 0.7561767 as test run time for ValidateIncidentRemoval failed test, which is as per the xml provided.
Are you observing this issue intermittently or always?

**Comment by fmuecke** [comment]
That is strange. I can reproduce it every time. 
I'm not quite sure what the cause might be. My build-server is on an English Windows OS but the TFS server might be German. Could it be that this is something locale specific (interpeting the decimal dot as a thousands separator)?
I'll check that on the morrow.

**Comment by vimegh** [comment]
@fmuecke I hope workaround worked fine for you. But can you elaborate more on problem by giving any example, so that i can try reproducing it on my end. Also by current locale, did you meant TFS locale or locale in which test results xml is generated?

**Comment by fmuecke** [comment]
@vimegh First the facts:
- the result files generated by xunit have decimal dots (see screenshot) for the floating point numbers.
![xunit_result](https://cloud.githubusercontent.com/assets/7921024/16447000/9e7c96a2-3dea-11e6-8a62-b7539923ab13.jpg)
- Our tfs server uses German language specific settings which use a commas as decimal separator instead of a dot
![region_settings](https://cloud.githubusercontent.com/assets/7921024/16447205/adf38b9e-3deb-11e6-90a7-ff63c4dcbf4f.jpg)
- After import of the test results the numbers a way too high
- The decimal symbol setting of the build server does not seem to matter
- If I modify the xunit result file so that it contains all commas as decimal symbol the results are correct.

So my theory is that the error happens when the number string is actually parsed. The code seems to interpret the dot in the number string as a digit grouping symbol instead of the decimal symbol - which might actually be the default behaviour for e.g. Double.Parse(string s...). As the input file explicitely uses dots as decimal symbol, the parse function needs to override the default behaviour to correctly parse it.

You should be able to reproduce the issue without changing anything on your test environment - just apply the workaround (replace dots with commas) which should lead to the same result with "normal" settings.

**Comment by vimegh** [comment]
@fmuecke Your theory is almost correct. We are looking into it. We reproduced the issue at our end.

If you use a build agent machine without German language specific settings that is if Build agent machine uses dot as decimal separator, then irrespective of settings as TFS server, results should get parsed correctly on this build agent and should get correctly published on TFS.

Basically, regional setting of user running Build agent or global regional setting of build agent machine should correspond with Xunit result file format. This can also serve as a another workaround for you.

I am assuming that user with which build agent is registered is also having same regional setting (on Build Agent Machine).

**Please Note:** Regional settings get associated with windows user, so do change it carefully. If you are using same user in build agent and TFS, please do check if region settings changes are getting reflected on multiple machines within the network for same user. Though, I am assuming that for TFS server you are using Global policy for regional setting, still mentioning this as a precaution.

**Comment by vimegh** [comment]
@fmuecke Just to update you, this issue has been fixed, and it should be available in next release of TFS, after which you wouldn't require the workaround; I will be marking this discussion as closed.

**Comment by fmuecke** [comment]
Awesome

----- Ursprüngliche Nachricht -----
Von: "Vishal Meghani" <notifications@github.com>
Gesendet: ‎25.‎07.‎2016 19:06
An: "Microsoft/vsts-tasks" <vsts-tasks@noreply.github.com>
Cc: "Florian Mücke" <fmuecke@gmail.com>; "Mention" <mention@noreply.github.com>
Betreff: Re: [Microsoft/vsts-tasks] PublishTestResults interprets times stampswrong for xunit v2 results (#1830)

@fmuecke Just to update you, this issue has been fixed, and it should be available in next release of TFS, after which you wouldn't require the workaround; I will be marking this discussion as closed.

**Comment by axelheer** [comment]
Hm, I'm having quite the same issue with the newest xunit and TFS versions.

The xunit file contains the (culture invariant) dot '.' as a decimal separator, but our build accounts should have the german culture (note: the newer windows versions don't use the dot as a thousand separator but some kind of special unicode character for german users...).

Since the run duration is always zero, I assume the time values cannot be read. (?)
