### ISSUE TITLE
Copy and Publish Build Artifacts: minimatch issue 

### ISSUE THREAD

**Issue by davidjward30** [Microsoft/vsts-tasks#1834]
The "Copy and Publish Build Artifacts" task claims to support minimatch patterns. 

As suggested here:
https://www.visualstudio.com/docs/build/steps/utility/copy-files#ExamplesCopyexecutablesandareadmefile

I am using a mimimatch pattern of the type 
`ConsoleApplication1\**\bin\**\!(*.pdb|*.config)`

to exclude specific extensions. However, if I have a file called

Company.Configuration.dll 

for example, then this also gets picked up by the exclusion clause as it has the string ".config" in it, although not of course at the end of the string as an extension.

Is there any way to achieve reliable file extension exclusion this with minimatch? This would be trivial with a regex!

A colleage of mine called the minimatch library directly through node command line and got the behaviour that I wanted (i.e the Company.Configuration.dll files gets copied). So for some reason the path through the agent appears to be different.

**Comment by davidjward30** [comment]
Re the Q & A. 

> Q: This step didn't produce the outcome I was expecting. How can I fix it?
> This step has a couple of known issues:
> Some minimatch patterns don't work.
> 
> It eliminates the most common root path for all paths matched.
> 
> You can avoid these issues by instead using the Copy Files step and the Publish Build Artifacts step.

Indeed, if I use the Copy Files step and Publish Build Artifacts step, I get the output I want. So please can the "Copy and Publish Build Artifacts" task simply be fixed to do the same thing?

Regards,

David.

**Comment by ericsciple** [comment]
Probably at least a warning should be added. I'll discuss with @TingluoHuang since he knows more history about this task.

**Comment by bryanmacfarlane** [comment]
copy and publish is being deprecated in favor of the copy task and the publish task.
