### ISSUE TITLE
Please add support OpenCover coverage report for Publish Code Coverage Results 

### ISSUE THREAD

**Issue by NikitaEgorov** [Microsoft/vsts-tasks#1859]
Now Publish Code Coverage Results support only:
JaCoCo
Cobertura

Please add support for OpenCover reports https://github.com/OpenCover/opencover

**Comment by atinb** [comment]
You can use a Cobertura converter like [https://github.com/danielpalme/OpenCoverToCoberturaConverter](url) to convert and upload your Code Coverage results. Thanks!

**Comment by agc93** [comment]
@atinb In #657 @gopinathch mentioned there was work planned to support other formats through some form of API. Is this work still planned or do we need to now rely on third-party conversions like the above to publish code coverage?

**Comment by RichiCoder1** [comment]
@atinb Are you taking community contributions on this?
