### ISSUE TITLE
Test certificate (text) in PowerShell on Target Machine

### ISSUE THREAD

**Issue by McMlok** [Microsoft/vsts-tasks#1873]
Hello,

is possible to unify text for parameter TestCertificate in task PowerShell on target machine with text in machine group window where is "Skip CA check" I think skip text is more clearer than "Test certificate". When I set true to testCertificate it skip CA test and false do CA check.

Thanks

**Comment by RoopeshNair** [comment]
@McMlok 

Appreciate your feedback. 
We're deprecating Machine Groups feature under Test hub. Please refer to [RM 2016 H2 Plans](https://blogs.msdn.microsoft.com/visualstudioalm/2016/04/13/release-management-planning-update-2016-h2/). Current investments on test hub machine groups are on priority issues only considering all the other features team is working on

Thanks
