### ISSUE TITLE
Resource messages are not getting loaded from resource.json by default

### ISSUE THREAD

**Issue by nigurr** [Microsoft/vsts-tasks#1874]
Existing task definitions load task related messages from "resource.json" by default.
In CoreCLR agent, it's not loading by default. 

Do we need to explicitly set them? 
tl.setResourcePath(path.join( __dirname, 'abcdef.json'));

**Comment by bryanmacfarlane** [comment]
I thought it was always explicit but eric can confirm

**Comment by ericsciple** [comment]
@nigurr I also was under the impression that it always has been explicitly required by the task to load it's resource strings. Skimming the code of the old Windows agent, I don't see anything special that would cause the resource strings to be loaded.

How sure are you of your statement? What agent are you seeing the behavior (old Windows agent or Node agent)?

**Comment by nigurr** [comment]
@AshwiniChalla can you give them repro?
