### ISSUE TITLE
Docs for creating .appxupload file using the UWP task is wrong

### ISSUE THREAD

**Issue by brainchest** [Microsoft/vsts-tasks#1884]
When using the `Universal Windows Platform` build task the docs (https://www.visualstudio.com/en-us/docs/build/apps/windows/universal) say that one has to use the `UapAppxPackageBuildMode` switch set to `CI` in order to create the `.appxupload` file for store uploads. However, this does not work. Took me a while to figure out that the value of this switch needs to be set to `StoreUpload` instead. The documentation should be updated accordingly. Pls. find more info here:

http://stackoverflow.com/questions/37713237/vsts-build-for-uwp-app-not-producing-a-appxupload-file/37722883#37722883

**Comment by ericsciple** [comment]
Thanks! Fixed.
