### ISSUE TITLE
bug in task RunVisualStudioTestsusingTestAgent

### ISSUE THREAD

**Issue by titans2016** [Microsoft/vsts-tasks#1887]
Hi.
I want report about bug for task RunVisualStudioTestsusingTestAgent.
As far I remembered in first version of tfs 2015 I saw current progress during test run.
For example Total tests: 50. Passed tests 47.
But when we installed last update of tfs and last update taks, we see following log:

DistributedTests: Test run 'XXXX' is in 'InProgress' state.
DistributedTests: Total Tests : 12, Passed Tests : 0
DistributedTests: Test run 'XXXX' is in 'InProgress' state.
DistributedTests: Total Tests : 12, Passed Tests : 0
DistributedTests: Test run 'XXXX' is in 'InProgress' state.
DistributedTests: Total Tests : 12, Passed Tests : 0
DistributedTests: Test run 'XXXX' is in 'InProgress' state.
DistributedTests: Total Tests : 12, Passed Tests : 0
DistributedTests: Test run 'XXXX' is in 'InProgress' state.
DistributedTests: Total Tests : 12, Passed Tests : 0
DistributedTests: Test run 'XXXX' is in 'Completed' state.
DistributedTests: Total Tests : 12, Passed Tests : 0
Some tests in the test run did not pass, failing the task.

Can you please clarify how we can fix this?

**Comment by atinb** [comment]
It used to work the same in 2015 RTM also. Since the tests are running remotely, the results are only updated after each batch of work given to a Test Agent finishes. If you have multiple agents running tests, you will see updates before all tests get executed.
