### ISSUE TITLE
 Azure Resource Group Deployment: Output Variables from ARM Templates

### ISSUE THREAD

**Issue by RDalziel** [Microsoft/vsts-tasks#1893]
How can i get access to Output Variables from ARM Templates in subsequent tasks?

I'm looking to setup an Application Insights Resource via the ARM template then output the instrumentation key for subsequent tasks. Is there a way with the current tasks that i can achieve this?

**Comment by RDalziel** [comment]
I've moved away from trying to manipulate outputs from ARM Templates and just plugged the instrumentation key into the app config (Which can be easily configured in ARM.

Still, would be nice if this functionality was available/clearer.

**Comment by brettjacobson** [comment]
@RDalziel How exactly did you accomplish this?  we're about to face the same problem; I'd wanted to be able to get the iKey if the resource was created and then stuff into our web.config.  This is only an issue if the resource gets created, so are you just bypassing this and manually finding the iKey and checking into your web.config in source control after the fact, to be used on next deploy?

**Comment by RDalziel** [comment]
On Startup i hook up the Key from app settings:

Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration.Active.InstrumentationKey =
                ConfigurationManager.AppSettings["appInsightsKey"];

On the ARM Template i have an AppSettings Component that depends on the AppInsights Setup and hooks up the key from the created App Insights component in a similar way to getting connection strings from Storage/SQL Database etc..

No constant checkins required - Azure Web App Settings take priority over whatever is in the web config so it's all controlled via the arm template.

**Comment by brettjacobson** [comment]
@RDalziel Hmm thanks for the description, but it doesn't make any sense to me.  I'm thinking I haven't done enough of this to understand what you're saying.  But we're actually trying to do this with on premises web sites.  Right now I'm thinking of having an additional PoSH step that "looks up" the iKey for the resource (whether newly created or not), and then manually updates the deployable web.config file to change the AppSetting line where the iKey is utilized.  Will be messy edited the XML web.config file though.

**Comment by RDalziel** [comment]
Ah - replacing the token for On Premise sites is different. My example can all be done in the ARM template because my APP and Insights are created there. But if your APP is on Premise - then yes, you'll need to either write a powershell script to extract the keys from existing resources or add an output to the ARM Template + Run the ARM deployment from a powershell task to extract the outputs. Once you have them in script - you can make them available to other tasks in VSTS.

IT's been mentioned in the past that the'll provide a mechanism to make ARM Template outputs available automatically in build templates, but for now we need to do things differently to access keys etc from Azure Resources.
