### ISSUE TITLE
Run Functional Test task aborts on warnings instead of continuing

### ISSUE THREAD

**Issue by abbottbd** [Microsoft/vsts-tasks#1900]
We have a test assembly that contains methods with the [testmethod] attribute, but the methods accept a parameter.  These methods are not actually 'executed' in the test run, however the run functional test task discovers these and aborts the test run after printing a warning that a teatmethod must not have parameters. The console logs this as a warning, and running from the command line vstest.console.exe logs this same warning but continues to execute the requested tests.  

Run Functional Tests should behave the same way that VSTest.console behaves.  It should log the warning but continue to run the choosen tests.

```
> DistributedTests: Test run is aborted. Logging details of the run logs.
> DistributedTests: New test run created.
> Test Run queued for Project Collection Build Service (TEAM FOUNDATION).
> DistributedTests: Test discovery started.
> DistributedTests: Test Run Discovery Aborted . Test run id : 1401359
> DistributedTests: UnExpected error occured during test execution. Try again.
> DistributedTests: Error : UTA007: Method MyMethod defined in class MyClass does not have correct signature. Test method marked with the [TestMethod] attribute must be non-static, public, return-type as void and should not take any parameter. Example: public void Test.Class1.Test(). Additionally, return-type must be Task if you are running async unit tests. Example: public async Task Test.Class1.Test2()
> DistributedTests: Test run aborted. Test run id: 1401359
> System.Exception: The test run was aborted, failing the task.
```

**Comment by AshwiniChalla** [comment]
Can you share a sample repro project to devops_tools@microsoft.com.

**Comment by AshwiniChalla** [comment]
I tried to repro this problem. Vstest.console have given this warning and exited out without executing tests for me. what version of VS have you used ?

**Comment by abbottbd** [comment]
Thanks,
I found my issue - I had a typo in my filters: TestCatagory instead of TestCategory, however that error wasn't being returned from the build.  Only after a careful visual inspection and trying the same from the command line did I see that the command line fails with an unknown option error, which doesn't show in the build.
