### ISSUE TITLE
multiselect pick list will not work with flat lists

### ISSUE THREAD

**Issue by abbottbd** [Microsoft/vsts-tasks#1901]
When Trying to create a multiselect pick list from a flat list the UI fails to load and instead renders an empty box with the 'manage' buttons even though manage is turned off.

**Comment by prawalagarwal** [comment]
Hi,

Can you please point to your task? One quick check, the properties of your control should declare

properties": {
            "**MultiSelectFlatList**": "True",
            "DisableManageLink": "True"
}

MultiSelect has been replaced by MultiSelectFlatList.

**Comment by abbottbd** [comment]
is MultiselectFlatList available in TFS 2015 update 2.1 for on-prem installs?  When I add this property the task fails to load in the web UI.

**Comment by prawalagarwal** [comment]
Hi, No MultiSelectFlatList is not supported in Update 2.1 This is supported in Update 3 which will be released soon. For update 2 MultiSelect should work.

Can you give some more details on how you are trying to use the control, the API and the contract you are following for this? This control is working in other released tasks on U2.1
