### ISSUE TITLE
Publish test-results does not find multiple test-results on a Mac when using wildcard

### ISSUE THREAD

**Issue by apacha** [Microsoft/vsts-tasks#1904]
When running on a Mac, the publish test-results step currently does not find (multiple) test-results on the disk when using a pattern.

The step is configured with the following wildcard:
$(Common.TestResultsDirectory)/TestResults-*.xml
![screen shot 2016-06-19 at 18 38 28](https://cloud.githubusercontent.com/assets/594497/16178591/10c4d364-364d-11e6-8aff-63e08d58a83e.png)

When executing, the step states: `2016-06-19T16:24:41.4661450Z ##[warning]No test result files matching /Users/alex/VstsBuildAgent/vsts-agent-osx.10.11-x64-2.102.0/_work/1/TestResults/TestResults-*.xml were found.
`
![screen shot 2016-06-19 at 18 34 13](https://cloud.githubusercontent.com/assets/594497/16178578/ce59203e-364c-11e6-961f-45844c655677.png)

Although the files are actually on the disk in the appropriate directory:
![screen shot 2016-06-19 at 18 33 28](https://cloud.githubusercontent.com/assets/594497/16178579/d2d625c6-364c-11e6-89ec-d9636d736c5a.png)

Whereas when providing the path to (one) test-result file explicitly `$(Common.TestResultsDirectory)/TestResults-UnitTest.xml`, the step works as expected.

**Comment by nigurr** [comment]
Hi,

I tried to repro the issue, it's working fine for me. 
![image](https://cloud.githubusercontent.com/assets/15208679/16183288/c54a2e44-36cd-11e6-8a3f-6c73be26692b.png)

![image](https://cloud.githubusercontent.com/assets/15208679/16183295/cf350c76-36cd-11e6-9c7a-fbcf0572a359.png)

Can you let me know the "Publish Test Results" task version number [task.json] will have it

**Comment by apacha** [comment]
It's version 1.0.29.

**Comment by nigurr** [comment]
I tried same thing in Mac, it worked. Can you are dropping the Test files in TestResults folder

**Comment by apacha** [comment]
I am using a command-line step that runs my nunit-tests:

Command: `nunit-console`
Arguments: `$(build.binariesdirectory)/$(BuildConfiguration)/test-assembly/SightPlayer.Ui.Test.dll -xml=$(Common.TestResultsDirectory)/TestResults-IntegrationTest.xml`

![screen shot 2016-06-22 at 08 31 54](https://cloud.githubusercontent.com/assets/594497/16257813/f17b1418-385a-11e6-80fa-8e46999fa403.png)

And as stated above, when specifying the test-results file explicitly, it does work. Only when using the wildcard and checking `Merge Test Results` it fails. Any way to debug this issue on my side?
Have you tried with `Merge Test Results` enabled?

**Comment by nigurr** [comment]
I tried to repro this issue again. Used `ubuntu` agent, but it shouldn't be an issue.

![image](https://cloud.githubusercontent.com/assets/15208679/16552248/20dd08ac-41dd-11e6-8dbc-5efa717eaec1.png)

![image](https://cloud.githubusercontent.com/assets/15208679/16552266/343d54b0-41dd-11e6-9bdf-b106a23d583a.png)

It's successful. Can you try one thing please?
Try to Publish Test Report with `Merge enabled` from `some other directory [`/Users/xxx/someFolder/]`?

**Comment by apacha** [comment]
I've tried to publish the test-results to /users/alex/TestResults and changed the pattern for the Publish Test Results step to `/Users/alex/TestResults/TestResults*.xml`. However, I received the same error message and no test-results were published: `2016-07-04T16:26:54.4090870Z ##[warning]No test result files matching /Users/alex/TestResults/TestResults*.xml were found.`

If the files were not present, why would the step work with the absolute paths given?

**Comment by nigurr** [comment]
@apacha, That's weird. Can you install latest agent and try once. if not, lets have skype call and close the issue. I tried to repro, but it's working without an issue :(

you can drop email to us with skype details: devops_tools at microsoft.com

**Comment by nigurr** [comment]
Ping. There's an alternative way to debug this.

In your build agent machine, you can find `publishtestresults.js` under tasks folder
Open this file and add this line before `tl.ls('-R','/Users/alex/TestResults/')`

You can find documentation about this `lib` here https://github.com/Microsoft/vsts-task-lib/blob/master/node/lib/task.ts

**Comment by nigurr** [comment]
Closing this issue. Please reopen if not resolved
