### ISSUE TITLE
Set-TaskVariable and -Secret switch

### ISSUE THREAD

**Issue by michaeljurek** [Microsoft/vsts-tasks#1905]
I've tried Set-TaskVariable in my build task and it works well.
However, -Secret switch (documented in SDK) seems to be missing, I am getting 

Set-TaskVariable : A parameter cannot be found that matches parameter name 'Secret'.

Microsoft.TeamFoundation.DistributedTask.Task.Common is 15.101.21417.0, signed 17.6.2016

**Comment by ericsciple** [comment]
@michaeljurek Is your execution handler `PowerShell` or `PowerShell3`?

**Comment by ericsciple** [comment]
https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/Consuming.md

**Comment by michaeljurek** [comment]
Thanks for the reply. Actually, I am on yet the way to custom task.
I used "PowerShell Script" task for prototyping the functionality (and plan to re-package to custom task later), it seems to use "PowerShellExe" execution handler.
Anything wrong with that?
Any other way to prototype without deploying the task first?

**Comment by ericsciple** [comment]
I see. The task SDKs are for custom tasks. For ad-hoc scripts you can use [logging commands](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md) (also work from custom tasks).

**Comment by ericsciple** [comment]
To answer your other question, yes you can prototype a custom task without deploying it. See the testing and debugging docs linked [from here](https://github.com/Microsoft/vsts-task-lib/tree/master/powershell/Docs).

The Typescript (Node) lib is similar. [Docs are here](https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/vsts-task-lib.md).

**Comment by michaeljurek** [comment]
I found it counter-intuitive - why I just can't use standard PowerShell cmdlety?
BUT - nevertheless, your advice with logging commands works, thank you
