### ISSUE TITLE
code analysis

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/vsts-tasks#1906]
Is there something for code analysis?

**Comment by nigurr** [comment]
Can you elaborate issue/requirement?

**Comment by jhaamit6666** [comment]
to have code analysed by StyleCop, FxCop, etc. Here is one example: https://github.com/TotalALM/VSTS-Tasks/tree/master/Tasks/Code%20Analysis

**Comment by nigurr** [comment]
@jhaamit6666 we don't have by default. However you can always use user community tasks. 
@atinb can give more details

**Comment by atinb** [comment]
Bogdan can give you more details. See https://blogs.msdn.microsoft.com/visualstudioalm/2016/02/11/use-sonarqube-quality-gates-to-control-your-visual-studio-team-services-builds/

**Comment by jhaamit6666** [comment]
https://github.com/jhaamit6666/VSTS-Tasks/tree/master/Tasks/Code%20Analysis can also be used.

**Comment by bgavrilMS** [comment]
Hi @ranjan-ranjan - we recommend people use the new Roslyn based analysers. FxCop is in the process of being deprecated and replaced with the Roslyn powered: https://www.nuget.org/packages/Microsoft.CodeAnalysis.FxCopAnalyzers/

If you'd like to get a more complex experience based on Code Analysis we recommend you use SonarQube, which we have integrated with the build. More details https://blogs.msdn.microsoft.com/visualstudioalm/tag/sonarqube/

For Java, we are also integrating SonarQube and looking at getting stand-alone analyzers (like PMD and FindBugs) in the mix as well.
