### ISSUE TITLE
Not sure "Take App Offline" is working

### ISSUE THREAD

**Issue by tebeco** [Microsoft/vsts-tasks#1912]
Hi, i'm trying to deploy a WebApp using VSTS "Release" tab in web Portal.
I've tried the default template with the step "Azure Web App Deployment" wich fails with a wonderfull :
"FILE_IN_USE" wich point to the infamous "Take offline" feature that is still to be implemented

So I tried the "AzureRM Web App Deployement (Preview)" Step
I've created the SPN (blablabla ...)
and since I checked "Specific Spot" everytime I load a page on the portal that reference my Release definition I got the wonderfull popup :

`Error(s):

500: Block Helper 'extractResource' not found for expression 'extractResource slots'
TFS.WebApi.Exception: Block Helper 'extractResource' not found for expression 'extractResource slots'
    at d (https://cdn.vsassets.io/bundles/vss-bundle-common-1867691122-vi12yNBMeXLDU4KHScOVXHg==:135:393)
    at https://cdn.vsassets.io/bundles/vss-bundle-common-1867691122-vi12yNBMeXLDU4KHScOVXHg==:135:3268
    at g (https://cdn.vsassets.io/bundles/vss-bundle-common-1867691122-vi12yNBMeXLDU4KHScOVXHg==:135:653)
    at https://cdn.vsassets.io/bundles/vss-bundle-common-1867691122-vi12yNBMeXLDU4KHScOVXHg==:135:3201
    at l (https://cdn.vsassets.io/bundles/vss-bundle-common-1867691122-vi12yNBMeXLDU4KHScOVXHg==:34:8126)
    at https://cdn.vsassets.io/bundles/vss-bundle-common-1867691122-vi12yNBMeXLDU4KHScOVXHg==:34:8352
    at t.when (https://cdn.vsassets.io/bundles/vss-bundle-common-1867691122-vi12yNBMeXLDU4KHScOVXHg==:34:3784)
    at t.u.promiseDispatch (https://cdn.vsassets.io/bundles/vss-bundle-common-1867691122-vi12yNBMeXLDU4KHScOVXHg==:34:2828)
    at https://cdn.vsassets.io/bundles/vss-bundle-common-1867691122-vi12yNBMeXLDU4KHScOVXHg==:34:1653
    at MessagePort.t (https://cdn.vsassets.io/bundles/vss-bundle-common-1867691122-vi12yNBMeXLDU4KHScOVXHg==:34:5777)
Session Id: bdeeb7af-9fa9-4372-beed-a42e00c22b15`

I can still Save & run (same failure)
I also tried to do without specific slot (same failure)

Is there any existing way to deploy a Web App (.net core RC2) on Azure using Release Managment ?

FYI :
It seems that my ResourceGroup is located in WestUs whereas my Resources inside are located in WestEurope (that might be the cause of the error 500)

But can anyone explain why the "take offline" is not taking offline the app ?

**Comment by Ajay-MS** [comment]
@tebeco  Are you still facing above issue ?

**Comment by tebeco** [comment]
I'll try in two/three hour
I'll have to remove custom task from release managment

**Comment by tebeco** [comment]
* It seems to be the same as before,
* I use "Deploy Website to Azure", I did not tried AzureRM this time (Last time i think I tried both)
* I'm deploying on a specific slot (if it help)

I'll see if I can recreate the AzureRM task, i've deleted it instead of disable it -_-'

**Comment by tebeco** [comment]
For AzureRM Deploy :
I still got an issue but my guess is that my configuration is wrong

>2016-08-23T20:11:07.3609898Z ##[error]Error: Source does not support parameter called 'IIS Web Application Name'. Must be one of (). Error count: 1.

the command line looks like :
"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package="C:\AgentPath\_w\r1\a\MySlot\drop\website.zip" -dest:auto,ComputerName="https://MyWebApp-MySlot.scm.azurewebsites.net:443/msdeploy.axd?site=MyWebApp(MySlot)",UserName="$MyWebApp__MySlot",Password=****,AuthType="Basic" -setParam:name="IIS Web Application Name",value="MyWebApp(MySlot)" -enableRule:AppOffline -userAgent:"VSTS_SomeWonderFullIdRemoved_release_1_26_45_1"
 
I can see :
-setParam:name="IIS Web Application Name"

I'm looking where does it comes from and how to "fix" it

**Comment by Ajay-MS** [comment]
@tebeco 

For AzureRMWebApp Task  , in current task you are using there is one issue if you have content zip ( ASP Core ) without parameter file  it will fail since it will not be able to override "IIS Web Application Name" because this parameter is never being declared. You can make it working by adding parameters.xml in root directory of you zip but this solution is just a work around not recommended.

I have fixed this issue as following PR - 
[Parameters file optional](https://github.com/Microsoft/vsts-tasks/pull/2309)

In recent deployments you will be able to get it working without adding parameters file.

second Issue that when you are deploying ASP.NET Core "Deploy Website to Azure" you are facing that some dlls are get locked. This behavior I observed with ASP.NET core first time it get deployed over new website but next time you deploy it complains few dlls are locked. Workaround it stop webapp and then deploy and then start webapp again but I am looking for some better solution will update you as soon as I get solution corresponding to it.

**Comment by tebeco** [comment]
@Ajay-MS 

I'm not sure to understand but it should now work without the XML file ?
I'm still getting
2016-08-25T13:55:51.8785614Z ##[error]Error: Source does not support parameter called 'IIS Web Application Name'. Must be one of (). Error count: 1.

**Comment by tebeco** [comment]
I probably miss configured it

**Comment by Ajay-MS** [comment]
@tebeco  

This will work without XML file it's right but this feature is not yet deployed. so you will not face this issue after build will be deployed ( approx time after one week ).

**Comment by tebeco** [comment]
@Ajay-MS 
Ok for the PR, the override will work, but tell me if i'm wrong you told me that the "SetParameters.xml" should work it I specify it, right ?

Did anything looks bad ?
![image](https://cloud.githubusercontent.com/assets/2266487/18002095/403f7e46-6b86-11e6-82f1-e67dbe6e0a58.png)



Msdeploy is still called like with both:
> -setParam:name="IIS Web Application Name",value="MyWebApp(DevCi)"
> -setParamFile:"C:\Vsts\MyWebApp\_w\r1\a\Dev_CI\drop\MyWebApp.SetParameters.xml"

Full line :
2016-08-26T09:52:02.7640471Z Running msdeploy command:
>"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
> -verb:sync
> -source:package="C:\Vsts\MyWebApp\_w\r1\a\Dev_CI\drop\Main.277.zip"
> -dest:auto,ComputerName="https://AzureScmOfMyWebApp:443/msdeploy.axd?site=MyWebApp(DevCi)",UserName="xxxxxx",Password=****,AuthType="Basic"
> -setParam:name="IIS Web Application Name",value="MyWebApp(DevCi)"
> -enableRule:DoNotDeleteRule
> -enableRule:AppOffline
> -setParamFile:"C:\Vsts\MyWebApp\_w\r1\a\Dev_CI\drop\MyWebApp.SetParameters.xml"
> -userAgent:"VSTS_SomeGuid_release_1_46_85_1"

**Comment by Ajay-MS** [comment]
@tebeco  Yes, it should work.

**Comment by tebeco** [comment]
Ok so the error message is still going on :
>Error: Source does not support parameter called 'IIS Web Application Name'. Must be one of (). Error count: 1.

Funny question :
I can read : "Must be one of ()" why this list is empty ?

**Comment by Ajay-MS** [comment]
Does your setParameters.xml contains 'IIS Web Application Name' parameter ?

**Comment by tebeco** [comment]
@Ajay-MS
I copied and pasted it just above tour post, i've just replaced the name of the azure web app and the slot

**Comment by Ajay-MS** [comment]
Can you email me your  parameters.xml at ajya@microsoft.com , I will explain you complete steps .

**Comment by tebeco** [comment]
@Ajay-MS
Even using :
* parameters.xml <== inside the Zip package at the root level
* SetParameters.xml <== outside & specify it to the Taks in VSTS GUI

Seem to fire the same error
I'll post detail at lucnh here about files contents just like indicated on the mail

**Comment by Ajay-MS** [comment]
@tebeco  As you are unblocked on this issue can i close this issue or you want me to open this till permanent fix of issue get deployed.

**Comment by tebeco** [comment]
You seem confident that the fix is going to make "optional" these two files so I let you choose :
* to close it either now 
* or at the deployment of the update (more accurate if other developer have the same issue)

Thx a lot anyway for the help

**Comment by Ajay-MS** [comment]
@tebeco  - Closing this issue feel free to reopen if you again face.
