### ISSUE TITLE
Publish Test Results always throws a blank warning

### ISSUE THREAD

**Issue by ekumlin** [Microsoft/vsts-tasks#1920]
Any time *Publish Test Results* is executed, regardless of input or result, it always shows a warning. This is thrown [on line 23 of PublishTestResults.ps1](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/PublishTestResults/PublishTestResults.ps1#L23):

    Write-Host "##vso[task.logissue type=warning;TaskName=VSTest]"

Looks like this was removed from an `if` statement in 9a393670, but I don't think that was the author's intent. With this line in place, fully successful builds are detailed as "0 error(s), 1 warning(s)" in email notifications, but there's no actual warnings to investigate, which is causing confusion.

Is there any reason to throw this warning? Can it be removed?

**Comment by nigurr** [comment]
This is been added for telemetry data.

**Comment by kaadhina** [comment]
@ekumlin Which build agent are you using? Is it https://github.com/Microsoft/vsts-agent/blob/master/README.md ?

**Comment by AshwiniChalla** [comment]
Are you using onpremise TFS ? If yes which version?

**Comment by ekumlin** [comment]
@nigurr Why do we have to get a warning in every one of our builds in order for telemetry data to be collected? This is confusing developers; telemetry collection should not be invasive or disruptive.

@kaadhina @AshwiniChalla I wasn't the one to set up the build machines, but the boxes I believe are running the VSTS agent (for Git) version 1.100.5. They are Azure VMs (not onprem boxes).

**Comment by atinb** [comment]
@ekumlin 
We are investigating the issue. There should not be a warning. We are also not able to repro it locally, hence our ask about the versions...

**Comment by ekumlin** [comment]
@atinb Hmm, interesting. It's worth noting that the warning doesn't appear in the build summary (since the text is blank); it appears if you receive an email notification that a build has completed, via VSTS Alerts.

![0 error(s), 1 warning(s)](https://cloud.githubusercontent.com/assets/1350074/16275691/ee9fdc6a-385f-11e6-8c9b-4d648238b1ae.png)

Some additional info: the version of the task (not the agent) is `\tasks\PublishTestResults\1.0.29\PublishTestResults.ps1`

**Comment by AshwiniChalla** [comment]
@bryanmacfarlane  Telemetry infra should have stopped from showing this warning in mail too. any idea what is going wrong?

**Comment by ekumlin** [comment]
@AshwiniChalla @bryanmacfarlane Do we have any update on this?

**Comment by ekumlin** [comment]
@AshwiniChalla Do we have any update on this?

**Comment by allendm-msft** [comment]
This has now been fixed and will be deployed out soon.
