### ISSUE TITLE
Do we have checkbox like we have pickList?

### ISSUE THREAD

**Issue by ranjan-ranjan** [Microsoft/vsts-tasks#1925]
Do we have checkBox like we have pikList?

**Comment by bryanmacfarlane** [comment]
yes, type boolean.  See code coverage enabled in gulp task: https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Gulp/task.json

**Comment by ranjan-ranjan** [comment]
i mean multiple options, not only two.

**Comment by bryanmacfarlane** [comment]
Oh - no we don't.  I can add it to our backlog. 

The only way to sort of do it would be to create a group and in that group have multiple boolean inputs so user could multi-select.

**Comment by ranjan-ranjan** [comment]
kindly add it to backlog.
