### ISSUE TITLE
Python installation directory missing from PATH

### ISSUE THREAD

**Issue by andycodecomplove** [Microsoft/vsts-tasks#1939]
Python 2.7 is installed on the hosted box, but the installation directory hasn't been added to PATH which causes:

> 'python' is not recognized as an internal or external command

And in turn breaks my build.

Why hasn't the installation directory been added to PATH? Will you add it to PATH?

Cheers,
Andy

**Comment by nigurr** [comment]
Try adding manually to Path and see if it helps. I am not sure, prior to Python 3.5, the PATH is auto appended

**Comment by ericsciple** [comment]
@thechrisjohnson - fyi

**Comment by andycodecomplove** [comment]
@nigurr how do I append to path without executing a separate batch file? See my [related issue](https://github.com/casperjs/casperjs/issues/1631) - I want to be able to run a npm script whilst ensuring the task works cross-platform.

**Comment by nigurr** [comment]
Are you using hosted build agent or your own build agent?

**Comment by andycodecomplove** [comment]
@nigurr hosted

**Comment by nigurr** [comment]
Can you try adding "Powershell" task before this and set this path explicitly

```
[Environment]::SetEnvironmentVariable
("Path",$env:Path + $VerifiedPathsToAdd,"Process")
```
FYI: https://msdn.microsoft.com/en-us/library/96xafkes(v=vs.110).aspx

**Comment by andycodecomplove** [comment]
@nigurr I'll give it a try, but won't it only set the path of that current ps session? I need to set it for the machine - I tried something like it before but I needed elevated privileges and it didn't work.

**Comment by andycodecomplove** [comment]
@nigurr I tried the script you suggested, with $VerifiedPathsToAdd equal to ;C:\Python, and it didn't work. I then changed "Process" to "User" and it still didn't work - I got the same error: "'python' is not recognized as an internal or external command". I then changed "User" to "Machine", which I think it should be as its a machine wide change I require, and this time the ps script failed to run: "Exception calling "SetEnvironmentVariable" with "3" argument(s): "Requested registry access is not allowed.""

**Comment by ericsciple** [comment]
@andycodecomplove Tasks run out of process. The Batch Script task offers a "Modify environment" flag that you can use to persist changes to env vars.

Otherwise you could use the task.setvariable command https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md . Although that may be considered a hack, since the command sets a job variable, which happens to be propagated to subsequent tasks as an env variable.

**Comment by andycodecomplove** [comment]
Hi @ericsciple, I'll take a look at the batch task. However, I and anyone else that wants to execute a python script will have to go through this same pain - why is the python installation directory missing from PATH? Will you add it to PATH?

**Comment by ericsciple** [comment]
I talked with @thechrisjohnson . He is going to look into it.

**Comment by andycodecomplove** [comment]
@ericsciple do you have an update?

**Comment by ericsciple** [comment]
@thechrisjohnson ?

**Comment by thechrisjohnson** [comment]
This is being fixed in the latest hosted image, which is being rolled out this week. I will post back on this issue when it's rolled out everywhere.

**Comment by andycodecomplove** [comment]
@thechrisjohnson thanks for the update. Looking forward to it :)

**Comment by bryanmacfarlane** [comment]
The image update went out.  Reactivate if it's not addressed.

**Comment by andycodecomplove** [comment]
It works :smile:. Thanks
