### ISSUE TITLE
Visual Studio Build task can't find packages restored by the NuGet Installer task

### ISSUE THREAD

**Issue by dawilliams** [Microsoft/vsts-tasks#1940]
Build Definition:
NuGet Installer task
- Installation Type = Restore

Visual Studio Build task
- Restore NuGet Packages = Not checked

This was working up until recently.  However recently, the Visual Studio Build task can not find the pacakges restored in the prior step.

**Comment by ericsciple** [comment]
@jascam - fyi

**Comment by kkdawkins** [comment]
Hello @dawilliams ! 

We are assuming that you are using your own private agent pool. We recently issued a hot fix for an issue with NuGet (rolling back to an older version of nuget.exe). We need you to update your agent. This is handled when you reboot the agent, can you try that?

Thanks!
Kevin

**Comment by dawilliams** [comment]
@kkdawkins We are on VSTS hosted build agents.  Does the hot fix still apply to us?

Thanks,

**Comment by kkdawkins** [comment]
@dawilliams Can you look into your build log at the NuGet version? It should be NuGet 3.3. 

We restored back to 3.3 because 3.4 changed the relative repository path within nuget.config was resolved.

**Comment by dawilliams** [comment]
@kkdawkins I'm having trouble finding the nuget version out.  It isn't on the machine path, nor does adding the verbosity or help flag show it for the restore.  Can you suggest any other way?

Thanks,

**Comment by dawilliams** [comment]
Guys,

This appears to be resolved now.  Our VSTS hosted agent is working fine now.

Thanks
