### ISSUE TITLE
[Gradle] defining `$(BuildID)` in the options is not passed to the script

### ISSUE THREAD

**Issue by vbossica** [Microsoft/vsts-tasks#1952]
**Steps to reproduce**

1. specify, in the options of a Gradle wrapper script task, the `$(BuildID)` variable (e.g. `-PreleaseVersion=1.0.$(BuildID)`
2. build the project

**Exepected bahavior**

the value `$(BuildID)` is evaluated

**Actual behavior**

the value is passed as is:

    gradlew -PreleaseVersion=1.0.$(BuildID) clean upload

**Comment by DavidStaheli** [comment]
Instead of $(BuildID), you can use $(Build.BuildID).
