### ISSUE TITLE
Unable to pass secure variables to PowerShell Task

### ISSUE THREAD

**Issue by OliverMartini** [Microsoft/vsts-tasks#1954]
I try to run a PowerShell task which accepts a secure variable (credential:slack-token) as an argument:
I selected the script and set the following arguments:
-SlackToken $(credential:slack-token)

2016-06-24T14:44:47.5095071Z ##[command]& 'C:\a\2f1232ef1\drop\PowerShellScript.ps1' -SlackToken ********

146 
2016-06-24T14:44:47.7625077Z ##[error]Missing an argument for parameter 'SlackToken'. Specify a parameter of type 'System.String' and try again.

As you can see, the SlackToken is provided as argument, visible as ***** in the publish output. But an error is thrown that it has to be specified.
Am I not able to pass secure variables as argument parameter in powershell scripts? What would a good workaround be?

Thanks,
Oliver

**Comment by ericsciple** [comment]
@OliverMartini you may need to add single quotes, e.g. `-SlackToken '$(credential:slack-token)'`

If you run the same command (printed by ##command) from the command line, does it work? Except using the real token value, not asterisks.

**Comment by OliverMartini** [comment]
@ericsciple thanks for your reply. That's exactly what made it work 5min after I posted this issue/question :-) My token, password started with '#'... what are the chances...

Sorry, was not aware that I had this item open. Otherwise I would have posted my solution earlier.

**Comment by Ashish-Jovial** [comment]
What is the solution of this problem, i am also getting the same problem.

Missing an argument for parameter 'pass'. Specify a parameter of type 'System.String' and try again.
