### ISSUE TITLE
how to execute Db Code First Migration on deploying process

### ISSUE THREAD

**Issue by heavenwing** [Microsoft/vsts-tasks#1956]
I want to execute Db Code First Migration on deploying process, just like publish Web project from visual studio with WebDeploy directly.

**Comment by RoopeshNair** [comment]
@heavenwing,

We have this on our backlog. However, we have few other priority fixes for the task pending. It'll take while before we can get to it.

**Comment by rajbalakrish** [comment]
Is there an update here ?

**Comment by RoopeshNair** [comment]
@rajbalakrish  - We now support variable substitution and transformation features in Azure App Service Deploy task and IIS Deploy (Deployment Groups) task. With this you should be able to update the connectionstrings or other variables to desired values. Let us know if you are still not able to run code first migrations.

**Comment by rajbalakrish** [comment]
@RoopeshNair Thanks .. Am reviewing this now :)
