### ISSUE TITLE
Getting "No build code coverage data available" after publishing code coverage results

### ISSUE THREAD

**Issue by chrisseroka** [Microsoft/vsts-tasks#1958]
Hi, I'm trying to publish code coverage results. I generate them manually by running 
```
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Dynamic Code Coverage Tools\CodeCoverage" collect /output:code.coverage dotnet test "test\path_to_unit_tests_project\project.json"
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Team Tools\Dynamic Code Coverage Tools\CodeCoverage" analyze /output:code.coverage.xml code.coverage
```

I added "Publish Code Coverage Results" step and specified:
Code Coverage tool: (I tried both: Jacoco, Cobertura)
Summary file: `$(Build.SourcesDirectory)\code.coverage.xml`
Report directory: (empty)
Additional files: `$(Build.SourcesDirectory)\code.coverage`

The build finishes successfully but I see "No build code coverage data available" in code coverage section. At the same time I see `*.coverage` and `*.coverage.xml` as artifacts.

Do I do something wrong or it is just not possible to fill the report this way?

**Comment by nigurr** [comment]
Can you paste the "Publish Code Coverage" task log in debug mode here

**Comment by atinb** [comment]
Uploading .coverage reports is not supported. One workaround would be to write code to modify the trx file and attach the coverage file to it and then Publish it using Publish Test Results task. Thanks!
