### ISSUE TITLE
Importing AzureRM Powershell module Delay

### ISSUE THREAD

**Issue by sameer-kumar** [Microsoft/vsts-tasks#1963]
Hi,

I’m using on-prem TFS 2015 Update 2 Release Management tasks for Azure integration. I have an Azure Deployment task of Create Update Resource Group. This task takes longer than expected to execute. The first few lines from log are:

```
1.	2016-06-27T16:45:18.8768463Z Executing the powershell script: E:\ReleaseManagerAgents\tasks\AzureResourceGroupDeployment\1.0.55\DeployAzureResourceGroup.ps1
2.	2016-06-27T16:45:26.9328590Z Importing Azure Powershell module.
3.	2016-06-27T16:45:58.4050028Z Importing AzureRM Powershell module.
4.	2016-06-27T16:54:13.3354261Z AzurePSCmdletsVersion= 1.5.0
```

It took approx. 9 minutes to move from line # 3 to 4. Is it acceptable?

 I tried with another task as well like Run Powershell in Azure. Unfortunately it also took similar amount of delay.

Is it just me?

Thanks!

**Comment by ericsciple** [comment]
This might be due to module auto-loading. I recently ported that code and removed the dependence on module auto-loading.

A machine with faster IO would likely bring the time down significantly. We saw similar issues from ps module auto-loading on the hosted build machines before we switched to VMs with faster disk.

**Comment by sameer-kumar** [comment]
It works fine and much faster if I invoke a custom Powershell script on the release agent manually. So auto-loading may not be a issue. I guess it is something inside the VSTS task which takes this unusual time.

**Comment by sameer-kumar** [comment]
Nothing significant with my Disk specific counters like response time, queue length, all graphs looks normal and fine.

**Comment by ericsciple** [comment]
It would be interesting to know if the issue repros for you on VSTS with the Azure PowerShell task. The code has been heavily refactored since then, which won't ship with an on-premises version until the next major version of TFS.

**Comment by sameer-kumar** [comment]
You can mark it as closed. I heard back that its fix is due in next release.
https://github.com/Azure/azure-powershell/issues/2541

**Comment by sameer-kumar** [comment]
Sorry, I know it's been closed. Is there a way you can provide me with refactored code so that i can configure it on my on-prem environment. 

Thanks!
