### ISSUE TITLE
Output Variables not available as $(variables)

### ISSUE THREAD

**Issue by AHoran** [Microsoft/vsts-tasks#1965]
TFS 2015 Update 3.
AzureResourceGroupDeployment Task 1.0.62

[Output Variables](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/DeployAzureResourceGroup#output-variables) here it claims that all Resource Template output variables are now created as variables for later use.
My template has 2 output variables, I can see them in deployment history in Azure Portal. However the variables are not being set in my Release.

```
"outputs": {
        "domainname": {
            "type": "string",
            "value": "[variables('hostDNSName')]"
        },
        "storageAccount_UniqueName": {
            "type": "string",
            "value": "[variables('storageAccount_UniqueName')]"
        }
    },
```

I was previously (TFS 2015 Update 2) using this powershell to collect the variables as the task didn't support. I have disabled this script as it shouldn't be necessary. 

```
$outputs = (Get-AzureRmResourceGroupDeployment -ResourceGroupName $resourceGroup -DeploymentName $resourceGroup | Select -Last 1).Outputs
$outputs.Keys | % { Write-Host ("##vso[task.setvariable variable="+$_+";]"+$outputs[$_].Value) }
```

However even if I do enable this script it doesn't work because the Deployment name now changes on each deployment and I don't know how to get it. Previously the deployment name was the same as the resource group name, now it's something like _template-20160628-0254_

**Comment by AHoran** [comment]
I might be mistaken here, and it could be a different problem that i'm having.

**Comment by AHoran** [comment]
Actually, this is a real problem.

**Comment by AHoran** [comment]
Do you require more information to help diagnose this issue?

**Comment by KrishnaAdityaB** [comment]
@AHoran 

1. Can you modify your script to get things running? 
_DeploymentName_ is optional in _Get-AzureRmResourceGroupDeployment_. We can get all the deployments and then get the latest.
Or Get the resource group by name and fetch the properties you are interested in.

2. I am sorry that the documentation caused confusion for you. The _output variable_ in the documentation doesn't refer to those in the template. It refers to the _Resource Group_ variable in the _Output_ section of the task. This exposes only IP Address and FQDNs. It doesn't expose the output variables from template.

We will see if a task enhancement is needed to support _exposing output variables from template_ in the future.

**Comment by AHoran** [comment]
I had already updated my script as per your recommendation in point 1.

Regarding point 2. I believe that creating variables for all template output variables would be very useful. As you can guess from my example I am creating a storage account with a unique name within the ARM script, and the best way to discover this name and to use it in the rest of the script is via the template output section. I'm sure there are many other use cases related.

**Comment by KrishnaAdityaB** [comment]
@AHoran Thanks for the feedback
@RoopeshNair to consider/comment on the enhancements

**Comment by RoopeshNair** [comment]
@AHoran,

We have added feature to our backlog wherein CSM output  can be set as Task out put variables. However, it will be a while before we can get to it.
