### ISSUE TITLE
gulp test does not run on Linux

### ISSUE THREAD

**Issue by Sachin077** [Microsoft/vsts-tasks#1969]
gulp test runs perfectly fine on windows but it fails with the following error in Linux:
Tests/L0/Maven/_suite.ts(13,21): error TS2307: Cannot find module '../../../Tasks/Maven/CodeAnalysis/analysisResult'.
![err](https://cloud.githubusercontent.com/assets/7456601/16409371/cb5e4126-3d3a-11e6-8f21-61b5f965ca75.PNG)

**Comment by nigurr** [comment]
closing this issue as we all fixed the UTs
