### ISSUE TITLE
SqlAzureDacpacDeployment - BACPAC improvement

### ISSUE THREAD

**Issue by mathieu-benoit** [Microsoft/vsts-tasks#1974]
Hi there, first of all, thank you for providing this very interesting SqlAzureDacpacDeployment vsts task.

Like you mention on the "Know Limitation" part of the README.md file it could be very great to be able to import BACPAC file.
Like you say it looks like it could be easy to integrate: https://msdn.microsoft.com/en-us/hh550080(v=vs.103).aspx with the /a:import, etc.

If I will have some time I will be interesting to contribute to this work, but I'm curious to know how you are thinking about that. What about the name of this task with "Dacpac"? Are you planning to do a more generic task for dacpac, bacpac and sql script by renaming this task? Or create a new one for each individual purpose?

Thank you,

**Comment by RoopeshNair** [comment]
@mathieu-benoit 
Yes, we do want to make it generic. We plan to update current task to handle sql script scenarios. 
Contributions welcome.

Thanks,

**Comment by arangas** [comment]
@RoopeshNair Great to hear that contributions are welcome. I think @mathieu-benoit (and possibly myself) would like to contribute, but how is that to be done? Is there an existing Github issue to cover it? I'm particularly interested in being able to deploy a .mdf file, probably easiest once it's been exported to a BACPAC [using this approach](https://azure.microsoft.com/en-us/documentation/articles/sql-database-cloud-migrate-compatible-export-bacpac-sqlpackage/).
