### ISSUE TITLE
How to automate the deployment steps for Xamarin iOS app -- Fastlane?

### ISSUE THREAD

**Issue by Ali-Syed** [Microsoft/vsts-tasks#1984]
Hi,

I want to automate the deployment for Xamarin iOS app directly to the appstore. Do you we have any steps in VSTS for that? If not, are you planning to add the m anytime soon?

Someone suggested to me that I can have build the project through 'Cake' in VSTS and use fastlane tools like (snapshot, supply, pilot etc) in VSTS to automate the deployment. Can you tell me if its possible? I tried searching for fastlane tools in the VSTS marketplace but was not able to find. I was wondering how can we achieve the automated deployment for iOS app.

Thanks.

**Comment by bryanmacfarlane** [comment]
I believe we have docs.  At a minimum - building the app - not sure about into the app store.  Madhuri can confirm

**Comment by Ali-Syed** [comment]
I am able to build the app and generate the ipa file. I was wondering about the deployment part. 
If we have any steps for that, if not how do you suggest to automate the deployment?

**Comment by madhurig** [comment]
@Ali-Syed: we are currently working on deployment automation that uses fastlane. We are running into an issue that we are working with the fastlane team on. Once that is resolved we will be able to release it. 

Thanks,
Madhuri

**Comment by madhurig** [comment]
@Ali-Syed : We released an extension to automate deployments of iOS apps to the Apple App Store: https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store . Check it out and give us feedback.

Thanks,
Madhuri
