### ISSUE TITLE
Some tests in the test run did not pass, failing the task

### ISSUE THREAD

**Issue by titans2016** [Microsoft/vsts-tasks#1990]
Hi.
I have tests which execute tests on remote test agents (Windows 7). Build definition use test plan. When I execute it shows me:

> DistributedTests: Test run 'XXX' is in 'InProgress' state.
> DistributedTests: Total Tests : 336, Passed Tests : 0
> DistributedTests: Test run 'XXX' is in 'InProgress' state.
> DistributedTests: Total Tests : 336, Passed Tests : 0
> DistributedTests: Test run 'XXX' is in 'InProgress' state.
> DistributedTests: Total Tests : 336, Passed Tests : 0
> DistributedTests: Test run 'XXX' is in 'InProgress' state.
> DistributedTests: Total Tests : 336, Passed Tests : 0
> DistributedTests: Test run 'XXX' is in 'Completed' state.
> DistributedTests: Total Tests : 336, Passed Tests : 0
> Some tests in the test run did not pass, failing the task.

So this task execute during few minutes. If I switch to another test agent, tests execute 100% successful. It means that problem with test agent.

My test agent was update for last version of test agent 2015 Update 3.

On test agent in log file I see next log (part of them):

> V, 2128, 3, 2016/06/30, 13:06:00.247, 48450464367, DTAExecutionHost.exe, TestPluginCache: Updating loadOnlyWellKnownExtensions from False to False.
V, 2128, 3, 2016/06/30, 13:06:00.247, 48450465025, DTAExecutionHost.exe, TestPluginCache: Ignoring the new extensions update as there is no change. Current extensions are 'C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO 14.0\COMMON7\IDE\EXTENSIONS\MICROSOFT\WEB TOOLS\DNX\Microsoft.VisualStudio.Web.UnitTest.TestAdapter.dll'.
I, 2128, 3, 2016/06/30, 13:06:00.247, 48450465524, DTAExecutionHost.exe, Initializing the platform loadOnlyWellKnownExtensions=False, forceX86Discoverer=False.
V, 2128, 3, 2016/06/30, 13:06:00.247, 48450491359, DTAExecutionHost.exe, TestRunRequest.ExecuteAsync: Creating test run request.
W, 2128, 3, 2016/06/30, 13:06:00.247, 48450494509, DTAExecutionHost.exe, TelemetrySession: Error in starting Telemetry for unit test session : Cannot access a disposed object.
Object name: 'it is not allowed to use disposed Microsoft.VisualStudio.Telemetry.TelemetrySession object.'.
V, 2128, 3, 2016/06/30, 13:06:00.263, 48450559431, DTAExecutionHost.exe, TestRunRequest.ExecuteAsync: Created test run request.

So how it's fix?

**Comment by nigurr** [comment]
Can you please post the fresh DTAExecution Host log? Please clear up the file before running the tests.

**Comment by titans2016** [comment]
Hi.
Here link to this log.
[https://1drv.ms/u/s!AvT3p5dgeHiNgQ-DTycg_zrrAm5N](https://1drv.ms/u/s!AvT3p5dgeHiNgQ-DTycg_zrrAm5N)

Thanks in advance.

**Comment by titans2016** [comment]
Also, can you please clarify. If it is required install Visual Studio on test agent for execute coded UI tests?

**Comment by atinb** [comment]
No, Visual Studio is not required on the Test Agent machine. Thanks!

**Comment by nigurr** [comment]
Can you send me your skype details to debug this issue `devops_tools at microsoft.com`

**Comment by nigurr** [comment]
Had offline discussion with customer and closing the issue.
