### ISSUE TITLE
AzureFileCopy - Copy to any WinRM enabled machine?

### ISSUE THREAD

**Issue by AHoran** [Microsoft/vsts-tasks#1992]
It seems that this task expects to copy to VMs that are in Azure and more specifically in the Azure Resource Group. I have an ARM templated deployment that contains a storage account, but my target machine is no in this ARM Resource Group.

I wish to copy files to a machine in AWS (but it could be anywhere I guess). I have separately ensured that WinRM is enabled and configured on this machine.

This task seems to contain all of the components required to enable this scenario, yet it's tying itself into Azure only. I have looked at at the WindowsMachineFileCopy also, but that uses robocopy and seems to try and copy to \\FQDN which won't work as on WinRM port is open on target machine.

**Comment by RoopeshNair** [comment]
Yes this is as per current design,  "Azure File Copy" is scoped to "Azure". We have plan to add generic copy over WinRM at sometime in future.

One option would be, with WMF5.0, You can –ToSession or -FromSession option to copy files over PS remoting sessions. 
For example: 
$remotesess = New-PSSession -ComputerName <computer name>
Copy-Item -Path C:\Source\a.csv -Destination C:\Source\a.csv -ToSession $remotesess
