### ISSUE TITLE
Path separators are mixed for windows vs *nix

### ISSUE THREAD

**Issue by nigurr** [Microsoft/vsts-tasks#1993]
If I use mixed paths in User input path variables, the tasks are failing to resolve the path correctly and thus failing.

This is scenario for most of the tasks where they use "path input" and "find files".

**Comment by nigurr** [comment]
@ericsciple is looking into this issue as per https://github.com/Microsoft/vsts-task-lib/pull/83


I am closing issue from our side as we have bug against our tasks [Ant/Maven/Gradle/VsTest]

**Comment by ericsciple** [comment]
Can you send me the bug? Does it have repro steps?

**Comment by nigurr** [comment]
internal tracking in mseng: 592128

**Comment by bryanmacfarlane** [comment]
Use forward slash in cross platform tasks.  Node will handle correctly in all platforms
