### ISSUE TITLE
Deploy to App under existing Site

### ISSUE THREAD

**Issue by swcarter007** [Microsoft/vsts-tasks#1999]
I am trying to deploy to an application that exists under an existing site, but the deploy task doesn't seem to allow the ability to do that.  Whenever I tried to set the WebsiteName to be the application name, it says site does not exist.  Whenever I tried to set the WebsiteName to be the main website name, it overrides that website instead of creating a subfolder.

**Comment by pascalberger** [comment]
The IIS Web Deploy task is now maintained in its own repository at https://github.com/Microsoft/vsts-rm-extensions. Maybe you should open an issue there.
FYI I asked about the same and got the reply that it is planned (but won't hurt to have it in an issue to track somewhere :)

**Comment by swcarter007** [comment]
I opened the issue in the new repo.  Thanks.

https://github.com/Microsoft/vsts-rm-extensions/issues/56
