### ISSUE TITLE
PublishTestResults Task fails on Linux vso agent

### ISSUE THREAD

**Issue by grawcho** [Microsoft/vsts-tasks#2004]
Publish test results task does not compile typescript to javascript file (missing PublishTestResults.js file on the agent tasks folder) and does not import / copies necessary node_modules for runtime.
I Created a separate task containing the Javascript and the node_modules folder and the publish works fine.

i would like to understand how the agent compiles the typescript file and imports the node modules in runtime Or whether my solution is a valid one (i feel it is not best practice)

**Comment by nigurr** [comment]
@grawcho We internally compile the entire `vso-agent-tasks` and upload the npm package with dependent modules and compiled `js` files. So your `vsts-agent` doesn't compile on the fly.

If you want to patch tasks, you should compile locally and patch the compiled task to your TFS

**Comment by grawcho** [comment]
thanks.
so the issue in fact is that PublishTestResults.js is missing from the uploaded content of the agent tasks on my server (on-prem TFS2015.2)?
if this is the case than i guess my solution will suffice and you should make sure that this file is added (or already added) in future updates.

**Comment by nigurr** [comment]
We don't check in the compiled files as source code. If you look into our Read Me on how to patch tasks, it clearly explains this. Closing this issue now
