### ISSUE TITLE
RunDistributedTests task issue with TestAdaptersPath

### ISSUE THREAD

**Issue by fbouteruche** [Microsoft/vsts-tasks#2014]
Hi,

In the documentation of this task, it indicates that "The task automatically searches for "packages" directory that exists in the same folder as the .sln file (nuget restored directory structure)" but there is not nuget restore on the machine where the distributed tests are run. You must explicity set up the TestAdaptersPath with a runsettings file and copy the TestAdapters dll on the machine.

Can you add a field to set the TestAdaptersPath and avoid the use of a runsettings file please ?

**Comment by atinb** [comment]
Thanks for pointing out the documentation bug. We will fix it.
I have added the feature request to our backlog.
Atin.
