### ISSUE TITLE
BuildPollingException when SVN server is unreachable

### ISSUE THREAD

**Issue by tomkuijsten** [Microsoft/vsts-tasks#2017]
Our SVN server is rebooted over night. Sometimes when I enter the office and open up the build overview page, it's completely red. All builds are failed with the exception found at the bottom of this post. It's a "connection timed out" exception. I do understand that this will be a problem for polling, but I didn't expect it to result as a "fail" build status.

TFS 2015 Update 2
Windows Server 2012 R2

An exception occurred while polling the repository. Error: Microsoft.TeamFoundation.Build2.Server.Extensions.BuildPollingException: Unable to connect to a repository at URL 'https://privateurl/svn/SO/releases/repo' ---> SharpSvn.SvnException: Unable to connect to a repository at URL 'https://privateurl/svn/SO/releases/repo' ---> SharpSvn.SvnException: Connection timed out --- End of inner exception stack trace --- at SharpSvn.SvnClientArgs.HandleResult(SvnClientContext client, SvnException error, Object targets) at SharpSvn.SvnClient.InternalLog(ICollection`1 targets, Uri logRoot, SvnRevision altPegRev, SvnLogArgs args, EventHandler`1 logHandler) at SharpSvn.SvnClient.Log(Uri target, SvnLogArgs args, EventHandler`1 logHandler) at SharpSvn.SvnClient.GetLog(Uri target, SvnLogArgs args, Collection`1& logItems) at Microsoft.TeamFoundation.Build2.Server.Extensions.SvnConnector.GetLogs(IVssRequestContext requestContext, Uri repositoryUri, String sourceBranch, Int64 lastVersionBuilt, SvnConnection connection, Int32 timeoutSeconds, IEnumerable`1& logItems) at Microsoft.TeamFoundation.Build2.Server.Extensions.SvnSourceProvider.<>c__DisplayClass19_2.<GetSourceVersionsToBuild>b__3() at Microsoft.VisualStudio.Services.WebApi.HttpRetryHelper.Invoke(Action action, Int32& remainingRetries) at Microsoft.TeamFoundation.Build2.Server.Extensions.SvnConnector.RetrySvnAction(IVssRequestContext requestContext, Action action, Int32 retryLimit, Int32& retries) --- End of inner exception stack trace --- at Microsoft.TeamFoundation.Build2.Server.Extensions.SvnConnector.RetrySvnAction(IVssRequestContext requestContext, Action action, Int32 retryLimit, Int32& retries) at Microsoft.TeamFoundation.Build2.Server.Extensions.SvnSourceProvider.GetSourceVersionsToBuild(IVssRequestContext requestContext, BuildDefinition definition, List`1 pathFilters, Boolean batchChanges, String previousVersionEvaluated, Dictionary`2& ciData, String& lastVersionEvaluated) at Microsoft.TeamFoundation.Build2.Server.Extensions.BuildPollingJobExtension.Run(IVssRequestContext requestContext, TeamFoundationJobDefinition jobDefinition, DateTime queueTime, String& resultMessage).

**Comment by ericsciple** [comment]
@jeffyoung @AlexRukhlin fyi

Closing. Not an issue with this repo. Refer to this page to open a bug: https://www.visualstudio.com/en-us/docs/build/troubleshooting#i-need-more-help-i-found-a-bug-i-ve-got-a-suggestion-where-do-i-go

**Comment by DavidStaheli** [comment]
By the way Tom, the right people have seen your comment and we want to address this.  Currently, these failed builds are the mechanism for making people aware that the polling failed.  We've talked about disabling the build trigger (polling) after a number of failed attempts so that they don't pile up.  Your feedback and ideas would be welcome!  Feel free to email me at dastahel at microsoft.
