### ISSUE TITLE
DistirbutedTest 'aborted'

### ISSUE THREAD

**Issue by elamine** [Microsoft/vsts-tasks#2020]
Hi, i'm trying to run functional test from tfs, a coded ui test, i've tried before with tfs 2015 update 2/ agent update 2 / win 7
but i always have this message "Failed to obtain durationInMs field."
untill i tried a solution given by another member, which is to use the TestAgent RTM Agent.
but when i tried to run tests as Test Plans and not assembly the bug happened again.
i'm now using the update 3 version but getting the same problem
could you help please 
thank you
config : 
Visual Studio Team Foundation Server 2015 - Version 14.102.25423.0  (update 3)
Test Agent  Update3 14.0.25420.1
Test machine OS version  - tried  win7 and win8

DistributedTests : La série de tests '8885' est à l'état 'Aborted'.
DistributedTests : Nombre total de tests : 1, tests réussis : 0
DistributedTests : La série de tests a été abandonnée. Journalisation des détails des journaux d'exécution.
DistributedTests : Une nouvelle série de tests a été créée.
Série de tests mise en file d'attente pour Project Collection Build Service.
DistributedTests : Test discovery started.
DistributedTests : Test Run Discovery Completed . Test run id : 8885
DistributedTests : 1 test cases discovered.
DistributedTests : Test execution started. Test run id : 8885
DistributedTests : UnExpected error occured during test execution. Try again.
DistributedTests : Error : Une ou plusieurs erreurs se sont produites.--->Failed to obtain durationInMs field.
DistributedTests : Test run aborted. Test run id: 8885
System.Exception: La série de tests a été abandonnée. Échec de la tâche.
******************************************************************************
Tâche de finalisation : RunVisualStudioTestsusingTestAgent
******************************************************************************
System.Exception: Échec de la tâche RunVisualStudioTestsusingTestAgent. Ceci a entraîné l'échec de la tâche. Pour plus d'informations, voir les journaux de la tâche.
à Microsoft.TeamFoundation.DistributedTask.Worker.JobRunner.Run(IJobContext jobContext, IJobRequest job, IJobExtension jobExtension, CancellationTokenSource tokenSource)
Le processus de travail Worker-a4fe9eab-fb43-4a60-bf35-62f75412b499 a fini d'exécuter le travail a4fe9eab-fb43-4a60-bf35-62f75412b499
******************************************************************************
Finalisation de Build
******************************************************************************

[DTAExecutionHost.txt](https://github.com/Microsoft/vsts-tasks/files/348100/DTAExecutionHost.txt)

**Comment by atinb** [comment]
Please see issue #1463. This happens when there is a corrupt install of the Test Agent on the machine. we recommend you uninstall the test agent, delete the folder C:\Program Files (x86)\Microsoft Visual Studio 14.0 (assuming test machine has only test agent installed and no VS is installed) and then use the Deploy Test Agent task to automatically download and install the right agent for you.
Thanks!

**Comment by elamine** [comment]
i tried first to uninstall the agent and delete the folder, it doesn't change anything, I've even tried with a new WIN8.1 Virtual Machine completly fresh, with an automatic download for the deploy test agent task, but still have the same problem. Any other Idea ?
thanks

**Comment by vimegh** [comment]
@elamine In order to understand the problem further can provide following information to me:

**Comment by elamine** [comment]
1- In Test Agent Machine: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.TestService.TcmTestResultPublisher.d

 14.98.25331.0

In TFS server: C:\Program Files\Microsoft Team Foundation Server 14.0\Application Tier\TFSJobAgent\Plugins\Microsoft.TeamFoundation.TestManagement.Server.dll

14.102.25423.0

thank you

**Comment by elamine** [comment]
Finally It worked by installing the English Language Pack on the Test Machine which was originally French. It's working  but it means that is not possible to run tests on different environments, I think there is a bug somewhere...

**Comment by vimegh** [comment]
Thanks Elamine for sharing that information, it seems helpful. We tried with normal en-US machine earlier and it was working, I will try again with French machine and will update.

**Comment by vimegh** [comment]
Just to update you, we are able to reproduce the problem with french OS machine, and are working on finding the resolution.

**Comment by elamine** [comment]
Thank you Vishal for updating, I'll be happy to be informed about the results

**Comment by harshac-ms** [comment]
Hi Elamine, we have identified the issue and fixed it. It will be available in next deployment.

**Comment by elamine** [comment]
Hi Harshac, thank you for keeping me informed, please feel free communicating me any other related information in the future.

**Comment by dremond** [comment]
Hi all,

I have exactly the same problem (tfs 2015 update 3 on prem and clean test machine with agent 2015 update 3 with french windows 7 os)

Can you please give us some information about the next deployment. 
I've tried to execute the latest version of the RunDistributedTests and it failed with the same error.

Can you provide us a fix to deploy or give us the fix availability

Thank you
David

**Comment by persnow** [comment]
> Finally It worked by installing the English Language Pack on the Test Machine which was originally French. 

Where can I found this english package? For windows ou agent?
