### ISSUE TITLE
"Run functional tests" tasks. Video is not recorded

### ISSUE THREAD

**Issue by lopeg** [Microsoft/vsts-tasks#2032]
Hello
We are using "Run functional tests" tasks to run UI tests
Now we need to enable video recording of failed tests. Due to Microsoft recommendations we created and connected to task a testsettings file (Attached).
Locally video is being recorded with this file, but via build definition - it does not work

[Local.zip](https://github.com/Microsoft/vsts-tasks/files/350169/Local.zip)

**Comment by lopeg** [comment]
No errors, but  Video is not uploaded, video is not saved locally as well
testsettings file seems to be ignored by tfs
Locally (on my pc) it works ok

**Comment by tanvi-soni** [comment]
Can you share your tfs build logs with us.

**Comment by kardinal3000** [comment]
I have the same issue. I dont know how I can turn on recording my "code UI tests" The video is not being uploaded with the test results. I can see only *.trx files and screenshots *.png. Maybe you have a some tips about What should I do for get the video file? 
I will be very grateful if you help me.

**Comment by atinb** [comment]
Can you please send the build logs to devops_tools at microsoft dot com? Thanks!

**Comment by kardinal3000** [comment]
@atinb Sorry, but I did not understand what the "build logs" do you mean? in my build definition I  have 4 steps: Build *sln, Publish artifacts, DeployVisualStudioTestAgent, RunDistributedTests. Send the all build log to **devops_tools at microsoft.com**?

The main aim of that issue, I want to know how can I manage the mechanism  make video for my **"codedUITests"**. Where I can read about it? Specifically in my case with the new vNext system I want to see test results with  attachments *.trx,*png, ***.wvm** (video format)

**Comment by atinb** [comment]
Are you using TestContext.AddResultFile to link the video file to your test? If not, can you try doing that? (https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.testtools.unittesting.testcontext.addresultfile.aspx)

**Comment by kardinal3000** [comment]
@atinb  Yes, we are using "TestContext.AddResultFile". Unfortunately I don't see video file in my attachments. I don't understand how can I turn on make video file.  Sorry, maybe I don't have enough knowledge. Sometime ago, I used this [**article**](https://msdn.microsoft.com/en-us/library/dd286596.aspx) but it works for (xaml) MTM.
vNext - I tried to modify [**runsetingfile**  ](https://msdn.microsoft.com/en-us/library/ee256991.aspx)- didn't help

**Comment by vimegh** [comment]
@kardinal3000 Ideally, if video recording is specified in datacollector, then it should get uploaded to TFS. In order to understand the real issue here, we would be requiring build agent and test agent logs. Can you please do following:

Set variable system.debug=true in your build definition in TFS. 
Also, in Test Agent machine take a backup of C:\\DtaLogs folder and delete the folder.
Now Run your build definition and please provide us following logs:
1. After run, goto your build and click on "Download all logs as zip" and provide that zip file to us.
2. In Test Agent Machine, provide logs generated in C:\\DtaLogs folder

**Comment by kardinal3000** [comment]
I checked back my  C:\DtaLogs\DTAExecutionHost.exe.txt. I found a lot of messages 

> "ScreenCapture.wmv with description Screen capture video". 

But any of them weren't  added in  attachments test results.
also I found 

> DefaultTestRunEvenHandler.GetRunAttachmentsWithTrx : Adding trx file C:\Users\USer\AppData\Local\Temp\TestResults_3c7a1fa4-6c81-42ee-8bf1-bdb6b8c93e2f\USer_WIN-VM 2016-07-26 04_41_07.trx to run attachments

> Cleanup.Run : Deleting results directory : C:\Users\USer\AppData\Local\Temp\TestResults_3c7a1fa4-6c81-42ee-8bf1-bdb6b8c93e2f


C:\DtaLogs\DTAExecutionHost.exe.txt.
[Logs.txt](https://github.com/Microsoft/vsts-tasks/files/383640/Logs.txt)

**Comment by kardinal3000** [comment]
Thanks a lot guys for your assist. You do a great work. We can close this issue. I was looking in the wrong place.  I found wmv files in attachment in each test case. :)

**Comment by Selvaraj1989** [comment]
Hi,
I have created .testsettings file with **Video Recorder and System Info** and pointed it to "Run Settings File" in Run Functional test task. I am able to see the "SystemInformation.xml" attached to the test result of the test case. But i am not able to find the video recording either in the test result as well in the test case.

Please help me to find where the video is located.

Thanks in advance
Selvaraj C

**Comment by LokiMidgard** [comment]
I have the same problem.
```SystemInformation.xml``` is created but the video is missing.
