### ISSUE TITLE
Publish test results task links tests with build but not release

### ISSUE THREAD

**Issue by sshumakov** [Microsoft/vsts-tasks#2033]
Hello,

I am using VSTS task to publish build results during build and release process.

The publish during build process works just fine, but release process associates tests with the build which triggered release, not the release itself.

It would be nice to have those tests associated with both: release and build to better see testing applied during certain release flow.

Is there a way to fix it?

**Comment by allendm-msft** [comment]
Hi @sshumakov 
I tried this with the vstest task and the publish test results task on my vsts account and was unable to repro.

Can you share more details on the task that you are using and the input parameters for the same?

**Comment by sshumakov** [comment]
Hi Allen,

We use publish test results with cmd which runs xunit tests on dotnet core.

The steps are the following:
1. Run cmd which runs tests and outputs report files in xunit format
2. Run Publish Test Results task which publishes previous reports, params are:

- Test result format: Xunit
- Test result files: $(System.DefaultWorkingDirectory)\our_project_name\TEST-*.xml
- Merge Test results: yes
- Test Run Title: our title
- Platform: any cpu
- Configuration: release
- Upload Test Attachments: yes
- Enabled: yes
- Continue on error: yes
- Always run: yes
- Timeout: yes

Do we try to associate task with build or release or both? For me build association works fine, just release has this issue.

**Comment by prawalagarwal** [comment]
Hi Sergii,

We are looking into this issue and will get back to you with the findings. Thanks.

**Comment by prawalagarwal** [comment]
Hi Sergii,

This issue is fixed with the latest core-clr agent. Are you using some other agent? Can you verify your scenario now?

**Comment by sshumakov** [comment]
Hi Prawal,

I confirm that this issue has been fixed and I see results of tests associated with release.

Is there any way to configure task to associate test results with both: build and release?

**Comment by prawalagarwal** [comment]
Hi Sergii,

Currently you cannot associate test results with both build and release. Thanks for verifying.

**Comment by himanshubshah** [comment]
Hi Prawal, 

For the on-prem tfs, should we expect fix to be available with upcoming tfs "15" release. Test results are not getting associated with Release. We are on on-prem tfs 2015 update 2.

**Comment by prawalagarwal** [comment]
Hi @himanshubshah ,

Yes the fix will be available in Dev15 release. For now you can also try using the latest core-clr agent with your server.
