### ISSUE TITLE
Couldn't initiliaze test case and test data

### ISSUE THREAD

**Issue by vicky6nov** [Microsoft/vsts-tasks#2035]
Why it is looking in my user specific folder even though I have given proper target folder where I have copied my binaries.

Assert.Inconclusive failed. Couldn't initiliaze test case and test data. Error message: 'C:\Users\vsrivastava16\AppData\Local\Temp\UI\UIControls.xlsx' could not be found. Check the spelling of the file name, and verify that the file location is correct. If you are trying to open the file from your list of most recently used files, make sure that the file has not been renamed, moved, or deleted.

**Comment by atinb** [comment]
@vicky6nov 
Which task are you using to run the tests? Does it work if you directly call into vstest.console.exe with the binaries?

**Comment by vicky6nov** [comment]
We have made it work while changing our app.config file and provincial no
input file path as as absolute path.

Still I want to use relative path instead of absolute. How can it work with
relative path?

**Comment by atinb** [comment]
This seems to be the same issue as #1638. We are considering our default working directory to be %temp% instead of the folder specified in the task. Opened a bug to track on our side.

**Comment by Manmp** [comment]
I am still facing the same issue. Can you please let me know if any workaround?
