### ISSUE TITLE
error : iOS code signing key 'Business Name, Inc.' not found in keychain

### ISSUE THREAD

**Issue by CCooperBH** [Microsoft/vsts-tasks#2040]
In `xcode-task-utils.js` `function determineIdentity(input)` calls `function removeExecOutputNoise(input)` which removes commas from the certificate identity. 

The problem arises because Apple forces businesses to use their legal entity name for the iOS enterprise developer program. So, a business named "Business Name, Inc." will get the following error: `/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.Common.targets: error : iOS code signing key 'Business Name, Inc.' not found in keychain`.

**Comment by madhurig** [comment]
@CCooperBH: Thank you for reporting the issue, we are moving away from these scripts. I will ensure we fix this in the next version.

**Comment by madhurig** [comment]
Fix is in: https://github.com/Microsoft/vsts-tasks/pull/2021

**Comment by madhurig** [comment]
Fix has been deployed to Team Services, please let us know if you still see any issues.
