### ISSUE TITLE
Run Functional Test/Test Agent Deployment fails

### ISSUE THREAD

**Issue by huserben** [Microsoft/vsts-tasks#2046]
Hi

I'm having issues using the Test Agent Deployment/Run Functional Test Tasks.
I earlier had problems as well (https://github.com/Microsoft/vsts-tasks/issues/1483) and the answer was that it will be fixed as soon as we update our TFS to 2015 Update 2.

So we did, but still we have problems.

Following is the setup:
We have a TFS 2015 Update 2 on prem and as well a build agent that runs on a server that is on premises. We run the build agent with a service account that is part of our domain.
Then we have virtual machines were we want to run UI Tests on with the "Run Functional Test" task.
These VM's are not part of our domain and only have one admin user. I think this was the problem why it was not working before TFS update 2, but I can't get it to work now either.

It seems like that during the "Visual Studio Test Agent Deployment" Task it tries to configure the test agent and there are some errors. Now I was not sure if/where I have to put credentials from our domain to access TFS?

Thanks for your help

I attached the DTAExecutionHost which shows some more details.

[DTAExecutionHost.exe.zip](https://github.com/Microsoft/vsts-tasks/files/354337/DTAExecutionHost.exe.zip)

**Comment by nigurr** [comment]
In the attached log, there are not any concerning errors.
Can you remove the existing log and run the DTA flow and paste the full log in case of any error

**Comment by huserben** [comment]
Hi

so these lines in the log are normal:
   DTAExecutionHost.exe, Communicating to the Token Servicehttp://<url.of.tfs>:8080/tfs/PSAC_RD
   DTAExecutionHost.exe, Service task failed. Retry attempt 10.

I will run the tests again as soon as I'm in the office.

Thanks for your help

**Comment by huserben** [comment]
Hi there

so i ran again the tests and following was shown after some time on the VM:
![vm-state](https://cloud.githubusercontent.com/assets/5486874/16721695/74270382-4741-11e6-838e-dd4cceda6645.PNG)

I aswell attached the logs.
So it detects my one test that fits to the filter criteria, but I think it is not run (on the TFS, I get now since some minutes only: 
DistributedTests: Test run '985' is in 'InProgress' state.
DistributedTests: Total Tests : 1, Passed Tests : 0
[DTAExecutionHost.exe.log.txt](https://github.com/Microsoft/vsts-tasks/files/356548/DTAExecutionHost.exe.log.txt)

**Comment by huserben** [comment]
Hello
Just a little update on that issue. I did reinstall the OS on the VM and then tried again. That seems to have fixed the issue, so probably it was something that was misconfigured before (maybe because I tried as well earlier to run the tests before we updated TFS to 2015 Update 2).

Anyway thanks for your support.
