### ISSUE TITLE
Copy to share from Linux

### ISSUE THREAD

**Issue by bbusacker** [Microsoft/vsts-tasks#2049]
How can you tell which tasks are targeted for which environments?  I can get the Publish Build Artifacts task to work if I first mount the file system where I want to copy the files.  I always get and error that I have to ignore because the task trys to associate a UNC path \\server\drop folder but the I wasn't able to specify it that way on Linux so it fails.  Thanks for any feedback.

Brandon

**Comment by ericsciple** [comment]
It sounds like a bug in the task. Can you paste the error? It sounds like the copy succeeds, and the error is only when linking the artifact.

**Comment by renevanosnabrugge** [comment]
Same error here. When calling the function tl.command("artifact.associate", data, targetPath); it throws an error 
2016-07-11T14:03:20.6707550Z ##[error]Unsupport artifact location: /home/XXXXX/myagent/_builds/56
2016-07-11T14:03:20.6812800Z ##[error]Unable to process command ##vso[artifact.associate artifacttype=filepath;artifactname=DROP;artifactlocation=/home/XXXX/myagent/_builds/56;]/home/XXXX/myagent/_builds/56 successfully.

When commenting out this line, it succeeeds.  Same goes for the Copy and Publish Build Artefact..

**Comment by bryanmacfarlane** [comment]
@renevanosnabrugge - we need agent version.

Does it work if you do a server drop?

@bbusacker - writing to a UNC share in Linux will be problematic.  You need to mount, map and get the inputs correct.  Does a server drop work?

**Comment by bbusacker** [comment]
I believe publishing back to source control will work (server drop).   I understand UNC shares work on Linux but need to be mounted.  So my question really is what are the proper inputs for this task to be able to copy files to a file server drop location or mount loation using this task?

**Comment by bryanmacfarlane** [comment]
Server drop doesn't go back to source control.  It goes to our file container service which is backed by azure blob service in VSTS and the DB in on-prem

Can you provide your inputs that didn't work?

**Comment by bbusacker** [comment]
Path to Publish: $(build.artifactstagingdirectory)
Artifact Name: drop
Artifact Type: File Share
Path: $(agent.builddirectory)/Builds/$(Build.DefinitionName)/$(Build.BuildNumber)

I mounted my drop location at $(agent.builddirectory)/Builds.   Of course the task expects a network accessible path which what I've specified is not and fails.  To workaround the issue I've just just checked continue on error. 

I also tried using \\machinename\share but Linux doesn't understand that syntax.  Doing this causes the association part to work but the copying part fails.

Is there some other syntax for specifying a network path in Linux that the task understands?   smb://?  cifs://?  or //machinename/share?

**Comment by bryanmacfarlane** [comment]
Can you copy files to that mounted share via the cmd line fine?

**Comment by eugenebruk** [comment]
I'm trying to run a build on Linux agent. I have mounted Windows share on Linux, and can read the content fine, The files got copied successfully from Linux to Windows, but the association task still failed (see output below). Agent version is 2.103.1, OS is Linux RHEL Server 7. I tried putting smb:// prefix in front of /dfs/..., but that didn't help.
Thanks!

2016-07-22T20:25:54.8691980Z ##[error]Unable to process command '##vso[artifact.associate artifacttype=filepath;artifactname=drop;artifactlocation=/dfs/tfsdrop/SCM/CrossPlatformTest/112722;]Associating artifact' successfully. Please reference documentaion (http://go.microsoft.com/fwlink/?LinkId=817296)

86 
2016-07-22T20:25:54.8699910Z ##[error]Unsupport artifact location: Associating artifact

87 
2016-07-22T20:25:54.8710170Z ##[debug]System.Exception: Unsupport artifact location: Associating artifact

88 
   at Microsoft.VisualStudio.Services.Agent.Worker.Build.ArtifactCommandExtension.ProcessArtifactAssociateCommand(IExecutionContext context, Dictionary`2 eventProperties, String data)

89 
   at Microsoft.VisualStudio.Services.Agent.Worker.WorkerCommandManager.TryProcessCommand(IExecutionContext context, String input)

90 
2016-07-22T20:25:54.8787760Z ##[section]Finishing: Publish Artifact: drop

**Comment by bbusacker** [comment]
@bryanmacfarlane Mounting the windows share and then copying the files works fine.  It is the association piece that causes the error.

**Comment by eugenebruk** [comment]
Same here. The files got copied OK from Linux to Windows file server, but it's just a directory not associated in any build, so it has a limited value without association. I also tried file://<hostname>/directory name notation, but that didn't work either, throwing the same exception as before ("Unsupport artifact location").

**Comment by bryanmacfarlane** [comment]
Flagging this as documentation.  The net is on Linux / OSX, you map the UNC to a local path and use the copy task to copy to the local path.  Then use the publish artifact task **with the UNC path that was mapped locally**.  That is so others see a UNC share in the web UI - not the local path on your build machine.  In the 105 rollout, we changed publish artifact on Linux / OSX to only register the artifact (and not try to copy to a UNC share which will not work).  I will doc.

**Comment by eugenebruk** [comment]
Thanks for the update! This is what I ended up doing: creating a drop share manually and copying output files there outside of Publish/copy task. However, the task still creates a Windows-style directory (\\server\share\dir) on Linux and actually puts some files there! I had to manually delete it afterwards, this is not a big deal, so if the task will do just the association, that would be very good.

**Comment by bbusacker** [comment]
Perfect.  Thanks for doing that.

**Comment by bryanmacfarlane** [comment]
The net of the story is for now don't use PublishBuildArtifacts to UNC share on nix.  You can (1) publish to server or (2) map share and use copy task on nix.

We are adding a story on our backlog to support UNC shares on nix (including experience from web).

**Comment by aumanjoa** [comment]
But if I want to use the files I copy than in an release how I can do that?

**Comment by bryanmacfarlane** [comment]
Use a server artifact (not UNC share) on the publish side.
