### ISSUE TITLE
Code coverage summary was found, but no artifacts were present to fetch the summary file

### ISSUE THREAD

**Issue by nanivijay** [Microsoft/vsts-tasks#2051]
![snip_20160708232151](https://cloud.githubusercontent.com/assets/5945591/16706469/ca1c2082-4562-11e6-8436-21a5c370b935.png)
![image](https://cloud.githubusercontent.com/assets/5945591/16706476/f5874314-4562-11e6-88a9-8b33ca630cd1.png)
i converted opencover xml to cobertura format.
I gave the cobertura.xml in the publish code coverage task.I am getting the attached error message.

Please help me resolving the issue

**Comment by nigurr** [comment]
Can you please past the screenshot of `Artifacts`?
Is there any folder with name `Code Coverage Report` under `Artifacts`?

**Comment by nanivijay** [comment]
![image](https://cloud.githubusercontent.com/assets/5945591/16721112/a252cc8c-46f1-11e6-979f-9c32cce2e0fa.png)

Yes. Please find the attached image

**Comment by nanivijay** [comment]
I am using opencover to generate the codecoverage xml(https://github.com/OpenCover/opencover) for asp.net 5 DNX application. After that i am using Reportgenerator to generate the htmls.(https://github.com/danielpalme/ReportGenerator) .VSTS supports Cobertura in the publish task so i converted the opencover coverage xml to Cobertura using https://github.com/danielpalme/OpenCoverToCoberturaConverter.

Please let me know if you need more information.

**Comment by nigurr** [comment]
@nanivijay the folder name should be in this format `Code Coverage Report_buildId`
how are you publishing these reports?

**Comment by nanivijay** [comment]
@nigurr The folder name is as expected. 

![image](https://cloud.githubusercontent.com/assets/5945591/16727977/a0b3c65c-4718-11e6-8856-ddcc86dd642e.png)
![image](https://cloud.githubusercontent.com/assets/5945591/16727991/b3ac9676-4718-11e6-9865-a4c28f524610.png)

**Comment by nanivijay** [comment]
any pointers????

**Comment by atinb** [comment]
Does OpenCoverToCoberturaConverter not create HTML files also? I am not sure how similar the format of Cobertura HTML is to that generated by ReportGenerator. Thanks!

**Comment by nanivijay** [comment]
OpenCoverToCoberturaConverter is converting the opencover summary xml to Cobertura xml format. 
The publish task is not taking care of creating htmls if we provide xml? reportgenerator generates based on xml.

**Comment by nigurr** [comment]
@nanivijay we don't generate HTML based on XML file currently.

**Comment by atinb** [comment]
@nanivijay 
Thanks for the information. Like Nitin said, we do not create HTML files. We are investigating why your uploaded HTML files are not working and I will get back to you next week on that. As a workaround, you can download your HTML artifacts and open them locally in a browser.

**Comment by nanivijay** [comment]
@nigurr @atinb Thank you guys.

**Comment by AshwiniChalla** [comment]
The issue is with the extension of html files. We support .html files., But the report generator has generated .htm files. We will fix this.

**Comment by nanivijay** [comment]
@AshwiniChalla renaming htm to html worked for me. i can use this work around until you fix. Thanks

**Comment by atinb** [comment]
Great! Thanks for confirming

**Comment by nanivijay** [comment]
any plans to support opencover format in vsts code coverage publish tasks?

**Comment by atinb** [comment]
No current plans. Thanks!

**Comment by TwinbrotherPro** [comment]
Exploring still the .htm vs .html issue. When are you expecting to fix that? :)

**Comment by atinb** [comment]
The fix should be deployed within a week. Thanks!

**Comment by ylin2slbcom** [comment]
hi experts,

i use coverage.py to run the tests, and to generate the report coverage.xml 

but vsts is asking for summary file, and keeps complainting about 
"2016-08-01T19:53:05.6705490Z Reading code coverage summary from '/home/_work/4/s/coverage.xml'
2016-08-01T19:53:05.6754020Z ##[warning]No coverage data found. Check the build errors/warnings for more details.

if i use "coverage report", i can see the coverage stat.

any help here?

thanks

**Comment by atinb** [comment]
I commented on #2186 that you opened. lets use that to track the issue.
Thanks!
