### ISSUE TITLE
Ability to Copy/Clone a task in Release

### ISSUE THREAD

**Issue by Timor1986** [Microsoft/vsts-tasks#2062]
Hi, I would like to copy-paste or clone a Task in a Realse Definition so I would not need to add the same task and fill it with the same configuration all over again.

**Comment by RoopeshNair** [comment]
@Timor1986,

We have this on our backlog. 
For now, as a workaround you can setup an environment with the intended tasks and use “Clone environment…” option from the environment menu (“…”) which should copy all the tasks over to a new environment.

**Comment by RoopeshNair** [comment]
Will be tracked in backlog, closing the issue
