### ISSUE TITLE
State of Tools Installer

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vsts-tasks#2066]
Whats the state of Tools installers as described [here](https://github.com/Microsoft/vsts-tasks/blob/master/docs/tools.md). Are they implemented in the meantime or is this still just a planning document? It describes that there should be some Tools installer available in this repository under a Tools path, but this doesn't seem to exist yet.

**Comment by bryanmacfarlane** [comment]
It's high on the backlog.  It's probably one of the first features we'll work on as soon as the new combined agent and new UX is done (both in TFS.vNext and rolling now in VSTS).   Probably starting in a month or so
