### ISSUE TITLE
How execute karma tests in RunVisualStudioTestsusingTestAgent

### ISSUE THREAD

**Issue by titans2016** [Microsoft/vsts-tasks#2071]
Hi.
It's possible execute tests on remote test agent via RunVisualStudioTestsusingTestAgent?
If no, could you please add feature to tasks?
Our karma tests use chrome and required interactive mode.
That's why we can't use build agent.

**Comment by allendm-msft** [comment]
@titans2016 fair ask. We will track this. 

To clarify we support any tests that are executable via vstest.console.exe in the Run Functional Tests task. So if you have a karma UT adapter for vstest you would be able to use the task.

**Comment by titans2016** [comment]
Does it mean, that on test agent we should install visual studio and some karma adapter?

**Comment by allendm-msft** [comment]
You would just need to copy the [karma unit test adapter for vstest] (if one exists) into the <tainstalldir>\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions folder. 
No VS install needed at all.

Caveat. Given that I dont know of any such adapter I havent tested this out myself but it should work.

[1]: https://blogs.msdn.microsoft.com/visualstudioalm/2012/07/31/writing-a-visual-studio-2012-unit-test-adapter/

**Comment by atinb** [comment]
@titans2016 
Is the issue resolved? Thanks!

**Comment by titans2016** [comment]
No. test adapter still doesn't see any karma adapter. We decided rewrite tests to chutzpah runner. Thanks.
