### ISSUE TITLE
Azure Deployment:Create Or Update: Problem using a variable for the subscription

### ISSUE THREAD

**Issue by janecos** [Microsoft/vsts-tasks#2092]
I am using Azure Deployment:Create Or Update Resource Group action in a release which has 2 environments. The environments should be in 2 different subscriptions. I have created the service endpoints and selecting either one in the dropdown for editing the task and deploying work.
However if I create a variable and put the name of the endpoint into the variable it doesn't work. In the logs I see the command
Get-ServiceEndpoint -Name TestingSub -Context Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.TaskContext

and then the error 
##[error]System.Collections.Generic.KeyNotFoundException: The service endpoint TestingSub was not found

Should this work, or is there another way to use different subscriptions?

**Comment by pavanadepu2** [comment]
Currently I am looking into the issue, will get back to you soon with the findings.

**Comment by janecos** [comment]
Any update - should this work?

**Comment by kmkumaran** [comment]
@janecos, the variable support for service endpoint is not supported at this moment. You will have to continue with your current approach of selecting the endpoint in drop down in each of the environments.
