### ISSUE TITLE
Inline Script Capability in Power Shell on Target Machines

### ISSUE THREAD

**Issue by zechariahks** [Microsoft/vsts-tasks#2093]
Can we have the Inline Script capability in PowerShell on Target Machines task as it is there on PowerShell Task. If we have this functionality we don't have to write a script and check in, we can simply call them from inline script itself.

**Comment by RoopeshNair** [comment]
@zechariahks,

Current design of the task expects the script / dependent scripts to be on the target or is accessible from the target. We don't have inline-scripting feature planned for "PS on target" task.  Contributions welcome
 
On a related note, checked-in script is recommended as it promotes config-as-code tenet

**Comment by ThePickNick** [comment]
I like that feature too, inline script is much more convenient as on some targeted machine we are tying to execute script does not exist.

**Comment by kmkumaran** [comment]
@ThePickNick - Inline scripting is now available from 3.* version of the PowerShell on Target task.
