### ISSUE TITLE
auto-populate picklist data based on json results of webservice

### ISSUE THREAD

**Issue by shmullikah** [Microsoft/vsts-tasks#2094]
Hi,
i want to add a new extension to VSTS marketplace that publishes a deployment event to new relic service.
pretty straightforward task that can be easily achieved in powershell.
the issue i'm facing is to actually be able to help task's users and to pre-populate a drop down of all their applications names in new relic so they can choose an application name and then pass it to script for publish.
for getting the application names list in powershell i did the following:
```
$RestURL='https://api.newrelic.com/v2/applications.json'
$APIKey='xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

$Headers=@{"x-api-key"=$APIKey}

$r= Invoke-WebRequest -Uri $RestURL -Method Get -Headers $Headers -TimeoutSec 300

$myCustomObject = $r | ConvertFrom-Json
foreach ($appname in $myCustomObject.applications)
{
  write-host   $appname.name
 }
```

i need the list of ALL $appname.name to be auto populated in a field after one inserted his API KEY in a different field.

**Comment by bryanmacfarlane** [comment]
RM did this work.

**Comment by GitHubSriramB** [comment]
Suggest doing the following:
- Create a custom endpoint for relic service
- Add a dataSource in the endpoint corresponding to the REST URL to query applications
- Add a resultSelector within the dataSource to parse out the Name from each of the appName json element
- Add an endpoint input to your task
- Add a dataSourceBinding from your task that references the dataSource you defined in the endpoint

You can refer to how drop down for Azure storage accounts has been added to Azure File Copy task as an example:
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureFileCopy/task.json

To get the data sources for Azure, you can query the Azure endpoint type using the following REST call:
https://<account-name>.visualstudio.com/defaultcollection/_apis/distributedtask/serviceendpointtypes?type=Azure

The dataSource that the task refers to is this one:
{"name":"AzureStorageServiceNames","endpointUrl":"$(endpoint.url)/$(endpoint.subscriptionId)/services/storageservices","resultSelector":"xpath://ServiceName"},

Hope this helps.

**Comment by shmullikah** [comment]
Hi @GitHubSriramB ,
sorry for the dealy :).
Thanks for your help, it wasn't easy and defiantly not well documented but I've succeeded to populate the picklist according to a service endpoint and packed it as an extension.
the final stage is to run the script that is calling a the endpoint URL (token based auth).
i need to use the endpoint URL with the API token and call another API based and the endpoint URL.
any suggestions?
i saw the Get-VstsInput and the GetEndpointData somewhere but they are not reconized.
tried to import-module Microsoft.TeamFoundation.DistributedTask.Task.Internal.dll and
Microsoft.TeamFoundation.DistributedTask.Task.Common.dll but it failed with:

**_Import-Module : Could not load file or assembly 'Microsoft.TeamFoundation.DistributedTask.Agent.Interfaces, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its 
dependencies. The system cannot find the file specified._**

**Comment by ericsciple** [comment]
If you are using the "powershell3" task execution handler, you want [Get-VstsEndpoint](https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/FullHelp/Get-VstsEndpoint.md). Here is an [example](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Common/VstsAzureHelpers_/VstsAzureHelpers_.psm1). You would need to use [Get-VstsInput](https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/FullHelp/Get-VstsInput.md) to resolve the Name to pass to Get-VstsEndpoint.

If you are using the "node" task execution handler, then use similar functions: getInput, getEndpointUrl, getEndpointDataParameter, getEndpointAuthorization.

The task.internal module is for the legacy, closed-source "powershell" task execution handler.

**Comment by shmullikah** [comment]
@ericsciple @GitHubSriramB 
thanks guys.
i ran the following code:
`$testendpoint=Get-VstsInput -name NewRelicService`
and got its id.
then ran 
`$testendpoint=Get-VstsEndpoint -name $testendpoint`
and got:
@{Url=https://api.newrelic.com/v2; Data=; Auth=}
this is a working endpoint that is token based (the task itself uses it to auto-populate a picklist successfully).
why the Auth attribute is empty?
how can i get the token safely and invoke another REST call to his URL without the need to specify the token again (it is was already inserted when i defined the service endpoint).

thanks

**Comment by shmullikah** [comment]
@GitHubSriramB @ericsciple  @bryanmacfarlane 
Hi Guys, 
sorry to bother but do you have any news?

**Comment by shmullikah** [comment]
i'll try and update, thanks!

**Comment by shmullikah** [comment]
@ericsciple 
worked like a charm, thank you very much guys!
