### ISSUE TITLE
Copy Files Task / Publish Build Artifacts Task copy to invalid UNC OR drive root produces RangeError: Maximum call stack size exceeded Issue

### ISSUE THREAD

**Issue by gencebay** [Microsoft/vsts-tasks#2098]
TFS Agent copy files task trying to create a directory on Network Mapped Drive (Z:\Releases, z drive is UNC Path as Mapped Network Drive) but getting this error:
![copyfiles_stack_size_exceeded](https://cloud.githubusercontent.com/assets/879469/16909639/9375d952-4cdc-11e6-9c44-24d1bf6d4044.PNG)

`RangeError: Maximum call stack size exceeded 
String.slice (native) 
Object.dirname (path.js:795:17) 
mkdirSyncRecursive (D:\agent\tasks\CopyFiles\1.0.13\node_modules\shelljs\src\mkdir.js:7:22) 
mkdirSyncRecursive (D:\agent\tasks\CopyFiles\1.0.13\node_modules\shelljs\src\mkdir.js:16:3) 
mkdirSyncRecursive (D:\agent\tasks\CopyFiles\1.0.13\node_modules\shelljs\src\mkdir.js:16:3) 
mkdirSyncRecursive (D:\agent\tasks\CopyFiles\1.0.13\node_modules\shelljs\src\mkdir.js:16:3) 
mkdirSyncRecursive (D:\agent\tasks\CopyFiles\1.0.13\node_modules\shelljs\src\mkdir.js:16:3) `

**Comment by c-enders** [comment]
I get exactly the same error. On 8 july 2016 it worked fine. What has changed in path.js ?

**Comment by CinnamonRage** [comment]
I am also getting this error, though I only have it when running on a specific environment. The folder I am copying to does exist.

**Comment by gencebay** [comment]
I found the issue on my side! 
Please dont run the TFS Agent on Command Line as Administrator, it cannot access the network mapped drive when open as Administrator.
 [helpful link](http://spurious-logic.net/mapped-drive-tfspain)

**Comment by bastianjohn** [comment]
I had the same problem and we've got a workaround. The VSO Agent was running under the Local Services account. We changed it to an admin account that we were using to log in to the VM. Also the Everyone Permission did not work with the Local Services Account in the VSO Agent. 
I hope it helps you too.

**Comment by bryanmacfarlane** [comment]
Yep, that is a bad error which essentially means the share doesn't exist or no permissions (agent runs as).  We are changing this task to call robocopy.

**Comment by bryanmacfarlane** [comment]
Eric, this should be in next deployment right?

**Comment by ericsciple** [comment]
Yes the fix for Copy Files will roll out with 106.
