### ISSUE TITLE
Gulp task doesn't treat warnings and errors as such

### ISSUE THREAD

**Issue by jmezach** [Microsoft/vsts-tasks#2100]
When using the gulp task it seems that warnings and/or errors that are generated aren't picked up as errors and/or warnings and thus my build turns green while in reality I have a compile error in my TypeScript.

Is this something missing in the Gulp task or is there some way I can configure gulp to output these errors differently so they will be picked up by the task/agent?

**Comment by bryanmacfarlane** [comment]
This is missing in the use of the gulp file.  You need to get gulp to fail and return non zero.

For example, create another gulp task that is dependent on your compile gulp task.  If that one runs, regardless of your output, your tasks didn't fail.

If gulp returns 0, your compile task didn't fail.  And we fail on RC.
