### ISSUE TITLE
visual studio test agent delpoyment task fail with message 'Did not find TestAgentConfig.exe 

### ISSUE THREAD

**Issue by ignorent** [Microsoft/vsts-tasks#2101]
I have two PC, both are win7 installed. 
I want to build a automatic test platform using TFS.
I want to use PC1 as TFS server, I have Microsoft TFS 2015, Visual studio 2015 installed.  
and in PC2, I have  Visual studio 2015  installed, I want the PC2  to be testing PC( include Coded UI test)

I create one Build in clude
1# Visual Sutodio Build task
2# Windows Machine file Copy 
3# Visual studio test agent delpoyment
4# Run functional test.

once I running the build I will get following message error at step 3#

DistributedTests: Task 'ConfigureTestAgent' for machine apcnopc7pm5z2x:5985's Error : System.Exception: Did not find TestAgentConfig.exe at : **C:\Program Files\Microsoft Visual Studio 14.0\Common7\IDE\TestAgentConfig.exe**. Ensure that TestAgent is installed.

it looks that the issue is happen while configure the test agent, I guess there may be something need to be installed first, but I missed.

anything wrong with me? can anybody help me ?

**Comment by atinb** [comment]
Can you please send screenshots of your Deploy and Run tasks? Thanks!

**Comment by ignorent** [comment]
my 
![image](https://cloud.githubusercontent.com/assets/20531731/16941213/52651b2c-4dc1-11e6-948b-4621f367b0ab.png)
my deployment task screen

the error will happen on this step, the running task do not even got chance to execute

here is the run task screen
![image](https://cloud.githubusercontent.com/assets/20531731/16941248/8ed2205a-4dc1-11e6-9266-cd143e90c6cc.png)


thanks
ray

**Comment by atinb** [comment]
Thanks. Have you pre-downloaded the 2015 agent and placed it on the share? If so, can you confirm the Build agent has access to that share? Or if you look in the Deploy logs, do you see any other warning / errors?

**Comment by ignorent** [comment]
@atinb 
Thanks. Have you pre-downloaded the 2015 agent and placed it on the share? If so, can you confirm the Build agent has access to that share? Or if you look in the Deploy logs, do you see any other warning / errors?
------------------------
Yes, the build agent is pre-downloaded, and delopy task successfully copy it from share folder to the destination folder and name it as  "c:\testagent\vstf_testagent.exe"
![image](https://cloud.githubusercontent.com/assets/20531731/16941898/8c4a2a40-4dc5-11e6-93d4-1968341ade7b.png)

the error is happen when it  "config  test agent"

**Comment by allendm-msft** [comment]
@ignorent i just tried this locally and dont see any issues in this scenario so need your help to debug further. 

We noticed that files are being copied to *networkservice* appdata location. what account/user are you using for the admin creds of your machine group? what account is your build agent running as?

**Comment by ignorent** [comment]
@allendm-msft 

all of the are running in my domain account, the domain account are administrator of the two PC

**Comment by allendm-msft** [comment]
@ignorent can you try out a remote powershell command (Invoke-command) to the same machine and print the username ? Does it should localsystem or networkservice?

**Comment by atinb** [comment]
Closing due to no response. If this issue still persists, please reopen and let us know what the output of the powershell command above was. Thanks!
