### ISSUE TITLE
DTAExecutionHost.exe The process was terminated due to an unhandled exception.

### ISSUE THREAD

**Issue by kardinal3000** [Microsoft/vsts-tasks#2102]
I have test VM **Windows 7 Professional SP1** and  **Microsoft Agents for Visual Studio 2013 v 12.0.40629**
 I decided move to  the new base-script system (vNext). When I have created new VM and using your "DeployVisualStudioTestAgent" task, I see installed **Microsoft Agents for Visual Studio 2015 v 14.025420.1**. Everything works excellent. But when I have try to install Test Agent (Interactive mode) on the my old VM I always get two errors in Event logs:

**Error 1**
> Application: DTAExecutionHost.exe
> Framework Version: v4.0.30319
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.MissingMethodException
> at Microsoft.VisualStudio.TestService.AgentExecutionHost.Program.Main(System.String[])

**Error 2**
> Faulting application name: DTAExecutionHost.exe, version: 14.98.25331.0, time stamp: 0x574e13b4
> Faulting module name: KERNELBASE.dll, version: 6.1.7601.23418, time stamp: 0x5708a7e4
> Exception code: 0xe0434352
> Fault offset: 0x0000c54f
> Faulting process id: 0x290
> Faulting application start time: 0x01d1e18e5029f93b
> Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\DTAExecutionHost.exe
> Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
> Report Id: 8ddd4ab7-4d81-11e6-a141-005056a545b2

Test Agent becoming in unused state. Right now I see only one way to fix it. It's reinstall my old VM.
 I hope you have other ways to fix it. Please assist me with that 
Thank you for advance!

**Comment by allendm-msft** [comment]
@kardinal3000 when you say you are installing the test agent on "your old vm" does it mean you have both the agents on the same VM? That is something we do not support today. 

Independent to that the missingmethodexception usually indicates a faulty install. This exception should never occur in a shipping product for obvious reasons.

**Comment by kardinal3000** [comment]
@allendm-msft after running "Deploy Visual Studio Test Agent". The service **Test Agent 2013** disappeared I cant find it in "uninstall a program" and I observe the only one test agent 2015. So, right now I have the only one **Microsoft Agents for Visual Studio 2015 v 14.025420.1. update 3** on  my old vm.  Also I tried to make
1.  Reboot VM 
2.  Uninstall/Ininstall **Microsoft Agents for Visual Studio 2015 v 14.025420.1.**. manually 
3.  Windows update 
4.  Update Framework 4.0, install Framework 4.5, 4.51, 4.6

I still try to find resolving of this problem

**Comment by allendm-msft** [comment]
ideally a process dump wouldve helped. if you can get a dump of the dtatexecutionhost.exe and share the call stack for the missingmethodexception it would help.

**Comment by allendm-msft** [comment]
@kardinal3000 do you have any more data for us?

**Comment by kardinal3000** [comment]
Yes I have, sorry for delay with reply I will send the next week at the moment i have a lot of other issues

**Comment by kardinal3000** [comment]
Guys, could you please close this issue. It's no more topical question.
