### ISSUE TITLE
Issue with task timeouts

### ISSUE THREAD

**Issue by RaphaelYoshiga** [Microsoft/vsts-tasks#2104]
I am trying to set the timeout for my vs test task, but it doesn't look like it has any effects on the test execution.
![untitled](https://cloud.githubusercontent.com/assets/6370804/16952395/ebc6cff0-4dc0-11e6-9bb1-02849bce624e.png)

I've set for 1 minute (minimum), but I can have a test running for more than two minutes.
Any ideas on why?
Also the timeout could be in seconds for this task.

**Comment by RaphaelYoshiga** [comment]
Note: I got around the problem by having a .testsettings with the timeout there.
But the timeout parameter still doesn't have any influence

**Comment by allendm-msft** [comment]
@bryanmacfarlane any known issue with timeouts? Am able to repro too.

**Comment by ericsciple** [comment]
@RaphaelYoshiga What is your agent version?

**Comment by RaphaelYoshiga** [comment]
@ericsciple I'm using the hosted queue.
Is that the version you are asking for?
C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\**1.102.0**\tasks\CopyFiles\
[logs_129.zip](https://github.com/Microsoft/vsts-tasks/files/378361/logs_129.zip)

The logs are attached as well if needed.

Cheers,

**Comment by bryanmacfarlane** [comment]
RM did the task level timouts

**Comment by vithati** [comment]
This issue exist in windows legacy agent for tasks which are using execution handle type “powershell”. Other tasks don't have this issue. 

This issue not exist in **vsts-agent**. Hosted queues are migrating to use vsts-agent. Soon this issue resolved.
