### ISSUE TITLE
NuGet Packager support for filtering to nuspec files and preferring csproj

### ISSUE THREAD

**Issue by mwadams** [Microsoft/vsts-tasks#2112]
We would like to be able to apply a filter for nuspec files, but then actually use the .csproj file if it is present in that location.

This allows us to use the automated nuspec token replacement stuff, while creating packages only for those components that have a nuspec file alongside the csproj (or a hand crafted nuspec file somewhere else)

We'll put together a PR which illustrates what we mean. 

(Or is there a better way of doing this; manually filtering out the csproj's we don't want isn't a good solution?)

**Comment by zjrunner** [comment]
Not Dev15.  I'm a little concerned about pinning too much to the nuspec existence with nuget in the middle of all the xproj/msbuild/nuspec/json shuffle.  We should see this start to shape up soon and then we'll need to look at the best way of identifying which folders need to be packed (match pattern today). From there we need a clear decision tree (if X exists we always should do Y), or the user could use multiple pack tasks with different patterns and different rules (use csproj, use nuspec, etc).  Once nuget releases the future flow it will be easier to guide the task.

**Comment by alexmullans** [comment]
Closing this as a feature request that we'll track as part of the next wave of package producer improvements.
