### ISSUE TITLE
[Question] Is it possible to use Azure File Copy w/o Public IP?

### ISSUE THREAD

**Issue by brandongodby78** [Microsoft/vsts-tasks#2115]
Using RM Hosted agent is there a way to use Azure File Copy without giving your machines public IP addresses?

**Comment by Ajay-MS** [comment]
@brandongodby78  , No it is not possible to use Azure file copy without public IP. Public IP address of the VM is must for Azure File Copy task. This is required to establish connection to the machine from Agent.

**Comment by yaronmaz** [comment]
what is the agent and vm are at the same vNET?
