### ISSUE TITLE
Azure DACPAC deployments are failing

### ISSUE THREAD

**Issue by janecos** [Microsoft/vsts-tasks#2116]
This morning my VSTS deployments are all failing due to issues deploying the databases.

I am using hosted agents, and the Azure SQL Database Deployment task.
The error is usually - [error]System.Management.Automation.RuntimeException: IPAddress mentioned is not a valid IPv4 address.

I have 3 databases on the same server, sometimes deployment of the first database succeeds, but then the second fails.
The steps to delete the rules were sometimes failing too (if it got past the create), but I have disabled these now.
The rules were set to Autodetect. I don’t think the firewall rule is needed at all because the server is set to allow access from within Azure so I changed it to a known IP address (my office) and it is still failing with this message.

How can I stop it from doing anything with the firewall, or make the step work?

Thanks,
Jane

**Comment by Ajay-MS** [comment]
@janecos  Depending on email conversation  I am closing this issue. Feel free to reopen if you face issue again.

**Comment by jdallegion** [comment]
Can we even get an idea of WHAT the issue was?  Experiencing the same issue today.
