### ISSUE TITLE
Windows 7 sp2

### ISSUE THREAD

**Issue by dremond** [Microsoft/vsts-tasks#2132]
Hi,

Windows 7 sp2 does not exists.
Please fix the prerequisites.

Best Regards
David

**Comment by bryanmacfarlane** [comment]
Can you supply details in what doc/product area you're seeing a ref to this?  Would help us fix it.

**Comment by dremond** [comment]
Hi,

The error is located in the "prerequisites" section : https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/DeployVisualStudioTestAgent

For your information, I add also to execute this script before enabling PS Remoting on my windows 7 sp1 machines (http://serverfault.com/questions/530903/enable-psremoting-on-windows-server-2008-r2-error):

reg add HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v LocalAccountTokenFilterPolicy /t REG_DWORD /d 1 /f


Best regards

David

**Comment by nigurr** [comment]
Thanks for reporting it. Fixed it 👍
