### ISSUE TITLE
Nuget Packager fails when mixing .csproj and .nuspec when <files></files> are included.

### ISSUE THREAD

**Issue by patrickmichalina** [Microsoft/vsts-tasks#2138]
Building a csproj works when there is no .nuspec file. Building works when there is just a .nuspec file.

Project is in a sub-directory within a solution.

Has this happened to anyone else?

```
Path cannot be null.
Parameter name: path
System.Exception: Unexpected exit code 1 returned from tool NuGet.exe
at Microsoft.TeamFoundation.DistributedTask.Task.Internal.PowerShell.InvokeToolCmdlet.ProcessRecord()
at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by jmyersmsft** [comment]
@patrickmichalina We rolled back the version of NuGet.exe in the build agent last night due to several bugs in the new version, which may have mitigated this for you. We would still like to investigate this with you and/or hand off to the NuGet team however.

**Comment by patrickmichalina** [comment]
Interesting. I can't get enough enough from the logs to know what exactly is failing. It appears that the base directory is changing when it attempts to read the files to copy into the nuget directory. When I pack from .csproj with a corresponding .nuspec it works locally on my machine just fine from the command line. Didn't want to manually try nuget.exe on VSO because of authentication, so I'm using just the .nuspec for now. But it would be nice to use the csproj if this ever gets fixed :)

**Comment by jmyersmsft** [comment]
@patrickmichalina can you confirm this is still happening for you?

**Comment by zjrunner** [comment]
@patrickmichalina - any update or repro?  There isn't enough to go on here in this thread.  There were some issues in nuget pack (https://github.com/NuGet/Home/issues/2965) in the 3.5 beta streams so it would be good if you could validate against the newest nuget.exe nightly.  If this is an issue we'll want to get it over to them.  For now the packaging task will stay on 3.3 by default, but you can use your own custom nuget.exe and soon you'll be able to choose an in-task 3.5.1 as opt-in so if there is an issue here please reactivate this item with a repro or get it right on the nuget folks if that is the proper source.
