### ISSUE TITLE
Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL when running the test using TFS "run functional tests" task

### ISSUE THREAD

**Issue by dixu99** [Microsoft/vsts-tasks#2144]
Hi, 

We use "Visual Studio Test Agent Deployment" and "Run Functional tests" tasks in TFS to set up the test agent on a test machine and run selenium tests there. The test agent is set up not to run as "interactive process". 

Before last week, all the tests run fine in this set up. However, a few days ago, all tests started failing with error message like this:
OpenQA.Selenium.WebDriverException: OpenQA.Selenium.WebDriverException: The HTTP request to the remote WebDriver server for URL http://localhost:19509/session timed out after 60 seconds.

On the same machine, I can run the tests fine if I invoke the tests using vstest.console.exe from command line. Running the tests in visual studio works as well.

I tried to use "interactive process" mode. The thing is I have to log on to the test server and keep the session open otherwise the set up agent process keeps restarting the test machine, account used to set up the test agent is an admin user account, We are not using CodedUI, just plain selenium.

We were able to run the tests fine without checking "interactive process" for months. We are on TFS 2015 update 1, no recently TFS or agent update. RunVisualStudioTestsusingTestAgent task version is 1.0.22. We specified the test agent location and "Update Test Agent" is not checked, so there is no update to the version of test agent right. There was no code change to tests themself either. 

I couldn't find out why tests started failing with no obvious configuration or code changes. Does anyone see this issue before or know a solution?

Thanks,
Di

**Comment by atinb** [comment]
My guess would be the browsers got updated and need a newer version of the driver. Nothing has changed from the test agent side...
