### ISSUE TITLE
NuGet tasks rely on Agent.BuildDirectory in old-style credential flow

### ISSUE THREAD

**Issue by AlasGou** [Microsoft/vsts-tasks#2148]
I'm running a NuGet publish action in a Release. As of today with no other changes(It used to work) its broken with the following error:

2016-07-28T10:34:36.3675308Z ##[debug]agent.buildDirectory=undefined
2016-07-28T10:34:36.3987310Z ##[error]TypeError: Path must be a string. Received undefined

Judging by the log output lines i've been getting, it's to do with this commit.

https://github.com/Microsoft/vsts-tasks/commit/eccf75765a6f379051688ff63e3c99ab9230acb0

When it switched from a powershell implementation to a ts implementation. Can't be 100% certain though.

To replicate do a NuGet Publish inside of a release, on a windows build agent.

**Comment by bryanmacfarlane** [comment]
I've looped in the packaging team.  Thanks for reporting.

**Comment by RDalziel** [comment]
I'm also getting publish issues on build with version 0.2.0

"Unhandled: %s is not a solution file. Check the 'path to solution or packages.config' property of the NuGetInstaller task."

**Comment by AlasGou** [comment]
The workaround for this was to update the build agent to the latest version.

**Comment by jmyersmsft** [comment]
@RDalziel That's a different bug. Could you open a separate issue and @mention me? As a workaround, check the 'Path/Pattern to nupkg' for doubled semicolons, or semicolons at the beginning or end of the value. We had an internal report of that as well, and a trailing semicolon (resulting in an "empty" pattern)is what triggered that bug for them.

**Comment by jmyersmsft** [comment]
Fixed by #2154
