### ISSUE TITLE
NuGet Publish Error on Version 0.2.0

### ISSUE THREAD

**Issue by RDalziel** [Microsoft/vsts-tasks#2150]
as Requested - seperate issue for this error:

"Unhandled: %s is not a solution file. Check the 'path to solution or packages.config' property of the NuGetInstaller task."

This, for me, has only started happening today. I've had some input from the team below already which i'll look into.
@jmyersmsft "As a workaround, check the 'Path/Pattern to nupkg' for doubled semicolons, or semicolons at the beginning or end of the value. We had an internal report of that as well, and a trailing semicolon (resulting in an "empty" pattern)is what triggered that bug for them.

**Comment by RDalziel** [comment]
I had a semi colon at the end of the path @jmyersmsft  - Removing it got me round the problem!

**Comment by jmyersmsft** [comment]
This will be fixed when #2195 is deployed.

**Comment by zjrunner** [comment]
#2195 fixed, merged, shipped.
