### ISSUE TITLE
Rerun failed test cases from TFS 2015

### ISSUE THREAD

**Issue by myuzhang** [Microsoft/vsts-tasks#2155]
As we began to use TFS 2015, we can't find a way to rerun the failed test cases under the same test run from Run Functional Task.
For 2013, we are using MTM to rerun the failed test cases under the same test run conveniently.

Someone suggested to write PS to get the failed test cases from the same test run and rerun, if this is the only way, can anyone show an example in details, please?

Thanks

**Comment by atinb** [comment]
We are looking at how best to provide this functionality, but for now, this is not an inbuilt feature. You can use [TFS REST APIs](https://www.visualstudio.com/en-us/docs/integrate/api/test/results) to find the failed tests and retrigger them. Thanks!

**Comment by myuzhang** [comment]
Thanks Atin a lot.
The API provides test point re-activate so that I can re-activate failed test points, however it doesn't provide re-activate test run. Or I missed something.

**Comment by atinb** [comment]
The way I was thinking about it, you would query for the failed tests and then retrigger them on the Build agent itself or one of the test machines. Thanks!

**Comment by psutharsan** [comment]
I have same problem cannot rerun the failed tests. Is there going to be fixed? Thanks

**Comment by daniel-terceros-incontact** [comment]
Hey guys, it would be possible to provide me an example to re run failed test by using rest apis in tfs 2015? Thanks :)
