### ISSUE TITLE
Directory files not copied to output on dotnet build in VSTS

### ISSUE THREAD

**Issue by rschiefer** [Microsoft/vsts-tasks#2157]
I added a "Deployment" directory to my ASP.NET Core site with a PowerShell file in it.  I marked this directory to copyToOutput in the project.json.

```
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "copyToOutput": {
      "include": [ "Deploy" ]
    }
```
This appears to work fine locally.  The ps1 file is always updated in the bin folder.

In VSTS however it only appears to be copied one time and then not updated on subsequent builds.  I am using a VS Build task in my build def.  I was only able to get it to update if I added a task to delete the bin folder first.

With further testing I think I resolved this issue by tweaking my include to point to the files in the folder instead of the folder itself.

```
  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "copyToOutput": {
      "include": [ "Deploy/**" ]
    }
```

I have not done extensive testing here just wanted to see if others have seen the same behavior.  This was super confusing and I wasted a couple days on it.

**Comment by bryanmacfarlane** [comment]
This seems like feedback for dotnet build tool.  You're not having an issue with any of the tasks in this repro.  We will however create dotnet build tasks and/or templates as the dust settles and the dotnet tools get closer to release.
