### ISSUE TITLE
Update the AzCopy tool installed with the agent

### ISSUE THREAD

**Issue by nelsonmorais** [Microsoft/vsts-tasks#2169]
The current version of the AzCopy installed in the Agent\worker\tools\AzCopy is an old version (3.1.0) that doesn't support the /BlobType:Append option.

Please update the AzCopy tool to the latest version to provide support for Append blobs

**Comment by niadak** [comment]
Hi Nelson,
Thanks for your feedback. I agree that AzCopy.exe we are using is bit older. We will update this soon.

**Comment by nelsonmorais** [comment]
Thanks! Can you update this thread when its done?

**Comment by niadak** [comment]
sure.

**Comment by RoopeshNair** [comment]
@nelsonmorais, We're locked for next couple of months. We will revisit the request post that.

**Comment by saberell** [comment]
I have the same issue, you broke my build server again with the last update containing the same way too old azcopy version (3.1.0). Please update azcopy to the last version (5.0.0).
