### ISSUE TITLE
RunDistributedTests cannot access collection

### ISSUE THREAD

**Issue by cwoolumtechnossus** [Microsoft/vsts-tasks#2178]
I am trying to run a data driven Coded UI Test where my data source is VSTS. 

```
 [DataSource("Microsoft.VisualStudio.TestTools.DataSource.TestCase", "https://testcollection.visualstudio.com/defaultcollection;Foo", "78785", DataAccessMethod.Sequential)]
```

The problem is that because the task does not support overriding the user of the test run, the agent tries to connect to VSTS as the windows service account which is not valid. 

Is it possible to set a run context with a VSTS user?

**Comment by allendm-msft** [comment]
@cwoolumtechnossus so you want to run a particular test under a different user context? We do not have that functionality today. 

@atinb to track the feature request

**Comment by cwoolumtechnossus** [comment]
I am fine running the entire run as a single user. It just needs to be a VSTS user so that it has access to data in VSTS

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by atinb** [comment]
Unfortunately, Data driven tests are currently only supported if the data is coming from xml, csv or sql end points. Run Functional Tests task cannot be used for data coming from VSTS. Adding this support is on our backlog. Thanks!

**Comment by fbouteruche** [comment]
Hi @atinb , 

Can you share with us the roadmap for this feature ? It is very important for non-technical tester.
