### ISSUE TITLE
DeployAzureResourceGroup - Start Single Machine

### ISSUE THREAD

**Issue by russelldyas** [Microsoft/vsts-tasks#2181]
Is there a way of starting single machine instead of a group using the DeployAzureResourceGroup task.  

As we have a number of release manager and build processes where we need to start one to two machines in a resource group but having to wait and run those extra machines is a waste etc.

From

Russell

**Comment by niadak** [comment]
Hi Russell,
Thanks for your feedback. We are not supporting Machine Level filtering for Start/Stop/Delete actions in DeployAzureResourceGroup task yet. We will take this as enhancement and take as per as our team priority.

**Comment by RoopeshNair** [comment]
@russelldyas 

You'd have to rely on Azure PowerShell task to manage individual VMs. We don't have any plans to take this up anytime soon. We're locked for next few months.

We're open to contributions.
