### ISSUE TITLE
No coverage data found

### ISSUE THREAD

**Issue by ylin2slbcom** [Microsoft/vsts-tasks#2186]
hi experts,

i use coverage.py to run the tests, and to generate the report coverage.xml

but vsts is asking for summary file, and keeps complainting about 
"2016-08-01T19:53:05.6705490Z Reading code coverage summary from '/home/_work/4/s/coverage.xml'
2016-08-01T19:53:05.6754020Z ##[warning]No coverage data found. Check the build errors/warnings for more details.

if i use "coverage report", i can see the coverage stat.

any help here?

thanks

![image](https://cloud.githubusercontent.com/assets/18427489/17329127/d7b20022-5886-11e6-8d43-4305d7a04e8b.png)

**Comment by atinb** [comment]
Can you please send a coverage file to atinb at microsoft dot com so that we can take a look? Thanks!

**Comment by atinb** [comment]
ping. Please send us the file so that we can investigate. Thanks!

**Comment by allendm-msft** [comment]
No repro at our end and no response here either.

**Comment by aarcro** [comment]
Hope we can reopen this issue. I'm seeing the same behavior. I attached logs and coverage.xml
[coverage.xml.txt](https://github.com/Microsoft/vsts-tasks/files/751707/coverage.xml.txt)
[publish.coverage.log.txt](https://github.com/Microsoft/vsts-tasks/files/751709/publish.coverage.log.txt)

So it does find the coverage.xml, and publishes it as an artifact.

https://www.dropbox.com/s/g6f044iis4ig0k7/Screenshot%202017-02-03%2017.38.29.png

But there's no coverage report on build details:

https://www.dropbox.com/s/1xg9isagp4wm1ab/Screenshot%202017-02-03%2017.39.13.png

**Comment by Steztric** [comment]
I am also experiencing this issue. According to the Coverage.py documentation, the output format is compatible with Cobertura;

[http://coverage.readthedocs.io/en/coverage-4.2/cmd.html](http://coverage.readthedocs.io/en/coverage-4.2/cmd.html)

However when I integrate the build step, I also get

`##[warning]No coverage data found. Check the build errors/warnings for more details.`

Please help me fix this.

**Comment by ylin2slbcom** [comment]
rename the attached python script from .py.txt to .py

and run 'python fix_coverage_for_cobertura.py coverage.xml' you will get the compatible coverage file



[fix_coverage_for_cobertura.py.txt](https://github.com/Microsoft/vsts-tasks/files/1156075/fix_coverage_for_cobertura.py.txt)

**Comment by Steztric** [comment]
Thanks for your help. Against the new issue I filed (#4814 referenced above) I discovered the reason was that my version of Coverage.py was out of date - I needed to upgrade from 4.2 to 4.4.1 and this fixed the problem.

**Comment by AmudhaPalani** [comment]
After I upgraded Coverage.py to 4.4.1, it finds the coverage.xml and publishes it as an artifact.
But still there's no coverage report on build details. The following message is displayed "Code coverage data cannot be displayed. Please verify that a valid directory containing code coverage files, including an index.html was used to publish data."

Please help me fix this.

**Comment by 4c74356b41** [comment]
I got the same behavior once, but most of the time its just empty
