### ISSUE TITLE
Question about task.json

### ISSUE THREAD

**Issue by kardinal3000** [Microsoft/vsts-tasks#2189]
Guys, please need your assists.
Where can I find information about structure of task.json file and explanation of different keys, parameters, properties in the task.json file. I am working on creating custom task for my needs. I want to use all possible facilities.
I Used  "inputs", "groups", "sourceDefinitions" maybe exist others ? where i can get  a full list of that.

"properties": {"DisableManageLink": "True"} - Big question. Which they can be, and how can I find that

**Comment by bryanmacfarlane** [comment]
Unfortunately, we need to publish a schema doc.   It's high on our backlog.  The best resource is these open source tasks as a reference.  We will get to it soon.

**Comment by kardinal3000** [comment]
Thank you for your reply

**Comment by bryanmacfarlane** [comment]
Resolving to backlog.  We will add schema support soon.
