### ISSUE TITLE
XCode build failure - "Code Sign error: No codesigning identities found" after latest release

### ISSUE THREAD

**Issue by Squiggle** [Microsoft/vsts-tasks#2190]
Having had a functional build of a Cordova app for a couple of months, it has suddenly (in the past 5 days) started to fail with the error:
`Code Sign error: No codesigning identities found: No codesigning identities (i.e. certificate and private key pairs) that match the provisioning profile specified in your build settings (“ExampleBrand News Dev”) were found.`

It appears to succesfully create/configure/unlock the keychain and import the .p12 certificate, locating the valid identity.

However, when it comes to signing the build we have a failure.

Our configuration for Signing & Provisioning is as follows:
Override Using: *File Contents*
P12 Certificate File: (build variable)
P12 Password: (build variable)
Provisiong Profile File: (build variable)
Remove Profile After Build: false

I attach the build output for the Xcode build step:
[xcode_task_output.txt](https://github.com/Microsoft/vsts-tasks/files/397554/xcode_task_output.txt)

To clarify: No configuration or cert files were altered. Build is failing for unknown reason.

**Comment by madhurig** [comment]
@Squiggle: I released a fix for this yesterday, let me know if you are still seeing issues. Sorry for the inconvenience.

Thanks,
Madhuri

**Comment by madhurig** [comment]
@Squiggle: Let me know if you are still seeing issues with your builds. 

Thanks,
Madhuri

**Comment by Squiggle** [comment]
Sorry for the slow response.

Yes, it was (silently) resolved after an update. Thanks so much!
