### ISSUE TITLE
XCode Build Task not using Provisioning Profile value

### ISSUE THREAD

**Issue by mchamler** [Microsoft/vsts-tasks#2199]
Here's what our XCode build command used to look like:
[command]/usr/bin/xcodebuild -sdk iphoneos -configuration Dogfood -workspace /Users/olssvcxe/vsoagent/_work/21/s/SnackySkeleton/BookIt.xcworkspace -scheme BookIt-Dogfood build DSTROOT=/Users/olssvcxe/vsoagent/_work/21/s/SnackySkeleton/iphoneos/Dogfood/build.dst OBJROOT=/Users/olssvcxe/vsoagent/_work/21/s/SnackySkeleton/iphoneos/Dogfood/build.obj SYMROOT=/Users/olssvcxe/vsoagent/_work/21/s/SnackySkeleton/iphoneos/Dogfood/build.sym SHARED_PRECOMPS_DIR=/Users/olssvcxe/vsoagent/_work/21/s/SnackySkeleton/iphoneos/Dogfood/build.pch **PROVISIONING_PROFILE=bb91c2ed-e6fe-438f-87f8-c24c53ccb757**

Here's what it looks like now:
[command]/usr/bin/xcodebuild -sdk iphoneos -configuration Dogfood -workspace /Users/olssvcxe/vsoagent/_work/21/s/SnackySkeleton/BookIt.xcworkspace -scheme BookIt-Dogfood build DSTROOT=/Users/olssvcxe/vsoagent/_work/21/s/SnackySkeleton/iphoneos/Dogfood/build.dst OBJROOT=/Users/olssvcxe/vsoagent/_work/21/s/SnackySkeleton/iphoneos/Dogfood/build.obj SYMROOT=/Users/olssvcxe/vsoagent/_work/21/s/SnackySkeleton/iphoneos/Dogfood/build.sym SHARED_PRECOMPS_DIR=/Users/olssvcxe/vsoagent/_work/21/s/SnackySkeleton/iphoneos/Dogfood/build.pch

Logs: [logs_48508.zip](https://github.com/Microsoft/vsts-tasks/files/398516/logs_48508.zip)

Note that the provisioning profile is no longer added as a build argument. It also looks like the profile isn't being copied to the build machine anymore.

**Comment by bryanmacfarlane** [comment]
I believe Madhuri might have just fixed this.  Adding

**Comment by madhurig** [comment]
@mchamler : Thanks for verifying the fix. The fix will be available on Team Services in the next week or 2.

**Comment by madhurig** [comment]
Fix has been deployed to Team Services, please let me know if you have an issue after switching back to the original pool.

Thanks,
Madhuri
