### ISSUE TITLE
Broken selection of files in Publish Test Results

### ISSUE THREAD

**Issue by elibarzilay** [Microsoft/vsts-tasks#2208]
I'm not completely sure about it since it's hard to find proper documentation, but it looks like the selection of "Test Results Files" in the "Publish Test Results" is misbehaving in a linux build agent.

What I want to do is have test logs dumped into the designated test result directory and publish them from there.  As a simple example, I made my build script generate a `$COMMON_TESTRESULTSDIRECTORY/foo.xml` file.  Then, in the "Test Results Files" input field I specify:

    $(Common.TestResultsDirectory)/foo.xml

and that works.  However, if I change it to a pattern that includes all xml files:

    $(Common.TestResultsDirectory)/**/*.xml

or even a simpler pattern:

    $(Common.TestResultsDirectory)/*.xml

then it complains that it didn't find any files.  OTOH, if I dump the results in the source tree, and then use some pattern that is relative to the source tree like

    testresults/**/*.xml

then it works fine.  Finally, in an attempt to still keep the test logs at the right place I tried to make a `testresults` symlink in the source tree that points at `$COMMON_TESTRESULTSDIRECTORY`, so the pattern should be the same --- but with a symlink it failed too.  So it looks like the pattern mechanism is somehow broken in that it's restricted to not see anything outside of the source tree, even via a symlink.  (And that sounds broken since the log files *can* be read.)

**Comment by tanvi-soni** [comment]
Hi,
We are looking into the issue why rooted paths are not working on linux. We will get back to you when we have a fix.

**Comment by SatishThareja** [comment]
Fix committed, closing the issue.
