### ISSUE TITLE
Coded UI Framework - DTAExecutionHost.exe Crashes

### ISSUE THREAD

**Issue by cytron201** [Microsoft/vsts-tasks#2213]
Hi,

Test agents have been running fine for a month then suddenly started crashing on VM Test Agent. I've updated to latest installs, but issues range from the DTAExecutionHost.exe Command window throwing an exception, to test runs completing with all tests failing (even when using past cuts of tests and web site code).

Something on the environment has changed to cause this, yet only windows updates have been performed on the Agents, which i assume would be very unlikely to affect?

Didn't realise this was the place for bugs, so had posted here, please see this for more details:

https://social.msdn.microsoft.com/Forums/en-US/99ff16cf-75b6-4ea1-8544-790b603abd28/coded-ui-framework-issues-with-virtual-machine-test-agents?forum=visualstudiogeneral

**Comment by SatishThareja** [comment]
Hi cytron201,

Please share the following logs to helps us debug this issue:
1.  C:\DtaLogs\DtaExecutionHost.exe.log (after clearing the older logs)
2. %temp%\TestAgentConfig.Log

Thanks
Satish

**Comment by cytron201** [comment]
[DTAExecutionHost.exe.txt
![cuit error](https://cloud.githubusercontent.com/assets/19473631/17621710/2e845cca-608d-11e6-87a5-1aa510c8d803.png)
](https://github.com/Microsoft/vsts-tasks/files/415236/DTAExecutionHost.exe.txt)
[TestAgentConfig.txt](https://github.com/Microsoft/vsts-tasks/files/415237/TestAgentConfig.txt)

All Attached. Have also checked the Domain Account we use for Testing, and password is not expired etc.

As mentioned, the only environmental changes seemed to be regular windows updates, it was 100% before this happened to both agents.

**Comment by SatishThareja** [comment]
@cytron201 Do you see this issue after agent machine reboot or does this happen otherwise as well?

**Comment by cytron201** [comment]
Yes I see this crash after a reboot, but if i am able to get the agent restarted, i still get the issue where it will fail all tests with a Click Command when i run a build.
It's as if the framework is blocked from interacting with the Web page. I will run the same build immediately afterwards and it would then pass. Again, and it might fail again.

**Comment by cytron201** [comment]
At other times, after running builds, i will just see the "DTAExecutionHost.exe has stopped working" message, and no black screen with that exception, or any other open windows.

**Comment by SatishThareja** [comment]
We are working on the fix for crash after agent reboot and the fix shall be available soon.
Can you check the UI screenshots for failed tests to see if something is blocking the test execution?

**Comment by cytron201** [comment]
Great news thanks. Would i build that from this GIT project or would it be released as a new Agent installer exe to be downloaded from the usual TFS downloads?

Failed test executions just show me the Windows Lock screen on the VM, (which i suspect might be the issue), but then why would they have worked then stopped working? Is DTAExecutionHost.exe linked to logging into the VM to run the tests?

**Comment by rkapso** [comment]
I am also seeing the DTAHost crash after a reboot, is this expected only first time after a reboot or the error persists if so is there any workaround not to hit this issue.

**Comment by SatishThareja** [comment]
@cytron201 The test agent fix is now available on VSTS. If you are using a on-premise TFS, you will need to patch the executable. Please drop an email to  devops_tools@microsoft.com, so that we can share the fix with you.

**Comment by cytron201** [comment]
@SatishThareja Many thanks, that is great news. I tried to email the address supplied and it was rejected by the postmaster as it is an external company email. Have you another address i can contact please?

Also, I am trialing TFS15 on another server. Will this exe also work on a build agent for that or is there a completely different version?

**Comment by SatishThareja** [comment]
@cytron201 I have received your email and will share the fix with you.

**Comment by SatishThareja** [comment]
@cytron201 Sent you an email sharing the fix.

**Comment by SatishThareja** [comment]
@cytron201 Did you get unblocked after patching the executable?

**Comment by sailajacharan** [comment]
HI @SatishThareja  we are facing the same issue for more than a month. We got our test agents imaged and the issue was resolved for couple of days, but now its back.

Could you plz send us the fix that you have, we would like to give it a try. Thank you.

Can I send an email to devops_tools@microsoft.com to get the fix.

**Comment by cytron201** [comment]
@SatishThareja I am rerunning builds tomorrow having re-imaged my VMs so i'll feedback soon.

**Comment by SatishThareja** [comment]
@sailajacharan Sure. Please send an email to devops_tools@microsoft.com, we will share the fix with you.

**Comment by sawpresto** [comment]
Thanks for the patched DTAExecutionHost, Satish! I'm wanting to run the exe on a Windows 7 Ultimate machine, but it looks like the scheduled task, DTAConfig, that starts the DTAExecutionHost.exe, pops up with taskeng.exe and sits there stuck for a couple of minutes then closes. The DTAExecutionHost doesn't pop up. I know that Task Scheduler itself works because I can have it open Chrome or MSTest (opens then closes quickly) so it has to do with the DTAExecutionHost executable. Do you know how to fix that?

**Comment by SatishThareja** [comment]
@sawpresto Test agent installation requires Windows 7 with .Net 4.5. Please make sure these prerequisites are met for test agent machine. https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/DeployVisualStudioTestAgent

**Comment by Dev25141** [comment]
Hello SatishThareja,
Many thanks for addressing the "DTAExecutionHost not working" issue. Would you please guide me where I can find the test agent fix. 

Appreciate your direction on this
Dev

**Comment by SatishThareja** [comment]
@Dev25141 
Please follow the steps below to fix this issue:
1. Set Update Test Agent option to true in Deploy Test Agent Task.
2. Queue a new build. While queuing the build, add a build variable '__ __ShouldPatchMSI__ __' and set it to 'true'. (remove spaces in the parameter name)

![image](https://cloud.githubusercontent.com/assets/15210210/18301058/0d74031e-74ec-11e6-9dea-a769c79dbc06.png)

After the Deploy Test Agent Step completes, DTAExecutionHost executable will be updated with the required fix and should not throw exception on reboot.

**Comment by Dev25141** [comment]
Hi SatishThareja, Thank you for the quick response. 
I tried the above fix and build log says "Test Agent Location input is only supported for on premise TFS. Clear this input value and try again." 

Please advise
Thanks
Dev

**Comment by Dev25141** [comment]
FYI... our company has TFS Online (cloud based). So for TFS online, it automatically applies the fix? or Is there something I need to do. Appreciate your input 

Thanks

Dev

**Comment by Dev25141** [comment]
Hi SatishThareja, Thank you for the quick response.
I tried the above fix and build log says "Test Agent Location input is only
supported for on premise TFS. Clear this input value and try again."

Please advise
Thanks
Dev

**Comment by SatishThareja** [comment]
@Dev25141 If you are on VSTS (TFS online), you just need to enable Update Test Agent option in Deploy Test Agent task. This will automatically update your test agent during the deployment.

**Comment by Dev25141** [comment]
Perfect!
Thank You Satish! You have been very very helpful

Dev

**Comment by m-martin** [comment]
Hi Satish,
after applying your fix to our on-premise installation, I keep getting another error when executing a coded UI test:
![error on test execution](https://cloud.githubusercontent.com/assets/1142712/18343168/8b041226-75b2-11e6-8148-27a7c1b458a4.png)

In the Windows application event log, the following error appears for source VSTTExecution:
> The description for Event ID 0 from source VSTTExecution cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
>
> If the event originated on another computer, the display information had to be saved with the event.
>
> The following information was included with the event: 
>
(DTAAgentExecutionService, PID 3284, Thread 7) AgentExecutionService: TrySubscribeToAgentHostExitedEvent threw exception:System.InvalidOperationException: Sequence contains no elements
>    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
>    at Microsoft.VisualStudio.TestService.AgentExecutionService.AgentExecutionService.TrySubscribeToAgentHostExitedEvent()

> the message resource is present but the message is not found in the string/message table

Do you (or someone else) know how to fix?

Thanks.

**Comment by SatishThareja** [comment]
@m-martin It looks like there is a gap between the patch and already installed test agent.
Can you share a few details to help us narrow down this issue:
- TFS version
- Test Agent version

Before applying the patch, at what point during test execution did you observe the crash?

Thanks
Satish

**Comment by m-martin** [comment]
@SatishThareja We are using TFS version 14.102.25423.0.
The original version of the DTAExecutionHost was 14.95.25118.0.

Before I applied your patch, we observed the crash after restarting the test machine.
After applying your patch, we observed the crash whenever executing a remote test (using a TFS build with the "Run Functional Tests" build step).

Thanks.

**Comment by SatishThareja** [comment]
@m-martin It looks like you were using Test Agent Update 2 version, so applying the executable patch will result in error mentioned by you in previous comments. 
You can follow the steps below to fix this issue:
1. Set Update Test Agent option to true in Deploy Test Agent Task.
2. Queue a new build. While queuing the build, add a build variable '__ ShouldPatchMSI __' and set it to 'true'. (remove spaces in the parameter name)
![image](https://cloud.githubusercontent.com/assets/15210210/18381405/aa006e94-7699-11e6-879d-2ebf2df39465.png)


After the Deploy Test Agent Step completes, DTAExecutionHost executable will be updated with the required fix and should not throw exception on reboot.

**Comment by ShakedTBolt** [comment]
Satish,
We are using tfs 15 rc 2 with agent of 2015 update 3, and we have the same issue. can you please send me the patch? or refer it to it.

Thanks!

**Comment by Selvaraj1989** [comment]
@SatishThareja I am also facing the same issue of crashing the DTAExecutionHost.exe. Could you please help me by pointing out the patch link.
![capture](https://cloud.githubusercontent.com/assets/22670803/19649599/0bba7e92-9a24-11e6-9fab-db0b507b04ab.JPG)
