### ISSUE TITLE
VSTF_TESTAGENT 14.0.24712 needed

### ISSUE THREAD

**Issue by codelabexpert** [Microsoft/vsts-tasks#2227]
Hello,
for the task "deploy test agent" I need a new version of vstf_testagent.exe because I want to take advantage of the task "functional test run" using test plans.
But it is only possible to download vstf_testagent.exe 14.0.23107 which doesn't support functional test runs using test plans.
What should I do?

Thank you!

**Comment by SevenBitSignature** [comment]
We expericenced the same problem (TFS 2015 Update 3). The download link given in the help text (http://go.microsoft.com/fwlink/?LinkId=536423) is incorrect in that it downloads an outdated version.

You can get the latest version here:
https://www.visualstudio.com/downloads/download-visual-studio-vs
Tools for Visual Studio 2015 -> Agents for Visual Studio 2015 Update 3

**Comment by codelabexpert** [comment]
That's great! Thank you :-)

**Comment by atinb** [comment]
Thanks for reporting. We will fix the bug
