### ISSUE TITLE
Archive Files task is geting wrong working directory

### ISSUE THREAD

**Issue by Alexander-Taran** [Microsoft/vsts-tasks#2242]
`var winSevenZipLocation =  path.join(tl.cwd(), '7zip/7z.exe');`

this line translates into this command `C:\tfs_agent\_work\1\s\7zip\7z.exe` when tool runs. Instead of `C:\tfs_agent\_work\_tasks\ArchiveFiles_d8b84976-e99a-4b86-b885-4849694435b0\1.0.2\7zip\7z.exe`

Seems like when task is created - CWD points to source directory

**Comment by bryanmacfarlane** [comment]
Yes, by default if not specified the current working directory of a task is the root of the repo.

Jason, __dirname would be the location of the script.

See if path.join(__dirname, '7zip/7z.exe'); works

**Comment by Alexander-Taran** [comment]
Yep, just the right kind of magic!!! 
Will you fix it in repo?
or should I create a PR?

**Comment by bryanmacfarlane** [comment]
A PR is fine.  thanks

You may want to also PR into releases/104 since that's the sprint that's about to go out.

**Comment by DavidStaheli** [comment]
Jason is away so I'll test this, merge it, and get it into the releases/m104 branch.  Thanks, guys!

**Comment by bryanmacfarlane** [comment]
https://github.com/Microsoft/vsts-tasks/pull/2243

**Comment by bryanmacfarlane** [comment]
Java team did archive task

**Comment by DavidStaheli** [comment]
Fixed by #2243
