### ISSUE TITLE
Ignored tests marked as "Passed"

### ISSUE THREAD

**Issue by LiohAu** [Microsoft/vsts-tasks#2247]
Hello,

In my build I currently have a task that run nunit tests, and in these tests, I have an Assert.Ignore() when the mobile device on which the test should execute is not connected to the mac executing nunit.

After the execution, I use the publish test results task to publish the .xml file, but when I go in the "Tests" tab of the build, I see all the "ignored" tests as "Passed". Shouldn't that tab support more than a binary passed/failed status (like in microsoft test manager) ?

PS : Sorry if it's not related to the publish task.

Edit: By the way, is there a task that could be used to retrieve the test configurations from MTM and execute my nunit task for each on each device passing the configuration as env var ?

**Comment by atinb** [comment]
Can you please attach a output xml file generated by NUnit? Thanks!

**Comment by LiohAu** [comment]
You will find one here : https://www.dropbox.com/s/nz0typxzlq6gdz8/TestResults-Specflow.xml?dl=0

**Comment by tanvi-soni** [comment]
Can you tell me which version of agent you are using and is your machine Windows/Linux. And are you using Windows (legacy) agent?

**Comment by LiohAu** [comment]
I am using the mac/linux agent.

**Comment by tanvi-soni** [comment]
Can you try running the build against latest agent on VSTS. That should resolve the issue.

**Comment by tanvi-soni** [comment]
Did you try running the build against the latest agent on VSTS.

**Comment by LiohAu** [comment]
Not yet, will do it in few days.

**Comment by tanvi-soni** [comment]
That should be fine. You can the latest agent from github. https://github.com/Microsoft/vsts-agent/releases

**Comment by SatishThareja** [comment]
@LiohAu Did you get unblocked after using the latest agent?

**Comment by LiohAu** [comment]
Yes, I just checked and it looks like the issue is solved.
