### ISSUE TITLE
Request for AzureServiceBus Task

### ISSUE THREAD

**Issue by philcarbone** [Microsoft/vsts-tasks#2251]
I may contribute this myself, but in case someone has the know how to leverage existing Azure Tasks, I figured I'd ask first. I'd love to fire up some custom message to my AzureServiceBus (not the messages built into VSTS). These messages would be specific based on task variables, etc. during a build or release. Anyway this is just a request to create a Task for Custom AzureServiceBus Messages that can take build/environment variables in the body.

**Comment by RoopeshNair** [comment]
@philcarbone 
You can take a look at existing Azure tasks in this repo, We encourage contributions.

Adding this to our backlog, However, we're locked with our plans for the current year.
