### ISSUE TITLE
Xcode task tests are failing

### ISSUE THREAD

**Issue by HSAR** [Microsoft/vsts-tasks#2254]
I am running CI over recent feature work in preparation for a merge and find that two L0 tests are reported as failing in CI:

- run Xcode build, signing with P12 and provisioning profile
- run Xcode build, signing with P12 only, no provisioning profile

Checking the build history, they have been failing since Monday 8th August.

**Comment by madhurig** [comment]
@HSAR: Thanks for reporting, I know about this. These two tests fail on Windows but work on Mac and I haven't been able to track down why. Seems like string.indexOf(string) behaves differently when the tests are run on Windows. I will disable them on Windows till I track down the issue.
