### ISSUE TITLE
VSO Run Functional Tests , requires user to be logged on

### ISSUE THREAD

**Issue by edwinash** [Microsoft/vsts-tasks#2255]
In our Tfs build we have a Deploy VS agent Task. This task uses a Test Machine group and group uses a particular account that has local admin on the machine and is project admin in TFS.
This Tasks deploys and configures the Test agent correctly with the same user on the remote machine but it will kick you off the remote session if you are logged on.
Our issue is that when we run the Functional Test Task, the test fails every single time except if you re-log on to the remote machine with the user account.
When re-logged on you can see a cmd window with the DTAExecutionHost.exe running and then the Tests run correctly.
Why does the remote machine require the user to be logged on ?
Why do the tests fail unless logged on ?

**Comment by allendm-msft** [comment]
@edwinash can you try logging into the machine manually yourself? We have noticed that some of our users have some popups on logon that block the UI and not allowing us to start our services unless the login is completed.

**Comment by edwinash** [comment]
Hi , I tried as suggested and there was no UI prompts only the DTAExecutionHost.exe  cmd window is open.

**Comment by allendm-msft** [comment]
One of the common issues we see is that the active session of the logged on user gets locked after some duration. Can you have a look at [this stackoverflow answer ](http://stackoverflow.com/questions/11744526/is-it-possible-to-run-coded-ui-tests-without-having-to-connect-via-remote-deskto) and see if it applies to you too

**Comment by edwinash** [comment]
Thank you for the update , we ended up resolving the issue by moving to selenium grid to auto run the tests.
