### ISSUE TITLE
Deploy TestAgent in interactive mode does not log user on after reload

### ISSUE THREAD

**Issue by Olafski** [Microsoft/vsts-tasks#2258]
Hi,

I'm trying to get my deployment to run a SpecFlow test suite. Most of the tests don't use the UI and those tests work fine when I don't click the "interactive mode" checkbox in the Deploy TestAgent task.

However, some tests require a browser (using Selenium) and so I enabled the checkbox. As I understand it, this will configure automatic logon and disable the screensaver, then reboot so the machine logs on automatically with the configured user.

What actually happens, is that the machine (a Hyper-V VM running Windows 10) reboots but does not seem to log on. The tests do seem to run when I am already logged on to the machine in Hyper-V manager, but I need this to be part of my nightly deployment, during which time I won't be logged on.

If I log on manually after a reboot, I see a black window with DTAExecutionHost.exe in it. 

I'm using TFS 2015 update 2 on premise, if that helps.

[DTAExecutionHost.exe.log.txt](https://github.com/Microsoft/vsts-tasks/files/414864/DTAExecutionHost.exe.log.txt)

**Comment by allendm-msft** [comment]
@Olafski can you have a look at https://github.com/Microsoft/vsts-tasks/issues/2255

**Comment by SatishThareja** [comment]
@Olafski Did you get unblocked after following #2255?

**Comment by SatishThareja** [comment]
Closing this thread due to no response.
