### ISSUE TITLE
Poor Logging in ArchiveFiles Task

### ISSUE THREAD

**Issue by technicallyerik** [Microsoft/vsts-tasks#2259]
Right now if there is a failure in the ArchiveFiles task, a message is output to "see log for details", but the execution result is never actually logged anywhere.

```
function handleExecResult(execResult, archive) {
    if (execResult.code != tl.TaskResult.Succeeded) {
        var message = 'Archive creation failed for archive file: ' + archive + ' See log for details.';
        failTask(message);
    }
}
```

This is the only thing that appears in the logs:

> 2016-08-11T20:17:31.2572436Z [command]D:\agent\_work\1\s\7zip\7z.exe a -tzip D:\agent\_work\1\s\Test.zip files are here
> 2016-08-11T20:17:31.2572436Z ##[debug]task result: Failed
> 2016-08-11T20:17:31.2572436Z ##[debug]Processing: ##vso[task.issue type=error;]Archive creation failed for archive file: D:\agent\_work\1\s\Test.zip See log for details.
> 2016-08-11T20:17:31.2572436Z ##[error]Archive creation failed for archive file: D:\agent\_work\1\s\Test.zip See log for details.

This makes debugging unnecessarily difficult.

**Comment by DavidStaheli** [comment]
Thanks, technicallyerik.  We will address this promptly.

**Comment by bryanmacfarlane** [comment]
Java team did archive task.

**Comment by jasholl** [comment]
Thanks for reporting.  Fixed with https://github.com/Microsoft/vsts-tasks/pull/2330
