### ISSUE TITLE
Publish build artifact error misleading when share does not exist

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-tasks#2261]
When the share does not exist, the task errors with:
>shell.js: internal error 
RangeError: Maximum call stack size exceeded

The error also likely occurs if the svc account doesn't have permission to view the share.

Additional details @ https://social.msdn.microsoft.com/Forums/vstudio/en-US/eb91ab94-f359-4b47-996e-0e2fce835273/publish-build-artifacts-step-fails-when-using-artifact-type-fileshare-tfs-2015?forum=tfsbuild

**Comment by bryanmacfarlane** [comment]
interesting ...

**Comment by ericsciple** [comment]
Duplicate of https://github.com/Microsoft/vsts-tasks/issues/2098
