### ISSUE TITLE
Archive Files task doesn't work

### ISSUE THREAD

**Issue by technicallyerik** [Microsoft/vsts-tasks#2267]
The Archive Files task doesn't work on our Windows build agent.

The task is trying to execute 7zip from our sources directory:  `D:\agent\_work\1\s\7zip\7z.exe`

However, at no point is 7z.exe copied to this location.  I do see it here:  `D:\agent\_work\_tasks\ArchiveFiles_d8b84976-e99a-4b86-b885-4849694435b0\1.0.2\7zip`.

Either this task is not correctly copying 7zip to our source directory, or not referencing the correct directory when trying to execute 7zip.

**Comment by bryanmacfarlane** [comment]
Yes.  Dupe: https://github.com/Microsoft/vsts-tasks/issues/2242

PR was here: https://github.com/Microsoft/vsts-tasks/pull/2243

David, we should patch the service.

**Comment by DavidStaheli** [comment]
Apologies for the delay.  The fix will be available everywhere in production on Wednesday, August 17.
