### ISSUE TITLE
Azure File Copy:System.Management.Automation.RuntimeException: Unable to get FQDN for all resources in ResourceGroup

### ISSUE THREAD

**Issue by batcoder619** [Microsoft/vsts-tasks#2271]
I have setup an Azure File Copy task to copy build files to an Azure VM which is under a Dev resource group. Upon creating release I get below error. Not sure what to do next or how to fix it.

> 2016-08-15T06:07:56.7253114Z ##[debug]System.Management.Automation.RuntimeException: Unable to get FQDN for all resources in ResourceGroup : 'DevResourceGroup'
>2016-08-15T06:07:56.8223047Z ##[debug]Completed Azure File Copy Task for Azure VMs Destination
>2016-08-15T06:07:56.8333110Z ##[error]System.Management.Automation.RuntimeException: Unable to get FQDN for all resources in ResourceGroup : 'DevResourceGroup'
>2016-08-15T06:07:56.9153011Z Finishing task: AzureFileCopy
>2016-08-15T06:07:56.9173003Z ##[error]System.Exception: Task AzureFileCopy failed. This caused the job to fail. Look at the logs for the task for more details.
>2016-08-15T06:07:56.9173003Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Worker.JobRunner.Run(IJobContext jobContext, IJobRequest job, IJobExtension jobExtension, CancellationTokenSource tokenSource)

**Comment by fijiancoder** [comment]
Please note same error appears when using **Azure Resource Group Deployment** task with action **Select Resource Group**

**Comment by kalim81** [comment]
Am getting the same error. All vm's in my resource group are RM and not classic. The VM's do not have a public IP. They have a load balancer in front of them which does have a public IP. I have tried using machine names, tags and IP (internal 10.0.0....) address.

**Comment by thdeltei** [comment]
I have the same problem when trying to provision a resource group through VSO, it successfully provision the resources but the build fails because of this error at the end
`Unable to get FQDN for all resources in ResourceGroup : `
Does it mean that I need to add a public IP in order to get rid of the error?

**Comment by vincentdass** [comment]
@thdeltei , public IP is required to resolve this issue.

**Comment by SQLSuperGuru** [comment]
My VMs have public IPs as well as Fully qualified domain names set up, but I am running into the same issue - Unable to get FQDN for all resources in ResourceGroup :

**Comment by vincentdass** [comment]
@SQLSuperGuru , Can u share the full log (Build/Release with system.debug mode **true**) ?

**Comment by vincentdass** [comment]
@thdeltei , Did you get your issue resolved ? If so, I can close this thread.

**Comment by thdeltei** [comment]
I haven't got around testing it just yet, but feel free to close the issue, thanks

**Comment by jaquelinecramos** [comment]
My VMs have public IPs as well as Fully qualified domain names set up, but I am running into the same issue 

 ##[debug]Trying to get FQDN for the azureRM VM resources from resource Group 
Index operation failed; the array index evaluated to null.

**Comment by nuvulanaresh** [comment]
I am still facing this issue below. I am trying to copy artifacts from my Azure Repos to a VM using Az Pipelines. VM's don't have a public IP and our policy does not allow to create one. Please let me know if there is any alternative?
"Unable to get FQDN for all resources in ResourceGroup".
