### ISSUE TITLE
PublishBuildArtifacts task taking long time in copying large files

### ISSUE THREAD

**Issue by dwaheed** [Microsoft/vsts-tasks#2277]
PublishBuildArtifacts task is taking more than an hour to copy about 80GB of data to a File Share.
VSTS Default XAML takes only about 14 minutes to copy the same data to the same share.

**Comment by bryanmacfarlane** [comment]
hi pri

**Comment by ericsciple** [comment]
https://github.com/Microsoft/vsts-tasks/pull/2282

**Comment by bryanmacfarlane** [comment]
This is fixed in the 105 sprint rollout.
