### ISSUE TITLE
Question best way for workflow  

### ISSUE THREAD

**Issue by kardinal3000** [Microsoft/vsts-tasks#2280]
Hello guys,
I have one VM for testing also I have Test Plan and Test Suite. I need run my tests three times but with different Test Configurations.

How I implemented it now: 
![pic1](https://cloud.githubusercontent.com/assets/18549964/17697727/27487f1a-63bf-11e6-965b-456c15be6b31.png)

It works well but when my Build Agent has exceeded the maximum execution time of one hour the next steps are aborted and the tests that were working on current step return the result. That's good and obvious.

My question is: 
How can I create if it possible of course! Workflow with one task "Deploy Test Agent" and three tasks "Run Functional Tests" successively. Maybe you have tips or suggestions about it

![pic2](https://cloud.githubusercontent.com/assets/18549964/17698200/5a1a696e-63c2-11e6-87d5-6faed9fc6bdb.png)

**Comment by atinb** [comment]
This assumes that most of the time is being spent in the Deployment tasks which I doubt. Can you please confirm? Thanks!

**Comment by kardinal3000** [comment]
Yes. I confirm it. Deployment tasks usually take too much time. 
If we talk about "Visual Studio Test Agent Deployment" the working process of that task is clear but it is not flexible and universal solution. 
About "Run Funtional Tests" task. Yes, it works good. But it would be great to extend the functionality. I mean add the ability to select multiple Tests Configurations simultaneously. Anyway, I think that in TFS15 of these issues have been resolved in other way.

So, back to my question is it correct to increasing the working time of the build agent. I mean this value "Build job timeout in minutes" in General tab? or exist other way. 
How can I get Test Results without increasing time job for build agent and don't use a lot of the same tasks as I mentioned above. Thanks!

**Comment by atinb** [comment]
@kardinal3000 
We are looking at removing the need to have a Deploy task before Run task. Until then, you will need to increase the Build timeout to enable all your tests to complete. Thanks!

**Comment by SatishThareja** [comment]
@kardinal3000 You can try disabling 'Update Test Agent' option in Deploy Test Agent Task to reduce the agent deployment time.
