### ISSUE TITLE
Visual Studio Test Agent Deployment task fails on all subsequent builds after reboot

### ISSUE THREAD

**Issue by baheath** [Microsoft/vsts-tasks#2281]
I have a build definition set up including the Visual Studio Test Agent Deployment task. I created a machine group with a single machine in it. The first time this build is executed (when the test machine is clean and has never had a test agent deployed to it), everything works fine, until the test machine is rebooted. Then, all subsequent builds fail at this task.

### Build error:
Start test agent process:
Test agent process started successfully.
Service Configuration:
Configured service successfully.
Start Service:
Service start is in progress.
Service start is in progress.
Service start is in progress.
Service start is in progress.
Service start is in progress.
Service start is in progress.
Service start is in progress.
Service start is in progress.
Service start is in progress.
Stderr : Service VSTTAgent was not found on computer '.'.
The specified service does not exist as an installed service
Exception : Could not complete operation as the timeout expired.
Exit code : -1
Return code received : -1 

### Logs:
[logs.zip](https://github.com/Microsoft/vsts-tasks/files/420972/logs.zip)

**Comment by tanvi-soni** [comment]
Hi, 
can you add variable system.debug in your build definition and set it to true. Please queue a new build with system.debug set and share build logs, testagentconfig logs and dtalogs. You can share the logs on the emailId:  devops_tools@microsoft.com

**Comment by baheath** [comment]
The requested logs have been sent to devops_tools@microsoft.com.

**Comment by tanvi-soni** [comment]
I have received the logs, will get back to you.

**Comment by tanvi-soni** [comment]
Can you try running the deploy test agent task with "interactive process" box as unchecked. Let me know if it passes.
And did you make any changes to the build definition including login credentials, besides rebooting the test agent machine.

**Comment by baheath** [comment]
I ran a build with Interactive Process unchecked, and the result was the same. (Failed with the same error.)

No changes have been made to the machine. This happens every time (confirmed on 3 VMs):
1. Create new VM
2. Run build (passes)
3. Run build (passes)
[Builds will pass until...]
4. Reboot VM (no changes made to VM; simply shutdown and boot again)
5. Run build (fails on deploy agent step)
6. Run build (fails on deploy agent step)
[Builds will always fail on deploy agent step]

Also, I see this error in the Windows Event Log:
(DTAAgentExecutionService, PID 4048, Thread 4) AgentExecutionService: Exception occurred while starting the execution host: System.ServiceModel.AddressAlreadyInUseException: Cannot listen on pipe name 'net.pipe://localhost/' because another pipe endpoint is already listening on that name. ---> System.IO.PipeException: Cannot listen on pipe name 'net.pipe://localhost/' because another pipe endpoint is already listening on that name. --- End of inner exception stack trace --- at System.ServiceModel.Channels.PipeConnectionListener.Listen() at System.ServiceModel.Channels.BufferedConnectionListener.Listen() at System.ServiceModel.Channels.ExclusiveNamedPipeTransportManager.OnOpen() at System.ServiceModel.Channels.TransportManager.Open(TransportChannelListener channelListener) at System.ServiceModel.Channels.TransportManagerContainer.Open(SelectTransportManagersCallback selectTransportManagerCallback) at System.ServiceModel.Channels.TransportChannelListener.OnOpen(TimeSpan timeout) at System.ServiceModel.Channels.ConnectionOrientedTransportChannelListener.OnOpen(TimeSpan timeout) at System.ServiceModel.Channels.NamedPipeChannelListener`2.OnOpen(TimeSpan timeout) at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout) at System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpen(TimeSpan timeout) at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout) at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout) at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout) at Microsoft.VisualStudio.TestService.AgentExecutionService.TokenSender.Start() at Microsoft.VisualStudio.TestService.AgentExecutionService.AgentExecutionService.OnStart(String[] args)

However, I don't see anything using that pipe:
PS C:\Windows\system32> [System.IO.Directory]::GetFiles("\\.\\pipe\\")
\\.\\pipe\\lsass
\\.\\pipe\\protected_storage
\\.\\pipe\\ntsvcs
\\.\\pipe\\scerpc
\\.\\pipe\\plugplay
\\.\\pipe\\Winsock2\CatalogChangeListener-320-0
\\.\\pipe\\epmapper
\\.\\pipe\\Winsock2\CatalogChangeListener-1dc-0
\\.\\pipe\\LSM_API_service
\\.\\pipe\\eventlog
\\.\\pipe\\Winsock2\CatalogChangeListener-3b0-0
\\.\\pipe\\Winsock2\CatalogChangeListener-258-0
\\.\\pipe\\keysvc
\\.\\pipe\\atsvc
\\.\\pipe\\Winsock2\CatalogChangeListener-15c-0
\\.\\pipe\\DAV RPC SERVICE
\\.\\pipe\\wkssvc
\\.\\pipe\\srvsvc
\\.\\pipe\\browser
\\.\\pipe\\1f19e1c5-ddbb-4578-ba06-b349f8b01fd8
\\.\\pipe\\DeploymentExecution
\\.\\pipe\\trkwks
\\.\\pipe\\Winsock2\CatalogChangeListener-250-0
\\.\\pipe\\W32TIME_ALT
\\.\\pipe\\MsFteWds
\\.\\pipe\\TermSrv_API_service
\\.\\pipe\\PIPE_EVENTROOT\CIMV2SCM EVENT PROVIDER
\\.\\pipe\\winreg
PS C:\Windows\system32>

**Comment by SatishThareja** [comment]
@baheath Are you seeing any error messages reported in Event Viewer after you reboot the test agent machine?

**Comment by baheath** [comment]
@SatishThareja I don't see any errors specifically after rebooting. I _do_ see the error I mentioned in my previous comment immediately after the deploy agent task runs, and also if I try to start the service manually.

**Comment by SatishThareja** [comment]
@baheath When you hit this issue, can you check if the service DTAAgentExecutionService is already running?
It may be possible that another instance of service configured with some other account might be causing the contention here.

**Comment by baheath** [comment]
@SatishThareja I can recreate the pipe error in the Event Viewer just by starting the service manually. I go to Services, verify that the DTAAgentExecutionService is Stopped. Then, if I manually start it, I get an error dialog saying:

---------------------------
Services
---------------------------
The Visual Studio Distributed Test Automation Service service on Local Computer started and then stopped. Some services stop automatically if they are not in use by other services or programs.
---------------------------
OK   
---------------------------

I can then see a new error entry in the Event Viewer (the AddressAlreadyInUseException mentioned previously).

**Comment by SatishThareja** [comment]
@baheath Can you try executing the powershell command ' Get-Service *DTA*' as administrator and share the results?
Also, can you disable auto restart of DTAAgentExecutionService before restarting the VM and re-run the scenario i.e reboot and queue build ?

**Comment by baheath** [comment]
@SatishThareja 
#### Requested command:
```
Windows PowerShell
Copyright (C) 2013 Microsoft Corporation. All rights reserved.

PS C:\Windows\system32> Get-Service DTA*

Status   Name               DisplayName
------   ----               -----------
Stopped  DTAAgentExecuti... Visual Studio Distributed Test Auto...


PS C:\Windows\system32>
```

I also tried:

- Disabling restart of DTAAgentExecutionService on error
- Setting DTAAgentExecutionService to Manual

Both resulted in the same issue (and the same error in Event Viewer).

**Why is the agent using the pipe 'net.pipe://localhost/'?** (Error says "Cannot listen on pipe name 'net.pipe://localhost/' because another pipe endpoint is already listening on that name.") That isn't a normal pipe name to try to open; usually something like 'net.pipe://localhost/some_unique_id' is used.

**Comment by SatishThareja** [comment]
@baheath The agent uses a named pipe with an identifier after localhost in the url. This is a generic message that shows up for any pipe that already exists. Can we have a skype call to debug this issue? Please share your skype id over email to  devops_tools@microsoft.com and specify the time when you are avilable,so that I can schedule the call accordingly,

**Comment by baheath** [comment]
@SatishThareja I tried the same scenario outlined above with a Windows 10 vm and everything works as expected. So it seems that this is an issue with the agent deploying to Window 7.

**Comment by SatishThareja** [comment]
@baheath As you are unblocked, let us know if we can close this thread?

**Comment by OleksiyAntonov** [comment]
Colleagues, I have the same issue on Windows 7 Service Pack 1, german version.
I need to deploy test agent to this platform, could you please explain solution for Windows 7?
