### ISSUE TITLE
Support "full deployment" for resource groups

### ISSUE THREAD

**Issue by piquet-h** [Microsoft/vsts-tasks#2283]
If a template pulls a resource out, it should be deleted. That way users can commit code to remove obsolete accounts or assets by just removing them from the template. ie support "complete" deployment based on https://azure.microsoft.com/en-us/documentation/articles/resource-group-template-deploy/

**Comment by RoopeshNair** [comment]
Deployment mode option to do incremental / complete is on our backlog. It would be available some time towards end of the year.

**Comment by piquet-h** [comment]
Is there a link to the backlog where I can follow along?

**Comment by RoopeshNair** [comment]
Not sure if you can access our backlog which is on our vs.com account. If you're MSFT FTE then drop me a note and I share the backlog item with you
