### ISSUE TITLE
Additional Settings in SonarQube Begin Analysis

### ISSUE THREAD

**Issue by NikitaEgorov** [Microsoft/vsts-tasks#2288]
Please make field Additional Settings like multiLine
Very difficult to support long text line

`/d:sonar.ts.tslintconfigpath=$(Build.Repository.LocalPath)\src\tslint.json /d:sonar.cs.opencover.reportsPaths="$(Common.TestResultsDirectory)\opencover-coverage.xml" /d:sonar.cs.nunit.reportsPaths="$(Common.TestResultsDirectory)\test-results.xml"`

**Comment by bgavrilMS** [comment]
That makes sense, I'll look into it.

**Comment by NikitaEgorov** [comment]
@bgavrilMS can I do it by myself via pull request?

**Comment by bgavrilMS** [comment]
Sure, if you send a PR I'm happy to review it, test it and merge it. Please read the how to contribute docs and please bump the task version in the task.json

**Comment by bgavrilMS** [comment]
I logged a bug on our internal VSTS account. We are looking at doing this in a few sprints, when we plan to move the build tasks into a separate extension.
