### ISSUE TITLE
Azure Powershell task: Error regarding multi-factor authentication

### ISSUE THREAD

**Issue by efridman** [Microsoft/vsts-tasks#2290]
We have an "Azure PowerShell" task in our VSTS release pipeline that fails intermittently with this error: 

##[error]AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access 'XXX'.

The task is configured with an Azure Classic connection type and a dedicated organization account with MFA disabled.

This error usually disappears after one or two retries of the pipeline, without any additional changes.
We have several similar pipelines and we get this error in at least one of them daily, so this is becoming a big nuisance.

**Comment by kmkumaran** [comment]
@efridman , is MFA authentication enabled in your organization? If so, using it in automated flow will be a problem. If you need Azure classic connection you can consider moving to cert based authentication. If you can move to Azure RM connection, you can consider using spn based authentication.

**Comment by efridman** [comment]
@kmkumaran We're only using MFA for Azure Administrators. MFA is not enabled for user accounts and the account we're using for the VSTS service endpoint, in particular.

We can't switch to an Azure RM connection for these scripts right now, since we use the **Get-AzureRMRoleAssignment** cmdlet and we then run into this problem - https://github.com/Azure/azure-powershell/issues/1896

We can try using cert-based authentication and see if that helps.

**Comment by kmkumaran** [comment]
@efridman did cert endponts help you?

**Comment by efridman** [comment]
@kmkumaran No, when using a cert endpoint the Azure PS task fails with this error: 
**##[error]Run Login-AzureRmAccount to login.**

This occurs before any script code is run.

**Comment by kmkumaran** [comment]
@efridman - Does your script have AzureRM commands? The login-AzureRmAccount will be required only if you have Azure RM commands. Cert based authentication works only with Azure Classic commands.

**Comment by efridman** [comment]
@kmkumaran Yes, we have AzureRM cmdlets in the script. So, what are our options then?
We can't use cert-based authentication, we can't use SPN-based authentication (bug with cmdlets to manage roles), and we get this MFA bug in credential-based authentication.

**Comment by kmkumaran** [comment]
@efridman - Given that your script requires AzureRM and your org has Multi factor auth, SPN based authentication will be the correct way. The issue you referenced related to AzureRMRoleassignment is marked closed. If so, can you try with SPN based auth?

**Comment by kmkumaran** [comment]
@efridman - Did you try with SPN based auth? Do you need any further assistance from us?

**Comment by efridman** [comment]
@kmkumaran - No, SPN auth doesn't work. The issue I referenced was closed in August and the VSTS hosted agents are still running Azure PS 1.3.2 which is several months old.

Regarding MFA
- we have MFA only for Azure admins
- the account we use in the Azure service endpoint in VSTS is not an admin and does not have MFA enabled
- this error is intermittent, it appears haphazardly in release tasks, and disappears after a retry without any changes

Looking at these symptoms it looks like a bug either in the VSTS tasks or the underlying Azure PS

**Comment by kmkumaran** [comment]
@efridman - I have opened an issue with Azure team on this regard. https://github.com/Azure/azure-powershell/issues/2984.
 
You might want to follow this issue, incase Azure team requires any additional data / logs to analyze this further.

**Comment by efridman** [comment]
@kmkumaran Thanks.

**Comment by kmkumaran** [comment]
@efridman - There is an ask for additional logs. Can you respond to the issue https://github.com/Azure/azure-powershell/issues/2984

**Comment by kmkumaran** [comment]
@efridman - Given that we are tracking the issue in Azure PS issues, I plan to mark this thread closed. Let me know if you are ok with it.
