### ISSUE TITLE
Sonar Build failed in TFS property "sonar.cs.fxcop.assembly" must be set and the project must have been built to execute FxCop rules.

### ISSUE THREAD

**Issue by dpadhya1990** [Microsoft/vsts-tasks#2291]
Hello 
I am trying to build sonar build in our TFS environment but getting below mention error 
Start Sonar-runner
ERROR: Error during Sonar runner execution
ERROR: Unable to execute Sonar
ERROR: Caused by: The property "sonar.cs.fxcop.assembly" must be set and the project must have been built to execute FxCop rules. This property can be automatically set by the Analysis Bootstrapper for Visual Studio Projects plugin, see: http://docs.codehaus.org/x/TAA1Dg.If you wish to skip the analysis of not built projects, set the property "sonar.visualstudio.skipIfNotBuilt".
ERROR:
ERROR: To see the full stack trace of the errors, re-run SonarQube Runner with the -e switch.
ERROR: Re-run SonarQube Runner using the -X switch to enable full debug logging.
the project(solution) is created in visual studio 2008 version and in our build server visual studio 2015 is installed so to paased this build i had mentioned /toolsversion:3.5 in msbuild argument 
Environment details
TFS 2015 update 1 (build server)
sonar version 4.5.1, sonar runner - 2.4, C# plugin 3.3  
CI build for the same solution is successful but sonar build is showing partially succeed
what could be the reason of this ? 

Regards
Dushyant Padhya

**Comment by bgavrilMS** [comment]
Hi Dushyant, 

Are you using the SonarQube build tasks? In that case you should not need to install the sonar runner anymore. 

Your SonarQube environment is very outdated. The C# plugin has been significantly changed in later versions. Please update the C# plugin to the latest version (5.3.2) and SonarQube to the latest LTS version - http://www.sonarqube.org/downloads/
