### ISSUE TITLE
Task: "Index Sources & Publish Symbols", support include/exclude pattern in Search pattern like in VSTest task

### ISSUE THREAD

**Issue by DanielTheCoder** [Microsoft/vsts-tasks#2298]
Include patterns start with ‘+:’, and exclude patterns with ‘-:’ (Default is include). For Javascript tests, this will point to .js files containing the tests. Folders/Files which are having ";" in their names should be given as ";;" in input.
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VsTest/README.md
Sample-input: **\bin\**\*.pdb;-:**\_lib\**;-:**\_repo\**;-:**\_app\**

**Comment by atinb** [comment]
I am not sure I understand. Did you want the help text to be modified?

**Comment by atinb** [comment]
Daniel, can you please let me know? Thanks!

**Comment by DanielTheCoder** [comment]
Sorry, missed to provide some essential information, I have updated the title.
Currently in VSTest task, exclude pattern is supported. It would be nice if also in the build task "Index Sources & Publish Symbols" exclude patterns would be supported.

**Comment by ericsciple** [comment]
It should work. Have you tried it?

**Comment by ericsciple** [comment]
@DanielTheCoder
