### ISSUE TITLE
Sonar build for TFS is failed says cannot find .pdb file 

### ISSUE THREAD

**Issue by dpadhya1990** [Microsoft/vsts-tasks#2299]
Hello 
Our sonar build (XAML Build) for TFS is failed with below mentioned error 
Start Sonar-runner

ERROR: Error during Sonar runner execution
ERROR: Unable to execute Sonar
ERROR: Caused by: Cannot find the .pdb file "C:\Builds\1\HORIZON\Sonar_RichClient\src\NET-WIN_EUR_OrderCareCM\OrderCare\OrderEntry\EntryChannel\RichClient.......\Referentials\Commercial\Rules\bin\Debug\Essilor.OrderCare.Referentials.Commercial.Rules.pdb" inferred from the property "sonar.cs.fxcop.assembly".
ERROR:
ERROR: To see the full stack trace of the errors, re-run SonarQube Runner with the -e switch.
ERROR: Re-run SonarQube Runner using the -X switch to enable full debug logging.
the project(solution) is created in visual studio 2008 version and in our build server visual studio 2015 is installed so to paased this build i had mentioned /toolsversion:3.5 in msbuild argument 
Environment details
TFS 2015 update 1 (build server)
sonar version 4.5.1, sonar runner - 2.4, C# plugin 3.3

CI build for the same solution is successful but sonar build is showing partially succeed with missing .pdb file 
what could be the reason of this ?

Regards
Dushyant Padhya

**Comment by bgavrilMS** [comment]
Hi Dushyant, 

As stated before, we do not provide support for this version of SonarQube / C# plugin as it is very old. The LTS version of SonarQube is 5.6 and the latest C# plugin is at version 5.3.2. If you are able to upgrade and still face problems, please log a issue again.
