### ISSUE TITLE
Help needed with a picklist

### ISSUE THREAD

**Issue by davesmits** [Microsoft/vsts-tasks#2307]
I am writing a task to automatically submit an app to an MDM envoriment. I have everything in basic working but I now have to fill in an App Id myself. I try to make this a picklist in the UI.

For me it's not really clear how the picklist is working and seeing two different approaches using dataBindingSource and sourceDefinitions.

The webservice to get this data is AAD protected. So I have a clientId, ClientSecret and TenantID. In my powershell script I use these variables to get the access token. these values above are stored in a connected account.

During the build the powershell script reads the values out the connectedAccount to get the access token and then performs the right calls.

How I do this for the picklists? someone that can help me in the right direction?

**Comment by bryanmacfarlane** [comment]
RM added the picklists.  Sriram can point you to documentation.

**Comment by GitHubSriramB** [comment]
dataSourceBindings is what we would recommend to use going forward for dropdown scenarios. sourceDefinitions are still supported but mainly from a backward compatibility perspective. We will not be doing any feature enhancements on top of sourceDefinitions.

We are in the process of documenting how to create custom endpoints. We will include details around dataSourceBindings in that.

In this thread, I mentioned how dataSourceBinding/dataSource work together:
https://github.com/Microsoft/vsts-tasks/issues/973

We currently do not support generating access token using the other details in the endpoint & use it in subsequent query to populate drop-down. Is it possible to pre-create an access token and provide it as part of the endpoint? If so, we should be able to use this pre-created token to query dataSources and populate drop-downs.

**Comment by davesmits** [comment]
Thanks. Generated tokens are valid for 12 hour so not going to work for me. Thanks will keep close watch if its going be solved
