### ISSUE TITLE
PowerShellOnTargetMachines task changes the LCM mode back to Push

### ISSUE THREAD

**Issue by sameer-kumar** [Microsoft/vsts-tasks#2312]
I'm trying to deploy my on-prem ASP.Net applications to target nodes using TFS 2015 Update 2. When RM executes "**Run PowerShell on Target Machines**" task which contains my DSC configuration script (to create app pool and IIS website using xWebAdministration module), it flips back the LCM's RefreshMode to 'Push' on target node.
Earlier, I configured these target nodes to pull mode so that they can pull custom resources from my DSC web based pull server.

Is this something known or am I missing something?
Thanks for your help!

**Comment by chshrikh** [comment]
@sameer-kumar the task does not set any LCM setting explicitly, unless the user script does it.

Here I am providing you a sample file copy DSC configuration and script, could you please run it on your box.
1) Set the required ( Pull ) LCM setting on target box
2) Provide the appropriate paths in task for init.ps1 and configuration.ps1
3) Execute the task and check the setting on target machine 
4) Let us know the result and detail logs for this exercise

#### Save this as init.ps1

$ConfigData = @{
    AllNodes = @(
         @{ NodeName = "*"},

         @{ NodeName = "localhost";            
            SourcePath = $env:SystemDrive + "\Test1\source.txt"
            DestinationPath = $env:SystemDrive + "\Test1\testing.txt"
          }         

    )
}

New-Item $env:SystemDrive\test1 -ItemType Container -Force
New-Item $env:SystemDrive\test1\test.txt -ItemType File -Force



------------------------------------------------------------------------------------------------
#### Save this as configuration.ps1

configuration FileCopy{

    Node $AllNodes.NodeName
    {

        File CopyTxtFile
        {
            Ensure = "Present"  
            Type = "File" 
            Recurse = $true
            SourcePath = $Node.SourcePath
            DestinationPath = $Node.DestinationPath   
            
        } 
    }

}

FileCopy -ConfigurationData $ConfigData -Verbose

**Comment by sameer-kumar** [comment]
Steps to set LCM on target node in PULL mode:

```
$configurationData=
@{
    AllNodes=
    @(
        @{
            NodeName='localhost'
            Roles=@('Web','Database')
        }
    )
}

[DscLocalConfigurationManager()]
Configuration LocalConfigurationManager
{
    Node $AllNodes.NodeName
    {
        Settings
        {
            RefreshMode = 'Pull'
            ConfigurationMode = 'ApplyAndAutoCorrect'
            RebootNodeIfNeeded = $True    
            RefreshFrequencyMins = 30 
        }
        
        ConfigurationRepositoryWeb DSCPullSrv
        {
            ServerURL = 'https://PullServer:8080/PSDSCPullServer.svc'
            RegistrationKey = '5ecc0ec3-bc14-48ba-9651-cbf183e52a0f'
            ConfigurationNames = @('ClientConfig')
        }
        
    }
}
LocalConfigurationManager -ConfigurationData $configurationData -OutputPath C:\Dsc\Mof-Verbose
 
Set-DscLocalConfigurationManager -Path C:\Dsc\Mof-Verbose 
```

Verify the LCM state on target node after above step:

```
PS C:\Users\sam> Get-DscLocalConfigurationManager


ActionAfterReboot              : ContinueConfiguration
AgentId                        : 880A9AF7-689E-11E6-80FE-005056A72860
AllowModuleOverWrite           : False
CertificateID                  : 
ConfigurationDownloadManagers  : {[ConfigurationRepositoryWeb]DSCPullSrv}
ConfigurationID                : 
ConfigurationMode              : ApplyAndAutoCorrect
ConfigurationModeFrequencyMins : 15
Credential                     : 
DebugMode                      : {NONE}
DownloadManagerCustomData      : 
DownloadManagerName            : 
LCMCompatibleVersions          : {1.0, 2.0}
LCMState                       : Idle
LCMStateDetail                 : 
LCMVersion                     : 2.0
StatusRetentionTimeInDays      : 10
PartialConfigurations          : 
RebootNodeIfNeeded             : True
RefreshFrequencyMins           : 30
RefreshMode                    : Pull
ReportManagers                 : {}
ResourceModuleManagers         : {}
PSComputerName                 : 
```

Next, trigger the deployment on this target node which contains your specified scripts.
Then re-run on target node and I get this:

```
PS C:\Users\sam> Get-DscLocalConfigurationManager


ActionAfterReboot              : ContinueConfiguration
AgentId                        : 880A9AF7-689E-11E6-80FE-005056A72860
AllowModuleOverWrite           : False
CertificateID                  : 
ConfigurationDownloadManagers  : {[ConfigurationRepositoryWeb]DSCPullSrv}
ConfigurationID                : 
ConfigurationMode              : ApplyAndAutoCorrect
ConfigurationModeFrequencyMins : 15
Credential                     : 
DebugMode                      : {NONE}
DownloadManagerCustomData      : 
DownloadManagerName            : 
LCMCompatibleVersions          : {1.0, 2.0}
LCMState                       : Idle
LCMStateDetail                 : 
LCMVersion                     : 2.0
StatusRetentionTimeInDays      : 10
PartialConfigurations          : 
RebootNodeIfNeeded             : True
RefreshFrequencyMins           : 30
RefreshMode                    : PUSH
ReportManagers                 : {}
ResourceModuleManagers         : {}
PSComputerName                 : 
```

**Comment by chshrikh** [comment]
@@sameer-kumar Could you please share the detail logs for same

**Comment by sameer-kumar** [comment]
sorry due to org. policies I am not authorized to share logs.
Do you know where are MOF files are sitting? That is my RM task contains a ps1 file which consists of DSC configuration. That means this task is compiling this into MOF and executing it. I want to look at this compiled output MOF. Do you know the location?
Thanks!

**Comment by chshrikh** [comment]
@sameer-kumar can we have a call to debug it further . Please share your mail id with us, so that I can set-up a call with you. You may mail your details to RM_Customer_Queries at Microsoft dot com

**Comment by chshrikh** [comment]
if issue is still there, please reach us at RM_Customer_Queries at Microsoft dot com .
