### ISSUE TITLE
Gradle test warning and no test results

### ISSUE THREAD

**Issue by bgavrilMS** [Microsoft/vsts-tasks#2318]
While building a Gradle project I am getting the following warning. I am also unable to find any test results. I am using the hosted agent. 

Unable to process logging event:##vso[results.publish type=JUnit;mergeResults=true;publishRunAttachments=true;resultFiles=C:/a/1/s/Bukkit/build/test-results/TEST-br.com.gamemods.minecity.bukkit.MineCityPluginTest.xml,C:/a/1/s/Core/build/test-results/TEST-br.com.gamemods.minecity.api.command.CommandTreeTest.xml,C:/a/1/s/Core/build/test-results/TEST-br.com.gamemods.minecity.api.command.MessageTransformerTest.xml,C:/a/1/s/Core/build/test-results/TEST-br.com.gamemods.minecity.api.StringUtilTest.xml,C:/a/1/s/Core/build/test-results/TEST-br.com.gamemods.minecity.api.world.BlockPosTest.xml,C:/a/1/s/Core/build/test-results/TEST-br.com.gamemods.minecity.api.world.ChunkPosTest.xml,C:/a/1/s/Core/build/test-results/TEST-br.com.gamemods.minecity.api.world.RegionPosTest.xml,C:/a/1/s/Core/build/test-results/TEST-br.com.gamemods.minecity.commands.CityCommandTest.xml,C:/a/1/s/Core/build/test-results/TEST-br.com.gamemods.minecity.datasource.sql.SQLSourceTest.xml,C:/a/1/s/Core/build/test-results/TEST-br.com.gamemo...

**Comment by tanvi-soni** [comment]
Can you share your build logs with us. Please mail them to devops_tools@microsoft.com. And can you try to publish a single test result file and see if it gives the same warning.

**Comment by bgavrilMS** [comment]
Hi @tanvi-soni  - I have tried with both a multi module gradle and a single module gradle build, so a single test result file gives the same result. This repros for me every time with the hosted agent. For example try to build https://github.com/bgavrilMS/TestGradle

Please confirm this does not repro for you before I send logs.

**Comment by nigurr** [comment]
@bgavrilMS Are you using "Legacy Windows Agent"? In some of the SUs, still the hosted agent is running on Legacy one. If yes, this issue has been fixed yesterday should be available in next few days.

**Comment by allendm-msft** [comment]
This has been fixed. Verify with latest windows legacy agent.
