### ISSUE TITLE
Question: $distributedTaskContext

### ISSUE THREAD

**Issue by crshnbrn66** [Microsoft/vsts-tasks#2320]
In the following Powershell script this variable is defined but I cannot seem to find what the value is supposed to be.   

I can get the Modules loaded, but cannot seem  to determine what tfs is passing to this script from the run functional tests task.

**Comment by ericsciple** [comment]
That is from the old problematic, closed source, undocumented, sealed, legacy powershell execution handler.

It would be better to use the recommended execution handlers: https://github.com/Microsoft/vsts-task-lib

**Comment by crshnbrn66** [comment]
does this mean that I need to update tasks for the on premise tasks for tfs?

**Comment by ericsciple** [comment]
Are you writing a custom task? Or trying to understand what an in-the-box task is doing? This repo contains the in-the-box tasks as open-source examples and we are moving away from that handler (I believe most are converted now in master). releases/m83 is what shipped TFS RTM, 89 -> update1, 95 -> update 2/3. You shouldn't update the tasks that ship in the box. Newer tasks may demand newer features (you shouldn't take master and upload it to a 2015 RTM server).

**Comment by crshnbrn66** [comment]
I'm trying to figure out how the inbox task is working. I can't seem to get my variables and what not straight.

**Comment by crshnbrn66** [comment]
So then are these modules going to be more open in the upcoming releases: 
Microsoft.TeamFoundation.DistributedTask.Task.Deployment.Azure                                                                                                                                 
Microsoft.TeamFoundation.DistributedTask.Task.Deployment.Chef                                                                                                                                  
Microsoft.TeamFoundation.DistributedTask.Task.Deployment.Internal                                                                                                                              
Microsoft.TeamFoundation.DistributedTask.Task.Deployment.RemoteDeployment                                                                                                                      
Microsoft.TeamFoundation.DistributedTask.Task.Internal                                                                                                                                         
Microsoft.TeamFoundation.DistributedTask.Task.Common                                                                                                                                           
Microsoft.Teamfoundation.DistributedTask.Task.CodeCoverage                                                                                                                                     
Microsoft.TeamFoundation.DistributedTask.Task.DTA

**Comment by ericsciple** [comment]
No, those are part of the legacy execution handler.

It would be better to use one of the recommended execution handlers ("node" or "powershell3"): https://github.com/Microsoft/vsts-task-lib

**Comment by ericsciple** [comment]
I've gone ahead and closed since this doesn't sound like an issue with any of the tasks in this repo and the libs should get you going in the right direction. The legacy handler you are referring to is deprecated and simply still exists for back-compat. You should use the new libs. Let me know if any issues and we can reopen or open an issue in the lib repo.
