### ISSUE TITLE
Archive Files task does not work on 32bit Windows

### ISSUE THREAD

**Issue by Morcatko** [Microsoft/vsts-tasks#2321]
7zip.exe and 7zip.dll that are part of Archive Files task are 64bit only.

Could you include+support also 32bit OS?
Or at least add an option to provide custom 7zip.exe (via settings or environment variable)

**Comment by bryanmacfarlane** [comment]
The agent is supported 64 bit only.  https://github.com/Microsoft/vsts-agent

If you're willing to supply a custom 7zip, then why not just write a powershell script?

**Comment by Morcatko** [comment]
I did it with powershell, but there is a task so I would expect it to work. Everything I use works on 32bit - Visual Studio build, powershell, command line, azure tasks, npm, AppInsight annotations, This is the first time I hit some issue.

The provided link does not say anything about bitness, also the installation does not block me and VSOnline works as expected.

**Comment by bryanmacfarlane** [comment]
See the releases for 2.x.  All 64 bit


https://github.com/Microsoft/vsts-agent/releases



Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by bryanmacfarlane** [comment]
All agents going forward are 64 bit.  We are updating our readme to make it clear
