### ISSUE TITLE
AzureFileCopy does not support AzureUSGovernment

### ISSUE THREAD

**Issue by thomaspmorgan** [Microsoft/vsts-tasks#2335]
The Azure File Copy task does not support AzureUSGovernment for blobs.  It uses the wrong management uri https://management.core.windows.net/ instead of the correct https://management.core.usgovcloudapi.net

**Comment by kmkumaran** [comment]
@thomaspmorgan can you please share the logs with us. Can you also tell us what is the task version you notice. You can find that from the task.json file in the Tasks folder that is downloaded under agent install path.

**Comment by kmkumaran** [comment]
@thomaspmorgan can you also let us know if you are using Windows Legacy agent? If so, can you try the same scenario with latest core-clr based agent instead of the windows legacy agent.

**Comment by bryanmacfarlane** [comment]
That's the 1.x agent.  There's a 2.x agent available.  (core-clr is implementation detail).

**Comment by thomaspmorgan** [comment]
My version is 1.0.42 for AzureFileCopy from the task.json file.  I am using TFS 2015 Update 3.  Is the 2.x agent available for TFS 2015 Update 3? If so, how do I update?

**Comment by kmkumaran** [comment]
@thomaspmorgan the support for other Cloud enviornments apart from Azure Cloud is not present in TFS 2015. The support will be available in current VSTS and in the upcoming Dev15 RC2 onwards.

**Comment by kmkumaran** [comment]
@thomaspmorgan I am marking this thread closed based on above response. Feel free to re-open if you have further queries.
