### ISSUE TITLE
NuGet Packager task is only supported on Windows

### ISSUE THREAD

**Issue by rnithish** [Microsoft/vsts-tasks#2344]
Hello,

From the JSON file here https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/NugetPackager/task.json 

I can see that Cmd is one of the demand for this task, which  is preventing me to run this in a MAC environment.
How do I bypass this?

**Comment by jmyersmsft** [comment]
I'm not sure why the task demands the Cmd capability, but the task is still written in PowerShell, so I don't think it'll work anyway. You can try manually setting the Cmd capability on your Mac agent in the admin panel, but I don't think the agent supports tasks written in PowerShell on the Mac. 

Of the three NuGet tasks, we have only specifically targeted the Installer task for development and testing on non-Windows platforms at this time, though the Publisher task may also work. We intend to fully support Mac and Linux build agents for all three tasks in the future, but do not have a specific timeline for that at this time.

**Comment by ericsciple** [comment]
Generally the Cmd demand is used so the job is routed to a Windows machine. The agent currently does not support Core Powershell as an execution handler for custom task authors. Node is current the xplat solution for custom task authors.

**Comment by zjrunner** [comment]
Closed as dup of #1756 (cross plat support)
