### ISSUE TITLE
AzureFileCopy cannot create a new container on a Premium Storage Account and Fails

### ISSUE THREAD

**Issue by Capua89** [Microsoft/vsts-tasks#2353]
Hi, 

I'm trying to copy files across to Azure VM thats OS disk resides in a premium storage account. 

Same build step works fine for a VM on a normal storage account but fails to create container for premium storage account fail the task. 

Below is the log:

> 2016-08-29T06:57:22.2775619Z ##[debug][Azure Call]Retrieved storage key successfully for the storage account: <my storage account name> in resource group: <my resource group name>
> 2016-08-29T06:57:22.2845616Z ##[debug][Azure Call]Creating AzureStorageContext for storage account: <my storage account name>
> 2016-08-29T06:57:22.3195664Z ##[debug][Azure Call]Created AzureStorageContext for storage account: <my storage account name>
> 2016-08-29T06:57:22.3375640Z ##[debug][Azure Call]Creating container: 71e82fbc-4aaf-4fb4-8ac1-076ca1366787 in storage account: <my storage account name>
> 2016-08-29T06:57:22.6895737Z ##[debug]Caught exception from task script.
> 2016-08-29T06:57:22.6905746Z ##[debug]Error record:
> 2016-08-29T06:57:22.7745799Z ##[debug]New-AzureStorageContainer : The remote server returned an error: (400) Bad Request. HTTP Status Code: 400 - HTTP Error Message: One of the headers specified in the request is not supported.
> 2016-08-29T06:57:22.7765776Z ##[debug]At C:\agent\tasks\AzureFileCopy\1.0.72\AzureUtilityGTE1.0.ps1:123 char:22
> 2016-08-29T06:57:22.7775789Z ##[debug]+         $container = New-AzureStorageContainer -Name $containerName -Context $st ...
> 2016-08-29T06:57:22.7795775Z ##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 2016-08-29T06:57:22.7805788Z ##[debug]    + CategoryInfo          : CloseError: (:) [New-AzureStorageContainer], StorageException
> 2016-08-29T06:57:22.7825773Z ##[debug]    + FullyQualifiedErrorId : StorageException,Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.NewAzureStorageCont    ainerCommand
> 2016-08-29T06:57:22.7835788Z ##[debug] 
> 2016-08-29T06:57:22.7865769Z ##[debug]Script stack trace:
> 2016-08-29T06:57:22.8185789Z ##[debug]at Create-AzureContainer, C:\agent\tasks\AzureFileCopy\1.0.72\AzureUtilityGTE1.0.ps1: line 123
> 2016-08-29T06:57:22.8195781Z ##[debug]at <ScriptBlock>, C:\agent\tasks\AzureFileCopy\1.0.72\AzureFileCopy.ps1: line 95
> 2016-08-29T06:57:22.8205791Z ##[debug]at <ScriptBlock>, <No file>: line 1
> 2016-08-29T06:57:22.8225803Z ##[debug]at <ScriptBlock>, <No file>: line 22
> 2016-08-29T06:57:22.8245791Z ##[debug]at <ScriptBlock>, <No file>: line 18
> 2016-08-29T06:57:22.8255790Z ##[debug]at <ScriptBlock>, <No file>: line 1
> 2016-08-29T06:57:22.8285800Z ##[debug]Exception:
> 2016-08-29T06:57:22.8385794Z ##[debug]Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (400) Bad Request. HTTP Status Code: 400 - HTTP Error Message: One of the headers specified in the request is not supported. ---> Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
> 2016-08-29T06:57:22.8395798Z ##[debug]   at Microsoft.WindowsAzure.Storage.Shared.Protocol.HttpResponseParsers.ProcessExpectedStatusCodeNoException[T](HttpStatusCode expectedStatusCode, HttpStatusCode actualStatusCode, T retVal, StorageCommandBase`1 cmd, Exception ex)
> 2016-08-29T06:57:22.8415792Z ##[debug]   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.<CreateContainerImpl>b__27(RESTCommand`1 cmd, HttpWebResponse resp, Exception ex, OperationContext ctx)
> 2016-08-29T06:57:22.8425868Z ##[debug]   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.EndGetResponse[T](IAsyncResult getResponseResult)
> 2016-08-29T06:57:22.8445793Z ##[debug]   --- End of inner exception stack trace ---
> 2016-08-29T06:57:22.8455797Z ##[debug]   at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End()
> 2016-08-29T06:57:22.8475794Z ##[debug]   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.EndCreateIfNotExists(IAsyncResult asyncResult)
> 2016-08-29T06:57:22.8485829Z ##[debug]   at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass1`1.<CreateCallback>b__0(IAsyncResult ar)
> 2016-08-29T06:57:22.8505796Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
> 2016-08-29T06:57:22.8515803Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> 2016-08-29T06:57:22.8535798Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> 2016-08-29T06:57:22.8545811Z ##[debug]   at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.NewAzureStorageContainerCommand.<CreateAzureContainer>d__0.MoveNext()
> 2016-08-29T06:57:22.8565797Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
> 2016-08-29T06:57:22.8575799Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> 2016-08-29T06:57:22.8595798Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> 2016-08-29T06:57:22.8605795Z ##[debug]   at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.<RunConcurrentTask>d__0.MoveNext()
> 2016-08-29T06:57:22.8615800Z ##[debug]   --- End of inner exception stack trace ---
> 2016-08-29T06:57:22.8635803Z ##[debug]Request Information
> 2016-08-29T06:57:22.8645800Z ##[debug]RequestID:72627d93-001c-0031-77c2-014664000000
> 2016-08-29T06:57:22.8665806Z ##[debug]RequestDate:Mon, 29 Aug 2016 06:57:22 GMT
> 2016-08-29T06:57:22.8675802Z ##[debug]StatusMessage:One of the headers specified in the request is not supported.
> 2016-08-29T06:57:22.8695799Z ##[debug]ErrorCode:UnsupportedHeader
> 2016-08-29T06:57:22.8965807Z ##[error]The remote server returned an error: (400) Bad Request. HTTP Status Code: 400 - HTTP Error Message: One of the headers specified in the request is not supported.
> 2016-08-29T06:57:22.9565818Z Finishing task: AzureFileCopy
> 2016-08-29T06:57:22.9605820Z ##[error]System.Exception: Task AzureFileCopy failed. This caused the job to fail. Look at the logs for the task for more details.
> 2016-08-29T06:57:22.9615819Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Worker.JobRunner.Run(IJobContext jobContext, IJobRequest job, IJobExtension jobExtension, CancellationTokenSource tokenSource)
> 2016-08-29T06:57:22.9645819Z Entering OnFinalizeJob
> 2016-08-29T06:57:22.9665823Z Leaving OnFinalizeJob
> 
>

**Comment by kmkumaran** [comment]
@Capua89 - Thanks for reporting the issue. We understand the problem and are working on a fix. Will update you once we have it addressed.

**Comment by kmkumaran** [comment]
@Capua89 - We have addressed this issue. The fix is already deployed for few accounts. The roll out to other Scale units is still in progress. The fix should be available for all accounts at max by next week.

**Comment by Capua89** [comment]
Thanks. Does your fix also includes a workaround for the file size limitation of premium account storage?

**Comment by kmkumaran** [comment]
@Capua89 - Are you refering to the page blob size limits? Since premium storage account supports only page blob type, the write has to align with 512-byte page boundaries. The fix does not change any of these requirements.

**Comment by kmkumaran** [comment]
Marking it closed. Feel free to reopen if there are further queries.
