### ISSUE TITLE
Code coverage became delete link and meta tags.

### ISSUE THREAD

**Issue by m-andrei** [Microsoft/vsts-tasks#2357]
Hello, with last update of vs online, code coverage became upload html without styles.
index.html generated so `<head>
    <title>Code coverage report for All files</title>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="prettify.css" />
    <link rel="stylesheet" href="base.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type='text/css'>
        .coverage-summary .sorter {
            background-image: url(sort-arrow-sprite.png);
        }
    </style>
</head>`
 but after "Publish Code Coverage Results" in section "Code coverage" index html in iframe looks so
`<head>
    <title>Code coverage report for All files</title>
    <style>
.coverage-summary .sorter {
}
</style>
</head>`

**Comment by allendm-msft** [comment]
@m-andrei we have had to move away from the rich html rendering of 3rd party html within our experience to avoid any potential security threats. This had to be done immediately to fix the security hole.

We are actively engaging with the right folks to see what would be the right thing to do to ensure the best experience for our customers without compromising on any aspects of maintaining a highly secure service. 

My apologies for the sudden change in your experience but be assured that it was something done with the best interest of our customers in mind. We will share more about this in a blog post shortly.
