### ISSUE TITLE
Machine file copy task fails proxy authentication even when agent is setup to work with corporate proxy

### ISSUE THREAD

**Issue by schnitty** [Microsoft/vsts-tasks#2359]
Agent Version: 205.2

I have successfully configured the agent and when running it states that it is working behind the authenticated proxy.

When it gets to the MachineFileCopy task it fails with a 407 Proxy authentication error.

Manually going into the .CONFIG files for all the tasks in the externals folder and adding

```
<system.net>
    <defaultProxy useDefaultCredentials="true" >
    </defaultProxy>
</system.net>
```

resolves the issue.

Is there any harm in making that the default configuration for tasks so others don't run into this?

**Comment by asranja** [comment]
Hi, 

Can you please confirm whether you are dealing with "Azure File Copy" Task or "Windows Machine File Copy" Task ? Also, need some more information regarding the location of the .CONFIG files that you are editing.

**Comment by asranja** [comment]
@schnitty Just a gentle reminder in case you are still facing the issue.

**Comment by RoopeshNair** [comment]
Closing this as it doesn't have enough information and the thread is dead
