### ISSUE TITLE
VSTS Run Functional Tests Task fails with Azure servers with self signed certs on Hosted Agents

### ISSUE THREAD

**Issue by dawilliams** [Microsoft/vsts-tasks#2364]
Recently our Function Tests task started failing with the following error.  
```
##[warning]DistributedTests: Task 'CheckTACompat' for machine uxtest1.centralus.cloudapp.azure.com:5986's Error : System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server uxtest1.centralus.cloudapp.azure.com failed with the following error message : The server certificate on the destination computer (uxtest1.centralus.cloudapp.azure.com:5986) has the following errors:    
 
 The SSL certificate is signed by an unknown certificate authority. For more information, see the about_Remote_Troubleshooting Help topic.
```
Prior tasks in the same definition **AzureVMs File Copy** and **Deploy Test Agent** work fine using this self signed cert?

**Comment by allendm-msft** [comment]
@dawilliams one of the main differences with the functional test tasks are that they run on the test agent machines. Are the certs on those machines up to date?

**Comment by dawilliams** [comment]
@allendm-msft They are.  The cert details are 

*.centralus.cloudapp.azure.com
Dec 31st 2011 and Dec 31st 2021

**Comment by dawilliams** [comment]
@allendm-msft I can access the VM from my local laptop using the following...

```
$hostName=<fqdn-of-vm> # example: "uxtest1.centralus.cloudapp.azure.com"
$winrmPort = '5986'

# Get the credentials of the machine
$cred = Get-Credential

# Connect to the machine
$soptions = New-PSSessionOption -SkipCACheck
Enter-PSSession -ComputerName $hostName -Port $winrmPort -Credential $cred -SessionOption $soptions -UseSSL
```

**Comment by dawilliams** [comment]
Any update on this?  Anything I can do to test or help?

**Comment by allendm-msft** [comment]
@dawilliams I havent had the time to look at it this week. Will pick this up early next week. Appreciate the patience.

**Comment by allendm-msft** [comment]
@kmkumaran does this sound familiar

**Comment by allendm-msft** [comment]
@dawilliams is "Test Certificate" checkbox checked in the task?

**Comment by dawilliams** [comment]
I'm not seeing that option...

![image](https://cloud.githubusercontent.com/assets/581113/18386256/56ec5684-765b-11e6-9d85-23c5e4de496b.png)

**Comment by allendm-msft** [comment]
This is a part of the deploy agent task. It shows up when you select "https"

**Comment by dawilliams** [comment]
It wasn't set since that is the default.  I went ahead and set it and made sure "Test Certificate" was selected but it didn't change the result.

**Comment by kmkumaran** [comment]
@dawilliams - Enabling "Test Certificate" option is equivalent to setting skipca option in session options (similar to your script above). Hence you should no longer see failure related to CA verification. Can you share your logs. Please set system.debug variable to true and collect the logs.

**Comment by dawilliams** [comment]
Here is the deploy test agent config...

<img width="201" alt="vsts_deploy_testagent" src="https://cloud.githubusercontent.com/assets/581113/18513290/895c5aba-7a52-11e6-80a6-ecef990f8be9.PNG">

**Comment by dawilliams** [comment]
@kmkumaran @allendm-msft I re-ran the deploy (2nd run after setting the Test Cert) and it worked this time.  You can close this ticket.  Thanks for working with me on this.

**Comment by allendm-msft** [comment]
Good to know. Thanks
