### ISSUE TITLE
NuGet Packager fails with Unrecognized root element in Core Properties part. Line 2, position 2.

### ISSUE THREAD

**Issue by markanewman** [Microsoft/vsts-tasks#2369]
I don't know if this has a better home, but the version of NuGet deployed to the hosted build servers (C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.104.1\agent\worker\tools\NuGet.exe) seems to suffer from a new-ish issue in the [exe] (https://github.com/NuGet/Home/issues/1921).

If I get the latest version of nuget.exe and check it into my repo and set the Advanced | Path to NuGet.exe option to $(build.sourcesDirectory)\nuget.exe, the problem is resolved.

**Comment by zjrunner** [comment]
We've stopped using the in-agent nuget.exe at this point as it led to complications with update (which agents were you using vs which tasks were you using).  The newest (around 0.2.19) has a toggle for you to choose a built-in version of nuget or your custom version.  3.3 is still the default for now and is the same one you mentioned as installed on agents, but 3.5 is also an option.  Once we have a deprecation flow in tasks we'll be moving to 3.5 as the default value.  At this time we do not plan to update or remove the version on-agent as we do not know who has a legacy custom task dependency here.
