### ISSUE TITLE
DSC Partial Configurations Not Working

### ISSUE THREAD

**Issue by oloagentolo** [Microsoft/vsts-tasks#2371]
When I try to run a PowerShell DSC script with partial configurations using the "PowerShell on Target Machines" task, it fails with the following message:

"The only way DSC Partial Configurations can be used in Push mode is if the Publish-DscConfiguration Cmdlet is used. No other push cmdlet is supported. To avoid this error, either set a metaconfiguration without partial configurations, or use the Publish-DscConfiguration cmdlet to deploy your partial configuration."

The thing is that my script does call the "Publish-DscConfiguration" command for each partial configuration that needs to be deployed.  If I include the "Start-DscConfiguration -UseExisting" command explicitly in my script after the publish commands, the script deploys the configuration correctly as expected.  But the task fails because the task is calling the "Start-DscConfiguration" command again afterwards (probably without the -UseExisting flag) and it appears to being do so for each configuration individually, which will not work since each configuration is identified as a partial configuration.

**Comment by chshrikh** [comment]
this has been fixed and will be available in couple of weeks with next deployment
