### ISSUE TITLE
The job running on agent has exceeded the maximum execution time while all build steps was completed

### ISSUE THREAD

**Issue by thuongngo85** [Microsoft/vsts-tasks#2380]
Hi,
I'm facing the issue: all build steps in the build definition was completed but the vNext build showed the error message "The job running on agent has exceeded the maximum execution time". You can refer to the picture below for more detail:
![cleanup_task_hang](https://cloud.githubusercontent.com/assets/2087533/18121296/144e74b6-6f8e-11e6-9266-314bd3bd1ebd.PNG)

In additional information, my test suite is small and this issue happens when I queued build in more than 10 times. The build job timeout configuration is 60 minutes.
 Could you please take a look on this issue?

**Comment by ericsciple** [comment]
"Ran for 61 minutes" and your build job timeout is 60.

**Comment by ericsciple** [comment]
please reopen if i'm missing something

**Comment by thuongngo85** [comment]
Hi,
 My test ran very quickly, it took about 2 minutes. I concerned why all build steps was completed but the build job still wait and then be time out.

**Comment by ericsciple** [comment]
Can you send ersciple the build log? (at microsoft com)

**Comment by thuongngo85** [comment]
Here is the build log:
[1_Build.txt](https://github.com/Microsoft/vsts-tasks/files/448677/1_Build.txt)
[3_Build solution $vsotestvsotest_viet2vsotest_viet2.sln.txt](https://github.com/Microsoft/vsts-tasks/files/448678/3_Build.solution.vsotestvsotest_viet2vsotest_viet2.sln.txt)
[4_Copy files from $(Build.Repository.LocalPath).txt](https://github.com/Microsoft/vsts-tasks/files/448680/4_Copy.files.from.Build.Repository.LocalPath.txt)
[5_Deploy TestAgent on vsotest.txt](https://github.com/Microsoft/vsts-tasks/files/448679/5_Deploy.TestAgent.on.vsotest.txt)
[6_Run Tests vsotest_viet2.dll on vsotest.txt](https://github.com/Microsoft/vsts-tasks/files/448681/6_Run.Tests.vsotest_viet2.dll.on.vsotest.txt)
[7_Post Job Cleanup.txt](https://github.com/Microsoft/vsts-tasks/files/448682/7_Post.Job.Cleanup.txt)
[2_Get Sources.txt](https://github.com/Microsoft/vsts-tasks/files/448683/2_Get.Sources.txt)

**Comment by ericsciple** [comment]
@TingluoHuang - thoughts? Diag log needed? Something hanging on server side?

**Comment by ericsciple** [comment]
@thuongngo85 can you send ersciple a mail (at microsoft com) with a zip of the diag logs if you still have them from this build (in the _diag directory in the root of the agent folder). This looks like the 2x agent so [this repo](https://github.com/Microsoft/vsts-agent/issues) would be a more appropriate place to discuss. closing the issue here, let's continue over email and/or an issue on the agent repo.

**Comment by vegvarizoltan** [comment]
Hello,
I have the same issue with my build agent. Can you share your solution for the problem, if you successfully resolved it.

**Comment by ashu16815** [comment]
![image](https://user-images.githubusercontent.com/25782668/37932004-d5931a04-31a3-11e8-92b7-0d51f906cedd.png)
under the settings of your build definition: General->Build job timeout in minutes.

**Comment by CMIRA0906** [comment]
It works. Thanks

**Comment by ylmcr7** [comment]
`jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 60`

**Comment by ylmcr7** [comment]
jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 60

**Comment by ylmcr7** [comment]
jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 60
