### ISSUE TITLE
Unable to processing logging event - progress percentage

### ISSUE THREAD

**Issue by sheldonhull** [Microsoft/vsts-tasks#2390]
On premise TFS 2015 Update 3
When I try updating the progress percentage on a task, I show the message 
`Unable to processing logging event:##vso[task.setprogress=12;]RandomText`

For long running builds I'd like a straight forward way to update progress so long running jobs could be updated on progress. I thought I had this working in the past, is there any workaround for on-premise to show progress, or modules for feeding write-progress into the format required by tfs vnext build server?

**Comment by ericsciple** [comment]
You're usage is wrong. See https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md

**Comment by sheldonhull** [comment]
@ericsciple  do you have some insight? I've spent a _lot_ of time working on these tasks, and not sure what I specifically did wrong. I'm only asking as I've put a lot of time into working w/it correctly, so my fundamental understanding must be wrong.

**Comment by bryanmacfarlane** [comment]
The link he supplied has a clear doc and example:
```
##vso[task.setprogress value=75;]Upload Log
```
Here's what you did

```
##vso[task.setprogress=12;]RandomText
```
You are missing value=

**Comment by sheldonhull** [comment]
_Thank you_ 

It was starting to blur together. Totally missed that simple syntax issue. Thanks for the insight. That helped me resolve it quickly!
