### ISSUE TITLE
Sonarqube configuration for Vnext build 

### ISSUE THREAD

**Issue by dpadhya1990** [Microsoft/vsts-tasks#2393]
Hello Team 
I want to create sonarbuild (Vnext) for my TFS server, our sonar server is very old (4.5.2 and C# plugin is 3.3) so i dont thing so this will work for Vnext build ? 
so for this I have to create my own sonar server, if i installed sonarqube 5.2 do i need to install Mysql server and what could be the minimum supported C# plugin i have to used and is there any other tool required apart from this ? (I am new to sonarqube :)  ) 
TFS server version is 2015 Update1
Regards
Dushyant

**Comment by bgavrilMS** [comment]
@dpadhya1990  - I recommend you install the LTS (long term support) version of SonarQube, which is now 5.6.1. I don't recommend you install 5.2, it's quite old and many features will not work with TFS Build. 

By default, SonarQube uses an in-memory database for evaluation purposes. You have to install and configure a database of your own for any real work, otherwise you won't be able to upgrade from one version of SQ to the next. But the in-memory one is good enough to configure your builds etc. You can use MySQL, but you can also use the free SQL Server Express 

After you install SQ, log in as admin and go to the update centre. The C# plugin is installed by default, you just need to update it to the latest version. We do not support any non official version of SonarQube / C# plugin, so if you encounter a problem we'll usually ask you to update to the latest. 

See our blog for more articles related to this: https://blogs.msdn.microsoft.com/visualstudioalm/tag/sonarqube/

Also, on your build agent, make sure you install Java (the JRE, you don't need the whole JDK).

**Comment by dpadhya1990** [comment]
Hello bgavrilMS 
Thanks for the reply, do i need to download sonar runner as well ? 
Regards
Dushyant

**Comment by bgavrilMS** [comment]
No, the build task will take care of all of that for you. You only need to install the SQ server somewhere and make sure Java is installed on the build agent.

**Comment by dpadhya1990** [comment]
Hello bgavrilMS
Thanks for the help, 
I had created sample sonar build in TFS (VNext version) for my test application, i had installed all the required component for this i have sonar server and java installed on my agent but till its showing error as no agent found could be found with the following capabilities: SonarQube, msbuild, java, visual studio, vstest but i think i had all the capabilities available in my agent ( i am not able to add screen shot here but i had posted same question TFS forum with screen shot : https://social.msdn.microsoft.com/Forums/en-US/42928578-1166-4d35-91b0-5099661830b7/tfs-vnext-build-for-sonar?forum=tfsbuild  
please let me know if missed something in configuration
Regards
Dushyant

**Comment by bgavrilMS** [comment]
A couple of questions: 

1. Are you sure you're building with the right agent? Maybe you're using a different agent queue. 
2.Have you completed any build on this agent, for example one without the sonarqube tasks?

I don't think we've ever placed a "SonarQube" capability request on the tasks, we only ask for msbuild and java.

**Comment by dpadhya1990** [comment]
hello 
Thanks for the reply 
Yes i have created CI build here which ran successfully

**Comment by dpadhya1990** [comment]
Hello again
Build at least started i had made such silly mistake,  under general --> demands sonar was added as exits, i delete that and run build it worked. i think this was the thing which preventing build to start.

**Comment by bgavrilMS** [comment]
Makes sense. In general I avoid editing agent capabilities / demands. The SonarQube tasks rely solely on Java to run.

**Comment by dpadhya1990** [comment]
Hello bgavrilMS
Thanks a lot for your reply i am to generate dashboard and seems all working fine except in side unit test coverage instead of results its showing as hyphen ( - ) 
 is there any configuration i have to do or any additional plugin is required ? 
in build output i can see My unit test cases are passed. kindly adviced 
Regards
Dushyant Padhya

**Comment by bgavrilMS** [comment]
You shouldn't need to do anything. 

In your MSTest / VSTest build task - did you enable code coverage?

**Comment by dpadhya1990** [comment]
yes code coverage is enabled (marked as checked)  in VS test build task

**Comment by bgavrilMS** [comment]
I just ran a build and I confirm I cannot see the code coverage file as well. I logged a bug on the SonarQube Scanner that is owned by Sonar Source to track this: https://jira.sonarsource.com/browse/SONARMSBRU-262

Thanks for reporting!

**Comment by venky76v** [comment]
Hi, 
We have a on prem installation of TFS (TFS 2017) and I am attempting to integrate SonarQube analysis into our build steps. I have installed the SonarQube extension on the TFS server and added a service endpoint to point to a server where I have SonarQube Server installed and configured. 

When I attempting to trigger a build, I am getting an error "**No agents could be found with the following capabilities: msbuild, java, visualstudio**". Does my build server need JRE to be installed to get the SonarQube build steps to work? SonarQube website says this:

**Installation

Make sure the .NET Framework v4.5.2+ is installed
Make sure the Java Runtime Environment 8 is installed
Install the extension from the marketplace**

**Comment by bryanmacfarlane** [comment]
@venky76v - if you go to the sonar extension in the marketplace there’s a support link.  You can ask questions about sonar and it’s extension there
