### ISSUE TITLE
AzureFileCopy doesn't set content types

### ISSUE THREAD

**Issue by onovotny** [Microsoft/vsts-tasks#2395]
The current AzureBlobCopy VSTS task does not set any content types based on file extension and thus are wrong (all are `application/octet-stream`) by default.

Many people won't know about the /setContentType AzCopy args, so it may be a good idea to expose that directly as a checkbox on the VSTS task.

**Comment by bryanmacfarlane** [comment]
Is Azure Blob Copy a task in this repo?  Is it in the box or a custom extension?

**Comment by onovotny** [comment]
The tasks are in this repo and it's an "in-box"/default extension for all accounts afaik.

https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/AzureFileCopy

**Comment by bryanmacfarlane** [comment]
OK - you're referring to AzureFileCopy task.  Yes, that's in this repo.

**Comment by onovotny** [comment]
Yes, sorry, updated the title

**Comment by RoopeshNair** [comment]
@onovotny 

We support setting content type as an additional argument. As of now the same additional argument input field is being used for upload to blob and download to VM and list of additional parameters supported are different for each scenario. 

To improve usability, we have plans to split this into a separate tasks. It is on our backlog, no time-lines  yet. 

As of now, users can specify - 
**Blob Destination**: Supported additional arguments for copy to blob are /BlobType:, /Pattern:, /L, /Z, /XN, /A, /IA:, /XA:, /NC:, /DestType: and /SetContentType.
**VM Destination**: Supported additional parameters for copy to VM are /Pattern:, /L, /NC: and /XN.

Closing this thread

**Comment by onovotny** [comment]
@RoopeshNair I am aware that you can specify those arguments in the "additional argument" input field. I'm just suggesting that most people don't know the arguments and aren't intimately familiar with `AzCopy`, so exposing a few more arguments in the task UI might be helpful.

**Comment by tabeth** [comment]
I agree with @onovotny. I was attempting to serve some HTML using a Blob and saw that the HTML was not properly set in terms of its content type. Some search lead me to this, thankfully.

**Comment by NSTA1** [comment]
Worth noting that /SetContentType sets javascript files' content type to application/x-javascript which is not RFC compliant.

**Comment by chrisfoster78** [comment]
Related issue: https://github.com/Microsoft/vsts-tasks/issues/5590

**Comment by pksorensen** [comment]
what should additionalArgumentsForBlobCopy be given to set `Cache-Control: max-age=31557600` ?

**Comment by skamoda** [comment]
Any news related to what should be given to set `Cache-Control` in AdditionalArgumentsForBlobCopy?

**Comment by chidozieononiwu** [comment]
In my case setting additionalArgumentsForBlobCopy actually resulted in wrong Content Type being set
```
additionalArgumentsForBlobCopy: |
            '/SetContentType'
            '/Y'
            '/Pattern:*'
            '/S'
```
What worked for me is to remove all te additional parameters, then the task was able to set correct content types for .html and .js files
