### ISSUE TITLE
Ordered test support in Run Functional Tests task #1923

### ISSUE THREAD

**Issue by sailajacharan** [Microsoft/vsts-tasks#2397]
https://github.com/Microsoft/vsts-tasks/issues/1923

HI @atinb, we implemented above work around and were very happy to see ordered tests run successfully. But we now are in to an issue where the test results generated from TFS build
show passed while an individual test in the ordered test suite actually failed.

![pimsbuild](https://cloud.githubusercontent.com/assets/20461864/18171064/3f5a317a-7026-11e6-9d9f-0a39d19d9e94.PNG)

**Comment by allendm-msft** [comment]
@sailajacharan thanks for reporting this. It is a known issue we are investigating and want to fix in vnext

**Comment by allendm-msft** [comment]
@sailajacharan we have a workaround for the workaround issue :) 
if you run your .orderedtest independently you can consume [this script in a powershell](https://github.com/Microsoft/customer-scripts/blob/master/test/build/orderedtest/throwif-trxfromtestrun-ofbuild-hasfailedoutcome.ps1) task, immediately after the test task. 

The .ps1 provided is just a sample so feel free to tweak it as per your needs.

**Comment by allendm-msft** [comment]
@sailajacharan have a look at [this blog post](https://blogs.msdn.microsoft.com/allendm/2016/08/09/executing-ordered-tests-on-remote-machines-using-run-functional-tests-task/) providing a workaround for this problem. 

The apis used are for vsts/tfs15. You can modify them easily if you are working on earlier versions of TFS

**Comment by K5i4** [comment]
@allendm-msft is there any progress on the issue? Will the solution honour the order of test cases within in a test suite?
