### ISSUE TITLE
AzureRm Web App Deployment - "SubscriptionID must be a valid GUID" - Error

### ISSUE THREAD

**Issue by Bunty-Thakkar** [Microsoft/vsts-tasks#2398]
I added a **AzureRm Web App Deployment** build step for my project. In that step, the first field is to select Azure Subscription for which I have to create one **service endpoint**.
While creating it, I have to select one Azure RM Subscription and give one Connection Name.

Now when i select a subscription from the provided dropdown list, if the subscription name is in the following format **subscriptionName (xyz) (subscriptionID)**, it displays an error **SubscriptionID must be a valid GUID**. 

Else if the subscription name is in the format **subscriptionName (subscriptionID)**, it works fine.

Azure is extracting and identifying subscriptionID from the first present round bracket i.e **subscriptionName _(subscriptionID)_** whereas if it were **subscriptionName _(xyz)_ (subscriptionID)**

I have attached a following screenshot for better understanding.

![error](https://cloud.githubusercontent.com/assets/16079134/18174895/ef957980-708c-11e6-816f-ce7c97c71a60.png)

As seen in the image, The first round bracket also contains **SubscriptionName** followed by the actual subscriptionName. Whereas SubscriptionID is present in the second round bracket.

I have tried selecting other subscriptions, it works fine but when I select such subscriptions, it doesn't work.

Thanks.

**Comment by kmkumaran** [comment]
@Bunty-Thakkar - Thanks for reporting the issue. We are aware of this bug and have addressed this. The fix should be available as part of our next deployment.

@pavanadepu2

**Comment by Bunty-Thakkar** [comment]
@kmkumaran Thanks.

**Comment by NicolasRiou** [comment]
same issue here ... is it really fixed ?

**Comment by DavidDAmato** [comment]
I am also having this same problem, here's a code snippet used from PowerShell that's throwing the error: 

$connectionName = "AzureRunAsConnection"
    $servicePrincipalConnection=Get-AutomationConnection -Name $connectionName        
    Add-AzureRmAccount `
        -ServicePrincipal `
        -TenantId $servicePrincipalConnection.TenantId `
        -ApplicationId $servicePrincipalConnection.ApplicationId `
        -CertificateThumbprint $servicePrincipalConnection.CertificateThumbprint `
        -SubscriptionId $SubscriptionID

**Comment by KrishnaAdityaB** [comment]
@NicolasRiou Are you facing the issue exactly as mentioned by Bunty-Thakkur?
If yes, can you share you visualstudio.com account name? 
If no, can you share the screenshots like Bunty-Thakkur did.

You can mail the details to RM_Customer_Queries at Microsoft.com.

**Comment by vincentdass** [comment]
Closing this issue as there is no response.
Feel free to open the issue, if required.
