### ISSUE TITLE
Questions: How should I setup my VSTS Builds for a solution which has dotnet core and non-core dependencies

### ISSUE THREAD

**Issue by johnkattenhorn** [Microsoft/vsts-tasks#2420]
It's a question not an issue - hope that's ok.

We have a ASP.NET Core API project which depends on some non-core C# project in the same solution.

When I came to setup the CI build I setup:

GitVersion Task
NuGet Restore
DotNet Restore
Build

It fails in the DotNet Restore as the depend projects are not yet built. I'm about to create two new solution files to split the core and non-core builds and add an additional build step so it looks like this

GitVersion Task
NuGetRestore
Build Non-Core SLN
DotNet Restore
Build Core SLN
....

Does seems reasonable ? Have I missed something with dotnet restore ? I looks at the command options and nothing jumped out at me to build dependant projects or such like.

**Comment by johnkattenhorn** [comment]
I'm still stuck with this issue, I can't find a combination of

`dotnet restore`

`& 'C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe' <SFSolution Name> /t:Package /p:platform="x64" /p:configuration="Release"`

**Comment by DavidStaheli** [comment]
@zjrunner, would your team own the dotnet restore scenario?  Thanks.

**Comment by zjrunner** [comment]
We don't own a dotnet restore task today if that is the question.  We already have on our backlog general dotnet restore support for auth (dotnet doesn't currently support plugin credential providers or encrypted creds so we're waiting/pushing/working toward that first).  

This sounds like an issue to be resolved first with the dotnet-cli or msbuild spaces first.  If it comes down to tasks around packaging that don't support the commands needed to get this rolling then that is probably with me, but the above sounds like confusion around even how the individual tools should be sequenced (regardless of build/task infra)

**Comment by DavidStaheli** [comment]
Hi @johnkattenhorn.  Sorry for the delay.  Did you find a solution, or is this still an issue for you?

**Comment by johnkattenhorn** [comment]
This is still a problem for us but it turned out not to be anything to do with the restore. 

The build steps fail regardless of the restore, I've got another issue logged here:

https://github.com/Azure/service-fabric-issues/issues/66

PS. There seems to be a lot of people with this issue in dotnet core and plenty of workarounds but none I've seen so far work for us.

**Comment by DavidStaheli** [comment]
Thanks, John.  I'll close this issue since it's tracked by the other one you referenced.  Sorry for the trouble you're seeing and I hope we can resolve the other issue quickly.
