### ISSUE TITLE
ServiceFabricUpdateAppVersions.ps1 - Multiple DataPackages not supported

### ISSUE THREAD

**Issue by mkosieradzki** [Microsoft/vsts-tasks#2421]
When Service Manifest contains multiple DataPackages, following error is thrown:

##[error]Cannot process argument transformation on parameter 'NewPackageXml'. Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Xml.XmlElement".

**Comment by EricJizbaMSFT** [comment]
I don't believe I have permissions to close this issue, but it has been fixed in the referenced pull request.

**Comment by mkosieradzki** [comment]
@EricJizbaMSFT Thanks a lot.
