### ISSUE TITLE
Azure Copy Task Failed with Access is Denied

### ISSUE THREAD

**Issue by boydc2014** [Microsoft/vsts-tasks#2427]
My AzCopy task failed with **Access is Denied**:
```
2016-09-06T08:37:52.4872690Z` ##[section]Starting: AzureVMs File Copy
 
.... 
2016-09-06T08:38:33.5108343Z ##[error]Connecting to remote server [xxxxxx].eastasia.cloudapp.azure.com failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.To fix WinRM connection related issues, select the 'Enable Copy Prerequisites' option in the task. If set already, and the target Virtual Machines are backed by a Load balancer, ensure Inbound NAT rules are configured for target port (5986). Applicable only for ARM VMs. For more info please refer to https://aka.ms/azurefilecopyreadme
 ....
2016-09-06T08:38:33.5577117Z ##[section]Finishing: AzureVMs File Copy
```
I've tried the following:

* 1. check winrm is listening on HTTPS port
* 2. make sure connection is not blocked by inbound rules by configure Firewall and NetworkSecurityGroup
* 3. make sure "Enable Copy Prerequisites" and "Test Certificate" are checked following
https://blogs.msdn.microsoft.com/muthus_blog/2016/03/24/simplifying-winrm-pre-requisites-in-azure-vms-as-part-of-release-and-build-workflows/
* 4. make sure i have a self-signed certificate by following 
https://github.com/Microsoft/vsts-tasks/issues/1008 (.\ConfigureWinRM.ps1 *.eastasia.cloudapp.azure.com)
* 5. add my build agent to trustedHosts by setting trustedHost to "*"
* 6. make sure remote UAC is closed by following 
 https://support.microsoft.com/en-us/kb/951016#bookmark-diditfix

When I run 
```
$soptions = New-PSSessionOption -SkipCACheck
$cred = Get-Credential
$computername = 'my domain'
$computerport = '5986'
Enter-PSSession -ComputerName $computername -Port $computerport -Credential $cred -SessionOption $soptions -UseSSL
```

Enter-PSSession : Connecting to remote server *.eastasia.cloudapp.azure.com failed with the following error
message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.
At line:1 char:1
+ Enter-PSSession -ComputerName $computername -Port $computerport -Credential $cre ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (kickoffbot.eastasia.cloudapp.azure.com:String) [Enter-PSSession], PSR
   motingTransportException
    + FullyQualifiedErrorId : CreateRemoteRunspaceFailed

I have no idea what's next to try.

**Comment by boydc2014** [comment]
@pavanadepu1 @praneethy91 is there anything I should check

**Comment by sawpresto** [comment]
I'm not sure if this would help, but when I debugged these tasks with winrm, I tried the following:
- Make sure WinRM is running in the Services Panel
- Run winrm quickconfig -transport:https just in case
- On the machine, run Enable-PSRemoting

**Comment by boydc2014** [comment]
@sawpresto thanks for the advices.  I checked my remote machine again:

1. WinRM is running in service panel
2. winrm quickconfig -transport:https just in case  shows
```
WinRM service is already running on this machine.
WSManFault
    Message
        ProviderFault
            WSManFault
                Message = WinRM cannot process the configuration request. This action requires input XML conta
lement name of Analyze_INPUT with value "http" or "https".

Error number:  -2144108479 0x80338041
The SOAP XML in the message does not match the corresponding XML schema definition. Change the XML and retry.
```
3. Enable-PSRemoting ask to confirm this action.

**Comment by boydc2014** [comment]
@sawpresto  After I confirm all actions, **Enter-PSSession works!!!!**. Thank you so much.

May I ask why
1. my winrm service is running
2. winrm enumerate winrm/config/listener looks good
3. winrm quickconfig -transport:https  shows it's running
Still i need to run Enable-PSRemoting ??

**Comment by sawpresto** [comment]
Awesome! I believe that a lot of other tasks on remote machines require remote PS (and a lot of the tasks run as PS scripts), so just a guess from experience with those other tasks. Glad that helped!

**Comment by pavanadepu2** [comment]
@bodyc2014, Enable-PsRemoting does the following actions:
a. Sets winrm to receive remote requests.
b. Updates winrm for remote management.
c. Enables firewall exception for winrm.

It seems in your case there was no firewall exception for winrm. And upon running Enable-PSRemoting, the firewall exception got enabled and you are able to make the connection successfully.

I hope it answered your question.

**Comment by boydc2014** [comment]
@pavanadepu2 I manually created the inbound firewall rules. So I think firewall seems not to be  the problem.

Acutally, before I encounter the error "access denied", I got "certificate not matched" error. Which means firewall is OK or I can not get a chance to check certificate.
