### ISSUE TITLE
DeployAzureResourceGroup synax error in file AzureUtilityLTE9.8.ps1

### ISSUE THREAD

**Issue by hiyadav** [Microsoft/vsts-tasks#2432]
line 52 : should the -TemplateParameterFile be given as `"csmParametersFile`" 
here is reference for the cmdlet "New-AzureResourceGroupDeployment" in version 0.9.8: https://msdn.microsoft.com/en-us/library/azure/dn757690(v=azure.98).aspx

**Comment by bryanmacfarlane** [comment]
Is that an issue with one of the task in this repo or an azure ps question?

**Comment by kmkumaran** [comment]
@hiyadav - Thanks for reporting. There has to be a double quote to handle while spaces in the parameters file path. We will address it.

**Comment by hiyadav** [comment]
I have a fix and have raised a PR : here is the link -https://github.com/Microsoft/vsts-tasks/pull/2447
