### ISSUE TITLE
Upload test results for each machine in machine group with Run Functional Tests

### ISSUE THREAD

**Issue by sawpresto** [Microsoft/vsts-tasks#2437]
In TFS 2015.3, I'd like to have a unique test result uploaded to TFS for each machine that is run in a machine group when executing the Run Functional Tests task. For example, when I run the task with machines A, B, and C, it will only show test results in the Test tab for C. It looks like the "Distribute tests by number of machines" checkbox in VSTS doesn't necessarily mean that each test result for each machine will be uploaded. The alternative would be needing to run the Run Functional Tests task _X_ number of times for _X_ number of machines, which would be redundant. Is this already possible for the task?

**Comment by nigurr** [comment]
@sawpresto currently this is not possible. The idea behind Distributed Testing is to distribute the tests across machines for parallelism and efficiency.

**Comment by sawpresto** [comment]
So it's intentional that using the Run Functional Tests task with a machine group, it will only publish test results for the last machine?

**Comment by atinb** [comment]
@sawpresto 
That is incorrect. Results are uploaded from all machines that are running tests and you can see the machine on which the test ran in the Test details. Why do you think only results from the last machine are being uploaded? Are you seeing less number of results than the tests being run?

**Comment by sawpresto** [comment]
That's what I would assume as well, that each machine would show up with test results, but when I ran it with TFS 2015.3, when running the task with two machines listed in the task, only one would upload test results (the last one).

**Comment by atinb** [comment]
Is it possible that all the tests are running on that 1 machine? Are you seeing a discrepancy in the number of tests that ran? What TFS version are you using and are the tests in 1 dll? Thanks!

**Comment by sawpresto** [comment]
It looked like when I ran the task, it logged the tests running in multiple machines. Yes, the same number of tests ran for each machine. Using TFS 2015.3, tests in one dll. I'll try this again and let you know if I get the same issue.

**Comment by atinb** [comment]
@sawpresto 
Are you still seeing the issue? Thanks!

**Comment by sawpresto** [comment]
I'm not able to find the machines again that I tested this on, so go ahead and close this and I'll comment again if I find anything. Thanks!

**Comment by atinb** [comment]
Thanks! Closing issue as per comment above.
