### ISSUE TITLE
VSTest: Setting "Path to Custom Test Adapters" leads to error in VSTest.ps1

### ISSUE THREAD

**Issue by zjgeary** [Microsoft/vsts-tasks#2438]
When we set "Path to Custom Test Adapters" as a part of of a VSTest task in our release definition, the test task fails with:
##[error]System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'vstestLocationMethod'.
Setting "Path to Custom Test Adapters" was the only change we made, and reverting it causes the tests to pass again (excluding the ones it can't run without the adapter).
Any ideas?

**Comment by nigurr** [comment]
@zjgeary this parameter has been added very recently and i believe it's not yet deployed in VSTS. Can you please let me know whether you are using VSTS or On Prem TFS?

**Comment by zjgeary** [comment]
We are using VSTS. I'm not sure what changed in the last 16 hours, but it seems to work now. Thanks!

**Comment by nigurr** [comment]
Please reopen if you encounter this again
