### ISSUE TITLE
Can we add PSSessionOptions to the PowerShellJob.ps1 / Invoke-PsOnRemote

### ISSUE THREAD

**Issue by tagwise-eu** [Microsoft/vsts-tasks#2441]
Hi there,

Please do not that this is a duplication request that was to a closed ticket #1394.
However I don't need the arguments listed by the topic starter, but need a different one.

To be specific: -IncludePortInSPN
(Example: $sessionOptions = New-PSSessionOption -IncludePortInSPN)

I need these as we use a CRM environment with host specific SPN's. These SPN's are registered under a IIS AppPool user (different to the deployment user, used by TFS)  as we are using multiple front-ends. As we are using multiple front-ends, I'm unable to remove the existing SPN's.

I added a new port-specific SPN, and can connect with PowerShell with above snippet.
However in order to be using these within TFS Build, I need that parameter added to the PowerShell jobs.
See community question of me regarding this: https://social.msdn.microsoft.com/Forums/vstudio/en-US/7e9e7a6c-fd0e-45c9-bec1-08322183c2d6/powershell-on-target-machines-failes-due-to-crms-spn-records?forum=tfsbuild

As I said, this ticket is a duplication. I still created this to show the need for it (multiple people requiring it apparently).

Hopefully you can help me out!

With kind regards,

Mike van Engelen

**Comment by RoopeshNair** [comment]
We have this on our backlog, however it will be a while before we can get to this based on current priorities (5-6 months).

**Comment by sergeytunnik** [comment]
Hi.
We are facing exactly the same issue. We have Dynamics CRM deployment and were going to utilize TFS release management for deploying. It is quite frustrating that MS core products can't work together.

**Comment by tagwise-eu** [comment]
Hi Sergey,

I do have a workaround available;
- First create specific SPN's for the portnumbers of the WinRM service (elevated PowerShell)
SetSPN.exe -s HTTP/$($env:COMPUTERNAME):5985 $env:COMPUTERNAME 
SetSPN.exe -s HTTP/$($env:COMPUTERNAME).$($env:USERDNSDOMAIN):5985 $env:COMPUTERNAME

- Make the user used for the deployments part of the "Administrators" group (you could login by Local Security Profile)
- For SQL server, make the user sysdba (perhaps less rights are required, but this is how we have it currently setup)

Use a "forward" script, so this script you call from TFS with some arguments, and then execute the specifc script on the remote machine. Script is such as:
`$ServerName = "$($args[0])"

# Generic session options for PSSession
$sessionOptions = New-PSSessionOption -IncludePortInSPN

# Create custom remote connection to include the SPN
$session = New-PSSession -Computername $($ServerName) -SessionOption $sessionOptions
Invoke-Command -Session $session -filepath "\\<server>\nameofscript.ps1" -argumentlist <ANY SCRIPT ARGUMENTS>
Remove-PSSession -Session $session`

**Comment by sergeytunnik** [comment]
@tagwise-eu thank you for complete solution.
I'm currently also checking something more sophisticated for deployment such as PSDeploy  or PSCI.
