### ISSUE TITLE
Dynamic picklist in TFS task

### ISSUE THREAD

**Issue by deepad5** [Microsoft/vsts-tasks#2446]
I am trying to create dynamic picklist tied to a service end point. However I am seeing the error below while trying to connect to the service end point in fiddler.
{"$id":"1","innerException":null,"message":"The request was aborted: Could not create SSL/TLS secure channel.","typeName":"Microsoft.TeamFoundation.DistributedTask.WebApi.ServiceEndpointQueryFailedException, Microsoft.TeamFoundation.DistributedTask.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"ServiceEndpointQueryFailedException","errorCode":0,"eventId":3000}

The server I am connecting to expects the TLS protocol to be set. I am able to invoke the rest api from a powershell script by setting the security protocol  as below in the code.
[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy
[System.Net.ServicePointManager]::SecurityProtocol = @("Tls12")

Questions:
1) Is it possible to do the same while creating the service end point or in the task.json ? 
2) Is it possible to dynamically populate the picklist from a powershell script so that I could call the rest api from the powershell script after setting the certificate policy and protocol. If so, could you point me to the details?

If there is any other way to solve this issue, please let me know.

Thanks.

**Comment by bryanmacfarlane** [comment]
RM did the dynamic pick lists

**Comment by GitHubSriramB** [comment]
Specifying PS script to dynamically populate picklist is not supported. 

We however support providing additional auth. headers in the endpoint type contribution. Would the settings you specifying through PS script be finally added as additional auth. headers in the HTTP request? If so, you could provide them in the endpoint contribution json.

For e.g. Endpoint type can define an auth. header like the following as part of contribution:

  "authenticationSchemes": [
          {
            "type": "ms.vss-endpoint.endpoint-auth-scheme-token",
            "headers": [{"name": "Authorization", "value": "Basic {{ #base64 endpoint.username \":\" endpoint.apitoken }}"}],
...

Headers is an array & so additional headers can be specified if required.

Would this help?

**Comment by deepad5** [comment]
[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy
[System.Net.ServicePointManager]::SecurityProtocol = @("Tls12") 
Setting these in the powershell script set the security protocol used by the ServicePoint in a programmatic manner.  I am not sure if internally TFS appends this information into the request header.
In the declarative form for the service point, is there a way to set the protocol information?

**Comment by GitHubSriramB** [comment]
There is no way to set protocol information as above in declarative form within service endpoint type contribution. We would need to understand how the request is made using the above parameters using Fiddler. Can you check?

In the meantime, we will add an item into our backlog to support passing protocol information & investigate what it takes when we get to it.

**Comment by deepad5** [comment]
I checked Fiddler after running the powershell script that makes rest calls to an Https server after setting the TLS 1.2 protocol.
Nothing seems to be set in the headers. 

---------------------------------------------output---------------------------------
Encrypted HTTPS traffic flows through this CONNECT tunnel. HTTPS Decryption is enabled in Fiddler, so decrypted sessions running in this tunnel will be shown in the Web Sessions list.

Secure Protocol: Tls12
Cipher: Aes128 128bits
Hash Algorithm: Sha256 256bits
Key Exchange: ECDHE_RSA (0xae06) 256bits

== Server Certificate ==========
[Subject]
  CN=<machine name>, OU=<org name>, O=<orgname>, L=<location>, S=<state>, C=<country>

[Issuer]
  CN=<machine name>, OU=<org name>, O=<orgname>, L=<location>, S=<state>, C=<country>
  
[Serial Number]
  7047556485

[Not Before]
  6/28/2016 12:38:32 PM

[Not After]
  10/26/2016 12:38:32 PM

[Thumbprint]
  D31063E9EB16BA11075F8B6Eytyutyut78768686

**Comment by deepad5** [comment]
Could you please check if there is a workaround for this, because right now we have text boxes for our fields and the user experience is not great. We would ideally like to show picklists populated through data from the rest calls to our server over Https and right now we are blocked due to the ssl/tls handshake issue.

**Comment by deepad5** [comment]
@GitHubSriramB  could you please provide me the link to the backlog item to support passing protocol information to service end points?

**Comment by GitHubSriramB** [comment]
@deepad5 Our backlog is not shareable outside of Microsoft. 

We need to investigate what it takes to support querying HTTPS based external services using Tls12 protocol. Sorry - don't have a solution for your right now.
