### ISSUE TITLE
Ant build step is getting appended with un known information

### ISSUE THREAD

**Issue by penupati** [Microsoft/vsts-tasks#2463]
Hi, I am using ant build step where pre defined build.xml loads for our Java Junit testing.
Here is the entry given for Options = -Dagent.dir="$(Agent.BuildDirectory)/s" -Dunit.test=com.oilspace.apps.aspect.admin.TestAspectAdmin -logfile tests_console_output.txt

While executing ant build, we are getting additional input as /src  at the end of this Option entry, result is mentioned below.

/ci04_home/AspectAdmin03/ci04_agent03/_work/3/s -Dunit.test=com.oilspace.apps.aspect.admin.TestAspectAdmin -logfile tests_console_output.txt/src

Where Agent.BuildDirectory = /ci04_home/AspectAdmin03/ci04_agent03/_work/3/s 

Due to this change, out ant builds are getting successful.
Let us know how to resolve this issue.

**Comment by DavidStaheli** [comment]
@penupati, I apologize for the problem.  Thank you for reporting it.  It is a bug in the Ant task that was released to production.  We are hot-fixing it in production and the problem will disappear momentarily.  I will re-comment once the fix is in place.

**Comment by DavidStaheli** [comment]
Hi @penupati, the problem should now be fixed in Team Services.  Please let me know if you still see it.  Thanks again for reporting it.  Sorry for the inconveniences!
