### ISSUE TITLE
Publish Test Results, NUnit3 format support

### ISSUE THREAD

**Issue by AlexKosmich** [Microsoft/vsts-tasks#2468]
Looks like NUnit3 format is not supported at the moment. 
Getting error when trying to upload NUnit3 test results: 

_Invalid results file. Please make sure the Test Result Format field in the task matches the result format of the file_

Is it possible to implement support of the new format? since it contains more useful data.
https://github.com/nunit/dotnet-test-nunit/issues/75

**Comment by allendm-msft** [comment]
Created a PR on the agent repo 
https://github.com/Microsoft/vsts-agent/pull/629

**Comment by tiefling** [comment]
What is the likely time line on this?

**Comment by atinb** [comment]
We have a PR out for review. Waiting for a few signoffs. Thanks!

**Comment by kaadhina** [comment]
This is already in.

**Comment by asartem** [comment]
doesn't work for me. TFS 2015, v 14.102.25423.0 
Invalid format error message is displayed when use nunit3 and try to publish it's xml  test result file
