### ISSUE TITLE
Cannot set environment variable when using CmdLine task

### ISSUE THREAD

**Issue by LiohAu** [Microsoft/vsts-tasks#2470]
Right now I use the CmdLine task to run "mono" as tool with "nunit-console.exe" as parameter so I can run my mobile tests without developing a custom task.

Now I would like to improve this a little bit, and set 2 environment variable that would contain the device model / OS on which I want to run my tests (and later fill these variable dynamically using our test plan in MTM).

How can I set these 2 env vars since CmdLine does not seem to recognize the "VAR=VALUE tool_name" in the tool field ?

**Comment by ericsciple** [comment]
Variables on the definition are propagated to tools as environment variables.

**Comment by ericsciple** [comment]
and you can set variables dynamically. see the setvariable command: https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md

other option is to use a shell script.

**Comment by LiohAu** [comment]
@ericsciple  My point was that you cannot reproduce this : 
```
SOME_VAR=`some_binary_result` command_to_exec
```
