### ISSUE TITLE
AzureFileCopy: Error Task in VSO. Version 1.0.77 Bad Gateway. (in function: Get-AzRMStorageKeys

### ISSUE THREAD

**Issue by jabjohanna** [Microsoft/vsts-tasks#2472]
**ExceptionMessage: The remote server returned an error: (502) Bad Gateway. (in function: Get-AzRMStorageKeys)**

System.Exception: Task AzureFileCopy failed. This caused the job to fail. Look at the logs for the task for more details.
at Microsoft.TeamFoundation.DistributedTask.Worker.JobRunner.Run(IJobContext jobContext, IJobRequest job, IJobExtension jobExtension, CancellationTokenSource tokenSource)

**Comment by kmkumaran** [comment]
@jabjohanna - Can you enable system.debug to true and provide the failure log.

**Comment by jabjohanna** [comment]
Hello, you activate it, but where I find the log?

**Comment by jabjohanna** [comment]
[3_AzureVMs File Copy.txt](https://github.com/Microsoft/vsts-tasks/files/464656/3_AzureVMs.File.Copy.txt)

**Comment by bryanmacfarlane** [comment]
If you set system.debug to true on the definitions variables you will see addition lines in the normal console and logs with [debug] prefix

**Comment by rajatagrawal-dev** [comment]
@jabjohanna - We are not able to reproduce the error. Please provide a mail id so that we can communicate with you directly to figure out the issue.

**Comment by rajatagrawal-dev** [comment]
Hi @jabjohanna . Were you able to successfully execute the Azure File copy task? If no, then please reach out to us at "RM_Customer_Queries@microsoft.com" so that we can fix this issue as soon as possible.

**Comment by rajatagrawal-dev** [comment]
Closing this issue on failure of receiving further updates. Please reopen it with latest logs if you encounter this issue again.
