### ISSUE TITLE
Copy Publish Artifact: "Artifact Type" help markdown is unclear

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/vsts-tasks#2476]
On the "Copy and Publish Build Artifacts" task, the help markdown for the "Artifact Type" input says "The type of artifact to create."  This adds no value because there is no explanation of the difference between "server" and "file share."  When possible, the help markdown should be sufficient to avoid having to visit the main documentation.

**Comment by ericsciple** [comment]
The general rule of thumb we've applied is a short sentence or two in the tooltip and anything more than that belongs in the docs.

**Comment by DavidStaheli** [comment]
Proposed slight improvement in PR #2513.
