### ISSUE TITLE
Publish Test Results task: associate results with a different build

### ISSUE THREAD

**Issue by julioct** [Microsoft/vsts-tasks#2478]
We would like to use the Publish Test Results VSTS task to publish test results that should be associated to a different build than the one that is running the task. This task would run from a different build definition than the one that actually performs the build, but we would like to have its results associated to that other build. However the task does not provide a parameter were we can specify the build that results should be associated to.

Is there a way this can be achieved?

**Comment by atinb** [comment]
This is not possible from the task. You can use the REST APIs to achieve this
Thanks!
