### ISSUE TITLE
Copy Publish Artifact: "Contents" input markdown is incorrect

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/vsts-tasks#2479]
On the "Copy and Publish Build Artifacts" task, the **Contents** input markdown is incorrect.  It says "Supports multiple lines or minimatch patterns" which is not accurate.

**Comment by ericsciple** [comment]
What's inaccurate? The task carries two implementations so something may have regressed or never reached parity on a specific platform.

**Comment by DavidStaheli** [comment]
Sorry, I should have been more clear.  The input field is a textbox, so it does not support multiple lines like the markdown suggests.

**Comment by ericsciple** [comment]
The Contents input is `"type": "multiLine"` and I'm able to enter multiple lines. Are you not able to enter multiple lines? What browser/OS are you using?

Or are you saying it doesn't _look_ like a multi-line input? I can't tell on my laptop - I'm on a small high-res monitor and Windows manipulates the size of inputs so they don't look really small - it does a good job most of the time, but i can't tell what the UI is _really_ supposed to look like.

**Comment by DavidStaheli** [comment]
Interesting.  I wonder why `multiLine` is appearing as a textbox.  I'm using the latest Chrome with a production account.  See below:

![copypublishscreenshot](https://cloud.githubusercontent.com/assets/1767415/18435623/5d8d086c-78c2-11e6-8024-33df49e9ff0d.png)

**Comment by ericsciple** [comment]
@yaananth ?

**Comment by yaananth** [comment]
That is just being displayed as textbox, but indeed it's textarea, will get styling fixed in current sprint. Next deployment should fix the look of it.
