### ISSUE TITLE
Gulp task fails if test result publishing is enabled

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/vsts-tasks#2483]
Enabling test results publishing in the Gulp task fails with this error:

> Unable to process logging event:##vso[results.publish type=JUnit;mergeResults=true;publishRunAttachments=true;resultFiles=C:/a/1/s/ArchiveFiles/test-results.xml;]

Using the "Publish Test Results" task instead to publish the same results succeeds.

See the build log here (ping me for access):
https://xplatalm.visualstudio.com/L2.Tasks/_build/index?buildId=2792&_a=summary

**Comment by nigurr** [comment]
@DavidStaheli are you using Legacy Windows Agent? If yes, what's the agent version?
Can you try to upgrade your agent to latest Legacy Windows Agent and run the same?
This is indeed fixed in 1.105.x and I am able to verify the same in 1.105.6

**Comment by DavidStaheli** [comment]
Hi @nigurr.  I confirmed that this is fixed with 1.105.x.  Thank you!
