### ISSUE TITLE
Clarification on task.setprogress value expected behavior

### ISSUE THREAD

**Issue by sheldonhull** [Microsoft/vsts-tasks#2493]
I couldn't find clarification in the documentation on the expected behavior of setting task progress. 

if ` ##vso[task.setprogress value =100;]` is updated, should this impact the task operation? 

For example, if I run a task, and this value gets set to 100 in the middle of the script and then run some post cleanup steps, is the expected behavior to 

1. terminate further execution, or to just update status in the timeline, 
2. Allow powershell/other continue to finish?

**Comment by bryanmacfarlane** [comment]
It doesn't affect execution at all.  It simply instructs the agent to update the progress of the current task.  The agent will in turn put that update message in a queue to batch up with console lines etc... and that feedback will make it down to all connected browsers watching that build via SignalR.

**Comment by sheldonhull** [comment]
Perfect. That's what I wanted to confirm. Thank you for the quick response.
