### ISSUE TITLE
MSBuild timeline logger error

### ISSUE THREAD

**Issue by PrashanthReddyAnnedla** [Microsoft/vsts-tasks#2498]
We are trying build one of our solution with VSTS Build task. The build is failed with below error. It looks like an issue with the build task itself.

Unable to process command '##vso[task.logdetail id=7810f8b5-0de4-474d-afba-d4d6b721aa9b;parentid=fb1f3040-fa78-4941-8832-2535c9be448a;type=Build;state=InProgress;starttime=2016-09-12T17:27:46.8338215Z]' successfully. Please reference documentaion (http://go.microsoft.com/fwlink/?LinkId=817296)
Name is required for this new timeline record.

**Comment by ericsciple** [comment]
Is this for the VSBuild task? As a workaround you can uncheck "Record project details" on the advanced section of the task.

A fix is rolling out for this and the deployment should be finishing in the last scale units soon. Which scale unit are you on? check `nslookup <account>.visualstudio.com` and the SU is indicated in the output, e.g. tfsprodscus***su5***.cloudapp.net

**Comment by PrashanthReddyAnnedla** [comment]
Yes, this is VSBuild task. Unchecked the "Record project details" and is working fine now.

SU : "tfsprodeus2su2.cloudapp.net"
