### ISSUE TITLE
Doesn't work ArchiveTask

### ISSUE THREAD

**Issue by titans2016** [Microsoft/vsts-tasks#2500]
Hi.
I want discuss ArchiveFiles tasks.
https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/ArchiveFiles

We uploaded to our  tfs this task. but we can't  execute this task (all value default. Error: The directory name is invalid).
In task.json I noticed, that during execution nodeJS task, call archivefiles.js
But I can't find this file on github. 
Can you please explain, how it's works?

**Comment by jasholl** [comment]
Hi.  During the build for this task the typescript file that is checked in, archivefiles.ts is compiled to the javascript file, archivefiles.js.  This is the general architecture for all the tasks written in typescript.  If you wish to upload to tfs using the tfx command line, what you need to do is first build the task.  There is some documentation at the root of this git repository on how to do this, but here's the cheat sheet.

- clone this git repo (which it seems like you have already done)
- install node from nodejs.org
- from root of your cloned git repo run npm update
- from the root of your cloned git repo run gulp
- install and configure the tfx command line utility (which it seems like you have already done)
- from the root of your cloned git repo run tfx build tasks upload --task-path _/build/Tasks/ArchiveFiles
- if tfx complains that the task could not be uploaded, then first remove it by running tfx build tasks delete --task-id taskID   (for taskID, use the value in the task.json file).
