### ISSUE TITLE
SVN externals checkbox defaults to "checked" even when saved as unchecked (TFS 2015 Update 3)

### ISSUE THREAD

**Issue by BastiDD** [Microsoft/vsts-tasks#2510]
Whether marked as fixed in #1491 the bug is still present on our build machine. We are using TFS 2015 update 3 (version 14.102.25423.0) on a Windows Server 2008R2 Server.

**Comment by bryanmacfarlane** [comment]
That fix didn't get in until TFS 15 which is about to release RC2.  Thanks for reporting.

**Comment by BastiDD** [comment]
We recently updated our production servers to TFS2015 update 3 and we really need the svn integration without this annoying bug. Is it possible to ship a hotfix for that?
