### ISSUE TITLE
Copy Files Over SSH: download to host not supported

### ISSUE THREAD

**Issue by matshal** [Microsoft/vsts-tasks#2514]
Copy Files Over SSH only supports uploadFile

downLoadFile() to host would be most valuable in integrations towards test and build systems.

**Comment by bryanmacfarlane** [comment]
our java team worked on

**Comment by DavidStaheli** [comment]
Thanks, @matshal.  This is on our backlog and I hope we get to it quickly.

**Comment by DavidStaheli** [comment]
Closing this issue now that it has been added to our backlog.
