### ISSUE TITLE
No tests were discovered from the specified test sources

### ISSUE THREAD

**Issue by Alcruz** [Microsoft/vsts-tasks#2520]
Hello, right now I am setting up a continuous deployment workflow, but I am getting the following error when the Run Functional Test task run. I think the problem is because I'm using xunit. I would appreciate any help.

![functional-test-conf](https://cloud.githubusercontent.com/assets/2265826/18528925/fc79f6a6-7a98-11e6-9617-41e53b3ab259.PNG)

![functional-test](https://cloud.githubusercontent.com/assets/2265826/18528926/fc7dc2e0-7a98-11e6-9946-128886ebb5dc.PNG)

**Comment by allendm-msft** [comment]
@Alcruz do you have the xunit adapter available on your test machine?
You would need to copy the xunit adapter from your vs machine (<VSIntallDir>\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions) to your test agent box (<TestAgentInstallDir>\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions\Microsoft.VisualStudio.TestPlatform.Extensions)

**Comment by Alcruz** [comment]
Hey @allendm-msft, In First place, thanks for taking your time to respond to my issue.

I went to the target directory (\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions) then I create Microsoft.VisualStudio.TestPlatform.Extensions folder and copy that dll within it. But same error has occurred.

When you said the xunit adapter, are you referring about "xunit.runner.visualstudio.testadapter.dll" ?

**Comment by allendm-msft** [comment]
Something is amiss. You shouldnt have to create the folder on your test machine. it should be present when you install the test agent. 

Yes the xunit adapter I am referring to is what you have noted above.

**Comment by Alcruz** [comment]
@allendm-msft, The issue was that I was not including the xunit dependencies with my test dlls, I included it with my tests binaries and It works great.

Thanks for the help.
