### ISSUE TITLE
MSBuild task: The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception

### ISSUE THREAD

**Issue by julioct** [Microsoft/vsts-tasks#2537]
Starting yesterday our builds are failing with this error:

C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\BuildInfo\Microsoft.VisualStudio.ReleaseManagement.BuildInfo.targets(147,5): warning : The type initializer for 'LibGit2Sharp.Core.NativeMethods' threw an exception. 
MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in the temporary files directory named MSBuild_*.failure.txt.

The warning comes from the **CreateTfsBuildInfoFile** target in Microsoft.VisualStudio.ReleaseManagement.BuildInfo.targets and is executed because we have configured our web project so that a **BuildInfo.config** file is generated during the build. We need that file for proper diagnostics of deployed bits, so we can’t disable its generation. 

I have confirmed that any build agent on version **1.105.6** hits this issue. However, build agents still in version **1.104.1** are not hitting this issue at all. We are very lucky in having 2 out of our 20 agents still in version 1.104.1, but for the most part the upgrade to 1.105.6 is totally breaking our builds. As soon as those two machines acquire the new version we will be blocked on producing new bits.

Can somebody investigate what’s going on there?

**Comment by bryanmacfarlane** [comment]
RM team added this msbuild target.

**Comment by RoopeshNair** [comment]
In VS 15, this feature has been removed.  It was added for AppInsights to enable deployment markers. AppInsights is no longer scanning for this file.

**Comment by GeorgeTsiokos** [comment]
It's been working for me in VS 15 with on-prem VS 15 builds.
Broke in VS 17, vsts builds: Microsoft/visualstudio-docs#81
AI still supports it: https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/develop/Src/WindowsServer/WindowsServer.Shared/BuildInfoConfigComponentVersionTelemetryInitializer.cs#L52

**Comment by GeorgeTsiokos** [comment]
I wrote a script that I ran on the vsts build agents and found that the `Hosted` agents have the targets file while `Hosted VS2017` do not:

Hosted agents
==========
 - Directory: C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v12.0\BuildInfo
 - Directory: C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\BuildInfo

Hosted VS2017 agents
==========
 - Not found

**Comment by SergeyKanzhelev** [comment]
@RoopeshNair Application Insights is still relying on `BuildInfo.config`. Can the target be added back?

**Comment by RoopeshNair** [comment]
AFAIK, Feature was deprecated and removed from VS2017. 
It is recommended to use AppInsights for diagnostic requirements.
https://azure.microsoft.com/en-us/documentation/articles/app-insights-visual-studio/

**Comment by SergeyKanzhelev** [comment]
@RoopeshNair I'm working in Application Insights. And we DO still rely on it. My question is why it was cut without notifying us and can it  be returned back?

**Comment by piotrzaremba** [comment]
Can I ask why this bug is closed?  This is an open issue in several of my teams code bases, especially since we heavily rely on Application Insights and the following plugin that we use to annotate releases in Application Insights.  The following extension that Microsoft supports also requires a BuildInfo.config file.

https://marketplace.visualstudio.com/items?itemName=ms-appinsights.appinsightsreleaseannotations

**Comment by GeorgeTsiokos** [comment]
@RoopeshNair https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/master/Src/WindowsServer/WindowsServer.Shared/BuildInfoConfigComponentVersionTelemetryInitializer.cs
