### ISSUE TITLE
VSTS agents - java memory is not getting released

### ISSUE THREAD

**Issue by penupati** [Microsoft/vsts-tasks#2538]
Hi,
We are running Junit test cases using Ant build tool in vso agents (Linux machines).
This VM RAM is 28 GB. We are running 2 agents in one Linux machine.
When Junit test cases are running, 27 memory is getting consumed which is not getting released completely. Due to which when next VSTS tests starts, unable to execute test cases due to low memory.
Can you please let us know what is the issue here with vso agents?

**Comment by bryanmacfarlane** [comment]
This is likely not an agent or task issue.  The task is simply calling the ant cmd line tools.

Have you looked into which process is using that memory?

Note that we also run the task and the worker process out of proc so the process (and any memory it consumed) goes away after the task and job run.

Also include what you are using.  On-prem?  which version?  VSTS?  which agent version?  etc...

Run a cmd line or script task after your tests to dump process info.

**Comment by DavidStaheli** [comment]
Hi @penupati, is this still an issue for you and something we can help with?  Otherwise, I will close this issue.  Thank you.

**Comment by DavidStaheli** [comment]
Hi @penupati, thank you for reporting this issue.  I will close it for now, but please do not hesitate to comment or reopen it if we can assist you in any way.
