### ISSUE TITLE
AzureRMWebAppDeployment fails on version 1.0.19

### ISSUE THREAD

**Issue by nelsonmorais** [Microsoft/vsts-tasks#2547]
The AzureRMWebAppDeployment fails after it was updated to version 1.0.19 (version 1.0.16 was working fine).

The error message is:
...
279 2016-09-16T10:19:38.3131207Z msdeploy command ran successfully.
280 2016-09-16T10:19:38.3756495Z Updating deployment status
**281 2016-09-16T10:19:38.5631205Z ##[error]You cannot call a method on a null-valued expression.**
_282 2016-09-16T10:19:38.5787459Z Finishing task: AzureRMWebAppDeployment_
**283 2016-09-16T10:19:38.6099957Z ##[error]System.Exception: Task AzureRMWebAppDeployment failed. This caused the job to fail. Look at the logs for the task for more details.**
**284 2016-09-16T10:19:38.6099957Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Worker.JobRunner.Run(IJobContext jobContext, IJobRequest job, IJobExtension jobExtension, CancellationTokenSource tokenSource)**

Apparently this situation has occured before on some other similar task and required a fix, see: https://github.com/Microsoft/vsts-tasks/issues/1121

Is there a workaround so that I can run the deployment?

I tried to rename the directory 1.0.19 of the task, but as soon as the deployment process started the task with th version 1.0.19 was downloaded again. Is there a way to force the usage of a previous version, 1.0.16 for instance?

**Comment by nelsonmorais** [comment]
Update:
I tried to copy the contents of a previous version (1.0.16 and 1.0.14) of the task to the 1.0.19 folder to see if I could workaround the problem, but I got the same error message. 

Now I start to think that the problem might not be with the task but with something else, maybe the agent (current version is 15.**105**.25714.0 previous was 15.**104**.25617.0) because it was also updated.

Any suggestions for a quick workaround are very welcome :)

**Comment by bryanmacfarlane** [comment]
Right after it write updating deployment status, it makes an http call to azure

https://github.com/Microsoft/vsts-tasks/blob/5d91ca69deb68daf0810435c4f9cc3360a25ddb2/Tasks/AzureWebPowerShellDeployment/Publish-AzureWebDeployment.ps1#L173

**Comment by bryanmacfarlane** [comment]
Looks like it makes an azure http call after logging updating status

https://github.com/Microsoft/vsts-tasks/blob/5979a762a3ab90e3af878c670070ac3474af0569/Tasks/AzureRmWebAppDeployment/Utility.ps1#L364

What's odd is it's done in a try catch.  Perhaps it's failing in the catch handler?  Maybe formatting the message?  response body or something null?  Just a guess.

**Comment by Ajay-MS** [comment]
@nelsonmorais  

In catch part error is first being shown as warning so need to enable debug logs and after that error is being shown as warning but in between some reference results into null. To identify actual cause need verbose logs.

Add a variable system.debug and its value to be true and share logs at RM_Customer_queries@microsoft.com and ajya@microsoft.com.

**Comment by nelsonmorais** [comment]
@bryanmacfarlane / @Ajay-MS I agree with you both.

I've set the variable System.Debug = true and I have now a bit more info:

- Apparentely the certificate for the xxxxx.scm.azurewebsites.net is not valid see error in line 982 and image attached of the invalid certificate
- Because of that the PUT command fails and inside the catch the $response might be null see error line 1012

I believe that if the certificate problem gets fixed, our issue is gone, but in any case the catch handler should be improved also.

Our question now is, why is the certificate for xxxxxx.scm.azurewebsites.net invalid?
![invalid certificate](https://cloud.githubusercontent.com/assets/4737667/18585757/1d669cb2-7c19-11e6-9d9b-d770c2ecf950.png)


980 2016-09-16T11:54:24.8356930Z Updating deployment status
981 2016-09-16T11:54:24.8513242Z ##[debug]PUT https://XXXXXXXXXX.scm.azurewebsites.net/deployments/123321123321 with -1-byte payload
**982 2016-09-16T11:54:25.0075734Z ##[debug]System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.**
983 2016-09-16T11:54:25.0075734Z ##[debug]   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, Exception exception)
984 2016-09-16T11:54:25.0075734Z ##[debug]   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
985 2016-09-16T11:54:25.0075734Z ##[debug]   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
986 2016-09-16T11:54:25.0075734Z ##[debug]   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
987 2016-09-16T11:54:25.0075734Z ##[debug]   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
988 2016-09-16T11:54:25.0075734Z ##[debug]   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
989 2016-09-16T11:54:25.0075734Z ##[debug]   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
990 2016-09-16T11:54:25.0075734Z ##[debug]   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
991 2016-09-16T11:54:25.0075734Z ##[debug]   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
992 2016-09-16T11:54:25.0075734Z ##[debug]   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
993 2016-09-16T11:54:25.0075734Z ##[debug]   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
994 2016-09-16T11:54:25.0075734Z ##[debug]   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
995 2016-09-16T11:54:25.0231977Z ##[debug]   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
996 2016-09-16T11:54:25.0231977Z ##[debug]   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
997 2016-09-16T11:54:25.0231977Z ##[debug]   at System.Net.ConnectStream.WriteHeaders(Boolean async)
998 2016-09-16T11:54:25.0231977Z ##[debug]   --- End of inner exception stack trace ---
999 2016-09-16T11:54:25.0231977Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
1000 2016-09-16T11:54:25.0231977Z ##[debug]   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
1001 2016-09-16T11:54:25.1013321Z ##[debug]Leaving C:\VSTS-Agent\VSTS Build and Deploy Agent - 2016-07-04\tasks\AzureRMWebAppDeployment\1.0.19\AzureRMWebAppDeployment.ps1.
1002 2016-09-16T11:54:25.1013321Z ##[debug]Caught exception from task script.
1003 2016-09-16T11:54:25.1169505Z ##[debug]Error record:
1004 2016-09-16T11:54:25.2419618Z ##[debug]Update-DeploymentStatus : You cannot call a method on a null-valued expression.
1005 2016-09-16T11:54:25.2419618Z ##[debug]At C:\VSTS-Agent\VSTS Build and Deploy Agent - 2016-07-04\tasks\AzureRMWebAppDeployment\1.0.19\AzureRMWebAppDeployment.ps1:110 char:5
1006 2016-09-16T11:54:25.2419618Z ##[debug]+     Update-DeploymentStatus -azureRMWebAppConnectionDetails $azureRMW ...
1007 2016-09-16T11:54:25.2419618Z ##[debug]+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1008 2016-09-16T11:54:25.2419618Z ##[debug]    + CategoryInfo          : InvalidOperation: (:) [Update-DeploymentStatus], RuntimeException
1009 2016-09-16T11:54:25.2419618Z ##[debug]    + FullyQualifiedErrorId : InvokeMethodOnNull,Update-DeploymentStatus
1010 2016-09-16T11:54:25.2419618Z ##[debug] 
1011 2016-09-16T11:54:25.2419618Z ##[debug]Script stack trace:
**1012 2016-09-16T11:54:25.2575680Z ##[debug]at Update-DeploymentStatus, C:\VSTS-Agent\VSTS Build and Deploy Agent - 2016-07-04\tasks\AzureRMWebAppDeployment\1.0.19\Utility.ps1: line 371**
1013 2016-09-16T11:54:25.2575680Z ##[debug]at <ScriptBlock>, C:\VSTS-Agent\VSTS Build and Deploy Agent - 2016-07-04\tasks\AzureRMWebAppDeployment\1.0.19\AzureRMWebAppDeployment.ps1: line 110
1014 2016-09-16T11:54:25.2575680Z ##[debug]at <ScriptBlock>, <No file>: line 1
1015 2016-09-16T11:54:25.2575680Z ##[debug]at <ScriptBlock>, <No file>: line 22
1016 2016-09-16T11:54:25.2575680Z ##[debug]at <ScriptBlock>, <No file>: line 18
1017 2016-09-16T11:54:25.2575680Z ##[debug]at <ScriptBlock>, <No file>: line 1
1018 2016-09-16T11:54:25.2575680Z ##[debug]Exception:
1019 2016-09-16T11:54:25.2731961Z ##[debug]System.Management.Automation.RuntimeException: You cannot call a method on a null-valued expression.
1020 2016-09-16T11:54:25.2731961Z ##[debug]   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
1021 2016-09-16T11:54:25.2731961Z ##[debug]   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
1022 2016-09-16T11:54:25.2731961Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
1023 2016-09-16T11:54:25.2731961Z ##[debug]   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
1024 2016-09-16T11:54:25.2731961Z ##[debug]   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
1025 2016-09-16T11:54:25.2731961Z ##[debug]   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
1026 2016-09-16T11:54:25.2731961Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
1027 2016-09-16T11:54:25.2731961Z ##[debug]   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
1028 2016-09-16T11:54:25.2731961Z ##[debug]   at System.Management.Automation.CommandProcessorBase.Complete()
1029 2016-09-16T11:54:25.3044510Z ##[error]You cannot call a method on a null-valued expression.

**Comment by nelsonmorais** [comment]
@Ajay-MS I tried to sent the email to the accounts you have mentioned using my work account at nelson.morais at philips.com but I got a response of sender not allowed, so I posted the message above here.

**Comment by Ajay-MS** [comment]
@nelsonmorais  I got email from you. Thanks for your analysis it's true that $response is null in catch I will fix that bug. I am trying to find why is the certificate for xxxxxx.scm.azurewebsites.net is showing invalid for you, will update you on it.
Meanwhile you can unblock by removing following lines
[https://github.com/Microsoft/vsts-tasks/blob/5979a762a3ab90e3af878c670070ac3474af0569/Tasks/AzureRmWebAppDeployment/Utility.ps1#L370-L376](https://github.com/Microsoft/vsts-tasks/blob/5979a762a3ab90e3af878c670070ac3474af0569/Tasks/AzureRmWebAppDeployment/Utility.ps1#L370-L376
)

**Comment by nelsonmorais** [comment]
@Ajay-MS Thanks for the fast response. I've just deleted the web sites and I'm creating the resources again to see if the problem with the certificates gets fixed somehow. I'll post an update also.

**Comment by nelsonmorais** [comment]
@Ajay-MS 
Recreating the Web Sites resources did not fix the certificate problem.
Commenting the lines avoids the exception inside the catch but the deployment still fails because of the invalid certificate, see log below. So we still can't deploy :(

279 2016-09-16T13:27:38.8440416Z Updating deployment status
280 2016-09-16T13:27:39.0003055Z ##[warning]Cannot update deployment status for  - 
281 2016-09-16T13:27:39.1096504Z ##[error]Error Code: ERROR_CERTIFICATE_VALIDATION_FAILED More Information: Connected to the remote computer ("cseudev.scm.azurewebsites.net") using the specified process ("Web Management Service"), but could not verify the serverΓÇÖs certificate. If you trust the server, connect again and allow untrusted certifica tes.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CERTIFICATE_VALIDATION_FAILED.
282 2016-09-16T13:27:39.1096504Z ##[error] Error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel.
283 2016-09-16T13:27:39.1096504Z ##[error] Error: The remote certificate is invalid according to the validation procedure.
284 2016-09-16T13:27:39.1096504Z ##[error] Error count: 1.
285 2016-09-16T13:27:39.1252646Z Finishing task: AzureRMWebAppDeployment
286 2016-09-16T13:27:39.1565203Z ##[error]System.Exception: Task AzureRMWebAppDeployment failed. This caused the job to fail. Look at the logs for the task for more details.
287 2016-09-16T13:27:39.1565203Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Worker.JobRunner.Run(IJobContext jobContext, IJobRequest job, IJobExtension jobExtension, CancellationTokenSource tokenSource)

**Comment by nelsonmorais** [comment]
@Ajay-MS 
After reading http://www.iis.net/learn/publish/troubleshooting-web-deploy/web-deploy-error-codes#ERROR_CERTIFICATE_VALIDATION_FAILED and changing the msdeploy tasks to include the extra parameter -allowUntrusted I was able to deploy the web sites.

We still have the problem with the certificates for *.scm.azurewebsites.com which continue to be invalid, sou we sould still like to have an update from you on this topic if possible.

**Comment by Ajay-MS** [comment]
@nelsonmorais 
With passing -allowUntrusted as additional argument , i assume your RD succeed. I hope you are unblocked for now. Right?

Since your are getting certificate being invalid, after an discussion with team I will respond to you for sure.

**Comment by nelsonmorais** [comment]
@Ajay-MS Indeed! I was able to deploy for now using the -allowUntrusted as an additional argument to the MSDeploy task.

I'll for your feedback regarding the certificate issue.

Thanks!

**Comment by Ajay-MS** [comment]
@nelsonmorais 
As per conversation with @davidebbo closing this issue. If you face this issue in future, feel free to open it again. Thanks for debugging during issue.
