### ISSUE TITLE
Deploy.ps1 Failed to contact Naming Service

### ISSUE THREAD

**Issue by ccanuel** [Microsoft/vsts-tasks#2558]
@EricJizbaMSFT 
commit 18053ec804ced925adb07847b07b572966762d54

$clusterConnectionParameters["ConnectionEndpoint"] = ([System.Uri]$connectedServiceEndpoint.url).Authority # Authority includes just the hostname and port

This is not true. ".Authority" does NOT include the port. resulting in
## [error]No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS issue.

Quick fix (but sloppy)
$clusterConnectionParameters["ConnectionEndpoint"] += ":19000"

**Comment by EricJizbaMSFT** [comment]
According to [the documentation](https://msdn.microsoft.com/en-us/library/system.uri.authority(v=vs.110).aspx), it "Gets the Domain Name System (DNS) host name or IP address _and the port number_ for a server."

Could you share a screenshot of your service endpoint configuration? There could be an edge case we're not handling. You can also set 'System.Debug' to 'true' in your release definition and the logs might have more information about the error

**Comment by ccanuel** [comment]
Yes that's prob right but Azure support wants me to deal with this bug here (which has already cost us 2 dev days plus 4 days of 4 hosted agents plus 3 day of 4 local agents already).

So here we are

![2016-09-19 17_57_58-photos](https://cloud.githubusercontent.com/assets/15924840/18639135/fd68b1c6-7e92-11e6-9d65-2f73ac2335df.png)

I have also the "System.Debug" cause that's what i used to debug this. But I'd rather not post that here in public.

**Comment by EricJizbaMSFT** [comment]
Sorry I meant a screenshot of your service endpoint in VSTS. Is the endpoint prefixed with 'https://' or 'http://'?

**Comment by ccanuel** [comment]
HTTP:// (or none depending on which variable you are talking about)

I used this inside the deploy.ps1

#DEBUG
"Endpoint:"
$connectedServiceEndpoint | ConvertTo-Json -Depth 32
#/DEBUG
...
#DEBUG
"ConnectionEndpoint:" + $clusterConnectionParameters["ConnectionEndpoint"]
$clusterConnectionParameters["ConnectionEndpoint"] += ":19000"
#/DEBUG

And got this
2016-09-19T10:01:36.9147458Z Endpoint:
2016-09-19T10:01:37.7701117Z {
2016-09-19T10:01:37.7701117Z     "Url":  "http://blablabla.westeurope.cloudapp.azure.com/",
2016-09-19T10:01:37.7701117Z     "Data":  {
2016-09-19T10:01:37.7701117Z              },
2016-09-19T10:01:37.7701117Z     "Auth":  {
2016-09-19T10:01:37.7701117Z                  "scheme":  "None"
2016-09-19T10:01:37.7701117Z              }
2016-09-19T10:01:37.7701117Z }
2016-09-19T10:01:37.7860996Z ConnectionEndpoint:blablabla.westeurope.cloudapp.azure.com

**Comment by EricJizbaMSFT** [comment]
I'm talking about in your *.visualstudio.com account -> Team Settings -> Services -> <your service endpoint> -> Update service configuration

It should look like this:
![untitled](https://cloud.githubusercontent.com/assets/11282622/18641174/4c0870b6-7e50-11e6-83fa-6337fca71005.png)

**Comment by ccanuel** [comment]
was 
http://blablabla.westeurope.cloudapp.azure.com/
is now (guessing who ever set this up missed that)
https://blablabla.westeurope.cloudapp.azure.com:19000/

i added the ":19000" cause that's what you had in your example. 
and added "https" cause it said "Prefix the value with "https://". This value overrides the publish profile."

**Comment by EricJizbaMSFT** [comment]
Closing since the solution was to add the port in the service endpoint. Reopen if you're still having issues.

**Comment by majkelllo** [comment]
How to reopen the issue ? I started having this error yesterday. ( I've seen there was some maintanance done, as i've seen my clusters were in "updating infrastructure" status. I'm definitely using the right endpoint with 19000. Any ideas ?

**Comment by EricJizbaMSFT** [comment]
@mthalman-msft

**Comment by MikkelHegn** [comment]
One thing to note is that we changed the required input to be prefixed with tcp:// so tcp://mycluster.FQDN:19000 would be the right input.
@majkelllo You posted an issue on SF issue with authentication issues. Is this the same issue? https://github.com/Azure/service-fabric-issues/issues/146

**Comment by majkelllo** [comment]
Yes that was the same issue. Prefixing with tcp:// solved the problem. Thanks.

**Comment by MikkelHegn** [comment]
@kmkumaran I think you can close this again (I do not have access to do that)

**Comment by joshiabk** [comment]
I just would like to know, how to get connected to SF Cluster Endpoints from behind corporate proxy?
As I am getting below 

> WARNING: Failed to contact Naming Service. Attempting to contact Failover Manager Service... WARNING: Failed to contact Failover Manager Service, Attempting to contact FMM... False WARNING: No connection could be made because the target machine actively refused it 40.117.45.185:19000 Connect-ServiceFabricCluster : No cluster endpoint is reachable, please check if there is connectivity/firewall/DNS issue. At line:1 char:1 + Connect-ServiceFabricCluster -ConnectionEndpoint mycluster.westus.cloudap ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : InvalidOperation: (:) [Connect-ServiceFabricCluster], FabricException + FullyQualifiedErrorId : TestClusterConnectionErrorId,Microsoft.ServiceFabric.Powershell.ConnectCluster


Help would be appreciated.

**Comment by MikkelHegn** [comment]
@joshiabk PowerShell CmdLets connect to port 19000 on remote clusters.

**Comment by afcook** [comment]
joshiabk Did you ever solve your problem with deploying to cluster on corporate side? I have the same challenge

**Comment by joshiabk** [comment]
Hi @afcook in corporate connectivity there are many restrictions on the port. So I tried to connect azure from other network and it is working. So possibly need to ask IT team to grant the permissions.

**Comment by nithya7969** [comment]
@EricJizbaMSFT Can you please reopen this issue? I am facing the same problem as above (please look at the screenshot). None of the above solutions worked for me. 

![image](https://user-images.githubusercontent.com/14325992/39011467-18bac648-43d7-11e8-88af-c2260e9714f5.png)

![image](https://user-images.githubusercontent.com/14325992/39011563-695e7d9c-43d7-11e8-966f-b24770ea4a5d.png)

I have already wasted a week over this. Please fix this ASAP.

**Comment by EricJizbaMSFT** [comment]
Unfortunately I haven't worked on Service Fabric for over a year now and can't really help you. This issue (and this repository) is specifically for Service Fabric _on VSTS_, but from your screenshot it appears that you're having issues outside of VSTS. I recommend getting more general Service Fabric support from one of the options listed here: https://docs.microsoft.com/azure/service-fabric/service-fabric-support
