### ISSUE TITLE
Azure Deployment task status showing succeeded though the deployment is failed

### ISSUE THREAD

**Issue by PrashanthReddyAnnedla** [Microsoft/vsts-tasks#2569]
I am using Azure deployment task for WebApp deployments. The task status is showing as succeeded though we have an error in the logs and the deployment is not succeeded. 

2016-09-19T19:32:09.7471700Z ##[error]Unable to perform the operation ("Delete File")  for the specified directory ("D:\home\site\wwwroot\bin\Microsoft.IdentityModel.dll"). This can occur if the server administrator has not authorized this operation for the user credentials you are using.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_INSUFFICIENT_ACCESS_TO_SITE_FOLDER.
 
Is there anyway to fail the task if the deployment has any errors with it.

**Comment by kmkumaran** [comment]
@PrashanthReddyAnnedla - Can you tell us which task you are using and facing this issue. Is it "Azure Web App Deployment" or "AzureRM App Service Deployment".

**Comment by PrashanthReddyAnnedla** [comment]
Its "Azure Web App Deployment"

**Comment by vincentdass** [comment]
@PrashanthReddyAnnedla , thanks for reporting. It will be fixed in upcoming release.

**Comment by PrashanthReddyAnnedla** [comment]
@vincentdass - Attached the log file. I am not sure about the task version, it wont display in the log output.
[Log.txt](https://github.com/Microsoft/vsts-tasks/files/485710/Log.txt)

Scale Unit : "tfsprodeus2su2.cloudapp.net"

**Comment by vincentdass** [comment]
@PrashanthReddyAnnedla , **"-verbose"** is provided in **Additional Arguments**. This makes the command not to throw any error, even if they fail. You task will throw error for failure cases, by removing it.

**Comment by PrashanthReddyAnnedla** [comment]
@vincentdass - Thanks for the update. Will remove it from the additional arguments
Closing this thread. Will Re-Activate if we still see this issue.
