### ISSUE TITLE
JS content in Task definition.

### ISSUE THREAD

**Issue by marag** [Microsoft/vsts-tasks#2621]
Is it possible or will be possible to add JS script in Task content? for instance for dynamically manipulate with parameters  or do the simple verification of field. 

For now, the task has only a few  kind of input allowed in task.json file.  Is there any plans to increase it with Table,  Label e.t. ?

**Comment by bryanmacfarlane** [comment]
We've considered have js extensions as part of the task.  It's on our backlog (for the service, not this task repo).  

In the meantime, you have the basic types and current task.json behaviors and then it's agent side runtime failures / messaging.  not ideal, we know.
