### ISSUE TITLE
xctool deprecated

### ISSUE THREAD

**Issue by aldodfm** [Microsoft/vsts-tasks#2626]
Hello,

https://github.com/facebook/xctool <- xctool is deprecated.

> Note: Support for building projects with xctool is deprecated and will not be updated to support future versions of Xcode. We suggest moving to xcodebuild (with xcpretty) for simple needs, or xcbuild for more involved requirements. xctool will continue to support testing (see above).

**Comment by bryanmacfarlane** [comment]
Yep - we just finished up xcpretty support this sprint.  + Madhuri

**Comment by madhurig** [comment]
@aldodfm: xcpretty support will roll out to Team Services with the currently ongoing deployment. You can see all the release notes here: https://www.visualstudio.com/en-us/articles/news/2016/sep-21-team-services. We haven't removed xctool support from the task yet but we will mark it deprecated in the next deployment.
