### ISSUE TITLE
Azure Deployment: DoNotDelete for specif folder

### ISSUE THREAD

**Issue by jirisykora83** [Microsoft/vsts-tasks#2630]
Hi,

is possible in Azure Deployment task set "DoNotDelete" for specific folder? When i uploading some image in my app to /wwwroot/img folder and i want not delete it on every deployment. It is possible via some additional arguments?

**Comment by Ajay-MS** [comment]
@jirisykora83 

Yes you can skip your image folder from being deleted with every deployment. You just need to skip that folder.

Use following command as value of additional argument
`-skip:Directory=wwwroot\\images`

**Comment by jirisykora83** [comment]
@Ajay-MS Thank you very much for your advice 👍
