### ISSUE TITLE
Add cache / restore artifacts feature

### ISSUE THREAD

**Issue by NGPixel** [Microsoft/vsts-tasks#2637]
When running a command like **npm install**, it currently re-downloads all node module dependencies on every build, which is time consuming and repetitive.

Some CI services have resolved this issue by introducing cache folders. You can specify folders that are backup at the end of a build, stored as a zip, then restored on the next build. This significantly reduces build time. It would be great for VSTS to have a similar feature.

Another solution would be to have a task to restore artifacts from the previous build. This would probably be the fastest to implement as the **Publish Build Artifacts** task already exists. It just needs the reverse.

Thanks!
Nick

**Comment by zjrunner** [comment]
Interesting, but it sounds like a general build infra request and not unique to npm.  I'll take it offline and either get it into our backlog or the generic Build backlog and find it a home.
