### ISSUE TITLE
EF Core Migrations - No executable found matching command "dotnet-ef"

### ISSUE THREAD

**Issue by srfabio** [Microsoft/vsts-tasks#2643]
We are trying to generate SQL scripts for the migrations `dotnet ef migrations script {...}` as part of the build process but there doesn't seem to be a way of dealing with them at the moment (other than using visual studio). I might be missing something here but both vso build agents and azure apps are unable to apply migrations so I'm wondering how to do it as part of the CI/deployment pipeline.

Thanks

**Comment by bryanmacfarlane** [comment]
What do you do locally on your dev box on the command line?  And does that work?

**Comment by srfabio** [comment]
Locally I can run `dotnet ef {any command}` and it works fine.

**Comment by bryanmacfarlane** [comment]
What version of VS is installed?  What version of dotnet is installed?  What is the log output when you run it as part of the CI build?

**Comment by srfabio** [comment]
Visual studio 2015 Update 3 and dotnet 1.0.0-preview2-003131

Running as part of the CI build gives me this: `No executable found matching command "dotnet-ef"` .The offending build step is just a command line executing "dotnet ef migrations {etc}"

**Comment by srfabio** [comment]
Not sure if this is really relevant to the case but here's a section of the project.json:

`  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final",
    "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "net461": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  }`

**Comment by chrisrpatterson** [comment]
Have you restored your nuget packages?

**Comment by bryanmacfarlane** [comment]
@srfabio ?

**Comment by srfabio** [comment]
I'm sorry for the delay. Yes we did restore nuget as the first build step but that didn't solve the problem.

However, looks like we solved it by changing the working folder to 'src/{project}' on the command line step.

Thanks

**Comment by bryanmacfarlane** [comment]
Thanks for following up.

**Comment by bragma** [comment]
Hi @srfabio 
can you please explain how you use the script to apply a migration from VSTS?
Thanks!

**Comment by srfabio** [comment]
Hi @bragma 
I don't have access to the code or VSTS anymore but essentially we've used the script to generate SQL files as part of the build process and then on the Release definition we had a step that would deploy/execute those scripts on our Azure database. That was the only way we could deploy migrations on azure.

Hope this helps (sorry for the lack of detail)

**Comment by bragma** [comment]
@srfabio thanks it's what I expected. I was looking for an official way for handling migrations in Azure when deploying from VSTS.

**Comment by jholovacs** [comment]
I still can't get this to work.  Very frustrating.  I have a script after deployment is done that is supposed to run 
`dotnet ef database update`
and it blows up the build with
`No executable found matching command "dotnet-ef"`
I even included a line in my csproj file like so:
```
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.2" />
  </ItemGroup>
```
...but it seems to be ignored.

**Comment by srfabio** [comment]
@jholovacs That's the error I had before, I only needed to change the working folder path to src/{project_name}

**Comment by K-Ikram** [comment]
I doesn't work, still have the same error

**Comment by ronnieoverby** [comment]
*(#&%$*(#&$! I'm dealing with this too!

**Comment by rodyvansambeek** [comment]
I had the same problem. 
But changing the build definition to something like the following works: 

```
- task: DotNetCoreCLI@2
  displayName: 'Generate EF Migrations script'
  inputs:
    command: custom
    custom: 'ef'
    arguments: 'migrations script --project $(project) --output $(Build.ArtifactStagingDirectory)/SQL/$(scriptName) --context $(dbContext)  --idempotent'

```

It looks like the dotnet Core custom build task puts a dash between the dotnot executable and the custom command contains spaces. This seems like a bug. 

Please reopen this issue.

**Comment by Marbulinek** [comment]
I had the same issue exactly in Azure Pipelines and finally this is my solution:
Command Line step:
`steps:
- script: '$env:ASPNETCORE_ENVIRONMENT='Development''
  displayName: 'Set DB Environment'
`

Command Line step: (also define working directory of project)
`steps:
- script: 'dotnet-ef database update --project $(project)'
  workingDirectory: TunelHelperApi
  displayName: 'Database Update'
  continueOnError: true
`
