### ISSUE TITLE
Archive tasks suddenly stop working when Prefix root folder name to archive paths is not checked

### ISSUE THREAD

**Issue by brunobertechini** [Microsoft/vsts-tasks#2646]
[log.txt](https://github.com/Microsoft/vsts-tasks/files/489639/log.txt)
Hello there,

I have couple release definitions using Extract/Archive tasks working for a while. YEsterday, suddenly, the archive task stopped working with this error:

Archive creation failed for archive file: C:\a\r1\a{Artifact_Build_Name}\drop\MyProject.zip

It happens only when I uncheck the "Prefix root folder name to archive paths" option. If I check this option it works fine. But, since this is a webdeploy package im extracting/compacting I still need to use the "flat" files in the archive.

Im guessing the error is relative to " current working directory" where 7z.exe is triggered. It says:

[command]C:\a_tasks\ArchiveFiles_d8b84976-e99a-4b86-b885-4849694435b0\1.0.5\7zip\7z.exe a -tzip C:\a\r1\a{Artifact_Name}\drop\MyPackagedFile.zip archive.xml Content parameters.xml systemInfo.xml

File not found. (see log attached)

It was working until yesterday...

log.txt

**Comment by brunobertechini** [comment]
I tried to replace the default Archive/Extract files with TotalALM 7zip but ran into another issue

[https://github.com/TotalALM/VSTS-Tasks/issues/14](url)

**Comment by brunobertechini** [comment]
Im stuck with builds failing and cant go any further

**Comment by jasholl** [comment]
Sorry for your troubles.  My hunch is this recent change to fix a bug with the current working directory not working correctly when a file was specified (instead of a folder) broke your scenario:  commit: c168a3facbf5e66ebf74bf280f7a2080252f3c8c  Could you run your build again with system.debug=true and include the log file to confirm this.  I'm working on a fix for you.

**Comment by brunobertechini** [comment]
Thank you. Is this Syste,.debug a variable right ?

**Comment by jasholl** [comment]
Yes, system.debug is a variable.  If you manually trigger the build, you should see the option to enable it for that single build in the dialog.  You can also enable it in the build definition itself on the variables page -- this will affect all runs for this build definition.

**Comment by brunobertechini** [comment]
Please find in attachment the Task log.

[5_Archive files .txt](https://github.com/Microsoft/vsts-tasks/files/490211/5_Archive.files.txt)

**Comment by jasholl** [comment]
Thanks.  Yes, I think it is as I expected -- it's miss calculating the current working directory; it should be C:\a\r1\a\WBM_Web\ but is coming back with C:\a\r1\a\WBM_Web\drop.  Drop me an email at jasholl  at microsoft dot com and I'll get you a new version of this task to try -- and maybe we can jump on the phone too if you need help setting it up.

**Comment by jasholl** [comment]
Oh, and what version of the agent is running; you should see that at the very top of the log for the entire build.  I'm presuming it's 2.107.0

**Comment by brunobertechini** [comment]
AgentVersion: 2.107.0

**Comment by brunobertechini** [comment]
Sent you an email to get the new version.

**Comment by jasholl** [comment]
Send you the new task with instructions.  If all goes well, this is the fix: https://github.com/Microsoft/vsts-tasks/pull/2649

**Comment by brunobertechini** [comment]
Task Updated. Release completed successfully.

Version 1.0.6 is back on the game ;)

**Comment by brunobertechini** [comment]
Thank you very much. What should I do when the new version is available?

Bruno

**Comment by jasholl** [comment]
You shouldn't need to do anything, the task will automatically be updated when the new version roles out.
