### ISSUE TITLE
Invalid Swift Support - The SwiftSupport folder is empty.

### ISSUE THREAD

**Issue by aldodfm** [Microsoft/vsts-tasks#2647]
Hello,

It seems that when you want to release your .IPA apps that use with Swift language, instead of compiling the IPA file with :
`xcr.arg(['-sdk', sdk, 'PackageApplication', '-v', app, '-o', ipa]);`

You need to use: 
`xcodebuild -exportArchive -exportFormat ipa -archivePath <path to archive> -exportPath <path to output>`

Something that it's explained here: [XCArchive to ipa](https://encyclopediaofdaniel.com/blog/xcarchive-to-ipa/)

So, right now, with the current xcode task only works with objective-c projects, if you want to compile Swift project or projects with libraries in swift, you will receive an email from Apple saying:

> Invalid Swift Support - We have discovered one or more issues with your recent delivery for XXXXX(my app name). To process your delivery, the following issues must be corrected:
> 
> Invalid Swift Support - The SwiftSupport folder is empty. Rebuild your app using the current public (GM) version of Xcode and resubmit it.
> 
> Once these issues have been corrected, you can then redeliver the corrected binary.

Right now i fixed this issue with following build definition steps:

1. INSTALL cocoapods
2. Xcode build (without xctool)
3. execute shell script [package_ipa.sh](https://github.com/bq/ipa-packager/blob/fe3df2bdcf626128e99bbe691cf50849ef347491/package_ipa.sh) with arguments: $(agent.builddirectory)/output/$(SDK)/$(Configuration)/build.sym/$(Configuration)-$(SDK)/$(APPLICATION_NAME).app $(agent.builddirectory)/output/$(SDK)/$(Configuration)/build.sym/$(Configuration)-$(SDK)/$(APPLICATION_NAME).ipa

With this shell script, i can publish perfectly to testFlight with [vsts-itunes task](https://github.com/Microsoft/app-store-vsts-extension)

**Comment by bryanmacfarlane** [comment]
What version of XCode?

**Comment by madhurig** [comment]
@aldodfm: Thanks for the details, I will update the task to use xcodebuild -exportArchive if it is Xcode 7 or higher

**Comment by aldodfm** [comment]
@madhurig , please take care about exportOptionsPlist file, where is defined what target will be exported. ;)

**Comment by madhurig** [comment]
https://github.com/Microsoft/vsts-tasks/pull/2701

**Comment by madhurig** [comment]
Fix has been merged and will be deployed to Team Services starting Oct 16th and should roll out to all accounts in about a week.
