### ISSUE TITLE
Add template URL support to DeployAzureResourceGroup

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/vsts-tasks#2652]
If you specify a URL for the template file this task adds 'C:\a\r1\a\' as a prefix and then fails because that is obviously an invalid location.
```
No files were found to deploy with search pattern 'C:\a\r1\a\https:\\mysa.blob.core.windows.net\template.json'
```
The funny thing is if you call `New-AzureRmResourceGroupDeployment -TemplateFile https://mysa.blob.core.windows.net/template.json` it actually works (you don't need to use `New-AzureRmResourceGroupDeployment -TemplateUrl ...`).

Could you add support for URL template files?  Maybe you add a check (if the file name starts with 'http') that causes URLs to get passed straight through without being manipulated?

Thanks!

**Comment by RoopeshNair** [comment]
@gregjhogan we have on our backlog to support linked templates and option to specify template URI location. However the task is undergoing some changes to make it compatible with xPlat agents etc, so it will be a while before we can get to it. We are tracking this on our backlog. 

Thank you

**Comment by gregjhogan** [comment]
@RoopeshNair are you open to a pull request for the current codebase to add support in the short-term?
