### ISSUE TITLE
ServiceFabricDeploy task does not wait for deployment completion when using override publish profile

### ISSUE THREAD

**Issue by mkosieradzki** [Microsoft/vsts-tasks#2654]
When using Override All Publish Profile Upgrade Settings  (even in Monitored mode) - Publish-UpgradedServiceFabricApplication.ps1 exits on
  if (!$UpgradeParameters["Monitored"] -and !$UpgradeParameters["UnmonitoredAuto"])
        {
            return
        }

Probably upgrade parameters are passed in a different convention.

**Comment by ericsciple** [comment]
Fix will roll out with m107 which starts to roll in a couple weeks.
