### ISSUE TITLE
Upload custom task with extension breaks existing custom task and existing releases/builds from direct publish

### ISSUE THREAD

**Issue by sawpresto** [Microsoft/vsts-tasks#2675]
I created a custom build task that I uploaded to my local TFS 2015.3 machine with the direct publish model. After the task was in TFS, I created an extension that included the same custom build task with a higher version number (same ID, higher version). I installed the extension and the web UI didn't throw any errors.

However, when trying to open up the existing release definition that uses the custom task, it looks like the Javascript breaks and I'm unable to fix it. That happens both for existing release and build definitions that have the task in it.
![image](https://cloud.githubusercontent.com/assets/11528965/18846956/064a058e-83dd-11e6-8ca8-3a47f3fa7905.png)

I believe that I was able to test it and the task hadn't updated, but as of writing and uploading the extension, I can't get past the Javascript UI errors to check (can't create a release because the UI is broken). 

When looking at the logs in Event Viewer, after I delete the extension to see if the uninstall fixes the issue with the UI and task, I receive `TF1590003: No app with {guid of extension} is installed in this account `which makes sense because the TFS instance is looking for tasks that no longer exist. An error comes right after that error message that says "`Exception occurred while installing the extension {extension name} with version 1.0.1. Exception is System.ApplicationException: Could not retrieve installed extension.
` It seems to mean that it doesn't actually install the extension because I think that was when I would not notice a change in the task. 
Any ideas to overwrite a custom task that was uploaded with the direct publish model using the extension model without deleting the task or creating a separate task?

**Comment by bryanmacfarlane** [comment]
send a mail to me.  my alias is bryanmac and I'm at microsoft dot com.

This repo is for issues with tasks in this repo.  I'll line you up with someone to help

**Comment by sawpresto** [comment]
Oops, sorry about that!
