### ISSUE TITLE
Build Tasks failing with exception: Unhandled: tl.createToolRunner is not a function

### ISSUE THREAD

**Issue by hubertusgr** [Microsoft/vsts-tasks#2685]
Hi!
I am new to node and used your gulp script to build the tasks. I have downloaded the release version m106 and I am using the latest agent that can be downloaded (vsts-agent-osx.10.11-x64-2.107.0.tar)

I uploaded the tasks from the _build/tasks folder to our on premise tfs2015.3 server and I now get the following message when running the build:
Unhandled: tl.createToolRunner is not a function

Somehow it seems like I am doing something wrong but I have no clue where to start.

Can you assist me with my issue?
As another question I would like to know with branch was released with tfs 2015.3 so that I could maybe delete the tasks from our tfs server and upload the old ones again.

Best Regards and thanks in advance.
Hubertus

PS.: a part of the log form the build console follows here:

loading INPUT_SOLUTION
loading INPUT_CONFIGURATION
loading INPUT_CWD
loading INPUT_PACKAGEAPP
loading INPUT_FORSIMULATOR
loading INPUT_SIGNMETHOD
loading INPUT_UNLOCKDEFAULTKEYCHAIN
loading INPUT_P12
loading INPUT_PROVPROFILE
loading INPUT_REMOVEPROFILE
loading ENDPOINT_AUTH_$/
loading ENDPOINT_AUTH_SCHEME_$/
loading ENDPOINT_AUTH_PARAMETER_$/_ACCESSTOKEN
loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
loading SECRET_TEAMAPIKEY
loading SECRET_XAMARINPASSWORD
loaded 18
solution=/Users/buildagent/myagent/_work/1/s/Connectors/TheMobile/Xamarin/TheMobileApp/TheMobileApp.sln
check path : /Users/buildagent/myagent/_work/1/s/Connectors/TheMobile/Xamarin/TheMobileApp/TheMobileApp.sln
configuration=Testing
args=null
packageApp=true
forSimulator=false
device: iPhone
mdtoolLocation=null
cwd=/Users/buildagent/myagent/_work/1/s
check path : /Library/Frameworks/Mono.framework/Versions/Current/Commands/xbuild
xbuild=/Library/Frameworks/Mono.framework/Versions/Current/Commands/xbuild
check path : /Library/Frameworks/Mono.framework/Versions/Current/Commands/nuget
nuget=/Library/Frameworks/Mono.framework/Versions/Current/Commands/nuget
task result: Failed
Processing: ##vso[task.issue type=error;]Unhandled: tl.createToolRunner is not a function
Unhandled: tl.createToolRunner is not a function

**Comment by chrisrpatterson** [comment]
You have uplaoded an incomplete task the best I can tell.  My guess is you have an incomplete task lib and something is wrong with the build you ran for the tasks.  In addition you can only upload tasks from the version that matches your TFS from the appropriate releases branch, not directly from master.

**Comment by ericsciple** [comment]
the tasks from releases/m95 shipped with TFS2015.3

**Comment by hubertusgr** [comment]
Hi!
I appreciate your help and will try to get back to the shipped tasks that came with TFS2015.3. 
I used gulp to build all the tasks at once with the gulpfile.js that is on the root of the vsts-tasks-releases-m106 directory.
There I had no errors when building and it looks right. All tasks are shipped with node_modules inside and there the vsts-task-lib is inside. It was created automatically I guess by node. 
There is nothing manual I did...

Would there be anything else I need to do additionally to running the gulp script?
I really appreciate your help here.

Best regards Hubertus

**Comment by hubertusgr** [comment]
I just checked the code a bit and it seems that the version of the vsts-task-lib is the wrong one. The one that is packed in my node_modules is the version 0.9.20. I truly can not find a function createToolRunner in the task.js there. in the version 0.7 this function is there so it seems that I am getting the wrong vsts-task-lib version. Am I correct here?

Best Regards

**Comment by hubertusgr** [comment]
Hi!

I just cleaned everything and did a fresh build using gulp, and guess what: Its fine now!

I don't know how the wrong version of the vsts-tasks-lib got into my tasks at the first time but now its working just fine!

Thanks for your help here.
