### ISSUE TITLE
README tutorial link produces 404

### ISSUE THREAD

**Issue by njappboy** [Microsoft/vsts-tasks#2686]
Currently the [README.md](https://github.com/Microsoft/vsts-tasks/blob/master/README.md) tutorial to [https://www.visualstudio.com/en-us/integrate/extensions/develop/add-build-task](https://www.visualstudio.com/en-us/integrate/extensions/develop/add-build-task) returns a 404.

**Comment by bryanmacfarlane** [comment]
we're investigating.

**Comment by bryanmacfarlane** [comment]
fixed
