### ISSUE TITLE
Archive files tasks suddenly failing

### ISSUE THREAD

**Issue by janecos** [Microsoft/vsts-tasks#2689]
My builds suddenly stopped working today. The Archive Files tasks is failing to find any of the files to put into the archive. I saw issue #2646 which is the same issue and is now closed. The build task on my machine was updated to 1.0.5 this morning which caused the builds to fail. It looks like the issue has been fixed in 1.0.6 - how do I get that version (or go back to 1.0.4)?
Sorry for the newbie question - I didn't find any instructions on how to specify a version number for a task.

**Comment by treierts** [comment]
We are having the same issue. Builds working yesterday are now failing.

We are trying to zip files published with dotnet publish, but the Archive Files Task CWD's into the wrong folder and will not find all the required files:

For example:

dotnet publish outputs the files to `src/$(SolutionName)/bin/$(BuildConfiguration)/net451/win7-x64/publish`
The Archive Files task CWD's into `src/$(SolutionName)/bin/$(BuildConfiguration)/net451/win7-x64` and will not find the files required.

This was working yesterday.

**Comment by muttech** [comment]
I'm seeing the same issue with a Hosted agent and it started between 10:48 AM and 4:02 PM CDT yesterday (9/27).

If I check "Prefix root folder name to archive paths" the ArchiveFiles task works, but then my Azure Web Site deploy is deployed under the "publish" folder.

**Comment by jaredcnance** [comment]
I am also having this issue. It appears that it is running 7z.exe from the parent directory instead of the rootFolder.

**Comment by bryanmacfarlane** [comment]
I believe Yang has a fix to patch.  Getting confirmation on patch would be great.  I believe they are pushing today.

**Comment by yacaovsnc** [comment]
The patch is being pushed out now.  Could you please try your build again?

**Comment by jaredcnance** [comment]
My builds are fixed. Thanks

**Comment by treierts** [comment]
I can confirm that the Archive Task now works as expected. Thanks!

**Comment by janecos** [comment]
I confirmed my build is also now working.
Are you making any process changes to stop broken builds being pushed into VSTS? This issue was found and the code change already made well before 1.0.5 was pushed into my environment and broke my build.
My company is considering moving more projects into VSTS and reliability of builds is important. I understand bugs will exist, I just would hope that known bugs that break basic functionality don't get into production.

**Comment by yacaovsnc** [comment]
@janecos First of all sorry about this breakage, I totally agree with you that bugs which break basic functionalities should not get into production.  We are actively working on improving both our unit tests coverage as well as E2E testing infrastructures and we hope to catch those show stoppers before they hit production.  We also dogfood our tasks in production and have the ability to apply patches quickly.  We understand our current limitation and are actively working on updating the release process to reduce those occurrences.  Again sorry for the problem this has caused.

**Comment by janecos** [comment]
In this case the issue was found (and fixed) before it was pushed to production (see #2646). I guess it wasn't identified as a show stopper?

**Comment by DavidStaheli** [comment]
Hi @janecos.  Unfortunately, in this case, it was an oversight.  We fixed the bug, but missed cherry-picking the commit into the branch from master that had already been created for deployment to production.  The fix didn't make it into the deployment branch.
