### ISSUE TITLE
Chef Knife task output empty lines to the logs

### ISSUE THREAD

**Issue by goreish** [Microsoft/vsts-tasks#2691]
Output from PowerShell scripts run by the Chef Knife task get multiple empty lines with every line written to the logs in VSTS Releases. This happens on Agents using VSO v2.x and not on Agents using VSO v1.x
The Agent queue owners suspect that the task is handling character returns differently. They think that the Chef Knife Task is using VSO v1.x and suggest updating it to use VSO v2.x. 
See sample from the logs with duplicate lines
![chefknifetasklogs](https://cloud.githubusercontent.com/assets/22485422/18895885/e00c52fa-84d1-11e6-8958-a2d52428e35e.png)

Here is a sample from a normal PowerShell Task in the same release:
![powershelltasklog](https://cloud.githubusercontent.com/assets/22485422/18895970/95f2b5e6-84d2-11e6-95a7-d46f123e9ae3.png)

**Comment by KrishnaAdityaB** [comment]
Thanks @goreish 
As this is not a functionality bug or automation blocker - we will take it up with the next functionality update to the task
