### ISSUE TITLE
Run Functional Task failed to run Tests

### ISSUE THREAD

**Issue by AbrahamDhanyaraj** [Microsoft/vsts-tasks#2696]
Hi Team,

I have Machine Group with 3 VM's , In which CUIT testcases gets distribute in all the VM's. Out of which 1 VM failed to run testcases and sets testcases  to Status - None 

Verified vstest.console works fine by RDPing , and it works great. PFB DTA log files . 

V, 7864, 1, 2016/09/28, 08:26:13.952, HostName\DTAExecutionHost, FileMonitor: TryReadToken Waiting for file creation.
V, 7864, 3, 2016/09/28, 08:26:14.311, HostName\DTAExecutionHost, FileMonitor: FileCreated Required file found.
V, 7864, 1, 2016/09/28, 08:26:14.327, HostName\DTAExecutionHost, FileMonitor: ReadFile completed.
V, 7864, 1, 2016/09/28, 08:26:14.608, HostName\DTAExecutionHost, FileMonitor: TryDeleteFile succeeded.
I, 7864, 1, 2016/09/28, 08:26:15.014, HostName\DTAExecutionHost, ExecutionTaskStateModel.GetExecutionAdapter : Initializing VstestAdapter.
I, 7864, 1, 2016/09/28, 08:26:15.030, HostName\DTAExecutionHost, ExecutionTaskStateModel.Start : Starting to monitor tasks
V, 7864, 1, 2016/09/28, 08:26:15.030, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [https://VSAccount.visualstudio.com/_apis/test/Agents/134/Commands/0] (GET)0[test]
I, 7864, 1, 2016/09/28, 08:26:15.202, 627185644524, DTAExecutionHost.exe, ********************************************************************
I, 7864, 1, 2016/09/28, 08:26:15.202, 627185645855, DTAExecutionHost.exe, Main.InitializeAndStartExecutionHost. ExecutionHost has been started
Web method response: [https://VSAccount.visualstudio.com/_apis/test/Agents/134/Commands/0] (GET)0[test] 263 ms
V, 7864, 9, 2016/09/28, 08:26:15.717, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 7864, 9, 2016/09/28, 08:26:15.736, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 7864, 9, 2016/09/28, 08:26:15.736, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 3000 milliseconds.
V, 5808, 1, 2016/09/28, 08:28:30.626, HostName\DTAExecutionHost, FileMonitor: ReadFile completed.
V, 5808, 1, 2016/09/28, 08:28:30.924, HostName\DTAExecutionHost, FileMonitor: TryDeleteFile succeeded.
I, 5808, 1, 2016/09/28, 08:28:32.079, HostName\DTAExecutionHost, ExecutionTaskStateModel.GetExecutionAdapter : Initializing VstestAdapter.
I, 5808, 1, 2016/09/28, 08:28:32.079, HostName\DTAExecutionHost, ExecutionTaskStateModel.Start : Starting to monitor tasks
V, 5808, 1, 2016/09/28, 08:28:32.097, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [https://VSAccount.visualstudio.com/_apis/test/Agents/134/Commands/0] (GET)0[test]
I, 5808, 1, 2016/09/28, 08:28:32.423, 712913484, DTAExecutionHost.exe, ********************************************************************
I, 5808, 1, 2016/09/28, 08:28:32.423, 712914917, DTAExecutionHost.exe, Main.InitializeAndStartExecutionHost. ExecutionHost has been started
Web method response: [https://VSAccount.visualstudio.com/_apis/test/Agents/134/Commands/0] (GET)0[test] 587 ms
V, 5808, 8, 2016/09/28, 08:28:33.079, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 5808, 8, 2016/09/28, 08:28:33.094, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 5808, 8, 2016/09/28, 08:28:33.094, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 3000 milliseconds.
V, 5808, 4, 2016/09/28, 08:28:36.219, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [https://VSAccount.visualstudio.com/_apis/test/Agents/134/Commands/0] (GET)0[test]
Web method response: [https://VSAccount.visualstudio.com/_apis/test/Agents/134/Commands/0] (GET)0[test] 36 ms
V, 5808, 7, 2016/09/28, 08:28:36.251, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 5808, 7, 2016/09/28, 08:28:36.266, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 5808, 7, 2016/09/28, 08:28:36.266, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 9000 milliseconds.
V, 5808, 4, 2016/09/28, 08:28:45.276, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [https://VSAccount.visualstudio.com/_apis/test/Agents/134/Commands/0] (GET)0[test]
Web method response: [https://VSAccount.visualstudio.com/_apis/test/Agents/134/Commands/0] (GET)0[test] 35 ms
V, 5808, 9, 2016/09/28, 08:28:45.307, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 5808, 9, 2016/09/28, 08:28:45.307, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 5808, 9, 2016/09/28, 08:28:45.307, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 27000 milliseconds.
V, 5808, 10, 2016/09/28, 08:29:12.316, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [https://VSAccount.visualstudio.com/_apis/test/Agents/134/Commands/0] (GET)0[test]
Web method response: [https://VSAccount.visualstudio.com/_apis/test/Agents/134/Commands/0] (GET)0[test] 48 ms
V, 5808, 9, 2016/09/28, 08:29:12.365, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 5808, 9, 2016/09/28, 08:29:12.365, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 5808, 9, 2016/09/28, 08:29:12.365, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 50000 milliseconds.
V, 5808, 11, 2016/09/28, 08:30:02.371, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [https://VSAccount.visualstudio.com/_apis/test/Agents/134/Commands/0] (GET)0[test]
Web method response: [https://VSAccount.visualstudio.com/_apis/test/Agents/134/Commands/0] (GET)0[test] 53 ms
V, 5808, 12, 2016/09/28, 08:30:02.418, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 5808, 12, 2016/09/28, 08:30:02.418, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 5808, 12, 2016/09/28, 08:30:02.418, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 50000 milliseconds.
V, 5808, 14, 2016/09/28, 08:30:52.439, HostName\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [https://VSAccount.visualstudio.com/_apis/test/Agents/134/Commands/0] (GET)0[test]

Could you please assist ?

Thanks,

Abraham

**Comment by allendm-msft** [comment]
@AbrahamDhanyaraj this is odd. Is "vsaccount" your account name?
If you can provide your account details we can debug further from our end. You can send it to us at devops _underscore_ tools _at_ microsoft _dot_ com

**Comment by AbrahamDhanyaraj** [comment]
@allendm-msft.  No. Its not, its fnsmis

**Comment by AbrahamDhanyaraj** [comment]
@allendm-msft  Its FNSMIS

**Comment by allendm-msft** [comment]
This didnt help as much as I hoped :) 
Would love your help on a repro. Here is what I need you to do
a) delete contents of c:\dtalogs on your test machines
b) rerun your scenario
c) share the logs with us
d) also share details of the inputs to the "run functional tests" task
