### ISSUE TITLE
"Test Filter Criteria" is Truncated while executing Funtional Tests through VSO Build Definition Task.

### ISSUE THREAD

**Issue by AmaranAthigaman** [Microsoft/vsts-tasks#2717]
Hi All,

I have a build definition configured to execute my UI automation Tests. The build definition has a "Test Agent Deployment" build task followed by a "Run Functional Test" build task. 
There are around 400 tests which get executed. 
I am currently re-running the failed tests from the above test run by following the below steps.
1. Once the above two tasks are complete I have a task which will get the names of the failed test cases and construct a test filter criteria through powershell. Example : Name = "XYZ" | Name = "ABC"
2. This filter criteria is stored in a variable and is configured as my "Test Filter Criteria" in the third build task to "Run Functional Tests".

**The Test filter criteria length is around 15788 characters with around 150 test case names given in the filter condition.

When the tests starts executing I see that there are only 35 tests that are getting executed. The test filter criteria is actually getting truncated and the first 35 tests are only considered for the test run.**

Has any one faced this issue. Is this a bug or is there a workaround for this.

Troubleshooting done.
1. Tried to create a new build definition with only one build Task "Run Functional Tests" and passed the same filter criteria text. I see it getting again truncated to only 35 test methods in the test run instead of around 150.
2. Ensured that the test filter criteria is in correct format. Something similar to this(Name = "XYZ" | Name = "ABC") with 150 test names.

Please provide your thoughts/solution on this issue.

Thanks.

**Comment by hqer2k9** [comment]
Hey,

hopefully i understood you right.
An approach could be to go the other way around, to net let test A. B and C run. But rather deactivate the other tests that should not be run.

for example with this String in "Test Filter Criteria": **TestCategory!=MyTests1&TestCategory!=MyTests2&TestCategory!=OtherTests**

hope that helps

BR

**Comment by AmaranAthigaman** [comment]
Thanks for your response. 

I have around 400 test cases out of which 150 are failed test cases. If i go the other way around(Consider passed tests case names in the filter condition) also i will have a very long test filter condition and it will again get truncated.
So, it may not workout for me.

**Comment by allendm-msft** [comment]
@AmaranAthigaman we dont have a good workaround for this use case today. Adding in our PM to track the feature ask

**Comment by AmaranAthigaman** [comment]
@allendm-msft . This looks like a bug to me where the TestFilterCriteria is actually getting truncated if there are more than ~2000 characters in the textbox. This seems to be failing in a normal build definition with just a Test agent and test execution task configured.

Can you please confirm?

- Thanks, Amaran

**Comment by AmaranAthigaman** [comment]
Hi All,

I am facing the same issue still and its blocking our test execution builds. It would be great if anyone could share any suggestions.

Thanks.

**Comment by allendm-msft** [comment]
@AmaranAthigaman you can work around this limitation by splitting your run up by using multiple deploy test agent + run functional tests tasks.

**Comment by AmaranAthigaman** [comment]
@allendm-msft  is there a way to repeat the Functional test task in a loop by changing the filter criteria alone (or) should i add one functional test task for each of my iteration of test execution with different filter criteria?

**Comment by allendm-msft** [comment]
There is no repeat in loop option. You would need to add a combo of deploy + run tasks per change in filter

**Comment by AmaranAthigaman** [comment]
Thanks for your suggestion @allendm-msft . 
I had this in my mind already but it wasn't looking to be a clean solution as the number of tests in my filter condition will be dynamic. So, i will not have predefined number for the combo of deploy and run tasks to be configured. I will have to have make few assumptions and have multiple combos configured.
At this point i think i will have to go with it. 

Is there any ETA or bug for this limitation, so that i can track this to be fixed in future releases?

- Thanks.

**Comment by allendm-msft** [comment]
This is on our backlog but I dont have a good timeframe for it.

**Comment by PBoraMSFT** [comment]
@AmaranAthigaman - sounds like your scenario is to be able to re-run failed tests. This is already on the backlog. https://github.com/Microsoft/vsts-tasks/issues/3170 
If this functionality was added, do you have other scenarios where providing a long filter criteria using test names is necessary?

**Comment by nigurr** [comment]
Closing this issue as there' no response. feel free to reopen it :)

**Comment by ChethanRavulaGit** [comment]
Is this issues fixed?
I am planning to implement similar setup

**Comment by prawalagarwal** [comment]
@ChethanRavulaGit If you are using the VsTest task (version 2), you get the rerun functionality inbuilt and there is no need to create a setup as described above. We highly recommend to move to VsTest task as RunFunctionalTest task has been deprecated and VsTest task supports distributed testing in a much more robust manner.

**Comment by dejansimeunovic** [comment]
Hi @prawalagarwal ,

How can we use the inbuilt ReRun functionality with the VsTest task? Is there some documentation, or some valuable examples? I tried to find the guide/doc for it online, but I wasn't that lucky...

Does it have to be preceded by "Visual Studio Test Agent Deployment" task (like "Run Functional Tests" task did), or it needs something else?

**Comment by dejansimeunovic** [comment]
Hi @AmaranAthigaman ,

Is there any chance that you could share your PowerShell script, and explain how you made it, or at least give us the guidelines how you did it? I need to do exactly the same thing in our build/test environment...
Thanks in advance (in any case)!

**Comment by prawalagarwal** [comment]
@dejansimeunovic Here is a [link](https://blogs.msdn.microsoft.com/visualstudioalmrangers/2018/02/08/vsts-gems-identify-flaky-tests/) explaining rerun in VsTest task. VsTest task is a stand alone task and does not need to be preceded by Deploy Agent task (DTA and RFT tasks are now deprecated).

**Comment by dejansimeunovic** [comment]
@prawalagarwal first of all, sorry for the late answer. And, thanks a lot for the link.

However, this is a solution for the On-Premises version. Since we are using TFS it doesn't really apply to us (at least not yet, because it says "TFS Availability - Future"). Do you know (approx) when it comes to TFS?

**Comment by prawalagarwal** [comment]
@dejansimeunovic Rerun was introduced from TFS 2018 Update 2 onwards.

**Comment by dejansimeunovic** [comment]
Oh, that's great!
Thanks for the quick answer!
