### ISSUE TITLE
Occasional timeout during Run Functional Test step

### ISSUE THREAD

**Issue by geoffstew4** [Microsoft/vsts-tasks#2721]
I have hit the following error several times when running builds.  If I queue another build it will typically complete with no issue.  What specifically is timing out at 1:40 and is this timeout a setting that can be changed to a longer duration?

Thanks
Geoff
[10_Run Tests AutomatedRegressionTests.dll on AnalyticsMachines.txt](https://github.com/Microsoft/vsts-tasks/files/501884/10_Run.Tests.AutomatedRegressionTests.dll.on.AnalyticsMachines.txt)

**Comment by allendm-msft** [comment]
@geoffstew4 Can you share the logs from c:\dtalogs from your target machine?

**Comment by geoffstew4** [comment]
I will need to get the logs the next time I run into the error.  Let me know what account details would be helpful.  Thanks

**Comment by allendm-msft** [comment]
You can send us the logs on devops _underscore_ tools _at_ microsoft _dot_ com
if you are on visualstudio.com it would help to get your account name on the same email.

**Comment by geoffstew4** [comment]
I sent the logs to the email you indicated above but it was rejected with this message.  I am attaching them here as well.

The groups only accept messages from people in their organization or on their allowed senders list, and your email address isn't on the lists.
[10_Run Tests AutomatedRegressionTests.dll on AnalyticsMachines.txt](https://github.com/Microsoft/vsts-tasks/files/509956/10_Run.Tests.AutomatedRegressionTests.dll.on.AnalyticsMachines.txt)
[DTAExecutionHost.exe_auto02.zip](https://github.com/Microsoft/vsts-tasks/files/509958/DTAExecutionHost.exe_auto02.zip)

**Comment by geoffstew4** [comment]
Attached is the log from the build machine, appears to look the same as the console output.  My account is gstewart at itron dot com.
[Worker_20161005-024157-utc.log.txt](https://github.com/Microsoft/vsts-tasks/files/511401/Worker_20161005-024157-utc.log.txt)

**Comment by allendm-msft** [comment]
Based on a conversation with the relevant owners it looks like this is an error that can be ignored. 
It means there is one batch of console line live feedback didn’t made to server due to http timeout.
Customer may experience few console line missing, but this won’t affect their build quality and build logs.
There is only one batch failed in the attached log, so it might just because some network issue.

Have assigned this to @TingluoHuang if there are any followups

**Comment by geoffstew4** [comment]
This causes the tests to abort and the step to fail and no test results to publish so I disagree that this can be ignored

[cid:image001.png@01D21F54.A11900D0]

**Comment by geoffstew4** [comment]
This causes the tests to abort, the step to fail and no test results to publish so I disagree that this can be ignored

**Comment by geoffstew4** [comment]
On my past three builds it has a similar failure, all of the tests complete but the final results don't post correctly due to the timeout.  Is this setting something I can configure?  I've tried rebooting the build box and the test machines but get the same result

DistributedTests: Test run is aborted. Logging details of the run logs.
DistributedTests: New test run created.
Test Run queued for Project Collection Build Service (ItronCloudServices).
DistributedTests: Test discovery started.
DistributedTests: Test Run Discovery Completed . Test run id : 13542
DistributedTests: 32 test cases discovered.
DistributedTests: Test execution started. Test run id : 13542
DistributedTests: UnExpected error occured during test execution. Try again.
DistributedTests: Error : One or more errors occurred.--->The HTTP request timed out after 00:01:40.
DistributedTests: Test run aborted. Test run id: 13542

[Worker_20161026-201214-utc.zip](https://github.com/Microsoft/vsts-tasks/files/554395/Worker_20161026-201214-utc.zip)

[DTAExecutionHost.exe.zip](https://github.com/Microsoft/vsts-tasks/files/554401/DTAExecutionHost.exe.zip)

**Comment by acesiddhu** [comment]
@geoffstew4 Looks like publishing of test result attachment is timing out. Do you have any test case level attachments? Whats the size of those?

**Comment by geoffstew4** [comment]
If you are referring to the TRX files they are relatively small 16 – 18 KB, 4 of my 5 distributed machines were able to publish the results.

[cid:image001.png@01D2301F.72042780]

**Comment by acesiddhu** [comment]
No I was referring to some other attachments (like intellitrace, system info etc). do you have a testsetting/runsetting? Is any data collector on in that?

**Comment by geoffstew4** [comment]
I don’t specify a testsetting/runsetting file so it is using whatever is default.  I am unclear on what the second question is referring to.

**Comment by acesiddhu** [comment]
From logs I see UITestActionLog.html. Does this look familiar?

**Comment by geoffstew4** [comment]
I can get those for each of the individual aborted tests, is that what you are looking for?

[cid:image001.png@01D2303B.7FF322D0]

**Comment by acesiddhu** [comment]
Yes that will be great if possible. If not let me know the size of these files. By the way how does these file get generated?

**Comment by geoffstew4** [comment]
They are generated by our CodedUI tests, I have attached one as an example.  This is the largest one I have seen.

**Comment by sailajacharan** [comment]
@acesiddhu i am having same issue. I have CodedUI tests running on 1 test agent. All tests were running good so far, but from last 3 days, theres some tests failing on build. Looks like these tests are not even being run. Build/Tests, the status of test is Other and theres no test results.

Below is DTA execution host log file, TFS version
![tfsversion](https://cloud.githubusercontent.com/assets/20461864/20115675/c8aac93a-a5be-11e6-823d-1e6249711c71.png)

**Comment by acesiddhu** [comment]
@sailajacharan this seems to be other issue. Can we track this as a separate issue on GitHub? Also if you can give more details on error etc that will help

**Comment by vimegh** [comment]
@geoffstew4 I was just checking old issues for cleanup. Just wanted to confirm, is this problem still reproducible at your end? Please let us know.

**Comment by geoffstew4** [comment]
I have not seen this in a while so we can probably close this thread.
