### ISSUE TITLE
Profdata format support in coverage task

### ISSUE THREAD

**Issue by LiohAu** [Microsoft/vsts-tasks#2724]
Hello,

I am trying to generate code coverage from my iOS tests and I would like to use the publish code coverage task but at the moment it looks like the only format supported are jacoco and cobertura.

Would it be possible to add profdata format (I don't think it will be used for iOS apps only since it's the llvm format I believe).

I know that slather can generate cobertura from profdata files, but I don't think that will generate a summary (which is required on the task) AND additional report files (I will try to test that soon).

**Comment by allendm-msft** [comment]
@LiohAu have you taken a look at the llvm-cov functionality? There are some posts on [how to conver the default profdata format to cobertura](http://mgrebenets.github.io/mobile%20ci/2015/09/21/code-coverage-for-ios-xcode-7) which then can be used to publish to tfs and get all the goodness.

This could be an cmdline invocation step after your test execution, after which you can upload your coverage data.

If you have an interest in contributing this feature into the project we would love to work with you on it. Reference [https://github.com/Microsoft/vsts-agent/tree/master/src/Agent.Worker/CodeCoverage](https://github.com/Microsoft/vsts-agent/tree/master/src/Agent.Worker/CodeCoverage)

**Comment by LiohAu** [comment]
@allendm-msft Yes I have looked at this post, and it uses slather. But last time I tried, slather generated only one xml file and it looks like the provided coverage task needs 2 things : a summary AND reports XML files.

I will try to look at the agent when I have time (but first I need to better understand how the profdata format works).

**Comment by allendm-msft** [comment]
We will keep this post updated once we provide first class support for this feature.

**Comment by LiohAu** [comment]
This is the best I can do with the time I have and my limited typescript skills.

[iOSCoverage.zip](https://github.com/Microsoft/vsts-tasks/files/516581/iOSCoverage.zip)

Anyway it worked for me.

**Comment by LiohAu** [comment]
@allendm-msft does my contribution changes anything to the backlog?
