### ISSUE TITLE
Deploying WebApp with WebJob to virtual application not deploying webjobb correctly

### ISSUE THREAD

**Issue by gwendo** [Microsoft/vsts-tasks#2729]
I’m facing an issue when deploying my application to a virtual application that has webjobs associated with it using AzureRmWebAppDeployment. The webjob under the app_data folder is unpacked and deployed under the virtual application, but it should actually be moved one level up to the root, in order for it to be picked up and deployed as well.

Is this a known issue or could this be fixed somehow?

**Comment by JoeBrockhaus** [comment]
I'm also seeing issues with the WebApp WebDeploy. 

My issue is not the same as yours, but it seems some rolling updates are causing issues.

**Comment by JoeBrockhaus** [comment]
Did you use Visual Studio to 'Add Existing Project as WebJob"?

This will install `Microsoft.Web.WebJobs.Publish` into the WebApp & Console App. 
It will also create `WebApp/Properties/webjobs-list.json` & `/Properties/webjobs.props` 
(.props in both Web & Console)

Not sure if that would solve your problem. 

Perhaps the issue you are seeing is related to the new 2.0.1 version, which has been causing other issues like #2719

**Comment by abatishchev** [comment]
Can you please elaborate on what do you mean saying "to a virtual application"?
Deploying WebJobs to default location using the latest version of the task (2.0.2 I believe) works fine for us.

**Comment by gwendo** [comment]
![azurerm-virtualapp](https://cloud.githubusercontent.com/assets/903636/19028749/d8da26ac-893f-11e6-9ee0-e5d93e7fbc86.PNG)

I used visual studio to add the webjob and it created all the mentioned files.
@abatishchev see the screenshot to what I mean by installing to a virtual application.

**Comment by abatishchev** [comment]
I see, I have blank line in that field.

**Comment by kmkumaran** [comment]
Based on the responses in the thread, I am marking it closed. Feel free to re-open the issue if you need further assistance.

**Comment by gwendo** [comment]
How can you close it based upon the comments. The issue is still not resolved. The deploy job is not deploying the WebJob correctly

**Comment by eloekset** [comment]
I tried this right now and can confirm that it doesn't work to deploy WebJobs to a virtual application, while running the same release script and deploy to the root of another Azure WebSite works fine.
![2016-12-21_1350](https://cloud.githubusercontent.com/assets/791721/21389945/93ac90c8-c784-11e6-80e9-202e53f6425f.png)

**Comment by JoeBrockhaus** [comment]
@gwendo, I believe @kmkumaran is referring to https://github.com/Microsoft/vsts-tasks/pull/2744#discussion_r81733928 .. 

That said, fwiw, I'm not sure WebJobs outside the scope of deploying to the root of a site makes sense. 
So deploying to a VirtualDirectory might simply be impossible. But if so, this should be called out explicitly by documentation.
