### ISSUE TITLE
Cloud Base Load Test fails with The test mix for scenario "Mix" contains the following test that cannot be found

### ISSUE THREAD

**Issue by dawilliams** [Microsoft/vsts-tasks#2751]
Hello,

This could be a config error but we can't get a test that works locally to run in VSTS.  It seems to run one test then we keep getting the following error:

> Microsoft.PowerShell.Commands.WriteErrorException: The test mix for scenario "Mix" contains the following test that cannot be found: "mesa.core.api.perf.tests.dll". Update the test mix of the scenario to remove test that do not exist and add any renamed test. Then rerun your load test. Note: Do not edit the load test xml file directly. This is not supported when you run your load test with Visual Studio Team 

The odd thing is that it is referencing a dll which isn't a test.  Here is the configuration of the task
![image](https://cloud.githubusercontent.com/assets/581113/19046960/73caf0a4-8965-11e6-8155-ef6dc7df65fa.png)

Here is the contents of the directories:

Directory: C:\a\1\s\Mesa.Core.API.Perf.Tests\bin\Release
Mode                LastWriteTime     Length Name                 
                                                                                                                 
d----         10/3/2016   4:18 PM            Settings                                                                  
d----         10/3/2016   4:18 PM            Tests                                                                     
-a---         10/3/2016   4:18 PM      10752 Mesa.Core.API.Perf.Tests.dll                                              
-a---         10/3/2016   4:18 PM        430 Mesa.Core.API.Perf.Tests.dll.config                                       
-a---         10/3/2016   4:18 PM      22016 Mesa.Core.API.Perf.Tests.pdb                                              
-a---         10/3/2016   4:18 PM     194336 Microsoft.IdentityModel.Clients.ActiveDirectory.dll                       
-a---         10/3/2016   4:18 PM      51520 Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.dll          
-a---         10/3/2016   4:18 PM     131969 Microsoft.IdentityModel.Clients.ActiveDirectory.xml                       
-a---         6/28/2015   9:58 PM     664408 Microsoft.VisualStudio.QualityTools.WebTestFramework.dll                  
-a---         7/22/2013  12:52 AM     369845 Microsoft.VisualStudio.QualityTools.WebTestFramework.xml                  
-a---         10/3/2016   4:18 PM     522752 Newtonsoft.Json.dll                                                       
-a---         10/3/2016   4:18 PM     516075 Newtonsoft.Json.xml                                                       
-a---         10/3/2016   4:18 PM     157696 Polly.dll                                                                 
-a---         10/3/2016   4:18 PM     480768 Polly.pdb                                                                 
-a---         10/3/2016   4:18 PM     310320 Polly.xml                                                                 
-a---         10/3/2016   4:18 PM      16896 SourceMed.Mesa.Authentication.dll                                         
-a---         10/3/2016   4:18 PM      16914 SourceMed.Mesa.Authentication.xml                                         
-a---         10/3/2016   4:18 PM      36352 SourceMed.Mesa.Communication.dll                                          
-a---         10/3/2016   4:18 PM      39753 SourceMed.Mesa.Communication.xml                                          
-a---         10/3/2016   4:18 PM      12800 SourceMed.Mesa.Core.dll                                                   
-a---         10/3/2016   4:18 PM      22525 SourceMed.Mesa.Core.xml                                                   
-a---         10/3/2016   4:18 PM     185544 System.Net.Http.Formatting.dll                                            
-a---         10/3/2016   4:18 PM     192626 System.Net.Http.Formatting.xml

Directory: C:\a\1\s\Mesa.Core.API.Perf.Tests\bin\Release\Tests
Mode                LastWriteTime     Length Name                                                                      
                                                                  
-a---         10/3/2016   4:32 PM      30354 CoreAPI.loadtest                                                          
-a---         10/3/2016   4:32 PM        851 When_Getting_User_Roles.cs                                                
-a---         10/3/2016   4:32 PM        921 When_Querying_For_User_Privileges.cs                                      
-a---         10/3/2016   4:32 PM        974 When_Querying_Tenant_Controller.cs

**Comment by dawilliams** [comment]
Ok, we got past this issue.  Some files the test needed were missing.

**Comment by boulajp** [comment]
I'm facing a similar issue. My loadtest requires a dll file created earlier in the build chain. How did you manage give the loadtest access to the required dll?

**Comment by BWBuchanan7** [comment]
@dawilliams could you clarify how you solved this exactly? I seem to be in the same situation but am not able to see why this .dll can't be found.
