### ISSUE TITLE
Cloud Base Load Test fails with authentication token has expired error

### ISSUE THREAD

**Issue by dawilliams** [Microsoft/vsts-tasks#2752]
Our Cloud Base Load Test task fails with

> Microsoft.PowerShell.Commands.WriteErrorException: Unable to start data collection from Application Insights because the authentication token has expired. No application counters will be collected for this load test. Sign out and sign in to https://foo.visualstudio.com/ from a browser before queueing the load test run.

We've set this up using a Generic Service Point and a Token key.  Is there something else we are missing?

Thanks!

**Comment by dpksinghal** [comment]
Hi

Have you done the following?
_Sign out and sign in to https://foo.visualstudio.com/ from a browser before queueing the load test run._

It is needed as the token that we get to communicate with Application Insights service gets expired after 12 hrs.

You can reach out to vsoloadtest@microsoft.com for all your load test related queries.

Regards,
Deepak.

**Comment by dawilliams** [comment]
Sorry for the late response.  @dpksinghal your suggestion did resolve the issue.

**Comment by dpksinghal** [comment]
Glad to hear this.
