### ISSUE TITLE
Is TestAgentInstall.ps1 is missing the negative sign on line 71?

### ISSUE THREAD

**Issue by StingyJack** [Microsoft/vsts-tasks#2764]
The code segment below from  vsts-tasks/Tasks/DeployVisualStudioTestAgent/TestAgentInstall.ps1  looks like its missing the negative sign preceding the exit code const. 

```		if($exitCode -eq 2147205120) ```

Is this intended to be the positive value?

**Comment by allendm-msft** [comment]
it should be negative. PR raised.
