### ISSUE TITLE
Incorporate 3rd Party Provisioning Tools

### ISSUE THREAD

**Issue by brentarias** [Microsoft/vsts-tasks#2765]
I would like to execute Terraform or Ansible scripts in my CD pipeline as tasks.  I expected these tasks would be either built-in or available in the extension marketplace, but they are not.

So I ask:

- Will these be added? Or...
- Am I asking the wrong question?  If there is a reason why such tasks would not make sense as part of a VSTS build definition, I would like to understand why.

**Comment by DavidStaheli** [comment]
Hi @brentarias, you are asking the right question.  We are always adding more built-in tasks and extensions, but haven't gotten to Ansible or Terraform yet.  You would always be welcome to create your own extensions for them in the Marketplace.  @RoopeshNair might have a better idea for when we could get to them ourselves.
