### ISSUE TITLE
FTP Upload `Clean` Option only performs a shallow clean

### ISSUE THREAD

**Issue by dsschnau** [Microsoft/vsts-tasks#2768]
In the tooltip for VSTS FTP Upload Task, the 'Clean' option states it will Recursively delete the contents of the target folder before the upload.

![cleandir_description](https://cloud.githubusercontent.com/assets/1373329/19090406/3e5fee5a-8a4c-11e6-8da6-c05d3bae938f.png)

It looks like this isn't the case, as I found when trying to use the FTP task to replace the contents in my sites `wwwroot/` directory, it only did a shallow delete.

I think the problem is on [line 99 of ftputils.ts](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/FtpUpload/ftputils.ts#L99). The call out to `node-ftp` accepts a [recursive option](https://github.com/mscdex/node-ftp/blob/master/lib/connection.js#L738) that is not currently enabled.

I can gladly submit a PR for this issue but I wanted to ask first if this design was intentional. Thank you!

**Comment by DavidStaheli** [comment]
Thank you for reporting this, @dsschnau.  It is definitely an oversight.  Would you like to submit the PR?  Otherwise, we'll gladly get to it sometime this week.

**Comment by DavidStaheli** [comment]
Thank you for reporting this, @dsschnau.  It is definitely an oversight.  Would you like to submit the PR?  Otherwise, we'll gladly get to it sometime this week.

**Comment by dsschnau** [comment]
Looks like I'm mistaken - There is a helper function that does include the `recurisve` parameter set to `true` on [line 84](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/FtpUpload/ftputils.ts#L84). My issue must be elsewhere.

I'll close this issue. Thank you for the quick feedback!
