### ISSUE TITLE
Trailing \ in Path to Publish field fails the copy new .37

### ISSUE THREAD

**Issue by chrisrpatterson** [Microsoft/vsts-tasks#2793]
if you leave a trailing '\' in the "Path to Publish" field for the Publish Artifact build step, the copy will fail.  This wasn't a problem with version .34 of the build step. Seems to have been introduced with .37

**Comment by ericsciple** [comment]
Anyone know what OS the repros on? I can't repro on Win 7 SP 1.

**Comment by ericsciple** [comment]
Nevermind I've got a repro. This happens when the source path contains a space and ends with `\`

**Comment by ericsciple** [comment]
PR https://github.com/Microsoft/vsts-tasks/pull/2846

**Comment by ericsciple** [comment]
Fix will go out with the m108 deployment (starts rolling in about 3wks).
