### ISSUE TITLE
How to display test results of individual test in the ordered test suite in TFS Web

### ISSUE THREAD

**Issue by ampetrushenko** [Microsoft/vsts-tasks#2803]
Hi!
After we have implemented ordered tests we can see only "Main" test result in TFS Web, but to see test results of individual tests in the ordered test suite we need to download the *.trx file and open it in Visual Studio.

Maybe anybody know how to display test results of individual test in the ordered test suite in TFS Web, without downloading *.trx

Thank you in advance

**Comment by allendm-msft** [comment]
@ampetrushenko This is a limitation of the run functional test task. You can publish the trx file using the "publish test results" task and it will show you all the tests but you wont know which ".orderedtest" they were associated with etc.

**Comment by ampetrushenko** [comment]
Hi @allendm-msft !
Thank you for your answer!
We have added Publish Test Results Task with the following settings:
![image](https://cloud.githubusercontent.com/assets/20642314/19314919/8597b998-90a4-11e6-971f-499e24c5d58f.png)

But test results still displayed as one test. In log I can see:
No test result files were found using search pattern 'C:\a\r1\a\**\*.trx'

How can i set correct location of *.trx file?

**Comment by ampetrushenko** [comment]
@DavidStaheli  Can we reopen this issue?
Thank you in advance!
