### ISSUE TITLE
Cannot Email "RM_Customer_Queries at microsoft dot com"

### ISSUE THREAD

**Issue by jfoshee** [Microsoft/vsts-tasks#2806]
The `SqlAzureDacpacDeployment` task documentation suggests emailing `RM_Customer_Queries at microsoft dot com`.  Emailing that address bounces with an error like:

> Your message to <redacted>@microsoft.com couldn't be delivered.
> The group vsdpteng only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.

**Comment by KrishnaAdityaB** [comment]
@jfoshee we got it fixed. please re-open this if you still face the issue.
