### ISSUE TITLE
Service Fabric Update Application Versions tries to compare against wrong directory

### ISSUE THREAD

**Issue by kostrse** [Microsoft/vsts-tasks#2808]
When **Update only if changed** is set, **Service Fabric Update Application Versions** task tries to compare contents of the application package against a wrong directory of previous package.

### Description

My build creates Service Fabric application package under the path:
`src/Services/ServiceFabricApplication1/pkg/Release`

My **Publish Build Artifacts** task publishes this directory (*Path to Publish*) into *Artifact Name* `ServiceFabricApplication1`

The **Service Fabric Update Application Version** tasks unpacks the given artifact into the directory `D:\build\tmp\ServiceFabricApplication1`, so my *ApplicationManifest.xml* file for the previous build is at `D:\build\tmp\ServiceFabricApplication1\ApplicationManifest.xml`

But the task tries to find it at `D:\build\tmp\ServiceFabricApplication1\src\Services\ServiceFabricApplication1\pkg\Release\ApplicationManifest.xml`

### Log
```
##[section]Starting: Update Service Fabric App Versions
Searching for application package: D:\build\1\s\src\Services\ServiceFabricApplication1\pkg\Release
Found application package: D:\build\1\s\src\Services\ServiceFabricApplication1d\pkg\Release
Version Suffix: '.0.1.7'
Previous build number: '0.1.6'
Downloading artifact 'ServiceFabricApplication1'...
Previous build location: 'D:\build\tmp\ServiceFabricApplication1'
Searching application type 'ServiceFabricApplication1Type' for changes...
##[error]Cannot find path 'D:\build\tmp\ServiceFabricApplication1\src\Services\ServiceFabricApplication1\pkg\Release\ApplicationManifest.xml' because it does not exist.
##[section]Finishing: Update Service Fabric App Versions
```

**Comment by EricJizbaMSFT** [comment]
Ideally you could specify whatever you want for the subpath of the previous drop artifact. However, if we implemented a field to specify the subpath, we wouldn't have a good way to set that path when a user's task is upgraded. Since this could break existing users and there's an existing workaround (make sure the subpaths match), closing this as won't-fix for now.

Please re-open if you feel strongly about this.

**Comment by pgrapso** [comment]
Hello,
I am having exactly the same problem but the service fabric app I am trying to build is new in my solution so it does not exist in the previous build.

@EricJizbaMSFT: you mentioned there is a workaround for this? I would really appreciate your help.

Thanks.
