### ISSUE TITLE
No "Clean before build" option in Xamarin.iOS project task

### ISSUE THREAD

**Issue by alxbog** [Microsoft/vsts-tasks#2825]
It'd be very useful option.

Current workaround: explicitly running "xbuild /t:clean" before Xamarin.iOS build task.

**Comment by jsauvexamarin** [comment]
You can clean by using a variable:
https://www.visualstudio.com/docs/build/define/repository##build_clean_variable

**Comment by ericsciple** [comment]
@madhurig  fyi regarding feedback

There is also the clean checkbox on the repo tab of the definition. Technically it's a different thing than running the clean target. Repo clean for a git repo is "git clean -fdx ; git reset --hard". For TFVC on OSX it's drop the workspace and re-sync (it's scorch on Windows but scorch is not implemented in TEE CLC yet).

**Comment by madhurig** [comment]
@alxbog: I am seeing that xbuild /t:clean does not clean up the IPAs on the latest Xamarin. Does it work for you?

**Comment by alxbog** [comment]
@madhurig Didn't check that in fact. I'm using repo clean now.

**Comment by madhurig** [comment]
@alxbog: I will follow up on the right way to cleanup all artifacts created by Xamarin iOS build. If we provide a clean option, it should not just pass /t:Clean if that is not sufficient. I agree this will be a useful option to add!

**Comment by madhurig** [comment]
We are tracking this on our internal product backlog.

**Comment by madhurig** [comment]
Cycle 9 of Xamarin has the changes to respect /t:Clean i.e. all build output is cleaned. The IPAs no longer are generated under a timestamped folder.
