### ISSUE TITLE
Unable to disconnect service endpoint if the user who created it has been removed from subscription

### ISSUE THREAD

**Issue by TheSchmoe** [Microsoft/vsts-tasks#2832]
I'm trying to disconnect a service endpoint in VSTS and the person who created it is no longer a part of our team.  When I click 'Disconnect' I get the following error: 

> Failed to unassigning contributor role for the service principal on subscription Id [sub id]: error code: BadRequest, innner error code: InvalidRoleAssignmentId, inner error message The role assignment ID '' is not valid. The role assignment ID must be a GUID.

My best guess is that this is a result of the user who created the service endpoint not having a role assignment anymore.  Any help or workarounds would be greatly appreciated.

**Comment by nibras85** [comment]
I'm getting this same issue. Please fix!

**Comment by SushantKadam008** [comment]
Hi,
Is there any solution for this ? Even I am facing the same issue.

**Comment by pavanadepu2** [comment]
@SushantKadam008 , @nibras85 , @TheSchmoe, If the current user doesn't have enough permissions on the azure subscription, then the disconnect operation throws the above error. To resolve this issue, make sure the current user is an owner of the Azure subscription.

**Comment by pavanadepu2** [comment]
The above issue has been fixed. Now you should be able to disconnect. Let me know if you still see an issue while disconnecting the service endpoint.
