### ISSUE TITLE
How is service fabric certificate cleared from the store?

### ISSUE THREAD

**Issue by dennisfrostlander** [Microsoft/vsts-tasks#2834]
Hi,

I was just curious how Service Fabric Deployment task handles the certificates. This task imports the certificate to the store and then the rest of deployment works as intended.
See https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/ServiceFabricDeploy/utilities.ps1, Add-Certificate script.

But I don't understand one thing - how is the certificate removed from the store after the task or the build finishes? I did not find any code for doing that.
Even if the certificate is somehow removed, can other evil builds running at the same time on the same hosted VM access my cluster if they use pick proper certificate from the store?

**Comment by ericsciple** [comment]
The hosted image is thrown away after each build. It's essentially a fresh machine every build.

**Comment by ericsciple** [comment]
Please reopen if that doesn't fully answer the question.
