### ISSUE TITLE
Run Functional Tests Queuing

### ISSUE THREAD

**Issue by ShakedTBolt** [Microsoft/vsts-tasks#2836]
Hi,

When trying to run more than release definition on the same group of machines, I'm getting warning the following warning:

DistributedTests: You may be using machine across one or more concurrent builds. This is currently not supported. Use an unique machine per build definition and ensure there are no concurrent builds In Progress from any given build definition using a machine. 

This is a big issue for us, because we have more than 30 releases (microservices), and we would like to have the machines as flexible as it can.
There is any way to queue the tests on the machines? or at least wait until all the tests are done.
I was trying to wait for taskeng process to finish with no luck.

Thanks!

**Comment by hqer2k9** [comment]
As far as i know, there is no way to accomplish what you are trying to do. What you could do is create 1 agent pool with 1 agent and queue everything on that agent so the builds queue one after another. But this may be not the best way considering the build time.

**Comment by ShakedTBolt** [comment]
Actually, for now we can create few agents that will use only specific servers. still not perfect.
This is a subject of change?
Got the feeling that microsoft take a step back every new version. Things that were trivial in the past now requires a lot of efforts to accomplish.

**Comment by atinb** [comment]
@ShakedTBolt Thanks for the feedback. This is definitely something we are working on addressing. Please stay tuned to our VSTS release notes - we should have something to try and give feedback in a couple of sprints. Thanks!
