### ISSUE TITLE
Changeset is linked to arbitrary work items

### ISSUE THREAD

**Issue by Griffelo** [Microsoft/vsts-tasks#2841]
Hi,

on TFS 15 RC2 we have an gated checkin build. It has only two task. Visual Studio Build and Visual Studio Test.
Now we have the issue that every changeset that has been checked in is linked to an arbitrary list of additional work items.

I found no solution to change that behavior.

Thanks

**Comment by ericsciple** [comment]
See https://github.com/Microsoft/vsts-agent/issues/559

**Comment by Griffelo** [comment]
Hi,
the workaround works for us.
Thanks a lot!
