### ISSUE TITLE
vsbuild task - supported products

### ISSUE THREAD

**Issue by amccool** [Microsoft/vsts-tasks#2849]
[question tag]

What editions of Visual Studio are supported?
Visual Studio Express for Web?
Express at all?

**Comment by ericsciple** [comment]
Yes they are all supported. Currently the task uses the value in the dropdown to correlate which version of msbuild to invoke and passes the visualstudio version as a property on the msbuild cmdline (can influence some target decisions e.g. which version of stylecop targets to use).
