### ISSUE TITLE
Run Functional Tests split into two runs within one build

### ISSUE THREAD

**Issue by hqer2k9** [Microsoft/vsts-tasks#2854]
We have 2 test runs that run after another, short running tests (110 min) and long running tests (50 min) . is it possible to make those run at the same time with 1 build? like saying short running tests have test machine 1-6 and long running tests machine 7-10 ? currently test distribution can only distribute in one task for all machines. Would speed up the build much.

**Comment by allendm-msft** [comment]
@hqer2k9 currently this is not possible in build. But you could use release having 2 environments. 1st env having the short running tests and 2nd env having the long running tests and both can be scheduled in parallel by having the release trigger to be associated with your build.

**Comment by hqer2k9** [comment]
@allendm-msft Thanks for the fast and good reply! Will definitely try this out :)
