### ISSUE TITLE
JaCoCo coverage data found

### ISSUE THREAD

**Issue by leantk** [Microsoft/vsts-tasks#2856]
I enabled JaCoCo for my Gradle build task but the completed build says the results are not found. I have 3 separate packages built by the Gradle build. From the logs I see:

2016-10-12T16:16:33.1800310Z Reading code coverage summary from '/home/xplatalm/vsts-agent/_work/5/s/CCReport43F6D5EF/summary.xml'
2016-10-12T16:16:33.4526460Z ##[warning]No coverage data found. Check the build errors/warnings for more details.

The summary.xml file exists on the build machine and contains a lot of entries that looks like: 
<sessioninfo id="xplatalm-lbuild-03-55d93ee1" start="1476286613883" dump="1476286631570"/>

I'm not sure if that file hold contains more or not. I've attached my log file from my build so you can look for yourself.

[logs_3338777.zip](https://github.com/Microsoft/vsts-tasks/files/525233/logs_3338777.zip)

**Comment by nigurr** [comment]
@leantk 
Can you share this info?
1. vsts-agent version and task version
2. please enable `system.debug = true` in build variables and share the build log
3. please attach the `summary.xml`

**Comment by nigurr** [comment]
Closing this issue as we are not able to repro.
Please feel free to reopen if you are still facing issue

**Comment by SaikatCool** [comment]
@leantk did you find a solution to this problem??

@nigurr I am the same problem, could you please support??

**Comment by nigurr** [comment]
@SaikatCool this should have been fixed now. We have rolled out fix already. Can you share your DevOps Account?

**Comment by SaikatCool** [comment]
How do u want me to share my account? Actually it is a corporate account. 
I have created a new issue anyway:
https://github.com/Microsoft/azure-pipelines-tasks/issues/10271

Let me know if you anything else.
