### ISSUE TITLE
AzureRM Web App deployment issue : Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by PrashanthReddyAnnedla** [Microsoft/vsts-tasks#2858]
We are using Deploy AzreRM Web App task for deployment. Getting below error while deploying

2016-10-12T09:36:10.2957680Z ##[debug]Processing: ##vso[task.issue type=error;]TypeError: Cannot read property 'id' of undefined 
2016-10-12T09:36:10.2957680Z ##[error]TypeError: Cannot read property 'id' of undefined

Attaching the log
[Error.txt](https://github.com/Microsoft/vsts-tasks/files/525552/Error.txt)

**Comment by vincentdass** [comment]
@PrashanthReddyAnnedla , please add `console.log(url); console.log(headers);` below [azurermutil.**js**](https://github.com/Microsoft/vsts-tasks/blob/releases/m106/Tasks/AzureRmWebAppDeployment/azurermutil.ts#L206)
and  `console.log(body); console.log(webAppIDDetails ); `  below [azurermutil**.js**](https://github.com/Microsoft/vsts-tasks/blob/releases/m106/Tasks/AzureRmWebAppDeployment/azurermutil.ts#L212)
 and run the task and provide the logs. Please make sure that the changes are made in **'.js'** files **not in '.ts'** files.

**Comment by nibras85** [comment]
I am getting the same issue. Very frustrating..

**Comment by PrashanthReddyAnnedla** [comment]
@vincentdass - We dont have access to the Agent machines hence cannot update the script!

I will try to do it my local agent and see if I am able to repro this issue!

**Comment by nibras85** [comment]
@vincentdass  I was able to add the logging to the task in my local agent and I got the output but it has my subscription ID and other sensitive info that I can't share here... from what I gathered from the logs... I'm guessing that the API call to look up the Azure WebApp... is returning an empty array...

**Comment by vincentdass** [comment]
@nibras85 , thanks for the info. Can you replace header  in [azurermutil.js](https://github.com/Microsoft/vsts-tasks/blob/releases/m106/Tasks/AzureRmWebAppDeployment/azurermutil.ts#L204)  with
`var headers = {
        authorization: 'Bearer '+ accessToken,
        'Cache-Control':  'no-cache'
    };
`
and queue a new build/release ?

**Comment by nibras85** [comment]
@vincentdass  I did. Same error.

**Comment by PrashanthReddyAnnedla** [comment]
@vincentdass , 
One more observation : Selected the slot, resource group in the task. Got the error as 404 not found, though the website exists

**Comment by vincentdass** [comment]
@PrashanthReddyAnnedla ,  Did you create a slot from Azure Portal ? (if Slot is not created, it throws 404 error)
![image](https://cloud.githubusercontent.com/assets/20121508/19416605/58a6443e-93b2-11e6-99a8-0483ab623bc8.png)

**Production** slot is applicable only for Azure Classic Web Deployment Task. It should not be explicitly specified as slot for AzureRM web App Deployment task. By default, it is deployed in Production slot.

**Comment by PrashanthReddyAnnedla** [comment]
@vincentdass 
I am not trying to create a new slot here, deploying to Production slot only.
I will send you the details over the mail.

**Comment by vincentdass** [comment]
@nibras85 , Can u mail the log with the debug messsages ?

**Comment by nibras85** [comment]
@vincentdass please share your email address and I can share the logs with you. Thanks.

**Comment by vincentdass** [comment]
@nibras85, vinca@micrsoft.com

**Comment by nibras85** [comment]
@vincentdass sent. Thanks a lot.

**Comment by vincentdass** [comment]
@nibras85 , @PrashanthReddyAnnedla . It's a genuine issue and will be fixed in the upcoming deployment.

**Comment by mxa0079** [comment]
@vincentdass any work arounds?

**Comment by bryanmacfarlane** [comment]
@vincentdass - do we want to patch the task or is it fixed in 107 (rolling now)?

**Comment by vincentdass** [comment]
@bryanmacfarlane  - We will patch this issue with 107. We have recently identified the different cause of issue will fix it soon .

**Comment by Ajay-MS** [comment]
@max0079

We have identified different cause of this issue. Need some info from you regarding issue.
1. Does webapp on which you are trying to deploy already exists?
2. Follow steps being mentioned by @vincentdass  in his first reply.
3. Enable debug logs, you can enable debug logs by adding variable 'System.Debug' and set its value to 'true' and share logs at ajya@microsoft.com.

**Comment by mxa0079** [comment]
@Ajay-MS We are using hosted agents,so we cannot make the changes mentioned by @vincentdass (and cannot afford the time to create a dedicated agent to debug this issue) -- however, I will be glad to enable the verbose logs if this will help you.

**Comment by vincentdass** [comment]
@mxa0079 , this issue is hotfixed and will be available in a day or two.
