### ISSUE TITLE
Display test results of individual test in the ordered test suite in TFS Web

### ISSUE THREAD

**Issue by ampetrushenko** [Microsoft/vsts-tasks#2862]
Following your recommendations in Issue #2803  we have added Publish Test Results Task with the following settings:
![image](https://cloud.githubusercontent.com/assets/20642314/19314919/8597b998-90a4-11e6-971f-499e24c5d58f.png)

But test results still displayed as one test. In log I can see:
_No test result files were found using search pattern 'C:\a\r1\a\**\*.trx_'

How can i set correct location of *.trx file?

**Comment by allendm-msft** [comment]
$(System.DefaultWorkingDirectory)\TestResults\*.trx

**Comment by SatishThareja** [comment]
@ampetrushenko Did changing the results file pattern unblock you?

**Comment by SatishThareja** [comment]
@ampetrushenko Ping. Did your issue get resolved?
