### ISSUE TITLE
Run Functional Test task run cannot be aborted or stopped

### ISSUE THREAD

**Issue by hqer2k9** [Microsoft/vsts-tasks#2865]
In TFS 15/ TFS 2015 vNext how can you stop or abort a test run? You can stop the Build that started the test run, but the test run will continue till you shut down the test machines.

**Comment by allendm-msft** [comment]
This is a bug

**Comment by hqer2k9** [comment]
@allendm-msft  ok,, thanks for the reply! Got any good workarounds or scripts or anything to share? :)

**Comment by SatishThareja** [comment]
@hqer2k9 I have shared a script to stop test execution here: https://1drv.ms/u/s!Aj_8waqf3hLypzPntAPzwx7jWDf5.
Please try the script and let us know if you get unblocked.

**Comment by hqer2k9** [comment]
Hey @SatishThareja thanks for the reply, It works but its like restarting the test machine, which seems to be the more secure way to abort the test run to make sure there is nothing else running in the background. Do you have a timeframe when this will be implemented with TFS on Prem?

**Comment by atinb** [comment]
@hqer2k9 We have copied this to our backlog. The earliest this would be onprem is dev15 Update1
Thanks!

**Comment by MSTestAuto** [comment]
I am experiencing the same issue with TFS 2017. When will this be fixed?

**Comment by mikefourie** [comment]
Still seeing this in 2017 Update 2

**Comment by hamidshahid** [comment]
@atinb we are still seeing this issue in TFS 2017 Update 2. Any updates please?
