### ISSUE TITLE
Copy and Publish Build Artifacts - Always finds zero files on Mac agent.

### ISSUE THREAD

**Issue by janniklind** [Microsoft/vsts-tasks#2866]
Hi.

I am having troubles with the "Copy and Publish Build Artifacts" task, when it is running on a Mac agent. It seems that it never finds any files. The same task runs fine on VSTS hosted agent.

I get the following output from the log:
2016-10-11T17:50:15.7669480Z ##[section]Starting: Copy Publish Artifact: drop
2016-10-11T17:50:16.0421920Z Cleaning staging folder: /Users/vso123456/vsts-agent/_work/2/a/drop
2016-10-11T17:50:16.0470280Z found 0 files
2016-10-11T17:50:16.0690400Z ##[section]Finishing: Copy Publish Artifact: drop

Steps to reproduce:

1. Create a new Git repository or just use an existing.
2. Create a new build definition with "Copy and Publish Artifacts" as the only build step.
3. Set "Copy Root" to `$(Agent.BuildDirectory)`
4. Set "Contents" to `**\*`
5. Set "Artifact Name" to `drop`
6. Set "Artifact Type" to `Server`
7. Now run the build on the VSTS Hosted agent.
8. Verify that an artifact named "drop" is created.
9. Now run the build on a Mac agent. (I am using the Macincloud VSTS Agent linked below).
10. Verify that an artifact is not created. (The error!)

Does the  "Copy and Publish Build Artifacts" not support Mac agents?

Macincloud VSTS Agent link:
https://support.macincloud.com/support/solutions/articles/8000023177-versions-of-tools-and-applications-on-vsts-agent-plan-servers-

**Comment by ericsciple** [comment]
Does it work with `**/*` instead?

**Comment by janniklind** [comment]
Unfortunately no.

I have even tried just using `$(Build.SourcesDirectory)` as Copy Root, and then in Contents I have added a complete path to a file I know exists in the source repository.

**Comment by ericsciple** [comment]
Are you using forward slashes and case-sensitive?

I'm not able to repro. Can you please provide some sample inputs?

**Comment by ericsciple** [comment]
...i mean sample inputs for the case where you are specifying the complete path to the file.

**Comment by janniklind** [comment]
Hi.

To ensure we are testing at the same I have created a repository:
https://github.com/janniklind/vsts-copy-publish

I have created a build definition with just a single "Copy and Publish Build Artifacts" task:
![image](https://cloud.githubusercontent.com/assets/707081/19410669/169f2422-92f2-11e6-9657-6d0cbb4a23cb.png)

When I run it on the hosted Microsoft Agent in VSTS it copies all the files without any problems: [hosted-build-log.txt](https://github.com/Microsoft/vsts-tasks/files/531171/hosted-build-log.txt)

However when I run on the MacinCloud Agent it always find zero files:
[macincloud-build-log.txt](https://github.com/Microsoft/vsts-tasks/files/531176/macincloud-build-log.txt)

**Comment by ericsciple** [comment]
Can you try with `**/*` instead of `**\*`?

**Comment by ericsciple** [comment]
fyi - `**/*` (forward slash) works for me on OSX using your repository. The approach we generally try to take in the tasks and agent is: the tasks and agent should not convert backslash to forward slash on Linux/OSX, since backslash is a valid file name character. On Windows, in certain places, we take the opposite approach since forward slash is not a valid file name character.

For path pattern matching, use forward slash if your definition runs on Windows and OSX/Linux. If it runs on Windows only, then backslash is OK as well.

**Comment by janniklind** [comment]
Today I tried with the `**/*` in the sample project and it worked. Don't know why I didn't test that in the sample project. I thought I had, but I must be wrong.

I still had trouble in my original project, but after removing the build step and adding it again, it now seems to work. I have no idea what it was.

Anyway, this can be closed, thanks for your help! :)
