### ISSUE TITLE
Nuget install/restore vsts feed warning

### ISSUE THREAD

**Issue by xingyu217** [Microsoft/vsts-tasks#2868]
##[warning]To connect to NuGet feeds 
    hosted in your Team Services account/TFS project collection with 
    NuGet 3.1 or below, edit your build definition to specify a path 
    to a NuGet.config containing the package sources you wish to use.

This warning occurs even though using higher version of Nuget tool or do not restore package from VSTS feed.

**Comment by zjrunner** [comment]
Thanks for reporting.  I see the issue in the code coming from our transition from depending on assets coming with the agent to being deployed with the task.  You can get around this by either (1) choosing to use the Nuget 3.5 version radio button in the task config or (2) supplying a path to your nuget.config.

**Comment by xingyu217** [comment]
Thanks.
