### ISSUE TITLE
[Question] How do I setup SonarQube task in VSTS for PHP?

### ISSUE THREAD

**Issue by sinapis** [Microsoft/vsts-tasks#2870]
Hi,

If I only add "SonarQube for MSBuild - Begin Analysis" and "SonarQube for MSBuild - End Analysis" I get the following error:

> The SonarQube MSBuild integration failed: SonarQube was unable to collect the required information about your projects.
> Possible causes:
> 1. The project has not been built - the project must be built in between the begin and end steps
> 2. An unsupported version of MSBuild has been used to build the project. Currently MSBuild 12.0 upwards are supported
> 3. The begin, build or end steps have not all been launched from the same folder

But how do I build PHP? Can you please advise what build step I should use?

Note, I have SonarQube analysis up and running for .Net and Java projects for the same account.

**Comment by bgavrilMS** [comment]
Hi @sinapis - we don't an out of the box solution for scanning PHP yet, however this is in the plans. By reading on the PHP plugin (http://docs.sonarqube.org/display/PLUG/PHP+Plugin) it seems that the analysis needs to be driven via the SonarQube Scanner. 

We are transferring ownership to Sonar Source and it's on their backlog to provide a task that drives the scanner - the tracking item is https://jira.sonarsource.com/browse/MMF-498 

In the meantime - consider using a private build agent and install the SonarQube Scanner on it. Then drive it via the command line (there are cmd / powershell build tasks you can use).
