### ISSUE TITLE
Obscure failures in publish test results

### ISSUE THREAD

**Issue by elibarzilay** [Microsoft/vsts-tasks#2873]
We have a build definition with two steps, the first is a Shell Script where the actual build happens, and then we have a "Publish Test Result" step for JUnit format files.  We ran into a few problems with this, two examples: when a JUnit file has no tests (the `testsuite` tag has `tests="0"`), or when there's an ignored test it's reported with a time of `"-0.001"`.  (The tests are actually Scala tests, which produce JUnit xml files.)

But the real problem is that in each of these failures, all I see in the log is:

```
Failed to publish test results: Test result completed date must be
greater than test result start date
```

And no further information is provided --- specifically, it doesn't say what part of the XML was broken, and more importantly, it doesn't say _which_ file was broken.  I now find myself fixing such problems by disabling all tests, then enabling them one by one to see which one failed, and then I try to guess what is it that made it fail to fix it.

Is there some way to see this information (the failing xml file, and the reason for the failure)?

**Comment by SatishThareja** [comment]
@elibarzilay Can you share the xml file, so that we can repro and debug the issue locally?

**Comment by SatishThareja** [comment]
@elibarzilay Ping.

**Comment by elibarzilay** [comment]
@SatishThareja, sorry -- it's a new project and things are moving fast so I can't reproduce the results easily (would require tweaking the build definition that people are actively using).

When we run the scala tests, it generates junit-style files by default, and those were giving us these problems -- there is a command-line argument that makes it produce slightly different junit files which seem to work better, and we therefore switched to using them.  The default files are still generated too, so I can send you the two sets of files and maybe the difference would be helpful?  (Maybe via email to avoid making it public?)

**Comment by SatishThareja** [comment]
@elibarzilay Sure, do share the files. If we can repro the issue using the files, it will be easy to debug the issue.

**Comment by knunery** [comment]
Did this issue get resolved?

**Comment by drorwolmer** [comment]
The full error log is 
```
2017-12-17T03:21:07.1182881Z Timestamp is not available for one or more testsuites. Total run duration is being calculated as the sum of time durations of detected testsuites
2017-12-17T03:21:09.4784351Z ##[warning]Failed to publish test results: Test result completed date must be greater than test result start date
```

I read https://github.com/Microsoft/vsts-agent/blob/master/src/Agent.Worker/TestResults/JunitResultReader.cs and implemented:

```sh
sed -i /path/to/test/output/*.xml -e "s/<testsuite/<testsuite timestamp=\"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\"/g"
```

works great!
