### ISSUE TITLE
Can't specify credentials for AzureRMWebAppDeployment

### ISSUE THREAD

**Issue by robertmclaws** [Microsoft/vsts-tasks#2879]
I am attempting to deploy a site with this task, and I've configured it to use the AzureRM subscription I configured in VSTS. There are no fields to specify a password, so I assumed it was getting the security through the service configuration. However, when the task executed, I got this error message:

```
2016-10-14T21:09:39.3433187Z ##[error]Error: Get Token request returned http error: 401 and server response: 
{
"error":"invalid_client",
"error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: 5f79c903-6d6c-4536-ad0a-47080d2a71f5\r\nCorrelation ID: ff9c22ec-c64b-4843-8219-afc36154cfc8\r\nTimestamp: 2016-10-14 21:09:37Z",
"error_codes":[70002,50012],
"timestamp":"2016-10-14 21:09:37Z",
"trace_id":"5f79c903-6d6c-4536-ad0a-47080d2a71f5",
"correlation_id":"ff9c22ec-c64b-4843-8219-afc36154cfc8"
}
```

Any ideas? Thanks!

**Comment by mvvsubbu** [comment]
Hi Robert,

Sorry for the issue, can you help me with the following details

1.  When you selected the endpoint, is the App Service Names drop down got automatically populated on clicking refresh??
2.  Is the issue consistently happening?
3.  Share task log by setting system.debug variable value to true
4.  Capture fiddler traces and share them.

**Comment by asranja** [comment]
@robertmclaws Hi Robert, any update on the issue ?
