### ISSUE TITLE
'System.Collections' already has a dependency defined for 'Microsoft.NETCore.Platforms'.

### ISSUE THREAD

**Issue by patrickmichalina** [Microsoft/vsts-tasks#2880]
When running the nuget pack task in VSTS online, the default version of nuget fails when a package references System.Collections. This was discovered when I updated some libraries to a newer version of OData.EDM 7.0.0. This failure does not happen when using the latest version, 3.5.0.rc1. It would be nice if the nuget tasks allowed one to select a version of the exe they run. Instead of having to include some reference in source control.

**Comment by zjrunner** [comment]
We are looking at making this better, but it needs to coordinate with some task-lib work to make it easier to fetch and cache tools.  For now you can use a powershell task to pull nuget to the machine prior to running the packager if you prefer not to have it checked in.

**Comment by patrickmichalina** [comment]
@zjrunner thanks

**Comment by Kwal** [comment]
Any updates on this?

**Comment by zjrunner** [comment]
We did add 3.5 to the nuget tasks, but nugetpackage is still on the older powershell task engine.  This enhancement is being tracked as part of a larger Nuget Task Upgrade set in our internal system here:
Feature 564185: NuGet build tasks v2

**Comment by Kwal** [comment]
Awesome - thanks for the update!
