### ISSUE TITLE
Unable to read NUnit 3 TestResults.xml files

### ISSUE THREAD

**Issue by tiefling** [Microsoft/vsts-tasks#2887]
VSTS will not read XML file output from NUnit 3. This is crucial for dotnet core support, where the VSTS test runner itself doesn't work.

We have no viable solution here for visibility of build failure.

**Comment by atinb** [comment]
Same issue as #2468. We are working on adding the support.
Thanks!

**Comment by tiefling** [comment]
Thanks @atinb - I hadn't found that before - I'll follow it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
