### ISSUE TITLE
[Question] How to update tasks w/o internet connection

### ISSUE THREAD

**Issue by Gimpan** [Microsoft/vsts-tasks#2890]
Hi,

I have a questions about how to get new vsts tasks to my build agents or TFS '15'. Correct me if I'm wrong, but as I understand it:
-Build agents uses vsts tasks
-vsts tasks are downloaded when newer versions are released
-Tasks are updated automatically
-Internet connection is required.

What if my environment does not have internet access?
I need to get a specific task working (#2689) that I understand have been fixed. I've tried downloading node.js and used npm to build release m107. I understand that I need package it but how do I do from here?

I've tried my googling skills and looked around here for documentation but I feel it'd be easier to just ask.
If there is a forum or other website for questions like this, any directions would be appreciated.

Thanks!

**Comment by bryanmacfarlane** [comment]
Tasks are downloaded from the server.  They are downloaded when a new version is available in your server (not the internet).

**Comment by Gimpan** [comment]
@bryanmacfarlane Thanks for your reply, that makes perfect sense now that you mention it!

So to the follow up questions:
How do our tfs server download new versions? Through Windows Update?
Are there ways to "upload" the new tasks to our server? Like manually copy paste/deploy?

**Comment by DavidStaheli** [comment]
Hi @Gimpan, for on-premises installs of TFS (not Team Services), the update mechanism for built-in build/release tasks is installation of quarterly updates (the next being in November).  You could build this repo yourself and use the [tfx](https://github.com/Microsoft/tfs-cli) tool to upload individual task folders in the _build directory to your TFS server, but that is **unsupported** and **doesn't always work** because tasks are not back-tested nor always compatible with prior versions of TFS.  You would have the best luck with TFS 2015 Update 3 and the latest build agent version, but there is still no guarantee.  :(

**Comment by Gimpan** [comment]
@DavidStaheli ,thanks for your reply.

I've not been able to find information on these quarterly updates but  I guess they are not the RC releases? We're currently using TFS '15' RC1.

Is it a Microsoft server update that we need to subscribe to? Not sure about how these updates work and I don't know how to explain to the guys servicing our servers what I need.

This is a temporary fix but I built the repo and copied the archiving task to the build agent -> work folder -> tasks. This works for that build agent now and runs fine. I'll have to put some time on learning tfx and try your suggestion, even if it is unsupported. :P

**Comment by DavidStaheli** [comment]
Unfortunately my use of the word "update" had a different meaning.  :)  The TFS quarterly updates are not automatic updates.  They are actually quarterly releases.  The next major version of TFS will be released in ~November.  Then there are typically 3 "quarterly update" releases yearly that must be installed manually.  This is of course different than the cloud-hosted Team Services that is auto-updated every 3 weeks.

Your approach of patching the agent's work folder should be fine for the Archive Files task.  If/when you install the final release of TFS '15' (~November), you'll get a newer Archive Files task that will automatically override your patch to the agent's work folder.  Great job being brave!  :)
