### ISSUE TITLE
[xcode] build task now tries to archive by default

### ISSUE THREAD

**Issue by BluMist** [Microsoft/vsts-tasks#2893]
this is causing our builds to fail; we don't need to run archive on each build
the actions is set to "build" only

**Comment by madhurig** [comment]
@BluMist: Can you verify the "Create App Package" option is unchecked in your task? The option is checked by default but if you uncheck it and still have an issue, please attach the build log or email me the debug logs - madhurig at microsoft dot com. 

Thanks,
Madhuri

**Comment by BluMist** [comment]
Can we still generate .ipa without checking "Create App Package"? archive was not required previously to generate .ipa

**Comment by madhurig** [comment]
@BluMist: To generate an IPA you have to check "Create App Package". We recently changed the behavior if using Xcode 7 or 8 to archive and then export which is the recommended method. Can you confirm which version of Xcode you are using?

Please send me the log, so I can investigate why you are hitting an error. To go back to the old behavior, on your build definitions set a variable "useXcrun" to "true". That should generate the IPA with the "xcrun" tool like before. 

Thanks,
Madhuri

**Comment by BluMist** [comment]
Given the magnitude of the changes, would have preferred this to be an opt-in feature instead of having to opt-out with an undocumented parameter.

A few issues:
1. Our team uses archive only for production/appstore builds, so we explicitly disable archive for our scheme and manually enable for archiving, therefore this fails for us.
2. The new method now compiles twice, significantly adding to the build time. It runs xcodebuild build and then xcodebuild archive. I don't see a way to disable the first round of compile with the current parameteres.
3. We now need to figure out the correct parameters for xcodebuild archive in order to produce the right .ipa with the correct codesign. This will require some time for trial and error, especially with the issue with double compile above.

**Comment by madhurig** [comment]
@BluMist: Thanks for the feedback. I will consider switching back to "xcrun" as the default for Xcode 7.
1. Do you use the IPA generated by the build since it is not code signed?  
2. I understand the building twice for creating the IPA with the new mechanism (this is recommended by Xcode). We have another task "XcodePackageiOS" that uses xcrun. We are considering allowing that to only create IPA or provide more options in the Xcode task to be more flexible but that will require a big change in inputs. Once there is an ability for users to opt-in to task features instead of always getting the update, we will do that. 

Thanks,
Madhuri

**Comment by BluMist** [comment]
Thanks, Madhuri. Any ETA on when this will be deployed?

regarding codesign, the .app is always signed. .ipa is essentially a zip looking at the xcrun script. I'm not sure what xcodebuild archive does differently.

**Comment by madhurig** [comment]
@BluMist: I am hoping to deploy today. The .ipa generated by xcrun is invalid if you have some projects like Swift or Watchkit. Apple deprecated xcrun and it is not recommended for generating your app packages with Xcode 7 and 8. I found that is still works for Objective C projects. Can you please share the build definition settings and the error log from your failure?

Thanks,
Madhuri

**Comment by madhurig** [comment]
@BluMist: The task will continue using xcrun by default. To use xcodebuild archive/export you will need to set a variable useXcrun=true. In the next update we will provide an option in the task.
