### ISSUE TITLE
Upgrade Service Fabric Deployment Scripts to version 2.3

### ISSUE THREAD

**Issue by philcarbone** [Microsoft/vsts-tasks#2894]
People are receiving a timeouts on the upload of Service Fabric applications. The 2.3 release has updates to fix this. Could this be updated in the tasks and have the CopyPackageTimeoutSec argument override added to the task settings?

**Comment by daroco** [comment]
I see that Dev15.Update1 is marked as 100% complete - is there an ETA on when that will be released into VSO?

**Comment by EricJizbaMSFT** [comment]
If you're asking specifically about this issue, we have not implemented a fix yet. We will try to get it in the next sprint, which will release in about a month

**Comment by edtheshed** [comment]
any updates?
