### ISSUE TITLE
vnext agent disk runs full regulary

### ISSUE THREAD

**Issue by hqer2k9** [Microsoft/vsts-tasks#2902]
hard disk where VNext agent is running gets full because the _work folder doesn't get cleaned. The "Clean" command within the build definition does not help, there are just getting number folders created (1,2,3,4,5,6,7 and so on..) after 2 or 3 work days, the hard disk is full and the number folders have to be deleted manually

**Comment by bryanmacfarlane** [comment]
clean command just cleans that repo (git clean -fdx, git reset hard or tf scorch).  How many definitions is that agent building?  There's a repo per definition that the agent builds.  The only time it generates another folder is if the url / repo / endpoint changes on the repo.

Here's how it works:  https://github.com/Microsoft/vso-agent/blob/master/docs/workfolder.md

When the url changes, it will mark the repo as orphaned.  We have work starting this sprint, to run clean up on repos.  But first, you should understand why you're getting so many.  

If you have a bunch of definitions all build by the same set of agents, you will end up with all agents have all repos for all definitions. 

This is also not a task issue.  The agent is here: https://github.com/Microsoft/vsts-agent
