### ISSUE TITLE
ConfigureWinRM.ps1 downloads from non existing urls

### ISSUE THREAD

**Issue by RomanDidenko** [Microsoft/vsts-tasks#2908]
Tasks/PowerShellOnTargetMachines/ConfigureWinRM.ps1 script try to download tools from non existing url https://azurergtaskstorage.blob.core.windows.net/winrm/makecert.exe

**Comment by zhy2002** [comment]
+1

**Comment by ignacy130** [comment]
+1

**Comment by pavanadepu2** [comment]
@RomanDidenko , @zhy2002 , @ignacy130 , Thanks much for reporting the issue. 
The issue is fixed, you may retry your script to configure the WinRM.

**Comment by asranja** [comment]
Closing this issue as it has been resolved by @pavanadepu2
