### ISSUE TITLE
Run Functional Test task fails

### ISSUE THREAD

**Issue by jtbatzer** [Microsoft/vsts-tasks#2922]
I'm trying to run a Selenium test using the Run Functional Test step from a vNext build definition on TFS 2015, the test project's sources are built on the TFS server and copied to a remote machine running Windows 8.1. However, when it's to run the unit test, nothing happens with a repeated message " test is in state 'InProgress' " in the TFS console. On the DTAExecutionHost log file in the remote machine, the following lines are repeated (snippet from end of log file):

Web method response: [https://kl-atlas.server.com/tfs/DefaultCollection/_apis/test/Agents/25/Commands/0](GET)0[test] 53 ms
V, 2184, 153, 2016/10/22, 16:44:54.183, KLPC-607V\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 2184, 153, 2016/10/22, 16:44:54.183, KLPC-607V\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 2184, 153, 2016/10/22, 16:44:54.183, KLPC-607V\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 50000 milliseconds.
V, 2184, 154, 2016/10/22, 16:45:44.468, KLPC-607V\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [https://kl-atlas.server.com/tfs/DefaultCollection/_apis/test/Agents/25/Commands/0](GET)0[test]
Web method response: [https://kl-atlas.server.com/tfs/DefaultCollection/_apis/test/Agents/25/Commands/0](GET)0[test] 34 ms
V, 2184, 155, 2016/10/22, 16:45:44.499, KLPC-607V\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 2184, 155, 2016/10/22, 16:45:44.499, KLPC-607V\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 2184, 155, 2016/10/22, 16:45:44.499, KLPC-607V\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 50000 milliseconds.

This task times out after 1 hour on the TFS server.

**Comment by SatishThareja** [comment]
@jtbatzer We will need build logs to debug this issue. Please collect the build logs by setting build variable 'system.deug' to true and send it to devops_tools@microsoft.com.
Please mention the version for TFS, Test Agent and build agent as well.

**Comment by SatishThareja** [comment]
@jtbatzer Please include DtaExecutionHost logs as well.

**Comment by jtbatzer** [comment]
@SatishThareja - I have sent the email with log files to devops_tools@microsoft.com.  Thanks for the quick response.

**Comment by jtbatzer** [comment]
@SatishThareja - I received an undeliverable message with failed delivery to several recipients/groups when sending email to devops_tools@microsoft.com.

**Comment by jtbatzer** [comment]
@SatishThareja - Just checking in.  Is there any update on the review of the log files?

**Comment by SatishThareja** [comment]
@jtbatzer Looks like the logs shared by you contain information for  more than one run. Can you download the build logs (setting system.debug to true) from build summary page and share it with us?

**Comment by jtbatzer** [comment]
@SatishThareja - I emailed the build agent logs and build logs from the summary page to devops_tools@microsoft.com.  Please confirm receipt.  Thanks!

**Comment by SatishThareja** [comment]
@jtbatzer Ack. Received the logs.

**Comment by jtbatzer** [comment]
Hi, Any update?  Thanks!

**Comment by SatishThareja** [comment]
Issue was due to default configuration missing for the projects and was resolved after a default config was added to the affected projects.

**Comment by jar240** [comment]
@SatishThareja could you add a little more background? While it's great that you answered, it doesn't seem to contain enough information to help others to "add a default config tot he project".
