### ISSUE TITLE
AzureRmWebAppDeployment failing to find package using a windows share

### ISSUE THREAD

**Issue by markphillips100** [Microsoft/vsts-tasks#2923]
A recent [change](https://github.com/Microsoft/vsts-tasks/pull/2571) to use a glob library for locating a package causes releases using a windows share to not be located (no feature for this in glob perhaps?).

The following used to work however the glob.sync will not match this.
\WINDOWSBUILD\B\myartifacts\myproduct\mypackage.zip

Can we have this fixed asap as it has broken numerous window agent release definitions.  For a quick workaround I've had to use an absolute local path with drive like the following but this assumes only the one agent building and releasing:
F:\BuildArtifacts\myartifacts\myproduct\mypackage.zip - note the double slash escaping to support glob again.

**Comment by Ajay-MS** [comment]
@markphillips100 

Thanks for reporting issue. I have created PR corresponding to solution to this issue and will be fixed soon.
[Window Shared Path Fix](https://github.com/Microsoft/vsts-tasks/pull/3014)

**Comment by KrishnaAdityaB** [comment]
#3014

**Comment by Ajay-MS** [comment]
@markphillips100 

PR corresponding to issue has been merged in master. Will be available with next deployment.
