### ISSUE TITLE
Upgrading Service Fabric applications now waits while each upgrade rolls to all nodes

### ISSUE THREAD

**Issue by rhan1161** [Microsoft/vsts-tasks#2929]
VSTS now upgrades SF applications in a "serialized" mode.  In the past, VSTS would upgrade one application on one node and then move on to the next application.  At the same time, Service Fabric then rolled the upgrades to the other nodes in the background.  After October 20, I noticed that VSTS doesn't do this anymore.  That is, VSTS upgrades one application on the first node, and then wait until the upgrade has rolled to the other nodes.  In my case, I have 5 nodes in my Service Fabric cluster.  Once the upgrade has rolled to all the nodes, then VSTS moves to upgrading the next application.  Consequently, this "serialized" upgrade process extends the upgrade time from 16 minutes to 1 hour and 40 minutes (in my case) and much longer if I have more than 5 nodes.

Is there a flag or setting that I use to get the previous behavior?

**Comment by rhan1161** [comment]
As an alternative to reduce the deployment time, can we set VSTS to deploy multiple applications to the SF cluster at the same time?  I can manually deploy multiple applications to SF cluster using Powershell so the cluster supports concurrent upgrades. Can VSTS do this?

**Comment by EricJizbaMSFT** [comment]
The non-"serialized" behavior you saw before was a bug - see #2654. The task _should_ wait so that you get accurate logs if the upgrade passed or failed. This fix just recently rolled out.

That being said, I see your desire for 'parallelized' deployments. The current task is only set up for one application at a time. I assume you have multiple tasks in one release definition (one for each application)?  I would suggest one release definition per application so that you can run multiple in parallel (although you would still be limited by the number of build agents you have).

Would you rather have speed than complete logs? If so, we could consider adding an option where the task kicks off a deployment and doesn't wait to see if it succeeds (the old behavior).

**Comment by rhan1161** [comment]
Thank you for the response.  I currently have 18 different applications to be deployed to multiple SF clusters and I put all 18 deployment tasks in one release definition.   I think creating one release definition per application is not practical and error prone, not to mention that I will have to build each application separately which will take longer than building all 18 applications using a single build definition.

I prefer speed than a single log file.  For development, testing, and production deployment, it is imperative that we reduce the deployment time.  Our deployment time has increased from 16 minutes to 1 hour 40 minutes and this time will just increase when I add more nodes to the cluster.  Regarding the log file, I'm ok with multiple log files (one per app).  So, yes, I'd like to have that option to have the old behavior.

**Comment by MikkelHegn** [comment]
Please reach out at mikhegn@microsoft.com to discuss the above scenario. I would like to know more in details of your setup. Thanks.

**Comment by MikkelHegn** [comment]
Hi rhan1161, we have no current plans to change the deploy task, but are happy to take in pull requests for additional / enhanced features. However, I would like your input if a generic Service Fabric PowerShell task, that takes any PowerShell script would be helpful in this scenario?

**Comment by rhan1161** [comment]
Hi Mikkel,
What would a generic SF Powershell task do?  Will it be able to run PowerShell script that requires administrator right for deploying a SF application?

**Comment by MikkelHegn** [comment]
Hi rhan1161

Sorry for being brief in the original comment - let me expand.

The hard part running a custom PowerShell script against a Service Fabric cluster in VSTS is authentication and connection to the cluster. The idea with the PowerShell for Service Fabric task is that you input a Cluster Connection as a Service Endpoint (like you do with the deployment task today) and then provide a script to run in the context of that connection. The service endpoint supports no-auth, certificate based auth and AAD auth.

Regarding admin rights, depending on what PS-commands you want to run against the cluster, you will need different level of permissions.

Be aware that the PS script will run on the VSTS agent, which has the Service Fabric cdmlets installed.

In your case, you could change the Deploy-FabricApplication.ps1 script and put it in your repo, and then run this script using this task.

**Comment by rhan1161** [comment]
As long as I can run the deployment scripts in VSTS and get the previous "parallelized" upgrade process, this will work well for me.

**Comment by mikanyg** [comment]
@MikkelHegn A Service Fabric PowerShell task is a very good idea. It removes the friction with authentication as you mention and enables advanced deployment pipelines using the SF PowerShell API.

**Comment by bishalpd** [comment]
@MikkelHegn now that service fabric powershell task is available, should we close this issue or are you considering adding option to support parallel deployment?

**Comment by rhan1161** [comment]
Does the new SF powershell task allow me to run the deployment scripts with Administrative rights?  I'm deploying/upgrading services to a secured SF environment?

**Comment by bishal-pdMSFT** [comment]
@rhan1161 SF powershell task allows you to connect to secure cluster using your credentials(cert based or AAD based) and then it runs PS commands under that connection context. Whether or not you can run admin commands depends on your connection context. So if you are using a administrator role to connect, you can run admin commands. See this [link ](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-cluster-security-roles)for RBAC

**Comment by bishal-pdMSFT** [comment]
@RoopeshNair

**Comment by MikkelHegn** [comment]
I suggest closing this issue.

**Comment by RoopeshNair** [comment]
@rhan1161 please suggest your ideas and vote on [UserVoice](https://visualstudio.uservoice.com/forums/330519-team-services/category/145269-release-management) closing the request
