### ISSUE TITLE
Sonar build for Visual studio post SonarQube upgrade

### ISSUE THREAD

**Issue by dpadhya1990** [Microsoft/vsts-tasks#2944]
Hello ,

Our sonar build (XAML build )  is getting failed after we upgrade our sonar server, e 
following are the error logs

Start Sonar-runner
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/sonar/api/utils/SonarException : Unsupported major.minor version 52.0
○at java.lang.ClassLoader.defineClass1(Native Method
○at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
○at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
○at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
○at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
○at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
○at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
○at java.security.AccessController.doPrivileged(Native Method)
○at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
○at org.sonar.runner.impl.IsolatedClassloader.loadClass(IsolatedClassloader.java:94)
○at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
○at java.lang.Class.getDeclaredMethods0(Native Method)
○at java.lang.Class.privateGetDeclaredMethods(Class.java:2531)
○at java.lang.Class.getMethod0(Class.java:2774)
○at java.lang.Class.getMethod(Class.java:1663)
○at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:85)
○at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
○at java.security.AccessController.doPrivileged(Native Method)
○at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
○at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
○at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
○at org.sonar.runner.api.Runner.execute(Runner.java:100)
○at org.sonar.runner.Main.executeTask(Main.java:70)
○at org.sonar.runner.Main.execute(Main.java:59)
○at org.sonar.runner.Main.main(Main.java:53)

Previous sonar version - 4.5.2 C# plugin 3.3 sonar runner 2.4
Current sonar version - 5.6.3 C# plugin 5.3.2 sonar runner 2.4 
Do we need to upgrade our sonar runner ? or do we need to change or edit sonar-project.properties file post upgrade
the build was running fine before, please advice 
Regards
Dushyant Padhya

**Comment by bgavrilMS** [comment]
Hi @dpadhya1990, 

This repo is for the TFS Build (i.e. non-XAML build) integration with SonarQube. Please contact SonarQube directly with this query. 

As far as I remember, you need to integrate using the SonarQube Scanner for MSBuild and not with the general purpose Sonar Scanner (formerly known as the sonar-runner). 

http://docs.sonarqube.org/display/SONARQUBE53/Analyzing+with+SonarQube+Scanner+for+MSBuild#AnalyzingwithSonarQubeScannerforMSBuild-tfs2013FromTeamFoundationServer2013(XAMLbuildsystem)
