### ISSUE TITLE
Azure CLI Preview task - 'C:\Program' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by mateusrodrigues** [Microsoft/vsts-tasks#2950]
The task seems to be throwing some kind of error due to the spaces in the command line that gets the console confused and throwing an "unknown command" error.

The log specifically says:

> 2016-10-26T02:25:53.1597767Z ##[section]Starting: Swap Deployment Slots
> 2016-10-26T02:25:53.1887934Z ==============================================================================
> 2016-10-26T02:25:53.1887934Z Task         : Azure CLI Preview
> 2016-10-26T02:25:53.1887934Z Description  : Run a Shell or Batch script with Azure CLI commands against an azure subscription
> 2016-10-26T02:25:53.1887934Z Version      : 0.2.3
> 2016-10-26T02:25:53.1887934Z Author       : Microsoft Corporation
> 2016-10-26T02:25:53.1887934Z Help         : [More Information](http://go.microsoft.com/fwlink/?LinkID=827160)
> 2016-10-26T02:25:53.1897762Z ==============================================================================
> 2016-10-26T02:25:54.2670023Z _'guid suppressed for security reasons'_ exists true
> 2016-10-26T02:25:54.2870020Z [command]C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin\azure.cmd config mode arm
> 2016-10-26T02:26:28.5434619Z Microsoft Azure CLI would like to collect data about how users use CLI
> 2016-10-26T02:26:28.5434619Z commands and some problems they encounter.  Microsoft uses this information
> 2016-10-26T02:26:28.5434619Z to improve our CLI commands.  Participation is voluntary and when you
> 2016-10-26T02:26:28.5434619Z choose to participate your device automatically sends information to
> 2016-10-26T02:26:28.5434619Z Microsoft about how you use Azure CLI. 
> 2016-10-26T02:26:28.5434619Z 
> 2016-10-26T02:26:28.5434619Z If you choose to participate, you can stop at any time later by using Azure
> 2016-10-26T02:26:28.5434619Z CLI as follows: 
> 2016-10-26T02:26:28.5434619Z 1.  Use the azure telemetry command to turn the feature Off. 
> 2016-10-26T02:26:28.5434619Z To disable data collection, execute: azure telemetry --disable
> 2016-10-26T02:26:28.5434619Z 
> 2016-10-26T02:26:28.5434619Z If you choose to not participate, you can enable at any time later by using
> 2016-10-26T02:26:28.5434619Z Azure CLI as follows: 
> 2016-10-26T02:26:28.5434619Z 1.  Use the azure telemetry command to turn the feature On. 
> 2016-10-26T02:26:28.5434619Z To enable data collection, execute: azure telemetry --enable
> 2016-10-26T02:26:28.5434619Z 
> 2016-10-26T02:26:28.5434619Z Select y to enable data collection :(y/n) 
> 2016-10-26T02:26:28.5434619Z You choose not to participate in Microsoft Azure CLI data collection.
> 2016-10-26T02:26:28.5434619Z 
> 2016-10-26T02:26:28.5434619Z 
> 2016-10-26T02:26:28.5434619Z [32minfo[39m:    Executing command [1mconfig mode[22m
> 2016-10-26T02:26:28.5444617Z [32minfo[39m:    New mode is arm
> 2016-10-26T02:26:28.5444617Z [32minfo[39m:    [1mconfig mode[22m command [1m[32mOK[39m[22m
> 2016-10-26T02:26:28.5484619Z [command]C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin\azure.cmd login -u ******** -p ******** --tenant ******** --service-principal
> 2016-10-26T02:26:30.3302544Z [32minfo[39m:    Executing command [1mlogin[22m
> 2016-10-26T02:26:30.3302544Z [32minfo[39m:    Authenticating...
> 2016-10-26T02:26:30.3302544Z [32minfo[39m:    Added subscription Visual Studio Enterprise: BizSpark
> 2016-10-26T02:26:30.3302544Z [32minfo[39m:    Setting subscription "Visual Studio Enterprise: BizSpark" as default
> 2016-10-26T02:26:30.3302544Z [32minfo[39m:    [1mlogin[22m command [1m[32mOK[39m[22m
> **2016-10-26T02:26:30.3382529Z [command]C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin\azure.cmd account set Visual Studio Enterprise: BizSpark
> 2016-10-26T02:26:30.3432534Z 'C:\Program' is not recognized as an internal or external command,
> 2016-10-26T02:26:30.3432534Z operable program or batch file.**
> **2016-10-26T02:26:30.3462536Z [command]C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin\azure.cmd account clear -s Visual Studio Enterprise: BizSpark
> 2016-10-26T02:26:30.3522552Z 'C:\Program' is not recognized as an internal or external command,
> 2016-10-26T02:26:30.3522552Z operable program or batch file.**
> 2016-10-26T02:26:30.3602533Z ##[error]Script failed with error: 'C:\Program' is not recognized as an internal or external command,
> 2016-10-26T02:26:30.3602533Z operable program or batch file.
> 2016-10-26T02:26:30.3602533Z 
> 2016-10-26T02:26:30.3622619Z operable program or batch file.
> 2016-10-26T02:26:30.3622619Z 
> 2016-10-26T02:26:30.3672613Z ##[section]Finishing: Swap Deployment Slots

**Comment by ericsciple** [comment]
@mateusrodrigues does one of your args have a space in it? if so, any way to avoid an arg it a space in it? or put the cmd file in a location that does not have a space in the path?

**Comment by ericsciple** [comment]
@hiyadav 
it looks like this line is the issue `C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\wbin\azure.cmd account set Visual Studio Enterprise: BizSpark`. i'm guessing `Visual Studio Enterprise: BizSpark` is actually quoted on the CreateProcess cmdline.

there is a really bizarre quirk when creating a process for a cmd file on Windows and the file has a space in the path and a quoted arg is passed. i'm working on wrapping up a PR to conveniently handle it in toolrunner. i'm hoping to wrap up the PR soon (tomorrow?). https://github.com/Microsoft/vsts-task-lib/pull/157

**Comment by hiyadav** [comment]
@ericsciple 
yeah the argument "Visual Studio Enterprise: BizSpark" is quoted when passed to the command line. This seems like the same issue as in the PR, so can I assign the issue to you ?

**Comment by ericsciple** [comment]
I'm not going to modify the Azure CLI task. If you want to wait for my changes to toolrunner, then you can. I'm planning to wrap up those changes soon (probably tomorrow). If this is a super urgent bug and you need to release a fix or workaround sooner than that, then don't wait on my change.

**Comment by ericsciple** [comment]
if you do need an urgent workaround and you know you are always executing a cmd/bat file on windows, [this is a workaround](https://nodejs.org/api/child_process.html#child_process_spawning_bat_and_cmd_files_on_windows)

**Comment by hiyadav** [comment]
hey, we are waiting for your changes to go in, have already verified, the task works fine with your changes even with arguments having spaces in them and also the file path having spaces in them.

**Comment by mateusrodrigues** [comment]
@ericsciple @hiyadav no hurries with that one, just making sure you guys knew about it :) when is the fix expected to roll in?

**Comment by ericsciple** [comment]
If it goes into this sprint (normal checkin process cutoff is friday), then it will start rolling out next week and continue for a week or so until the deployment reaches all scale units.

If you want a fix before, then after it goes into master I can get you a private build (or you can build it from this repo) and you can upload it to your account.

**Comment by mateusrodrigues** [comment]
@ericsciple all good, I can wait for it to release. Let me go ahead and close this issue, once it's been solved :) thanks, guys!

**Comment by ericsciple** [comment]
fyi i'm still working on the lib changes. i had a setback at home and lost a day. i have some more test cases to added, but the PR is really close. i'm hoping to finish test cases today or tomorrow.

**Comment by mateusrodrigues** [comment]
@ericsciple all good 👍

**Comment by ericsciple** [comment]
@hiyadav fixed in task-lib 1.0.0
