### ISSUE TITLE
Control Progressive Test Results updates in Test Runs.

### ISSUE THREAD

**Issue by AmaranAthigaman** [Microsoft/vsts-tasks#2952]
Hi All,

I have a query related to test execution through VSO build Task.

I see the below logs while I am executing the tests from the VSO build Tasks. The batch size here is showing as 1000. Is there a way i can change this batch size so that the test results are updated in the test run more frequently?

I, 4704, 22, 2016/10/25, 17:55:08.630, \DTAExecutionHost, TcmRestApiHelper.UpdateTestResultsToTestRun : Starting update in batches of 1000. Total batches : 1
V, 4704, 22, 2016/10/25, 17:55:08.630, \DTAExecutionHost, TcmRestApiHelper.ProcessResultsInBatches : Updating a batch of test results on tcm. Processing batch 1 of 1...

Thanks,
Amaran. A.

**Comment by atinb** [comment]
@AmaranAthigaman The publishing of results is done at the end of the set of tests given to the machine to execute. With Visual Studio Test task, that means you only see results at the end of all the tests being run. For Run Functional Test task that distributes tests, it means results are uploaded once the tests being executed on a particular machine are finished execution.
