### ISSUE TITLE
Extract Files Task when used as a Release Task fails 

### ISSUE THREAD

**Issue by optiks** [Microsoft/vsts-tasks#2957]
See comments within https://connect.microsoft.com/VisualStudio/feedback/details/3109092/extract-files-task-when-used-as-a-release-task-fails.

"Trying to use the extract files task (https://www.visualstudio.com/en-us/docs/build/steps/utility/extract-files) fails with the error:

TypeError: path must be a string
No path specified for search pattern: **\*.zip defaulting to: undefined
Searching for: **\*.zip under directory: undefined
##[error]path must be a string

Note that this task is defined as a Utility task, *not* as a build-specific task. 

The documentation states the following, however the design of the task is flawed in my opinion: 
"The archives you want to extract. The default file path is relative from the root folder of the repo (same as if you had specified $(Build.SourcesDirectory))."

As a workaround, a release variable Build.SourcesDirectory can be created with value $(System.DefaultWorkingDirectory)."

The assumption is that the extract files task (https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/ExtractFiles/extractfilestask.ts) always has the 'build.sourcesDirectory' variable available, which is not the case when using the task as a release task. 

My suggestion would be that the source folder should be configurable and exposed through the task as a parameter.

**Comment by DavidStaheli** [comment]
Apologies for the trouble this caused you, @optiks.  Thanks for the great investigation.  This is fixed via pull request #2974, which applies this fix to Extract Files, Archive Files, Gradle, Maven, and Decrypt File.
