### ISSUE TITLE
Xamarin.iOS task started failing few days ago

### ISSUE THREAD

**Issue by khymenko** [Microsoft/vsts-tasks#2963]
We have a build for our app setup in Team Services. It is configured to build both iOS and Android version of our Xamarin-based app on a Mac. It was working fine for several month. But suddenly iOS step started failing with following error:
XamariniOS task failed with error Error: Failed cd: cd: no such file or directory: /Users/scanco/Agent/Work/8/b/iOS

To make sure this is not an issue with our project sources or properties I've setup a build for one of our sample apps. It has exactly same issue.

Looks like this is an issue in build agent itself. As I understand directory "b" is to hold binaries produced by the build and directory "iOS" is hold binaries specific to Xamarin.iOS build step.

Any advice that is happening?

I thought updating build agent could help, but there is no manual update as far as I understand. Although it should update itself automatically I'm not sure if we have latest version or not. Our current version is 2.105.6

I attach log from TFS build.
[1_Build.txt](https://github.com/Microsoft/vsts-tasks/files/555931/1_Build.txt)

**Comment by madhurig** [comment]
@khymenko : Can you check what you have set in the Xamarin iOS task for Working directory? The latest version of the agent is 2.108 but your version should work too.

**Comment by khymenko** [comment]
Thanks, @madhurig. After cleaning working directory build is running again :)
