### ISSUE TITLE
TFS2015 Coded UI testing fails in build process, can't load assembly

### ISSUE THREAD

**Issue by RuslKoval** [Microsoft/vsts-tasks#2965]
Hi,
I can't run Coded UI testing in build process on TFS2015.
I get "DistributedTests: Error : Could not load file or assembly" (see screenshot)
![build_error](https://cloud.githubusercontent.com/assets/23101758/19775327/bead556e-9c78-11e6-841c-fa08afd11d75.png)
It's strange, becouse I can run same .dll on the same machine in VS2015 and it works.
I think something is wrong with testagent, although testagent deployment step finished successfully, but on different test machines I get the same crash of DTAExecutionHost.exe after machine's reboot like here https://github.com/Microsoft/vsts-tasks/issues/2213 and patch doesn't help me. I resolved crash by replacing DtaExecutionHost.exe with this https://1drv.ms/u/s!Aj_8waqf3hLypyxtiQw9DoD6PG5E like here https://github.com/Microsoft/vsts-tasks/issues/2809 , but it didn't help with testing in build.
Could you help me to solve this issue, plz? Thanks!

**Comment by acesiddhu** [comment]
@RuslKoval Can you run ildasm on the test dll and check all reference needed for this dll in the manifest? Are all references there on the machine?

**Comment by RuslKoval** [comment]
so fast response, cool) I'v sent logs by mail to devops_tools@microsoft.com
and yes, we checked all references are there on the machine

**Comment by RuslKoval** [comment]
and can it be for the same .dll is needed different references when executing by Visual Studio or testagent?

**Comment by acesiddhu** [comment]
Can you send us Manifest to devops_tools@microsoft.com?

**Comment by acesiddhu** [comment]
one more thing. is this dll build on 64 bit platform and the machine where test agent is installed in a 32 bit machine or vice versa?

**Comment by SatishThareja** [comment]
@RuslKoval Can you try executing the tests manually from the comandline using vstest console command and share the results with us?

The path to vstest console will look something like: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe".

**Comment by RuslKoval** [comment]
@SatishThareja , I'v just run my .dll from cmd, as You said, and it works!

**Comment by RuslKoval** [comment]
I sent a mail  to devops_tools@microsoft.com with my test .dll, Manifest and GAC-file

**Comment by RuslKoval** [comment]
Is there any news for me?

**Comment by acesiddhu** [comment]
@ruslkoval the attachment was removed. Can u zip it again and rename .zip to something else and send it over again.

**Comment by RuslKoval** [comment]
@acesiddhu , I'v sent you logs again. Just say if you need something else.

**Comment by acesiddhu** [comment]
The attachments are getting removed. So I will start by running vstest.console.exe on the same test agent machine where you are seeing the error. Do you see the same error?

C:\program files (x86)\microsoft visual studio 14.0\common7\ide\commonextensions\microsoft\testwindow\vstest.console.exe <test dll path>

**Comment by RuslKoval** [comment]
I sent you a link, where you can download all information you need

**Comment by RuslKoval** [comment]
@acesiddhu, I didn't understand your last comment

**Comment by RuslKoval** [comment]
It seems I found a reason of failing of my test. As You can see on the 1st screenshot, test agent tries to run .dll from shared path and then fails. I placed .dll to the test machine by path d:\folder and wrote this path as "Test Drop Location" and now it works! As workaround, I'll add additional step to my build definition to copy tests .dll-files from build drop location to the test machine. But it's strange that test agent can't load tests from shared folder.

**Comment by acesiddhu** [comment]
It is not a test agent limitation. This is how .net works. Even if you try to load the dll from network share in a console app this will happen. I guess there is some policy or OS restriction. See this blog http://www.clearmindsoftware.com/post/Resolution-Error-Could-not-load-file-or-assembly-file5c5cserver5cpath5cfiledll-or-one-of-its-dependencies-(0x80131515)

I will close the issue. Thanks
