### ISSUE TITLE
Task.json input type of password

### ISSUE THREAD

**Issue by jakebair** [Microsoft/vsts-tasks#2967]
Is there a way to specify an input to be a secured field (masks the input)?

```
{
   "name": "password",
   "type": "password",
   "label": "Password",
   "defaultValue": "",
   "required": true
}
```
![image](https://cloud.githubusercontent.com/assets/6116637/19783038/98401040-9c4d-11e6-95eb-33ab4bc5b696.png)

**Comment by bryanmacfarlane** [comment]
Nope.  Because that would encourage folks to enter passwords in an input field.  Instead, they should enter in variables, tick the lock to secure it and reference it in the input field via $(varname).  There's UX discussions going on for how to automate that a bit (present the lock next to input and it does what I just described behind the scenes).

Variables that are secrets get encrypted and stored securely.

**Comment by jakebair** [comment]
Well, that presents an interesting dilemma for my purpose, I want to have multiple build steps that all use the same build task, but have different usernames/passwords. If I use variables, then they would all have the same name.

I thought of a solution, I could have an input for the variable name that your would then have point to the secured variable for that build step. Not perfect but would work for me.

I still think that UX should figure out how to have secured inputs for build tasks.

**Comment by bryanmacfarlane** [comment]
Understood.  

Can you have a variable per instance of input?  e.g. task.foo.password, task.bar.password etc...?

**Comment by jakebair** [comment]
considering it would be a repeated build step, I'm not sure how to do that.

**Comment by bryanmacfarlane** [comment]
Process:
Step1: FooTask, input password=$(foo1.password)
Step2: FooTask, input password=$(foo2.password)

Variables:
foo1.password=apassword (lock)
foo2.password=diffpassword (lock)

??

**Comment by emre-aki** [comment]
Hey @bryanmacfarlane,

> **_Variables that are secrets get encrypted and stored securely._**

As for _that_, how shall one read these variables from a PowerShell script? Is doing a `$env:<variable_name>`going to return a `string`, or something like `System.Security.SecureString`? I need to be able to use that secret variable in a `.ps1` file.
