### ISSUE TITLE
VSTest cannot be run in a release definitions

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/vsts-tasks#2976]
The VSTest task cannot be run in a release definition because it uses an environment variable that is only available in builds:

**vstest.ts line 42:**
`var sourcesDir = tl.getVariable('build.sourcesdirectory');`

Instead of `Build.SourcesDirectory`, it should use `System.DefaultWorkingDirectory` which contains the same value as `Build.SourcesDirectory` but works in both Build and Release.

**Comment by nigurr** [comment]
https://github.com/Microsoft/vsts-tasks/pull/2994 will be fixed in this

**Comment by nigurr** [comment]
This is handled already https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VsTest/vstest.ts#L67
