### ISSUE TITLE
[feature request] service-fabric-versioning task to replace version numbers in manifests

### ISSUE THREAD

**Issue by mikanyg** [Microsoft/vsts-tasks#2977]
The current usage of the service-fabric-versioning task will only append a unique version number to service fabric applications. This makes the Continouos Delivery scenario for SF applications easy to implement, but forces a certain versioning scheme, making it harder to combine it with Semantic Versioning and the Git Version build task.

I would like the option to simply replace the version numbers in the manifest files.

I really like the current ability to detect changes in services by comparing against earlier builds, but would like the freedom of replacing a version number like you can in this 3rd party build/release extension: https://github.com/colindembovsky/cols-agent-tasks/tree/master/Tasks/VersionAssemblies

**Comment by EricJizbaMSFT** [comment]
Dupe of #2377 

The fix should have been deployed to almost everyone at this point. Check your versioning task to see if a 'Version Behavior' option exists. Re-open if you're still having issues
