### ISSUE TITLE
Multiple task inputs

### ISSUE THREAD

**Issue by yigaldviri** [Microsoft/vsts-tasks#2980]
Hi, I'm trying to create a task that uses an input that may repeat itself several times dynamically. Each time the user enters such an input I will add another field (of the same type) to the task.
So actually i'm talking about the possibility of "n" inputs of some type.
Is there a way to create such inputs (kind of a dynamic array of inputs) in the task.json file?

**Comment by ericsciple** [comment]
the only mechanism today is visibility rules. would that enable your scenario? here is an [example](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/MSBuild/task.json#L123)

**Comment by yigaldviri** [comment]
That won't help me because the visibility rule will only apply to a fixed number of inputs and I wont "n" inputs. 
Thanks anyway.

**Comment by bryanmacfarlane** [comment]
We have a task type of dictionary (table) on the backlog.  That might help.

**Comment by bryanmacfarlane** [comment]
Closing since we don't track backlog here.

**Comment by kumarkpsaravana** [comment]
@bryanmacfarlane can we have the dictionary type of input for a task now?
