### ISSUE TITLE
Question: Can't create a task group containing Service Fabric deployment tasks

### ISSUE THREAD

**Issue by rhan1161** [Microsoft/vsts-tasks#2981]
I have a release definition that contains multiple Service Fabric (SF) deployment tasks.  I would like to group all the SF deployment tasks in one task group so I can create more release definitions for other SF clusters.  SF deployment task, however, requires a cluster connection name which cannot be externalized into a variable.  Is there plan to resolve this issue?  Or is there a different way to create the task group that contains SF deployment tasks?

**Comment by rhan1161** [comment]
I didn't think that this was a Service Fabric issue.  It's a feature request for VSTS to parameterize service endpoints.

**Comment by shashban** [comment]
@rhan1161 - You're right. VSTS task groups do not support parameterization of endpoints. We have it in our backlog but can't commit to exact timelines as yet. Unfortunately, I can't offer a workaround either.
