### ISSUE TITLE
[Feature request] Make $(Build.SourceVersion) to have "All" scope

### ISSUE THREAD

**Issue by rhan1161** [Microsoft/vsts-tasks#2982]
I am using $(Build.SourceVersion) as part of my build number so I can easily pick the builds just by looking at the changeset numbers when I'm deploying build.  However,  $(Build.SourceVersion) is only populated when the build is started from CI.  If I start the build manually and not specify the changeset number, the build will automatically build the latest changeset but $(Build.SourceVersion) is blank.  So now my builds do not have consistent naming... the CI builds include changeset numbers and the manual builds do not.  I think this is an inconsistent behavior.
$(Build.SourceVersion) currently has an "Agent" scope, instead of "All" scope, unless the build is started from CI.  I'd like to request to have $(Build.SourceVersion) to be set before the manual build is started so I can use it a part of the build number.

**Comment by ericsciple** [comment]
@chrisrpatterson fyi

closing the issue here since it isn't an issue with this repo. i'll send an email to chris as well
