### ISSUE TITLE
What is the correct way to debug your scripts in PowerShellOnTargetMachines?

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-tasks#2983]
I have a series of Powershell modules that I am executing with PowerShellOnTargetMachines.

I am trying to see the debug statements within the VSTS build log, but I am having a real hard time getting them to come through.

I understand that **Write-Host** is not recommended for automation, so my question is, what should I use?  I have tried **Write-Debug**, **Write-Verbose** and made sure the preferences are set right.  But when I call a function from the main script all my logging disappears.  The only output I can get to appear is **Write-Output** from the top most script.  I obviously can't use **Write-Output** from called functions as they may return a value.

This is possibly a more generic powershell question, but I am wondering if there are any best practices for use with this task?

**Comment by bryanmacfarlane** [comment]
Question likely more appropriate on this repo: https://github.com/Microsoft/vsts-task-lib

**Comment by ericsciple** [comment]
@chshrikh may be able to help redirect to folks who own this task. Owners of this task may have better suggestions.

I dont know the full details of the task implementation, but *I think* this is how powershell remoting works - only the output pipeline and error pipeline come back across the wire. One thing that may work is wrap the contents of your target script inside a script block, and then redirect the pipelines. E.g. something like this might work to force the warning/verbose/debug pipelines into the output pipeline
```powershell
. {
[...]
} 2>&1 3>&1 4>&1 5>&1 |
    ForEach-Object {
        if ($_ -is [[System.Management.Automation.ErrorRecord]) {
            $_
        } else {
            ,$_ | Out-String
        }
    }
```

**Comment by gregpakes** [comment]
@ericsciple Thanks for your input.  When I do my own PS remoting, I get all the output sent back to the host.  When I use this task, I only get "Write-Output" from the top most page.

**Comment by ericsciple** [comment]
have you tried setting a variable system.debug to true on the definition. typically in the ps tasks, verbosepreference is set to continue only when that var is set.

**Comment by gregpakes** [comment]
Yep - I've set system,debug and I've set VerbosePreference and DebugPreference to Continue.

**Comment by KrishnaAdityaB** [comment]
@gregpakes 
What are the versions of agent and PowerShell on Target Machines task you have?

I am able to get the logs when I tried with agent version 2.109.1,  task version 1.0.43. Below are the sripts

**verboseModule.psm1**
```
function moduleFunction() {
    Write-Verbose "inside module function"
}
```

**script.ps1**
```
Write-Verbose "inside parent file" -Verbose

Import-Module $PSScriptRoot/verboseModule.psm1
moduleFunction
```

**output**
```
	 Deployment started on target machine...

inside parent file

Loading module from path 'C:\temp\scripts\verboseModule.psm1'.

Exporting function 'moduleFunction'.

Importing function 'moduleFunction'.

inside module function
```

**Comment by gregpakes** [comment]
@KrishnaAdityaB 

I am using TFS "15" RC2.

The agent is 2.105.6.  I 'm afraid I don't know how to check the inbuilt task versions.

**Comment by KrishnaAdityaB** [comment]
@gregpakes 
I am able to get the logs with TFS "15" RC2 and agent 2.105.6 too.

My PS version on both agent and target machines is 4.0. Can you provide me yours?

Can you start with simple sample scripts I provided earlier - and check if you are getting logs in your environment?

**Comment by KrishnaAdityaB** [comment]
@gregpakes 
Reg: Difference between download and installed and those just on disk
Can you quickly try with your scripts just on disk?

This along with executing simple scripts should help us narrow down the issue to either _the way they are get_ or _to something in your script_.

**Comment by KrishnaAdityaB** [comment]
@gregpakes 
did you get a chance to experiment? any findings?

**Comment by KrishnaAdityaB** [comment]
I will be out of office for 2 weeks. Including @chshrikh and @rajatagrawal-dev

**Comment by haydenhancock** [comment]
I am having the same issue. My build task copies over the script to the server and then I use the PowerShell on Target Machines tasks to execute the script. The script executes fine, however, nothing is written to the build log. Specifically, I am using Write-Verbose. The server has PowerShell 5.1.14339.206 installed.

When testing the script directly on the server I discovered:
- Write-Verbose would only work in a conditional statement if I set the -Verbose option
- Write-Verbose would work as expected outside of a conditional statement

When testing the script using VSTS I discovered:
- Write-Verbose would never work in a conditional statement, even if I set the -Verbose option
- Write-Verbose would work as expected outside of a conditional statement

**Comment by chshrikh** [comment]
@haydenhancock could you please try a simple script something like - 
write-verbose "Hi there without verbose"

the build should show logs something like - 

==============================================================================
Task         : PowerShell on Target Machines
Description  : Execute PowerShell scripts on remote machine(s)
Version      : 1.0.43
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=627414)
==============================================================================
Preparing task execution handler.
Executing the powershell script: C:\Agents\t2\vstsagent\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\1.0.43\PowerShellOnTargetMachines.ps1
Deployment started for machine: '<my machine with port>'
	 Deployment started on target machine...
Hi there without verbose
Deployment status for machine '<my machine with port>' : 'Passed'


Also can you share what is the Powershell version on target box

**Comment by haydenhancock** [comment]
@chshrikh As I mentioned, Write-Verbose works correctly outside of a conditional statement. I read up a bit more on these cmdlets and determined that I must set the $VerbosePreference variable to "Continue" in the script in order to get anything passed to the build log.

**Comment by chshrikh** [comment]
@haydenhancock  thanks for update. I hope you got unblocked on this.

**Comment by haydenhancock** [comment]
@chshrikh No problem. It helps if you read the documentation.
