### ISSUE TITLE
[Feature request] ServiceFabricDeploy control OverwriteBehavior from task 

### ISSUE THREAD

**Issue by mikanyg** [Microsoft/vsts-tasks#2984]
I would like the option to manual set the OverwriteBehavior of Publish-NewServiceFabricApplication so I can control the scenario where removing existing application and replace with a new application package disregarding versionnumbers.

Basically I want to control the value of -OverwriteBehavior as seen in this line: https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/ServiceFabricDeploy/deploy.ps1#L166

ATM this can be achieved from the Deploy-FabricApplication.ps1 that is created along with the Service Fabric application template in VS, but not through the ServiceFabricDeploy VSTS task.

**Comment by MikkelHegn** [comment]
Hi mikanyg, we have no current plans to change the deploy task, but are happy to take in pull requests for additional / enhanced features.

**Comment by mikanyg** [comment]
@MikkelHegn what is the expected timeline for having a PR reviewed?

**Comment by MikkelHegn** [comment]
@ericsciple Do you know the timeline for PR reviews?

**Comment by MikkelHegn** [comment]
I'm sure he refers to this: https://github.com/Microsoft/vsts-tasks/pull/3382 :-)

**Comment by ericsciple** [comment]
For this task, I would think the decision would come down to a decision between you and Muthu (or the PM on Muthu's team - Gopi might be the right contact?)

**Comment by MikkelHegn** [comment]
@mikanyg: As you can see we are learning the process of getting your PR approved as we go along - thanks for pushing us down this path - you changes will merge very soon...

**Comment by mikanyg** [comment]
Sure no problem. Been pushing you all since May 2016 when I firstsuggested the SF deploy task over on user voice. Great to see it getting better and better.

**Comment by MikkelHegn** [comment]
Completed merge: https://github.com/Microsoft/vsts-tasks/pull/3382
