### ISSUE TITLE
Gradle build task use outdated libraries, unable to upgrade directly

### ISSUE THREAD

**Issue by gedeh** [Microsoft/vsts-tasks#2986]
When building Android app with latest SDK, support, and Google services, task gradle:assemble with latest gradle wrapper will fail to upgrade the SDK in hosted build agent.

1. Unable to download due to missing accepted licences of SDK components
2. Unable to update due to agent account restriction (moving downloaded updates into hosted agent SDK is failing)

My workaround to allow me build Android with latest SDK components:
1. PowerShell task to download SDK zip to Build.SourcesDirectory
2. PowerShell task to extract the SDK zip
3. PowerShell task to upgrade the SDK components
4. Copy licenses to SDK from repository
5. Create local.properties to make gradle task use downloaded SDK instead of ones provided in hosted machine

**Comment by gedeh** [comment]
More information:
Gradle version: 2.14.1

Error message on issue #1:
You have not accepted license agreement of the following SDK components:
[Google Repository, Android Support Repository, SDK Patch Applier v1]
Workaround:
Commit accepted licences locally to repository then using Copy files tasks to $(AndroidSDK)/licenses directory

Error message on issue #2:
Warning: an error occurred during installation: Failed to move away or delete existing target file
Workaround: As described in issue details

**Comment by madhurig** [comment]
@gedeh: We normally see the "Not accepted license agreement" error when the required Android SDK or build tools or SDK components are not already installed on the hosted build VMs. Updating the SDK has helped resolve the issue for other customers. Which version of Android SDK are you using? Do you still need the workaround?

Thanks,
Madhuri

**Comment by gedeh** [comment]
Hi @madhurig, thanks for your reply. Yes when this issue is raised the SDK components are not yet updated in hosted build VM as mentioned in my issue above. I am always try to use latest SDK and tools on my project. The main idea of the issue was if customer needs newer SDK than what installed in hosted build machine, the build should able to update to requested version seamlessly without have to use mentioned workaround, if possible.

I will try to modify my build to skip the workaround and believe it will work if hosted agent has the version. But I think will fail again once I update the components.

Thanks

**Comment by madhurig** [comment]
@gedeh: The issue with automatically updating the requested version is the license agreement. We need a way for the user to agree to installing new components on the VM during their build. The amount of time it takes to download the component would also be a concern on hosted build. It will be a good enhancement.

**Comment by gedeh** [comment]
@madhurig yes I agree if it should be classified as enhancement as not everyone might happy with auto downloading latest SDK components which consumes their hosted build agent build time resource. Also, there might be a concern about each of introduced license agreements.

I am happy if you decided to close this issue or leave it as is as enhancement request.

Thanks! :1st_place_medal:

**Comment by dozgunyal** [comment]
Hi @gedeh , may i ask you to share your scripts here to help us until this issue is resolved?

**Comment by gedeh** [comment]
Hi @dozgunyal, sorry being away lately, will attach the script soon tonight. Thanks!

**Comment by gedeh** [comment]
hi @dozgunyal,

My build tasks to download, extract, update, and accept SDK licenses scripts content are inline:

**PowerShell: Download Android SDK to sources directory**
`$url = "https://dl.google.com/android/android-sdk_r24.4.1-windows.zip"`
`$output = "$(Build.SourcesDirectory)\android-sdk_r24.4.1-windows.zip"`
`Write-Host "Download '$url' to '$output'"`
`$wc = New-Object System.Net.WebClient`
`$wc.DownloadFile($url, $output)`

**Extract file: Extract the downloaded SDK zip file**
`Archive file patterns: android-sdk_r24.4.1-windows.zip`
`Destination folder: $(Build.SourcesDirectory)`

**PowerShell: Create local.properties file so the build will use downloaded SDK**
`$sdkLocation = "$(Build.SourcesDirectory)\android-sdk-windows"`
`$sdkLocation = $sdkLocation.Replace("\","\\").Replace(":", "\:")`
`$content = "sdk.dir=$sdkLocation"`
`$file = "$(Build.SourcesDirectory)\local.properties"`
`Write-Host "Create file '$file' with content '$content'"`
`$content | Set-Content "$file"`

**Run cmd: Update local Android SDK**
`echo y | $(Build.SourcesDirectory)\android-sdk-windows\tools\android.bat update sdk --no-ui --all --filter tools,platform-tools,extra-google-m2repository,extra-google-google_play_services,extra-android-support`

**Copy files: Copy accepted local build Android SDK licenses**
`Source: $(Build.SourcesDirectory)\android-licenses\**`
`Target: $(Build.SourcesDirectory)\android-sdk-windows\licenses`
_note that I have the accepted license files in my code repository_

Then after SDK is in place, you can run gradle tasks to build, test, etc. If you need clarification of above script please shout, I am happy to help :)

Thanks,
Hendra

**Comment by DavizOWNS** [comment]
thanks @gedeh 
I am interested where did you find that link to download android SDK (https://dl.google.com/android/android-sdk_r24.4.1-windows.zip). I would like to know it in case I need to download different version.

**Comment by gedeh** [comment]
Hi @DavizOWNS,

I get the link from Android SDK Manager window. See the details in Android SDK Manager Log window

**Comment by madhurig** [comment]
We are moving to a monthly cadence with image updates which alleviates this problem partly, we don't plan to add a feature in the Gradle task.
