### ISSUE TITLE
'Active Directory Password' in SqlAzureDacpacDeployment Task

### ISSUE THREAD

**Issue by ogoodwin** [Microsoft/vsts-tasks#2987]
Is there currently a way to use 'Active Directory Password' authentication with the SqlAzureDacpacDeployment task for dacpac deployment? I have tried specifying this in the TargetConnectionString parameter but this fails because the task is already using other 'target' parameters like TargetDatabaseName, TargetUser, and TargetPassword which cannot be used at the same time as TargetConnectionString. I noticed in the source that a connection string can be used if the targetMethod is set to 'connectionString' (Utility.ps1 line 167) but it looks like targetMethod is always set to 'server'. 

Thanks,

**Comment by Ajay-MS** [comment]
@ogoodwin 

Yes, you are right currently target method is set to 'Server' only for "SQL Azure Dacpac Deployment" task. Target method "connection string" is not being supported yet. I am marking it as enhancement and after a discussion with PM will take it as a feature.

**Comment by RoopeshNair** [comment]
@ogoodwin we have added to our backlog to support connection string as an option to connect to DB. However it will take a while before we can get to it. (2-3months).

Thanks

**Comment by AlexKeySmith** [comment]
Hi, was there any progress made in the end?

It would be great not to even need to specify a password and have the VSTS deployment service principal be the admin of the database server.

**Comment by RoopeshNair** [comment]
@AlexKeySmith 

Unfortunately, we haven't been able to get to this. Currently working on few high priority items. 
We do encourage contributions, if you are willing to share it would be awesome and other users can benefit as well.

Thanks,
Roopesh Nair
