### ISSUE TITLE
DacPac Deploy Task does not log stderr to Build/Release Log

### ISSUE THREAD

**Issue by colindembovsky** [Microsoft/vsts-tasks#3002]
When using the DacPac Deploy Task, I can see what looks like stdout in the build/release log. However, if the dacpac deployment fails, the stderr output does not appear in the build/release log. I do see:

```
Initializing deployment (Start)
Initializing deployment (Failed)

##[error]
ErrorRecord : *** Could not deploy package.
```

However, running the same command in a console gives the actual error (like incorrect SQL version or whatever). It would be great if the stderr was put onto the build/release logs so that we can see error details.

**Comment by nickeyyan** [comment]
@KrishnaAdityaB Since my team has used VSTS to do our deployment and we have many databases. If the deployment failed without detail log, we have to spend a lot of time on investigating. Please fix this issue ASAP. Thanks a lot.

**Comment by KrishnaAdityaB** [comment]
[SQL Server Database Deploy](https://github.com/Microsoft/vsts-tasks/blob/releases/m109/Tasks/SqlServerDacpacDeployment/task.json) task in this repo is deprecated. Please use the [WinRM - SQL Server DB Deployment](https://github.com/Microsoft/vsts-rm-extensions/tree/master/Extensions/IISWebAppDeploy/Src/Tasks/SqlDacpacDeploy) task from [this extension](https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.iiswebapp).

This issue has been moved to the new task's repo https://github.com/Microsoft/vsts-rm-extensions/issues/147
