### ISSUE TITLE
Password with $ sign not handled correctly in PS

### ISSUE THREAD

**Issue by don18** [Microsoft/vsts-tasks#3007]
Hi,

We have passwords that include a $ sign. 
The password is added as variable in a builddefinition.
When the password is passed to the PowerShell script it is edited after the $ sign.

Example:
Gn$12c1a1Cv ==> Gn
Gn$12c#1@a1Cv  ==> Gn#1@a1Cv
 
This site gives an example of how we use the password in combination with PS task. https://shiningdragonsoftware.net/2015/06/16/tfs-build-vnext-scripts-and-variables/

Is the $ sign not supported or is this a bug?

Kind Regards,
Fabian

**Comment by ericsciple** [comment]
it's a feature of the powershell task. the arguments are passed to your powershell script *from* powershell, which enables using powershell features (e.g. array syntax, etc). it sounds like you need to add single quotes around the input, e.g. '$(myvar)'.

**Comment by ericsciple** [comment]
closing. please reopen if i've missed something.

**Comment by don18** [comment]
Thanks! It works with the single quotes around the input.
