### ISSUE TITLE
sh macosx - cannot execute binary file

### ISSUE THREAD

**Issue by alexszilagyi** [Microsoft/vsts-tasks#3011]
I have a build definition in Visual Studio Online which is integrated with [MacInCloud](https://www.macincloud.com/), I'm encountering an issue regarding to **`010_add_platform_class.js`** file permissions.

According to [Microsoft's article](https://www.visualstudio.com/en-us/docs/build/apps/mobile/cordova-command#the-ionic-command-task) I should run this command: **`chmod +x hooks/after_prepare/010_add_platform_class.js`**

> Troubleshooting Tip: If you encounter a spawn EACCES error when building on a Mac or Linux, be sure all files in the hooks folder to have an "execute bit" set as this a requirement for Cordova. To resolve, add an execute bit to the files in source control or add the following using the Command Line task: chmod +x hooks/after_prepare/010_add_platform_class.js

Therefore I have the following build definition for iOS:

![ios_builddefinition](https://cloud.githubusercontent.com/assets/1736655/19924614/58dedd1c-a0f5-11e6-8ff5-836b21044774.png)

but the build fails at the 2nd step (**sh**), as described in below screen-shot:
Option with **`chmod +x`**
![shell_error_x](https://cloud.githubusercontent.com/assets/1736655/19924701/c0f654ac-a0f5-11e6-925e-4ff44021fddf.png)

Option with **`chmod 777`**
![shell_error_777](https://cloud.githubusercontent.com/assets/1736655/19924742/e1b10c78-a0f5-11e6-9fdd-4b37ccb116ac.png)

I have checked the OS (MAC OS capabilities) and it has the **`sh`** tool in order to run that command:
![mac-capabilities](https://cloud.githubusercontent.com/assets/1736655/19924786/276fde1a-a0f6-11e6-8631-40c6408e324f.png)

But it doesn't works / passes because of the `126 error` (which supposes to mean: not an executable)

Please note that running this command on local MAC it works.

1. What would be the proper solution for the permission error of: `hooks/after_prepare/010_add_platform_class.js` ?

2. How I'd be able to solve the `126 error` which the second step is returning to me?

**Comment by bryanmacfarlane** [comment]
Have you tried command line task:
Tool: chmod
Arguments: +ux ...

**Comment by alexszilagyi** [comment]
@bryanmacfarlane : thanks, that solved.

**Comment by robbiemu** [comment]
Bryan's answer might possibly have once been correct,but not when the installer creates a symlink:

lrwxr-xr-x  1 robbiemu  admin  55 Apr 30 11:12 /usr/local/bin/vsts-npm-auth -> ../lib/node_modules/vsts-npm-auth/bin/vsts-npm-auth.exe

and chmod'ing the 'exe' does not work either (in case that is not obvious)

**Comment by capz** [comment]
this is also an issue for me. why do I have an exe to begin with? its exactly the same as Robbie above for me
