### ISSUE TITLE
Build tasks using SSL certificates 

### ISSUE THREAD

**Issue by yigaldviri** [Microsoft/vsts-tasks#3012]
Hi,
I'm not sure if this is the right place to ask but I couldn't find anywhere else.
I wrote a build task that executes Http calls (over NodeJs). I want to support Https as well but I need a certificate for that. I found that in the Docker extension they were able to get the certificate through the service end-point like this:

<img width="450" alt="validate-endpoint" src="https://cloud.githubusercontent.com/assets/13430395/19927018/919952d0-a100-11e6-8491-fd294f136689.png">

However, I couldn't find any on-line example for a service end-point that contains the certificate (I found [this](https://blogs.msdn.microsoft.com/sriramb/2016/09/14/service-endpoints-authentication-schemes), but it's a partial answer and also not working) or any documentation at all regarding the options I have when writing the vss-extension.json file (and also for task.json).

Is there any documentation for all the options available in vss-extension.json file?
Is there any example, similar to the Docker extension, that I can use?

**Comment by KrishnaAdityaB** [comment]
@yigaldviri you can download the Docker Extension as VSIX from https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.docker.
Rename the .vsix to .zip and extract the extension.vsomanifest file from it.
You can see how the endpoint was defined to take certificates.

**Comment by yigaldviri** [comment]
@KrishnaAdityaB thanks!

**Comment by KrishnaAdityaB** [comment]
@GitHubSriramB for general documentation of all the available options and writing vss-extension.json file.

**Comment by GitHubSriramB** [comment]
This blog has info on how to customize endpoints:
https://blogs.msdn.microsoft.com/sriramb/2016/09/15/service-endpoints-customization/

**Comment by yigaldviri** [comment]
@GitHubSriramB, that blog doesn't talk about certificates. And by the way you should restyle that post since it isn't so readable. Especially the Jsons parts which needs indentation.
