### ISSUE TITLE
Allow steps in definition to be disabled for pull request builds

### ISSUE THREAD

**Issue by justinpatten** [Microsoft/vsts-tasks#3023]
We have continuous integration defined to run in our dev branch. The build definition for that branch includes a step to publish to Azure. We do not want to have the PR build also get published to Azure. For now, I have cloned the definition and removed the publish step. Ideally, we want to be able to disable certain steps in the PR builds.

**Comment by ericsciple** [comment]
@chrisrpatterson to consider feedback.

closing the issue here since it's not an issue with the tasks in this repo.
