### ISSUE TITLE
NotImplementedException for Cmdlet output

### ISSUE THREAD

**Issue by marag** [Microsoft/vsts-tasks#3026]
Hi,

I have powershell script which calls cmdlet (C# module) and it executes by my Build Task.  I would like to add logging to cmdlet execution. Never do this before so at first I've merely tried all possible options in  BeginProcessing() method :

```
WriteDebug("WriteDebug");
WriteVerbose("WriteVerbose");
WriteWarning("WriteWarning BeginProcessing");

ErrorRecord err = new ErrorRecord(new Exception("my exceptiom"), "errId", ErrorCategory.CloseError, "something wrong");

WriteError(err);
 WriteObject("WriteObject BeginProcessing");
```

The Task failed  with this exception:

> ##[debug]WriteDebug
> ##[error]System.NotImplementedException: The method or operation is not implemented.
> ##[error]   at Microsoft.TeamFoundation.DistributedTask.Handlers.PowerShellHandler.InternalPowerShellHostUI.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
> ##[error]   at System.Management.Automation.Internal.Host.InternalHostUserInterface.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
> ##[error]   at System.Management.Automation.MshCommandRuntime.InquireHelper(String inquireMessage, String inquireCaption, Boolean allowYesToAll, Boolean allowNoToAll, Boolean replaceNoWithHalt)
> ##[error]   at System.Management.Automation.MshCommandRuntime.WriteDebug(DebugRecord record, Boolean overrideInquire)
> ##[error]   at System.Management.Automation.Cmdlet.WriteDebug(String text)
> ##[error]   at PSModule.CmdletNewTask.BeginProcessing() in C:\PSModule\CmdletNewTask.cs:line 16
> ##[error]   at System.Management.Automation.Cmdlet.DoBeginProcessing()
> ##[error]   at System.Management.Automation.CommandProcessorBase.DoBegin()
> 

I've commented _WriteDebug("debug info");_  line and try to execute again :
 

> ##[debug]WriteVerbose
> ##[warning]WriteWarning BeginProcessing
> ##[error]System.NotImplementedException: The method or operation is not implemented.
> ##[error]   at Microsoft.TeamFoundation.DistributedTask.Handlers.PowerShellHandler.InternalPowerShellHostUI.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
> ##[error]   at System.Management.Automation.Internal.Host.InternalHostUserInterface.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
> ##[error]   at System.Management.Automation.MshCommandRuntime.InquireHelper(String inquireMessage, String inquireCaption, Boolean allowYesToAll, Boolean allowNoToAll, Boolean replaceNoWithHalt)
> ##[error]   at System.Management.Automation.MshCommandRuntime.WriteWarning(WarningRecord record, Boolean overrideInquire)
> ##[error]   at System.Management.Automation.Cmdlet.WriteWarning(String text)
> ##[error]   at PSModule.CmdletNewTask.BeginProcessing() in C:\PSModule\CmdletNewTask.cs:line 18
> ##[error]   at System.Management.Automation.Cmdlet.DoBeginProcessing()
> ##[error]   at System.Management.Automation.CommandProcessorBase.DoBegin()

I've commented WriteWarning also, and have next exception with WriteError()

> ##[debug]WriteVerbose
> ##[error]System.NotImplementedException: The method or operation is not implemented.
> ##[error]   at Microsoft.TeamFoundation.DistributedTask.Handlers.PowerShellHandler.InternalPowerShellHostUI.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
> ##[error]   at System.Management.Automation.Internal.Host.InternalHostUserInterface.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
> ##[error]   at System.Management.Automation.MshCommandRuntime.InquireHelper(String inquireMessage, String inquireCaption, Boolean allowYesToAll, Boolean allowNoToAll, Boolean replaceNoWithHalt)
> ##[error]   at System.Management.Automation.MshCommandRuntime._WriteErrorSkipAllowCheck(ErrorRecord errorRecord, Nullable`1 actionPreference)
> ##[error]   at System.Management.Automation.MshCommandRuntime.DoWriteError(Object obj)
> ##[error]   at System.Security.SecurityContext.Run(SecurityContext securityContext, ContextCallback callback, Object state)
> ##[error]   at System.Management.Automation.MshCommandRuntime.WriteError(ErrorRecord errorRecord, Boolean overrideInquire)
> ##[error]   at System.Management.Automation.Cmdlet.WriteError(ErrorRecord errorRecord)
> #[error]   at PSModule.CmdletNewTask.BeginProcessing() in C:\PSModule\CmdletNewTask.cs:line 21
> ##[error]   at System.Management.Automation.Cmdlet.DoBeginProcessing()
> ##[error]   at System.Management.Automation.CommandProcessorBase.DoBegin()

From my experiment only WriteVerbose and WriteObject works, and maybe ThrowTerminatingError ( I'm not sure because output is ambiguest).  How to fix this problem? I need additional  to implement something ? please give examples if it is.

Referenced : System.Management.Automation v2.0.50727

**Comment by bryanmacfarlane** [comment]
This looks like a powershell programming issue (not a CI task issue which is what this repo is for).  Does the powershell script in question work on your machine?

**Comment by marag** [comment]
Thanks, that is one of part of my concern. The issue reproduce only  for cmdlet in Build Task. If I run the same script and cmdlet  directly in Powershell, than all messages normally showes.

**Comment by ericsciple** [comment]
prior to calling writewarning, can you log the warning preference variable? it looks like it may be set to inquire and should be either continue or silentlycontinue. 

side note, it looks like you are using the PowerShell task execution handler, i would recommend the [Node handler or PowerShell3 handler](https://github.com/Microsoft/vsts-task-lib)

**Comment by marag** [comment]
Thanks! You right about preferences, it help me to find the cause.  It was  '-Debug'  parameter,  which force  operations asks to continue confirmation as for  'Inquire' mode.  Either way, as I understand  for now TFS doesn't support 'Inquire' mode,  does it plan to be supported in future?

**Comment by ericsciple** [comment]
no. it's a non-interactive process. paste this into a cmd.exe command prompt: `powershell.exe -noninteractive -command "$warningpreference = 'inquire' ; write-warning 'hello world'`
