### ISSUE TITLE
SSH task and SSH Service Endpoint

### ISSUE THREAD

**Issue by JulioECastro** [Microsoft/vsts-tasks#3031]
I've installed SSH task on my TFS 2015 update 3 on-premises.
But I realized no SSH service endpoint option appear. Its possible to install this endpoint type on premises?
![serviceendpoints](https://cloud.githubusercontent.com/assets/5825419/20010630/998d50da-a287-11e6-8743-9dbdd206734d.png)

**Comment by ericsciple** [comment]
@DavidStaheli to weigh in. it sounds like the min agent version should be bumped on the task (technically min server version is the real issue)

**Comment by JulioECastro** [comment]
Finnally I found in a blog the task need the SSH enndpoint and this is a buitin type of endpoint in TFS 15 and not TFS 2015. I decided upgrade to TFS 15 RC3. 
Solved! Thanks
Can I modify the documentation?

**Comment by DavidStaheli** [comment]
Sorry for the confusion you faced, @JulioECastro.  Yes, please feel free to modify the documentation.  Thanks!
