### ISSUE TITLE
Gradle multi-project detection doesn't work if script needs a property

### ISSUE THREAD

**Issue by shruda** [Microsoft/vsts-tasks#3037]
The multi-project detection doesn't work if the gradle script needs a porperty e.g. the password of a repository.

**Problem in case of the gradle.ps1 - TFS 2015 Update 3**
Line 104 doesn't use the $options property, therefore execution of "gradlew properties" throws an exception and the build fails with:

2016-11-07T10:58:57.7644413Z ##[debug]Running batch script.
 
2016-11-07T10:58:57.7800682Z ##[debug]   Path: D:\Agents\2\_work\1\s\Desktop\gradlew
 
2016-11-07T10:58:57.7800682Z ##[debug]   Arguments: properties
 
2016-11-07T10:58:57.7800682Z ##[debug]   WorkingFolder: D:\Agents\2\_work\1\s\Desktop
 
2016-11-07T10:59:02.1863281Z ##[error]System.Exception: Unexpected exit code received from batch file: 1
 
2016-11-07T10:59:02.1863281Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Task.Internal.PowerShell.InvokeBatchScriptCmdlet.ProcessRecord()
 
2016-11-07T10:59:02.1863281Z ##[error]   at System.Management.Automation.CommandProcessor.ProcessRecord()

**Output of the "gradlew properties" script without the options**
FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Agents\2\_work\1\s\Desktop\build.gradle' line: 11

* What went wrong:
A problem occurred evaluating root project 'enterprise'.
> No such property: deploymentPassword for class: org.gradle.api.internal.initia
lization.DefaultScriptHandler

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED

Total time: 21.094 secs

My multi-project script looks like the following:

buildscript {
	repositories {
		maven{
			url "http://.../nexus/repository/maven-public/"
			credentials {
				username System.getenv('DEPLOYMENT_USERNAME') ?: deploymentUsername
				password deploymentPassword
			}
		}
	}
	dependencies { classpath 'com.google.protobuf:protobuf-gradle-plugin:0.7.6' }
}

...

options are -PdeploymentPassword myPassword

**Comment by nigurr** [comment]
@shruda I guess we need to pass the options while calling `gradlew properties`?
Correct me on that. If that's the case, will help in fixing it internally for you and make the appropriate fix in the task too.

**Comment by shruda** [comment]
Hi nigurr,
yes that's right. The options must be added to the gradlew properties call.

Best Regards,
Steve

**Comment by nigurr** [comment]
@shruda do you have any open source project to try it out. It will be helpful to test it out.

**Comment by shruda** [comment]
@nigurr  I've created a multimodule for you which helps you to reproduce the issue.

https://github.com/shruda/bugreports/tree/master/vsts-tasks/3037/multimodule

Gradle wrapper: vsts-tasks/3037/multimodule/gradlew
Options: -PmyProperty=MyValue
Tasks: build
Working directory: vsts-tasks/3037/multimodule

If it works, then you will see the following output at the log:
2016-11-17T09:49:57.0981760Z multimodule: The value of myProperty is 'test'
2016-11-17T09:49:57.2231789Z module-one: The value of myProperty is 'test'
2016-11-17T09:49:57.2231789Z module-two: The value of myProperty is 'test'

if not ...
2016-11-17T09:49:11.5043084Z ##[error]Unexpected exit code received from batch file: 1
2016-11-17T09:49:17.9261287Z ##[error]> multimodule: myProperty isn't available!

The second error is only visible because of my hasProperty check in the build.gradle file.

**Comment by nigurr** [comment]
Thanks for the contribution. I will def take this to fix this issue.

**Comment by nigurr** [comment]
@shruda I just looked at code. indeed we are passing `options` to `properties`.
You need to pass properties `-PmyPassword=abcxyz -PmyUsername=123456` in `gradle task options` field.

Correct me If I am missing something

**Comment by shruda** [comment]
I see - vbossica added it.
https://github.com/Microsoft/vsts-tasks/commit/1b3dbf42de2fcb933cb8d46518b56da2b70916a2

Which version will include this fix? At the moment I'm using TFS 2015 Update 3.

**Comment by nigurr** [comment]
@shruda It should be available in Dev15 TFS

**Comment by shruda** [comment]
OK perfect thanks!
