### ISSUE TITLE
ManualIntervention task cancels entire release

### ISSUE THREAD

**Issue by schmidtaa** [Microsoft/vsts-tasks#3042]
When running a manual intervention task on the server agent in TFS vNext (Online), the entire release is marked as Rejected instead of being placed into In-progress state waiting for a manual task completion. No banner with link to go to the next step is shown for that rejected Release.

Of note, similar activity in Octopus correctly pauses the release until assignee clicks Continue or Abort of the release workflow.

**Comment by dhashrath-msft** [comment]
@schmidtaa can you please let us know is this still happening in the vsts account you shared with me .

**Comment by dhashrath-msft** [comment]
I am closing this issue as @schmidtaa confirmed it works for him now after todays release management service deployment.
