### ISSUE TITLE
TFS2015 upd3 build definition doesn't copy to shared folder

### ISSUE THREAD

**Issue by RuslKoval** [Microsoft/vsts-tasks#3049]
Hi,
I have a problem with deploying build to shared folder on my test machine (virtual machine with Windows7).
I just need to copy files from one shared folder (build drop folder) to another shared folder (on my test VM ware) in my build step, but I get error like this:
![image](https://cloud.githubusercontent.com/assets/23101758/20098624/697c7324-a5bd-11e6-8e53-3a146d9acc57.png)
I can execute xcopy manually from command line, so I'm sure my folder is shared and my xcopy command is correct.

So what else should I do to get access to shared folder (on Windows7 VMware) in my build step?

P.S. I've tried to deploy files with different steps "Copy Files", "Batch Script", "Publish Build Artifacts" directly to the test machine, "Windows Machine File Copy", but always with "access denied" error

**Comment by RuslKoval** [comment]
![image](https://cloud.githubusercontent.com/assets/23101758/20107554/9295a950-a5e1-11e6-8fd7-5a0fdaaf1275.png)

**Comment by ericsciple** [comment]
the error message is bad and has been improved a more recent version. the process doesn't have access to the share.

**Comment by ericsciple** [comment]
you need to either run the agent interactively from a command prompt while logged in as a user that has access to the share, or run it as a service and the service account should have network access to the share.

**Comment by RuslKoval** [comment]
@ericsciple , thanks. 
It would be nice if You give me link/instruction "how to update", because after update build agent, I still see the same errors.
