### ISSUE TITLE
vNext release definition does not allow to use DayOfYear in the Release name format

### ISSUE THREAD

**Issue by schmidtaa** [Microsoft/vsts-tasks#3052]
The following format does work in Build definition as Build name format, but doesn't work in Release name format:

Release_$(MajorVersion).$(MinorVersion).$(Year:yy)$(DayOfYear)$(rev:.rr)

**Comment by bansalaseem** [comment]
Thanks for reporting it. I have filed an item in our backlog to enhance the list of tokens we support in release name format and include the following tokens. Please take a look at it and do let me know in case there is something else as well which you feel is missed, 

$(DayOfMonth)
$(DayOfYear)
$(Hours)
$(Minutes)
$(Month)
$(Seconds)
$(Year:yy)
$(Year:yyyy)

Regards
Aseem Bansal

**Comment by schmidtaa** [comment]
Thanks, the list from above looks good. This would allow to have more flexibility to have the release naming according to the versioning approach accepted by the our development team.

**Comment by rohit-batra** [comment]
This functionality has been added
![image](https://cloud.githubusercontent.com/assets/21075522/22290702/793baa52-e328-11e6-90a3-f27c518a7990.png)
