### ISSUE TITLE
TestAgent/DistributedTests/DTAExecutionHost - "TestExecutionCommand received with None" - until timeout

### ISSUE THREAD

**Issue by Erezinho** [Microsoft/vsts-tasks#3053]
Working with TFS vNext for more than 2 months with 2 build definitions - suddenly the Test agent ("Run Functional Tests) is stuck on "DistributedTests: Test run '123456' is in 'InProgress' state." up until time out. No test is executed.
This happens on two test machines (Win7/Win10). There is one build machine with 3 Agent which master the two test machines.
Restarting the machines did not help. Restarting Agents did not help either.
While (many) other problems where respectively detailed and I could solved them. in this case I have no clue. 
Would be better to have more user friendly error log and I need help here to solve this issue and re-initiate automatic testing.

Checking DTAExecutionHost.exe.log on Win10 machine and I see the following lines (repeatedly):

b method running: [http://<url to tfs>/_apis/test/Agents/319/Commands/0] (GET)0[test]
Web method response: [http://<url to tfs>/_apis/test/Agents/319/Commands/0] (GET)0[test] 18 ms
V, 4480, 132, 2016/11/08, 22:44:27.523, TESTER2\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 4480, 132, 2016/11/08, 22:44:27.523, TESTER2\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 4480, 132, 2016/11/08, 22:44:27.523, TESTER2\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for some time.
V, 4480, 122, 2016/11/08, 22:45:17.539, TESTER2\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [http://<url to tfs>/_apis/test/Agents/319/Commands/0] (GET)0[test]
Web method response: [http://<url to tfs>/_apis/test/Agents/319/Commands/0] (GET)0[test] 14 ms
V, 4480, 128, 2016/11/08, 22:45:17.555, TESTER2\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 4480, 128, 2016/11/08, 22:45:17.555, TESTER2\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 4480, 128, 2016/11/08, 22:45:17.555, TESTER2\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for some time.

**Comment by vimegh** [comment]
@Erezinho .What is Run Functional Test Task failure reason? Also, what are the versions of Test Agent and Build Agent that you are using? Is this TFS On prem? Can you share the build logs with system.debug set to true. You can drop us a mail at devops_tools@microsoft.com with the required logs. Thanks.

**Comment by Erezinho** [comment]
Hi, this issue is not reproducible any more.
After several days it just started to work again (just as it stopped working suddenly)... Nothing was done.
Unfortunately, there are too many issues with TFS vNext build system... very unstable, very frustrating system to work with. 
Currently we are considering moving to Jenkins. 
(If not and if it will show up again, I'll put here the info you were asking for.)

Thanks!

**Comment by PBoraMSFT** [comment]
@Erezinho - thank you for the candid feedback. Other than the issues with the run functional tests task, what are the other pain points that you are facing that are making you consider moving to Jenkins? Can you please send me an email at pbora AT microsoft DOT com ?

**Comment by vimegh** [comment]
As this issue is not reproducible any more, marking it closed for now. @Erezinho If you face the similar  problem again, please feel free to open a issue here. Thanks.
