### ISSUE TITLE
vstest error 225

### ISSUE THREAD

**Issue by Red1Bouarour** [Microsoft/vsts-tasks#3055]
Hi,
I try to Build the solution and execute my test project with vsTest, but i have this errors:

##[error]Unhandled Exception: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

##[error]   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
##[error]   at System.Reflection.RuntimeModule.GetTypes()
##[error]   at System.Reflection.Assembly.GetTypes()
##[error]   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
##[error]   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(ImportDefinition definition)
##[error]   at System.ComponentModel.Composition.Hosting.AggregateCatalog.GetExports(ImportDefinition definition)
##[error]   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
##[error]   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InnerCatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)

##[error]   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
##[error]   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
##[error]   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
##[error]   at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
##[error]   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
##[error]   at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
##[error]   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
##[error]   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
##[error]   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore(Type type, Type metadataViewType, String contractName, ImportCardinality cardinality)
##[error]   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExportCore[T](String contractName)
##[error]   at Microsoft.VisualStudio.TestPlatform.CommandLine.TestRunResultAggregator.get_Instance()
##[error]   at Microsoft.VisualStudio.TestPlatform.CommandLine.Executor.Execute(String[] args)
##[error]   at RockSteady.Program.Main(String[] args)
##[error]Échec de la série de tests VSTest. Code de sortie : 255

i don't know what'is the cause of this error.
Any idéas ?

**Comment by Faizan2304** [comment]
Hi @Red1Bouarour,
Are you still facing the issue???
If yes can you please let us know the version of Test Agent where you are facing this. Mean while can you try repairing Test Agent.

**Comment by prawalagarwal** [comment]
Closing due to no repro. Reach to us at devops_tools[at]microsoft[dot]com if you are still facing issues.
Thanks
