### ISSUE TITLE
Release Management artifact variable information

### ISSUE THREAD

**Issue by iamthegD** [Microsoft/vsts-tasks#3059]
Hi, If not appropriate place, feel free to del/move.

We are using Release Management (great tool) and we are wondering if its possible to download parts of a build artifact instead of the whole shebang.

Case is, our builds output artifact are 5GB but to run a release with tests and QA we only need 2gb out of it.

We did try to look for Build.ArtifactSource* or Artifact.DropFolder* but it seems the concept of the DROP folder from a XAML build is all managed under the hood (correct me if I'm wrong). Documentation doesn't refer to the drop and stuff related to artifacts is about the staging folder.

Is there a way to figure out the full build drop value in a variable so we can only grab what we want as artifact ?

Thanks

**Comment by bansalaseem** [comment]
We don't have this feature right now but it is in our product backlog. I will educate my colleagues about your request so that they know that you are asking also for this feature. 

Regards
Aseem Bansal

**Comment by iamthegD** [comment]
Thanks for the quick reply !
