### ISSUE TITLE
TestAgent Functional Tests with NUnit Adapter

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-tasks#3060]
I have having issues with getting the Functional Tests task to discover my nunit tests.

The documentation states that the packages folder next to the solution file will be searched automatically for any test adapters.  That's great if you are using the task in the build pipeline, but I fail to see how it works if you are using it in the release pipeline as there is no sln file.

My scenario is:

1. Build pipeline performs build
2. Trigger release which builds VM in Azure DevTest Labs.  This release pipeline, sets up the application on the VM and then attempts to run our seleniun tests on it.  

Unfortunately, the tests task fails.  I believe this is because the NUnit testadapter cannot be found.

I have already tried forcing the build to copy the packages folder into the artifact, so it was available on the deployed server, but this didn't work.

I have also seen that you can specify a path to the adapter in the runsettings, but I have a couple of issues with this.

- The runsettings files are used in dev too, so I don't want to hard code the adapter path as it will change depending on where the tests are run.
- Where is the path in the runsettings relative too?

The log file is attached.

[DTAExecutionHost.exe.txt](https://github.com/Microsoft/vsts-tasks/files/582570/DTAExecutionHost.exe.txt)

**Comment by kaadhina** [comment]
You are correct about the packages folder being next to the solution folder for the auto search to work. This will mean, you have to copy the sln file and the packages folder to the remote test agent machine. This in turn will require you to copy the sln file also into artifacts.

To use runsettings, you can specify the absolute path to the adapter in it.

If you run in to issues or concerns with these approaches, please reach out to devops_tools[at]microsoft[dot]com with the logs.

**Comment by grajdeanserghei** [comment]
I totally agree with gregpakes. It seems that runsettings file requires absolute path to testadapter. Why not just provide additional parameter for test adapter path as it is in "Visual Studio Tests" Taks?

**Comment by kaadhina** [comment]
@gregpakes Did force copying the sln file along with the packages folder work for you? 
It should then pick up the adapter automatically. If it still did not, send us the build logs to devops_tools[at]microsoft[dot]com

**Comment by kaadhina** [comment]
@gregpakes Did the above work?

**Comment by vimegh** [comment]
Closing the issue here, assuming the solution provided by @kaadhina has worked, and customer hasn't responded for long time.

**Comment by gregpakes** [comment]
I don't see @kaadhina 's solution as workable.

The tests are supposed to be run against the compiled output, so it makes no sense copying the sln file to the outputs.  The other src would not be available so, no I don't see this as a solution.

**Comment by vimegh** [comment]
@gregpakes Assuming that you are able to provide test adapter path in runsettings file, and you are not blocked due to this issue, we are taking this as your feedback, and will try to improve the experience further. I am opening a backlog item internally for us to track. I hope that is fine.
