### ISSUE TITLE
Make.js is not properly working if inside a directory that contains a whitespace

### ISSUE THREAD

**Issue by hubertusgr** [Microsoft/vsts-tasks#3062]
Hi!
This is about the release m108:

I was trying to use your make.js to build the tasks and found out, that when the script is inside a directory that contains a whitespace it does not work.

my path was:
"E:\Documents\VSTS Tasks\vsts-tasks-releases-m108\vsts-tasks-releases-m108"
and the script failed at the first build task and after I have changed the directory name 'VSTS Tasks' to 'VSTS_Tasks' it worked.

There is something inside your script where you are not propery dealing with the path.

Best Regards and thanks for your great work!
Hubertus

**Comment by ericsciple** [comment]
i think that's an ok solution since it is dev requirement only. it's probably from some of the command lines that are executed.
