### ISSUE TITLE
XamarinTestClound Build tasks has issues on OSx because it is looking for a file called "xamarintestcloud.js" but the file is acutally named "XamarinTestCloud.js"

### ISSUE THREAD

**Issue by hubertusgr** [Microsoft/vsts-tasks#3064]
This is for Release m108:
In the task.js you see on line 155 the following statement:
    "instanceNameFormat": "Test $(app) with Xamarin.UITest in Xamarin Test Cloud",
    "execution": {
        "Node": {
            "target": "xamarintestcloud.js",
            "argumentFormat": ""
        },

actually in the folder _build\tasks\XamarinTestCloud the task is named "XamarinTestCloud.js" when it is build with your make.js script. This causes issues on unix systems.

**Comment by hubertusgr** [comment]
EDIT: I just saw that there is a difference on my files and on your release branch. This issue did not occur again after downloading the branch again. 

---> Sorry for the wrong post please close this issue

**Comment by AlexRukhlin** [comment]
A user mistake.
