### ISSUE TITLE
[Feature request] Add 'Associate Build Artifacts' task

### ISSUE THREAD

**Issue by drolevar** [Microsoft/vsts-tasks#3069]
Currently Publish Build Artifacts task does not support file shares on Linux. And taking into account complexity of the task might never be supported.
To enable having build artifacts located on a file share I suggest adding a 'Associate Build Artifacts' task which only associates a certain file share location with a build artifact.
The actual copying of the build artifacts will be done by a custom step earlier (for example, via a mounted folder).

**Comment by ericsciple** [comment]
recently we made changes to that task and thought about doing this. however it would leave the hyperlink in the web UI somewhat useless and also file share artifacts participate in artifact cleanup jobs which introduces other challenges.

**Comment by drolevar** [comment]
Well, not sure about the artifact jobs part...
But my point is that the hyperlink in the web UI won't be useless if it's associated with the artifact that exists at this location.
And the task of placing it there can be done earlier.

**Comment by bryanmacfarlane** [comment]
This is easy enough to do with a script invoking ##vso command.  You can also create a market place task.  We won't add to in the box.
