### ISSUE TITLE
Key Vault datasource for Azure Resource Manager Endpoint type

### ISSUE THREAD

**Issue by ogoodwin** [Microsoft/vsts-tasks#3077]
I am creating a custom build task where I would like to bind a picklist to a key vault datasource from an ARM endpoint. The ARM endpoint type does not appear to define a datasource for retrieving key vaults from an azure subscription. Am I missing something here? Is there an alternative other than creating a new, custom endpoint type? Are there any plans to implement this feature?

Thanks

**Comment by KrishnaAdityaB** [comment]
@ogoodwin 
There is no first class support for this today. @RoopeshNair for further details.

**Alternative Today**
Write an Azure PowerShell script that reads from key vault and saves them as Build/Release variables for the next tasks to consume. You can use Azure PowerShell task to execute this script.

**How to pass secrets from one task to other**
You have to consume the [VSTS Task SDK](https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/README.md) to get and set the Build/Release variables.
In the script read from key vault and save the secret as a variable _secretFromKeyVault_ using the [Set-VstsTaskVariable](https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/Commands.md#set-vststaskvariable) cmdlet. Don't forget to pass the _-secret_ flag.
You can consume this in the next task by passing _$(secretFromKeyVault)_ in the appropriate field of the task. Or if you want to consume it in another script, you can use [Get-VstsTaskVariable](https://github.com/Microsoft/vsts-task-lib/blob/master/powershell/Docs/Commands.md#get-vststaskvariable) cmdlet.

**Comment by ogoodwin** [comment]
Thanks @KrishnaAdityaB. I have that portion working. My question was around displaying a picklist of existing subscription key vaults in the task UI rather having the user specify the name of the vault in an input field. As far as I understand, my options are to either add a new key vault datasource to the ARM endpoint type, or create a new custom endoint type that exposes a key vault datasource.

Thanks,

**Comment by KrishnaAdityaB** [comment]
@ogoodwin this should help https://blogs.msdn.microsoft.com/sriramb/2016/09/15/service-endpoints-data-sources/

**Comment by KrishnaAdityaB** [comment]
@ogoodwin sorry, I misunderstood the question first time.
@GitHubSriramB can help you on this

**Comment by GitHubSriramB** [comment]
@ogoodwin - We support defining the URL to query inline with data source binding. So in your case, the custom build task can define a data source binding that doesn't refer to a data source but defines the URL to query as part of the data source binding itself.

for e.g.:
{
  "target": "keyvault",
  "endpointUrl": "https://management.azure.com/subscriptions/$(endpoint.subscriptionId)/resourcegroups/$(ResourceGroupName)/providers/Microsoft.KeyVault/vaults?api-version=2016-02-01",
  "resultSelector": "jsonpath:$.value[*].name"
},

Pl. check the api version to use (the version I have used in the example above might not be the right one).

Also, you can optionally use resultTemplate in case you want to return back value/displayvalue (to show display value in the task input but store the value as part of the release definition).
