### ISSUE TITLE
Azure deployment fails?

### ISSUE THREAD

**Issue by asadsahi** [Microsoft/vsts-tasks#3078]
Build definition of an application that works:

![image](https://cloud.githubusercontent.com/assets/3470892/20218532/f5ea9bc2-a81c-11e6-944c-9588407d10bc.png)

Created a new build definition having exactly same steps, targetting a different code repository and azure web app, but getting this error:

![image](https://cloud.githubusercontent.com/assets/3470892/20218592/4a690dc8-a81d-11e6-85ae-3810ce505361.png)

Here is how the task look like:

![image](https://cloud.githubusercontent.com/assets/3470892/20218669/9bafd784-a81d-11e6-837c-b8e35f356152.png)

I have made sure that variable names are correct as well, corresponding to new application build directory.

The only difference I can spot is the version of Azure RM deploy task.

Am I missing anything?

**Comment by b4rj** [comment]
Same thing here. Yesterday it was working normaly...

**Comment by b4rj** [comment]
By the way, a same post whas open here https://github.com/Microsoft/vsts-tasks/issues/3074  asadsahi

**Comment by asadsahi** [comment]
Thanks @b4rj sorry missed that. Closing this one.
