### ISSUE TITLE
Unable to deploy when Service Fabric application is built as part of a Task Group

### ISSUE THREAD

**Issue by rhan1161** [Microsoft/vsts-tasks#3080]
I have a build task for building a Service Fabric application and I can build and deploy this application without any problem.  However, if the build task is put inside a Task Group, VSTS fails to deploy the application.  VSTS reports the following error:
##[error]Exception while parsing XML file: C:\Users\buildguest\AppData\Local\Temp\TestApplicationPackage_4424177776\jdsdhq5b.smf\release\ApplicationManifest.xml

**Comment by harshil93** [comment]
@rhan1161 Can you please add more details about how you are creating a Task Group for which it is failing. It will be really good if you can provide us with a repro.

**Comment by rhan1161** [comment]
I created the TaskGroup by editing the Build Definition.  This created a task group that was then included in my Build Definition.  I will try to see if we can send you a repro build.

**Comment by rhan1161** [comment]
Our latest tests showed that we can now deploy our applications when built using Task Group.  Thank you for looking into this issue.

**Comment by rhan1161** [comment]
This problem has re-appeared.  It looks like the deployment fails when parsing the ApplicationManifest.xml.  After VSO build, the size of this file is twice what it should be and the file is now encoded in usc-2 le format.  When I replaced this file with the original file, I was able to redeploy.

**Comment by rhan1161** [comment]
Workaround: I ran a powershell script to convert the file to ascii encoding.  Problem solved.  Thank you.
