### ISSUE TITLE
could not remove directory (code EPERM)

### ISSUE THREAD

**Issue by RobBowman** [Microsoft/vsts-tasks#3082]
I'm running latest version of TFS 2015 release manager. I have a simple release that includes a "CopyFiles" task. I need to have the "Clean Target Folder" option of the task enabled.

![umuxq](https://cloud.githubusercontent.com/assets/6296919/20246710/f2a6dca2-a9b4-11e6-8754-421a45115593.png)

I have three target environments configured. Both are newly created identical Windows servers. The CopyFiles task works fine against the first two servers but for the next environment in the pipeline, when copying to the second server I get the following error:

`2016-11-11T21:41:07.4324714Z found 2 files
2016-11-11T21:41:07.4324714Z ##[debug]file:D:/Build/_work/df9f2c4cf/(master) Orchard BTDF/drop/20161111.5.zip will be copied.
2016-11-11T21:41:07.4324714Z ##[debug]file:D:/Build/_work/df9f2c4cf/(master) Orchard BTDF/drop/Unzip.ps1 will be copied.
2016-11-11T21:41:07.4324714Z Cleaning target folder: \\Steatbt02\BizTalkDeployments2\Orchard
2016-11-11T21:41:07.4324714Z ##[debug]rm -rf \\Steatbt02\BizTalkDeployments2\Orchard
2016-11-11T21:41:07.4480915Z rm: could not remove directory (code EPERM): \\Steatbt02\BizTalkDeployments2\Orchard
2016-11-11T21:41:07.4480915Z ##[debug]task result: Failed`

There's no sign of errors in the event log.

I created the share "\Steatbt02\BizTalkDeployments2" and granted "full-access" permissions to the account running the build agent. I even tried logging onto the build server and run as for the command prompt using the credentials of the build agent. From this command window I was able to remove the target folder "\Steatbt02\BizTalkDeployments2\Orchard" - so I can't think why the build agent would have trouble doing the same!

Any ideas what could be wrong, or what extra steps I could take to track down the root cause of the problem?

SO Post here: [http://stackoverflow.com/questions/40556921/tfs-release-copyfiles-task-gives-code-eperm](url)

**Comment by ericsciple** [comment]
does the service account have permissions granted on the local files as well. when you use the "Advanced Sharing" permissions management UI to grant permissions, you also need to grant permissions on the local dir as well.

**Comment by ericsciple** [comment]
nevermind, i see now you said it works when you run a process as the account it works.

**Comment by ericsciple** [comment]
@RobBowman have you changed the service account's password recently, if so restarting the box might help.

**Comment by ericsciple** [comment]
@RobBowman Does it work without `Clean Target Folder` checked? Something could have a handle to the file at the time the step is running.

**Comment by bryanmacfarlane** [comment]
We've tried to repro and answers not supplied.  Closing for now.

**Comment by xzlichao** [comment]
Just as @ericsciple said, make sure the service account have permissions granted on the local directory. 
You have to add **NETWORK SERVICE** account and have permissions granted to access the **Orchard**  folder. Right-click the **Orchard** folder --> **properties**-->tap to **Security**-->**Advanced**-->**Add**--> **select a principal** --> ...  find the service account (Network Service in this case) to add.
