### ISSUE TITLE
Copy Files should match dot files

### ISSUE THREAD

**Issue by Zoxive** [Microsoft/vsts-tasks#3085]
I'm having a problem copying files that start with a dot (ex .gitignore)

Looking up how a library like https://github.com/isaacs/minimatch does it, they have an option "dot" which has to be set to true. Is there any way that copy files task can support this?

**Comment by ericsciple** [comment]
for now what you can do is, wherever you have a pattern like `**/*`, also add the same pattern `**/.*`

**Comment by ericsciple** [comment]
we are working on cleaning up globbing consistency across the tasks now and will be improving docs as part of that effort as well

**Comment by Zoxive** [comment]
That worked thank you.

Also thanks in the future for updating the documentation to help others with this issue as well.
