### ISSUE TITLE
Visual Studio Test Agent Deployment hangs with 'Interactive Process' checked

### ISSUE THREAD

**Issue by Cva2904** [Microsoft/vsts-tasks#3087]
Hi everyone,

As part of continuous integration, i have created build definition to execute my coded ui tests on remote machine.
I am able to execute the tests, in remote machine when i queue the build and keep the remote machine active.
But, when i schedule the build at a particular time, build is getting failed saying "Task 'DeployTestAgent' on machine 'bedac2469:5985' is taking time".

Can you please help on this.

Thanks in advance.

**Comment by nigurr** [comment]
@Cva2904 

Please don't allow any other user to login to the Test Agent machine
If you RDP into that machine, please close the RDP by closing it and not minimize it

The nature of Coded UI scenarios require the Machine to be untouched and self-contained.

**Comment by Cva2904** [comment]
@nigurr ,

I have tried the above option as well and this is also not working.

**Comment by nigurr** [comment]
can you please attach the DTAExecutionHost log from Test Agent machine (C:\DtaLogs)
and your build log with `system.debug = true`

**Comment by Cva2904** [comment]
@nigurr,

Attached is the log file.

[DTAExecutionHost.exe.txt](https://github.com/Microsoft/vsts-tasks/files/597055/DTAExecutionHost.exe.txt)

**Comment by preetsaimutneja** [comment]
can you try with 'Update Test Agent' option checked in 'Deploy TestAgent' task

**Comment by Cva2904** [comment]
@preetsaimutneja 

I have tried that as well, but ended up with the same issue.

**Comment by preetsaimutneja** [comment]
Can you please contact me at prmutn[AT]microsoft.com .

**Comment by Cva2904** [comment]
@prmutn

Can you share the email id that i need to share the logs

**Comment by preetsaimutneja** [comment]
Email it to devops_tools[at]microsoft.com

**Comment by Cva2904** [comment]
@preetsaimutneja 

now i am able to schedule coded ui tests.

Now, i looking to execute build definition using Test Plan.

Steps followed: Selected Test Plan in Run Functional Step, and appropriate values and executed the build definition.

I am getting the error as "No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct."

**Comment by prawalagarwal** [comment]
@Cva2904 

Which version of TFS are you on? Please ensure that your test dlls are present in the folder you are indicating as Test Drop Location.

**Comment by Cva2904** [comment]
@prawalagarwal 

TFS 2017

**Comment by Cva2904** [comment]
hi everyone,

looking to send email on the status of build definition i.e, if the build pass, i need to send pass report and if it fails i need to send fail report with screenshot.

Thanks in advance.

**Comment by kaadhina** [comment]
@Cva2904 can you confirm if you were able to run the test plan scenario?

**Comment by Cva2904** [comment]
@kaadhina 

I tried doing so, but when we are executing using test plan, test agent is not identifying the required assembly files and .dll's.

So tried executing using Priority and was able to do it.

Thanks.

**Comment by Cva2904** [comment]
Hi All,

I am able to send email notifications once my build gets executed.

Thanks.

**Comment by kaadhina** [comment]
If you are still blocked, here is some troubleshooting that might help:
If your intention is to run a particular set of test methods from a set of dlls based on name,priority etc, you are on the right direction.
If you are trying to run the test cases of a particular test plan, test suite, and test config,
Check whether the testplan, suite, config selection that you have made points to the required test cases, and that those test cases have associated automation pointing to the required test methods to be run.
You can find this from the test plan hub of tfs.
Please send over the details to devops_tools@microsoft.com for further clarification/help.
