### ISSUE TITLE
Visual Studio Test Agent Deployment fails due to login legal notice

### ISSUE THREAD

**Issue by pundj** [Microsoft/vsts-tasks#3090]
The Windows 7 VM that I am using as the machine to run my Coded UI tests with using the Run Functional Tasks task is part of a domain that requires a legal notice that comes up before logging on to the machine. When the Visual Studio Test Agent Deployment task gets to the ConfigureTestAgent.ps1 step, sometimes it reboots the machine, but then cannot get past the legal notice to autologon again when the machine comes back up, which then stalls the task until it times out and fails. If I log on to the machine after it comes back up after the restart while the task is still running and click the OK button to get past the legal notice, the task finishes properly and goes on to run the tests. I have tried running a powershell script on the machine just before the Visual Studio Test Agent Deployment task which clears out the registry keys which hold the values of the legal notice, but since the machine is a member of the domain which sets the group policy for the legal notice, it ends up getting refreshed prior to the machine rebooting during the task.

How do I: 
1. Keep the task from rebooting the machine, or
2. Run my script to clear the registry keys for the login notice immediately before the machine reboots

If you have another workaround, that would be great as well. I also need to mention that it is **highly unlikely** that our IT Security head will allow a group policy exception for this machine for the legal notice, so please provide a workaround that does not involve that. Thanks!

**Comment by nigurr** [comment]
@pundj, the nature of Coded UI test execution requires DTA process to run in interactive mode.
One way to avoid rebooting is
1. Don't allow any other user to login to this machine
2. Uncheck 'Update Test Agent' option in Deploy Test Agent task

This should bypass the requirement of `Reboot` scenario. Please give it a try and update us.

**Comment by pundj** [comment]
I have uncheck the Update Test Agent option in the task and have only logged in to the server as the user that runs the task and it is still rebooting every once and a while, but I am not sure what situations are causing that. Can you please detail all the circumstances that will cause the test agent machine to reboot during the Visual Studio Test Agent Deployment task? 

Also, is there any way I could modify the ConfigureTestAgent.ps1 script so that just before it reboots the machine, it clears the values from the registry keys associated with the legal notice caption and text?

**Comment by nigurr** [comment]
Run tests with admin process [configure and test agent username] should be same. in those cases, you don't see reboot.

**Comment by pundj** [comment]
I have the same username and password for all the steps, and still it reboots sometimes. Can you please tell me **all** the situations **do** cause a reboot? And can you please answer my last question from my previous response about if it is possible to modify the powershell script to insert a few commands to clear the registry key values for the legal notice immediately prior to the reboot call? Thanks!

**Comment by pundj** [comment]
Can you please update this thread to provide answers to the above questions? Thanks!

**Comment by nigurr** [comment]
Hi, Sorry for the delay
1. Reboot happens because of Full .Net installation typically first time installation of Test Agent
2. Running UI Test scenarios under test account where there might be another active desktop sessions

I believe registry setting might help or may not depends on your company IT group policy
but here's the link for the same http://www.howtogeek.com/howto/windows/disable-that-annoying-windows-logon-warning-message/

**Comment by pundj** [comment]
I am experiencing reboots more often that what you describe. I am using a single user only for the test agent machine. No other user is specified in the VSTS Tasks, and that user is the only user that logs into the machine.

I have a task which runs immediately prior to the Visual Studio Test Agent Deployment task which runs a powershell script on the test agent machine which clears out the registry keys related to the legal notice. However, since the Visual Studio Test Agent Deployment task takes a while prior to the reboot, the registry keys are populated again by the time the reboot happens.

Can you please answer this question that I've mentioned a couple times above: Is there any way I could modify the ConfigureTestAgent.ps1 script so that just before it reboots the machine, it clears the values from the registry keys associated with the legal notice caption and text?

**Comment by nigurr** [comment]
@pundj Sorry currently this is not possible as the reboot logic exists in the `Test Agent` code. Another important thing is if the registry is keep refreshed with "Auto logon" message, you can't by pass it. During the reboot of machine, windows loads Group policies which will push the registry config during the startup.

I am trying to help you unblock by not getting rebooted so that it works for you. 
Did you disable "Update Test Agent" option in Deploy Test Agent task?

**Comment by pundj** [comment]
Sorry for the delay. The "Update Test Agent" option in Deploy Test Agent task has been disabled in all cases reported above.

**Comment by nigurr** [comment]
@prawalagarwal will help you on this

**Comment by prawalagarwal** [comment]
@pundj 

Have you tried on some other agent machine (with a more recent OS version) if the issue exists there too? 

Can we have a skype call discussing your issue? Please reach out to us at devops_tools[at]microsoft[dot]com with details of your TFS version, Agent versions and for organizing the meeting.

Thanks

**Comment by pundj** [comment]
I currently do not have access to a Windows 10 VM at my organization. Other suggestions for OS?

I will send an email to set up a call. Thanks.

**Comment by prawalagarwal** [comment]
@pundj We have received your mail. We are looking into the issue. Thanks

**Comment by prawalagarwal** [comment]
@pundj were you able to try with a different OS version?

**Comment by pundj** [comment]
@prawalagarwal Unfortunately I do not have access to any VMs with newer operating systems in the same environment.

**Comment by tanvi-soni** [comment]
The test agent needs to reboot the machine to create an active session. Hence, that cannot be avoided to run UI tests. The only options we can suggest for you to get unblocked are: 
i.  Maintain an active session, i.e. the machine should be logged in with the same credentials used by test agent and it should not be locked or minimized
ii. Use a different set of test machines that do not come under IT policy
