### ISSUE TITLE
Can not build Android 7 xamarin apps

### ISSUE THREAD

**Issue by drpulpie** [Microsoft/vsts-tasks#3094]
I upgraded to Complie using Android 7
Then the VSTS build failed

C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets (569, 2) 
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(569,2): Error XA0000: Could not determine API level for $(TargetFrameworkVersion) of 'v7.0'.

Process 'msbuild.exe' exited with code '1'.

![image](https://cloud.githubusercontent.com/assets/1228876/20341413/790f0606-abe6-11e6-9ddf-99e5af97d62e.png)

**Comment by madhurig** [comment]
The hosted build VMs do not have Xamarin.Android 7.0 support though the Android SDK 24 is installed. We will be updating them early next year after the holidays.

Sorry for the inconvenience.

Thanks,
Madhuri

**Comment by shortstuffsushi** [comment]
If this hasn't been done yet, why not keep the issue open? That way we can get updated when it's *actually* fixed for us.

**Comment by madhurig** [comment]
@shortstuffsushi : We have a couple of other issues related to Android 7 with Xamarin on hosted build. A new version of the VM is available which has Android SDK 24 on it, so you shouldn't see this particular error. Can you please follow this issue instead: https://github.com/Microsoft/vsts-tasks/issues/3237?

**Comment by shortstuffsushi** [comment]
Sure. Linking issues is fine, as long as we've got somewhere to watch.

**Comment by chris1248** [comment]
I have this issue too. I'm new to android, and so this is stopping me in my tracks this morning.

**Comment by madhurig** [comment]
@chris1248: The issue was resolved and closed. If you are seeing a similar error now, please open a new issue with build log and details on which agent queue you are using.
