### ISSUE TITLE
dotnet tasks fail when executed on external build server

### ISSUE THREAD

**Issue by danielcweber** [Microsoft/vsts-tasks#3098]
Hello,

I got a simple build definition that uses the new dotnet task (preview) to restore, build, test and pack my project. The project(s)-field is set to

**/project.json on restore, build and pack tasks
**/*Tests/project.json on the test task.

Everything works beautifully on the hosted build server. The log of restore starts with

>2016-11-16T15:23:31.7112509Z ##[section]Starting: Restore
>2016-11-16T15:23:31.7602495Z
> ...
>2016-11-16T15:23:31.7602495Z Task         : .NET Core (PREVIEW).

I then tried to run the build on one of our own build servers. It has Visual Studio 2015 Update 3 installed as well as "Microsoft .NET Core 1.1.0 - SDK 1.0.0 Preview 2.1-003177 (x64)". All dotnet tasks fail with the message "Project file(s) matching the specified pattern were not found.". Specifically, the log of restore looks substantially different (only few lines, can provide more)

>2016-11-16T20:04:30.5305592Z Set workingFolder to default: C:\agent\tasks\DotNetCoreCLI\0.1.0
>2016-11-16T20:04:30.9055608Z ##[debug]agent.workFolder=C:\agent\_work
>2016-11-16T20:04:30.9211849Z ##[debug]loading inputs and endpoints
>2016-11-16T20:04:30.9211849Z ##[debug]loading ENDPOINT_AUTH_1DA08703-470D-4634-B30A-E1DB636F54B0
>2016-11-16T20:04:30.9211849Z ##[debug]loading >ENDPOINT_AUTH_PARAMETER_1DA08703-470D-4634-B30A-E1DB636F54B0_ACCESSTOKEN
2016-11-16T20:04:30.9394337Z ##[debug]loading >ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN:

On top we see that the working folder is set to the DotNetCoreCLI-task-folder, something that's not done when running on the integrated hosted build server. Obviously there's no project.json here. The logs of all tasks look very similar, setting the wrong working directory, setting some variables and failing in the end. This line may be of interest:
>##[debug]Glob pattern: ["C:\\agent\\tasks\\DotNetCoreCLI\\0.1.0\\**\\project.json","!C:\\agent\\tasks\\DotNetCoreCLI\\0.1.0\\**\\*.Tests\\project.json"]

Still, the task seems to get the location of dotnet.exe right (C:\Program Files\dotnet\dotnet). Running dotnet restore/build/etc. locally on the build server runs just fine, so the SDK is verified to be working.

**Comment by pragupta-ms** [comment]
Hi Daniel,

This is happening as you have legacy version of the agent on your build servers (not happening on hosted since the agent is updated here). In order to resolve this please **update your build server agents to the latest version**. If for some reason/requirement you are unable to update the agent version then edit all the .NetCore tasks setting **Project(s**) value as  "**$(system.defaultworkingdirectory)/**/project.json**" without the quotes.
