### ISSUE TITLE
The test cases renamed, test report shown the renamed and previouse test on same report which used vsts functional test

### ISSUE THREAD

**Issue by nickeyyan** [Microsoft/vsts-tasks#3109]
Hi VSTS-Tasks Team,

We met an issue. We used VSTS Release Management - Test Task - Functional Test task to verify our binary. 

Recently, we modified a test case name. But the test report still shown the previouse test case and new test case on same report. Certainly, the previouse result said " command name not found System.NotImplementedException"

I have tried to reflector the binary and confirmed that the test case has been renamed.
Also, I used vstest.console.exe to run the binary locally. No test case found.

I believe it might be VSTS test display issue.

**Comment by vimegh** [comment]
This issue is being discussed with customer on email: devops_tools@microsoft.com and is not reproducible as of now. hence marking this closed.
