### ISSUE TITLE
Extract files task fails on clean destination

### ISSUE THREAD

**Issue by andrasg** [Microsoft/vsts-tasks#3111]
Every once in a while the Extract files task with the clean destination enabled fails after clean. I could not find a pattern. Whenever this happens, the target folder is going missing (is deleted in this task).
```
2016-11-17T20:45:44.8977942Z Cleaning destination folder before extraction: C:\inetpub\wwwroot_INT-fe
2016-11-17T20:45:45.0384251Z Error: EPERM: operation not permitted, stat 'C:\inetpub\wwwroot_INT-fe'
```

**Comment by DavidStaheli** [comment]
Thanks for reporting this, @andrasg.  Are you using the Microsoft-hosted build agent, or connecting your own build agent?

**Comment by andrasg** [comment]
It's on my own agent.

**Comment by ericsciple** [comment]
is `wwwroot_INT-fe` a folder or a file?

**Comment by andrasg** [comment]
It's the destination folder I am extracting to.

**Comment by ericsciple** [comment]
it sounds like something may have a handle open on that folder.

the task is calling rmRF and then statSync. rmRF is ultimately calling fs.rmdirSync. i think what is going on is similar to the behavior described in the [unlink](http://man7.org/linux/man-pages/man2/unlink.2.html) man page...
>If the name was the last link to a file but any processes still have the file open, the file will remain in existence until the last file descriptor referring to it is closed.

attempting to stat the file while it is in this state causes EPERM. simple repro from an interactive Node prompt:

```javascript
fs.mkdirSync('unlink-dir-test')
var fd = fs.openSync('unlink-dir-test', 'r')
fs.rmdirSync('unlink-dir-test')
try {
  fs.statSync('unlink-dir-test')
} catch (err) {
  if (err.code == 'EPERM') {
    console.log('yep, EPERM');
  }
} finally {
  fs.closeSync(fd);
}
```

if the call to `closeSync` is delayed, then you can watch in explorer and see the folder does not go away until `closeSync` is called.

i'm not sure offhand what a better pattern to follow would be here... i also tried lstat and it also throws EPERM. there is of course things that can be done, but it would also be nice to find a general pattern that can be applied elsewhere.

**Comment by ericsciple** [comment]
i'm thinking rmRF should be modified to have retries with delays and ultimately fail if stat keeps throwing EPERM after n seconds

**Comment by ericsciple** [comment]
@andrasg can you try modifying the your task on disk (under the _work/_tasks of the agent) to add some crude retry logic. this will help to confirm the assumption. replace the following lines in extractfilestask.js
```javascript
        // Create the destination folder if it doesn't exist
        if (!tl.exist(destinationFolder)) {
            console.log('Creating destination folder: ' + destinationFolder);
            tl.mkdirP(destinationFolder);
        }
```

with
```javascript
        // Create the destination folder if it doesn't exist
        var exists;
        var attempts = 0;
        while (true) {
            attempts++;
            console.log('Attempt ' + attempts + ' checking if dest exists.');
            try {
                exists = tl.exist(destinationFolder);
                break;
            }
            catch (err) {
                if (err.code == 'EPERM' && attempts < 20) {
                    console.log('Destination was not removed. Sleeping 1 second.');
                    require('child_process').execSync('cmd.exe /s /c "ping 127.0.0.1 -w 1 -n 2 1>NUL 2>NUL"');
                    continue;
                }

                throw err;
            }
        }
```

**Comment by renatotkr** [comment]
any updates on this issue?

I have a similar problem with copy files task when clean is enabled
`2017-02-15T12:57:44.5509653Z Cleaning target folder: \\univmfs01\projetosprot$\Backup\AvaliacaoDesempenho\
2017-02-15T12:57:44.5509653Z ##[debug]rm -rf \\univmfs01\projetosprot$\Backup\AvaliacaoDesempenho\
2017-02-15T12:57:50.1920133Z ##[debug]creating path: \\univmfs01\projetosprot$\Backup\AvaliacaoDesempenho\
2017-02-15T12:57:50.1920133Z shell.js: internal error
2017-02-15T12:57:50.1920133Z Error: EPERM: operation not permitted, mkdir '\\univmfs01\projetosprot$\Backup\AvaliacaoDesempenho'`

I'm using Windows Machine File Copy as a workaround, but I have to provide username and password. looks like it uses robocopy

**Comment by DavidStaheli** [comment]
@ericsciple, this appears to affect multiple tasks.  Do you advise fixing this in the task-lib and having the tasks adopt a new task-lib version?

**Comment by ericsciple** [comment]
@renatotkr are you able to confirm whether the crude retry logic i pasted above eliminates the problem you are seeing?

**Comment by renatotkr** [comment]
@ericsciple 

I've tried as suggested but it didn't work

I noticed that I'm using copyfiles version 1.0.13 and there are newer versions, I guess this may be the problem.

I'm using TFS on premise, but I didn't find out how to update it. Could you help?

Thanks!

**Comment by ericsciple** [comment]
@renatotkr if you want to build the repo (contribute instructions in readme.md), then you can use tfx to upload the copy files task layout that is produced under _build\tasks\copyfiles. you would want to build a release branch, releases/m112. i added a change in m112 so that if you select "clean", then it only cleans the contents and doesnt drop the folder. that may solve the problem you are running into.

**Comment by ericsciple** [comment]
...oops the change is only in master, not in releases/m112

**Comment by ericsciple** [comment]
and tfx is here: https://github.com/Microsoft/tfs-cli
the build tasks upload command is what you want

**Comment by renatotkr** [comment]
@ericsciple 
Thanks for the info, I managed to install the latest version following your steps

Did couple of tests and it appears to be working fine

I would like to suggest to automatically update all the in the box tasks more often, 4 months is a long time (if I understood correctly, only for on premise TFS)

Thanks for the help
