### ISSUE TITLE
Retrieving the Access Token for the current Auth Context in Azure Powershell scripts

### ISSUE THREAD

**Issue by RDalziel** [Microsoft/vsts-tasks#3119]
I'm looking to create a task that will communicate with an application via an Azure AD Access token.

Given that i already have a user in this AD and a Principal setup - how can i retrieve the current access token to send that onto APIs in the same subscription?

Wasn't sure where to post this as it's not really an issue, but i can't find anything in the docs for this!

**Comment by ericsciple** [comment]
are you looking to create a custom task, or use an ad hoc script? the Azure PowerShell task and Azure CLI task initialize the connection for you and then call your ad hoc script. if an ad hoc script doesn't suffice, then you might want to look at those tasks to see how they setup the connection.

**Comment by RDalziel** [comment]
This is for a custom Azure Powershell Task - I am looking to utilize the initialized connection in someway to get an auth token to use to authenticate with an API I've setup in the subscription.

Ideally i'm looking to do it with minimal additional parameters (Preferably no extra!) than just the service principal

**Comment by ericsciple** [comment]
ok if you are writing a custom task, you can look at what the Azure PowerShell task does. it references the code under Common/VstsAzureHelpers_ to initialize the connection from the service endpoint that the user selects in the task UI. the helper module is bundled with the task at build-time of the tasks repo. other tasks in this repo reference that helper module as well, so they would also be a go-by.

**Comment by susanadomingos-falck** [comment]
Activate the additional option "Allow scripts to access the OAuth token" for the Agent job and use the variable $env:SYSTEM_ACCESSTOKEN
