### ISSUE TITLE
RunDistributedTests how can I get such ability:

### ISSUE THREAD

**Issue by kardinal3000** [Microsoft/vsts-tasks#3130]
A few days ago I had the needs pass the values of variables (fields)  to  the **RunDistributedTests** task through "Queue build" variables(fields) . The task looks simple. But.
I cant understand how can I pass values to fields: **Test Plan - "type": "pickList", Test Suite - "type": "pickList", Test Configuration - "type": "pickList"**  use the button "Queue build"

 **RunDistributedTests** task:
![2016-11-21 18_22_44-microsoft team foundation server - microsoft edge](https://cloud.githubusercontent.com/assets/18549964/20490741/ae1b5888-b017-11e6-877e-d2a714b96608.png)

**"Queue build" button**
![2016-11-21 18_23_23-microsoft team foundation server - microsoft edge](https://cloud.githubusercontent.com/assets/18549964/20521099/42f80e2a-b0b2-11e6-96c0-cb9ee3aaf7ca.png)

Please assist me. Is there any way to realize it

**Comment by nigurr** [comment]
@kardinal3000 currently this is not possible. We fetch the Testplan/suite information from Test Management APIs.

The alternative way is you can create the build definition through simple program using Build APIs [https://www.visualstudio.com/en-us/docs/integrate/api/build/builds] and achieve it.

**Comment by hubertusgr** [comment]
Hi!
I am also stumbling across this issue!
Is there any chance that you implement the option to use variables inside this build task to specify the test plan and suites on the fly?

The reason why this would be handy is:
We are having one test plan with suites and test cases for our release process. We have a couple of iterations of our software that are still supported and updates for those are provided (2016U1 and 2017 U4 etc.) We use the same test plan for all iteration and tests that are created for features that are not available in olderversions have the iteration property set to the minimum supported version always.

Currently there is no way of filtering these testcases in the suite by any property when a build is started so we created query based suites that give us a view of the test that are availailable for each iteration.
If we could parameterize the testplan and suite inputs in this taks we would not need to clone the build definitions for each supported iteration but could use one build definition for running the tests across different iterations without getting any errors that the binaries of a test case are not included in the dlls.

I hope that I could give you some usecase for this.
If you have any tips how to avoid my issue please feel free to provide me some info.

Best Regards Hubertus

**Comment by nigurr** [comment]
@PBoraMSFT
