### ISSUE TITLE
Chef Tasks

### ISSUE THREAD

**Issue by mikkoc** [Microsoft/vsts-tasks#3151]
We're using VSTS hosted version.
I can configure a Chef Server service endpoint but I don't understand how to use this information in a task?

Found this https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/Chef but it seems it's not available on the marketplace. I don't think I'm supposed to package it and publish it on the market since I didn't write it :)

What would be the correct approach?
Thanks

**Comment by RoopeshNair** [comment]
Chef task is currently in private preview and not rolled out publicly. You may download and upload it to your account (after changing the guid etc) but **not** publish it on marketplace. 

The task itself is being reworked, we don't have time-lines/availability of this at this point in time.
