### ISSUE TITLE
Invalid 'JUnit' test results format

### ISSUE THREAD

**Issue by PeterJakubik** [Microsoft/vsts-tasks#3154]
Hello
I'm running some Ant build with JUnit 4 tests.
The build is OK, but I don't see the Testresults.
My Build steps:
1. Ant ... with build.xml
2. Publish Test ... format JUnit

Here are my build issues:

_Invalid results file. Make sure the result format of the file 'C:/a/1/s/JTestOnline_Test/junit/TEST-JUnitTestSuite.xml' matches 'JUnit' test results format._
 
_nvalid results file. Make sure the result format of the file 'C:/a/1/s/JTestOnline_Test/junit/TEST-TestCalculator.xml' matches 'JUnit' test results format._
 
_Invalid results file. Please make sure the Test Result Format field in the task matches the result format of the file: C:\a\1\s\JTestOnline_Test\junit\TEST-JUnitTestSuite.xml_
 
_Invalid results file. Please make sure the Test Result Format field in the task matches the result format of the file: C:\a\1\s\JTestOnline_Test\junit\TEST-TestCalculator.xml_

What is  the Expected JUnit rest result format?

Here is the sample xml JUnit result:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<testsuite errors="0" failures="2" hostname="MD1HP1XC" name="JUnitTestSuite" skipped="0" tests="2" time="0.139" timestamp="2016-11-25T17:19:40">
  <properties>
    <property name="java.vendor" value="Oracle Corporation" />
    <property name="java.specification.version" value="1.8" />
    <property name="ant.project.invoked-targets" value="JTestOnline_Test" />
    <property name="env.PROCESSOR_LEVEL" value="6" />
  </properties>
  <testcase classname="TestCalculator" name="test" time="0.006">
    <failure message="Not yet implemented" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Not yet implemented
	at TestCalculator.test(TestCalculator.java:9)
</failure>
  </testcase>
  <testcase classname="TestCalculator" name="test1" time="0.001">
    <failure type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError
	at TestCalculator.test1(TestCalculator.java:14)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>```

Thank you
Peter

**Comment by kaadhina** [comment]
Peter,
Send a mail to devops_tools [at] microsoft [dot] com with the following info:
1. A copy of the full xml files that you have mentioned above (TEST-JUnitTestSuite.xml) that are not getting published for you.
2. If the above snippet is the full file, run the scenario again after setting build variable system.debug = true, and send us the build logs.
3. Are you on vsts or on-prem, and if on-prem, which version?

Thanks,
Kavipriya.

**Comment by PeterJakubik** [comment]
mail sent, I'll update the Issue accordingly

**Comment by PeterJakubik** [comment]
The JUnit scheme is here  [https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd)

Although the generated XML files were not strictly JUnit 4 conform : "Attribute 'skipped' is not allowed in element <testsuite>"
It works.

I fixed the ant build.xml and provided the needed Parameters for Ant build step in TFS.

**Comment by gchadid** [comment]
what parameters did you modified in the build.xml and in the ant build steps?
