### ISSUE TITLE
Visual Studio Build: Supply list of solutions to build

### ISSUE THREAD

**Issue by mieliespoor** [Microsoft/vsts-tasks#3159]
Currently, the Visual Studio Build task allows you to specify wildcards to build all solutions found to matching the wildcard. This however in some cases will pick up solutions we don't want to include in the build.

It would be great if we could specify a list of solutions to build. We should still be able to list wildcards for the solution names.

Or we should be able to specify solutions we don't want to include. I however like this$(SolutionsToBuild) property we had with the XAML builds. That worked quite well.

Sample:
Dir structure:
/src/Folder1/some.solutionname.sln
/src/Folder2/some.other.solutionname.sln
/src/Folder2/ecluded.solutionname.sln
/src/Folder3/random.sln

Task Property Values:
Solutions : **\some*.sln, **\random.sln

**Comment by bryanmacfarlane** [comment]
Thanks - I've added this to our feature backlog for consideration.  Note you should also be able to (1) use exclusion patterns and (2) use multiple instances on the msbuild tasks (the reason we didn't make it multi valued).

Note that if the list is huge, you should also consider the factoring of your dev builds and source (how do devs build a full product locally).
