### ISSUE TITLE
DotNetCoreCLI test can't publish xml test results for multiple test projects at once

### ISSUE THREAD

**Issue by kyschouv** [Microsoft/vsts-tasks#3164]
When running the .NET Core command "test", you can specify multiple projects to test with wildcard syntax. E.g. "**/test/**/project.json". However, since there's no per-project variable, and you have to specify a full filename for the test -xml parameter, it's impossible to use the test command for multiple projects if you intend to publish the test results at all.

I'd suggest adding a $(ProjectName) parameter (or something similar) to the script that gets substituted with the current project name/folder/path during execution. Then custom arguments could change per-project.

**Comment by azooinmyluggage** [comment]
Hi @kyschouv,

This is valuable feedback. Thanks!! 
We have added it to our backlog. 

regards,
Atul Malaviya
Program manager | VSTS

**Comment by chshrikh** [comment]
closing the issue, will track in backlog
