### ISSUE TITLE
VSTest task fix for dll search seems to be missing from on premise Team Foundation 2015 Update 3

### ISSUE THREAD

**Issue by bthomsons** [Microsoft/vsts-tasks#3168]
I have an on premise instance of Team Foundation 2015 Update 3 but I am missing this fix from Feb 2016:

[https://github.com/Microsoft/vsts-tasks/commit/fe096977af951100cfaf16e2568e4e08cc0a149b](https://github.com/Microsoft/vsts-tasks/commit/fe096977af951100cfaf16e2568e4e08cc0a149b)

The version of the VSTest task is 1.0.32 and looking in VSTest.ps1 in the folder \agent\tasks\VSTest\1.0.32\ I have this:

```powershell
# check for solution pattern
if ($testAssembly.Contains("*") -Or $testAssembly.Contains("?"))
{
    Write-Verbose "Pattern found in solution parameter. Calling Find-Files."
    Write-Verbose "Calling Find-Files with pattern: $testAssembly"    
    $testAssemblyFiles = Find-Files -SearchPattern $testAssembly -RootFolder $sourcesDirectory
    Write-Verbose "Found files: $testAssemblyFiles"
}
else
{
    Write-Verbose "No Pattern found in solution parameter."
    $testAssemblyFiles = ,$testAssembly
}
```

I would be expecting this:

```powershell
$testAssemblyFiles = @()
# check for solution pattern
if ($testAssembly.Contains("*") -Or $testAssembly.Contains("?"))
{
    Write-Verbose "Pattern found in solution parameter. Calling Find-Files."
    Write-Verbose "Calling Find-Files with pattern: $testAssembly"    
    $testAssemblyFiles = Find-Files -SearchPattern $testAssembly -RootFolder $sourcesDirectory
    Write-Verbose "Found files: $testAssemblyFiles"
}
else
{
    Write-Verbose "No Pattern found in solution parameter."
    $testAssemblyFiles += ,$testAssembly.Split(";")
}
```

This is my version of TFS

![image](https://cloud.githubusercontent.com/assets/20319781/20719481/f62e81f8-b653-11e6-9489-e8a535661299.png)

Looking at the release of Update 3, it looks like this fix should be included:

https://www.visualstudio.com/en-us/news/releasenotes/tfs2015-update3-vs#testing

There doesn't seem to be any way of updating the task other than doing it manually which doesn't seem like the right thing to do.

**Comment by ericsciple** [comment]
you can workaround the issue by including a trivial wildcard, e.g. `?` in place of some char in your file name

the release branches correspond to sprintly releases. releases/m95 was used for TFS 2015 Update 2 and Update 3. releases/m105 was TFS 2017 RTM.

if you upload a task from a release branch, you need to follow the build process. build output gets generated under a folder `_build`. tfx cli can be used to upload the task to your server.

note, the goal of open sourcing the tasks is not to provide a delivery mechanism for newer tasks against an older server. the in-the-box tasks are open source examples for task authors.

another option would be (if you have a small number of agents) to edit the task cache on disk.

**Comment by bthomsons** [comment]
hello @ericsciple thanks for that info. I managed to work around the issue using the wildcard as you suggested. 

Is there a record of what label goes with which TFS release?

**Comment by vimegh** [comment]
@bthomsons In TFS 2017 onwards, build agent version corresponds to branch tag viz. Agent with version 2.105.7 shipped in TFS2017 will be using task definitons from releases/m105 branch.

**Comment by bthomsons** [comment]
@vimegh awesome, thanks for the update
