### ISSUE TITLE
CopyFiles fails with "File name doesn't indicate a full path to a executable file."

### ISSUE THREAD

**Issue by tanyabr** [Microsoft/vsts-tasks#3172]
I've uploaded the CopyFiles tasks exactly as it is from the repository, but it doesn't seem to be working.
I receive the following error:

```
##[warning]File name doesn't indicate a full path to a executable file.
 
Set workingFolder to default: C:\TFSAgent\_work\SourceRootMapping\ec44a2f1-8190-47d8-a3e5-0b70b32c474b\Job-63af1de4-ec55-4287-b2c8-5a070aa7dfb8
 
##[error]The directory name is invalid
```

Any ideas?

**Comment by ericsciple** [comment]
it sounds like you uploaded the source code only and not the layout produced by the build process. contribute instructions are listed in the readme and contain instructions to build

also, master is the active development branch. releases/m* are release branches that correspond to sprintly releases. m95 is tfs 2015 update 2 and 3, m105 is tfs 2017 rtm
