### ISSUE TITLE
Task fails while printing exception code

### ISSUE THREAD

**Issue by HarishMS** [Microsoft/vsts-tasks#3182]
The task failed while printing exception code in catch block.
This should be handled gracefully.

Please refer to following release for detailed logs:
https://mseng.visualstudio.com/VSOnline/_apps/hub/ms.vss-releaseManagement-web.hub-explorer?releaseId=231320&_a=release-logs

**Comment by ericsciple** [comment]
the task that failed the job is `Powershell++` which is not in this repo
