### ISSUE TITLE
Xcode 8 on Sierra build issue regarding the use of /usr/bin/security command

### ISSUE THREAD

**Issue by madhurig** [Microsoft/vsts-tasks#3196]
Copied from issue opened by @Vinzz: https://github.com/Microsoft/vsts-agent/issues/704 

## **Agent version and platform**
Version of your agent? 2.102.0/2.100.1...
<br>
OS of the machine running the agent? OSX/Windows/Linux...
<br>
## **VSTS type and version**
VisualStudio.com or On-Prem TFS?
<br>
If On-Prem TFS, which release, 2015 RTM/QU1/QU2?
<br>
If VisualStudio.com, what is your account name? http://account.visualstudio.com
<br>
## **What's not working?** 
Please include error messages and screenshots
<br>
## **Agent and Worker's diag log**
Logs are located at the `_diag` under agent root folder, agent log prefix with `Agent_`, worker log prefix with `Worker_`. all sensitive information should already be masked out, please double check before paste here.

**Comment by Vinzz** [comment]
@madhurig FYI, one of my colleague made a fix on **xcode-task-utils.js**, and it now builds OK:

78,81c78
<                 // on macOS Sierra, the security command has an issue and cannot get UUID properly
< //              return exec('/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(/usr/bin/security cms -D -i "' + profilePath + '")')
<                 //use open ssl command instead
<                 return exec('/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(openssl smime -inform der -verify -noverify -in "' + profilePath + '")')
---
>                 return exec('/usr/libexec/PlistBuddy -c "Print UUID" /dev/stdin <<< $(/usr/bin/security cms -D -i "' + profilePath + '")')
123,124d119
<     // openssl command may output the string 'Verification successful', so also consider it as noise 
<     output = output.replace('Verification successful','');

**Comment by madhurig** [comment]
@Vinzz: thanks for the update. Your colleague is welcome to submit a pull request with the fix since the code is open source. I will fix it for the next update of VSTS otherwise anyway. Appreciate you sharing the issue and your solution.

**Comment by madhurig** [comment]
Thank you for submitting a PR. 

I verified that the fix is not required in the current code but only needed for the old code used for your on-premises TFS server. The current code only takes the stdout from the security tool and so it does not see the bug from the security tool in Sierra.

**Comment by NicoNB** [comment]
Hello,

I have exactly the same issue.
When this fixe will be available?

**Comment by madhurig** [comment]
@NicoNB: Please confirm the version of onpremise TFS server you are using?

**Comment by NicoNB** [comment]
@madhurig: TFS 2015 update 2

**Comment by madhurig** [comment]
@NicoNB: Unfortunately, further updates are not planned for TFS 2015, since TFS 2017 is available. You can try the fix provided by @Vinzz in the xcode-task-utils.js on your build machine. If that works well for you, I can provide a zip of the task you can upload to your server. 

Thanks,
Madhuri

**Comment by NicoNB** [comment]
Hello @madhurig,
thank you for your answer and thank you @Vinzz for the fix. It works with this fix :-)

**Comment by aaronwjha** [comment]
I am having this issue as well with TFS 2015 update 2 and macos Sierra. What are my options to get this working?

**Comment by aaronwjha** [comment]
I see the fix, thanks. But I’m having a hard time building. Where can I find instructions?

**Comment by madhurig** [comment]
@aaronwjha: The instructions for building for TFS 2015 Update2 are at : https://github.com/Microsoft/vsts-tasks/blob/releases/m95/docs/contribute.md 

Please try it. I will look into uploading the built task to GitHub for other customers to access.  

Thanks,
Madhuri

**Comment by aaronwjha** [comment]
Thanks. I was able to build it.

**Comment by aaronwjha** [comment]
What are the steps to install to TFS 2015?

**Comment by madhurig** [comment]
@aaronwjha: Were you able to upload the task to your server? I use the [TFS CLI](https://github.com/Microsoft/tfs-cli). Since it is on-premise Basic authentication needs to be enabled to upload the task, it can be disabled after the upload. Instructions for setting up basic auth are [here](https://github.com/Microsoft/tfs-cli/blob/master/docs/configureBasicAuth.md)

tfx login --auth-type basic
tfx build tasks upload --task-path <folder of the task that you built>

Thanks,
Madhuri

**Comment by aaronwjha** [comment]
I have run the build and package commands, but I do not see a 'task.zip' package for the common/ios-signing-common task.  I see this error at the end of the package:

> > Linking non-aggregated-layout
> ERROR: Non-aggregated layout for m113 (47c44512) not found in the cache. Publish the latest m113 and then try again.

**Comment by madhurig** [comment]
@ericsciple : Any idea on the error @aaronwjha is seeing?

**Comment by ericsciple** [comment]
@aaronwjha you can just run `npm install && node make.js build --task <task name here>` and the layout for the task you are interested in will be created under the _build folder. the package command is for our CI

**Comment by madhurig** [comment]
@ericsciple: This is for TFS 2015 Update 2, so releases/m95 branch and not master.

**Comment by ericsciple** [comment]
oh ok, then build instructions for releases/m95 are listed in that branch. the readme should contain a link to the contribute doc, which contains the build instructions.

same idea though, the files you're interested in will be under _build.

**Comment by madhurig** [comment]
For convenience of any other users who might run into this, I have compiled the code and tested it against TFS 2015 Update 3. 

[Xcode.zip](https://github.com/Microsoft/vsts-tasks/files/842559/Xcode.zip)

Compatible stable build agent download location: https://github.com/Microsoft/vsts-agent/releases/tag/v2.112.0 

How to install the task on the TFS 2015 server:
1.	Install tfx CLI: https://github.com/Microsoft/tfs-cli  
2.	Connect to the TFS server (user will need to have permissions to upload the task to the collection, collection admins should generally have this permission). Basic auth needs to be enabled to upload the task, it can be disabled after the upload is complete.
Tfx login –auth-type basic
3.	Tfx build tasks upload –task-path <path to unzipped Xcode task folder that contains the task.json>
