### ISSUE TITLE
VSTS Xamarin.ios build issue - The job has been abandoned because agent admins-Mac-mini did not renew the lock. Ensure agent is running, not sleeping, and has not lost communication with the service.

### ISSUE THREAD

**Issue by pallaviak1** [Microsoft/vsts-tasks#3201]
Hi

Abruptly I am facing below issue in my Xamarin.ios project VSTS build as below:
**The job has been abandoned because agent admins-Mac-mini did not renew the lock. Ensure agent is running, not sleeping, and has not lost communication with the service.** 

My observation is,
•	Before few days, build was successful (which includes xamarin.ios project containing solution, running UITest on xamarin test cloud, after build deployment on hockeyapp release step)
•	I restarted my Mac machine which is on premise host, after that I started facing the issue
•	If I am not running my Xamarin UITest on cloud (it means build is taking less time), then build is getting successful but after that, the Release step failed with same above error
•	If my build contain running UITest step, build step is failing, I made sure UITest is successful, Publish artifact step is failing

I have tried re-configuring agent, altogether new agent setup but not success.

Please help.

**Comment by ericsciple** [comment]
@pallaviak1 what agent version are you using?

**Comment by pallaviak1** [comment]
the tar file which I have downloaded from VSTS agent, is vats-agent-osx-x64-2.109.1.tar, I guess 2.109.1 is stating the version.

**Comment by ericsciple** [comment]
@pallaviak1 can you zip your _diag folder under the agent and send it to ersciple (at microsoft dot com)

**Comment by ericsciple** [comment]
i haven't seen a mail come through yet. let me know if i've missed something.

closing the issue here since this is not an issue with the tasks in this repo. it sounds like a flaky network issue, a network configuration issue, an issue with the agent (repo [located here](https://github.com/Microsoft/vsts-agent)), or an issue with the service.
