### ISSUE TITLE
Make Test step ignore test adapters

### ISSUE THREAD

**Issue by phatcher** [Microsoft/vsts-tasks#3223]
Our project is largely written in C# but we also have a C++ client.

We upgraded the NUnit Test Adapter from 3.4.1 to 3.6.0 and now the test step for native tests fail as the behaviour on an unhandled assembly has changed from a warning to an error; I've raised this with the NUnit team.

However, for this test step we don't need the NUnit test adapter, but the step always searches the packages folder and so find the NUnit adapter.

So can we have an option that disables searching the packages folder or can you suggest some other work around - I'm going to regress the version of the test adapter for now, but that's only a short-term solution.

**Comment by acesiddhu** [comment]
there is no good way to do this today. you can delete the packages folder and then try test step. does that work? I want to understand more why using adapter path from packages path wont work. Do you have details of that?

**Comment by phatcher** [comment]
We have two sets of tests, the C# ones using NUnit which needs the NUnit 3 Test Adapter and the C++ which don't need any adapter.

The C# test step run fine, but when the C++ test step runs it picks up the NUnit 3 Test Adapter which fails to handle it and throws an error.

The documentation for the step says "Directory path to custom test adapters. Nuget restored adapters are automatically searched for."

Are you saying if I specify a path here, it won't look in packages - I presumed this was in addition to packages?

**Comment by prawalagarwal** [comment]
Hi @phatcher 

For VsTest task if you specify some path in custom adapters, then it should not look in packages folder anymore and this can be your workaround for now. Please make sure that the path you give is a valid path, otherwise it will throw saying the path does not exist.

Thanks

**Comment by prawalagarwal** [comment]
@phatcher Were you able to try the workaround? Please update us.

**Comment by prawalagarwal** [comment]
Closing this issue. You can mail us at devops_tools[at]microsoft[dot]com for any further issues
