### ISSUE TITLE
TFS Run Functional Test in parallel

### ISSUE THREAD

**Issue by vladaliniacob** [Microsoft/vsts-tasks#3225]
Is there any option which I can use in order to run tests from different assemblies on the same machine in the same time ? In Visual Studio this can be achieved by setting the MaxCpuCount to 0 in a .runsettings file. I'm looking for a similar option in TFS also.

**Comment by acesiddhu** [comment]
@vladaliniacob ideally if the tests are UI test parallelism on same machine will interfere. if you still want to add parallelism you can do via runsettings as you have mentioned and ensure that you check "Distribute tests by number of machines" this option in Run Functional test task

**Comment by vladaliniacob** [comment]
@acesiddhu Unfortunately in the version of TFS that use right now (TFS 2015), that option is not available ... Is there another option ?

**Comment by prawalagarwal** [comment]
@vladaliniacob If you are on an older version, there is no explicit option to enable parallelism. Parallelism happens at container (dll) level, where different dlls are distributed among the machines in the machine group to run tests in parallel.

**Comment by prawalagarwal** [comment]
@vladaliniacob Do you have any other queries on this issue? You can also reach out to us at devops_tools[at]microsoft[dot]com for any further information. 
Thanks

**Comment by vladaliniacob** [comment]
@prawalagarwal No, I don't have any other queries. Thank you for your help.
