### ISSUE TITLE
Azure SQL Database Deployment task doesn't output stderr

### ISSUE THREAD

**Issue by qetza** [Microsoft/vsts-tasks#3228]
When using the Azure SQL deployment task I can see what in the log the output of stdout but when an error occurs the output which is on stderr doesn't appear in the logs.

Running the same command in a console gives the actual error. It would be great if the stderr output was displayed in the log as error messages so that we can see error details.

**Comment by chshrikh** [comment]
@qetza, can you provide the sample command for which you are seeing the issue

**Comment by chshrikh** [comment]
@qetza if possible please share the sample commands with us

**Comment by qetza** [comment]
@chshrikh sorry for the late reply, here is a [dacpac](https://github.com/Microsoft/vsts-tasks/files/660726/mydb.zip) that when run locally through sqlpackage displays the exact error:
![publish-sql-azure](https://cloud.githubusercontent.com/assets/8191369/21308831/0a188f0a-c5dc-11e6-8396-344ab5168760.png)

but when running on the Azure SQL Database Deployment task, the error is not displayed and we only know it's a failure.

**Comment by chshrikh** [comment]
@qetza thanks for sharing the details. We are working on fix. This should get solve with next deployment.

**Comment by chshrikh** [comment]
@qetza closing this issue as fix will be available with next deployment
