### ISSUE TITLE
DeployAzureResourceGroup - Validation Mode lacking error message on failure

### ISSUE THREAD

**Issue by stevenfollis** [Microsoft/vsts-tasks#3234]
Hi, I'm using the [DeployAzureResourceGroup Task](../tree/master/Tasks/DeployAzureResourceGroup) in **Validation Only** mode to validate an ARM Template across multiple regions (configured as Environments in a Release Definition). 

For a particular template, when I Validate via the XPlat CLI I get a nice error message as to why it failed:

![image](https://cloud.githubusercontent.com/assets/5393923/21103072/d7a70976-c04e-11e6-912e-58d8d8c99587.png)

Since DocDB is unavailable in the Brazil South region, the template failed validation. 

However, when I run the same validation in my VSTS Build Definition with the DeployAzureResourceGroup task, I do not get any details other than "failed":

![image](https://cloud.githubusercontent.com/assets/5393923/21103115/14af6c0a-c04f-11e6-9ab1-e3e57f444237.png)

![image](https://cloud.githubusercontent.com/assets/5393923/21103167/4d2b2d76-c04f-11e6-999e-db2fdbb95986.png)

It would terrific to see an error message echoed out to the logs directly in VSTS to better understand why the task failed and expedite debugging. Thanks!

**Comment by hiyadav** [comment]
thanks @stevenfollis  for reporting it, we have fixed it and will be available in the next release.
