### ISSUE TITLE
What's the correct syntax for passing inline PowerShell script arguments?

### ISSUE THREAD

**Issue by jdshkolnik** [Microsoft/vsts-tasks#3245]
Hi,

I can't seem to pass named arguments to an inline script and couldn't find any documentation for it. What's the correct syntax?

**Comment by ericsciple** [comment]
this works for me:
Type: `Inline Script`
Arguments: `-myparam1 'my param value 1' -myparam2 'my param value 2'`
Inline Script:
```
param($myparam1, $myparam2)

write-host "myparam1 is $myparam1"
write-host "myparam2 is $myparam2"
```

**Comment by jdshkolnik** [comment]
I was missing the param($myparam1, $myparam2) statement. Might be useful in the task input tooltip. Thanks.
