### ISSUE TITLE
Logging command updatebuildnumber fails and then succeeds

### ISSUE THREAD

**Issue by TheBeardedLlama** [Microsoft/vsts-tasks#3275]
...but it fails the build...

So I have this:
`Write-Host "##vso[build.updatebuildnumber]$newBuildNumber"`

in a powershell step at the start of my build.

I get the most peculiar behaviour. The step registers a failure, but it still updates 
However, because of the failure, the build does not continue.

Here's the log section:

![image](https://cloud.githubusercontent.com/assets/1180470/21317616/ca305ba8-c5fd-11e6-9726-c836df657373.png)

**Comment by ericsciple** [comment]
@TheBeardedLlama i think something more is going on. the agent intercepts the command from STDOUT, and performs the update build number action. the agent - separate process simply reading STDOUT from your script - doesn't know anything about the powershell variable you used to construct the command. the error message contains `$newBuildNumber")` and indicates to me that your command is malformed. to get a better idea of what is actually being written over STDOUT, either:
1) consult the worker log in the _diag folder under the agent. *i think* it contains the full unparsed `##` command
or 2) change your script to instead print something like `Write-Host "vso[build.updatebuildnumber]$newBuildNumber"` (removed leading `##`) so you can verify the structure of the command you are writing.

also i just noticed you are using the powershell++ task, so i dont know if that is causing any interference (not a task in this repo). if you can repro with the regular powershell task then that would rule that out.

**Comment by TheBeardedLlama** [comment]
@ericsciple you hit the nail on the head with your closing remark

I was told to use that task type and I didn't parse that in my head

switched to standard powershell task and it's all happy

many thanks for the assistance
