### ISSUE TITLE
Not able to proceed with Azure deployment

### ISSUE THREAD

**Issue by shaunbatty** [Microsoft/vsts-tasks#3278]
I am trying to deploy an azure service using TFS with the below configurations - but stuck with "ResourceNotFound: The role name Worker in the extension configuration is invalid." issue.

![image](https://cloud.githubusercontent.com/assets/7004237/21327542/870d1398-c5e4-11e6-92e7-9056026bcd11.png)

After the build is complete, I am trying to depoy the CSPKG in the staging slot. But facing the issue below - 

![image](https://cloud.githubusercontent.com/assets/7004237/21327467/2679003c-c5e4-11e6-87c3-0fc8ee5ee9d1.png)

Now sure how I can get past this. It would be great help if someone can get me past this issue.

**Comment by chshrikh** [comment]
@shaunbatty could you please set the system.debug variable with value as true and share the logs to RM_Customer_Queries at Microsoft dot com or post them here

**Comment by shaunbatty** [comment]
Hi @chshrikh, the logs that I had pasted over there is from the continuous deployment in TFS. The logs are from the test agents that TFS picks up at random which I dont have control over. Is there a way to set the system.debug in build agents? Please let me know.

**Comment by chshrikh** [comment]
@shaunbatty I mean you need to set that variable in your release / build definition.  For build you can refer here https://www.visualstudio.com/en-us/docs/build/define/variables

**Comment by shaunbatty** [comment]
@chshrikh : uploading the logs here. Please let me know if the logs are detailed enough. 
[logs_1183.zip](https://github.com/Microsoft/vsts-tasks/files/674607/logs_1183.zip)

**Comment by chshrikh** [comment]
@shaunbatty could you please confirm "qaMODProvisioning" service exist. Please create an service "qaMODProvisioning" on portal and then try to run this task

**Comment by shaunbatty** [comment]
@chshrikh Yes, the qaMODProvisioning does exist as a cloud service. Please see below screenshot. 

![image](https://cloud.githubusercontent.com/assets/7004237/21530405/84311346-ccf5-11e6-8b2e-402b7fbfa9b8.png)

I am trying to deploy the service in staging slot as you might have known already.

**Comment by vincentdass** [comment]
@shaunbatty , Can you ensure that the extensionConfiguarion(`Extensions `folder) is related to cspkg package that your trying to deploy. It looks like they are irrelevant. 
You can also deploy the package without the Extensions Folder.

**Comment by vincentdass** [comment]
@shaunbatty , IS the issue reolved ?

**Comment by shaunbatty** [comment]
Vicent, the issue still persists. I am not sure what you are talking about in the previous comment. Can you please elaborate that?

**Comment by vincentdass** [comment]
@shaunbatty , Published Cloud service package generally contains **<CloudService>.cspkg**, **ServiceConfiguration.Cloud.cscfg** and **extensions folder**. 

![image](https://cloud.githubusercontent.com/assets/20121508/21976850/c0a79a4e-dbf9-11e6-8006-59afcaa6dab5.png)

Extension Folder contains the configuration settings for each worker/WebRole. 
When the Web/Worker role name doesn't match with the names in the Extensions folder, it raises the error 
**ResourceNotFound: The role name `<role>` in the extension configuration is invalid.**

Can you ensure Worker role exists in **DemoServices.cspkg** ?
If possible, can you try to remove the Extension folder and queue a new release ?

**Comment by vincentdass** [comment]
@shaunbatty , is the issue resolved ?
