### ISSUE TITLE
npm install needs authentication in VSTS hosted build

### ISSUE THREAD

**Issue by stan-dcip** [Microsoft/vsts-tasks#3279]
In Visual Studio Team Services, I am trying to run npm install on a hosted build server prior to my solution getting built. But access to our https://our_url.visualstudio.com/GIT is being denied:

> npm ERR! git clone --template=C:\NPM\Cache_git-remotes_templates --mirror https://our_url.visualstudio.com/GIT/_git/our_url-gulp-bundle-helper C:\NPM\Cache_git-remotes\git-https-our_url-visualstudio-com-GIT-git-our_url-gulp-bundle-helper-2-2-7-88eb446d: Cloning into bare repository 'C:\NPM\Cache_git-remotes\git-https-our_url-visualstudio-com-GIT-git-our_url-gulp-bundle-helper-2-2-7-88eb446d'...

> npm ERR! git clone --template=C:\NPM\Cache_git-remotes_templates --mirror https://our_url.visualstudio.com/GIT/_git/our_url-gulp-bundle-helper C:\NPM\Cache_git-remotes\git-https-our_url-visualstudio-com-GIT-git-our_url-gulp-bundle-helper-2-2-7-88eb446d: Fatal: InvalidOperationException encountered.
> 
> npm ERR! git clone --template=C:\NPM\Cache_git-remotes_templates --mirror https://our_url.visualstudio.com/GIT/_git/our_url-gulp-bundle-helper C:\NPM\Cache_git-remotes\git-https-our_url-visualstudio-com-GIT-git-our_url-gulp-bundle-helper-2-2-7-88eb446d: fatal: Authentication failed for 'https://our_url.visualstudio.com/GIT/_git/our_url-gulp-bundle-helper/'
> 
> npm ERR! git clone --template=C:\NPM\Cache_git-remotes_templates --mirror https://our_url.visualstudio.com/GIT/_git/our_url-gulp-bundle-helper C:\NPM\Cache_git-remotes\git-https-our_url-visualstudio-com-GIT-git-our_url-gulp-bundle-helper-2-2-7-88eb446d: fatal: Authentication failed for 'https://our_url.visualstudio.com/GIT/_git/our_url-gulp-bundle-helper/'

It appears it's simply our access being denied, which I thought I was fixing by going into GIT and adding the 'Project Collection Build Service Accounts' to the team permissions, but that doesn't seem to do the trick. Any idea what i need to do to get the hosted build server to have permissions to our GIT server?

**Comment by Laro88** [comment]
Same issue here - should be an obvious thing but I simply can't get it work.

**Comment by zjrunner** [comment]
The build isn't actually running 'as' a user with access, but it has access to a bearer token for access.  When you use npm to talk to the vsts packaging service, the npm task injects the token into a configuration file to make it work.  talking to git via npm needs additional work.  Sorry for the holiday delay, sending to some other folks internally who know more about the npm::git flow than I.

**Comment by Laro88** [comment]
@zjrunner what is the point of the build user that is configured in vsts? It ought to be a no brainer to link to other self developed modules inside vsts git and be able to integration them properly. If I could put the code that I'm am trying to include on public npm then things would be fine - the reason for using vests is to get company code integrated in a sensible way :-) I sure hope ms will make this work soon.

**Comment by zjrunner** [comment]
There is a distinction between the build user, and the user running an agent process.  An agent process generally runs as a low-priv user (NETWORK SERVICE), and the vsts user is a scoped and limited bearer token that can be used in-build.  That gives some protections to the machine and scope+user control/flexibility to the build definition, but tools that depend on the calling user context can need additional auth assistance, and generally tools need custom auth help anyway if they aren't tightly AAD coupled.  Build definitions know how to work with git and auth, and the npm task knows how to work with npm and auth for the vsts package service (so, configuring your repo url in .npmrc and the task sets it up so npm will properly auth).  In this case it is npm doing a git flow which is a mashup that currently doesn't pre-auth (that is why I mentioned I was forwarding to some other team members -- there are workarounds here).  

Can you let me know how you have this configured?  Do you just have a repo url as a dependency in your package.json?

**Comment by langdonx** [comment]
@stan-dcip @Laro88 Did you ever get this working for you?

@zjrunner In my case, I simply have a VSTS URL as a dependency in `packages.json`.  This works great locally and on Jenkins (where I ultimately build).  I'm using build services on VSTS to version and queue Jenkins builds.

```
  ...
  "dependencies": {
    "angular": "1.6.4",
    "bootstrap": "4.0.0-alpha.6",
    "git+https://xxx.visualstudio.com/xxx/_git/xxx.WebApp.Core#7c960785"
  }
  ...
```

Is the .npmrc trick a workaround or just some ideas?  What exactly would go in the file, and where would it go?  I assume not in the repo, as it might interfere with local development.

**Comment by Laro88** [comment]
We Got it to work with an access tolken in the .npmrc file in root of project. It is a Security hack (shared tolken i git repo) but but so far unavoidable.

**Comment by bryanmacfarlane** [comment]
@Laro88 - note that you shouldn't have to checkin a token to a git repo (bad).  Worst case - you have a step in the build that writes the .npmrc using a secret variable on the definitions variable tab.  But you shouldn't even have to do that - just wanted to point out there's hack - 1 :)

**Comment by lsantos10** [comment]
@Laro88  

> But you shouldn't even have to do that

Could you expand how this could be performed? I'm have not been able to do this

**Comment by keithrob** [comment]
@stan-dcip ,
We have made a bunch of improvements to how the NPM build task handles authentication.  Please take a look at the new options [here](https://www.visualstudio.com/en-us/docs/build/steps/package/npm).
