### ISSUE TITLE
Service Fabric Deploy task should fail deploy task when rollback occurs

### ISSUE THREAD

**Issue by mikanyg** [Microsoft/vsts-tasks#3285]
Just had an incident where a deployment to our Service Fabric cluster, using the SF Deploy Task initiated a rollback due to some failing health checks during upgrade. 

In the build log no warning or error is highlighted and the task it-self is successfull (green icon). If the upgrade was not monitored, then it would easily have slipped through as a successfull upgrade.

I would expect that a rollback showed up in the logs as Warnings or Errors (color high-lighted) and also failing the SF deploy task.

If the current behaviour is "by design" then at least provide an option in the deployment task to mark rollbacks as deployment failures.

**Comment by MikkelHegn** [comment]
Hi mikanyg, we have no current plans to change the deploy task, but are happy to take in pull requests for additional / enhanced features.

**Comment by mikanyg** [comment]
Just tested the latest repo version (1.3.3) of the ServiceFabricDeploy task. It fails as expected on upgrade rollbacks, so I guess it has been fixed.

**Comment by MikkelHegn** [comment]
@mikanyg Thanks - apparently this was added in a November check in - 1.2.0: https://github.com/Microsoft/vsts-tasks/pull/3137 - I think this is the one that got rolled out the beginning of this year.

Sorry for not catching that in the original repsonse :-)
