### ISSUE TITLE
Revision not incrementing if updating build number through build.updatebuildnumber

### ISSUE THREAD

**Issue by scripniciuc** [Microsoft/vsts-tasks#3289]
In order to distinguish between official releases (from our master branch) and private releases from feature branches, I'm trying to update a build number depending on the source branch of the build. To achieve this, I have the build number configured as $(Date:yy).$(Date:MMdd).[BuildType]$(Rev:rrr). Inside a task in the build definition I then replace [BuildType] with either 1 or 2 depending on whether the source branch is 'refs/heads/master', by using the following powershell command:

`Write-Host "##vso[build.updatebuildnumber]$BuildNumber"`

The problem is that the revision `$(Rev:rrr)` doesn't seem to get incremented build-over-build. I assume this is because this should only update if nothing else in the build number has changed.

Am I taking the wrong approach to achieve my goal of having a different build number format depending on the source branch? Or is there anything else I could do to ensure the revision gets updated?

**Comment by bryanmacfarlane** [comment]
please create an issue in the vsts-agent repro.  not an issue with one of the tasks in this repo ..
