### ISSUE TITLE
WindowsMachineFileCopy using /xd doesnt honor multiple machines

### ISSUE THREAD

**Issue by amccool** [Microsoft/vsts-tasks#3299]
when WindowsMachineFileCopy is used to copy to multiple machines, and the /XD option is used in the additional arguments in order to exclude a directory, the path specified needs to be able to replace the drive letter with all the servers in the list.

e.g.
(server1, server2, server3)
`/XD c:\XXXX`

needs to become
```
\\server1\c$\XXXX
\\server2\c$\XXXX
\\server3\c$\XXXX
```

similar to the way done with the destination path

**Comment by chshrikh** [comment]
@amccool /XD is used for excluding the source. So in logs you can see "Exc Dirs : \\Sourceserver1\SkipThisFolder" .  this will not get resolve as target paths.

**Comment by amccool** [comment]
I need a bit more clarification.    If the destination contains a directory I do not wish to be deleted and this folder also does not exist in the source, I can use the `/XD` option to prevent that destination directory from being deleted, correct?

Further, what is the syntax for the `/XD` directory specification?
Do I include the source drive letter, or do I use the UNC format of the `\\machinename\share letter` ?

**Comment by chshrikh** [comment]
1)If the destination contains few directories and you do not want to delete all of them, ( and same directories do exist / does not exist with source does not matter), ensure you do not use clean target option in advance section of task. This will ensure nothing gets cleaned from target. you may not need to use /xd for this. 
2) If the destination contains few directories and you not want only specific directory to be deleted, ( and same directory do exist / does not exist with source does not matter), ensure you use clean target option in advance section of task and use /xd option to prevent the specific folder form getting cleaned from target but you need to give the destination path as \\targetServer1\c$\XXXX ( as you mentioned in your first post), as of now task does not resolve it for you. 
Also this will not work for multiple machines. You may need to add different file copy task for each destination server. Please check below image for same 

![image](https://cloud.githubusercontent.com/assets/11972852/21514634/3a399644-cced-11e6-96d5-2ed6003bf385.png)

**Comment by amccool** [comment]
Thanks for the clarification.    I indeed do have the 2nd scenario.  Thanks for marking this issue with "enhancement"

**Comment by mvvsubbu** [comment]
@amccool 

Using multi config feature in Release you can achieve what you are looking for without adding multiple instances of task. I have given details with screen shots below

1. Enable multi-configuration
a. Select Run on Agent
b. Expand Run on multiple agents in parallel section
c. Set **Type of parallelism** to : Multi-configuration
d. Set **Multipliers** to **Machines**
e. Set Maximum number of agents to, some number depending on how many at a time you want to do.

Refer screen shot below 

![enable multi config](https://cloud.githubusercontent.com/assets/11993108/26616929/cff73774-45ef-11e7-9add-c48e6c373626.jpg)

2.  Define multipliers variable in variable section with comma separated list of machine names on which you want to copy. Refer screen shot below 

![variables](https://cloud.githubusercontent.com/assets/11993108/26616971/1ec43c8a-45f0-11e7-806c-a3d4b373f774.jpg)

3. Make of the multiplier variable in your windows file copy as illustrated below. This does the trick of changing machine name for each config and execute the task.

![task usage](https://cloud.githubusercontent.com/assets/11993108/26616997/4fb53b82-45f0-11e7-8de7-b0abd9be6710.jpg)
