### ISSUE TITLE
web app config files overwritten by web job deployment

### ISSUE THREAD

**Issue by Sshnyari** [Microsoft/vsts-tasks#3306]
We have a web app and a webjob that need to be deployed to an App service.
We use one "Azure App Service Deploy" task for each one of them to do this.
They both have Config Folder containing some xml files (different contents for each project)
Web App : 
![image](https://cloud.githubusercontent.com/assets/16015858/21480577/af7fa55a-cb5e-11e6-95b7-d27d4cbf850c.png)

WebJob
![image](https://cloud.githubusercontent.com/assets/16015858/21480596/d33e7e3a-cb5e-11e6-98f5-07145acb0482.png)

The web app gets deployed before the webjob in the same release.

When the web job is deployed, the webapp's Config folder contents get replaced by the web job's config files.

Here is an edited section of the webjob deployment task

> 2016-12-26T09:56:24.8650899Z Info: Adding file (WebAppName\app_data\jobs\triggered\WebJobName\zh-Hant\Microsoft.Data.Services.Client.resources.dll).
> 2016-12-26T09:56:24.8680900Z Info: Adding file (WebAppName\app_data\jobs\triggered\WebJobName\zh-Hant\System.Spatial.resources.dll).
> 2016-12-26T09:56:24.8680900Z Info: Adding file (WebAppName\app_data\jobs\triggered\WebJobName\zxing.dll).
> 2016-12-26T09:56:24.8680900Z Info: Adding file (WebAppName\app_data\jobs\triggered\WebJobName\zxing.pdb).
> 2016-12-26T09:56:24.8680900Z Info: Adding file (WebAppName\app_data\jobs\triggered\WebJobName\zxing.xml).
> 2016-12-26T09:56:24.8680900Z Info: Updating file (WebAppName\bin\Config\log4net.config).
> 2016-12-26T09:56:24.8700904Z Info: Updating file (WebAppName\bin\Config\secrets.config).
> 2016-12-26T09:56:24.8700904Z Info: Updating file (WebAppName\bin\ConnectionStrings.config).
> 2016-12-26T09:56:24.8700904Z Info: Updating file (WebAppName\bin\WebJobName.exe).
> 2016-12-26T09:56:24.8700904Z Info: Updating file (WebAppName\bin\Settings.job).
> ...
> 2016-12-26T09:56:24.8710902Z Info: Updating file (WebAppName\bin\Web.config).
> 2016-12-26T09:56:24.8710902Z Info: Updating file (WebAppName\Config\log4net.config).
> 2016-12-26T09:56:24.8710902Z Info: Updating file (WebAppName\Config\secrets.config).
> 2016-12-26T09:56:24.8710902Z Info: Updating file (WebAppName\ConnectionStrings.config).
> 2016-12-26T09:56:24.8710902Z Info: Adding ACL's for path (WebAppName)
> 

Is this a normal behaviour ?

**Comment by mvvsubbu** [comment]
Sorry for the issue. 

When we deploy App Service, the content you gave in the task gets uploaded to the corresponding mapping path of the App Service. 

So now when you are deploying Web Job here also the content gets uploaded to mapping root folder. To avoid over writing of the App Service files you could generate the Web Job build out to have actual job exes in root folder of something like this App_Data\Jobs\Continuous\<WebJobName>

**Comment by Sshnyari** [comment]
For the moment, we just inverted the tasks order, since Config folder in the app's root is only used by the web app. The web job use the one in the bin folder I think. Anyway, for this particular App Service, all the necessary settings are in the azure app settings.

How can we put the job exes in the App_Data during the build definition ?
It is quiet troublesome to do it in Pre/Post-Build script since the "webjob-publish-settings.json" configuration wouldn't be taken into account.

Is there a plan to change this behaviour or to package a web app's deployment and its webjobs into a single task ?

**Comment by mvvsubbu** [comment]
The following post describes how to add a web job to existing solution with web app. Follow the post to generate msbuild output. 

https://blogs.msdn.microsoft.com/tfssetup/2016/05/18/deploying-and-schedule-azure-webjobs-from-vsts-to-azure-web-app-with-bonus-cron-scheduling/

Build output of the webapp zip contains both the web app and web job. I tried this on a sample project here is the output for that app.

![image](https://cloud.githubusercontent.com/assets/11993108/21537143/e43cac6a-cdb2-11e6-8f1f-73f7e9525204.png)

![image](https://cloud.githubusercontent.com/assets/11993108/21537153/1832d008-cdb3-11e6-81a5-5d99074804c9.png)

Now use App Azure App Service and deploy the App Service using this zip file. Now both App Service and corresponding job should be updated. Can you try this works for you not and let us know?

**Comment by Sshnyari** [comment]
Actually, that's partially what we are doing.
The msbuild generates both webjob and web app zip files
But we have 2 deploy tasks :
- one that uses the web app zip file
- one that uses the web job zip file

So only the first task is needed to deploy both the web app and web job ?
Should we specify all zip files in one task ?
How can we do that (multple targets for one task) ?

**Comment by vincentdass** [comment]
@Sshnyari , Building the solution with MSBuild generates zip for Web App and web jobs. 
Deploying only the `web app zip file` is sufficient as it contains the web job files. You can view the web job files in web app zip file inside `app_data` folder.
Please do follow the steps provided by @mvvsubbu ,and let us know if u face any issue.

**Comment by Sshnyari** [comment]
It doesn't seem to work. The Web app zip file doesn't contain an app_data folder.
Here is the msbuild arguments we use : 
`/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.stagingDirectory)" /p:SkipExtraFilesOnServer=true`

**Comment by vincentdass** [comment]
@Sshnyari , Can u send the debug logs logs of Build (Package creation)  and Release (App Service Deploy Task)  to  `RM_Customer_Queries@microsoft.com`  with this issue link?

**Comment by vincentdass** [comment]
To deploy web job to Azure App Service, it must be added as a part of Web App solution (It shouldn't be created seperately).

Web Job can be added to Web App solution using the below step.
![image](https://cloud.githubusercontent.com/assets/20121508/21638592/e822f97c-d291-11e6-84c3-af4141bdcb70.png)

You can find the web job bundled with web app solution in Web Deploy package using these [steps](https://github.com/Microsoft/vsts-tasks/issues/3306#issuecomment-269582714).

**Comment by NenoLoje** [comment]
@vincentdass  A related question to this thread:

When using a single `.zip` package that contains both the web app and one or more web jobs. How do I replace the parameters of those web jobs?

The **Deploy Azure Web App** task only takes a single `.SetParameters.xml` file and that contains the settings from the Web App only. Any hints?

Thanks,
--Neno

**Comment by vincentdass** [comment]
@NenoLoje, you can use XML Variable substitution to update values in web.config / WebJob.exe.config.
![image](https://user-images.githubusercontent.com/20121508/27118225-f8930e02-50f7-11e7-8acc-096e63c2d1b4.png)
The values are updated only in *.config files and it may get overridden by parameters.xml during deployment (MSDeploy).
