### ISSUE TITLE
Shouldn't the Gulp task demand gulp?

### ISSUE THREAD

**Issue by ricardoserradas** [Microsoft/vsts-tasks#3315]
As the Hosted Build agent has this capability, wouldn't it be interesting if this task demands it?

**Comment by ericsciple** [comment]
no the [task doesn't require gulp to be in the PATH](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Gulp/gulptask.ts#L19) (which is what the agent checks to interpret the capability)
