### ISSUE TITLE
Build Xamarin.iOS: Failure of "'OutputPath' property is not set for this project" with custom Build Configuration on xBuild 

### ISSUE THREAD

**Issue by jamesatgithub** [Microsoft/vsts-tasks#3323]
we have a custom build configuration in our VS solution and it builds fine on local VS + local Mac Build Agent, but got below error with VSTS Build Xamarin.iOS task.  Is the custom build configuration not supported or any special configuration we should do on VSTS task?

"Target ResolveProjectReferences:
Project "/Users/dev1/myagent/_work/1/s/AAA.Core.PCL/BBB.Core.PCL.csproj" (default target(s)):
Target _CheckForInvalidConfigurationAndPlatform:
/Library/Frameworks/Mono.framework/Versions/4.6.2/lib/mono/xbuild/14.0/bin/Microsoft.Common.targets: error : 'OutputPath' property is not set for this project. Usually this is caused by invalid Configuration/Platform combination. Original values: Configuration: Release_AAABBB Platform: iPhone.
Task "Error" execution -- FAILED"

**Comment by jamesatgithub** [comment]
this is not a bug. in the Build Xamarin.iOS task, the Solution property should be the .sln file instead of the ios .proj file and since my mac didn't have android sdk installed I added a iOS only .sln and fixed the issue

reference: https://bugzilla.xamarin.com/show_bug.cgi?id=25480

**Comment by campersau** [comment]
I had the same issue and added an `Or` condition to the release property group in the PCL project:

```xml
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' Or '$(Configuration)|$(Platform)' == 'Ad-Hoc|iPhone' ">
```

**Comment by tompi** [comment]
@campersau Thank you, this solved my problem as well! (I have extra PCL-code I download in a post-build script)
