### ISSUE TITLE
Subversion Repository - Revision-field not accepting variables

### ISSUE THREAD

**Issue by RPaardekam** [Microsoft/vsts-tasks#3327]
For one of our projects I am using a Subversion Repository endpoint. I would like to set the revision at queue-time, which means I created a variable, e.g. $(SvnPinnedRevision). I was hoping I could use that variable in the Revision-field of the Repository-tab but that field seems to be restricted to only allow numeric values, or the word HEAD. Is it possible it could be extended to accept variables as well?

**Comment by AlexRukhlin** [comment]
Hi,

I've added this request to our backlog. 

Thanks,
Alex

**Comment by jpricketMSFT** [comment]
Since this issue has been added to our backlog and is not an issue with the tasks themselves. I am closing this issue.
