### ISSUE TITLE
Task packages are including dev depencies modules as well

### ISSUE THREAD

**Issue by mvvsubbu** [Microsoft/vsts-tasks#3336]
Run node make.js build --task AzureRmWebAppDeployment the resulting task output folder contains dev dependencies as in the package. 

This is happening because we are running npm install instead of npm install --production
 npm install e:\Enlistments\GitHub\vsts-tasks\_build\Tasks\Common\webdeployment-common

**Comment by ericsciple** [comment]
Fixed as part of this commit: https://github.com/Microsoft/vsts-tasks/commit/0ea764c87a840378c03870a09017c638c934f88e

Tasks can declare dev dependencies in a package.json under the task's Tests folder. I also added validation so the build fails if devDependencies are defined in the wrong place.
