### ISSUE TITLE
Node Modules have to be duplicated for each task

### ISSUE THREAD

**Issue by knom** [Microsoft/vsts-tasks#3338]
Each task requires it's own `node_modules` folder.
Which results in a HUGE size of the VSIX file.

Is there a way the node_modules folder could be shared?

**Comment by ericsciple** [comment]
@knom if you're npm version is less than 3, then switching to npm3 will cut down on the size of the node_modules folder. other than that, no there is no way today to reference common files across tasks within the vsix

**Comment by ericsciple** [comment]
sent to sanyogita as fyi for future consideration
