### ISSUE TITLE
Azure Web App Deployment doesn't show web apps in non-default Resource Groups

### ISSUE THREAD

**Issue by FramnkRulez** [Microsoft/vsts-tasks#3351]
I am unable to get the dropdown in the Azure Web App Deployment task to list any web application that I have which is in a non 'default' resource group on Azure.  For instance, if I provision a new ASP.NET Core web application to Azure and elect to create a 'new' named resource group, the resultant web app will not be available from the Azure Web App Deployment task.

However if I follow the same process for the ASP.NET Core web application and select one of my default resource groups (i.e. Default-USEast) it seems to show up just fine.

**Comment by vincentdass** [comment]
@FramnkRulez , Can you please provide more context on the issue ?
Are you referring to App Service plan or Resource Group ?

**Comment by FramnkRulez** [comment]
I'm not sure I understand the question... as I understand Azure, a ResourceGroup is a container for the App Service Plan and the App Service itself.  I am referring to the App Service (not the plan) that I want to deploy using the Azure Web App Deployment task.  Everything in Azure now appears to be grouped under a Resource Group even classic web applications which were bucketed under default resource groups.  Is that understanding correct?

**Comment by vincentdass** [comment]
@FramnkRulez , Yes, every resource is grouped under Resource Group. Can you provide some context on **`non 'default' resource group`** and **`create a 'new' named resource group`**

**Comment by FramnkRulez** [comment]
I had several classic Azure web applications that were automatically rolled into default resource groups based on their region when Resource Groups were introduced to Azure.  For instance, Default-Web-EastUS.  I can use the Azure Web App Deployment task to target my app content to any of these default resource groups.

However when I use Visual Studio to publish if I select to create a new Resource Group for my web application I am unable to select my web app from the dropdown in the Azure Web App Deployment build task.  It is only seeing the web applications that were automatically rolled into default resource groups.

**Comment by vincentdass** [comment]
@FramnkRulez , which task are you referring to ? `Azure Cloud Service Deployment` or `Azure App Service Deploy` task ?

**Comment by FramnkRulez** [comment]
I'm using TFS 2015 Update 3 on-premise and the task is named Azure Web App Deployment.  I do not see one named Azure App Service Deploy, is this on hosted VSTS only?

**Comment by vincentdass** [comment]
@FramnkRulez , is this issue resolved ? Is the new app shown in drop-down of Web App (in AzureRM Web App Deployment task) ?

**Comment by FramnkRulez** [comment]
I do not see the 'AzureRM Web App Deployment' on our server.  We are using TFS2015 Update 3 on-premise.

**Comment by vincentdass** [comment]
@FramnkRulez , `AzureRM Web App Deployment task` is not available in TFS-15 U-3 On-Premise.
You need to upgrade your [TFS](https://www.visualstudio.com/en-us/news/releasenotes/tfs2017-relnotes) to get the task.

You can also upload the [task](https://github.com/Microsoft/vsts-tasks/tree/releases/m105/Tasks/AzureRmWebAppDeployment) to your TFS. Please change the [task-ID ](https://github.com/Microsoft/vsts-tasks/blob/releases/m105/Tasks/AzureRmWebAppDeployment/task.json#L2)before uploading the above task.

**Comment by vincentdass** [comment]
@FramnkRulez , Is the issue resolved ?

**Comment by FramnkRulez** [comment]
You mentioned upgrading TFS however I do not see an upgrade to TFS on-premise beyond update 3 which is already installed.  Is this going to be released as a TFS on-premise update?

**Comment by vincentdass** [comment]
@FramnkRulez , There is no updated after U-3. You need to get the latest [release](https://www.visualstudio.com/en-us/news/releasenotes/tfs2017-relnotes). 
You can upload the task, if u do not want the latest  TFS.

**Comment by FramnkRulez** [comment]
Thanks I didn't realize that 2017 was out already.
