### ISSUE TITLE
Current Xamarin.Android version appears to have a bad mono-symbolicate install

### ISSUE THREAD

**Issue by psycosyd** [Microsoft/vsts-tasks#3353]
When setting up a new Xamarin.Android Release build I was seeing the following error:

"C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(2289,3): Error MSB3073: The command ""C:\Program Files (x86)\MSBuild\Xamarin\Android\mono-symbolicate" store-symbols 

This appears to be in line with a current known issue with Xamarin.Android pre C8SR1:
https://bugzilla.xamarin.com/show_bug.cgi?id=46279

Updating the installed version of Xamarin.Android should also include a good version of mono-symbolicate

**Comment by ericsciple** [comment]
@psycosyd this sounds like a machine prereq issue rather than an issue with the task. is that correct? if so, are you saying there is an issue with the version of Xamarin installed on the "hosted" build machine?

**Comment by psycosyd** [comment]
@ericsciple To my understanding that is correct. The hosted build machines likely need an update of Xamarin.Android based on what I have gathered.

**Comment by madhurig** [comment]
@psycosyd: Thanks for notifying us.
It looks like Xamarin update Cycle 9 which has the fix is not available in stable channel yet. I am following up on whether it would be better to wait for Cycle 9 or go back to an older stable channel build. 

Thanks,
Madhuri

**Comment by psycosyd** [comment]
@madhurig I checked with Brendan Zagaeski. C8SR1 and later builds are all fine, the QA team is explicitly testing for it. The fix in C9 is that it will be no longer possible for the bad installer to be generated in the first place. Upgrading to latest stable, or at least C8SR1 should provide the fix

**Comment by madhurig** [comment]
Cycle 9 which has the fix is now available on the hosted build VMs.

**Comment by EArtem** [comment]
Hi. We facing this issue now with executing SignAndroidPackage on Mac OS X in release configuration. What is interesting:
- With executing /Library/Frameworks/Mono.framework/Commands/msbuild /t:SignAndroidPackage /p:Configuration=Release /Users/workspace/Droid/Project.Droid.csproj via terminal all is fine.
- With executing the same command in Jenkins its failed:
_CopyPackage:
  Copying file from "/Users/workspace/Droid_APK_Release/src/cross-platform/Platform//Droid/obj/Release/android/bin/name.android.apk" to "bin/Release/name.android.apk".
  Creating directory "bin/Release/name.android.apk.mSYM".
  "/Library/Frameworks/Xamarin.Android.framework/Versions/Current/bin/mono-symbolicate" store-symbols "bin/Release/name.apk.mSYM" "obj/Release/android/assets"
  /Library/Frameworks/Xamarin.Android.framework/Versions/Current/bin/mono-symbolicate: line 6: exec: mono: not found
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2194,3): error MSB3073: The command ""/Library/Frameworks/Xamarin.Android.framework/Versions/Current/bin/mono-symbolicate" store-symbols "bin/Release/name.apk.mSYM" "obj/Release/android/assets"" exited with code 127. [/workspace/Droid_APK_Release/src/cross-platform/Platform/Targets/Droid/project.Droid.csproj]
Done Building Project "/Users/workspace/Droid_APK_Release/src/cross-platform/Platform/Droid/name.Droid.csproj" (SignAndroidPackage target(s)) -- FAILED.
