### ISSUE TITLE
App.config not used

### ISSUE THREAD

**Issue by RobBowman** [Microsoft/vsts-tasks#3363]
I have a unit test dll containing Specflow tests. These tests make use of steps that are contained within a different (common) dll and so I have added the following App.config file to the unit test project so that the common steps can be found:

`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="specFlow" type="TechTalk.SpecFlow.Configuration.ConfigurationSectionHandler, TechTalk.SpecFlow"/>
  </configSections>
  <specFlow>
    
    <unitTestProvider name="MsTest"/>
    <stepAssemblies>
       <stepAssembly assembly="LCC.Integration.Common.Components" /> 
    </stepAssemblies>
  </specFlow>
<startup><supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.5.1"/></startup></configuration>
`

This works fine when I execute locally from within VS. However, when I executed using the "Run Functional Tests" tasks, I first got an error that nUnit couldn't be found (my App.config should ensure that MsTest is used rather than nUnit). After deploying nUnit to the GAC I got an error that the custom steps couldn't be found. This suggests that the App.config file is not being read by whatever is executing the tests. 

I have set the "Copy to Output Directory" property of the App.config file to "Copy always", and can confirm that it is available in the \bin\Release folder on my build server.

More info here: [http://stackoverflow.com/questions/41447029/run-functional-tests-task-and-specflow](url)

How can I ensure that the App.config of the test assembly is used?

**Comment by kaadhina** [comment]
Please ensure you have copied the config file to the test drop location on the test agent machine.
If you are still hitting this issue, please reply back to devops_tools@microsoft.com with the test agent logs at C:\dtalogs on the test agent machine, and also build logs after setting build variable system.debug=true.

**Comment by RobBowman** [comment]
Hi, I tried to send you an email but got the following message: 

> The groups only accept messages from people in their organization or on their allowed senders list, and your email address isn't on the lists.

Are you able to email me at rob.bowman147@gmail.com ?

**Comment by tanvi-soni** [comment]
Hi Rob,
We have received your email. We will take a look at it.

**Comment by kaadhina** [comment]
Updating the outcome here: It turned out to be because of a missing config file in the test assembly folder. 
Any dependency such as the config file, referenced binaries need to be copied to the folder from which you are running the tests in the target machine.
Closing this issue.
Rob, if you face any other issue, feel free to open another ticket or send us a mail as above, for us to take it forward. 
Thanks.
