### ISSUE TITLE
What's the right syntax to pass a hash-table as a parameter to PowerShell build step?

### ISSUE THREAD

**Issue by acosmici** [Microsoft/vsts-tasks#3367]
Hello guys,

Could you please help me to add tags to an Azure storage account with the following line in VSTS?

New-AzureRmStorageAccount -ResourceGroupName "testing" -Name "testing123456devcsp" Location "North Europe" -Type "Standard_LRS" -Tag @{Owner = "Undifined"; Programme = "Undifined"; Workstream = "Undifined"; CostCentre = "Undifined"}

I am receiving the following error:    Duplicate keys '' are not allowed in hash literals.

I know that were some issues with passing hash-table to Powershell with VSTS, could you please help me to fix this issue?

Thanks,
Adrian

**Comment by ericsciple** [comment]
@acosmici which build task are you using?

**Comment by ericsciple** [comment]
i'm not able to repro the issue. here's what i tried:
Add PowerShell Script task:
Type: Inline Script
Inline Script:
```
function foo { $args }

foo -ResourceGroupName "testing" -Name "testing123456devcsp" Location "North Europe" -Type "Standard_LRS" -Tag @{Owner = "Undifined"; Programme = "Undifined"; Workstream = "Undifined"; CostCentre = "Undifined"}
```

based on the output of my attempted repro, it looks like the hashtable was passed correctly

**Comment by acosmici** [comment]
@ericsciple in fact I had a issue trying to pass powershell parameters from on script to another, the problem is fixed now.

Thanks,

**Comment by nakahparis** [comment]
Hello @acosmici,
I'm trying to pass a hashtable from one PowerShell script task to another one. It seems that's not possible with the classic syntax : ##vso[task.setvariable variable=testvar;]testvalue
Have you find a way to pass an object or hastable to next tasks ?
