### ISSUE TITLE
ARM Resource Deployment DNS Regular Check Failure

### ISSUE THREAD

**Issue by iamthemovie** [Microsoft/vsts-tasks#3373]
When ever any changes to our infrastructure ARM templates occur we always build and destroy a temporary environment as part of our CI/CD pipeline.

Quite often though the builds fail due the VSTS ARM Template task not picking up our DNS records for our App Service.

To be clear, the DNS Records are there and have been for months. 3/10 times it succeeds and we just have to keep pressing queue until it succeeds at the moment. They test build uses a static DNS record which is never changed or updated.

Our DNS is hosted by Cloud Flare.

Bug perhaps?

Below is the error:
```
{
"status": "Failed",
  "error": {
    "code": "ResourceDeploymentFailure",
    "message": "The resource operation completed with terminal provisioning state 'Failed'.",
    "details": [
      {
        "code": "DeploymentFailed",
        "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.",
        "details": [
          {
            "code": "NotFound",
            "message": "{\r\n  \"Code\": \"NotFound\",\r\n  \"Message\": \"Hostname 'REDACTED' does not exist.\",\r\n  \"Target\": null,\r\n  \"Details\": [\r\n    {\r\n      \"Message\": \"Hostname 'REDACTED' does not exist.\"\r\n    },\r\n    {\r\n      \"Code\": \"NotFound\"\r\n    },\r\n    {\r\n      \"ErrorEntity\": {\r\n        \"Code\": \"NotFound\",\r\n        \"Message\": \"Hostname 'REDACTED' does not exist.\",\r\n        \"ExtendedCode\": \"04020\",\r\n        \"MessageTemplate\": \"Hostname '{0}' does not exist.\",\r\n        \"Parameters\": [\r\n          \"REDACTED\"\r\n        ],\r\n        \"InnerErrors\": null\r\n      }\r\n    }\r\n  ],\r\n  \"Innererror\": null\r\n}"
          }
        ]
      }
    ]
  }
}
```

This is the binding in the template:
```
{
    "apiVersion": "2015-08-01",
    "type": "hostNameBindings",
    "name": "HOSTNAME",
    "dependsOn": [
        "SITE"
    ],
    "properties": {
        "siteName": "SITENAME",
        "domainId": null,
        "hostNameType": "Verified"
    }
}
```

These failures are purely down to DNS, worked 3rd time just now:

![image](https://cloud.githubusercontent.com/assets/369020/21697239/4dd89db0-d389-11e6-93bd-a2b02ba3d9cf.png)

**Comment by aydey** [comment]
This failure is coming from Azure Resource Group Manager and not the task. You could try to repro the issue from the command line to confirm the same. Also from your description it seems that you are destroying and creating the environment again - does this mean deleting and creating the azure app? The error in that case could be due to some race condition for the host name to be verified from the azure side. You might need to follow it up with the Azure Web App team for further clarification on this.

**Comment by aydey** [comment]
I am closing this issue owing to the fact that the failure is coming from Azure.

**Comment by iamthemovie** [comment]
Thanks for the information I will pass this issue on as reference. Thanks!
