### ISSUE TITLE
Execute Azure SQL : DacpacTask release failed due to not clearing IP Range

### ISSUE THREAD

**Issue by mrjono1** [Microsoft/vsts-tasks#3374]
When using Execute Azure SQL : DacpacTask (SqlAzureDacpacDeployment) I was getting failed released then eventually found out that I had an issue in the firewall section. Due to the line number errors in the powershell scripts.

1. Expand Firewall section
2. Select Specify Firewall Rules Using: IPAddressRange and type in a StartIP Address and EndIP Address values click save
3. Select Specify Firewall Rules Using: AutoDetect and click save (this does not clear the StartIP Addressand EndIP Address values, causing my build to fail)

Workaround
1. Expand Firewall section
2. Select Specify Firewall Rules Using: IPAddressRange
3. Clear in a start and end ip values
3. Select Specify Firewall Rules Using: AutoDetect
4. Click save (this will now clear the IP values and allow build to work)

Fix
When Selecting Specify Firewall Rules Using: AutoDetect clear the StartIP Address and EndIP Address automatically.

**Comment by vincentdass** [comment]
@mrjono1 , thanks for reporting the issue. The values will be shown in UI, but it is validated in the [task](https://github.com/Microsoft/vsts-tasks/blob/releases/m109/Tasks/SqlAzureDacpacDeployment/Utility.ps1#L55).

Can you enble **system.debug = true** and queue a new release ?
In the logs, you can find that the IP address range is autodetected and not taken form input field value.

**Comment by vincentdass** [comment]
@mrjono1 , Is the issue resolved ?

**Comment by vincentdass** [comment]
@mrjono1 , if the issue is not resolved, please feel free to open the thread.

**Comment by mrjono1** [comment]
sorry I didn't get back to you I was on unable to get the logs in time. The code you pointed out looks good, not sure what happened to me
