### ISSUE TITLE
Running Get-AzureSBNamespace in the context of Principal Authentication

### ISSUE THREAD

**Issue by RDalziel** [Microsoft/vsts-tasks#3391]
Hey Folks, wondering if anyone can shed some light here. I'm looking to remove any usage of credentials on our release templates and trying to figure out how to run Get-AzureSBNamespace within a RM Context.

Locally, running "Login-AzureRMAccount" and hitting Get-AzureSBNamespace everything returns fine. However on the build server (using the same Initialize-Azure functions as the AzurePowershell tasks) i'm getting issues trying to hit this command.

On the hosted agents - get 

"No default subscription has been designated. Use Select-AzureSubscription -Default <subscriptionName> to set the default subscription."

Anyone have any pointers here?

**Comment by RDalziel** [comment]
Update - I've managed to get in via the following APIs https://docs.microsoft.com/en-us/rest/api/servicebus/ Getting an Access token to management.azure.com using the principals key and ID.

Still got problems on the hosted agents, but progress at least!

**Comment by vincentdass** [comment]
@RDalziel , We **cannot run Get-AzureSBNamespace within RM Context,** it required Azure Classic Connection.
It runs on local box because, an instance of AzureSubscription is already saved in the machine.
You can view the instance by running `Get-AzureSubscription`.

**Comment by vincentdass** [comment]
@RDalziel , Is the issue resolved ?

**Comment by RDalziel** [comment]
I managed to figure it out with the API, however since then i've moved onto using the new(ish) RM Powershell command as it cuts my code a considerable amount!

"Get-AzureRmServiceBusNamespaceKey"
