### ISSUE TITLE
[Feature Request]service-fabric-versioning task - allow to specify single service/artifact for version update

### ISSUE THREAD

**Issue by mkosieradzki** [Microsoft/vsts-tasks#3397]
It would be useful very useful able to override version of single or multiple artifacts only eg. MyService1/MyCodePackage;MyService1;MyService2/MyDataPackage

**Comment by ericsciple** [comment]
User voice is probably a better place to request features

**Comment by RoopeshNair** [comment]
@mkosieradzki can you please vote on User Voice to get right prioritization.
I have added this to backlog, we will re-evaluate based on user asks. 
Closing it now.
