### ISSUE TITLE
Deploy AzureRM App Service Additional Arguments doesn't work with v2.1.9 of Azure App Service Deploy

### ISSUE THREAD

**Issue by dawilliams** [Microsoft/vsts-tasks#3415]
The upgrade of the Azure App Service Deploy task to version 2.1.9 on the hosted agents has broken my values in the Deploy AzureRM App Service Additional Arguments field.  These values worked in version 2.1.8.

The error is...
##[error]Error: The regular expression 'MesaDevAdmin\Logs' is invalid.
Error: parsing "MesaDevAdmin\Logs" - Unrecognized escape sequence \L.

and the config is 
![image](https://cloud.githubusercontent.com/assets/581113/21895781/8750bc06-d8a9-11e6-9cb2-0c4140313a40.png)

**Comment by vincentdass** [comment]
@dawilliams, thanks for reporting the issue.
Can u change the double quotes in **Additional arguments** to single quotes ?
`-skip:SkipAction=Delete,objectName=dirPath,absolutePath='$(webAppName)\\Logs'`

**Comment by dawilliams** [comment]
Thanks @vincentdass!  That worked.
