### ISSUE TITLE
Why doesn't Azure App Service Deploy use SetParameters file by default?

### ISSUE THREAD

**Issue by phatcher** [Microsoft/vsts-tasks#3416]
The standard build process produces a <Projectname>.SetParameters.xml file along side the zip file containing the contents to be published, so I have a token replacement step which substitutes the token values.

Unfortunately the unless you explicitly specify the file in the task, the parameter file is not used by the publish process.

Can you change it so that if not specified it looks for a SetParameter.xml file in the same location as the zip file?

**Comment by RoopeshNair** [comment]
We have add this to our backlog. However it will be another 3-4 sprints before we can get to it. 

Thanks

**Comment by phatcher** [comment]
Did you close this because you've done it?

It's bad practice to close it just because you say you're going to do it.
