### ISSUE TITLE
 Cannot pass DestinationSpecifier with quotes from TFS to OSX

### ISSUE THREAD

**Issue by Vinzz** [Microsoft/vsts-tasks#3417]
We want to launch xcode tests via the xcodebuild task, and struggle with the [destinationspecifier ](http://www.5neo.be/use-xcodebuild-cli-to-launch-ios-simulator-and-device/)parameter.

In our case, the platform name is 'iPhone 5', so the destinationspecifier for our command ought to be:
`-destination name="iPhone 5",OS="10.2"`

How to pass such double quotes from TFS to an OSX agent? All we tried seemed to fail us (\" or "" or even '")

Thanks

PS: I first open the issue on the [vsts-agent rep](https://github.com/Microsoft/vsts-agent/issues/751)o, but was redirected here

**Comment by madhurig** [comment]
I have this in my build definition: -destination "platform=iOS Simulator,name=iPhone 6s" and it works. Please try: -destination "name=iPhone 5,OS=10.2" and see if that helps. 

The arguments are split on spaces and the quotes indicate it is one argument and should not be split. I agree this is confusing.

Thanks,
Madhuri

**Comment by Vinzz** [comment]
Thanks @madhurig, that's exactly what we needed to do. And indeed it's a bit confusing,
