### ISSUE TITLE
 One or more of the steps defined in the build does not have an associated task definition

### ISSUE THREAD

**Issue by vmakhaev** [Microsoft/vsts-tasks#3418]
We've been using cloud VSTS with custom agent. It works most of a time, but sometimes we get this error for build:

`One or more of the steps defined in the build does not have an associated task definition. Check if the task was uninstalled or has failed a licensing check.`

After manual restart, build runs smoothly without any problems.

This can be connected to https://github.com/Microsoft/vsts-tasks/issues/1816 and https://github.com/Microsoft/vsts-tasks/issues/1170

**Comment by ericsciple** [comment]
@vmakhaev by manual restart, do you mean restarting the agent?

**Comment by ericsciple** [comment]
i found out there is an investigation currently regarding this issue.

**Comment by ericsciple** [comment]
@yaananth fyi

**Comment by yaananth** [comment]
@vmakhaev Could you share the following details:
What's your account name?
Time when you observed the issue?
I think those tasks are coming from an extension correct?

**Comment by vmakhaev** [comment]
@ericsciple by "restarting" I mean "Queue new build"

@yaananth 
Account name: "usinnovation"
There is [link](https://usinnovation.visualstudio.com/Cortex/_build/index?buildId=211&_a=summary) to the failed build with this issue (yesterday, just before I created this issue). Another [one](https://usinnovation.visualstudio.com/Cortex/_build/index?buildId=210&_a=summary).
We are using Docker extension in these builds.

**Comment by yaananth** [comment]
Thanks!
I see first occurrence at 2017-01-12 12:35:03.4072654 UTC and last  2017-01-12 16:14:49.5055690 UTC.

There has been similar occurrence of this issue for another account. We enabled tracing that would help us in narrowing the issue down. If it happens again, please reopen the issue that should point out what is happening.

As of now, the issue doesn't seem to be happening.

**Note**: If any one else is seeing the same issue for VSTS (**not** TFS onPrem), please add account information here and reopen the issue. So that we will have all the data needed in a single place.

**Comment by sachinjoshi27** [comment]
@yaananth 

We are facing exact same issue today (just now).

Account name GTILeap.

I just created a new build definition and its not even allowing me to queue the build. We are not using any extension.

**Comment by Jonathan34** [comment]
Just had the same on VSTS. Created a build, saved as a template, created another build from the template, changed 2 variables, tried to save & queue, failed.

**Comment by sanyogitaranade** [comment]
@Jonathan34 , are you using any task which was installed as a part of extension? If yes, what is the VSO account name and Extension Name?

**Comment by sanyogitaranade** [comment]
@sachinjoshi27, are you still facing this issue?

**Comment by Jonathan34** [comment]
@sachinjoshi27 we have no extension AFAIK, or at least i am not using them.
i do use a lot the tasks groups with variables groups though. so the template is based off that.

**Comment by sachinjoshi27** [comment]
@sanyogitaranade : I was able to get around this issue and able to queue builds now.

@Jonathan34  : You might want to remove any meta-tasks (task groups) and re-add them. This worked for me.

**Comment by Jonathan34** [comment]
@sachinjoshi27 yes i can remove/re-add everything, but that's going to be a bit painful :)

**Comment by sanyogitaranade** [comment]
@Jonathan34. @sachinjoshi27 , Actually this is not exactly related to tasks, so I have forwarded it to the team which works on Task Groups. They will do further investigation.

**Comment by Jonathan34** [comment]
thanks, the remove/add does the trick in the meanwhile.

**Comment by yaananth** [comment]
Reopening the issue.
To summarize:

- If the task is coming from an extension -> this issue should be fixed in VSTS and TFS Update 1 RC2 (at min)

- If the task is not coming from an extension and uses task groups - seems like workaround is to remove and add all of them back - needs investigation

**Comment by sachinjoshi27** [comment]
@yaananth  : I'm still seeing this issue. We are using custom task groups that are not coming from extensions. Let me know if you need any info.

our VSTS account is https://gtileap.visualstudio.com

**Comment by yaananth** [comment]
@harshil93 Could you take a look at the issue? Do we have telemetry up?

**Comment by harshil93** [comment]
@yaananth My telemetry changes will be going with 116 deployment. The account in question is still on 115. I will wait for a couple of days so that 116 is rolled out to this scale unit where the gtileap account is.

**Comment by harshil93** [comment]
@sachinjoshi27 I can see some logs for an extension, can you please confirm, that this isn't the issue.

Contribution EnterpriseServicesDevOpsTeam.BuildTool-Tasks.task-ESDevopsServiceEndpoint was not returned by EMS. Task bc59c8e7-7b9a-4699-98fc-fa77b48b3d97, version 2.2.201703234 may have been disabled.

Contribution EnterpriseServicesDevOpsTeam.BuildTool-Tasks.task-ESDevopsFxCop was not returned by EMS. Task dbd8dc33-6b75-4361-a74e-afc94f53a7af, version 2.2.201703062 may have been disabled.

**Comment by harshil93** [comment]
@sachinjoshi27 Is it happening again ? If not I will close this issue.

**Comment by sachinjoshi27** [comment]
@harshil93  : For now, this issue is not happening. You can close this issue.

I still have one question though, going forward if my build definition contains meta-tasks or extensions will this issue crop up ? Removing and adding all tasks manually defeats the whole purpose of templated definitions.

**Comment by harshil93** [comment]
No it shouldn't happen. Let us know if it is happening again.

**Comment by pabrams** [comment]
This is happening to me on TFS 2017.3.  Was this ever fixed, or do I have to use the workaround of removing/re-adding all task groups when creating a new definition from a template?

**Comment by pabrams** [comment]
Opened #7609
