### ISSUE TITLE
ServiceFabricDeploy does not have demands for SF SDK capability for agent

### ISSUE THREAD

**Issue by mikanyg** [Microsoft/vsts-tasks#3419]
Ran into an issue where ServiceFabricDeploy task failed with the following error message:

**##[error]Supported task execution handler not found. Supported handlers: Node**

Found out that our Agent pool, which already had two private agents (Windows based, with VS and SF SDK), was updated with a new OSX based agent being added to the pool by a mistake. Since the ServiceFabricDeploy task does not add any demands to any SF SDK to be present on the agent, the release was sent to the Mac, causing the above error.

We started by adding custom demands and capabilities on the windows agents, but since we have a fair amount of release definitions for our many SF based applications and services, we ended up creating a new pool and moving the OSX agent, instead of updating all our release defs with new demands.

How come the ServiceFabricDeploy does not have demands for the SF SDK to be present on the agent, and why does installing the SF SDK not show up as a capability on the windows agents?

**Comment by MikkelHegn** [comment]
In regards to the SF SDK requirement. All we need for build and publish is either part of the .sfproj (a NuGet package) or a set of PS utilities in the deploy task. We do rely on the SF Runtime to be installed.

**Comment by ericsciple** [comment]
@MikkelHegn since the Service Fabric tasks only run on Windows, adding a demand for CMD will ensure it gets routed to a Windows agent. [Example here](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/BatchScript/task.json#L23).

**Comment by mikanyg** [comment]
@ericsciple that would do the trick, but it seems like a workaround since the task really depends on Powershell and the SF runtime (and its cmdlets). But as far as I can tell only private agents report PowerShell as a capability, I cannot see this capability in the Hosted agent in my VSTS account.

**Comment by ericsciple** [comment]
The big problem today is that capabilities are not extensible. The next step to addressing that is a tool installers feature (pulling tools on the fly).

Regarding the missing powershell capability on the hosted agent, I'll check with someone offline about that.

**Comment by ericsciple** [comment]
Reassigning to Service Fabric area. This specific issue would have been avoided (job routed to Mac agent) if the Service Fabric had a demand for CMD to ensure routed to a Windows agent. [Example here.](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/BatchScript/task.json#L23)

**Comment by bishal-pdMSFT** [comment]
Closing this issue as CMD has been added as demand.
