### ISSUE TITLE
ServiceFabricDeploy fails for UserCredential constructor arity in latest hosted agent

### ISSUE THREAD

**Issue by PlasticLizard** [Microsoft/vsts-tasks#3434]
The latest update of the hosted agent, which seems to have been released on 1/13/2017, is causing the ServiceFabricDeploy task to fail on line 97 of Tasks/ServiceFabricDeploy/utilities.ps1:

$userCredential = Create-Object -TypeName Microsoft.IdentityModel.Clients.ActiveDirectory.UserCredential -ArgumentList @($authParams.Username, $authParams.Password)

With this error:

##[error]Cannot find an overload for "UserCredential" and the argument count: "2".

The failing Service Fabric Application Deployment task is version 1.2.1 and the failing agent version is 2.111.1

The last successful release in my environment was deploy task version 1.2.1 and the failing agent version is 2.110.0

So it looks like an incompatibility of some kind introduced in the agent since the exact same task version used to work. I"ll create a ticket in the agent repo too, but thought you should know.

**Comment by ericsciple** [comment]
The bug is understood now. The task leverages the a DLL delivered by the agent (fragile assumption) and should pull the DLL it needs when the task is built.

From offline discussion, it sounds like the needed version of the DLL can be obtained from this package https://www.nuget.org/packages/Microsoft.IdentityModel.Clients.ActiveDirectory/

And the tasks repo has infrastructure to pull the dependency at build time. Reference example here: https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/PublishSymbols/make.json#L3

**Comment by justinpatten** [comment]
I'm having the same issue and it is blocking the deployment of new builds. Any ETA on a fix?

**Comment by NickDarvey** [comment]
This is blocking deployment for us too. Updates please?

**Comment by ericsciple** [comment]
@MikkelHegn or @kmkumaran would know more details. i know the issue is being worked on.

**Comment by ericsciple** [comment]
It looks like the issue only affects connections using AAD auth. Using a different auth type would workaround the issue.

Additionally, while the hotfix is being worked on, I published [a private here](https://github.com/Microsoft/vsts-tasks/releases/tag/servicefabricdeploy-m111-private) that you can use TFX to upload to your account. I don't have a proper Service Fabric env to test against (AAD creds), but I think this will work.

**Comment by justinpatten** [comment]
@ericsciple I installed the hotfix on our account and was able to deploy. Thanks!

**Comment by ericsciple** [comment]
@justinpatten thanks for confirming the fix!

**Comment by yorgovs** [comment]
@ericsciple When can we expect an official fix? This is directly influencing our production deployment atm.

**Comment by ericsciple** [comment]
@yorgovs If you can post your account name here or send it to ersciple, I can see what we can do to expedite the roll-out to your scale unit (mail to me at microsoft.com). Same goes for anyone else, feel free to send me your account name.

**Comment by ericsciple** [comment]
...e.g. https://`account`.visualstudio.com

**Comment by ericsciple** [comment]
Some folks were asking so I updated the instructions on the [release page for the private](https://github.com/Microsoft/vsts-tasks/releases/tag/servicefabricdeploy-m111-private).

**Comment by ericsciple** [comment]
The fix has rolled out to about half of the accounts now. ETA for all accounts is later this evening.

**Comment by LarsKemmann** [comment]
@ericsciple Just FYI, this was still occurring on the 'bynalogic' tenant as of 15 minutes ago, but installing the hotfix has resolved the issue for me as well. Thanks so much!

**Comment by ericsciple** [comment]
The fix has rolled out everywhere now. Thanks everyone!
