### ISSUE TITLE
Arbitrary xcodebuild parameters

### ISSUE THREAD

**Issue by jschiessl** [Microsoft/vsts-tasks#344]
Is it possible to pass arbitrary parameters to the xcode build task? As far as I can see, only $(Configuration) and $(SDK) get passed down to the commandline invocation.

**Comment by bryanmacfarlane** [comment]
not right now.  I'll use this issue to add it.

**Comment by bryanmacfarlane** [comment]
on a side note, if you could elaborate on the additional things you're looking to pass then that would help as well for the flip side of the problem ... make sure we can handle all the main scenarios in a first class way while letting you fallback on arbitrary args

**Comment by jschiessl** [comment]
Hi Brian,
that sounds great. Specifically, we had to use the PROVISIONING_PROFILE flag during build to get push notifications for our app running.
My current workaround for this is to check in a build script into VCS that performs the necessary xcodebuild task - still need to parameterize it, though.

**Comment by bryanmacfarlane** [comment]
Thanks - that helps.  I'll add the other cmdlines input and figure out where provisioning profile fits into the first class model. (another input?)

**Comment by tonyblues** [comment]
+1 to add support for extra command line parameters.

We are now using xcodebuild with the "Test" action to trigger our Unit Tests and UI Tests. We'd like to specify the "-destination" parameter to xcodebuild so we can choose a particular device type (iPad, iPhone, etc.) for the simulator to run the UI Tests.

Thanks!

**Comment by bryanmacfarlane** [comment]
This is fixed in master and will roll out soon (week or so).  It might be sooner if we patch it (considering another issue which would carry this work)

**Comment by miktav** [comment]
I'm having problems using the -destination parameter when the parameter value contains spaces. I've described my problem here: 

http://stackoverflow.com/questions/43989967/xcodebuild-error-option-destination-requires-at-least-one-parameter-of-the-f

From your comment, I was hoping this issue had been resolved. Can you suggest a workaround? Thanks!
