### ISSUE TITLE
Azure SQl Dacpac deployment failing

### ISSUE THREAD

**Issue by bipindas** [Microsoft/vsts-tasks#3444]
I have a dacpac deployment that's failing. Its pushing to 2 other environments without problems. Dev and QA are deployed successfully but sandbox is failing. I get the error. Credentials are the same for all 3 db's. I tried with both Autodetect firewall and IP address range. 

Unable to connect to master or target server 'XX_Sandbox'. You must have a user with the same password in master or target server .
Azure SQL Dacpac task failed.

**Comment by vincentdass** [comment]
@bipindas ,It looks like the task failed for invalid user credentials.
Can you queue a new release with system.debug = true ?
you can find the **sqlpackage.exe command** with arguments in debug logs. Please run that command locally with appropriate password. Can you also try to login to Azure SQL Server from 'Microsoft SQL Server Managment Studio' ?

**Comment by bipindas** [comment]
Thanks. From the log sqlpackage command I could see that the username was incorrect. Something must have changed with the vsts task. previously we had to specify the user name as username@servername. Now it looks like the task is appending the server name automatically so I ended up with username@servername@servername. Updated that and the task ran successfully.

Thanks!
