### ISSUE TITLE
.NET Core restore/build with a .csproj instead of a project.json

### ISSUE THREAD

**Issue by alexbance** [Microsoft/vsts-tasks#3445]
Hi,

We've run into an issue where we cannot build our .Net Core app in VSTS because the build definitions are looking for project.json files not the .csproj files. I have tried both the .Net Core (Preview) definition and using a command line definition.
 On the documentation for the hosted pool it says the build server is deployed with both .Net Core 1.0 and 1.1 runtimes. How do I specify which runtime to use or how do I specify to look for .csproj files?

Thanks for your help,
Alex

**Comment by StrangeWill** [comment]
Did .NET Core move to removing the project.json yet? All my .NET Core projects still have those.

**Comment by alexbance** [comment]
Turns out we were using a pre-release, we've reverted to the current version for now. Cheers
