### ISSUE TITLE
Azure RM Service Endpoint: endpoint.url should resolve to https://management.azure.com

### ISSUE THREAD

**Issue by mclark1129** [Microsoft/vsts-tasks#3450]
This is a follow up to #3424 but is focused on what I believe is a specific bug causing my issue.

The Azure RM Service Endpoint type defines its URL as `https://management.core.windows.net` which is the Azure Classic API and not the Azure RM API at `https://management.azure.com`.  If you look at the datasources defined in the endpoint here:

`https://yourinstance.visualstudio.com/defaultcollection/_apis/distributedtask/serviceendpointtypes?type=AzureRM`

You will see that all datasources are defined as a REST calls to the Azure RM API at `https://management.azure.com`.  The `endpointUrl` defined for the endpoint itself is the only one that uses `https://management.core.windows.net`.  This prevents me from being able to define a custom `dataSourceBinding` that leverages the Azure RM Service Endpoint to make calls against the Azure RM API

I believe this endpoint URL should be changed to `https://management.azure.com`.

**Comment by Ajay-MS** [comment]
@mclark1129 

You are right  in this context, endpoint.url should be https://management.azure.com for AzureRm endpoints. We will fix this issue soon.

**Comment by mvvsubbu** [comment]
We have addressed this in current sprint. It should be available in next 3 - 4 weeks. I am closing the issue as fix is completed. Please feel free to re-open if there is any issue once 113 deployment is done.
