### ISSUE TITLE
Select artifacts download by glob pattern

### ISSUE THREAD

**Issue by damienpontifex** [Microsoft/vsts-tasks#3459]
The release agent can be configured to "Skip artifacts download", but wondering whether a task could be created for artifact download that allowed a glob pattern to be specified?

As an example:
We have multiple Environments in the release pipeline, one of which only does an ARM deployment which only needs two json files. We still need to download all artifacts to be able to get just these two files in this step.

**Comment by gopinathch** [comment]
Sorry Damien, currently we do not have support for partial artifacts download, we have it in backlog and we will be picking up support for this.

**Comment by nibras85** [comment]
Release time could be cut by half if I was able to specify downloading of artifacts per environment.

**Comment by RoopeshNair** [comment]
We have this on our backlog. However it will be 2-3 months before we can get to it based on current priorities.  Closing it for now.

Thanks

**Comment by chamindac** [comment]
Hi @damienpontifex 

I know this is a very late reply. But I have a [component in Marketplace which can filter artifacts for downloading. ](https://marketplace.visualstudio.com/items?itemName=chamindac.chamindac-vsts-release-task-download-artifacts)

Hope this helps until something is available in default artifacts download steps.

**Comment by nibras85** [comment]
@chamindac I'm using your extension and its very useful. Thanks.

**Comment by damienpontifex** [comment]
Thanks @chamindac I'll check it out

**Comment by phatcher** [comment]
@RoopeshNair  Why did you close this if you haven't done it yet?

**Comment by RoopeshNair** [comment]
@phatcher we are tracking this internally.
