### ISSUE TITLE
Warnings in Azure File Copy Task

### ISSUE THREAD

**Issue by jhumphries83** [Microsoft/vsts-tasks#3464]
When the Azure File Copy task runs as part of my build I receive this warning twice in the log:

`##[warning]GeoReplicationEnabled property will be deprecated in a future release of Azure PowerShell. The value will be merged into the AccountType property.`

This is adding extra noise to my otherwise clean build.

I am using the following settings in the Azure File Copy task:

- Connection type: Azure Classic
- Destination Type: Azure VMs
- Select Machines By: Machine Name

Could the script be modified so that the warnings aren't raised every time the task is run?

**Comment by mvvsubbu** [comment]
Thanks for bringing it to our notice we will address this.

**Comment by mvvsubbu** [comment]
We are not using any option as reported by command let. We have an open issue with Azure team (https://github.com/Azure/azure-powershell/issues/3116) for the same. If there is anything we need to address in the task we will do that based on their reply.

Mean while if you wanted have release without warnings can you try using Azure Resource Manager based endpoint and do the copy using same?

**Comment by mvvsubbu** [comment]
Tacking the issue with the above mentioned azure powershell issue. Closing it here.
