### ISSUE TITLE
Publish-TestResults cmdlet not cleaning up after itself?

### ISSUE THREAD

**Issue by juramicrosoft** [Microsoft/vsts-tasks#3471]
It seems that trx attachment uploads by way of the Publish-TestResults cmdlet are not cleaning up temporary artifacts from the NetworkService temp folder, causing the drive to fill.

**Comment by vimegh** [comment]
@juramicrosoft Are you observing this with VStest task or publish test reults task?
I think deleting the trx file is not the responsibility of Publish Test results cmdlet, as the file is not generated by it. Publish Test results cmdlet just reads the file and publishes the result.

**Comment by vimegh** [comment]
@juramicrosoft Can you please respond to my previous comment. Thanks.

**Comment by juramicrosoft** [comment]
This is with the Publish Test Results task being directly called by a custom task.  We have a remediation in place and I will get a verification as soon as is viable.

**Comment by nigurr** [comment]
@juramicrosoft this seems to be not an issue with the task. Can you confirm is it because of your custom implementation?
