### ISSUE TITLE
VsTest task fails even when all tests passed

### ISSUE THREAD

**Issue by tomasherceg** [Microsoft/vsts-tasks#3473]
We have a project where `VsTest` task consistently fails even when all tests passed.

In the log, I see this:

```
2017-01-22T16:22:52.4050809Z Total tests: 150. Passed: 149. Failed: 0. Skipped: 1.
2017-01-22T16:22:52.4050809Z Test Run Successful.
2017-01-22T16:22:52.4050809Z Test execution time: 17.1337 Minutes
2017-01-22T16:22:52.5342314Z ##[debug]rc:0
2017-01-22T16:22:52.5342314Z ##[debug]success:false
2017-01-22T16:22:52.5342314Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
2017-01-22T16:22:52.5461701Z ##[error]Error: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 0
```

When I download and open the `.trx` file from the build agent and open in Visual Studio, it says that all tests passed (one is skipped, because it is marked using the `Ignore` attribute which is correct).

The version of VsTest task is `2.0.5` (C:\BuildAgent\tasks\VSTest\2.0.5)

We are using the default configuration, no special options. 
We have installed both VS 2015 and VS 2017 RC on the build agent.

[logs_7207.zip](https://github.com/Microsoft/vsts-tasks/files/722074/logs_7207.zip)

[TFSBA_TFSBA4WS12R2 2017-01-22 16_06_05.zip](https://github.com/Microsoft/vsts-tasks/files/722075/TFSBA_TFSBA4WS12R2.2017-01-22.16_06_05.zip)

**Comment by vimegh** [comment]
@tomasherceg Can you please check eventviewer at the time failure and share what application error is observed there. Thanks.

**Comment by tomasherceg** [comment]
@vimegh I have looked into both Application and System category in the Event Viewer but there is nothing related to the vstest.console.exe.

**Comment by vimegh** [comment]
@tomasherceg What happens if you run the command directly on the machine from command prompt. do you see any error?

You can run following and check. Does it show any error?
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" C:\BuildAgent\_work\12\s\src\DotVVM.Samples.Tests\bin\ANC_Firefox\net461\DotVVM.Samples.Tests.dll /logger:trx

Also run following, and share the error.txt if nonempty.
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" C:\BuildAgent\_work\12\s\src\DotVVM.Samples.Tests\bin\ANC_Firefox\net461\DotVVM.Samples.Tests.dll /logger:trx 2>error.txt

Thanks.

**Comment by DOMZE** [comment]
I have the same problem.

all tests passed, 2 skipped tests, but agent determines that the build fails.
Using NUnit 3.6.0 and NUnitTestAdapters 3.7.0

It does because Skipped tests generate error messages when running 2>error.text

**Comment by nigurr** [comment]
@codito Can you help with this?

**Comment by nigurr** [comment]
Closing this thread as it's been answered here https://github.com/Microsoft/vstest/issues/285#issuecomment-268286300
Further discussion can happen in that thread as it's more related to vstest.console.exe behaviour

**Comment by bergmeister** [comment]
@nigurr Your link does not explain how we can use the vstest task with skipped tests and not have the task fail. The PR above (#3558) could have helped you to achieve this

**Comment by nigurr** [comment]
@bergmeister I understand your concern, however we can't break this default functionality. 
We would be interested to know in which scenario we need to write to error stream and still pass the test?

`If it's an error, the test should fail. If it's not an error, then it shouldn't be in error stream. it can be in standard stream.`

**Comment by bergmeister** [comment]
@nigurr 
Here is the log below using the vstest task v2 that uses the `Visual Studio Test Platform Installer` of version [15.7.2](https://www.nuget.org/packages/Microsoft.TestPlatform/15.7.2).  All tests pass and there are no skipped or inconclusive tests but the task is still marked as red. The tests are using `NUnit3`. Here is the log:
```
Total tests: 890. Passed: 890. Failed: 0. Skipped: 0.
2018-06-01T07:38:16.0669743Z Test Run Failed.
2018-06-01T07:38:16.0682091Z Test execution time: 12.9580 Minutes
2018-06-01T07:38:16.0926380Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
2018-06-01T07:38:16.1082348Z ##[error]Error: D:\_Builds\RCSSV-EM20-014T.01\_tool\VsTest\15.7.2\x64\tools\net451\Common7\IDE\Extensions\TestPlatform\vstest.console.exe failed with return code: 1
2018-06-01T07:38:16.9141667Z ##[error]VsTest task failed.
```

**Comment by lankaapura** [comment]
Hey @bergmeister did you find a fix or workaround for this issue? Thanks.

**Comment by bergmeister** [comment]
It was a problem of the test adapter throwing due to a misconfiguration, so kind of yes but my point was that the pipeline should be more robust because in my case it was still good enough to run the tests.

**Comment by lankaapura** [comment]
@bergmeister thanks! it was a misconfiguration in my case too. My test dll filter was picking up a wrong dll which caused above error.

**Comment by kfry88** [comment]
Hi guys, may I know what exactly was the misconfiguration and how was it fixed? Sorry, I'm pretty new to this and everything works fine on my computer, but it just doesn't build on the server. I have almost the same errors.

**Comment by bergmeister** [comment]
I think there can be a multitude of causes, in my case it was that test runsettings were still pointing to an old NUnitv2 test adapter although we were on Nunitv3, which I could find out by reading the logs carefully, which I suggest you to do as well.

**Comment by kfry88** [comment]
thx  
I am a beginner when it comes to both nunit and azure build. I have never used a runsetting file before and I don’t see one in my projects. Can you give me a pointer or two how to find my runsetting file and what to look for? I don’t have any nunit 2 tests at all in my entire solution. 
Sorry. I know my question is off topic, but I tried to google it around and but didn’t have much luck finding a clear cut answer.

**Comment by lankaapura** [comment]
@kfry88 in my case it was I was feeding dll which doesn't have any tests. Double check what you provide to following.

![image](https://user-images.githubusercontent.com/403912/58773836-421ce500-85dc-11e9-88d2-cdcd3b6c4148.png)

**Comment by kfry88** [comment]
My dll was picked up by and executed correctly first.
Then for some reason, the wrong version of Nunit adapter is also triggered and causing VSTest to fail in the end even though all my tests are passed:

2019-06-02T23:20:30.8294344Z NUnit Adapter 3.13.0.0: Test execution complete
2019-06-02T23:20:30.8799670Z NUnit VS Adapter 2.0.0.0 executing tests is started
2019-06-02T23:20:31.2315332Z Exception NUnit.Core.UnsupportedFrameworkException, Exception thrown executing tests in d:\a\1\s\Source\NET\Test\Test.Core.Tests.Unit\bin\Release\Test.Core.Tests.Unit.dll
2019-06-02T23:20:31.2316484Z NUnit VS Adapter 2.0.0.0 executing tests is finished

I guess from my workstation, i am not using VSTEST instead, i am using the nunit adapter to do this, so i am not getting errors.

**Comment by kfry88** [comment]
Finally, I found the issue. Well mine is a bit unexpected. Some very capable developer decided to check in the bin release folder into spruce control. The checked in folder contained nunit 2 test adapter. Even though it’s in a totally different folder as my nunit 3 tests, somehow it vstest decides to try and use the version 2 adapter to run my nunit 3 tests. Even though within the same folder, there is nunit 3 test adapter dlls also. 
I can finally stop pulling my hair out now. :(
