### ISSUE TITLE
Execute Nuget.exe from powershell vsts build task 

### ISSUE THREAD

**Issue by sowsan** [Microsoft/vsts-tasks#3474]
Hello Team -
Trying to execute an .exe from powershell task. For that, I'm trying to set it as not read-only but its not working. Any work-around ?
Set-ItemProperty is not setting it as $false and I'm getting the value always false.
==========script===========
-exeUrl $(build.sourcesdirectory)\uHub.App\Stateless1\tools\Nuget.exe
$out = Get-ItemProperty $exeUrl -Name IsReadOnly
Write-Host $out.IsReadOnly
Set-ItemProperty $exeUrl -Name IsReadOnly $false
$out = Get-ItemProperty $exeUrl -Name IsReadOnly

sowmyancs

**Comment by bryanmacfarlane** [comment]
Doesn't seem to be an issue with the tasks in this repo.  Seems to be a general powershell exec process problem.
