### ISSUE TITLE
Copy Files Task: Is there a way to enable .file to be copied

### ISSUE THREAD

**Issue by melborp** [Microsoft/vsts-tasks#3478]
Hi 
It seems that by default .project and other files starting with . are not copied. glob and minimatch have a way to enable .dot files to be included.
The option "dot: true". 

Is there a way to override and enable .dot files to copied for Copy Files task?
(referene: https://github.com/isaacs/minimatch (read: dot) )

**Comment by ericsciple** [comment]
The dot:true option is used now in the 2.x version of the Copy Files task (rolled out recently)

**Comment by melborp** [comment]
Hi, is that coming with TFS 2017 RTM on-premis as well? or Update 1?
These tasks are platform tasks right, so they would be updated by TFS version / update.

**Comment by ericsciple** [comment]
2017 update 1

**Comment by ericsciple** [comment]
a workaround is to specific `.*` as a pattern
