### ISSUE TITLE
Test Agents deployment stucks on deploying test agents

### ISSUE THREAD

**Issue by arunkumar90** [Microsoft/vsts-tasks#3490]
I am having issue on the test agents deployments step. 
I am trying to set them up as interactive. I can see my VM gets rebooted multiple times when trying to deploy test agent.
I think it is because my VM domain policy doesn't allow auto logon. (It works when I uncheck interactive box)
I have already got the test agents on the VM, I am not sure why it is trying to install and reboot the VM everytime I have trying to run the deploy agent step. I am using TFS 2015 agent and running the installer for TFS test agents 2015. My VM cannot download files from internet so I have provided the setup exe path in the agent location parameter. 

If I remove the agents deployment steps, visual studio complains that deploy agent step need to be run before running the tests. Is there a way we can run functional tests without deploy agents step?

Please find the screenshot below:
![agent deployment issue](https://cloud.githubusercontent.com/assets/25336148/22275472/bba5a44a-e2f8-11e6-84cd-e6b600a9557c.PNG)

**Comment by arunkumar90** [comment]
I have an update regarding the above issue. When it is restarting the VM and fail to logon back to server for running test due to the domain group policy. But when I manually logon to the server with the same service account, it start running the tests on the server automatically. Is that possible to automate the process somehow?

**Comment by vimegh** [comment]
Test Agent machines are rebooted in following scenrios
a.    First time installation of Test Agent which might install .NET which requires reboot
b.    The test agent admin credentials and test user credentials are different which might need to force reboot to logoff all the users

Can you make sure in “Deploy Test Agent Task”-> ‘Update Test Agent’ checkbox is not selected (by default it’s selected and forces to reinstall TA everytime)
Also please try running tests with same admin/user credentials, in which case you would not require autologon.

**Comment by vimegh** [comment]
You can refer to : https://github.com/Microsoft/vsts-tasks/issues/2239 

Additon to above, presently we dont have any solution for this. For Test agent to run interactively, we need to have a valid user session on the box and if that session is not present then we rely on autologon to create that session and therefore we reboot. Hence the dependency.  

You can try doing above but if that doesn't work then 
1. Either configure as service and use if that is an option.
2. Ask your IT admin to disable your domain policies around autologon for your test machines.

On your question "Is there a way we can run functional tests without deploy agents step?" No, presently its not possible to run RFT without deploying test agent.

Thanks.
