### ISSUE TITLE
Real time status/logs of test execution not available on VSTS console

### ISSUE THREAD

**Issue by mohit1606** [Microsoft/vsts-tasks#3492]
Hello,

As we are running our test cases, the result is shown only after the test execution.
I have the following query-
- Real time status of test execution is not available on VSTS. Only after the test execution is completed, the status is shown on the portal.
Even the test console output log is not available in the VSTS console. It is only available in the VSTS agent for which every time we have to login to the Agent and check it.

**I would like to know is there any way to download or see the console output test logs in the VSTS console?**

Request you to help me to clarify these doubts.

Thanks
Mohit

**Comment by vimegh** [comment]
@mohit1606 In case of failed tests, you will be able to see the console output of test in Test tab of completed build, by clicking on the failed test(Also console output of failed test can be seen in VSTS build Console during execution). We dont show console output for passed tests, as that is rarely needed and ideally shouldn't be required. 

Assuming you are using VSTest task to run the tests, regarding real time status, you will be able to see each test passing or failing on the console output one by one. Please let us know what exactly are you looking for.

**Comment by vimegh** [comment]
@mohit1606 Just a reminder, Were you able to see console output for failed tests?

**Comment by cltshivash** [comment]
You should be able to download the trx of the test run from run details/summary. The trx will contain all the information that you are looking for.  Does this help answer your query ?

**Comment by mohit1606** [comment]
Hi,
Thank you. We are able to see the logs now and also download them from VSTS logs.
For this we have made some small changes in our ANT script.

Thanks

**Comment by sonalsavaratkar** [comment]
Hello,

I have similar requirement, doesn't matter if test is failed or passed. I want to see my logs in real time which I am logging with either:
`System.Diagnostics.Trace.WriteLine("Trace writeline");`
or 
`Console.WriteLine(message);`

My tests are integration test where a good amount of data is cross-checked. So I want to provide a custom summary of what all type of data has been cross-verified.

Please help.

**Comment by AndyLysenko** [comment]
> Hello,
> 
> I have similar requirement, doesn't matter if test is failed or passed. I want to see my logs in real time which I am logging with either:
> `System.Diagnostics.Trace.WriteLine("Trace writeline");`
> or
> `Console.WriteLine(message);`
> 
> My tests are integration test where a good amount of data is cross-checked. So I want to provide a custom summary of what all type of data has been cross-verified.
> 
> Please help.

Have you managed to work around the problem? Any way to attach logs to a test run?
