### ISSUE TITLE
Need to add -SkipCNCheck option for remote powershell tasks

### ISSUE THREAD

**Issue by karlrissland** [Microsoft/vsts-tasks#3494]
If you are standing up lab machines, they may or may not be a part of a domain.  If they are not part of a domain, you need to provision an HTTPS WinRM endpoint for remote powershell to work.  To do that, you need to create a self signed cert.

In my case, I provisioned a self signed cert as *.EastUs2.cloudapp.azure.com which worked fine when I was connecting to <machine>.EastUS2.cloudapp.azure.com, but the port was accessible externally.

To increase security, I created a new build agent VM in the same VNet as the VM I wanted to deploy to and removed the public IP address.

Was able to ping the VM from the build agent via its Azure DNS name without issue.

Was able to powershell remote to the VM via Enter-PSSession -computerName <VMName> -UseSSL -SessionOption(New-PSsessionOption -SkipCACheck -SkipCNCheck) without issue.

XCopy task worked just fine, however the deploy test agent task failed with the following error message;

```
2017-01-25T18:50:28.6420411Z ##[warning]DistributedTests: Task 'PopulatingMachinesPresentState' for machine appiumwin10:5986's Error : System.Management.Automation.Remoting.PSRemotingTransportException: Connecting to remote server appiumwin10 failed with the following error message : The server certificate on the destination computer (appiumwin10:5986) has the following errors:     
 
2017-01-25T18:50:28.6420411Z The SSL certificate contains a common name (CN) that does not match the hostname. For more information, see the about_Remote_Troubleshooting Help topic.
 
2017-01-25T18:50:28.6420411Z    at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()
```

Searching through the repository, I noted that a few of the tasks that leverage powershell remoting only have the option -SkipCACheck, -SKipCNCheck is not used.

Not sure if this is by design or an oversight.  What is the best way to solve this problem?

Thank you?

**Comment by kmkumaran** [comment]
You can generate a test certificate that matches the host name. Refer these blogs for help:
https://blogs.msdn.microsoft.com/muthus_blog/2015/11/04/pre-requisites-for-using-azure-vms-in-winrm-based-tasks-in-build-and-release-management-workflows/
https://blogs.msdn.microsoft.com/muthus_blog/2016/03/24/simplifying-winrm-pre-requisites-in-azure-vms-as-part-of-release-and-build-workflows/

**Comment by kmkumaran** [comment]
@karlrissland - Are you unblocked?

**Comment by mvvsubbu** [comment]
We are not SkipCN intentionally, You need to have CN matching. I am closing this issue as it is as designed.
