### ISSUE TITLE
Setting a timeline record's state to `skipped` in a logging command results in no icon

### ISSUE THREAD

**Issue by agc93** [Microsoft/vsts-tasks#3511]
Using the [commands documentation](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md), the following is a valid timeline record command:

```
##vso[task.logdetail id=guid here;state=skipped;progress=100;]Task D
```

However, using this command in a PowerShell Script step results in the record appearing in the timeline with a 0:00 duration and a white square for an icon, as in the below screenshot:

![pasted_image_at_2017_01_31_01_11_am](https://cloud.githubusercontent.com/assets/1369269/22428598/674bab6a-e753-11e6-90b2-c009328bbf9f.png)

**Comment by bryanmacfarlane** [comment]
you should open this issue in the vsts-agent repo.  This is the same command the agent uses.

https://github.com/Microsoft/vsts-agent

**Comment by ericsciple** [comment]
i believe the white square is the icon
