### ISSUE TITLE
Timeline record's `progress` value does not affect build progress.

### ISSUE THREAD

**Issue by agc93** [Microsoft/vsts-tasks#3513]
Setting the `progress` value of any logging commands including both `task.setprogress` and `task.logdetail` doesn't have any impact on any counters of build progress. The left sidebar percentage shows a fixed percentage for the duration of a PowerShell Script test, even if the script itself outputs a logging command specifying a value for progress. The progress is also not shown in any timeline views.

What does this value actually influence?

**EDIT**: It also appears that the 'current operation' value for the `task.setprogress` command also does not have any effect on the UI. What exactly is `task.setprogress` supposed to *do*?

**Comment by bryanmacfarlane** [comment]
You should log this in the agent repo.  These are the same commands the agent itself uses

https://github.com/Microsoft/vsts-agent
