### ISSUE TITLE
Azure SQL DB Deployment:  Missing Firewall Auto-Detect Option

### ISSUE THREAD

**Issue by brett3210** [Microsoft/vsts-tasks#3514]
The "Azure SQL DB Deployment" Task is missing the auto-detect option (mentioned in the documentation) for the combo field "Specify Firewall Rules Using", for hosted automation agents

**Comment by mvvsubbu** [comment]
This option is available only for VSTS.  There is refresh button at the end of the input, try refreshing it should show up if you are using VSTS

**Comment by mvvsubbu** [comment]
If the option doesn't show up for VSTS even after refresh, feel free to re open

**Comment by brett3210** [comment]
Thanks, the Auto-Detect option still doesn't show up after refresh in Chrome, however it does show in Firefox.  Therefore please re-open (I don't have permissions to re-open)

**Comment by mvvsubbu** [comment]
Can you share the fiddler traces of vsts request when you did refresh from chrome. It shouldn't browser dependent.

**Comment by brett3210** [comment]
Working in Chrome now, after upgrading the Chrome version

**Comment by mvvsubbu** [comment]
Thanks for confirming
