### ISSUE TITLE
Azure App Service Deploy: Wildcards in "SetParameters File" Field Causes Error

### ISSUE THREAD

**Issue by brett3210** [Microsoft/vsts-tasks#3515]
The "Azure App Service Deploy" task supports wildcards for the "Package or Folder" field but not the "SetParameters File" field.  The error returned is:
"2017-01-31T03:00:33.4775945Z ##[error]Error: Set parameters file not found: D:\a\r1\a\Test Product A FL2\**\*.SetParameters.xml"

**Comment by mvvsubbu** [comment]
Yes It is as designed you have to give full path of the set parameter file.

**Comment by brett3210** [comment]
Thanks, as per the error log extract in my previous message, it doesn't appear to work as designed.  Therefore, can you please clarify why you have closed this Issue?

**Comment by mvvsubbu** [comment]
We are not supporting regular expression for set parameters file name and hence I closed. Did you meant something else?

**Comment by brett3210** [comment]
Sorry, I misunderstood your earlier response.  It would be great if you could add wildcard support as a future feature request for all path based fields please

**Comment by mvvsubbu** [comment]
Adding our PM to do needful.

**Comment by RoopeshNair** [comment]
@brett3210  - we encourage contributions, if you are willing, could you please submit a PR?
