### ISSUE TITLE
vstest: Can't specify multiple console options to vstest executable

### ISSUE THREAD

**Issue by ytimenkov** [Microsoft/vsts-tasks#3516]
This is regression from v1:
 1. Add vstest task
 1. Specify at least 2 parameters in "Other console options", e.g. "/inIsolation /platform:x64"
 1. Expected result: Both parameters are passed as a separate parameters to vstest command line.
 1. Actual result: console options is quoted and passed as a single parameter to vstest:
`2017-01-31T13:35:59.7656188Z [command]"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" C:\agent\_work\r1\a\mybuild\Myproject.Tests.dll "/inIsolation /platform:x64" /logger:trx`

**Comment by vimegh** [comment]
@ytimenkov Thanks for reporting. This is a valid bug. If you have dependency on console options, for now you can continue to use v1 of task. We will fix this for v2 preview task next release and update here.

**Comment by vimegh** [comment]
@ytimenkov We are planning to remove "other console options" Input in vstest 2.0 task. We will be exposing the Isolation option on UI and for specifying /platform:x64 one can use run settings file. for eg: check TargetPlatform in https://msdn.microsoft.com/en-us/library/jj635153.aspx?f=255&MSPPError=-2147217396
which you can do presently also as a workaround to specify platform argument in console option. 

Do let us know, if you see any concern with that.
