### ISSUE TITLE
MSBuild.SonarQube.Runner executable could not be found

### ISSUE THREAD

**Issue by eliassal** [Microsoft/vsts-tasks#3517]
Hi, I downloaded the extension for TFS 2015 update 3, installed it in my collection and created and end poing. Then I configured 2 steps as indicated before and after my build, I am getting the following error 
##[error]The MSBuild.SonarQube.Runner executable could not be found. Check that the build definition includes a SonarQube Pre-Build step 
My sonar server Version is 5.6.3 running on Linux fedora. 
Do I need to install any other tools? I understand that The SonarQube Extension embeds its own version of the SonarQube Scanner for MSBuild.

**Comment by ericsciple** [comment]
@eliassal that task isn't maintained in this repo anymore. The fwlink in the latest version that shipped from this repo [points to here](https://blogs.msdn.microsoft.com/visualstudioalm/2015/08/24/build-tasks-for-sonarqube-analysis/). It looks like from there, there is a link over to docs.sonarqube.com.

The SonarQube website that it links to should have some place for support. Another think you could try, when you download the task, the task.json or some other file (e.g. maybe a package.json?) may have a link to the repo where the task lives now.

**Comment by eliassal** [comment]
I am reallty confused with your response
At https://blogs.msdn.microsoft.com/visualstudioalm/2015/08/24/build-tasks-for-sonarqube-analysis/
comments are closed.
Pointing to https://blogs.msdn.microsoft.com/visualstudioalm/2015/07/28/msbuild-and-team-foundation-server-integration-with-sonarqube-version-1-0-released/
comments are also closed
Going to(as indicated) to
https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Extension+for+VSTS-TFS
no pissibility to ask or comment neither.

Regards,

**Comment by ericsciple** [comment]
there is a Get Support link on the [home page](https://docs.sonarqube.org/display/HOME/SonarQube+Platform). you may be able to reach the owners of the task from there.

**Comment by ericsciple** [comment]
which extension did you install?

**Comment by eliassal** [comment]
The one  on
https://marketplace.visualstudio.com/items?itemName=SonarSource.sonarqube
for TFS 2015 update 3 o premise

**Comment by ericsciple** [comment]
it looks like this might be the repo: https://github.com/SonarSource-VisualStudio/sonar-scanner-msbuild

**Comment by eliassal** [comment]
Agree, I visited it already but no way to post an issue, there is a link to jira but also no link to report an issue

**Comment by ericsciple** [comment]
@bgavrilMS @duncanpMS can you help redirect this issue?

**Comment by bgavrilMS** [comment]
@eliassal - appologies for any confusion the transition of the SonarQube tasks creates. We documented the transfer in this [blog post ](https://blogs.msdn.microsoft.com/visualstudioalm/2016/12/13/sonarsource-have-announced-their-own-sonarqube-team-services-tfs-integration/
) and link to it from the old tasks. 

Since the build tasks are owned by Sonar Source, the company behind SonarQube, you have to contact them for support. You can either post your question on stackoverflow or ask on https://groups.google.com/forum/#!forum/sonarqube  

Hope this helps!

**Comment by eliassal** [comment]
Thanks, I have already opened a thread in stackoverflow on Friday at
http://stackoverflow.com/questions/42008232/sonarqube-vsts-marketplace-extension

**Comment by eliassal** [comment]
Hi, yesterday, while I was playing with my build as I needed it to succeed, I removed  the "SQ....Ened Analysis New", reput it again, and hop, my build worked like a charm and I got analysis in Sonarqube server
Thanks for your help
