### ISSUE TITLE
ServiceFabricDeployTask Error -1073741819 : Deploy to Linux Cluster w/Certificate Security setup

### ISSUE THREAD

**Issue by FBNitro** [Microsoft/vsts-tasks#3522]
I'm using VSTS on VisualStudio.com to deploy a service fabric app to 2 clusters running on Azure.  One cluster is setup as unsecured, the other is setup as secured by certificate.  Both are configured as Linux clusters.  

Using the unsecured cluster, I have no problem deploying the Application.  Using the secured cluster, I get error code -1073741819.

For the Secure Cluster, I am using a CA Signed certificate, since my first thought was that a self-signed cert was the issue.  I received the same error on the CA cert as the self-signed cert.  I have no issues connecting to the Explorer endpoint on the cluster using "https://mydomain.com:19080/Explorer" after I install the certificate as a personal key.

From what I can tell, the secure cluster service endpoint has the correct certificate, password, etc.  They are the same ones I am using if I manually connect to the cluster.  I used the powershell command in the info popup to populate the base64 encoded certificate, the password is correct (I verified several times), the thumbprint is also correct.  The endpoint is set to "tcp://mydomain.com:19000".

I've included a the relevant portion of the log as an attachment, this was with System.Debug=true.
[SecureDeployFailure.txt](https://github.com/Microsoft/vsts-tasks/files/745365/SecureDeployFailure.txt)

**Comment by mani-ramaswamy** [comment]
Can you share the command that you used (for the self-signed cert deploy)?  were you able to connect to the cluster using CLI?

**Comment by mani-ramaswamy** [comment]
And as of now, you cannot connect to  a secure linux cluster with PS if that's what you are doing. We're working on a fix for that. You'll have to use Azure CLI to connect to secure LInux clusters.

**Comment by bishalpd** [comment]
@mani-ramaswamy is there a doc which specifies why secure linux clsuter is not supported in PowerShell? I don't think we can do much in the task if PS itself does not support connecting to secure linux cluster.

**Comment by bishal-pdMSFT** [comment]
Closing this as it is by design.

**Comment by FBNitro** [comment]
So, in the end, you're telling me via a VSTS Release, using the deployment tools provided, I cannot deploy a secure linux cluster and this is by design?

**Comment by MikkelHegn** [comment]
@FBNitro By design as in - we have not build the feature yet..

**Comment by goranjovanovic25** [comment]
Any updates when will this be available? Any time soon?
