### ISSUE TITLE
PublishTestResults .ts version handles wildcards differently than the .ps1 version

### ISSUE THREAD

**Issue by cgapeart** [Microsoft/vsts-tasks#3528]
I have build definitions for a cross platform project that includes running googletest unit tests in both Linux and windows.  I have the junit style xml test results on each of them being generated in the staging directory (e.g. BuildAgent/_work/1/a).  On our windows build platform, **/TEST-*.xml works fine, and the test results are published properly.

Under Linux, it appears that if wildcards are used, it uses the System.DefaultWorkingDirectory (e.g. BuildAgent/_work/1/s), and so far I haven't managed to it to publish results unless I name the files without wildcards.

The problem was in both the vsoagent version, and the latest vsts version -- though it appears I am using PublishTestResults 1.0.22. I haven't yet decoded the documentation or other search results to figure out how to upload a new version of a task to the server.

It does appear that the latest version on the master branch has different code that uses the find-files-legacy library to find the files, but it still references System.DefaultWorkingDirectory.

None the less, this issue may be fixed in the latest version, but since I haven't seen any similar issue report, I am posting it here to help direct others facing the same issue.

Ultimately, I want to be able to use wildcards, and I want it to search the same directory relative to build variables on each system, not withstanding file system differences.

**Comment by nigurr** [comment]
@cgapeart I tried reproducing the issue. I am able to publish the files in *nix with wildcard support.

Can you share your file structure and task configuration

![image](https://cloud.githubusercontent.com/assets/15208679/22961719/2944c726-f36e-11e6-8b49-8d64fc5ee52e.png)

![image](https://cloud.githubusercontent.com/assets/15208679/22961735/4b8271bc-f36e-11e6-8f3f-e239cfff6a83.png)

**Comment by cgapeart** [comment]
The task configuration is pretty much the default, but it was looking for $(Build.StagingDirectory)/TEST-*.xml

**/Test-*.xml was used as well, but it couldn't find the files either.

As you can see in the logs from your test run, **/Test-*.xml is off of the /s/ directory by default on linux.  On windows it will pull from /a/ as well.

Admittedly, our build configuration dumping the files in the /a/ directory could probably be improved as well, but the core of the issue is that worked in windows, but not in linux.

I worked around it by specifying full paths (off of $(Build.StagingDirectory)) to each of the two files I wanted to publish and using two publish commands.  It works for now, but it means if I add tests later on, I have to update the build whereas the wildcards would just pick up the results automatically.

**Comment by nigurr** [comment]
@cgapeart sorry If I am unable to get this right.

By default the working dir -> agent/work/1/s/
the pattern is -> **/Test*.xml
in windows -> it's case insensitive
in linux -> it's case sensitive

This should work if your files are under /s/ path. if windows version is doing something out of this directory, that's a bug.

I hope this answers your query. feel free to post your build configuration and file structure if you still notice some issue

**Comment by nigurr** [comment]
As there's no response, closing this thread. Please reopen if needed
