### ISSUE TITLE
'System.Globalization' already has a dependency defined for 'Microsoft.NETCore.Platforms'

### ISSUE THREAD

**Issue by roberteblackwood** [Microsoft/vsts-tasks#3530]
Using Flurl 2.2.1 which has a dependency on System.Globalization >=4.0.11 (lowest version installed), I get the following error in my package build in VSTS:

**##[error]'System.Globalization' already has a dependency defined for 'Microsoft.NETCore.Platforms'.**

I tried downgrading to Flurl 2.0.0 to get rid of the System.Globalization dependency, (still has .NETPlatform dependencies, including System.Linq >=4.0.0), and I now get the following:

**##[error]'System.Linq' already has a dependency defined for 'System.Collections'.**

Is it possible this could be resolved by specifying a different NuGet exe in the task?

**Comment by ericsciple** [comment]
@roberteblackwood which task is this issue for?

**Comment by roberteblackwood** [comment]
NuGet Packager

**Comment by alexmullans** [comment]
This is fixed by #4397, which provides a new multi-purpose NuGet task that supersedes the old NuGet Packager task and uses NuGet 4.0 by default.
