### ISSUE TITLE
"Error: Failed which: Not found ant: null" with Ant task 1.0.56

### ISSUE THREAD

**Issue by MagnusTim** [Microsoft/vsts-tasks#3540]
Hi,
I upgraded to TFS 2017 RTM this weekend for a customer and after the upgrade I get the following error when using the Ant build task (1.0.56): "Error: Failed which: Not found ant: null". 

Ant is installed on the server and I have an ANT_HOME path set.

The Ant task log down to the error looks like this:
2017-02-06T12:42:31.8656110Z Set workingFolder to default: D:\Builds\Agent2\tasks\Ant\1.0.56
2017-02-06T12:42:33.8500028Z ##[debug]agent.workFolder=D:\Builds\Agent2\_work
2017-02-06T12:42:33.8500028Z ##[debug]loading inputs and endpoints
2017-02-06T12:42:33.8656250Z ##[debug]loading ENDPOINT_AUTH_$/
2017-02-06T12:42:33.8656250Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_$/_ACCESSTOKEN
2017-02-06T12:42:33.8656250Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2017-02-06T12:42:33.8656250Z ##[debug]loading ENDPOINT_AUTH_SCHEME_$/
2017-02-06T12:42:33.8656250Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2017-02-06T12:42:33.8656250Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2017-02-06T12:42:33.8656250Z ##[debug]loading INPUT_ANTBUILDFILE
2017-02-06T12:42:33.8812513Z ##[debug]loading INPUT_CLASSFILESDIRECTORIES
2017-02-06T12:42:33.8812513Z ##[debug]loading INPUT_CODECOVERAGETOOL
2017-02-06T12:42:33.8812513Z ##[debug]loading INPUT_JAVAHOMESELECTION
2017-02-06T12:42:33.8812513Z ##[debug]loading INPUT_JDKARCHITECTURE
2017-02-06T12:42:33.8812513Z ##[debug]loading INPUT_JDKUSERINPUTPATH
2017-02-06T12:42:33.8812513Z ##[debug]loading INPUT_JDKVERSION
2017-02-06T12:42:33.8812513Z ##[debug]loading INPUT_PUBLISHJUNITRESULTS
2017-02-06T12:42:33.8812513Z ##[debug]loading INPUT_TARGETS
2017-02-06T12:42:33.8812513Z ##[debug]loading INPUT_TESTRESULTSFILES
2017-02-06T12:42:33.8812513Z ##[debug]loaded 16
2017-02-06T12:42:35.3187615Z Error: Failed which: Not found ant: null

/Magnus

**Comment by xzhe** [comment]
Hi,

Can you run ant from the command line? It looks like that ant is not in your PATH.

**Comment by MagnusTim** [comment]
Hi,
Command line does not work but the agent identifies both ant and ANT_Home as capabilities, should not that be enough?

**Comment by DavidStaheli** [comment]
Hi @MagnusTim.  Sorry for the trouble and disruption to your customer's build processes.  There are two things affecting what you're seeing:

First, just as you noted above, when the build agent starts, it checks to determine whether it has the Ant "capability."  Depending on which version of the agent you're running, it does this by looking for the ANT_HOME environment variable or for 'ant' in the path.  It sounds like your agent found this capability.

Second, when the build is executing, the Ant build task ([source code here](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/ANT/anttask.ts#L174)) simply expects 'ant' to be in the path.  Can you please verify it's in the path?  Sometimes people hit an issue where it's in the path for one user account of the OS, but not in the path for the account the build agent is running as.

You could also make sure you're running a newer version of the build agent (manually downloadable from [here](https://github.com/Microsoft/vsts-agent)) in case that portion didn't get updated during your upgrade.

If you still have an issue, can you please send me your full build log?   (dastahel@microsoft.com)

Thanks,
David

**Comment by MagnusTim** [comment]
Hi David,
Thanks for you answer

**1. Agent**
I am running the latest build agent version -2.111.1

**2. The ant build task**
Yest, ant is in the path.
Is there a way to get more debug information from the anttask.ts, I saw there where the tl.debug rows in the code, I have set the system.debug=True in the build.

I tried to runt the ant command in a command prompt from the java SDK\bin folder then I got it to work.
Like this, standing in c:\Program Files\Java\jdk1.8.0_101\bin
Running D:\ant\bin\ant.bat -buildfile  D:\Builds\TestNewAgent\_work\2\s\MySourcesfolders\build.xml, so it seems that is does not find Java SDK. I have Java JRE on the same macine as well.

I have also tried to add the Java SDK path to the JDK path under Advanced in the ant asks, still I get: Failed which: Not found ant: null

I will am sending the entire log to you.

/Magnus

**Comment by MagnusTim** [comment]
xzhe and David, you where both right, it vas the PATH to D:\ANT\Bin that was missing for the Build user.

Thanks!

**Comment by DavidStaheli** [comment]
Thank you for reporting the issue regardless, @MagnusTim.  Maybe the conversation here will be helpful to others.

**Comment by kimptoc** [comment]
The method for finding maven provides a bit more feedback, maybe something similar/better could be adopted for the ant task too. :)

**Comment by DavidStaheli** [comment]
@ericsciple, people are finding this error message pretty cryptic:
`Error: Failed which: Not found ant: null`

Can the task-lib's [task.ts line 1003](https://github.com/Microsoft/vsts-task-lib/blob/master/node/task.ts#L1003) supplement the error to output something more, like:
`Error: Failed which: the tool was not found in the path: ant`

**Comment by ericsciple** [comment]
makes sense

**Comment by Brain2000** [comment]
A year later and it still reports "Not found ant: null".
Thanks for having this thread available, I was able to easily fix the issue.

**Comment by JaydeepUniverse** [comment]
I am facing this issue even though tried with all possible configuration.

In the agent

```
nnadmin@cc-base-vm:~$ echo $PATH
/usr/local/ant/bin:/usr/local/ant/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
nnadmin@cc-base-vm:~$ echo $ANT_HOME
/usr/local/ant
nnadmin@cc-base-vm:~$ which ant
/usr/local/ant/bin/ant
nnadmin@cc-base-vm:~$ ls -ltrh /usr/local/ant/bin
total 72K
-rw-r--r-- 1 root root 1.8K Oct 13 04:41 runrc.cmd
-rwxr-xr-x 1 root root 3.3K Oct 13 04:41 runant.py
-rwxr-xr-x 1 root root 4.1K Oct 13 04:41 runant.pl
-rw-r--r-- 1 root root 1.1K Oct 13 04:41 lcp.bat
-rw-r--r-- 1 root root 4.3K Oct 13 04:41 envset.cmd
-rwxr-xr-x 1 root root 3.4K Oct 13 04:41 complete-ant-cmd.pl
-rw-r--r-- 1 root root 3.4K Oct 13 04:41 antenv.cmd
-rwxr-xr-x 1 root root 2.1K Oct 13 04:41 antRun.pl
-rw-r--r-- 1 root root 1.5K Oct 13 04:41 antRun.bat
-rwxr-xr-x 1 root root  862 Oct 13 04:41 antRun
-rw-r--r-- 1 root root 2.8K Oct 13 04:41 ant.cmd
-rw-r--r-- 1 root root 7.3K Oct 13 04:41 ant.bat
-rwxr-xr-x 1 root root  12K Oct 13 04:41 ant
```

But while running through the pipeline
```
##[debug]which 'ant'
##[debug]not found
##[debug]Unable to locate executable file: 'ant'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
##[error]Error: Unable to locate executable file: 'ant'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

In the pipeline running through simple commands just to verify if ant is working
```

##[debug]/usr/bin/bash arg: --noprofile
##[debug]/usr/bin/bash arg: --norc
##[debug]/usr/bin/bash arg: /home/nnadmin/azure-devops-agent/_work/_temp/26d82427-22eb-4318-be3c-b03114ea4482.sh
##[debug]exec tool: /usr/bin/bash
##[debug]arguments:
##[debug]   --noprofile
##[debug]   --norc
##[debug]   /home/nnadmin/azure-devops-agent/_work/_temp/26d82427-22eb-4318-be3c-b03114ea4482.sh
/usr/bin/bash --noprofile --norc /home/nnadmin/azure-devops-agent/_work/_temp/26d82427-22eb-4318-be3c-b03114ea4482.sh
+ java -version
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
+ /usr/local/ant/bin/ant -version
Apache Ant(TM) version 1.10.12 compiled on October 13 2021
+ which ant
+ ant -version
/home/nnadmin/azure-devops-agent/_work/_temp/26d82427-22eb-4318-be3c-b03114ea4482.sh: line 5: ant: command not found
##[debug]Exit code 127 received from tool '/usr/bin/bash'
##[debug]STDIO streams have closed for tool '/usr/bin/bash'
```

Kindly advise how to resolve this issue?
User is same for which ant is installed and pipeline agent is running
