### ISSUE TITLE
AzureRmWebAppDeployment: Json Variable Substitution causes build to hang 

### ISSUE THREAD

**Issue by weltan** [Microsoft/vsts-tasks#3544]
I'm using the Azure App Service Deploy 3.*(preview) task (I assume that's AzureRmWebAppDeployment?) to deploy a node.js app to an App Service Web App running Windows. I'm able to successfully build/deploy a working app. 

However, when I try to add an additional feature, 'File Transforms & Variable Substitution Options' -> 'JSON variable substitution', it causes the build to hang indefinitely (30 minutes +).

Here's the abbreviated logs, let me know if you need more and I can pm them to you:
```
******************************************************************************
Starting: Azure App Service Deploy: esb-test
******************************************************************************
==============================================================================
Task         : Azure App Service Deploy
Description  : Update Azure App Service using Web Deploy / Kudu REST APIs
Version      : 3.0.5
Author       : Microsoft Corporation
Help         : [More Information](https://aka.ms/azurermwebdeployreadme)
==============================================================================
agent.workFolder=D:\a
loading inputs and endpoints
.....
SetParametersFile=D:\a\1\s
RemoveAdditionalFilesFlag=false
ExcludeFilesFromAppDataFlag=false
TakeAppOfflineFlag=false
RenameFilesFlag=false
AdditionalArguments=null
WebAppUri=null
XmlTransformation=false
JSONFiles=properties.json
XmlVariableSubstitution=false
....
Got connection details for Azure App Service:'myAppHere'
Finding files matching input: D:\a\1\s
System.DefaultWorkingDirectory=D:\a\1\s
```

Build hangs on the last line.

In Variables, I have `database.sqlUser` for name and `user1` for value: build fails both when the value is secret (lock is checked), and when value is in plaintext. 'Allow at Queue Time' is not checked.

Looking at the code, it seems like this might be an issue in the `createEnvTree` function, as I don't see the debug message on line 65 [here](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Common/webdeployment-common/jsonvariablesubstitutionutility.ts).

**Comment by vincentdass** [comment]
@weltan , thanks for reporting the issue. 
Can you enable system.debug = true and queue a release and share the logs ?

Can you please enable `XML transformation`  option in **'File Transforms & Variable Substitution Options**', if it doesn't hurt your deployment ?

[If XML tranformation is enabled, it will search for web.<env_name>.config and apply transformation on web.config]. If no such file is found, transformation is skipped.

For **File Transforms & Variable Substitution Options**,  if package(zip) is provided, it will be extracted to a temp location. If Folder path is provided, it will be copied to temp location. 
It may be possible that the extraction or copy makes the deployment to hang. 


If you have access to the release agent, we can add some debug statements and observe the logs

**Comment by weltan** [comment]
@vincentdass just pm'ed you via email with a full set of logs, enabling the `XML transformation` didn't seem to make a difference. We are in fact using a folder path: `$(Build.SourcesDirectory)` for the deploy task, so maybe that's why.

**Comment by vincentdass** [comment]
@weltan , This issue is resolved and the fix will be available in upcoming deployment.
The issue was with copying the sourceDirectory to temp folder (sub folder of source directory).
