### ISSUE TITLE
Need to execute my automation scripts when build is moved from dev to QA environments.

### ISSUE THREAD

**Issue by Cva2904** [Microsoft/vsts-tasks#3573]
Hi Everyone,

I need to execute my automation scripts when build is moved from dev to QA environments.

I am entirely new to this approach.

Please keep me posted if any one has worked on this earlier.

Thanks in advance.
Siva.

**Comment by ericsciple** [comment]
This doesn't sound like an issue with any tasks in this repo. Build docs [are here](https://www.visualstudio.com/en-us/docs/build/overview). Release docs [are here](https://www.visualstudio.com/en-us/docs/release/overview).
