### ISSUE TITLE
Use variables from "Build number format" in "Artifact Name"

### ISSUE THREAD

**Issue by rbluethl** [Microsoft/vsts-tasks#3585]
Hello,

I wanted to ask if it's possible to use the same variables from Build number format (for example "$(Build.DefinitionName)_$(date:yyyyMMdd)$(rev:.r)_$(BuildConfiguration)") in the **Publish Build Artifacts** task's Artifact Name?

Currently, our setup is configured as follows:

Build number format: $(Build.DefinitionName)_$(date:yyyyMMdd)$(rev:.r)_$(BuildConfiguration)
Artifact Name: $(Build.DefinitionName)_$(BuildConfiguration)

However, we encountered troubles using the variables $(date:yyyyMMdd) and $(rev:.r) in the Artifact Name.
This seems a little bit odd, since the variables $(Build.DefinitionName) and $(BuildConfiguration) are also available in both of the names above. Is there a chance to achieve using the same variables/format?

Thank you in advance.
Ronald

**Comment by ericsciple** [comment]
@chrisrpatterson @bryanmacfarlane fyi

@rbluethl today it's not supported

**Comment by renatotkr** [comment]
@ericsciple 

Do you plan to support this?

Thanks

**Comment by ericsciple** [comment]
Would using $(build.buildnumer) in the artifact name solve what you are after?

**Comment by renatotkr** [comment]
yes, I'm using a task to process the buildnumber as I need before

It would be simpler if I could just use this variable directly, just a suggestion

thanks for the fast reply!
