### ISSUE TITLE
Azure App Service Deploy MSDeploy Additional Arguments

### ISSUE THREAD

**Issue by podgito** [Microsoft/vsts-tasks#3587]
I'm receiving the error: 
> Unrecognized argument '"-setParam:name=MyParam,value=test"'. All arguments must begin with "-".

Looks like the value provided in the Additional Arguments field is being wrapped in double quotes. Must have been introduced very recently as I had been using this for deployments 4 weeks ago, successfully.

**Comment by podgito** [comment]
Just adding logs to compare the MSDeploy commands which further highlights the issue. (I've hidden some sensitive  values)

> 2017-01-06T10:11:30.2356658Z "C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe"  -verb:sync -source:package="C:\Agent\dd337cfa0\Release\drop\src\AuthServer.Api\dist\AuthServer.Api.zip" -dest:auto,ComputerName='https://SITENAME.scm.azurewebsites.net:443/msdeploy.axd?site=SITENAME',UserName='********',Password='********',AuthType='Basic' -setParam:name='IIS Web Application Name',value='SITENAME' -setParamFile="C:\Agent\dd337cfa0\Release\drop\src\AuthServer.Api\dist\AuthServer.Api.SetParameters.xml" -setParam:name="IdentityContext-Web.config Connection String",value="Server=tcp:DBNAME.database.windows.net,1433;Database=DBNAME;User ID=USER;Password=********;Trusted_Connection=False;Encrypt=True;" -userAgent:VSTS_258956bd-9a5b-43ad-aebc-0871debbcf9e_release_2_63_63_1 2>error.txt

> 2017-02-10T12:43:54.7305853Z [command]"C:\Program Files (x86)\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package='C:\Agent\dd337cfa0\Release\drop\src\AuthServer.Api\dist\AuthServer.Api.zip' -dest:auto,ComputerName='https://SITENAME.scm.azurewebsites.net:443/msdeploy.axd?site=SITENAME',UserName='********',Password='********',AuthType='Basic' -setParam:name='IIS Web Application Name',value='SITENAME' -setParamFile=tempSetParameters.xml "-setParam:name=IdentityContext-Web.config Connection String,value=Server=tcp:DBNAME.database.windows.net,1433;Database=DBNAME;User ID=USER;Password=********;Trusted_Connection=False;Encrypt=True;" -userAgent:VSTS_258956bd-9a5b-43ad-aebc-0871debbcf9e_release_2_64_64_1

**Comment by arjgupta** [comment]
hi podgito, earlier you would have been passing additional arguments as -setParam:name=**"**MyParam**"**,value=**"**test**"**    
Please try passing like so: -setParam:name=**'**MyParam**'**,value=**'**test**'**
just replace the " with '  . It should work

**Comment by podgito** [comment]
Yes, thank you, that worked.

**Comment by podgito** [comment]
Apologies, I jumped the gun on that saying it worked. It did not throw the error this time. However examining my server after the deployment it seemed like the setParam did nothing. However changing the name and value to not use any quotes works on the server. AFAIK the quotes should be used when names or values have spaces in them. So I believe this is still an issue.

**Comment by arjgupta** [comment]
Hi podgito , can you send us the debug logs for the case when you are replacing " with '

**Comment by podgito** [comment]
I investigated further. Everything is fine with regards the MSDeploy (using single quotes instead of double) 

The issue I'm actually seeing now is that **redeploying the same build with new setParam value is not seen on the server's web.config**. It requires me to create a new build and release that, then the new value is seen.

You can close this issue and I will investigate this other issue. Would you have any advice on how to investigate this or where the problem might lie?

**Comment by arjgupta** [comment]
Hi @podgito , can you verify that in your parameter.xml file , the parameter that you are trying to substitute, is declared and scope and match are correctly specified.

**Comment by podgito** [comment]
I have encountered an issue when using single quotes instead of double quotes.

In the Additional Arguments I have -setParam:'tickets_v5Entities-Web.config Connection String'='$(ConnectionString)'

My connection string is an entity framework connection string which as you probably know contains single quotes for example

metadata=res://*/Models.Domain.EventsModel.csdl|res://*/Models.Domain.EventsModel.ssdl|res://*/Models.Domain.EventsModel.msl;provider=System.Data.SqlClient;provider connection string='1.2.3.4;initial catalog=myDB;user id=admin;password=password123;MultipleActiveResultSets=True;App=EntityFramework'

I believe that double quotes are the correct way to delimit the start and end of the values and not single quotes.
