### ISSUE TITLE
Capture Trace/TestContext Writes

### ISSUE THREAD

**Issue by marianogenovese** [Microsoft/vsts-tasks#3588]
Hi!, im using VSTest task in TFS (V. 14.102.25423.0) for running my tests, in these tests i use:
Debug.WriteLine, Trace.WriteLine and TestContext.WriteLine but none of the messages written on the console do not appear. There are a config to change?

**Comment by vimegh** [comment]
@marianogenovese  You can refere to #3492 . We dont show test console output for passed tests. Only in case of failed tests, you will be able to see the console output of test in Test tab of completed build or in build UI while running tests.

**Comment by cltshivash** [comment]
You should be able to download the trx of the test run from run details/summary. The trx will contain all the information that you are looking for.

**Comment by marianogenovese** [comment]
Hi, is possible to change that behaviour, show my trace writes always?

**Comment by bgavrilMS** [comment]
Might work with a .runsettings file - have a look at DeleteDeploymentDirectoryAfterTestRunIsComplete property https://msdn.microsoft.com/en-us/library/jj635153.aspx

**Comment by cltshivash** [comment]
@marianogenovese We don't have plans to do that. We will take up the ask an enhancement request.
