### ISSUE TITLE
semi-colon separation in command field of ssh task

### ISSUE THREAD

**Issue by singlewind** [Microsoft/vsts-tasks#3602]
By design, the ssh task will separate command with semi-colon which makes challenge for cases like if we have semi-colon in the parameters which not suppose to be separated. Like connection string in .NET Core.

The code may can be improved by not separate quoted strings like printf "a=b;c=d" to printf "a=b and c=d"

**Comment by ancaantochi** [comment]
I run into the same issue when I pass a connection string as argument.

**Comment by lkillgore** [comment]
Hi @singlewind and @ancaantochi, I think we have a solution for you: in version 0.121.0 we added a new option 'inline' script, which allows for a full-blown bash script.  No need for ';' delimited input anymore.  Please check it out when you get a chance and let us know if it doesn't fit your needs.

I'm closing this ticket with the expectation that this will work for you.  If you have any other suggestions or improvements, please open another ticket.  Thanks!
