### ISSUE TITLE
Coverage data for native linux builds

### ISSUE THREAD

**Issue by lmussier** [Microsoft/vsts-tasks#3605]
Hello,

I have a question regarding #3036 and the newly available linux hosted machine.
The cobertura task only accepts coverage report aligned with coverage-04.dtd, the fact is a lot a linux native builds are based on gcc which generate it own type of coverage reporting (with lcov). A common way to integrate coverage reports to CI services (i.e jenkins) is to generate cobertura report from gcc report thanks to gcovr (which is still based on coverage-03.dtd).
And as it stands now, the whole process fails because the coverage tasks accept only coverage-0.4.dtd format.

The need here is to have gcc based coverage report available in VSTS, I think there is a least two possible ways to do so :
- Create a lcov task
- Add the possibility to cobertura task to work with coverage-03.dtd

Is there a plan to support more coverage tools or extends the existing tasks?

Ps: Having gcovr produce coverage-04.dtd based report is certainly the solution for me but it is not available (I've submit an issue on gcovr side).

**Comment by nigurr** [comment]
@lmussier Currently we do support latest version (coverage-04.dtd).
We do welcome your support in improving this. 

Please do vote for this in user voice forum so that we can prioritize the same
https://visualstudio.uservoice.com/forums/330519-team-services/category/145281-test
