### ISSUE TITLE
NuGet Publisher Tasks with additional option "ignore existing packages"

### ISSUE THREAD

**Issue by smartin34** [Microsoft/vsts-tasks#3606]
Let’s assume you have a TFS build process which produces 30 NuGet packages, each with its own package version.
29 packages are unchanged, just the contents of a single package has been changed, so the developer increases the version number for this package in AssemblyInfo.cs using the AssemblyInformationalVersion.
Other 29 packages are also produced with each build, because the build is configured to produce packages for all .csproj’s or .nuspec’s in the repository.
But as these 29 unchanged packages are not marked as “new” (no change at the package version), they should be ignored at publishing to the package feed.
Already existing package versions on the feed should never been touched again! There’s no overwrite allowed on the server feed. AllowOverwriteExistingPackages=false.

There should be definitely an option to ignore the packages during “nuget push” (in the VSTS/TFS NuGet Publisher Task by the way), when the packages with the same ID are already exist on the feed.
It should not abort to push on first “collision”, it should just ignore it when the option “AllowOverwriteExistingPackages” on the server is disabled.

In the scenario, this will result in just adding the single package which was really changed, the other 29 will be ignored and not pushed again. The Developer does not need to push a package by hand.

**Comment by alexmullans** [comment]
This is fixed in #4397
