### ISSUE TITLE
Visual Studio Team Services Agent Deployment task stuck indefinitely on all subsequent builds after reboot

### ISSUE THREAD

**Issue by bhushanjogi** [Microsoft/vsts-tasks#3610]
Hello devops_tools@microsoft.com,

Need you help.. VSTS build is stuck in the queue indefinitely and it shows build cancelling but doesn't cancel..

Following if the error : 
ERROR:
System.ServiceModel.AddressAlreadyInUseException: Cannot listen on pipe name 'ne
t.pipe://localhost/taskagent/49/2c17f384d8ff129f087b0697352a9b4f' because anothe
r pipe endpoint is already listening on that name. ---> System.IO.PipeException:
 Cannot listen on pipe name 'net.pipe://localhost/taskagent/49/2c17f384d8ff129f0
87b0697352a9b4f' because another pipe endpoint is already listening on that name
.

**Comment by treierts** [comment]
Where did you find this error? We are also having problems with our Hosted Build Agents. The build jobs are queued up and waiting for a free agent, but all agents are Online & Ready. Nothing happens.

**Comment by bhushanjogi** [comment]
try executing .RunAgent.cmd from agent folder on buildserver.. If its working properly it will kick start the agent but in this case it throws above error message.. please let me know if you find the solution

**Comment by treierts** [comment]
I ran the .Run.cmd in my agent folder, and it just says this:

**Comment by bhushanjogi** [comment]
@treierts   any update ? 
@devops_tools@microsoft.com  please respond

**Comment by treierts** [comment]
This was our issue, I don't know if this is related to your issue:

https://blogs.msdn.microsoft.com/vsoservice/?p=13385

**Comment by sureshjanarthan** [comment]
Hi @treierts , I am also facing same issue.  Were you able to get a solution for this issue.

**Comment by treierts** [comment]
@sureshjanarthan Yes, the issue resolved itself within the same day. Please see the link https://blogs.msdn.microsoft.com/vsoservice/?p=13385 which describes what the issue was.
