### ISSUE TITLE
Post Clean Up ends up with error

### ISSUE THREAD

**Issue by hqer2k9** [Microsoft/vsts-tasks#3628]
Trying to clean up the vnext agent working directory with the "Delete Files" task.

> Source Folder: $(Agent.BuildDirectory)
> Contents: *

when executing the build, it finishes as partialy succeeded with the following error message:

```
Error: Failed rmRF: rm: could not remove directory (code EBUSY): D:\Agent1\_work\13\s
Couldn't delete one or more files
```

looking into the agent directory, the "S" folder is still there, but empty.
I then tryed using inline poweshell with a 10 second wait pause, but the error still comes up.
any ideas how to post clean up the source folder?

**Comment by ericsciple** [comment]
@hqer2k9 i'm just guessing, but it could be the `s` folder itself if it's the working directory for the process doing the cleanup. One thing you could try is changing the pattern to $(Agent.BuildDirectory)/**/* and that pattern may avoid the root folder itself.

**Comment by bryanmacfarlane** [comment]
This can be achieved by setting the Build.Clean variable.  See Q & A section.  Let the agent do this for you.

https://www.visualstudio.com/en-us/docs/build/define/repository

**Comment by Mardoxx** [comment]
@bryanmacfarlane this only does it when initializing the job, not post job.

**Comment by Mardoxx** [comment]
I set the `Build.Clean` to `all` and it does nothing post job. It just clears the directories _before_ pulling sources, not after everything has built successfully. Also see https://github.com/Microsoft/vsts-agent/issues/708
