### ISSUE TITLE
Non-Fatal - fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by Mertsch** [Microsoft/vsts-tasks#3631]
This is absolutely not fatal at all, as I am building from TFVC

```##[section]Starting: Test Assemblies
==============================================================================
Task         : Visual Studio Test
Description  : Run tests with Visual Studio test runner
Version      : 2.0.13
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=835764)

[...]
[command]C:\Build\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.0.13\TestSelector\TestSelector.exe PublishCodeChanges
PERF: CommandUtility.GetBaseLineBuild: took 543.9862 ms
PERF: GetCommitsAssociatedBetweenBuilds: took 44.7715 ms
fatal: Not a git repository (or any of the parent directories): .git
PERF: GenerateExternalGitChanges: took 119.9295 ms
Total code changes = 0
==============================================================================```

**Comment by prawalagarwal** [comment]
Hi @Mertsch,

This seems like a bug. Thanks for reporting. Will update this thread with ETA for the fix.

Thanks

**Comment by Mertsch** [comment]
@prawalagarwal Yes, it was a non-test-impacting code change

**Comment by prawalagarwal** [comment]
@Mertsch  The fix has been pushed. You will not see this log from next release. (10-15 days)

Thanks

**Comment by JawadS** [comment]
Hi guys, I keep getting the above error when trying to pull and push to a github repo in VSTS tasks. Can you please help? Below is what my task looks like and it keeps throwing the above error. 

![image](https://user-images.githubusercontent.com/8505245/28530680-8cb3a084-708c-11e7-851f-a2e04bc78e24.png)
