### ISSUE TITLE
TFS 2015 U3 - custom task isn't visible

### ISSUE THREAD

**Issue by nixel2007** [Microsoft/vsts-tasks#3639]
Hello.
I've create an extension with some custom tasks.
When I upload this extension to VSTS, I can found them in build-def steps.
Then I've tried to install this extension on (on prem) TFS 2015, project collection also was selected. But I can't find my tasks at build-def (i've checked the `all` category also).
Any tips I missed?

My task.json looks like this:
```json
{
    "$schema": "https://raw.githubusercontent.com/AArnott/vso-agent-tasks/9b41d803a/tasks.schema.json",
    "id": "d50af4f0-3820-46c1-8861-ccada0c43755",
    "name": "gitsync",
    "visibility": [
        "Build",
        "Release"
    ],
    "friendlyName": "GitSync",
    "description": "1C Storage to git synchronization",
    "helpMarkDown": "",
    "category": "Utility",
    "author": "SilverBulleters, LLC",
    "version": {
        "Major": 0,
        "Minor": 2,
        "Patch": 4
    },
    "instanceNameFormat": "GitSync",
    "inputs": [
        // some inputs
    ],
    "execution": {
        "Node": {
            "target": "index.js"
        }
    }
}
```

P.S. Sorry, if I post in wrong repo.

**Comment by nixel2007** [comment]
Want to add - I've tried install other extensions ([this](https://marketplace.visualstudio.com/items?itemName=nkdagility.gittasks&targetId=a0d9ff6d-52a1-4e04-aa95-4dc437ec6ab9) for example) - I can add them to my build-def without any problems

**Comment by bryanmacfarlane** [comment]
Are you writing an extension or using tfx to upload (testing)?

Move this issue to here:  https://github.com/Microsoft/vsts-task-lib
