### ISSUE TITLE
Execute UWP Unit tests projects on Windows Server 2016 Build Controller with TFS 2015 Build Agent (non xaml)

### ISSUE THREAD

**Issue by dersteve** [Microsoft/vsts-tasks#3640]
On a Windows Server 2016 machine with a TFS 2015 Build Agent (TFS Build System - not the old XAML Builds) the execution of UWP Unit Tests hangs/fails.

When logging on to the server the UWP unit test app is started, but it seems to fail to communicate back to the test runner. The test runner runs into a timeout, when looking into the logs.

**Comment by nigurr** [comment]
@dersteve Can you give more information on how you are running your tests and share your build logs with us? [please do enable `system.debug=true` in build variables

**Comment by nigurr** [comment]
Closing this issue as there's no further information available. Please do reopen if needed

**Comment by dersteve** [comment]
Here is the **test log**: You can see that there is timeout at the end.

V, 3464, 1, 2017/02/15, 10:21:54.487, 1714666733072, vstest.console.exe, AddPackage(eb61e043-d453-43ae-bda3-569724225115_1.0.0.0_x64__41zkwv185hb04) Error Code:0 and Error Message:
V, 3464, 1, 2017/02/15, 10:21:54.675, 1714668560193, vstest.console.exe, Established network loopback.
V, 3464, 1, 2017/02/15, 10:21:54.675, 1714668561047, vstest.console.exe, AppContainerUtilities.InstallPacakge(eb61e043-d453-43ae-bda3-569724225115_1.0.0.0_x64__41zkwv185hb04) returned:0
V, 3464, 1, 2017/02/15, 10:21:54.675, 1714668562408, vstest.console.exe, AppContainerUtilities.InstallPacakge: Time taken for Installing pacakge 00:00:03.5453938
I, 3464, 1, 2017/02/15, 10:21:54.675, 1714668612155, vstest.console.exe, RunTestsArgumentProcessor:Execute: Test run is starting.
V, 3464, 1, 2017/02/15, 10:21:54.737, 1714669231077, vstest.console.exe, Package C:\[....]ABCDEF.Tests_Test\[.....].Tests.appx has architecture X64.
V, 3464, 1, 2017/02/15, 10:21:54.753, 1714669334400, vstest.console.exe, Using effective platform:X64 effective framework:Framework45
I, 3464, 1, 2017/02/15, 10:21:54.831, 1714670131428, vstest.console.exe, Using platformType OutOfProc for inIsolation=True.
V, 3464, 1, 2017/02/15, 10:21:54.847, 1714670348690, vstest.console.exe, TestRunRequest.ExecuteAsync: Creating test run request.
I, 3464, 1, 2017/02/15, 10:21:54.862, 1714670389971, vstest.console.exe, AssemblyResolver: Microsoft.VisualStudio.Utilities.Internal, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Resolving assembly.
I, 3464, 1, 2017/02/15, 10:21:54.862, 1714670453643, vstest.console.exe, AssemblyResolver: Microsoft.VisualStudio.Utilities.Internal, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Resolved assembly. 
I, 3464, 1, 2017/02/15, 10:21:54.862, 1714670487027, vstest.console.exe, AssemblyResolver: Microsoft.VisualStudio.Telemetry, Version=14.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Resolving assembly.
I, 3464, 1, 2017/02/15, 10:21:54.878, 1714670550081, vstest.console.exe, AssemblyResolver: Microsoft.VisualStudio.Telemetry, Version=14.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a: Resolved assembly. 
V, 3464, 1, 2017/02/15, 10:21:54.987, 1714671614015, vstest.console.exe, TestRunRequest.ExecuteAsync: Created test run request.
V, 3464, 1, 2017/02/15, 10:21:54.987, 1714671680755, vstest.console.exe, TestRunRequest.ExecuteAsync: Starting.
I, 3464, 1, 2017/02/15, 10:21:54.987, 1714671693772, vstest.console.exe, TestRunRequest.ExecuteAsync: Starting run with settings:TestRunCriteria:
   KeepAlive=False,FrequencyOfRunStatsChangeEvent=10,RunStatsChangeEventTimeout=00:00:01.5000000,TestCaseFilter=Priority!=0,TestExecutorLauncher=Microsoft.VisualStudio.TestPlatform.Utilities.UniversalAppTestExecutorLauncher
   Settingsxml=<RunSettings>
  <RunConfiguration>
    <ResultsDirectory>C:\TestResults</ResultsDirectory>
    <TargetPlatform>X64</TargetPlatform>
    <TargetFrameworkVersion>Framework45</TargetFrameworkVersion>
  </RunConfiguration>
</RunSettings>

V, 3464, 1, 2017/02/15, 10:21:54.987, 1714671697388, vstest.console.exe, TestRunRequest.ExecuteAsync: Wait for the first run request is over.
V, 3464, 1, 2017/02/15, 10:21:54.987, 1714671748433, vstest.console.exe, TestExecutorServiceClient: StartTestRun: Validated the parameters and updated the active context.
V, 3464, 1, 2017/02/15, 10:21:55.003, 1714671791180, vstest.console.exe, TestExecutorServiceClient: ShouldRelaunchExecutorProcess: Restart executor process True. Previous launcher '', Current launcher 'Microsoft.VisualStudio.TestPlatform.Utilities.UniversalAppTestExecutorLauncher'
V, 3464, 1, 2017/02/15, 10:21:55.003, 1714671791653, vstest.console.exe, TestExecutorServiceClient: EnsureInitialized: Relaunching executor.
V, 3464, 1, 2017/02/15, 10:21:55.050, 1714672322992, vstest.console.exe, TestExecutorServiceClient: Initializing Proxy connection.
I, 3464, 1, 2017/02/15, 10:21:55.050, 1714672362095, vstest.console.exe, UniversalTestExecutorProxy: Creating a test executor service using EndPointAddres: 'net.tcp://127.0.0.1:11000/UniversalTestExecutorService'
V, 3464, 1, 2017/02/15, 10:21:55.409, 1714675858517, vstest.console.exe, Activating vstest.executionengine from elevated process
V, 3464, 1, 2017/02/15, 10:21:56.128, 1714683052050, vstest.console.exe, LaunchActivator: Returned with processId:4932
V, 3464, 1, 2017/02/15, 10:21:56.128, 1714683169704, vstest.console.exe, AppContainerUtilities.LaunchAppContainerTestExecutor: Started Windows app process: pid=4932 PackageFullName:eb61e043-d453-43ae-bda3-569724225115_1.0.0.0_x64__41zkwv185hb04 AppId:vstest.executionengine.universal.App.
V, 3464, 1, 2017/02/15, 10:21:56.128, 1714683170346, vstest.console.exe, AppContainerUtilites.LaunchAppContainerTestExecutor: Time taken for launching Windows app Test Executor 00:00:00.7417164
I, 3464, 1, 2017/02/15, 10:22:56.181, 1715283644409, vstest.console.exe, TestExecutorServiceClient: StartTestRun: Started the test run on the executor.
I, 3464, 1, 2017/02/15, 10:22:56.181, 1715283645579, vstest.console.exe, TestRunRequest.ExecuteAsync: Started.
V, 3464, 1, 2017/02/15, 10:22:56.181, 1715283645952, vstest.console.exe, RunTestsArgumentProcessor:Execute: Test run is queued.
V, 3464, 1, 2017/02/15, 10:22:56.181, 1715283657426, vstest.console.exe, TestRunRequest.WaitForCompletion: Waiting with timeout -1

**Comment by dersteve** [comment]
Please reopen the ticket @nigurr and sorry for the small delay in my answer.

**Comment by nigurr** [comment]
@dersteve I didn't get the issue. Can you please describe in details what's expected and what's happening

**Comment by dersteve** [comment]
I have a Windows Server 2016 machine where there is a TFS Build Agent running.

My build definition builds via the VS-Build task a solution that contains a UWP Test Project to execute UWP Unit tests. The test runner is vstest.console.exe as we use the normal VS/MS Unit Test libraries/infrastructure.

When I execute the build the test execution task fails with a timeout. When opening up the Windows Server 2016 the UWP Unit Test App is still open. It looks like the app can't communicate back with the test runner . The logs from the test runner task are the logs I've just added to this issue.

**Comment by cltshivash** [comment]
@dersteve Are you able to run the test on the 2016 build machine from cmdline directly ?

**Comment by dersteve** [comment]
@cltshivash I get the same problem, when executing them from the cmdline - it also hangs - via vstest.console.exe

**Comment by cltshivash** [comment]
@dersteve I believe the changes called out here [2016 RTM](https://blogs.technet.microsoft.com/nanoserver/2016/10/04/appreciating-the-windows-server-2016-desktop-experience/) are impacting this scenario. Please try running the tests on windows 10 and use a build agent on windows 10.
