### ISSUE TITLE
Build Variables should not be capitalized

### ISSUE THREAD

**Issue by bgavrilMS** [Microsoft/vsts-tasks#3645]
If I set a custom build variable, for example: **hello = world**
And then I run a script that prints all the env variables
I get back: 

**HELLO                          world**         

This is a problem because many systems are case sensitive. In our case, we are using Appium (a well known test framework) to run Android and iOS tests. The tests are configured to listen to environment variables that we then pass on to the Appium server, like device = "android_6.0", which is not the same as DEVICE="android_6.0"

**Comment by mjcheetham** [comment]
Looks like [this](https://github.com/Microsoft/vsts-agent/blob/d830baaacc55701b3a05c0c35cf84fe5cf09161d/src/Agent.Worker/Handlers/Handler.cs#L138) is the place where `ToUpperInvariant()` is being called.

**[src/Agent.Worker/Handlers/Handler.cs:138](https://github.com/Microsoft/vsts-agent/blob/d830baaacc55701b3a05c0c35cf84fe5cf09161d/src/Agent.Worker/Handlers/Handler.cs#L138)**
```cs
// Add the variable using the formatted name.
string formattedKey = (pair.Key ?? string.Empty).Replace('.', '_').Replace(' ', '_').ToUpperInvariant();
AddEnvironmentVariable(formattedKey, pair.Value);
```

**Comment by ericsciple** [comment]
not an issue with the tasks in this repo. i'll start a mail thread offline
