### ISSUE TITLE
Cordova Build 

### ISSUE THREAD

**Issue by rajbalakrish** [Microsoft/vsts-tasks#3656]
- The cordova build task is failing in the iOS step citing the below error
- Please specify a build.json file according to https://taco.visualstudio.com/en-us/docs/vs-taco-2017-ios-guide/#xcode8 - Detailed [logs_5153.zip](https://github.com/Microsoft/vsts-tasks/files/787362/logs_5153.zip) attached
- However the same codebase without any changes is successfully built in my local environment
- Using MacIncloud Build agent and signing identity is up-to date. Am suspecting a task issue. Do you have a feedback ?

**Comment by madhurig** [comment]
Cordova build task issues are part of an extension. Please report issues here: https://github.com/Microsoft/vsts-cordova-tasks/issues 

Thanks,
Madhuri
