### ISSUE TITLE
Run powershell script on Azure VM failed

### ISSUE THREAD

**Issue by acosmici** [Microsoft/vsts-tasks#3661]
Hello guys,

I am encountering an error when trying to run a powershell script on Azure VM;

##[error]System.Management.Automation.RuntimeException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: C:\inetpub\wwwroot\AzureSitecore\Website\Unicorn\Feature\Identity\SERIAL~1 - The directory is not empty. ---> System.Management.Automation.RuntimeException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: C:\inetpub\wwwroot\AzureSitecore\Website\Unicorn\Feature\Identity\SERIAL~1 - The directory is not empty.

Please note that this script is running without any issue when is started from that VM but from VSTS I am getting that error random, so in my case the success rate is 50% when running.
How can I solve this issue?

Kind Regards,
Adrian Cosmici

**Comment by arjgupta** [comment]
Hi @acosmici , Can you please share the full debug logs for the task at RM_Customer_Queries@microsoft.com. You can generate the debug logs by setting the system.debug variable to true in the variables tab

**Comment by acosmici** [comment]
Hi Arjun,

Please find the log attached to this email.

Regards,
Adrian Cosmici

**Comment by acosmici** [comment]
Hi guys,

Any updates on solving this issue?

Thanks,
Adrian

**Comment by arjgupta** [comment]
Hi @acosmici , the logs show that the error is originating from the powershell script that you are trying to execute. The Script name suggests that you are trying to remove a directory. Can you verify whether you are using the correct options with the deletion command. For eg. If you are using the Remove-Item cmdlet of powershell to delete your folder and if the folder you are trying to delete has subfolders, then you will have to specify the -recurse option as well.

**Comment by acosmici** [comment]
Hi @arjgupta, yes indeed with this script I am trying to remove a folder and subfolders, but as I mentioned before there is no error when I am going remote on that VM and run the script from there. I only receive that error when I am running from VSTS.
In the attachment you can see the script that I am running for this task. Please note that all the lines that are commented were previously executed and the error received was the same.

[RemoveUnicornFolder.ps1.txt](https://github.com/Microsoft/vsts-tasks/files/813056/RemoveUnicornFolder.ps1.txt)

**Comment by arjgupta** [comment]
Hi @acosmici , It seems you are trying to remove a folder in an iis website. Do you Stop your website, before running this script? If not, can you try stopping the website, then run the script, then start the website. You can use the iis web server administration cmdlets for this purpose: `start-website` and `stop-website` . You can find more about them [here](https://technet.microsoft.com/en-us/library/ee790599.aspx)

**Comment by acosmici** [comment]
Hi @arjgupta, I've tried to stop and start the website but still facing this issue.

**Comment by arjgupta** [comment]
Hi @acosmici , it seems, that there is some process that has a handle on the directory that you are attempting to delete. Can you please ensure that before running the script, no process has a handle on the directory. You can also try to stop the App Pool of the website before running the script. You can use the IIS Web Administration Module cmdlets to start, stop websites and app pools. You can also verify if there is any error with the script, by modifying it to delete some other folder on your machine instead of a website folder

**Comment by niadak** [comment]
@acosmici , Are you still facing the issue? Can you please stop the App Pool of the website before running the script and try once as @arjgupta has suggested earlier.

**Comment by acosmici** [comment]
@niadak, it appears that solved my issue. Thanks for the support.
