### ISSUE TITLE
VsTest 2.0 preview is not finding test adapter

### ISSUE THREAD

**Issue by qetza** [Microsoft/vsts-tasks#3662]
Hi,
I've tried using the 2.0 preview of the vstest task and it fails to find the xunit test adapter which is present as a nuget package.

I've done some analysis and think the issue is that the matching to find test adapter is using the pattern `**\packages\**\*TestAdapter.dll` and is not specifying the `nocase` option to minimatch but the xunit test adapter has the name `xunit.runner.visualstudio.testadapter.dll`.

You should replace in `isNugetRestoredAdapterPresent`: `{ matchBase: true }` with `{ matchBase: true, nocase: true }`.

**Comment by nigurr** [comment]
Addressed in this PR: https://github.com/Microsoft/vsts-tasks/pull/3677

Thanks for reporting the issue. It will be available with next VSTS deployment
