### ISSUE TITLE
Deploying Azure cloud service fails with internal error

### ISSUE THREAD

**Issue by asmaarabie** [Microsoft/vsts-tasks#3663]
I'm trying to deploy a cloud service through TFS continuous deployment and it fails: 

> 2017-02-21T16:15:55.6199788Z ##[error]InternalError : The server encountered an internal error. Please retry the request.

Retrying the request several times also results in a failure.

**Comment by niadak** [comment]
@asmaarabie Thanks for reporting the issue. Can you please share the details logs with us. You can set System.Debug = true in variable tab and requeue the deployment to generate details log. You can send the logs to RM_Customer_Queries@microsoft.com

**Comment by niadak** [comment]
@asmaarabie, Are you still facing the issue? If so please send the details logs to RM_Customer_Queries@microsoft.com

**Comment by asmaarabie** [comment]
It disappeared after a couple of hours
ᐧ

**Comment by niadak** [comment]
@asmaarabie Thanks for your confirmation.
