### ISSUE TITLE
WindowsMachineFileCopy doesnt work or the docs arent clear

### ISSUE THREAD

**Issue by StingyJack** [Microsoft/vsts-tasks#3664]
Source value like `$(Build.Repository.LocalPath)\**` copies some files but not others.

It doesnt fail outright (wildcards in path supported?), it just skips some files silently. 

Docs say wildcards like *\.zip are not supported but im not using that kind (i dont know what that would actually find). It just doesnt copy some of the files in subfolders.

**Comment by arjgupta** [comment]
Hi @StingyJack , can you please share the debug logs at RM_Customer_Queries@microsoft.com. Meanwhile, you can try Giving the source like so: `$(Build.Repository.LocalPath)`. It should copy all files from the folder specified.

**Comment by StingyJack** [comment]
I want to use 'folder\**' like every other task, not whatever that forbidden wildcard pattern is. 

Are *all* wildcards forbidden? I can't see how that would be very useful. Is this a build task that is being obsoleted?

**Comment by arjgupta** [comment]
Hi @StingyJack , No, currently we do not support regular expression like so `folder\**` . You also mentioned that  using the `$(Build.Repository.LocalPath)\**`, you were able to copy some files and not others. Can you clean your destination Directory, and try to copy again and see if you observe the same behaviour?

**Comment by StingyJack** [comment]
it was skipping files that exist in the source but not the target.  i replaced the task with both a powershell script and the other copy task and they work fine. dropping the "all file and subfolders" wildcard from this task also worked.

i've not seen regex wildcarding used for windows filesystems. clearly it works in some cases, but my intent was to mimic a dos `xcopy *.*`, and the unsupported wildcard example just looks like a syntax error.

**Comment by RoopeshNair** [comment]
@StingyJack, we encourage contributions, if you are willing, could you please submit a PR?

**Comment by StingyJack** [comment]
@RoopeshNair - Thanks but I'll pass on this. A PR to make the Windows File Copy task source(s) work like windows filesystem copy/xcopy wildcards,  or work like other tasks do with filesystem globbing (or to have this task just use the credentials the build agent is already running under) would probably be pushed.
