### ISSUE TITLE
Exception in ServiceFabricDeploy - Authority is null when using AAD credentials

### ISSUE THREAD

**Issue by mikanyg** [Microsoft/vsts-tasks#3678]
Got the following exception upon deployment after I had changed the AAD credentials for the SF Connection.

##[error]Exception calling ".ctor" with "1" argument(s): "Value cannot be null.
##[error]Parameter name: authority"

I have tried to update the AAD credentials for the connection once more, but same result. 

The debug output shows the following exception and stacktrace:

... AAD Authority: 
... Cluster Application ID: 
... Client Application ID: 
... ##[debug]Leaving D:\BuildAgents\BuildAgent\tasks\ServiceFabricDeploy\1.3.3\deploy.ps1.
... ##[debug]Caught exception from task script.
... ##[debug]Error record:
... ##[debug]New-Object : Exception calling ".ctor" with "1" argument(s): "Value cannot be null.
... ##[debug]Parameter name: authority"
... ##[debug]At D:\BuildAgents\BuildAgent\tasks\ServiceFabricDeploy\1.3.3\utilities.ps1:67 char:12
... ##[debug]+     return New-Object -TypeName $TypeName -ArgumentList $ArgumentList
... ##[debug]+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... ##[debug]    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
... ##[debug]    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand
... ##[debug] 
... ##[debug]Script stack trace:
... ##[debug]at Create-Object, D:\BuildAgents\BuildAgent\tasks\ServiceFabricDeploy\1.3.3\utilities.ps1: line 67
... ##[debug]at Get-AadSecurityToken, D:\BuildAgents\BuildAgent\tasks\ServiceFabricDeploy\1.3.3\utilities.ps1: line 94
... ##[debug]at <ScriptBlock>, D:\BuildAgents\BuildAgent\tasks\ServiceFabricDeploy\1.3.3\deploy.ps1: line 72
... ##[debug]at <ScriptBlock>, <No file>: line 1
... ##[debug]at <ScriptBlock>, <No file>: line 22
... ##[debug]at <ScriptBlock>, <No file>: line 18
... ##[debug]at <ScriptBlock>, <No file>: line 1
... ##[debug]Exception:
... ##[debug]System.Management.Automation.MethodInvocationException: Exception calling ".ctor" with "1" argument(s): "Value cannot be null.
... ##[debug]Parameter name: authority" ---> System.ArgumentNullException: Value cannot be null.
... ##[debug]Parameter name: authority
... ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.Authenticator.DetectAuthorityType(String authority)
... ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.Authenticator..ctor(String authority, Boolean validateAuthority)
... ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext..ctor(String authority)
... ##[debug]   --- End of inner exception stack trace ---
... ##[debug]   at System.Management.Automation.DotNetAdapter.AuxiliaryConstructorInvoke(MethodInformation methodInformation, Object[] arguments, Object[] originalArguments)
... ##[debug]   at System.Management.Automation.DotNetAdapter.ConstructorInvokeDotNet(Type type, ConstructorInfo[] constructors, Object[] arguments)
... ##[debug]   at Microsoft.PowerShell.Commands.NewObjectCommand.CallConstructor(Type type, ConstructorInfo[] constructors, Object[] args)
... ##[error]Exception calling ".ctor" with "1" argument(s): "Value cannot be null.
... ##[error]Parameter name: authority"

Any ideas @MikkelHegn @NCarlsonMSFT ?

**Comment by mikanyg** [comment]
Switched to the Hosted Agent Pool, and everything was working as expected.

The private agents are running version 1.105.6, could that be the cause of the issue?

**Comment by bishal-pdMSFT** [comment]
Hosted agents are running Service Fabric SDK 2.3.311 onwards.

**Comment by MikkelHegn** [comment]
And being upgraded to 2.5 in a few weeks?
