### ISSUE TITLE
Question-Is it possible to upload attachments to the test results screen in TFS?

### ISSUE THREAD

**Issue by chrisrpatterson** [Microsoft/vsts-tasks#3679]
When one of our tests fails it dumps some information to an external log file that would be really great to attach to the test results? Is this possible to do?

**Comment by acesiddhu** [comment]
@bbusacker if the test prints the information as console logs we will automatically show it in test run summary (see below image).

![image](https://cloud.githubusercontent.com/assets/1168823/23934947/cb5aefde-096e-11e7-8a65-373663e8c3bd.png)

**Comment by acesiddhu** [comment]
Closing this. Let me know if there are more questions
