### ISSUE TITLE
Xamarin: Error MSB4018: The "LinkAssemblies" task failed unexpectedly.

### ISSUE THREAD

**Issue by ericbrunner** [Microsoft/vsts-tasks#3681]
Hi,

Today I updated the Xamarin.Forms and System.Net.Http nugets from

```

<package id="Xamarin.Forms" version="2.3.3.180" targetFramework="monoandroid70" />
   <package id="System.Net.Http" version="4.3.0" targetFramework="monoandroid70" />
```
 

to

```
<package id="System.Net.Http" version="4.3.1" targetFramework="monoandroid71" />
  <package id="Xamarin.Forms" version="2.3.3.193" targetFramework="monoandroid71" />
  
```

and the VSTS build failed with that error:

> C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1580,5): Error MSB4018: The "LinkAssemblies" task failed unexpectedly.
> Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Reference to metadata item 'Mono.Security.Cryptography.SymmetricTransform' (defined in 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e') from 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' could not be resolved. ---> Mono.Cecil.ResolutionException: Failed to resolve Mono.Security.Cryptography.SymmetricTransform
> at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
> at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
> at Mono.Linker.Steps.MarkStep.MarkType(TypeReference reference)
> at MonoDroid.Tuner.MonoDroidMarkStep.MarkType(TypeReference reference)
> at Mono.Linker.Steps.MarkStep.InitializeType(TypeDefinition type)
> at Mono.Linker.Steps.MarkStep.InitializeAssembly(AssemblyDefinition assembly)
> at Mono.Linker.Steps.MarkStep.Initialize()
> at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
> at Mono.Linker.Pipeline.Process(LinkContext context)
> at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
> at Xamarin.Android.Tasks.LinkAssemblies.Execute()
> --- End of inner exception stack trace ---
> at Java.Interop.Tools.Diagnostics.Diagnostic.Error(Int32 code, Exception innerException, String message, Object[] args)
> at Xamarin.Android.Tasks.LinkAssemblies.Execute()
> at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
> at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
> Process 'msbuild.exe' exited with code '1'.

The previous builds worked. 

The first I saw in file compare that the new nugets target monoandroid71.

hope someone can help me. In the meanwhile I revert to the previous versions that target monoandroid70

best
Eric

**Comment by madhurig** [comment]
@ericbrunner; Xamarin Android 7,1 and required Android SDK build tools are not fully installed on the hosted build VMs. @thechrisjohnson has an update in progress which once complete should resolve your issue.

**Comment by madhurig** [comment]
@ericbrunner: All the planned updates to the Hosted build VMs are completed. Please try and let us know if you are still seeing issues.

**Comment by madhurig** [comment]
Please open new issue if you continue seeing issues. All planned updates have been deployed to "Hosted" and "Hosted VS2017" pools.
