### ISSUE TITLE
Vnext Zip Drop Location

### ISSUE THREAD

**Issue by SamKni8** [Microsoft/vsts-tasks#3682]
Hi, I am new to TFS and when i build my app and Package binaries by passing inline MSBuild Argument:
/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation=$(build.artifactstagingdirectory)
Also used "Publish Build Artifact" task and provided path to publish as "$(build.artifactstagingdirectory)"
And the binaries are copied as zip but with this lengthy folder path on build server; \\$BuildServer\e$\WebWork\1\a\Content\E_C\WebWork\1\s\Dev\ProviderGeoSearch\obj\Release\Package\PackageTmp\$Allbinarieshere. Want to reduce these lengthy subfolders.

**Comment by ericsciple** [comment]
@SamKni8 it sounds like you may want to customize the OutDir or OutputPath in your msbuild targets file.

**Comment by SamKni8** [comment]
Yes, but have less idea as to how i could customize it.
Currently when I publish my app to IIS Physical Path(\\Devserver\e$\WebDemoRoot\Website\) It is dropped with following path \\Devserver\e$\WebDemoRoot\Website\code\drop\Projectname.zip\Content\E_C\WebWork\1\s\Dev\ProviderGeoSearch\obj\Release\Package\PackageTmp\bin.
I want it to drop bin to Publish path here "\\Devserver\e$\WebDemoRoot\Website\code\bin"
Also what i had learnt was when we use IIS-Web App Deploy for deployment, it uses zip file as source files to deploy and then unzips it at the destination path. However, that is not happening in my case.
Assistance would be appreciated.

**Comment by bryanmacfarlane** [comment]
Not an issue with the task.  More of an msbuild question.

**Comment by rakeshjjain** [comment]
Hi Bryan,

Any suggestion on what the solution to this is?
