### ISSUE TITLE
Task "Azure Cloud Service Deployment" does not support the storage account created via ARM template

### ISSUE THREAD

**Issue by tousinn** [Microsoft/vsts-tasks#3683]
Hi there,

It looks like task "Azure Cloud Service Deployment" does not support the storage account created via ARM template.

When we pass a storage account created via ARM template to parameter "Storage Account", the task will end with error 

> "ResourceNotFound: The storage account 'XXXXXXXX' was not found."

It seems that in the function "Get-DiagnosticsExtensions", it will get the primary key of the storage like this 

> $primaryStorageKey = (Get-AzureStorageKey -StorageAccountName "$storageAccount").Primary

However, this will not be able to get the access key created by ARM template.

Is that possible to update the taks to support both the classic storage account and the one created by ARM template?

Thanks!

**Comment by jpricketMSFT** [comment]
Hi @tousinn,

It appears that you already have a good understanding of the problem. Do you have a proposed solution? If so, you can fork this repository and submit a pull request with your solution. See the contributing document (https://github.com/Microsoft/vsts-tasks/blob/master/docs/contribute.md) for more details.
If you don't have a solution, we will try to prioritize the work, and get a solution as soon as possible.

Thanks,
Jason

**Comment by tousinn** [comment]
Hi @jpricketMSFT 

Thanks for you reply.

I have tried to submit my solution in the pull request 
https://github.com/Microsoft/vsts-tasks/pull/3690

Please let me know if you have any questions.

Cheers,
Jin

**Comment by Ajay-MS** [comment]
@jpricketMSFT  @tousinn 

Azure cloud service deployment task is supposed to work with classic endpoints. Since it works with classic endpoint it can’t support ARM storage account in this task as ARM cmdlet can be access using ARM endpoint.

Cloud service is a classic resource. Modern storage accounts are ARM based resources. Both uses different types of endpoint to work with. That’s why I was not able to merge above PR.

**Comment by RobLSDev** [comment]
@Ajay-MS - Is this really still an issue?  From the Azure portal it allows users to deploy using an ARM-based storage account.  It would be great if this functionality was supported in the pipelines so we could migrate all of our existing classic storage accounts.
