### ISSUE TITLE
" One or more of the steps defined in the build does not have an associated task definition" follow up on #3418

### ISSUE THREAD

**Issue by Jonathan34** [Microsoft/vsts-tasks#3686]
> There are issues with the request or definition that will prevent the build from running:
> One or more of the steps defined in the build does not have an associated task definition. Check if the task was uninstalled or has failed a licensing check.

Just had the same on VSTS. Created a build, saved as a template, created another build from the template, changed 2 variables, tried to save & queue, failed.
not sure how to reopen the issue, but ill create a new one.

https://slb-swt.visualstudio.com/UCP/_build/index?context=allDefinitions&path=%5C&definitionId=299&_a=completed

**Comment by yaananth** [comment]
#3418 has good information on this issue, let's use the same. I am reactivating it.
