### ISSUE TITLE
Gradle Build Task

### ISSUE THREAD

**Issue by deisterhold** [Microsoft/vsts-tasks#3687]
When building a project with gradle, the Android SDK is downloaded properly, but afterwards the license agreement for the SDK is not accepted so the project fails to build.

Output:

```
Checking the license for package Android SDK Build-Tools 25.0.2 in C:\java\androidsdk\android-sdk\licenses
Warning: License for package Android SDK Build-Tools 25.0.2 not accepted.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
.
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
```

**Comment by jeffyoung** [comment]
Hi @deisterhold.  This is a case of your app requiring a later version of the tools than are installed on the hosted build image.  (We've seen it before.)  Until we deploy a new hosted image, another customer posted information on a possible workaround at #2986.  And, unfortunately, always having the latest (and using the latest during a build) is problematic (as some discussions in that thread point out).  For the record, I believe we have SDK 25.0.0 currently installed on the host image.

**Comment by madhurig** [comment]
Android SDK 25.0.2 is now available on the hosted build VMs.

**Comment by nielsen72** [comment]
@madhurig is this available already? We still see this issue
```
2017-03-16T09:35:26.3427953Z Checking the license for package Android SDK Build-Tools 25.0.2 in C:\java\androidsdk\android-sdk\licenses
2017-03-16T09:35:26.3437956Z Warning: License for package Android SDK Build-Tools 25.0.2 not accepted.
2017-03-16T09:35:26.3617944Z 
2017-03-16T09:35:26.3617944Z FAILURE: Build failed with an exception.
2017-03-16T09:35:26.3617944Z 
2017-03-16T09:35:26.3617944Z * What went wrong:
2017-03-16T09:35:26.3617944Z A problem occurred configuring project ':app'.
2017-03-16T09:35:26.3617944Z > You have not accepted the license agreements of the following SDK components:
2017-03-16T09:35:26.3617944Z [Android SDK Build-Tools 25.0.2].
```

**Comment by madhurig** [comment]
@nielsen72: The SDK version was updated to 25.2.5 but a couple of build tools versions 25.0.2 and 25.0.3 were not installed. There is an update in progress that should bring those. I will update once those are deployed.

**Comment by madhurig** [comment]
@thechrisjohnson is rolling out the update and will be able to provide a timeline.
