### ISSUE TITLE
Docker Integration install issue

### ISSUE THREAD

**Issue by xingyu217** [Microsoft/vsts-tasks#3694]
When install this extension to VSTS: https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.docker, it throws:
Extension operation denied by event callback. All the task versions belonging to Contribution tasks/docker should have the same task id. Tasks with version 0.3.1 and version 0.3.4 do not have same ids.

**Comment by harshad-kathiriya** [comment]
I got the same issue.
![image](https://cloud.githubusercontent.com/assets/15572545/23401643/6fcfab24-fdce-11e6-9539-cb140b5f1747.png)

**Comment by karluiz** [comment]
Same problema here!

**Comment by harshad-kathiriya** [comment]
Suddenly, Issue resolved. Not sure what microsoft did for that.

**Comment by Franklin89** [comment]
Still not working on my side. Just retried after your comment :-(

**Comment by karluiz** [comment]
solved !

**Comment by Franklin89** [comment]
@karluiz How did you get this solved? I am still having the same issue...

**Comment by Franklin89** [comment]
solved here aswell....gave it some more time :-)
