### ISSUE TITLE
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR during our tests run

### ISSUE THREAD

**Issue by x1c0** [Microsoft/vsts-tasks#3710]
We had our VSTS agents running gulp karma just fine for several months. Since we increased the number of tests PhamtomJS simply disconnects in the middle of our tests run. 

we tried to increase karma timeouts without any results. this is the output:

<img width="1277" alt="screen shot 2017-03-01 at 15 00 27" src="https://cloud.githubusercontent.com/assets/2421483/23462886/e2775f02-fe8f-11e6-85df-1861e1edd4cd.png">

Thank you in advance for some help

**Comment by cltshivash** [comment]
Please follow up with the concerned tool owners.
