### ISSUE TITLE
Missing Documentation on "Azure PowerShell" Task

### ISSUE THREAD

**Issue by brett3210** [Microsoft/vsts-tasks#3712]
I'm struggling to find documentation on the "Azure PowerShell" Task.  The "More Information" link for the Task takes you to the link below, which in turn takes you to the VSTS Tasks Code page in GitHub:
https://www.visualstudio.com/en-gb/docs/build/steps/deploy/azure-powershell

In particular, I'd like to understand what the "Azure PowerShell" task does (and doesn't do) compared to the "PowerShell on Target Machines" Task

**Comment by ericsciple** [comment]
@brett3210 depending on which type of endpoint you are using, the azure powershell task attempts to find/load the azure or azure rm modules on your machine, and initialize the connection, before running your script. So when your script runs, you can move forward with running azure powershell commands, and don't need to worry about initializing the connection. The specific commands that it runs are printed in cyan in the web console.

**Comment by brett3210** [comment]
Thanks.  How does the Task know which machine(s) to apply the steps (which you mentioned) to, given there isn't a "Machines" field for the Task (unlike the "PowerShell on Target Machines" Task)

**Comment by ericsciple** [comment]
The Azure PowerShell task just runs as task in your build (whatever machine your build lands on). The bootstrapper script initializes the azure powershell connection before invoking your script.

**Comment by niadak** [comment]
AzurePowerShell task is equivalent to PowerShell task under Utility category except it set up Azure connection and allow user to execute Azure PowerShell commmands. Both run on the Automation agent machine.

On the other hand "PowerShell on Target Machines" task run the PowerShell task to a Remote machine.

**Comment by niadak** [comment]
@brett3210 I am assuming you have clarity on Azure PowerShell task behavior. I am closing the issue. Please feel free to repopen if you need any more info.
