### ISSUE TITLE
Handling KendoUI controls using coded ui

### ISSUE THREAD

**Issue by Cva2904** [Microsoft/vsts-tasks#3728]
Hi Everyone,

i have written customised coded using UITestControl and UITestControlCollection to select values from KendoUI Dropdown using CodedUI.

I am able to select value from dropdown, but i having performance issue [it takes time while selecting the values].

Need inputs on who we can reduce time while selecting values from dropdowns.

Thanks in advance,
Siva Kumar.

**Comment by cltshivash** [comment]
Not related to the VSTS Tasks. Please work with Microsoft Support for Coded UITest Issues.
