### ISSUE TITLE
DistributedTests: Error "Value cannot be null. Parameter name: uriString"

### ISSUE THREAD

**Issue by ppptrevoro** [Microsoft/vsts-tasks#3763]
I am getting this error when trying to run CodedUITests on a windows 7 virtual machine using the DistributedTests task.  The tests are found but never execute and I am hit with the following error message:

DistributedTests: UnExpected error occured during test execution. Try again.
DistributedTests: Error : One or more errors occurred.--->Value cannot be null.
Parameter name: uriString

*TFS 2015 update 3 On Premises*
[worker_logs.txt](https://github.com/Microsoft/vsts-tasks/files/831705/worker_logs.txt)
[DTAExecutionHost.txt](https://github.com/Microsoft/vsts-tasks/files/831704/DTAExecutionHost.txt)
[agent_20170308-230218-utc.txt](https://github.com/Microsoft/vsts-tasks/files/831706/agent_20170308-230218-utc.txt)

**Comment by nigurr** [comment]
@ppptrevoro This is something not expected. Seems like you are using Visual Studio Test Agent 2015 Update 2. Can you please install Update 3 and try running the tests.

**Comment by acesiddhu** [comment]
Closing this issue for now. Assuming @nigurr 's suggestion worked. Please re open if this doesn't work
