### ISSUE TITLE
WindowsMachineFileCopy does not work with UNC paths with subdirectories

### ISSUE THREAD

**Issue by pentp** [Microsoft/vsts-tasks#3765]
When _Destionation Folder_ is of the form `\\srvname.domain\sharename\subdirname` and the subdirectory doesn't exist then it fails:
> System.Management.Automation.RuntimeException: Copying failed for resource :
Failed to connect to the path \\srvname.domain\sharename\subdirname with the user srvname\tfs for copying.
System error 55 has occurred.
The specified network resource or device is no longer available.

**Comment by niadak** [comment]
@pentp  Thanks for reporting the issue. For UNC path as destination in this task, the path required to be already present. Is there any specific scenario where you need the sub directory to be created by the task?

**Comment by pentp** [comment]
I was hoping to use a deployment model where I only need access to an UNC share (i.e., no WinRM). I could create the proper folder structure with a script beforehand, but that kind of defeats the purpose of this copy task - I could just as well call robocopy directly from my script.

In any case, the error message is really confusing.

**Comment by niadak** [comment]
@pentp thanks for your reply. We use net use command internally to map the destination before copy and that command fails if the destination folder does not present. In that case, the error message "**The specified network resource or device is no longer available.**" is correctly indicating the folder is not present.

I agree that this is a good scenario when the sub directory does not present we need to create it as robocopy does the same. Marking this as a bug. Thanks for reporting the issue.

**Comment by RoopeshNair** [comment]
The destination should be a valid path is a reasonable assumption. Since this is a corner scenario, I'm closing this. Will consider this if multiple users are hitting this issue

**Comment by Digitaledgestudios** [comment]
We are having this issue also and we were monitoring its progress. Its a shame it is closed.

**Comment by SamNutkins** [comment]
I'm having this issue as well.  Seems like a fairly common scenario to have a daily build dropped into a network share (new folder each time).  This works with a simple robocopy call, but i'm forced to write my own script instead of being able to use this task.

**Comment by RoopeshNair** [comment]
Appreciate if you can vote on [uservoice](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/category/145269-release-management). It will help in better prioritization and tracking. Thank you

Roopesh Nair

**Comment by pabrams** [comment]
I'm having this same issue.  As a workaround I guess I'll have to make sure the folders exist first via script, or create my own task.

**Comment by RoopeshNair** [comment]
we will had this to our backlog. However, it will be a while before we can get to it (~5-6months).

**Comment by mhalkyer** [comment]
We're still having this problem as well. Still a few months out @RoopeshNair ?

**Comment by rajatagrawal-dev** [comment]
Support for creating directories in UNC destinations has been added. It should be available for all accounts in 3-4 weeks.
