### ISSUE TITLE
Xamarin.Android linking fails with TargetFramework 7.1

### ISSUE THREAD

**Issue by richardpike** [Microsoft/vsts-tasks#3770]
Essentially this issue is a copy of #3191 but for the increased target framework.

Is there an expected date for the Hosted VM's to be updated so I can build 7.1?

**Comment by madhurig** [comment]
Hosted build VMs have been updated and they have Xamarin Android 7.1 and Android SDK 25.0.2. The documentation will be updated today. 

Thanks,
Madhuri

**Comment by richardpike** [comment]
Thanks. Just ran a successful build.
