### ISSUE TITLE
Path to Custom Test Adaptors has trouble finding xunit.runner.visualstudio.2.2.0

### ISSUE THREAD

**Issue by robpex** [Microsoft/vsts-tasks#3776]
The Visual Studio Test Task is not able to find the xunit test adapter, even when specifying part of the path.  I reproduced this on our build server and found that it won't work until you specify the full path, including "_common"  (eg. "D:\agent\_work\57\s\src\Fabrikam\packages\xunit.runner.visualstudio.2.2.0\build\_common").  If you only provide the path up until "packages" or anything before "_common", it says "Starting test execution, please wait..." but completes without running any tests.  Interestingly, it seems to be doing *something* with the xunit adapter, because if I intentionally mess up the path with an invalid value, it will return an error indicating that it couldn't be found.  I thought it wasn't finding the NuGet package by default because I have "src" at the start of my path, but it still won't find it in the subdirectory when I specify the test adapter path.

**Comment by robpex** [comment]
After looking at the code, this probably belongs in Microsoft/vstest.  I will move it yet again once I confirm.

**Comment by nigurr** [comment]
This is addressed here. Should be fixed with next deployment [week or 2 week max]
https://github.com/Microsoft/vsts-tasks/pull/3677

**Comment by robpex** [comment]
@nigurr i don't know if this is the same issue.  I turned on diagnostics and ran vstest and it had a lot of errors using reflection when it found the .net core versions of the xunit adapter (I'm not using any .net core stuff yet).  Those errors are silently ignored, so, to the VSTS user, it just looks like no tests were found.  I didn't have enough time to take it further than that, unfortunately.  Looking at the fix you linked to, I think this is probably different because it's finding the adapters, it's just dying on the reflection stuff.  Still, probably a vstest.console issue, not vsts-tasks.  I will try to reproduce it, but it's going to have to be on my nights/weekends so someone might beat me to it.

**Comment by nigurr** [comment]
@robpex can you try running 'vstest.console.exe' in local box and see if it works out. if it doesn't it should be reported here https://github.com/Microsoft/vstest
If it's working with vstest.console.exe and but if there's a problem with vsts pipeline, let us know the issue. 

Thanks
