### ISSUE TITLE
Azure CLI 2.0 Support

### ISSUE THREAD

**Issue by artberri** [Microsoft/vsts-tasks#3779]
Hi,

Are you planning to add support to the Azure CLI 2.0?

I mean, right now, Azure related tasks are implemented based on the Node.js Azure CLI, for example:
https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/AzureResourceGroupDeployment

Will these tasks work in the future with the Azure CLI 2.0?
https://docs.microsoft.com/en-us/cli/azure/install-azure-cli

Thanks in advance

**Comment by ds-ms** [comment]
@artberri I'm not sure I understood your comment. 

We support azure-cli 2.0 in "Azure CLI" task which you'll be seeing in a couple of weeks. 
As per the AzureResourceGroupDeployment task, it doesn't use Azure-CLI modules at all, we use REST API of azure to communicate.

**Comment by artberri** [comment]
@ds-ms 

It's nice to see that now the tasks are being implemented with clossplatform tools :+1: , it was not like this in the past and I needed to deploy resource groups with custom scripts. (they required powershell making them impossible to run on Linux)
https://github.com/Microsoft/vsts-tasks/commit/0ece4dcbfd167ee023b661c74ba0af9a9d546783

Thank you for that!.

But there are still other Azure related tasks that are only implemented with powershell, like:
https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/AzureFileCopy

And I was wondering if you are thinking on moving them to the xplat tool.
