### ISSUE TITLE
Help text for avgResponseTimeThreshold of QuickPerfTest is wrong

### ISSUE THREAD

**Issue by DarqueWarrior** [Microsoft/vsts-tasks#3781]
The help text for QuickPerfTest avgResponseTimeThreshold  reads 
"Load test run duration in seconds."
which is a copy and paste error from runDuration and needs to updated.

**Comment by acesiddhu** [comment]
Thanks @DarqueWarrior . Here is the PR with the fix https://github.com/Microsoft/vsts-tasks/pull/3817/files
