### ISSUE TITLE
System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'testSelector'.

### ISSUE THREAD

**Issue by colinmcbride** [Microsoft/vsts-tasks#3782]
I am using pretty much all of the defaults when trying to run unit tests as part of the automated build proces. It keeps failing with the error: System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'testSelector'. LegacyVSTSPowerShellHost.exe completed with return code: -1.

Full Error:
==============================================================================
Task         : Visual Studio Test
Description  : Run tests with Visual Studio test runner
Version      : 1.0.84
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=624539)
==============================================================================
Preparing task execution handler.
Executing the powershell script: D:\a\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\1.0.84\VSTest.ps1
!**\obj\**)
System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'testSelector'.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
LegacyVSTSPowerShellHost.exe completed with return code: -1.

**Comment by acesiddhu** [comment]
@colinmcbride I tried to repro this but I am not able to repro this. Can you put system.debug = true in build definition variables, queue the build again and share the build logs.

**Comment by mickyd** [comment]
+1 getting this too

**Comment by vferras** [comment]
Hello,

I'm still facing the same issue, here the outputs:

PowerShellHandler.Execute - AddCommand(D:\a\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\1.0.84\VSTest.ps1)
PowerShellHandler.Execute - Add inputParameters
PowerShellHandler.Execute - AddParameter(testAssembly=**\bin\Integration\*UnitTest*.dll)
PowerShellHandler.Execute - AddParameter(testFiltercriteria=)
PowerShellHandler.Execute - AddParameter(runSettingsFile=D:\a\1\s)
PowerShellHandler.Execute - AddParameter(overrideTestrunParameters=system.debug = true)
PowerShellHandler.Execute - AddParameter(codeCoverageEnabled=true)
PowerShellHandler.Execute - AddParameter(runInParallel=true)
PowerShellHandler.Execute - AddParameter(vstestLocationMethod=version)
PowerShellHandler.Execute - AddParameter(vsTestVersion=14.0)
PowerShellHandler.Execute - AddParameter(vstestLocation=)
PowerShellHandler.Execute - AddParameter(pathtoCustomTestAdapters=)
PowerShellHandler.Execute - AddParameter(otherConsoleOptions=)
PowerShellHandler.Execute - AddParameter(testRunTitle=)
PowerShellHandler.Execute - AddParameter(platform=)
PowerShellHandler.Execute - AddParameter(configuration=)
PowerShellHandler.Execute - AddParameter(publishRunAttachments=false)
PowerShellHandler.Execute - AddParameter(testSelector=testAssemblies)
PowerShellHandler.Execute - AddParameter(testAssemblyVer2=AXA.Drive.Backend.API.UnitTest\bin\Integration\AXA.Drive.Backend.API.UnitTest.dll)
PowerShellHandler.Execute - AddParameter(testPlan=)
PowerShellHandler.Execute - AddParameter(testSuite=)
PowerShellHandler.Execute - AddParameter(testConfiguration=)
PowerShellHandler.Execute - AddParameter(tcmTestRun=$(test.RunId))
PowerShellHandler.Execute - AddParameter(searchFolder=)
PowerShellHandler.Execute - AddParameter(runOnlyImpactedTests=False)
PowerShellHandler.Execute - AddParameter(runAllTestsAfterXBuilds=50)
PowerShellHandler.Execute - AddParameter(uiTests=false)
PowerShellHandler.Execute - AddParameter(runTestsInIsolation=False)
PowerShellHandler.Execute - Invoke
System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'testSelector'.
Processed: ##vso[task.logissue type=error;]System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'testSelector'.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
LegacyVSTSPowerShellHost.exe completed with return code: -1.
******************************************************************************
Finishing: Unit Tests
******************************************************************************

Best,

Víctor

**Comment by acesiddhu** [comment]
Few more question
1) which version of the task are you using? From logs I see version 1 but the parameters it is using is of version 2.
2) is this happening in build or release pipeline?
3) can you share the json from history tab in build definition with me. you can just share contents of "id": "ef087383-ee5e-42c7-9a53-ab56c98420f9", task in the json. it will look something like . you can mail me on "devops_tools AT Microsoft DOT com>"
{
      "enabled": true,
      "continueOnError": false,
      "alwaysRun": false,
      "displayName": "Test Assemblies **\\$(BuildConfiguration)\\*test*.dll;-:**\\obj\\**",
      "timeoutInMinutes": 0,
      "task": {
        "id": "ef087383-ee5e-42c7-9a53-ab56c98420f9",
        "versionSpec": "2.*",
        "definitionType": "task"
      },
      "inputs": {
        "testSelector": "testAssemblies",
        "testAssemblyVer2": "**\\*project*.dll\n!**\\obj\\**",
        "testPlan": "",
        "testSuite": "",
        "testConfiguration": "",
        "tcmTestRun": "$(test.RunId)",
        "searchFolder": "$(System.DefaultWorkingDirectory)",
        "testFiltercriteria": "",
        "runOnlyImpactedTests": "false",
        "runAllTestsAfterXBuilds": "50",
        "uiTests": "false",
        "vstestLocationMethod": "version",
        "vsTestVersion": "14.0",
        "vstestLocation": "",
        "runSettingsFile": "",
        "overrideTestrunParameters": "",
        "runInParallel": "false",
        "runTestsInIsolation": "false",
        "pathtoCustomTestAdapters": "",
        "codeCoverageEnabled": "false",
        "testRunTitle": "",
        "platform": "$(BuildPlatform)",
        "configuration": "$(BuildConfiguration)",
        "publishRunAttachments": "true"
      }
    }

**Comment by acesiddhu** [comment]
also if you can mail me the account name (<**accountname**>.visualstudio.com) at devops_tools AT Microsoft DOT com, it will be great

**Comment by VaughanJ** [comment]
This was resolved for me by using the version 2 task. I was originally running version 1 and getting this error and simply upgraded to version 2 and the issue went away.

**Comment by acesiddhu** [comment]
@VaughanJ  you should be able to use version 1 as well. I am trying to see why did we hit this error in first place

**Comment by vferras** [comment]
Indeed I'm using version 1, and using the Build pipeline.
About the json you asked, I don't know how to get it :/
And also I've sent you by email my account name.

**Comment by vferras** [comment]
By the way, the email is being rejected

**Comment by acesiddhu** [comment]
@vferras I got the mail. Let me check.

**Comment by acesiddhu** [comment]
Ok I got a repro. Can you confirm if you are using latest build definition editor? if yes can you use the old editor and save the build definition and try again?

**Comment by vferras** [comment]
I can confirm I was using the new editor, and with the old one is working fine. Thanks!!

**Comment by acesiddhu** [comment]
we are tracking the bug in new editor internally. I am closing the issue now. Let me know if the workaround doesn't work

**Comment by mickyd** [comment]
How do I revert to the **old editor**?  I can no longer see the hat switch in VSTS.

Also, after changing the Test step to **v2**, I now get:

> Method Horatio.Tests.HipChatTests.ClassInit has wrong signature.  Parameter 1 should be of type Microsoft.VisualStudio.TestTools.UnitTesting.TestContext

Thanks

**Comment by acesiddhu** [comment]
@mickyd check https://www.visualstudio.com/en-us/articles/news/2017/jan-05-team-services#try-out-new-features-we-are-working-on . you can turn off "New Build Editor" from here.
@AbhitejJohn any idea here for the ClassInit error?

**Comment by AbhitejJohn** [comment]
@mickyd : VS 2017 is defaulting to the new cross-plat nuget based MSTest Framework for a new test project. The above exception in ClassInit should throw when you refer **Microsoft.VisualStudio.QualityTools.UnitTestFramework** as well. Can you paste the signature of your class initialize method please?

**Comment by mickyd** [comment]
@AbhitejJohn sure.  ClassInit is simply the code from the wizard that I uncommented:

```
[ClassInitialize]
public static void ClassInit(TestContext context) { ... }
```

I should point out that this code was **working** on my **local** machine, even with the default VS NuGet reference.  It was not until I tried to run it on **VSTS** that it failed.
		
> 2017-03-16T03:42:34.8598319Z Microsoft (R) Test Execution Command Line Tool Version 14.0.25420.1
> 2017-03-16T03:42:34.8598319Z Copyright (c) Microsoft Corporation.  All rights reserved.

However, replacing the NuGet with an reference to the non-NuGet **Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll** version 10.1.0.0 (which looking at the Properties window shows **C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ReferenceAssemblies\v2.0\Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll**).

**Comment by AbhitejJohn** [comment]
Thanks @mickyd. Does your solution have projects with older/different versions of the MSTest nuget? Is it possible to point us to a link of your build where this failed? The logs for the vstest task should help us understand this better. @acesiddhu Any other thoughts?

On a side note, please refer to 10.0.0.0 of the old QualityTools.UnitTestFramework instead of 10.1.0.0 if you choose to move there. 10.1 was only shipped for compat reasons.

-Abhitej.

**Comment by mickyd** [comment]
Hi @AbhitejJohn ,

No. 

Sure,  not sure if you can get in though:  https://medicaldirector.visualstudio.com/TED/_build/index?buildId=9505&_a=summary

Will do!

**Comment by AbhitejJohn** [comment]
Nah. 401. Can you attach the diagnostic logs for the vstest task please?

**Comment by acesiddhu** [comment]
@mickyd can you download the build logs and share that. Link to the build don't work as we don't have access

**Comment by acesiddhu** [comment]
Also make sure you set system.debug = true in definition before running the build

**Comment by mickyd** [comment]
@AbhitejJohn sure, here you go 

[5_Test Assemblies debughoratio.tests.dll;-obj.txt](https://github.com/Microsoft/vsts-tasks/files/852145/5_Test.Assemblies.debughoratio.tests.dll.-obj.txt)

**Comment by AbhitejJohn** [comment]
Ah I see the problem. You have a testsettings file. Do we need that? The new MSTest Framework no longer supports the legacy test settings. Can you please consider moving over to a [runsettings](https://msdn.microsoft.com/en-us/library/jj635153.aspx)?

**Comment by mickyd** [comment]
Got ya.   All fixed now.  Thanks for your help everyone

**Comment by acesiddhu** [comment]
Great!
