### ISSUE TITLE
csproj based asp.net core website vsts issue

### ISSUE THREAD

**Issue by asadsahi** [Microsoft/vsts-tasks#3790]
The error I getting when trying to publish asp.net core website which is csproj based is:

![image](https://cloud.githubusercontent.com/assets/3470892/23943870/caddbb5a-0968-11e7-9eb2-a06ba47c5e0f.png)

This is my task definition:
![image](https://cloud.githubusercontent.com/assets/3470892/23946314/d9db27d8-0971-11e7-9a77-26bc46716341.png)

There is new csproj file at the root, there is no project.json, but the error I am having is a bit confusing.

**Comment by ds-ms** [comment]
@asadsahi are you using a Hosted Agent or your own?

**Comment by asadsahi** [comment]
I believe its hosted:

![image](https://cloud.githubusercontent.com/assets/3470892/23993068/0efb7aa6-0a37-11e7-9a42-fdd6170e64cb.png)

**Comment by ds-ms** [comment]
The version of dotnet on the hosted agents is "1.0.0-preview2-1-003177" which doesn't support any dotnetcore commands with _.csproj_ files. 
The reason you're getting that confusing error message is, the task supports searching and using .csproj files, so if you see the command which was executed, it gave the .csproj file as a parameter; when dotnet command expected a project.json file.

You could migrate your current project to '1.0.0-preview2-1-003177' to use hosted agents. (For reference: [How to migrate](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-migrate)) Or, you could configure an agent yourself with the latest version of dotnet to run it using .csproj files. (For reference: [How to install a VSTS agent](https://www.visualstudio.com/en-us/docs/build/actions/agents/v2-windows))

We will be shipping a new hosted pool, with VS 2017 RC installed on it, soon which will be updated with the latest version of dotnet to help you use your .csproj files
