### ISSUE TITLE
cURLUploader add -T, unpossuble to use -F

### ISSUE THREAD

**Issue by ghostinside** [Microsoft/vsts-tasks#3792]
I think we should have an option to decide how to uplod file, -T or if i need multipart form use -F instead

**Comment by madhurig** [comment]
@ghostinside : The cURLUploader task is a convenience task for uploading files, hence -T is passed. If you want to use cURL with -F option, you can write a script and run it using the [Shell script task](https://www.visualstudio.com/en-us/docs/build/steps/utility/shell-script) or the [Batch script task](https://www.visualstudio.com/en-us/docs/build/steps/utility/batch-script) .

Thanks,
Madhuri
