### ISSUE TITLE
VS2017 on Private Agent, new CSProj fails to reference Nuget assemblies

### ISSUE THREAD

**Issue by dibble-james** [Microsoft/vsts-tasks#3798]
We have  VS2017 installed on a private agent.  When we build a "mixed" solution of old and new CSProj files using the Visual Studio Build task it fails to build with assembly reference errors, eg: 
`
The type or namespace name 'AutoMapper' could not be found (are you missing a using directive or an assembly reference?)
`

Opening and build the solution manually with Visual Studio on the agent itself works fine.  

We have a Nuget restore task before the build task and all the Nuget packages are being restored into the `packages` directory.  We have `Visual Studio 2017` selected as the "Visual Studio Version" on the build task.

**Comment by ericsciple** [comment]
The VSBuild task is a thin wrapper over msbuild.exe (cmdline printed in cyan in the log). The NuGet restore task should also print the cmdline it runs. To troubleshoot, I would recommend trying to repro locally on your box by running running the same/similar command lines.

If the correct version of msbuild is being called and the correct vsversion property passed on the command line, then the VS Build task is doing what it's supposed to do.

**Comment by dibble-james** [comment]
Running the MSBuild command locally raw on a fresh checkout yields the same errors.  Now to find what magic Visual Studio is doing...

I'll close the issue.  Sorry for jumping to conclusions!

**Comment by dibble-james** [comment]
For anyone who comes across this, I found that adding `/t:restore` in the "MSBuild Arguments" solved the issue.  Visual Studio does this for you when building inside the IDE.

**Comment by ericsciple** [comment]
@zjrunner fyi - it sounds like the nuget restore task is not restoring everything?

**Comment by dibble-james** [comment]
@ericsciple @zjrunner  In my case, I had a Unit Test project using old style CSProj that coincidentally used the same Nuget references as my new format CSProj it was testing.  Therefore, all the references I required were available in `\packages` but MSBuild didn't seem to want to use them.  Does Nuget 4.X do something different than Nuget 3.5.0...?  That was my suspicion but I couldn't find a 4.X Nuget.CommandLine executable from a cursory Google to test that theory.  `/t:restore` appears to run 4.X and it fixed my issue so I didn't dig much deeper.  Let me know if I can provide any more details that might be of use to you.

**Comment by zjrunner** [comment]
Yep, was half way through that response.  4.0 is the only nuget.exe that can find msbuild 15 and correctly parse the projects to understand PackageReference.  In the nuget restore task you should be able to use the ()Custom option and put the path to where nuget 4 sits on a machine with 2017 on it, or you could write a task up front that pulls it onto the agent in a known location and uses that path.  The team that owns the task is looking to make 4.0 easier to consume soon, up front of larger work on the tasks.
