### ISSUE TITLE
Cannot specify /UseVsixExtensions:true in Visual Studio Test task version 2.0.17

### ISSUE THREAD

**Issue by marcwmiller** [Microsoft/vsts-tasks#3799]
I was able to specify other console options /UseVsixExtensions:true in version 2.0.13 in order for my .NET core/xUnit tests to be discovered and run. The other console options have been removed from UI. What is recommendation to provide this option through the latest Visual Studio Test task UI?

Here is command line for a VSTS build using version 2.0.13 of VSTest task on 2/25/2017 that was able to discover and run unit tests successfully:

`[command]"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" D:\a\1\s\test\BuildTest.Web.App.Tests\project.json /EnableCodeCoverage /UseVsixExtensions:true /logger:trx`

(Note the /UseVsixExtensions:true setting). 

This is the test project.json file:
```
{
  "version": "1.0.0-*",

  "testRunner": "xunit",

  "dependencies": {
    "dotnet-test-xunit": "2.2.0-*",
    "BuildTest.Web.App": "1.0.0-*",
    "Microsoft.CodeCoverage": "1.0.2",
    "xunit": "2.2.0-*",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.1.0"
    },
    "Moq": "4.7.0",
    "Microsoft.DotNet.InternalAbstractions": "1.0.500-preview2-1-003177"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}
```
Here is the command line on 3/16/2017 with version 2.0.17 with NO changes to the project files or build tasks:

`[command]"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" C:\a\1\s\test\BuildTest.Web.App.Tests\project.json /EnableCodeCoverage /logger:trx`

As you can see the /UseVisixExtensions:true is no longer on the command line, resulting in:

```
Information: Additionally, you can try specifying '/UseVsixExtensions' command if the test discoverer & executor is installed on the machine as vsix extensions and your installation supports vsix extensions. Example: vstest.console.exe myTests.dll /UseVsixExtensions:true

##[warning]No results found to publish.
```

**Comment by bpsmicro** [comment]
I found a problem which may be related. In my Other Console Options, I have:

`**/UseVsixExtensions:true /Platform:x64**`

That throws an error during the test process to the effect "/Platform:x64 is an unexpected parameter for 
UseVisxExtensions option". When you look at the command line, it has quoted the entire Other Console Options string, so the command line looks similar to:

`**...\vstest.console.exe <path to file(s)> "/UseVsixExtensions:true /Platform:x64" /logger:trx.**`

(I've omitted some parts for brevity). The quotes are causing the parser to not see two separate options, but one option that's mal-formed. I'm wondering if this is related to marcwmiller's reported issue, or separate.

**Comment by marcwmiller** [comment]
Unfortunately in the 2.0.17 version of VSTest task, the Other Console Options text box in the UI has been removed, and therefore no way to provide any command line options, causing my unit tests to no longer be discovered and run.

**Comment by Benalink** [comment]
Is it possible to test csproj dotnet core tests with the VSTest task without this option? I'm still not sure if this task is supposed to work with core or if we are supposed to use dotnet test.

**Comment by marcwmiller** [comment]
No, without the /UseVsixExtenstions:true, the xUnit tests go undiscovered and therefore cannot be run. This task did work with core when the option is provided to the command line.

I believe this task is supposed to work with core as this was the guidance indicated by Pratap Lakshman in his post [https://blogs.msdn.microsoft.com/visualstudioalm/2016/09/01/announcing-mstest-v2-framework-support-for-net-core-1-0-rtm/](url) when testing using VSTS (see section with same title about half way down post).

**Comment by bpsmicro** [comment]
Should I create a new issue covering the problem I mentioned above ("Other Console Options" won't work with more than one option)? I guess it's separate from, but related to this one.

**Comment by marcwmiller** [comment]
Issue still observed in VSTest task 2.0.19 - additionally documentation indicates existence of "Other console options" [https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/VsTest/README.md](url), which is no longer the case.

**Comment by bpsmicro** [comment]
So if I'm reading correctly, earlier versions of the v2 VSTest task were broken because of errant quotes around the "Other Console Options"; and later versions are **more** broken because we can't specify the options **at all**. That's bad, very bad. I was kinda hoping to start playing with the new "impacted tests" stuff, but I guess not anytime soon. :-(

**Comment by marcwmiller** [comment]
You are reading it correctly.

**Comment by acesiddhu** [comment]
I will take a look at this one. If possible if there is a repro test proje t available i can quickly work on getting this working or providing workaround. Else i will try to repro

**Comment by marcwmiller** [comment]
Thank you. I have a repo test project, but its not in a github repo. Should I zip and attach file?

**Comment by acesiddhu** [comment]
yes that will help

**Comment by marcwmiller** [comment]
Please find attached a zipped Visual Studio 2015 solution using the ASP.NET Core Web Application template and an xUnit test project.
[BuildTest.zip](https://github.com/Microsoft/vsts-tasks/files/861606/BuildTest.zip)

**Comment by acesiddhu** [comment]
@marcwmiller are you using vs2015? Also are you using your own pool or hosted pool? also r u using runsettings?

**Comment by marcwmiller** [comment]
I am using vs2015, hosted pool and a runsettings file.

**Comment by acesiddhu** [comment]
@bpsmicro are your tests .net core tests? or normal xunit tests? if it is normal you can create another issue on GitHub. also r u using version 1 of the task?

**Comment by bpsmicro** [comment]
Ours are nunit tests. Right now I've reverted to version 1 of the task because we need both /UseVsixExtensions:true and /Platform:x64 options, and v1 works.
For my specific issue with the v2 task, I guess I want to see Other Console Options put back **and** no longer quoted in the actual command line. I can log that separately if you wish.

**Comment by acesiddhu** [comment]
@bpsmicro lets have another issue opened for your scenario. will check that out once I am done with this issue

**Comment by bpsmicro** [comment]
Done: [https://github.com/Microsoft/vsts-tasks/issues/3836](https://github.com/Microsoft/vsts-tasks/issues/3836)

**Comment by acesiddhu** [comment]
@marcwmiller can you put this in ur runsettings and see if it works

```
<RunConfiguration>    
    <!-- Path to Test Adapters -->  
    <TestAdaptersPaths>c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet\ProjectSystem</TestAdaptersPaths>  
  </RunConfiguration> 
```

**Comment by marcwmiller** [comment]
Unfortunately, it did not work. Please see attached VSTS build log.
[logs_581.zip](https://github.com/Microsoft/vsts-tasks/files/861916/logs_581.zip)

**Comment by acesiddhu** [comment]
@marcwmiller sorry for the trouble. Here are two short term workarounds till we get this fixed
1) add two cmd line task in ur build definition.
copy "c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet\ProjectSystem\*.*" $(Build.Repository.LocalPath)

![image](https://cloud.githubusercontent.com/assets/1168823/24240805/e62db6b4-0fd8-11e7-9c30-b636cf23888f.png)

and 
copy Microsoft.VisualStudio.Projectsystem.DotNet.UnitTestAdapter.dll Microsoft.VisualStudio.Projectsystem.DotNet.TestAdapter.dll
in working folder $(Build.Repository.LocalPath)

![image](https://cloud.githubusercontent.com/assets/1168823/24240792/daaf8e2a-0fd8-11e7-9996-5feca0acd6a8.png)

and add this in your vstest task in custom adapter path $(Build.Repository.LocalPath)
![image](https://cloud.githubusercontent.com/assets/1168823/24240865/13e14c74-0fd9-11e7-81df-acfa8f7910ef.png)


2) use command line vstest.console.exe to run test via usevsixextensions:true and then use publish test results task to publish results.

**Comment by marcwmiller** [comment]
@acesiddhu thank you very much for the workaround - it worked well. I look forward to the final resolution. 

FWIW - anyone else reading these comments who has encountered the same issue before the VSTest task is fixed, **item 1** in the workaround **instructions** above is missing a backslash in the first copy argument `ProjectSystem*.*`, which results in a copy error. However, the image of the first command line task has the backslash in the path, but it might be missed - like I did.

**Comment by cltshivash** [comment]
Final resolution is being tracked by the issue #3836
