### ISSUE TITLE
Functional test step fails with no failure

### ISSUE THREAD

**Issue by mutee88** [Microsoft/vsts-tasks#3803]
Hello, 

I have a functional test step which fails since the Coded UI tests don't pass. But the tests don't fail either so am wondering if the tests run in the first place. See attached screenshots. 
![nonfailednonpassed](https://cloud.githubusercontent.com/assets/6734562/24041010/b621f0ea-0b1c-11e7-95b6-1543e15bcfe3.PNG)
![results_others](https://cloud.githubusercontent.com/assets/6734562/24041069/ed45c286-0b1c-11e7-963d-c950f4156b7b.PNG)

**Comment by cltshivash** [comment]
@mutee88 Did you look into the trx for the test run to see the outcome of the test cases ?

**Comment by mutee88** [comment]
Yes I did. Somehow this issue has been solved. 

The problem was  that I was running functional tests using vs2013 and the test agents where 2015.3

**Comment by tanvi-soni** [comment]
@mutee88 Thanks for confirming that you are unblocked.
