### ISSUE TITLE
 The container XXX could not be found. (hope someone can help)

### ISSUE THREAD

**Issue by allanmoller** [Microsoft/vsts-tasks#3804]
Hey all, 

hope someone can help before i go crazy :-) until yesterday i was able to add artifacts from other VSTS projects, this suddenly stopped. Initially i thought it was an issue with my GIT repo so tried rebuilding with no success, now i have tried setting up a test project with below settings.

VSTS test project1 -> GIT repo with a folder containing a single ps1 file (scripts\helloworld.ps1) ->
i have created a build definition (helloworld) with build step (Copy Publish artifact):

copy root: blank
contents: scripts\**
artifact name: helloworld
artifact type: server

i have within "same project" created a release definition and linked above artifact i have added following task:

powershell script:

Type: file path
Script path: $(System.DefaultWorkingDirectory)/helloworld/helloworld/helloworld.ps1

from another project i have created another release definition with following settings:

Artifacts: helloworld
type: build
project: test project1
source (build definition): helloworld
source alias: helloworld

task:

powershell script:

Type: file path
Script path: $(System.DefaultWorkingDirectory)/helloworld/helloworld/helloworld.ps1

But when i run this i get the following errors:

Downloading artifacts failed: Microsoft.VisualStudio.Services.FileContainer.ContainerNotFoundException: The container 1081070 could not be found. 

The container 1081070 could not be found. 

iam am now totally lost can some help and maybe give and answer to why this was working perfectly yesterday?

**Comment by GitHubSriramB** [comment]
@allanmoller - Could you pl. clarify if the release was able to download the artifacts from "test project1" build definition before and it started to fail later on?

Also, could you share your account name?

**Comment by GitHubSriramB** [comment]
@allanmoller - Could you also confirm that the build used for the release is not deleted?

**Comment by allanmoller** [comment]
before it started not to work i was able to consume artifacts from anther project (Azure PS scripts) but now it dosnt, only difference is that i tried adding some files (using VSTS) to GIT rep (test project 1) after which i cannot consume artifacts from this project!

**Comment by GitHubSriramB** [comment]
Thanks for the update. We will investigate and get back to you with our findings.

**Comment by Serjster** [comment]
Yes, we are experiencing the exact same problem. This seems to be a fairly recent break, it was working about 2 weeks ago.

**Comment by GitHubSriramB** [comment]
We have fixed the issue & it will be available as part of 2.115.0 version of agent:
https://github.com/Microsoft/vsts-agent/releases/tag/v2.115.0

Apologies for the inconvenience.
