### ISSUE TITLE
Where to see the recorded video of CodedUI Tests using vNext Build?

### ISSUE THREAD

**Issue by Selvaraj1989** [Microsoft/vsts-tasks#3806]
Hi all,

I have created .testsettings file with Video Recorder and System Info and pointed it to "Run Settings File" in Run Functional test task. I am able to see the "SystemInformation.xml" attached to the test result of the test case. But i am not able to find the video recording either in the test result as well in the test case.

Please help me to find where the video is located.

**Comment by acesiddhu** [comment]
@Selvaraj1989 can u attach the test settings? you should see the video in for each test case (test results). do u see this for failed test results?

**Comment by Selvaraj1989** [comment]
Hi @acesiddhu , please find attached the test settings file and i am able to see only the SystemInformation.xml file only attached with the failed test case.

**Test Result Attachment Screenshot:**
![attachment1](https://cloud.githubusercontent.com/assets/22670803/24093391/8e73f548-0d79-11e7-9f88-41e471fe7583.JPG)


[TestSettings.txt](https://github.com/Microsoft/vsts-tasks/files/854281/TestSettings.txt)

Thanks
Selvaraj C

**Comment by acesiddhu** [comment]
@Selvaraj1989 I see <MediaRecorder sendRecordedMediaForPassedTestCase="false" xmlns="" />
in the settings. Did this test failed? this will create video for failed test case only

**Comment by acesiddhu** [comment]
Saw your comment about the failing test. Let me try this out. Are you using vsts or tfs on prem? if it is TFS which version?

**Comment by Selvaraj1989** [comment]
@acesiddhu Yes, the test case got failed and i am not able to see the video recording.

I am using TFS 2015 Update 3 and i am running the automated tests using vNext build.

Thanks
Selvaraj C

**Comment by acesiddhu** [comment]
@Selvaraj1989 what is the OS you are using. if this is a server SKU did u enable Desktop experience

**Comment by acesiddhu** [comment]
Check this blog for pre reqs
https://blogs.msdn.microsoft.com/rubel/2009/11/25/recording-video-of-desktop-while-testing-through-test-runner/

Desktop experience is needed for all server SKUs. Also the test agent should be configured as process in such cases

**Comment by acesiddhu** [comment]
I am closing this issue. Let me know if the above links doesn't help. I tried locally and things were working for me.
