### ISSUE TITLE
SonarQube analysis report not showing on build summary when using Gradle Build Task

### ISSUE THREAD

**Issue by GersonDias** [Microsoft/vsts-tasks#3807]
Hello,

I have a lot of builds using Gradle with Sonar Analysis and after upgrading to TFS 2017.1, the sonar's section that used to be in Build Summary won't appear anymore.

Another Code Analysis tools are working well (eg. checkstyle), but Sonar not... how can I troubleshoot that?

**Comment by yacaovsnc** [comment]
We can start troubleshooting by enable debug logs.  Set "system.debug" to "true" from the Variables tab in your build definition.  The log should give us more context.  

Thanks!

**Comment by GersonDias** [comment]
I attached the log here. Although every thing looks ok for me, there are no sonar section in build summary... 
[log_gradle.txt](https://github.com/Microsoft/vsts-tasks/files/855781/log_gradle.txt)

ps: The sonar is on version 5.6.2

**Comment by yacaovsnc** [comment]
Thanks for the log.  I think there is a bug in the code.  I will create a pull request with a fix soon.

**Comment by yacaovsnc** [comment]
#3823 merged.  Since you are on TFS, we need to manually apply the patch with [tfx cli](https://github.com/Microsoft/tfs-cli/blob/master/docs/buildtasks.md) tool.

**Comment by GersonDias** [comment]
It's worked! Thanks!

Since the version with bug is bundled in TFS 2017.1, I suppose that I'll have to manually update this task in every install, is it correct? I'm asking that because i'm act as ALM Consultant and I manage many TFS installations...

**Comment by yacaovsnc** [comment]
Unfortunately you need to update all affected servers.  :(  Sorry for the inconvenience.
