### ISSUE TITLE
Run Functional Tests does not supply Suite and/or TestCase info the test engine.

### ISSUE THREAD

**Issue by varnk** [Microsoft/vsts-tasks#3808]
When I use a Test Plan / Suites / Test Case in Run Functional Tests step, the test step runs the associated automation for each Test Case, but there are no parameters set for the TestMethod to read such as is done when the same tests are run using MTM.   Seems like the Run Distributed Tests task should pass the Plan / Suite / and Test Case information to the Test Method.  In particular, I need custom parameters defined for the Test Case, which are also currently not set for the TestMethod when it is executed.

**Comment by cltshivash** [comment]
You can help us prioritize this higher by posting this feature suggestion to UserVoice: https://visualstudio.uservoice.com/forums/330519-team-services/category/145281-test so that we can prioritize suggestions based on user votes
