### ISSUE TITLE
Multi select picklist does not work with custom input

### ISSUE THREAD

**Issue by divyau12** [Microsoft/vsts-tasks#3809]
When Trying to enter a custom input in a multiselect pick list, it doesn't work if the custom input is not one the options of the picklist. This is not an issue when multiselect is turned off i.e I am able to put in a custom input and works just fine. Please guide how to get the scenario working

**Comment by bryanmacfarlane** [comment]
Not an issue with one of the tasks here.  Can you open an issue with vsts-task-lib repo?
