### ISSUE TITLE
Incremental build for files changed only (Wordpress)

### ISSUE THREAD

**Issue by mabbashm110** [Microsoft/vsts-tasks#3810]
Hi

I have a build and release pipeline for Wordpress php files, but I only want to create a build for the files changed in source control. I am not using a Visual Studio Build task as this does not apply in case of php files I guess.

Here is how the pipeline is configured:
Currently under the **build** I am using publish artifacts only from $(Build.SourcesDirectory) and under the **release** pipeline I am copying those artifacts to the website using FTP upload.

Since the amount of files is larger than 10K, I want it to only build files that have changed and publish those instead of the whole directory again. How do I achieve that within the build as the release will automatically pick files up based on the artifacts.

**Comment by bryanmacfarlane** [comment]
VSTS is the CI system.  We run command line tools like msbuild, gradle, xcodebuild etc... which are build tools.  We don't create build tools.

So the key question is, as a php developer, how would you build/create a package with only the files that changed from your development desktop?  

Once that is identified, a task can be created to run it.  

Consider tools like robocopy, rcopy etc... which already have options to mirror files and update only what has changed.  That would allow you to create a custom task or script  that would do this.

The issues here are for tracking issues with existing tasks (look in Tasks folder), not for potentially new custom tasks.
