### ISSUE TITLE
Error 404 Not Found

### ISSUE THREAD

**Issue by bipindas** [Microsoft/vsts-tasks#3816]
I keep getting a 404 not found error in the SQL DACPAC deployment task. This was working well before. Suddenly stopped working 2-3 weeks back.

**Comment by niadak** [comment]
@bipindas  Thanks for reporting the issue. This is a known issue and has been fixed permanently. The fix will be available (deployed) to all in 3 weeks. We can apply a work around to unblock you for now.

Can you please share your VSTS account name so that we can unblock you?

**Comment by millimike** [comment]
We've got the same problem. Could you, please, apply the workaround for us as well? pcisae.visualstudio.com

**Comment by niadak** [comment]
@millimike , We have applied the work around for pcisae.visualstudio.com. Please validate the fix.

**Comment by millimike** [comment]
11 deployments - all green! Thank you!

**Comment by niadak** [comment]
@bipindas Are you still block on this? If so, please share your VSTS account name with us so that we can unblock you. You can email to RM_Customer_Queries@microsoft.com for the same.

**Comment by bipindas** [comment]
Hello, 

Sorry for the delayed response. We don't have any immediate SQL deployments scheduled. I have anyway sent the email to the address mentioned. 

Thanks!

**Comment by Ajay-MS** [comment]
@bipindas 
We have fixed issue from our end. Can you confirm if you issue is being fixed for you.

**Comment by Ajay-MS** [comment]
@bipindas 
I am assuming above issue for you has been fixed as I am able to verify that from my end. If you still face this issue please feel free to reopen this issue.

**Comment by bipindas** [comment]
@Ajay-MS thats fine thanks. Like I mentioned earlier, I don't have any immediate SQL deployments scheduled. I had already made the changes manually when it failed the first time. I can report back if it happens again.
