### ISSUE TITLE
Accessing the current build logs

### ISSUE THREAD

**Issue by yohanb** [Microsoft/vsts-tasks#3822]
Hi,
I've been meaning to write a custom build step to analyze the current build logs and fail if a condition is met (ex: if the string 'error' is found, fail the current build).  This is a feature I'm currently using in TeamCity and would really enjoy seeing it in VSTS.
Is it possible to access the build logs within a VSTS task?
Thanks,

Yohan

**Comment by bryanmacfarlane** [comment]
Yep, you have full access to the disk.   You can write a custom task (and publish to the market place to share).  Use the lib in node or powershell.  Docs are included and our tasks here are OSS as a reference.

https://github.com/Microsoft/vsts-task-lib

There's also variables to use:
https://www.visualstudio.com/en-us/docs/build/define/variables

Another option is to write an ad-hoc powershell task, use the variables above (like source directory) and run with the powershell task.  That's more appropriate for your custom use.

Guidance - not a specific task issue in this repo so closing.
