### ISSUE TITLE
Unable to see the test details on using the "Run functional Tests" task

### ISSUE THREAD

**Issue by girishgoudar** [Microsoft/vsts-tasks#3824]
We are not able to see the test result after using the "run functional test task"
![testresult](https://cloud.githubusercontent.com/assets/12731096/24134753/4f89c14c-0e2c-11e7-89a6-dce0ce481544.png)

Task configuration 
![taskconfiguration](https://cloud.githubusercontent.com/assets/12731096/24134812/9ce2fdfa-0e2c-11e7-9995-c12f2c3da23f.png)

**Comment by acesiddhu** [comment]
@girishgoudar there is a outcome filter in the summary page. it is selected as Failed and no test failed. Hence you are not able to see any test results
![image](https://cloud.githubusercontent.com/assets/1168823/24136667/dd7d7bac-0e35-11e7-8348-c9a719c600fb.png)

**Comment by girishgoudar** [comment]
Hi

I have logged a new issue for runnung functional test .issue id #3834

Can you please look into it

Thanks
Girish


Sent from my Windows Phone
________________________________
