### ISSUE TITLE
Test: Default sorting missing

### ISSUE THREAD

**Issue by sumalik** [Microsoft/vsts-tasks#3830]
The functional test task does not do a default sort of the Test Plans. This cause issues when there are a lot of test plans and not sorting order.

**Comment by cltshivash** [comment]
You can help us prioritize this higher by posting this feature suggestion to UserVoice: https://visualstudio.uservoice.com/forums/330519-team-services/category/145281-test so that we can prioritize suggestions based on user votes

**Comment by sudeeptm** [comment]
This is not a feature request, the VSTS task for executing test should by default have the drop down sorted. In the instance where the project is running it has ~1000 test plans making a selection extremely unpredictable and time consuming.
