### ISSUE TITLE
Output path error for sfproj

### ISSUE THREAD

**Issue by awcab** [Microsoft/vsts-tasks#3833]
Trying to build a service fabric project (vs2017) with core dependencies.  Builds fine locally with msbuild, but I get the error below on vsts.  I ensured that there is a valid Release/x64 and output path configuration for all of the projects.

[error]C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(737,5): Error : The OutputPath property is not set for project 'Fabric.sfproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project.

**Comment by dbreshears** [comment]
Do you have the NuGet restore build step as the first step in the task?   I can repro this if I disable the "Nuget restore **\*.sln step".    If you do have this step, can you reply with the Nuget restore log

**Comment by awcab** [comment]
Thanks so much @dbreshears!  Any idea why this is the case?  I was thinking dotnet restore should handle everything nuget does?

**Comment by bishal-pdMSFT** [comment]
@awcab did adding/enabling nugget restore fix the problem for you?

**Comment by awcab** [comment]
@bishal-pdMSFT Yes, that fixed it for me.  Just have to make sure to use nuget 3.3.  I believe 3.5 is still broken.

**Comment by alexmullans** [comment]
Sounds like this is fixed. For future reference: NuGet 4 (which, assuming you're using a Windows build agent, is functionally equivalent to dotnet) is now available as an option in the NuGet Installer task, and should fix the issues you're seeing above.

**Comment by MattHartz** [comment]
Hi @alexmullans , I experience this with 4.3 but works when running locally.  Is this an issue currently?

**Comment by alexmullans** [comment]
@MattHartz no known issues that I'm aware of. Do the configuration and platform you're using in your VSTS build line up with what you're using locally?

**Comment by MattHartz** [comment]
Hi @alexmullans.  Yeah i decided to grab the commands straight from TFS and slightly modify them for local.  This is what I'm running:

"C:\Users\user\Downloads\nuget.exe" restore "C:\MySolution.sln" -Verbosity Detailed -NonInteractive

"C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\MSBuild\15.0\Bin\amd64\msbuild.exe" "C:\MySolution.sln" /nologo /nr:false /p:AddCorrelationIds=false /p:platform="x64" /p:configuration="release" /p:VisualStudioVersion="15.0"

**Comment by alexmullans** [comment]
Hmm, ok. Can you file something on https://developercommunity.visualstudio.com/spaces/21/index.html
