### ISSUE TITLE
VSTest task: Put back Other Console Options, and don't quote the string

### ISSUE THREAD

**Issue by bpsmicro** [Microsoft/vsts-tasks#3836]
See also [https://github.com/Microsoft/vsts-tasks/issues/3799](https://github.com/Microsoft/vsts-tasks/issues/3799).

I was testing with the v2 VSTest task shipped with TFS 2017 Update 1. I haven't tried later versions (mostly because I can't figure out how to install them). Our tests are ordinary nUnit and some xUnit tests against .NET project on an in-house TFS 2017 setup, using VS2017 on the build machines.

The initial problem is that if you put something in Other Console Options, you can see in the log that the generated command line to vstest.console.exe puts quotes around what you enter. So, I'll put in:

`/UseVsixExtensions:true /Platform:x64`

and the generated command line will be similar to:

`...\vstest.console.exe <path to file(s)> "/UseVsixExtensions:true /Platform:x64" /logger:trx`

This results in an error because it treats that as one option, schmooshing UseVsixExtensions and Platform:x64 together and then getting totally confused.

Apparently, later releases of the v2 VSTest task actually removes Other Console Options entirely, which is even worse. So I see two fixes:

1) Put back Other Console Options
2) When generating the command line, don't put quotes around the Other Console Options string.

**Comment by acesiddhu** [comment]
@bpsmicro are you using nugget package for nunit and xunit? if yes ideally the task should auto detect nunit and xunit adapters to run the test.

for x64 you can put this in runsettings file. check runsettings example here
https://msdn.microsoft.com/en-us/library/jj635153.aspx

**Comment by bpsmicro** [comment]
I'm not familiar with "nugget package". But assuming that's auto-correct "helping" and you meant "NuGet package", that answer is No. But I'm not opposed to trying.

I'll also look at the runsettings approach. We're currently not using that, but I'm not opposed to trying that either.

I'll poke at this and get back to you.

**Comment by acesiddhu** [comment]
yup nuget is what I meant (auto correct)

**Comment by tanvi-soni** [comment]
@bpsmicro are you unblocked by using nuget package and runsettings file ?

**Comment by bpsmicro** [comment]
I gave up on the v2 VSTest task for now. While I could replace the use of /UseVisxExtensions via including the test adapter in the solution's NuGet package, and the /Platform via a .runsettings file, I ran into other unrelated problems with the task. So for now I'm sticking with the v1 version, and I'll just hope the v2 one gets better at some point.

**Comment by PBoraMSFT** [comment]
@bpsmicro - I am sorry to hear that you are experiencing issues with the v2 task. We are looking to make this task version the default in the upcoming couple of sprints, so making sure customers are successful is a priority for us. I would like to understand better the issues you are facing, so we can address them. Can you please send me details about the other issues you are running into? You can reach me at pbora AT microsoft DOT com.
I can also setup some time over Skype if necessary.

**Comment by bpsmicro** [comment]
E-mail sent. I can run some tests for you offline and send some logs, and then we can decide if I need to log new issues here.

**Comment by RanjanarMS** [comment]
@PBoraMSFT : Hope you will take it offline

**Comment by cindymarie** [comment]
I encountered this issue a while ago while building my project with vstest. Tests were undiscoverable. :(

**Comment by PBoraMSFT** [comment]
@cindymarie - this issue that has been addressed a long time ago. If you are facing any problems with using vstest task, please log a new one. 
I am locking the conversation on this one to prevent old threads from going unnoticed.

@cltshivash @acesiddhu - FYI.
