### ISSUE TITLE
Gulp build is not considering shrinkwrap file 

### ISSUE THREAD

**Issue by mvvsubbu** [Microsoft/vsts-tasks#3843]
To lockdown the versions of direct and indirect dependencies to a module, task author can create npm-shrinkwrap.json file. This file locks down the version of dependencies, currently for webdeployment-common folder there is a npm-shrinkwrap.json file added but this is not honored during build process.

**Comment by bryanmacfarlane** [comment]
not a task issue ...

it's a repo infra issue

I think you just need to append this line.

https://github.com/Microsoft/vsts-tasks/blob/master/make-options.json#L75

**Comment by bryanmacfarlane** [comment]
closing because general shrinkwrap / impounding is high on our backlog.  Since your tasks went to shrinkwrap files and did feature support for that, you can modify the build script.
