### ISSUE TITLE
vstest TRX file not being uploaded

### ISSUE THREAD

**Issue by amccool** [Microsoft/vsts-tasks#3866]
since upgrading vstest we are no longer getting the test results uploaded.   We see this in the logs

```
Results File: C:\r5eBldAgent\_work\2\s\TestResults\loadbuild_R5EBUILDAGENT01 2017-03-24 15_11_46.trx
Vstest failed with error. Check logs for failures. There might be failed tests.
Error: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1
Unable to process logging event:##vso[results.publish type=VSTest;mergeResults=false;platform=any cpu;config=release;publishRunAttachments=true;resultFiles=C:\r5eBldAgent\_work\2\s\TestResults\loadbuild_R5EBUILDAGENT01 2017-03-24 15_11_46.trx;]
Vstest exited with return code: 1.
```

**Comment by acesiddhu** [comment]
Whats thw version build agent you are using?

**Comment by amccool** [comment]
PS C:\r5eBldAgent> .\agent\VsoAgent.exe /Version
1.95.3

on premise TFS 2105 Update 3

**Comment by acesiddhu** [comment]
sorry for more questions. 
Are you on TFS on prem 2015 update 3 or you are using vsts?
What version of vstest task are you using? version 1 or version 2?

**Comment by amccool** [comment]
on premise TFS 2105 Update 3

2.0.19

**Comment by acesiddhu** [comment]
in that case how did you get vstest 2.0.19. did you upload it? vstest works only with agent version 2.

**Comment by bryanmacfarlane** [comment]
@acesiddhu - the task should demand 2.x agent in the task.json.  Does it do that?

**Comment by acesiddhu** [comment]
@bryanmacfarlane it doesn't do that as this was shipped in update 1 where only agent version 2 is supported. is that correct?

**Comment by amccool** [comment]
we were having alot of issues with the 1.x version not looking thru sub-directories to find nuget'ed test adapters.   version 2.x appears to do this much better.

We upgraded using https://github.com/Microsoft/vsts-tasks/issues/3768

**Comment by amccool** [comment]
Is it possible to leave the 2.x task installed (1.x is installed as well), and make the "demands" use the 1.x task?  forgive my syntax and nouns, these vNext tasks and agent internal bits are new to me.

**Comment by acesiddhu** [comment]
@amccool not sure if this can be done in tfs 2015 update 3. Feature to choose a select major version of task was introduced in tfs 2017 update 1. @bryanmacfarlane any suggestions here?

@amccool you can also continue to use vstest v2 task and to publish results you can use publish teet results task and choose vstest option in that. But I am not sure if there can be any other issues if you continue to use version 2 vstest

**Comment by amccool** [comment]
We added the "Publish Test Results" task with VStest format, and **/*.trx and that is working fine.
