### ISSUE TITLE
Service Fabric Deploy task should support Windows Authentication

### ISSUE THREAD

**Issue by wasabii** [Microsoft/vsts-tasks#3873]
I use an on-premise cluster, with Windows Authentication as the auth method. There's no option for this in the external resource definition.

It's as simple as adding a new radio button and putting -WindowsCredential on the Connect-ServiceFabricCluster call.

**Comment by MikkelHegn** [comment]
Backlogged...

**Comment by Adebeer** [comment]
I need this too, please. Is there another way I can workaround this issue? I'm trying to setup a Service Fabric Release with deployment to our on-premise cluster.
