### ISSUE TITLE
Gradle task fails when installing Android Support Repository v47.0.0

### ISSUE THREAD

**Issue by mrbelk** [Microsoft/vsts-tasks#3891]
Trying to set up a CI build of an Android app and as the gradle task works through its chores, it fails trying to install the Android Support Repository (revision 47.0.0).

Here is the error from the gradle build step:
`
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':components'.
      > Could not resolve all dependencies for configuration ':components:_debugPublish'.
         > A problem occurred configuring project ':models'.
            > Failed to install the following SDK components:
              [Android Support Repository]
              Please install the missing components using the SDK manager in Android Studio.
`
Where do I tell my project to not require this version of the support repository?

I have other Xamarin.Android projects that build just fine. I know it's like apples and oranges, but ultimately the xamarin build needs the same SDK files as a native android app does, right?

**Comment by madhurig** [comment]
@mrbelk: What android SDK version are you targeting?

**Comment by mrbelk** [comment]
The project was targeting 25, but we just changed it to 24. We are using the hosted build agent, FWIW.

**Comment by madhurig** [comment]
@mrbelk: Thanks, does 24 work or do you see the same issue? The hosted build agents don't have all the build tools versions for SDK 25. Please check the build-tools version being used in your project.

**Comment by mrbelk** [comment]
no, targeting 24 does not work, either. the gradle task fails with the same error trying to load the support repository v47.0.0. what version of the build tools should the project use?

**Comment by madhurig** [comment]
25.0.2 and 25.0.3 are not installed on the hosted build machines, so targeting those build tools will give an error. We have an update planned to include those. I checked the "Android Support Repository" version included on the image - we have version **46**, I see the update to version 47 but we don't have a plan to update that as of now.

The software update process on the hosted build agents is slower due to several reasons - one of them being we have one VM image for all accounts in Team Services. We try to install most of the components  needed to build common projects but it is not guaranteed to include all components or the latest components. 

We are moving towards a different model that will allow us to add new software faster and give users options in what software components they require. Till that is available the alternate option would be to setup your own build server and install the components required for your build.

Thanks,
Madhuri

**Comment by mrbelk** [comment]
I just looked over the dev's shoulder and he's specifying the build tools at v25.0.0. He doesn't see anywhere to explicitly set the support repository version.

**Comment by sahilNaran** [comment]
@madhurig How does one use Android support repository 46 instead of 47?

**Comment by sahilNaran** [comment]
@mrbelk Have you found a workaround?

**Comment by niiiksh** [comment]
@mrbelk how did you change android support repository version to **46**?

**Comment by sahilNaran** [comment]
@niiiksh 
I managed to get my build running with the help of @leantk.
There's a couple of things that I did:
- I set up the following build steps
![image](https://cloud.githubusercontent.com/assets/7221948/25116171/51f6f2b6-240b-11e7-9315-8136c78e312c.png)

In the powershell script for "Type" select "Inline Script". In the "Inline Script" text input enter the following:
`New-Item -ItemType Directory -Path "C:\java\androidsdk\android-sdk\licenses"

New-Item -Name 'android-sdk-license' -ItemType File -Value '8933bad161af4178b1185d1a37fbf41ea5269c55' -Path "C:\java\androidsdk\android-sdk\licenses"

Get-Content "C:\java\androidsdk\android-sdk\licenses\android-sdk-license"`

- Then navigate to "Project Settings" -> "Agent queues"
![image](https://cloud.githubusercontent.com/assets/7221948/25116283/08351d46-240c-11e7-86d0-1feaa9f5b603.png)

- Select hosted VS2017. Then click on "Capabilities", add java ("C:\Program Files (x86)\Java\jdk1.8.0_112") and then click save changes. It should look like this.
![image](https://cloud.githubusercontent.com/assets/7221948/25116350/83f521e2-240c-11e7-8e7d-a8a2a5678414.png)

- Then when you build it select "Hosted VS2017" from the dropdown.
![image](https://cloud.githubusercontent.com/assets/7221948/25116401/deebc542-240c-11e7-9704-fa8330ec31c0.png)

**Comment by niiiksh** [comment]
@sahilNaran I'm using Android Studio, does hosted VS2017 will work for it?

**Comment by sahilNaran** [comment]
@niiiksh In my honest opinion, it need not matter what IDE you are using.
I am using Android Studio as well, however whenever I commit to the master branch my build (using the Hosted VS2017 build agent) is automatically triggered,it builds successfully and generates the artifacts (.APK files).
I do hope someone VSTS replies and provides you with clear instructions as I could be sending you on a wild goose chase :-)

**Comment by madhurig** [comment]
@sahilNaran, @niiiksh: VS 2017 image should work for native android builds (i.e. even when you are using Android Studio as your IDE). With the next update of VS 2017 image you will not need to setup the capabilities manually. The script you are using to add the licenses should not be required as well.

**Comment by niiiksh** [comment]
@madhurig Seems like script for licenses is not required already. But I followed @sahilNaran steps with no luck. This is what I get in console:
```
C:\a\1\s\gradlew.bat :application:assembleRelease
Observed package id 'add-ons;addon-unknown-unknown-19' in inconsistent location 'C:\Program Files (x86)\Android\android-sdk\add-ons\addon-google_apis-google-19' (Expected 'C:\Program Files (x86)\Android\android-sdk\add-ons\addon-unknown-unknown-19')
Observed package id 'add-ons;addon-unknown-unknown-23' in inconsistent location 'C:\Program Files (x86)\Android\android-sdk\add-ons\addon-google_apis-google-23' (Expected 'C:\Program Files (x86)\Android\android-sdk\add-ons\addon-unknown-unknown-23')
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Project 'application' not found in root project 's'.
```
And at the end:
`Error: C:\a\1\s\gradlew.bat failed with return code: 1`

**Comment by sahilNaran** [comment]
@niiiksh instead of :application:assembleRelease use :app:assembleRelease
On a side note could you please upload your module structure and your gradle file

**Comment by niiiksh** [comment]
@sahilNaran Thank you, that helped!
