### ISSUE TITLE
Insufficient privileges while running Azure Active Directory cmdlets

### ISSUE THREAD

**Issue by witua** [Microsoft/vsts-tasks#3895]
Hello there,

I am trying to run a Azure PowerShell task in vsts and I am facing an issue of using Active Directory cmdlets (e. g. https://docs.microsoft.com/en-us/powershell/resourcemanager/azurerm.resources/v3.7.0/get-azurermadapplication). The message I receive is "Insufficient privileges to complete the operation".

What could be the problem and how to solve it?

**Comment by Ajay-MS** [comment]
@witua 


For user credential based authentication, you will get access to run azure active directory cmdlets and it will be successful. But user credential based authentication is not being supported via Tasks.

For service principal credentials, the application associated with the service principal needs to be granted sufficient graph permissions for the operations you want to use – so you need to grand permissions through the portal.

**Comment by Ajay-MS** [comment]
@witua 

Since didn't get response from long time I am assuming you are unblocked on issue. So closing this issue feel free to reopen if you still facing this issue.

**Comment by Jaffacakes82** [comment]
@Ajay-MS do you know which permission is required against the Service Principal to allow it to execute Get-AzureRmADApplication?

'Read directory data' doesn't seem to do the trick.

**Comment by zeevm** [comment]
I'm stuck on the exact same issue, anyone has a solution?

**Comment by SumiranAgg** [comment]
@zeevm This is dupelicate of https://github.com/Microsoft/vsts-tasks/issues/7710 
Please follow that thread. Closing this issue.
