### ISSUE TITLE
Can't find a way to parameterize AzureRM Subscription in Azure CLI tasks to make them reusuable between subscriptions

### ISSUE THREAD

**Issue by samattridge** [Microsoft/vsts-tasks#3896]
When using the Azure CLI task in Release Management you have to specify the AzureRM Subscription as part of the task arguments.  This is a selectable dropdown list that contains the list of Azure subscriptions that have been connected to VSTS.

I can't find a way of making this into a variable or parameter so that the task can be re-used across multiple subscriptions.  Am I missing something or is this not an option?  If it isn't an option, could it be made one?

Many thanks in advance.

**Comment by ds-ms** [comment]
@samattridge That is not an option as of now. Adding @RoopeshNair to take a call on this

**Comment by N-Usha** [comment]
@samattridge , currently Azure connection type, Azure subscription fields are of complex types which cannot be parameterized. In other words, you cant use a variable like $(subscription) in the release definitions. It has to be set from the drop-down.

**Comment by samattridge** [comment]
Thanks @N-Usha.  So this means we need to duplicate any tasks that use the Azure CLI Preview type for each subscription we want to use them in?  Seems rather counter-intuitive.  I'd obviously prefer not to do this so I'll have to find a work-around.

**Comment by mattlunn** [comment]
@samattridge: Have you found a workaround for this? We are stuck in the same situation...

**Comment by mitch-b** [comment]
We are in a situation where we have multiple developers - with multiple connected MSDN Azure subscriptions - registered as services in TFS. If I wanted to deploy a new Web App (and related assets) to my MSDN, I need to create a duplicate Release Management environment, and switch all of the ARM deployment tasks to my subscription. Everyone will have to do this, then our UAT/Production environments will point to our enterprise subscription. 

If any tasks change, this is now a manual effort to keep them all in sync. If we could use a variable to pass in the service/subscription ID, that would make this a lot more painless.

**Comment by N-Usha** [comment]
We are sorry for the trouble you are having Mitchell. We have now added the feature enhancement to our backlog and would soon be addressing it soon (exact timelines are not available though for now). Will keep you posted once its available. Thanks!

**Comment by mqlkmd** [comment]
Any update on the timeline for this feature?

We use taskgroups to ensure its the exact same way we run some of the release tasks through out the different environments. 
Obviously, we dont have production and development in same Azure subscription - so this is definitely a must for us.

Thanks.

**Comment by RoopeshNair** [comment]
@mqlkmd, In your taskgroup specify a $(subscriptionNameVar) or something similar for the subscription field. This will expose the subscription field as an input parameter for the task group. Now in each of your environment, you will be able to specify a different subscription endpoint.

**Comment by mqlkmd** [comment]
@RoopeshNair , are you sure this is working? I've tried to set the variable both as the subscription id and as the service enpoint name (like its listed if you use the normal picklist), but to no avail. The error is something regarding endpoint url not found. 
I think the subscription picklist selection is also setting some hidden fields like endpoint url and auth settings and thats why its not working with a variable.

@N-Usha do you have any updates on this issue?

Thanks.

**Comment by RoopeshNair** [comment]
@mqlkmd, where are you setting the variable? in task group UI or in the build/release definition? You need to specify $(foobar) in the endpoint field in the task group UI. If it isn't working for you, drop a note on https://developercommunity.visualstudio.com/spaces/21/index.html

**Comment by mqlkmd** [comment]
@RoopeshNair , I have tried both from the release def. and from the task group where I put the vsts variable in the "Azure Subscription" field of the task. The value Im providing for the variable is the endpoint id, which is the "id" field when looking at the REST api:
`        {
            "data": {
"deleted": "for simplicity"
            },
            "id": "5574c7d9-bdf4-6cb4-8e3b-9f2di4ne4e87",
            "name": "My Service Endpoint Name",
            "type": "azurerm",
            "url": "https://management.azure.com/",
            "createdBy": {
"deleted": "for simplicity"
            },
            "authorization": {
                "scheme": "ServicePrincipal"
            },
            "isReady": true,
            "operationStatus": {
                "state": "Ready",
                "statusMessage": ""
            }
        },
`

Anyways, I will post the issue on the link you sent.
Thanks for your help.

**Comment by mqlkmd** [comment]
@RoopeshNair , btw I have only tried this in the "Azure Powershell" task. Does it matter whether its the "Azure Powershell", "Azure CLI" or "Azure App Service Deploy" task?

**Comment by RoopeshNair** [comment]
No it shouldn't matter. btw, I requested to post on dev community so that we can share screenshots :)

**Comment by mqlkmd** [comment]
@RoopeshNair , thanks. I've posted the question on VS community site and share the link here if anybody else are interested: https://developercommunity.visualstudio.com/content/problem/149337/use-a-vsts-variable-to-set-subsriptionservice-endp.html

**Comment by mqlkmd** [comment]
For those interested, for me this actually works if you are using the "Azure App Service Deploy" task in your task group.
If you dont use that and only have "Azure Powershell" tasks, there is a workaround.
I posted my findings and the workaround on the issue here: https://developercommunity.visualstudio.com/content/problem/149337/use-a-vsts-variable-to-set-subsriptionservice-endp.html
