### ISSUE TITLE
Xamarin.Android build step fails loading .csproj file

### ISSUE THREAD

**Issue by mrbelk** [Microsoft/vsts-tasks#3900]
A Xamarin.Forms based solution that as recently as 2 days ago built just fine using the hosted agent now fails with the following error in the Xamarin.Android step:
`
2017-03-29T21:41:18.0531714Z   C:\a\1\s\Droid\bulkDelivery.Droid.csproj(527,45): error MSB4025: The project file could not be loaded. '<', hexadecimal value 0x3C, is an invalid attribute character. Line 527, position 45.
`

The line in question is this:
`
	<Import Project="..\packages\Xamarin.Forms.2.3.3.193\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20\Xamarin.Forms.targets" Condition="Exists('..\packages\Xamarin.Forms.2.3.3.193\build\portable-win+net45+wp80+win81+wpa81+MonoAndroid10+Xamarin.iOS10+xamarinmac20\Xamarin.Forms.targets')" />
`

I have tried manually retyping the line to no avail. I removed the line, pushed my repository, and the build step was at least able to load the project file and start building. I have moved the line to other spots in the project file and the build step fails with the same error, but referencing the new line.

What might be the problem?

**Comment by mrbelk** [comment]
I should mention that the project loads and builds fine with Xamarin Studio for Mac.

**Comment by jpricketMSFT** [comment]
@mrbelk - There have been no updates on the hosted build agent in past 2 weeks. It might be an encoding change between Mac and Windows. The hosted build machine is Windows. Can you build the same project in VS on Windows?

Thanks,
Jason

**Comment by mrbelk** [comment]
let me pull the latest in my windows VM and see if I can build it there. I don't have XS for windows installed, so it will be using VS2017. I assume that's OK, yes?

**Comment by mrbelk** [comment]
so the entire solution loaded and built successfully using VS2017 with Xamarin 4.3.0.784 and Xamarin.Android 7.1.0.41

**Comment by jpricketMSFT** [comment]
Thanks for giving that a try. I noticed this on the Xamarin forums site that might help, but the problem isn't completely the same:
https://forums.xamarin.com/discussion/69829/compiling-error-xamarin-ios-common-targets

I am not sure what the next steps should be. Can you attach your entire csproj file?

Thanks,
Jason

**Comment by mrbelk** [comment]
Here you go. I can see that you're as flummoxed by this as I am.

[bulkDelivery.Droid.csproj.txt](https://github.com/Microsoft/vsts-tasks/files/883666/bulkDelivery.Droid.csproj.txt)

**Comment by jpricketMSFT** [comment]
The file certainly looks okay to me. I don't see any problems. I will ask others on the team if they have any ideas on what could cause this.

**Comment by mrbelk** [comment]
I know. which is what makes this issue so bizarre.

**Comment by mrbelk** [comment]
I'm going to try setting up a local build agent and see if that works. we already have one set up to do some windows builds; so I just need to install the xamarin and android bits

**Comment by mrbelk** [comment]
I think I figured it out. I "upgraded" to use the v2 of the "VersionAssemblies" task and it did something bad so that in the line mentioned in the error (which loads the Xamarin.Forms targets) was being resolved to point to "c:\<blah>\Xamarin.Forms.<ReleaseVersion>w.x.y.z</ReleaseVersion>\blah\blah". I had to set up my own build agent so that I would be able to see the fetched source code with the changes some of my other tasks were performing.

**Comment by jpricketMSFT** [comment]
@mrbelk - thanks for sharing what you found. Were you able to fix the issue and use the hosted build machine again?

**Comment by mrbelk** [comment]
Yes I was/am. Thanks for your help. Sorry if I made you go round in circles on a wild goose chase.

________________________
Matthew Belk
ph. 678-287-3315

**Comment by jpricketMSFT** [comment]
No Worries :)
Glad you figured it out and got everything working.
