### ISSUE TITLE
Xml Trasformation Azure AppService Deploy

### ISSUE THREAD

**Issue by sudeeptm** [Microsoft/vsts-tasks#3902]
Azure App service deploy task does not perform the update to settings while deploying a dotnet core application.

**Comment by vincentdass** [comment]
@sudeeptm , Can you be more specific about the issue ?

The config transfoms will be run for `*.Release.config` and `*.<EnvironmentName>.config` on the `*.config file`.
Please ensure that the transform config files (say Web.Release.config) and main config file (say Web.config) are present in the same folder.

To transform `Web.config` by `Web.Debug.config`,  Rename your environment name as 'Debug'.
![image](https://cloud.githubusercontent.com/assets/20121508/24508950/ada510da-1582-11e7-9d26-bd07d195c17d.png)

Hope this helps.

**Comment by sudeeptm** [comment]
The task works properly for a regular MVC app or a web app where the file is named web.config. The task however has no effect on a dotnet core app where the settings file is named appsettings.json.

**Comment by vincentdass** [comment]
@sudeeptm , Currently Transform on appsettings.json is not supported.
You can use `JSON variable substitution` to substitute values in appsetttings.json.
![image](https://cloud.githubusercontent.com/assets/20121508/24537979/eb58d656-1603-11e7-956e-70f17cc2afa5.png)

Another workaround is to [set the variable in App Settings to use other env. app settings file](https://blog.elmah.io/configuration-with-azure-app-services-and-aspnetcore/).

**Comment by vincentdass** [comment]
Closing this thread, hoping that the above workaround will resolve the issue.
Please feel free to open the thread, if the issue persists.
