### ISSUE TITLE
Cannot see test analysis colnum in release dashboard and test tab

### ISSUE THREAD

**Issue by GuofuZhong** [Microsoft/vsts-tasks#3907]
![image](https://cloud.githubusercontent.com/assets/25610375/24503591/4ddd41ce-1585-11e7-8b52-84a25cde1289.png)
Hi guys
we have some unstable  test,
we have to update analysis in Test Run Explorer.
make sure this test isn't blocker.
but our DRI cannot see analysis content in dashboard directly.
I'm just wondering if you have plan of adding more column options? such as test analysis column.

**Comment by bryanmacfarlane** [comment]
This repo is for tracking tasks that ship with VSTS and TFS.
