### ISSUE TITLE
Azure App Service MSDeploy SetParam Additional Arguments

### ISSUE THREAD

**Issue by podgito** [Microsoft/vsts-tasks#3910]
I refer you to issue #3587 in which a workaround for the issue was to use single quotes. 

I have encountered an issue when using single quotes instead of double quotes with EF connection strings

In the Additional Arguments I have -setParam:'tickets_v5Entities-Web.config Connection String'='$(ConnectionString)'

My connection string is an entity framework connection string which as you probably know contains single quotes for example

`
metadata=res:///Models.Domain.EventsModel.csdl|res:///Models.Domain.EventsModel.ssdl|res://*/Models.Domain.EventsModel.msl;provider=System.Data.SqlClient;provider connection string='1.2.3.4;initial catalog=myDB;user id=admin;password=password123;MultipleActiveResultSets=True;App=EntityFramework'`

I've tried escaping the single quote but with no luck.

I believe that double quotes are the correct way to delimit the start and end of the -setparam values and not single quotes.

**Comment by podgito** [comment]
Just to add, I noticed that in version 3.x you support XML transformations, presumable separate to MSDeploy. If that's the direction I should take for swapping environmental variables at deploy time I will be happy to adopt that instead.

**Comment by vincentdass** [comment]
@podgito , thanks for reporting the issue. 
Please do try any of the possible workaround below:

- **XML Transformation**: Provide your transformation logic in Web.< EnvironmentName > .config.
- **XML Substitution:** : Substitute values in *.config file. (Currently special XML characters are escaped , which will be fixed in upcoming dpeloyment).
- **[SetParameter ](https://msdn.microsoft.com/en-us/library/ff398068(v=vs.110).aspx)file**: Create a  XMl file that replaces parameters.xml values and provide it as input in setparameter file input.

**Comment by vincentdass** [comment]
Closing this thread, hoping that the above workaround will resolve the issue.
Please feel free to open the thread, if the issue persists.

**Comment by podgito** [comment]
If I am looking to deploy a web application which is packaged into a single zip file, is the XML transformation in the v3.x task supposed to work? Doesn't seem to. It seems to only work on XML files it can find in a directory.

**Comment by vincentdass** [comment]
@podgito , XML transformation will work for both web package and folder.
In case of zip, we extract the zip and apply the transformation.

For the XML transformation to take effect, the transform files (say Web.debug.config) should be in the same folder as main config file (say web.config).

**Comment by podgito** [comment]
Apologies, I meant XML variable substitution instead of XML transformation.

**Comment by vincentdass** [comment]
@podgito , yes, XML substitution is also available in ZIP package.
ZIP package is extracted ,when any of the option in file transformation group is enabled and the corresponding transformation is applied and zipped back.

**Comment by vincentdass** [comment]
Closing this thread as threre is no action item on team.
