### ISSUE TITLE
VSTS Test Result Analysis: Failure Type add "Faluse Alarm" and Resolution add "External Issue"

### ISSUE THREAD

**Issue by nickeyyan** [Microsoft/vsts-tasks#3911]
Hi VSTS Team,

As we used VSTS to run our test cases, but we found that default fields are not enough. It would be better to havev below items.

Failure Type: Add "Faluse Alarm"
Resolution: Add "External Issue"
Result Grid: Add "Analyzed Result"

Thanks,
Nickey

**Comment by bryanmacfarlane** [comment]
This repo is for build and release tasks.  That doesn't sound like a task issue.

**Comment by nickeyyan** [comment]
@bryanmacfarlane this is VSTS view issue. To make it more reasonable.
