### ISSUE TITLE
unable to StartSonar.bat file.

### ISSUE THREAD

**Issue by dpadhya1990** [Microsoft/vsts-tasks#3919]
Hello Team 

I am currently configuring sonarqube 6.3 for TFS 2015, while running StartSonar.bat file getting below mentioned error 
--> Wrapper Started as Console
Launching a JVM...
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
  Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.

2017.03.31 02:58:58 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory C:\sonarqube\temp
2017.03.31 02:58:58 INFO  app[][o.s.p.m.JavaProcessLauncher] Launch process[es]: C:\Program Files\Java\jre1.8.0_121\bin\java -Djava.awt.headless=true -Xmx1G -Xms256m -Xss256k -Djna.nosys=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=C:\sonarqube\temp -javaagent:C:\Program Files\Java\jre1.8.0_121\lib\management-agent.jar -cp ./lib/common/*;./lib/search/* org.sonar.search.SearchServer C:\sonarqube\temp\sq-process3543446633649820202properties
2017.03.31 02:59:10 INFO  app[][o.s.p.m.Monitor] Process[es] is up
2017.03.31 02:59:10 INFO  app[][o.s.p.m.JavaProcessLauncher] Launch process[web]: C:\Program Files\Java\jre1.8.0_121\bin\java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=C:\sonarqube\temp -javaagent:C:\Program Files\Java\jre1.8.0_121\lib\management-agent.jar -cp ./lib/common/*;./lib/server/*;C:\sonarqube\lib\jdbc\h2\h2-1.3.176.jar org.sonar.server.app.WebServer C:\sonarqube\temp\sq-process482105096691381396properties
2017.03.31 02:59:12 INFO  app[][o.s.p.m.Monitor] Process[es] is stopping
2017.03.31 02:59:12 ERROR app[][o.s.p.m.Monitor] Process[web] failed to start
2017.03.31 02:59:13 INFO  app[][o.s.p.m.Monitor] Process[es] is stopped
<-- Wrapper Stopped

Regards

Dushyant Padhya

**Comment by bryanmacfarlane** [comment]
This repo doesn't deliver sonar.bat.  You will have to follow up with the sonar team.  This repo is for the in the box tasks that ship with VSTS and TFS.

**Comment by DavidStaheli** [comment]
Here is a forum where questions can be asked of SonarSource about SonarQube integration with TFS/Team Services:  https://groups.google.com/forum/#!forum/sonarqube
