### ISSUE TITLE
xUnit tests are not discovered unless the path to the runner is explicitly specified

### ISSUE THREAD

**Issue by Leon99** [Microsoft/vsts-tasks#3923]
Looks like /TestAdapterPath is not passed to vstest.console.exe unless the path (in my case `$(System.DefaultWorkingDirectory)\packages\xunit.runner.visualstudio.2.2.0\build\_common`) is explicitly specified in the build definition, despite the hint that suggests 

> Nuget restored adapters are automatically searched for.

**Comment by nigurr** [comment]
@Leon99 can you please post your Build log with system.debug=true

**Comment by devdigital** [comment]
Also facing the same issue using TFS Version 15.112.26307.0 on-prem - explicitly setting the TestAdapterPath fixes the issue.

**Comment by nigurr** [comment]
@devdigital I believe you are using VsTest task v2 version? If so, this fix is available in next TFS Update 2017 Update2

**Comment by devdigital** [comment]
Thanks, will give that a try

**Comment by mclark1129** [comment]
When I try to add `$(System.DefaultWorkingDirectory)\packages\xunit.runner.visualstudio.2.2.0\build\_common\` in the test adapter path, my build will fail with the message.  

> Error: The path 'C:\a\1\s\packages\xunit.runner.visualstudio.2.2.0\build' specified in the 'TestAdapterPath' is invalid. Error: The custom test adapter search path provided was not found, provide a valid path and try again.

For some reason the Execute Tests task appears to be stripping `_common\` from the path.  Not sure if that is just a logging issue or not.

**Comment by nigurr** [comment]
Hi, This has been fixed in latest task version. it should be rolling out to VSTS customers in a week or two.
