### ISSUE TITLE
vstest.executionengine.exe has stopped working

### ISSUE THREAD

**Issue by k3flo** [Microsoft/vsts-tasks#3926]
Dear Microsoft Team,

after you sugessted not executing the integration tests on the build server (https://github.com/Microsoft/vsts-agent/issues/883)  I set up a new VM where our application, the tests agent and the tests binaries gets deployed. The deployment works fine but when the tests gets executed the test runner is always crashing after some time (it is mostly running about 70 minutes).
The new VM is also a Windows 2008R2 Server (like before). I attached the screenshot that shows how the test runner crashes and also I attached the DTAExecutionHost.exe.log file and two event viewer log screenshots. 

Please help us soon. It is really important for us to run our integration tests every day.

Thanks for your help.

With kind regards
Florian Ertelt

[DTAExecutionHost.exe.txt](https://github.com/Microsoft/vsts-tasks/files/889116/DTAExecutionHost.exe.txt)

![eventlog1](https://cloud.githubusercontent.com/assets/12381373/24597412/05924c34-1846-11e7-94f9-87b06535708c.jpg)

![eventlog2](https://cloud.githubusercontent.com/assets/12381373/24597415/094fab28-1846-11e7-97ae-25cd955dc990.jpg)

![test_agent_crash](https://cloud.githubusercontent.com/assets/12381373/24597419/0ea713d6-1846-11e7-91e5-afdf5cb3b17c.PNG)

**Comment by nigurr** [comment]
@k3flo Can you please attach the process dump when it crashes? 
Are you able to run these tests using "vstest.console.exe" in the same machine?

**Comment by k3flo** [comment]
@nigurr the dump file is 1 GB big (zipped).
I upladed it at uploadfiles.io: https://ufile.io/c1db21
If I should upload it somewhere else, please let me know.

**Comment by nigurr** [comment]
@k3flo thanks alot

**Comment by nigurr** [comment]
Tracking here: https://github.com/Microsoft/vstest/issues/704
