### ISSUE TITLE
<Parameter> attributes are case-sensitive when overriding

### ISSUE THREAD

**Issue by ekumlin** [Microsoft/vsts-tasks#3929]
When using a `runsettings` file in Visual Studio, the following block is valid:

	<RunSettings>
	  <TestRunParameters>
	    <Parameter Name="foo" Value="bar" />
	  </TestRunParameters>
	</RunSettings>

However, the *Run Tests* task assumes that the `name` and `value` attributes are lowercase ([settingshelper.ts:183](https://github.com/Microsoft/vsts-tasks/blob/fd0f5c9c2e75b143f0d1a3eb64ac3d311d48ca37/Tasks/VsTest/settingshelper.ts#L183)). This means that the parameters are not replaced, and no warning or error is provided to explain the behavior. Without viewing the source code, it is not obvious that this is required.

Additionally, debug logs even put these in uppercase when outputting:

	2017-04-03T21:09:36.6415615Z ##[debug]Name : foo Value : bar

Which makes the issue even more confusing.

**Ask: Please either add documentation explicitly stating that replaced `<Parameter>` attributes are case-sensitive, or support case-insensitive attributes.**

**Comment by tanvi-soni** [comment]
@ekumlin Thanks for bringing up this issue. We are discussing this internally on how we want to address this.

**Comment by nigurr** [comment]
Addressed here https://github.com/Microsoft/vsts-tasks/pull/4137
