### ISSUE TITLE
"dotnet publish" VSTS task reorders arguments, cannot pass additional arguments to MSBuild

### ISSUE THREAD

**Issue by AaronRM** [Microsoft/vsts-tasks#3938]
To repro, create an instance of the .NET Core (Preview) task, set the command to 'publish' and the arguments to the following:

`--output $(Build.ArtifactStagingDirectory) --configuration $(BuildConfiguration) /p:MyProperty=true`

When executed, you'll notice that the above arguments are not in the order specified. The following command ends up getting executed:

`dotnet.exe publish <pathToCsproj> --configuration Release /p:MyProperty=true --output <outputPath>`

Note that the argument order was switched around. This causes dotnet.exe to treat everything after '--configuration Release' as an additional argument to MSBuild. MSBuild then fails on the --output argument.

**Comment by ds-ms** [comment]
I will look into it.

**Comment by ds-ms** [comment]
https://github.com/Microsoft/vsts-tasks/pull/4013 Fixed in this PR
