### ISSUE TITLE
VSTS Test Result Analysis: Failure Type add "Faluse Alarm" and Resolution add "External Issue" 

### ISSUE THREAD

**Issue by nickeyyan** [Microsoft/vsts-tasks#3941]
Hi VSTS Team,
As we used VSTS to run our test cases, but we found that default fields are not enough. It would be better to havev below items.
Failure Type: Add "Faluse Alarm"
Resolution: Add "External Issue"
Result Grid: Add "Analyzed Result"

Thanks,
Nickey

**Comment by bryanmacfarlane** [comment]
This repo does not track all issues with VSTS.  This repo and the issues are for the tasks.  

Re-open if you are having an issue with one of these tasks: https://github.com/Microsoft/vsts-tasks/tree/master/Tasks

If you have feedback on VSTS, look here: https://www.visualstudio.com/en-us/docs/provide-feedback
