### ISSUE TITLE
Azure Resource Group Deployment task - Add " Stop and deallocate virtual machines" action

### ISSUE THREAD

**Issue by PauloRamosGit** [Microsoft/vsts-tasks#3946]
Current "Stop virtual machines" action does not deallocate the VM which leads to continued compute costs.
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/powerOff

Having a " Stop and deallocate virtual machines" action will give the option to stop and deallocate the VM wish stops the compute costs.
/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Compute/virtualMachines/{vmName}/deallocate

**Comment by leftler** [comment]
Possible duplicate of #3868

**Comment by leftler** [comment]
My PR was accepted so it should make its way to production eventually.

**Comment by PauloRamosGit** [comment]
Great stuff! Thanks.
