### ISSUE TITLE
Chef and Chef Knife stuck in preview

### ISSUE THREAD

**Issue by bryanmacfarlane** [Microsoft/vsts-tasks#3950]
These tasks need to come out of preview for QU2 or get deleted since they were never non preview.

Address by 116 so you have a sprint of runway for 117 cutoff.

**Comment by RoopeshNair** [comment]
@bryanmacfarlane @kmkumaran 

I'm working with Chef team get it converted into an official extension from Chef. There are active deployment with this task. Without replacement, I don't want to pull this out. 

I'll check back with Chef team about availability of the extension. We might have to hold this a little longer.

Thanks,
