### ISSUE TITLE
FtpUpload task fails with the wrong error message when the protocol is missing from the Server URL

### ISSUE THREAD

**Issue by nemesv** [Microsoft/vsts-tasks#3956]
Steps to reproduce:

Add an FTP Upload task
Enter the server name without a protocol: e.g.: ftp.someserver.com
Fill in the other required fields
Save the task
Run the build

Output:
The task fails with a quite unhelpful error message:

    ##[error]Unhandled: Cannot read property 'toLowerCase' of null

Expected output:
The task editor UI should  validate the ServerName that it contains a port or the task should fail with a more useful error message.

**Comment by DavidStaheli** [comment]
Hi @nemesv, thank you for reporting this!  That was quite a vague error message.  I created a pull request for this (#3957) and it should get fixed today.

**Comment by DavidStaheli** [comment]
This is now fixed.  Thanks again, Viktor!

**Comment by nemesv** [comment]
Thanks David for the fix!

**Comment by AndyRace** [comment]
FYI: I came across this today.
Adding ftp:// as the protocol sorted it
