### ISSUE TITLE
Docker: Re-tagging a Docker image is difficult in VSTS build definitions

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/vsts-tasks#3959]
This was reported by a large enterprise customer.  Can we make this easier?

"Let me explain the scenario we have currently setup with in our build definitions, as we are using docker vsts-agent to run our builds, our build-agent goes away once the build is complete."

**Build-Def1:**
1.	Build Docker image – with version tag ( This works on plugin)
2.	Push to registry        ( This works on plugin)
3.	Deploy to a remote machine

**Build-Def2:**
1.	Run integration tests – if passed
2.	Retag image – to mark it-passed ( This requires to pull image, retag and push to a different registry)  - this is where we have to use script, as it requires at least 5 steps on build definition just for retagging

**Build-Def3:**
1.	Run e2e test
2.	Retag image – to mark e2e-passed  ( This requires to pull image, retag and push to a different registry) - this is where we have to use script, as it requires at least 5 steps on build definition just for retagging

**Comment by azooinmyluggage** [comment]
Thanks for the details. I am writing the next set of improvements to the task and I will keep this scenario as a priority.

**Comment by iandvt** [comment]
Any update on this scenario? I would like to do something similar in my deployment process

1) Push an image tagged as master to ACR and have it auto deploy to the staging slot of a Web App
2) Require a manual step / intervention to trigger a Web App Slot Swap from staging to production
3) Retag image master image as latest

**Comment by azooinmyluggage** [comment]
Yes. Have you tried the latest App Service task version. It has support for Web App for Containers and the scenario you have mentioned can be easily attached.
Also look at Azure DevOps Project in case you want to setup a container pipeline in just three simple steps.
https://azure.microsoft.com/en-in/features/devops-projects/

**Comment by Shaddix** [comment]
I see how the task integrates with Slot Swap, but what about initial request:

> This requires to pull image, retag and push to a different registry

Can this be done in one build step now?

**Comment by simonjduff** [comment]
I'm also keen for this. My builds are similar:
B1) Build unit test, tag as release candidate.
B2) Tag as stable release
