### ISSUE TITLE
PublishCodeCoverageResults Task Summary File & Report Directory Parameters do not allow for wildcard/glob patterns

### ISSUE THREAD

**Issue by klabranche** [Microsoft/vsts-tasks#3960]
I am using the Publish Code Coverage Results task in TFS 2015 (Version 14.102.25423.0) and I have to explicitly state the location of my summary file and report directory. 

For example, if I use below for Summary File the task fails with "does not exist or is not accessible"
$(build.sourcesdirectory)\artifacts\**\*$(configuration)\testresults\coverage\cobertura.xml

However, if I replace the wildcards with the full path it works.

This is problematic as a folder in the wildcard section is dynamically made based off the version #'s of the app being built.

**Expected Results** 

To use wildcards/glob patterns like the Publish Test Results allow for the Test Results Files parameter.

**Comment by DavidStaheli** [comment]
Hi @klabranche.  Thanks for reporting this.  We're close to having a fix in place with pull request #3969.

**Comment by klabranche** [comment]
Awesome!!! Thanks Team!!! 👍
