### ISSUE TITLE
Some VSTS accounts can't view nuget 4.0 in NuGet Installer task

### ISSUE THREAD

**Issue by lvsezhufu** [Microsoft/vsts-tasks#3966]
**Nuget version 4.0** is available for **NuGet Installer task**. But for some VSTS accounts, the version 4.0 can't found. Does there need some settings to make nuget 4.0 display?

An account doesn't show nuget 4.0:

![nuget4 0 is not display](https://cloud.githubusercontent.com/assets/23092306/24791113/7b07cfee-1bab-11e7-92ec-dafba16ea878.png)

The other account show nuget 4.0:

![nuget4 0 display](https://cloud.githubusercontent.com/assets/23092306/24791116/7feee240-1bab-11e7-9c6c-eed28da33f6a.png)

**Comment by NetTecture** [comment]
Seconded. Not seeing it eiither, no way to change to some sort of preview of the next version.

**Comment by ericsciple** [comment]
it looks like this was added in the last deployment. the deployment rolls out in rings. the deployment has reached everywhere now. please reopen if not resolved.
