### ISSUE TITLE
"dotnet publish -o obj/foo" does not respect output parameter

### ISSUE THREAD

**Issue by golfguy0082** [Microsoft/vsts-tasks#3972]
I found that when passing an explicit output path to the `dotnet publish` task, the task modifies the output path by appending the projectFileName on the end (see [getModifiedOutputForProjectFile](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/DotNetCoreCLI/dotnetcore.ts)).  This is unexpected and makes it hard to chain commands together when left "guessing" what the output path will actually be.

Expected behavior:
If an explicit output path is specified, it should be left untouched

Actual behavior:
The projectFileName is appended to the output path.

**Comment by benc-uk** [comment]
Same problem here, I'm getting 's' appended to my path NO MATTER WHAT I DO!
so specifying `--configuration release -o pub` in my task results in `publish /opt/vsts/work/1/s/dotnet-demoapp.csproj --configuration release --output pub/s` being executed.

**Where is this 's' coming from, this doesn't happen when running locally, only in VSTS**

**Comment by benc-uk** [comment]
I've given up on the Dotnet Core tasks, and just used a simple command task

**Comment by DarqueWarrior** [comment]
I just did the same thing in using the command task instead of this one. I was trying to use the task to publish my project and line 42 messes everything up. If I wanted the project name on the end of my output path I would have put it there.  Respect the parameters passed to the task or at least give the option to not have you touch the parameters.

**Comment by sachinma** [comment]
With 2.0 version of the task, now there is an option to not change the default behavior by appending the container path. With this control is in user's hands.
The reason for still having the option to preserve the old behavior is that the task can work with multiple projects. In such a case, if an ouput path is provided, this behavior lets you have cleanly publish all of them.
