### ISSUE TITLE
maven build job on PR can't find report-task.txt

### ISSUE THREAD

**Issue by ratcashdev** [Microsoft/vsts-tasks#3976]
Using VSTS 2017 and Sonarqube 6.x
PR jobs are started with `-Dsonar.analysis.mode=issues` hence sonar does not generate the report-task.txt. The build does not find it, and consider the sonar analysis broken. As a result the PR is not populated with sonar analysis result's comments.

**Comment by ericsciple** [comment]
Sonar integration is a third party extension (not this repo)

**Comment by ericsciple** [comment]
@DavidStaheli to verify i'm not overlooking something (since this is a Maven build). I think this issue should be closed here and follow with Sonar folks would be best.

**Comment by ratcashdev** [comment]
Just mentioning, that while we do have installed the extension from SONAR (3rd party), it does not look like  the maven job was not replaced (yet) by the Sonar folks - I know the MS Build tasks are already deprecated because of this.

**Comment by ratcashdev** [comment]
Note that the above happens with `Include full analysis report in the build summary (SQ 5.3+)` enabled but without `Fail the build on quality gate failure (SQ 5.3+)` being active.

**Comment by ratcashdev** [comment]
FYI, after checking the sources, it seems it's really `https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/Maven` that currently provides this functionality for maven.

**Comment by lkillgore** [comment]
Hi @ratcashdev, we made some changes recently, and I believe this is currently set to the behavior you're requesting, so I'm closing this ticket.  If that's not the case or if need a change in functionality, please open a new ticket for our consideration.  Thanks!

(Additionally, we've asked SonarQube to take over the development of the SonarQube logic, so this may change in the future.)
