### ISSUE TITLE
Update to Task version 1.1.9 results in SQLCMD path issue on build server

### ISSUE THREAD

**Issue by divyesh-parikh** [Microsoft/vsts-tasks#3984]
SqlAzureDatpacDeployment task updated to version 1.1.9. This caused the release to fail with the following error:

The term 'sqlcmd.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Deployment works fine with version 1.1.8

**Comment by brushwood24** [comment]
I am seeing the same behavior.  1.1.9 broke our Azure SQL dacpac deploy tasks that were working in 1.1.8.  We get the error:
The term 'sqlcmd.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by minghan** [comment]
I am seeing the same issue too.

**Comment by mvvsubbu** [comment]
There is another issue opened for the same, I am linking it here and closing this thread. Please refer the other one for updates. 

https://github.com/Microsoft/vsts-tasks/issues/3993
