### ISSUE TITLE
Real time logs/stats of unit test execution on VSTS console

### ISSUE THREAD

**Issue by sonalsavaratkar** [Microsoft/vsts-tasks#3986]
Hello,

I have similar requirement as issue  #3492 , doesn't matter if test is failed or passed. I want to see my logs in real time which I am logging with either:
`System.Diagnostics.Trace.WriteLine("Trace writeline");`
or
`Console.WriteLine(message);`

My tests are integration tests where a good amount of data is cross-checked. So I want to provide a custom summary of what all type of data has been cross-verified.

Please help.

**Comment by nigurr** [comment]
Hi,
Currently this feature is not available. Please add post your suggestion here and we will add it to our backlog https://visualstudio.uservoice.com/forums/330519-team-services
