### ISSUE TITLE
VSTest task ignores the VSTS TestResults directory $(Common.TestResultsDirectory) while saving test results

### ISSUE THREAD

**Issue by jerryjoseph-net** [Microsoft/vsts-tasks#3990]
VSTest task used to create the test results in $(Common.TestResultsDirectory). This worked well with VSTS since it deletes and recreates this folder in the beginning of each build. 

A [recent commit](https://github.com/Microsoft/vsts-tasks/commit/a36ed4f67049938d6e9e0361b5f0e31bf8d55da0) has changed this behavior. Now the test results are being created in /s/TestResults/ and I need an extra step to delete this folder.

IMO this is unnecessary and VSTest task should use the VSTS path $(Common.TestResultsDirectory) when possible.

[Related issue](https://github.com/Microsoft/vsts-tasks/issues/2745)

**Comment by RanjanarMS** [comment]
Yes the test results are created in /s/TestResults/, but you don't need to cleanup manually. It will cleaned up by the next build.

**Comment by jerryjoseph-net** [comment]
The next build cleans up /TestResults which is $(Common.TestResultsDirectory) but not /s/TestResults which is $(Build.SourcesDirectory)/TestResults

My build logs are showm below

2017-04-13T07:27:54.0190444Z ##[debug]Preparing build directory.
2017-04-13T07:27:54.0659230Z ##[debug]Delete existing artifacts directory: 'H:\a\A1\_work\xxx\a'
2017-04-13T07:27:54.0659230Z ##[debug]Deleting artifacts directory: 'H:\a\A1\_work\xxx\a'
2017-04-13T07:27:54.2690613Z ##[debug]Creating artifacts directory: 'H:\a\A1\_work\xxx\a'
2017-04-13T07:27:54.2690613Z ##[debug]Delete existing test results directory: 'H:\a\A1\_work\xxx\TestResults'
2017-04-13T07:27:54.2690613Z ##[debug]Deleting test results directory: 'H:\a\A1\_work\xxx\TestResults'
2017-04-13T07:27:54.2690613Z ##[debug]Creating test results directory: 'H:\a\A1\_work\xxx\TestResults'

**Comment by RanjanarMS** [comment]
Hey this deletion is not shown in the logs.. But are you seeing trx files piling up with builds?

**Comment by RanjanarMS** [comment]
Closing this as the issue no repro and no response from the customer

**Comment by edenroz** [comment]
This issue still persiste for me:
In Azure DevOps Pipeline while getting sources I get

##[error]One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (The startIndex argument must be greater than or equal to zero. (Parameter 'startIndex'))) (The startIndex argument must be greater than or equal to zero. (Parameter 'startIndex')))) (The startIndex argument must be greater than or equal to zero. (Parameter 'startIndex'))
