### ISSUE TITLE
SqlAzureDapacDeployment Broken when trying to add IP Address Ranges on Private Agent

### ISSUE THREAD

**Issue by debugthings** [Microsoft/vsts-tasks#3993]
## Problem Description
There is a bug in the Utility.ps1 that checks the connection for the IP address range that expects a the sqlcmd.exe to be in the PATH. This breaks any existing release on an agent that does not explicitly have sqlcmd.exe in the PATH.

[Line 26](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/SqlAzureDacpacDeployment/Utility.ps1#L26) has the sqlcmd.exe hard coded when they should either use the Execute-Command as demonstrated [here](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/SqlAzureDacpacDeployment/DeploySqlAzure.ps1#L178), or use the [Get-SqlPackageOnTargetMachine](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/SqlAzureDacpacDeployment/FindSqlPackagePath.ps1#L1) to find the file path.

## Expected Behavior
It works without error.

## Actual Behavior
A failed release and the following error message `##[error]The term 'sqlcmd.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

**Comment by minghan** [comment]
**Work around**: Add a powershell VSTS task as a first step in the build/release definition. Use the "Inline Script" type.
Inline Script contents:

```
# https://github.com/Microsoft/vsts-tasks/issues/3993
$sqlcmd = "C:\Program Files\Microsoft SQL Server\110\Tools\Binn";
Write-Host "##vso[task.setvariable variable=PATH;]${env:PATH};${sqlcmd}";
```

Tweak `$sqlcmd` as necessary.

**Comment by mvvsubbu** [comment]
We have fix ready, we are in the process of validation. We will update you as soon it is rolled out

**Comment by mvvsubbu** [comment]
Fix is rolled out to all the accounts. Now your task should work without having sqlcmd.exe in PATH. Please let me know if any one you still facing issue.
