### ISSUE TITLE
Run Function Test fail on DataSource

### ISSUE THREAD

**Issue by titans2016** [Microsoft/vsts-tasks#4003]
Hi.
We have a lot of tests based on codedUI c#.
We decided add Attribute DataSource to the one test.
The attribute DataSource is using library Microsoft.VisualStudio.TestTools.DataSource.TestCase.
In local machine working like a charm.
I configured our tfs url and number of test case.

I've also created build definition, which should execute test on test agent.
But when this test executing, It fail build:

> The unit test adapter failed to connect to the data source or to read the data. For more information on troubleshooting this error, see "Troubleshooting Data-Driven Unit Tests" (http://go.microsoft.com/fwlink/?LinkId=62412) in the MSDN Library. Error details: Could not load file or assembly 'Microsoft.TeamFoundation.TestManagement.Controller, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

I've found similar issue [https://social.msdn.microsoft.com/Forums/en-US/04de8e74-c4dd-4691-a0b5-0a796ddb12a9/tfs-2015-vnext-release-definition-not-executing-datadriven-coded-ui-tests?forum=tfsbuild](url), but their advice didn't help.

Please fix it as soon as possible.
It's block our continuous testing pipeline!

**Comment by RanjanarMS** [comment]
This scenario is not supported as of now. Adding it to our backlog.

**Comment by RanjanarMS** [comment]
Added this to our backlog and closing the thread for now.

**Comment by MSTestAuto** [comment]
I'm experiencing the same issue and since most of our tests use the Test Case as the data source, it will really be holding us back. 

What's the status on this? Is there an item link you can add here so that we can follow the progress and status?

**Comment by nshr87** [comment]
Same here.
Locked on outdated MTM, xaml builds and 2013 agents till this issue will be fixed...

**Comment by MSTestAuto** [comment]
I contacted them and they said it should hopefully be fixed in 2-3 sprints. In the meantime, we're pushed to use the new vnext build because of our new feature that will fail the old xaml builds. We created a workaround with our tfs admin where he actually copies all the Test Case data/parameters to a separate sql server DB with each test case having its own table (updated automatically with the Test Case changes), and we just set the TestMethods to that SQL data source.

**Comment by PBoraMSFT** [comment]
@MSTestAuto @nshr12 - this is being picked up for execution this sprint. We expect this to be available on VSTS in 2-3 sprints and on TFS on-prem in the next available update cycle.

**Comment by arienjan** [comment]
Hi, 
Is this issue now fixed in the team foundation server 2017 update 3 release?

**Comment by PBoraMSFT** [comment]
@arienjan - this will get deployed to VSTS with the Sprint 127 deployment (for reference: Sprint 126 deployment started earlier this week). This will make it to on-premises TFS with the next update for TFS 2018.
