### ISSUE TITLE
Using ##vso[task.setprogress value=x] on Releases

### ISSUE THREAD

**Issue by GreyMana-git** [Microsoft/vsts-tasks#4006]
Does ##vso[task.setprogress value=x] work on Release or is it a Build only? Using it while building correctly shows the percentage behind the current step (but does not show the current task)

While running a Release the set.progress percentage won't be shown anywhere but is omitted in the console output window, so it seems to be recognized somehow.

Steps to reproduce:
- Have a build with an artifact
- Create new empty Release Definition
- Add PowerShell Task and switch to "Inline"
- Add following Code to inline input:
Write-Host "Hello World!"
for ($i = 0; $i -le 100; $i += 10)
{
    Write-Host ([string]::Format("##vso[task.setprogress value={0};]Deploy {1}", [int] $i, "MySolution"))
    Write-Host ([string]::Format("Task: {1} / Perc: {0}", [int] $i, "MySolution"))
    Start-Sleep -Seconds 1
}

- Queue new Release

Tested with Hosted and private Agent, both don't show the progress.

**Comment by bryanmacfarlane** [comment]
It should work in either.  It's not specific to build or release.  RM should fix it.

**Comment by kasubram** [comment]
This if fixed.

**Comment by DynConcepts** [comment]
Just tested this with TFS-2017.....  Not Working In Releases!!!!!! (But is working in Build!!!!)

**Comment by kasubram** [comment]
Sorry, this fix didn't make it to TFS 2017. This is only available from TFS 2018.

**Comment by DynConcepts** [comment]
@kasubram - Thanks (FYI: Had that been explicitly stated that is was fixed **for VSTS** in the Aug 18th comment, it would have saved me at least 4 hours - and who knows how much time across the developer community)
