### ISSUE TITLE
[PowerShell Task] Tooltip wrong or functionality wrong

### ISSUE THREAD

**Issue by Gordon-Beeming** [Microsoft/vsts-tasks#401]
The PowerShell task tooltip for working folder says it defaults to where the script is located but seems to be defaulting to the root of where the code is checked out.

**Comment by bryanmacfarlane** [comment]
We had long discussions and we're going to update the tooltip to be correct for script compat.  Eric, please fix.

**Comment by bryanmacfarlane** [comment]
This is fixed in the rollout going now
