### ISSUE TITLE
Release tasks should use the accurate Azure product name

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/vsts-tasks#4010]
These tasks refer to an "Azure **WebApp**".  The [official product name](https://azure.microsoft.com/en-us/services/app-service/web/) is "Azure **Web App**".

- AzureAppServiceManage
- IISWebAppDeploymentOnMachineGroup
- IISWebAppManagementOnMachineGroup

**Comment by mvvsubbu** [comment]
Fixed
