### ISSUE TITLE
WindowsMachineFileCopy local deployment

### ISSUE THREAD

**Issue by ygeelen-tb** [Microsoft/vsts-tasks#4014]
We install VSTS agents directly on application servers to deploy on the same machine.
According to the help tooltips it would be possible to use local paths like F:\Websites\www.example.com\ but this is throwing errors.
Also in the case of a local path I'd like the task to simply use robocopy without using WinRM or the net use command.

That way we don't need to make Shared Folders, set special permissions and we no longer run into concurrency issues when doing multiple deployments (net use can only connect once).

What do you think?

**Comment by kmkumaran** [comment]
Would Copy Files Task be useful for your need?

**Comment by ygeelen-tb** [comment]
Kind of, but that task offers only a small subset of the features of WindowsMachineFileCopy.
I would prefer a WindowsMachineFileCopy task which can handle both scenarios (local+remote deployment). Perhaps you could introduce a radiobuttonlist to choose between them?
Your robocopy logic can be shared codewise for both cases.

**Comment by RoopeshNair** [comment]
@ygeelen-tb  [user voice ](https://visualstudio.uservoice.com/forums/330519-team-services/category/145269-release-management) is a typically a better place for feature requests

**Comment by ygeelen-tb** [comment]
That's for VSTS in general though, but I created an item:
https://visualstudio.uservoice.com/forums/330519-team-services/suggestions/18965380-windowsmachinefilecopy-local-deployment

**Comment by ygeelen-tb** [comment]
@kmkumaran Will this be implemented?

**Comment by RoopeshNair** [comment]
@ygeelen-tb  - we are currently focussed on issues that affect broader set of customers, We know this issue is important for your, we will continue to monitor the user [voice item](https://visualstudio.uservoice.com/forums/330519-team-services/suggestions/18965380-windowsmachinefilecopy-local-deployment). Closing the issue as duplicate
