### ISSUE TITLE
Add WIX to the VS2017 agent

### ISSUE THREAD

**Issue by janpieterz** [Microsoft/vsts-tasks#4026]
I'd like to request adding WIX to the VS2017 hosted agent.

I moved to the VS2017 hosted agent, and found out when wanting to start building the installers there too, that WIX wasn't installed (yet).

Also, looking around a bit here, I saw for example on https://github.com/Microsoft/vsts-tasks/issues/3971 and on other posts that there are a lot of changes being made continuously to the hosting agents. Are these logged somewhere so there's some insight in what's upcoming? Not sure how difficult it would be to update for example https://www.visualstudio.com/en-us/docs/build/concepts/agents/hosted#software-on-the-hosted-build-server to show an 'upcomming' or a changelog or something alike, or have a .md/umbrella issue in here with the current status + the changes being rolled out / worked on?

**Comment by ericsciple** [comment]
An image update is currently rolling out and should finish today. It will have WIX 3.10.

I don't think there is a place to view upcoming changes. I'll fwd this feedback along to appropriate folks.
