### ISSUE TITLE
Add SQL Server Data Tools to VS2017 Hosted Agent

### ISSUE THREAD

**Issue by marcwmiller** [Microsoft/vsts-tasks#4028]
Please add SQL Server Data Tools to the VS2017 Hosted agent to allow database CI/CD builds for Visual Studio 2017 projects targeting that hosted agent.

Thank you.

**Comment by pavanadepu2** [comment]
@marcwmiller, thanks much for reporting issue.
Let me check with Hosted Agent team and get back to you on this issue.

**Comment by pavanadepu2** [comment]
@marcwmiller, could you please let me know which project type you are trying to build. Also, it would be great if you can explain your scenario in detail.

**Comment by andygjp** [comment]
Hi @pavanadepu2 ,

In my case I have upgraded the project files of a VS2015 solution to the new csproj format. The solution also includes a SSDT project which is built and the output of this is deployed in a subsequent release. I'd hoped that I would just be able to change the agent to the VS2017 one, but the build fails. To get around this I've had to break the build in two: first the assemblies are built on the VS2017 agent and then I have a step that triggers the a separate build of the SSDT project on the VS2015 agent. The release is triggered when the VS2015 build is done and it pulls in the artefacts of the two builds. This is not ideal, but it works.

I'd like to have a single build definition as my total build time has gone up and I only get 240 mins a month.

Cheers,
Andy

**Comment by marcwmiller** [comment]
@pavanadepu2, I have a VS2017 solution with VS2017 projects (ASP.NET Core 1.1 Web applications and class libraries), along with a SQL Server Database Project. I want to build / deploy my database using the SSDT project as documented here [https://www.visualstudio.com/en-us/docs/build/apps/aspnet/ci/build-aspnet-dacpac](url).

In order to build my VS2017 solution, I have to use the VS2017 Hosted agent, but it does not have SSDT installed, which prevents me from building my SQL Server Database project in the VS2017 solution.

This scenario works fine if the solution / projects are in VS2015, where I can use the Hosted agent that has SSDT installed. That tooling allows the SQL Server database project to build and produce the dacpac file.

@andygjp, I too implemented two builds as a work around. One build using the VS2017 Hosted agent for the .NET Core VS2017 projects the other using the "standard" Hosted agent for the SQL Server Database project. As you indicated, this really isn't an acceptable solution. Since build chaining is not supported, there is no way to establish a dependency between the two builds. There is potential for one of the builds to break, and have a Release automatically triggered if the build it is dependent upon is successful. Now you have a broken deployment.

As an early adopter of .NET Core / VS2017 solutions, I do get frustrated when the tooling lags the push for the vNext IDE - especially things like Code Coverage and VSTS hosted Build & Releases.

**Comment by marcwmiller** [comment]
Hosted VS2017 now has SQL Server Data Tools "Extras", which solves issue.

**Comment by OrestTkachuk** [comment]
Could you please provide path to SQL Server Data Tools? I've tried following configuration for SqlPackage capability:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC
C:\Program Files (x86)\Microsoft SQL Server\130\DAC\bin

Build fails with error message: "Unable to find the location of Dac Framework (SqlPackage.exe) from registry on machine TASKAGENT9-0001".
