### ISSUE TITLE
Task should provide inline script

### ISSUE THREAD

**Issue by sdib** [Microsoft/vsts-tasks#4035]
Hi, 

I'd like to be able to run an inline powershell script (defined in my Release) on target machine.
Is there a way to do this ? 

Regards,
Simon

**Comment by ericsciple** [comment]
@sdib the powershell script task has an option for inline

**Comment by sdib** [comment]
@ericsciple sorry I'm using the "Powershell On Target Machine" task and I don't have this option

**Comment by ericsciple** [comment]
@kmkumaran fyi - although we typically dont track feature requests here so i would expect the issue to be closed soon. [user voice](https://visualstudio.uservoice.com/forums/330519-team-services) is a typically a better place for feature requests

**Comment by RoopeshNair** [comment]
Thank you for your feedback. Now we have added the support for inline scritp in the latest version 3.* (preview), 

![image](https://user-images.githubusercontent.com/1370480/46869447-7bd08e00-ce49-11e8-8fa3-4e284fca241a.png)
