### ISSUE TITLE
VSTS Queue Jenkins build throws 500 error

### ISSUE THREAD

**Issue by karann-jain** [Microsoft/vsts-tasks#4044]
Hi,

I see this error for all CI build triggered from VSTS. But i dont see this error when i manually queue a build. Not sure what is the issue.

{
	"statusCode": 500,
	"body": "java.lang.NullPointerException\n\tat hudson.plugins.git.RevisionParameterAction.shouldSchedule(RevisionParameterAction.java:182)\n\tat hudson.model.Queue.scheduleInternal(Queue.java:615)\n\tat hudson.model.Queue.schedule2(Queue.java:585)\n\tat hudson.model.Queue.schedule2(Queue.java:705)\n\tat hudson.plugins.tfs.model.BuildCommand.innerPerform(BuildCommand.java:93)\n\tat hudson.plugins.tfs.model.BuildCommand.perform(BuildCommand.java:203)\n\tat hudson.plugins.tfs.TeamBuildEndpoint.innerDispatch(TeamBuildEndpoint.java:311)\n\tat hudson.plugins.tfs.TeamBuildEndpoint.dispatch(TeamBuildEndpoint.java:166)\n\tat hudson.plugins.tfs.TeamBuildEndpoint.doBuild(TeamBuildEndpoint.java:328)\n\tat java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)\n\tat org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)\n\tat org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)\n\tat org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)\n\tat org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)\n\tat org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)\n\tat org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)\n\tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)\n\tat org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:374)\n\tat org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)\n\tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:845)\n\tat org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)\n\tat org.kohsuke.stapler.Stapler.service(Stapler.java:238)\n\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)\n\tat hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:135)\n\tat org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:225)\n\tat hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)\n\tat io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)\n\tat hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)\n\tat jenkins.metrics.impl.MetricsFilter.doFilter(MetricsFilter.java:125)\n\tat hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)\n\tat hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:59)\n\tat hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)\n\tat hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:126)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:80)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)\n\tat hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)\n\tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\tat jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)\n\tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\tat org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)\n\tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\tat org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)\n\tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\tat org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)\n\tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\tat jenkins.security.BasicHeaderProcessor.success(BasicHeaderProcessor.java:140)\n\tat jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:82)\n\tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\tat org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)\n\tat hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)\n\tat hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)\n\tat hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)\n\tat hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:553)\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)\n\tat org.eclipse.jetty.server.Server.handle(Server.java:499)\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)\n\tat winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)\n\tat java.lang.Thread.run(Thread.java:745)\n",
	"headers": {
		"server": "nginx/1.11.8",
		"date": "Mon, 17 Apr 2017 06:58:03 GMT",
		"content-type": "text/plain;charset=UTF-8",
		"transfer-encoding": "chunked",
		"connection": "close",
		"x-content-type-options": "nosniff"
	},
	"request": {
		"uri": {
			"protocol": "https:",
			"slashes": true,
			"auth": null,
			"host": "jenkins-host",
			"port": 443,
			"hostname": "jenkins-host",
			"hash": null,
			"search": "?delay=0sec",
			"query": "delay=0sec",
			"pathname": "/jenkins/team-build/build/job-name",
			"path": "/jenkins/team-build/build/job-name?delay=0sec",
			"href": "https://jenkins-host/jenkins/team-build/build/job-name?delay=0sec"
		},
		"method": "POST",
		"headers": {
			"Jenkins-Crumb": "<crumb>",
			"content-type": "application/x-www-form-urlencoded",
			"content-length": 2249,
			"authorization": "Basic <token>"
		}
	}
}

**Comment by karann-jain** [comment]
I tried reproducing this issue, looks like this issue occurs even on manual triggers.

**Comment by jpricketMSFT** [comment]
@karann-jain - thanks for providing repro steps. We will take a look at this issue soon.

**Comment by kelliejos** [comment]
@karann-jain We have a new version of the plugin that we'd like you to try. It has a fix in it that may help with your build. Could you email me at kellie.jos at Microsoft.com and I'll send you the new plugin version.  Thanks.

**Comment by nonotest** [comment]
hello, this is still happening for me

**Comment by kelliejos** [comment]
@nonotest We recently released a new version of the tfs-plugin which contains the fix for this issue. Please try updating your tfs-plugin version to version 5.126.0. Thanks.

**Comment by madhurig** [comment]
Closing since we believe the latest version of the Jenkins tfs plugin has a fix. Please open a new issue if you see errors with the new version of the Jenkins tfs plugin.

Thanks,
Madhuri
