### ISSUE TITLE
AzureFileCopy - casing Blob Prefix 

### ISSUE THREAD

**Issue by euhm** [Microsoft/vsts-tasks#4080]
Hello,

when you define a Blob Prefix, the folder is created in lower case. Which took some to figure out why the package could not be found during my arm template deploy. The package URI is case sensitive.

As prefix I used 'Build.BuildNumber' (transformed to lowercase), which I also used as parameter for my arm template, which is default casing. Result is a 404 during deploy task when trying to download the package.

Workaround: I added a step to transform Build.BuildNumber to Build.BuildNumberLowerCase and used this variable as parameter.

May it'is better to keep the default casing? Or do I miss something?

Kind regards,

bob

**Comment by niadak** [comment]
@euhm We have fixed the issue. It should work fine now. Please feel free to reopen the issue it you are still facing it.
