### ISSUE TITLE
Nuget Packager not creating packages in the same folder of the csproj

### ISSUE THREAD

**Issue by ironicnet** [Microsoft/vsts-tasks#4097]
## Description
When building a NuGet Package and leaving the Package Folder empty, it doesn't build the package next to the csproj as it should.
## Steps to reproduce it:

- Create a Build definition with a Nuget Packager 
  -  Path to csproj or nuspec file(s) to pack: **\*.csproj
  - Package Folder: (empty)
  - Pack options		
  - Include referenced projects: not checked
  - Automatic package versioning: Off
  - Configuration:release
  -NuGet Arguments: -Symbols -Version $(Build.BuildNumber)

## Expected output:
As described by the info in the "Package Folder" field. 

> Folder where packages will be created. If empty, packages will be created alongside the csproj or nuspec file.

It should create the .nupkg next to the csproj. 

## Actual output:
It creates the nuget in the root of the working directory instead of being next to the csproj.

**Comment by alexmullans** [comment]
This should be fixed by #4397, which will place NuGet packages in the $(Build.ArtifactStagingDirectory) by default.
