### ISSUE TITLE
AzFileCopy tasks failing - looks like it's parsing the AZFileCopy directory incorrectly

### ISSUE THREAD

**Issue by goatmale** [Microsoft/vsts-tasks#4103]
Hello,
I am having an issue with my Azure File copy tasks. It looks like they are failing due to the fact that the directory of the build agent (under C:\Program Files\VSTS Build Agent\Tasks\AzureFileCopy\1.0.87) isn't being handled properly. I am using the latest version of a private build agent and the latest 3.8.0 version of the azure module. Builds worked previously, but they seem like the builds started to fail on 4/20. 

The only other notable thing is that I switched the Azure service setup from credential based storage to certificate based as a troubleshooting step. I rebooted the agent server as well.

Here is the gist of the error I get when debugging is on:
https://gist.github.com/goatmale/b0c94ef7da8fabac058320b49a7b9d45

Notably,
**2017-04-23T01:07:52.9461829Z ##[debug]   at Microsoft.VisualStudio.Services.DevTestLabs.Deployment.BuildUploadHandler.InternalDoUpload()\r\nLogs:\r\n
2017-04-23T01:07:52.9481825Z ##[debug][2017/04/22 20:07:42][ERROR] The syntax of the command is incorrect. Error parsing the argument "Files\VSTS": parameter name is required.
2017-04-23T01:07:52.9541830Z ##[debug][2017/04/22 20:07:47][ERROR] The syntax of the command is incorrect. Error parsing the argument "Files\VSTS": parameter name is required.
2017-04-23T01:07:52.9601835Z ##[debug][2017/04/22 20:07:52][ERROR] The syntax of the command is incorrect. Error parsing the argument "Files\VSTS": parameter name is required.**

**Comment by goatmale** [comment]
Just a small update, after re-reading the instructions, I saw that I should be on version 1.3.2 of the azure powershell module. I downgraded, rebooted, and now i'm still getting that same error.

**Comment by goatmale** [comment]
Just an update, I renamed the folder **"C:\Program Files\VSTS Build Agent\tasks\AzureFileCopy\1.0.87"** to **"C:\Program Files\VSTS Build Agent\tasks\AzureFileCopy\1.0.89"** on the build agent as a temporary workaround and my builds are working again. This is a pretty hacky workaround because I don't know the proper way to do this. I see in the readme.md that there is a section for "working with older versions" but in clicking the link I can't find any information on doing so.
Thanks,

**Comment by pavanadepu2** [comment]
@goatmale, from the error it seems the problem is with having spaces in the agent folder name path.
Can you try placing an agent in a folder whose path contains no spaces such as "C:\VSTSBuildAgent".

**Comment by blarsonrp** [comment]
I do not know how to change the agent folder. It seems like spaces should be supported in build agents. Again, the version 1.0.87 worked fine.

**Comment by mvvsubbu** [comment]
We are going to address this issue, for the time being to unblock your self you can have agents bit under a folder with no spaces in it.  We will update once the spaces issue is being addressed.

**Comment by goatmale** [comment]
Can you provide instructions on how to do that?
Thanks!

**Comment by mvvsubbu** [comment]
You can refer this link for details https://github.com/Microsoft/vsts-agent/blob/master/README.md

**Comment by mvvsubbu** [comment]
Are you able to configure your agent with different working directory?

**Comment by blarsonrp** [comment]
No – I have been just renaming the old build agent folder to the new version name to use the old version still. Do you have an ETA on when this could be fixed?

**Comment by mvvsubbu** [comment]
@kmkumaran to comment on ETA

**Comment by vincentdass** [comment]
The issue is fixed and the fix will be available in upcoming deployment.

**Comment by aghattam** [comment]
I'm trying to copy the files from Shared folder into Azure blob from Azure storage Azcopy .I'm getting the follow error.
[ERROR] The syntax of the command is incorrect. Error parsing the argument "Source:\\siebelprodshare\SiebelPROD_xfer\Xogistics\Inbound\Returns": parameter name is required.

Script am using.
AzCopy.exe /Source:\\share\xfer\data\Inbound\Returns /Dest:https://blobqa.blob.core.windows.net/spark/hive/warehouse/snap/ DestKey:"2seytLvnhrJ8wFyKauKb75SvbzVghrXlhX6snGeTIKP/XaO4gzdJ1JSYysDwWIQEGyO68dElo3RHoQq=="

Any help is greately appricated..

**Comment by aghattam** [comment]
trying to copy the flat files.
