### ISSUE TITLE
AzureFileCopy fails when copying artifact build to premium storage VM

### ISSUE THREAD

**Issue by aliew** [Microsoft/vsts-tasks#4117]
Hi there,

I have created a release from VSTS to an Azure VM (non-classic) that has a running website on IIS. I am testing this one single task in my release definition that is AzureFileCopy. I am trying to copy my build artifact containing the [web deploy package].zip to the destination location within my Azure VM. This is my single objective that is to use AzureFileCopy to copy my build artifacts to the destination location on my Azure VM (target machine)

Here is my current setup. My Azure VM (that is the target machine) has been readily setup with the following:

1. WinRM listeners setup with HTTPs on the target machine. This was done by running the ConfigureWinRM.ps1 FQDN/IP address https command.
2. New self signed certificate has been installed on the target machine.
3. Enabled File and Printer sharing via netsh advfirewall firewall set rule group="File and Printer Sharing" new enable=yes on the target machine.
4. Verifed that I can connect to the target machine by running the command below:
$hostName="<DNS_NAME>" # example: "mywindowsvm.westus.cloudapp.azure.com"
$winrmPort = "5986"

# Get the credentials of the machine
$cred = Get-Credential

# Connect to the machine
$soptions = New-PSSessionOption -SkipCACheck
Enter-PSSession -ComputerName $hostName -Port $winrmPort -Credential $cred -SessionOption $soptions -UseSSL

One note, my VSTS subscription is a separate subscription from the target machine subscription. The VSTS subscription has currently been added as a Global Administrator user to the general subscription that owns the target machine. In short, VSTS and the target machine is not under the same owner. However, as a global administrator, I am able to setup the appropriate Azure Resource Manager endpoint for my VSTS account to communicate with the target machine.

After having filled in the necessary fields for the AzureFileCopy task whilst setting my System.Debug variable to true, I have obtained the exception below.
2017-04-25T00:53:19.7309652Z ##[debug]\nRetrying to upload.\nFailed to upload files to Azure Storage. Detailed error:\r\nSystem.Exception: [2017/04/25 00:53:07][ERROR] [OrganisationName].[ProjectName].WebApplication.SetParameters.xml: File size 330 bytes is invalid for PageBlob, must be a multiple of 512 bytes.

I am currently using a storage account that is of the Premium storage level. I have seen this issue stated here at this link https://github.com/Microsoft/vsts-tasks/issues/3499 which mentions a limitation of the AzureFileCopy task to support Premium storage accounts.

Is there a workaround to the above? I am in dire need of help from the community to solve this issue with the AzureFileCopy task.

@RoopeshNair 
@satender2017
@bryanmacfarlane 

Your inputs will be much valued.

Regards,
Adrian

**Comment by RoopeshNair** [comment]
@aliew -Adrian, premium storage accounts do not support uploading files with sizes that are not in multiples of 512 bytes. They are used to store persistent, unmanaged disks for VMs. Premium storage account is not intended to be used to store tiny blobs.

You may verify this by uploading the file to the Azure Premium storage directly.

**Comment by aliew** [comment]
@RoopeshNair - Is there a workaround for this? Or do you recommend migrating from Premium to Standard? What is the best suggestion here?

I am only performing a very simple operation to copy a build artifact containing a web deploy package to the target machine.

Regards,
Adrian

**Comment by satender2017** [comment]
@aliew -I have the same objective and also faces the exactly same issue. AzureFileCopy task wont work with premium storage account for sure as premium storage account has that size limitation(allows only multiple of 512 bytes) and it is not handle in AzureFileCopy task.

Even I am looking for some workaround for this.
@RoopeshNair -It will be great if you can provide any workaround for this scenario.

Here only option is left with us is to use Standard one rather than premium storage account.

**Comment by katatohuk** [comment]
Guys, I have the same issue but with Standard storage account, anyone has the same?
