### ISSUE TITLE
NuGet Publisher fails with "Incorrect relative path"

### ISSUE THREAD

**Issue by cswing** [Microsoft/vsts-tasks#4118]
The default NuGet Publisher task fails with the following message:  
`##[error]Incorrect relative path '**/*.nupkg;-:**/packages/**/*.nupkg;-:**/*.symbols.nupkg' specified.`

I believe there is an underlying issue with Find-Files because I was getting the same error with the Nuget Packager task. When using the example path in the tooltip `**\*.csproj;-:**\*.Tests.csproj`, the same error is logged.

Steps to reproduce
- Create a VS build with the default tasks, including a NuGet Publisher task.
- Execute the build.
- Build fails the error message.

**Comment by alexmullans** [comment]
Thanks for reporting. I'll add this to our list of issues to validate as we rebuild the packager and publisher tasks.

**Comment by alexmullans** [comment]
This is fixed by #4397.
