### ISSUE TITLE
.webtest test result publication

### ISSUE THREAD

**Issue by miles1302** [Microsoft/vsts-tasks#4120]
Hello,

I'm having warning messages following the run of a bunch of webtests using the command line tool mstest.exe
Could someone explain why I'm having this ? the IN and OUT folders are correctly created on the server but I guess that the publish result task cannot access or read what is in those folders...
![image](https://cloud.githubusercontent.com/assets/28003879/25383764/bda69a90-29bd-11e7-8550-30e91762ce72.png)

thanks for you help

Kind regards,

**Comment by prawalagarwal** [comment]
Hi @miles1302 ,

Do you see the results updated on your build page for this test result file? This error shows up in 2 cases:

1) First, if the size of the test result file is greater than 100mb. In this case, you should still see the updated results on the summary page against the run.

2) Second, when the agent does not find the file in the specified path. Please confirm that the test result file is present on the path published by the error code above. 

Let us know your findings.

**Comment by prawalagarwal** [comment]
@miles1302 Any updates here?

**Comment by miles1302** [comment]
Dear @prawalagarwal thank you for your reply.
I resolved the initial issue because the path to the result file was not correct.
I am now looking to do a powershell script in order to mass publish many TRX files in our VSTS project. I want to give each TRX file a different run title and merge them all so that they appeart neatly in VSTS. Unfortunatly I am now having an issue in naming the build under the project for which I want to publish the results
I am using the following command
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\MSTest.exe
/publish:https://bla-bla-bla.visualstudio.com
/PublishResultsFile:D:\Work\WebTestsResults\resultFile.trx
/teamproject:Testing
/publishbuild:'build id in VSTS'
/flavor:Release
/runtitle:Test1
/platform:AnyCPU

I have the following error message
Build 20170511.7 cannot be found under team project "Testing".

Any suggestions ?

Thx

**Comment by miles1302** [comment]
Dear @prawalagarwal
I found about the build uri issue I was having. I am know triying to publish the test result file using mstest command line directly into vsts in the release section.
it doesn't seem to be possible because the only switch available is /publishbuild .
Can I not use the release URI for this switch or is the another switch for Release that I have missed.

thanks for your help

**Comment by prawalagarwal** [comment]
Hi @miles1302 ,

Yes currently it is not possible to use mstest.exe to publish test results against a release. You can use the Publish Test Results task in your release flow in VSTS to publish your result files against a Release.

Since your original issue is resolved I am closing this thread. Please reach out to devops_tools[AT]microsoft[DOT]com if you have any other issues. Thanks
