### ISSUE TITLE
File uploaded using task.uploadfile is not included in log file zip.

### ISSUE THREAD

**Issue by mdkiefer** [Microsoft/vsts-tasks#4126]
I have a task that creates a log file and then uses the task.uploadfile to associated it with the build definition using an Inline Powershell script:
```
$filePath = (Join-Path $env:BUILD_STAGINGDIRECTORY "MyLogFile.log")
Set-Content -Path $filePath -Value @"
This is the log file text.
"@
Write-Host "Attempting to initiate upload of $filePath"
#NOTE:This doesn't fail, but I can't find the uploaded file anywhere from the build summary, including from the downloaded logs zip file.
Write-Host "##vso[task.uploadfile]$filePath"
```

It seems to be working successfully per the debug log below:
```
2017-04-25T20:43:20.1803908Z Attempting to initiate upload of G:\tfs\Agent01\_work\20\a\MyLogFile.log
2017-04-25T20:43:20.1803908Z ##[debug]Processed: ##vso[task.uploadfile]G:\tfs\Agent01\_work\20\a\MyLogFile.log
2017-04-25T20:43:20.2115910Z ##[section]Finishing: task.uploadfile
```

However, the "MyLogFile.log" is NOT included in the zip file when I click "Download all logs as zip". We are using TFS 2017. 

AGENT_VERSION is 2.105.7

**_Any ideas WHY the file isn't available?_**

**Comment by ericsciple** [comment]
Sorry I didn't see this issue sooner. This was a server side bug and I merged a fix into master on 1/3/2017 (commit 1a32c720: Merged PR 172808: Fix build logs zip to contain task.uploadfile attachments).

I checked the release branch, and it looks like the fixed landed in on-premises TFS with TFS 2017 Update 1.

**Comment by bootrider** [comment]
Still happening on TFS 2018 Update 3.1

**Comment by bootrider** [comment]
It happens if the file does not have .log extension
