### ISSUE TITLE
Need ability to parameterize Service Fabric endpoint

### ISSUE THREAD

**Issue by alextolp** [Microsoft/vsts-tasks#4128]
Need ability to parameterize the cluster endpoint in VSTS, e.g. -

![sfe](https://cloud.githubusercontent.com/assets/12418633/25412911/20573b50-29db-11e7-99a6-8977c5145a55.jpg)
Service Fabric endpoint

**Comment by bishal-pdMSFT** [comment]
@alextolp what parameters can you possible use in this dialog? This dialog is not in context of a release or build and hence you wan't be able to use release/build variables.

**Comment by sachinma** [comment]
@GitHubSriramB Do you think this is valid enhancement request for service endpoints?

**Comment by GitHubSriramB** [comment]
Endpoint URL cannot have parameters. 

If the intent is to create a single endpoint that points to different clusters then this scenario is not supported. We need three different endpoints to access the three different clusters (although the credentials to access them is the same).

**Comment by MikkelHegn** [comment]
@sachinma @GitHubSriramB 
I have two proposals for this:
1. Add the ability to use parameters in endpoints
2. Add the ability to all tasks using endpoints, to override specific parts of the endpoint configuration.

What's the possibility of doing 1? As we would then not have to change all tasks using these endpoints?

**Comment by GitHubSriramB** [comment]
Reopening issue until we have a closure on approach to take.

@MikkelHegn - could you pl. clarify the scenario where you want to create endpoint with parameters and when these parameters will be filled in?

**Comment by GitHubSriramB** [comment]
@MikkelHegn - Will sync up offline with you to add the scenario requirement to our backlog. Will close this issue for now.
