### ISSUE TITLE
XML variable substitution not working for configSections 

### ISSUE THREAD

**Issue by nirjashrestha** [Microsoft/vsts-tasks#4131]
The XML variable substitution is not working for configSections in web.config file. The sections 'value' does not update as per the Release definition variables.

**Comment by vincentdass** [comment]
@nirjashrestha , thanks for reporting this issue and the fix.
I shall fix this issue with my  other PR.
For a workaround, you can set up a private agent and modify the task as the fix will be available only in next deployment.

**Comment by arjgupta** [comment]
Hi @nirjashrestha . Can you please share the debug logs for the task. Also please share the web.config file that you are trying to apply the transformations on. You can send the files to RM_Customer_Queries@microsoft.com

**Comment by nirjashrestha** [comment]
@arjgupta @vincentdass Please could you provide an update on this issue. Have sent the log and web.config file.

**Comment by arjgupta** [comment]
@nirjashrestha , I am closing this issue based on our offline discussion. Your first issue was regarding xml variable substitution for setparameters file. This has been added to our back log. Your second query, was regarding how the xml variable substitution work in general. We are in process of writing blogs and help articles for the same, and the task will be updated with links to those accordingly

**Comment by Code4Kicks** [comment]
When will this be working?  I'm on 3.* and variable substitution is not working.  I've added variables to the environment definition but it never changes in the web.config file on release.  Please advise, thank you.

**Comment by DrEsteban** [comment]
We are also seeing this issue on task version 3.*, but with the appSettings section.  We are using the KeyVault task to download secrets and set build variables, and are expecting these build variables to be substituted in the Web Deploy process.  This isn't happening.

This worked for us just fine until this week.  Has there been a bad release of this task?
