### ISSUE TITLE
Question: How to upload custom logs as part of test execution?

### ISSUE THREAD

**Issue by NikolayKash** [Microsoft/vsts-tasks#4134]
Hello.  
During test run our app under test generates some logs, how can we attached these logs to test run automatically  by run test task and be available here 

![image](https://cloud.githubusercontent.com/assets/8295880/25419783/626c2abe-2a5d-11e7-85b9-3337e27fcdf5.png)

**Comment by cltshivash** [comment]
You can use the TestContext and do TestContext.AddResultFile or drop files to the results directory property https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.testtools.unittesting.testcontext.aspx

**Comment by NikolayKash** [comment]
Thanks a lot
