### ISSUE TITLE
Execution host waiting for a long time (queue not found)

### ISSUE THREAD

**Issue by ISAF87** [Microsoft/vsts-tasks#4139]
Environment: Windows 10
TFS: VS2015 CU3

When the run tests step starts it launched DTAExecutionhost.exe and then starts listening/waiting for a long time.

Two questions I have regarding this: comments in the config state the polling will exponentially increase. How does it get from 3->9->27->50? 
As 50 seconds seems like a long interval. 

What is it waiting for and is there anything we can do to speed up this process? As we have around 10 different users. this processes adds another half hour in total to the testrun, with just idling.

Log:
V, 5808, 1, 2017/04/25, 13:41:29.170, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [<tfs url>/_apis/test/Agents/52/Commands/0] (GET)0[test]
I, 5808, 1, 2017/04/25, 13:41:29.217, 143911608, DTAExecutionHost.exe, ********************************************************************
I, 5808, 1, 2017/04/25, 13:41:29.217, 143911881, DTAExecutionHost.exe, Main.InitializeAndStartExecutionHost. ExecutionHost has been started
Web method response: [<tfs url>/_apis/test/Agents/52/Commands/0] (GET)0[test] 56 ms
V, 5808, 10, 2017/04/25, 13:41:29.358, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 5808, 10, 2017/04/25, 13:41:29.358, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 5808, 10, 2017/04/25, 13:41:29.358, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 3000 milliseconds.
V, 5808, 5, 2017/04/25, 13:41:32.375, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [<tfs url>/_apis/test/Agents/52/Commands/0] (GET)0[test]
Web method response: [<tfs url>/_apis/test/Agents/52/Commands/0] (GET)0[test] 7 ms
V, 5808, 9, 2017/04/25, 13:41:32.375, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 5808, 9, 2017/04/25, 13:41:32.375, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 5808, 9, 2017/04/25, 13:41:32.375, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 9000 milliseconds.
V, 5808, 11, 2017/04/25, 13:41:41.390, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [<tfs url>/_apis/test/Agents/52/Commands/0] (GET)0[test]
Web method response: [<tfs url>/_apis/test/Agents/52/Commands/0] (GET)0[test] 15 ms
V, 5808, 10, 2017/04/25, 13:41:41.406, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 5808, 10, 2017/04/25, 13:41:41.406, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 5808, 10, 2017/04/25, 13:41:41.406, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 27000 milliseconds.
V, 5808, 12, 2017/04/25, 13:42:08.414, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [<tfs url>/_apis/test/Agents/52/Commands/0] (GET)0[test]
Web method response: [<tfs url>/_apis/test/Agents/52/Commands/0] (GET)0[test] 12 ms
V, 5808, 10, 2017/04/25, 13:42:08.414, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 5808, 10, 2017/04/25, 13:42:08.414, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 5808, 10, 2017/04/25, 13:42:08.414, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 50000 milliseconds.
V, 5808, 13, 2017/04/25, 13:42:58.429, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [<tfs url>/_apis/test/Agents/52/Commands/0] (GET)0[test]
Web method response: [<tfs url>/_apis/test/Agents/52/Commands/0] (GET)0[test] 8 ms
V, 5808, 15, 2017/04/25, 13:42:58.429, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 5808, 15, 2017/04/25, 13:42:58.429, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 5808, 15, 2017/04/25, 13:42:58.429, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 50000 milliseconds.
V, 5808, 14, 2017/04/25, 13:43:48.450, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [<tfs url>/_apis/test/Agents/52/Commands/0] (GET)0[test]
Web method response: [<tfs url>/_apis/test/Agents/52/Commands/0] (GET)0[test] 7 ms
V, 5808, 15, 2017/04/25, 13:43:48.450, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 5808, 15, 2017/04/25, 13:43:48.450, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 5808, 15, 2017/04/25, 13:43:48.450, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 50000 milliseconds.
V, 5808, 16, 2017/04/25, 13:44:38.469, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [<tfs url>/_apis/test/Agents/52/Commands/0] (GET)0[test]
Web method response: [<tfs url>/_apis/test/Agents/52/Commands/0] (GET)0[test] 15 ms
V, 5808, 15, 2017/04/25, 13:44:38.485, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
V, 5808, 15, 2017/04/25, 13:44:38.485, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [<tfs url>/_apis/test/Agents/52/Commands/1] (GET)1[test]
I, 5808, 18, 2017/04/25, 13:44:38.485, <machinename>\DTAExecutionHost, ExecutionTaskStateModel.RunStateTransitionsAsync : Handle transition between states
I, 5808, 18, 2017/04/25, 13:44:38.485, <machinename>\DTAExecutionHost, ExecutionTaskStateModel.Initialize : Initializing the execution host.

**Comment by cltshivash** [comment]
Thanks for the feedback. Do you have any other task between the Visual Studio Test Agent Deployment task and the Run Functional Tests task ? The execution host is looking for commands that would be assigned once the run functional tasks creates the test run and execution workflow starts.

**Comment by ISAF87** [comment]
No, Run Functional Tests is started right after the Test Agent deployment task.

**Comment by Koritsune** [comment]
Hello, I have this same issue, on and off. It will often work for a long time then stop working for a few days and the logs show the following error in the DTAExecution log:

Web method running: [/_apis/test/Agents/1396/Commands/0] (GET)0[test]
Web method response: [/_apis/test/Agents/1396/Commands/0] (GET)0[test] 12 ms
DTAExecutionHost.exe Information: 0 : TestExecutionServiceCommandQueueListener:DispatchAsync Command Microsoft.TeamFoundation.Test.WebApi.TestExecutionServiceCommand received.
    DateTime=2018-09-19T17:18:00.3703415Z
DTAExecutionHost.exe Information: 0 : TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
    DateTime=2018-09-19T17:18:00.3703415Z
DTAExecutionHost.exe Information: 0 : TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 27000 milliseconds.
    DateTime=2018-09-19T17:18:00.3703415Z
DTAExecutionHost.exe Information: 0 : TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent 1396
    DateTime=2018-09-19T17:18:27.4015221Z

Ideally I'd like to not have this issue occur at all. It continuously is checking, usually it successfully starts tests under 2 minutes but now it runs for 30 minutes and continuously displays that section in the logs.

**Comment by SinghHemant86** [comment]
Hello,
I am also facing the same issue, whats the potential solution for this as I don't have so many days to wait.

Thanks in advance.

**Comment by cltshivash** [comment]
@SinghHemant86 Please use the VSTest task. RFT task is deprecated.
