### ISSUE TITLE
Security exceptions during cleanup after test run

### ISSUE THREAD

**Issue by ISAF87** [Microsoft/vsts-tasks#4144]
Client: Window 10
TFS: TFS2015 CU3

At the end of the Run functional Test step, a cleanup it done and the script attempts to clean up all kinds of registry settings. Yet they seem to fail. But it does not fail the Run Functional test step.

Which permissions are required to get this working?
If we run the steps again, could this cause any issues? As our steps look like:

prepare agent (user 1)
run tests
prepare agent (user 2)
run tests
...
prepare agent (user 10)
run tests

Log:
V, 5808, 21, 2017/04/25, 13:45:18.387, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
I, 5808, 21, 2017/04/25, 13:45:18.387, <machinename>\DTAExecutionHost, ExecutionTaskStateModel.ListenerCommandReceived : Requesting a stop on Stop command.
I, 5808, 21, 2017/04/25, 13:45:18.387, <machinename>\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Stop listening on Stop command.
I, 5808, 23, 2017/04/25, 13:45:18.387, <machinename>\DTAExecutionHost, ExecutionTaskStateModel.RunStateTransitionsAsync : The task was cancelled
W, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, ExecutionHost.DeleteStoredCredentials: Unable to delete stored credentials. Clear the credentials cache manually whenever possible.
I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removing agent setting RegisteredAgentIdOnTfs on agent machine
I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removing agent setting RegisteredAgentIdOnTfs on agent machine - 32 bit hive
W, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Exception: System.Security.SecurityException
	Message: Requested registry access is not allowed.
	Stack Trace:    at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Microsoft.VisualStudio.TestService.Common.RegistryHelper`1.RemoveSetting(RegistryKey registryHive, String settingName)
	BaseExceptionMessage: Requested registry access is not allowed.

I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removed agent setting RegisteredAgentIdOnTfs on agent machine - 32 bit hive
I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removing agent setting RegisteredAgentIdOnTfs on agent machine - 64 bit hive
W, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Exception: System.Security.SecurityException
	Message: Requested registry access is not allowed.
	Stack Trace:    at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Microsoft.VisualStudio.TestService.Common.RegistryHelper`1.RemoveSetting(RegistryKey registryHive, String settingName)
	BaseExceptionMessage: Requested registry access is not allowed.

I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removed agent setting RegisteredAgentIdOnTfs on agent machine - 64 bit hive
I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removing agent setting TfsUrl on agent machine
I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removing agent setting TfsUrl on agent machine - 32 bit hive
W, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Exception: System.Security.SecurityException
	Message: Requested registry access is not allowed.
	Stack Trace:    at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Microsoft.VisualStudio.TestService.Common.RegistryHelper`1.RemoveSetting(RegistryKey registryHive, String settingName)
	BaseExceptionMessage: Requested registry access is not allowed.

I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removed agent setting TfsUrl on agent machine - 32 bit hive
I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removing agent setting TfsUrl on agent machine - 64 bit hive
W, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Exception: System.Security.SecurityException
	Message: Requested registry access is not allowed.
	Stack Trace:    at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Microsoft.VisualStudio.TestService.Common.RegistryHelper`1.RemoveSetting(RegistryKey registryHive, String settingName)
	BaseExceptionMessage: Requested registry access is not allowed.

I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removed agent setting TfsUrl on agent machine - 64 bit hive
I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removing agent setting DtlEnvUrl on agent machine
I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removing agent setting DtlEnvUrl on agent machine - 32 bit hive
W, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Exception: System.Security.SecurityException
	Message: Requested registry access is not allowed.
	Stack Trace:    at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Microsoft.VisualStudio.TestService.Common.RegistryHelper`1.RemoveSetting(RegistryKey registryHive, String settingName)
	BaseExceptionMessage: Requested registry access is not allowed.

I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removed agent setting DtlEnvUrl on agent machine - 32 bit hive
I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removing agent setting DtlEnvUrl on agent machine - 64 bit hive
W, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Exception: System.Security.SecurityException
	Message: Requested registry access is not allowed.
	Stack Trace:    at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Microsoft.VisualStudio.TestService.Common.RegistryHelper`1.RemoveSetting(RegistryKey registryHive, String settingName)
	BaseExceptionMessage: Requested registry access is not allowed.

I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removed agent setting DtlEnvUrl on agent machine - 64 bit hive
I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removing agent setting DtlMachineName on agent machine
I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removing agent setting DtlMachineName on agent machine - 32 bit hive
W, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Exception: System.Security.SecurityException
	Message: Requested registry access is not allowed.
	Stack Trace:    at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Microsoft.VisualStudio.TestService.Common.RegistryHelper`1.RemoveSetting(RegistryKey registryHive, String settingName)
	BaseExceptionMessage: Requested registry access is not allowed.

I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removed agent setting DtlMachineName on agent machine - 32 bit hive
I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removing agent setting DtlMachineName on agent machine - 64 bit hive
W, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Exception: System.Security.SecurityException
	Message: Requested registry access is not allowed.
	Stack Trace:    at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
   at Microsoft.VisualStudio.TestService.Common.RegistryHelper`1.RemoveSetting(RegistryKey registryHive, String settingName)
	BaseExceptionMessage: Requested registry access is not allowed.

I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, Removed agent setting DtlMachineName on agent machine - 64 bit hive
I, 5808, 23, 2017/04/25, 13:45:18.403, <machinename>\DTAExecutionHost, ExecutionHost.UnregisterFromServer : Agent is unregistering from server.
Web method running: [<tfs url>/_apis/test/Agents/52] (DELETE)52[test]
Web method response: [<tfs url>/_apis/test/Agents/52] (DELETE)52[test] 14 ms

**Comment by cltshivash** [comment]
You shouldn't hit issues for the steps mentioned. The user provided in the agent configuration section could lack admin rights on the agent machine leading to the observed behavior.

**Comment by ISAF87** [comment]
Sounds like a design flaw to me. Can imagine you want to run your tests as a specific user, with stripped down permissions, eg: Not administrator.
