### ISSUE TITLE
Unable to upgrade Service Fabric application if application type exists

### ISSUE THREAD

**Issue by ChristianMes** [Microsoft/vsts-tasks#4153]
Using the vsts ServiceFabricDeploy task does not allow to instantiate an existing application type (with different configuration). This is an issue to create a ring deployment where an applicationType+Version is tested and instantiated into Beta/Production.
The "Publish-UpgradedServiceFabricApplication" PS script supports the action "Upgrade" but the vsts task only allows "RegisterAndUpgrade". 

The problem results naturally in an error
`Application type 'XXX' and version '1.0.0.2017.4.26.1' was already registered with the cluster, unregistering it...`
` ##[error]Application type and version is still in use`

**Comment by bishal-pdMSFT** [comment]
A new configuration means a new version of service and application. Hence, you should update the version and then try upgrade. For more details see [here](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-tutorial-powershell).
Can you please provide more details about your ring set-up. are you using same cluster for multiple rings?

**Comment by ChristianMes** [comment]
Hi @bishal-pdMSFT , thanks for coming back on my issue.
We need to run multiple different versions of the same application in parallel separated in "Rings". One mesh of services as the "Canary"-Ring one as "Beta" and finally the production mesh. We have gateway services as entry points dispatching to those rings based on defined ring affinity. 

We are first upgrading the canary ring, if it is running successfully the same application type and version needs to be instantiated again upgrading the beta ring. The same with production.

This all takes place in the same cluster hosting one version of the gateways-app and three versions of the microservices application for the business logic.

It is possible doing this using "manual" deployment (powershell...). But it would be very much possible using the vsts task if it would allow an "upgrade" only call to "Publish-UpgradedServiceFabricApplication" or check for existing of an application-type and still allows the upgrade in the instances.

I hope this describes the use case well enough.

**Comment by mikanyg** [comment]
Would it make sense to have the task support all variants of the powershell cmdlet parameter, e.g. Register, Upgrade and RegisterAndUpgrade?

**Comment by ChristianMes** [comment]
Yes, that would help us, since we know that the application type is already registered in our case. Ideally there would be an option to "register-if-not-existing" and upgrade.

**Comment by bishal-pdMSFT** [comment]
This looks like a valid requirement to me. @MikkelHegn, @RoopeshNair should we add support for upgrading without re-register?

**Comment by ChristianMes** [comment]
Any updates on the issue? Would you accept PRs?

**Comment by mikanyg** [comment]
Yes they do. I have made several PRs that have been accepted. 

I think it would be quite easy to expose the action as a new parameter in the task and just pass the value to the Publish-UpgradedServiceFabricApplication cmdlet, since it already supports the parameter.

**Comment by MikkelHegn** [comment]
Yes - please submit PRs - we don't have this high enough on our backlog to get to it anytime soon.

**Comment by MikkelHegn** [comment]
@ChristianMes - Just to make sure you are not blocked - You can use the Service Fabric PowerShell task from a release definition to manipulate anything in the cluster as part of your deployment. It let's you run any PowerShell command against the cluster.

**Comment by bishal-pdMSFT** [comment]
@ChristianMes do you have any plan to raise PR for this?

**Comment by apryiomka** [comment]
Hi, any update on this? I have exactly the same scenario. We deploy the (web) application package on one port for "testing in production" (think of it as staging slot for cloud services), something like application.cloudapp.azure.com:**123**. Once the testing was successful, we want to deploy the same build on different port - application.cloudapp.azure.com:**321** where **321** is the production port. We don't want to have to unprovision the application package that is running on port **123**, all we need is to upgrade the provisioned package to the new version for the production app instance. The current VSTS task tries to unprovision the existing package which is running on port **123**, but all we need is the upgrade of the port **321** application. How can we run upgrade only task if the package with the same version already exist?

**Comment by MikkelHegn** [comment]
@apryiomka - You're only option is to provide your own PowerShell script with that logic. The Service Fabric PowerShell task was created for scenarios like these as there can be many different ways you want to deploy the application. The SDK scripts are mainly there to support the Visual Studio experience, and the versions of these scripts we use in VSTS is a fork of what's in the SDK.
