### ISSUE TITLE
How to escape semicolons when overriding test run parameters in version 2.* preview

### ISSUE THREAD

**Issue by cwhiting17** [Microsoft/vsts-tasks#4156]
When attempting to use a Visual Studio Test task with a SQL Server connection string with semicolons in the variable to override the run settings file parameter with Version 2.* preview, the test always fails.  If the semicolons are not escaped with the forward slash as used with Version 1.* the RunSettings file is only replaced to the first space after the first semicolon in the connection string.  If the semicolons are escaped as required for Version 1.*, an error is thrown: **Format of the initialization string does not conform to specification**.  This seems to be a repeat of issue #2567.  How are semicolons in override variables to be handled?

**Comment by prawalagarwal** [comment]
Hi @cwhiting17,

Are you on TFS or VSTS? If TFS which release?

I tried reproducing the issue on TFS2017 and couldn't. Can you send a snapshot of how you are declaring your Override Test Run Parameters field? Thanks

**Comment by cwhiting17** [comment]
We are using VSTS.
[cid:image002.jpg@01D2C3D6.C9796700]

**Comment by prawalagarwal** [comment]
Hi @cwhiting17 , the image is not attached properly. Cannot download it from here. Can you reach out to us at devops_tools[AT]microsoft[DOT]com with the attachment? Thanks

**Comment by cwhiting17** [comment]
I tried to email the image to devops_tools@microsoft.com  and the email was rejected.

This is how the overrides are being done
-AppServer $(APPSERVER) 
-Port $(PORT) 
-SqlConnectionString $(SQLCONNECTIONSTRING)

**Comment by nigurr** [comment]
You can escape (`\`) the values like this `escaped\;string` => `escaped;string`

**Comment by HWouters** [comment]
In version 2 escape mechanism is still not working. This is what I get replaced in my runsettings:
<Parameter name="ConnectionString" value="Server=tcp:___.database.windows.net,1433\;Initial"/>
=>escape character is not removed and it breaks on the first space

If I don't put an escape character I get this:
<Parameter name="ConnectionString" value="Server=tcp:___.database.windows.net,1433;Initial"/>
=> Still breaks on the space from "Initial Catalog"

**Comment by nigurr** [comment]
@HWouters ah sorry for that. v2 does has the escape capability. Write the string in `"` quotes

![image](https://cloud.githubusercontent.com/assets/15208679/26623448/5cd00994-460b-11e7-9e6e-ef772d4d2e40.png)

**Comment by HWouters** [comment]
@nigurr thanks, that works!
