### ISSUE TITLE
Azure Resource Group Deployment Task - Allow wildcards in template location when using linked artifacts

### ISSUE THREAD

**Issue by duckwaffle** [Microsoft/vsts-tasks#4158]
Hi guys,

Currently when using the "Linked artifact" option in the ARM Template deploy task, the path to the template json file must be absolute, resulting in an error if you try to use pattern matching to find the json file.

It would be great if you could use wildcard folder/file matching that is available in almost every other task in this library, when trying to create build/release templates it is much easier to use pattern matching rather than variables for artifact folder name + relative path etc.

Obviously this wouldn't work with URL links, but since we have access to the filesystem for linked artifacts, I don't see any issue in allowing this sort of pattern matching, especially if the Azure App Service Deploy task can get away with it for finding a zip file.

Cheers,
Richard

**Comment by ds-ms** [comment]
@duckwaffle thank you for the feedback. We have made this update to the task (https://github.com/Microsoft/vsts-tasks/pull/4671); you'll be seeing it in production in the next three weeks. :)

**Comment by duckwaffle** [comment]
@ds-ms cool! Thanks for the update 👍
