### ISSUE TITLE
HockeyApp package upload timeout inside corporate proxy

### ISSUE THREAD

**Issue by fahms** [Microsoft/vsts-tasks#4161]
I am under the corporate proxy. When uploading the package to HockeyApp it fails. I have the proxy configured at the build agent machine level and able to access the hockeyApp api's.

Where should I configure the proxy for this task?

`2017-04-27T08:56:18.1861560Z ##[section]Starting: Deploy APK to HockeyApp
 
2017-04-27T08:56:18.2002300Z ==============================================================================
 
2017-04-27T08:56:18.2002480Z Task         : HockeyApp
 
2017-04-27T08:56:18.2002620Z Description  : Deploy your alpha and beta builds of mobile apps to HockeyApp
 
2017-04-27T08:56:18.2002750Z Version      : 1.115.0
 
2017-04-27T08:56:18.2002870Z Author       : Microsoft Corporation
 
2017-04-27T08:56:18.2003190Z Help         : 
 
2017-04-27T08:56:18.2003340Z ==============================================================================
 
2017-04-27T08:56:18.8605780Z ************************************ exists true
 
2017-04-27T08:57:33.9639750Z ##[error]Error: Failed to upload the package. Error: {"code":"ETIMEDOUT","errno":"ETIMEDOUT","syscall":"connect","address":"50.16.201.45","port":443}
 
2017-04-27T08:57:33.9853740Z ##[section]Finishing: Deploy APK to HockeyApp`

**Comment by DavidStaheli** [comment]
Hi @fahms, here are instructions for configuring the proxy used by the agent:
https://github.com/Microsoft/vsts-agent/blob/master/docs/start/proxyconfig.md

I'll close this issue for now, but please reopen it if you encounter any trouble.

**Comment by fahms** [comment]
Hi @DavidStaheli, I already tried the link.
I do not have an issue with the agent and server connection, it works fine and able to get the packages. It is when I try to upload the package to HockeyApp it times out. Which I am not sure is it because of proxy or some other settings.

**Comment by DavidStaheli** [comment]
Ah, sorry I misunderstood.  I suspect the HockeyApp extension is not properly using the proxy settings.  I'll look into that.

**Comment by lkillgore** [comment]
Hi @fahms, there are a few additional environment variables that affect the Hockey App.  The variables are described here:  https://www.npmjs.com/package/request#controlling-proxy-behaviour-using-environment-variables

HTTP_PROXY / http_proxy
HTTPS_PROXY / https_proxy
NO_PROXY / no_proxy

Please let me know if this works for you.

**Comment by fahms** [comment]
Hi @lkillgore, I have already tried https://jjasonclark.com/how-to-setup-node-behind-web-proxy/

**Comment by madhurig** [comment]
@fahms : The HockeyApp task uses the [request node module](https://github.com/request/request) that needs a different proxy configuration. Please try setting the HTTP_PROXY and HTTPS_PROXY on the build definition "Variables" tab. Let us know if that helps.

Thanks,
Madhuri

**Comment by madhurig** [comment]
I was able to repro the ECONNRESET with an authenticated proxy if the credentials are incorrect or not specified correctly. 

Please check your settings for HTTP_PROXY and HTTPS_PROXY environment variables.
HTTP_PROXY=http://username:password@proxyserver:port
HTTPS_PROXY= https://username:password@proxyserver:port

I found that putting username:password in quotes does not work. If there is an “@” or “:” in the password, it should be escaped e.g. %40 for “@”.

Thanks,
Madhuri

**Comment by madhurig** [comment]
This issue was also tracked via a DTS and is confirmed resolved, so closing.
