### ISSUE TITLE
Azure App Service Deploy v3 & Virtual Application

### ISSUE THREAD

**Issue by ichivers** [Microsoft/vsts-tasks#4163]
I changed an Azure App Service deploy task to v3, the release then failed on that step saying it couldn't find the virtual application.  I changed it back to a v1 and it worked ok.

I used the exact virtual directory from the Azure portal in the virtual application field 

/sitevists

**Comment by vincentdass** [comment]
@ichivers , thanks for reporting the issue.
Currently deploying to virtual directory is not supported in major version. Can you please enable **Application** option in `Virtual Application and directories`.
![image](https://cloud.githubusercontent.com/assets/20121508/25481127/673ccc44-2b69-11e7-9f2d-cdf88aba975e.png)
and remove leading '/' from virtual application name in your release definition.
![image](https://cloud.githubusercontent.com/assets/20121508/25481854/bcc6171c-2b6c-11e7-91d8-0db11f4ec848.png)

**Comment by ichivers** [comment]
It is an Application:

![image](https://cloud.githubusercontent.com/assets/5063940/25482296/14e38c1e-2b49-11e7-9f9b-eec5708a7de1.png)

![image](https://cloud.githubusercontent.com/assets/5063940/25482364/5dfcb45c-2b49-11e7-8592-7121eec4abf6.png)

2017-04-27T10:23:53.4522030Z ##[debug]Processing: ##vso[task.issue type=error;]Error: Virtual application doesn't exists : /sitevisits
2017-04-27T10:23:53.4522030Z ##[error]Error: Virtual application doesn't exists : /sitevisits
2017-04-27T10:23:53.4522030Z ##[debug]Processing: ##vso[task.complete result=Failed;]Error: Virtual application doesn't exists : /sitevisits

If I change it back to a v1 it works ok.

**Comment by vincentdass** [comment]
Thanks for the instant reply.

Can you please change the virtual application name as '**sitevisits**' from '**/sitevisits**'  (Remove the trailing `/`) only in Release definition ?
![image](https://cloud.githubusercontent.com/assets/20121508/25483580/135206b6-2b74-11e7-84e8-20e3c2f30305.png)

**Comment by vincentdass** [comment]
@ichivers , is the issue resolved ?

**Comment by ichivers** [comment]
Sorry not had a chance to try your suggestion yet. Should get to it later this week, today is a public holiday in the U.K.  

Regards,
Ian.

**Comment by michelkamp** [comment]
just tried it and it works. Just follow vincentdass answer .
The mistake i made was that i was in the dev slot and forgot to create the virtual directory + application ;-)

michel

**Comment by vincentdass** [comment]
@ichivers , is the issue resolved ?
We added supported for handling virtual application name prefixed with `/`, which will be available in a week or two. (**3.3.4** Task Version). 
You can try the workaround by removing the trailing `/` in your virtual application name (in Release Definition).

**Comment by ichivers** [comment]
Yes that resolves the issue. I noticed that it is case sensitive as well, is that intentional ?

Sorry about the delay, I had to setup a new environment to try the suggestion.

**Comment by vincentdass** [comment]
@ichivers ,Virtual Application name is not case sensitive. We will fix this in the upcoming version.
Thanks for reporting the issue. :)

**Comment by MatteoSp** [comment]
Same issue.

My app service settings:

![appservice](https://user-images.githubusercontent.com/206792/41414800-4f189f94-6fe7-11e8-9ec4-71debe4adcc7.PNG)

My task settings:

![deploytask](https://user-images.githubusercontent.com/206792/41414818-59d4b2d8-6fe7-11e8-8194-9a353c245737.PNG)

My task log (System.Debug was set to true):

[tasklog_9.log](https://github.com/Microsoft/vsts-tasks/files/2102506/tasklog_9.log)

**Comment by vincentdass** [comment]
@MatteoSp , can you ensure that you created virtual application in **staging** slot?
If the issue still exists, browse `https://resources.azure.com/subscriptions/f7904463-b451-4f2d-a0aa-ea800705e73b/resourceGroups/map-dev/providers/Microsoft.Web/sites/cd-public-map/slots/staging/config/web` and share the result to `RM_CUSTOMER_QUERIES AT MICROSOFT DOT COM`

**Comment by MatteoSp** [comment]
thanks, that solved the issue. I didn't get web applications needs to be created in slots too.

**Comment by ChrisProlls** [comment]
Just a question : is it normal that the root path is cleaned when an application is deployed on a virtual directory ?
I noticed this behavior on my pipeline recently ...
@vincentdass

**Comment by brettkc** [comment]
> Just a question : is it normal that the root path is cleaned when an application is deployed on a virtual directory ?
> I noticed this behavior on my pipeline recently ...
> @vincentdass

I am seeing this also. @ChrisProlls did you solve this?

**Comment by dotnetgik** [comment]
we are facing same issue with the task version 4
