### ISSUE TITLE
SQLPackage path detection

### ISSUE THREAD

**Issue by tomvo12** [Microsoft/vsts-tasks#4164]
Hi!

We face the following problem: on VS2017 Azure Base (image SKU VS-2017-Ent-WS2016) the SSDT package is pre-installed (path: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130). However, the registry keys that have been valid for older VS versions are obviously not present. Hence, the SqlDac deployment task does not find the executable on the build agent. This should probably be fixed so that the metioned azure image could be used as a build agent as was before with vs 2015.

**Comment by mvvsubbu** [comment]
There is a different issue for the same and hence closing this here, please track issue https://github.com/Microsoft/vsts-tasks/issues/4338 for updates
