### ISSUE TITLE
No documentation for Azure Powershell task

### ISSUE THREAD

**Issue by letmaik** [Microsoft/vsts-tasks#4165]
https://www.visualstudio.com/en-gb/docs/build/steps/deploy/azure-powershell
When I click on the referenced GitHub page I see just source code, no documentation, not even a README file. How is this helping the average user?

**Comment by rokmicrosoft** [comment]
Done. It is now redirecting to https://docs.microsoft.com/en-us/vsts/build-release/tasks/deploy/azurepowershellv3.3?view=vsts .
