### ISSUE TITLE
Shell Script task should support inline script

### ISSUE THREAD

**Issue by DavidStaheli** [Microsoft/vsts-tasks#4168]
Customers are requesting that the Shell Script task allow inline entry of script text, just like the PowerShell task allows.

**Comment by anthonychu** [comment]
@DavidStaheli Are you open to a community contribution on this?

**Comment by DavidStaheli** [comment]
Absolutely @anthonychu!

**Comment by bryanmacfarlane** [comment]
We have bigger feature work on our backlog where we inline the web editor (monaco) and put the inline contents in file service (blob) with a reference to it in the definition.  This will come with that.

We're tracking that work externally.

**Comment by DavidStaheli** [comment]
That sounds awesome!

**Comment by 0xced** [comment]
Any update about this?
