### ISSUE TITLE
.ipa not generated even though I have checked Create App Package

### ISSUE THREAD

**Issue by fahms** [Microsoft/vsts-tasks#4174]
I have all the configurations correctly set. The build is successful and able to see the .app and .dSYM files generated. However .ipa file is not generated even if Create App Package checked.
Using TFS 2015 update 4.
MacOS Sierra
Xcode 8+

From logs, I can see singing identity as - even though they are imported correctly in the logs above.
`2017-04-27T09:41:23.8480370Z Signing Identity:     "-"
2017-04-27T09:41:23.8482750Z 
2017-04-27T09:41:23.8486530Z     /usr/bin/codesign --force --sign - --keychain=/myagent/_work/9/s/_tasktmp.keychain --timestamp=none `

**Comment by madhurig** [comment]
@fahms: Can you provide the full build log? Do you see any errors in your build?

TFS 2015 does not have the latest Xcode task changes that were shipped to Team Services. But I  compiled the task and tested it against TFS 2015 Update 3. Please check the last response on this post and see if you can update the task on your TFS server: https://github.com/Microsoft/vsts-tasks/issues/3196 

Thanks,
Madhuri

**Comment by fahms** [comment]
@madhurig followed your comments in the link provided. However no luck. Also, I see the .app generated do not have provisioning profile embedded though it is able to detect the certificate and profile.

`Signing Identity:     "-"`

**Comment by madhurig** [comment]
Please attach or send (to madhurig at microsoft.com) your debug build logs from the updated task. 

Thanks,
Madhuri

**Comment by fahms** [comment]
@madhurig Thanks very much. Finally was able to configure this and manage to generate the IPA.
