### ISSUE TITLE
What is the Powershell++ task used for

### ISSUE THREAD

**Issue by Mardoxx** [Microsoft/vsts-tasks#4181]
What is the Powershell++ task used for. How does it differ from the normal Powershell task?

**Comment by bryanmacfarlane** [comment]
This repo tracks issues with these tasks:  https://github.com/Microsoft/vsts-tasks/tree/master/Tasks

Powershell++ is a custom task extension.  You'll have to ask them.

**Comment by Mardoxx** [comment]
It does the same as the normal powershell one provided by yourselves, so why have both?

Little redundant?
