### ISSUE TITLE
Tasks with gyp built dependencies

### ISSUE THREAD

**Issue by aloisdeniel** [Microsoft/vsts-tasks#4183]
I'm currently trying to write my own VSTS extension with its custom task. This task depends on [sharp](https://www.npmjs.com/package/sharp) that has to be build at `npm install` time through **gyp**. But the `node_modules` seem to have to be included into the `.vsix` before upload of the extension so I didn't find any solution for this (*maybe pre-compiling the module for all agent architectures and requiring the module thanks to the current agent executing architecture*) ...

**Comment by bryanmacfarlane** [comment]
please open on the vsts-task-lib repo and we'll discuss their (this covers tasks in this repo)
