### ISSUE TITLE
Azure App Service Deploy V3 - options missing

### ISSUE THREAD

**Issue by parcae** [Microsoft/vsts-tasks#4187]
I am using the V3 version of the App Service Deploy in several releases and I noticed that since last thursday or friday a lot of the options of the V3 template are missing.
Seems like the template is suddenly incomplete. Switching back to V2 brings back most of the options.

**Comment by pavanadepu2** [comment]
@parcae, thank you for reporting the issue. 

We have recently updated the task UI. In V3 template, first you need to select your web app name. Based on your web app selection, the other field will render dynamically.

**Comment by parcae** [comment]
When we are using variables, like "$(ApplicationPath)" the options are not displayed. I can work around it by selecting something from the dropdown first and then replace that with our variable.... but it doesn't feel logical...

**Comment by Geertvdc** [comment]
Agree with @parcae we use a lot of variables for our web app names (multiple steps same web app) so filling in the web app name is really annoying

**Comment by pavanadepu2** [comment]
@parcae , @Geertvdc I agree with you. Currently we are working on the solution. Thanks much for the feedback.

**Comment by carlwoodhouse** [comment]
also had to switch back to v2, the dropdowns never manage to populate for us (we have to type the names in manual for some reason) so can never get the additional options on v3!

**Comment by arjgupta** [comment]
@parcae , A fix for this issue has been deployed, if you type in the variable name the other options should populate. I am closing this issue. If you are still facing this issue, or want any clarification, please feel free to reopen

**Comment by Oddleif** [comment]
I am still having this issue. My issue though seems to be that the app service originally was created as an API App. So every time I choose that all the input fields dissapear for v3. v2 appears as expected though, except I really need the JSON variable substitution feature in v3...
