### ISSUE TITLE
Can't add tag for release definitions via logging commands.

### ISSUE THREAD

**Issue by andremarques023** [Microsoft/vsts-tasks#4189]
I have been using the option to add a tag for current build via logging command. At this moment there's no such functionality for release definitions (or at least not documented yet).

How can it be accomplished and used? Maybe through the REST API, but I can't find it neither. I think it would be great to have this implemented as a logging command.

**Comment by bryanmacfarlane** [comment]
This repo is for these tasks:  https://github.com/Microsoft/vsts-tasks/tree/master/Tasks

You'll need to follow up with RM team.  Perhaps in the vsts-agent repo (where logging commands are)
