### ISSUE TITLE
Unable to generate a .vsix file from the vsts-tasks archive

### ISSUE THREAD

**Issue by kittenpoop** [Microsoft/vsts-tasks#4190]
After fiddling around I finally figured out how to get the archive to build (npm run build). So that I can use a few tasks as example to create my own build-task.

I have a resulting '_build' folder with the tasks that are interesting by adapting the 'make-options.json' file.
But to my surprise no 'vss-extension.json' file anywhere to start packaging to a .vsix, also a target to create the .vsix file is also unfound.

So how do I create/generate the .vsix file from the sources?

**Comment by bryanmacfarlane** [comment]
You should ask this on the vsts-task-lib repo.

This repo is for tasks: https://github.com/Microsoft/vsts-tasks/tree/master/Tasks
