### ISSUE TITLE
Azure SQL Database Deployment Error after enabling SQL data sync

### ISSUE THREAD

**Issue by paonekumar** [Microsoft/vsts-tasks#4191]
After enabling Azure SQL Data sync, I am getting below warning while executing DACPAC and deployment if getting failed.  I want to Ignore these errors and continue with deployment.

**SQL72030: If this deployment is executed, changes to xxxxxx might introduce run-time errors in**

I tried adding /p:TreatTSqlWarningsAsErrors=False to Additional SqlPackage.exe Arguments under deployment package and it is failing with the below error. 

##[error]*** 'TreatTSqlWarningsAsErrors' is not a valid argument for the 'Publish' action.

**Comment by arjgupta** [comment]
Hi @paonekumar , you can refer to [this](https://msdn.microsoft.com/library/hh550080(vs.103).aspx#Anchor_2) link to see the parameters supported by the publish action

**Comment by paonekumar** [comment]
Thanks @arjgupta for your help. I was using a wrong Publish action.

**Comment by ananthaakumar** [comment]
@paonekumar i am facing the same issue. Can i know what publish action you used to resolve this.

**Comment by paonekumar** [comment]
@ananthaakumar I have used below publish action to Ignore verification errors and for not dropping objects not in source.
 /p:TreatVerificationErrorsAsWarnings=false /p:BlockOnPossibleDataLoss=False /p:DropObjectsNotInSource=False /p:DropConstraintsNotInSource=false /p:DropIndexesNotInSource=false /p:DropDmlTriggersNotInSource=false /p:ScriptDatabaseOptions=False

**Comment by ananthaakumar** [comment]
@paonekumar Thanks a lot. its working for me.

**Comment by jklaus** [comment]
@paonekumar - what did doing this do to datasync?  Does the underlying datasync schema update?  Are you having to maintain the associated triggers as well or are you just modifying the source table's columns?
