### ISSUE TITLE
Unable to Launch the Process from Process.Launch 

### ISSUE THREAD

**Issue by Jassi1313** [Microsoft/vsts-tasks#4200]
Hi,
I am running the Functional test using team services. and there is an exex file on my C drive but I am not able to launch the process using process.launch
though when the code was in TFS same function used to launch the process from exe.

**Comment by bryanmacfarlane** [comment]
This repo tracks issues with CI tasks ( https://github.com/Microsoft/vsts-tasks/tree/master/Tasks )
