### ISSUE TITLE
Xcode - failing build task.  "Select a development team in the project editor.  "

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/vsts-tasks#4216]
My build is failing on this.  However, I have a development team name set in the editor of both the project and the target.   I am not sure what else to try here?  

![screen shot 2017-05-03 at 8 34 43 pm](https://cloud.githubusercontent.com/assets/4327773/25687930/f9460df0-303f-11e7-964e-c65ac29c8f9c.png)

**=== BUILD TARGET Responder OF PROJECT Responder WITH THE DEFAULT CONFIGURATION (Release) ===
Check dependencies
Signing for "Responder" requires a development team. Select a development team in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.3'**
** BUILD FAILED **
The following build commands failed:
	Check dependencies
(1 failure)
Error: /usr/bin/xcodebuild failed with return code: 65

Any ideas.

**Comment by madhurig** [comment]
This seems like a project configuration issue. When building in Xcode, check if the scheme and configuration match “Release” and “Responder”. You can also verify by running this command on your Mac: /usr/bin/xcodebuild -sdk iphoneos -configuration Release -workspace Responder.xcworkspace -scheme Responder archive

This post seems relevant: http://stackoverflow.com/questions/39524148/requires-a-development-team-select-a-development-team-in-the-project-editor-cod 

Thanks,
Madhuri

**Comment by jrmcdona** [comment]
This was something I was doing wrong and not related to the Xcode task.
