### ISSUE TITLE
Publish symbols to drop

### ISSUE THREAD

**Issue by dtorg** [Microsoft/vsts-tasks#4231]
I am trying to publish symbols to the drop location as an artifact but I get an error when I try to specify a location on the $(Build.SourcesDirectory) or  $(Build.ArtifactStagingDirectory) directories. The documentation mentions to use Publish Artifact but I am unsure of the specifics how this needs to be set up.

**Comment by chrisrpatterson** [comment]
Take a look at https://www.visualstudio.com/en-us/docs/build/concepts/definitions/build/artifacts

**Comment by bryanmacfarlane** [comment]
reactivate if those docs don't help or you're still suspecting an issue / bug
