### ISSUE TITLE
Rerun failed test cases from TFS 2015 

### ISSUE THREAD

**Issue by psutharsan** [Microsoft/vsts-tasks#4232]
Not able to rerun the failed test from TFS release. There should be a easier way to select the failed test from the Test results and run it from there. Thanks.

**Comment by nigurr** [comment]
@psutharsan Hi, Currently this feature is not available. it's in our backlog. Please vote for this @ https://visualstudio.uservoice.com/forums/330519-team-services and give us your suggestions
