### ISSUE TITLE
 Azure App Service Deploy Task:  [error]Error: socket hang up

### ISSUE THREAD

**Issue by ampetrushenko** [Microsoft/vsts-tasks#4241]
After task was updated to 3.3.1 version, task failing with error [error]Error: socket hang up
I am using VSO with private build agent 2.115 version.

**Comment by arjgupta** [comment]
Hi @ampetrushenko , can you please send the debug logs to RM_Customer_Queries@microsoft.com . You can generate the full debug logs by setting the system.debug variable to true in the variables tab.

**Comment by ampetrushenko** [comment]
Logs were sent to email RM_Customer_Queries@microsoft.com. Thanks

**Comment by mvvsubbu** [comment]
As per the last conversation we had it started working without any additional actions for both hosted/on prem agents. So I am closing this issue as nothing is actionable, feel free to re-open if it happens again.
