### ISSUE TITLE
Build is waiting for a pipeline to be assigned. But nothing is In Progress

### ISSUE THREAD

**Issue by rodrigomocca** [Microsoft/vsts-tasks#4254]
Hi, I'm having an strage issue.
When I queue a build I'm getting this message: Build is waiting for a pipeline to be assigned.
![image](https://cloud.githubusercontent.com/assets/4087916/25749666/b3d9f622-3185-11e7-8166-68a4ad261318.png)
But if I enter to expore pipelines queue:
![image](https://cloud.githubusercontent.com/assets/4087916/25749728/e7a04628-3185-11e7-91d6-72410c474b7b.png)
![image](https://cloud.githubusercontent.com/assets/4087916/25749731/ea37424c-3185-11e7-924e-11e2a3c9503e.png)
![image](https://cloud.githubusercontent.com/assets/4087916/25749736/ec219a1c-3185-11e7-8913-d2346149d058.png)
![image](https://cloud.githubusercontent.com/assets/4087916/25749741/edcd63f0-3185-11e7-9bcf-06bda73970fb.png)

The only In queue is the build I'm trying to run.

Any ideas?

**Comment by bryanmacfarlane** [comment]
This is not a task issue from the repo.  It was related to live site incident on the service.   email be - bryanmac and that's at microsoft if you're still having an issue.  I'll have someone look at it.
