### ISSUE TITLE
VSTest: Test Impact Analysis not working for x64 Assemblies

### ISSUE THREAD

**Issue by TheodorKleynhans** [Microsoft/vsts-tasks#4255]
The step where tests are discovered (**ListFullyQualifiedTests**) does not pass the platform variable to vstest.console.exe resulting in the following:

> Test run will use DLL(s) built for framework Framework45 and platform X86. Following DLL(s) will not be part of run: 
> _{list of x64 assemblies}_ are built for Framework Framework45 and Platform X64.

I tested on the build agent, and executing the exact same command-line, but with **/Platform:x64** added, results in expected behaviour.

**Comment by acesiddhu** [comment]
Thanks for reporting it. Can you tell if the test assemblies are native or .net assemblies? Also in the task are you passing x64 via other console options or testsettings?

**Comment by TheodorKleynhans** [comment]
Hi.

It's .NET Assemblies. We force them to x64 since there is some PInvoke to a
native 64-bit dll.

We're passing x64 via Other Console Options.

Regards, Theodor


On 05 May 2017 5:19 PM, "Siddhartha Pandey" <notifications@github.com>
wrote:

Thanks for reporting it. Can you tell if the test assemblies are native or
.net assemblies? Also in the task are you passing x64 via other console
options or testsettings?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vsts-tasks/issues/4255#issuecomment-299493623>,
or mute the thread

**Comment by acesiddhu** [comment]
Can you use runsettings instead once with x64 option and remove other console output

https://msdn.microsoft.com/en-us/library/ee782531.aspx

Check this for runsettings example.


Sent from my Windows 10 phone

**Comment by acesiddhu** [comment]
@TheodorKleynhans did this work for you?

**Comment by acesiddhu** [comment]
Closing this issue. let me know if you are still blocked.
