### ISSUE TITLE
Publish Test Results step ignores "Always Run" option

### ISSUE THREAD

**Issue by Lugribossk** [Microsoft/vsts-tasks#426]
If I set up a build with a Publish Test Results step at the end, and set Always Run to true, then it still doesn't run if a previous step fails. If the previous step fails because of test errors, then that means tests results will only be collected for builds where the tests succeed, which is not that useful.

I also tried setting Continue on Error on the previous task, so that the build finishes with the "partially successful" status, which does let the test results be collected. However that status makes the "automatically build pull requests" feature think the build succeeded and allows it to be merged despite the test failures.

**Comment by bryanmacfarlane** [comment]
This is being fixed right now by replacing the job execution with a new steprunner.  See the tests @ https://github.com/Microsoft/steprunner/blob/master/src/tests.ts

**Comment by dragongame** [comment]
As I use google test framework  for the unit testing (under linux) I do the following to be able to upload the file and get a failing build. This obviously only works when the option for clean builds is enabled.

## 1) execute a shell script: 
    ./run_unittests || touch unittest.failed

## 2) publish test results

## 3) exectue a shell script: 
    if [ -f unittest.failed ];
    then
        exit 128
    fi

**Comment by bryanmacfarlane** [comment]
This is fixed in the new xplat agent.  https://github.com/Microsoft/vsts-agent

Wait for new preview coming early next week
