### ISSUE TITLE
Only one command should be used for npm. Use 'Arguments' input for additional arguments.

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/vsts-tasks#4262]
Hello-

I have two NPM commands and they seem to be fairly different.

One is:
npm install

2nd is:
npm run ionic:build --prod

Any reason why I cannot have two NPM tasks in the VSTS build task list?

Thanks

**Comment by chrisrpatterson** [comment]
Nope you can have as many as you need.  You can even change the display name for the instance in the editor so you can tell them apart in the build.

**Comment by yaroslavya** [comment]
Having the same issue. @chrisrpatterson can you give some more details on why it happens if you just add 2 npm commands one after another? I added `npm install` and `npm run build` which immediately gave me this error: 
"##[error]Only one command should be used for npm. Use 'Arguments' input for additional arguments."

**Comment by bryanmacfarlane** [comment]
And for the second task was it:
Npm
Command: run
Arguments: build

Or was it
Npm
Command: run build

?

**Comment by yaroslavya** [comment]
`run build` it is!

**Comment by jrmcdona** [comment]
You have to use the arguments in the second command.   Use

**Comment by bryanmacfarlane** [comment]
The second one isn't a command - it's arguments
run is the npm command.  build is an argument

**Comment by jrmcdona** [comment]
Ok, second "task" I should call it.  Not command!

**Comment by MonkeyAlex** [comment]
Thank you all.

The splitting up of "run build" into cmd="run" & arg="build" trick worked for me.

It started happening to me since upgrading to TFS 2017
in which **npm** was silently upgraded to 0.2.16.
