### ISSUE TITLE
Being able to specify the startpath for webdeploy when "Remove additional files at destination" is checked

### ISSUE THREAD

**Issue by parcae** [Microsoft/vsts-tasks#4277]
Not sure if this is a feasible option to request, but I would like to see the ability to supply a startpath for MSWebdeploy when the checkbox "Remove additional files at destination" is enabled. So in that case Webdeploy is doing a full sync on that path only and removing all additional files within that path and it's subfolders. 
Releases which are only updating parts of the folders in the webroot (which is intended in our case), are going to be a lot quicker because there is no need to first remove everything and then redeploy the entire web application.

**_To give an example of the supposed usage:_**
In our case we are using a Content Management System which contains a lot of files (12000+)..... On top of that we have our web application which needs to be deployed. So, doing a full deployment every time on such a large amount of files, takes quite a while. We have currently splitted the release into 2 parts:
1) the first part cleans everything and deploys the CMS files.
2) the second part deploys **only** our web application files.

However, if we want to only deploy a clean web application, _which you want most of the time_, we first need to remove all the files on the entire web application and redeploy the CMS first and then deploy the web application.

**Comment by phatcher** [comment]
There's another use case for this which I'm just encountering, say I have a web app with an api and a number of web jobs.

If I deploy any of these I'd like to wipe down the specific application's directory but not delete the other directories as each component might be on it's own release pipeline

**Comment by RoopeshNair** [comment]
We don't have support for specifying start path with default rules for MSDeploy operations. I would suggest your ideas at [UserVoice](https://visualstudio.uservoice.com/forums/330519-team-services/category/145269-release-management) and vote for it to get the right prioritization.
