### ISSUE TITLE
Get-AgentIPRange fails when password contains "|"

### ISSUE THREAD

**Issue by wimmeerschman** [Microsoft/vsts-tasks#4279]
When putting the firewall rules setting to "AutoDetect" it executes
    $ipAddressRange = Get-AgentIPRange -serverName $ServerName -sqlUsername $SqlUsername -sqlPassword $SqlPassword
$sqlPassword = firstPart|secondPart

This cmdlet fails, because it interprets the "|" symbol in the password as a pipe:
The term 'secondPart' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by bryanmacfarlane** [comment]
This isn't related to any of the tasks in this repo.  If it is, can you specify which one and reactivate?

**Comment by wimmeerschman** [comment]
Hi,

I didn't noticed I logged the issue on the level of all vsts tasks, the issues concerns this task:
/tree/master/Tasks/SqlAzureDacpacDeployment
More specific in file DeploySqlAzure.ps1, line 131.
