### ISSUE TITLE
Remove max size restriction for instructions on the manual intervention step

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vsts-tasks#4282]
Is there a specific reason why the instructions field of the manual intervention step [is restricted to 500 characters](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/ManualIntervention/task.json#L31)? IMHO it is not unusual to have instructions longer than 500 chars.

**Comment by azooinmyluggage** [comment]
Thanks for the valuable feedback. I have opened a bug to get this fixed.
