### ISSUE TITLE
Command Line - Piping commands to output file

### ISSUE THREAD

**Issue by duckwaffle** [Microsoft/vsts-tasks#4288]
Hi,

I'm trying to create a simple task that will output build variables to a file using the Command Line task, but I cannot get the stdout stream of echo to write to a file, is this possible? I have tried many different ways of getting the output to pipe into a file, but none of them seem to generate a file.

The methods I have tried are all variations using quotes, double quotes, backticks etc. of:

Task: `Command Line`
Tool: `echo`
Arguments: `$(ReleaseNotes) >> $(Build.ArtifactStagingDirectory)/releasenotes.txt`

I have even tried using `| tee $(Build.ArtifactStagingDirectory)/releasenotes.txt` which also does not work.

Does this task support piping at all? I could probably solve this by writing a script that does the task and committing it to the repo, but I would really like to avoid doing that as I am working on a build task template for future projects and I don't want to have to remember to include that script file for all future projects.

Cheers,
Richard

**Comment by duckwaffle** [comment]
It's worth noting that I have been testing on a mac build agent, so I don't have access to the powershell task, otherwise I would use an inline powershell script.

**Comment by bryanmacfarlane** [comment]
It does not support piping (that's a shell concept).  It supports running a process with arguments.

A script is probably the way to go.

We have discussed the possibility of taking your input and generating a temp script on the fly.

**Comment by duckwaffle** [comment]
Hmm, that is a touch annoying as there doesn't seem to be any way to write to a file on a non-windows agent without using a custom task.

**Comment by bryanmacfarlane** [comment]
Yeah, ad-hoc scripts (sh and ps1) are a much easier than a custom task.

**Comment by duckwaffle** [comment]
I do see that the SSH task allows for creating essentially an inline shell script, if I wanted to SSH into localhost, are there pre-defined variables for the build agent's username and password?

**Comment by duckwaffle** [comment]
Nevermind, that task requires a pre made endpoint.

**Comment by bryanmacfarlane** [comment]
we do it have it on our backlog for proper inline support of shellscript, cmd and ps1

**Comment by duckwaffle** [comment]
Ok cheers, I will close this now. Thanks for the info.

**Comment by MitchDart** [comment]
Did you manage to find a workaround @duckwaffle ? I have the same issue at the moment.
