### ISSUE TITLE
Test run is aborted. Logging details of the run logs. UnExpected error occured during test execution. Try again.

### ISSUE THREAD

**Issue by pcarcereri** [Microsoft/vsts-tasks#4290]
Hi, 

I am using TFS 2015 Release 3 and i found out an issue with the "Run Functional Tests" task when the user selects a particular test plan.
I created a test suite made by several tests created using MTM. By default MTM sets the "automation status" of each test to "Planned". I have associated the automation to four tests in the suite (using Visual Studio). 
It seems that the "Run Functional Tests" task tries to execute all the tests, both the "Automated" and "Planned" ones, and it ends up failing the complete test run. 

![1](https://cloud.githubusercontent.com/assets/1540078/25894611/c97a4db0-357c-11e7-8013-9c08f402f173.PNG)

![2](https://cloud.githubusercontent.com/assets/1540078/25894620/cfb75e8e-357c-11e7-9ccc-f7ffdcb0aa11.PNG)

Whenever i set the automation status of the tests that have been not yet automatized to "Not Automated", then everything runs as expected. 

![3](https://cloud.githubusercontent.com/assets/1540078/25894717/3eaef93c-357d-11e7-92ea-327d73fe0763.PNG)

![4](https://cloud.githubusercontent.com/assets/1540078/25894721/41da5278-357d-11e7-94bd-739ccee68c70.PNG)

I don't find this very intuitive from an user point of view as the tasks should execute only the tests that have been automated using visual studio (also because MTM sets by default the automation status as "Planned" and i have to change it every time). 

Thank you for your attention,
Pietro Carcereri

**Comment by nigurr** [comment]
@pcarcereri Sorry for the trouble. This has been fixed in TFS 2017 and later versions.
