### ISSUE TITLE
Service Application Deployment: Value does not fall within the expected range

### ISSUE THREAD

**Issue by awcab** [Microsoft/vsts-tasks#4292]
With no application changes, we just started seeing this today.  Things worked fine yesterday. Has something changed with the deploy task?

Successfully connected to cluster.
2017-05-10T17:17:53.0768795Z Searching for path: d:\a\1\s\Stage.xml
2017-05-10T17:17:53.0858774Z Found path: d:\a\1\s\Stage.xml
2017-05-10T17:17:53.0868750Z Overriding application parameter file specified in publish profile with 'd:\a\1\s\Stage.xml' specified in the VSTS task.
2017-05-10T17:17:57.4278778Z An application with name 'fabric:/MyFabric' already exists in the cluster with application type 'MyFabricType' and version '1.0.1'. Removing it.
2017-05-10T17:18:08.3318610Z Remove application instance succeeded
2017-05-10T17:18:11.3300419Z Unregister application type succeeded.
**2017-05-10T17:18:11.5733419Z ##[error]Value does not fall within the expected range.**
2017-05-10T17:18:11.6073445Z ##[section]Finishing: Deploy MyFabric

**Comment by MECLab-Keags** [comment]
We're experiencing the same issue as of today.

**Comment by aloneguid** [comment]
same for me today, absolutely nothing has changed in deployment scripts

**Comment by negberts** [comment]
Same here after upgrading to service fabric 5.6.204

**Comment by aloneguid** [comment]
@negberts my cluster is running 5.5.216.0 so nothing changed here

**Comment by negberts** [comment]
@aloneguid isn't your cluster automatically upgraded in Azure? Automatic upgrade is the default mode... 

![image](https://cloud.githubusercontent.com/assets/20299260/25955170/bfacc406-3668-11e7-9ed4-1daed5e6b61b.png)

**Comment by aloneguid** [comment]
@negberts as long as I understand it's not upgraded as soon as a new version appears - in your screenshot the current fabric cluster runs on 5.5.

**Comment by johnweeder** [comment]
I could not deploy, received this same error, until I forced a manual upgrade of the service fabric to 5.6. After upgrading, I now get a different message during deploy:
Split-Path : The term 'Split-Path' is not recognized as the name of a cmdlet, function, script file, or operable 
2>program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2>At C:\...Application\Scripts\Deploy-FabricApplication.ps1:159 

But the error does not prevent the script from continuing on and attempting a deployment.

**Comment by johnweeder** [comment]
I would also note that Platform installer wants to keep installing the SF SDK and Tools even though I have installed them multiple times!

**Comment by aloneguid** [comment]
I've changed the deployment queue from "Hosted VS2017" to "Hosted" and this started working again, therefore I suspect there is something wrong with the new VSTS image.

**Comment by rickm101** [comment]
Agreed - i'm having the same issue.

**Comment by bishal-pdMSFT** [comment]
As stated by @aloneguid, this seems to be an issue with Hosted VS2017 queue. Please use Hosted agent queue as workaround till we get to root of this issue.

**Comment by negberts** [comment]
We have our own build agent installed on a VM. It happens there too. What can we do?

**Comment by bishal-pdMSFT** [comment]
@negberts what is the service fabric SDK version on you agent. You can run following PS command to get SDK version: 
`Get-ItemProperty -Path "HKLM:\SOFTWARE\Microsoft\Service Fabric SDK" -Name FabricSDKVersion`

Also what is the service fabric version for your cluster?

**Comment by negberts** [comment]
We updated SDK on the agent. The cluster was not yet updated, although it had the setting automatic. Could that be the problem?

**Comment by bishal-pdMSFT** [comment]
I do think that could be the problem. New SDK version is failing to get application type information from cluster running older fabric. I can repro this issue even without VSTS in picture. Use latest SDK version 
2.6.204.9494 and try to run PS command Get-ServiceFabricApplicationType on a cluster having version 
5.5.216.0, I get exact same error.

**Comment by bishal-pdMSFT** [comment]
Service fabric team has confirmed issue with latest SDK. [https://github.com/Azure/service-fabric-issues/issues/267](https://github.com/Azure/service-fabric-issues/issues/267)
We are also rolling back SDK changes in hosted vs2017 queue. Till that time please use Hosted queue or private agent with n-1 SDK.

**Comment by pchamakura** [comment]
I faced the same issue. I just updated the cluster to the latest fabric version and this problem went away. 

What's stopping you from upgrading the fabric version. It's quick and easy.
