### ISSUE TITLE
PublishSymbols Task and Functional Breakpoints

### ISSUE THREAD

**Issue by johnkattenhorn** [Microsoft/vsts-tasks#4298]
I'm pretty sure this is nothing to do with the PublishSymbols task but I though I'd ask anyway. We have the following:

VSTS Private Build Agent
Shared Drive Using Azure File Storage to hold symbols
PublishSymbols step to publish to Shared Drive
Visual Studio 2017 Enterprise configured to use the same Shared Drive as Symbol Server

If I set a breakpoint and step into some code which we have symbols for it correctly finds them and then uses the symbol file to download the source.; this work fine (it's pretty cool as I'm newish to this).

However if I set a functional breakpoint to code that's been indexed at the sametime of the previous one the breakpoint is but I get the No Source Page in Visual Studio. 

Does anyone know the expected behaviour here ? Should hitting the functional Breakpoint download the source like stepping into the debugger ?

**Comment by chrisrpatterson** [comment]
I am not sure what you mean by functional breakpoint.  Can you provide some additional details?

**Comment by johnkattenhorn** [comment]
Thanks for responding @chrisrpatterson , I got this mostly working in the end by sharing the symbols with our machines via Azure Storages (Files), although for some reason the class I wanted to see the source for just isn't there. Pretty much everything else is from the same assembly. It's really odd but I'll close this I think.
