### ISSUE TITLE
Azure CLI task not finding `az` with `which` on macOS

### ISSUE THREAD

**Issue by cicorias** [Microsoft/vsts-tasks#4302]
Running on macOS and the which command doesn't find the Azure CLI installed via pip.

A `type az` finds it OK.
a `which az` returns nothing, which causes the task to fail as it checks for existence of `az` in the path.

![image](https://cloud.githubusercontent.com/assets/1080406/25977546/3b72ebe4-368a-11e7-883d-a335e8fc1233.png)

The location of the `az` script is in ` /Users/cicoriasmbp13/Library/Python/2.7/bin/az`

This location is also in the path. 

![image](https://cloud.githubusercontent.com/assets/1080406/25977581/7abfb598-368a-11e7-86d6-42dd86b0a18f.png)

Suggestion: Use `command -v az` or `type az` just to check if it exists.  The former is a Posix standard.

**Comment by cicorias** [comment]
So, removing all remnants of the `pip install` version of azure-cli via 
```
pip list --format=legacy |grep azure | cut -d ' ' -f 1 | xargs -L1 pip uninstall -y 
```

Then re-running the proper install script for azure cli 2.0 (pip was supported at some point) - 
```
curl -L https://aka.ms/InstallAzureCli | bash
```

Places the `az` in a path that is perhaps handled better by `which`.

However, if you take not of that Azure CLI install script, you'll see that they use the `command -v` option as it just works better.

```
command -v python > /dev/null 2>&1
if [ "$?" -ne 0 ]
then
  echo "ERROR: Python not found. 'command -v python' returned failure."
  echo "If python is available on the system, add it to PATH. For example 'sudo ln -s /usr/bin/python3 /usr/bin/python'"
  exit 1
fi
```

**Comment by cicorias** [comment]
Sorry, 1 last comment.

the `which` command doesn't handle `~` well, or if at all apparently.

So, any settings in scripts, profiles, etc. should use `$HOME` instead of prefix o `~`.  So, a path such as `~/bin` wont be checked by `which` it seems.

**Comment by chrisrpatterson** [comment]
Are you sure it is in the path for the agent?  Just because it is in your path does not mean it is in the path for the agent.

**Comment by cicorias** [comment]
Yes, as I launch the agent from same shell. It's 'which' that can't find it in any shell where path is set using ~ instead oh $HOME.

Once path is changed it works.

**Comment by ericsciple** [comment]
I believe `~` is a convention of the bash shell, and not understood at the OS level.

That's not to say that we shouldn't add support for it in the library that we use... Although if `which` doesn't support it, then I think we definitely shouldn't worry about it in our library.

**Comment by cicorias** [comment]
a `command -v az` would be most compliant and consistent.

**Comment by sachinma** [comment]
@ericsciple since this relates to how which works in the task lib, would you like to take this up? I have added you assignee..

**Comment by cicorias** [comment]
Not sure if you're taking this on, but seeing this with a few more partners I've worked with I investigated further.  

Please see https://github.com/Microsoft/vsts-task-lib/pull/249 for a PR that addresses this.

**Comment by ericsciple** [comment]
ok let's close the issue here and discuss on the task-lib repo since it's arguably not a "bug" (rather an enhancement for the lib)
