### ISSUE TITLE
No documentation for new .NET Core task

### ISSUE THREAD

**Issue by shaggygi** [Microsoft/vsts-tasks#4303]
It appears the [documentation ](https://www.visualstudio.com/en-us/docs/build/apps/aspnet/ci/build-aspnet-core) is not updated to use the new .NET Core task.

Trying to setup my CI/CD with no luck.  It can pull my source from my GitHub repo, but that's as far as I get.  Not sure what paths to add for solution/projects, how to setup test for Xunit project, etc.

Somewhat frustrating.  Any help (doc links) is appreciated.

**Comment by bryanmacfarlane** [comment]
I'll get this over to the RM team.

**Comment by shaggygi** [comment]
@bryanmacfarlane thank you

**Comment by sachinma** [comment]
This is now fixed.

**Comment by shaggygi** [comment]
@sachinma thanks.  Can you add a link here to the document update?

**Comment by sachinma** [comment]
The same link that you referred to earlier is now showing the right steps.
