### ISSUE TITLE
A parameter cannot be found that matches parameter name 'ComposeFilePath'.

### ISSUE THREAD

**Issue by CodedBeard** [Microsoft/vsts-tasks#4308]
Hi,
I've been testing the Docker-Compose to Service Fabric Preview task, and have not been having much luck. The new build tasks work fine, but when I attempt to run the release task, I just get the following:

> ##[section]Starting: Deploy docker-compose application to a Service Fabric cluster
==============================================================================
Task         : Service Fabric Compose Deploy (Preview)
Description  : Deploy a docker-compose application to a Service Fabric cluster.
Version      : 0.0.38
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=847030)
==============================================================================
Searching for path: d:\a\r1\a\ASP.NET with Containers-CI\docker-compose\docker-compose.yml
Found path: d:\a\r1\a\ASP.NET with Containers-CI\docker-compose\docker-compose.yml
Checking compose file
##[error]A parameter cannot be found that matches parameter name 'ComposeFilePath'.
##[section]Finishing: Deploy docker-compose application to a Service Fabric cluster

It looks like the error occurs on [this line](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/ServiceFabricComposeDeploy/ServiceFabricComposeDeploy.ps1#L38), but I cannot find where the `Test-ServiceFabricApplicationPackage` cmdlet is defined.

**Comment by bishal-pdMSFT** [comment]
@CodedBeard what agent are you using? Is it hosted/hosted vs2017 queue? if using private agent, what is service fabric SDK version on agent?

**Comment by CodedBeard** [comment]
@bishal-pdMSFT VS2017 hosted.

**Comment by bishal-pdMSFT** [comment]
Can you please enable debug logging and share debug logs for task. To enable debug logging, add a variable called "system.debug" with value true to release definition, then trigger a release.

**Comment by CodedBeard** [comment]
@bishal-pdMSFT  It turns out I must have failed to save changing the release agent change. As i just went back and checked it, and discovered it was on standard hosted. Switched it back to VS2017 and it worked fine. Thanks
