### ISSUE TITLE
Does not support Azure China Deployment

### ISSUE THREAD

**Issue by chenliang** [Microsoft/vsts-tasks#431]
Unable to modify the environment for AzureChinaCloud

**Comment by chenliang** [comment]
Temporarily solve

modify  'C:\Program Files\Microsoft Team Foundation Server 14.0\Build\Agent\Worker\Modules\Microsoft.TeamFoundation.DistributedTask.Task.Deployment.Azure\Microsoft.TeamFoundation.DistributedTask.Task.Deployment.Azure.psm1 '
line132: 
Set-AzureSubscription -SubscriptionName $azureSubscriptionName -SubscriptionId $azureSubscriptionId -Certificate $x509Cert -CurrentStorageAccountName $StorageAccount -Environment AzureChinaCloud   
 
support Azure Azure China Deployment

**Comment by chrisrpatterson** [comment]
That is interesting, I didn't think it was possible to deploy to the Azure China Cloud from outside of China.  It is also quite difficult for us to verify this scenario as we don't have access to subscriptions in Azure China.  

Is the only option you need the ability to specify the value for the -Environment parameter in the subscription selection?

**Comment by chenliang** [comment]
Microsoft.TeamFoundation.DistributedTask.Task.Deployment.Azure.psm1  scripts which use fixed parameters  -Environment AzureCloud  
China needs to use parameters  AzureChinaCloud

**Comment by yaananth** [comment]
copied to backlog, should be done for next sprint deployment

**Comment by yaananth** [comment]
Not yet fixed, will think of right approach ( i guess adding input to task )

**Comment by bryanmacfarlane** [comment]
@GitHubSriramB ??

**Comment by juniwang** [comment]
Is this issue fixed?

**Comment by bryanmacfarlane** [comment]
@githubsriramb?

**Comment by GitHubSriramB** [comment]
We are adding support for deploying to Azure Government clouds. Expect this to be available in next few weeks.

**Comment by RoopeshNair** [comment]
@chenliang,

With the latest deployment, support for govt. clouds is in place. Please refer to release notes for more info. https://www.visualstudio.com/news/2016-jul-29-vso

**Comment by kmkumaran** [comment]
Closing based on @RoopeshNair comments.

**Comment by lehne** [comment]
@RoopeshNair Those changes only support adding "Azure Classic" subscription. The publish to Azure Website Task for Azure Classic is deprecated. Will azure government support come for Resource Manager subscriptions?

**Comment by RoopeshNair** [comment]
@lehne  National cloud support for ARM endpoints is getting deployed. If you are looking for an early preview drop a note to us at rm_customer_queries at microsoft dot com
