### ISSUE TITLE
Secret variable cannot be used in PowerShell task if it contains an ampersand

### ISSUE THREAD

**Issue by ChristophB125** [Microsoft/vsts-tasks#4310]
1. Define a secret variable that contains an ampersand, e.g. ``a&b``
2. Secret variables have to be passed into scripts as a parameter and it will fail at the point of passing the variable in, i.e. just having ``Param($inputVariableWhichIsSecret)`` in the script is sufficient.
3. Because VSTS seems to execute PowerShell block by block it tries to evaluate the secret variable and returns a PowerShell error:

The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double 
quotation marks ("&") to pass it as part of a string.
At line:1 char:237
+ ... Clear() } ; Invoke-Expression -Command ([System.Text.Encoding]::UTF8. ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : AmpersandNotAllowed,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by ericsciple** [comment]
The params are passed on a powershell command line so you need to escape (e.g. wrap in double or single quotes).

Note, passing on a ps command line enables things like arrays and hashtables. So passing on the ps command line is intentional and correct.

**Comment by ChristophB125** [comment]
@ericsciple Thanks. Yes, that works, thanks. Would it make sense to document that the arguments to PowerShell actually get evaluated (e.g. in the help-markdown of the task)? I had a look at the documentation [here](https://www.visualstudio.com/en-us/docs/build/define/variables#secret-variables) which used to say that secret variables have to be passed in as $(mysecret), which seems to have changed by now as I can pass them in now as $env:mysecret as well. We as users rely on documentation and given that the behaviour of VSTS changes very quickly, it gets very confusing. Is there at least some sort of log to see the subtle changes of behaviour as you improve VSTS (which is appreciated btw)?

**Comment by ericsciple** [comment]
@ChristophB125 Secret variables do not get passed to ad hoc scripts. That has not changed.

Are you sure it's a secret?

I can't repro any issue with that behavior. Here is what I tried:
1. Create a definition with two variables
`MySecretVariable` = `MySecretValue` // this one is secret
`MyPublicVariable` = `MyPublicValue`

2. Add a PowerShell task with inline script:
```
"secret is: $env:MySecretVariable"
"public is: $env:MyPublicVariable"
```

3. Output of the script is:
```
secret is: 
public is: MyPublicVariable
```

**Comment by Saugat168** [comment]
I know that I am late into this thread, but I am kind of stuck. And this thread is the closest to the issue I have. So, I have a SAS token which is set in previous Release task and then the Create Resource Group Task uses that SAS token to create the resource group. However, when I try to use the same SAS Token in a powershell task, if I just use in the parameters section of the PowerShell Task
-SecretArgument '$(SASToken)' 

And then print it in the powershell script I get: ***
If I use , in the parameters section of the PowerShell Task
-SecretArgument $(SASToken)

And then print it out in the script, it errors out saying it contains"&" (the special characters that SAS token has), but I can see the half truncated value of $SASToken in the failed release log in clear text.

I have also used single quotes but that also masks it as ***. Is there a way to get this value in the powershell script?

Strangely , this SAS token works (without quotes) in the "Deploy Resource Group Task" when it's passed in the override parameter section (as many tutorials show).

I have run out of ideas to use it in the PowerShell task. Is this a bug in VSTS Release pipeline that secrets with special characters can't be used?
