### ISSUE TITLE
using variable with AzureRmWebAppDeployment App Service name

### ISSUE THREAD

**Issue by mmercan** [Microsoft/vsts-tasks#4312]
I can't use variable in App Service name of AzureRmWebAppDeployment (it requires had coded name to figure out application  type ("visibleRule": "WebAppKind = app || WebAppKind = functionapp")

We use Release Definition and environments for environment creation we run Azure Resource Group Deployment to create the Web Apps and AzureRmWebAppDeployment to deploy base files (Sitecore etc.  dll) I can use version 2 without a problem but when I try to update to version 3 only Azure Subscription and App Service name is visible

**Comment by mmercan** [comment]
Hi, @arjgupta I know that part but the problem is when I trigger the release definition there is no App service to deploy. there are more than 50 tasks I use per-environment which create the Azure components (including App Services) and do the pre-deployments (AzureRmWebAppDeployment) 

![capture_1](https://cloud.githubusercontent.com/assets/5808371/26058022/549ff480-39bf-11e7-96d5-6d8eae2c0ace.PNG)

**Comment by arjgupta** [comment]
Hi @mmercan , if you specify the variable name in the app service name input, the other inputs should appear automatically. Is that not happening?

**Comment by arjgupta** [comment]
Hi @mmercan , I am closing this issue. Please feel free to reopen if you are still blocked on this.
