### ISSUE TITLE
Jenkins Artifact Source not working for Multibranch Pipeline jobs

### ISSUE THREAD

**Issue by Symbianx** [Microsoft/vsts-tasks#4318]
Hello, 
First of all thanks for the great Jenkins support on VSTS.

We have been using the Release Management artifact source with Jenkins on 
several jobs, but now we are trying to use it on Multibranch Pipeline jobs, which basically creates a main job folder and inside it creates a pipeline job per branch. 
When we try to link the Artifact Source we can select the main Multibranch Pipeline job, but we can't select the specific pipeline job we want as the source.
This also applies for folder jobs.

Maybe a good option would be to allow the use of '/' to go to each sub-job.

**Comment by GitHubSriramB** [comment]
@Symbianx, thanks for the feedback. 

Looks like Multibranch Pipeline requires the "Pipeline Multibranch Plugin" to be installed. Can you pl. confirm?

**Comment by Symbianx** [comment]
Yes, that is the plugin.

**Comment by GitHubSriramB** [comment]
We haven't explored what it takes to support selecting artifact source for jobs coming out of this plug-in. We will add this item to your backlog & get back to you once we have added support. Thanks again for your feedback.

**Comment by Symbianx** [comment]
Also, keep in mind this issue does not affect only the plugin but also jobs that are grouped in folders.
Thanks.

**Comment by GitHubSriramB** [comment]
Sure. Thanks for the feedback. Will let you know once we have added this support.

**Comment by kasubram** [comment]
@Symbianx We are thinking of adding a branchname parameter while linking the artifact. After you choose the main MultiBranch pipeline job, there will be one more drop down to choose the branch you are interested in. Would that work for you? what is your opinion?

In your comment you mentioned this also applies for folder jobs. What do you mean by the folder job here?

> When we try to link the Artifact Source we can select the main Multibranch Pipeline job, but we can't select the specific pipeline job we want as the source.
> This also applies for folder jobs.

**Comment by Symbianx** [comment]
@kasubram, thanks for getting back to us.
Although that would be an improvement, it still wouldn't fully fit our needs.
In our MultiBranch pipeline job there are 2 branches that we want to deploy, **dev** and **master**, having the branch parameter in the artifact source would force us to create a release definition per branch which is not ideal.

I have some suggestions to share with you:
1. Have the branchname parameter in the release creation, so we would have to select the build version and the branch name for the MultiBranch artifact source. This is ideal.
If it is not possible to have multiple parameters for one artifact source, the artifact version could be the concatenation of the branch and the build names from Jenkins, something like `master/1.9.0.123`.


2. Much like your suggestion, but with support for selecting multiple branches.

Regarding the folder jobs, it is not related to this specific issue, but I'm refering to the [CloudBees Folders Plugin](https://wiki.jenkins.io/display/JENKINS/CloudBees+Folders+Plugin) which groups the jobs in folders for easier management.

**Comment by Symbianx** [comment]
This is major for us, we used a separate jenkins job to work around this.

🎉
