### ISSUE TITLE
Limitation of task.setvariable that a variable is only available on current agent should be documented

### ISSUE THREAD

**Issue by StefanSchoof** [Microsoft/vsts-tasks#4321]
I work on a TFS Server (15.112.26301.0) and tried using the task.setvariable command. I my scenario I can get a value on the first agent and need the value on the second agent in one environment. I tried to use the task.setvariable command, but the variable seems only available on the agent the `##vso[task.setvariable...` output is done.

The documentation on https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md should mention this Limitation.

**Comment by bryanmacfarlane** [comment]
The docs already state it's scoped to the following tasks:
"The first task can set a variable, and following tasks are able to use the variable"

**Comment by StefanSchoof** [comment]
I think them may case was not clear. I have a environment with two server phases. In my understanding of the following tasks is "Task 3" following the task with the setvariable, but only Task 2 has access to the variable
![settask](https://cloud.githubusercontent.com/assets/4662023/26142500/15ac3928-3ae1-11e7-9986-7f015f787e43.PNG)

I get following Output:

> 2017-05-17T07:09:46.8981665Z ##[section]Starting: vso[task.setvariable
> 2017-05-17T07:09:47.0700405Z ##[command]. 'C:\Users\user\AppData\Local\Temp\a56e1e71-8e1e-42f6-80e2-76b5ed3d36a6.ps1' 
> 2017-05-17T07:09:47.8044120Z ##[section]Finishing: vso[task.setvariable
> 2017-05-17T07:09:47.8044120Z ##[section]Starting:  Write-Host $env:testvar
> 2017-05-17T07:09:47.8200371Z ##[command]. 'C:\Users\user\AppData\Local\Temp\72f30388-d429-4431-8867-3130a5817d5f.ps1' 
> 2017-05-17T07:09:48.2731655Z HelloWorld
> 2017-05-17T07:09:48.2887888Z ##[section]Finishing:  Write-Host $env:testvar
> 2017-05-17T07:09:54.0387983Z ##[section]Starting:  Write-Host $env:testvar
> 2017-05-17T07:09:54.1325568Z ##[command]. 'C:\Users\user\AppData\Local\Temp\93b4b79e-9cb6-4be3-8611-b36654dc1501.ps1' 
> 2017-05-17T07:09:54.6013008Z 
> 2017-05-17T07:09:54.6169238Z ##[section]Finishing:  Write-Host $env:testvar

So "The first task can set a variable, and following tasks on the same agent are able to use the variable" is more precise.

**Comment by StefanSchoof** [comment]
@bryanmacfarlane: Are this better description changes any of your opinion, this is already adequate documented.
