### ISSUE TITLE
Process 'msbuild.exe' exited with code '-1' (again!)

### ISSUE THREAD

**Issue by rposener** [Microsoft/vsts-tasks#4325]
VSTS appears to be mainly resolved from this issue - however we have seen 2 failures of this status again in the last 24 hours.  Not sure if it's coincidence or not but both were the first build of each definition of the day, and both occurred about 60 seconds into msbuild.exe running on the first build task.  Any further insight @chrisrpatterson  @bryanmacfarlane ?  

Just had a second build fail on the second build task with the same -1 code. (that's a 3rd failure)

**Comment by bryanmacfarlane** [comment]
reopen the original issue.
