### ISSUE TITLE
Publishing test results with failed tests does not fail the 2015 TFS  build

### ISSUE THREAD

**Issue by Yaash19** [Microsoft/vsts-tasks#4335]
Hello,

i am using angular cli and for unit test i use Karma. So for CI TFS build, i am using npm task for karma unit test .  We use the "publish test results" task to publish the results to the build. The results get published correctly and we can see that some tests failed. When tests fail, however, the build is not marked as failed. I could fail the build when running npm test task, but the results would not get published. Is there a way for the build to look at the published test results and fail if there are test failures?

Thanks

**Comment by chrisrpatterson** [comment]
Your test runner needs to fail the build if there are failures.   You can set the control options on the publish results task to alwasy run or run even when previous tasks have failed

**Comment by Yaash19** [comment]
I need to fail the build based on test results from "Publish Test Results" task,  otherwise i don't see the test results in "Test" tab or in summary. Its says "No tests runs available for this build"

**Comment by 7c6f1568-555e-42a8-aff6-9045799c8b86** [comment]
@Yaash19 there is an option in the "Publish Test Results" task so it runs even if previous tasks failed the build. This is called "Always Run" in the version I am using. 

Alternatively, I tick the test run task option to "continue on error".

**Comment by GrimaceOfDespair** [comment]
Just wanted to add that the suggested workaround can still give issues. If you use a CI setup which you don't force clean checkouts upon for the sake of build time, your build might get started while having an old report in its folders. If you don't clean out these reports actively before the first failing build step, you end up publishing the report from that previous build.
