### ISSUE TITLE
Azure SQL Deployment Task is failing on build boxes having Dac Framework 13.0.3370.2

### ISSUE THREAD

**Issue by lorrinferdinand** [Microsoft/vsts-tasks#4338]
Perhaps I'm missing something on the box, but this has been reproduced on > 1 build box hosting VS 2017 VSTS agents.

I noticed in the powershell script that it is looking for the Dac F/W in this regkey: 
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\DacFramework\CurrentVersion

On the machine the (Default) value of 13.0.3370.2 is stored as a value at the key level.
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\Data-Tier Application Framework\CurrentVersion

The function, Get-RegistryValueIgnoreError,  also fails to find the version when the script is corrected.  Perhaps because the value is at the root of the $sqlRegKey rather than being a subkey/value pair.

Have other encountered this?
If I could get an older version of Dac F/W would that fix this issue?

This is the exact error we are getting ... "Unable to find the location of Dac Framework (SqlPackage.exe) from registry on machine $env:COMPUTERNAME" - which is basically the "I give-in, I have no idea what your looking for" error at the end.

**Comment by arjgupta** [comment]
Hi @lorrinferdinand , this is a known issue, we have added this to our backlog

**Comment by svandekrol** [comment]
Is there a workaround for this?  We switched our VS 2015 project to VS 2017, and can't deploy now, as one of the steps uses sqlpackage.exe!

**Comment by Ajay-MS** [comment]
@svandekrol 

We have recently fixed this issue of detection of SQLPackage.exe with VS2017.  Following are PR's with fix

Detection of SQLPackage.exe in SQLAzureDacpacDeployment 
https://github.com/Microsoft/vsts-tasks/pull/4915

Detection of SQLPackage.exe in agent capabilities 
https://github.com/Microsoft/vsts-agent/pull/1098

Detection logic in the task has already been deployed to production but the logic of detection of sqlpackage.exe in capability will be deployed with next release of the agent. 

At present, you can unblock your self-using any of following steps
1. Manually add SqlPackage.exe to capability list of the agent. 
2. Install data-tier application framework.

**Comment by Ajay-MS** [comment]
@svandekrol  

Are you unblocked on this issue?

**Comment by Ajay-MS** [comment]
@svandekrol 

Closing this issue as this has been fixed for VS 17 hosted agent pool too. Feel free to reopen issue in case of you still facing this issue.
