### ISSUE TITLE
Azure Resource deployment Task Failure

### ISSUE THREAD

**Issue by dewanymca** [Microsoft/vsts-tasks#4342]
Hi Team

I have been using “Azure resource Manager deployment” Task in VSTS to deploy the template using release manager. I am facing an issue with template where it fails with below observation:

1)	In VSTS release, Override template parameters shows below error. I have selected the file using browse button only. See attached 1.jpg and 2.jpg
![1](https://cloud.githubusercontent.com/assets/15336470/26189871/64389ed6-3bc4-11e7-810e-23c1f45a55f1.jpg)
![2](https://cloud.githubusercontent.com/assets/15336470/26189896/83493ec0-3bc4-11e7-9d2f-a7920565c5b5.jpg)

 

 

2)	I went ahead and deployed it and it failed with below error: 

2017-05-18T06:45:27.3061795Z ##[section]Starting: Service Bus:Create/Update Service Bus Alert
2017-05-18T06:45:27.3216637Z ==============================================================================
2017-05-18T06:45:27.3216637Z Task         : Azure Resource Group Deployment
2017-05-18T06:45:27.3216637Z Description  : Deploy, start, stop, delete Azure Resource Groups
2017-05-18T06:45:27.3216637Z Version      : 2.1.0
2017-05-18T06:45:27.3216637Z Author       : Microsoft Corporation
2017-05-18T06:45:27.3216637Z Help         : [More Information](https://aka.ms/argtaskreadme)
2017-05-18T06:45:27.3216637Z ==============================================================================
2017-05-18T06:45:27.6341731Z f5178d01-fb27-4c59-a0b5-2f0f4b69bc1a exists true
2017-05-18T06:45:27.6341731Z Checking if the following resource group exists: DeliveryOrderServiceOperationSIT.
2017-05-18T06:45:28.6490528Z Resource group exists: true.
2017-05-18T06:45:28.6490528Z Creating deployment parameters.
2017-05-18T06:45:28.6490528Z ##[error]Error: Ensure the Template file is valid. Task failed while parsing with following error: Unexpected token /
2017-05-18T06:45:28.6490528Z ##[section]Finishing: Service Bus:Create/Update Service Bus Alert

The same template works If I try to deploy using Powershell :

PS D:\Deepak\myWork\VSTS\SC-SCS-SC-DCS-DeliveryOrder\Operations\DCServices.Operations\Deployment\bin\Debug> .\Deploy-AzureResourceGroup.ps1 -StorageAccountName '' -ResourceGroupName 'DeliveryOrderServiceOperationSIT' -ResourceGroupLocation 'eastus2' -TemplateFile 'D:\Deepak\myWork\VSTS\SC-SCS-SC-DCS-DeliveryOrder\Operations\DCServices.Operations\Deployment\ServiceBus\createAlert.azuredeploy.json' -TemplateParametersFile 'D:\Deepak\myWork\VSTS\SC-SCS-SC-DCS-DeliveryOrder\Operations\DCServices.Operations\Deployment\ServiceBus\createAlert.azuredeploy.parameters.json' -ArtifactStagingDirectory '.' -DSCSourceFolder '.\DSC'  -Verbose 
VERBOSE: Performing the operation "Replacing resource group ..." on target "".
VERBOSE: 12:02:16 PM - Created resource group 'DeliveryOrderServiceOperationSIT' in location 'eastus2'

ResourceGroupName : DeliveryOrderServiceOperationSIT
Location          : eastus2
ProvisioningState : Succeeded
Tags              : 
ResourceId        : /subscriptions/c2403b7f-d35b-405a-bccf-d954202081ef/resourceGroups/DeliveryOrderServiceOperationSIT

VERBOSE: Performing the operation "Creating Deployment" on target "DeliveryOrderServiceOperationSIT".
VERBOSE: 12:02:21 PM - Template is valid.
VERBOSE: 12:02:27 PM - Create template deployment 'createAlert.azuredeploy-0518-0632'
VERBOSE: 12:02:27 PM - Checking deployment status in 5 seconds
VERBOSE: 12:02:33 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-scheduled  message in transactional queue greater than threshold-p3' provisioning status
 is succeeded
VERBOSE: 12:02:33 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-deadletter messgae in retry error queue greater than threshold-p1' provisioning status i
s succeeded
VERBOSE: 12:02:33 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-subscription deleted-p1' provisioning status is succeeded
VERBOSE: 12:02:33 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-deadletter messgae in transactional queue greater than threshold-p3' provisioning status
 is succeeded
VERBOSE: 12:02:33 PM - Resource Microsoft.OperationalInsights/workspaces 'DeliveryOrderServiceOperationSIT-la' provisioning status is succeeded
VERBOSE: 12:02:33 PM - Checking deployment status in 5 seconds
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-no telemetry data from service bus-p2/schedule-wd3jnzp2nimfg' provisioning sta
tus is succeeded
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-active message in retry error queue greater than threshold-p2/schedule-tnouiwy
3hcnjc' provisioning status is succeeded
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-active message in transactional queue greater than threshold-p3/schedule-lmqv7
ln5yuun4' provisioning status is succeeded
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules/actions 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-scheduled  message in retry error queue greater than threshold-p2/sche
dule-mcwsnfzb4amdu/alert-mcwsnfzb4amdu' provisioning status is succeeded
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-scheduled  message in retry error queue greater than threshold-p2/schedule-mcw
snfzb4amdu' provisioning status is succeeded
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-no telemetry data from service bus-p2' provisioning status is succeeded
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-active message in retry error queue greater than threshold-p2' provisioning status is su
cceeded
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-scheduled  message in retry error queue greater than threshold-p2' provisioning status i
s succeeded
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-active message in transactional queue greater than threshold-p3' provisioning status is 
succeeded
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules/actions 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-scheduled  message in transactional queue greater than threshold-p3/sc
hedule-6lwqd2xvjaepi/alert-6lwqd2xvjaepi' provisioning status is succeeded
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules/actions 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-subscription deleted-p1/schedule-phius24y2u22i/alert-phius24y2u22i' pr
ovisioning status is succeeded
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules/actions 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-deadletter messgae in retry error queue greater than threshold-p1/sche
dule-czl27dwni52ks/alert-czl27dwni52ks' provisioning status is succeeded
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules/actions 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-deadletter messgae in transactional queue greater than threshold-p3/sc
hedule-725tn5kdfx4lw/alert-725tn5kdfx4lw' provisioning status is succeeded
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-subscription deleted-p1/schedule-phius24y2u22i' provisioning status is succeed
ed
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-scheduled  message in transactional queue greater than threshold-p3/schedule-6
lwqd2xvjaepi' provisioning status is succeeded
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-deadletter messgae in retry error queue greater than threshold-p1/schedule-czl
27dwni52ks' provisioning status is succeeded
VERBOSE: 12:02:39 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-deadletter messgae in transactional queue greater than threshold-p3/schedule-7
25tn5kdfx4lw' provisioning status is succeeded
VERBOSE: 12:02:40 PM - Checking deployment status in 5 seconds
VERBOSE: 12:02:46 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules/actions 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-no telemetry data from service bus-p2/schedule-wd3jnzp2nimfg/alert-wd3
jnzp2nimfg' provisioning status is succeeded
VERBOSE: 12:02:46 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules/actions 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-active message in retry error queue greater than threshold-p2/schedule
-tnouiwy3hcnjc/alert-tnouiwy3hcnjc' provisioning status is succeeded
VERBOSE: 12:02:46 PM - Resource Microsoft.OperationalInsights/workspaces/savedSearches/schedules/actions 'DeliveryOrderServiceOperationSIT-la/alert|dcservices-deliveryorder-servicebus-sit-active message in transactional queue greater than threshold-p3/schedu
le-lmqv7ln5yuun4/alert-lmqv7ln5yuun4' provisioning status is succeeded

DeploymentName          : createAlert.azuredeploy-0518-0632
CorrelationId           : 8f0c0390-0df2-4f89-84ff-8247ead18083
ResourceGroupName       : DeliveryOrderServiceOperationSIT
ProvisioningState       : Succeeded
Timestamp               : 5/18/2017 6:32:42 AM
Mode                    : Incremental
TemplateLink            : 
TemplateLinkString      : 
DeploymentDebugLogLevel : 
Parameters              : {[omsWorkspaceName, Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable], [workspaceRegion, Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable], [omsSku, 
                          Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable], [environmentName, Microsoft.Azure.Commands.ResourceManager.Cmdlets.SdkModels.DeploymentVariable]...}
ParametersString        : 
                          Name             Type                       Value     
                          ===============  =========================  ==========
                          omsWorkspaceName  String                     DeliveryOrderServiceOperationSIT-la
                          workspaceRegion  String                     East US   
                          omsSku           String                     free      
                          environmentName  String                     SIT       
                          serviceResourceGroupName  String                     DeliveryOrderServicesSIT
                          componentName    String                     DCServices
                          serviceLine      String                     DeliveryOrder
                          alertNotificationEmail  String                     v-salakh@microsoft.com
                          txnQueueOMSQuery  String                     (Name_s=AllDeliveryOrders or Name_s=deliveryOrder)
                          errorQueueOMSQuery  String                     (Name_s=NonRetriableDeliverOrders or Name_s=RetriableDeliverOrders or Name_s=deliveryordererror)
                          azureComponentName  String                     ServiceBus
                          
Outputs                 : {}
OutputsString           :  

Please help.

Thanks
Deepak Sanghi

**Comment by sachinma** [comment]
@dewanymca can you confirm is it due to the fact that your template file contains comments? We are working on adding support for template file containing comments which we hope to deploy by next week. In the meantime as a work-around you can remove any comments from your file. @ds-ms who is looking at it.

**Comment by dewanymca** [comment]
Yes,it was because of comments only. Let me know once fix is deployed.

**Comment by ds-ms** [comment]
https://github.com/Microsoft/vsts-tasks/pull/4344 

This issue has been fixed. Will be rolled out in a couple of weeks.
