### ISSUE TITLE
Upgrading Azure Powershell to v4 breaks azure powershell task

### ISSUE THREAD

**Issue by edtheshed** [Microsoft/vsts-tasks#4346]
As detailed here:

https://github.com/Azure/azure-powershell/blob/preview/documentation/release-notes/migration-guide.4.0.0.md#breaking-changes-to-profile-cmdlets

v4 has a breaking change

**Comment by arjgupta** [comment]
Hi @edtheshed , a fix has been applied for this, and will be rolled out in the next couple of days

**Comment by mvvsubbu** [comment]
This issue is being addressed as part of the https://github.com/Microsoft/vsts-tasks/pull/4328 and it will be deployed in couple of weeks,
