### ISSUE TITLE
Feature Request: Publish Artifact Task - Multiple Threads

### ISSUE THREAD

**Issue by ArieHein** [Microsoft/vsts-tasks#4348]
Since under the hood, the Publish Artifact task is using Robocopy to copy the artifacts
and since Robocopy has had, for quite some time, the option to use /MT:[n] to do a n-thread copy, it would be great if we could either set it as a property on the task it self in for example the Advanced section (that doesn't exist for this task).

I have a HUGE web site using the Build-Release pipeline. it runs 13-15 min, where 85% of that is just the last step of publishing the artifacts. I can change the Robocopy PowerShell scripts and add the parameter to the command line but it would be better to have a real supported option.

**Comment by ericsciple** [comment]
@vijayma to comment. i believe this is on the backlog.

**Comment by vijayma** [comment]
This is now added to the backlog.

**Comment by ericsciple** [comment]
this is in master and will be rolling out with the next spring. deployment starts next week and continues over the following couple weeks.
