### ISSUE TITLE
DTAExecutionHost.exe, TestExtensionResolver: Failed to load the assembly 'Microsoft.VisualStudio.Utilities.Internal, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

### ISSUE THREAD

**Issue by keustermansk08** [Microsoft/vsts-tasks#4350]
The error in de log files van agent in test server is: DTAExecutionHost.exe, TestExtensionResolver: Failed to load the assembly 'Microsoft.VisualStudio.Utilities.Internal, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

This is the log file in Visual studio team service:
2017-05-18T14:42:25.7047639Z ##[section]Starting: Run Tests **\*test*.dll on TOBWEBT01.anaxis.be
2017-05-18T14:42:25.7047639Z ==============================================================================
2017-05-18T14:42:25.7047639Z Task         : Run Functional Tests
2017-05-18T14:42:25.7047639Z Description  : Run Coded UI/Selenium/Functional tests on a set of machines (using Test Agent)
2017-05-18T14:42:25.7047639Z Version      : 1.0.49
2017-05-18T14:42:25.7047639Z Author       : Microsoft Corporation
2017-05-18T14:42:25.7047639Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=624389)
2017-05-18T14:42:25.7047639Z ==============================================================================
2017-05-18T14:42:25.7047639Z Preparing task execution handler.
2017-05-18T14:42:26.9078908Z Executing the powershell script: F:\agent01\_work\_tasks\RunVisualStudioTestsusingTestAgent_d353d6a2-e361-4a8f-8d8c-123bebb71028\1.0.49\RunDistributedTests.ps1
2017-05-18T14:42:28.5172727Z DistributedTests: Environment WinRm Protocol HTTP.
2017-05-18T14:42:28.5641514Z DistributedTests: Creating run for selected test assemblies with following parameters
2017-05-18T14:42:28.5797750Z DistributedTests: SourceFilter: **\*test*.dll TestCaseFilter: 
2017-05-18T14:42:28.5797750Z DistributedTests: Run title: TestRun_Mercedes-CI_Release-59
2017-05-18T14:42:28.5797750Z DistributedTests: is automated: True
2017-05-18T14:42:28.5797750Z DistributedTests: build location: \\TOBWEBT01.anaxis.be\test\mercedes-commissions
2017-05-18T14:42:28.5797750Z DistributedTests: build id: 5168
2017-05-18T14:42:28.5797750Z DistributedTests: test configuration mapping: 
2017-05-18T14:42:29.5797739Z DistributedTests: Test Run with Id 325 Queued
2017-05-18T14:42:29.8610235Z DistributedTests: Test run '325' is in 'InProgress' state.
2017-05-18T14:42:39.9391638Z DistributedTests: Test run '325' is in 'Aborted' state.
2017-05-18T14:42:49.9548106Z ##[warning]DistributedTests: Test run is aborted. Logging details of the run logs.
2017-05-18T14:42:50.0173151Z ##[warning]DistributedTests: New test run created.
2017-05-18T14:42:50.0173151Z Test Run queued for Project Collection Build Service (tobius).
2017-05-18T14:42:50.0173151Z 
2017-05-18T14:42:50.0173151Z ##[warning]DistributedTests: Test discovery started.
2017-05-18T14:42:50.0173151Z ##[warning]DistributedTests: Test Run Discovery Aborted . Test run id : 325
2017-05-18T14:42:50.0173151Z ##[warning]DistributedTests: UnExpected error occured during test execution. Try again.
2017-05-18T14:42:50.0173151Z ##[warning]DistributedTests: Error : No tests were discovered from the specified test sources
2017-05-18T14:42:50.0173151Z 
2017-05-18T14:42:50.0173151Z ##[warning]DistributedTests: Test run aborted. Test run id: 325
2017-05-18T14:42:50.0173151Z ##[error]System.Exception: The test run was aborted, failing the task.
2017-05-18T14:42:50.0329356Z ##[error]PowerShell script completed with 1 errors.

**Comment by nigurr** [comment]
Hi,

Please attach your DTAExecutionHost.exe.log file.

**Comment by keustermansk08** [comment]
this is de DTAExecutionHost.exe.log file:

I, 5696, 1, 2017/05/18, 16:33:11.308, 9198147924, DTAExecutionHost.exe, Main.TryReadAndCacheVssCredentials Acquiring the Token Info
I, 5696, 1, 2017/05/18, 16:33:11.324, 9198390346, DTAExecutionHost.exe, Communicating to the Token Servicehttps://tobania.visualstudio.com
W, 5696, 1, 2017/05/18, 16:33:11.371, 9199019133, DTAExecutionHost.exe, Service task failed. Retry attempt 10.
I, 5696, 1, 2017/05/18, 16:33:14.418, 9242609625, DTAExecutionHost.exe, Closing the Token Service
I, 5696, 1, 2017/05/18, 16:33:14.589, TOBWEBT01\DTAExecutionHost, ExecutionTaskStateModel.GetExecutionAdapter : Initializing VstestAdapter.
I, 5696, 1, 2017/05/18, 16:33:14.589, TOBWEBT01\DTAExecutionHost, ExecutionTaskStateModel.Start : Starting to monitor tasks
V, 5696, 1, 2017/05/18, 16:33:14.589, TOBWEBT01\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [https://tobania.visualstudio.com/_apis/test/Agents/22/Commands/0] (GET)0[test]
I, 5696, 1, 2017/05/18, 16:33:14.918, 9249750809, DTAExecutionHost.exe, ********************************************************************
I, 5696, 1, 2017/05/18, 16:33:14.918, 9249752383, DTAExecutionHost.exe, Main.InitializeAndStartExecutionHost. ExecutionHost has been started
Web method response: [https://tobania.visualstudio.com/_apis/test/Agents/22/Commands/0] (GET)0[test] 413 ms
V, 5696, 7, 2017/05/18, 16:33:15.183, TOBWEBT01\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 5696, 7, 2017/05/18, 16:33:15.183, TOBWEBT01\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 5696, 7, 2017/05/18, 16:33:15.183, TOBWEBT01\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 3000 milliseconds.
V, 5696, 3, 2017/05/18, 16:33:18.199, TOBWEBT01\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [https://tobania.visualstudio.com/_apis/test/Agents/22/Commands/0] (GET)0[test]
Web method response: [https://tobania.visualstudio.com/_apis/test/Agents/22/Commands/0] (GET)0[test] 196 ms
V, 5696, 8, 2017/05/18, 16:33:18.386, TOBWEBT01\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 5696, 8, 2017/05/18, 16:33:18.386, TOBWEBT01\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 5696, 8, 2017/05/18, 16:33:18.386, TOBWEBT01\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 9000 milliseconds.
V, 5696, 4, 2017/05/18, 16:33:27.402, TOBWEBT01\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [https://tobania.visualstudio.com/_apis/test/Agents/22/Commands/0] (GET)0[test]
Web method response: [https://tobania.visualstudio.com/_apis/test/Agents/22/Commands/0] (GET)0[test] 720 ms
V, 5696, 7, 2017/05/18, 16:33:28.121, TOBWEBT01\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
V, 5696, 7, 2017/05/18, 16:33:28.121, TOBWEBT01\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [https://tobania.visualstudio.com/_apis/test/Agents/22/Commands/1] (GET)1[test]
I, 5696, 4, 2017/05/18, 16:33:28.121, TOBWEBT01\DTAExecutionHost, ExecutionTaskStateModel.RunStateTransitionsAsync : Handle transition between states
I, 5696, 4, 2017/05/18, 16:33:28.121, TOBWEBT01\DTAExecutionHost, ExecutionTaskStateModel.Initialize : Initializing the execution host.
V, 5696, 4, 2017/05/18, 16:33:28.121, TOBWEBT01\DTAExecutionHost, ExecutionTaskStateModel.GetTask : Querying the server for a new task. Current State of Execution Host: Waiting
Web method running: [https://tobania.visualstudio.com/_apis/test/Slices?testAgentId=22] (GET)Slices[test]
Web method response: [https://tobania.visualstudio.com/_apis/test/Slices?testAgentId=22] (GET)Slices[test] 239 ms
V, 5696, 4, 2017/05/18, 16:33:28.434, TOBWEBT01\DTAExecutionHost, ExecutionTaskStateModel.IsValidTask : Validating received slice of type Discovery.
V, 5696, 4, 2017/05/18, 16:33:28.434, TOBWEBT01\DTAExecutionHost, ExecutionTaskStateModel.GetExecutionTask : Executing the new task obtained from the server.
V, 5696, 4, 2017/05/18, 16:33:28.434, TOBWEBT01\DTAExecutionHost, VstestAdapter.ExecuteAsync : Starting Execution
V, 5696, 4, 2017/05/18, 16:33:28.449, TOBWEBT01\DTAExecutionHost, SourceFilter.Initialize : Initializing new filter instance with the filter string.
V, 5696, 4, 2017/05/18, 16:33:28.465, TOBWEBT01\DTAExecutionHost, SourceFilter.FilterSources : Source Filtering invoked.
V, 5696, 4, 2017/05/18, 16:33:28.465, TOBWEBT01\DTAExecutionHost, SourceFilter.GetFilteredSources : Starting filtering of test sources.
V, 5696, 4, 2017/05/18, 16:33:28.465, TOBWEBT01\DTAExecutionHost, SourceFilter.GetFilteredSources : Filtering of test sources completed.
V, 5696, 4, 2017/05/18, 16:33:28.465, TOBWEBT01\DTAExecutionHost, SourceFilter.FilterSources : Source Filtering completed.
V, 5696, 4, 2017/05/18, 16:33:28.496, TOBWEBT01\DTAExecutionHost, Discovery.Discovery : Creating new Discovery instance.
V, 5696, 4, 2017/05/18, 16:33:28.527, 9444605277, DTAExecutionHost.exe, TestPluginCache: Creating the plugin discoverer.
V, 5696, 4, 2017/05/18, 16:33:28.527, 9444612360, DTAExecutionHost.exe, TestPluginCache: Discovering the extensions using extension path.
V, 5696, 4, 2017/05/18, 16:33:28.746, 9447696480, DTAExecutionHost.exe, TestPluginCache: Discovered the extensions using extension path ''.
V, 5696, 4, 2017/05/18, 16:33:28.746, 9447855435, DTAExecutionHost.exe, TestPluginCache: Discoverers are 'Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration.MSTestDiscoverer, Microsoft.VisualStudio.TestPlatform.Extensions.VSTestIntegration, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a,Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension.TestDiscoverer, Microsoft.VisualStudio.TestTools.CppUnitTestFramework.CppUnitTestExtension, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
V, 5696, 4, 2017/05/18, 16:33:28.746, 9447857283, DTAExecutionHost.exe, TestPluginCache: Executors are 'executor://MSTestAdapter/v1,executor://CppUnitTestExecutor/v1,executor://UAPCppExecutorIdentifier'.
V, 5696, 4, 2017/05/18, 16:33:28.746, 9447858045, DTAExecutionHost.exe, TestPluginCache: Setting providers are 'DataCollectionRunSettings,RunConfiguration,MSTest'.
V, 5696, 4, 2017/05/18, 16:33:28.746, 9447858691, DTAExecutionHost.exe, TestPluginCache: Loggers are 'logger://Microsoft/TestPlatform/ConsoleLogger/v1,logger://Microsoft/TestPlatform/TfsLogger/v1,logger://Microsoft/TestPlatform/TrxLogger/v1'.
I, 5696, 4, 2017/05/18, 16:33:28.762, 9447986006, DTAExecutionHost.exe, TestPluginManager.CreateTestExtension: Attempting to load test extension: Microsoft.VisualStudio.TestPlatform.Extensions.RunConfigurationSettingsProvider
V, 5696, 4, 2017/05/18, 16:33:28.777, TOBWEBT01\DTAExecutionHost, VstestAdapter.ExecuteAsync : Returning
V, 5696, 4, 2017/05/18, 16:33:28.777, TOBWEBT01\DTAExecutionHost, Discovery.Run : Discovery run invoked.
I, 5696, 4, 2017/05/18, 16:33:28.793, TOBWEBT01\DTAExecutionHost, DiscoverTests.PerformDiscovery : Performing discovery for tests
V, 5696, 4, 2017/05/18, 16:33:28.793, TOBWEBT01\DTAExecutionHost, TestCaseFilter.TestCaseFilter : Creating new Filter instance.
V, 5696, 4, 2017/05/18, 16:33:28.793, TOBWEBT01\DTAExecutionHost, TestCaseFilter.Initialize : Initializing new filter instance with the filter string.
I, 5696, 4, 2017/05/18, 16:33:28.793, TOBWEBT01\DTAExecutionHost, DiscoverTests.PerformDiscovery : Initializing the source filter with filter text: **\MercedesTestAutomation.dll
V, 5696, 4, 2017/05/18, 16:33:28.793, TOBWEBT01\DTAExecutionHost, SourceFilter.Initialize : Initializing new filter instance with the filter string.

**Comment by nigurr** [comment]
@keustermansk08 Hi, can you please attach the file? The message log is incomplete.

Can you try running this command in your test agent machine `vstest.console.exe /ListTests:<YOUR TEST DLL PATH>`.
if you are using "Any Test adapters", make sure they are copied to test agent machines.

**Comment by keustermansk08** [comment]
http://prntscr.com/fatlj3

**Comment by nigurr** [comment]
@keustermansk08 that clearly indicates, there are missing "Any custom test adapters" which you are using. If you have custom adapters, can you copy them to the machine and discover tests `vstest.console.exe /ListTests:<YOUR TEST DLL PATH> /TestAdapterPath:<YOUR ADAPTER FOLDER>`

**Comment by acesiddhu** [comment]
@keustermansk08 we are closing the issue. let us know if it is still a blocker
