### ISSUE TITLE
ARM Template validation fails with Error: [object Object].

### ISSUE THREAD

**Issue by bvirkler** [Microsoft/vsts-tasks#4351]
Using the Azure Resource Group Deployment task (version 2.1.0) in validation mode.  When validation fails, the result is the unhelpful message

    2017-05-18T19:51:49.7809047Z ##[error]Template validation failed. Error: [object Object].

**Comment by ds-ms** [comment]
@bvirkler you could enable debug as true, as workaround to see the response
