### ISSUE TITLE
Returning a partially succeeded taskresult

### ISSUE THREAD

**Issue by ptoonen** [Microsoft/vsts-tasks#436]
If I understand https://github.com/Microsoft/vso-agent-tasks/blob/master/docs/authoring/commands.md correctly, logging a ##vso[task.complete result=SucceededWithIssues;] should make the task fail, this doesn't seem to happen however.

Is there any way to 'partially fail' a task?

**Comment by chrisrpatterson** [comment]
Ting?

**Comment by ptoonen** [comment]
Although I haven't been able to test this with the 2015.1 RC1 version, do you have any news on this issue?

**Comment by TingluoHuang** [comment]
This should be fixed now.
