### ISSUE TITLE
VS2017 Hosted Agent: SQL Server Data Tools

### ISSUE THREAD

**Issue by OrestTkachuk** [Microsoft/vsts-tasks#4362]
I've found closed issue [4028](https://github.com/Microsoft/vsts-tasks/issues/4028), but could you please provide path to SQL Server Data Tools? I've tried following configuration for SqlPackage capability:

- C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130\SqlPackage.exe
- C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130
- C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC
- C:\Program Files (x86)\Microsoft SQL Server\130\DAC\bin\SqlPackage.exe
- C:\Program Files (x86)\Microsoft SQL Server\130\DAC\bin

Build fails with error message: "Unable to find the location of Dac Framework (SqlPackage.exe) from registry on machine TASKAGENT9-0001".

**Comment by kidfreeze25** [comment]
SqlPackage.exe is currently located at "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130\SqlPackage.exe" on the Hosted VS2017 agent.

**Comment by mvvsubbu** [comment]
We have a different issue for the same, I am closing this issue, please follow this issue: https://github.com/Microsoft/vsts-tasks/issues/4338 for updates

**Comment by bryanmacfarlane** [comment]
I added a cmdline line task with:
cmd: dir
arguments: /s sqlpackage.exe
(advanced)working dir: C:\

I ran the build against the VS2017 queue (under options):

It's output was:

```
==============================================================================
Task         : Command Line
Description  : Run a command line with arguments
Version      : 1.1.3
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
==============================================================================
dir /s SqlPackage.exe
 Volume in drive C has no label.
 Volume Serial Number is 2C9B-8253
 Directory of c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130
03/01/2017  04:48 PM           143,040 sqlpackage.exe
               1 File(s)        143,040 bytes
```

Does that help you?

**Comment by bryanmacfarlane** [comment]
@OrestTkachuk - closing this again.  I just wanted to illustrate how you can use the system itself to answer questions like that.  hth.

**Comment by OrestTkachuk** [comment]
@bryanmacfarlane thanks for your response. As I mentioned before, I tried 'c:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130' path and the result was the same. I am waiting for the resolution of the #4338.

**Comment by bryanmacfarlane** [comment]
@OrestTkachuk - did you pick the VS2017 queue on the options tab?  The hosted pool queue only has 2015 which would be why it didn't find it.

**Comment by OrestTkachuk** [comment]
@bryanmacfarlane - I'm using Hosted VS2017 agent queue. I've attached configuration from the options tab and user, system capabilities from agent configuration.

- ![agent configuration](https://cloud.githubusercontent.com/assets/22443407/26308408/c5c25a58-3f01-11e7-8196-52f7a9ac0916.png)
- ![user capabilities](https://cloud.githubusercontent.com/assets/22443407/26308551/6cea4002-3f02-11e7-86b8-6ae86e124c76.png)
- ![system capabilities png](https://cloud.githubusercontent.com/assets/22443407/26308550/6ce8d794-3f02-11e7-8de0-325fea2ce97e.png)
-

**Comment by bryanmacfarlane** [comment]
@OrestTkachuk - OK.  SqlPackage is there per my dir /s output.  Also, don't rely on capabilities as sqlpackage isn't registered as a capability.  Have you tried to call it directly to prove it?  I believe the task isn't finding it via registry (issue you reported) which doesn't mean it isn't there :)  You question was where is it and dir /s answers the question but doesn't fix the task.

**Comment by OrestTkachuk** [comment]
@bryanmacfarlane - OK, thank you for the explanation and the example of using Command Line build step, it will help me in further development!

**Comment by sandorfr** [comment]
@bryanmacfarlane the sqlpackage version in the visual studio folder seems to be is a legacy version [(as explained here)](https://blogs.msdn.microsoft.com/ssdt/2016/06/30/changes-to-ssdt-and-sqlpackage-exe-installation-and-updates/) and with it we can run into [azure deployment issues](https://blogs.msdn.microsoft.com/azuresqldbsupport/2017/09/19/deployment-fails-with-unable-to-connect-to-master-or-target-server-mydb_svr-you-must-have-a-user-with-the-same-password-in-master-or-target-server-mydb-db/).

My understanding is that the hosted images do not include DacFramework.msi and as such do not contain the up to date standalone sqlpackage.exe. I feel like it should be included, or better we should have a tool installer task which would also put the selected version of sqlpackage in the path. 

I was about to give it a go but, there no easy constant point to get the binaries from. The only way to get the current version is through Microsoft download, The other option I would have liked better if this nuget package `https://www.nuget.org/packages/Microsoft.Data.Tools.Msbuild/`. However it is already lagging one version behind. Sadly https://www.nuget.org/packages/Microsoft.SqlServer.DacFx.x64/ which seems up to date only contains the libraries but not the executable. 

If you have any insights on the subject I'd be happy to submit a task around that (or add it to one of our extensions).

**Comment by Ajay-MS** [comment]
@sandorfr 

In hosted agent, 
Path of SQLPackage.exe in visual studio folder as follow (Legacy) 
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\130\SqlPackage.exe

Path of SQLPackage.exe with SQL Server ( Latest ) 
C:\Program Files (x86)\Microsoft SQL Server\140\Dac\bin\SqlPackage.exe 

We have logic in task to select latest version of SQLPackage.exe  among VS, SQL server and DacFx during the execution. So latest version of SQLPackage.exe should be ideally selected. And you task should have been executed with version 140 instead of 130. 

If that's not working for you please share logs, we will look into issue. 

Yes I am agree with you that latest version of DacFx should be installed to hosted agent as we gets frequent updates on DacFx. I will check this and will update you on timelines regarding this.

**Comment by sandorfr** [comment]
Yes it should definitely be up to date because Azure SQL Team expects it to be up to date: 
![image](https://user-images.githubusercontent.com/2660262/35210972-7f29de50-ffa8-11e7-9d66-053aae4a975a.png)

I still think that a tool installer would ease the usage as it would make it easier for people using on premise agent to be up to date and it could put the right version in the path. 

Regarding the issue it is not related to you task directly but on the one we are developing (which support multiple dacpac deployment). I guess we are not up to date on the selection of the appropriate location. I know where to look thanks to you :)

**Comment by sandorfr** [comment]
@Ajay-MS I tried the path you indicated and it does not exist on  hosted 2017 agents (EAU region in the present case). It seems to be: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140\SqlPackage.exe`

**Comment by Ajay-MS** [comment]
Hello sandorfr

**Available paths for SQLPackage.exe in Hosted 2017 Agent** 
* C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140\SqlPackage.exe
* C:\Program Files\Microsoft SQL Server\140\DAC\bin\SqlPackage.exe

**Available paths for SQLPackage.exe in Hosted Agent** 
* C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\SQLDB\DAC\140\SqlPackage.exe 
* C:\Program Files\Microsoft SQL Server\140\DAC\bin\SqlPackage.exe

**Comment by soccerjoshj07** [comment]
Is there any updates on this? I have SSDT 2017 installed on a build server as a private agent. SQLPackage.exe is not added as a capability even though SSDT 2017 is installed. I tried manually adding the sqlpackage.exe location to the PATH system environment variables and that did not help either. Installing SSDT 2015 adds the SQLPackage.exe as a capability, but not SSDT 2017. The above proposed solution does not help as you need the sqlpackage capability for an Azure Database deploy task.

**Comment by bojingo** [comment]
I have private build agents that for some reason just got the "150" DAC tools installed on half of them but not the other half. These agents all have multiple versions of the DAC tools, but the vsts task seems to just pick the newest, *even though for the agents with the newest it doesn't work*.

Please, please, **please add an option to the vsts task to explicitly specify which version of the DAC tools to use**. If I have 130, 140, and 150 in the Visual Studio install path, and my DACPAC only deploys successfully with 140, let me specify that!
