### ISSUE TITLE
Azure App Service Deployment: Linux preview deployment issue

### ISSUE THREAD

**Issue by hoetz** [Microsoft/vsts-tasks#4366]
I am trying to make sense of the deployment task when it comes to deploying a .net Core 1.1 web app to a Azure App Service Linux plan. I have set up the azure web app with the default container settings (built-in)
![image](https://cloud.githubusercontent.com/assets/3835948/26257570/fd809c5e-3c75-11e7-8f52-2cacf8a0702c.png)
Now I want to configure the VSTS deployment task and I am stuck here. I have no clue what to put in there. I know this is preview but maybe anyone can give me a hint.
![image](https://cloud.githubusercontent.com/assets/3835948/26257514/c7006be6-3c75-11e7-8736-978fde9367dc.png)

**Comment by azooinmyluggage** [comment]
For built in source the deployment to Web App on Linux will be similar to that of an App service. You will have to build the .NET Core app (restore, build, publish commands) and then use the VSTS App service deploy task.
There is one glitch we are trying to fix. Right now we detect if the app is an App service or Web app on Linux and based on that we change the UI of the task. If you are using built in source then switch to an app service in the dropdown (app service name dropdown) and then type or paste the name of web app on linux.
![image](https://cloud.githubusercontent.com/assets/6857119/26259391/6c17a6f6-3ce6-11e7-94de-ab56c2caaa0e.png)

If you plan to use Docker Hub or private registry then follow the steps in the blog. https://blogs.msdn.microsoft.com/visualstudioalm/2017/05/10/use-azure-portal-to-setup-continuous-delivery-for-web-app-on-linux/

**Comment by hoetz** [comment]
I am still not sure what to type into Registry & Repository. From what I see you have to use containers when doing App Service on Linux so I selected built-in as an image source. When I just type "foobar" into the fields the task starts, the app builds and deploys to the linux web app but nothing happens. I am missing something here and it's got to do with containers :)

**Comment by azooinmyluggage** [comment]
**Built-in Source**
When using built-in source the container deployment is done without exposing its complexity to the user.
That is why I said the deployment is done exactly like App service. You will have to build the .NET Core app (restore, build, publish commands) and then use the VSTS App service deploy task. Right now we detect if the app is an App service or Web app on Linux and based on that we change the UI of the task. If you are using built in source then switch to an app service in the dropdown (app service name dropdown) and then type or paste the name of web app on linux.

We will fix the issue in our task shortly.

**Docker Hub and Private Container registry.**
The UI you see in the VSTS task right now is tailored towards the scenario when your Web App on Linux is configured for Docker Hub or Private Registry source.
The blog link I shared explains how to setup build and release for Web App on Linux by using Docker Hub and Private Container registry.
You can create an Azure Container Registry https://docs.microsoft.com/en-us/azure/container-registry/container-registry-get-started-portal
And then use it with Web App on Linux https://docs.microsoft.com/en-us/azure/app-service-web/app-service-linux-using-custom-docker-image
The values you enter while configuring web on Linux to use Private registry is the value you need to enter in the VSTS task as well.

This is a bit confusing and we are working on fixing this end to end as wel as adding more documentation. If you are still facing issues I will be happy to help by getting in a short call/chat.

**Comment by hoetz** [comment]
Ok, so currently the VSTS tasks does not work with built-in image only with docker hub or private registry, right?

**Comment by hoetz** [comment]
So i think the best way is to use the CI option from the azure portal at the moment. It creates a CI release definition in VSTS. I manually created a build definition in VSTS with dotnet restore, build etc. and I think all the pieces are not there yet for simple deployment to the linux app service. I'll keep an eye on this :)

**Comment by azooinmyluggage** [comment]
The only missing piece is support for built-in source option. The task will support built-in source option shortly.
Is it working end to end for you now?

**Comment by azooinmyluggage** [comment]
The task has the capability and there is a UI issue we need to fix. I gave a work around:
_Right now we detect if the app is an App service or Web app on Linux and based on that we change the UI of the task. If you are using built in source then switch to an app service in the dropdown (app service name dropdown) and then type or paste the name of web app on linux._

**Comment by hoetz** [comment]
I'm sorry, I think I didn't fully understand what you mean by "built in source" ?

**Comment by azooinmyluggage** [comment]
Closing the issue for now.

**Comment by tylerjwatson** [comment]
This issue should absolutely not be closed.  I am having the same drama, and the workaround does not work.  Deploying a VSTS package to linux without going the private registry route to Linux app services is a no-go at the moment.

**Comment by rjstalb** [comment]
The issue still exists as of December...

**Comment by tylerjwatson** [comment]
We ended up migrating off of azure for our entire app stack. It’s a minefield of issues like this and not worth the effort. We now run containers on private infrastructure and it works flawlessly for an eighth of the price.

**Comment by rjstalb** [comment]
Awesome. We are contemplating the same. As for the above, we're temporarily biting the bullet and build/deploying to a windows-hosted service. Would love to hear more about your alt infrastructure... :)

**Comment by chrisrpatterson** [comment]
@tylerjwatson can you be more specific on the issues you hit?  In the case of the Built In source I see it in my account but it is possible there is something wrong in your scale unit or account for this task that we could look into.

![image](https://user-images.githubusercontent.com/185122/33642703-1a8a1f24-da09-11e7-8a9c-92cb374d0a60.png)

**Comment by azooinmyluggage** [comment]
@tylerjwatson @rjstalb 

Thanks for the feedback, sorry to hear that you are still facing issues. 

We have fixed the task with support for built-in source support and a cleaner UI. Check the screenshot posted by @chrisrpatterson. Now both options are supported:

1. Web App on Linux (built-in source)
2. Web App for Containers

I will be happy to help if even the updated task is not resolving your issues. You also mentioned that now you are running containers on private infrastructure. Can you please let me know if you faced issues with Container Registry based deployments as well?
