### ISSUE TITLE
AzureRmWebAppDeployment: Web.config doesn't get transformed

### ISSUE THREAD

**Issue by LarssonOskar** [Microsoft/vsts-tasks#4372]
Hi!
I'm using the AzureRmWebAppDeployment task (version 3) and trying to transform my Web.config file. The task outputs that everything went fine ("XML Transformations applied successfully") but the Web.config still has the same values as the original. My setup is:

![configtransforms](https://cloud.githubusercontent.com/assets/6553874/26309533/b781fd8a-3efd-11e7-964e-f9f1a54b17a3.PNG)

![environments_vsts](https://cloud.githubusercontent.com/assets/6553874/26309546/be4a0504-3efd-11e7-81ba-76a05c864247.PNG)

And if I preview the transforms in visual studio everything looks good.
Also found a thread on the same topic here: https://social.msdn.microsoft.com/Forums/vstudio/en-US/32b75db8-f6a5-4c5e-9e4e-251d01092b0b/deploy-azure-app-service-3-xml-transformation-does-not-transform-webconfig-on-release-vsts?forum=TFService 

//Oskar

**Comment by mvvsubbu** [comment]
@LarssonOskar,

If you are using MsDeploy Package for deployment, we have added some more guidance on how to get this working in new version of our task 3.3.6 which should reach to your account in a couple of weeks.

I am briefing the same here for you. Can you try these suggestions and let us know?

### To Skip Applying Web.<Env>.Config on your web.config during Msbuild, you need to update your Web.<Env>.Config files

1. Remove the <DependentUpon> tag for each config in the csproj file and rebuild. 
2. Ensure that the config file and transformation files are present in the same folder inside the package.

### To Skip Overriding Connection String value, with default value in the package.

1. ConnectionString attributes in Web.config is parameterized by default. Note that the transformation has no effect on connectionString attributes as the value is overridden during deployment by 'Parameters.xml or 'SetParameters.xml' files. You can disable the auto-parameterization by setting /p:AutoParameterizationWebConfigConnectionStrings=False during MSBuild package generation.

**Comment by LarssonOskar** [comment]
Hi @mvvsubbu and thanks for your reply!
Removing `<DependentUpon>` in the csproj file worked and the task now transforms the configs correctly! :+1:

**Comment by mvvsubbu** [comment]
Thanks for confirming I am going ahead and closing the issue

**Comment by Sclusterstack** [comment]
@mvvsubbu  i have tried all to alternative solution that are explained here. but nothing worked for me and i get error Error: XML transformation error while transforming.

**Comment by christiandersen** [comment]
I moved my web.test.config tranformation file to the root together with the web.config and then it worked. Thanks for this article.
