### ISSUE TITLE
Yaml Build Defintions?

### ISSUE THREAD

**Issue by ncthbrt** [Microsoft/vsts-tasks#4376]
Does this document indicate that a yaml build defintion in vsts is possible/ or in the works? 
https://github.com/Microsoft/vsts-tasks/blob/master/docs/yaml.md

What is the time line on this? And how will it integrate with source control? E.g. will the build server look in the root directory of the repo

**Comment by bryanmacfarlane** [comment]
It's in the works.  Here's an early video of a proto

https://www.youtube.com/edit?o=U&video_id=lkPnv5H2ANI

**Comment by ncthbrt** [comment]
Awesome. Sorry to bother again, but that link doesn't work for me.

**Comment by bryanmacfarlane** [comment]
hmmm.  How about this one?

https://youtu.be/lkPnv5H2ANI

**Comment by ncthbrt** [comment]
Yes that works :)

**Comment by bryanmacfarlane** [comment]
yeah - I copied the edit url the last time :/

**Comment by bryanmacfarlane** [comment]
That video also references tool installers which is a pre-cursor and is in preview now

https://www.youtube.com/edit?o=U&video_id=Ie8EuvqJ0Hg

**Comment by ncthbrt** [comment]
Funnily enough we were also talking about that very same problem this evening.
