### ISSUE TITLE
Problem publishing a custom project with custom bundle and modules in different folder

### ISSUE THREAD

**Issue by jersiovic** [Microsoft/vsts-tasks#4380]
This is how I have organized our folders to keep all our modules for a Project in a repo.

This is the root folder of our submodule repo and its nested folder and relevant files
```
\Orchard2\src\OrchardCore.DistribWebAPI
\Orchard2\src\OrchardCore.DistribWebAPI\Bundles\Directory.Build.props
\Orchard2\src\OrchardCore.DistribWebAPI\Bundles\PCCOM.Distrib.WebAPIBundle\PCCOM.Distrib.WebAPIBundle.csproj
\Orchard2\src\OrchardCore.DistribWebAPI\DistribWebAPI\DistribWebAPI.csproj (this is our startup project)

\Orchard2\src\OrchardCore.DistribWebAPI\Modules\PCCOM.Distrib.WebAPI.Core\PCCOM.Distrib.WebAPI.Core.csproj
D:\PROYECTOS\DistribOrchardWebAPI\Orchard2\src\OrchardCore.DistribWebAPI\Modules\PCCOM.Distrib.WebAPI.Setup\PCCOM.Distrib.WebAPI.Setup.csproj
...
```
This works properly and can be run from VStudio. However when I publish it I get following error:
```
  DistribWebAPI -> D:\PROYECTOS\DistribOrchardWebAPI\Orchard2\src\OrchardCore.DistribWebAPI\DistribWebAPI\bin\Release\netcoreapp1.1\DistribWebAPI.dll
  Copying package assets
D:\PROYECTOS\DistribOrchardWebAPI\Orchard2\src\OrchardCore.DistribWebAPI\Bundles\PCCOM.Distrib.WebAPIBundle\PCCOM.Distrib.WebAPIBundle.csproj : error MSB4057: The target "CopyPackageAssetFiles" does not exist in the project.
```
Maybe it is useful for you to know which is the content of this file \Orchard2\src\OrchardCore.DistribWebAPI\Bundles\Directory.Build.props 
```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="..\..\OrchardCore.Build\OrchardCore.Commons.props" />
</Project>
```
Does it have anything to do with the fact I have the bundle in a subfolder that it is not the default one? I mean other bundles are in OrchardCore folder. I moved it to a different location because I want to keep in the same repo my root project, my bundle project and its specific modules.

Any idea?

**Comment by jersiovic** [comment]
I did the following before publishing, but it didn't solve the problem:
`Orchard2\git clean -xdf`
`Orchard2\src\OrchardCore.DistribWebAPI\git clean -xdf`
`Orchard2\dotnet restore`

**Comment by bryanmacfarlane** [comment]
This doesn't seems like an issue with one of the CI tasks in this repo.   If you can supply which task and your CI build output, reactivate

**Comment by jersiovic** [comment]
Yes you are right, Iddin't noticed I submit my issue to the wrong repo
