### ISSUE TITLE
Docker task not supporting writing output to variable

### ISSUE THREAD

**Issue by devedse** [Microsoft/vsts-tasks#4387]
I created a pull request for Docker to support writing the output of a Docker command to a variable. This can be used to chain Docker commands. (E.g. obtaining all images and then running a docker command to remove them).

Since I have gotten almost no reply's on my PR I decided to create an issue regarding this as well.

All details regarding this are available in the PR: #4005

**Comment by chrisrpatterson** [comment]
We are currently working on more formal support for output variables in vsts tasks.  We expect to ship that soon, so once it is in place you can update your PR and we can take a look at it.

**Comment by devedse** [comment]
@chrisrpatterson, any update on the output variable support yet in VSTS? (Is there a preview available yet :)?)

**Comment by bryanmacfarlane** [comment]
It's coming in the sprint that's just starting to roll out now (119)

**Comment by devedse** [comment]
Great to hear :). Love the work you're doing guys!

**Comment by devedse** [comment]
@bryanmacfarlane @chrisrpatterson , Any update on this yet?

**Comment by bryanmacfarlane** [comment]
Early preview if feature should be rolled out

https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/outputvariable.md

**Comment by devedse** [comment]
@bryanmacfarlane , ah so this still requires some changes in the actual Docker task?

**Comment by ajinkya599** [comment]
Closing as fixed with pull request: #8183 and will be available in the next deployment.
