### ISSUE TITLE
Update azure node modules for vsts agent(private build agent)

### ISSUE THREAD

**Issue by kiransaa** [Microsoft/vsts-tasks#4388]
Hi
the ability to deploy a resource to multiple resourcegroups(https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-manager-cross-resource-group-deployment) was added recently to the azure resource manager but it requires that the powershell azure module be updated to the latest version. This I already did but since the azure resource group deployment task depends on node modules and not powershell I would like to know how to updte the node_modules to the latest version so they can use the latest azure arm api's.

Agent version and platform :
Version of your agent? 2.111.1
OS of the machine running the agent? Windows 2012R2
VisualStudio.com

**Comment by chrisrpatterson** [comment]
@RoopeshNair can you comment on when we will update the resource group to support these new features.

@kiransaa simply updating the node modules is not going to do anything for you unelss you are using one of the generic script options like the Azure CLI or Azure PowerShell

**Comment by kiransaa** [comment]
@chrisrpatterson  - appreciate the quick response. Figured that might be the case but wanted to verify :)....i am using the MS built task not a generic one.
