### ISSUE TITLE
DeployVisualStudioTestAgent task fails on Windows 10 VM

### ISSUE THREAD

**Issue by cmielke** [Microsoft/vsts-tasks#4395]
The DeployVisualStudioTestAgent task is failing when I try to deploy the Visual Studio 2017 test agent to a Windows 10 VM. I just created the VM fresh today, so I know that no other versions of the test agent have ever been installed on it. In the build log, I am seeing the following error message:

**Deployment aborted unexpectedly. This might be due to an unplanned restart of target machine. Consult the logs if any on the target machine to fix the issues and retry the operation.** 

The full log from the first run of the build is here:
[logs_45459.zip](https://github.com/Microsoft/vsts-tasks/files/1025824/logs_45459.zip)

After the first failure, I enabled the system.debug variable and ran the build again. The logs for that run are here:
[logs_45464.zip](https://github.com/Microsoft/vsts-tasks/files/1025845/logs_45464.zip)

On the Windows 10 VM, the only logging I can find is the following error in the Application event log:
![eventviewer](https://cloud.githubusercontent.com/assets/7267334/26407591/37f46002-4061-11e7-8ea1-c32ba633eeb7.JPG)

Please let me know if you need any more information.

**Comment by nigurr** [comment]
@cmielke Can you share the logs from `C:\TestAgent\DTAExecutionHost.exe,log`?

**Comment by cmielke** [comment]
Yes, I am using on-prem TFS. I apologize for not mentioning that in my original message. I was originally having the same issue as #3922, so I manually upgraded the task on a non-production TFS instance using the steps outlined in #3922. If this task is not compatible with Update 1, that is all I need to know. I will wait patiently for Update 2.

**Comment by nigurr** [comment]
@cmielke sorry for the trouble. It's worth waiting for Update 2 and use Deploy Task v2 version. There are no major changes between 2015 Test agent and 2017 Test agent. so you can continue to use Deploy Task v1 with test agent 2015 to run the tests

**Comment by cmielke** [comment]
@nigurr I was trying to upgrade one of my solutions to build with Visual Studio 2017. This solution has Coded UI Tests, which do not seem like they can be run on the 2015 Test Agent. If you can suggest a workaround, that would be great. Otherwise, I will just wait for update 2 before upgrading this build definition to build with 2017. Thanks.

**Comment by nigurr** [comment]
@cmielke Please follow similar to this https://blogs.msdn.microsoft.com/sathar/2016/08/01/running-coded-ui-tests-built-using-visual-studio-2013-with-team-foundation-server-2015/
You need to update the version numbers appropriately.
