### ISSUE TITLE
Manual Intervention always run/cleanup tasks

### ISSUE THREAD

**Issue by damienpontifex** [Microsoft/vsts-tasks#4400]
When a manual intervention step is rejected, it cancels the release entirely. There are some steps we'd like to do as a rollback (e.g. cancel azure deployment slot swap)

I have the Manual Intervention Control Options to 'Continue on error'
And then I have a powershell script in a subsequent Run on agent task that has 'Always run' enabled.

The powershell script checks for the environment status and then either completes or rolls back depending on this. It'd be great if manual intervention allowed later stages to run rather than just failing the entire release and stopping.

Is this possible? Or is there another method to enable a 'cleanup' task on intervention rejection?

**Comment by vithati** [comment]
Hi Damien, We enabled 'Continue on error' support in MI task. It will be available in 2 or 3 weeks. With this if 'Continue on error' enabled and MI rejected, deployment moves forward. But we don't change environment status on MI reject so in your next power shell task you don't know MI/Deployment rejected or not. For this we are adding one more feature. Till then you can call GetRelease Rest API from your powershell script and check status for MI task from environment deployment jobs. Based on status either complete or do roll back.

**Comment by damienpontifex** [comment]
Thanks @vithati 

Do you have a documentation link for that REST call? And also maybe something on how to do that from powershell? I assume I would have an oauth token inside the release I could grab to authenticate and do that also?

**Comment by vithati** [comment]
Rest API Doc: https://www.visualstudio.com/en-us/docs/integrate/api/rm/releases . 
In Phase properties -> Additional options -> Enable Allow scripts to access OAuth token. In power shell script use SYSTEM_ACCESSTOKEN environment variable for authentication while calling rest api. I don't have link to 'Phase conditions' feature work item. This feature available in 1 or 2 months. Once this feature enabled, you can see Phase conditions option in Phase properties. You can specify when to run next phase using phase condition.
