### ISSUE TITLE
Deploy TestAgent” task never finish when Interactive Process is checked

### ISSUE THREAD

**Issue by lei7081** [Microsoft/vsts-tasks#4405]
I am using TFS team service to deploy test agent to on premise Windows 2012 server VM in order to run CodedUI test there. When I uncheck Interactive process, it was deployed fine, but when interactive is checked, the task hangs and never finish. I am using the same credential with Admin privilege for both build agent and test agent (meaning I used same identity in team service UI in the deploy test agent step, and the build agent is configure on another PC with the same identity). The task stuck at "Task 'ConfigureTestAgent' on machine 'xxxxx.xxxxx.com:5986' is taking time. Please Wait".

**Comment by nigurr** [comment]
@lei7081 can you help us with below information?

Are you using On-Prem TFS or VSTS?
TFS version:

can you share the build log?

**Comment by shinydiamond** [comment]
Were you able to resolve the issue. i am in the same boat.

**Comment by lei7081** [comment]
Same process worked on another Azure server, could be the group policy issue, but I was not able to identify the exact problem.

**Comment by nigurr** [comment]
Please refer this blog for more details about reboot scenarios and policy restrictions
https://blogs.msdn.microsoft.com/devops/2017/07/03/deploy-visual-studio-test-agent-task-test-machine-rebooting-scenarios/
