### ISSUE TITLE
Argument access in mocks 

### ISSUE THREAD

**Issue by tojoti** [Microsoft/vsts-tasks#4408]
Hi,

while writing some powershell unit tests for a custom task I tried to access some of the passed arguments inside of the script block of a mock. I managed to get them using the $args variable but I would like to get them by name. Is there a way to do this?

Example:
I want to use a mock instead of
`Invoke-RestMethod -Method GET -Uri $myURL -OutFile $destination`
Which way would you suggest to access $myURL inside of the mock's scipt block?

Thanks!

**Comment by ericsciple** [comment]
pester is a popular unit test library, mocking framework, and test runner for powershell.

this doesn't sound like an issue specific to this repo.
