### ISSUE TITLE
Random failures from FTP task deploying to Azure Web App

### ISSUE THREAD

**Issue by ccit-spence** [Microsoft/vsts-tasks#4416]
I have a Spring Boot application using an executable JAR.  The FTP task randomly fails with the following error.  `[error]upload failed: /site/wwwroot/my-project.jar due to error: Error: read ECONNRESET`

 I can rerun the release and it will work.  No changes to the Release Definition.  Fails 40% of the time.

The FTP task is deploying to Azure using FTPS

**Comment by DavidStaheli** [comment]
Hi @ccit-spence, apologies for the trouble.  I feel your pain.  We are actively working with the Azure Web Apps team to make their FTPS support more reliable.  I hope to have more to report soon.

**Comment by edrohler** [comment]
I am experiencing this same issue as of today, 12/16/2017. I was using ftps and switched back to ftp to see if it works differently not using ftps.

**Comment by madhurig** [comment]
@edrohler: The Azure team was able to detect a server side issue which I believe you are encountering too. They are working on rolling out a fix.

**Comment by awentzel** [comment]
Possibly related to [here](https://github.com/Microsoft/vsts-tasks/issues/5929)

**Comment by edrohler** [comment]
@madhurig Awesome! I have gotten around it by just rerunning the release.

**Comment by joshmgross** [comment]
Closing this issue to clean up the backlog. Reopen this if the issue presents itself again.
