### ISSUE TITLE
DoNotStart parameter for Azure Cloud Service Deployment (New-AzureDeployment)

### ISSUE THREAD

**Issue by xingyu217** [Microsoft/vsts-tasks#4418]
There is the way to specify `-DoNotStart `argument for Azure Cloud Service Deployment (New-AzureDeployment)

**Comment by jaxidian** [comment]
I would love this to be added!

My particular use case is for a queue process job that I'm pre-deploying before later flipping the switch to turn it on. We are maintenance windows at night for deployments but we don't really want to do much work at night, so we prefer to deploy during normal business hours to staging environments and the flip switches at night to swap from staging to production environments. However, with something like a Queue Processor, your staging environment is potentially able to gobble up messages from a queue even when running on a staging server.

We previously solved this by passing the -DoNotStart arg when we were deploying via Jenkins. We're now moving over to VSTS builds but the built-in Task does not allow this. Whether we are given a checkbox to enable this flag or simply a textbox for additional parameters, it sure would be nice if we could do this without dropping down to custom Powershell scripts to accomplish this!

To be clear, when creating a new Service we are given a textbox for add'l parameters but those go to the `New-AzureService` call - nothing channels add'l params to the `New-AzureDeployment` call within the task.

**Comment by RoopeshNair** [comment]
Copied to backlog
