### ISSUE TITLE
If Target Machine has TestAgent and TestPro installed at the same time.  Deployment of TestAgent task fails 

### ISSUE THREAD

**Issue by NikolayKash** [Microsoft/vsts-tasks#4426]
Hi 

Our target machine has Test Agents 2017.2 and Test Professional installed at the same time, DTA can't start as it tries to find Microsoft.VisualStudio.TestPlatform.ObjectModel  using Test Pro path which does not have it

![image](https://cloud.githubusercontent.com/assets/8295880/26620485/b9399490-45eb-11e7-9d3d-5c86c3964e2c.png)

DTA log: 
[DTAExecutionHost.exe.zip](https://github.com/Microsoft/vsts-tasks/files/1040579/DTAExecutionHost.exe.zip)

**Comment by NikolayKash** [comment]
output of VS15 detect 
PS C:\Users\sysadm\Desktop> .\VS15Detect.ps1
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04">
  <S>C:\Program Files\Microsoft Visual Studio\2017\TestAgent</S>
</Objs>
PS C:\Users\sysadm\Desktop>

**Comment by nigurr** [comment]
@NikolayKash, can you install TestPro first and then install Test Agent?
We look for the latest installed VS product.

**Comment by nigurr** [comment]
We are closing this issue as we have internal bug to track the same. It will be fixed in next couple of sprints where we detect the right product instead of latest product.
