### ISSUE TITLE
vsts-npm-auth.exe failed with return code: 1 (VSTS)

### ISSUE THREAD

**Issue by JohnGalt1717** [Microsoft/vsts-tasks#4432]
Hi there, we have a strange problem that started cropping up on Monday of this week with no changes on our end.

We have Telerik npm libraries that we pull we have .npmrc file with the following:

@progress:registry=https://registry.npm.telerik.com/
//registry.npm.telerik.com/:_authToken=<token>

In our build setup we just have npm install.

Rarely this works however most of the time it doesn't with the following error:

d:\a\_tasks\Npm_fe47e961-9fa8-4106-8639-368c022d43ad\0.2.22\Npm\vsts-npm-auth\bin\vsts-npm-auth.exe -NonInteractive -Verbosity Normal -Config d:\a\1\s\.npmrc -TargetConfig d:\a\1\npm\auth.3367.npmrc
vsts-npm-auth v0.23.0.0 
-----------------------
Creating npmrcFile. Path: d:\a\1\npm\auth.3367.npmrc
Failed to get the required authentication tokens for npm. Error: d:\a\_tasks\Npm_fe47e961-9fa8-4106-8639-368c022d43ad\0.2.22\Npm\vsts-npm-auth\bin\vsts-npm-auth.exe failed with return code: 1

**Comment by b-barthel** [comment]
Does the task itself fail, or does it just spit out that error and continue?  I'd expect the vsts auth helper to fail to get credentials for a telerik registry, but our expectation is that it won't fail the overall task (I tried just now and saw the same error in the logs, but the task itself completed successfully).  Are there any other error messages in the log?

**Comment by JohnGalt1717** [comment]
It gets a warning, and the @progress stuff isn't actually ever downloaded thus our build fails on the next step.

I was able to fix this in that npm tacks on a space after the authToken on the same line. Before Vsts-npm-auth must have been triming or didn't care. Now it does as of Tuesday morning and it matters. Finding the character (by dumb luck) and removing it solved it and now the builds go through fine without a warning.

**Comment by alexmullans** [comment]
Can you ensure you're using the latest version of the npm task? It no longer uses the vsts-npm-auth executable and should not have this error. Look for the version selector just below the task name.

**Comment by JohnGalt1717** [comment]
Telerik/Progress put everything on GitHub without security anymore so I don't need to use this anymore so I can't confirm sorry.

**Comment by alexmullans** [comment]
No problem. Thanks for writing back. I'll close this for now.
