### ISSUE TITLE
VSTS Azure Deployment Task Documentation Missing (404)

### ISSUE THREAD

**Issue by pstricker** [Microsoft/vsts-tasks#4434]
Was looking for documentation on the Azure Deployment task and found that the link in VSTS dashboard (see attached) is returning a 404: https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/DeployAzureResourceGroup/README.md
![image](https://cloud.githubusercontent.com/assets/3308247/26642241/4ab66c92-45ea-11e7-8dae-d345710604be.png)

**Comment by sachinma** [comment]
You are using 1.* version of the task (latest is 2.*) and there was a slight rename of the folder structure which caused the break. While we fix the link in the task, for 1.* version, you can consult it here: https://github.com/Microsoft/vsts-tasks/blob/releases/m112/Tasks/DeployAzureResourceGroup/README.md

**Comment by ds-ms** [comment]
Fixed.
