### ISSUE TITLE
AzureAppService: Force use of Kudu

### ISSUE THREAD

**Issue by bvirkler** [Microsoft/vsts-tasks#4435]
Trying to use the Azure App Service Deployment task to deploy a Java war file.  I'm getting an error saying the file has to have a .zip extension.  So I uncheck the "Publish using Web Deploy" option, expecting it to use the Kudu api to just upload the war, but I'm still getting the same error about the .zip extension.  

Are my assumptions around the "Publish using Web Deploy" option incorrect?

**Comment by vincentdass** [comment]
@bvirkler , Can you please share the debug logs ?

**Comment by bvirkler** [comment]
@vincentdass Sorry, how do I get the debug logs?

**Comment by vincentdass** [comment]
@bvirkler , set `system.debug` = true in variable section (as Release Definition variable / Environment variable) and rerun the release.
![image](https://user-images.githubusercontent.com/20121508/26863540-d9be550e-4b70-11e7-98eb-e283e1bb6300.png)

**Comment by vincentdass** [comment]
@bvirkler , Is the issue resolved ? If not resolved, can you please share the debug logs by following the above steps ?

**Comment by vincentdass** [comment]
Closing the thread, as there is no reply from customer.
Please feel free to reopen the thread or create a new one, if required.
