### ISSUE TITLE
Question about VSBuild task

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vsts-tasks#4441]
In the latest version I do see that you used vswhere.exe as the VS Locator. My question is, is there a reason for that, against using using vssetup https://github.com/Microsoft/vssetup.powershell?

Thanks

**Comment by ericsciple** [comment]
No special advantage. I liked the simplicity of calling a command line tool. We need to call vswhere from multiple places: agent for capability scan and 4 tasks msbuild, vsbuild, vstest, xamarinandroid. The pattern of calling a command line tool is most flexible (vstest task is written in typescript).

**Comment by mmajcica** [comment]
As I had the same need in my code (retrieve VS path), I took a peak at your code. Using vssetup PS library turned out to be much more elegant solution in my case. Not only, it is about 5X smaller in size then vswhere thus the size of my build task is drastically smaller.
This means that in the https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Common/MSBuildHelpers/PathFunctions.ps1 the whole function function Get-VisualStudio_15_0 can be removed and the function Get-MSBuildPath can change the following:
```
if (($Version -eq "15.0" -or !$Version) -and # !$Version indicates "latest"
            ($visualStudio15 = Get-VisualStudio_15_0) -and
            $visualStudio15.installationPath) {
```
can change into:
```
# Search for a 15.0 Willow instance.
            if ($Version -eq "15.0" -and ($instance = Get-VSSetupInstance | Select-VSSetupInstance -Version '[15.0,)') -and $instance.installationPath)
```
