### ISSUE TITLE
Question about Runsettings and Timeout

### ISSUE THREAD

**Issue by BogdanVolodarskiy** [Microsoft/vsts-tasks#4443]
Hi!
So, the question: how to disable or increase 30 min timeout of test(it stop without any error after this 30 min) by using .Runsettings file? I tried set 0 in Control options in Timeout field, but it doesn't help. Thanks!
![capture](https://cloud.githubusercontent.com/assets/29121980/26679848/77e952a6-46df-11e7-80e0-34f339a7fa94.PNG)

**Comment by RanjanarMS** [comment]
You can use *.testsetting to override the timeout. This thread will help you on the details https://msdn.microsoft.com/en-us/library/ms243175.aspx

**Comment by BogdanVolodarskiy** [comment]
Thanks! But I already know it. For me it's necessary to use exactly *.runsettings.

**Comment by RanjanarMS** [comment]
Sorry... There is no timeout available with runsettings file ..

**Comment by NikolayKash** [comment]
So Control  Options\timeout field is confusing as default timeout when there is no testsetting specified is 30 minutes.

**Comment by RanjanarMS** [comment]
This is currently not supported. But I am adding this issue to our product backlog.

**Comment by bearkat2173** [comment]
Any update as to when this will be available?
