### ISSUE TITLE
Update NPM to V5

### ISSUE THREAD

**Issue by janpieterz** [Microsoft/vsts-tasks#4444]
The speed benefits are incredible, and there are quite some complaints about the NPM speed currently:
https://github.com/Microsoft/vsts-tasks/issues/553 

More information: https://github.com/npm/npm/releases/tag/v5.0.0

**Comment by chrisrpatterson** [comment]
Currently NPM 5 is not shipped with the node LTS.  As we move to the next Node LTS we will get the version of NPM that matches.

**Comment by bryanmacfarlane** [comment]
Is the request to update the hosted pool image?  (note the agent uses the installed npm on the box so it's not an agent thing)

**Comment by janpieterz** [comment]
Yeah this'd be for the hosted pool image, but I understand the choice for LTS versions!

**Comment by chrisrpatterson** [comment]
@janpieterz as I mentioned in the previous comment we currently keep the pool on the most recent LTS.   We do have a new task in the list called the Node Tool Installer that will let you install an arbitrary version of Node and optionally include the version of NPM that goes along with it.   Putting that in place should let you use any version of Node and NPM that you need.

**Comment by ggirard07** [comment]
Node.js 8.x is now the LTS version since 2017-10-31 but hosted agents still use v6.9.1.
Do you plan to update those anytime soon?
