### ISSUE TITLE
Unable to deploy Test Agent on Azure VM - WinRM issue when using a Private Build Agent

### ISSUE THREAD

**Issue by acosmici** [Microsoft/vsts-tasks#4450]
Hello guys,

I am trying to use a Private Build Agent to deploy Test Agent on Azure VM and run a UI Automatic Test there.
I am receiving the following issue when I am deploying the test agent on Azure VM:

Error occured on 'aamagentvsts1.northeurope.cloudapp.azure.com:5986'. Details : 'Connecting to remote server aamagentvsts1.northeurope.cloudapp.azure.com failed with the following error message : Access is denied. For more information, see the about_Remote_Troubleshooting Help topic.'. For troubleshooting, refer https://aka.ms/remotevstest.

Please note that I don't have this issue when I am trying to have this task running from the Hosted Agent.
I've tested the connectivity (WinRM) to this agent and everything works fine (please see the attachment)

![image](https://cloud.githubusercontent.com/assets/24937249/26715412/52cf3766-477e-11e7-8f98-2ebb8899d149.png)

Could you please help me with this?

Cheers,
Adrian Cosmici

**Comment by RanjanarMS** [comment]
Hope you tried manual WinRM connectivity from the build agent where the task was failing. Can you please get the build logs to investigate further (please set "System.Debug" to true before collecting the logs)

**Comment by RanjanarMS** [comment]
Closing this as we didn't get any response. Please reopen if required
