### ISSUE TITLE
Issues with Nuget pack on VSTS

### ISSUE THREAD

**Issue by kant2002** [Microsoft/vsts-tasks#4454]
I'm having issues packing the Nuget package and change build number using Nuget Packager. My project is MSBuild 15 project and build running on VS2017 hosted agent.
I try following scenarios:
- `Nuget packager` - Verionning scheme Off and passing -Suffix as Nuget parameter
  This produce `The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.`
- `Nuget command` and manually pass -Version in the Nuget arguments
  I get `Unable to cast object of type 'System.String' to type 'NuGet.Frameworks.NuGetFramework'.`

**Comment by alexmullans** [comment]
This looks like an issue with the old version of NuGet (3.3) used by the build tasks. In about 2 weeks, we'll have a new "NuGet" task you can grab from the catalog that supersedes this task and uses NuGet 4.0. The relevant PR is #4397
