### ISSUE TITLE
Azure web app linux deploy to slot

### ISSUE THREAD

**Issue by kevinluvian** [Microsoft/vsts-tasks#4460]
I noticed that there's no option to deploy to slot in azure web app linux in the VSTS
before, I tried to export the json task, and modify it manually to be able to deploy to slot, however, its not working
and then I noticed that it is intended to disable deploy to slot flag by this code
(https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureRmWebAppDeployment/azurermwebappdeployment.ts#L56)
```
        if(webAppKind && webAppKind === "linux") {
            deployToSlotFlag = false;
        }
```

is there any way to deploy to slot for azure web app linux? I think this is an must have features as to remove downtime in the deployment, and its become useless to have staging if we can't deploy to staging in the first place

**Comment by kevinluvian** [comment]
is it a good idea to use slot as production?
so I can just deploy to production and swap it to staging and use staging slot as my endpoint for my domain?

**Comment by azooinmyluggage** [comment]
We are adding support for this feature. In our backlog and coming soon.

**Comment by dikhakha** [comment]
Have added this functionality to AzureRm web app deployment task and it will be available after next deployment.

**Comment by kevinluvian** [comment]
Hi @dikhakha, thank you for the response, however, I can't find the option to deploy to slot, can you please tell me where can I change the setting?

**Comment by dikhakha** [comment]
@kevinluvian Deploy to slot option for Linux apps will be available by default in the next version of Azure RM Deployment task.
