### ISSUE TITLE
NUnit Tests not found when using version VsTask. v2 when using project.json

### ISSUE THREAD

**Issue by madaz** [Microsoft/vsts-tasks#4463]
Im getting the following when using the VsTest task `Version: 2.0.50`

`Warning: The path 'd:\a\1\s' specified in the 'TestAdapterPath' does not contain any test adapters, provide a valid path and try again.`

The reason is the NuGet restore task restores packages to `C:\Users\buildguest\.nuget\packages`

Looking at the logs I see the default setting for the TestAdapters is set to `/TestAdapterPath:"d:\a\1\s"` which is the solution source root

My test library `project.json` looks like

```
{
  "dependencies": {
    "Moq": "4.7.25",
    "NUnit": "3.7.0",
    "NUnit3TestAdapter": "3.7.0"
  },
  "frameworks": {
    "net461": {}
  },
  "runtimes": {
    "win-anycpu": {},
    "win": {}
  }
}
```

If I set the `Path to custom adapters` to `C:\Users\buildguest\.nuget\packages` it works.

Is there a BUILD variable for the user level packages folder?

**Comment by madaz** [comment]
I have opened an issue in the nunit adapter repo as this is probably more their problem as they should be outputing the NUnit3.TestAdapter.dll to the bin folder of the test class libraries, like what MSTestv2 does.

[nunit3adapater issue](https://github.com/nunit/nunit3-vs-adapter/issues/337)

**Comment by madaz** [comment]
I downgraded `NUnit` and `NUnit3.TestAdapter` nuget pkgs to `3.4.1` and the test task works as the NUnit3.TestAdpater.dll is now in the source bin folders.

Closing because the problem is with NUnit, not VsTest task

**Comment by madaz** [comment]
Reopening this issue after comments made by nunit.

Can you expose the buildguest .NuGet packages path as a build variable? Or add that as one of the adpater paths.

**Comment by kaadhina** [comment]
@madaz I hope you are using v2 of the vstest task. This will auto search for the test adapter in the search folder. The expectation is that all dependencies will be present there (In this case, the test adapter is also expected to be there). Then, you do not have to specify anything in the "Path to test adapters" field, and things should just run fine. 
To do this, you can simply add a reference to the nunit adapter in your project, and the adapter dll will get dropped along with the test binaries on build. This is the ideal way to get this working. Thanks.

**Comment by madaz** [comment]
@kaadhina Yes I was using the v2 of the task.  The problem is that the latest NUnit3Adapter nuget package does not place the NUnit3.TestAdapter.dll into the `bin` folders of the projects.  (Please see the comments by the NUnit team on the github  issue I tagged above, that is by their choice to do that, they used to output it to the bin folder) .

The NUnit3.TestAdapter.dll  only gets added to the global user packages folder `C:\Users\buildguest\.nuget\packages` on the build machine.

So the default search location is not finding a match for *.TestAdapter.dll

**Comment by kaadhina** [comment]
Adding a reference in your project, to the testadapter dll, in addition to the framework dll reference that you will already have, will solve this issue.

**Comment by madaz** [comment]
@kaadhina Adding a direct reference to the dll is not an answer as that is part of the nuget package manager and the nunit pkg.  The reference location is going to be different on different machines.

Im using the `project.json` nuget package format.

**Comment by kaadhina** [comment]
@madaz I believe your project should already have a  reference to the NUnit framework package (which will also be a nuget package and you must probably have a package reference to it). Similarly add a reference to the nunit testadapter package as well.

**Comment by OsirisTerje** [comment]
@kaadhina The projects don't need project references to the adapter.  The adapter is a tools package, and there is no need to add it to any projects.  It should stay in the packages folder. The packages folder are searched by Visual Studio, and any TFS build tasks should do the same.  If you're adding an assembly reference to it, then that will be broken with the next update of the adapter, as the path then includes the version number.

**Comment by madaz** [comment]
@kaadhina I do include the `NUnit3TestAdapter` package reference in my `proejct.json`.

This issue description contains a copy of the `project.json` contents.

**Comment by kaadhina** [comment]
Yes, the adapter is just a tool and is not "needed" as a reference. But the task expects all dependencies to be present in the search folder along with the actual test binaries, and adding a reference is the easiest way for you to get the adapter there.
If you want to avoid that, I believe nuget.exe has a command line option to specify the packages folder. You can define a build variable pointing to a custom location and specify that under nuget arguments as -PackagesDirectory FolderPath. And then you can use the same variable to specify custom adapter path under vstest execution options.

**Comment by RanjanarMS** [comment]
Please re-open if needed.
