### ISSUE TITLE
How Docker Push task can be used in conjuction with AWS docker registry?

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/vsts-tasks#4469]
Hello,

AWS Docker Registry does not have static username/password but in fact relies on calling APIs to retriever those which are valid for limited time. My understanding Endpoint definitions do not accept dynamic parameters, neither Docker push task can be customized directly with username/password. Is it possible somehow still use Docker push task somehow?

**Comment by bansalaseem** [comment]
I missed replying on this issue but you can use the steps mentioned here to push the [images ](https://blogs.msdn.microsoft.com/aseemb/2017/08/29/how-to-use-vsts-docker-task-to-push-to-aws-registry/) to aws registry. Please try them out and do let us know in case it does not work.

**Comment by artisticcheese** [comment]
@bansalaseem  This works only for 12 hours. AWS Docker username/password have limited lifetime.

**Comment by bansalaseem** [comment]
Thanks for raising this, I have tagged it as an enhancement and have assigned it to our PM so that he can put it in the backlog with the right priority.

**Comment by cameronattard** [comment]
You could still do it by installing [ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper) on your private agents if your agents have the correct ECR IAM permissions in the instance role.

**Comment by sukoneck** [comment]
Did this ever make it onto a backlog? Any recommendations/workarounds for hosted agents?
