### ISSUE TITLE
Deploy single file to AppService

### ISSUE THREAD

**Issue by phatcher** [Microsoft/vsts-tasks#4477]
Can someone advise on how the best way to deploy a single file to an AppService.

Scenario is a I have two build processes one produces a webjob, the other produces an exe that's going to be invoked; the exe build process is out of my control so I can't easily change it.

So I can have a release that links the two artefacts and deploy the webjob in the normal way, but I can't work out how to get the exe into the AppService.

**Comment by vincentdass** [comment]
@phatcher , currently single file deployment (except zip & war) is not supported.
Can you try to copy the exe file to a empty directory and try deploying the same directory to Azure App Service ?

**Comment by vincentdass** [comment]
@phatcher , is the issue resolved ?

**Comment by vincentdass** [comment]
@phatcher , Closing the thread, as the workaround provided will resolve the issue.
Please feel feel to reopen the thread or create a new one, if required. :)
