### ISSUE TITLE
NUnit System.OutOfMemoryException x64

### ISSUE THREAD

**Issue by BerendWouters** [Microsoft/vsts-tasks#4479]
Our solution uses NUnit 3 (including the TestAdapter), and has two main components: and API and a client.
The API is build in x64 mode, and thus should be tested in x64 mode as well. However, when setting the BuildPlatform in the Reporting options to x64, the tests for the API all fail due to an OutOfMemoryException. The client project doesn't have any issues regarding execution of the tests.

Task: Visual Studio Test
Task version: 1.x
NUnit Adapter Version: NUnit Adapter 3.7.0.0

**Comment by kaadhina** [comment]
@BerendWouters The Build platfor option is simply for reporting purposes, and has got nothing to do with the actual test run. To rule out any issue with the task itself, you can run the vstest.console.exe from command line and report back the result. You can find the full command line along with the options, to be run, from the build logs. 
We can then take it further and investigate the OOM expception.
Thanks.

**Comment by BerendWouters** [comment]
Well, it seems it's something wrong with NUnit itself. Running it on the command line causes the tests failing to load.
`Information: NUnit failed to load d:\a\1\s\`

**Comment by BerendWouters** [comment]
However, this is still annoying that we didn't notice this until today, since the exception doesn't cause the step to fail.

**Comment by kaadhina** [comment]
@jayaranigarg @Shyam-Gupta to help out further

**Comment by Shyam-Gupta** [comment]
@BerendWouters Can you please share the build logs. 
Also let us know the exact command line you used to run the tests and the error message you got.

**Comment by BerendWouters** [comment]
I already sent one to the support team that was assigned to me when I created a ticket via MS Support.

**Comment by Shyam-Gupta** [comment]
@BerendWouters Please let us know the support ticket number so that we can track it and get the logs.

**Comment by dpksinghal** [comment]
closing it on behalf of @Shyam-Gupta
