### ISSUE TITLE
NuGet Packager existing dependency error

### ISSUE THREAD

**Issue by random82** [Microsoft/vsts-tasks#4484]
Hi,

I got a following error when I try to package my binaries on a Hosted VSTS agent
`##[error]'Newtonsoft.Json' already has a dependency defined for 'Microsoft.CSharp'.`

**Comment by chrisrpatterson** [comment]
@alexmullans

**Comment by alexmullans** [comment]
This looks like an issue with the old version of NuGet (3.3) used by the build tasks. In about 2 weeks, we'll have a new "NuGet" task you can grab from the catalog that supersedes this task and uses NuGet 4.0. The relevant PR is #4397
