### ISSUE TITLE
Run Functional Tests Task - Error: Could not load file or assembly 'Microsoft.VisualStudio.Utilities.Internal

### ISSUE THREAD

**Issue by MSTestAuto** [Microsoft/vsts-tasks#4491]
I have been trying to set up automated Coded UI Tests with the new vNext Release - Run Coded UI Tests task. (We had it previously working for older XAML build and with Test Agent/Controller 2013.)

But there is an error when the test is run under Test Plan Test Selection. (Test Assembly works fine. ) Only one test runs out of several and the others are not failed but aborted.

I think the source of the error is this in the Dta Logs:
TelemetrySession: Error in Telemetry for unit test run session : Could not load file or assembly 'Microsoft.VisualStudio.Utilities.Internal, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

I have just installed/updated the Test Agent with the Visual Studio Test Agent Deployment task, which installed the Microsoft Agents for Visual Studio 2015 with Update 3.

This issue is probably related to the one here:
https://github.com/Microsoft/vsts-tasks/issues/4350
I have looked into it, but vstest.console.exe is not installed along with the agent. 

I've attached the full log for Dta:
[DTAExecutionHost.exe.log.txt](https://github.com/Microsoft/vsts-tasks/files/1060895/DTAExecutionHost.exe.log.txt)

Also, here is the logs for the release:
[TFS Release Log.txt](https://github.com/Microsoft/vsts-tasks/files/1060898/TFS.Release.Log.txt)

**Comment by bryanmacfarlane** [comment]
@nigurr - can you find who should look into this?

**Comment by nigurr** [comment]
@MSTestAuto Can you please share your test cases for the test suite/testplan

`https://{tfsinstance}/DefaultCollection/{project}/_apis/test/plans/{plan}/suites/{suite}/testcases`

**Comment by MSTestAuto** [comment]
Not sure what you mean by share the test cases...

Here is the selection for the Test Suites (I only chose a few small ones for now so it runs faster):
![image](https://user-images.githubusercontent.com/29276768/26931036-748c6546-4c5f-11e7-9249-4355754dd5e7.png)

Here is the Test Result:
![image](https://user-images.githubusercontent.com/29276768/26931132-c274c118-4c5f-11e7-9b67-2a428d92abfa.png)

Test Case that failed:
![image](https://user-images.githubusercontent.com/29276768/26931298-43844882-4c60-11e7-8817-e5535fe1c61c.png)

Test Case that passed:
![image](https://user-images.githubusercontent.com/29276768/26931361-88cfd4a6-4c60-11e7-998b-ae94051f3d13.png)

TestMethods:
namespace BackOffice.Web.Test.CodedUI.Start
{
    /// <summary>
    /// Summary description for Start
    /// </summary>
    [CodedUITest]
    public class Start : Helper.TestMethodBase
    {
        [TestMethod]
        public void T55983_TestTemp_Store()
        {
            // Create Credit Sale to make sure the store is pre-selected
            Pages.Main.OpenCreditSales_New_WaitAfter();
            Pages.CreditSales.Assert_DefaultStore();
        }

        [TestMethod]
        public void T55984_UserHQ_TestTemp()
        {
            // Go To Store Setup Page
            Playback.Wait(10000); // First time page access could take extra long time
            Pages.Main.OpenConfigurationGroup();
        }
    }
}

**Comment by MSTestAuto** [comment]
Might be helpful to note that we use an on-premise TFS (not on the cloud).

**Comment by MSTestAuto** [comment]
I tried a little bit with the rest APIs for TFS on powershell, but no luck as it has errors. Don't know if it's a credential issue or I just don't know how to use it properly. But since I don't know anything about rest APIs in general, it might take some time to understand it and troubleshoot it. (Didn't have to worry about these with test controller/agent 2013). Is there any other simpler way?

The test binaries are there in the Test Drop Location. And I know they are there for sure also, because running the test in Test Assembly Test Selection works, just not in Test Plan mode. I need the Test Plan working so that I can see the results in a graph for each Test Suite like how we had it previously working.

**Comment by MSTestAuto** [comment]
@kaadhina 

I figured out a bit on how to work with Rest APIs and the correct URLs.

$resource = 'http://trh-dev-tfs:8080/tfs/DefaultCollection/DotNetRetailSolutions/_apis/test/plans/52397/suites/52398/testcases'

Invoke-RestMethod -Uri $resource -cred $cred | ConvertTo-Json
{
    "value":  [
                  {
                      "testCase":  "@{id=55983; name=; url=http://trh-dev-tfs:8080/tfs/DefaultCollection/_apis/wit/workItems/55983; we
bUrl=http://trh-dev-tfs:8080/tfs/web/wi.aspx?pcguid=6959ad41-4df8-401d-b856-544dfbf9c860\u0026id=55983}",
                      "pointAssignments":  ""
                  },
                  {
                      "testCase":  "@{id=55984; name=; url=http://trh-dev-tfs:8080/tfs/DefaultCollection/_apis/wit/workItems/55984; we
bUrl=http://trh-dev-tfs:8080/tfs/web/wi.aspx?pcguid=6959ad41-4df8-401d-b856-544dfbf9c860\u0026id=55984}",
                      "pointAssignments":  ""
                  }
              ],
    "count":  2
}


$resource = 'http://trh-dev-tfs:8080/tfs/DefaultCollection/DotNetRetailSolutions/_apis/test/plans/52397/suites/52398/testcases/55983'

Invoke-RestMethod -Uri $resource -cred $cred | ConvertTo-Json
{
    "testCase":  {
                     "id":  "55983",
                     "name":  null,
                     "url":  "http://trh-dev-tfs:8080/tfs/DefaultCollection/_apis/wit/workItems/55983",
                     "webUrl":  "http://trh-dev-tfs:8080/tfs/web/wi.aspx?pcguid=6959ad41-4df8-401d-b856-544dfbf9c860\u0026id=55983"
                 },
    "pointAssignments":  [
                             {
                                 "configuration":  "@{id=12; name=Default Test Configuration}",
                                 "tester":  "@{id=e619a77f-27a3-4051-90a5-4c0a50116078; displayName=[User]; uniqueName=[ADUser]; url=http://trh-dev-tfs:8080/tfs/DefaultCollection/_apis/Identities/e619a77f-27a3-4051-90a5-4c0a50116078; imageUr
l=http://trh-dev-tfs:8080/tfs/DefaultCollection/_api/_common/identityImage?id=e619a77f-27a3-4051-90a5-4c0a50116078}"
                             }
                         ]
}


$resource = 'http://trh-dev-tfs:8080/tfs/DefaultCollection/DotNetRetailSolutions/_apis/test/plans/52397/suites/52398/testcases/55984'

Invoke-RestMethod -Uri $resource -cred $cred | ConvertTo-Json
{
    "testCase":  {
                     "id":  "55984",
                     "name":  null,
                     "url":  "http://trh-dev-tfs:8080/tfs/DefaultCollection/_apis/wit/workItems/55984",
                     "webUrl":  "http://trh-dev-tfs:8080/tfs/web/wi.aspx?pcguid=6959ad41-4df8-401d-b856-544dfbf9c860\u0026id=55984"
                 },
    "pointAssignments":  [
                             {
                                 "configuration":  "@{id=12; name=Default Test Configuration}",
                                 "tester":  "@{id=e619a77f-27a3-4051-90a5-4c0a50116078; displayName=[User]; uniqueName=[ADUser]; url=http://trh-dev-tfs:8080/tfs/DefaultCollection/_apis/Identities/e619a77f-27a3-4051-90a5-4c0a50116078; imageUr
l=http://trh-dev-tfs:8080/tfs/DefaultCollection/_api/_common/identityImage?id=e619a77f-27a3-4051-90a5-4c0a50116078}"
                             }
                         ]
}

**Comment by kaadhina** [comment]
Can you please also get the list of points: https://{tfsinstance}/tfs/DefaultCollection/{project}/_apis/test/plans/{plan}/suites/{suites}/points?configuration={configuration}
and mail back the results to devops_tools[at]microsoft[dot]com

**Comment by MSTestAuto** [comment]
@kaadhina 

I couldn't send the email to that address:
"The groups only accept messages from people in their organization or on their allowed senders list, and your email address isn't on the lists."

So, I will post the contents here.

Trying to get the points configuration fails – by name:
$resource = 'http://trh-dev-tfs:8080/tfs/DefaultCollection/DotNetRetailSolutions/_apis/test/plans/52397/suites/52398/points?configuration=Default Test Configuration&api-version=1.0'

Invoke-RestMethod -Uri $resource -cred $cred | ConvertTo-Json

Invoke-RestMethod : {"$id":"1","innerException":null,"message":"Test plan 52397 not found.","typeName":"Microsoft.TeamFoundation.TestManagement.WebApi.TestObjectNotFoundException, Microsoft.TeamFoundation.TestManagement.WebApi, Version=14.0.0.0, Culture=neu
tral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"TestObjectNotFoundException","errorCode":0,"eventId":3000}
At line:7 char:1
+ Invoke-RestMethod -Uri $resource -cred $cred | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand 

By id(I wasn’t sure which one it accepts):
$resource = 'http://trh-dev-tfs:8080/tfs/DefaultCollection/DotNetRetailSolutions/_apis/test/plans/52397/suites/52398/points?configuration=12'

Invoke-RestMethod -Uri $resource -cred $cred | ConvertTo-Json

Invoke-RestMethod : {"$id":"1","innerException":null,"message":"Test plan 52397 not found.","typeName":"Microsoft.TeamFoundation.TestManagement.WebApi.TestObjectNotFoundException, Microsoft.TeamFoundation.TestManagement.WebApi, Version=14.0.0.0, Culture=neu
tral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"TestObjectNotFoundException","errorCode":0,"eventId":3000}
At line:7 char:1
+ Invoke-RestMethod -Uri $resource -cred $cred | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand 

Getting test points itself has an error:
$resource = 'http://trh-dev-tfs:8080/tfs/DefaultCollection/DotNetRetailSolutions/_apis/test/plans/52397/suites/52398/points?api-version=1.0'

Invoke-RestMethod -Uri $resource -cred $cred | ConvertTo-Json

Invoke-RestMethod : {"$id":"1","innerException":null,"message":"Test plan 52397 not found.","typeName":"Microsoft.TeamFoundation.TestManagement.WebApi.TestObjectNotFoundException, Microsoft.TeamFoundation.TestManagement.WebApi, Version=14.0.0.0, Culture=neu
tral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"TestObjectNotFoundException","errorCode":0,"eventId":3000}
At line:7 char:1
+ Invoke-RestMethod -Uri $resource -cred $cred | ConvertTo-Json
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand 

The Test Configurations:
Invoke-RestMethod -Uri $resource -cred $cred | ConvertTo-Json

{
    "value":  [
                  {
                      "id":  2,
                      "name":  "BackOffice Test Configuration",
                      "url":  "http://trh-dev-tfs:8080/tfs/DefaultCollection/DotNetRetailSolutions/_apis/test/Configurations/2",
                      "project":  "@{name=DotNetRetailSolutions; url=http://trh-dev-tfs:8080/tfs/DefaultCollection/_apis/projects/DotNetRetailSolutions}",
                      "description":  "",
                      "lastUpdatedBy":  "@{id=e619a77f-27a3-4051-90a5-4c0a50116078; displayName=[User]; uniqueName=[ADUser]; url=http://trh-dev-tfs:8080/tfs/DefaultCollection/_apis/Identities/e619a77f-27a3-4051-90a5-4c0a50116078; i
mageUrl=http://trh-dev-tfs:8080/tfs/DefaultCollection/_api/_common/identityImage?id=e619a77f-27a3-4051-90a5-4c0a50116078}",
                      "lastUpdatedDate":  "2016-05-18T12:17:48.903Z",
                      "area":  "@{id=0; name=DotNetRetailSolutions}",
                      "revision":  6,
                      "values":  "@{Browser=Internet Explorer 11; OS=Windows 7}",
                      "state":  "inactive"
                  },
                  {
                      "id":  12,
                      "name":  "Default Test Configuration",
                      "url":  "http://trh-dev-tfs:8080/tfs/DefaultCollection/DotNetRetailSolutions/_apis/test/Configurations/12",
                      "project":  "@{name=DotNetRetailSolutions; url=http://trh-dev-tfs:8080/tfs/DefaultCollection/_apis/projects/DotNetRetailSolutions}",
                      "description":  "",
                      "lastUpdatedBy":  "@{id=e619a77f-27a3-4051-90a5-4c0a50116078; displayName=[User]; uniqueName=[ADUser]; url=http://trh-dev-tfs:8080/tfs/DefaultCollection/_apis/Identities/e619a77f-27a3-4051-90a5-4c0a50116078; i
mageUrl=http://trh-dev-tfs:8080/tfs/DefaultCollection/_api/_common/identityImage?id=e619a77f-27a3-4051-90a5-4c0a50116078}",
                      "lastUpdatedDate":  "2016-05-18T12:18:02.9Z",
                      "area":  "@{id=0; name=DotNetRetailSolutions}",
                      "isDefault":  true,
                      "revision":  4,
                      "values":  "@{Browser=Internet Explorer 11; OS=Windows 7}",
                      "state":  "active"
                  }
              ],
    "count":  2
}

**Comment by kaadhina** [comment]
Update: We debugged this and found the discovery is returning lesser number of test methods than present in the dll, and hence the test cases are not run. We are debugging further

**Comment by kaadhina** [comment]
@Shyam-Gupta who is looking into this further.

**Comment by kaadhina** [comment]
This ended up being because of improper filters, got fixed after fixing them. Closing this.
