### ISSUE TITLE
[AzureGroup task] Improve error output for key parser

### ISSUE THREAD

**Issue by danielstocker** [Microsoft/vsts-tasks#4492]
Hi there,

My customer and I were looking at an issue recently where a variable override for an Azure Resource Group deployment task did not seem to work as expected.

This is the error message we saw:
<img width="960" alt="vsts-error-message" src="https://user-images.githubusercontent.com/9444698/26942096-b95046c0-4c78-11e7-8194-08672c4f9d52.PNG">

I noticed that the customer had put -> NEED TO UPDATE <- into some of the variable field that they were overriding in the resource task. 

<img width="581" alt="vsts-variable-input" src="https://user-images.githubusercontent.com/9444698/26942097-b952d82c-4c78-11e7-8373-10cd587e4c2a.PNG">

Here is the parameters that they chose to override:

![vsts-task-resourcegroup-var-override](https://user-images.githubusercontent.com/9444698/26942099-b95512a4-4c78-11e7-903a-9ad8de956dbf.PNG)

This is what we had to do to change them:

![vsts-task-resourcegroup-var-override-fix](https://user-images.githubusercontent.com/9444698/26942098-b953540a-4c78-11e7-972c-9d9ca8718778.PNG)

Once the issue was resolved the reason for it seemed obvious, but it would help if the task could show a list of the keys it has recognised. 

In this "missing quotation marks" scenario the logic in https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureResourceGroupDeployment/operations/ParameterParser.ts seems to split NEED TO UPDATE into several potential values, rendering the result of the parse with empty keys. 

The ask here is to improve the error messaging in some way to make it clearer where empty keys could come from. 

When trying to do the same in PowerShell locally the deployment fails because PowerShell tries to recognise TO UPDATE .... as the start of a new cmdlet which it obviously isn't. So a similar issue but a clearer error message to the user.

**Comment by ds-ms** [comment]
When a value has spaces, it is expected to be enclosed in quotes. We have handled this case in the dialog, you don't need to add quotes explicitly anymore, this won't cause any issues during runtime.

Closing this issue.
