### ISSUE TITLE
Run Distributed Tests: Tests not getting executed

### ISSUE THREAD

**Issue by hubertusgr** [Microsoft/vsts-tasks#4505]
Hi!

I am using the distributed test task to run my ui tests (mstest) on my machines. For some reason only one machine does execute all tests. I use the test plan selection, and use one build that is configured and parameterized so that I can use the multi configuration option to run the same set of tests on different machines.
For some reason I do not get results for all tests on my environments (except the one where everything works!)

The execution DTA logs are attached.

In the results later I see that two of the selected test suites were successfully executed and the test cases of the other suites are there but have "none" as outcome.

[DTAExecutionHost.txt](https://github.com/Microsoft/vsts-tasks/files/1064153/DTAExecutionHost.txt)
[DTAExecutionHost - proper.txt](https://github.com/Microsoft/vsts-tasks/files/1064156/DTAExecutionHost.-.proper.txt)

This is how it looks like on the faulty runs:
![image](https://user-images.githubusercontent.com/22470791/26977474-51a91668-4d28-11e7-94fd-a819872062ef.png)

This is how it should look like:
![image](https://user-images.githubusercontent.com/22470791/26977516-7a57dea0-4d28-11e7-99b5-ccc6df7d5ca4.png)

It does not matter how I trigger the tests on those machines, I have been cloning the build definitions already and running it as a non multi config build and it also does not work...

**Comment by nigurr** [comment]
@hubertusgr did you enable "Distribute tests by number of machines" in Run Functional test task?

**Comment by hubertusgr** [comment]
@nigurr  No I did not enable this, should I?
because I have only one machine inserted.

**Comment by hubertusgr** [comment]
For your info:
Even before I switched over to having one test run with multi configuration, the test runs on the other machines (except the one where it works fine) where not executing all tests.
In the results of the run there are also less trx files attached.
Can you read out anything that might be wrong from the dta logs?

**Comment by nigurr** [comment]
@kaadhina will look into this

**Comment by kaadhina** [comment]
@hubertusgr I'm not sure if i got you right.
If you are trying to execute your test cases once, but distribute them over multiple machines: ensure you enable "Distribute tests by number of machines" to distribute equal number of test cases across the machines you have specified. And provide the logs collected from each of those machines.
If you are trying to run all the test cases multiple times, each time on different machine, by specifying multi-config: what is the issue here? The task would have triggered multiple times, each time with different config value. Provide us the build logs for this if this does not work.
You can mail us at devops_tools[at]microsoft[dot]com with the information.

**Comment by kaadhina** [comment]
Also, there is a new version available for the Deploy test agent task. You can switch to the new one if not already done.

**Comment by hubertusgr** [comment]
About the new version: As far as I know this does not work with on premise before 2017U2 comes out?

About your first question:
We are trying to execute all tests multiple times with different config values. The following screenshot show that we execute three builds at the same time with different configurations pointing to different machines. (The title run tests **\*test.dll is misleading because we do take the tests from a test plan! Also please ignore the one failing at the copy task...)

![image](https://user-images.githubusercontent.com/22470791/27080963-8fb61280-503e-11e7-9f61-66f349794b87.png)

On the machines only on the machine TE06 all tests are actually executed. On the others only 2 or 3 test suites are being executed and then the run states to be done (even if more test suites are selected...)
In the summary you can see that all test cases which should have been executed are actually listed but most of them are never run and can be seen with the outcome others:


![image](https://user-images.githubusercontent.com/22470791/27081095-312a4f00-503f-11e7-8e72-7b4741b40ce8.png)

This is the execution log where all selected tests are getting executed (config that starts with te06)
[DTAExecutionHost - TE06.txt](https://github.com/Microsoft/vsts-tasks/files/1071258/DTAExecutionHost.-.TE06.txt)

These are the others:
[DTAExecutionHost - TE05.txt](https://github.com/Microsoft/vsts-tasks/files/1071264/DTAExecutionHost.-.TE05.txt)
[DTAExecutionHost - TE04.txt](https://github.com/Microsoft/vsts-tasks/files/1071263/DTAExecutionHost.-.TE04.txt)
These are the others:

**Comment by hubertusgr** [comment]
Hi!

I have found one suspicious line in the dta log:
I, 5020, 15, 2017/06/13, 03:13:48.983, VIE1QATC04\DTAExecutionHost, DefaultTestRunEvenHandler.OnTestRunMessage : VstestAdapter.Execution - RunMessage : An item with the same key has already been added.

The following git hub issue seems to have a similar problem:
https://github.com/Microsoft/vsts-tasks/issues/2308

Could it be that I have a similar issue? What is the automated test ID and how can I check if this is not properly set on some tests. (the environment which is working is executing a reduced set of tests as it has a configuration that does not allow all tests to run, this might be the cause why this environment is running through and the other wich execute the full set of tests run into this issue....)

**Comment by kaadhina** [comment]
Hi,
I can see that there is a mismatch in the number of test cases discovered to begin with. One reason I can think of is, the binaries in some machines might be stale. I would suggest you to clean up the test drop locations on all machines and retry. 
The duplicate IDs might have been the issue here. You can check if you have multiple test cases linked to the same test method. In the test plans page on the server, use "add column options" to add Automated test id column to check this. Or you can also simply check the FQDN of the associated test method

**Comment by hubertusgr** [comment]
The number of test cases is mismatching because not all test cases have all 4 configurations assigned. The one that is working has the least number of test cases assigned so if duplicate ids are the issue they must be in those test cases that are not being executed by the working environment. I will report back after checking the linkings...

**Comment by hubertusgr** [comment]
I  have found some issues with double linking and now it seems to be fine and all tests are getting executed.

Thanks for your help here!
