### ISSUE TITLE
Test Run Aborted: Could not load dll

### ISSUE THREAD

**Issue by elangelo** [Microsoft/vsts-tasks#4514]
The test run always gets aborted with : 
2017-06-12T07:14:06.2237765Z ##[warning]DistributedTests: Error : Some tests could not run because all test agents of this testrun were unreachable for long time. Ensure that all testagents are able to communicate with the server and retry again.

Logging into the machine and browsing to c:\testagent i find a log file DTAExecutionHost.exe.log

DTAExecutionHost.exe Error: 0 : Main.InitializeAndStartExecutionHost. Exception occured during initialization/start: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.VisualStudio.TestPlatform.ObjectModel, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Comment by elangelo** [comment]
Weird thing , if I rerun the environment with the test run task in there the run completes succesful.

**Comment by elangelo** [comment]
It never works on a fresh run though. Anyone?

**Comment by elangelo** [comment]
![image](https://user-images.githubusercontent.com/1935881/27166141-fb1718f2-5198-11e7-8914-1fdaefbc70f0.png)

I have now added the Install Test runner and the run tests step twice. The first time it fails like before. The second time it runs just fine. I know you can't really tell from the screenshot but it's just because the second time only part of the tests are passing. The first time the tests never start running.

**Comment by mophdog** [comment]
I get the same behaviour and error in DTAExecutionHost.exe.log
I have not tried to re-deploy and run as part of my process, will test tomorrow if no better advice is given

**Comment by kaadhina** [comment]
Can you please provide us complete build logs (after setting build variable system.debug = true) and the complete log files for DTAExecutionHost.exe.log.
You can mail us at devops_tools[at]microsoft[dot]com

**Comment by elangelo** [comment]
@kaadhina , just send a mail to that address, hope you can pick this up fast.

**Comment by nigurr** [comment]
@elangelo we received the logs. will update

**Comment by mophdog** [comment]
I've sent my logs too, hope they're helpful

**Comment by nigurr** [comment]
@mophdog regarding your issue, there's Test Controller installed on the same machine of Test Agent.
`C:\Program Files (x86)\Microsoft Visual Studio\2017\TestController\Common7\IDE\CommonExtensions\Microsoft\TestWindow`

Test Agent machine shouldn't have any other VS products installed (Test Explorer/Test Controller/VS). It should be an isolated product.
Please uninstall other products and try running.

**Comment by mophdog** [comment]
Thank you @nigurr , I'll talk to my sysadmin about getting a new system set up for running the tests.

**Comment by elangelo** [comment]
@nigurr Have you found any time to have a look at the logs I uploaded? This is issue is still present on our environments.

**Comment by nigurr** [comment]
@elangelo do you have repro machine? We are investigating the same here https://github.com/Microsoft/vsts-tasks/issues/4684

**Comment by elangelo** [comment]
@nigurr Is it possible to schedule a call for this? I can't just give you access to our environments without involving way more ppl and probably we will need to escalate this. Maybe a call might be beneficial before going that route?

**Comment by nigurr** [comment]
@elangelo sorry for the trouble. We are already in touch with few customers who are hitting this issue. We will resolve it as soon as possible.
This is happening randomly and we are unable to repro in our local test infra. Please bear with us. Will be tracking this issue here https://github.com/Microsoft/vsts-tasks/issues/4684
