### ISSUE TITLE
Failed to install 'VisualStudioRemoteDeployer802f87bf-c4d5-45a3-99c1-cce54181142d' from service executable path VisualStudioRemoteDeployer.exe 

### ISSUE THREAD

**Issue by rubenfa** [Microsoft/vsts-tasks#4526]
Hi,

we are struggling with a problem when we try to execute a remote powershelll command on a machine that is out of Windows Domain. We have configured WinRM to use SSL with a self-signed certificate. Indeed we can execute remote scripts with Invoke-Command without problems. But when we use VSTS Remote Powershell Task, it is failing.

Here is the error we are receiving:

```
##[section]Starting: Extraer archivo zip en destino
Preparing task execution handler.
Executing the powershell script: C:\AgenteTFS\_work\_tasks\PowerShellOnTargetMachines_3b5693d4-5777-4fee-862a-bd2b7a374c68\1.0.41\PowerShellOnTargetMachines.ps1
Deployment started for machine: 'machine-name'
Excepción al llamar a "SetRight" con los argumentos "2": "Could not obtain the user information."
 CategoryInfo :NotSpecified: (:) [], MethodInvocationException
 FullyQualifiedErrorId :Exception
 ---> System.Management.Automation.RemoteException: Excepción al llamar a "SetRight" con los argumentos "2": "Could not obtain the user information."
   --- Fin del seguimiento de la pila de la excepción interna ---
   en Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.PowershellExecutor.Invoke(String errorContextMessage, Boolean writeResultToLog, Boolean isCancellable)
   en Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.RemoteDeploymentHelper.InstallServiceInternal(String serviceSourcePath, String serviceName, String destinationFileName)
   en Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.RemoteDeploymentHelper.InstallService(String serviceSourcePath, String serviceName, String destinationFileName)
   en Microsoft.VisualStudio.Services.DevTestLabs.Deployment.Deployment.DeploymentClient.<RunAsync>d__24.MoveNext()
---> (Nº de excepción interna 0) System.Management.Automation.RemoteException: Excepción al llamar a "SetRight" con los argumentos "2": "Could not obtain the user information."<---


Deployment status for machine 'machine-name' : 'Failed'


##[error]System.Management.Automation.RuntimeException: Failed to install 'VisualStudioRemoteDeployer802f87bf-c4d5-45a3-99c1-cce54181142d' from service executable path VisualStudioRemoteDeployer.exe . Consult the logs below:
Excepción al llamar a "SetRight" con los argumentos "2": "Could not obtain the user information."
 CategoryInfo :NotSpecified: (:) [], MethodInvocationException
 FullyQualifiedErrorId :Exception
 ---> System.Management.Automation.RuntimeException: Failed to install 'VisualStudioRemoteDeployer802f87bf-c4d5-45a3-99c1-cce54181142d' from service executable path VisualStudioRemoteDeployer.exe . Consult the logs below:
Excepción al llamar a "SetRight" con los argumentos "2": "Could not obtain the user information."
 CategoryInfo :NotSpecified: (:) [], MethodInvocationException
 FullyQualifiedErrorId :Exception

   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   en System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   en System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   en System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   en System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   en Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.VSTSPowerShellHost.Main(String[] args)
##[error]LegacyVSTSPowerShellHost.exe se completó con código de retorno: -1.
##[section]Finishing: Extraer archivo zip en destino

```

Any help will be apreciatted. 

Best regards

**Comment by chrisrpatterson** [comment]
Are you able to execute those commands from a powershell console on the build machine as the same local windows user as the build agent?

**Comment by rubenfa** [comment]
Yes. I can execute those commands from the local machine and from build machine with a remote session of PowerShell. But when I execute the remote task it fails with the message provided.

Thanks for your help.

**Comment by chshrikh** [comment]
@rubenfa could you please confirm if you are using the admin user to connect to remote machine

**Comment by rubenfa** [comment]
Hi @chshrikh . Thanks for your help.

Yes. The user we are using is an administrator from the remote machine

**Comment by chshrikh** [comment]
@rubenfa please check if given user has permission to run the service on vm. User must have Log on as a service Right on vm

**Comment by rubenfa** [comment]
Well, this permission was not present, but although I have added it, the task is not working. The error is the same.

**Comment by rubenfa** [comment]
Some idea about what could be happening?

**Comment by asranja** [comment]
@rubenfa this issue generally happens when the user doesn't have enough permissions to run as service on the machine. 
You can refer [this](https://technet.microsoft.com/en-us/library/cc794944(v=ws.10).aspx) if you want to know how to add log on as a service right.
Also, if the machine is domain joined, please provide the username as domain\username.

**Comment by vincentdass** [comment]
@rubenfa , does the [workaround](https://technet.microsoft.com/en-us/library/cc794944(v=ws.10).aspx) provided resolved the issue?

**Comment by rubenfa** [comment]
No. Is not working yet.

From host computer I can run this command without problems:

`Invoke-Command -computername COMPUTERNAME -UseSSL –ScriptBlock {Get-Process} -Cred
ential ""
`

That command prompts for user and password. I'm introducing the same user that we have configured in VSTS Remote Powershell Task, and it is working (we receive a list of processes on the remote computer).

I don't believe it is a permission problem.

Best regards.

**Comment by vincentdass** [comment]
@rubenfa , Can you please mail the logs to` RM_Customer_Queries@Microsoft.com`?
We can take this thread offline to quickly unblock you from the issue.

**Comment by briancuster** [comment]
I'm getting a similar error on TFS 2015 with Update 2.  Except it is an access denied error on creating the temporary folder for storing the VisualStudioRemoteDeployer.exe.  Any ideas what could be going on here?

**Comment by vincentdass** [comment]
@briancuster , Can you please share the bebug logs?

**Comment by rubenfa** [comment]
Ok, thanks to @vincentdass it is finally working.

We are performing the release from a domain machine to a machine out of the domain. We were setting username and machine name with the full name. So we were using `machine.ohterdomain.com\user` as credentials and `machine.ohterdomain.com`.  We changed it to `machine\user` and `machine` and now it is working.

Of course, we have changed our certificates too, because we are using SSL. 

Many thanks for your help.

**Comment by Onefox** [comment]
Hi, I have the a simulate setup than @rubenfa and tried the same solutions, but still getting the:
`2017-11-07T14:51:49.1135440Z ##[debug]System.AggregateException: Failed to install 'VisualStudioRemoteDeployerdbab9622-7e92-4555-9281-f06fa1d186f6' from service executable path VisualStudioRemoteDeployer.exe . Consult the logs below:
2017-11-07T14:51:49.1291707Z ##[debug]Access to the path 'VisualStudioRemoteDeployer2f4258e0-7fe9-46da-955a-94c0deb51427' is denied.
2017-11-07T14:51:49.1291707Z ##[debug] CategoryInfo :PermissionDenied: (C:\Windows\DtlD...5a-94c0deb51427:String) [New-Item], UnauthorizedAccessException`
Error.

The local user is local admin.
I use Remote Powershell via HTTP and I tried powershell 5 on the target server.
My build agent is running with a Domain User.

I use <HOSTNAME>\<LocalAdmin> and <HOSTNAME> as machine.

**Comment by rubenfa** [comment]
Have you tried to enable HTTPS? You can do it with a self-signed certificate if you want.  You can follow [this configuration guide](https://4sysops.com/archives/powershell-remoting-over-https-with-a-self-signed-ssl-certificate/)

Best regards.

**Comment by Onefox** [comment]
Thanks for the fast reply.
Sadly the error hasn't changed with HTTPS. I followed the linked guide.

**Comment by rubenfa** [comment]
Are you able to execute remote scripts on the remote machine from console?

**Comment by Onefox** [comment]
I moved to a Domain User now... 
A Workaround for me
Yes i was able to execute remote scripts with the user from another maschine (the agent)
