### ISSUE TITLE
DeleteExistingFiles rule not taking effect when using Azure

### ISSUE THREAD

**Issue by kowsheek** [Microsoft/vsts-tasks#453]
I have build and publish set up for a vNext ASP.Net project to an Azure website.

When deploying the with the `DeleteExistingFiles` flag on, `-enableRule:DoNotDeleteRule` is still being applied:

     $publishProperties = @{ 'WebPublishMethod'='MSDeploy';
                        'MSDeployServiceUrl'=$msdeployurl;
                        'DeployIisAppPath'=$website.Name;
		        'DeleteExistingFiles' = $true;
                        'Username'=$website.PublishingUsername;
                        'Password'=$website.PublishingPassword}

`Executing command ["C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:IisApp='C:\a\b3bf94c5\YakShaving\YakShaving\debug\Publish\wwwroot' -dest:IisApp='dev-yakshaving-ci',ComputerName='https://dev-yakshaving-ci.scm.azurewebsites.net/msdeploy.axd',UserName='$dev-yakshaving-ci',Password='{PASSWORD-REMOVED-FROM-LOG}',IncludeAcls='False',AuthType='Basic' -verb:sync -enableLink:contentLibExtension  -enableRule:DoNotDeleteRule -retryAttempts:2 -disablerule:BackupRule]`

Any help would be great since without deleting the packages (through web publish or manually) on Azure and the site dies on start.

**Comment by chrisrpatterson** [comment]
This looks like a potential bug in the ASP.NET publish module we call which is here https://github.com/aspnet/vsweb-publish.  @sayedihashimi if you seen this issue?  I haven't had a chance to start digging in yet.

**Comment by kowsheek** [comment]
From my skim-over on that repo, it looks like that even though the `DeleteExistingFiles` rule is handled: https://github.com/aspnet/vsweb-publish/blob/99d5cf7039341f81d0461dc86a1f2b617d809ceb/publish-module.psm1#L199 `-enableRule:DoNotDeleteRule` gets readded https://github.com/aspnet/vsweb-publish/blob/99d5cf7039341f81d0461dc86a1f2b617d809ceb/publish-module.psm1#L212 since `'EnableMSDeployBackup' = $false`

**Comment by kowsheek** [comment]
Any updates on this @chrisrpatterson @sayedihashimi?

**Comment by kmkumaran** [comment]
There is a preview version of [msdeploy based website deployment task](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/AzureRmWebAppDeployment) available now. You can take a look and provide us feedback. Kindly drop an email to rm_customer_queries on the domain microsoft dot com to enrol for preview, if you don't see the task.

**Comment by codito** [comment]
Closing this issue as preview task is now available.
