### ISSUE TITLE
Unable to build MSBuild task on Team service

### ISSUE THREAD

**Issue by avikenjale** [Microsoft/vsts-tasks#4531]
I have a  `.net core 1.1` app, which needs to build using msbuild 15.0. When I create Msbuild Task and select version `15.0` either `x64` or `x86` , getting following errors:

>Unable to find MSBuild version '15.0' for architecture 'x86'. Falling back to version '14.0'.
>Unable to find MSBuild version '15.0' for architecture 'x64'. Falling back to version '14.0'.

unable to proceed.

**Comment by bryanmacfarlane** [comment]
See #4361 

Use the VS 2017 Queue from the options tab.

Dupe

**Comment by bryanmacfarlane** [comment]
All the details here:  https://github.com/Microsoft/vsts-tasks/blob/master/docs/vshostedpools.md

We're addressing the usability issue in the sprint rolling out now.
