### ISSUE TITLE
NuGet targets, unable to resolve Microsoft.NETCore.App

### ISSUE THREAD

**Issue by Jonathan34** [Microsoft/vsts-tasks#4533]
Hi,

I followed closely the thread here: https://github.com/Microsoft/vsts-tasks/issues/3311
and it was said that improvement would be made so you could update more quickly the images on the agents, namely VS 2017.

I still cannot use .net core 2.0 in the Hosted VS 2017 as of today although .net core 2.0 preview 1 was released several weeks ago.
I cannot even use the Hosted linux and the official docker image as the Hosted linux agents are not available in my hosted agent pool in my team project (not released yet...).

Could you please clarify the plans?

```
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Unable to resolve 'Microsoft.NETCore.App (>= 2.0.0)' for '.NETCoreApp,Version=v2.0'.

Detected package downgrade: NETStandard.Library from 2.0.0-preview1-25301-01 to 1.6.1 
```

**Comment by bryanmacfarlane** [comment]
The VS2017 hosted pool has VS 2017 with all features installed on it.  The issues from #3311 (latency while in preview going to release) are not relevant since the image now has the full release VS 2017.

I'm adding the packaging team for your nuget issue.

@alexmullans

**Comment by Jonathan34** [comment]
I put a global.json as follow (this is the official sdk for preview 1 release):

```
{
    "sdk": {
        "version": "2.0.0-preview1-005957"
    }
}
```

but the VS 2017 agent still use the 1.0.4 sdk that does not support 2.0 packages.
```
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: NETStandard.Library from 2.0.0-preview1-25301-01 to 1.6.1 
```

So I think VS 2017 image does not natively provide the 2.0 preview 1 sdk.

**Comment by alexmullans** [comment]
@Jonathan34 can you try adding a NuGet Tool Installer task at the beginning of your build that specifies version 4.1.0? I'm wondering if this is a NuGet 4.0 issue.

**Comment by Jonathan34** [comment]
```
remote: 
remote:                    vSTs           
remote:                  vSTSVSTSv        
remote:                vSTSVSTSVST        
remote: VSTS         vSTSVSTSVSTSV        
remote: VSTSVS     vSTSVSTSV STSVS        
remote: VSTSVSTSvsTSVSTSVS   TSVST        
remote: VS  tSVSTSVSTSv      STSVS        
remote: VS   tSVSTSVST       SVSTS        
remote: VS tSVSTSVSTSVSts    VSTSV        
remote: VSTSVST    SVSTSVSTs VSTSV        
remote: VSTSv        STSVSTSVSTSVS        
remote:                VSTSVSTSVST        
remote:                  VSTSVSTs        
remote:                    VSTs    (TM)        
remote: 
remote:  Microsoft (R) Visual Studio (R) Team Services        
remote: 
Receiving objects:   0% (1/527)   
Receiving objects:   1% (6/527)   
Receiving objects:   2% (11/527)   
Receiving objects:   3% (16/527)   
Receiving objects:   4% (22/527)   
Receiving objects:   5% (27/527)   
Receiving objects:   6% (32/527)   
Receiving objects:   7% (37/527)   
Receiving objects:   8% (43/527)   
Receiving objects:   9% (48/527)   
Receiving objects:  10% (53/527)   
Receiving objects:  11% (58/527)   
Receiving objects:  12% (64/527)   
Receiving objects:  13% (69/527)   
Receiving objects:  14% (74/527)   
Receiving objects:  15% (80/527)   
Receiving objects:  16% (85/527)   
Receiving objects:  17% (90/527)   
Receiving objects:  18% (95/527)   
Receiving objects:  19% (101/527)   
Receiving objects:  20% (106/527)   
Receiving objects:  21% (111/527)   
Receiving objects:  22% (116/527)   
Receiving objects:  23% (122/527)   
Receiving objects:  24% (127/527)   
Receiving objects:  25% (132/527)   
Receiving objects:  26% (138/527)   
Receiving objects:  27% (143/527)   
Receiving objects:  28% (148/527)   
Receiving objects:  29% (153/527)   
Receiving objects:  30% (159/527)   
Receiving objects:  31% (164/527)   
Receiving objects:  32% (169/527)   
Receiving objects:  33% (174/527)   
Receiving objects:  34% (180/527)   
Receiving objects:  35% (185/527)   
Receiving objects:  36% (190/527)   
Receiving objects:  37% (195/527)   
Receiving objects:  38% (201/527)   
Receiving objects:  39% (206/527)   
Receiving objects:  40% (211/527)   
Receiving objects:  41% (217/527)   
Receiving objects:  42% (222/527)   
Receiving objects:  43% (227/527)   
Receiving objects:  44% (232/527)   
Receiving objects:  45% (238/527)   
Receiving objects:  46% (243/527)   
Receiving objects:  47% (248/527)   
Receiving objects:  48% (253/527)   
Receiving objects:  49% (259/527)   
Receiving objects:  50% (264/527)   
Receiving objects:  51% (269/527)   
Receiving objects:  52% (275/527)   
Receiving objects:  53% (280/527)   
Receiving objects:  54% (285/527)   
Receiving objects:  55% (290/527)   
Receiving objects:  56% (296/527)   
Receiving objects:  57% (301/527)   
Receiving objects:  58% (306/527)   
Receiving objects:  59% (311/527)   
Receiving objects:  60% (317/527)   
Receiving objects:  61% (322/527)   
Receiving objects:  62% (327/527)   
Receiving objects:  63% (333/527)   
Receiving objects:  64% (338/527)   
Receiving objects:  65% (343/527)   
Receiving objects:  66% (348/527)   
Receiving objects:  67% (354/527)   
Receiving objects:  68% (359/527)   
Receiving objects:  69% (364/527)   
Receiving objects:  70% (369/527)   
Receiving objects:  71% (375/527)   
Receiving objects:  72% (380/527)   
Receiving objects:  73% (385/527)   
Receiving objects:  74% (390/527)   
Receiving objects:  75% (396/527)   
Receiving objects:  76% (401/527)   
Receiving objects:  77% (406/527)   
Receiving objects:  78% (412/527)   
Receiving objects:  79% (417/527)   
Receiving objects:  80% (422/527)   
Receiving objects:  81% (427/527)   
Receiving objects:  82% (433/527)   
Receiving objects:  83% (438/527)   
Receiving objects:  84% (443/527)   
Receiving objects:  85% (448/527)   
Receiving objects:  86% (454/527)   
Receiving objects:  87% (459/527)   
Receiving objects:  88% (464/527)   
Receiving objects:  89% (470/527)   
Receiving objects:  90% (475/527)   
Receiving objects:  91% (480/527)   
Receiving objects:  92% (485/527)   
Receiving objects:  93% (491/527)   
Receiving objects:  94% (496/527)   
Receiving objects:  95% (501/527)   
Receiving objects:  96% (506/527)   
Receiving objects:  97% (512/527)   
Receiving objects:  98% (517/527)   
Receiving objects:  99% (522/527)   
Receiving objects: 100% (527/527)   
Receiving objects: 100% (527/527), 783.88 KiB | 0 bytes/s, done.
Resolving deltas:   0% (0/292)   
Resolving deltas:   4% (13/292)   
Resolving deltas:  11% (35/292)   
Resolving deltas:  15% (45/292)   
Resolving deltas:  16% (47/292)   
Resolving deltas:  17% (50/292)   
Resolving deltas:  18% (54/292)   
Resolving deltas:  20% (60/292)   
Resolving deltas:  24% (72/292)   
Resolving deltas:  27% (80/292)   
Resolving deltas:  28% (84/292)   
Resolving deltas:  29% (87/292)   
Resolving deltas:  31% (91/292)   
Resolving deltas:  34% (100/292)   
Resolving deltas:  38% (111/292)   
Resolving deltas:  40% (118/292)   
Resolving deltas:  42% (123/292)   
Resolving deltas:  43% (128/292)   
Resolving deltas:  44% (131/292)   
Resolving deltas:  45% (132/292)   
Resolving deltas:  46% (137/292)   
Resolving deltas:  47% (140/292)   
Resolving deltas:  48% (142/292)   
Resolving deltas:  51% (149/292)   
Resolving deltas:  52% (153/292)   
Resolving deltas:  53% (156/292)   
Resolving deltas:  54% (159/292)   
Resolving deltas:  56% (165/292)   
Resolving deltas:  58% (170/292)   
Resolving deltas:  59% (175/292)   
Resolving deltas:  60% (176/292)   
Resolving deltas:  61% (179/292)   
Resolving deltas:  62% (183/292)   
Resolving deltas:  63% (184/292)   
Resolving deltas:  64% (187/292)   
Resolving deltas:  65% (192/292)   
Resolving deltas:  66% (194/292)   
Resolving deltas:  67% (197/292)   
Resolving deltas:  69% (202/292)   
Resolving deltas:  70% (207/292)   
Resolving deltas:  71% (209/292)   
Resolving deltas:  72% (211/292)   
Resolving deltas:  73% (215/292)   
Resolving deltas:  75% (219/292)   
Resolving deltas:  78% (229/292)   
Resolving deltas:  79% (232/292)   
Resolving deltas:  80% (235/292)   
Resolving deltas:  81% (237/292)   
Resolving deltas:  82% (241/292)   
Resolving deltas:  83% (243/292)   
Resolving deltas:  84% (246/292)   
Resolving deltas:  85% (249/292)   
Resolving deltas:  87% (255/292)   
Resolving deltas:  88% (258/292)   
Resolving deltas:  89% (261/292)   
Resolving deltas:  90% (263/292)   
Resolving deltas:  91% (268/292)   
Resolving deltas:  92% (270/292)   
Resolving deltas:  93% (273/292)   
Resolving deltas:  94% (275/292)   
Resolving deltas:  95% (279/292)   
Resolving deltas:  96% (282/292)   
Resolving deltas:  97% (286/292)   
Resolving deltas:  98% (287/292)   
Resolving deltas:  99% (290/292)   
Resolving deltas: 100% (292/292)   
Resolving deltas: 100% (292/292), done.
From https://slb-swt-globalrealtime.visualstudio.com/WITSML%20Objects%20Library/_git/WITSMLObjectsLibrary
 * [new branch]      master        -> origin/master
 * [new branch]      netstandard20 -> origin/netstandard20
git checkout --progress --force 027fe7106bc56de70277291717df5e9f6fca00cd
Note: checking out '027fe7106bc56de70277291717df5e9f6fca00cd'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
  git checkout -b <new-branch-name>
HEAD is now at 027fe71... Enforce use of .net core 2.0 sdk
******************************************************************************
Finishing: Get Sources
******************************************************************************
******************************************************************************
Starting: Use NuGet 4.10
******************************************************************************
==============================================================================
Task         : NuGet Tool Installer
Description  : Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this step to change the version of NuGet used in the NuGet Restore and NuGet Command steps.
Version      : 0.1.0
Author       : Microsoft Corporation
Help         : 
==============================================================================
Downloading: https://dist.nuget.org/win-x86-commandline/v4.1.0/nuget.exe
Caching tool: NuGet 4.1.0 x64
Using version: 4.1.0
Found tool in cache: NuGet 4.1.0 x64
Using tool path: d:\a\_tool\NuGet\4.1.0\x64
Prepending PATH environment variable with directory: d:\a\_tool\NuGet\4.1.0\x64
******************************************************************************
Finishing: Use NuGet 4.10
******************************************************************************
******************************************************************************
Starting: Restore
******************************************************************************
==============================================================================
Task         : .NET Core
Description  : Build, test and publish using dotnet core command-line.
Version      : 1.0.2
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
==============================================================================
```
dotnet restore
```
  Installing Microsoft.Extensions.Configuration.FileExtensions 2.0.0-preview1-final.
...

Error: C:\Program Files\dotnet\dotnet.exe failed with return code: 1
"C:\Program Files\dotnet\dotnet.exe" restore "d:\a\1\s\Main\Source\proj\projA\projA.csproj"
  Restoring packages for d:\a\1\s\Main\Source\proj\projA\projA.csproj...
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: NETStandard.Library from 2.0.0-preview1-25301-01 to 1.6.1  [d:\a\1\s\Main\Source\proj\projA\projA.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  projA (>= 13.0.200) -> Microsoft.Extensions.Configuration.Json (>= 2.0.0-preview1-final) -> NETStandard.Library (>= 2.0.0-preview1-25301-01)  [d:\a\1\s\Main\Source\proj\projA\projA.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  projA (>= 13.0.200) -> NETStandard.Library (>= 1.6.1) [d:\a\1\s\Main\Source\proj\projA\projA.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: NETStandard.Library from 2.0.0-preview1-25301-01 to 1.6.1  [d:\a\1\s\Main\Source\proj\projA\projA.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  projA (>= 13.0.200) -> Microsoft.Extensions.Configuration.Binder (>= 2.0.0-preview1-final) -> NETStandard.Library (>= 2.0.0-preview1-25301-01)  [d:\a\1\s\Main\Source\proj\projA\projA.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  projA (>= 13.0.200) -> NETStandard.Library (>= 1.6.1) [d:\a\1\s\Main\Source\proj\projA\projA.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning : Detected package downgrade: NETStandard.Library from 2.0.0-preview1-25301-01 to 1.6.1  [d:\a\1\s\Main\Source\proj\projA\projA.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  projA (>= 13.0.200) -> Microsoft.Extensions.Configuration.Abstractions (>= 2.0.0-preview1-final) -> NETStandard.Library (>= 2.0.0-preview1-25301-01)  [d:\a\1\s\Main\Source\proj\projA\projA.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): warning :  projA (>= 13.0.200) -> NETStandard.Library (>= 1.6.1) [d:\a\1\s\Main\Source\proj\projA\projA.csproj]
  Lock file has not changed. Skipping lock file write. Path: d:\a\1\s\Main\Source\proj\projA\obj\project.assets.json
  Restore completed in 542.52 ms for d:\a\1\s\Main\Source\proj\projA\projA.csproj.
```

Still fails :(

**Comment by CoskunSunali** [comment]
I am having the same issue, please count me in.

**Comment by Jonathan34** [comment]
This issues seems to appears on visual studio 2017 actually, not sure it is related to the VSTS tasks anymore. I do not have a windows machine on hand but will try to check on a colleague's machine.

**Comment by jmyersmsft** [comment]
This is likely a consequence of the hosted agents not including preview versions of .net core.

**Comment by Jonathan34** [comment]
probably it is one issue but even on a windows pc with .net core 2 preview 1 installed, the same issue appears when building with vs 2017. but not with the cli (on the same machine).

**Comment by CoskunSunali** [comment]
In my case it builds fine on my computer. It is just the VSTS task failing, probably because of the reason @jmyersmsft mentioned above.

@jmyersmsft This issue with hosted VSTS agents not having the latest bits of other things started to become a serious obstacle for me. I don't know if it is just me but I, as a developer, like to enjoy preview builds so that I can be ready for the future releases and also do my best to provide early feedback. As you might imagine, it is hard to give up on a build mechanism just because I prefer working on pre-release software. I am wondering if these pre-release software can be deployed to the hosted build agents (being VS 2017 agents in this case) once a major version is achieved? I don't mean to ask for every single beta release but at least for some releases like preview1, preview2, etc. This can be an automated task. May I ask for your opinion on that if you are the right person to ask? Thanks in advance!

**Comment by jmyersmsft** [comment]
@CoskunSunali that feedback will need to go back to @bryanmacfarlane. I'm from the package management service.

**Comment by bryanmacfarlane** [comment]
@CoskunSunali - customers rely on those images for production builds.  For tools that are globally installed, need to wait until released (and even then they can destabilize someone).

We maintain pools for each era of VS and when VS2018 previews come out then we will have a preview of that one.

The problem is customer one wants everything else stable but preview of tool y installed and customer 2 wants everything else stable but preview of tool x installed.

There's two solutions to it:
- Create your own private agent on an azure VM.  You control your tool sets.  You get incremental source, packages, etc...
- Pull the tools JIT.  .net core tools can be downloaded JIT at the front of the build.  We recently create tool installers for this very reason.  We will add a net core tools one for convenience (so you don't have to write a script).  See here:  https://youtu.be/Ie8EuvqJ0Hg

Also keep in mind that the reasons the builds start relative quickly is large elastic pools of machines from homogenous images in data centers.  There are machines waiting around with the one VS2017 image that you use and the customer relying on that image for production builds.  We will have a VS2015 pool and a VS2018 preview one when it comes out.

**Comment by Jonathan34** [comment]
Or use the hosted linux agent and docker to build your app. 
Or add a step similar to nuget installer that we put at the beginning that allows to pull any version.

If this is not resolved in the vs 2017 agent image, then i'll probably use docker.

**Comment by CoskunSunali** [comment]
@bryanmacfarlane I cannot disagree with anything you say. May I ask, what is your opinion on an agent that is specific for developers? I mean, having another one just like "VS 2017" but something like "VS 2017 Dev". Production customers would not be affected in that case.

By the way, I was able to use some PowerShell scripts to download the dotnet runtime as the first step of the build definition (as you mentioned). I also figured out how to use the dotnet.exe that shipped with that download and execute further commands like `dotnet restore`, etc. Please see https://stackoverflow.com/a/41741641

My current problem is somehow not being able to find the MSBuild version 15 (or 15.1?). The documentation states "15" but the build agent VS 2017 is unable to find it. The same goes for "15.1".

I tried pulling NuGet 4.1.0 using the NuGet Installer Tool to see if that would help but there is no documentation for how to refer to that downloaded custom version later on within the NuGet Packager and NuGet Publisher tasks. Your assistance would be highly appreciated on this matter.

Please see my comment at https://github.com/NuGet/Home/issues/5170#issuecomment-309064229

**Comment by bryanmacfarlane** [comment]
Yes, we have discussed multiple per era images ( and one could be dev ).  I like your idea of vs2017-dev because we would only do that for the latest vs ( we could also call it just vs dev ).  That mitigates the explosion of images and reduction of elasticity.

There's a couple other efforts that are just now taking shape

Tool installers - see video link above.  We need a net core template that allows and encourages JIT pulling net core tools be version decouple from image

Docker - we're working on ability to select the image to run your build in.  Works great for semi smaller images like net core.  Not as viable for full VS but something we're aware of.  Also related to yaml also in the works where you'll be able to declare image or images to run build and tests in.  This really is the ideal solution for all of us - your defined env really is the same between dev, CI, prod


We just recently added the ability to have multiple hosted pools.  We are also investing in the image generation process to turn around images faster.  That will be critical for a dev

**Comment by CoskunSunali** [comment]
Sounds great. Thanks for the details!

These tool installers, once they are well documented and expanded to a range of other useful tools (including .NET Core) will be useful and will solve the problems of many, I believe. 

Regarding the video, I just watched it but did not really get the idea of how to really use the NuGet Tools Installer. It is also unknown to me if using NuGet 4.1.0 would really fix the MSBuild 15/15.1 issue. I would be grateful if you had a link to a blog post, document or something like that. I spent two days trying to figure out how to customize the NuGet Packager and NuGet Publishers to use the custom version of NuGet that is JIT pulled using NuGet Tools Installer and also fail finding the appropriate MSBuild version - even though it is the "VS 2017" agent and is supposed to have MSBuild 15/15.1 - I feel there is lack of documentation on it. 

Thanks for your time! 👍

**Comment by CoskunSunali** [comment]
@bryanmacfarlane A few updates from my end.

I wrote a PS script that downloads NuGet 4.1.0 and saves into a folder. Then the rest of my build uses that one and the issue with MSBuild 15 seems to be resolved. It may be a bug with NuGet 4.0.

And I also realized that I don't have to use the NuGet Packager and NuGet Publisher tasks at all. It seems that `dotnet pack` and `dotnet nuget push` are what I was supposed to use for convenience.

Thanks for your time replying!

**Comment by alexmullans** [comment]
NuGet 4.1 does indeed fix some issues. As of tomorrow, you should be able to replace your PowerShell script with the new NuGet Tool Installer task, specify 4.1.0 as the version to install, then use the new NuGet task to restore packages as expected.

We're also working on updates to properly support dotnet pack and dotnet nuget push in the dotnet task, but they're a sprint or two away.

**Comment by chunliu** [comment]
A workaround I used to build .net core 2.0 preview projects on VSTS: 

1. Get dotnet-install.ps1 from https://github.com/dotnet/cli/tree/release/2.0.0-preview2/scripts/obtain. Make sure it is from the correct branch that your code needs. 
2. Configure a PowerShell Script task to run this script. By default, this script will install the .net core sdk in $(LOCALAPPDATA)\Microsoft\dotnet\. 
3. Configure several Command Line tasks to run restore, build, test, and publish with dotnet cli. Instead of using dotnet directly, the full path of the installed sdk should be used, which is $(LocalAppData)\Microsoft\dotnet\dotnet.exe.  

With the above steps, I can build the .net core 2.0 preview projects successfully with VSTS.

**Comment by Liero** [comment]
Final .net 2.0 is out and still not solved.

I've added `NuGet Tool Installer` task that installs v4.3.0 as well as` .NET Core Tool Installer` and still getting: 
> C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Unable to resolve 'NETStandard.Library (>= 1.6.1)' for '.NETStandard,Version=v2.0'.

```
2017-08-16T15:44:41.1987575Z ##[section]Starting: Use NuGet 4.x
2017-08-16T15:44:41.2157578Z ==============================================================================
2017-08-16T15:44:41.2157578Z Task         : NuGet Tool Installer
2017-08-16T15:44:41.2157578Z Description  : Acquires a specific version of NuGet from the internet or the tools cache and adds it to the PATH. Use this step to change the version of NuGet used in the NuGet Restore and NuGet Command steps.
2017-08-16T15:44:41.2157578Z Version      : 0.1.1
2017-08-16T15:44:41.2157578Z Author       : Microsoft Corporation
2017-08-16T15:44:41.2157578Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=852538)
2017-08-16T15:44:41.2157578Z ==============================================================================
2017-08-16T15:44:42.2564137Z You are using a query match on the version string. Behavior changes or breaking changes might occur as NuGet updates to a new version.
2017-08-16T15:44:42.3644154Z Downloading: https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe
2017-08-16T15:44:42.4644166Z Caching tool: NuGet 4.3.0 x64
2017-08-16T15:44:42.4714159Z Using version: 4.3.0
2017-08-16T15:44:42.4724170Z Found tool in cache: NuGet 4.3.0 x64
2017-08-16T15:44:42.4724170Z Using tool path: d:\a\_tool\NuGet\4.3.0\x64
2017-08-16T15:44:42.4724170Z Prepending PATH environment variable with directory: d:\a\_tool\NuGet\4.3.0\x64
2017-08-16T15:44:42.4804171Z ##[section]Finishing: Use NuGet 4.x
```

```
2017-08-16T15:44:42.4824163Z ##[section]Starting: Restore
2017-08-16T15:44:42.4834169Z ==============================================================================
2017-08-16T15:44:42.4834169Z Task         : .NET Core
2017-08-16T15:44:42.4834169Z Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command. For package commands, supports NuGet.org and authenticated feeds like Package Management and MyGet.
2017-08-16T15:44:42.4834169Z Version      : 2.0.5
2017-08-16T15:44:42.4834169Z Author       : Microsoft Corporation
2017-08-16T15:44:42.4834169Z Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=832194)
2017-08-16T15:44:42.4834169Z ==============================================================================
2017-08-16T15:44:43.3298644Z SYSTEMVSSCONNECTION exists true
2017-08-16T15:44:43.3328644Z Saving NuGet.config to a temporary config file.
2017-08-16T15:44:43.3439930Z ##[warning]Can\'t find loc string for key: NGCommon_NoSourcesFoundInConfig
2017-08-16T15:44:43.3448653Z ##[warning]NGCommon_NoSourcesFoundInConfig d:\a\1\Nuget\tempNuGet_736.config
2017-08-16T15:44:43.3698655Z [command]"C:\Program Files\dotnet\dotnet.exe" restore d:\a\1\s\src\CommandStack\CommandStack.csproj --configfile d:\a\1\Nuget\tempNuGet_736.config --verbosity Detailed
2017-08-16T15:44:46.3920139Z   Restoring packages for d:\a\1\s\src\CommandStack\CommandStack.csproj...
2017-08-16T15:44:46.4455885Z C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Unable to resolve 'NETStandard.Library (>= 1.6.1)' for '.NETStandard,Version=v2.0'. [d:\a\1\s\src\CommandStack\CommandStack.csproj]
2017-08-16T15:44:46.4704173Z   Generating MSBuild file d:\a\1\s\src\CommandStack\obj\CommandStack.csproj.nuget.g.props.
2017-08-16T15:44:46.4751984Z   Generating MSBuild file d:\a\1\s\src\CommandStack\obj\CommandStack.csproj.nuget.g.targets.
2017-08-16T15:44:46.4762048Z   Writing lock file to disk. Path: d:\a\1\s\src\CommandStack\obj\project.assets.json
2017-08-16T15:44:46.5172057Z   Restore failed in 79.89 ms for d:\a\1\s\src\CommandStack\CommandStack.csproj.
2017-08-16T15:44:46.5192052Z   
2017-08-16T15:44:46.5192052Z   Errors in d:\a\1\s\src\CommandStack\CommandStack.csproj
2017-08-16T15:44:46.5202059Z       Unable to resolve 'NETStandard.Library (>= 1.6.1)' for '.NETStandard,Version=v2.0'.
2017-08-16T15:44:46.5202059Z   
2017-08-16T15:44:46.5202059Z   NuGet Config files used:
2017-08-16T15:44:46.5202059Z       d:\a\1\Nuget\tempNuGet_736.config
2017-08-16T15:44:46.5552047Z ##[error]Error: C:\Program Files\dotnet\dotnet.exe failed with return code: 1
2017-08-16T15:44:46.5552047Z ##[error]Packages failed to restore
2017-08-16T15:44:46.5622062Z ##[section]Finishing: Restore
```

**Comment by alexmullans** [comment]
@Liero sorry to hear that. The NuGet tool installer won't help at all here - you'll want the .NET Core Tool Installer task and .NET Core task for your scenario. You mentioned you'd tried the .NET Core Tool Installer but were still having issues. Did you use "2.0.0" for the Version field in that task? If so, could you share the output here? I'd expect that to have been able to resolve the issue you're seeing.

**Comment by Liero** [comment]
Actually, three steps vere required to make it work: https://stackoverflow.com/questions/45717283/vsts-build-packages-failed-to-restore-unable-to-resolve-netstandard-library/45726277?noredirect=1#comment78457101_45726277

I believe it could work by default without the three steps...

**Comment by aggieben** [comment]
@Liero I saw your SO post(s) earlier today and tried them, and I still experience this error currently.  I posted about it here: https://developercommunity.visualstudio.com/content/problem/159780/error-nu1100-unable-to-resolve-netstandardlibrary.html

I'm pretty sure the VS2017 hosted agent has the correct SDK bits, so it seems like the SDK version isn't the cause.  However, I still don't really have much idea what would be causing it.

**Comment by keithrob** [comment]
@aggieben,
Does your build task have a NET Core Tool Installer "2.0.0" [1] build step _before_ all of your other steps in the build?

[1]
![image](https://user-images.githubusercontent.com/908203/33565905-3b6c2ebc-d8d3-11e7-89bb-1b9571a7ac41.png)

**Comment by aggieben** [comment]
@keithrob no - but like I said I verified in the output that the correct version of the SDK is being used (and in addition to that, I'm now using a global.json to ensure an error occurs if the correct version isn't available).  

I did just figure this out, though.  I'm using Paket to manage my dependencies and I neglected to add NETStandard.Library to my `paket.dependencies` file.  So the root cause here was PEBKAC (problem exists between keyboard and chair). 😉

**Comment by keithrob** [comment]
@aggieben,
Glad to hear the problem is resolved.  Curious, can you explain how you verified the correct version of the SDK?

**Comment by aggieben** [comment]
>  I verified in the output

**Comment by tongtrongnhan** [comment]
I have same issue I fixed it by "Add  https://api.nuget.org/ to trusted site on Internet Option"
