### ISSUE TITLE
How do I specify --no-cache parameter for docker build command in task?

### ISSUE THREAD

**Issue by artisticcheese** [Microsoft/vsts-tasks#4539]
Hello,

Is there an option to inform docker CLI to use --no-cache parameter in task? Putting it into `Build Arguments` does not work since it's not a build argument.

**Comment by RoopeshNair** [comment]
Added to backlog.  It might take while before we can get to it.

**Comment by kachkaev** [comment]
Has this been implemented? Not sure why the issue is closed.

Using `--no-cache --pull` in CI/CD is critical as otherwise the resulting images are stateful. Previously ran tasks on an agent may affect the result, which contradicts the philosophy of CI/CD.
