### ISSUE TITLE
SqlAzureDacpacDeployment cannot find DacFramework 14.0.3691.3

### ISSUE THREAD

**Issue by kogir** [Microsoft/vsts-tasks#4542]
The latest Data-Tier Application Framework uses a new registry key to record its installation location. The current script is unaware and cannot find it.

New Key: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\Data-Tier Application Framework\InstallLocation`

The newest version (as of issue submission) can be downloaded [here](https://www.microsoft.com/en-us/download/details.aspx?id=55255).

I'd submit a PR but can't (after trying for a while) find a way to test it with VSTS online, and wouldn't want to submit untested code.

**Comment by kogir** [comment]
I was able to work around it for now by manually creating the old registry key it looks for. It seems it's been invalid for quite some time, since none of the DacFx 16.* or 17.* versions write it anymore.

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\DACFramework]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\DACFramework\CurrentVersion]
"Version"="14.0.3691.3"
```

**Comment by chshrikh** [comment]
@kogir this has been fixed and will be available with next deployment, approx after one month from now
