### ISSUE TITLE
[Azure Powershell] 'Get-AzureRmServiceBusTopicKey' is not recognized

### ISSUE THREAD

**Issue by damienpontifex** [Microsoft/vsts-tasks#4548]
I'm running an Azure Powershell task with an Resource Manager connection and get the following error:

> The term 'Get-AzureRmServiceBusTopicKey' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

The docs for this https://docs.microsoft.com/en-us/powershell/module/azurerm.servicebus/get-azurermservicebustopickey?view=azurermps-4.1.0  and going back in history, seems to be available after v3.8.0.

Is there some restriction in the task or the powershell module is not updated that this wouldn't work? If so, what is the recommended way to get the task up to date/include this module?

**Comment by chrisrpatterson** [comment]
The version of the powershell modules should just pickup whatever is installed on your build machine.  So you should simply update it there.

**Comment by damienpontifex** [comment]
Apologies, it was on the Hosted VS2017 image. I assumed this repo might track that, but maybe it's more to do with the VSTS infrastructure side. Looking now it's Azure Powershell 3.6.0 and hence the error https://www.visualstudio.com/en-us/docs/build/concepts/agents/hosted#software
