### ISSUE TITLE
TFS 2015 Release Cannot Get “Run Functional Tests” Task to Work on Multiple Machines

### ISSUE THREAD

**Issue by thoaingan** [Microsoft/vsts-tasks#4552]
On-prem TFS 2015 Update 3.

I have multiple machines (different Operating Systems) that I want to run my tests on. I'm having issues getting this simple flow to work successfully. Here's what I've tried:

1. Deploy Test Agent task on multiple machines are successful.

2. If I put multiple machines in one "Run Functional Tests" task, it will execute the test one ONE of those machines in step 1 only (and will complete successful if this is the first task). Logs here: [ReleaseLogs_57.zip](https://github.com/Microsoft/vsts-tasks/files/1077767/ReleaseLogs_57.zip)

2. If I set up 2 separate tasks, one for each machine, the 1st task will execute successfully, but as seen in bullet 2, the test is run on ANY ONE of the machines in step 1 (NOT the specific one specified for the task).  In the example attached, the 1st task is set up to run on Win7, but the test was actually executed on the Win8 machine.
Then the 2nd task (which is set up to run against the Win10 machine) will not complete, no matter what machine or test I put in it. Logs for this scenario attached: 
[ReleaseLogs_60.zip](https://github.com/Microsoft/vsts-tasks/files/1078061/ReleaseLogs_60.zip)

It seems that the PS script(s) for this task is broken in our environment. Here's the zip file of the entire "tasks" folder for your reference.
[tasks.zip](https://github.com/Microsoft/vsts-tasks/files/1080899/tasks.zip)

Thanks!

**Comment by thoaingan** [comment]
Instead of creating another issue, I'm attaching the logs here for the scenario where I have 2 "Run Functional Tests" tasks in the same Release (one for each of the machines). No matter what tests or machines I set up for the 2nd task, it always just sits there forever until I cancel the entire deployment. And the resulted logs are as shown.

Based on my observations for various issues I have with this task, here's a summary:

1. Deploy Test Agent task on multiple machines are successful.
2. If I put multiple machines for "Run Functional Tests" task, it will execute the test one ONE of those machines in step 1 only (and will complete successful if this is the first task).
[ReleaseLogs_58.zip](https://github.com/Microsoft/vsts-tasks/files/1077904/ReleaseLogs_58.zip)

2. If I add an additional "Run Function Tests" task, this task just doesn't complete (logs for this scenario attached).

It seems that the PS script for this task is broken in our environment.

**Comment by dpksinghal** [comment]
This scenario is not supported. The Deploy test agent and Run functional test task should be operated on the same set of machines. 

So if you want the Run functional task to run on a specific machine(s), please mention the same in Deploy test agent task as well.

You can use multiple Deploy test agent task along with Run functional test task instances to target specific machines.

**Comment by thoaingan** [comment]
As mentioned in my post, if I put the same number of machines on both Deploy and Run Functional Test tasks, the Run Functional Test task only executes the tests on **_ONE_** of those machines, not ALL of them as specified. Is that the expected behavior?

As of now, I have to add a pair of Deploy + Run for EACH machine. Is that the only supported configuration?

**Comment by dpksinghal** [comment]
#1 => Yes, it is expected if there is a single test dll. To enable distribution based on the tests (irrespective of the test dlls/containers), please enable the 'Distribute tests by number of machines' option available in the task.

#2 => Yes. At present this is the only supported behavior.

**Comment by thoaingan** [comment]
Where's the option to "Distribute tests by number of machines"? This is all I have for this task.
![image](https://user-images.githubusercontent.com/7240365/27436179-12c21340-5724-11e7-9e9b-70623957cb6a.png)

**Comment by dpksinghal** [comment]
Apologies for the confusion here. The feature that I mentioned in not available in TFS 2015 Update 3. 
It got added to the next major version of the TFS.

**Comment by thoaingan** [comment]
Thanks for the clarification!

So, to confirm, are you saying that the value specified in "Machines" of this "Run Functional Tests" task is **_pointless_** since the tests will be run on just **_ONE_** of the machines specified in the **_preceding_** "Deploy Test Agent" task?

This is not what the description of this task says according to its documentation: https://www.visualstudio.com/en-us/docs/build/steps/test/run-functional-tests

> Run Coded UI tests, Selenium tests, and functional tests **_on a set of machines_** using the test agent. Use this task when you want to run tests on remote machines, and you cannot run tests on the build machine.

**Comment by dpksinghal** [comment]
In TFS 2015 U3, if you have a single test assembly the tests will not be distributed on more than one machine. The distribution mechanism in this release is based on the number of test assemblies.

So if want to leverage test distribution, please see if you have more number of assemblies.

In later version of TFS, we have added the option to enable distribution of tests based on the number of machines.
