### ISSUE TITLE
Archive Files: Selecting gz for tar compression doesn't do anything

### ISSUE THREAD

**Issue by dpribyla** [Microsoft/vsts-tasks#4559]
On the Archive files task I select tar then gz for compression.  In the log it shows the following:

/bin/tar -c -f /opt/vsts/work/2/a/

I was expecting the -z switch.  I tried it with the other tar compressions and they both added the correct switches.

**Comment by DavidStaheli** [comment]
Hi @dpribyla, thank you for reporting this.  I apologize: this is a bug we discovered and fixed this week (commit [ffc71acb](https://github.com/Microsoft/vsts-tasks/pull/4507/commits/ffc71acbb83173150f0d052249546eb6f38708cb)).  It will be deployed to Team Services production in ~2 weeks.  If you need the fix sooner, or you are running TFS on-premises, please let me know and I can provide instructions and a ZIP file to patch your account/server.
