### ISSUE TITLE
Nuget restore build task fails with an error "A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details."

### ISSUE THREAD

**Issue by jeevaeastpoint** [Microsoft/vsts-tasks#4561]
We use a Mac build agent to build both xamarin.ios and xamarin.android projects. Ios seems to be fine but when building android project it always comes with this error message. Wondering whether these tasks are not made available for Mac agents. 
Is this true? If so is there any way to run these tasks in Mac agent. Can we install a Mac variant of PowerShell to make use of these tasks?

**Comment by emanuelquintero** [comment]
@jeevaeastpoint 
The task should** work on mac as long as you have Mono installed. 
If you do have Mono installed, could you make sure you're using the latest version of the task?
1. Go to your build definition
2. Go to the NuGet restore task
3. Search for a version dropdown within the task (it's text should be something like "0.*" or "1.*")
4. Select the latest version
5. Run the build

If you keep having issues, let us know so we can keep troubleshooting.

** Verification of the task is heavily Windows based

**Comment by alexmullans** [comment]
Closing this issue since I haven't seen a post back in a few weeks.
