### ISSUE TITLE
Azure Resource Deployment Task - override parameter issue

### ISSUE THREAD

**Issue by euhm** [Microsoft/vsts-tasks#4562]
Hello,

I had a value which contained the following value 'name - env', and this caused the following error:

2017-06-16T17:38:37.4839439Z ##[debug]Overriding key: 
2017-06-16T17:38:37.4839439Z ##[debug]There was an error while overriding '' parameter because of 'TypeError: Cannot read property 'type' of undefined'.

The issue was resolved with the new value 'name', so no dash and spaces.

kind regards,

bob

**Comment by euhm** [comment]
Value in 'override template parameters' was: -smtpUsername $(Custom.App.Smtp.Username)

Workaround is off course wrapping in quotes: -smtpUsername "$(Custom.App.Smtp.Username)"
My assumption was that the task wraps by default the values with quotes.

If not, ticket can be closed.

**Comment by hiyadav** [comment]
Thanks for reaching out to us.
The value in override parameters can contain spaces and dash, but for doing that you can do the following:
Case1: if using the multiline text box to enter the name and value, then you need to enclose the value inside Quotes: like the following: -Key "value with space and - dash".
Case2: use the "..." button to open "Override template parameters" Dialog box, and enter the key and value without quoting them manually. Like: 

![image](https://user-images.githubusercontent.com/20859325/27949606-e0548e52-631b-11e7-99d7-4227e5dfc8bb.png)

**Note**: only values containing spaces are enclosed with quotes automatically.

In your case, the value is a $(variable) with no spaces in its name, thus this value is not enclosed in quotes, but i guess the value of the $(variable) will be having spaces. We do not enclose the value of the $(variable) in quotes. We use the value as is. 

You can enclose the values of the $(variable) and then use it without fail or make use of any of the above cases.
