### ISSUE TITLE
Determine if the task is running in Build or Release definition

### ISSUE THREAD

**Issue by mortezag** [Microsoft/vsts-tasks#4568]
What is the suggested way to determine in the task if it is running in a Build definition or Release definition?

**Comment by DavidStaheli** [comment]
You could look for the presence of this environment variable that only has a value in Release: `Release.ReleaseId`

```
var releaseId = tl.getVariable('Release.ReleaseId');
if (!releaseId) {
}
```

The build and release variables are documented here:
[Build Variables](https://www.visualstudio.com/en-us/docs/build/define/variables)
[Release Variables](https://www.visualstudio.com/en-us/docs/build/concepts/definitions/release/variables#default-variables)

**Comment by bryanmacfarlane** [comment]
create an issue on vsts-task-lib repo and we will add a function

**Comment by ericsciple** [comment]
There is a variable system.hostType
