### ISSUE TITLE
Build fails on code using new binary literals for VB.NET 15.0

### ISSUE THREAD

**Issue by morphx666** [Microsoft/vsts-tasks#4577]
Compiling code using MSBuild 15.0 breaks complaining about a binary literal:

`Private vidModeChangeFlag As Integer = &B1000`

Here's the reported error message:

**Build**
x8086NetEmu\Adapters\Video\CGA\CGAAdapter.vb (115, 44)
x8086NetEmu\Adapters\Video\CGA\CGAAdapter.vb(115,44): Error BC30201: Expression expected.
Process 'msbuild.exe' exited with code '1'.
Directory 'd:\a\1\a' is empty. Nothing will be added to build artifact 'drop'.

**Comment by ericsciple** [comment]
The MSBuild task in VSTS is a thin wrapper of msbuild.exe. It sounds like the error is coming from msbuild itself (not this repo).

Please reopen if I've missed something and it's a bug in a task in this repo.
