### ISSUE TITLE
Get trigger that launched the release

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vsts-tasks#4583]
Is there a variable that will indicate how the release was launched, if is a CI or a scheduled trigger who started the release?

**Comment by GitHubSriramB** [comment]
@mmajcica - We support Release.RequestedFor variable. Would this suffice?

**Comment by mmajcica** [comment]
@GitHubSriramB  Release.RequestedFor will bring me the user name that requested the release, not if this was triggered by the CI trigger or of it was triggered by a scheduled trigger.

**Comment by GitHubSriramB** [comment]
@mmajcica - we will add the release reason as a variable. this will either be "manual" or "continuousIntegration". Will update once we have this support added.

**Comment by GitHubSriramB** [comment]
@mmajcica - We have added support for Release.Reason variable and it should be available in VSTS in next couple of weeks and in TFS 2018 RC1.

The reason could be one of the following:
Manual
ContinuousIntegration
Schedule
