### ISSUE TITLE
about "Test with Visual Studio Mobile Center"

### ISSUE THREAD

**Issue by jamesatgithub** [Microsoft/vsts-tasks#4591]
we have been using build in Mobile Center, but didn't get automation of Test with it and I found this task "Test with Visual Studio Mobile Center" in vsts, Can I use this task but with output of Mobile Center build to run the testing?

**Comment by madhurig** [comment]
@jamesatgithub: The "Test with Visual Studio Mobile Center" task allow running tests on mobile center if you using VSTS for build. There is some documentation available on this task here: https://docs.microsoft.com/en-us/mobile-center/test-cloud/vsts-plugin. Is this what you are looking for?

Thanks,
Madhuri
