### ISSUE TITLE
Java.exe exited with code 2

### ISSUE THREAD

**Issue by smedel** [Microsoft/vsts-tasks#4593]
Hello,

Here i will explain what problem i have.

I try to build my Xamarin Android project through VSTS, i got an error at the task : Build Xamarin.Android Project, you can see the error log in attachment.

@madhurig this error came after the previous one, (i solve the previous one).

[JavaExeCode2.txt](https://github.com/Microsoft/vsts-tasks/files/1088370/JavaExeCode2.txt)

**Comment by smedel** [comment]
Hello,

It's just resolved, i was misswriting $(BuildConfiguration) - $(BuildMode), it wasn't matching to my bin\Release-Staging\ folder, i've removed the spaces, and now it works.

**Comment by madhurig** [comment]
@smedel : Thanks for confirming.
