### ISSUE TITLE
Test Agent Deployment Fails with v2 2017 Agents

### ISSUE THREAD

**Issue by ileonidmas** [Microsoft/vsts-tasks#4594]
Hello!

For the last two days I am trying to run UI test on the remote machine. Unfortunally it always fails with during the test agent deployment in powershell script with this Error:
System.Exception: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Method "NewTriggerByLogon" not found

I have attached the whole log file. I would really appreciate if I could get help with solving the problem.

Best regards
Leo

[6_Deploy TestAgent on ft010240.ft.corp.txt](https://github.com/Microsoft/vsts-tasks/files/1088470/6_Deploy.TestAgent.on.ft010240.ft.corp.txt)

**Comment by nigurr** [comment]
@ileonidmas Can you refer to this post and see if it fixes?
https://marckean.com/2016/07/17/powershell-bug-new-scheduledtasktrigger/

This seems to be odd. This is Scheduler Task property and which should be available if you have PS more than 5

**Comment by ileonidmas** [comment]
It worked like a charm! Thank you very much for a quick and precise response!
