### ISSUE TITLE
Unknown issue in TestCloud submission task

### ISSUE THREAD

**Issue by jsauvexamarin** [Microsoft/vsts-tasks#4598]
My Xamarin.Android submission to XTC is failing:
https://gist.github.com/jsauvexamarin/a0b30e8fbe72cc8ada4af4beb01b1557

The weird thing is that it's telling me:
```Mono Shared Runtime is not supported. This can be resolved by changing the project configuration or using a Release build.```

...and I *don't* have shared runtime enabled for both Debug or Release builds. Plus, it's telling me to try a release build when I *am* performing a release build. EDIT: I have ensured these conditions by logging into my remote Mac build agent machine, locating the exact source code that is specified in the path in the log, opened it in VS4Mac, and verified that shared runtime is disabled for both Debug and Release.

Any clues here?

**Comment by madhurig** [comment]
@jsauvexamarin : This seems like a bug in the version of test-cloud.

The task looks for test-cloud.exe in the packages folder by default, in your build it is picking up /packages/Xamarin.UITest.2.0.9/tools/test-cloud.exe. Did you recently change the package version in your project or is this a new CI setup?

Thanks,
Madhuri

**Comment by wil55n** [comment]
I had the same issue. Once I reverted to UITest version 1.x the error went away.

**Comment by madhurig** [comment]
Closing since this is external to the VSTS task. 

Thanks,
Madhuri
