### ISSUE TITLE
"Run Functional Tests" Task Aborted without Reasons After Running Some Tests

### ISSUE THREAD

**Issue by thoaingan** [Microsoft/vsts-tasks#4612]
I have a "Run Functional Tests" Task that just got aborted after running for some time. I could see the tests being run, but it just then stopped without any obvious reasons, and all the tests that were run ended up not having any results attached to them.

This happens on any number of tests in a very random fashion. It is very frustrating since after waiting so long for the task, we don't get any results back if it dies prematurely.

Attached is the log for one example. File "5_Run Chrome SPB Tests on $(Win7).log" shows that it ran for roughly an hour, then just died. I was watching the screen the entire time, so I can confirm that it indeed executed the majority of the 77 tests it was supposed to run.

And no, please don't tell me I need to configure one test per task. I have hundreds of tests that can (and should be run) in one task.

[Attempt2.zip](https://github.com/Microsoft/vsts-tasks/files/1095340/Attempt2.zip)

**Comment by dpksinghal** [comment]
Hi

Sorry about this. I am looking into this and will revert soon.

Thank you,
Deepak.

**Comment by dpksinghal** [comment]
We are working over mail on this issue.

**Comment by dpksinghal** [comment]
This is resolved now. The issue was due to the timeout setting in the task.
