### ISSUE TITLE
Npm: Failed to get the required authentication tokens for npm

### ISSUE THREAD

**Issue by DovydasNavickas** [Microsoft/vsts-tasks#4614]
I got pretty much the same error as in #3805:
```
2017-06-22T21:39:25.2724226Z vsts-npm-auth v0.23.0.0 
2017-06-22T21:39:25.2724226Z -----------------------
2017-06-22T21:39:25.7443603Z ##[debug]rc:1
2017-06-22T21:39:25.7443603Z ##[debug]success:false
2017-06-22T21:39:25.7599865Z ##[warning]Failed to get the required authentication tokens for npm. Error: C:\Agents\agent-2\tasks\Npm\0.2.22\Npm\vsts-npm-auth\bin\vsts-npm-auth.exe failed with return code: 1
```
But because you went offline to solve the problem, nobody knows how you solved it.
It would be really nice that it worked out of the box or you shared the solution.

EDIT:
I've changed the referenced issue to #3805.

**Comment by alexmullans** [comment]
Can you ensure you're using the latest version of the npm task? It no longer uses the vsts-npm-auth executable and should not have this error. Look for the version selector just below the task name.

**Comment by alexmullans** [comment]
Closing this issue since the new version of the task doesn't use the tool in question.

**Comment by DovydasNavickas** [comment]
I am traveling right now. Will check next week.

**Comment by ba55ie** [comment]
When you are running an older version of the NPM task, then this was our fix: https://github.com/Microsoft/vsts-tasks/issues/3805#issuecomment-326238301

**Comment by andyhutch77** [comment]
@alexmullans Hi Alex, I am currently getting the above error and I would like to update the NPM tasks as you mention. 

We have upgraded to 'TFS 2017 update 2' but this still uses 'vsts-npm-auth' as we get the error. 

Any ideas?

Thanks in advance

Andy
