### ISSUE TITLE
NuGet Packager task missing NuGet Version and Verbosity arguments

### ISSUE THREAD

**Issue by dpen2000** [Microsoft/vsts-tasks#4625]
These are present on NuGet Installer and NuGet Publisher tasks but not this one. The only way I've been able to get this task to use 3.5.0 version of Nuget is to install NuGet.CommandLine and set the path to that.

**Comment by alexmullans** [comment]
This is fixed in the new "NuGet" task (which combines Installer, Packager, and Publisher functionality into a single task). Please consider switching to that task in the catalog.
