### ISSUE TITLE
Azure App Service Deploy task get "Error: No package found with specified pattern" when specify JSON variable substitution

### ISSUE THREAD

**Issue by lvsezhufu** [Microsoft/vsts-tasks#4637]
No matter for build or release, I always got this error for Azure App Service Deploy task:

`Error: No package found with specified pattern`

`appsettings.json` as below:
```
{
    "Logging": {
        "IncludeScopes": false,
        "LogLevel": {
            "Default": "Debug",
            "System": "Information",
            "Microsoft": "Information"
        }
    }
}
```

My details setting in a build definition as below:
![11](https://user-images.githubusercontent.com/23092306/27510164-cea362a6-593d-11e7-83d5-fe7dd402ab52.png)
![12](https://user-images.githubusercontent.com/23092306/27510169-d4f28088-593d-11e7-9673-6a8e15c10e75.png)

**Comment by vincentdass** [comment]
@lvsezhufu , looks like the issue is related to the package (Pakage or Folder Input) and not JSON variable substitution.
![image](https://user-images.githubusercontent.com/20121508/27511520-e2362dc0-5943-11e7-8800-150ee5c7d08c.png)
Can you please verify whether the package exists in your Code Repo (For Build) or in Artifact (For Release) ?
You can use Wilcard patterns to find the package.

**Comment by g-guth** [comment]
Same problem. My appsettings.json is inside a .zip file.

Then i get the error:
NO JSON file matched with specific pattern: appsettings.json

msbuild command:
`/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactstagingdirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"`

**Comment by lvsezhufu** [comment]
Even the *.zip including all the files in repo, it always has the same error message for build and release.

**Comment by vincentdass** [comment]
@lvsezhufu , Can you please share the debug logs for the  Build/Release. (by enabling system.debug = true).

@g-guth , It looks like the **appSettings.json** is present deep inside and not in immediate folder of the zip. For JSON variable subsitution, path should be provided relative to the root folder of the zip or folder. you can also provide wilcard patterns to search for JSON files. If any file path matched with wildcard pattern, then substitution is applied in the same file.  Can you please provide `**/appsettings.json' in JSON variable substitution input field ?

![image](https://user-images.githubusercontent.com/20121508/27541215-ba20a15e-5aa0-11e7-8818-be2cc72e8c0d.png)

**Comment by g-guth** [comment]
understood. Im using the default configuration for a `Build` process and for a `Release ` using the ASP.NET Core(.NET Framework) process on `Team Services`.
My drop folder structure is like:

-Linked Artifacts
  -build-clone
     -drop
            WebApp.zip
            WebApplication.Paramenters.xml
            WebApplication.SourceManifest.xml

**Comment by vincentdass** [comment]
@g-guth , is the issue resolved ?

**Comment by g-guth** [comment]
@vincentdass  I´ll try it today.

**Comment by g-guth** [comment]
@vincentdass i cannot make work, is it not about the fact that the file that im trying to change is inside the .zip folder?

**Comment by vincentdass** [comment]
@g-guth , When a Zip is provided, it is extracted to a new location and File Transformation options (Web.config / XML Transformation / XML or JSON variable substuttion) is applied in the same folder.

Can you please share the debug logs for the release you ran ?

**Comment by lvsezhufu** [comment]
I eventually build and release successfully now. There are two things need to be noticed:
1.make sure the artifacts are zipped for release to download, if you set package or folder as $(System.DefaultWorkingDirectory)\**\*.zip
2.The appsettings.json file usually is not located in the root of zip folder, so we usually need to use **/appsettings.json for JSON variable substitution.

Thanks for @vincentdass help.

**Comment by lvsezhufu** [comment]
I eventually build and release successfully now. There are two things need to be noticed:
1.make sure the artifacts are zipped for release to download, if you set package or folder as $(System.DefaultWorkingDirectory)***.zip
2.The appsettings.json file usually is not located in the root of zip folder, so we usually need to use **/appsettings.json for JSON variable substitution.

Thanks for @vincentdass help.

**Comment by trilokhya** [comment]
hai I am too getting same error..
how can I keep json variable pattern that is **/*appsettings.json
