### ISSUE TITLE
How to run git commands on Release tasks?

### ISSUE THREAD

**Issue by g-guth** [Microsoft/vsts-tasks#4655]
Im not finding a guide on how to run git commands on the release tasks.

I followed this [guide](https://www.visualstudio.com/en-us/docs/build/scripts/git-commands) but its focused on run git commands in the build tasks, it works fine, but not on the release tasks.

The only stuff i get to work is send my .git folder to the arctifacts directory, create a new branch and checkout to this branch using a .bat script, but when i try to push i get a permission error:
> fatal: could not read Username for 'https://myteamservice.visualstudio.com': Invalid argument

This is my artifacts folder:
![artifactos](https://user-images.githubusercontent.com/11525137/27590495-49094a72-5b25-11e7-8ffa-a1cb56f7d285.PNG)

The release log:
![error](https://user-images.githubusercontent.com/11525137/27590788-2112f7b0-5b26-11e7-98dc-bcf45a712e67.PNG)

**Comment by bryanmacfarlane** [comment]
The ad-hoc git commands referred to in that guide are for build and are setup by the 'get sources' phase in build.  The most significant piece is creds are configured for you so it *just works*.

Adding RM but I don't believe that's a built in RM concept.

**Comment by GitHubSriramB** [comment]
@g-guth - It is not possible to run git commands as "get sources" phase is specific to Build.

**Comment by g-guth** [comment]
@bryanmacfarlane  I make it work by sending the .git folder as a artifact, then i can make a git push on release. But it only works if I started the build manually by pressing the `Queue new build` button on the website. If I change it to continuous integration an trigger the build by making a push, it not works. The only difference i can see is that when i start a build manually the field `Requested by` is equal my user name Guilherme Guth, and if its triggered by the continous integration the field `Requested by`  is  `Microsoft.VisualStudio.Services.TFS on behalf of Guilherme Guth`

**Comment by GitHubSriramB** [comment]
@g-guth - will $(Build.RequestedFor) variable within Release work for you?

**Comment by GitHubSriramB** [comment]
@g-guth - I'm closing this issue assuming the above suggestion will work. Pl. let us know if this isn't the case.

**Comment by nealAR** [comment]
I'm running into the exact same issue. In the guide referenced in the original post there is supposed to be an option called "Allow scripts to access OAuth token," however in the new UI it looks like this has been removed (at the least it's not present under the current Options menu). Did anyone figure out a method for enabling script tasks to access git/bitbucket credentials?

https://docs.microsoft.com/en-us/vsts/pipelines/scripts/git-commands?view=vsts

**Comment by carloshenriqueribeiro** [comment]
@nealAR  I found it
![capture](https://user-images.githubusercontent.com/19979749/47126393-bded3b80-d25e-11e8-84d4-68580ec75ba0.JPG)
