### ISSUE TITLE
Run Functional Tests not finding ChromeDriver only on some machines?

### ISSUE THREAD

**Issue by NetTecture** [Microsoft/vsts-tasks#4694]
I have a problem with running functional tests. We are moving from another product to VSTS for our integration testing. As such, I am setting up a cluster of a number of VM's for running web based tests. They all are supposed to run the same tests in distributed fashion, to make things faster. Tests are C# written and selenium based.

For now, there are 4 VM's which I did reinstall this morning side by side (i.e. same step on all vm's, then same step again on all VM's).

This is a base VM, domain user with local admin rights, chrome installed.

The test package includes a nuget determined chromedriver.exe so that we do not ahve to manually update the test machines for new chromedriver versions.

Again, just to emphasize, this is for the same test run. I.e. the same test data packet is distributed to the same machines (machien names in a variable) using the Windows Machine File Copy task.

The functional tests do not run on 2 of the machines. 2 of the 4 machines properly start the tests,, chromedriver starts, opens chrome, all works nice.

THe other 2 machines fail to locate the chromedriver and I am out of my guts on why. I find error messages that read:

Assembly Initialization method Tests.Integ.XXX.AssemblySetup.SetUp threw exception. OpenQA.Selenium.DriverServiceNotFoundException: OpenQA.Selenium.DriverServiceNotFoundException: The file C:\Users\TestAgentUser\AppData\Local\Temp\TR_92acb\Deploy_TestAgentUser 2017-06-30 03_35_49\Out\chromedriver.exe does not exist. The driver can be downloaded at http://chromedriver.storage.googleapis.com/index.html. Aborting test execution.

I validated that the driver is in the proper place (in this case D:\Testfiles), at the same place as the other two machines. It seesms that for some reason two of the 4 VM's decide to look in the wrong place, and I am at a loss here. ANyone an idea? Any log I can check?

**Comment by dpksinghal** [comment]
Can you please share the complete build logs with us? It would be helpful if you can do a build with system.debug = true.

**Comment by NetTecture** [comment]
@dpksinghal Build or test logs? Because I run the tests from a release deployment, not a build. Want me to build with system.debug=true and then deploy? Please advice.

**Comment by dpksinghal** [comment]
No you can do the same in the release. Please set this variable and run the release once. After that please share the logs with me.

**Comment by vimegh** [comment]
@NetTecture Were you able to solve this problem? If not can you please share the release logs (with variable system.debug=true). 
Please also share DtaExecutionHost.exe.log from C:\Dtalogs folder for both passing and failing VM. 
Thanks.

**Comment by NetTecture** [comment]
@vimegh I have not solved it.

I am collecting DTAExecutionHost.exe.log later today.

Is there an email to send them to? I am not comfortable sharing environment specific with the internet.

**Comment by vimegh** [comment]
@NetTecture You can email logs to us at devops_tools@microsoft.com. Thanks.

**Comment by vimegh** [comment]
@NetTecture Did you get a chance to capture the logs?

**Comment by vimegh** [comment]
@NetTecture We are closing this for now. If you have already solved the problem, please share the resolution. If you are still seeing the issue, please feel free to reopen, and do send us the release logs (with variable system.debug=true) and DtaExecutionHost.exe.log from C:\Dtalogs folder in the VM for both passing and failing one. Thanks.

**Comment by NetTecture** [comment]
Reopenng. Just collecting the log files.

**Comment by NetTecture** [comment]
@vimegh Logs submitted. Please reopen.

**Comment by NetTecture** [comment]
@vimegh Logs not submitable. The email you indicated errors out. Error:

The groups only accept messages from people in their organization or on their allowed senders list, and your email address isn't on the lists.

**Comment by vimegh** [comment]
We have received the mail today. Reopening the issue.

**Comment by cltshivash** [comment]
@NetTecture The errors indicate that the chromedriver is missing in the tests deployment folder. I don't see a runsettings file used to enabled deployment. Could you please share details on how are you getting this file to be part of the test deployment folder. Is it specified as a deployment item on specific test classes ?

**Comment by NetTecture** [comment]
@cltshivash Yes, as I said in the original post. The chromedriver is set as part of the deployed files. This also works for SOME machines, intermittently (I.e. it is random after a restart whether it will work or not until the next restart). There is no runsettings - things work without (at least where the chromedriver is found). The chromedriver is just part of the deployed files (similar to the dll's that are distributed with the output of the test project). It is properly deployed to D:\Testfiles (which is where all the relevant files reside) and then the agent copy operation just decides to sometimes ignore it, it seems.

**Comment by cltshivash** [comment]
@NetTecture Can you please check if chromedriver.exe is specified as a deploymentitem ([DeploymentItem("chromedriver.exe")]) in your test code ? it is possible that it is specified in one of the test classes and not in all of them.

**Comment by NetTecture** [comment]
@cltshivash It is not. As in: not specificed in ANY SINGLE TEST. Is it necesssary? It seems not to be documented anywhere. If it is - why does it work on some machines? (which change after every reset). Here is the code I am using to load the chromedriver:

        [AssemblyInitialize]
        public static void SetUp(TestContext context) {
            var baseDir = Path.GetDirectoryName((typeof(AssemblySetup)).Assembly.Location);
            _webDriver = new ChromeDriver(baseDir);
        }

It works on all setups we call in TeamCity and it works on some of the machines in VSTS - as I already pointed out repeatedly, the machines change on reboots, so SOMETHING is off there. I hate random stuff thrown around like that.

**Comment by cltshivash** [comment]
@NetTecture The chromedriver.exe will be copied over to the test run directory based on the below

1. If there's a test that has a compile time dependency on it 
2. If it has been specified as a deployment item in the test class or in the testsettings.

Without looking at the code it is hard to comment on point no.1. Kindly add "chromedriver.exe" as a deploymentitem in the test code and verify if it helps. I tried locally and i am able to get past the error.

**Comment by nigurr** [comment]
Please reach us if the problem persists. closing this issue. Thanks for your support
