### ISSUE TITLE
Error from ps script reveals partial secret value

### ISSUE THREAD

**Issue by ebrucucen** [Microsoft/vsts-tasks#4695]
I have a build task with the Password variable passed from the Variables tab in the build definition marked as secret. After the script hit the Write-Error line, Build log/output window displayed my password as a clear text! Should not they be hidden always? 
![tfstask_password](https://user-images.githubusercontent.com/204902/27736574-a0ad9c8c-5d9c-11e7-9704-ce3a5c873690.PNG)
my password parameter on variable list of build definition:
![pass](https://user-images.githubusercontent.com/204902/27736631-ea1b576a-5d9c-11e7-9982-8d352ba2a75c.PNG)
the build definition:
![buildded](https://user-images.githubusercontent.com/204902/27736634-ec64c344-5d9c-11e7-80e6-f643b5c69332.PNG)

**Comment by ebrucucen** [comment]
and perfect, with the alert email, the devs sent the requests also has the password now!

**Comment by ericsciple** [comment]
@ebrucucen is the password truncated? The agent scrubs full matches only. If the password is not truncated, then what agent version are you on?

Note, we have changes coming that will avoid this. We are changing the task to encourage users to pass secrets via a new [environment input](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/powerShell/task.json#L38). The UI work is remaining.

**Comment by ebrucucen** [comment]
It is truncated due to the size limit of the display I guess. I expected, Write-VstsTaskError/or others do scrubbing before it goes out to stream...

**Comment by ericsciple** [comment]
Changing the `$errorView` setting might workaround the issue. PowerShell is creating the error message.

**Comment by ebrucucen** [comment]
If I reference from the variableset, i.e. ` $PasswordVar = $env:password  `, then it can't access the value...

`2017-06-30T14:21:37.6637944Z Pass: `

**Comment by ericsciple** [comment]
that's correct, it's feature work that is getting close but is not in production yet

**Comment by ebrucucen** [comment]
Ok, I have changed the order of the parameters, as for $errorview I need the most explicit logs to get the error right at the first sight. Thanks!

**Comment by ericsciple** [comment]
@ebrucucen fyi, [env is available in yaml now(https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-powershell.md#environment-variables)], will come to web designer in the future
