### ISSUE TITLE
Run Functional Test intermittent failure: Automation engine is unable to playback

### ISSUE THREAD

**Issue by lei7081** [Microsoft/vsts-tasks#4699]
We are using Visual Studio Team Service build process to run our Coded UI test on Azure VM, however, the build process (specifically a task call “Run Functional Test”) failed intermittently without anything being changed. The specific error message is:

“Error calling Initialization method for test class XXX: Microsoft.VisualStudio.TestTools.UITest.Extension.UITestException: Automation engine is unable to playback the test because it is not able to interact with the desktop. This could happen if the computer running the test is locked or it’s remote session window is minimized.”

Here are the setup for our test machine:
1. .Net framework 4.7
2. Powershell 5.1
3. PS remoting and WinRM enabled
3. Test machine is using static IP
4. we are using the same service account for build agent and test agent with Admin access to both test and build machine
5. auto logon configured
6. update test agent checked
7. test agent is running on Windows 10 Azure VM
8. Run test interactive is checked in build definition

Please let me know if you need future information. 

Thanks,

Lei

**Comment by dpksinghal** [comment]
Hi

Have you connected to the VM from some client and having one active session? This error can come in any of the following case:
1, VM doesn't have any active UI session
2. The machine is locked
3. If you had a RDP session and it is minimized.

Please see if any of the above is causing this in your case.

**Comment by lei7081** [comment]
No, I did an extensive search for my issue and made sure these scenario did not happen. Sometimes I run build immediately following restarting of the VM, it still did not work.

I suspect the interactive session did not establish before the test run due to network/machine performance, but cannot prove it.

**Comment by vimegh** [comment]
In order to create active interactive session DTA uses Autologon and when an interactive session is established, then only Run Functional test task is run (Refer https://blogs.msdn.microsoft.com/devops/2017/07/03/deploy-visual-studio-test-agent-task-test-machine-rebooting-scenarios/ ). So that might not be the cause.

I am suspecting something else is hampering the interactive access of UI.

Did you try running coded UI tests manually on the same VM or running the build definition with a RDP session open and not minimized? 
Also, did the test failed intermittently for once, or it keeps on failing again and again?

**Comment by lei7081** [comment]
I have tried to run it on a local VM with MSTest manually, it was working.
I just tried to open a RDP session, keep it open and run the test, this time it succeeded.
From the past experience, it could be successful for a few times, then fail and kept failing. It won't succeed again until I restarted the VM.





On Monday, July 17, 2017, 4:30:59 AM EDT, Vishal Meghani <notifications@github.com> wrote:


In order to create active interactive session DTA uses Autologon and when an interactive session is established, then only Run Functional test task is run (Refer https://blogs.msdn.microsoft.com/devops/2017/07/03/deploy-visual-studio-test-agent-task-test-machine-rebooting-scenarios/ ). So that might not be the cause.

I am suspecting something else is hampering the interactive access of UI.

Did you try running coded UI tests manually on the same VM or running the build definition with a RDP session open and not minimized?
Also, did the test failed intermittently for once, or it keeps on failing again and again?

**Comment by vimegh** [comment]
Can you try a few times with RDP session open. If it doesn't then it is highly possible that when no RDP session exists then something is blocking interactive UI may be locking of machine. 
Is this a Hyper-V VM?

**Comment by lei7081** [comment]
I tried a couple times with RDP session open and maximized, it worked.
But the problem is, without RDP, it does not fail all the time, it is a intermittent problem.

On Thu Jul 20 2017 02:59:01 GMT-0400 (Eastern Daylight Time), Vishal Meghani <notifications@github.com> wrote:


Can you try a few times with RDP session open. If it doesn't then it is highly possible that when no RDP session exists then something is blocking interactive UI may be locking of machine.
Is this a Hyper-V VM?

**Comment by vimegh** [comment]
@lei7081 Will it be possible for you to enable screen/video recording for both passed and failed tests for some time, so that when next time it fails, you can check on video recorded in order to see what was blocking the UI.

Also please maker sure that automatic locking of workstation is disabled. Search for registry key “DisableLockWorkstation” over web.

**Comment by lei7081** [comment]
I am admin on the box, but not sure if how can I enable recording while not logged on.
I can look into the auto lock issue, but I doubt this is the root cause. Sometimes even after I rebooted the VM, the test still cannot started, the VM should not be in locked status at that point.

Lei


On Mon Jul 24 2017 16:19:31 GMT-0400 (Eastern Daylight Time), Vishal Meghani <notifications@github.com> wrote:


@lei7081 Will it be possible for you to enable screen/video recording for both passed and failed tests for some time, so that when next time it fails, you can check on video recorded in order to see what was blocking the UI.

Also please maker sure that automatic locking of workstation is disabled. Search for registry key “DisableLockWorkstation” over web.

**Comment by vimegh** [comment]
@lei7081 You can specify a test settings file to record screen for failed tests Refer: https://msdn.microsoft.com/en-us/library/dd286596.aspx , that might help us to know whether screen is really getting locked os something elese is blocking the UI at the time of run.

Also, Can you always use following script to disconnect a rdp session from the VM you are using for  running UI Tests, sometimes disconnecting the RDP session cause screen to lock. https://github.com/Microsoft/customer-scripts/blob/master/test/RDPSession/disconnect.bat

Thanks.

**Comment by vimegh** [comment]
@lei7081 Did you try to get screen recording done for tests? Please let us know.

**Comment by lei7081** [comment]
We have moved the VM to another server OU last week and the error never occurred afterwards. I think the error was caused by certain Group Policy but cannot pinpoint which one.
