### ISSUE TITLE
mime type application/octet-stream is set on every file

### ISSUE THREAD

**Issue by vmachacek** [Microsoft/vsts-tasks#4705]
Hello, 

I'm using this task to copy build artifacts of angular app to blob storage, from where its accessed on web server, so those are essentially css and JS files. Problem is with Angular Material, which gets confused, because every file is application/octet-stream mime type and not corresponding mime type. When I download build artifacts and upload them again using  Azure Storage Explorer windows app it works. 

Can anyone point me to either better task which sets also mime type, or some arguments for VSO task, which wold do that?

**Comment by bryanmacfarlane** [comment]
What task are you using?

**Comment by vmachacek** [comment]
I think its https://aka.ms/azurefilecopyreadme

**Comment by vmachacek** [comment]
I found this https://docs.microsoft.com/en-in/azure/storage/storage-use-azcopy and there is paragraph regarding content type, so if you specify /SetContentType without a value, then AzCopy will set each blob or file's content type according to its file extension. I can confirm it works. Those mime types are rather weird like `application/x-javascript` and it doesn't know svg, woff and ttf, but thats okay, work now.
