### ISSUE TITLE
Azure Web App Deployment fails with ERROR_CONNECTION_TERMINATED

### ISSUE THREAD

**Issue by qmfrederik** [Microsoft/vsts-tasks#471]
I have the following build pipeline:

1. MSBuild task to build my web app using the `/target:Package` additional build arguments
2. Publish the .zip package as a build artifact (not really used in this scenario)
3. Azure Web App Deployment task where I deploy my web app to a test environment.

The Azure Web App Deployment task fails with the error message:
`Web Deploy experienced a connection problem with the server and had to terminate the connection. Contact your server administrator if the problem persists. Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CONNECTION_TERMINATED.`

The page that is linked does not contain any information about an error `ERROR_CONNECTION_TERMINATED`.

**Comment by qmfrederik** [comment]
Here are the log files:

```
2015-08-31T08:58:24.9892263Z Executing the powershell script: C:\vsoagent\tasks\AzureWebPowerShellDeployment\1.0.15\Publish-AzureWebDeployment.ps1
2015-08-31T08:58:25.2860804Z Looking for Azure PowerShell module at C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Azure.psd1
2015-08-31T08:58:26.0360271Z AzurePSCmdletsVersion= 0.9.3
2015-08-31T08:58:26.0828987Z Get-ServiceEndpoint -Name <my-guid-here> -Context Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.TaskContext
2015-08-31T08:58:26.1141468Z subscription= Quamotion (Production)
2015-08-31T08:58:26.1141468Z Get-X509Certificate -CredentialsXml <xml>
2015-08-31T08:58:26.1766425Z azureSubscriptionId= <my-guid-here>
2015-08-31T08:58:26.1766425Z azureSubscriptionName= Quamotion (Production)
2015-08-31T08:58:26.1766425Z azureServiceEndpoint= https://management.core.windows.net/
2015-08-31T08:58:26.1922669Z Set-AzureSubscription -SubscriptionName Quamotion (Production) -SubscriptionId <my-guid-here> -Certificate <cert> -Environment AzureCloud
2015-08-31T08:58:26.2703860Z Select-AzureSubscription -SubscriptionId <my-guid-here>
2015-08-31T08:58:26.2860095Z ConnectedServiceName= <my-guid-here>
2015-08-31T08:58:26.2860095Z WebSiteName= quamotion
2015-08-31T08:58:26.2860095Z Package= D:\Build\d0a91b73\artifacts\drop\Quamotion.Website.zip
2015-08-31T08:58:26.3016339Z Slot= 
2015-08-31T08:58:26.3016339Z AdditionalArguments= 
2015-08-31T08:58:26.3016339Z packageFile= Find-Files -SearchPattern D:\Build\d0a91b73\artifacts\drop\Quamotion.Website.zip
2015-08-31T08:58:26.3172576Z packageFile= D:\Build\d0a91b73\artifacts\drop\Quamotion.Website.zip
2015-08-31T08:58:26.3172576Z Get-AzureWebSite -Name quamotion -ErrorAction SilentlyContinue
2015-08-31T08:58:32.8066037Z Publish-AzureWebsiteProject -Name "quamotion" -Package "D:\Build\d0a91b73\artifacts\drop\Quamotion.Website.zip" 
2015-08-31T08:59:09.8584050Z ##[error]Web Deploy experienced a connection problem with the server and had to terminate the connection.  Contact your server administrator if the problem persists.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CONNECTION_TERMINATED.
```

**Comment by bryanmacfarlane** [comment]
Was this a one time failure or is it persistent?  Is it still reproducing?

**Comment by qmfrederik** [comment]
Hi Bryan,

I still reproduces, every time.

Frederik.

**Comment by chrisrpatterson** [comment]
Could you try and deploy your package using that command let from a powershell on your machine? I am not able to reproduce this.

**Comment by bryanmacfarlane** [comment]
@qmfrederik - also want to confirm that the build machine has network access to azure.  is this on-prem TFS or VSO?  We still can't repro so anything interesting network wise will help.

**Comment by qmfrederik** [comment]
@chrisrpatterson I ran the `Publish-AzureWebsiteProject` command on the VM and that completed successfully.

```
PS D:\> Publish-AzureWebsiteProject -Name "quamotion" -Package "D:\Build\d0a91b73\artifacts\drop\Quamotion.Website.zip"

VERBOSE: [Start]    Publishing package D:\Build\d0a91b73\artifacts\drop\Quamotion.Website.zip
VERBOSE: [Complete] Publishing package D:\Build\d0a91b73\artifacts\drop\Quamotion.Website.zip
```

So that seems to rule out a network connectivity 

I authenticated to Azure using the `Add-AzureAccount` command. The VSO task uses the certificate to authenticate, so perhaps that triggers different behavior.

I've tried to authenticate to Azure using the certificate. However, I don't have the `Get-X509Certificate` command available in a standard Azure PowerShell. How would you suggest I go about and manually run the deployment in PowerShell, while mimicking as close as possible the commands that the task actually uses?

I did gave it a try on the Hosted agent, and did proceed. So at least the setup of the Azure subscription in VSO seems to be correct.

I'm kind of at loss, so I guess being either able to run the exact same PowerShell commands the task executes would help, or some additional logging in the tasks themselves.

**Comment by chrisrpatterson** [comment]
The fact it works in hosted build and on your work station but not form your build VM to me does indicate network on some level.

You can run the exact commands https://github.com/Microsoft/vso-agent-tasks/blob/master/Tasks/AzureWebPowerShellDeployment/Publish-AzureWebDeployment.ps1

**Comment by adriaanthomas** [comment]
It looks like we're running into the same issue.

I have one build agent on Azure (West-Europe, VSO in West-Europe too) that works without any problems, but when I add a second one it keeps running into the above error. I compared the log output between the two (from the Azure Web App Deployment task) but they are exactly the same (apart from working directory which was on the D drive for the new agent, but I also tested that on C like the working agent, same result).

I am also able to run `Publish-AzureWebsiteProject` with the artefact from the build, on the faulty build VM (also after running `Add-AzureAccount`), so it does not appear to be a networking issue. Also, the hosted agent works, so it does not appear a configuration issue either.

When I compare the agent capabilities in VSO, they appear exactly the same. I also installed the build agent software from the same zip as the first agent, using the same VSO account, but it still does not work.

How can I help?

**Comment by adriaanthomas** [comment]
I do not have this issue when I create a build agent with size `Standard_D2`, but I do with size `Standard_D1`.

**Comment by purplepiranha** [comment]
This is definitely stressing me out!

I have the issue with my build agent running on the Basic_A1 size, but not with Basic_A2. I don't really want to have to run such a large instance purely because of deployment. I already limit it to running during daylight hours to save costs.

I can run everything ok through powershell, but via the build agent it fails.

It looks like it's a timeout issue on the Azure Wep App, but the logs tell me nothing.

**Comment by purplepiranha** [comment]
Also tried creating my own Azure Powershell script to do this rather than using the 'Azure Web App Deployment' build step. Still the same problem...

Works fine on the box, just not through VSO.

I'm wondering whether this a deliberate attempt by MS to make us either use their hosted build service (at a cost) or pay more for an Azure VM?

Why should web deploy need so much processor power? Surely it just copies the zip file across and then does all the work at the other end?

I'm using West Europe for both agent VM and the site that I'm deploying to. Has anyone had the same issue anywhere else?

**Comment by qmfrederik** [comment]
Hi @chrisrpatterson, @bryanmacfarlane 

So, there's three of us now who can each consistently reproduce the problem with Azure VMs. 
All of us host our VMs in the West Europe region.

May be related to the VM size (Basic_A1, Standard_A1 apparently don't work, whereas Basic_A2 and Standard_A2); at the same time, running the command from PowerShell does work.

Any thoughts? Can you reproduce this problem on, say, a Basic_A1 VM running in West Europe?

**Comment by yaananth** [comment]
sorry wasn't able to get to this. I created a VM to test this, i am on vacation for few weeks, but will try my best to atleast repro and we can get to it from there.

**Comment by yaananth** [comment]
So I did this -
Standard A1 size VM
West Europe

Against my own account in South Central US.

I didn't see any problem and webapp is deployed. So not sure what else we can do here.

**Comment by AndreaPic** [comment]
Hi,
I'have the same issue

My environment is:
App Service plan/pricing tier
 - Pricing Tier
 - Free
Location
- West Europe
Subscription name
- Visual Studio Professional with MSDN

In Visual Studio On Line the endpoint configuration is configured with :
Type: Azure
Connecting to service using certificate

Thanks for any suggestions

**Comment by yaananth** [comment]
@andreapic what build agent are you using?

**Comment by AndreaPic** [comment]
Hi @yaananth  
sorry for the late reply but I was on holiday.

I'm using Visual Studio On Line with free hosted agent, zero private agent then I have a free shared agent.
I haven't my private VM for the agent.

**Comment by qmfrederik** [comment]
Hi @yaananth 

I believe we have also started seeing this issue using the hosted Visual Studio build service (so no custom VM). Our account is hosted in the Europe region.

I believe we've opened a ticket with product support for this, @bartsaintgermain should be able to give you the ticket # if that helps.

Frederik.

**Comment by yaananth** [comment]
@qmfrederik sure that would help. We are seeing some perf issues lately.

**Comment by AndreaPic** [comment]
Hi @yaananth,@qmfrederik,@bartsaintgermain 
I think I found the problem.
I've made a build process with "Copy Publish Artifact" task before "Azure Deployment" task and in this configuration I reproduce the problem ("Copy Publish Artifact" work fine and "Azure Deployment" goes in "ERROR_CONNECTION_TERMINATED").
If I move the "Copy Publish Artifact" after "Azure Deployment", "Azure Deployment" work fine but "Copy Publish Artifact" is not executed (it remain gray).
It seems that there is an incompatibility between "Copy Publish Artifact" and"Azure Deployment".
What do you think ?

**Comment by chrisrpatterson** [comment]
Can you ping your account and send the result.  I would be interested to know which scale unit you are on.  Also which azure region are you targeting for your deployment?

**Comment by qmfrederik** [comment]
Hi @chrisrpatterson 

We’re on `tfsprodweusu4.cloudapp.net` and deploying to West Europe.

Hi @yaananth 

Issue # was 116010513545526

**Comment by AndreaPic** [comment]
Hi @chrisrpatterson
We reproduce the problem on tfsprodweusu4.cloudapp.net [191.233.96.220] in West Europe.
Thanks

**Comment by purplepiranha** [comment]
It's good to see that this is being looked into. I haven't tried again recently as I've had a lot on.

I'm also on `tfsprodweusu4.cloudapp.net` and was deploying to West Europe.
.

**Comment by KrishnaAdityaB** [comment]
@qmfrederik @adriaanthomas @purplepiranha If you are still seeing this issue: 
1. try the root cause mentioned at #1555 
2. reopen this
