### ISSUE TITLE
DownloadBuildArtifact - allow to specify a custom build ID and project name

### ISSUE THREAD

**Issue by garuma** [Microsoft/vsts-tasks#4710]
The task currently doesn't allow to specify a build ID other than "This build", it also doesn't allow to specify another project to get artifacts from.

Use case: a build definition triggers a build on another project build definition (e.g. running on a different OS) to produce a set of artifacts necessary for the first build, the DownloadBuildArtifact task should be usable to retrieve those generated artifacts.

**Comment by bryanmacfarlane** [comment]
Yes, all those are planned on our backlog.  The download task is in preview for this reason.
