### ISSUE TITLE
MSBuild Parameters

### ISSUE THREAD

**Issue by golfguru** [Microsoft/vsts-tasks#4711]
I'm running in to an issue that I can't seem to figure out. I'll describe the process below, and any information you can provide that will help me resolve this will be hugely beneficial to me.

I currently have a working Build Solution step that is using /p:OutDir="$(build.binariesdirectory)\\" as the MSBuild Argument, but giving me results that I don't like.

The problem with this configuration is that it outputs all the web.**.config files, so it hasn't done the transform to give me just the finalized web.config file like I get when I do a "Publish", instead I get the web.config, web.debug.config and web.release.confg files separately.

The other thing I don't like is that it puts the "roslyn" stuff in the main bin folder instead of a folder called "roslyn" in the bin folder (which is also something I get when I do a "Publish")

What I would like to do is have a nice clean package like I get when I do a "Publish"...so all the roslyn files in in the bin\roslyn folder and I get a single web.config file because it has been transformed properly. I've tried the following arguments in the MSBuild Arguments field, without any success. In fact when I use the following parameters I get an empty "b" folder when doing the build:

/p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:publishUrl=$(build.binariesdirectory)

I can't seem to get this to work correctly, so any help you can give will be beneficial.

fyi, I am currently running Team Foundation Server 2017 Update 1 on premise.

**Comment by bryanmacfarlane** [comment]
Seems like an msbuild issue, not a CI task issue.

Reactivate if you think the msbuild or vsbuild task isn't passing args etc... correctly
