### ISSUE TITLE
Nuget Restore task 1.0.1 fails to pickup nuget.config from Source root 

### ISSUE THREAD

**Issue by henning-krause** [Microsoft/vsts-tasks#4719]
TFS version: 2017.2 on-premise
Task version: 1.0.1

Given the following folder structure:

Source root
|-- Nuget.Config
|-- ConsoleApplication1
    |-- ConsoleApplication1.sln
    |-- ConsoleApplication1
        |-- ConsoleApplication1.csproj

The Nuget.config specifies a central target directory for the Nuget packages

If I build the solution from within Visual Studio 2017, the Nuget packages are restored and the solution is compiled correctly.

However, If I use the "NuGet Installer" task in my TFS build, the Nuget.config is ignored and the build process subsequently fails because Nuget restores the packages to a different directory where they are not picked up by MSBuild.

Is this the expected behavior?

**Comment by alexmullans** [comment]
Currently, you'll need to tell the task about your NuGet.Config in the 'Path to NuGet.Config' option.

**Comment by henning-krause** [comment]
@alexmullans, I'm using the version 1.x of the tasks, not the 0.x one.

The version 1 task let's me manually specify the destination directory for the packages, but not the path to the config file.
![image](https://user-images.githubusercontent.com/12197701/27872444-1eb97adc-61a9-11e7-9995-2cbb182aba96.png)

**Comment by alexmullans** [comment]
Have you tried the "Feeds in my NuGet.Config" radio button in the section above?

**Comment by henning-krause** [comment]
Ah.. okay. Thanks.
