### ISSUE TITLE
AzureRmWebAppDeployment not using Kudu to deploy on windows machine

### ISSUE THREAD

**Issue by samvdd** [Microsoft/vsts-tasks#4722]
In the AzureRmWebAppDeployment task you can define if you would like to use WebDeploy or Kudu. The only problem is if the deployment is done on a Windows machine it always deploys with WebDeploy (see code below).
In our case we would like to use Kudu deployment on our windows depoyment machine because we need to execute some extra commands.

Code from: webdeployment-common/utility.js :
```
export function canUseWebDeploy(useWebDeploy: boolean) {
    var win = tl.osType().match(/^Win/);
    return (useWebDeploy || win);
}
```
Code from: AzureRmWebAppDeployment\azurermwebappdeployment.ts :
```
if(deployUtility.canUseWebDeploy(useWebDeploy)) {
	if(!tl.osType().match(/^Win/)){
		throw Error(tl.loc("PublishusingwebdeployoptionsaresupportedonlywhenusingWindowsagent"));
	}

		var appSettings = await azureRESTUtility.getWebAppAppSettings(endPoint, webAppName, resourceGroupName, deployToSlotFlag, slotName);
		if(renameFilesFlag) {
			if(appSettings.properties.MSDEPLOY_RENAME_LOCKED_FILES == undefined || appSettings.properties.MSDEPLOY_RENAME_LOCKED_FILES == '0'){
				appSettings.properties.MSDEPLOY_RENAME_LOCKED_FILES = '1';
				await azureRESTUtility.updateWebAppAppSettings(endPoint, webAppName, resourceGroupName, deployToSlotFlag, slotName, appSettings);
			}
		}
		else {
			if(appSettings.properties.MSDEPLOY_RENAME_LOCKED_FILES != undefined && appSettings.properties.MSDEPLOY_RENAME_LOCKED_FILES != '0'){
				delete appSettings.properties.MSDEPLOY_RENAME_LOCKED_FILES;
				await azureRESTUtility.updateWebAppAppSettings(endPoint, webAppName, resourceGroupName, deployToSlotFlag, slotName, appSettings);
			}
		}
		console.log("##vso[task.setvariable variable=websiteUserName;issecret=true;]" + publishingProfile.userName);
		console.log("##vso[task.setvariable variable=websitePassword;issecret=true;]" + publishingProfile.userPWD);
		await msDeploy.DeployUsingMSDeploy(webDeployPkg, webAppName, publishingProfile, removeAdditionalFilesFlag,
						excludeFilesFromAppDataFlag, takeAppOfflineFlag, virtualApplication, setParametersFile,
						additionalArguments, isFolderBasedDeployment, useWebDeploy);
} else {
	tl.debug("Initiated deployment via kudu service for webapp package : " + webDeployPkg);
	if(azureWebAppDetails == null) {
		azureWebAppDetails = await azureRESTUtility.getAzureRMWebAppConfigDetails(endPoint, webAppName, resourceGroupName, deployToSlotFlag, slotName);
	}
	await DeployUsingKuduDeploy(webDeployPkg, azureWebAppDetails, publishingProfile, virtualApplication, isFolderBasedDeployment, takeAppOfflineFlag);

}
```
i would suggest the following to be changed in the webdeployment-common/utility.js (change || to &&):

```
export function canUseWebDeploy(useWebDeploy: boolean) {
    var win = tl.osType().match(/^Win/);
    return (useWebDeploy && win);
}
```

(Another suggestion is the check for windows in the first "if" should not be done because it is already validated in the canUseWebDeploy.)

**Comment by vincentdass** [comment]
@samvdd , thanks for the feedback.
Can you please explain what type of commands you need to execute ?

**Comment by samvdd** [comment]
Well for example the .deployment / deploy.cmd should be run by Kudu. Or for example we would like to run "npm install". We do release management with VSTS and it does automatic deployments to an azure webapp. But the npm packages are not included in the deploy.

**Comment by vincentdass** [comment]
You can run Post Deployment Script from the same Task.
Enable Deployment Script type to "Inline Script" and paste your commands in next input field (If the script char. count < 500) or select File type and choose your deploy.cmd (if available in artifact).

![image](https://user-images.githubusercontent.com/20121508/27907714-5eccbf0e-6266-11e7-831b-aaaf824d3b4c.png)

**Comment by vincentdass** [comment]
@samvdd, Are you able to run your custom script using the above feature ?

**Comment by samvdd** [comment]
The above feature is working for us, thank you. I would suggest to have a look at the original problem as well.

**Comment by vincentdass** [comment]
@samvdd , Deploy option is selected based on platform.
Wed Deploy (MSDeploy) option is made default for Windows platform to support customers with MSBuild packages. 
For other platforms, Kudu REST API is used. Please note that deployment hook is not invoked with this call.
To support this, we added Post Deployment script feature.

**Comment by vincentdass** [comment]
Closing the thread, as there is no action item.
