### ISSUE TITLE
Tie the Efforts to Task and Bug level

### ISSUE THREAD

**Issue by jachakrohit07** [Microsoft/vsts-tasks#4727]
Right now I have tied the Efforts at the PBI level. But now as the PBI has different tasks, I want to tie the Efforts at the Task and bug level which will sum up and show overall PBI efforts. Do I need to do any change in the workflow from Visual Studio Professional, so that the "Efforts" field will pop up whenever I create a new task under the PBI?

I would really appreciate detailed comments.

**Comment by bryanmacfarlane** [comment]
This doesn't seem like a CI server build task issue.  If so, reactivate with the task from this repo you're having an issue with (the list is in source under Tasks folder) and the build log.

**Comment by jachakrohit07** [comment]
Is there any specific Microsoft group where I can raise this question? It is not a bug

**Comment by bryanmacfarlane** [comment]
https://developercommunity.visualstudio.com and select Team Services
