### ISSUE TITLE
Only load test folder is copied to Agents

### ISSUE THREAD

**Issue by Gogeta094** [Microsoft/vsts-tasks#4739]
Greetings!

Our performance tests project contains folder with web tests, load test, assets etc.
What I've investigated from your script - that only folder, where load test leaves is being copied to the target test agent. Because of that all other important files are missing.

Q: Do I have only option to copy all .webtests, assets, .dlls to the folder where .loadtest leaves, or there is an other option how to deal with this?

Thanks!

**Comment by dpksinghal** [comment]
Yes it is the expected behavior. You need to copy the dependent files into the same folder. 

If you don't want to change the original drop location as part of the build, you can write a custom script and have it run as a task to move the copy to the folder where the loadtest file resides.
