### ISSUE TITLE
Multi-Agent with Visual Studio Test task is not distributing tests across 2 agents but executing all tests on both agents

### ISSUE THREAD

**Issue by jonlanceley** [Microsoft/vsts-tasks#4742]
I have a simple test of 6 unit tests which as part of a release are executed using 'Run on Agent' set with Multi-Agent, number of agents 2.  Should add this is TFS 2017.1

I have 1 Visual Studio Test task set to Visual Studio 2017 and using version 1.* or 2.* preview results in the same thing.  All the tests are executed by both agents.  So if I had 6 tests, after the run is complete it says 12 tests were executed.  I'm expecting 3 tests to be run on each agent = 6 tests should be executed.

Am I missing something that needs setting up? Or is this a bug?
Thanks
![capture](https://user-images.githubusercontent.com/4244440/27953406-8fd45fd8-6303-11e7-8536-09532001fdf5.PNG)

**Comment by dpksinghal** [comment]
Can you please share the release logs with us?

**Comment by jonlanceley** [comment]
This is what is executing:
![capture](https://user-images.githubusercontent.com/4244440/27977891-a976323e-6364-11e7-89dd-4b7f6abf49c6.PNG)

And the results:
The same 13 tests run on each agent
![capture2](https://user-images.githubusercontent.com/4244440/27977941-f42ad0a0-6364-11e7-942d-d9835b9dfb12.PNG)

The task setup (I've tried v1 agent, and run in parallel check box as well):
![capture3](https://user-images.githubusercontent.com/4244440/27978074-84c82554-6365-11e7-8e22-b0cfcc73f8ba.PNG)


Logs:
[ReleaseLogs_2024.zip](https://github.com/Microsoft/vsts-tasks/files/1132416/ReleaseLogs_2024.zip)

**Comment by jonlanceley** [comment]
Hi just wondering if anyone has any ideas about resolving this?

**Comment by vimegh** [comment]
@jonlanceley  Sorry we have been bit busy and it seems we have missed replying to this thread. 
I went through the logs provided, and I can clearly see that distribution has not kicked in, instead this is running same tests in 2 different agents. 

In order to further investigate, can you please help us by sharing the trx files generated (can be found attached to test run), and also release logs created with variable system.debug=true in release definition so that we can see debug logs. Thanks.

**Comment by jonlanceley** [comment]
Ok, thanks @vimegh for letting me know it's not supported as it's not obvious in the multi-agent setup box.  Do you know if this going to be in TFS 2017.2 ?

**Comment by vimegh** [comment]
@jonlanceley Yes support for distributing to multiple agent by VSTest V2 task in release flow is present in TFS 2017.2 and later. 

Closing the issue, please feel free to reopen if you have further queries. Thanks.
