### ISSUE TITLE
Missing leading characters from date and time in NugetCommand messes up ordering

### ISSUE THREAD

**Issue by SayusiAndo** [Microsoft/vsts-tasks#4752]
Hi All,

Thanks for creating NugetCommand task stuff in VSTS. Please find my following findings which should be good to have fixed.

Steps:
- create a small c# project
- set up a build for it
- add NugetCommand task to it
- at command select: Pack
- set up the Pack options - Automatic package versioning value to "Use the date and time"

Run it a few times and check the timestamps in the nuget package version. You will find something like this:

Build time: 17:04:05
result: package name - CI - yyyyMMdd-1745

Build time: 17:13:13
result: package name - CI - yyyyMMdd-171313

The ordering result in Visual Studio (list of packages is descending order) will be you can find below which is not correct.
package name - CI - yyyyMMdd-1745
package name - CI - yyyyMMdd-171313

The ordering should be like this:
package name - CI - yyyyMMdd-171313
package name - CI - yyyyMMdd-170405

**Comment by alexmullans** [comment]
This is fixed by #4775. Will be live in the next day or so.
