### ISSUE TITLE
Option for Symbols parameter in NugetCommand

### ISSUE THREAD

**Issue by SayusiAndo** [Microsoft/vsts-tasks#4753]
Hi all,

Thank you for creating NugetCommand!

I would like to request a checkbox for Symbols parameter. This way the package can contain pdb files too as it is described in [Nuget manual](https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#pack).

Thanks!

**Comment by ChristopherHaws** [comment]
I agree. I am having to use the `custom` command and pass all the arguments to nuget.exe manually. I would like to see this option added, or at the very least a way to add additional command arguments so I can add `-symbols` to it.

**Comment by alexmullans** [comment]
This is fixed by #4775. Will be live in the next day or so.

**Comment by alexmullans** [comment]
This is fixed by #4775. Will be live in the next day or so.
