### ISSUE TITLE
Timezone selector for datetime used in package versioning in NugetCommand

### ISSUE THREAD

**Issue by SayusiAndo** [Microsoft/vsts-tasks#4754]
Hi All,

Thanks for creating NugetCommand!

I would like to ask a timezone selector because timestamp used in package name when "Use the date and time" is in UTC. If I want some consistency between my nuget package name and my build name where I use timestamp too there will be 2 hours difference (I'm not in UTC timezone and VSTS build process uses my local time) which makes the the package management a bit complicated.

Thanks!

**Comment by alexmullans** [comment]
This is fixed by #4775. Will be live in the next day or so.
