### ISSUE TITLE
NuGet Restore Intermittently Fails

### ISSUE THREAD

**Issue by acgritt** [Microsoft/vsts-tasks#4759]
Using the newest version of the NuGet VSTS task causes an intermittent failure with the following message:

##[error]Error: No neutral-language version resource found in the file
##[error]Packages failed to restore

I cannot seem to find any information online for that error message.  I am not sure if this is an issue with the VSTS Task or with the change to NuGet 4.0 because any of the builds that were using NuGet 3.5 seem to be working fine and the new task doesn't allow control over the NuGet Version to use.

**Comment by alexmullans** [comment]
With the new task, you can add a separate "NuGet Tool Installer" task before the NuGet task, specify "3.5.0" as the version of NuGet to use, and fall back to NuGet 3.5.

I'll also ask someone to take a look at this error.

**Comment by keithrob** [comment]
@acgritt,
The message you are seeing is related to some code in the nuget task where we are trying to detect the nuget version and its associated 'quirks'.  Newer versions of nuget (e.g. 4.x) have fewer issues.  

I don't have too much information about your build env but using the nuget tool installer with the latest nuget build tasks provide a solid alternative to some of the legacy issues.

I'm going to close this; however, if you're still seeing the issue please reopen and we can continue triage.
Keith
