### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by Gogeta094** [Microsoft/vsts-tasks#4760]
I've created "Cloud based Load Test" and pointed it to my test artifacts output folder, which contains all needed Web Tests, Load Test,  testsettings and .dlls.

When test runs, I receive next error:
2017-07-10T11:08:41.6896968Z ##[warning][Exception] 1 occurrences of ['DownloadXML','DownloadXML','FileNotFoundException'] : Could not load file or assembly 'PerformanceTestsPlugins.PerformanceTests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. 

It is unable to find test plugin .dll, which is present on folder, which is being copied to Test Agents.
Just, to notice, I've tried to add that .dll as deployment item to .testsettings, but it seems, that this part of settings is not being taken into account.
Locally this load test works fine.

**Comment by vimegh** [comment]
@Gogeta094 Can you please share the screenshot of your Cloud based Load Test task definition Basically we want to confirm what path is being provided to Load test files folder? Is it a shared path? 
Also where this task is being used in build or release pipeline? 

Can you please send build/release logs created with system.debug=true set in variables to   vsoloadtest@microsoft.com for us to further check the problem.

**Comment by vimegh** [comment]
@Gogeta094 If you are still facing issue, please forward us the logs at task screenshot as mentioned in previous comment.

**Comment by Gogeta094** [comment]
@vimegh Oh, sorry for the delay. The issue was resolved by creating another artifacts source only for Performance Tests project. So it works fine for now!

**Comment by vimegh** [comment]
Thanks for updating @Gogeta094 . Closing the issue.
