### ISSUE TITLE
[Feature] Nuget Command - Pack - Custom Version

### ISSUE THREAD

**Issue by ChristopherHaws** [Microsoft/vsts-tasks#4763]
In the `nuget command` task, it would be nice to have the ability to select `Custom` from the `package version` dropdown and be given a parameter where we could enter in a custom version scheme such as `$(NugetPackageVersion)-ci-$(Build.BuildNumber)`. While I could make this an environment variable, I would prefer to have the ability to just enter this directly into the task itself.

Thanks!

**Comment by alexmullans** [comment]
For full control of the arguments provided to NuGet, we recommend using the "Custom" option in the "Command" dropdown.
