### ISSUE TITLE
Visual Studio 2017 version not available in Visual Studio Build Step

### ISSUE THREAD

**Issue by adailsonfilho** [Microsoft/vsts-tasks#4773]
Hi guys,

First of all thanks for making this open source! There follows my scenario:

**Environment**
- TFS 2015 update 4
- Visual Studio 2015 and 2017 installed where the agent runs

**Problem**
When using *Visual Studio Build Step* the *Visual Studio 2017* version is not available. In the drop down we have the following options: [Latest, 2015, 2013, 2012] ... But when we choose *Latest * 2015 is used. I had to use *MSBuild step* pointing out the path to MSBuild bin folder for VS 2017 (like is the solutions suggested here: https://stackoverflow.com/questions/42689384/how-to-use-visual-studio-2017-with-tfs-visual-studio-build-step)

Thanks in advance!

**Comment by ericsciple** [comment]
Specifying the path to msbuild is the solution for older TFS using newer VS. TFS doesn't know how to locate future VS versions. In fact the way to locate VS changed drastically between 2015 VS and 2017.

**Comment by ericsciple** [comment]
If we ever move to a model of publishing the tasks out of band (instead of, or in addition to being, bundled with TFS), that would be another way out of this problem.

**Comment by adailsonfilho** [comment]
Copy that! Thank you for clarifying it!
