### ISSUE TITLE
Config transform in Release when using AzureRmWebAppDeployment

### ISSUE THREAD

**Issue by AmeetAB** [Microsoft/vsts-tasks#4776]
Hi,

We have a product version specific build that has a release pipeline that goes from QA -> UAT -> PROD all on Azure.

We've somehow got the config transform to execute but will issues. The issue is that it picks up the Web.Release.config even when the environment variable "ReleaseConfiguration" is set to CloudQa, CloudUat & CloudProd in the variables section. Also the task for deployment fails without any logs so I've had to literally wait for it to come to a point when it fails while watching the logs and take a printscreen. That's how we've found out that the transform is happening with Web.Release.config which does not have any transform related entries in it.

How do I force the task to transform using the "ReleaseConfiguration" value?

**Comment by vincentdass** [comment]
@AmeetAB , Currently transformation is applied using Release-Environment Name.

 You need to change Release Environment Name and not Release Configuration.
![image](https://user-images.githubusercontent.com/20121508/28115621-48d11350-6723-11e7-8f34-8c38982e60c3.png)

Please change the Environment name to (CloudQa, CloudUat or CloudProd).

Old Editor View: 
![image](https://user-images.githubusercontent.com/20121508/28115582-282cf1aa-6723-11e7-8893-2866c425d809.png)

**Comment by AmeetAB** [comment]
That is what I got:

![image](https://user-images.githubusercontent.com/20840812/28121471-dc81f320-6738-11e7-86b6-a22822529d54.png)

**Comment by vincentdass** [comment]
@AmeetAB , *.Release.config is selected by default when available( in the same folder).
Order of Transformation  applied is as follows: `*.Release.config` followed by  `*.<Environment_Name>.config`

![image](https://user-images.githubusercontent.com/20121508/28129076-a11982fa-674f-11e7-8d1a-c83c33fc9b64.png)

**Comment by AmeetAB** [comment]
@vincentdass applied
```
<?xml version="1.0"?>
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
</configuration>

```
to both Web.Debug.config and Web.Debug.config and made the CI build configuration to run on "Debug" this resulted in the release picking the environment specific config file for transformation for the web api.

We, however, also have a web job as part of the solution which we'd like deployed. Although I'm getting the webjob deployed as desired, the transformation of App.config isn't happening. Here's the log from the release:
![image](https://user-images.githubusercontent.com/20840812/28155938-4b8a91a6-67ce-11e7-816b-ddf1c4d02a61.png)

It seems that the XML Transformation is looking for a Web.config and the transformation file instead of App.config. How do we handle App.config transformation? Here are the tasks in `CloudProd` environment:
![image](https://user-images.githubusercontent.com/20840812/28156035-9b1f5d8c-67ce-11e7-9da7-1a3366876750.png)

And this is the config of the web job deploy task:

![image](https://user-images.githubusercontent.com/20840812/28156092-df6d3efa-67ce-11e7-960e-ef70a2e1f3eb.png)

We have a lot of components using webjobs and releases with webjobs are important as part of ALM. Your help is appreciated!

**Comment by vincentdass** [comment]
@AmeetAB, To apply transformation in `App.config` file, your transformation configuration files should be named `App.Release.config` or `App.<EnvironmentName>.config` 

Can you please ensure that the files are present in same folder as well?

**Comment by AmeetAB** [comment]
@vincentdass they're in a different project but at the root and in the format App.<EnvironmentName>.config etc

In our case, App.CloudDev.config and so on.

**Comment by vincentdass** [comment]
@AmeetAB , can you please share the debug logs for the release (by setting  variable `system.debug = true`)?

Need to confirm whether the artifact contains the config and transform file in the same folder.

**Comment by AmeetAB** [comment]
@vincentdass here's some more information from my research:

I have also found another "gotcha":
On the project that contains the transformation files, this 
`<FilesToIncludeForPublish>AllFilesInTheProject</FilesToIncludeForPublish>`
has to be entered as a sub element of this property group of the csproj file
`<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' "> `
Our CI build runs on `debug` configuration so that's where I've got that <FilesToIncludeForPublish> entry, if someone runs CI in release mode then it has to obviously be included in that property group.

Unless the above happens, the config files are not part of the artifact package and transformation at release time cannot find the <Environment> specific transform file.

With webjob kind projects, in the build, this happens: 
```
2017-07-13T07:22:33.2974267Z _CopyAppConfigFile:
2017-07-13T07:22:33.2974267Z   Copying file from "App.config" to "bin\Debug\Transactions.WebJob.exe.config".
```
Obviously, at this point the App.config file has been changed into Transactions.WebJob.exe.config in the artifact package. I'm trying to apply the transformation at Release time and it cannot find the App.config or the corresponding App.<Environment>.config file. I can get the files to get copied over by adding <FilesToIncludeForPublish> but what about the App.config file getting copied into something else?

**Comment by vincentdass** [comment]
@AmeetAB , As you mentioned App.config is renamed to "<Application_Name>.exe.config". This is done by MSBuild to match the executable application file name [[Link](https://msdn.microsoft.com/en-us/library/ms229689(v=vs.90).aspx)].


You need to rename your transform files something like this
```
App.CloudProd.config => Transactions.WebJob.exe.CloudProd.config
App.CloudQA.config => Transactions.WebJob.exe.CloudQA.config
```

**Comment by AmeetAB** [comment]
@vincentdass did what you recommended and although the files are part of the artifact, the transformation task still seems to be looking for Web.config file for transformation.

![image](https://user-images.githubusercontent.com/20840812/28215041-37ef47c0-68ca-11e7-9e8c-96eb169ba34d.png)

Transform files:
![image](https://user-images.githubusercontent.com/20840812/28215099-702dc6de-68ca-11e7-93ca-c0a72156888c.png)

Actual config file:
![image](https://user-images.githubusercontent.com/20840812/28215196-c1a85f92-68ca-11e7-8d78-400c2af3674d.png)

**Comment by vincentdass** [comment]
@AmeetAB , please share the debug logs for the same.

**Comment by AmeetAB** [comment]
@vincentdass what's the best way to send you these logs?

**Comment by vincentdass** [comment]
@AmeetAB , you can paste the logs here.
You can also send the logs to RM_Customer_Queries@Microsoft.com with subject as "Config transform in Release when using AzureRmWebAppDeployment #4776" for reference.

**Comment by vincentdass** [comment]
@AmeetAB , closing the thread as there is no action item on us. (Based on the offline discussion)
Feel free to reopen or create a new issue, if required.
