### ISSUE TITLE
Jenkins Download Artifacts Task Failed

### ISSUE THREAD

**Issue by mousumid** [Microsoft/vsts-tasks#4778]
hi,
i am trying to create Jenkins build in TFS 2017. i have create Jenkins endpoint service and Jenkins service hook both the connection is succeed but in Download artifacts task is failed, where as in Jenkins server build is succeeded. My download artifacts task screen short is below.
![untitled](https://user-images.githubusercontent.com/24930378/28114199-5730f3c6-671d-11e7-972b-92e55173a675.png)
 And error is  "Could not find any artifacts for job TFS2017_job from build number 7".
please help me to resolve this issue.

**Comment by DavidStaheli** [comment]
Hi @mousumid, thank you for creating this issue.  Can you please create a variable on the **Variables** tab of your build definition named **System.Debug** with a value of **true**?  Then, can you please re-run the build and send the log file to me at dastahel at microsoft dotcom?

**Comment by mousumid** [comment]
Hello @David i already done this.

**Comment by DavidStaheli** [comment]
Did you already send the log file to me or someone else at Microsoft?  I've been out-of-office and still getting caught up.

**Comment by mousumid** [comment]
No @DavidStaheli. 
exactly right now in my Jenkins Server bin and obj/Debug folder is created but in my agent work folder bin and obj/Debug is not created.  below is the screen short. because of that "Could not find any artifacts for job TFS2017_job from build number 11" error is coming.
![2](https://user-images.githubusercontent.com/24930378/28115695-92c809a0-6723-11e7-93fd-ef10b55bb89e.png)
![3](https://user-images.githubusercontent.com/24930378/28115698-95ca5cc0-6723-11e7-90e0-2a1891e53a59.png)
