### ISSUE TITLE
New nuget publish task not compatible with minimatches fro

### ISSUE THREAD

**Issue by heaths** [Microsoft/vsts-tasks#4781]
With the old, task-specific build tasks now deprecated (e.g. NuGet Publish), I ported our settings over to the new NuGet task (using "publish" operation) but found - after many builds failed to actually publish any packages (i.e. not an error, just didn't do anything) - the tasks must assume a different root.

The old task appears to have used `$(Build.SourcesDirectory)` (or more likely `$(System.DefaultWorkingDirectory)`) as the root while the old one...well, I can't tell from the logs (something else that could be improved: task log just shows header; probably should log relevant variable values).

While it may be a breaking change to the new tasks to change the working directory now, at the very least it should probably be documented what the working directory is or that admins shouldn't rely on any particular root and use a root variable regardless.

**Comment by alexmullans** [comment]
This is by design - by default, the `pack` option will send packages to $(Build.ArtifactStagingDirectory) and the `push` option will pick up from that same directory. 

The `Path to NuGet package(s) to publish` textbox (right after the `Command` dropdown) gives you full control over where to find packages to publish.

**Comment by heaths** [comment]
And it's not working. The value I have in there is: `$(Build.SourcesDirectory)\**\*.nupkg;-:**\*.symbols.nupkg;-:**\packages\**\*.nupkg`. So even rooted, it's not finding packages.

**Comment by alexmullans** [comment]
Try `$(Build.SourcesDirectory)\**\*.nupkg;!**\*.symbols.nupkg;!**\packages\**\*.nupkg`. The task is now using the build task library's standard path parsing.

**Comment by heaths** [comment]
Trying that now. Note that the syntax is not documented in https://www.visualstudio.com/en-us/docs/build/steps/package/nuget#push-nuget-packages.

**Comment by alexmullans** [comment]
I'll queue an update to that page to add a link to https://www.visualstudio.com/en-us/docs/build/steps/file-matching-patterns, which covers the patterns.

**Comment by heaths** [comment]
Thanks. With this syntax, the files were discovered and processed appropriately.
