### ISSUE TITLE
Why does label source step not use the modified variable's value which defined in label format

### ISSUE THREAD

**Issue by lvsezhufu** [Microsoft/vsts-tasks#4784]
Assume I add a variable `testvar` in variables tab with value `old`.

And I modify the value by a PowerShell task: `Write-Host ("##vso[task.setvariable variable=testvar;]new")`.

And I define to tag source with the label formate `$(testvar)`.

As we knows, the value of testvar will be updated after it's modified by the PowerShell task. label sources is the last step for a build, but it still add a tag with name `old`. So why does label sources step not use the update value `new` to add the tag?

**Comment by FizzBuzz791** [comment]
I've just encountered this same issue. We're using Major.Minor.DayOfYear.HHMM-Nightly to tag our nightlies and the above process seemed like the obvious way to do this. If it's different then there definitely needs to be some documentation updates around this (or document, period, I haven't found anything so far).

**Comment by FizzBuzz791** [comment]
Scrap that, appears to be related to [#193](https://github.com/Microsoft/vsts-task-lib/issues/193).
Although documentation seems to have lost the bit pertaining to agent scope.
