### ISSUE TITLE
'PowerShell on Target Machines' task does not report output in the event of an exception being thrown

### ISSUE THREAD

**Issue by DanielBMann9000** [Microsoft/vsts-tasks#4787]
Create a console application as follows:
```
namespace TestConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello world!");

            try 
            {
                throw new NotImplementedException("Goodbye World!");
            }
            catch (Exception e) 
            {
                Console.WriteLine(e.Message);
                throw;
            }
            
        }
    }
}
```

If you run this application directly via the PowerShell on Target Machines task, it fails and **no output is reported**.

If you write a wrapper PowerShell script to run the console application,
```
param($ThingToRun)
try {
    Write-Verbose "start" -verbose
    $output = &$ThingToRun
    Write-Verbose $output -Verbose
    Write-Verbose "end" -verbose
}
catch {
    Write-Verbose "catch" -verbose
    Write-Verbose $output -Verbose
    Write-Verbose $_
    throw $_
}
finally {
    write-verbose "finally" -verbose
    Write-Verbose $output -Verbose
}
```
This will *also* not report any output from the console application **or** from the PowerShell script.

This is a huge issue because it makes debugging failing scripts essentially impossible. Setting `system.debug` to `true` does not change anything. Is this a known issue, or is there a workaround?

**Comment by chshrikh** [comment]
@DanielBMann9000  could you please try your ps script like this -

$ThingToRun = "<EXEAPP>"        
Write-Verbose "Start with $ThingToRun" -Verbose

$result =  cmd /c $ThingToRun 2`>`&1 

if($LASTEXITCODE -ne 0 )
{
    throw $result
}
else
{
    Write-Verbose "App logs $result" -Verbose
}

**Comment by chshrikh** [comment]
ensure you escape '>' '&' like -"$result =  cmd /c $ThingToRun 2``>``&1"

**Comment by chshrikh** [comment]
ensure you escape ">" and "&" symbols

**Comment by chshrikh** [comment]
![image](https://user-images.githubusercontent.com/11972852/28414508-906f578e-6d69-11e7-8105-a998d8a2462a.png)

**Comment by vincentdass** [comment]
@DanielBMann9000 , Is the issue resolved?
