### ISSUE TITLE
'Powershell on Target Machines' task fails if the supplied username contains a period.

### ISSUE THREAD

**Issue by DanielBMann9000** [Microsoft/vsts-tasks#4790]
In issue #2405, it was reported that if you use a period in a username in the Powershell on Target Machines task, the task will fail.

The suggested fix was "don't use a username with a period in it". That is not a solution, that is a workaround. The task should be fixed to support all valid Windows usernames.

**Comment by chshrikh** [comment]
DanielBMann9000  I am unable to repro the issue,. I used the user name for my azure vm as "domain.user1" it is working fine
