### ISSUE TITLE
PublishCodeCoverageResults should succeed with a warning when summary file does not exist

### ISSUE THREAD

**Issue by Blackbaud-TommyVernieri** [Microsoft/vsts-tasks#4800]
When the file PublishCodeCoverageResults task cannot find the summary file, the task fails with the following output:

```
Reading code coverage summary from 'C:\vsts-agent-win7-x64-2.111.1\_work\558\s/coverage/cobertura-coverage.xml'
##[error]Unable to process command '##vso[codecoverage.publish codecoveragetool=Cobertura;summaryfile=C:\vsts-agent-win7-x64-2.111.1\_work\558\s/coverage/cobertura-coverage.xml;reportdirectory=C:\vsts-agent-win7-x64-2.111.1\_work\558\s/coverage;]' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
2017-07-14T21:56:34.0259256Z ##[error]File 'C:\vsts-agent-win7-x64-2.111.1\_work\558\s/coverage/cobertura-coverage.xml' does not exist or is not accessible.
```

Contrast this with the output from the PublishTestResultsTask in a similar scenario:

```
##[warning]No test result files matching testresults\junitresults.xml were found.
```

Related code: https://github.com/Microsoft/vsts-tasks/blob/5100fd3719a26cb6021752f3e4326609df955df8/Tasks/PublishTestResults/publishtestresults.ts#L26

I propose the PublishCodeCodeCoverageTask should check for the existence of the summary file and issue a warning instead of an error in some cases. If the summary file does not exist and the "Fail When Code Coverage Results Are Missing" option is not checked, then output a warning and allow the task to succeed. If the summary file does not exist and the "Fail When...Missing" option is checked, then keep the current behavior: an error and a failed task.

If a missing file should fail the build, the Build Quality Checks task can handle that job.

This change will enable reuse of task groups across builds that do and do not include code coverage summary files.

**Comment by lkillgore** [comment]
OK, @Blackbaud-TommyVernieri, I'm convinced.  I've made a PR with your proposed behavioral change: https://github.com/Microsoft/vsts-tasks/pull/4820, which is currently under review.

Thanks for your contribution!
