### ISSUE TITLE
Cannot run functional tests in interactive mode in TFS 2017 team project

### ISSUE THREAD

**Issue by marcopierobon** [Microsoft/vsts-tasks#4817]
Hey,

We are trying to run our functional tests in interactive mode using TFS 2017 with team project source control.
We got this running in other team projects where GIT is used.
We deploy the test agent with the option for updating it activated
We have also tried to reuse the test agent machines from the GIT team project where it works, to no avail.

The DTAExecutionHost.exe.txt gives

I, 8816, 1, 2017/07/18, 12:33:38.397, 44435081265562, DTAExecutionHost.exe, Main.TryReadAndCacheVssCredentials Acquiring the Token Info
I, 8816, 1, 2017/07/18, 12:33:38.485, 44435082478968, DTAExecutionHost.exe, Communicating to the Token Service http://myTfsUrl:8080/tfs/myCollection
W, 8816, 1, 2017/07/18, 12:33:39.528, 44435097416029, DTAExecutionHost.exe, Service task failed. Retry attempt 10.
I, 20572, 1, 2017/07/18, 12:33:42.835, 44435144796158, DTAExecutionHost.exe, Main.TryReadAndCacheVssCredentials Acquiring the Token Info
I, 20572, 1, 2017/07/18, 12:33:42.928, 44435146081842, DTAExecutionHost.exe, Communicating to the Token Service http://myTfsUrl:8080/tfs/myCollection
I, 20572, 1, 2017/07/18, 12:33:44.749, 44435172160608, DTAExecutionHost.exe, Closing the Token Service
I, 20572, 1, 2017/07/18, 12:33:46.151, myTestMachine\DTAExecutionHost, ExecutionTaskStateModel.GetExecutionAdapter : Initializing VstestAdapter.
I, 20572, 1, 2017/07/18, 12:33:46.152, myTestMachine\DTAExecutionHost, ExecutionTaskStateModel.Start : Starting to monitor tasks
V, 20572, 1, 2017/07/18, 12:33:46.157, myTestMachine\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent
Web method running: [http://myTfsUrl:8080/tfs/myCollection/_apis/test/Agents/74959/Commands/0] (GET)0[test]
I, 20572, 1, 2017/07/18, 12:33:46.214, 44435193134421, DTAExecutionHost.exe, ********************************************************************
I, 20572, 1, 2017/07/18, 12:33:46.214, 44435193135389, DTAExecutionHost.exe, Main.InitializeAndStartExecutionHost. ExecutionHost has been started
Web method response: [http://myTfsUrl:8080/tfs/myCollection/_apis/test/Agents/74959/Commands/0] (GET)0[test] 57 ms
V, 20572, 7, 2017/07/18, 12:33:46.606, myTestMachine\DTAExecutionHost, TestExecutionServiceCommandQueueListener:DispatchAsync
W, 20572, 7, 2017/07/18, 12:33:46.609, myTestMachine\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : TestExecutionCommand received with None. Retrying it.
W, 20572, 7, 2017/07/18, 12:33:46.610, myTestMachine\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 3000 milliseconds.
V, 20572, 4, 2017/07/18, 12:33:49.620, myTestMachine\DTAExecutionHost, TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent Microsoft.TeamFoundation.Test.WebApi.TestAgent

Calling the API at _http://myTfsUrl:8080/tfs/myCollection/_apis/test/Agents/74959_
gives the result {"id":74957,"name":"myTestMachine","dtlEnvironment":{"id":0,"url":"dta://env/myProject/_apis/82470/201707181206420966"},"dtlMachine":{"id":0,"name":"myTestMachine:5985"},"capabilities":[],"testRunId":-1}
I assume the error is caused by testRunId":-1 as test executions from the GIT projects have a positive testRunId.
Why?

**Comment by vimegh** [comment]
@marcopierobon Can you please share complete build/release logs with variable system.debug set to true.
Also this seems to be part of DTAExecutionHost.exe.log, if you can clean dta logs folder before run and then share those logs with us, that will be really helpful in order for us to understand the problem here. Also in case you dont want to post here, you can email us at devops_tools[at]microsoft[dot]com . Thanks.

**Comment by marcopierobon** [comment]
I sent you an email with the logs

**Comment by vimegh** [comment]
@marcopierobon We have received the logs, we will analyze and get back to you.  Thanks.

**Comment by ExperienceITDetroit** [comment]
Hello, any update on this issue?

**Comment by mkonkolowicz** [comment]
Hello, I am seeing the same issue. Can you please provide an estimated time frame for sharing of investigation results?

**Comment by tanvi-soni** [comment]
@marcopierobon  Can you share the release logs for the project where it works so that we can compare the two scenarios. Also, can you try running the release after disabling custom slicing once.
You can email us at devops_tools[at]microsoft[dot]com

**Comment by tanvi-soni** [comment]
@marcopierobon Can you share the release logs for the project where it works so that we can compare the two scenarios.

**Comment by prawalagarwal** [comment]
@mkonkolowicz @marcopierobon  Are you still facing this issue?

**Comment by mkonkolowicz** [comment]
Hey guys,

Sorry, I haven't re-examined the issue in a few weeks, due to having to moved on to a different project. I will re-examine sometime in the next two weeks are reply. 

Thanks for following up!

**Comment by prawalagarwal** [comment]
We cannot reproduce the scenario on our side. The source control and the test task have no relation and are completely independent. Once the code is pulled from the appropriate version control, the test task uses that code to proceed further and is not dependent on what version control exists.

The error might be due to some other issue. Please reopen if you are still facing this.
