### ISSUE TITLE
VSTS dashboard widgets are not open source

### ISSUE THREAD

**Issue by ChristophB125** [Microsoft/vsts-tasks#4818]
The VSTS dashboard widgets for build results are not useful when using branches as I want to show only results of a specific branch.
If the VSTS widgets were open source similar to the tasks, I could fix this much more easily rather than having to write my own extension from scratch

**Comment by bryanmacfarlane** [comment]
I'll pass the feedback along.  I agree any extension would ideally be OSS as reference examples.  Closing here since not an issue with this repo.

**Comment by ChristophB125** [comment]
@bryanmacfarlane Thanks for passing the feedback on. The problem is that there is no practically useful way to raise issues (with the hope of actually achieving something) for VSTS other than the Github repos as UserVoice seems to be a dead letter box and in the past I also experienced that the VSTS team is not even responding on their Twitter account...
