### ISSUE TITLE
NPM Task is not taking environments files

### ISSUE THREAD

**Issue by paonekumar** [Microsoft/vsts-tasks#4826]
NPM task for building angular application with environment argument is running a default dev build 

build --prod --env=fut

Task

![image](https://user-images.githubusercontent.com/24321604/28349420-66bb01d4-6c08-11e7-9d9e-2095ddcbdeb6.png)

Log
![image](https://user-images.githubusercontent.com/24321604/28349471-a3b506ac-6c08-11e7-97b3-8482ee48fee0.png)

**Comment by keithrob** [comment]
@paonekumar,
I cannot tell what your npm run-script is actually doing but it looks like you're trying to pass the arguments "--prod" and "--env=dev100" to it.  The [NPM documentation states](https://docs.npmjs.com/cli/run-script) that you need to use the "--" delimiter to indicate that these custom arguments should be passed to spawned scripts.  As such, I think you need " build -- --prod --env=dev100".
