### ISSUE TITLE
ASP.NET (Preview) template fails with ASP.NET Core web project

### ISSUE THREAD

**Issue by Allann** [Microsoft/vsts-tasks#4831]
We were hoping to move to VSTS instead on TFS On-prem, but we have hit a huge roadblock I can't believe no-one else has.  Hence I am wondering what I have done wrong and need help to sort it out.

I have vanilla ASP.Net Core web project created by VS2017 15.2 (26430.16). Attached the solution in a zip file.
[WebApplication1.zip](https://github.com/Microsoft/vsts-tasks/files/1160840/WebApplication1.zip)

This is the error returned by the build 
> 2 error(s), 1 warning(s)
> --
> Build - 2 error(s), 1 warning(s)
> C:\Program Files   (x86)\Microsoft Visual   Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeployPackage.targets(124):C:\Program   Files (x86)\Microsoft Visual   Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeployPackage.targets(124,7):   Error MSB4184: The expression "[System.IO.Path]::GetDirectoryName('')"   cannot be evaluated. The path is not of a legal form.
> Process   'msbuild.exe' exited with code '1'.
> 

I have attached the log from the last build too:
[logs_92.zip](https://github.com/Microsoft/vsts-tasks/files/1160844/logs_92.zip)

It uses the Hosted agent instead of our local build agent as I thought it might be something we had setup wrong, but that didn't work either.

**Comment by bryanmacfarlane** [comment]
Can you confirm which queue you are using?  Hosted Pool or VS2017 Hosted Pool?  From log it looks like latter.

Also as a troubleshooting step, have you tried with a private agent?  Wondering if it's because hosted image is 15.1 and you have a 15.2 project??

**Comment by Allann** [comment]
Hosted VS2017.

**Comment by Allann** [comment]
FYI, it builds, runs, and publishes via VS2017 fine when run through the IDE.

**Comment by Allann** [comment]
More investigation reveals that the defaults added to a new build definition may be the culprit.

When I changed the MSBuild arguments to 

/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactstagingdirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"

the build started to work.  The default shown below:
/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"
contains a '\\' on the end of the PackageLocation variable.  Now sure what this is meant to be.

**Comment by bryanmacfarlane** [comment]
OK - taking the agent out of the picture ...

The build log shows exactly what command lines we are running.  Can you run the exact same command line and see if it repros?  Trying to figure out if cmdline vs VS thing.  (our agent just runs that command line).

**Comment by bryanmacfarlane** [comment]
When you created the build definition, what template did you use?

**Comment by Allann** [comment]
ASP.NET (Preview) but removed the Publish symbols path task.  everything else I left as default

**Comment by Allann** [comment]
It was the '\\\\' in the default arguments.  I just confirmed it in the original one that was failing too.

I realise that anything in Preview is not to be relied on, but the older ASP.Net core dotnet template never really worked well for us since we had multiple NuGet package stores and one of them was the Telerik Nuget store which we couldn't access unless we hardcoded a clear text password in the nuget.config file.

**Comment by bryanmacfarlane** [comment]
Thanks!  We will fix that.

**Comment by scottboehmer** [comment]
After investigating this a bit, it looks like the ASP.NET (Preview) template is only intended to work with full ASP.NET projects and it is working for those projects without any issues. When I tried removing the slashes from the template, it still did not work for a default ASP.NET Core project and would require further changes which could potentially cause the template to no longer work as well with full ASP.NET projects.

For an ASP.NET Core project, you should be able to use the ASP.NET Core template or customize the build steps to work for your specific project.
