### ISSUE TITLE
ASP.Net Core (preview) test task failing to run the found tests

### ISSUE THREAD

**Issue by Allann** [Microsoft/vsts-tasks#4834]
Hi again,
Now that my build is working I am investigating the reason why my tests are not executed.

[logs_109.zip](https://github.com/Microsoft/vsts-tasks/files/1161232/logs_109.zip)

As can be seen on line 3185 in the test log, it found 2 test assemblies, and 1 testadapter (line 6219).
However, it does not execute any of the tests.  I have tried both debug and release builds with no difference.

I notice that the path in the log specifies **d:\a\3\s\Dev\Jbssa.MasterData\tests\Jbssa.MasterData.UnitTests\bin\Release\netcoreapp1.1\Jbssa.MasterData.UnitTests.dll**
where the physical path is actually:
**d:\agent\\_work\3\s\Dev\Jbssa.MasterData\tests\Jbssa.MasterData.UnitTests\bin\Release\netcoreapp1.1**
but I'm assuming that it is using a path alias??? or something, since the build set uses a similar path ProjectFile: 'd:\a\3\s\Dev\Jbssa.MasterData\Jbssa.MasterData.sln'

Can anyone shed some light on why my tests are not being executed?

**Comment by vimegh** [comment]
@Allann Two things:
1. searchFolder=d:\a\3\s
Have you set this search folder in task definition. Check if you have used some variable which is having incorrect value? Aslo have you added any smbolic link,  as I can see "findOptions.followSymbolicLinks: 'true'"? 

2. How are you passing the test adapter path?  And what happens if you run the command printed in logs manually via cmd? 
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" d:\a\3\s\Dev\Jbssa.MasterData\tests\Jbssa.MasterData.UnitTests\bin\Release\netcoreapp1.1\Jbssa.MasterData.UnitTests.dll d:\a\3\s\Dev\Jbssa.MasterData\tests\Jbssa.MasterData.UnitTests\bin\Release\netcoreapp1.1\xunit.runner.visualstudio.dotnetcore.testadapter.dll /EnableCodeCoverage /logger:trx "/TestAdapterPath:\"d:\a\3\s\""

**Comment by vimegh** [comment]
@Alann Did you get the chance to try to check points mentioned in previous comments. Thanks.

**Comment by Allann** [comment]
@vimegh - sry i missed the response above, will check my spam filters.  
1. I can't use that search folder, if i do it won't run on the different agents we use (local and hosted). Currently we use ($(System.DefaultWorkingDirectory)
2.  I'm not.  There is a field called Path to custom test adapters. But the info button says Nuget restored packages are automatically searched for.  Since xUnit is installed via NuGet I didn't think I needed to add anything here.
Further I don't have permission to log into the local build server to run the commands locally. However, running them via a similar command line in my own environment works fine. Obviously the paths are different in this instance.

**Comment by Allann** [comment]
As additional information, this is the default test task added by the ASP.NET (PREVIEW) template.  It is easy to reproduce the above issue by creating a new ASP.Net Core web application and then add a xunit test project.
I can't use the ASP.NET Core build template because I can't set the credentials for external collections (i.e. telerik.com).  If this is not the case and this can be added to that template, can you please give instructions as to how this is achieved.
The steps in the current template:
NuGet restore:
- NuGet 2.*
- Command: restore
- Path to solution: **/*.sln
- Feeds: Feeds in my nuget.config
- Path to Nuget.config: $Master Data/Dev/Jbssa.MasterData/nuget.config
- Credentials for feeds: telerik.com
Build solution:
- Version 1.*
- Solution: **\*.sln
- Visual Studio Version: latest
- MSBuild arguments: /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactstagingdirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"
- Platform: $(BuildPlatform)
- Configuration: $(BuildConfiguration)
Test Assemblies:
- Version 2.*
- Select tests using: Test assemblies
- Test assemblies: **\$(BuildConfiguration)\netcoreapp1.1\*test*.dll !**\obj\**
- Search folder: $(System.DefaultWorkingDirectory)
- Test filter criteria: blank
- Run only impacted tests unchecked
- Run Test mix contains UI tests unchecked
- Select test platform using: Version
- Test platform version: Latest
- Settings file: blank
- Code coverage checked
- Build platform: $(BuildPlatform)
- Build configuration: $(BuildConfiguration)

Hope this helps clarify a little

**Comment by vimegh** [comment]
Thanks @Allann for sharing the details. Assigning to Tanvi to check it out.

**Comment by cltshivash** [comment]
@Allann The VSTest task currently doesn't support dot net core tests. You will need to use the dotnet core task with the command as test . You can add a publish test results task to publish the results back to the service. There is an improvements planned here with respect to results publish. The dotnet core task will do an auto publish of the results with the command as test.

**Comment by Allann** [comment]
@cltshivash thanks for getting back to me on this, i'll try to add that tomorrow when i'm back at work.  
Just as an aside, I find it strange that a ASP.Net Core solution template which includes tests doesn't actually support the tests project. Maybe that is just me?  Is there an expected delivery on this?
To prevent others from having the same issue, shouldn't the ASP.Net Core (preview) template have the test task removed since it doesn't support tests?
