### ISSUE TITLE
Calling a tool is hanging.  Need more details

### ISSUE THREAD

**Issue by lucky10893** [Microsoft/vsts-tasks#4836]
I am doing a VSTS build.It is running perfectly in my machine but when we try to run it in the build server it is getting struck into one step:"deleting .manifest.pregam" and after that build will get terminated after the buffer time.We are suspecting that this maybe the problem because of the certificate installation in the build machine as in log files it showing that the build is waiting for the "Signfile".Can anyone here suggest me how to overcome this hurdle?your suggestions will be appreciated.

**Comment by Fizcko** [comment]
Maybe it is just a problem of rights on the server. The account witch is running the TFS service have sufficient rights to delete this file ?

**Comment by lucky10893** [comment]
yes...the account have all the rights that are needed ..what i got from my analysis is that there must be some codesigning certificate issue as in the logfile it shows waiting for Signfile...and it is at that moment that our build hangs...we had already installed in the certificate in the build machine but then also this error is coming...so is there any other way by this certificate error may arise?

**Comment by bryanmacfarlane** [comment]
It's unclear on what task you're using, how you're using it and what's happening.  This issue just states you're having some issue with signing.  Typically means a file in use (typically intermittent) or you're calling a tool that needs an interactive UI (typically repos every time)

**Comment by bryanmacfarlane** [comment]
Closing for now due to lack of details.
