### ISSUE TITLE
Test Agent: What should we input as the parameter "Environment"?

### ISSUE THREAD

**Issue by aivendor** [Microsoft/vsts-tasks#4844]
![image](https://user-images.githubusercontent.com/20854126/28457701-b9d7af92-6e39-11e7-814e-1f95ab7cfdd3.png)
hi, I'm adding a deploy test agent task in tfs portal.
I had some virtual machines to run test on. I want to deploy tests with VS 2015 test agents which is said no need for test controller. So I didn't configure the test environment traditionally. So what should we input as a environment name? It's a necessary field. I didn't see an environment field in your guide page.
[guide page](https://www.visualstudio.com/en-us/docs/test/continuous-testing/set-up-continuous-testing-builds)
Some errors related to environment happened.
System.IO.FileNotFoundException: The specified module 'Microsoft.TeamFoundation.DistributedTask.Task.DistributedTestAutomation' was not loaded because no valid module file was found in any module directory.
System.Management.Automation.ParameterBindingException: A parameter cannot be found that matches parameter name 'EnvironmentName'.
PowerShell script completed with 2 errors.

**Comment by nigurr** [comment]
@aivendor This task is internal test task. Please use "Deploy and Configure Test agent" task which is official and publicly available.

**Comment by aivendor** [comment]
😀OK thanks

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
