### ISSUE TITLE
Slot settings on app start task doesn't save

### ISSUE THREAD

**Issue by twilly86** [Microsoft/vsts-tasks#4851]
I am having an issue with my build definition saving the slot settings on the stop azure app service task.

I check the "specify slot" box and save the build definition and refresh the screen and it goes back to being un-checked.

![image](https://user-images.githubusercontent.com/3496838/28470693-cbcafdb8-6df7-11e7-9a83-dfb81cc6b8ed.png)

**Comment by tjrobinson** [comment]
I'm having the same problem. It just caused my Production slot to get stopped! This is critical functionality to be correct.

**Comment by tjrobinson** [comment]
Note: This affects Builds, not just Releases.

**Comment by jmiddelkamp** [comment]
Same problem here... pretty annoying

**Comment by tjrobinson** [comment]
@jmiddelkamp @twilly86 I've emailed the team at Microsoft and had a brief response to say they'll look into it.

**Comment by jmiddelkamp** [comment]
@tjrobinson @twilly86 everything works fine if you save it in the old editor. So for the time being we could use this as a work-around.

**Comment by chshrikh** [comment]
we are taking a look

**Comment by chshrikh** [comment]
We have found the root cause for this issue, we are in process to fix this and get it hot fixed. We will keep you updated on same.

**Comment by jkonecki** [comment]
Could you provide ETA for the fix please? This is a critical piece of functionality.

**Comment by youngcm2** [comment]
It is in both start and stop to be clear.

**Comment by chshrikh** [comment]
If your scenarios is on Build then we have rolled out fix for Build, currently we are in process for rolling out fix for Release Management.

**Comment by Blackbaud-DerekAnderson** [comment]
Any update on when this will be resolved for Release Management?

**Comment by chshrikh** [comment]
this has been fixed for Release Management as well

**Comment by jmiddelkamp** [comment]
@chshrikh Thanks for the update!

**Comment by jkonecki** [comment]
@chshrikh Could you please close this issue to reflect its done status?
