### ISSUE TITLE
Checkbox menu in npm does not select properly

### ISSUE THREAD

**Issue by t-jakurl** [Microsoft/vsts-tasks#4853]
When using the checkbox multi-select dropdown menu labeled "Credentials for registries outside this account/collection" in npm and npm authenticate, you must click within the checkbox to select or deselect an option. The cursor, however, changes as if the entire option (including name and the rest of the bar) was clickable, and the change in color when mousing over an option also implies that the entire area is clickable.

**Comment by GitHubSriramB** [comment]
@t-jakurl - can you enable "New Release Definition Editor" preview feature and try this in the new Release Definition editor? We will be switching over to the new editor in new month or so & we are currently not fixing issues in the old editor. Pl. let us know if this issue repros in the new editor as well.

**Comment by t-jakurl** [comment]
This issue is also present in the new editor. The text is clickable, but the box is not, even though the cursor acts as if the box is. 

Also, when I select the "manage endpoints" gear option, it changes the group I'm in. 
![image](https://user-images.githubusercontent.com/29716162/28728325-1089bcd4-737d-11e7-9f0a-4d2047e0a757.png)
![image](https://user-images.githubusercontent.com/29716162/28728337-2310fcc8-737d-11e7-8e4c-8cef848398de.png)

**Comment by GitHubSriramB** [comment]
@t-jakurl - Apologies for the inconvenience. I will track fixing both the issues you identified. Thanks for your feedback.
