### ISSUE TITLE
FTP Upload - ECONNRESET 

### ISSUE THREAD

**Issue by Thieum** [Microsoft/vsts-tasks#4863]
When using the FTP Upload task on TFS On-Premise, and having the firewall up or down, the upload fails with an ECONNRESET error. 

If I use the cURL task it connects to the same server without any error, with firewall down for this program. (But curl doesn't work for recursive directory upload)

**Comment by DavidStaheli** [comment]
Hi @Thieum, thanks for reporting this.  We've known about the issue for a while and suspected it had to do with Azure Web Apps or IIS.  Are you using the FTP Upload task with either of those?

**Comment by Thieum** [comment]
It might be, as the ftp is located on Arvixe servers ( https://www.arvixe.com/ ), and we are using their windows servers. Not sure if there is a way to ask the server what it is running through ftp.

**Comment by Thieum** [comment]
This PowerShell script works in any case for us:


```
# Parameters
param(
    [Parameter(Mandatory=$true)][String]$ftpUrl,
	[Parameter(Mandatory=$true)][String]$ftpBasePath,
	[Parameter(Mandatory=$true)][String]$ftpUser,
	[Parameter(Mandatory=$true)][String]$ftpPwd,
	[Parameter(Mandatory=$true)][String]$pathToDeploy
)

# Get files
$files = Get-ChildItem -Path $pathToDeploy -recurse  
# Get ftp object
$ftp_client = New-Object System.Net.WebClient
$ftp_client.Credentials = new-object System.Net.NetworkCredential($ftpUser, $ftpPwd) 
$ftp_address = "ftp://" + $ftpUrl +"/" + $ftpBasePath
# Make uploads
foreach($file in $files)
{
    if ($file.Attributes -eq "Directory")
    {
        $directory = "";
        if ($file.FullName.Length -gt 0)
        {
			$directory = $file.FullName.Replace("\","/").Replace($pathToDeploy.Replace("\","/"),"")
        }

		try  
		{  
			"Creating dir $ftp_address/$directory"
			$makeDirectory = [System.Net.WebRequest]::Create( $ftp_address + $directory);
			$makeDirectory.Credentials = New-Object System.Net.NetworkCredential($ftpUser,$ftpPwd)
			$makeDirectory.Method = [System.Net.WebRequestMethods+FTP]::MakeDirectory;
			$makeDirectory.GetResponse();
		}  
		catch [System.Net.WebException]  
		{  
			$response = $_.Exception.Response;
			if ($response.StatusCode -eq [System.Net.FtpStatusCode]::ActionNotTakenFileUnavailable)
			{
				"Unable to create dir $ftp_address/$directory"  
			}
			else
			{
				Write-Error $_.Exception.Message
				Break
			}
		}  
    }
    else{
        $directory = "";
        $source = $file.DirectoryName + "\" + $file;
        if ($file.DirectoryName.Length -gt 0)
        {
			$directory = $file.DirectoryName.Replace("\","/").Replace($pathToDeploy.Replace("\","/"),"")
        }
        $directory += "/";
        $ftp_command = $ftp_address + $directory + $file
        $uri = New-Object System.Uri($ftp_command)
        "Uploading $directory$file..."
        $ftp_client.UploadFile($uri, $source)
    }
}
```

**Comment by filipczaja** [comment]
We are experiencing the same issue when uploading over FTP to an Azure WebApp.
Do you have any workarounds apart from dedicated PS script?

**Comment by joshmgross** [comment]
Closing this issue to clean up the backlog. Reopen this if the issue presents itself again.

**Comment by yashika06** [comment]
I am experiencing the same issue when trying to upload files over FTP to Azure Web App. Any pointers on this will be very helpful.

**Comment by vincentdass** [comment]
@yashika06 , sorry for the late response. Can you post your query [here](https://social.msdn.microsoft.com/Forums/azure/en-US/home?forum=windowsazurewebsitespreview) regarding app service?
