### ISSUE TITLE
Packer: Autogenerated configuration missing service principal objectID

### ISSUE THREAD

**Issue by sam-cogan** [Microsoft/vsts-tasks#4870]
When using the autogenerated packer template for building a windows machine image it will fail at the point it is creating a Keyvault with a fairly vague error:

`azure-arm: resources.DeploymentsClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="DeploymentFailed" Message="At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details."`

The issue seems to be down to the fact that the part of the script that assigns rights to the service principal to the KV it has created requires the objectID parameter to be supplied, which the VSTS auto generated implementation  does not seem to provide. This is the object ID of the service principal running the step.

This can be easily replicated just by trying to run any Windows VM image creation. I have tested with a custom packer file run locally and get the same error if an Object ID is not provided. Providing it resolves the issue.

**Comment by bishal-pdMSFT** [comment]
@sam-cogan are you using VSTS or on-prem TFS? If you are using VSTS, and have created ARM service endpoint using auto-creation mode, then you should not face this issue.

**Comment by sam-cogan** [comment]
I am using VSTS, but I'm not creating the end point using auto creation, I am adding it manually. It's not possible for me to use auto creation due to the way our environment is set up.

**Comment by bishal-pdMSFT** [comment]
@sam-cogan we are working to fix this

**Comment by bishal-pdMSFT** [comment]
#4919
