### ISSUE TITLE
Cannot create a virtual directory under a physical folder in a website using IIS Web App Manage

### ISSUE THREAD

**Issue by chrisnicholson** [Microsoft/vsts-tasks#4880]
I have a **IIS Web App Manage** step which creates a website: **Website**.

I then have a **IIS Web App Deploy** step which deploys a series of files and folders to **Website**. One of those physical folders created is called **products**. ie Website/products

I then have a **IIS Web App Manage** step which attempts to create a virtual directory (**myvirdir**) underneath this **products** folder. ie Website/products/myvirdir

The fields for this step have populated as follows:
The **Parent website name** has been set as **Website**
The **Virtual path** has been set as **/products/myvirdir**
The **Physical path** has been set as **%SystemDrive%\inetpub\wwwroot\MyVirDir**

Running this throws an error:
**Must use exact identifer for VDIR object with verb ADD**

The command that gets run is:
<pre>
##[command]"C:\Windows\system32\inetsrv\appcmd.exe"  add vdir /app.name:"Website/products" /path:"/myvirdir" /physicalPath:"%SystemDrive%\inetpub\wwwroot\MyVirDir"
</pre>

With some manual intervention to restore the values to how they were entered, the command which runs successfully needs to look like:
<pre>
C:\Windows\system32\inetsrv\appcmd.exe add vdir /app.name:"<b>Website/</b>" /path:"<b>/products/myvirdir</b>" /physicalPath:"%SystemDrive%\inetpub\wwwroot\MyVirDir"
</pre>

If I do not try to create **myvirdir** below **products**, so simply at the root level, then the behaviour is correct.

Given the values I have entered, I am not sure why the **Parent website name** value is modified to combine it with a portion of the **Virtual path** value.

Any suggestions?

**Comment by asranja** [comment]
Thanks for pointing this out to us @chrisnicholson .

The preview IIS Web App Manage task currently supports managing virtual directories of the form - Site/Vdir or Site/App/Vdir. 

We will add the support for nested virtual directories and virtual directories within nested applications.

**Comment by vercellone** [comment]
+1 @RoopeshNair Any updates on this enhancement?  Would a PR serve to expedite or hinder it?

**Comment by asranja** [comment]
Closing this issue. The fix has been made in the task. Thanks for contributing @vercellone #6308
