### ISSUE TITLE
Error installing HockeyApp

### ISSUE THREAD

**Issue by MookieFumi** [Microsoft/vsts-tasks#4881]
Hi, I can't install HockeyApp on my account. The message error is:

> An undefined error occurred while attempting to connect to the server. Status code 0: error.

Account: analyticalways.visualstudio.com

![image](https://user-images.githubusercontent.com/4056557/28633292-9a1374b8-7233-11e7-8eb7-a0f7449cf970.png)

https://marketplace.visualstudio.com/items?itemName=ms.hockeyapp&install=true

Thank you sou much.

**Comment by MookieFumi** [comment]
I have tried one more time and now the error is: 
![img_0164](https://user-images.githubusercontent.com/4056557/28642214-de9d37c2-7251-11e7-87e4-283fa65cb559.PNG)

Any suggestion? 

Thank you so much!

**Comment by bryanmacfarlane** [comment]
Issues here track tasks in this repo.

email me and I'll get you connected to someone who can help.  It's bryanmac and that's microsoft
