### ISSUE TITLE
Visual Studio Test build task - Unable to retrieve "Override TestRun Parameters" from CodedUITest class

### ISSUE THREAD

**Issue by Bebo2345** [Microsoft/vsts-tasks#4883]
We are using the _Visual Studio Test_ task to run our tests. Classes that specify the _TestClass_ attribute successfully retrieve the values specified by the _Override TestRun Parameters_ field on the build task via _TestContext.Properties_.

However, classes that use the _CodedUITest_ attribute are unable to retrieve the override values.

Is there any way to retrieve the values specified in the _Override TestRun Parameters_ field from _CodedUITest_ classes?

We are currently using TFS 2017 Update 1 OnPrem and Visual Studio 2015 Update 3.

Thanks!

**Comment by nigurr** [comment]
@Bebo2345 currently this functionality is not supported. Please use this link to refer to alternative solutions
https://stackoverflow.com/questions/32597776/testcontext-testrunparameters-in-coded-ui-test
