### ISSUE TITLE
[Feature] Ability to propogate environment changes

### ISSUE THREAD

**Issue by degant** [Microsoft/vsts-tasks#4903]
We have most of our apps using VSTS Release Management for releasing and deploying. All environments have been set up in the Release Definition i.e DEV1, DEV2, PPE1, PPE2, PROD etc. For the setup we created one environment with all the required tasks, tested it out, and later cloned it to created as many environments as required. 

Now every time we make few changes to tasks or steps in one environment it becomes an additional overhead to propagate the same changes to all the other environments. How about having something like _'Clone Changes to all other environments'_ - which will try to propagate the changes (made in the current revision) to the other environments. Not sure how feasible this is, but would be great to know what the developers have in mind. 

If there's a simpler way to get this done, please let me know or point me to a document explaining the same.

Thanks!

**Comment by bryanmacfarlane** [comment]
I'll pass along this feedback but it's not an issue with a task in this repo.

**Comment by degant** [comment]
Is there a different repo where I can post this? or uservoice?

**Comment by bryanmacfarlane** [comment]
https://developercommunity.visualstudio.com/spaces/21/index.html

**Comment by bryanmacfarlane** [comment]
or user voice

**Comment by degant** [comment]
Thanks @bryanmacfarlane. Although this is the incorrect repo for the feature request like you mentioned, sharing the uservoice links in case someone is looking for the same:

1. [Be able to copy a task to other environments](https://visualstudio.uservoice.com/forums/330519-team-services/suggestions/16617955-be-able-to-copy-a-task-to-other-environments)
2. [Release management: Task should be movable between agent phases](https://visualstudio.uservoice.com/forums/330519-team-services/suggestions/17032645-release-management-task-should-be-movable-between)

or use Task Groups instead, as explained [here](https://www.visualstudio.com/en-us/docs/build/concepts/library/task-groups). Completed [uservoice link](https://visualstudio.uservoice.com/forums/330519-team-services/suggestions/17695744-use-a-single-set-of-release-tasks-for-multiple-env)
