### ISSUE TITLE
NuGet restore should use the endpoint URL when provided and not rely on nuget.config

### ISSUE THREAD

**Issue by BiribiriJaNai** [Microsoft/vsts-tasks#4906]
Hi,
Trying to use the 2.0.5 version of Nuget task, I'm having some troubles figuring how to make it work with the restore command. 
I don't want to check in a nuget.config file. I expect the task to use the endpoint URL, as it already uses the credentials provided (just like in the push command).

**Comment by alexmullans** [comment]
Can you tell me more about your scenario? Specifically: are you restoring from package feeds outside of the Package Management extension in your VSTS account?  And, how are you restoring the packages locally without a NuGet.config?

**Comment by BiribiriJaNai** [comment]
I am currently using Nexus Repository as artifacts manager, plugged to a Nexus IQ Server.
In Nexus, I have a NuGet group, for reading and restoring purpose, which in turn:
 - Proxifies NuGet.org
 - Proxifies a dev/snapshot NuGet Nexus-hosted repository
 - Proxifies a production/release NuGet Nexus-hosted repository

Indeed, today, both developers and private agents can restore their packages using the default nuget.config file, which contains the URL of the NuGet group.

NuGet publish can only be achieved through a VSTS build/release, using one of two declared NuGet endpoints; one for snapshots, one for releases. In that way, the NuGet task uses the URL defined in the endpoint.

Now, on build agents (hosted or private), If I can avoid using the default nuget.config file when restauring, and -just like when I publish- rely on the endpoint URL, that would be nice.
If I'm not mistaken, the task creates a temporary nuget.config file. Why doesn't it use the endpoint URL?

**Comment by alexmullans** [comment]
Thanks for the response - it's helpful to understand your workflow. Quick clarification: is the 'default nuget.config file" you mentioned above already checked into your repo, or do developers and private agents acquire that file another way? 

To answer your last question: we generally advocate checking in a nuget.config so that the repository contains all the information (including package sources) needed to build successfully.

**Comment by BiribiriJaNai** [comment]
When I say the 'default' nuget.config file, I'm talking about the one created by default when you install Visual Studio: `%ProgramData%\NuGet\Config\` or now `%ProgramFiles(x86)%\NuGet\Config\`.

Today developers are asked to update this file (using Visual Studio) to use Nexus Repository as a package source . This is done manually on private build agents.

**Comment by alexmullans** [comment]
Makes sense; thanks.

We'll take this scenario (constructing a NuGet.config using Service Endpoints) as a potential improvement for v3 of the NuGet task. I'm going to close the GitHub issue and move this to our internal work tracking system so it doesn't get lost. Thanks for your input and for using VSTS!

**Comment by mjring** [comment]
@BiribiriJaNai We are running into a very similar issue with our private build agent with on-prem TFS 2018. What is your current workaround for now? Are you using an older version of the NuGet task? Were you able to find a solution that allowed using the v2.0 NuGet build task without requiring developers to check in the same nuget.config for each repo?

@alexmullans What is the latest on improvements to the NuGet build task to support this scenario?

**Comment by alexmullans** [comment]
@mjring nothing scheduled that directly impacts this, unfortunately. That said, we're starting on a pretty comprehensive revamp of how NuGet (including dotnet and msbuild, when they do NuGet operations) handles auth, which will impact the current implementation of the NuGet task. For example, we may end up not generating a temporary NuGet.config at all. So, I don't think we'd take a change in this area until that work shakes out.

For background, [NuGet/Home/6410](https://github.com/NuGet/Home/issues/6410) and [NuGet/Home/6486](https://github.com/NuGet/Home/issues/6486) are the tracking issues.
