### ISSUE TITLE
web.config prevents static html files from returning

### ISSUE THREAD

**Issue by tomresing** [Microsoft/vsts-tasks#4908]
When I set up continous deployment from github for my web app, the web.config file that was introduced by visualstudioonline.com's release manager stopped my html files from being served. When I deleted the web.config, the files would be served again. However, the continuous deployment transferred the web.config file over again and broke my app again.
Also, the readme.me that is linked to from the web.config settings in release manager doesn't document the web.config propoperty it is linked from:
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureRmWebAppDeployment/README.md
![generate web config](https://user-images.githubusercontent.com/2660081/28754782-911b15fc-7501-11e7-906e-adea3cf43d1e.png)
![dirlisting](https://user-images.githubusercontent.com/2660081/28754784-94364cb6-7501-11e7-940b-d2bc27cb8f2f.png)
![azure404](https://user-images.githubusercontent.com/2660081/28754785-96f4bda2-7501-11e7-8249-352fe3fed914.png)

**Comment by dikhakha** [comment]
Can you please specify for which 'Application framework' are you facing this issue? Also, what input values have you specified for web.config parameters?

**Comment by tomresing** [comment]
I specified Node.js when creating the app, though I'm using static HTML and
client side Javascript only.
When the project was created from the Azure portal, I don't believe I was
prompted for web.config parameters. I discovered them through
troubleshooting. When I deleted the web.config file and then unchecked the
option for web.config, my static html files were served.

**Comment by dikhakha** [comment]
When Node.js option is selected as app framework, it is assumed that server code will be there. Since your project has only client side javascript, web.config file is not needed. Under Azure RM Deployment task, uncheck 'generate web.config' option and save. This will ensure web.config file is not added every time deployment is triggered.

**Comment by tomresing** [comment]
Is there another option which allows for client side javascript? The options I see are ASP.Net, ASP.Net Core, Node.js, PHP and Python.
![configurecontinousdelivery](https://user-images.githubusercontent.com/2660081/28838691-f80c678e-76a5-11e7-8641-736c37619b2c.png)

**Comment by dikhakha** [comment]
Presently there is no option for this particular scenario. You can use Node.js option for one time set up of Continuous Deployment and modify the Release Definition as I mentioned above. We may support such cases in future if the requirement arises.

**Comment by dikhakha** [comment]
@azooinmyluggage Are we planning to support such scenarios in future?

**Comment by azooinmyluggage** [comment]
Hi @tomresing 

Sorry for the inconvenience. Support for static site as well as client side js frameworks is in our backlog. We are also adding support for other npm build scenarios too.

I hope un-checking the "Generate web.config" option in App service Deploy task has unblocked you. Let us  know if you need any help in setting up CI-CD for your app. Happy to help!!

regards,
Atul Malaviya

**Comment by tomresing** [comment]
Thanks. It works when I uncheck that option. It was hard to discover, so I thought I should report. Glad to hear your adding support for static sites and client side Javascript.
