### ISSUE TITLE
TFS2017 Deploy Agent Task V2.* Does Not Choose Proper Path For Agent Installation

### ISSUE THREAD

**Issue by mkonkolowicz** [Microsoft/vsts-tasks#4920]
**Summary**
After downloading the test agent to C:\TestAgent\GUID and copying it to C:\TestAgent, the task attempts to install from the location C:\TestAgent2017Setup. That directory does not exist, and the agent installation throws an error. This error does not happen on Version 1*. of the task. 
[VS2017DeployTestAgentTaskV1.txt](https://github.com/Microsoft/vsts-tasks/files/1188028/VS2017DeployTestAgentTaskV1.txt)
[VS2017DeployTestAgentTaskV2.txt](https://github.com/Microsoft/vsts-tasks/files/1188029/VS2017DeployTestAgentTaskV2.txt)

**Possible Root Cause:**
The problem seems to arise from the deploy test agent task which hard codes the name of the agent directory in case of the VS2017 task on line 137 of https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/DeployVisualStudioTestAgent/InstallTestAgent.ps1

$tpPath = Join-Path $env:SystemDrive TestAgent2017

This path is different from the location of where the agent is copied into (C:\testagent).

**Specific error**
Task 'InstallTestAgent' for machine QA1TSITEST16.MI.CORP.ROCKFIN.COM:5985's Error : System.Exception: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\TestAgent2017Setup\vstf_testagent.exe' because it does not exist.

**Comment by mkonkolowicz** [comment]
The wrong version of the installer is being pulled down to my install directory (v 14)

**Comment by ChrisBertrand** [comment]
What was the solution for this? I'm getting a similar error
