### ISSUE TITLE
Process 'msbuild.exe' exited with code '1'

### ISSUE THREAD

**Issue by deanilvincent** [Microsoft/vsts-tasks#4938]
2017-08-02T03:20:25.4030946Z ##[error]PayrollSystemWebApp\PayrollSystemWebApp\Models\PayrollDbContext.cs(32,67): Error CS0234: The type or namespace name 'SssContributions' does not exist in the namespace 'PayrollSystemWebApp.Models' (are you missing an assembly reference?)

I'm using Continuous Integration via VSTS and I got this error even I already checked-in my model and dbcontext. Everything's working properly on my local machine but I got no idea why I got this Build Solution Error. I tried to host using "Hosted" and "VS2017" but still the problem persists.

**Comment by bryanmacfarlane** [comment]
This is a build error in your solution.  The CI server did the proper thing here - it ran msbuild (the exact command line is in the log) and reported the error.

I would suggest you try setting up a clean machine/VM with just VS, sync your code clean and build with the exact command line to troubleshoot your build issue.  The difference between your machine and Hosted/VS2017, is the Hosted/VS2017 is a fresh clean machine.   It's a clean azure VM with VS installed on it.
