### ISSUE TITLE
Agents are failed to deploy with " The term 'Get-LocalizedString' is not recognized" error.

### ISSUE THREAD

**Issue by aivendor** [Microsoft/vsts-tasks#4946]
We are using Agent task deploy task in VSTS. It worked well yesterday. But today, something wrong is released maybe. Deploy task failed with error
![image](https://user-images.githubusercontent.com/20854126/28906279-025fcc90-7849-11e7-8136-ec2663c78bb1.png)
[ReleaseLogs_25376.zip](https://github.com/Microsoft/vsts-tasks/files/1195992/ReleaseLogs_25376.zip)

**Comment by nigurr** [comment]
@aivendor Did you configure your Release Phase parallel configuration with "Multi-Agent or Multi-Configuration"?
Phase parallelism must be set to None for Run Functional test task. It should throw right error message but failing to throw the same, which we will fix.

**Comment by nigurr** [comment]
Cloing this as its not supported scenario and fixed localization

**Comment by aivendor** [comment]
Thanks
