### ISSUE TITLE
Cannot authenticate on npmjs.com to publish a package with NPM task 1.*

### ISSUE THREAD

**Issue by asiffermann** [Microsoft/vsts-tasks#4956]
Hello,

I'm not sure if this issue should go there as it is more related to the options provided by the NPM service endpoint.

In fact, I tried to publish an existing package to npm.js I was publishing using the 0.* version of the task and an authentication token stored in the .npmrc file on my private build agent.

But with the new version of the task, I cannot neither fill this authentication token in a new NPM service endpoint (supports only Basic Auth or VSTS PAT) nor let the task use my .npmrc file.

I think a third option should be available to create a NPM service endpoint, "npmjs public registry", which would just ask for a connection name and an authentication token. Those would be sufficient to properly generate a .npmrc file at runtime.

Thank you!

**Comment by keithrob** [comment]
@asiffermann ,
When you put the public registry's token into [1], what happened when you clicked "Verify connection"?  This option should work for the public registry although the verbiage is confusing and something we will change.
Keith

[1]
![image](https://user-images.githubusercontent.com/908203/29573937-0e1fc9d8-8715-11e7-8b3e-600c72ffef33.png)

**Comment by asiffermann** [comment]
Hi,

I tried it before (was suspecting the verbiage issue), but it does not work:

![image](https://user-images.githubusercontent.com/12293953/29780916-c6d57a20-8c17-11e7-8115-8559f5db755f.png)

What I put in the PAT field is just the authentication token from npmjs, which looks like a GUID and is working when used from a .npmrc file.

**Comment by keithrob** [comment]
@asiffermann,
We are going to add a 3rd option for registries that use bearer auth (i.e. npmjs).  However, in the meantime might still be able to use basic auth with npmjs and ignore the verify connection button.  The build task should appropriately configure the .npmrc to use basic with npmjs.  This will work as long as [npmjs has basic enabled](http://blog.npmjs.org/post/160809090595/basic-auth-to-be-limited-soon).  
Keith

**Comment by keithrob** [comment]
@asiffermann,
I've fixed this.  You will no longer need to use basic auth for registries that aren't VSTS.  Task should be available on visualstudio.com very soon.

**Comment by asiffermann** [comment]
It seems to be already available on visualstudio.com! Many thanks @keithrob!
