### ISSUE TITLE
Azure file copy: Option to modify "Access type" of container not available

### ISSUE THREAD

**Issue by rhlgupta1383** [Microsoft/vsts-tasks#4957]
While using Azure file copy task, I was not able to find any option to modify the container's access type, which is Private by default.

**Comment by KrishnaAdityaB** [comment]
@rhlgupta1383 This is the design of the task, right now. 
You can add an Azure PowerShell task and modify the access type using cmdlets.

Thanks for bringing up the scenario.
 @RoopeshNair Is there is a specific reason we didn't expose this option? If not, can we consider this as enhancement?

**Comment by RoopeshNair** [comment]
@rhlgupta1383  - can you please post your request on [uservoice](https://visualstudio.uservoice.com/forums/330519-team-services?category_id=145269)?
