### ISSUE TITLE
NuGet restore breaks tests when specifying globalPackagesFolder in nuget.config

### ISSUE THREAD

**Issue by lkruger** [Microsoft/vsts-tasks#4961]
When specifying the globalPackagesFolder in the nuget config (like this)
``
    <config><add key="globalPackagesFolder" value="packages" /></config>
``
and then setting the "Path to NuGet.config" to the checked in nuget.config for the repository, the VsTest task can no longer find any tests.  However, if you leave the "Path to NuGet.config" empty, the tests are found and run properly.  Unfortunately, leaving it blank also creates a warning during the build: "No package sources were found in the NuGet.config file at D:\BuildAgent\_work\138\Nuget\tempNuGet_122239.config"

**Comment by cltshivash** [comment]
@lkruger Can you provide a repro solution (with an empty test method) ? Or provide the build logs (with system.debug set to true). What is the test framework being used ? Is there any test adapter added as a nuget package ?

**Comment by lkruger** [comment]
[logs_125125.zip](https://github.com/Microsoft/vsts-tasks/files/1228577/logs_125125.zip)

Here are the build logs for the failure to find any tests (This occurs by just setting the "Path to NuGet.config" in the restore step.

**Comment by lkruger** [comment]
[logs_125128.zip](https://github.com/Microsoft/vsts-tasks/files/1228585/logs_125128.zip)

Here are the build logs for the same repo with the the "Path to NuGet.config" cleared and where it finds all of the tests that were missed when the "Path to NuGet.config" was set.

**Comment by prawalagarwal** [comment]
Hi @lkruger,

It looks like you are trying to select the Feed source as your own Nuget.config file, and the warning pops up when you leave the Nuget.config file empty. If you are not specifying any particular feeds in your config file you can let the default option be your feed source:

![image](https://user-images.githubusercontent.com/13520100/29558961-4e9e9bca-874b-11e7-81f2-4e36a399f0bd.png)

and then leave the feed drop down as empty and check Nuget.org checkbox. This won't show the warning you are observing. Let us know if this solved your issue. Thanks.

**Comment by prawalagarwal** [comment]
Hi @lkruger ,

Were you able to resolve the issue?

**Comment by prawalagarwal** [comment]
Closing this thread. Please reopen if you are still facing the issue.
