### ISSUE TITLE
Powershell 2.0 inline script does not support passing arguments

### ISSUE THREAD

**Issue by kzu** [Microsoft/vsts-tasks#4971]
The `File Path`-based script allows passing in arguments:

![image](https://user-images.githubusercontent.com/169707/28975784-bf83ba66-7911-11e7-8a6f-be1881fde3bb.png)

The `Inline` one does not, however:

![image](https://user-images.githubusercontent.com/169707/28975795-c9b9cf02-7911-11e7-8109-3b2c1d3c3701.png)

This significantly reduces its usefulness when used in task groups that can automatically discover configurable inputs from arguments used in a script.

Relevant PR: https://github.com/Microsoft/vsts-tasks/pull/4578

**Comment by ericsciple** [comment]
can you add the macros into the inline script itself?

**Comment by kzu** [comment]
Surely can. 

Discoverability plummets and integration with task groups that can automatically discover those arguments and make them task group input properties configurable by the user completely vanishes though.

**Comment by ericsciple** [comment]
OK sounds like a bug in task groups then. I'm not sure why it would treat the inline script argument differently.

**Comment by kzu** [comment]
You do not think the arbitrary inconsistency in uex between inline and file path scripts is a bug regardless?? 👎

**Comment by kzu** [comment]
Funny! If I do configure the task `Arguments` first and *then* switch to `Inline` (thus the field `Arguments` dissappear) the task group UI does see the args, but they are never passed down to the inline script. Quite confusing ;)

**Comment by chrisrpatterson** [comment]
The reason they are different is because you can simply put the variables in the inline script which should be a lot simpler than dealing with arguments.  In the case of the file you have no option to do that.

**Comment by kzu** [comment]
I'd say the current experience is still more confusing than having it available in both, even if the variables can be used in the inline script directly, since that feature isn't easily discoverable (that is, it isn't even working PS script if you try to run it on your machine), whereas using arguments makes for way easier testing too before uploading.

**Comment by iyerusad** [comment]
@chrisrpatterson 
> The reason they are different is because you can simply put the variables in the inline script which should be a lot simpler than dealing with arguments

Alas, unless I am mistaken, this breaks ability to use data retrieved from `Azure Key Vault` task. Actually using `inline script` **appears to break all capability to retrieve ANY secret variables**. 
1. Use `Azure Key Vault` task to pull down a vault. 
![image](https://user-images.githubusercontent.com/25647368/30184005-a8f2bddc-93d9-11e7-9dc8-f183cf8cc43d.png)
2. Attempt to reference secrets pulled in previous task, using a `powershell`/`batch`/`shell` task using inline option - unable to extract the Key vault data pulled down.
![image](https://user-images.githubusercontent.com/25647368/30184121-1c8f4a08-93da-11e7-88ec-122493deea73.png)

No results:
```
2017-09-07T20:38:42.0319456Z ##[section]Starting: PowerShell Script
2017-09-07T20:38:42.0329255Z ==============================================================================
2017-09-07T20:38:42.0329255Z Task         : PowerShell
2017-09-07T20:38:42.0329255Z Description  : This is an early preview. Run a PowerShell script on Windows, macOS, or Linux.
2017-09-07T20:38:42.0329255Z Version      : 2.121.0
2017-09-07T20:38:42.0329255Z Author       : Microsoft Corporation
2017-09-07T20:38:42.0329255Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613736)
2017-09-07T20:38:42.0329255Z ==============================================================================
2017-09-07T20:38:43.0071563Z Generating script.
2017-09-07T20:38:43.0681597Z ##[command]"C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -File "d:\a\_temp\2ea4c913-5aec-405e-b326-008e447c8ee2.ps1"
2017-09-07T20:38:45.2496213Z ##[section]Finishing: PowerShell Script
```

**Comment by ericsciple** [comment]
@iyerusad you can use the macro syntax `$(mySecret)` syntax to pass secrets (same way if using a separate arguments text box).

alternatively, in yaml you can also pass via the [env dictionary](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-powershell.md#environment-variables). env dictionary will come to web designer in the future.
