### ISSUE TITLE
System.Management.Automation.RuntimeException: AuthorizationManager check failed

### ISSUE THREAD

**Issue by sameer-kumar** [Microsoft/vsts-tasks#4972]
I'm trying to create a Release Definition in TFS 2017 Update1 on-prem environment. I added a task for "Run PowerShell on Target Machines" and specified all the parameters. The PowerShell script is located on DFS shared path accessible from the remote machine. Execution policy of this remote machine is set to "Remote Signed" and the script is signed with a code-signing certificate from GoDaddy. When I try to run the deployment, I this below-mentioned error:

`2017-08-04T15:35:02.8994001Z ---> (Inner Exception #0) System.Management.Automation.PSSecurityException: AuthorizationManager check failed. ---> System.Management.Automation.Host.HostException: A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message: Run only scripts that you trust. While scripts from the internet can be useful, this script can potentially harm your computer. If you trust this script, use the Unblock-File cmdlet to allow the script to run without this warning message. Do you want to run \\shared\Scripts\ExtractFiles-v1.0.ps1?`

The strange and weird part is if I remote into the target machine using the same credentials I used in RM task, I can run and execute the same script (from the same network location) without any errors or prompts.

Is this me or everyone else? What am I doing wrong here?
Thanks!

**Comment by KrishnaAdityaB** [comment]
@sameer-kumar 
If you have any _Write-Host_ statements in your script, replace them with _Write-Verbose -Verbose_.
More details can be found at https://github.com/Microsoft/vsts-tasks/issues/612

**Comment by KrishnaAdityaB** [comment]
@sameer-kumar Please reopen the issue, if above solution doesn't work or the root cause is different

**Comment by tejaswivangaveeti** [comment]
got error while run the build pipeline:
system.management.automation.runtimeexception: scan cannot be completed failed to login
in azure devops security static code analysis task
