### ISSUE TITLE
NuGet push ignores negated pattern?

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/vsts-tasks#4973]
My build produces 2 packages:

    MyProject.1.0.0.nupkg
    MyProject.1.0.0-beta.nupkg

My Pre-release environment pushes one:

    **MyProject.*-beta.nupkg

And Release environment pushes another:

    **\MyProject.*.nupkg;-:**\*-beta.nupkg

But if I don't select "Allow duplicates to be skipped" I'm getting an error:

>The feed already contains 'MyProject 1.0.0-beta'.

I'm following [the doc](https://www.visualstudio.com/en-us/docs/build/steps/package/nuget#pack-nuget-packages) that states:

>You can negate a pattern by prefixing it with "-:". For example, specify **\*.csproj;-:**\*Tests.csproj to package all .csproj files except those ending in 'Tests' in all subdirectories in the repo.

Here's [a link](https://microsoft.visualstudio.com/DefaultCollection/Universal%20Store/Universal%20Store%20Team/_apps/hub/ms.vss-releaseManagement-web.hub-explorer?definitionId=3472&releaseId=209264&_a=release-logs) to the run which has this error (internal).

**Comment by abatishchev** [comment]
@keithrob can you please take a look?

**Comment by emanuelquintero** [comment]
@abatishchev Apologies, that doc needs to be fixed. 

Assuming you're using the NuGet task v2 then the negative pattern prefix has changed:
You can make a pattern negative by prefixing it with '!'. Example: **\*.csproj;!**\*.Tests.csproj

**Comment by abatishchev** [comment]
Thanks! It seems it works properly now. yes, please update the doc once you can.

**Comment by alexmullans** [comment]
The docs are updated: https://www.visualstudio.com/en-us/docs/build/steps/package/nuget

**Comment by ijabit** [comment]
You should also update the (i) informational icon in the VSTS task under the "Path to NuGet package(s) to publish". It currently says:

> The pattern to match or path to nupkg files to be uploaded. Multiple patterns can be separated by a semicolon, and you can make a pattern negative by prefixing it with '-:'. Example: **/*.nupkg;-:**/*.Tests.nupkg

**Comment by alexmullans** [comment]
@ijabit indeed, thanks. I've filed a bug on our internal backlog to do so.
