### ISSUE TITLE
Some tests could not run because test agent didn't update the testresults

### ISSUE THREAD

**Issue by cpoDesign** [Microsoft/vsts-tasks#4978]
Why my tests fails in middle of test run:
My tests just stopped working and there is no information why,

 Total Tests : 1021, Passed Tests : 719
2017-08-07T12:14:29.0055197Z ##[warning]DistributedTests: Test run is aborted. Logging details of the run logs.

[tasklog_29.zip](https://github.com/Microsoft/vsts-tasks/files/1204862/tasklog_29.zip)

Information about the host:

Windows 2016 datacentre hosted in azure
Standard DS4 v2 (8 cores, 28 GB memory)

**Comment by tanvi-soni** [comment]
Can you send c:\dtalogs\dtaexecutionhost.exe.log and event viewer logs from test agent machine to devops_tools@microsoft.com

**Comment by prawalagarwal** [comment]
Hi @cpoDesign,

Were you able to resolve the issue? If not, can you please send the logs to devops_tools@microsoft.com

Thanks.

**Comment by prawalagarwal** [comment]
Closing the issue. Please re open if you are still facing this.
