### ISSUE TITLE
Cannot load VstsAzureHelpers_ into a custom task

### ISSUE THREAD

**Issue by loshurik** [Microsoft/vsts-tasks#4981]
I create a custom task for TFS 1015 update 3 (agent version is 1.95.3)
VstsAzureHelpers_ is needed as a dependency.
I've downloaded it from latest master and copied to my task.
Here is what I get at the TFS agent side:
"The specified module 'E:\agent2\tasks\CustomAzurePowerShell\2.0.2\ps_modules\VstsAzureHelpers_' was not loaded because no valid module file was found in any module directory."
Please advise how to fix this.

**Comment by asranja** [comment]
@loshurik  We suggest you to build the task to get all the required dependencies. Clone the repo. Add your custom task to the Tasks folder. 

You can consider the AzurePowerShell task as an example. All the ps_modules dependency are specified in the make.json. 

Once you build the task (using node make.js build --task "ExactTaskName"), you will get the built task with all the dependency in the _build folder, which can be uploaded to the TFS server.
