### ISSUE TITLE
VS Test Agent Deployment - Failing with the error "Cannot find a process with the name 'DTAExecutionHost'"

### ISSUE THREAD

**Issue by mizbrodin** [Microsoft/vsts-tasks#4982]
I'm trying to run functional tests on a test machine from a VSTS build definition. I have an issue with the  VS Test Agent Deployment task (version 2.* using VS 2017). This task fails with the following error: 

> Error occured on '_<my_test_machine_hostname>_:5985'. Details : 'The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find a process with the name "DTAExecutionHost". Verify the process name and call the cmdlet again.'. For troubleshooting, refer https://aka.ms/remotevstest.

Here is the sanitized version of the full console output of the execution of this build task

[BuildConsoleOutput_sanitized.txt](https://github.com/Microsoft/vsts-tasks/files/1214599/BuildConsoleOutput_sanitized.txt)

I already tried:

1) Rebooting the test machine
2) Uninstalling VS Test Agent and having it installed again as part of the execution of the Deployment task.
3) Executing Enable-PSRemoting command.
4) Including test user account in the Administrators group of the test machine.
5) Running the build while having test user logged in to the machine (via RDP).

Is there anything else I can try to solve this issue?

Many thanks
Max

**Comment by xenalite** [comment]
We are experiencing the same issue using the same task and agent versions.
The only difference is that the deployment task fails for us and tests are not ran.

Step log:
[tasklog_6.txt](https://github.com/Microsoft/vsts-tasks/files/1214513/tasklog_6.txt)

**Comment by tanvi-soni** [comment]
Can you share testagentconfig.log file at devops_tools@microsoft.com. You will find the file in %temp% folder in test agent machine. Please share the build logs as well with system.debug set to true under in build definition.

**Comment by iangavr** [comment]
Same issue. Agent version is 15.3.26730.8

**Comment by nigurr** [comment]
Can you please try using Admin account for running the tests instead of different account? This should unblock. We have tracking bug for the same.

**Comment by nigurr** [comment]
This issue is getting addressed here: https://github.com/Microsoft/vsts-tasks/pull/5089
It will be available with next task release. Closing this issue.

**Comment by iangavr** [comment]
Already running under admin

Sent from my Sony Xperia™ smartphone

---- Nitin Gurram wrote ----


This issue is getting addressed here: #5089<https://github.com/Microsoft/vsts-tasks/pull/5089>
It will be available with next task release. Closing this issue.
