### ISSUE TITLE
Azure App Service Deploy: ERROR_FILE_IN_USE (even with Take App Offline + Rename locked files)

### ISSUE THREAD

**Issue by AaronRM** [Microsoft/vsts-tasks#4983]
Lately we've been seeing frequent failures in our VSTS releases of our ASP .NET Core app with output like the following (edited for privacy/clarity): 

```
[command]"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:package='package.zip' -dest:contentPath='mysite',ComputerName='https://mysite.scm.azurewebsites.net:443/msdeploy.axd?site=mysite',UserName='********',Password='********',AuthType='Basic' -enableRule:AppOffline -enableRule:DoNotDeleteRule -userAgent:myagent
---
##[error]Failed to deploy web package to App Service.
##[warning]Try to deploy app service again with Rename locked files option selected.
##[error]Error Code: ERROR_FILE_IN_USE
More Information: Web Deploy cannot modify the file '***.exe' on the destination because it is locked by an external process.  In order to allow the publish operation to succeed, you may need to either restart your application to release the lock, or use the AppOffline rule handler for .Net applications on your next publish attempt.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_FILE_IN_USE.
Error count: 1.
##[error]Error: C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe failed with return code: 4294967295
```

We are on task version 3.3.12. We have both "Take App Offline" and "Rename locked files" checked.  It appears that -enableRule:AppOffline is being passed to MSDeploy.exe. We're not sure if this is a bug in the VSTS task, in MSDeploy, or in Azure App Service.

It appears that similar feedback was reported [here](https://developercommunity.visualstudio.com/content/problem/18621/the-take-app-offline-option-in-deploy-step-doesnt.html), but was dismissed as "Not a Bug" with the suggested workaround being to use a separate task to take the app offline/online.

If the task can't (for whatever reason) guarantee to take the app offline, then the "Take App Offline" option should be removed from the task entirely.

**Comment by vincentdass** [comment]
@AaronRM , Currently there is an [active thread](https://github.com/Microsoft/vsts-tasks/issues/1607) for the same issue.
Can you please add `-retryInterval:6000  -retryAttempts:10` in **Additional arguments** under **Publish Using web deploy** option and re-queue the release?

**Comment by asranja** [comment]
@AaronRM I will take it that you are following the issue on the [active thread](https://github.com/Microsoft/vsts-tasks/issues/1607). Closing this issue as of now.
