### ISSUE TITLE
DistributedTests: Task 'ConfigureTestAgent' for machine l4-rin7utlefc.abcs.sqm:5985's Error : System.Exception: Unable to find TestAgent installation path

### ISSUE THREAD

**Issue by Maheshkhandave** [Microsoft/vsts-tasks#4988]
I am getting exception 'Unable to find TestAgent installation path' in test agent deployment step. we are using TFS 2017 Update-1 on premises version.
Task Version= 1.*

**Comment by prawalagarwal** [comment]
Hi @Maheshkhandave ,

Any updates here? Were you able to resolve the issue?

Thanks

**Comment by Maheshkhandave** [comment]
Hi Prawal,
This issue is still unresolved. I think it  is a known issue in TFS 2017 Update-1 which will be resolved in update-2.

Thanks,
Mahesh Khandave,
Test Automation Lead,
Global In-house Center(GIC), Pune
Wolters Kluwer Tax & Accounting
91.206.731.2747 tel
91.986.059.1870 mobile

**Comment by nigurr** [comment]
@Maheshkhandave It's known issue for v2 only. version 1 should continue to work with test agent 2015
