### ISSUE TITLE
Azure Key Vault - No error information is provided

### ISSUE THREAD

**Issue by tomkerkhove** [Microsoft/vsts-tasks#4989]
Currenly no error information is provided when something goes wrong.
This is mainly for all scenarios with exception of using the `*` filter, then it often gives an error message. 

## Reproducing the issue
Add  `Api-*` as a filter

## Expected Outcome
Step fails with clear message that I should use `*` or specific secret names such as `My-Secret`

## Current Outcome in VSTS
Step fails without any error message

**Comment by lovakumar** [comment]
Ack - we are looking into this.

**Comment by bansalaseem** [comment]
I have filed a bug to improve the error message here so that it gets tracked in one system.

**Comment by tomkerkhove** [comment]
Since it's closed, is it fixed then or?

**Comment by harshil93** [comment]
We never supported Api-* where * is a filter. We will now throw proper error and let user know that this isn't supported.
