### ISSUE TITLE
TargetAzurePs is not an input type available in Azure File Upload task after update. Broke our publish build jobs without notification.

### ISSUE THREAD

**Issue by kenotron** [Microsoft/vsts-tasks#4991]
A change to 1.0.94 -> 1.0.95 broke the builds for those who follow the Readme to install the Dec 2015 Azure Powershell SDK.

This is such a large checkin, I would have expected this to be updated to 2.x so that we can choose to update to 2.x when those build agents are updated.

**Comment by asranja** [comment]
@kenotron sorry for the issue that you experienced. Are you referencing the Azure File Copy task ?

**Comment by kenotron** [comment]
Yes. It now requires a version beyond what was recommended in the readme. I think this change is okay, but the issue is that the change is done as a patch level change. Therefore, folks do not have a chance to change out the Azure Powershell install before. There also is no mechanism of notification to users of this task.

**Comment by asranja** [comment]
Can you point out the exact error or failure that you experienced ?

**Comment by arjgupta** [comment]
the issue was fixed with later versions of the task. We ignore if there is an error in importing any azurerm submodule
