### ISSUE TITLE
Visual Studio Test Agent Deployment - Version 2.* credentials do not match version 1.*

### ISSUE THREAD

**Issue by xenalite** [Microsoft/vsts-tasks#4993]
I use version 1.* of "Visual Studio Test Agent Deployment" task, configured as such:
![image](https://user-images.githubusercontent.com/4509839/29086923-15ff23fa-7c6c-11e7-9c8a-bcc4b1903046.png)

I have a single test afterwards (Run functional tests), which asserts that currently executing user (Environment.UserName) is equal to value of $(TestUsername). This test passes in version 1.*.

Switching to version 2.* of "Visual Studio Test Agent Deployment" task, configured as such:
![image](https://user-images.githubusercontent.com/4509839/29087090-9d47ec5c-7c6c-11e7-9a92-0f41a97720a1.png)

The same test now fails, because currently executing user (Environment.UserName) is equal to value of $(AdminUsername).

**Comment by tanvi-soni** [comment]
@xenalite Thank you for the bringing the issue to our notice. 
We have reproduced the issue at our end and are currently investigating it.

**Comment by nigurr** [comment]
This issue is addressed here: https://github.com/Microsoft/vsts-tasks/pull/5089
It will be fixed with next deployment of VSTS. Closing this issue.

**Comment by bergmeister** [comment]
@nigurr @tanvi-soni  I encountered the same problem as reported by @xenalite  using VSTS and can therefore only assume that the referenced PR has not fixed the underlying problem.
