### ISSUE TITLE
AndroidSigning task should use secure files to avoid putting the keystore in the repo

### ISSUE THREAD

**Issue by gdavocap** [Microsoft/vsts-tasks#4995]
Use the new [secure files feature](https://www.visualstudio.com/en-us/docs/build/concepts/library/secure-files) to retrieve the keystore from the secure files in the VSTS library

**Comment by madhurig** [comment]
@gdavocap: Good suggestion! We have it on our backlog but it hasn't been scheduled yet.

Thanks,
Madhuri

**Comment by madhurig** [comment]
@gdavocap : This feature is available in the current VSTS deployment and should be available on all accounts by end of this week (approx.).

Thanks,
Madhuri
