### ISSUE TITLE
Getting 0 Identified Automated Tests while running Automated Tests in VSTS Test Manager using Builds

### ISSUE THREAD

**Issue by raman91dogra** [Microsoft/vsts-tasks#4996]
I am trying to integrate VSTS-UFT together such that Test Scripts can be run from VSTS Test Hub. Steps I follow:-
1. Create the Build Definition, Add Tasks like "Build Jenkins Job" , "Publish Test Results" in a Build.
2. Queue the Build and it is succeeded. Now I made a Test Suite under Test Plans Folder. After I create a Test Case, I right click Test Plan Settings and select Build Definition and Build Number.
3. Add a New Release Definition and Deployment is getting failed. When I check the Summary tab under Release, it is throwing me Error :- 
**connect ETIMEDOUT 10.77.13.57:8080 | connect ETIMEDOUT 10.77.13.57:8080**

4. When I try to run the Test Script using Test Type Options as Automate Tests using Release Environment, Selecting the Build, Release Definition and Environment, and click OK, Its not identifying the Automated Tests and giving me below Error Screenshot.
![image](https://user-images.githubusercontent.com/19578147/29119269-65a8e3d2-7cfd-11e7-872f-eae387cb25a6.png)

**Comment by cltshivash** [comment]
@raman91dogra Could you please provide more details on the task that you are using and if possible the build logs (with system.debug='true') ?

**Comment by raman91dogra** [comment]
@cltshivash Hi, I am trying to run HP UFT Script using VSTS Build. 
I have used UFT_TFS Plugin Task, First I run the Build . It actually invokes my Script and it runs end to end but still Overall Build gets failed.
Now I want to run a Test Case under Tests Folder using same Build i ran from Test Suite>> right Click Test Plan Settings. 
Now I run Test using Run with Options Command and it gives me Above Error in Screenshot. Hope you got what I am trying to achieve here.
Attaching the Build Logs here..
[logs_18.zip](https://github.com/Microsoft/vsts-tasks/files/1228394/logs_18.zip)

**Comment by raman91dogra** [comment]
@SadagopanRajaram Any updates. Do you need any help from me. Please reply

**Comment by SadagopanRajaram** [comment]
I assume you are refering to the feature documented at https://www.visualstudio.com/en-us/docs/test/continuous-testing/run-automated-tests-from-test-hub 
Can you please confirm that the test cases is associated with automation using the directions below? 
https://www.visualstudio.com/en-us/docs/test/continuous-testing/associate-automated-test-with-test-case for Visual Studio 2017 
https://msdn.microsoft.com/en-us/library/dd380741%28v=vs.120%29.aspx for Visual Studio 2015

**Comment by raman91dogra** [comment]
@SadagopanRajaram The Links you provided only works for Stuff to be run through Visual Studio. I have my Test Repository in HP UFT and not using Visual Studio. Does this Test worked only for Visual Studio related Code.

**Comment by raman91dogra** [comment]
@SadagopanRajaram I am running the Build having Tasks and  getting Error
1. Publish Test Results 
2. UFT File System Execution
3. Copy Files
4. Publish Build Artifacts
Build Errors:-
[logs_35.zip](https://github.com/Microsoft/vsts-tasks/files/1277083/logs_35.zip)

**1. The HTTP request   timed out after 00:01:40.
2. System.IO.FileLoadException:   Could not load file or assembly   'file:///C:\Users\P10401685\Desktop\ADM-TFS-Extension-master\ADM-TFS-Extension-master\installation\UFTWorking\bin\PSModule.dll'   or one of its dependencies. Operation is not supported. (Exception from   HRESULT: 0x80131515)
3. System.Management.Automation.CommandNotFoundException:   The term 'Invoke-FSTask' is not recognized as the name of a cmdlet, function,   script file, or operable program. Check the spelling of the name, or if a   path was included, verify that the path is correct and try again.
System.Management.Automation.ItemNotFoundException:   Cannot find path   'C:\Users\P10401685\Desktop\ADM-TFS-Extension-master\ADM-TFS-Extension-master\installation\UFTWorking\res'   because it does not exist.
4. PowerShell script   completed with 3 errors.**

Note:- Attaching the Build Logs. HPUFT Addin is already installed in VSTS.

**Comment by raman91dogra** [comment]
@SadagopanRajaram , @cltshivash Can you guys take a look on my above comments please.

**Comment by cltshivash** [comment]
@raman91dogra This works for tests that work through through the VS test platform. You can write a custom adapter to make the UFT tests runs as part of it. https://github.com/Microsoft/vstest

**Comment by raman91dogra** [comment]
@cltshivash Thanks for reply. Can you please guide how to write the Custom Adapter for same. I have not worked upon the stuff from quite a long time.But Now, I need to complete this on priority and there are no sources available anywhere.

**Comment by kasimvali31** [comment]
@raman91dogra 

1. The HTTP request timed out after 00:01:40.
2. System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\P10401685\Desktop\ADM-TFS-Extension-master\ADM-TFS-Extension-master\installation\UFTWorking\bin\PSModule.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
3. System.Management.Automation.CommandNotFoundException: The term 'Invoke-FSTask' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
System.Management.Automation.ItemNotFoundException: Cannot find path 'C:\Users\P10401685\Desktop\ADM-TFS-Extension-master\ADM-TFS-Extension-master\installation\UFTWorking\res' because it does not exist.
4. PowerShell script completed with 3 errors.



Solution:
=========
1.for first error,Unblock the files in following folder using powershell script
C:\Users\P10401685\Desktop\ADM-TFS-Extension-master\ADM-TFS-Extension-master\installation\UFTWorking\
2.create res and props folders in uftwotking folder

**Comment by ShivaLuckily** [comment]
System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\P10401685\Desktop\ADM-TFS-Extension-master\ADM-TFS-Extension-master\installation\UFTWorking\bin\PSModule.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)



How to resolve this issue?please help me
