### ISSUE TITLE
NPM task uses working dir as absolute path

### ISSUE THREAD

**Issue by danielstocker** [Microsoft/vsts-tasks#4997]
The VSTS agent will pull the target repo or artefacts it is working with into the standard **$(System.DefaultWorkingDirectory)** folder. (for example: D:\a\1\b\repo)

When specifying a working folder in the npm task by using the file picker (...) in the UI and selecting a repo path, we end up with an input that looks a little bit like this "/folder/otherFolder/".

If a working folder is specified the npm task will treat this path as an absolute path. 

In the above example the task would go to "C:\folder\otherFolder" before executing the specified npm command. 

This can seem inconsistent to the user as they are expecting the npm task to do something with their target repo. Other tasks (for example VS build) treat the working folder path as a path relative to $(System.DefaultWorkingDirectory). 

**Ask:** Consider changing workingDir in the npm task to $(System.DefaultWorkingDirectory) + workingDir with additional considerations for absolute paths if they are in fact entered.

**Comment by aldoms** [comment]
Are you selecting the working folder using the file picker in the Build Task UI? If so, you should end up with a relative path:
"folder/otherFolder/" instead of "/folder/otherFolder".

If provided with the first option, the task should use it relative to the source directory. Let us know if that's not the case to investigate further.

**Comment by bryanmacfarlane** [comment]
> When specifying a working folder ... by using the file picker (...) in the UI and selecting a repo path, we end up with an input that looks a little bit like this "/folder/otherFolder/".

That's not correct and I can't repro.  Is it a little like or exactly like?  Using the browse should produce a relative path (folder/otherFolder) to the root of the repo.  Preceding it with / tells it that it's absolute and goes to the root of the drive.

It's essentially what would happen if you cd from the root of the repo.

Re-open with repro steps if you see differently.
