### ISSUE TITLE
How to to produce both release and pre-release packages from one nuspec?

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/vsts-tasks#5001]
Currently my build produces both packages having a newer version every time:

    Release: Automatic package versioning = Use the build number
    Pre-release: Additional build properties = Version=$(user.BuildFullVersion)-beta

And the only one nuspec has a placeholder to version:

    <version>$version$</version>

I want to increment version manually, that it - repetitive build would produce same version until I increment it manually.

How can I achieve that still having single nuspec?

Can I adjust package version in the pack tasks like this:

    Release: $(PackageVersion) = $(PackageVersion)
    Pre-release: $(PackageVersion) = $(PackageVersion)-beta

**Comment by abatishchev** [comment]
As per Marina at https://stackoverflow.com/questions/45601861/how-to-to-produce-both-release-and-pre-release-packages-from-one-nuspec-in-vsts/45607639 currently you don't support wildcard for custom nuget command. Can you please plan this? Currently for release I can have 1 task for all 10 projects but for pre-release I have to clone 1 task 10 times.

**Comment by abatishchev** [comment]
hi @bryanmacfarlane, what do you think about wildcard support? thanks.

**Comment by keithrob** [comment]
@abatishchev,
Are you using hosted VSTS?  If so you should be able to add two v2.* nuget pack build steps to your build definition.  In each nuget pack build step, expand the section titled "Pack Options" and notice "Automatic Package Versioning"[1].  Here you can specify an environment variable and add the suffix (or not).  In the "Variables" section of your build you should create 2 variables PackageVersion and a composite called PackageVersionBeta.  In this manner, you can update a single variable and have it propagate.

Also, you may want to investigate [Packaging Release Views](https://www.visualstudio.com/en-us/docs/package/feeds/views).  With release views you can have a single version of your package and _promote_ it through quality rings.   In this manner, you can progressively expose the package to a broader and broader set of consumers.

Finally, regarding "wildcard for custom nuget command" this is something that we will add in a future release.

Keith

[1] 
![image](https://user-images.githubusercontent.com/908203/29580605-6cbdcdf8-872b-11e7-92a5-1618e0e3ab51.png)

**Comment by abatishchev** [comment]
hi @keithrob, not sure frankly what the term hosted VSTS stands for. Do you mean VSTS/VSO vs, on-prem TFS? We're using the microsoft.visualstudio.com instance.

Package version is kept into the nuspec file to avoid creating new version (two of them if include beta) on each build. Because this is a repo for shared components it includes several projects, each producing its own package based on its own nuspec.
In this scenario how can I produce beta/pre-release packages for all projects/nuspecs with a single task? I'm able to do that for release package:

     Path to csproj or nuspec file(s) to pack: **\*.nuspec
     Automatic package versioning: Off

Unfortunately Packaging Release Views won't work for us for now until support programmatic promotion.

**Comment by keithrob** [comment]
@abatishchev, 
I'm going to close this since you have a work-a-round.  As we discussed, offline, I believe that release views will be the best long term solution and I appreciate that we do not have the automation in place to make their usage easy at this point.  We are taking steps to make promotion to release views easier and more automated so that, in the future, you can simply use views and not worry about appending version suffixes.
Keith
