### ISSUE TITLE
Release: Not found gulpFile issue 

### ISSUE THREAD

**Issue by sprider** [Microsoft/vsts-tasks#5003]
Following the [SharePoint Framework solution deployments](https://www.eliostruyf.com/configure-a-build-and-release-pipeline-for-your-sharepoint-framework-solution-deployments/) to automate my deployement. 

I am getting the "Not found gulpFile: d:\a\r1\a\gulpfile.js" error on release 

![snip20170809_14](https://user-images.githubusercontent.com/21008316/29138246-b57c7f80-7d08-11e7-9ee6-9399fcb013e8.png)
![snip20170809_13](https://user-images.githubusercontent.com/21008316/29138258-bc2b52c0-7d08-11e7-968d-556e01177dbc.png)

Any idea?

**Comment by bryanmacfarlane** [comment]
Sounds like a release artifact and deployment scenario.  Looks like files aren't getting pulling into release artifact.

**Comment by GitHubSriramB** [comment]
@sprider

The gulpfile.js path in the screen shot above ($(System.DefaultWorkingDirectory)/build/release/s/gulpfile.js) is not the same as the one that you have mentioned in the error message (d:\r1\a\gulpfile.js). Are you sure the screen-shot corresponds to the task in the failing release?

Is gulpfile.js supposed to be part of an artifact associated with release?

**Comment by sprider** [comment]
Hi Sriram,

I fixed the issue by allowing warning in the gulp package task. 

It was failing with --ship argument. All good now. 

Thank you.
