### ISSUE TITLE
Nuget pack command cannot find build output for multiple targets

### ISSUE THREAD

**Issue by alexwiese** [Microsoft/vsts-tasks#5006]
Using the default .NET Core (.NET Framework) template on VSTS.
The build is output to the following locations (for both framework targets specified in the csproj):

    \bin\release\net461\output.dll
    \bin\release\netstandard1.6\output.dll

The Nuget task (version 2.0.5) looks for the output in the wrong location:

    NuGet.CommandLine.CommandLineException: Unable to find 'bin\release\output\bin\release\'. Make sure the project has been built.

**Comment by alexdrl** [comment]
This is related to https://github.com/NuGet/Home/issues/5832 and not related to the build task. We made a workaround using `GeneratePackageOnBuild` for .NET Standard libraries.

**Comment by keithrob** [comment]
Closing this out based on previous comment.

**Comment by verndemille** [comment]
This fails on a .NET framework pack that references a .NET Standard core library.

**Comment by Sreini** [comment]
@chris-strauss we are having the exact same issue still. Any progress on this? Did you find a workaround?

**Comment by Dejulia489** [comment]
I assume this is still an issue. Has anyone found a work around?

**Comment by chris-strauss** [comment]
> @chris-strauss we are having the exact same issue still. Any progress on this? Did you find a workaround?

@Sreini I had removed the Pack task from the pipeline and had the project pack on build.
![Capture](https://user-images.githubusercontent.com/47256320/59764383-ac36ba80-9269-11e9-8e05-251e6613d862.JPG)
