### ISSUE TITLE
Publish-UpgradedServiceFabricApplication Action=Upgrade bug

### ISSUE THREAD

**Issue by Adebeer** [Microsoft/vsts-tasks#5014]
When doing Action=Upgrade in this powershell script, and there is an update error, the script shouldn't try to do an unregister inside catch block. This fails in my scenario as the package is in use by another app.

Specifically, in my scenario, I use same package with multiple environments (package contains profiles for multiple environments - e.g. testing, staging, production). As such, only the initial environment deployment needs to register the package - subsequent ones only do an upgrade using existing package in image store.

Sometimes the Upgrade fails - but because catch statement tries to do an Unregister for the app type,
 (which fails with package in use error), it hides the original error.

So essentially there's 2 bugs to fix:
a) Don't execute Unregister-ServiceFabricApplicationType in upgrade catch block when Action=Upgrade (ie. it should only do it if Action=RegisterAndUpgrade as no registration was performed)
b) Don't hide the original exception that occurred within the try block. By doing (a) above, if this action fails, one's left into the dark as to why the upgrade failed - i.e. do something like Write-Error $_.Exception|format-list prior to invoking Unregister-ServiceFabricApplicationType 
Note: I'm not a Powershell guru...so maybe you want to log the error differently... 

Finally, another enhancement I made in my project to the default VS Studio Deploy-FabricApplication.ps1 script is to add a BypassAppRegistration switch parameter. In doing so, this deploy script can be enhanced to support Upgrade and Create actions for the Publish-Upgraded/NewServiceFabricApplication functions. 

See below:
[Deploy-FabricApplicationExt.ps1.txt](https://github.com/Microsoft/vsts-tasks/files/1216797/Deploy-FabricApplicationExt.ps1.txt)

**Comment by bishal-pdMSFT** [comment]
@Adebeer "Service fabric deploy" task always sets action as "RegisterAndUpgrade" and hence it is fine to always unregister the application-type if upgrade fails.
Are you running this task parallely in different release environments? Interesting that you are not getting error when second environment will try to register the app-type while first env has already registered it.

**Comment by Adebeer** [comment]
@bishal-pdMSFT 
Thanks for your reply. I think you are misunderstanding my scenario a bit, so I'll try to explain bit more.

I've got a VSTS build definition defined that creates a versioned package for my Service Fabric Application - let's call this V1. This V1 package also contains the application parameter files Testing.xml, Staging.xml and Production.xml for my 3 environments. Note: These Application name is uniquely defined for each environment - e.g. fabric:/myapp-Testing etc...

I've also got a VSTS release definition defined with the 3 environments. So, after a successful VSTS build, it deploys the V1 package to Testing. Up to this point everything is as per normal and you can use RegisterAndUpgrade or RegisterAndCreate to deploy the V1 Testing application using Testing.xml (part of the package) - and the register process will register V1 package in image store.

Some stage later we want to deploy this same V1 package but this time using Staging.xml or Production.xml parameter file. This is where the problem lies because if you try to use RegisterAnd* it'll fail because in this mode it'll try and re-register the V1 package (as it is currently in use by fabric:/myapp-Tesing...and you can't also register V1 twice in image store...as per your comment - this is what I'm avoiding by using Action=Upgrade/Create). This is why I've had to alter the the default Deploy-FabricApplication.ps1 file so I can use it in my build process to deploy this same V1 package as fabric:/myapp-Staging/Production WITHOUT it trying to unregister the V1 package.

So, the end result is the same V1 package in the image store - but deployed 3 times as 3 different application instances using each of the different 

Hope my scenario now makes more sense to you - thanks Bishal.

**Comment by bishal-pdMSFT** [comment]
Thanks @Adebeer, I understand your flow now. However, I don't understand how "Deploy-FabricApplication.ps1" is coming into picture. Are you using this script directly instead of "Service fabric deploy" task? That script is released by VS IDE team and we don't contribute to it.

We do use `Publish-NewServiceFabricApplication.ps1` and `Publish-UpgradedServiceFabricApplication.ps1` released by them and we can think about modifying the usage so that task supports upgrade/create without register.

**Comment by Adebeer** [comment]
@bishal-pdMSFT 
You can ignore my changes to Deploy-FabricApplication.ps1 - I'm using this (modified) script directly in my VSTS build processes.

I'd appreciate it though if you could apply the fixes to the Publish-* scripts as they are part of SDK and I can't simply modify these and run them directly (I tried...but had some runtime errors due to its dependency on other scripts etc...again, i'm not a PS guru!). 

Thanks!!

**Comment by bishal-pdMSFT** [comment]
@Adebeer we do not own Publish-* scripts and hence can't modify them. Adding @MikkelHegn for that.

However, I would suggest you to use "Service fabric deploy" task instead of these scripts directly. You can list any issues (like the current one) and we would be happy to improve the task.

**Comment by MikkelHegn** [comment]
For the subsequent deployments to other "environments" (which in Service Fabric lingo is creating new Named Application Instances of the same Application Type and Version), simply run the New-ServiceFabricApplication cmdlet. https://docs.microsoft.com/en-us/powershell/module/servicefabric/new-servicefabricapplication?view=azureservicefabricps

**Comment by Adebeer** [comment]
@MikkelHegn Thanks Millel. 
I don't have any issues calling either New/Update-ServiceFabricApplication cmdlet. My problem is there is a bug with the Update-ServiceFabricApplication cmdlet as per above which I would like fixed

**Comment by MikkelHegn** [comment]
Yes - I opened a bug here to get this fixed in the SDK: https://github.com/Azure/service-fabric-issues/issues/408

For the VSTS task, someone will have to update the script here, as the task do not rely on the SDK: https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/ServiceFabricDeploy

**Comment by bishal-pdMSFT** [comment]
Thanks @MikkelHegn , we will take updated scripts from SDK once the referenced issue is fixed.

@Adebeer If we change the VSTS task("ServiceFabricDeploy") behavior to support both RegisterAndUpdate and Update, would you start consuming the task instead of raw scripts? Or is there some other issues as well blocking you from using task?

**Comment by Adebeer** [comment]
@bishal-pdMSFT: That's exactly what I want - i'd love to be able to use the task directly; thank you so much! :)

**Comment by bishal-pdMSFT** [comment]
Great. We will plan the fix.
