### ISSUE TITLE
Docker Build an image task error 

### ISSUE THREAD

**Issue by takazm** [Microsoft/vsts-tasks#5020]
i have configured a build task to build a docker image in a .net core app using on-prem build agent. All other tasks succeed except the image build part.  Docker is installed and running on build agent. I get the following error:

**open //./pipe/docker_engine: Access is denied. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.**

**Comment by jikuma** [comment]
Have you installed docker toolbox for windows or docker for windows on the build agent ? Can you try running docker build command directly on build agent and let me know the result.

**Comment by bansalaseem** [comment]
Closing because of no response
