### ISSUE TITLE
Azure App Service Deploy Task - Could not find the End of Central Directory Record

### ISSUE THREAD

**Issue by larserikfinholt** [Microsoft/vsts-tasks#5021]
The task has been running for several weeks, but suddenly stopped with the following error:

2017-08-14T09:32:31.2397851Z ##[section]Starting: Azure App Service Deploy: xxxx
2017-08-14T09:32:31.2410405Z ==============================================================================
2017-08-14T09:32:31.2410405Z Task         : Azure App Service Deploy
2017-08-14T09:32:31.2410405Z Description  : Update Azure Web App Services, Web App On Linux , Function Apps, Mobile Apps using Web Deploy / Kudu REST APIs
2017-08-14T09:32:31.2410405Z Version      : 3.3.13
2017-08-14T09:32:31.2410405Z Author       : Microsoft Corporation
2017-08-14T09:32:31.2410405Z Help         : [More Information](https://aka.ms/azurermwebdeployreadme)
2017-08-14T09:32:31.2410405Z ==============================================================================
2017-08-14T09:32:34.3473460Z Got connection details for Azure App Service:'xxxx'
2017-08-14T09:32:36.3641276Z ##[error]Error: Could not find the End of Central Directory Record

**Comment by vincentdass** [comment]
@larserikfinholt ,  can you please set `system.debug` variable to true, re-run the release and share the logs?

**Comment by vincentdass** [comment]
@larserikfinholt , can you please share the logs for investigation?

**Comment by vincentdass** [comment]
Closing this thread as there is no response from customer.
Please re-open the thread, if required and provide Debug logs too.

**Comment by strand** [comment]
> 2017-12-27T21:49:47.5916921Z Got connection details for Azure App Service:'sia-reconvener-ppe'
> 2017-12-27T21:49:47.5917759Z ##[debug]Performing the deployment of webapp.
> 2017-12-27T21:49:47.5919180Z ##[debug]Finding files matching input: d:\a\r1\a\SIA_Reconvener_CI\dist
> 2017-12-27T21:49:47.5921520Z ##[debug]set reconvenerUrl=http://sia-reconvener-ppe.azurewebsites.net
> 2017-12-27T21:49:47.5939404Z ##[debug]Processed: ##vso[task.setvariable variable=reconvenerUrl;secret=false;]http://sia-reconvener-ppe.azurewebsites.net
> 2017-12-27T21:49:47.9778782Z ##[debug]Azure web app is available.
> 2017-12-27T21:49:50.9798699Z ##[debug]Initiated deployment via kudu service for webapp package : d:\a\r1\a\SIA_Reconvener_CI\dist
> 2017-12-27T21:49:50.9801189Z ##[debug]Requesting for Auth Token: https://login.windows.net/********/oauth2/token/
> 2017-12-27T21:49:51.1269028Z ##[debug]Requesting Azure App Service web config Details: https://management.azure.com/subscriptions/a83b1dd0-478c-4fe4-af6e-e71d94058e4a/resourceGroups/sia-reconvener-dev/providers/Microsoft.Web/sites/sia-reconvener-ppe/config/web?api-version=2016-08-01
> 2017-12-27T21:49:52.2177180Z ##[error]Failed to deploy web package to App Service.
> 2017-12-27T21:49:52.2177464Z ##[debug]Processed: ##vso[task.issue type=error;]Failed to deploy web package to App Service.
> 2017-12-27T21:49:52.2178102Z ##[debug]task result: Failed
> 2017-12-27T21:49:52.2189576Z ##[error]Error: Error: Could not find the End of Central Directory Record
> 2017-12-27T21:49:52.2190009Z ##[debug]Processed: ##vso[task.issue type=error;]Error: Error: Could not find the End of Central Directory Record
> 2017-12-27T21:49:52.2213204Z ##[debug]Processed: ##vso[task.complete result=Failed;]Error: Error: Could not find the End of Central Directory Record
> 2017-12-27T21:49:52.2213714Z ##[debug]Application Insights is not configured for the App Service sia-reconvener-ppe. Skipping adding release annotation.
> 2017-12-27T21:49:52.2214094Z ##[debug]Web App Publish Kudu URL: sia-reconvener-ppe.scm.azurewebsites.net:443
> 2017-12-27T21:49:52.2214406Z ##[debug]build.sourceVersionAuthor=undefined
> 2017-12-27T21:49:52.2214712Z ##[debug]build.requestedfor=Strand McCutchen
> 2017-12-27T21:49:52.2215019Z ##[debug]build.buildUri=vstfs:///Build/Build/8853
> 2017-12-27T21:49:52.2215347Z ##[debug]release.releaseUri=vstfs:///ReleaseManagement/Release/2137
> 2017-12-27T21:49:52.2215923Z ##[debug]build.buildId=8853
> 2017-12-27T21:49:52.2216226Z ##[debug]release.releaseId=2137
> 2017-12-27T21:49:52.2216507Z ##[debug]build.buildNumber=8853
> 2017-12-27T21:49:52.2217044Z ##[debug]release.releaseName=Release-10
> 2017-12-27T21:49:52.2217387Z ##[debug]system.TeamFoundationCollectionUri=https://azsrels.visualstudio.com/
> 2017-12-27T21:49:52.2217732Z ##[debug]system.teamProjectId=1ab87a75-b7f1-450e-a912-2bb3bafd591d
> 2017-12-27T21:49:52.2218087Z ##[debug]build.sourceVersion=dafc699e50fe62e141a9d28edc2579e6dc900200
> 2017-12-27T21:49:52.2218425Z ##[debug]build.repository.name=SIA_Reconvener
> 2017-12-27T21:49:52.2218746Z ##[debug]build.repository.provider=TfsGit
> 2017-12-27T21:49:52.2219055Z ##[debug]build.buildUri=vstfs:///Build/Build/8853
> 2017-12-27T21:49:52.2219399Z ##[debug]release.releaseUri=vstfs:///ReleaseManagement/Release/2137
> 2017-12-27T21:49:52.2219853Z ##[debug]build.buildId=8853
> 2017-12-27T21:49:52.2220290Z ##[debug]release.releaseId=2137
> 2017-12-27T21:49:53.5667906Z Successfully updated deployment History at https://sia-reconvener-ppe.scm.azurewebsites.net/api/deployments/21371514411392213
> 2017-12-27T21:49:53.5803809Z ##[section]Finishing: Azure App Service Deploy: sia-reconvener-ppe
> 2017-12-27T21:49:53.5862532Z ##[section]Finishing: Release

**Comment by strand** [comment]
After a bit of pain I discovered that my app was lacking a web.config file. I believe this may be the underlying cause of the original poster's issue. I will investigate adding error handling which indicates that this file is not getting loaded in the environment, and the user may be able to resolve the issue by following the instructions here: https://github.com/projectkudu/kudu/wiki/Using-a-custom-web.config-for-Node-apps

**Comment by vincentdass** [comment]
@strand , the issue is with compressing the folder to a zip file prior deployment and not with web.config file. Are you using private agent or Hosted agent - (windows / Linux) ?

**Comment by strand** [comment]
I was working with Linux initially, and tried switching to Windows, then successfully deployed to Windows. I was not using zip to get a successful build, instead once a build is successful, my release process retrieves a git repo. If you would like I could spend some time writing out complete reproduction steps later this week.

**Comment by vincentdass** [comment]
@strand , thanks for the info. On Windows platform, we use MSDeploy for deployment which takes both Folder and Zip as input. On Non-Windows Platform (Linux/  MAC), we use ZIP API , which takes ZIP as input. 
So, for Linux, we compress the given folder and upload the same. As mentioned earlier, there is an issue with the compression technique (for large package size). We are currently investigating on this issue. I hope that you are currently unblocked by using the Windows agent.

**Comment by strand** [comment]
I am unblocked, but I'm not following _how_ this was caused by zip, when I used git to transmit my repo. I made [this PR based on my troubleshooting,](https://github.com/Microsoft/vsts-tasks/pull/6112) and in looking at the original poster's stacktrace I recognize that my error message was the same (`Could not find the End of Central Directory Record`) but that the cause of the failure was differen, This error occurs any time there is a connection hiccup in the build/release process, and I think this error is not a good message to the end user, as it is unclear that this is a connection issue either caused by a lack of authed creds or a lack of a required resource.

**Comment by vincentdass** [comment]
@strand , thanks for the detailed info.
Can you please share the new debug logs to `RM_CUSTOMER_QUERIES@MICROSOFT.COM`  so that we can take this thread in private and debug the issue?
We are currently fixing some reliability issues and will be adding more debug / console statements to provide better insights to the user.

**Comment by vincentdass** [comment]
@strand , Can you share the debug logs to `RM_CUSTOMER_QUERIES@MICROSOFT.COM`?

**Comment by strand** [comment]
@vincentdass Apologies for dropping this. I am going on vacation next week, but hope to find time to send you deets tomorrow. Thank you for reminding me of this.

**Comment by strand** [comment]
![Kermit waving hands and saying Yay](https://media1.tenor.com/images/afc199aba63308be9826b60cfc574653/tenor.gif?itemid=8712171)
