### ISSUE TITLE
Deploy Azure App Service 3.*- XML transformation onto WWWROOT/Web.config Fails

### ISSUE THREAD

**Issue by hammer5280** [Microsoft/vsts-tasks#5026]
During a release XML transformation works for:

BIN\Web.Production.config transformed ONTO BIN\Web.config

How can I get:

PackageTmp\bin\Web.Production.config to transform ONTO \PackageTmp\Web.config aka (WWWROOT/Web.config)

Thanks!

**Comment by vincentdass** [comment]
@hammer5280 , currently XML transformation is applied when the config and transform files are in the **same folder**. We do have a story for `Advanced transformation` in our backlog, which will be taken based on the priority.

**Comment by hammer5280** [comment]
@vincentdass, Thanks for the clarification.  Do you know of a "work-around" so during the build process the Web.Production.config is copied to the root folder in the .zip artifact during the MsBuild step?

**Comment by vincentdass** [comment]
@hammer5280 , checkout this [stackoverflow post](https://stackoverflow.com/q/5915610) on copying files to different folder during MSBuild.

**Comment by vincentdass** [comment]
Closing the thread, as there is no action item.
