### ISSUE TITLE
Failures in publish test results: Test result completed date must be greater than test result start date

### ISSUE THREAD

**Issue by duoxu** [Microsoft/vsts-tasks#5028]
Hi guys,

We are using VSTS to build our project and using Publish Test Results task to publish the Junit test results.

I have attached the TEST-*.xml files.

Question:

1. How did you determine the start date and complete date?

For example, one test xml file contains

`<testsuite errors="0" failures="0" hostname="duoxu-ubuntu" name="org.apache.zookeeper.server.DeserializationPerfTest" skipped="0" tests="8" time="0.17" timestamp="2017-08-14T23:10:41">`

The timestamp unit is second and time is within 1 sec, so I assume this test completed date is not greater than start date? Is it a bug (should be >= rather than >)?

**Comment by SadagopanRajaram** [comment]
https://github.com/Microsoft/vsts-agent/pull/1035 on the Microsoft/Vsts-Agent repo has fixed the issue reported here. Please let us know if this does not resolve your issue.
