### ISSUE TITLE
VSTS build task fails on a .NetFramework4.6.1 project references .NetStandard2.0

### ISSUE THREAD

**Issue by cilerler** [Microsoft/vsts-tasks#5047]
- a **.Net Framework 4.6.1** project that references **.NetStandard2.0** _(not preview)_ project
- **Visual Studio 2017 Update 3** _(not preview, VisualStudio.15.Release/15.3.0+26730.3)_ 

so far everything is working fine in LOCAL environment.
When I run a build on **Visual Studio Team Services** it throws the error/s below

## Error message 

```
##[error]src\Ninja.Dojo\Fight.cs(18,19): Error CS0012: The type 'IServiceProvider' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

Please advise 🤗

**Comment by chrisrpatterson** [comment]
We don't have the images updated across all pools with VS2017.3 and .NET Core 2.0 yet.  You can try to add a NuGet Tool Installer to the front of your build and have it install NuGet 4.* to get the latest and then have a .NET Core Tool Installer and select the SDK options and put 2.0.0 in for the version.

**Comment by cilerler** [comment]
thank you, unfortunately I already tried that but didn't solve it.

**Comment by cilerler** [comment]
Closing this one and will follow up at dotnet/standard#454

**Comment by cilerler** [comment]
I have to re-open this one, since it is either going to be solved by dotnet/standard team _(via new tooling)_ or through VSTS team _(rolling VS2017.3 to all agents or providing a method etc.)_

@chrisrpatterson is there any time frame to complete rolling VS2017.3? or magic syntax to pull an agent that has it?

a show stopper at this point. 😢

**Comment by bryanmacfarlane** [comment]
It doesn't have to be a show stopper.  You can deploy a private agent on your own vm.

15.3 on the convenient hosted pool is in progress

**Comment by cilerler** [comment]
Thanks @bryanmacfarlane.

Easier workaround came from **dotnet/standard** team, wanted to share it here incase someone else hits the same bump.

https://www.nuget.org/packages/NETStandard.Library.NETFramework/2.0.0-preview2-25405-01 solves the issue.

> _It was the previous way we were planning to handle this issue but instead decided to do it directly in tooling._

**Comment by bryanmacfarlane** [comment]
Cool.  15.3 is rolling now.  Early next week everywhere

**Comment by cilerler** [comment]
just to inform if anyone hits here, it has been rolled and VSTS is working just fine... 😎
