### ISSUE TITLE
IIS Web App Manage(Preview): SSL Certificate thumbprint contains non-hexadecimal characters in binding

### ISSUE THREAD

**Issue by bdbvb** [Microsoft/vsts-tasks#5048]
For the IIS Web App Manage(Preview) task, I've configured a valid, hex thumbprint, with no spaces or punctuation, just a-f, A-F, and 0-9.

But I get this warning:

"SSL Certificate thumbprint contains non-hexadecimal characters in binding : ( https/All Unassigned:443 ) . Trimming all non-hexadecimal characters."

Binding configuration looks like this:

![image](https://user-images.githubusercontent.com/11095196/29420723-ce400292-8340-11e7-82cf-d8fb19e2963a.png)

**Comment by asranja** [comment]
@bdbvb Can you enter the thumbprint directly (instead of the varibale $(SSLThumbprint) in the SSL certificate thumbprint input to see if there is any non-hexadecimal character in the input. In case of error, the UI shows :

![bindingsssl](https://user-images.githubusercontent.com/20986928/29448398-19ca3b6e-8414-11e7-8ad3-c033c48d193e.PNG)

**Comment by bdbvb** [comment]
Weird. I did a select/copy of the value from the release definition, and pasted into the Add Bindings dialog, and though it looks perfect, I do get the error you mention:

![image](https://user-images.githubusercontent.com/11095196/29460040-4c102360-83f4-11e7-892b-dc6ffd93af4d.png)

I originally copy/pasted the value from the thumbprint of the built-in Windows certificate viewer and deleted the spaces. 

I guess the next thing I should try is typing the value in by hand.

Since I'm thinking this might be a common use-case (copying the value from the certificate viewer and pasting it), I wonder if the "SSL certificate thumbprint" field could be enhanced to automatically trim out any non-hex characters, spaces, etc.

I'll try by hand and see how it goes....

**Comment by bdbvb** [comment]
Using a Unicode converter, I see my thumbprint is actually something like:

&#x200E;61e22fb554ac0db05c2b32a4cfee821b05963135

200E is the Left to Right Mark (https://en.wikipedia.org/wiki/Left-to-right_mark)

I'm guessing (maybe) when copying that value from the Windows certificate viewer, it includes this hidden character.

So I suppose it's technically not a bug :-) 

However, would be nice for it to automatically trim that sort of thing out, since I'm guessing it might be a common use case. 

Thanks!

**Comment by bdbvb** [comment]
(Update: I did try selecting and copying the thumbprint value from the certificate viewer and pasting it into a unicode converter, and it indeed is the culprit.)

![image](https://user-images.githubusercontent.com/11095196/29461015-27eaaaf6-83f8-11e7-86fc-3d24c52c1170.png)

![image](https://user-images.githubusercontent.com/11095196/29461040-3d88a82c-83f8-11e7-865b-6b9638b6fc45.png)

**Comment by asranja** [comment]
@bdbvb Yes, you are right. The thumbprint from the certificate manager does append an invisible Unicode at the beginning of the thumbprint. Currently we are not trimming it out in the UI. We let the task trim out any non-hexadecimal character and spaces.
