### ISSUE TITLE
NuGet restore task fails from the Xamarin.Android template in TFS 2017 update 2 

### ISSUE THREAD

**Issue by SandipAhluwalia** [Microsoft/vsts-tasks#5049]
Hi,

After looking all the NuGet restore issues here, none of them seems to resolve and/or are related to my issues. 

I getting the following after updating the version of NuGet to 4.0.0 in the NuGet restore task:

**_Detected NuGet version 4.0.0.2283 / 4.0.0
SYSTEMVSSCONNECTION exists true
C:\agent\_work\_tasks\NuGetInstaller_333b11bd-d341-40d9-afcf-b32d5ce6f23b\0.2.31\node_modules\nuget-task-common\NuGet\4.0.0\NuGet.exe restore -NonInteractive C:\agent\_work\1\s\DummyPrismUnityXFApp\DummyPrismUnityXFApp.sln
MSBuild auto-detection: using msbuild version '15.1.1012.6693' from 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\15.0\bin'.
Restoring NuGet package Prism.Core.6.3.0.
Restoring NuGet package CommonServiceLocator.1.3.0.
Restoring NuGet package Prism.Forms.6.3.0.
Restoring NuGet package Prism.Unity.Forms.6.3.0.
Restoring NuGet package Unity.4.0.1.
Restoring NuGet package Xamarin.Android.Support.Animated.Vector.Drawable.23.3.0.
Restoring NuGet package Xamarin.Forms.2.3.3.193.
Restoring NuGet package Xamarin.Android.Support.Design.23.3.0.
Restoring NuGet package Xamarin.Android.Support.v7.AppCompat.23.3.0.
Restoring NuGet package Xamarin.Android.Support.v4.23.3.0.
Restoring NuGet package Xamarin.Android.Support.v7.CardView.23.3.0.
Restoring NuGet package Xamarin.Android.Support.v7.MediaRouter.23.3.0.
Restoring NuGet package Xamarin.Android.Support.v7.RecyclerView.23.3.0.
Restoring NuGet package Xamarin.Android.Support.Vector.Drawable.23.3.0.
WARNING: Unable to find version '6.3.0' of package 'Prism.Core'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Prism.Core.6.3.0' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  Unable to connect to the remote server
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 93.184.221.200:443_**

The above is repeated for all the packages listed. Below are my settings in the build definitions:

![image](https://user-images.githubusercontent.com/4387978/29422509-5eee4f22-8370-11e7-8887-760296584cf5.png)

Out of the box, the Xamarin.Android template sets the NuGet version to 3.3.0 and uses version 0.* of the NuGet restore task. However this was giving errors like "3.3.0\NuGet.exe failed with return code: 1":

**_Detected NuGet version 3.3.0.212 / 3.3.0
SYSTEMVSSCONNECTION exists true
C:\agent\_work\_tasks\NuGetInstaller_333b11bd-d341-40d9-afcf-b32d5ce6f23b\0.2.31\node_modules\nuget-task-common\NuGet\3.3.0\NuGet.exe restore -NonInteractive C:\agent\_work\1\s\DummyPrismUnityXFApp\DummyPrismUnityXFApp.sln
MSBuild auto-detection: using msbuild version '4.0' from 'C:\Windows\Microsoft.NET\Framework\v4.0.30319'.
C:\agent\_work\1\s\DummyPrismUnityXFApp\DummyPrismUnityXFApp\DummyPrismUnityXFApp.UWP\DummyPrismUnityXFApp.UWP.csproj(138,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
Error: C:\agent\_work\_tasks\NuGetInstaller_333b11bd-d341-40d9-afcf-b32d5ce6f23b\0.2.31\node_modules\nuget-task-common\NuGet\3.3.0\NuGet.exe failed with return code: 1
Packages failed to install_**

I also tried using NuGet version 3.5 as suggested by various other related issues reported and got:

**_Detected NuGet version 3.5.0.1938 / 3.5.0
SYSTEMVSSCONNECTION exists true
C:\agent\_work\_tasks\NuGetInstaller_333b11bd-d341-40d9-afcf-b32d5ce6f23b\0.2.31\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe restore -NonInteractive C:\agent\_work\1\s\DummyPrismUnityXFApp\DummyPrismUnityXFApp.sln
Failed to load msbuild Toolset
  Could not load file or assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Error: C:\agent\_work\_tasks\NuGetInstaller_333b11bd-d341-40d9-afcf-b32d5ce6f23b\0.2.31\node_modules\nuget-task-common\NuGet\3.5.0\NuGet.exe failed with return code: 1
Packages failed to install_**

Note, I also tried updating the Nuget restore task to version 1.* as shown in the settings below, but this then gave me another error during the NuGet restore task step: connect ETIMEDOUT 93.184.221.200:443:

![image](https://user-images.githubusercontent.com/4387978/29423282-0ddd33de-8373-11e7-96b6-b912f3bda081.png)

The error then reported:

**_C:\WINDOWS\system32\chcp.com 65001
Active code page: 65001
connect ETIMEDOUT 93.184.221.200:443_**

So can someone give me any help to get this part of build step working as I am currently going around in circles!?

**Comment by SandipAhluwalia** [comment]
Hi again,

Further to my post above, I tried getting it to work with NuGet v3.5 as some people on various forums have indicated this version seems to work. So after looking at the error messages again for when I initially tried NuGet v3.5 (see above post), I noticed it was trying to find msbuild v14.0, so as my build agent only has Visual Studio 2017, I had to separately install the MS Build Tools 2015 (https://www.microsoft.com/en-us/download/details.aspx?id=48159), but this then gave me a further error, which was related to missing the Microsoft.Windows.UI.Xaml.CSharp.targets file, so I found this link (https://stackoverflow.com/questions/45041972/microsoft-windows-ui-xaml-csharp-targets-missing-on-ci-server) that helped me resolve that particular issue. So then I finally ended up with the same error I had when using NuGet v4.0 as I first indicated in my above post, e.g.

**_WARNING: Unable to find version '6.3.0' of package 'Prism.Unity.Forms'.
  https://api.nuget.org/v3/index.json: Unable to load the service index for source https://api.nuget.org/v3/index.json.
  An error occurred while sending the request.
  Unable to connect to the remote server
  A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 93.184.221.200:443_**

Further info/context on my set up and what I am trying to achieve... I am trying to set up a Xamarin Forms CI build pipeline and we want to use TFS 2017 to do this as we want it on premise. So to test this objective, I installed TFS 2017 update 2 Express edition on my Windows 10 machine at work, which is behind a company firewall. I then set up a Windows build agent on the same machine (for test purposes) and I am now trying to set up a Xamarin Android build definition using the template.

So if anyone out there can give me any pointers on the issues I am seeing then that would be much appreciated.

**Comment by SandipAhluwalia** [comment]
UPDATE: Resolved

It looks like I am talking to myself in this post :) So after further studying the error messages in my post and doing more research, I realized that the connection to the NuGet server errors was related to my company proxy that my machine was using. In the end, on top of the changes I mentioned above, I had to configure my TFS server 2017 to use my domain user account instead of the system account. I also re-configured my agent to use my domain user account as well. Now I am not sure if the first change to the TFS server 2017 was needed, but I did both at the same time and the NuGet restore task works with NuGet v3.5 with the extra changes mentioned above, and worked with NuGet v4.0 too.

It still doesn't work with version 1.* of the NuGet restore task because it is still giving those timeout errors mentioned above.

In general, it seems this Xamarin.Android template doesn't work out of the box with a Windows agent that has Visual Studio 2017 installed. The main amends needed are to update the Nuget version to 4.0 in the NuGet restore task and manually add the Xamarin.Android capability to the Windows agent.

**Comment by keithrob** [comment]
@SandipAhluwalia ,
Apologies for the delay.  Here are a couple of thoughts:

- I'm not sure how your corporate proxy is configured, but I would suggest using a service account as opposed to your domain user account when running the agent.  Running the agent as you is a security risk.

- The new 2.* versions of the nuget task will respect the proxy settings of the agent.  IOW, if you configure the agent to use a corporate proxy, the nuget task will supply those [settings ](https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#environment-variables) to nuget.exe and when your restore command is executed nuget.exe will go through your proxy.

- Need more information about "It still doesn't work with version 1.*.." as I'm not groking the issue here. However, if you have a corporate proxy in place, please stick with the 2.* versions of the task.

**Comment by SandipAhluwalia** [comment]
@keithrob , Thanks for the tips. In my TFS 2017 update 2 Express edition, it doesn't seem to have 2.* version of the NuGet restore task. I am hoping it will have it in the full professional edition or is it only available via VSTS?

**Comment by keithrob** [comment]
@SandipAhluwalia,
Version 1.* of the Nuget task also respects the [proxy settings](https://www.visualstudio.com/en-us/docs/build/actions/agents/v2-windows#how-do-i-configure-the-agent-to-work-through-a-web-proxy-and-connect-to-team-services) of the agent.  In fact, if you [enable debug](https://www.visualstudio.com/en-us/docs/build/define/variables#control-variables) you should see a line that looks like[1].
Keith


[1] Adding environment variable for NuGet proxy: yourProxyHere
