### ISSUE TITLE
How to call a function when using "Powershell on Target Machines"?

### ISSUE THREAD

**Issue by mayeager22** [Microsoft/vsts-tasks#5059]
I have a Powershell script with functions that I can call directly from the command-line if I dot source that script first:

 . .\Install-BizTalkApplication.ps1 ; FullInstallProcess-BizTalkApplication {arguments}

Is there a way to dot source the script in the Powershell on Target Machines task?

**Comment by KrishnaAdityaB** [comment]
Try 
`.  $PSScriptRoot\Install-BizTalkApplication.ps1 ; FullInstallProcess-BizTalkApplication {arguments}`

_.\file.ps1_ - searches the file.ps1 in current working directory instead of the directory of script file. 
_$PSScriptRoot_ gives the script file's directory.

**Comment by KrishnaAdityaB** [comment]
Please reopen the issue if above solution doesn't work.
