### ISSUE TITLE
Xamarin Android build task

### ISSUE THREAD

**Issue by christophedemey** [Microsoft/vsts-tasks#5062]
Hi, 

I just had a very unpleasant experience with the xamarin android build task and took me over a day to figure everything out.
Maybe some stuff can be improved to prevent people from losing this much time over this.

My problem and the solutions are posted in this thread : 
https://developercommunity.visualstudio.com/content/problem/96957/xamarin-android-build-failing.html

**Comment by madhurig** [comment]
@christophedemey : Thank you for sharing your experience and solution. We don't have an automated way to pick up the right agent queue based on what you are building currently. It is something we are investing to make it easier to get started. We will take your feedback into account.

Thanks,
Madhuri

**Comment by christophedemey** [comment]
@madhurig thank you.

Things you could include that i believe could make life allot easier :
- The makelink script that is required because the sdk is in program files and java cant handle the space.
- Version patching in AndroidManifest.xml (i did this myself with a console app and shell script task).
- A decent android app will not build if JDK is not set to x64 (out of memory exception elsewise).

**Comment by madhurig** [comment]
@christophedemey: Thanks for the details!
- We are working with Xamarin team to fix the issue with their build tools not being able to handle the space in android SDK path. 
- This is a common request, we have a few tasks in the [marketplace](https://marketplace.visualstudio.com/search?term=versioning&target=VSTS&category=All%20categories&sortBy=Relevance)  that I know customers use. I have personally used the one in [this extension](https://marketplace.visualstudio.com/items?itemName=colinsalmcorner.colinsalmcorner-buildtasks)
- That is good feedback, we can update the defaults to be x64 easily.

Thanks,
Madhuri

**Comment by madhurig** [comment]
@christophedemey:
- Latest versions of Xamarin handle spaces in the Android SDK path
- We don't have a built in task for versioning but we have options on the marketplace.
- We have updated the default to be x64 in the task

So, I am closing the issue.

Thanks,
Madhuri
