### ISSUE TITLE
NuGet restore fails when encountering netcoreapp2.0 -> netstandard2.0 references

### ISSUE THREAD

**Issue by sandersaares** [Microsoft/vsts-tasks#5065]
It appears that the NuGet restore task in VSTS uses some old version of NuGet that is unable to deal with netcoreapp2.0 projects that reference netstandard2.0 projects.

This is running on a custom agent with VS 2017 update 3 and .NET Core SDK 2.0.0.

Directly invoking `nuget.exe restore` with NuGet 4.3.0 instead of using the NuGet task works fine. I would expect the NuGet task to also work fine here.

Task log attached: [4_NuGet restore.txt](https://github.com/Microsoft/vsts-tasks/files/1238075/4_NuGet.restore.txt)

**Comment by IvanAlekseev** [comment]
I am having the same issue. Using [this](
https://github.com/Microsoft/vsts-tasks/issues/3798#issuecomment-287105240) workaround allowed to build on hosted agent

**Comment by chrisrpatterson** [comment]
If you need a more recent version of NuGet you need to specify that in your definition. Due to a wide variety of compatibility issues in NuGet.exe we can't blindly update everyone to more recent versions

**Comment by IvanAlekseev** [comment]
Thank you @chrisrpatterson, I just found a vsts task to update a nuget. Is there an option to always use the most recent one?

**Comment by alexmullans** [comment]
If you're using the NuGet Tool Installer task, you can use wildcards (e.g. 4.* or *) to always use the latest version available from https://dist.nuget.org. Note that things sometimes break or change between (even minor) versions, so this can introduce some instability to your build.

**Comment by IvanAlekseev** [comment]
Thanks @alexmullans, 4.3.0 works for us now
