### ISSUE TITLE
Test Agent Deployment time is varying from one build definition to another.

### ISSUE THREAD

**Issue by Cva2904** [Microsoft/vsts-tasks#5068]
Dear Team,

We have implemented build definition as part of continuous integration, to check the application on different machine.

The problem we are facing is, test agent deployment is taking more time in one build definition and less time in another build definition.

Do let me know if you need further inputs on the same.

Thanks,Siva. A

**Comment by nigurr** [comment]
@Cva2904 Can you please provide more info on this?

1. Do test agent machines belongs to on-prem or azure?
2. What's the version of Deploy Test agent are you using?
3. Is it consistently producing the same delay?
4. Can you please share build/release logs if it's getting repro continuously.

**Comment by Cva2904** [comment]
@nigurr 

we are using Test Agent 2015 on IBM server.
there are no logs generated and we are facing this issue atleast once in a week.

Thanks.
Siva

**Comment by nigurr** [comment]
@Cva2904 can you please share the requested information?

**Comment by Cva2904** [comment]
@nigurr 

we are using IBM server with windows 8.1 enterprise edition operating system.
when ever the issue its producing the same delay and we are timed out message after the wait time.
the logs are getting updated with the latest build executions.

Kind Regards,
Siva.

**Comment by nigurr** [comment]
@Cva2904 Can you please share the details which are requested earlier?

   1.  Do test agent machines belongs to on-prem or azure?
   2.  What's the version of Deploy Test agent are you using?
   3.  Is it consistently producing the same delay?
   4.  Can you please share build/release logs if it's getting repro continuously.

**Comment by nigurr** [comment]
Please open the issue with the required details if it's reproducible continuously.
For optimizing test agent installation we recommend using offline installation as mentioned here: https://blogs.msdn.microsoft.com/devops/2017/05/05/using-visual-studio-agent-deployment-task-on-machines-not-connected-to-the-internet/

**Comment by Cva2904** [comment]
@nigurr 

the link related to download test agent in the above url is not working.

can you share me the latest url.

thanks in advance,
Siva.
