### ISSUE TITLE
Feature request: run PowerShell as admin/sudo

### ISSUE THREAD

**Issue by sandersaares** [Microsoft/vsts-tasks#5073]
I use the PowerShell task to deploy software as part of a release process. To facilitate the needed activities, I would like to run the script as Administrator (on Windows) or via sudo (on Linux). At the moment, there does not seem to be any direct mechanism to do this.

**Comment by bryanmacfarlane** [comment]
@sandersaares - can you run a private agent as admin?  Or are you referring to a hosted pool?

**Comment by sandersaares** [comment]
Yes, this is about a private agent. The user does have admin/sudo rights, it is just a question of actually doing the elevation when a task is run.

**Comment by mayeager22** [comment]
I am wondering this same thing.  There are spaces for "Admin Login" and "Password", but the remote powershell does not run with elevated permissions.

**Comment by ericsciple** [comment]
@sandersaares I don't think a non-interactive non-elevated process elevate itself. If you run as a Windows service and the account is a local administrator, it will run elevated.

**Comment by ericsciple** [comment]
Taking tasks out of the picture, how would you do this normally?

I would think the solution is remoting.

**Comment by sandersaares** [comment]
I do not remember anymore what my exact use case was in august 2017 but right now, I am not particularly feeling any lack of elevation capability in agent tasks. As such, I am unable to really comment on the substance of the matter and do not consider the issue I opened relevant anymore. Accordingly, I will close it.

**Comment by ThePickNick** [comment]
I have a use-case where I need to run a Powershell Task as administrator. rather a command that need elevated privileges, the Task "Powershell on Remote Machines" is not applicable in my case as i need to have Inline scripting area in the task it self not the path to the ps1 file. as they do not exist on machines.

**Comment by kmkumaran** [comment]
@ThePickNick - With regard to your comment on inline script support for "Powershell on Remote Machines" task, the support has been recently added in the 3.* version of the task.

**Comment by foolip** [comment]
This would have been handy in https://github.com/web-platform-tests/wpt/pull/14300. There are some things we have to do as an administrator (e.g. installing HTTPS certificates) but others that *can't* be done using an administrator, namely running `MicrosoftEdgeDriver`. This mix is tricky to get right, and something that effectively is like `sudo` would make it easier.

**Comment by foolip** [comment]
@thejohnjansen @mustjab, would you mind asking around if there's an open issue somewhere for what we need?

**Comment by fabiostawinski** [comment]
I have a setup here, with the agent running with a user which is the server admin also. It when tries to run Powershell on target machines, it fails when it needs admin elevation, when I tried to excute in the server manually, it popups the UAC window before it gets elevated. Is there any way to elevate without being locked by UAC? and also without disabling UAC?

**Comment by smholvoet** [comment]
@fabiostawinski Running into this exact issue.

Did you ever get around solving this?

**Comment by fabiostawinski** [comment]
> @fabiostawinski Running into this exact issue.
> 
> Did you ever get around solving this / finding a workaround 🙏?

Actually I disabled UAC 👎

**Comment by nturnerlivanova** [comment]
.`run: |
          #Requires -RunAsAdministrator
          Start-Process -Wait -FilePath ..`

This works for me

**Comment by ClaudioRowe** [comment]
> .`run: | #Requires -RunAsAdministrator Start-Process -Wait -FilePath ..`
> 
> This works for me

How do you use it? Does it come with a prompt? I need to pipeline the cron to reset of a service and it needs to be done as admin, prompt won't do

**Comment by nturnerlivanova** [comment]
> > .`run: | #Requires -RunAsAdministrator Start-Process -Wait -FilePath ..`
> > This works for me
> 
> How do you use it? Does it come with a prompt? I need to pipeline the cron to reset of a service and it needs to be done as admin, prompt won't do

Here was my scenario:

I needed to uninstall an application through the pipeline. But, windows pops up the dialog to modify or uninstall with buttons which breaks the silent process.

By attaching this command, there is not a popup and it will uninstall silently with no prompt. This was the only way I could find to avoid UI interactions.

**Comment by ClaudioRowe** [comment]
> > > .`run: | #Requires -RunAsAdministrator Start-Process -Wait -FilePath ..`
> > > This works for me
> > 
> > 
> > How do you use it? Does it come with a prompt? I need to pipeline the cron to reset of a service and it needs to be done as admin, prompt won't do
> 
> Here was my scenario:
> 
> I needed to uninstall an application through the pipeline. But, windows pops up the dialog to modify or uninstall with buttons which breaks the silent process.
> 
> By attaching this command, there is not a popup and it will uninstall silently with no prompt. This was the only way I could find to avoid UI interactions.

How did you input credentials?

**Comment by nturnerlivanova** [comment]
> > > > .`run: | #Requires -RunAsAdministrator Start-Process -Wait -FilePath ..`
> > > > This works for me
> > > 
> > > 
> > > How do you use it? Does it come with a prompt? I need to pipeline the cron to reset of a service and it needs to be done as admin, prompt won't do
> > 
> > 
> > Here was my scenario:
> > I needed to uninstall an application through the pipeline. But, windows pops up the dialog to modify or uninstall with buttons which breaks the silent process.
> > By attaching this command, there is not a popup and it will uninstall silently with no prompt. This was the only way I could find to avoid UI interactions.
> 
> How did you input credentials?

You can pass in credentials, which i'm not doing and it takes a few lines of code. I'm using the local administrator for the build service. I'm not a powershell expert.

`#Requires -RunAsAdministrator
          Start-Process -Wait -FilePath "pathtounistall.exe" -ArgumentList "/q" -PassThru`

I see that you can use choclatey also

**Comment by ClaudioRowe** [comment]
> > > > > .`run: | #Requires -RunAsAdministrator Start-Process -Wait -FilePath ..`
> > > > > This works for me
> > > > 
> > > > 
> > > > How do you use it? Does it come with a prompt? I need to pipeline the cron to reset of a service and it needs to be done as admin, prompt won't do
> > > 
> > > 
> > > Here was my scenario:
> > > I needed to uninstall an application through the pipeline. But, windows pops up the dialog to modify or uninstall with buttons which breaks the silent process.
> > > By attaching this command, there is not a popup and it will uninstall silently with no prompt. This was the only way I could find to avoid UI interactions.
> > 
> > 
> > How did you input credentials?
> 
> You can pass in credentials, which i'm not doing and it takes a few lines of code. I'm using the local administrator for the build service. I'm not a powershell expert.
> 
> `#Requires -RunAsAdministrator Start-Process -Wait -FilePath "pathtounistall.exe" -ArgumentList "/q" -PassThru`
> 
> I see that you can use choclatey also

So in run: you put the uninstall command, then you piped the #Requires so it runs only when the prerequisites are met? If you are connected as admin you need to input -RunAsAdministrator so ensure that it does?

**Comment by nturnerlivanova** [comment]
> > > > > > .`run: | #Requires -RunAsAdministrator Start-Process -Wait -FilePath ..`
> > > > > > This works for me
> > > > > 
> > > > > 
> > > > > How do you use it? Does it come with a prompt? I need to pipeline the cron to reset of a service and it needs to be done as admin, prompt won't do
> > > > 
> > > > 
> > > > Here was my scenario:
> > > > I needed to uninstall an application through the pipeline. But, windows pops up the dialog to modify or uninstall with buttons which breaks the silent process.
> > > > By attaching this command, there is not a popup and it will uninstall silently with no prompt. This was the only way I could find to avoid UI interactions.
> > > 
> > > 
> > > How did you input credentials?
> > 
> > 
> > You can pass in credentials, which i'm not doing and it takes a few lines of code. I'm using the local administrator for the build service. I'm not a powershell expert.
> > `#Requires -RunAsAdministrator Start-Process -Wait -FilePath "pathtounistall.exe" -ArgumentList "/q" -PassThru`
> > I see that you can use choclatey also
> 
> So in run: you put the uninstall command, then you piped the #Requires so it runs only when the prerequisites are met? If you are connected as admin you need to input -RunAsAdministrator so ensure that it does?

What I found as specifying the verb did not work for me. Only when I prefixed the #Requires which is the same as Run As from the context menu. The build service has admin rights to accomplish this, so you may need to set permissions as needed. Here is my entire text. Maybe this helps:

` run: |
          #Requires -RunAsAdministrator
          Start-Process -Wait -FilePath "fullpathtouninstall.exe" -ArgumentList "/q" -PassThru`

You may need to test it out and see what works for you.
