### ISSUE TITLE
Chain build/release

### ISSUE THREAD

**Issue by cilerler** [Microsoft/vsts-tasks#5074]
is there a native way of trigger a build on another project when a release get completed?

I found that there is a marketplace item exist for this but wondering if this is available by Microsoft?

https://marketplace.visualstudio.com/items?itemName=benjhuser.tfs-extensions-build-tasks

**Comment by GitHubSriramB** [comment]
@cilerler - We do not have any native support for triggering build on a release completion. 

The task that you pointed to in the extension is a good alternative. The other option would be to have your own PS script that can invoke the Build REST API to trigger build and include it within the appropriate environment in Release.

**Comment by cilerler** [comment]
@e078108 https://blogs.msdn.microsoft.com/visualstudioalmrangers/2018/04/26/vsts-gems-chain-related-builds/

**Comment by e078108** [comment]
@cilerler it doesn't help to trigger build from a release pipeline.

However this is how I solved it:
- Added an Agentless phase in release pipeline
- Used "Invoke REST API" task
- Used POST API to invoke the build (ref. to build definition ID)

**Comment by bansalaseem** [comment]
@GarethOates, you should able to deploy releases also via a custom task.
