### ISSUE TITLE
Nuget pack *.nuspec - System.IO.FileNotFoundException: File not found:.

### ISSUE THREAD

**Issue by Pitterling** [Microsoft/vsts-tasks#5086]
Hi,
I'm trying to convert from deprecated Nuget Packager task .. using nuget pack with my *.nuspec file ends in FileNotFoundException for the files to be packed. I tried to copy the files beforehand to different locations without luck.

Unfortunately the debug and verbose output do not list where the task is expecting the files.

Where do i need to put the files to be packed?

Thanks

**Comment by Pitterling** [comment]
Please tell me, what is the [BasePath ](https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#pack ) for the files specified in *.nuspec?

**Comment by Pitterling** [comment]
it seems that it is looking for the files in the location where the *.nuspec file is located. In my case this is a sub-subdirectory ... please provide the option again to specify the basepath parameter

**Comment by keithrob** [comment]
Fixed by #6645
