### ISSUE TITLE
VSMobileCenterUpload fails 

### ISSUE THREAD

**Issue by ridomin** [Microsoft/vsts-tasks#5092]
Tryed to upload UWP app from VSTS build to MobileCenter.

The task fails with error:
Cannot POST /v0.1/apps/https://mobile.azure.com/users/*****

Looks like the app slug is not in the correct format, although I could not find documentation (well, just an empty page here: https://www.visualstudio.com/en-us/docs/build/steps/deploy/mobile-center-upload ) so I followed the instructions in the tooltips.

Any ideas?

**Comment by madhurig** [comment]
The appslug should be username/appname (the help has some details)
<img width="300" alt="appslug" src="https://user-images.githubusercontent.com/3269636/29619323-d12edecc-87e8-11e7-9158-6c16ee017326.png">
The best way to find these values is from the mobile center url.

We are trying to improve the experience here, so you can just pick your app without having to figure this out.

Thanks,
Madhuri

**Comment by ridomin** [comment]
what is not clear from the help is the final format. 
Should be http://mobile.azure.com/users/rido/apps/myapp or just rido/myapp ?

**Comment by madhurig** [comment]
@ridomin: Ah I see, it should be rido/myapp and not the full URL.
