### ISSUE TITLE
"Object reference not set to an instance of an object" error happens all the time we run test cases.

### ISSUE THREAD

**Issue by Jinwenxin** [Microsoft/vsts-tasks#5093]
![image](https://user-images.githubusercontent.com/7763785/29600211-2d737dbe-8807-11e7-8439-19858907eed6.png)
All tests are running failed with such errors. But nothing changes on my side. Any ideas?
Configuration of my release: 
![image](https://user-images.githubusercontent.com/7763785/29600302-a21ae08a-8807-11e7-87d2-bff1da3067dc.png)

**Comment by nigurr** [comment]
@Jinwenxin Thanks for reporting this issue. This is hotfixed and thanks for support.
