### ISSUE TITLE
Visual Studio Test Agent Deployment fails to connect to test agent FQDN with error 67

### ISSUE THREAD

**Issue by dbtfsbre** [Microsoft/vsts-tasks#5095]
After updating to TFS 2017 SP2, V1 of "Visual Studio Test Agent Deployment" starts to produce a lot of errors in our environment and V2 fails the build.
During the task, CopyFilesToTestAgent is called which throws error 67 ("The network name cannot be found.")

The test agent machines are not in a domain, but they have their own primary DNS suffix.
They are reachable via ping from the build agent, opening \\\\TESTAGENT1.uitest.local in Explorer from the build agent is possible.
Attached is the debug log of the task under Version 1 which was working until our upgrade.
[Task log vstask testagentdeployment error 67.txt](https://github.com/Microsoft/vsts-tasks/files/1245371/Task.log.vstask.testagentdeployment.error.67.txt)

I first thought that this issue may be related to Robocopy which requires a domain and username when connecting to a remote machine which we don't have because the test agents are not domain joined and all have different machine names. But the error message looks different somehow.

**Comment by nigurr** [comment]
@dbtfsbre Can you please let us know the OS version of build agent and test agent machine?

**Comment by dbtfsbre** [comment]
The build agent is on Windows Server 2012 R2 (6.3.9600.0) and the test agent runs Windows 10 (10.0.14393.0).

**Comment by dbtfsbre** [comment]
@nigurr Is this combination not supported?

**Comment by nigurr** [comment]
@dbtfsbre it's supported. but we haven't seen this (tried repro internally). Are all these machines are connected to same domain group?

**Comment by dbtfsbre** [comment]
@nigurr Our test machines are not domain-joined. The build agent is domain-joined.

Currently on the test agents we have WinRM configured for HTTP only, not HTTPS. The build tasks are configured to use HTTP. This is to skip the certificate generation when deploying virtual machines.

**Comment by nigurr** [comment]
@dbtfsbre does domain joined account has write permission to the test agent machine? I am suspecting that would be the case. Does Windows file copy task works on the same machine?

**Comment by dbtfsbre** [comment]
@nigurr Windows file copy does not work on this same machine. The reason behind should be that it uses Robocopy and we provide something like ".\username" as Admin login name. Robocopy does not accept this, it needs a domain. Our test machines all have different machine names, so I can't provide a domain.

The credentials which I provide to "Visual Studio Test Agent Deployment" are the admin credentials on the test agent machine, in the same format: ".\username"

**Comment by dbtfsbre** [comment]
I read further and it seems that what I am trying to do (connect to Workgroup machines via HTTP) is not supported: https://www.visualstudio.com/en-us/docs/build/apps/cd/deploy-webdeploy-iis-winrm

So I am going to change to HTTPS. Only I need to use a script which configures WinRm and creates the certificate with the correct computer name after creating our virtual machines.
