### ISSUE TITLE
Cannot Run Service Fabric Tasks on Deployment Groups

### ISSUE THREAD

**Issue by SamuelMcAravey-NVP** [Microsoft/vsts-tasks#5097]
Hi everyone, so we ran into an issue this week where we need to run the Service Fabric related tasks in a Deployment Group (details below). I found these pull requests (#3412, #3527) that add the `runsOn` property that limits the tasks to only build agents, making it so that we can't use them on Deployment Groups. I can create a pull request if needed (created: #5098), but in the short term I created a modified version of the tasks that changes the `runsOn` property to allow Deployment Groups.

### In short: The `runsOn` property artificially constrained a perfectly valid use case. Can we get it updated to allow Deployment Groups?

**Scenario:**
We are running Service Fabric inside of a virtual network with an internal load balancer (no public IP), and we have a JumpBox/Bastion VM that is available publicly that has access to the fabric cluster. Because of that we have set up the JumpBox to perform the actual deployment to the cluster, and also joined the JumpBox to VSTS as part of a Deployment Group. So the only thing we needed to do differently from a publicly available fabric cluster was to run the VSTS release in the context of the JumpBox, but since the task wasn't available to Deployment Groups we couldn't run the deployment tasks. 

Now I understand the rational behind not making this available to deployment groups (talk to the cluster, not to individual VMs), but in this case we were artificially constrained by this. The only change we made was to change the `runsOn` property, and the task worked out of the box.

Thanks everyone!

**Comment by SamuelMcAravey-NVP** [comment]
#5098

**Comment by chrisrpatterson** [comment]
@SamuelMcAravey-NVP why not join the agent on the jump box to a normal pool in VSTS that would work as well.  The deployment group and the deployment model it follows does not really fit for ServiceFabric.

**Comment by SamuelMcAravey-NVP** [comment]
While yes, I can join the jump box as a build agent but it makes the following scenario untenable.

I have several environments set up (call it 6 of them), each with their own fabric cluster and jump box, and I want the same application to be released to all environments. By having the jump boxes as build agents only 1 out of the 6 will get the updated package. But by having them all as part of a deployment group all 6 environments would get the updated package.

Like I mentioned, I was able to get this working for our own VSTS account by modifying the existing task and re-uploading it to our account. I understand and agree that Deployment Groups in general don't  make sense for a fabric cluster, but in this case I was using the deployment groups to push changes to all machines rather than choosing one out of a pool.

**Comment by bishal-pdMSFT** [comment]
@SamuelMcAravey-NVP Are you going to merge your PR? Otherwise I will raise PR.

**Comment by SamuelMcAravey-NVP** [comment]
Yes, I'll get that merged here shortly and ready to go.

**Comment by SamuelMcAravey-NVP** [comment]
Well... I'm obviously a GitHub noob, but I think I have the pull request updated. I'm not sure why it's showing so many commits and file changes since I only changes 8 files. Thoughts?

**Comment by bishal-pdMSFT** [comment]
Your PR is quite old and your branches `SamuelMcAravey-NVP:master` and `Microsoft:master` have diverged a lot. You need to first pull latest changes from Microsoft:master and then rebase your commit. Or since your commit is smaller, you can just cherry-pick your commit.
