### ISSUE TITLE
Support for arbitrary Nuget versions in Nuget installer package

### ISSUE THREAD

**Issue by henning-krause** [Microsoft/vsts-tasks#5109]
The version 0.x of the task allows a user to select an arbitrary nuget.exe which it should use to restore the packages.

It would be nice to have this option in the current version as well. 

Reason:
I've just converted a package of ours to a netstandard2.0 assembly and published it to our TFS nuget feed. Then I added it as a <PackageReference> to a couple of projects which target .Net 4.6.2. In the next build, the nuget restore fails with this error message:

``` 
Package MyPackage 12.1.10 is not compatible with net462 (.NETFramework,Version=v4.6.2). Package MyPackage 12.1.10 supports: netstandard2.0 (.NETStandard,Version=v2.0)
2017-08-24T11:21:39.8123608Z     One or more packages are incompatible with .NETFramework,Version=v4.6.2.
```

The tasks currently uses Nuget 4.0 to restore the packages. And indeed, if I use that version to restore the package on my development computer, I get the same error. But Nuget 4.3 can cope with this situation quite well.

Now I was forced to downgrade to the 0.x version of the task which let me specify the nuget.exe. But I loose cool feature of the 1.x version: Specify the private Nuget feed.

**Comment by bryanmacfarlane** [comment]
There's a tool installer task for nuget that does that.  By having it as an upfront task it sets up the env for multiple task invocations or scripts

I agree that it should also be available as a convenience on the task( with the default being PATH)

**Comment by henning-krause** [comment]
Which task would that be? I didn't find it in my On-Premise installation and a quick glance on the market place also didn't yield any results.

**Comment by bryanmacfarlane** [comment]
What version is your on prem tfs?

**Comment by henning-krause** [comment]
2017.2

**Comment by dasMulli** [comment]
Is there a way to install the "official" nuget tool installer to the on-prem TFS? Really need to use NuGet 4.3 now for mixed `packages.config` / `PackageReference` solutions requiring `netstandard2.0` support for `net461` projects.

**Comment by henning-krause** [comment]
@dasMulli, can you use my workaround: Revert to version 0.x of the task? That got a "Works on my machine award" :-)

**Comment by dasMulli** [comment]
Which requires installing a nuget.exe on each machine in the same location or adding one to the project :( (ugly but yeah).
I was hoping for a ps1 script to install the missing task just like the script for vsbuild/msbuild tasks for 2017 RTM+Update1

**Comment by henning-krause** [comment]
I just added a download task for nuget as a first step in my pipeline....

**Comment by dasMulli** [comment]
Turns out I can also use the 1.* task when I add this to your script to set the variable that the new NuGet tasks use:
```powershell
Write-Host ("##vso[task.setvariable variable=NuGetExeToolPath]" + $path)
```

**Comment by henning-krause** [comment]
I updated our setup to TFS 2018 RC2, but the issue remains. Altough a new version of the Nuget task, the issue remains.

**Comment by bryanmacfarlane** [comment]
@henning-krause- did you use the nuget installer task with 2018?

**Comment by henning-krause** [comment]
@bryanmacfarlane, yes, I did. Updated the task to the latest version (2.0). At least, the workaround from @dasMulli still works in combination with my inline PoweShell task.

**Comment by bryanmacfarlane** [comment]
@henning-krause 

Not sure you're using the right task.  NugetToolInstaller is in the tools category.  It's not in version 2.0 (it's 0.x).  https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/NuGetToolInstaller/task.json#L15

As you can see here, it takes a version spec including wild cards:  https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/NuGetToolInstaller/task.json#L29

Are you not seeing that in 2018?

**Comment by henning-krause** [comment]
Ah.. didn't saw that one. Just added it to the pipeline and it works like charm :-)

**Comment by bryanmacfarlane** [comment]
Awesome.  Yeah, we started a whole new category of tasks.  One of the benefits is it prepends the path so you can even use nuget in scripts downstream during the build and it will use that one. 

https://github.com/Microsoft/vsts-tasks/blob/master/docs/tools.md

**Comment by dasMulli** [comment]
Glad to see it is going to be in 2018, but is it going to be in 2017 u3? Don't have the RC installed anywhere..

**Comment by dasMulli** [comment]
The interesting thing is it listed in the database but nowhere in the UI..

```sql
SELECT *
  FROM [Tfs_Configuration].[Task].[tbl_TaskDefinition]
  WHERE Name LIKE '%NuGet%'
```
