### ISSUE TITLE
V3 of AzureRmWebAppDeployment does not allow you to deploy to a slot for a API app.

### ISSUE THREAD

**Issue by leftler** [Microsoft/vsts-tasks#5115]
The deploy to slot option defined in https://github.com/Microsoft/vsts-tasks/blob/fe3532c4dee9c9e0a882d6d621055777366e9dae/Tasks/AzureRmWebAppDeployment/task.json#L81-L89

is only visible when `WebAppKind = app || WebAppKind = functionapp || WebAppKind = applinux`, if you have a `WebAppKind = api` the slots option will not be visible.

This does not appear to be intended behavior as this behavior allows for slots in the v2 version of the task.

**Comment by grantwar** [comment]
Is there any progress on this issue? Having to downgrade all my releases is becoming tedious.

**Comment by vincentdass** [comment]
@grantwar, currently we are working on this issue.
As a workaround, Can you please replace the App Name with some Release variable (say `$(appname)`) and set the release variable to your App Service name?
In this way, WebAppKind is changed to 'app' and slot option will be visible.

**Comment by KrishnaAdityaB** [comment]
Fix was checked-in. This will be deployed to production in next 3-4 weeks
