### ISSUE TITLE
Add a feature for passing arguments to the test adapter

### ISSUE THREAD

**Issue by rjaesguerra** [Microsoft/vsts-tasks#5118]
Our tests is written in TAEF and is using the TAEF adapter. We have our tests classified so as we can select which test methods to run. Right now, there is no way of running the Visual Studio test task and passing a query to the TAEF adapter. I think this is an important feature to add.

**Comment by prawalagarwal** [comment]
Hi @rjaesguerra ,

Thanks for your feedback. Since this is a feature request, please reach out to us at devops_tools[at]microsoft[dot]com and we will pick it up from there.
