### ISSUE TITLE
MultiSelectFlatList picklist rendering

### ISSUE THREAD

**Issue by joalmeid** [Microsoft/vsts-tasks#5122]
`In a pickList input, if it is defined as a MultiSelectFlatList, the selected values are not correctly rendered when I reopen the task details.

In my example, I have this pickList input:
{
            "name": "osApplication",
            "type": "pickList",
            "label": "Application",
            "defaultValue": "",
            "required": true,
            "helpMarkDown": "Select one or more applications to deploy. [Learn more.](https://www.medium.com)",
            "properties": {
                "MultiSelectFlatList": "True",
                "DisableManageLink": "True",
                "EditableOptions": "false",
                "PopulateDefaultValue": "true"
            }
        },
`
Whenever I reopen an existing task, when I've previously selected two items, i get:
![image](https://user-images.githubusercontent.com/4800035/29725996-fa5ae776-89c5-11e7-9e0f-28df2cd6c9f2.png)
**It is not displaying the correct selected items**.

I should get, the following rendering. (This happens whenever I pick values, when configuring the task.)
![image](https://user-images.githubusercontent.com/4800035/29726020-15dfdb8c-89c6-11e7-8eca-d1c8d4c81fb1.png)

This is the pickList input, with all the values.
![image](https://user-images.githubusercontent.com/4800035/29726016-0e40488a-89c6-11e7-8699-77de5621e29f.png)

**Comment by shyama1208** [comment]
@joalmeid Can you please let us know which task you are using. Otherwise, can you provide some other repro for the issue ?
Also, we have MultiSelectFlatList input in 'Azure App Service Manage' task. The input is 'Install Extensions' and is visible when 'Action' = 'Install Extensions'. If possible, can you try out this task and see if same issue appears?

**Comment by joalmeid** [comment]
Provided access to my sub, where the issue occurs.
Just tried the input is 'Install Extensions'  in 'Azure App Service Manage' task, and in fact it didn't repro.

**Comment by asranja** [comment]
The "PopulateDefaultValue": "true" property doesn't support multi-select picklists. Can you remove the property and retry ?

**Comment by joalmeid** [comment]
Removed PopulateDefaultValue from input properties. Totally worked.
Thanks @asranja and @shyama1208
