### ISSUE TITLE
Process 'msbuild.exe' exited with code '1'.

### ISSUE THREAD

**Issue by SickAmente** [Microsoft/vsts-tasks#5132]
The build job on vsts always runned fine. But now the build job is broken and i don't know why. 
We use our own build agent (not the hosted agent) and we get always this error since some days.

I attached the log files of the vsts build job.
Maybe you can figure out what is the problem here?

For your information we have a second build for another .NET product that is running fine... So i think the problem is not our own build server ...

With kind regards,
SickAmente
[logs_1888.zip](https://github.com/Microsoft/vsts-tasks/files/1256665/logs_1888.zip)

**Comment by bryanmacfarlane** [comment]
If msbuild returned 1 and the build failed then the CI system ( and this task which runs msbuild ) did its job correctly.  You have to figure out why your build failed

**Comment by SickAmente** [comment]
Hi Bryan,

but the Log of the VSTS Console shows that there are no build errors. For what shall I search then?

![image](https://user-images.githubusercontent.com/31407374/29776544-2f406bb0-8c09-11e7-896d-1f7bb72f631a.png)

**Comment by bryanmacfarlane** [comment]
The log clearly shows that msbuild exited with a return code of 1, that's a failure.
