### ISSUE TITLE
64k environment variable limit

### ISSUE THREAD

**Issue by ericsciple** [Microsoft/vsts-tasks#5133]
The following tasks need to be updated to the task lib 0.8.2 or higher to get the fix:

- [x] DeployVisualStudioTestAgent
- [x] ServiceFabricComposeDeploy
- [x] ServiceFabricDeploy
- [x] ServiceFabricPowerShell
- [x] ServiceFabricUpdateAppVersions
- [x] XamarinAndroid

**Comment by ericsciple** [comment]
https://github.com/Microsoft/vsts-tasks/issues/5078

**Comment by ericsciple** [comment]
PR to use as an example: https://github.com/Microsoft/vsts-tasks/pull/4660

**Comment by prawalagarwal** [comment]
This is done for [DeployVisualStudioTestAgent](https://github.com/Microsoft/vsts-tasks/pull/5222) task. @ericsciple please verify.

**Comment by prawalagarwal** [comment]
Removing test label as DTA task changes are done. Let me know if it is required.

**Comment by nigurr** [comment]
@ericsciple after updating the VstsTaskSdk version, I am seeing below message in Task and seems to be genuine
the psm1 file is having reference to the dll, however it's not being present in the lib.

```
Add-Type : Could not find file 'D:\Agent_Latest\_work\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c
60d2b6\2.1.24\ps_modules\VstsTaskSdk\VstsTaskSdk.dll'.
At D:\Agent_Latest\_work\_tasks\DeployVisualStudioTestAgent_52a38a6a-1517-41d7-96cc-73ee0c60d2b6\2.1.24\ps_modules\Vsts
TaskSdk\VstsTaskSdk.psm1:20 char:1
+ Add-Type -LiteralPath $PSScriptRoot\VstsTaskSdk.dll
```

**Comment by ericsciple** [comment]
@nigurr you are missing [this line](https://github.com/Microsoft/vsts-tasks/pull/4660/files#diff-903a6497ecbd54360703b61bb1dd869eR23).

**Comment by AlexRukhlin** [comment]
The change is committed to master.

**Comment by bishal-pdMSFT** [comment]
Updated Service fabric tasks with lib.

**Comment by bishal-pdMSFT** [comment]
@ericsciple All the tasks are done i guess. Should we close this issue?
