### ISSUE TITLE
Deploy Azure App Service 3.*- XML transformation fails onto WebJobName.exe.config

### ISSUE THREAD

**Issue by hammer5280** [Microsoft/vsts-tasks#5134]
During a release XML transformation does not work for the Azure WebJob Config:

App.Production.Config transformed ONTO WebJobName.exe.config 

Is this supported?

The warnings I receive from the release log are:

Unable to apply transformation for the given package. Verify the following.
1. Whether the Transformation is already applied for the MSBuild generated package during build. If yes, remove the <DependentUpon> tag for each config in the csproj file and rebuild.
2. Ensure that the config file and transformation files are present in the same folder inside the package.

**Comment by vincentdass** [comment]
@hammer5280 , thanks for reaching out.
XML transformation is applied for config files named `*.config` matching transformation files `*.Release.config` and `*.<environment_name>.config`. (More info [here](https://www.visualstudio.com/en-us/docs/build/steps/transforms-variable-substitution#configuration-transform-file-naming-conventions))

As you know, during build, `App.config `is renamed to `WebJobName.exe.config`.
Please rename your transformation files to match the configuration file. In your case, rename the **App.Production.config** to **WebJobName.exe.Production.config**.

Currently, we don't support transformation for configuration files with different names and directory path. We have a story for the above case (Advanced transformation) in our backlog, which will be taken based on the priority.

**Comment by RoopeshNair** [comment]
Marketplace.visualstudio.com does have few extensions that support variable sub substitution , tokenization etc. Have you explored them?

For feature requests, please post on [UserVoice](https://visualstudio.uservoice.com/forums/330519-team-services?category_id=145269)
