### ISSUE TITLE
External Git artifact source on Release Management

### ISSUE THREAD

**Issue by Symbianx** [Microsoft/vsts-tasks#5136]
Hello,
It would be handy to have an External Git artifact source for Release Management, just like the Builds have.
Although it may seem counter-intuitive it is helpful for artifacts that don't require compilation.

In our case we have our integration tests kept in a separate repository from the source code and would like to link them to the release for testing the various environments. 

As a workaround we created a build that copies the files from the external git repository and publish them as artifact. In the release we link the build as an artifact source. 
This is not ideal, besides being one more step to manage, this does not guarantee that the last integration tests are being used, as the build only checks for new commits every 3 minutes.

**Comment by JacobHenner** [comment]
Would also be helpful for Subversion. In my case, I have deployment scripts in repositories, so being able to pull the scripts from the repositories and then execute them without an additional build step or a manual call to git/svn would be quite helpful.

**Comment by omeshp** [comment]
@Symbianx @JacobHenner In Release Management artifacts can be extended via contributions, it should be easy to integrate different providers using extensions. Which git/svn providers do you want to integrate with. @Symbianx If it is vsts/tfs git then https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.vss-services-externaltfs extension might help.

**Comment by Symbianx** [comment]
@omeshp Currently we are using on-premises GitLab for our repositories. Although it would be great to have a native GitLab integration, we would be happy with the external Git artifact source present in the VSTS builds.

**Comment by GitHubSriramB** [comment]
@Symbianx - Thanks for the suggestion.

Authoring artifact contribution for GitLab is currently what we support. You could refer to the external TFS extension that @omeshp referred to on how this can be done.

Would be great if you could try this, We would be glad to assist you in case you need any help here.

**Comment by Symbianx** [comment]
@GitHubSriramB Thanks for getting back.

I may be missing something, but the extension that @omeshp referred to is to link Git repositories from ** external TFS/VSTS**. Our goal is to reference repositories stored on an **on-premises GitLab**.

Am I missing something?

**Comment by GitHubSriramB** [comment]
@Symbianx - Yes. You would have to author an artifact source contribution for GitLab. You cannot reuse External TFS/VSTS artifact as-is.

We plan to improve documentation we have around authoring artifact source contribution in near future. Until then, the extensions we have in vsts-rm-extension GitHub repo can be used as reference.

Note that we don't currently support Continuous Deployment for external artifact sources used in Release.

**Comment by Symbianx** [comment]
Thank you, a while a go I searched for that extension point in the docs and didn't find it.

We will look into creating our own artifact source for it then.

**Comment by omeshp** [comment]
@Symbianx An artifact extension was recently authored for consuming gitlab sources in release, might be of interest to you: https://marketplace.visualstudio.com/items?itemName=onlyutkarsh.gitlab-integration
