### ISSUE TITLE
PS on remote machines: Only part of first line of Write-Verbose goes to Release Management logs.

### ISSUE THREAD

**Issue by mayeager22** [Microsoft/vsts-tasks#5138]
I have a command-line task calling Psexec to call a Powershell script (because the "Powershell on remote machines" will not allow me to run as an admin user).

I have several Write-Verbose ... -Verbose lines in that Powershell script, but it seems that only the part of the first one is written to the vsts logs.  How can I get all of the Write-Verbose commands to go to the vsts logs?

Below is my script and screenshot of the VERBOSE output I get:

param(
  [Parameter(Position=0,Mandatory=$true,HelpMessage="The name of the BizTalk app being deployed (for use in logfile name).")]
  [Alias("app")]
  [string]$BTSApp,
  
  [Parameter(Position=1,Mandatory=$true,HelpMessage="Msi file should be existing")]
  [ValidateScript({Test-Path $_})]
  [Alias("msi")]
  [string]$MsiFile,
  
  [Parameter(Position=2,HelpMessage="Path wherein the resource file will be installed")]
  [Alias("path")]
  [string]$ApplicationInstallPath,
  
  [Parameter(Position=3,Mandatory=$true,HelpMessage="Only valid parameters are DEV, INT, UAT and PROD")]
  [Alias("env")]
  [string]$Environment,

  [Parameter(Position=4,Mandatory=$true,HelpMessage="Should deployment be done to the Biztalk DB (true if this is the last (or only) server).")]
  [Alias("BTDeployMgmtDB")]
  [string]$DeployBizTalkMgmtDB
  )

$VerbosePreference = "Continue"
$TimeStamp = Get-Date -format "yyyyMMdd_HHmmss"
$Logfile = "E:\Deploy\Logs\Deploy_" + $BTSApp + "_" + $TimeStamp + ".log"
Write-Verbose "For detailed information on this command see $Logfile on the target server." -Verbose
Write-Verbose "Deployment results can be found in $ApplicationInstallPath\DeployResults" -Verbose

$ThingToRun = "powershell -command `"& {. E:\Deploy\Install-BizTalkApplication.ps1 ; FullInstallProcess-BizTalkApplication -msi $MsiFile -path '$ApplicationInstallPath' -env $Environment -BTDeployMgmtDB $DeployBizTalkMgmtDB}`""
Write-Verbose "Start with $ThingToRun" -Verbose

$result = cmd /c $ThingToRun 2`>`&1 | Tee-Object -file $Logfile

if($LASTEXITCODE -ne 0 )
{
throw $result
}
else
{
Write-Verbose "App logs $result" -Verbose
}

Write-Verbose "Lastexitcode $LASTEXITCODE" -Verbose

![image](https://user-images.githubusercontent.com/9683192/29795349-15a1c4a6-8c09-11e7-9d78-2bceff988a3a.png)

**Comment by KrishnaAdityaB** [comment]
@mayeager22 what did you mean by 

> "Powershell on remote machines" will not allow me to run as an admin user

The task uses the credentials provided as input. Those credentials can be admin's on the remote machine. If this is not working for you - can you share the debug logs of that instance?

**Comment by mayeager22** [comment]
@KrishnaAdityaB 

When I try to run a "Powershell on remote machines" command with a user that is an admin on the remote machine, it is not running as elevated and commands (such as editing the registry) are failing.  There is another issue, #5073 that I believe talks about this.

**Comment by KrishnaAdityaB** [comment]
@mayeager22 
Can you share the debug logs of the "PowerShell on remote machines" task and the Command Line task you used with psexec?
You can send them to RM_Customer_Queries at Microsoft dot com

**Comment by KrishnaAdityaB** [comment]
@mayeager22 I got the logs on e-mail. 
I will look into the Remote PS issue. Forked a separate thread for that #5218 
I will leave this thread to continue on the logs issue. @bryanmacfarlane can help you here. I will forward the corresponding debug logs in our internal e-mails.

**Comment by chshrikh** [comment]
@mayeager22 please let us know if you are still facing this issue

**Comment by chshrikh** [comment]
please feel free to reopen this, if you are still facing an issue
