### ISSUE TITLE
Azure App Service Deploy V3 - options missing

### ISSUE THREAD

**Issue by Oddleif** [Microsoft/vsts-tasks#5147]
It seems that Azure App Service Deploy task does not like API Apps, as every time I choose an App Service API app as target for deployment all the deployment options dissaper. Similar to what is described in #4187.

If I select v2 the fields for that version appears as expected, except I really need the JSON variable substitution feature in v3...

**Comment by KrishnaAdityaB** [comment]
Similar to #5115 . Closing this thread and tracking it there.
