### ISSUE TITLE
dotnet pack vs nuget pack

### ISSUE THREAD

**Issue by KZeronimo** [Microsoft/vsts-tasks#5148]
Apologize in advance - I've done some cursory digging but I'm not sure I'm clear on the use cases

In the past if I've had a solution that mixed .net framework lib output and .net standard lib output I used the deprecated nuget packaging task the framework projects and dotnet pack for the .net standard projects - going forward is that bifurcation going to continue to exist or should nuget pack be able to span both use cases

If both tasks are going to continue forward it would be nice to see them unified wrt the configuration they support - for example --include-source

**Comment by alexmullans** [comment]
@anangaur can you comment here?

**Comment by anangaur** [comment]
Doesn't the following command pack symbols and sources?
`> nuget.exe pack <csproj> -Symbols`

Alternatively, If you are multi-targeting in the same project i.e. if you are using:
```
   <TargetFrameworks>netstandard2.0;net45</TargetFrameworks>
```
then you can set the following properties in the project file (csproj) and a **regular build** will generate **one**  package that targets both the TFMs along with the symbols and sources:

```
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <IncludeSource>True</IncludeSource>
```

**Comment by keithrob** [comment]
Closing based on previous suggestion.
