### ISSUE TITLE
VSTS Task fails to restore certain project references

### ISSUE THREAD

**Issue by mclark1129** [Microsoft/vsts-tasks#5151]
This issue seems to have cropped up sometime in the past week, and I'm not entirely sure why.  One of my builds stopped working and fails to restore a unit test project which has a project reference to a web app within my solution.

2017-08-29T20:14:57.6398410Z 

> d:\a\1\s\test\AmWins.AmLink.Identity.Server.UnitTests\AmWins.AmLink.Identity.Server.UnitTests.csproj : error NU1105: Unable to find project information for 'd:\a\1\s\src\AmWins.AmLink.Identity.Server\AmWins.AmLink.Identity.Server.csproj'. The project file may be invalid or missing targets required for restore.

I experience this behavior when trying to run `dotnet restore` via the following tasks
.NET Core Task: dotnet restore 1.*
Command Line 1.*

Strangely enough if I change the Command Line task v2 (2.120.1)  then the packages restore correctly.  Unfortunately, shortly after that I run `dotnet test` using the .NET Core task and it fails with the same message.

I am unable to reproduce this locally using `dotnet` on the command line.  Packages continue to restore just fine.  Until today I was running 1.1.0 of the SDK locally, but even after installing 2.0.0 the command line works properly.  I expect this would eliminate some project compatibility issue building older projects agains the 2.0 SDK.

**Comment by bryanmacfarlane** [comment]
getting this over to some packaging folks.  Thanks for reporting

**Comment by MisinformedDNA** [comment]
Is there a known workaround? It works locally, but fails in VSTS. Using .NET Core SDK 1.1 and tried both the .NET Core tasks 1.* and 2.* and both failed.

**Comment by alexmullans** [comment]
Make sure you're using .NET Core 2.*, and also add a new .NET Core Tool Installer and set the version parameter to 2.0.0.

**Comment by MisinformedDNA** [comment]
Is there a workaround if I stay on .NET Core 1.1? It's weird that some projects restore fine and others do not.

**Comment by alexmullans** [comment]
You might try keeping the Tool Installer, but specifying a different release from the table [here](https://github.com/dotnet/core/blob/master/release-notes/releases.csv). Make sure to also select SDK or Runtime based on the version you enter.

**Comment by mclark1129** [comment]
I used the installer task to install version 1.0.4 of the SDK now my build is able to complete successfully.

**Comment by mclark1129** [comment]
Closoing as I have an acceptable workaround for the issue.
