### ISSUE TITLE
Missing leading characters from date and time in DotNetCoreCLI messes up ordering

### ISSUE THREAD

**Issue by pspill** [Microsoft/vsts-tasks#5165]
This is the same issue that was found previously for NuGetCommand, #4752, needs to be fixed in DotNetCoreCLI as well.

Build time: 17:04:05
result: package name - CI - yyyyMMdd-1745
Build time: 17:13:13
result: package name - CI - yyyyMMdd-171313

The ordering result in Visual Studio (list of packages is descending order) will be you can find below which is not correct.

package name - CI - yyyyMMdd-1745
package name - CI - yyyyMMdd-171313

The ordering should be like this:

package name - CI - yyyyMMdd-171313
package name - CI - yyyyMMdd-170405

**Comment by emanuelquintero** [comment]
This issue will be solved by [this PR](https://github.com/Microsoft/vsts-tasks/pull/5347).
The fix will go out in the next deployment.
