### ISSUE TITLE
DotNetCoreCLI pack off by one calculating month in version string

### ISSUE THREAD

**Issue by pspill** [Microsoft/vsts-tasks#5166]
DotNetCoreCLI task is generating a version string with the incorrect month/

For example, in a build 20170830.2, dotnet.exe is being invoked with "dotnet.exe pack /p:PackageVersion=1.3.0-CI-2017730-115639 (etc.)"

**Comment by emanuelquintero** [comment]
This issue will be solved by [this PR](https://github.com/Microsoft/vsts-tasks/pull/5347).
The fix will go out in the next deployment.
