### ISSUE TITLE
Publish .trx Test Results Doesn't Contain Test Owners

### ISSUE THREAD

**Issue by yiqzhou** [Microsoft/vsts-tasks#5174]
VSTS task "Publishing Test Result" doesn't show test owners while the owners information exist in the published .trx file. It began in 1 or 2 hours.

![image](https://user-images.githubusercontent.com/29744299/29909579-2c2cc5a2-8e59-11e7-9ed9-b822cc679bf1.png)

**Comment by yiqzhou** [comment]
Add some details recently got:
For "Publish Test Results", it seems recordings of a test's owner fade after hours. If result of the test is published again, even in another build or release, test owner in the older build can be fetched.
We've got 3 tests as example:
1.Microsoft.Ads.UcmApi.Database.FunctionalTests.UcmTicketingTests.GetFilteredTicketGrid
2.Microsoft.Ads.UcmApi.FunctionalTests.TicketingWorkspaceTests.TicketingAdminApiTests.TicketingWorkspaceTeamProductDataTable
3.Microsoft.Ads.UcmApi.FunctionalTests.TicketingWorkspaceTests.GetAndSearchTicketApiTests.TicketingWorkspaceBookOfTickets_V2
The 1st test comes from [one assembly](https://msasg.visualstudio.com/DefaultCollection/Bing_Ads/_build/index?buildId=735120&_a=summary&tab=ms.vss-test-web.test-result-details), while the 2nd and the 3rd come from [the other](https://msasg.visualstudio.com/DefaultCollection/Bing_Ads/_build/index?buildId=735222&_a=summary&tab=ms.vss-test-web.test-result-details).
We got their APIs from webpage and wrote a script to query continuously. And caught some results:
![image](https://user-images.githubusercontent.com/29744299/30012381-ee622282-9171-11e7-8902-244a62e732d4.png)
![image](https://user-images.githubusercontent.com/29744299/30012387-fbf306e6-9171-11e7-9c99-48561ec2d841.png)
![image](https://user-images.githubusercontent.com/29744299/30012399-07b06e24-9172-11e7-95c1-ee8ef4e13ea3.png)
It appears to be that test owner seldom got lost. However, this is because that we have started to run these tests more frequently (due to cloudtest fixed). Last week, these tests got run and published for 3 hours only once and the tests' owner disappeared about 1 hour after result files published.

**Comment by yiqzhou** [comment]
I've ran the script to detect test owner of Microsoft.Ads.UcmApi.Database.FunctionalTests.UcmTicketingTests.GetFilteredTicketGrid() for 24 hours and here's the result:
![image](https://user-images.githubusercontent.com/29744299/30053877-d2a13844-925c-11e7-87dc-e16a54e41e83.png)
1. There is a cycle of about 1 hour but not precisely.
2. At each reappearance of test owner, I found a test result publishment record during past 1 minute in our team's records. It's not a "recovery" but a "republishment" from other builds or releases.
Hope these may help.

**Comment by ratrakapil** [comment]
We will investigate this issue and get back by Monday. Thanks for details.

**Comment by whichrakesh** [comment]
Owner and priority are updated based on the run and in this case, there was a different run that wasn’t publishing the owner info while publishing results from "Publish test results task". The customer has agreed to fix this from his side.
