### ISSUE TITLE
AzurePowerShell task should expose an option to not "Fail on Standard Error"

### ISSUE THREAD

**Issue by KrishnaAdityaB** [Microsoft/vsts-tasks#5182]
I have a script that throws non-terminating errors. I don't want my task to fail on these error messages. 
As of today, AzurePowerShell task fails on any standard error. It should expose an option like the PowerShell task to skip this behavior.

**Comment by RoopeshNair** [comment]
Rolled out as part of 3.* (preview) version of the task

![image](https://user-images.githubusercontent.com/1370480/38233282-ac67b9d4-3737-11e8-8ad7-18f4fcbca215.png)
