### ISSUE TITLE
The VsTest task's "Path to Custom Test Adapters" hover help should be a bit more specific.

### ISSUE THREAD

**Issue by dee-see** [Microsoft/vsts-tasks#5183]
The help mentions "Nuget restored adapters are automatically searched for.".

I wasted quite a bit of time wondering why it didn't work before heading over to the [readme](https://github.com/Microsoft/vsts-tasks/blob/releases/m109/Tasks/VsTest/README.md) that added "If there is a packages folder in the sources directory, it is automatically searched for testadapters.". We don't restore our packages in the default packages directory so that explained my problem. It would be nice if that bit or a variant of it was in the help shown in the build edition screen.

**Comment by nigurr** [comment]
This is resolved now.
