### ISSUE TITLE
Run Tests via test plan where multiple test cases are associated with the same test method

### ISSUE THREAD

**Issue by AndrewASel** [Microsoft/vsts-tasks#5197]
Hello,

In our coded UI test solution we have cases when multiple test cases associated with one test method. I tying to run this tests:
Run Test>Test selection>Test plan, select suite contained two or more duplicate test name, IDs etc.
And getting error in DTAExecutionHost.exe.log
VstestAdapter.Execution - RunMessage : An item with the same key has already been added.

I also changed Test selection to Test Assembly and added in Filter criteria tests with same name like this:
Name=TestMethod1 | Name=TestMethod1  | Name=TestMethod2
As results 2 test passed, TestMethod1 was handled as 1 test.

The question, is there any workaround to run coded UI test if test plan contains multiple test cases associated with one test method?

**Comment by nigurr** [comment]
@AndrewASel Sorry for the trouble. Unfortunately, currently there is no work around for the same. We have fixed this issue in 15.3 Test Agent.
For older versions, you can duplicate the test method and associate to two test cases separately.

**Comment by AndrewASel** [comment]
Hello @nigurr 
Thank you! I updated test agent to 15.3 and tests associated with multiple test cases are executed. I have one more question: I noticed that if test assigned to 2 or more test cases it executed 2 or more times. I our case we have tests which cover 10 test cases, this test executed 10 times and it take very long time. Is there available any option or setting which allow run test once and update all associated test cases with outcome result at least in test plan suite level?

**Comment by nigurr** [comment]
@AndrewASel I am sorry to say this, currently there's no workaround available. From the user perspective, test execution supposed to execute all test cases from test suite. We don't validate on the associated test methods. 
Alternatively, you can combine your multiple test cases into single test case and associate to one test method.
