### ISSUE TITLE
Some tests result in pending state when testsettings file specified in Run Functional Tests task

### ISSUE THREAD

**Issue by yorhpokie** [Microsoft/vsts-tasks#5209]
If I specify a .testsettings file in the Run Functional Tests v1.* task, as many as 75 test cases out of 291 show pending status.  Even if the .testsettings file contains no sub elements, many tests still show pending status.  The second issue is these test results don't explain why these tests show pending status and why they didn't run.  This is a worse experience than MTM.  I have attached 2 .testsettings file and 2 screenshots.

[Temp.zip](https://github.com/Microsoft/vsts-tasks/files/1271709/Temp.zip)

**Comment by nigurr** [comment]
@yorhpokie sorry for the inconvenience.  Please feel free to share your feedback: https://visualstudio.uservoice.com/forums/330519-team-services. We will be glad to improve the experience.

Seems like these test cases are skipped/ignored. Do you have any filters on Run Functional Test task? Can you please attach DTAExecutionHost.exe.log file from Test agent machine [C:\dtalogs\dtaexecutionhost.exe.log or C:\testagent\dtaexecutionhost.exe.log]?

**Comment by yorhpokie** [comment]
_Hi nigurr and prawalagarwal,

I don't have any filters on Run Functional Test task.  In the latest test run where I specify only 2 test agents, half of the tests ran and the other half resulted in pending state.  I have attached a zip file that contains the dtaexecutionhost.exe.log files for both test agents.  Please let me know what you find out.  Thank you!
[DTAExecutionHost.exe.zip](https://github.com/Microsoft/vsts-tasks/files/1279226/DTAExecutionHost.exe.zip)
_

**Comment by nigurr** [comment]
@yorhpokie 

Are you running the tests using Test Plan/Test suites?

**Comment by yorhpokie** [comment]
Yes, the Test Plan/Test suites are from MTM.

**Comment by nigurr** [comment]
@yorhpokie Are there any test cases are associated to same test method?
This is known issue where if multiple test cases are associated to same test method, there will be an error and tests wont be executed. This is fixed in VS 15.3 and later versions. We suggest you to remove duplicated test cases or duplicate the test methods and re associate test cases.

**Comment by yorhpokie** [comment]
@nigurr All of our test cases have unique test method.  This issue only happens if a .testsettings file is specified in the Run Functional Test task, even when the .testsettings file is mostly empty.  Please investigate further.  This is blocking us from moving to the test infrastructure in TFS 2017, especially considering MTM will be deprecated in TFS 2018.

**Comment by nigurr** [comment]
@yorhpokie We are happy to help you on this and help you to migrate. Can you please raise support ticket with Microsoft Customer Service? Please let me know if you need any assistance regarding the same.

**Comment by prawalagarwal** [comment]
Closing this. Please re-open if you still need assistance on this issue.
