### ISSUE TITLE
"Powershell on remote machines" will not allow me to run as an admin user

### ISSUE THREAD

**Issue by KrishnaAdityaB** [Microsoft/vsts-tasks#5218]
Forked from #5138

**Comment by KrishnaAdityaB** [comment]
@mayeager22 I was not able to reproduce this issue. 
My "PowerShell on Target Machine" task is successfully executing with admin permissions. I tried with below script
```
Write-Verbose -Verbose "Echoing into file in system drive :: start"
echo "Hi" > c:\temp.txt
Write-Verbose -Verbose "Echoing into file in system drive :: finish"

Write-Verbose -Verbose "Adding a registry key under HKLM :: start"
REG ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /f /v DummySz /t REG_SZ /d 0
Write-Verbose -Verbose "Adding a registry key under HKLM :: finish"

Write-Verbose -Verbose "Adding a registry key under HKCU :: start"
REG ADD HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies /f /v DummySz /t REG_SZ /d 0
Write-Verbose -Verbose "Adding a registry key under HKCU :: finish"
```

If you face any Access Denied errors when using this task - Please execute the same script manually in a Remote PS session. If it is failing, you have to fix the permissions. If it is passing, you can reopen the issue by attaching the debug logs.

In your particular case, I got your logs in e-mail. The logs didn't suggest any errors with Authorization. They were about some file missing.

**Comment by mayeager22** [comment]
The file was missing because a command failed to run that creates the file.

Thank you,

Mary Ann Yeager | Software Configuration Manager
Phidiax, LLC | www.phidiax.com<http://www.phidiax.com/>
Phone: 303-669-6944 | Main Office: 720-310-0161 | Email: MaryAnnYeager@phidiax.com<mailto:MaryAnnYeager@phidiax.com>
[Phidiax_Logo_Basic_with_Phidias_SubLabel_ReDraw_Phi_Black_W180]

[inc5000_num_317_withStats]

**Comment by KrishnaAdityaB** [comment]
@mayeager22 reopening the issue to investigate further.

**Comment by MEbbesenDB** [comment]
I don't know if this helps, but when I want to run a remote PS Script that needs to run something in an elevated prompt, I start the script out with the following in my scriptblock:

If (-NOT ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator))
			{   
				$arguments = "& '" + $myinvocation.mycommand.definition + "'"
				Start-Process powershell -Verb runAs -ArgumentList $arguments
				Break
			}

It checks if PS is elevated and if not elevates it if the user has the rights to be an admin

**Comment by mayeager22** [comment]
I have tried a variation of this, but it did not seem to help.

I have a Powershell script that call another Powershell script with several functions.  Would it suffice to just put this elevation check in the wrapper script?

**Comment by KrishnaAdityaB** [comment]
@mayeager22 Sorry for the delay in response. Adding @vincentdass who is taking care of customer issues for this week and next.

I am still not convinced, what you were facing was because of not having admin rights. 
From the logs I saw, all commands returned with Exit code 0. And the expected file was from %temp% folder. I might be wrong, but writing to user's %temp% folder shouldn't require admin permissions.

Please try this and share the observations. Later, we can debug the script together.
1. Increase the verbosity of the failing command's logs
2. Print the file path that the command tried to write to
3. And do the above 2 steps with the command that is failing to access the created file

**Comment by vincentdass** [comment]
Closing this issue, as no response received.
Feel free to open the issue, if required.
