### ISSUE TITLE
Unable to run remote powershell without credentials

### ISSUE THREAD

**Issue by atulsureka** [Microsoft/vsts-tasks#5226]
Hi

I created a **PowerShell on Target Machines** task which executes a power shell on remote machine. This task is created as a part of release definition. 

Logically speaking when I trigger a new release then build agent executes this power shell on remote machine. Let's say target machine is M1 & my build agent is running under a user account u1. I made u1 as administrator on M1. 

If the account under which service agent is running is an administrator on target machine then why do I need to explicitly mention the credentials. If I do not specify the credentials then it throw error. 

Atul

**Comment by KrishnaAdityaB** [comment]
@atulsureka This behavior is the current design. 
So, we will consider this thread as a suggestion not an issue. Please log the suggestion at https://visualstudio.uservoice.com. We will prioritize it based on voting.

To maintain backward compatibility - we were not able to fail during RD saving.
