### ISSUE TITLE
Build tag 'XYZ' was not added successfully

### ISSUE THREAD

**Issue by karpis** [Microsoft/vsts-tasks#5228]
Using
`
Write-Host ##vso[build.addbuildtag]XYZ
`
from PowerShell within a build.

The tag _is_ properly added to the build, but the error message 
> Build tag 'XYZ' was not added successfully

is dispalyed in logs and the build fails because of that.

The command is _successful_ if build tag 'XYZ' _does not exist_ for the team project.
The command is _successful_ if build tag 'XYZ' _exists_ for the team project.
The command **_fails_** if a build tag _with different casing_ (e.g. 'Xyz', 'xyz', etc) exists for the team project.

In my case, the team project already has a build tag 'Xyz' (note the casing). When I try to tag a build with 'XYZ', the tag '**Xyz**' is re-used and the error message is written.

I'm totally okay with reusing a tag with different casing, but the error message should not be displayed if the tag added uses different casing than existing.

Using TFS 2017 Update 2 on-prem. Agent version is 2.117.2.

**Comment by bryanmacfarlane** [comment]
please create an issue in the vsts-agent repo.  not a task issue
