### ISSUE TITLE
Packages failed nuget restore VS 2017 in VSTS projects .net standard

### ISSUE THREAD

**Issue by izefler** [Microsoft/vsts-tasks#5236]
Hello,

I need help!

I am using an on-premises build server, Windows with VS 2017 installed, I have other applications with the same features and works perfectly.

However for a specific application the error occurs!

In the task nuget restore it can not restore all the packages, the following error occurs:

Committing restore...
Generating MSBuild file d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms\obj\MRV.Obras.Mobile.Forms.csproj.nuget.g.props.
Generating MSBuild file d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms\obj\MRV.Obras.Mobile.Forms.csproj.nuget.g.targets.
Writing lock file to disk. Path: d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms\obj\project.assets.json
Restore failed in 545.85 ms for d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms\MRV.Obras.Mobile.Forms.csproj.
Errors in d:\a\15\s\src\dev\mobile\Shared\MRV.Obras.Mobile.Forms.Sincronizacao\MRV.Obras.Mobile.Forms.Sincronizacao.csproj
Unable to resolve 'd:\a\15\s\src\dev\mobile\Shared\MRV.Obras.Mobile.Forms.Core\MRV.Obras.Mobile.Forms.Core.csproj' for '.NETStandard,Version=v1.5'.
Unable to resolve 'd:\a\15\s\src\dev\mobile\Shared\MRV.Obras.Mobile.Forms.OrdemServico\MRV.Obras.Mobile.Forms.OrdemServico.csproj' for '.NETStandard,Version=v1.5'.
Errors in d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms\MRV.Obras.Mobile.Forms.csproj
Unable to resolve 'd:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms.Sincronizacao\MRV.Obras.Mobile.Forms.Sincronizacao.csproj' for '.NETStandard,Version=v1.6'.
NuGet Config files used:
d:\a\15\s\src\dev\nuget.config
Feeds used:
http://nuget.syncfusion.com/nuget_xamarin/nuget/getsyncfusionpackages/xamarin
https://api.nuget.org/v3/index.json
Installed:
100 package(s) to packages.config projects
56 package(s) to d:\a\15\s\src\dev\Shared\MRV.Obras.Mobile.Domain.OrdemServico\MRV.Obras.Mobile.Domain.OrdemServico.csproj
56 package(s) to d:\a\15\s\src\dev\Shared\MRV.Obras.Mobile.Domain.Core\MRV.Obras.Mobile.Domain.Core.csproj
35 package(s) to d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms.Core\MRV.Obras.Mobile.Forms.Core.csproj
35 package(s) to d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms.OrdemServico\MRV.Obras.Mobile.Forms.OrdemServico.csproj
29 package(s) to d:\a\15\s\src\dev\mobile\Shared\MRV.Obras.Mobile.Forms.Sincronizacao\MRV.Obras.Mobile.Forms.Sincronizacao.csproj
35 package(s) to d:\a\15\s\src\dev\mobile\shared\MRV.Obras.Mobile.Forms\MRV.Obras.Mobile.Forms.csproj
Error: d:\a_tool\NuGet\4.0.0\x64\nuget.exe failed with return code: 1
Packages failed to restore

Print settings task nuget:

![image](https://user-images.githubusercontent.com/2823190/30079194-c6af5e28-9255-11e7-9611-bbef2c81e51b.png)

Print settings file nuget:

![image](https://user-images.githubusercontent.com/2823190/30079216-d5de2b9a-9255-11e7-8733-cd039d38dddc.png)

**Comment by alexmullans** [comment]
Can you update the NuGet Restore task to version 2, and also add a "NuGet Tool Installer" task at the beginning of your build set to 4.3.0?

**Comment by dasMulli** [comment]
@alexmullans is the "NuGet Tool Installer" supposed to be available on TFS 2017 Update 2? I was unable to find it..

**Comment by dasMulli** [comment]
better to continue the on-prem discussion in https://github.com/Microsoft/vsts-tasks/issues/5109

**Comment by keithrob** [comment]
@dasMulli ,
The new Nuget Tools installer is not available in TFS2017U2.  However, I have created a [powershell script](https://github.com/keithrob/tools/blob/master/vstsfetchnuget.ps1) which will fetch it for you and add the version of nuget you want to the head of $env:PATH.  @alexmullans also blogged about it [here](https://blogs.msdn.microsoft.com/devops/2017/09/29/using-the-latest-nuget-in-your-build/).  

To use the script... 
1. check it into your repo
2. Create a powershell step and point it at the checked in script.
3. In the arguments section, specify the semver version of a nuget.exe from [here](https://www.nuget.org/downloads) that you want to use.  It should look like this...

![image](https://user-images.githubusercontent.com/908203/31091128-c3c1c30e-a75e-11e7-8c79-8674bc656b0b.png)

**Comment by dasMulli** [comment]
@keithrob thank's for responding, I have followed up on @bryanmacfarlane's suggestion to do the download during the build.

I'm using the new NuGet tasks now but run an inline powershell task before to download the right nuget.exe and configure the build variable that the new NuGet tasks use to determine its location:

```powershell
$path = (Get-Content Env:BUILD_REPOSITORY_LOCALPATH) + "\nuget.exe"
if (!(Test-Path $path)) {
    iwr https://dist.nuget.org/win-x86-commandline/v4.3.0/nuget.exe -OutFile $path
}
Write-Host ("##vso[task.setvariable variable=NuGetExeToolPath]" + $path)
```
