### ISSUE TITLE
Is there a reason you can't select VS2010 in VSBuild task?

### ISSUE THREAD

**Issue by LokiMidgard** [Microsoft/vsts-tasks#5241]
It seems like the scripts support VS2010: [VSBuild.ps1](https://github.com/Microsoft/vsts-tasks/blob/c7abcd615d8232c392c37db186dcd893c283596d/Tasks/VSBuild/VSBuild.ps1#L56)  
But in the UI it is missing: [task.json](https://github.com/Microsoft/vsts-tasks/blob/5fbcd26e49fa469346b71ffc16b1d2d66ff3a754/Tasks/VSBuild/task.json#L51)

I could use this. Are there known problems with vs2010?

**Comment by ericsciple** [comment]
I dont know if the custom msbuild logger will work with it. You can use the MSBuild task and specify the location to msbuild.exe and try it. If not, a script calling msbuild.exe and checking exit code would be the workaround.
