### ISSUE TITLE
Pass all variables include secret variables to the PowerShell script argument 

### ISSUE THREAD

**Issue by kardinal3000** [Microsoft/vsts-tasks#5244]
Hello guys,
I am using On-Prem TFS 2017 U2, version of agent 2.117
I have some challenges maybe you give me advice to how can it be solved
I have release definition which has more than 50 variables. The count of variables always change. In my release pipe I use task "run PowerShell on remote machine".

How can I pass all variables include secret variables to the my PowerShell script argument as an array or hash table where in one variable I will have all the values.

This command Get-ChildItem Env: | Out-String shows all environment variables without secret variables.
I understand that I can pass secret variables in the arguments line as -getVar1 $(getVar1) -getVar2 $(getVar2)
But I repeat the number of secret variables are always changing. So my concern is when I added new secret variable to Tab "Variables" I have to add this in the my script arguments. The chance to make a mistake are grow.

Thanks

**Comment by GitHubSriramB** [comment]
@kardinal3000 - secret variables can be only passed as explicit argument. 

@ericsciple - is there any other suggestion to address this scenario?

**Comment by ericsciple** [comment]
The only way currently is explicit argument. Don't you have to update your downstream script each time also? Why do your variable names constantly change? Can you provide more details about the scenario?

**Comment by kardinal3000** [comment]
My case, I have release definition with 7 environments (Dev, QC, INT, Stage, etc)  where I use Variable groups (15), Variables (12) and Configure Variables (32) in each layer I have secret variables.
I use only one task "Run PowerShell on Remote Machine". This task has field "Session Variables" where I specify all variables, if I skip it this step my script will not work. I do it this action on  each environment.

Every time when I need to remove or add new variable I am meeting with challenges. I have to go through all environments and check back task "Run PowerShell on Remote Machine" - "Session Variables".  Instead of doing this in one place.

I'm wondering if there is any other scenario to pass variables  to remote PowerShell task

**Comment by GitHubSriramB** [comment]
@kardinal3000 - by using a task group that contains the "Run Powershell on Remote Machine" task with the session variables values, you can avoid having to update the arguments across different environments every time. You only need to update the task group.

But you would still to pass the secret variable explicitly as argument to the task.

**Comment by kardinal3000** [comment]
Honestly I can use `VstsTaskSdk`. Besides the task "Run PowerShell on Remote Machine" already uses 
`VstsTaskSdk`. 

I have redesigned the code of this task. I created the new extension and upload to TFS.

So, using `Get-VstsTaskVariableInfo` I just get all job variables available to the task and generate `$sessionVariables` string. 

As a result I have a solution -  every time when I use modified "Run PowerShell on Remote Machine" task. In my PowerShell script I can get access to all job variables include secret vars using the `get-variable` cmdlet

**Comment by GitHubSriramB** [comment]
@kardinal3000 - This sounds like a reasonable approach to get what you want.
@ericsciple - I assume using Get-VstsTaskVariableInfo in this case would be supported. Could you pl. confirm?

**Comment by haole223** [comment]
@kardinal3000 - Can you please elaborate on how you redesigned the code of the task to get all the job variables?  When I tried using the Get-VstsTaskVariableInfo I wasn't getting any values back.  You said you created a new extension is this available on the marketplace?

**Comment by kardinal3000** [comment]
@haole223 - Yes I have extension but I didn't post it on the marketplace.
my extension has two modified task that base on the standard vsts\tasks (Run PowerShell script and Run PowerShell scripts on Target Machines)

Extension : [PowerShellExtraAbility.zip](https://github.com/Microsoft/vsts-tasks/files/1704548/PowerShellExtraAbility.zip)
Inside the archive you will find Read.md file (_in the folder Powershell.Extension_) with detail description how use tasks. Also to find my changes in scripts search for comments with a tag # kardinal3000
Than you have to[ build extention](https://docs.microsoft.com/uk-ua/vsts/extend/get-started/node) and install
