### ISSUE TITLE
Use Multiple Package Feeds in .NET Core Restore Task

### ISSUE THREAD

**Issue by Rabadash8820** [Microsoft/vsts-tasks#5265]
I have a build definition and several package feeds in the same VSTS account, and I would like to use these package feeds in the build's .NET Core Restore task.  I am using the 2.* preview version of the Restore task, but unfortunately it looks like only one feed can be selected at a time in the Task UI (see screenshot below).  We can of course add multiple feeds to a nuget.config file, but this is a less than optimal solution as that file must also contain credentials, which I would really prefer not to commit to version control.  Separating multiple feed names with delimiters does not work either, generating errors similar to `error : NuGet.Config is not valid XML.  The ',' character, hexadecimal value 0x2C, cannot be included in a name`.  If users are allowed to create multiple package feeds, then we really need to be able to select multiple feeds in build tasks.

![image](https://user-images.githubusercontent.com/8388785/30186124-3640cc02-93f2-11e7-9882-80bdbdf8facd.png)

**Comment by racemills89** [comment]
Also having the same issue. Is there any way to achieve referencing two feeds from my internal VSTS packages within the same .Net Core restore task?

**Comment by alexmullans** [comment]
Checking in a NuGet.config is the right way to go when you're using multiple feeds. The task will automatically provide credentials for all VSTS feeds in the same account as the build.
