### ISSUE TITLE
ServiceFabricDeploy: Removes all application instances when using invalid parameters file

### ISSUE THREAD

**Issue by RaleS** [Microsoft/vsts-tasks#5275]
Providing an invalid application parameter file removes all applications.

In this case, publishing profile xml file has been used as input for Application Parameters.
This was initial deployment of Service Fabric application.
Deployment task Overwrite Behavior is set to Always.

Agent version: 2.120.2
Service Fabric Cluster version: 5.7.198.9494

> 2017-09-08T06:39:59.6519071Z ##[section]Starting: Deploy Service Fabric Application
> 2017-09-08T06:39:59.6779086Z ==============================================================================
> 2017-09-08T06:39:59.6789086Z Task         : Service Fabric Application Deployment
> 2017-09-08T06:39:59.6789086Z Description  : Deploy a Service Fabric application to a cluster.
> 2017-09-08T06:39:59.6789086Z Version      : 1.3.10
> 2017-09-08T06:39:59.6789086Z Author       : Microsoft Corporation
> 2017-09-08T06:39:59.6789086Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=820528)
> 2017-09-08T06:39:59.6789086Z ==============================================================================
> 2017-09-08T06:40:03.4482450Z Searching for path: d:\a\r1\a\Admin Manager\drop\projectartifacts\src\AdminManager\AdminManager\PublishProfiles\Cloud.xml
> 2017-09-08T06:40:03.4802464Z Found path: d:\a\r1\a\Admin Manager\drop\projectartifacts\src\AdminManager\AdminManager\PublishProfiles\Cloud.xml
> 2017-09-08T06:40:03.5222469Z Searching for path: d:\a\r1\a\**\drop\applicationpackage
> 2017-09-08T06:40:03.7722518Z Found path: d:\a\r1\a\Admin Manager\drop\applicationpackage
> 2017-09-08T06:40:03.9962719Z Imported cluster client certificate with thumbprint '********'.
> 2017-09-08T06:40:04.0132595Z 
> 2017-09-08T06:40:04.0142592Z Thumbprint                                Subject                                                                      
> 2017-09-08T06:40:04.0142592Z ----------                                -------                                                                      
> 2017-09-08T06:40:04.0142592Z ********  CN=***.northeurope.cloudapp.azure.com                              
> 2017-09-08T06:40:09.2948876Z Successfully connected to cluster.
> 2017-09-08T06:40:09.3398912Z Searching for path: d:\a\r1\a\Admin Manager\drop\projectartifacts\src\AdminManager\AdminManager\PublishProfiles\Cloud.xml
> 2017-09-08T06:40:09.3538907Z Found path: d:\a\r1\a\Admin Manager\drop\projectartifacts\src\AdminManager\AdminManager\PublishProfiles\Cloud.xml
> 2017-09-08T06:40:09.3558956Z Overriding application parameter file specified in publish profile with 'd:\a\r1\a\Admin Manager\drop\projectartifacts\src\AdminManager\AdminManager\PublishProfiles\Cloud.xml' specified in the VSTS task.
> 2017-09-08T06:40:11.0965629Z An application with name '' already exists in the cluster with application type 'System.Object[]' and version 'System.Object[]'. Removing it.
> 2017-09-08T06:40:12.5818208Z Remove application instance succeeded
> 2017-09-08T06:40:14.4321711Z Remove application instance succeeded
> 2017-09-08T06:40:15.8602689Z Remove application instance succeeded
> 2017-09-08T06:40:17.1724852Z Remove application instance succeeded
> 2017-09-08T06:40:18.4740264Z Remove application instance succeeded
> 2017-09-08T06:40:19.7606449Z Remove application instance succeeded
> 2017-09-08T06:40:21.0474832Z Remove application instance succeeded
> 2017-09-08T06:40:22.8401621Z Remove application instance succeeded
> 2017-09-08T06:40:24.2440855Z Remove application instance succeeded
> 2017-09-08T06:40:25.5540699Z Remove application instance succeeded
> 2017-09-08T06:40:25.9106556Z ##[error]Value does not fall within the expected range.
> 2017-09-08T06:40:25.9486543Z ##[section]Finishing: Deploy Service Fabric Application

**Comment by kuvinodms** [comment]
Fix has been merged. It will get deployed in couple of weeks.

**Comment by bishal-pdMSFT** [comment]
@kuvinodms , I think this can be closed?

**Comment by kuvinodms** [comment]
Closing
