### ISSUE TITLE
Publish Test Results task does not include test attachments for NUnit results

### ISSUE THREAD

**Issue by kdubau** [Microsoft/vsts-tasks#5276]
When using the NUnit result format in Publish Test Results task, if the tests have test attachments, they are not published along with the results.

```xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
...
                  <attachments>
                    <attachment>
                      <filePath>C:\Users\XYZ\AppData\Roaming\Microsoft\VisualStudio\15.0_c63a6c7b\ActivityLog.xml</filePath>
                    </attachment>
                    <attachment>
                      <filePath>C:\Users\XYZ\AppData\Roaming\Microsoft\VisualStudio\15.0_c63a6c7b\ActivityLog.xsl</filePath>
                    </attachment>
                    <attachment>
                      <filePath>C:\TestResults\3762b4e2\XYZ\ZipLogs.zip</filePath>
                    </attachment>
                    <attachment>
                      <filePath>C:\TestResults\3762b4e2\XYZ\TestReport.html</filePath>
                    </attachment>
                  </attachments>
...
</test-run>
```

but 
![image](https://user-images.githubusercontent.com/2809202/30221413-243beede-9491-11e7-8430-cedc68027fd0.png)

Let me know if you need any more information!

**Comment by kdubau** [comment]
Is there any way to work around this?

**Comment by vinodjo** [comment]
Thanks for you feedback. Currently we don't have the support to add test attachments in Publish Results Test task. I am adding this to our backlog. Unfortunately at this stage I can't provide a precise timeline on this. Would also request you to add it to the user voice so that users can up vote this feature https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services

**Comment by vinodjo** [comment]
Have added the request to our backlog. Closing this as a suggestion.

**Comment by alexlazarciuc** [comment]
Hi @vinodjo 

Can you please reference here the item you raise on VSTS to be able to vote for it?

Thanks
