### ISSUE TITLE
Can we stop and start DTAAgentExecutionService on remote machine using TFS Build Definition Continuous Integration 

### ISSUE THREAD

**Issue by Cva2904** [Microsoft/vsts-tasks#5279]
Dear team,

Can we stop and start DTAAgentExecutionService on remote machine using TFS Build Definition ][Continuous Integration].

Do let me know if you need further inputs from my side.

Kind Regards,
Siva. A

**Comment by nigurr** [comment]
@Cva2904 currently it's not possible. To run tests in remote machine, use "Deploy Test agent task and Run functional test task"

**Comment by Cva2904** [comment]
@nigurr 

the reason for this is that my build definition is failing at deploy test agent task. so we thought of stopping the service after build completes and restart the service before deploying the test agent.

can i have your skype for bussiness id, so that i can explain the issue in detail.

Thanks in advance,
Siva.

**Comment by nigurr** [comment]
Please drop a mail: devops_tools at   microsoft  dot com

**Comment by Cva2904** [comment]
@nigurr 

i have sent mail to devops_tools@microsoft.com with the error logs.

**Comment by Cva2904** [comment]
@nigurr 

i haven't sent mail to devops_tools@microsoft.com and the ticket is assigned to ranjanar@microsoft.com.

i have shared the error logs to ranjanar@microsoft.com and awaiting for the response.

Kind Regards,
Siva.
