### ISSUE TITLE
Instances lost when using Azure Cloud Cloud Service deployment task

### ISSUE THREAD

**Issue by lucasmaj** [Microsoft/vsts-tasks#5291]
When using Azure Cloud Cloud Service deployment task the number of role instances appears to be dictated by the service configuration file. This process disregards the currently applied scales. 

For example, while autoscale on production slot would have bumped up # of instances to lets say 20 because of high load, a release to that slot would bring # of instance down to whatever the service config has. Not desired.

Any suggestions on how to keep the number of instances when deploying Cloud Services?

Thanks

**Comment by vincentdass** [comment]
@lucasmaj , As you know, with deployment, the number of instances are overridden by config file value.
Please open the issue with Cloud Service team to resolve.
