### ISSUE TITLE
Add -allowProvisioningUpdates  to the xcode-archive step as variable

### ISSUE THREAD

**Issue by schmichri** [Microsoft/vsts-tasks#5295]
Hi MS-Team, 

Apple will provide XCode9 with automatic signing on the commandline very soon. Please enhance xcode.ts for VSTS to support `-allowProvisioningUpdates` during archive-export. 

E.g. as boolean field or something. 
```
                 //export the archive
                    var xcodeExport: ToolRunner = tl.tool(tl.which('xcodebuild', true));
                    xcodeExport.arg(['-exportArchive', '-archivePath', archive]);
                    xcodeExport.arg(['-exportPath', exportPath]);
                    xcodeExport.argIf(exportOptionsPlist, ['-exportOptionsPlist', exportOptionsPlist]);

                   xcodeExport.arg(['-allowProvisioningUpdates', allowProvisioningUpdates]);
```
Otherwise Xcode9 Auto-Signing is not working in VSTS

**Comment by schmichri** [comment]
Guys, this is pretty urgent for us. Is there a way to speed this up?

**Comment by madhurig** [comment]
@schmichri : Hi, 

We support running Xcode9 builds in VSTS as long as you provide the provisioning profiles. Even with auto-signing, you can collect the provisioning profiles from the developer machine. What issue are you seeing with signing? Please share your logs here or email them to me at madhurig at microsoft.com.

To support "-allowProvisioningUpdates", the build server will need access to your Apple Developer Account. We are reviewing the best way to do that. If you are running the builds on a trusted Mac, you can login to the Apple Developer Portal and store the credentials on the build server and pass "-allowProvisioningUpdates" to the Xcode task via additional arguments in the task. It should be able to download the provisioning profiles in that case. 

Thanks,
Madhuri

**Comment by schmichri** [comment]
@madhurig Hi, 

> If you are running the builds on a trusted Mac, you can login to the Apple Developer Portal and store the credentials on the build server and pass "-allowProvisioningUpdates" to the Xcode task via additional arguments in the task. It should be able to download the provisioning profiles in that case.
This is what we've tried but it's actually not the case. XCode9 in the agent has an valid Developer Portal sign-in. 
If've provided `-allowProvisioningUpdates` in Advanced->Arguments but it is not passed to the exportArchive Step in the task 
![bildschirmfoto 2017-09-15 um 10 50 24](https://user-images.githubusercontent.com/8415907/30474455-08d456d6-9a04-11e7-90a4-57d2b85df867.png)

`[command]/usr/bin/xcodebuild -exportArchive -archivePath /Users/builder/vsts-agent/_work/1/s/LS.xcarchive -exportPath /Users/builder/vsts-agent/_work/1/output/iphoneos/Dev/_XcodeTaskExport_LS -exportOptionsPlist _XcodeTaskExportOptions.plist
`

If I copy/paste this commandline appending `-allowProvisioningUpdates`  on the shell of the buildagent it works fine.

**Comment by madhurig** [comment]
@schmichri: You are right, we are not passing in the additional args to export. In your case it might help to have additional args for export specifically since sharing the additional args for build and export doesn't make sense. I can see that being useful in general too. 

Thanks,
Madhuri

**Comment by madhurig** [comment]
This attached zip file has a new version of the task that allows passing in "Export Arguments". 

[Xcode.zip](https://github.com/Microsoft/vsts-tasks/files/1313912/Xcode.zip)

To upload to your account:
1.	Unzip attached zip file
2.	Install tfs-cli 
`tfx login` (enter collection url followed by PAT)
 `Tfx build tasks upload –task-path <unzipped Xcode task location>`

Thanks,
Madhuri

**Comment by madhurig** [comment]
@schmichri : Closing since we added the ability to pass additional arguments to export.

Thanks,
Madhuri
