### ISSUE TITLE
dotnet pack datetime versioning not guaranteeing that a newer package will have a higher version

### ISSUE THREAD

**Issue by jwace81** [Microsoft/vsts-tasks#5296]
A package generated on 8/8 had the version 1.0.0-CI-**201788**-*, but then a build produced on 8/11 had the version 1.0.0-CI-**2017811**-*.  The 8/11 package is seen as older than the 8/8 package.  The date time versioning should probably use 2 digit numbers for the month and day so the versions become 1.0.0-CI-20170808-* and 1.0.0-CI-20170811-*.

**Comment by emanuelquintero** [comment]
This issue will be solved by [this PR](https://github.com/Microsoft/vsts-tasks/pull/5347).
The fix will go out in the next deployment.
