### ISSUE TITLE
[DeployTestAgent] TestAgentConfiguration task stop with ErrorActionPreference exepction (TFS2017,VMWare)

### ISSUE THREAD

**Issue by kuglerus** [Microsoft/vsts-tasks#5305]
Hi everyone,

As part of continuous integration, i have created build definition to execute my unit tests on remote machine.
I have a TFS 2017 Server in domain and a test domain VMWare virtual desktop.
I configured the build and i opened the https port with winrm commands.
In the log you will see the build server can communicate with the client.
TestAgentConfiguration task stop with ErrorActionPreference exepction and I can't solve this problem:
##[error]Error occured on '[testMachineIP]:5986'. Details : 'The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Exception calling ".ctor" with "2" argument(s): "One or more errors occurred."'

I have obfuscated same internal data on purpose.

I attach printscreen and the build log.

Do let me know if you need further inputs from my side.

Thanks in advance.
Kugler B.

![builddeploytestagent1](https://user-images.githubusercontent.com/22192164/30364681-8aad7f0c-9865-11e7-8152-0dfff4dd87bb.PNG)

**Comment by RanjanarMS** [comment]
Sorry for the inconvenience. This error happens when the DTA machine (test domain machine) is not able to  communicate to the TFS machine via http or https. Please see if you can ping the tfs machine from the DTA machine.

**Comment by kuglerus** [comment]
Hello!
I checked the Internet Explorer settings. I managed to communicate with TFS(on DTA machine).
I tried the build again and I still get same error message.

Any other ideas?
Thank you in advance for your help

**Comment by RanjanarMS** [comment]
I want to understand this statement a bit more "managed to communicate with TFS(on DTA machine)". What settings you changed in the VM? Is the VM reverted to any snapshot before running the next build?

**Comment by RanjanarMS** [comment]
Closing this thread, as there is traction for last 12 days. Please reopen the thread with details.
