### ISSUE TITLE
Task 'Deploy Test Agent' fails: Test Agent installation/update stuck

### ISSUE THREAD

**Issue by nesshoever** [Microsoft/vsts-tasks#5310]
I created a VS 2017 solution that executes UI tests (using Chrome through Selenium). I build and deploy this test solution through VSTS to a VM (Win Srv 2012, VS 2017 Community installed).
After upgrading the VM to Visual Studio 2017, the next deployment got stuck with the task 'Deploy test agent' during the installation of the Visual Studio 2017 test agent. The setup process remained at 100% CPU load and stayed that way for 36 hours. Then I killed the process. Further build runs went the same way.
In the end, I installed the Visual Studio 2017 test agent manually. From then on the task to deploy the test agent succeeds, if I do NOT enable 'Update Test Agent'.
For now this scenario is running ok, but in the long run the option to update the test agent should be working - let alone needing to manually install a test agent for any new test VM.

**Comment by RanjanarMS** [comment]
There is no need for installing Visual Studio in the test VM. Please use a clean VM without VS.

**Comment by nesshoever** [comment]
The description includes TWO machines. One machine for the build process (having VS 2017 installed). The other machine (for the tests) does NOT have VS 2017 installed, just the VS2017 test agent, which should originally be triggered by the build task, if I understand that correctly.

**Comment by kaadhina** [comment]
"VM (Win Srv 2012, VS 2017 Community installed)" Can you please confirm that this is not the case?
If this VM has VS 2017 Community installed, please retry on a clean VM
If it does not, please  collect the logs from c:\testagent if you are on v2 of deploy test agent task, c:\dtalogs if you are on v1 and share them with us.

**Comment by nesshoever** [comment]
I see, my description has been not very good. I used to build on a VM using 2017 Community, but I moved for the build to VSTS.
The VM running the test agent only has the Visual Studio 2017 Test Agent installed. The deploy task is V2, so I attached the DTAExecutionHost.exe.log (as TXT file).
[DTAExecutionHost.exe.log.txt](https://github.com/Microsoft/vsts-tasks/files/1311057/DTAExecutionHost.exe.log.txt)

On a side note: I checked the installed Test Agent version and found an update to be needed (see screenshot). The update takes ages and uses up all available CPU power.

![screenshot_2017-09-18_16-42-52](https://user-images.githubusercontent.com/11948164/30547951-169be592-9c91-11e7-87e2-b5a9895c1bc1.png)

**Comment by kaadhina** [comment]
1. For a build where this issue is hit, can you share the installation logs from %temp%. The file would be named as dd_vsts_testagent* 
2. Can we try this on another clean VM, without a manually installed agent, so we can rule out any issue specific to that machine?

**Comment by abhishkk** [comment]
Closing this issue as we haven't got any response for a while. Please reopen the issue if required.

**Comment by nesshoever** [comment]
I suspect a configuration proble on the VM. I created another VM (Win 10 Azure VM) and there the problem did not occur. So we should keep that closed ;)
