### ISSUE TITLE
vNext Release - Run on Agent high deployment timeout doesn't work

### ISSUE THREAD

**Issue by MSTestAuto** [Microsoft/vsts-tasks#5313]
I have set a 360 timeout for a vNext release as we run a lot of automated tests. But it times out at 60 minutes and aborts the current test run.

Configuration:
![image](https://user-images.githubusercontent.com/29276768/30382782-578ca7f2-98a0-11e7-87d6-165306b59b1c.png)

Test run timeout:
![image](https://user-images.githubusercontent.com/29276768/30382837-82c1bdfe-98a0-11e7-888d-2f7dc11f9ffb.png)

If I set the timeout to 0 minutes for infinite timeout, it works fine.

**Comment by RanjanarMS** [comment]
Sorry for the issue you are noticing, can you please enable the debug logs (by adding the variable "System.Debug = true") and send us the same. Also please let us know you ****.visualstudio.com account name.

**Comment by ShreyasRmsft** [comment]
Closing this issue as we've gotten no response for a while. Please reopen this issue if you feel more clarification from our side is necessary.
