### ISSUE TITLE
Most settings for Azure App Service Deploy task are missing in new release editor

### ISSUE THREAD

**Issue by benc-uk** [Microsoft/vsts-tasks#5324]
When using v3.0 of the *Azure App Service Deploy* task and the new release editor, nearly all the important settings are missing/hidden. See screenshot

![2017-09-14_100025](https://user-images.githubusercontent.com/14982936/30421277-285b5ffc-9934-11e7-9ffc-44c19033d973.png)

If you switch to the old editor you can see them
![2017-09-14_100055](https://user-images.githubusercontent.com/14982936/30421278-285d59e2-9934-11e7-8dd6-57cac031e38a.png)

This means the task is unusable with the new editor.

This seems like a bug in the new editor, it's very confusing for first time VSTS users and my customers telling them they need to switch between editor modes and jump about the UI

**Comment by vincentdass** [comment]
@benc-uk , The additional input field shows up when you provide the subscription name and App Service name in appropriate input fields. This change is made to dynamically render appropriate fields for the selected app service (Windows App / Linux App)

**Comment by benc-uk** [comment]
The fields do not appear when you have picked a subscription and webapp, here I have them set as linked paramters

![2017-09-14_101821](https://user-images.githubusercontent.com/14982936/30421889-210eef3c-9936-11e7-98ac-db24a3bde208.png)

**Comment by benc-uk** [comment]
Even if I unlink the those parameters and pick my sub and app name from the dynamic drop down list, I still see no other settings below 
(Note. the linked parameters is how it was set up by the template "Deploy Node.js App to Azure App Service") 

![2017-09-14_102024](https://user-images.githubusercontent.com/14982936/30421983-7173f8d2-9936-11e7-9e01-9000918f4889.png)

**Comment by benc-uk** [comment]
OK. I can see those extra fields if I add the tasks to an empty process and don't use the *Deploy Node.js App to Azure App Service* template.

This is a problem on two levels:
- I want to use that template when teaching people VSTS as it sets some of the extra but confusing things needed (like the web.config settings required for Node.js)
- If it only works when you pick something from the dynamic dropdown how can we ever do DevOps and continuous deployment with this task??!  
People should be creating their app service using ARM templates and infrastructure as code, the app service web app will ***not exist*** when I am editing this release definition (it is created as **part** of the release process), so my app service name will always need to be some variable or parameter that I pass to the task

**Comment by vincentdass** [comment]
@benc-uk , thanks for the info. It's a genuine issue and will be fixed soon.

**Comment by vincentdass** [comment]
@benc-uk , updated the comment with more info.
Closing the issue as the workaround provided will resolve the issue.
