### ISSUE TITLE
Permission denied when using file share if agent service user doesn't have the permission

### ISSUE THREAD

**Issue by 50802353** [Microsoft/vsts-tasks#5325]
The build agent running as userA while the file share folder is granted for userB.
There's no configuration in build task for me to config the credential to let these tasks work as userB.

This affects two tasks below:
- Copy Files
- Publish build artifacts (to File Share)

Please help fix ASAP.

**Comment by bryanmacfarlane** [comment]
That's currently the requirement.  The agent must runs as the account that copies the files.

There's is a long term feature on the backlog to support "registered shares" where you provide the credential and we use that.

**Comment by jawn** [comment]
> There's is a long term feature on the backlog to support "registered shares" where you provide the credential and we use that.

Has the status of this changed, or still in the backlog?
