### ISSUE TITLE
Azure file copy - No files copied to VM

### ISSUE THREAD

**Issue by karlrissland** [Microsoft/vsts-tasks#5326]
Working with the AzureVMs File Copy Task with no luck.

I can see the files copied to the storage account correctly, then get cleaned up.  But, no files are copied to my target VM and no errors are logged.

**Here I show my task configuration.**

![taskconfig](https://user-images.githubusercontent.com/9871029/30429578-f9e0e664-9925-11e7-8d67-bace87d429f7.PNG)

**Here you can see that I am targeting WebSrv1 and trying to push files to c:\WebFiles**

![targetlog](https://user-images.githubusercontent.com/9871029/30429580-f9e43bb6-9925-11e7-87f2-1960ca97923b.PNG)

**Here you can see that the task is completing successfully**

![finished](https://user-images.githubusercontent.com/9871029/30429581-f9e614ea-9925-11e7-8247-1f6c5dd80c39.PNG)

**Here I have a screen shot of WebSrv1.  Notice that no files are copied.  Also, note that the WinRM Https endpoint isn't configured.  That alone should have caused the task to throw an error since it requires that endpoint.  If the files didn't get to the machine, I don't want to see the task marked as pass.**

![websrv1](https://user-images.githubusercontent.com/9871029/30429579-f9e3d4aa-9925-11e7-932e-2172c50a23b3.PNG)

It doesn't look like this task will support using WinRM HTTP via the server name as opposed to the full DNS name, is that correct?  If so, think I need to use the copy task, but either way, There is an issue here that the task didn't throw an error

**Comment by vincentdass** [comment]
@karlrissland , `Enable Copy Prerequisites` option is enabled and it configures the WIMRM HTTPS port automatically.
![image](https://user-images.githubusercontent.com/20121508/30531128-bdea41b8-9c69-11e7-9553-2e6c60e862a5.png)

Can you please share the following details to debug the other issue:
* Debug logs for the release
* Number of VM's associated with the resource group selected
* Can you please check whether the files are copied to other VMs in your resource group?

**Comment by vincentdass** [comment]
@karlrissland , is the issue resolved?

**Comment by Ajay-MS** [comment]
@karlrissland 
Closing this issue assuming you are unblocked on this issue. Feel free to reopen in case problem still persists.
