### ISSUE TITLE
Cannot find xamarinios.js?

### ISSUE THREAD

**Issue by lavahot** [Microsoft/vsts-tasks#5332]
So I keep getting this error where the agent cant find xamarinios.js when running the task as a build step. Of course, there is no xamarinios.js, only a xamarinios.ts. When is this supposed to be transpiled? Did I miss a step when I uploaded this task? Could there be some prerequisite that I missed installing?

**Comment by bryanmacfarlane** [comment]
Did you upload the source code and not the built task?

**Comment by bryanmacfarlane** [comment]
https://github.com/Microsoft/vsts-tasks/blob/master/docs/contribute.md

Shows how to build a task.

**Comment by lavahot** [comment]
Yep, that's exactly what I did, my mistake. Thanks for the quick response.
