### ISSUE TITLE
Azure File Copy: Increase SasToken TTL

### ISSUE THREAD

**Issue by sergsalo** [Microsoft/vsts-tasks#5334]
Is there a way to increase "Storage Container SasToken" TTL from default 4 hours? I want to have it like a year.

**Comment by RoopeshNair** [comment]
For security reasons, default expiry time is set to allow enough time to complete the deployment. If you need longer duration, you can use custom script.

**Comment by sergsalo** [comment]
why not to by default set it to 4 hours but allow people to still configure it?
