### ISSUE TITLE
Create an official Microsoft.VSTS.SourceLink nuget package

### ISSUE THREAD

**Issue by mjsabby** [Microsoft/vsts-tasks#5335]
I'd like to propose we create a nuget package to make it trivial for people to do SourceLinking when using VSTS Build Agents.

VSTS has publicly documented build variables that we can use to target most customers' build scenarios with respect to SourceLinking if not all.

The following targets I'm proposing are for VSTS GIT Repos AND VSTS Build Agents. You can imagine we'd like to make another for GitHub Git Repos and VSTS Build Agents, etc.

I'm happy to make a nuget package for the VSTS GIT Repos and VSTS Build Agent scenario. But it'd great to get official guidance here.

```csharp
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup Condition="'$(TF_BUILD)' == 'true'">
      <DebugType>full</DebugType>
      <SourceLink>$(IntermediateOutputPath)source_link.json</SourceLink>
    </PropertyGroup>
    <Target Name="GenerateSourceLink" BeforeTargets="CoreCompile" Condition="'$(TF_BUILD)' == 'true'">
      <PropertyGroup>
        <SourceLinkRoot>$(BUILD_REPOSITORY_LOCALPATH.Replace("\", "\\"))</SourceLinkRoot>
        <SourceUri>$(SYSTEM_TEAMFOUNDATIONCOLLECTIONURI)$(SYSTEM_TEAMPROJECT)/_apis/git/repositories/$(BUILD_REPOSITORY_NAME)/items?api-version=1.0&amp;versionType=commit&amp;version=$(BUILD_SOURCEVERSION)&amp;scopepath=*</SourceUri>
      </PropertyGroup>
      <WriteLinesToFile File="$(SourceLink)" Overwrite="true" Lines='{"documents": { "$(SourceLinkRoot)\\*" : "$(SourceUri)" }}' />
    </Target>
</Project>
```

**Comment by mjsabby** [comment]
@dandancode

**Comment by bryanmacfarlane** [comment]
you can create a suggestion on user voice or developer community.  This repo is for tasks and it's issues
