### ISSUE TITLE
task repo build process does not support building from behind a proxy

### ISSUE THREAD

**Issue by lavahot** [Microsoft/vsts-tasks#5343]
Unfortunately the mechanism used to download blob files does not respect HTTP_PROXY, HTTPS_PROXY, nor NO_PROXY environment variables (or their lowercase versions), which makes building behind a proxy impossible. Please make this mechanism proxy aware, preferably referencing the aforementioned environment variables.

EDIT FOR CLARIFICATION: I'm referring to when tasks are built with `node make.js build`, not the execution of any particular task.

**Comment by ericsciple** [comment]
Which task?

**Comment by lavahot** [comment]
Well, lots of them, anything that downloads a blob. To name two: ArchiveFiles and XamariniOS.

**Comment by lavahot** [comment]
```
Getting task externals
Downloading file: https://vstsagenttools.blob.core.windows.net/tools/7zip/1/7zip.zip
C:\Users\lavahot\Documents\vsts-tasks\node_modules\sync-request\index.js:37
    throw new Error(response.error.message || response.error || response);
    ^

Error: getaddrinfo ENOTFOUND vstsagenttools.blob.core.windows.net vstsagenttools.blob.core.windows.net:443
```

**Comment by bryanmacfarlane** [comment]
This is currently not a goal
