### ISSUE TITLE
Cloud-based Web Performance Test not exposing self-provisioned agent group

### ISSUE THREAD

**Issue by lei7081** [Microsoft/vsts-tasks#5344]
Found a previous issue reported here: https://github.com/Microsoft/vsts-tasks/issues/3668 , wondering if it has been fixed. If not, do we have an alternative to run performance test on intranet site on a schedule also collecting diagnostic data?

**Comment by ShreyasRmsft** [comment]
Please have a look at:
https://blogs.msdn.microsoft.com/devops/2016/08/23/testing-privateintranet-applications-using-cloud-based-load-testing/

The section you are interested in is 'Using Visual Studio Enterprise IDE'

Basically what you need to do is tick the radio button that says use self provisioned rig and then go ahead and provide the details of the rig (namely rig name and number of agents to use) in the .loadtest file which you can author from visual studio. The link I've provided will guide you through adding these properties to your .loadtest file.

Let me know if this doesn't work for you.

**Comment by ShreyasRmsft** [comment]
Closing this issue as we've gotten no response for a while. Please reopen this issue if you feel more clarification from our side is necessary.
