### ISSUE TITLE
upload extension and get "Cannot insert dublicate key row in object"

### ISSUE THREAD

**Issue by kardinal3000** [Microsoft/vsts-tasks#5345]
Hello guys, 

I create my custom extension and use your task  "PowerShellOnTargetMachines." your task use "DeploymentUtilities\Microsoft.TeamFoundation.DistributedTask.Task.Deployment.Internal.psm1"

When I tried to upload Extension  ".vsix package" I faced with unexpected issue:

`Cannot insert duplicate key row in object 'Gallery.tbl_Asset' with unique index 'PK_tbl_Asset'. The duplicate key value (), 1.0.0, <NULL>, PowerShellOnTargetMachinesExtra\DeploymentUtilities\Microsoft.TeamFoundation.DistributedTask.Task.Deployment.Internal.psm1`

I investigated that and found that the same module exist in the Build Agent 
> ".\externals\vstshost\Microsoft.TeamFoundation.DistributedTask.Task.Deployment.Internal.psm1"

Please can you help me with understanding how can I upload it

**Comment by vincentdass** [comment]
@kardinal3000 , Can you try changing the GUID of the custom extension and then upload the updated extension?

**Comment by kardinal3000** [comment]
Hi @vincentdass 

GUID of the custom extension  - you mean to do this in the extension manifest.json?
