### ISSUE TITLE
Cannot pass an array of strings in the Override Template Parameters setting

### ISSUE THREAD

**Issue by joe45sp** [Microsoft/vsts-tasks#5346]
I have tried every combination I could think of:

{\"East US 2\"}
[\"East US 2\"]
@(\"East US 2\")
{"East US 2"}
["East US 2"]

Every time I get the following error:
2017-09-15T18:11:35.9031720Z ##[error]Deployment template validation failed: 'The provided value for the template parameter 'webAppLocation' at line '1' and column '1392' is not valid.'.
2017-09-15T18:11:35.9031720Z ##[error]Task failed while creating or updating the template deployment.

**Comment by sachinma** [comment]
Array parameters and complex objects were not supported in over-ride section till recently. You could have specified them in the parameters file.
We have just added support for them in over-ride parameters and the fix is rolling out to customers in stages. You should see it in around 2 weeks.

**Comment by ds-ms** [comment]
@joe45sp 
use ["East US 2"] as the value, 
if you're using Release Editor, add a new variable system.debug and set the value to true, 
if you're using Build editor, set the value system.debug to true
And queue a build/release accordingly and attach the logs here.

**Comment by jerryjren** [comment]
@joe45sp 

Have you found a solution for your problem? I'm facing the same issue, tried all the possible combinations.
