### ISSUE TITLE
Failed to run selenium automated test in Azure VM (server 2016) with Run functional test task

### ISSUE THREAD

**Issue by aivendor** [Microsoft/vsts-tasks#5359]
Our release definition:
https://mseng.visualstudio.com/AppInsights/_apps/hub/ms.vss-releaseManagement-web.cd-workflow-hub?definitionId=334&_a=environments-editor-preview
We've created an azure VM whose VS is server 2016.
chromedriver.exe was copied to the directory of build artifact folder. It can be started. But the URL left "data;" and whole browser is empty.
Is there something extra we need to set when run cases on a server machine?

**Comment by cltshivash** [comment]
You need to check on selenium forums on the compat requirements/error. 

There's one improvement you can do is to use the vstest v2 task itself for running UI tests. You can configure the agent to run interactively and can do distribution as well. Please read : https://blogs.msdn.microsoft.com/devops/2017/03/26/vstest-task-dons-a-new-avatar-testing-with-unified-agents-and-phases/
