### ISSUE TITLE
Older NuGet version re-appearing in _tool folder

### ISSUE THREAD

**Issue by jdshkolnik** [Microsoft/vsts-tasks#5361]
Hi,

When I use the deprecated NuGet Packager task, it uses externals\nuget.exe and works fine. When I use the new NuGet task, it fails because it uses an older version that appears under the _tool folder even if I first delete it. How do I prevent this?

**Comment by zarenner** [comment]
Hi John,

Can you please share a screenshot of your NuGet (and any other relevant task) settings, as well as the error details so I can try to reproduce this? Thanks.

**Comment by keithrob** [comment]
@jdshkolnik,
I'm not sure if you are using a *.visualstudio.com account or if you have an on-prem TFS server; however, I can offer the following advice.  If you are using *.visualstudio.com account the recommended procedure is to use the NuGet tool installer at the start of your build task to pick the version of NuGet you want to use for subsequent build steps.  The NuGet command task will discover that the tool installer has been run and use the version of nuget.exe specified therein.

If you are on VS2017, the tool installer was not yet released.  In that scenario, you can create a powershell step that executes [this ](https://github.com/keithrob/tools/blob/master/vstsfetchnuget.ps1) script which will fetch nuget.exe and append it to the head of your $env.PATH.

Keith

**Comment by jdshkolnik** [comment]
I'll give it a try, thanks.
