### ISSUE TITLE
Task Fails on unpack of 'Test Execution' File

### ISSUE THREAD

**Issue by RoakyWood** [Microsoft/vsts-tasks#5370]
Hi folks!

OS: Windows 2012 R2 no Service Pack
TFS Version: TFS 2017 Update 2
Time: Defective Since TFS Update 1 (i.e., worked before doesn't work now. No other relevant changes)
Software: Issue is with the Deploy TestAgent Task
Activity: Run Automated Tests through the Build Feature against a Test Agent.
Experience Level: Automated testing suites through Microsoft TFS on Prem since 2013
User Response: Tried Version 1 and Version 2

1. On the Test Agent, the Task navigates to C:\TestAgent
2. The task drops a zip archive named 'TestExecution'
3. ROOT CAUSE: It fails to unzip the archive
4. Then it gives an error message that it can’t find the DTAExecution Host and several other files
5. I then manually intervene and paste in the unpacked file to the C:\TestAgent folder and the tests start running!
 
[1_Build.txt](https://github.com/Microsoft/vsts-tasks/files/1314827/1_Build.txt)
![deploytestagenttaskunpackdefectbugerror](https://user-images.githubusercontent.com/6556382/30601095-0f89703c-9d2f-11e7-9817-ba213edb789c.jpg)

The task script appears to be broken.
It have lost the ability to run tests from the build.
Kindly provide a time frame on the fix for this bug.

Best Regards,
E.I.

**Comment by ShreyasRmsft** [comment]
Can you please send us the build logs and also the DTAExecution logs from the machines where the test is being run? Also can you let me know what led you to believe that it's the zip extraction that's failing?

**Comment by RoakyWood** [comment]
It absolutely was the unzip task that was failing I watched it happen in real time. The issue was that I was running Powershell 2.0 I upgraded to 4.0 and now it works.

Thanks for following up though.

On Sep 25, 2017, at 6:50 AM, Shreyas R <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you please send us the build logs and also the DTAExecution logs from the machines where the test is being run? Also can you let me know what led you to believe that it's the zip extraction that's failing?
