### ISSUE TITLE
Enhancement npm publish "skip if already exists option"

### ISSUE THREAD

**Issue by baywet** [Microsoft/vsts-tasks#5380]
Quick suggestion here. We're deploying packages automatically using the npm task in publish mode.
It's really great, the only thing that's missing would be an option to "skip publishing if the package with same name and version is already on the feed" thus avoiding error and failing the release.

**Comment by alexmullans** [comment]
Thanks for this suggestion! I've added it to our backlog, so I'm going to close the Github issue.

**Comment by baywet** [comment]
Thanks, will you update that issue once it's implemented?

**Comment by alexmullans** [comment]
Sure. Full disclosure: I don't think we'll be able to schedule it in the remainder of this calendar year.
