### ISSUE TITLE
Nuget push to external nuget server using apikey no longer working

### ISSUE THREAD

**Issue by cory-nmdp** [Microsoft/vsts-tasks#5383]
The Nuget V2 task to push packages to an external Nuget server endpoint using apikey connection is no longer working and returning the following errors:

2017-09-20T16:24:22.7643802Z ##[warning]Can\'t find loc string for key: Error_ApiKeyNotSupported
2017-09-20T16:24:22.7643802Z ##[error]Error: Error_ApiKeyNotSupported

**Comment by Zuul86** [comment]
Is there any way to use version 2.0.6?  It was working in that.

**Comment by chrish619** [comment]
Seems to have been caused by #4984
Even thought this is marked for DotNetCoreCLI, this causes breaking changes in the 'standard' NuGet tasks.

**Comment by Zuul86** [comment]
To get around this issue I just used Custom and used push as the command and arguments.  That way it bypasses that issue.

**Comment by PalleDue** [comment]
Nuget.exe cannot use wild cards. Instead of using custom I used this inline powershell script:

```
Write-Host "Looking in path $Env:BUILD_SOURCESDIRECTORY"
$files = Get-ChildItem -Path "$Env:BUILD_SOURCESDIRECTORY" -Recurse -Include *.nupkg -Name
$apikey = <apikey>
$nugetsource = <nugetsource>
foreach ($f in $files)
{
    Write-Host $f
    &nuget.exe push $f $apikey -Source $nugetsource
    exit 0
}
exit 1
```

**Comment by kyleherzog** [comment]
Same issue here.  I switched to use Custom with the following argument as a workaround for now.

`push $(System.DefaultWorkingDirectory)/$(Release.DefinitionName)/drop/Release/** -ApiKey $(NuGet.ApiKey) -Source $(NuGet.Source)`

**Comment by tkcrown** [comment]
Same issue here. Any fix plan? Thanks

**Comment by kanvuduc** [comment]
+1 here.

**Comment by SergeBerwert** [comment]
+1

**Comment by jonkeda** [comment]
+1

**Comment by Iapmes** [comment]
+1

**Comment by daanl** [comment]
+1

**Comment by antonio-neto-basecone** [comment]
+1

**Comment by cucamacuca** [comment]
+1

**Comment by demetrioalvesnl** [comment]
+1

**Comment by Iapmes** [comment]
Easiest work-around for me: Revert back temporarily to using the deprecated NuGet publisher with a generic endpoint. (May require changes to minimatch patterns.)

**Comment by xavierdecoster** [comment]
For any MyGet users affected by this VSTS change: your MyGet username and MyGet scoped access token (API key) can also be used for Basic Authentication.

You can update the NuGet Service Connection in your Team Project to use Basic Authentication, and leverage your MyGet scoped API key and MyGet username as basic auth credentials.

We updated our docs to reflect this: 
https://docs.myget.org/docs/reference/vsts-integration#Add_a_NuGet_Service_Connection_to_your_MyGet_feeds

![image](https://user-images.githubusercontent.com/880728/30800080-233cdc72-a1df-11e7-9c67-a13b542beacd.png)

**Comment by pedro-resende-1981** [comment]
+1

**Comment by jiraf** [comment]
+1

**Comment by advdberg** [comment]
+1

**Comment by fvelasco1** [comment]
+1

**Comment by jochenvangasse** [comment]
+1

**Comment by SanderSiep** [comment]
+2

**Comment by alesebi91** [comment]
+1

**Comment by cvvvlad** [comment]
+1

**Comment by mikehowey1** [comment]
Auto updates without rollback.....going to be the death of the platform real quick.

**Comment by alexmullans** [comment]
Thanks for reporting. We're determining the root cause of this issue now and will share more details here soon.

**Comment by wyrdfish** [comment]
We also used the deprecated push command also with a generic service endpoint.
maybe allowing the task version selector to be explicit not just major version would help in these instances.

**Comment by alexmullans** [comment]
This is now being tracked as an incident: https://blogs.msdn.microsoft.com/vsoservice/?p=15005

**Comment by scottkoland** [comment]
+1

**Comment by baskint** [comment]
👍

**Comment by felipeOliveira** [comment]
+1

**Comment by Schenz** [comment]
+1

**Comment by alexmullans** [comment]
The fix is now out to all but one of the remaining deployment rings. The majority of users should be unblocked now; the failure rate is down to ~6%. The current ETA for completing this on the final deployment ring is 22:00 UTC. We will provide another update in 2 hours or less at https://blogs.msdn.microsoft.com/vsoservice/?p=15005

**Comment by keithrob** [comment]
@chrish619 ,
The PR you linked to wasn't the root cause.  The root cause is [this](https://github.com/Microsoft/vsts-tasks/pull/5456/files).  
Keith

**Comment by chrish619** [comment]
@keithrob: Fair enough, I did mention it was a _possible_ cause;
Also, a null coalescing truthy, [in this method,](https://github.com/Microsoft/vsts-tasks/pull/5456/files#diff-56b99ee433c329284ed69fdbbb502334R29) e.g.
```
function test(param?:boolean){
  param = param || true; // ?
  return param;
}
```
Will always evaluate to true..
