### ISSUE TITLE
VstsTaskSdk missing in AzureWebPowerShellDeployment Task

### ISSUE THREAD

**Issue by thomasmktong** [Microsoft/vsts-tasks#5388]
Hi, when I start a deployment task of Azure App Service: Classic today, I found the following problem

```
2017-09-21T00:06:52.6276856Z ##[error]File not found: 'C:\VSTS-Agent-2.104.0\_work\_tasks\AzureWebPowerShellDeployment_dcbef2c9-e4f4-4929-82b2-ea7fc9166109\1.0.46\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1'
```

After some investigation, it seems to me that my VSTS agent has downloaded a new version of AzureWebPowerShellDeployment (1.0.46) few hours ago, Comparing the folder structure between the  latest version and older version, seems it used to have a VstsTaskSdk folder under ps_modules, but now the whole folder and its scripts inside are missing.

**Comment by kinoro** [comment]
Please can we get a fix for this Microsoft - we are using VSO and this is happening since yesterday using Hosted agents. Why did you even mess with it in the first place? It is deprecated so leave it alone.

**Comment by arjgupta** [comment]
hi @kinoro , we are hotfixing this. I will update here once that is done. Meanwhile, can you please tell me your account name.

**Comment by chadidbarnero** [comment]
Hi,

Is there any workaround available while you work in the hotfix?

Thanks.

**Comment by thomasmktong** [comment]
@chadidbarnero , if you use private pipeline, you can copy the whole VstsTaskSdk folder from old version to new version. Probably @arjgupta can help if you use hosted pipeline?

**Comment by chadidbarnero** [comment]
thanks @thomasmktong. Unfortunately I only have hosted pipelines...

**Comment by arjgupta** [comment]
we have hotfixed the task. Can you please confirm if you are unblocked. The newer version is 1.0.47

**Comment by thomasmktong** [comment]
@arjgupta , I confirm that my build agent has picked up the new version and deployment can be done successfully. Many thanks.

**Comment by chadidbarnero** [comment]
It is working now. thanks.

**Comment by arjgupta** [comment]
I am closing this issue, please feel free to open this issue, if you are still facing it
