### ISSUE TITLE
How to really run tests in parallel, or troubleshoot when they don't?

### ISSUE THREAD

**Issue by abatishchev** [Microsoft/vsts-tasks#5400]
I'm using the Visual Studio Tests task with "Run tests in parallel on multi-core machines" checkbox selected. But they still run sequentially. I believe the test agents pool which I'm using has all machines multi-core, it's the [Universal Store](https://microsoft.visualstudio.com/DefaultCollection/Universal%20Store/Universal%20Store%20Team/_admin/_AgentQueue?queueId=34&_a=agents) pool in the Microsoft VSTS instance.

**Comment by ShreyasRmsft** [comment]
Can you please re-run the build with System.debug set to True and share the build logs with devops_tools@microsoft.com so that I can have a look?

**Comment by ShreyasRmsft** [comment]
@abatishchev tagging you for notification.

**Comment by ShreyasRmsft** [comment]
@abatishchev  Okay so I had a look at your runs. 

<RunSettings>
  <RunConfiguration>
    <TargetPlatform>x64</TargetPlatform>
    <MaxCpuCount>0</MaxCpuCount>
  </RunConfiguration>
</RunSettings>

This is the run settings file being passed to vstest console which clearly indicates that the VsTest task is passing on the information to vstest console to use all available cpu cores (0 indicates use all).

However I'd like to tell you that this sort of parallelization works only at an assembly level, ie if all your tests are in the same dll then it will not be able to parallelize the execution.

**Comment by ShreyasRmsft** [comment]
Also since you are interested in parallelizing the tests you should try out the phases in release that allow multi-agent parallelism. This should help cut down your test run time considerably.

Please take a look at https://blogs.msdn.microsoft.com/devops/2017/03/26/vstest-task-dons-a-new-avatar-testing-with-unified-agents-and-phases/ for guidance on using this feature.

**Comment by abatishchev** [comment]
Thanks for confirmation and for the link, will try it out!

**Comment by abatishchev** [comment]
@ShreyasRmsft hi, can I ask for some help to reconfigure my build properly? Here's its definition: https://microsoft.visualstudio.com/defaultcollection/Universal%20Store/Universal%20Store%20Team/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=17821
I have 2 assemblies of unit tests I want to run in parallel so I turned off Multi-agent with Maximum number of agents: 2. But it stills runs the full set, all 31 tests twice.

**Comment by ShreyasRmsft** [comment]
@abatishchev sorry for not replying sooner. The multi agent flow is not yet supported in build. Currently it's only available in the release pipeline (the blog points it out I believe). It may take a while for it be supported in the build pipeline.

**Comment by abatishchev** [comment]
No problem, thanks for coming back on this! And thanks for explaining. Let me try it out in one of my release definitions rather than build.

**Comment by cordialamit** [comment]
Hi,

Wanted to check back on this. I have two assemblies holding unit tests and checked "run in parallel" option in vsts task but it still executes sequentially.

Can someone please help here:
https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=7376351&_a=summary

Thanks
Amit
