### ISSUE TITLE
TFS 2017 Build Fails - can't publish test results

### ISSUE THREAD

**Issue by santoorman** [Microsoft/vsts-tasks#5404]
TFS 2017 Build is failing on the Visual Studio Test task when it tries to publish tests result.  Using task version 2.* ... version 1.* was not working anymore (couldn't find path vstest.console.exe and acted strange when I put specific path)... how can I get this to work?  using tfs 2017.5 on the build server, and TFS Version 15.117.26714.0, using the latest agent from that.

<p>2017-09-21T20:29:13.5158841Z Results File: D:\agent1\_work\1\s\Dev\20170305_MD_4.4\TestResults\TfsService_DEVBUILD5 2017-09-21 15_14_33.trx
<BR>2017-09-21T20:29:14.5470386Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.
<BR>2017-09-21T20:29:14.5470386Z ##[error]Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1
<BR>2017-09-21T20:29:17.9532729Z ##[warning]Failed to publish test results: '', hexadecimal value 0x10, is an invalid character. Line 10256, position 10.
<BR>2017-09-21T20:29:17.9532729Z ##[error]Vstest exited with return code: 1.

**Comment by ShreyasRmsft** [comment]
Hi @santoorman, It's a known issue in results publishing. We are working on it and we'll update you once the fix is ready.

**Comment by munir131** [comment]
When test cases are few at that time this error is not occurring. But when test cases are in large number at that time it appears. Can we put the delay between `tests executor task` and `test publish task`?

**Comment by santoorman** [comment]
I don't really understand what you mean. It is the same number of tests whether it fails or not.

Anyway I will try what you suggest where exactly is this setting?

Also which version of vstest.console.exe to use?

**Comment by ShreyasRmsft** [comment]
We already have bugs filed for this and are actively working on it.

**Comment by ShreyasRmsft** [comment]
@santoorman Can you please share the .trx file and the build logs with us at devops_tools@microsoft.com

**Comment by ShreyasRmsft** [comment]
We have fixed it in TPV2 (Test Platform Version 2) and VS 2017 Update4.
