### ISSUE TITLE
App Service Deploy fails with ERROR_CONNECTION_TERMINATED

### ISSUE THREAD

**Issue by lczc1988** [Microsoft/vsts-tasks#5410]
Deploying with VSTS into a staging slot with auto-swap enabled will swap the slots, even if an error occurs during deployment. The error is reported as a warning in the logs. This problem has been happening for a few weeks and is consistent when the connection is terminated during deployment. We are able to work around the failed version by re-deploying the code.
 
Here are the warnings that are reported during the deployment:
Warnings (3)
Error Code: ERROR_CONNECTION_TERMINATED
More Information: **Web Deploy experienced a connection problem with the server and had to terminate the connection.**  Contact your server administrator if the problem persists.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CONNECTION_TERMINATED.
Error: Unexpected end of file has occurred. The following elements are not closed: results. Line 1, position 370.
Error count: 1.

We are using the ‘Azure App Service Deploy’ task version ‘3.*’. I can’t see from the portal whether it is 3.3 or 3.2 but I assume it is 3.3.
 
As for the connection issue, we are running in a VSTS Hosted agent so we won’t be able to diagnose the network from our end unfortunately.

Since it is a hosted agent, I unfortunately have no control over the location and/or network of the agent. 

However, I am inclined to believe that the agent is typically hosted in the Australia East Data Center along with all of our app services.

**Comment by vincentdass** [comment]
@lczc1988 , can you please share the debug logs (set _**system.debug**_ to **_true_** and rerun release).
Can you try adding `-retryAttempts:10 -retryInterval:6000` to additional arguments of Publish Using Web Deploy option.

**Comment by lczc1988** [comment]
Thank you for your quick reply. Let me do it and update here.

**Comment by vincentdass** [comment]
@Iczc1988, is the issue resolved?

**Comment by Ajay-MS** [comment]
@lczc1988 
Closing this issue assuming you are unblocked on this issue. Feel free to reopen in case of the problem still persists.
