### ISSUE TITLE
Are the hosted azure powershell versions correct?

### ISSUE THREAD

**Issue by AlexKeySmith** [Microsoft/vsts-tasks#5415]
In the "Azure Powershell Version" contextual help it states 2.1.0 on the 2017 hosted queue and 3.6.0 on the hosted queue.

However when comparing this to the [documented installed versions](https://docs.microsoft.com/en-us/vsts/build-release/concepts/agents/hosted)

It states:

**Hosted**
Azure PowerShell 3.6.0
AzureRM PowerShell 3.6.0

**Hosted VS2017**
Azure PowerShell 3.8.0 (Installed)
AzureRM PowerShell 3.8.0 (Installed)
Azure PowerShell 4.2.1 (Saved)
AzureRM PowerShell 4.2.1 (Saved)

I'm not sure if I'm understanding the help correctly, but to me it appears that the version numbers are incorrect? 

> In case of hosted agents, the supported Azure PowerShell Versions are: 2.1.0(Hosted VS2017 Queue), 3.6.0(Hosted Queue).
> To pick the latest version available on the agent, select "Latest installed version".
> 
> For private agents you can specify preferred version of Azure PowerShell using "Specify version"

![image](https://user-images.githubusercontent.com/912653/30741068-5edd7a94-9f8b-11e7-8a0e-b8a9e27005c5.png)

**Comment by arjgupta** [comment]
Hi @AlexKeySmith , in Hosted Pool, by default( i.e. if you use version 1 of Azure PowerShell task) azureps 3.6.0 will get picked up. You have option for specifying 2.1.0 and 4.2.1 as well using version 2 of the Azure PowerShell task.

In hosted VS2017 Pool, by default Azure PowerShell will get picked up. You have option for specifying 3.8.0 and 4.2.1 using version 2 of the Azure PowerShell task. We will update the documentation
