### ISSUE TITLE
How to set Json file as a password in Docker registry service registration

### ISSUE THREAD

**Issue by cilerler** [Microsoft/vsts-tasks#5443]
I need to push docker images to a 3rd party service.

Their authentication is through JSON file which has `"` and ` ` characters in it and the file is ~2350+ characters long.

> _In their documentation they are suggesting to use it like below_

```bash
set /p PASS=<keyfile.json>
docker login -u _json_key -p "%PASS%" https://<registry>
```

I wonder how should I set that as a password in following screen?

![image](https://user-images.githubusercontent.com/385958/30782764-76630f9a-a106-11e7-9485-ddf3b1f60a45.png)

**Comment by jikuma** [comment]
what does <keyfile.json> mean. If it means content of keyfile.json. Try pasting the content of the file in password field.

**Comment by GitHubSriramB** [comment]
@cilerler - pl. try the suggestion given by @jikuma 

I am closing this issue as of now. Pl. re-open in case you have further queries.

**Comment by cilerler** [comment]
I'm sorry I completely forgot this one.   

Unfortunately it doesn't work, I believe that field has a limit restriction, Since file content is over 2K+ characters, it could be the problem.  Can you confirm if that field has a character limit or not please?  

_It's a password field, can't see it and not sure if it's posting it correctly_
