### ISSUE TITLE
Socket Exception while running load test with Self Provisioned test rig

### ISSUE THREAD

**Issue by PoojaMiraje** [Microsoft/vsts-tasks#5444]
A connection attempt failed because connected party did not respond properly after period  of time

The webtest alone works fine

**Comment by ShreyasRmsft** [comment]
Can you please elaborate? Did you try running the web test from the same machine the self provisioned agent is on?

**Comment by ShreyasRmsft** [comment]
Closing this issue as we've gotten no response for a while. Please reopen this issue if you feel more clarification from our side is necessary.

**Comment by PoojaMiraje** [comment]
No I am running the test from my local sytem and connecting to the rig

**Comment by abhishkk** [comment]
Did you get a chance to look at the response given by Deepak over mail? Following is the response:

This could be an application/rig issue. You should dig into the server logs and see if the connections are getting closed properly and there are no timeouts.

In the load test you can enable TCPV4 counters if not done already to monitor the connections health from the agent machines.
https://blogs.msdn.microsoft.com/devops/2016/09/30/cloud-load-testing-service-is-hyper-scale-ready-lessons-from-generating-1m-concurrent-user-load/

**Comment by PoojaMiraje** [comment]
yes I tried enabling TCPV4 counters and I am count for connection failuer

**Comment by abhishkk** [comment]
Can you please respond the same over the email query (on which Deepak has already replied). Deepak will be helping you out on this solving this issue.

**Comment by PoojaMiraje** [comment]
Hi ,

I have tried collecting TCPV4 socket details. Most of the sockets are
getting into waiting state and most of sockets will be getting resetted.

**Comment by abhishkk** [comment]
@PoojaMiraje There is a email conversation already going on vsoloadtest@microsoft.com titled "Loadtest Error". Can you please follow up there?
