### ISSUE TITLE
How to pass parameters to custom test adapter (nUnit3)

### ISSUE THREAD

**Issue by asartem** [Microsoft/vsts-tasks#5450]
I had a console command step which ran nunit3-console with parameters and published test results to a file TestResults.xml using nunit test adapter

I need this file in one these formats: junit, nunit, tap, robot to publish on hiptest.net
When I've moved to step Visual Studio Test, I added a Path to Custom Test Adapters to Nunit folder in nuget, but I see no way of how to generate TestResults.xml file (exact name and format) and\or pass some parameters to nunit test runner. There is other console options input which is used for vstest.console.exe

usage of the new style apporach:
1. use VS test step
2. publish test results to trx file

doesn't wokr, while I need xml nunit format for test results, not trx.

usage of the old style approach: 
1. use cmd to run nunit3-console.exe
2. get TestResult.xml file from it
3. and then publish it to hiptest AND TFS 
doesn't work for me as well, because TFS says, that nunit result format is not valid.

**Comment by ShreyasRmsft** [comment]
@asartem Can you tell us why you need the results to be in xml nunit format? Is the only reason you need it because you need to publish it to hiptest also? Also can you let me know why you need to publish the results to hiptest?

**Comment by asartem** [comment]
>  Also can you let me know why you need to publish the results to hiptest?

I need to implement technical and business requirements. I need to publish end-to-end test results to hiptest.net to display results and state for business and BA and also to TFS for development needs.

Also NUnit is very shared and common test format supported by other sistems, if they support .net, de-facto  standard.

**Comment by PBoraMSFT** [comment]
@asartem - Visual Studio Test platform produces TRX. For extensibility in result formats, this forum is not the right one. Please post this ask on https://github.com/Microsoft/vstest/

About the other requirement to run nUnit tests using nunit runner, you can do that and publish results using the publish test results task. Is that not working for you?

**Comment by abhishkk** [comment]
Closing the issue as we haven't got any response for a while. Please re-open the issue if required.
