### ISSUE TITLE
Azure App Service Deploy 403 Error

### ISSUE THREAD

**Issue by fuocor** [Microsoft/vsts-tasks#5458]
The Azure App Service Deploy has started throwing 403 errors when running.
This was working as recently as Saturday, and has not been modified.

additionally, in the task configuration, I cannot change/select any app service.

`2017-09-25T17:29:05.2346239Z ==============================================================================
2017-09-25T17:29:05.2346239Z Task         : Azure App Service Deploy
2017-09-25T17:29:05.2346239Z Description  : Update Azure Web App Services, Web App On Linux , Function Apps, Mobile Apps using Web Deploy / Kudu REST APIs
2017-09-25T17:29:05.2346239Z Version      : 3.3.15
2017-09-25T17:29:05.2346239Z Author       : Microsoft Corporation
2017-09-25T17:29:05.2346239Z Help         : [More Information](https://aka.ms/azurermwebdeployreadme)
2017-09-25T17:29:05.2346239Z ==============================================================================
2017-09-25T17:29:06.1955591Z ##[error]Forbidden
2017-09-25T17:29:06.1955591Z ##[error]Unable to retrieve connection details for Azure App Service:'ossiacodevui'. Status Code: 403 Forbidden
2017-09-25T17:29:06.1995574Z ##[section]Finishing: Azure App Service Deploy: ossiacodevui
`

**Comment by vincentdass** [comment]
@fuocor , Can you please verify whether the SPN expired (Validate once from service endpoint)?
![image](https://user-images.githubusercontent.com/20121508/30852253-cbc661a8-a2c8-11e7-8347-7e4f3b466a02.png)

**Comment by fuocor** [comment]
I'm getting the following error on the verify

Failed to obtain the Json Web Token(JWT) for service principal id '819b4687-bb01-4f9a-97cb-1d69a3183b66'. Exception Message: AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided. Trace ID: 856eeadc-74d1-4712-947a-ae03a1952500 Correlation ID: 93caf92c-f760-4b17-9bfc-711950f60b4d Timestamp: 2017-09-26 16:50:18Z

**Comment by vincentdass** [comment]
@fuocor , it looks like SPN expired. Can you update the endpoint?

**Comment by fuocor** [comment]
Where and how do I do that?

**Comment by fuocor** [comment]
I used the update service configuration and it returned 

Failed to query service endpoint api: https://management.azure.com//subscriptions/39125119-2e00-4137-aba1-fea44b2d9aeb?api-version=2016-06-01. Error Message: The remote server returned an error: (403) Forbidden..

**Comment by vincentdass** [comment]
Have you tried [this ](https://blogs.msdn.microsoft.com/devops/2015/10/04/automating-azure-resource-group-deployment-using-a-service-principal-in-visual-studio-online-buildrelease-management/)to update your SPN?
If not, can you try the manual configuration steps and update Service Principal ID and key.

**Comment by fuocor** [comment]
Creating a new SPN seems to have resolved the problem. The update just fails

**Comment by vincentdass** [comment]
@fuocor , Is the task succeeding now?

**Comment by Ajay-MS** [comment]
@fuocor  Closing this issue assuming you are unblocked on this issue. Feel free to reopen in case of problem still persists.

**Comment by dsharma01** [comment]
The SPN itself is like a user in Azure AD, by default it has no rights. You have to provide it "contribute" permissions, if you wish to use the SPN to create or update resources in Azure. The powershell script commonly available to create SPN does that for you.

**Comment by PoppyPham** [comment]
Oh man, thank @dsharma01 I follow the instruction of MS to create Azure Resource API with Client Principal ID here, and in the instruction they set the Role to the "Reader" which caused the Error.
And after i set to "Contributor" it works. I wasted 1 day fir this shit.

**Comment by kmkumaran** [comment]
@PoppyPham, you can also use this [script ](https://github.com/Microsoft/vsts-rm-extensions/blob/master/TaskModules/powershell/Azure/SPNCreation.ps1) for creating Service principal with appropriate permission for VSTS. The script by default assigns the contributor permission.

**Comment by PoppyPham** [comment]
Thank a lot @kmkumaran

**Comment by 199219921992** [comment]
@kmkumaran @vincentdass I am getting Failed to obtain the Json Web Token(JWT) for service principal id +  Exception Message: Object reference not set to an instance of an object error even after adding SPN to subscription and providing the contributor role and made the secret key as Never expires, what should we do now.
Created seperate Issue- https://github.com/microsoft/azure-pipelines-tasks/issues/10321

Thanks in advance for early looks.
