### ISSUE TITLE
Publish test results is failing

### ISSUE THREAD

**Issue by munir131** [Microsoft/vsts-tasks#5467]
When `Publish test results` task is trying to upload Junit formatted xml file at that time it is throwing error like `Failed to publish test results: Illegal characters in path.`

Publish Test Results : version 2.0.1

![image](https://user-images.githubusercontent.com/6319375/30853499-9cb8ada4-a2cc-11e7-8311-d3c2877834bc.png)

**Comment by munir131** [comment]
![image](https://user-images.githubusercontent.com/6319375/30862913-2e48eeee-a2ed-11e7-8d00-550c29dd5135.png)
Also those tests stay `in progress` state forever.

**Comment by SadagopanRajaram** [comment]
@munir131 - can you please share following details with the devops_tools@microsoft.com alias? 
1) The xml file which is failing
2) Details of server/service - are you using Team Foundation Server or VSTS? If TFS, which version? 
3) Is it a hosted agent or private build/automation agent? 
4) What is the source directory for the path? What is the filter in the "Publish Test Results" task? Are you using v1.* or v2.* of the task? 
Thanks
Sada

**Comment by munir131** [comment]
@SadagopanRajaram  Mail sent. Let me know if you want any other details from my side.

**Comment by munir131** [comment]
@SadagopanRajaram @bryanmacfarlane @nigurr @kaadhina Any update on this?

**Comment by mouse9** [comment]
I am also facing the same issue. Any updates?

**Comment by Dushelov** [comment]
Same problem with both versions (v1.* and v2.*)

**Comment by munir131** [comment]
@SadagopanRajaram @bryanmacfarlane @nigurr @kaadhina Please update on this. Our build system is on hold due to this issue.

**Comment by nigurr** [comment]
This is discussed here: https://github.com/Microsoft/vstest/issues/683
@SadagopanRajaram can we please have fix for the same in vsts-agent side for handling it?

**Comment by silentbobbert** [comment]
I can see this problem on the current version of this task, and the previous version I was using: v1.0.36

**Comment by michel-weber** [comment]
I have the same problem.

**Comment by munir131** [comment]
I found the issue. VSTS test result task considering this  "…" (\u2026)  Unicode character as invalid in my case.

**Comment by octatone** [comment]
I have the same issue using version 1 or 2 of the test publish task

**Comment by SadagopanRajaram** [comment]
The test runner needs to be updated to the latest version. Please see below post. 
https://github.com/Microsoft/vstest/issues/683

**Comment by SadagopanRajaram** [comment]
Closing this issue - we verified that the JUNit XML was not properly formatted resulting in failure.
