### ISSUE TITLE
Install build agent interactive mode hangs in TFS 2015

### ISSUE THREAD

**Issue by shinydiamond** [Microsoft/vsts-tasks#5474]
I am trying to install build agent with same credentials both on TFS and build agent and 
configuring it as 'Interactive Mode' by saying N to Windows as a service (y/n).

On command prompt displayed as 'Registering the agent xxxxxx with the server 'TFS server'
Press Ctrl+C to quit....

I waited for almost for an hour and see below in _diag/log what could I possibly be doing wrong?

19:33:32.158658 Created Session: cb2d8912-32a8-463a-8896-f0fec93f41bc
19:33:32.162655 MessageQueueListener.DispatchAsync - starting loop
19:33:32.164656 MessageQueueListener.DispatchAsync - Getting message from Session: cb2d8912-32a8-463a-8896-f0fec93f41bc
19:33:32.169658 Waiting for Escape key on background thread: True
19:33:32.169658 Waiting for shutdown request event on background thread: True
19:34:22.172853 MessageQueueListener.DispatchAsync - message received.
19:34:22.172853 MessageQueueListener.DispatchAsync - No message retrieved from Session: cb2d8912-32a8-463a-8896-f0fec93f41bc
19:34:22.172853 MessageQueueListener.DispatchAsync - Getting message from Session: cb2d8912-32a8-463a-8896-f0fec93f41bc
19:35:12.173048 MessageQueueListener.DispatchAsync - message received.
19:35:12.173048 MessageQueueListener.DispatchAsync - No message retrieved from Session: cb2d8912-32a8-463a-8896-f0fec93f41bc
19:35:12.173048 MessageQueueListener.DispatchAsync - Getting message from Session: cb2d8912-32a8-463a-8896-f0fec93f41bc
19:36:02.173236 MessageQueueListener.DispatchAsync - message received.
19:36:02.173236 MessageQueueListener.DispatchAsync - No message retrieved from Session: cb2d8912-32a8-463a-8896-f0fec93f41bc
19:36:02.173236 MessageQueueListener.DispatchAsync - Getting message from Session: cb2d8912-32a8-463a-8896-f0fec93f41bc
19:36:52.174429 MessageQueueListener.DispatchAsync - message received.
19:36:52.174429 MessageQueueListener.DispatchAsync - No message retrieved from Session: cb2d8912-32a8-463a-8896-f0fec93f41bc
19:36:52.174429 MessageQueueListener.DispatchAsync - Getting message from Session: cb2d8912-32a8-463a-8896-f0fec93f41bc
19:37:42.175625 MessageQueueListener.DispatchAsync - message received.

**Comment by bryanmacfarlane** [comment]
It looks as though it's running and waiting for a build on the queue.  Agent issues are tracked in the vsts-agent repo, not here.
