### ISSUE TITLE
docker-compose build task fails with [could not read CA certificate "/vsts/agent/_work/_temp/DockerConfig_1506458440225/ca.pem"]

### ISSUE THREAD

**Issue by colindembovsky** [Microsoft/vsts-tasks#5475]
I'm running a docker-compose build task to build service images. The task used to work with version 0.4.0 but the latest version, 0.4.4, fails with a "cannot find ca.pem" error:

```
2017-09-26T20:40:41.6744880Z Step 5/5 : ADD ./target/myshuttledev.war /usr/local/tomcat/webapps/myshuttledev.war
2017-09-26T20:40:45.3554830Z  ---> 281155bf4628
2017-09-26T20:40:45.4178900Z Removing intermediate container 3464841f32b7
2017-09-26T20:40:45.4194200Z Successfully built 281155bf4628
2017-09-26T20:40:45.4495870Z Successfully tagged cdmochjavaacr.azurecr.io/web:latest
2017-09-26T20:40:45.8352160Z [command]/usr/local/bin/docker tag cdmochjavaacr.azurecr.io/db cdmochjavaacr.azurecr.io/db:20170926.4
2017-09-26T20:40:45.8417690Z could not read CA certificate "/vsts/agent/_work/_temp/DockerConfig_1506458440225/ca.pem": open /vsts/agent/_work/_temp/DockerConfig_1506458440225/ca.pem: no such file or directory
2017-09-26T20:40:45.8542230Z ##[error]could not read CA certificate "/vsts/agent/_work/_temp/DockerConfig_1506458440225/ca.pem": open /vsts/agent/_work/_temp/DockerConfig_1506458440225/ca.pem: no such file or directory
2017-09-26T20:40:45.8617290Z ##[error]/usr/local/bin/docker failed with return code: 1
2017-09-26T20:40:45.8980030Z ##[section]Finishing: Build services
```

There are 2 images in the docker-compose file: both image builds succesfully and it appears the tagging command actually worked. However, the task is not completing because of the file not found error.

I'm connecting to an Azure Container Registry, so I use those settings. I tried to create a "plain" container registry endpoint to the same ACR, but got the same failure.

Full source code and instructions I'm following are found here: https://almvm.azurewebsites.net/labs/java/builddocker.html

**Comment by colindembovsky** [comment]
Turns out this was an issue with the `microsoft/vstsagent` container we were using. The `DOCKER_HOST` and `DOCKER_TLS_VERIFY` environment variables were set, but `DOCKER_CERT_PATH` had not been set. Setting that resolved the issue!

**Comment by jikuma** [comment]
Hey Colin, Can you help me understand the issue a bit more. If you are using Docker Compose task you need not set DOCKER_HOST,  DOCKER_TLS_VERIFY, DOCKER_CERT_PATH variable manually.
You should create Docker Host endpoint and specify server url, ca certificate, certificate, key in the endpoint.
Then use this endpoint in docker compose task. Go to advance section and specify Docker Host connection. Task will itself set appropriate env variables for docker client to connect to docker deamon socket.
Can you help we with the information about how you are using the task so that we can handle such error appropriately.

**Comment by jikuma** [comment]
Hey Colin, I got the issue you are not using Docker Host endpoint at all. Can you share complete log whose snippet you have pasted above. This will help me understand the issue completely.

**Comment by bryanmacfarlane** [comment]
opening the issue to see if we can do something in the task to help guide the user.

**Comment by colindembovsky** [comment]
Here's the Dockerfile that we use for our build agent - which is a docker container:

```
FROM microsoft/vsts-agent

# configure docker
COPY .docker /root/.docker/
ENV DOCKER_HOST=tcp://$HOSTNAME:2376 DOCKER_TLS_VERIFY=1 
```
We then start the agent using this command:
```
docker run -e VSTS_ACCOUNT=<account> -e VSTS_TOKEN=<token> -e VSTS_POOL=<pool> -v /var/run/docker.sock:/var/run/docker.sock --name vstsagent -it vsts/agent
```
This starts the agent container and gives the container access to the host's docker daemon.

We then have a `docker compose build` task in our build _with no host endpoint set_ since we want the agent to use the system settings. In this configuration, we get the error message described in this issue.

However, if we change the Dockerfile to:
```
FROM microsoft/vsts-agent

# configure docker
COPY .docker /root/.docker/
ENV DOCKER_HOST=tcp://$HOSTNAME:2376 DOCKER_TLS_VERIFY=1 DOCKER_CERT_PATH=/root/.docker
```
then we get successful builds.

If the error message instead specified "DOCKER_CERT_PATH is not set" (for the case where no host endpoint is selected) it would greatly help debugging this config error.

**Comment by bryanmacfarlane** [comment]
@jikuma - is what @colindembovsky mentioned possible?

**Comment by colindembovsky** [comment]
Hi @jikuma and @bryanmacfarlane 

I've submitted a PR that I think will warn the user about the missing variable.

**Comment by jikuma** [comment]
@colindembovsky thanks for the PR. I saw the PR, are you assuming that every one will want to have a TLS connection between cleint and daemon?
The complete check should be,  to see if TLS verify is set. If set get the cert dir, if found are the certificate present in the directory or not.
Thanks for your help here.

**Comment by colindembovsky** [comment]
Hi @jikuma - good point! I've updated the logic to check if DOCKER_TLS_VERIFY is set before checking for the DOCKER_CERT_PATH.

**Comment by jikuma** [comment]
@colindembovsky you are setting env variables in the DockerFile and in this PR you are validating execution env variable values. 
If you specify env variable inside Dockerfile, these variables are only available inside container and there is no way we can validate in task if the variables are properly set for executing container.
Another way to specify Docker Host is through using Docker host endpoint, where we have appropriate check and we create proper command to set docker host. 
Therefore this change will not warn user if env variables are set inside container.
