### ISSUE TITLE
Unit Tests that that create UI controls fail with latest version of vstest.console.exe

### ISSUE THREAD

**Issue by santoorman** [Microsoft/vsts-tasks#5476]
using vstest.console.exe version as described here:

https://github.com/Microsoft/vsts-tasks/issues/5404#issuecomment-332210558

It now publishes properly but now we are getting exceptions with unit tests that create UI controls (running on TFS 2017 server):
System.InvalidOperationException: The calling thread must be STA, because many UI components require this.

These worked fine with the Built In version of vstest.console.exe.

Now am stuck - if I use version of vstest.console.exe that passes all tests (including these UI tests), then it can't publish it (issue 5404 above).  If I use version of vstest.console.exe that can publish properly, then some of the UI tests fail.

What to do?

**Comment by santoorman** [comment]
just to make clearer 

This one fails on UI tests:
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe"
Version 15.0.0.0
System.InvalidOperationException: The calling thread must be STA, because many UI components require this.

When I use the “latest platform version” – I believe it uses the following?  This one doesn’t publish results:
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"
Version 15.0.26720.2
Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe failed with return code: 1 
2017-09-21T20:29:17.9532729Z ##[warning]Failed to publish test results: '�', hexadecimal value 0x10, is an invalid character. Line 10256, position 10.

**Comment by singhsarab** [comment]
@santoorman 
For the STA issue, can you please try setting the execution-thread-apartment-state
https://github.com/Microsoft/vstest-docs/blob/master/docs/configure.md#execution-thread-apartment-state

**Comment by santoorman** [comment]
thanks but no go:

2017-09-29T21:22:21.9246859Z Error: Invalid settings 'RunConfiguration'. Unexpected XmlElement: 'ExecutionThreadApartmentState'.
2017-09-29T21:22:21.9246859Z ##[warning]Vstest failed with error. Check logs for failures. There might be failed tests.

<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  
  <RunConfiguration>
    <ResultsDirectory>.\TestResults</ResultsDirectory>
    <TargetPlatform>x64</TargetPlatform>
    <TargetFrameworkVersion>Framework45</TargetFrameworkVersion>
	     
     
  </RunConfiguration>

also tried to add this in build definition (Override test run parameters):

RunConfiguration.ExecutionThreadApartmentState=STA

**Comment by abhishkk** [comment]
This issue was moved to Microsoft/vstest#1164
