### ISSUE TITLE
Wix 3.11

### ISSUE THREAD

**Issue by rgiurea** [Microsoft/vsts-tasks#5479]
Hello,

having some issues building a wix setup project because the hosted vs2017 does only have wix 3.10 installed. Would it be possible to update to 3.11?

Thanks. Regards.

**Comment by bryanmacfarlane** [comment]
We install VS 15.3 (2017 update 3).  Does that come with wix 3.11?  What are you using on your desktop?

**Comment by bryanmacfarlane** [comment]
BTW, not a task issue but I'll redirect to the image creation folks.

**Comment by MireilleHanna** [comment]
it has been updated already

**Comment by virzak** [comment]
Could you also make this available for VS 2019?

Here is the error message I'm getting:

```
##[error]Wix\NoviView.Bundle\NoviView.Bundle.wixproj(91,3): Error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\WiX\v3.x\Wix.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```
