### ISSUE TITLE
nuget restore fails with local feed and .net core 2 app

### ISSUE THREAD

**Issue by Jonathan34** [Microsoft/vsts-tasks#5507]
Hi,

Using VSTS to build asp.net core 2.0 app with VS 2017 on an windows on-premise agent.
i have this nuget.config at the root of my solution:
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
    <add key="NuGetFeed Local" value="NugetFeed" />
    <add key="[removed]-Auth-VSTS" value="https://[removed].pkgs.visualstudio.com/_packaging/[removed]/nuget/v3/index.json" />
  </packageSources>
  <apikeys>
    <add key="https://[removed].pkgs.visualstudio.com/_packaging/[removed]/nuget/v3/index.json" value="[removed]" />
  </apikeys>
  <packageSourceCredentials>
    <[removed]-Auth-VSTS>
      <add key="Username" value="[removed]" />
      <add key="ClearTextPassword" value="[removed]" />
    </[removed]-Auth-VSTS>
  </packageSourceCredentials>
  <activePackageSource>
    <add key="api.nuget.org" value="https://api.nuget.org/v3/index.json" />
  </activePackageSource>
</configuration>
```
I restore one nuget package from the NugetFeed folder as you can see above and then most from nuget.org.

In VSTS i have these settings:
![image](https://user-images.githubusercontent.com/3976137/30993010-66f48222-a472-11e7-9544-6249b83bb8e3.png)

When i start the build, it creates a temporary nuget.config file in `_work/3/Nuget/` and it then tries to locate the folder `NugetFeed` which is found at `_work/3/s/NugetFeed`.

Copying the NugetFeed folder in `_work/3/Nuget/` solves the issues. 
Otherwise you end up with error message from nuget saying it cannot find a package (that exists in nuget.org) from the folder `_work/3/s/NugetFeed`

```
Failed to retrieve information about 'xunit' from remote source 'C:\agent\_work\3\Nuget\NugetFeed'.
NuGet.Protocol.Core.Types.FatalProtocolException: Failed to retrieve information about 'xunit' from remote source 'C:\agent\_work\3\Nuget\NugetFeed'.

```

**Comment by pspill** [comment]
Thanks for the detailed report @Jonathan34. As you noted, this bug is a side effect of the fact that this task creates a temporary nuget.config in order to inject credentials. Glad to see that you found a workaround.

I copied this into our backlog, and we will work on a change that will alleviate this kind of issue by bypassing the need to create temporary config files.

**Comment by pspill** [comment]
Copied to backlog, will address in a future release.

**Comment by Jonathan34** [comment]
How can i track this issue if it is copied in a backlog somewhere and fixed some day?
sorry but i d rather keep the bug opened until fixed.

**Comment by bryanmacfarlane** [comment]
@Jonathan34 - unfortunately, the backlogs are not OSS.  Forwarding this for feedback however.

**Comment by bryanmacfarlane** [comment]
Also labelling as an enhancement.  If it's work that's on the horizon, we sometimes keep open as an enhancement.    However, this seems like an issue.  Is it really feature work to net core 2 works with a local feed?

@pspill ?

**Comment by Jonathan34** [comment]
Local feeds are supported in .Net Core 2 but not through the VSTS CI/CD.
It took time for VSTS to step up and support .net core 2, apparently still a bit lacking although i admit it's nearly there!

We could argue this to be a enhancement or a bug but it seems like a side effect of a current buggy implementation that implies a non-working behavior for the end user with non productive time and limited integration.
Anyway, I trust you will all fix this small annoyance quickly :)

**Comment by Jonathan34** [comment]
Also this is quite dangerous since if someone updates the package un the local folder in the VCS (git) without updating the agent, then we end up deploying something outdated and potentially buggy...
Any update on a resolution for this?

**Comment by Jonathan34** [comment]
is that fixed/implemented now?

**Comment by Psijic** [comment]
Hello, I have a problem to build a project. Is it okay?
`Failed to retrieve information about 'Microsoft.Build.Tasks.Core' from remote source 'http://cis.stagehosts.com/guestAuth/app/nuget/v1/FeedService.svc/FindPackagesById()?id='Microsoft.Build.Tasks.Core''.
  404 ()`

**Comment by parid0kht** [comment]
I had this problem and resolved it by updating Nuget version using bellow task in `azure-pipelines.yml`

```
steps:
  - task: NuGetToolInstaller@1
    displayName: "Install specific version of Nuget"
    inputs:
      versionSpec: '5.11.0'
```
