### ISSUE TITLE
Task for email notifications (i.e. failed build or successful build)

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/vsts-tasks#5521]
Hello,
I am checking to see if there are any tasks that can be used at the end of a build for build success/build failure.  The built in notifications for VSTS do not allow customizaton for the email subject which isn't too good if you have  a lot of build definitions and deployments.

Any ideas what task could be used for this?

Thanks

**Comment by vbossica** [comment]
Have you tried the [Send Email task](https://marketplace.visualstudio.com/items?itemName=rvo.SendEmailTask) from the marketplace?

You can then customize the subject/content with the various [build variables](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?tabs=batch)

**Comment by bryanmacfarlane** [comment]
https://marketplace.visualstudio.com/search?term=email&target=VSTS&category=All%20categories&sortBy=Relevance

**Comment by vijayma** [comment]
While we cannot support customization at this point, we are working on refreshing the notification emails with more info both in the title and in the content. With the new title you should be able to filter the emails better. ETA: Next 2-3 months.
