### ISSUE TITLE
The Azure CLI task inline script has a 500 character max length

### ISSUE THREAD

**Issue by leidegre** [Microsoft/vsts-tasks#5540]
What possible reason could there be for this!? It just gets in the way. I would very much like this arbitrary limit to be removed. I managed to save and run the script by simply editing the HTML using the browser dev tools why would you do this to me?

**Comment by leidegre** [comment]
If you want to accept this change I created a pull request with a more reasonable limit https://github.com/Microsoft/vsts-tasks/pull/5541

**Comment by sachinma** [comment]
Thanks for the change. I have merged it.
