### ISSUE TITLE
Could not load file or assembly 'Microsoft.VisualStudio.QualityTools.CodedUITestFramework

### ISSUE THREAD

**Issue by LarsOleKMD** [Microsoft/vsts-tasks#5542]
WIN Server 2016 , TFS 2017 UP 1  Agent 1.120.2 
VS2017 15.3.3  install on the build server and test.server is the samne server 

If i open the Ui test projekt on the server in VS2017 i can run the test bye VS2017 

run the test bye agent vNext then say cannot  load 'Microsoft.VisualStudio.QualityTools.CodedUITestFramework

The test i open notpad write som think and close without save

DistributedTests: Test Run with Id 81 Queued
DistributedTests: Test run '81' is in 'InProgress' state.
DistributedTests: Test run '81' is in 'InProgress' state.
DistributedTests: Test run '81' is in 'InProgress' state.
DistributedTests: Test run '81' is in 'InProgress' state.
DistributedTests: Test run '81' is in 'InProgress' state.
DistributedTests: Test run '81' is in 'Aborted' state.
DistributedTests: Test run is aborted. Logging details of the run logs.
Processed: ##vso[task.logissue type=warning]DistributedTests: Test run is aborted. Logging details of the run logs.
DistributedTests: New test run created.
Processed: ##vso[task.logissue type=warning]DistributedTests: New test run created.
Test Run queued for Project Collection Build Service (TEAM FOUNDATION).

DistributedTests: Test discovery started.
Processed: ##vso[task.logissue type=warning]DistributedTests: Test discovery started.
DistributedTests: Test Run Discovery Aborted . Test run id : 81
Processed: ##vso[task.logissue type=warning]DistributedTests: Test Run Discovery Aborted . Test run id : 81
DistributedTests: UnExpected error occured during test execution. Try again.
Processed: ##vso[task.logissue type=warning]DistributedTests: UnExpected error occured during test execution. Try again.
DistributedTests: Error : MSTestAdapter failed to discover tests in class 'CodedUITestProject3.CodedUITest1' of assembly 'C:\Deploy\CodedUITestProject3.dll'. Reason Could not load file or assembly 'Microsoft.VisualStudio.QualityTools.CodedUITestFramework, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..
Processed: ##vso[task.logissue type=warning]DistributedTests: Error : MSTestAdapter failed to discover tests in class 'CodedUITestProject3.CodedUITest1' of assembly 'C:\Deploy\CodedUITestProject3.dll'. Reason Could not load file or assembly 'Microsoft.VisualStudio.QualityTools.CodedUITestFramework, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified..

DistributedTests: Test run aborted. Test run id: 81
Processed: ##vso[task.logissue type=warning]DistributedTests: Test run aborted. Test run id: 81
System.Exception: The test run was aborted, failing the task.
Processed: ##vso[task.logissue type=error;]System.Exception: The test run was aborted, failing the task.
DistributedTests: Deleted test settings with id : 18
PowerShell script completed with 1 errors.

**Comment by abhishkk** [comment]
Can you share following logs to devops_tools@microsoft.com?
1. Add/set 'system.debug' variable to true in your build/release definition and share the logs folder.
2. For checking assembly load failure, share fusion logs:
    -	Open developer command prompt from Start menu
    -	Run fuslogvw command to open fusion log viewer UI.
    -	In fusion log viewer UI, Settings > Check ‘log bind failures to disk’. Also enable ‘custom log path’ and give any path where fusion logs will be saved.

**Comment by LarsOleKMD** [comment]
Hi abhishkk i cannot send a mail to devops_tools@microsoft.com the mail come back ?

**Comment by abhishkk** [comment]
Hi Lars, We have received the mail. I will look into the logs and reach back. Thanks.

**Comment by abhishkk** [comment]
There are few issues with your run. Please follow below suggestions for your issue:
1. Build Agent and Test Agent on same machine is not a supported scenario. Please use separate machines for build agent and test agent. You will/might run into many issues if same machine is used for both.
2. Test Agent and Visual Studio installed on same machine is not a supported scenario. Ideally in your build agent machine, only Visual Studio should be installed and on your test agent machine, only Test Agent should be installed. 

**Building tests in VS 2015 and running it in TA 2015 / TA 2017**: Project build in VS 2015 can be ran in both TA 2015 and TA 2017. Please follow below steps:
1. Create the test in VS 2015 (Your current project is build in VS 2017)
2. Install VS 2015 (only) on build agent. Build task will build project for VS 2015. (Currently build task was building project for VS 2017 as both VS 2015 and VS 2017 were installed in build agent). 
2.  Deploy test agent task (v1 version) supports only TA 2015. But Deploy test agent task v2 version (available from TFS 2017 Update 3) supports both TA 2015 and TA 2017.
3. Run functional tests task will run tests in Test agent chosen in Deploy test agent task.

**Building test in VS 2017 and running it in TA 2017**: Project build in VS 2017 can be ran in TA 2017 only. Please follow below steps:
1. Create the test in VS 2017.
2. Install VS 2017 (only) on build agent. Build task will build project for VS 2017.
3. Update TFS to update 3. Change Deploy test agent task version to v2. Select test agent version value as VS 2017.
4. Run functional test task will run tests in TA 2017.

**Comment by vimegh** [comment]
@ISAF87 I hope steps provided above by @abhishkk helped. Closing the issue for now as there is no response, please feel free to reopen if you are still facing the issue. Thanks.

**Comment by LarsOleKMD** [comment]
I am coming back for holiday...
I have test with TFS 2017 Up1 and separate build server where VS2017 is installed.  Create a new windows 10 machine and I have install nothing on the windows 10 machine
Is the same issue, I am waiting for the TFS2017 UP 3 is released, so I have the right set-up
