### ISSUE TITLE
git submodule summary error

### ISSUE THREAD

**Issue by antispinward** [Microsoft/vsts-tasks#5551]
Hello,

I am writing a powershell script which performs a number of git commands at the end of a build.

When running:
`git submodule summary $submoduleName`
I am getting the following error:
`/mingw64/libexec/git-core/git-sh-setup: line 179: egrep: command not found`

This is on v2.117.2
I have so far found a work around to set this variable:
`system.prefergitfrompath = true`

**Comment by bryanmacfarlane** [comment]
Doesn't appear to be an issue with any of the tasks in this repo.
