### ISSUE TITLE
Deploy Azure App Service deploys WAR to root under Linux and is not visible by default

### ISSUE THREAD

**Issue by pjquirk** [Microsoft/vsts-tasks#5559]
This may be by design or I don't understand the Azure App Service well enough, but the out-of-the-box experience isn't great.

When running on a Linux agent, the 'Deploy Azure App Service' task explodes the WAR to `/wwwroot` and it is not navigable by default.  Going to the app service's root (`http://<azurewebsite>/`) still shows the welcome page, which is served out of `/wwwroot/webapps/ROOT`.

Interestingly, when running on a Windows agent, this task _copies_ the WAR to `/wwwroot/webapps`, and you can navigate to it at `http://<azurewebsite>/<warfilename>`.

To me, it's strange that the task behaves very differently depending on the OS of the agent, but why would the Windows scenario work out of the box but the Linux one does not?

**Comment by Ajay-MS** [comment]
@pjquirk 

Deployment of java app is currently not supported with Linux based agent. We are working on it and will fix it soon.

**Comment by Ajay-MS** [comment]
@pjquirk 

We have fixed this issue in master. 
PR - https://github.com/Microsoft/vsts-tasks/pull/5628

Will be deployed with the deployment of next release.
