### ISSUE TITLE
IIS Web Application Management failed to work for non admin user accounts

### ISSUE THREAD

**Issue by sujitks** [Microsoft/vsts-tasks#5567]
Hi There,

**IIS Web Application management task fails** to create or update the application pool on the deployment target if vsts agent running on the deployment target are not running with the administrator account.

Could you please suggest what permission user account should have which is used for running the vsts agent?

**Comment by pjquirk** [comment]
That task ultimately uses [appcmd.exe](https://technet.microsoft.com/en-us/library/jj635852.aspx) to perform its work.  The help for that application states:

> Appcmd.exe resides in the %windir%\system32\inetsrv directory, which is available only to the Administrator account or to users who are members of the Administrators group on the computer.

So, the user account used to run the agent for this particular task should belong to the administrator's group.

**Comment by sujitks** [comment]
Can an option be added in the task to allow running it in another elevated account context please? A deployment agent running in administrator account does not make any sense. Does it?

Thanks

**Comment by Ajay-MS** [comment]
@sujitks 

For IIS Web Application Management task, Administrator privilege is required as Appcmd.exe resides in the %windir%\system32\inetsrv directory. On this directory users in Administrator group or "NT AUTHORITY/SYSTEM" have modify permission. Adding a non administrator user on this directly is not suggested to prevent any modification to system files by non-admin user.

**Comment by RoopeshNair** [comment]
As mentioned above in "pjquirk commented on Oct 6, 2017 ", the appcmd.exe is available only for administrators group
