### ISSUE TITLE
Show branch information for build artifacts when creating a release

### ISSUE THREAD

**Issue by KZeronimo** [Microsoft/vsts-tasks#5568]
## Issue
When creating a release the artifacts from the associated build do not show the branch from which they were build.  You only know after the release is queued which branch the artifacts were built from and if the release artifact filters will be satisfied

## Proposal
In addition to showing the build number of the artifact- also show the branch from which it was built

<img width="668" alt="screen shot 2017-10-05 at 4 19 00 pm" src="https://user-images.githubusercontent.com/21271446/31252970-fcaa2e42-a9f0-11e7-985c-7eea19734ed7.png">

**Comment by pjquirk** [comment]
This is a feature request for the VSTS/TFS product itself, not one of its tasks.  Please use [UserVoice](https://visualstudio.uservoice.com/forums/330519-team-services) to submit feature requests for the product, as this repository is only for certain tasks.
