### ISSUE TITLE
Adding support for collecting results in Jenkins pipeline job

### ISSUE THREAD

**Issue by to-kr** [Microsoft/vsts-tasks#5570]
I cannot find a way how to get "team-results" when using JenkinsQueueJob with Jenkins pipeline job. There is no equivalent for "Collect results for TFS/Team Services" in pipelines.

**Comment by pjquirk** [comment]
Unfortunately you're right, there is no way to get the results when using this task to queue pipeline jobs.

This issue has [been reported against the Jenkins TFS plugin](https://issues.jenkins-ci.org/browse/JENKINS-44213).  Any changes to that plugin will be reflected in the task here.

**Comment by to-kr** [comment]
I have finally found the answer. I can use the **General Build Step**
```
step([$class: 'TeamCollectResultsPostBuildAction', 
    requestedResults: [
        [includes: 'output/**/TEST-*.xml', teamResultType: 'JUNIT']
    ]
])
```
