### ISSUE TITLE
IIS Web Deploy - JSON replacement for non .json files

### ISSUE THREAD

**Issue by thurfir** [Microsoft/vsts-tasks#5573]
Hello,

We would like to apply JSON replacements from the IIS Web Deploy task on some of our configuration files. However as these files may contain sensible informations we save them as .json.config files to prevent them from being exposed by IIS.

As the IIS Web Deploy task use the file type to detect if the file is a JSON or not, the replace is currently forbidden:

jsonvariablesubstitutionutility.ts (77)
`            if(path.extname(file) !== '.json') {
                throw new Error(tl.loc('JSONvariablesubstitutioncanonlybeappliedforJSONfiles'));
}`

Is there a workaround? Thanks.

**Comment by Ajay-MS** [comment]
@thurfir 

As you also know we are here strongly checking with extension '.json' only. 

Only possible workarounds are 
1. To change the file to .json extension.
                  _But this is a restriction from your end because you don't want to expose it by IIS_. 
2. To customize your local task to remove this check to get you unblocked on this issue. 

I will check if we could support '.json.config' files too so that you will not face the issue in future.

**Comment by thurfir** [comment]
@Ajay-MS Being able to use .json.config (or other .json.* file formats) would be much appreciated, thank you.
On the meanwhile we might change the file format then perform a file rename to avoid this issue, creating and maintaining custom VSTS tasks is not possible for us right now.

**Comment by Ajay-MS** [comment]
@thurfir 

Thanks for your  kind cooperation. We will fix issue soon and will be available to you with next deployment.

**Comment by Ajay-MS** [comment]
@thurfir 

We have removed the check for extension of JSON based files. 
PR - https://github.com/Microsoft/vsts-tasks/pull/5611 

Closing this issue.
