### ISSUE TITLE
Azure SQL Database Deployment Task fails as it cannot locate SqlPackage.exe

### ISSUE THREAD

**Issue by SunnyOswal** [Microsoft/vsts-tasks#5574]
We have installed SSDT nuget package **(Microsoft.data.tools.msbuild)** on vsts agent. But in our VSTS release definition , Azure SQL Database Deployment Task fails as it cannot locate SqlPackage.exe

**Error:**
Unable to find the location of Dac Framework (SqlPackage.exe) from registry on machine.

As part of installation of nuget package,we have already set environment variables such as **SQLDBExtensionsRefPath** , **SSDTPath** , **SqlPackage** pointing to SqlPackage folder .
I have checked the **FindSqlPackagePath.ps1** script and it looks for SqlPackage in registries.

 Do i need to explicitly add/update registry ? If yes,which registry key should i update ?

**Comment by pjquirk** [comment]
The SqlPackage.exe distributed with the Nuget package does not advertise its existence to the system in any way, so there's no easy way to determine if it's there.

Please read [this section of the readme](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/SqlAzureDacpacDeployment#automation-agent) for this task for a number of supported ways to install SqlPackage.exe.

**Comment by SunnyOswal** [comment]
Hey Patrick,
Already went through the prerequisites. Was just wondering , Could we add this as a feature request i.e to support sql deployment task where agents have SSDT nuget package installed ?

Use case:
We want to use docker windows containers as VSTS agents in our release definitions and want containers to be as light as possible.

Thanks,
Sunny Oswal

**Comment by pjquirk** [comment]
In that case, can you create a new issue for that? The title of this issue does not reflect what you just asked and I don't want it to get lost.

**Comment by SunnyOswal** [comment]
Sure. Posted Feature request: https://github.com/Microsoft/vsts-tasks/issues/5575
