### ISSUE TITLE
How to use the common module in custom tasks?

### ISSUE THREAD

**Issue by BiribiriJaNai** [Microsoft/vsts-tasks#5577]
Trying to use secure files in a custom task, I found [this link](https://docs.microsoft.com/en-us/vsts/build-release/concepts/library/secure-files). 
Exploring the source code of this repo, I also found some examples, like the [InstallAppleProvisioningProfile ](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/InstallAppleProvisioningProfile/preinstallprovprofile.ts)task.

Are these modules (**securefiles-common**, **npm-common**...) reusable in a custom task?
If so, how?

**Comment by ericsciple** [comment]
@BiribiriJaNai Nope, they are internal libraries for tasks in this repo.

**Comment by TechnologyAnimal** [comment]
I came here looking for the same answer.  If it's not possible, why is it listed on docs.microsoft.com?  I'd really love to find an example in a custom task using powershell...

https://docs.microsoft.com/en-us/vsts/build-release/concepts/library/secure-files
https://docs.microsoft.com/en-us/vsts/build-release/tasks/utility/install-apple-provisioning-profile
https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/InstallAppleProvisioningProfile

**Comment by nexsodev** [comment]
Download the source code, compile, install packages and create a tar file.
Or just [click here](https://drive.google.com/open?id=1aJypGRMLEa-hyr43filHhloCsyyh3VMX). I already done this for you.
Simple install the tar:
`npm i ./securefiles-common.tar`
