### ISSUE TITLE
Build Test Hub reports incorrect test results.

### ISSUE THREAD

**Issue by skushubar** [Microsoft/vsts-tasks#5589]
Our CI build includes a Visual Studio Test (version 2) task.  When looking at the logs for the task after a build it shows:

```
2017-10-09T11:48:20.3576503Z Total tests: 1102. Passed: 1102. Failed: 0. Skipped: 0.
2017-10-09T11:48:20.3576503Z Test Run Successful.
```
However the Test Results section on the build summary shows some spurious number of failed tests.  The Tests Hub  shows the same number of tests as failed, but if you look at an individual "failed" test there is no error message or stack trace that you typically find with a failed test.

Most builds incorrectly report the same three tests as failed - but occasionally it reports some other tests as failed.

**Comment by abhishkk** [comment]
@skushubar Can you please provide following information to  to devops_tools@microsoft.com to debug this issue?
1. Set 'system.debug' variable to true in your build definition and share the logs zip.
2. Share the trx attachment file(s).
3. Screen shot of test results section.

Please share above information for both scenarios (once when three tests are shown as failed and once when all tests are shown as failed)

**Comment by skushubar** [comment]
@abhishkk  Requested files have been sent.  To clarify: there is really only one scenario in that "some" tests that pass are shown as failed in the test hub.  I was just making a point that it is not always the same set of tests.

**Comment by abhishkk** [comment]
@skushubar Thanks for the logs. Your tests passed successfully. After test run, we create a trx file in which we add result info of every test (including each test specific attachment). It seems for the test which is shown as failed in build summary, platform was unable to access the test result attachment path and thus test result state was updated as Error in trx.
Build summary view is dependent on trx file and thus you are seeing test result as failed.

For getting more info on this issue, can you please do following:
1. After running the tests where some tests fails, run the tests again locally from console. For doing so, run the command (which is present in logs) from same machine where tests failed. For reference, in current provided logs, command is present at line 17992 of 12_Test It!.txt. Share the result status, trx file and diag file (you can check the diag file path in command itself)
2. Open trx file of Step 1 in VS. If all tests are passed in trx, then repeat step 1 multiple times (say 3-4 times). But if you are seeing some tests with result status as 'Error' in trx, then no need to repeat step 1.

Please let know in case of any clarifications.

**Comment by skushubar** [comment]
@abhishkk  Files have been sent.

**Comment by abhishkk** [comment]
This issue was moved to Microsoft/vstest#1271

**Comment by abhishkk** [comment]
Moved issue to test platform team. Issue is related to platform as tests ran locally from console(as asked in step 1 above) is also failing.
