### ISSUE TITLE
The nuget task should reference $(System.ArtifactStagingDirectory) instead of $(Build.ArtifactStagingDirectory)

### ISSUE THREAD

**Issue by onetrueerror** [Microsoft/vsts-tasks#5594]
## Troubleshooting

When creating a new nuget task in **_Release manager_**, it incorrectly references `Build.` instead of `System.`.

![bild](https://user-images.githubusercontent.com/6445000/31352346-b97447d4-ad2e-11e7-93b1-9f752214284b.png)

This is tricky since the task will not produce an error if no nuget packages is found. So if you are not aware of what the output should be, you might assume that the package got pushed correctly.

Instead, the task should use `$(System.ArtifactDirectory)/*.nupkg` when the step is created, as defined in the predefined variables:

![bild](https://user-images.githubusercontent.com/6445000/31352421-fffe79fe-ad2e-11e7-9175-ea5759705f12.png)

## Environment

* VSTS
* nuget task, version 2.0

**Comment by keithrob** [comment]
Thanks for the suggestion.  We may address this in a future release.
