### ISSUE TITLE
Variable substitution for ApplicationSettings not working

### ISSUE THREAD

**Issue by shaneholder** [Microsoft/vsts-tasks#5595]
It seems that while appSettings are correctly substituted, applicationSettings are not.

Her in xmlvariablesubstituionutility.ts the code is iterating through a set of tags.

https://github.com/Microsoft/vsts-tasks/blob/a698fb593f58fe733df94aa166a99ed3ea6dda5b/Tasks/Common/webdeployment-common/xmlvariablesubstitutionutility.ts#L84

There appears to be special case code for configSections and connectionStrings
https://github.com/Microsoft/vsts-tasks/blob/a698fb593f58fe733df94aa166a99ed3ea6dda5b/Tasks/Common/webdeployment-common/xmlvariablesubstitutionutility.ts#L125

and the rest of the code goes to updateXmlNodeAttribute
https://github.com/Microsoft/vsts-tasks/blob/a698fb593f58fe733df94aa166a99ed3ea6dda5b/Tasks/Common/webdeployment-common/xmlvariablesubstitutionutility.ts#L178

It looks like updateXmlNodeAttribute is really designed for appSettings structures as:
```
<appSettings>
<add key="blat" value="blart"/>
</appSettings>
```
and not applicationSettings structures which look like:
```
<applicationSettings>
  <myCustomSection>
   <setting name="blat" serializeAs="String">
      <value>blart</value>
   </setting>
  </myCustomSection>
</applicationSettings>
```

**Comment by Ajay-MS** [comment]
Currently, two formats are being supported for variable substitution in all other section except connection strings. 

1.  In key="<KEY_NAME"> value="<KEY_VALUE>" format
 ```
       <appSettings>
                 <add key="blat" value="blart"/>
       </appSettings>
```

2.  In <KEY_NAME>=<KEY_VALUE> format 
 ```
       <appSettings>
                 <setting blat="blart">
                  </setting>
       </appSettings>
```

As already mentioned by you, if the value of key exists as a child that format is not being supported.  I am marking this as the enhancement.  Please update me if you can change your application settings as the 2nd format I have specified so that you can be unblocked.

**Comment by shaneholder** [comment]
I am unable to locate any documentation on the 2nd option suggested, can
you point me to an example so I can better understand this format?

**Comment by Ajay-MS** [comment]
@shaneholder 

Refer following documentation 
[xml-variable-substitution](https://docs.microsoft.com/en-us/vsts/build-release/tasks/transforms-variable-substitution#xml-variable-substitution )

Variable "invariantName" in above documentation is according to 2nd format.

**Comment by nyn3x** [comment]
@Ajay-MS: I encountered the same challenge. I cannot change the format of my config, as this has been gerenated by Visual Studio 😉  as part of strong-type property-settings.

I would really love to keep those strong typed settings within my code - and not swith to appSettings, which would be read using the ConfigurationManager.

**Comment by shaneholder** [comment]
Ok, so I ran my tests again, same results.

I am running on Windows 10:

```
> node -v; npm -v
v4.8.6
3.10.10

> node make.js build --task AzureRmWebAppDeployment; node make.js test --task AzureRmWebAppDeployment

```

I thought the best thing would be to create a branch on my repository to illustrate the error.  Please see:

https://github.com/shaneholder/vsts-tasks/tree/5595_evidence
Below is the Trace file from the run notice the line about configSections not being found.

I also created a PR against my own repository to try and give a cleaner view to the changes:

https://github.com/shaneholder/vsts-tasks/pull/1

```
TRACE FILE: C:\d\github\vsts-tasks\_build\Tasks\AzureRmWebAppDeployment\node_modules\webdeployment-common\Tests\L1XmlVarSub.js.log
##vso[task.debug]agent.workFolder=undefined
##vso[task.debug]loading inputs and endpoints
##vso[task.debug]loaded 0
##vso[task.debug]Initiated variable substitution in config file : C:\d\github\vsts-tasks\_build\Tasks\AzureRmWebAppDeployment\node_modules\webdeployment-common\Tests\L1XmlVarSub\Web_test.config
##vso[task.debug]Detecting file encoding using BOM
##vso[task.debug]Unable to find node with tag 'applicationSettings' in provided xml file.
##vso[task.debug]Processing substitution for xml node : appSettings
##vso[task.debug]Updating value for key=webpages:Versionwith token_value: CONFIG_FILE_SETTINGS_TOKEN(webpages:Version)
##vso[task.debug]Processing substitution for xml node : connectionStrings
##vso[task.debug]Detecting file encoding using BOM
##vso[task.debug]Unable to detect File encoding using BOM
##vso[task.debug]Detecting file encoding without BOM
##vso[task.debug]Parameters file - Replacing value for name: DefaultConnection-Web.config Connection String with : PARAM_FILE_REPLACE_TOKEN(DefaultConnection-Web.config Connection String)
##vso[task.debug]Parameters file - Replacing value for temp_name: PARAM_FILE_REPLACE_TOKEN(DefaultConnection-Web.config Connection String)
##vso[task.debug]Parameter file C:\d\github\vsts-tasks\_build\Tasks\AzureRmWebAppDeployment\node_modules\webdeployment-common\Tests\L1XmlVarSub\parameters_test.xml updated.
##vso[task.debug]Substituting connectionString value for name=DefaultConnection with token_value: CONFIG_FILE_CONN_STRING_TOKEN(DefaultConnection)
##vso[task.debug]Substituting connectionString value for name=OtherDefaultConnection with token_value: CONFIG_FILE_CONN_STRING_TOKEN(OtherDefaultConnection)
##vso[task.debug]Substituting connectionString value for name=ParameterConnection with token_value: CONFIG_FILE_CONN_STRING_TOKEN(ParameterConnection)
##vso[task.debug]Substituting connectionString value for connectionString=NoConnectionName with token_value: CONFIG_FILE_CONN_STRING_TOKEN(connectionString)

##vso[task.debug]Unable to find node with tag 'configSections' in provided xml file.

##vso[task.debug]Substituting original value in place of temp_name: CONFIG_FILE_SETTINGS_TOKEN(webpages:Version)
##vso[task.debug]Substituting original value in place of temp_name: CONFIG_FILE_CONN_STRING_TOKEN(DefaultConnection)
##vso[task.debug]Substituting original value in place of temp_name: CONFIG_FILE_CONN_STRING_TOKEN(OtherDefaultConnection)
##vso[task.debug]Substituting original value in place of temp_name: CONFIG_FILE_CONN_STRING_TOKEN(ParameterConnection)
##vso[task.debug]Substituting original value in place of temp_name: CONFIG_FILE_CONN_STRING_TOKEN(connectionString)
##vso[task.debug]Config file C:\d\github\vsts-tasks\_build\Tasks\AzureRmWebAppDeployment\node_modules\webdeployment-common\Tests\L1XmlVarSub\Web_test.config updated.
##vso[task.debug]Initiated variable substitution in config file : C:\d\github\vsts-tasks\_build\Tasks\AzureRmWebAppDeployment\node_modules\webdeployment-common\Tests\L1XmlVarSub\Web_test.Debug.config
##vso[task.debug]Detecting file encoding using BOM
##vso[task.debug]Unable to find node with tag 'applicationSettings' in provided xml file.
##vso[task.debug]Unable to find node with tag 'appSettings' in provided xml file.
##vso[task.debug]Processing substitution for xml node : connectionStrings
##vso[task.debug]No substitution variables found for parameters.xml
##vso[task.debug]Substituting connectionString value for name=MyDB with token_value: CONFIG_FILE_CONN_STRING_TOKEN(MyDB)
##vso[task.debug]Unable to find node with tag 'configSections' in provided xml file.
##vso[task.debug]Substituting original value in place of temp_name: CONFIG_FILE_CONN_STRING_TOKEN(MyDB)
##vso[task.debug]Config file C:\d\github\vsts-tasks\_build\Tasks\AzureRmWebAppDeployment\node_modules\webdeployment-common\Tests\L1XmlVarSub\Web_test.Debug.config updated.
```

Also note lines:

https://github.com/Microsoft/vsts-tasks/blob/6c393dee733b813bc6c3f350f8eb5fd68abf4eae/Tasks/Common/webdeployment-common/xmlvariablesubstitutionutility.ts#L128-L132

are the lines for connectionStrings and it is calling substituteValueinParameterFile()

which in turns calls:

https://github.com/Microsoft/vsts-tasks/blob/6c393dee733b813bc6c3f350f8eb5fd68abf4eae/Tasks/Common/webdeployment-common/xmlvariablesubstitutionutility.ts#L48

Which I believe is the crux of the problem.  I hope this illustrates the issues I am having and the PR I generated https://github.com/Microsoft/vsts-tasks/pull/5893 I believe address this issue.

Thank you for your time.
Regards,
Shane Holder

**Comment by Ajay-MS** [comment]
Yes, you are right here I have figured out the issue.  PR that you have shared will surely solve this issue.  I will validate your changes and will take your changes. 

**Problem**
Since xmlDomLookUpTable  is a global variable and invoking initialize DOM is updating it's value. 
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Common/webdeployment-common/ltxdomutility.ts#L5

So, this issue will be faced if you have a package with parameters.xml and you are trying to substitute in config section. 

@vincentdass 
Can you please review this PR -  https://github.com/Microsoft/vsts-tasks/pull/5893

**Comment by shaneholder** [comment]
Thank you for reviewing my comments and code.  I saw your comment about getChildren on the XmlDom and it still does not return nested children nodes.  I encountered this in the PR for #5595 I am working on, however it looks like getChildrenByFilter will do a recursive search for nodes, although not an O(1) operation.  If you want an O(1) you might want to continue using lxdomutility but write it so that it's an instance and not a singleton.  If you determine that using getChildrenByFilter will work then I can have a PR for the settings issue I reported earlier.  Settings does not use the NameValueSectionHandler, but rather uses ClientSettingsSection and the structure is a bit more complex, so I believe one needs to inspect the type on the <section> element and make a decision of which XML replacement algorithm to use.

**Comment by Ajay-MS** [comment]
@shaneholder 

I am preferring O(1) operation in order to make substitution operation fast. 

I have raised a PR . You can verify your tests on it. 
https://github.com/Microsoft/vsts-tasks/pull/5912

**Comment by shaneholder** [comment]
Just as an FYI PR #5912 resolves #5892  but not this issue.  The comments for #5892 ended up side tracked here.  This issue is around being able to use .Net applicationSettings which are not attribute based but rather element based.  They use the type of System.Configuration.ClientSettingsSection and have the following structure:

```
<configSections>
  <section name="myCustomSection" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
</configSections>

<myCustomSection>
   <setting name="blat" serializeAs="String">
      <value>blart</value>
   </setting>
</myCustomSection>
```

I believe that looking at the type attribute on the section and determining which xml replacement process might be a reasonable solution.

**Comment by shaneholder** [comment]
Now that #5893 has been fixed, what are your thoughts on fixing this issue?  I would rather not rewrite my code to use appSettings when strongly typed choices are available.

**Comment by Ajay-MS** [comment]
@shaneholder 

I am completely with you regarding this. We will soon add soon support for variable substitution in this format.

**Comment by Ajay-MS** [comment]
@shaneholder 

Here's the PR for supporting above mentioned format in XML variable substitution - https://github.com/Microsoft/vsts-tasks/pull/6024

You can also review and validate it.

**Comment by Ajay-MS** [comment]
Closing this issue as we have fixed it in master. It will be available with next deployment approx 4 weeks from now.

**Comment by shaneholder** [comment]
Is there some indication that a fix has been deployed?  And the ETA of 4 weeks, is that when it should be available to me as a user or is that a Ring 0 deployment estimate?

**Comment by Ajay-MS** [comment]
@shaneholder 
ETA that I have shared with you is approx ETA of deployment to all Rings. But this release has been skipped.  So I will notify you as soon as deployment of next release will start.

**Comment by christopherbauer** [comment]
@Ajay-MS When is this going out to the rest of us? I have an entire build pipeline that can't function because we are using the strongly-typed settings object.

**Comment by Ajay-MS** [comment]
We have skipped deployment of one release (M128)  in between. Deployment of release M129 has been started and will be available in next 2 weeks to almost all rings. 

 Though I will not recommend to run a pre release version. But for you info in case of it's blocking you below are the steps to achieve it. 

Deploying copy of task by changing Task Id
1. Clone vsts-tasks repo
2. Open task.json file of Azure App Service task and change task Id guid
3. Build task by running command - gulp build --task AzureRmWebAppDeployment
4. Deploy task using tfx cli => tfx build tasks upload --task-path  &lt;Path of task build&gt;

**Comment by christopherbauer** [comment]
@Ajay-MS Ok on your recommendation I will not run the prerelease. Until then I suppose we will run a copy-item for the web.config via a post deploy powershell script and make a note to followup on this release in 2 weeks. Thank you

**Comment by christopherbauer** [comment]
The account is under upclear, thanks Ajay.

**Comment by Ajay-MS** [comment]
@christopherbauer 

Changes have been deployed to all Rings. Please validate the changes to your account.

**Comment by shaneholder** [comment]
Success!!! THANK YOU SO MUCH!
