### ISSUE TITLE
Entering Tag Format Crashes App

### ISSUE THREAD

**Issue by martinfletcher** [Microsoft/vsts-tasks#5610]
Server: VSTS
Account: tigerbay.visualstudio.com
Project: SerenHR
Build Definition: CI-TEST-1-TAGSOURCE
Agent: Hosted VS2017
Issue:

When setting a tag format, entering '$(' causes the app to crash. Need to close browser tab/window as page not responsive.

Pasting the full tag format into the field works. Seems like some typeahead/intellisense functionality may be erroring.

No error logs are available as the app does not get to the point where errors are logs, this is a fatal error.

**Comment by MireilleHanna** [comment]
I could not reproduce the issue, have u tried this recently, is it still a problem?

**Comment by bryanmacfarlane** [comment]
This is also not an issue with the tasks in this repo.  If you are still having an issue, try at developer community
