### ISSUE TITLE
I would like to update the release "description" at runtime

### ISSUE THREAD

**Issue by don18** [Microsoft/vsts-tasks#5612]
## Context
I have a setup where a completed build, triggers a automatic creation of a release.
I would like to update the description value of the release

## Setup
- I have created a powershell task with the two following options but none of them work  
    - #Write-Output ("##vso[task.setvariable variable=Release.ReleaseDescription;]Testing it")    
    - #Write-Output ("##vso[task.setvariable variable=RELEASE_RELEASEDESCRIPTION]1.2.3.4")

## Result
- The release description is not updated. 

## Note
- If I manually create a release and fill in the description it works

**Comment by bansalaseem** [comment]
You should make a rest API call to update the release with a new description. Here is one such [link ](https://blogs.msdn.microsoft.com/aseemb/2016/05/23/how-to-update-release-level-variables-using-rm-rest-apis/) where we are updating the release with a new variable value and your code should be very similar. Please try it out and do let me know in case it does not work

**Comment by chandan-anjani** [comment]
Closing the thread as Aseem suggestion should help here. Feel free to re-open, if it doesn't help you.

**Comment by ahaleiii** [comment]
The link provided by @bansalaseem's [answer](https://github.com/Microsoft/azure-pipelines-tasks/issues/5612#issuecomment-338150893) helped me resolve an issue I was having:
https://developercommunity.visualstudio.com/content/problem/407703/update-release-api-returns-tf400898-an-internal-er.html

**Comment by gojanpaolo** [comment]
Here's what we have in Azure DevOps Server 2019 which uses [predefined variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops-2019&tabs=classic) and [release variables](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=azure-devops-2019&tabs=batch).

Note that you will need to [**Allow scripts to access the OAuth token **](https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops-2019&tabs=classic#systemaccesstoken).

```powershell
$appendReleaseDescription = "<your message>"

$releaseUri = "${env:System_CollectionUri}${env:System_TeamProject}/_apis/release/releases/${env:Release_ReleaseId}?api-version=5.0"

$token = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes(":$env:System_AccessToken"))
$headers = @{Authorization="Basic$token"}

$release = Invoke-RestMethod -Method Get -Headers $headers -Uri $releaseUri
$release.description = "$env:Release_ReleaseDescription | $appendReleaseDescription"

$release = $release | ConvertTo-Json -Depth 100
$release = [Text.Encoding]::UTF8.GetBytes($release)

Invoke-RestMethod -Method Put -ContentType "application/json" -Headers $headers -Uri $releaseUri -Body $release
```

Hope it helps! :)
