### ISSUE TITLE
PublishCodeCoverageResults & Merge reports

### ISSUE THREAD

**Issue by jycouet** [Microsoft/vsts-tasks#5617]
Hello, 

I have 2 phases in my build process, each phase has:
- Publish Test Results
- Publish Code Coverage

On the summary of the build, I have a nice overview of tests (with the 2 phases)
But on Code Coverage I get only 1 output of "Publish Code Coverage", 1 phase is missing.

How should I merge the 2 reports?
- file: cobertura-coverage.xml
- folder: lcov-report

Thank you for your help

**Comment by nigurr** [comment]
@jycouet, currently this feature is not supported. @PBoraMSFT will address the feature request.

**Comment by jycouet** [comment]
Hi @PBoraMSFT 
Do you have an idea of when you will be able to address this? :)
Thank you

**Comment by jycouet** [comment]
Sorry to come back to this... I would actually need this soon :)
I would like to know if you are working on it, or I should try to make a PR?

Let me know please @nigurr @PBoraMSFT 

Thank you

**Comment by PBoraMSFT** [comment]
@jycouet - This is on our backlog, but not scheduled yet.
You can workaround by writing a task to merge the code coverage files and then publish them using the publish code coverage task.
I am closing this issue here as we don't track backlog items here.
