### ISSUE TITLE
[Release Task] IIS Web App Deploy : XML Substitution unable to parse config with CDATA section

### ISSUE THREAD

**Issue by Kingclove** [Microsoft/vsts-tasks#5618]
## Issue Description
XML substitution does not work on Web.config's that have a CDATA section. During the xml substitution, it says it is unable to parse file. When I remove that section, it works fine. I am using version 0.0.24

### Error logs

` ##[debug]Unable to parse file : C:\vstsagent\A1\_work\r1\a\temp_web_package_24166107407845216\Content\C_C\agent\_work\1\s\SomeSite.Web.Api\obj\any cpu\release\Package\PackageTmp\Web.config
##[debug]Error: Incomplete document`

**Comment by Ajay-MS** [comment]
@Kingclove 

I have tried a web.config with CDATA field I didn't encounter unable to parse file issue. It seems that issue might be the content of CDATA. Can you please share complete debug logs at rm_customer_queries@microsoft.com  . Debug logs you can enable by adding release variable  system.debug with value true. Can you also share a snippet of your web.config which includes CDATA or it will be best if you could share complete web.config file.

**Comment by Ajay-MS** [comment]
@Kingclove 

Can you please confirm if you still facing this issue. If yes, please share debug logs.

**Comment by Ajay-MS** [comment]
Closing this issue assuming you are unblocked on this issue. Feel free to reopen in case you are still facing this issue.

**Comment by mkw1** [comment]
Here is my CDATA that causes the same problem for me (from [ELMAH](https://elmah.github.io/a/error-filtering/#using-jscript)). 

`<errorFilter>
      <test>
        <jscript>
          <expression>
            <![CDATA[
              // @assembly mscorlib
              // @assembly System.Web, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
              // @import System.IO
              // @import System.Web

              HttpStatusCode == 404
              || BaseException instanceof FileNotFoundException 
              || BaseException instanceof HttpRequestValidationException
              || Context.Request.UserAgent.match(/crawler/i)                      
              || Context.Request.ServerVariables['REMOTE_ADDR'] == '127.0.0.1' // IPv4 only
              ]]>
          </expression>
        </jscript>
      </test>
    </errorFilter>`

**Comment by asranja** [comment]
@mkw1 We are aware of this issue and have come up with a fix. The fix will be deployed soon.

**Comment by mkw1** [comment]
That's fantastic news. Thank you.
