### ISSUE TITLE
Azure Resource Group Deployment uses incorrect date for deployment name

### ISSUE THREAD

**Issue by kensykora** [Microsoft/vsts-tasks#5619]
## Environment

VSTS / Hosted Agent

## Issue Description

When deploying an ARM template using the "Azure Resource Group Deployment" task, it creates a deployment with a date where the month is incorrect.

For example, I deployed something today (October 11, 2017, 19:52) and it created a deployment with the name `azuredeploy-2017911-1952`

Expected: Correct Date (e.g., `azuredeploy-20171011-1952`) -- Also please use 2-digit formatted month and date numbers such that it can be alphabetized when sorted by name. (e.g., 20170911 not 2017911)

**Comment by sachinma** [comment]
This has been resolved and will be rolled out in the coming updates.
