### ISSUE TITLE
Deploy test agent task runs infinitely and does not exit. 

### ISSUE THREAD

**Issue by SanthoshYalamuri** [Microsoft/vsts-tasks#5624]
Hello,

Issue Description:

We have release definitions set up to execute Coded UI test cases, the test agent deployment task has run into an issue where in it the execution does not end until the deployment is manually cancelled, the message displayed on the terminal is as follows "DistributedTests: Task 'ConfigureTestAgent' on machine 'HOSTNAME:5985' is taking time. Please Wait" 

vsts_testagent.exe path is supplied from local path.
[21_Deploy TestAgent .log](https://github.com/Microsoft/vsts-tasks/files/1378393/21_Deploy.TestAgent.log)

Environment Details:
 TFS on-premises , TFS 2017 15.112.26307.0 (Tfs2017.Update1)
    
Build Agent : Private, OS: Windows Server 2012 R2, build agent version : 2.112.0

Test Agent : Private, OS: Windows 10

Test deployment task version: vstf_testagent.exe version version 14.0.23107.10

Please find the debug error log attached.

**Comment by dpksinghal** [comment]
Are you still seeing the issue? As there is another thread where you have reached the test execution. If yes, please share the agent logs with us.

Location - c:\dtalogs\dtaexecutionhost.exe.log

I see that you are using the older version of the DeployTestAgent task, we recommend to move to the latest version as we have done couple of improvements in the latest bits.

**Comment by dpksinghal** [comment]
Closing this issue due to no response. We have been in touch with Santosh over mails as well. Santosh, please let us know if you have any open query.

**Comment by SanthoshYalamuri** [comment]
Hello, 

The issue was resolved after both the build and test agents were configured with the same credentials. Thank you.

Regards,
Santhosh
