### ISSUE TITLE
Run Functional Tests task fails with error "The agent process was stopped while the test was running"

### ISSUE THREAD

**Issue by SanthoshYalamuri** [Microsoft/vsts-tasks#5625]
Hello,

Issue description:

The Coded UI test cases executed with Run functional tasks exit with the following error message: "The agent process was stopped while the test was running." These test cases were executed successfully before and the error description is not clear to investigate further and resolve the issue. Could you please share some information on the root cause and the probable solutions for the same. Thanks in advance.

Error message:
**##[error]System.Exception: Some tests in the test run did not pass, failing the task.**
[21_Deploy TestAgent .log](https://github.com/Microsoft/vsts-tasks/files/1378448/21_Deploy.TestAgent.log)
[22_Run Desktop client test cases.log](https://github.com/Microsoft/vsts-tasks/files/1378449/22_Run.Desktop.client.test.cases.log)

Environment Details:
TFS on-premises , TFS 2017 15.112.26307.0 (Tfs2017.Update1)

Build Agent : Private, OS: Windows Server 2012 R2, build agent version : 2.112.0

Test Agent : Private, OS: Windows 10

Test deployment task version: vstf_testagent.exe version version 14.0.23107.10

Please find the debug error log attached.

**Comment by dpksinghal** [comment]
The tests in the task have failed and hence the task is marked as failed.

_2017-10-12T06:31:18.0575470Z DistributedTests: Total Tests : 1, Passed Tests : 0
2017-10-12T06:31:28.0730432Z ##[error]System.Exception: Some tests in the test run did not pass, failing the task._

I would recommend to analyze the test failure. After the analysis, if you think it is a platform/environment issue, please share the DTA logs with us. You can get it from agent machine. Location - 'c:\dtalogs\dtaexecutionhost.exe.log'

**Comment by dpksinghal** [comment]
Closing this issue. We have been in touch with Santosh over mails as well. Santosh, please let us know if you are blocked here.

**Comment by SanthoshYalamuri** [comment]
Hello,

The issue was resolved after autologon tool was configured on the test agents.

Regards,
Santhosh
