### ISSUE TITLE
build task not picking up variables and service endpoint

### ISSUE THREAD

**Issue by tankthomas** [Microsoft/vsts-tasks#5632]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
VSTS

- Agent - Hosted or Private: 
    
 private with windows server 2012 R2

## Issue Description

build task not picking up variables and service endpoint

1. I have variables defined.
![image](https://user-images.githubusercontent.com/6215939/31517615-ba9055ae-af59-11e7-9236-715af2c27708.png)
2. in my build definition , i have that group included
![image](https://user-images.githubusercontent.com/6215939/31517673-deb5941c-af59-11e7-9612-745c92b15bc7.png)
3.and I apply  it to the build step
![image](https://user-images.githubusercontent.com/6215939/31517689-f106e94a-af59-11e7-9e50-0ea649f2eafd.png)
4.and it errors out
![image](https://user-images.githubusercontent.com/6215939/31517712-08fd7776-af5a-11e7-91cb-7c2c19b9b466.png)

everything works fine yesterday at least till 4pm yesterday. and also those service endpoint we have as following is not been applied to build task either: none of those two sets of account is been applied.
![image](https://user-images.githubusercontent.com/6215939/31517778-3ab2a480-af5a-11e7-9ddb-d60db34c426b.png)

not sure if it's more like an agent issue or vsts itself's issue

**Comment by rmarinho** [comment]
Same here..

**Comment by yaananth** [comment]
This should be already fixed. Let me if it isn't.

**Comment by rmarinho** [comment]
@yaananth yeah it's fixed today. what was the issue ?

**Comment by yaananth** [comment]
There was an incident on it, where variable groups are not being returned, we fixed it as soon as we found out about it. There was also another incident related to that, which needed more attention, the impact wasn't clear, because of these multiple incidents, I believe we couldn't get communication out while the fix is rolling out.

Sorry for the inconvenience caused.

**Comment by rmarinho** [comment]
Was this the right place to track this? since there was no feedback was hard to understand if i should raise a support ticket or not, do we have a better place inside DevDiv to talk about this?

**Comment by GitHubSriramB** [comment]
@tankthomas - 

We have identified issue due to which variable groups in Build weren't working as expected within tasks. You should not be running into issue with variable groups within Build anymore.

What was the issue you observed with service endpoints? Is this issue resolved now?
