### ISSUE TITLE
[Feature Request][Area:Release] Allow customization of pre-deployment approval and post-deployment approval to an environment, based on conditions.

### ISSUE THREAD

**Issue by lavanyasubbarayalu** [Microsoft/vsts-tasks#5642]
Release Definition: Allow customization of pre-deployment approval and post-deployment approval to an environment, based on conditions.This option will be useful to bring in gating mechanism in the release pipeline. 
Common conditions are : 
Integration/regression test pass % set with threshold value. If the test pass % is less, then pre-deployment approval should not be triggered, in the scenarios where pre-deployment approval is set as automatic. 
Other conditions are : 
1. Using code coverage % as gated metric 
2. Using Environment Availability/Readiness test results as gated metric, to enable pre-deployment approval.

**Comment by bansalaseem** [comment]
Thanks Lavanya for your suggestion and in case you have more suggestions, please keep sharing them. 

As mentioned [here ](https://docs.microsoft.com/en-us/vsts/release-notes/), we have a feature in our backlog called greenlighting with which you should be able to configure your deployment gates on an environment and those gates need to pass before deployment gets triggered on it. This feature is fairly high on our backlog which means that there is a decent probability that it will get done soon.

**Comment by shashban** [comment]
@lavanyasubbarayalu We're happy to inform you that the feature mentioned by Aseem above is complete and available for use. You can have an Azure function to query for the test results, and use it as a pre-deployment and post-deployment gate. Using the time fields, you'll also be able to specify if the criteria should be re-evaluated multiple times while the team works on completing any remaining tests.
Read more about release gates at https://blogs.msdn.microsoft.com/devops/2017/11/16/release-gates-releases-with-continuous-monitoring-built-in/

**Comment by RoopeshNair** [comment]
Closing as we support gates feature in release, please refer to Shashban update above
