### ISSUE TITLE
Failed to Create Resource Group and Vms

### ISSUE THREAD

**Issue by AfidahTan** [Microsoft/vsts-tasks#5648]
Hi Team,

Sorry I am new to this and pardon me if I don't provide the sufficient information. I try to set up Release Definition for my Selenium testing. I received the following error when trying to create new Resource groups and VM in VSTS. I am using AzureVM. I am using Hosted Agent.

Error that I got:

"##[error]Standard Error Message: Failed to set extension on Virtual Machine ns-qa-ta-r492. Error: WSManFault\n    Message = The client cannot connect to the destination specified in the request. Verify that the service on the destination is running and is accepting requests.

Attached here is the log. 

Please advise.

[tasklog_4 (5).zip](https://github.com/Microsoft/vsts-tasks/files/1386843/tasklog_4.5.zip)

Regards,
Afidah

**Comment by ds-ms** [comment]
This issue is duplicate to whatever was going on RMCQ
