### ISSUE TITLE
Nuget Command Task does not allow for arbitrary arguments

### ISSUE THREAD

**Issue by Cellivar** [Microsoft/vsts-tasks#5656]
## Environment
TFS 2018 RC2 (Freshly installed!)

## Issue Description
The new NuGet command task that is replacing the separate NuGet tasks does not allow for additional NuGet arguments to be specified for the `pack` command. This is a regression in functionality from the previous NuGet packager task, as I can no longer specify the flag `-NoDefaultExcludes`. We use a NuGet package to distribute a `.editorconfig` file to our team, and NuGet by default will exclude any dot-prefix files.

Deprecated NuGet Packager task interface:
![image](https://user-images.githubusercontent.com/1441553/31674381-b04b3c88-b32f-11e7-9f47-2d13b88aab9b.png)

We would like to see the field added back in. In the meantime we will continue using the deprecated build task.

**Comment by pspill** [comment]
@Cellivar The design of the latest version of the NuGet build command is to guide the user through the most common settings for each command, and to give them full control of all possible options through the "custom" command options. So in this case, you could select Command = "Custom" and Command and arguments = "pack path/to/your.nuspec -NoDefaultExcludes -Properties Configuration=$(BuildConfiguration) -OutputDirectory path/to/outputdir"

Please let us know your feedback about this option -- does this work for you in this case?
