### ISSUE TITLE
Manage App Service - Extracted to a Task Group as Parameters, the Slot Resource Group & Name fields do not populate from Azure. 

### ISSUE THREAD

**Issue by JoeBrockhaus** [Microsoft/vsts-tasks#5657]
## Environment
- VSTS
    - Account: **mssc**
    - Project: **MatRv2**
    - Release: 
        - DefinitionId: **52**
        - EnvironmentId: **92**

- Agent 
    - Queue: **Hosted VS2017**

## Issue Description

When the App Service Manager task is part of a Task Group, with Parameters for Azure Connection, App Service Name, Slot Resource Group, and Slot Name, the latter 2 are not populated from Azure. 

Prior to being in a Task Group they populate just fine. 
(To be honest, I didn't even expect this to be a feature, but was happily surprised!)

![image](https://user-images.githubusercontent.com/5933609/31677728-54f66f86-b331-11e7-8b7f-6de09c79a734.png)

**Comment by rokmicrosoft** [comment]
@JoeBrockhaus AzureConnectionGuid seems different from task UI {Azure subscription}. Are you using custom task ? We never supported pre-populate Slot Resource Group and Slot Name. Can you please share the log at RM_Customer_Queries@microsoft.com.

**Comment by niadak** [comment]
@JoeBrockhaus , I am closing the issue. Please feel free to reopen the issue or contract us @ RM_Customer_Queries@microsoft.com. if you are still facing the issue

**Comment by JoeBrockhaus** [comment]
Sorry for delayed response. This is a set it and forget it kind of issue for me, but I ran across it again. 

Steps to Reproduce: 
1. Add a `Manage App Service` Task to a Release. 
1. Select an appropriate `Azure Connection`. 
1. As you work your way through the configuration, you'll find that all 3 of the following fields will auto-populate:
   - `App Service Name` 
   - `Slot Resource Group`
   - `Slot Name`
1. Extract the Task as a Task Group. 
1. Create Task Properties for the necessary Task fields (`Azure Connection`, `Service Name`, `Slot Resource Group`, `Slot Name`, etc)
1. Save Task Group and return to the Release. 
1. Configure the Task Group: Select an appropriate `Azure Connection`. 
1. As you work your way through the configuration, _only the `Azure Connection` &  `App Service Name` fields will auto-populate._ 
1.  **`Slot Resource Group` & `Slot Name` _do not_ populate as they do when they are a normal Task.**
