### ISSUE TITLE
Question: Npm task registries

### ISSUE THREAD

**Issue by calebcartwright** [Microsoft/vsts-tasks#5659]
(On VSTS)
Really more of a clarification question on expected task behavior..

We noticed different behavior around external registries with the [npm task](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/Npm) based on the command selected (Registry configuration is pointed to 'Registries in my .npmrc' on all tasks).

When the command is set to `publish`, the registry url will be automatically pulled from the url specified in the npm service endpoint and automatically set in the generated .npmrc file. The task successfully publishes the package to the registry specified in the service endpoint.

However, the same configuration for the `install` command does *_not_* automatically pull in the registry url from the service endpoint, and as such packages are pulled from the default npmjs registry and not the registry specified in the same service endpoint. ( Enabling 'Verbose logging' on the task shows npm fetching from https://registry.npmjs.org/...) 

In looking at the source for both [npmcustom.ts](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Npm/npmcustom.ts) (used for `install` command) and [npmpublish.ts](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Npm/npmpublish.ts)  (used for `publish` command) it appears that for `install`, npmcustom has [a condition on whether always-auth is true](https://github.com/Microsoft/vsts-tasks/blob/a4a5970e8608c7e41906a24890260aad8b5c1d3e/Tasks/Npm/npmcustom.ts#L35)  whereas [npmpublish does not have that check and always appends the registry line
](https://github.com/Microsoft/vsts-tasks/blob/a4a5970e8608c7e41906a24890260aad8b5c1d3e/Tasks/Npm/npmpublish.ts#L28)

Is that the expected behavior? If so, does that mean the `install` command requires the registry be set elsewhere by the user (via .npmrc file in source control, set in configuration on agent, etc.)?

**Comment by alexmullans** [comment]
Thanks for asking. This is the expected behavior. For install, we want to promote the best practice of having a .npmrc checked into your repo, so that anyone cloning it knows where to restore packages from.
