### ISSUE TITLE
Xamarin.Android builds unable to run because Xamarin.Android not detected as a system capability when Xamarin.Android 8.1.0.20 alpha installed

### ISSUE THREAD

**Issue by andrewtechhelp** [Microsoft/vsts-tasks#5660]
## Environment
- Server - VSTS or TFS on-premises? VSTS
- Agent - Hosted or Private: macOS 10.12.6, Agent Version 2.123.0

## Issue Description
Currently, the way the Xamarin.Android system capability is detected by the VSTS agent is that it looks for the 'generator' executable in '/Library/Frameworks/Xamarin.Android.framework/Commands/' (with Commands being an alias to '/Library/Frameworks/Xamarin.Android.framework/{insert latest version here}/bin/' (see this link to see the code that does this detection: https://github.com/Microsoft/vsts-agent/blob/f7e9a7ee42d0c30f0d31d449bb51d95bd6e9e0fb/src/Agent.Listener/Capabilities/NixCapabilitiesProvider.cs#L70 )

This has worked all the way up to Xamarin.Android 8.0.0.33. However in the latest Xamarin.Android alpha (8.1.0.20), the 'generator' executable is no longer located in that folder (the only executable in that folder now is 'smcs'). This means that the Xamarin.Android system capability is no longer detected automatically by the VSTS Agent and therefore Xamarin.Android builds no longer run on the VSTS Agents because the capabilities no longer meet the demands of those builds (that Xamarin.Android exists).

This can be worked around by manually adding a Xamarin.Android user capability, but ultimately the solution seems like it needs to be a change to how Xamarin.Android system capability detection is done. I'm not sure what the preferred approach would be (changing it from 'generator' to 'smcs' or another completely different detection method).

**Comment by madhurig** [comment]
The fix on the agent is available for Xamarin.Android capability.

**Comment by osvaldcs** [comment]
The fix on the agent is available for Xamarin.Android capability v.2.129.1 link: https://github.com/Microsoft/vsts-agent/releases/
