### ISSUE TITLE
FTPS upload - succeeds, but nothing uploaded

### ISSUE THREAD

**Issue by LaevaertK** [Microsoft/vsts-tasks#5661]
When using the FTP upload task ons VSTS,  the task succeeds, but nothing is transferred.
We're using a hosted agent, version 2.123.0 on a Windows 10 enterprise
The FTP-server is on a synology NAS, and I can connect/upload using Filezilla.

![image](https://user-images.githubusercontent.com/18716704/31707770-801d81a6-b3ed-11e7-812a-2c0752588479.png)

**Comment by lkillgore** [comment]
Hi @LaevaertK.  That's quite peculiar.  I did a quick sanity check on the task internally just to make sure that nothing broke, and it is working.

Would you mind checking a few things?  Could you tell me exactly which version of the task you're using?  In your log it should look something like:

```
 Task         : FTP Upload
 Description  : FTP Upload
 Version      : X.XXX.X <= this version
 Author       : Microsoft Corporation
 ```
Also, can you access the FTP server from the Hosted machine?  If you open up a command prompt on the machine where the agent is running, can you use the FTP command to connect, login and copy the files over?

A couple of points I noticed in your log:
1) It's not getting a 'greeting'.  (The server isn't sending back a response on the connection https://github.com/mscdex/node-ftp)
2) Nor is it getting a 'ready'.

I'm hoping that connecting via FTP on your agent will give us more diagnostic information.

Thanks!

**Comment by jpricketMSFT** [comment]
Closing this issue due to lack of response.
