### ISSUE TITLE
Unable to add a development link to a task

### ISSUE THREAD

**Issue by IeuanWalker** [Microsoft/vsts-tasks#5663]
## Environment
- Server - VSTS 
    Account Name: CardiffCouncilICT
    Project Name: Cardiff App

## Issue Description

Adding a development link inside a task no longer works.
Previously I was able to connect a commit to the relevant task, now I get an empty drop down for "Link Type".

My managers are convinced they haven't altered any permissions. 

He elevated my permission to the same level as his, and I was still unable to do it, but my manager is able to do it from his account,

So no one on my team is able to add the development link.

![screenshot_1](https://user-images.githubusercontent.com/6544051/31713813-6ec4da26-b3f7-11e7-8637-9ea239cb8e87.png)

**Comment by bryanmacfarlane** [comment]
That's not an issue with one of the CI tasks in this repo.
