### ISSUE TITLE
Knowledgebase of changes/impact to custom tasks for migration of TFS 2015 to TFS 2017

### ISSUE THREAD

**Issue by sheldonhull** [Microsoft/vsts-tasks#5673]
I have been looking for information on what changes to custom tasks in TFS 2017 have been made so I know what I might need to migrate or might be able to leverage in TFS 2017 Update 2. 

I see references to "objects" in the [new documentation in the json definition](https://docs.microsoft.com/en-us/vsts/extend/develop/build-task-schema). Some previous limitations that challenged my ability to write pipeline driven build tasks was only being able to take string values, not even boolean would process other than as string values.  Has this behavior changed in TFS 2017? Any other documentation relating to new improvements in custom build tasks that I can review to see impact to my current work?

If there is a better location to ask this, then please let me know.

**Comment by MireilleHanna** [comment]
You can check the release notes for all the updates between 2015-2017 [here](https://docs.microsoft.com/en-us/vsts/release-notes/2017/)

**Comment by ericsciple** [comment]
This repo is for the in-the-box tasks. Custom-task-author docs are in the vsts-task-lib repo. Specifically here is a doc noting [agent features](https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/minagent.md) (and which agents correspond to which tfs version).

Updating from TFS 2017 RTM to U2 should not require any reaction from in-the-box tasks in this repo. If so, I would think it is a bug in the task.

The agent is also backward compatible and should not require any reaction when you move from 2017 RTM to Update 2.
