### ISSUE TITLE
Add task for running command on Azure VMs without admin credentials

### ISSUE THREAD

**Issue by gregjhogan** [Microsoft/vsts-tasks#5676]
The [PowerShell on Target Machines](https://docs.microsoft.com/en-us/vsts/build-release/tasks/deploy/powershell-on-target-machines) task requires admin credentials and WinRM.  It would be a lot more convenient for Azure VMs if you added support for using [run-command](https://docs.microsoft.com/en-us/cli/azure/vm/run-command?view=azure-cli-latest#az_vm_run_command_invoke) (removing the need for admin credentials and WinRM).

**Comment by RoopeshNair** [comment]
@gregjhogan, we do support Azure PowerShell and Azure CLI commands for Azure VMs. With  [Deployment Groups](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/release/deployment-groups/) you can run the scripts locally without having to remote.  

PowerShell on target is generic WinRM tasks that can be used for on-premises VMs as well. At this moment no plans to add Azure VM dependencies to it.

**Comment by gregjhogan** [comment]
Yes, I know there are a number of different ways to run commands on Azure VMs, but I think it would be a lot simpler if you had a dedicated task.  No need for deployment group (and PAT to manage) and no need to write a wrapper script just to call the ARM runCommand API.

**Comment by RoopeshNair** [comment]
Just so that I understand the request correctly, are you suggesting a dedicated task for Azure VMs to run scripts remotely? 

PAT for deployment groups is only for registering/in-registering the agent. Once the hand-shake is made the agents use it's own encrypted token to communicate. You don't have to maintain the PAT.

**Comment by gregjhogan** [comment]
The design is up to you (a dedicated task would work for me).  The run command API is the simplest way to  run powershell on a VM (since you already had to have a RM credential to create the VM), so I thought it would be logical to have a task that can do it considering you already have tasks for running commands over WinRM.
