### ISSUE TITLE
Can't build 1709 Nano Server Images

### ISSUE THREAD

**Issue by davidobrien1985** [Microsoft/vsts-tasks#5697]
## Environment
VSTS

- Agent - Hosted or Private: 
Hosted

## Issue Description

I'm trying to build a Windows Nano Server 1709 image, which fails because the underlying agent is not on 1709.
When will the hosted VSTS agents be updated so that we can build 1709 images?

### Error logs

```
container 376e29b291aa290ebdff35b4eaa136595fc6d168a63bddc5ef0436955018aeaf encountered an error during CreateContainer: failure in a Windows system call: The operating system of the container does not match the operating system of the host. (0xc0370101) extra info: {"SystemType":"Container","Name":"376e29b291aa290ebdff35b4eaa136595fc6d168a63bddc5ef0436955018aeaf","Owner":"docker","VolumePath":"\\\\?\\Volume{8c532bb7-b8d6-11e7-a98e-000d3ad0bf62}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\376e29b291aa290ebdff35b4eaa136595fc6d168a63bddc5ef0436955018aeaf","Layers":[{"ID":"edf18442-d0d5-5666-ad3b-f1da335d7ee1","Path":"C:\\ProgramData\\docker\\windowsfilter\\8176c946554686556e471bd8e61c9bcf66e2c1afe64b282c92311a5dda7d2a19"},{"ID":"ce3684a5-d7b9-5142-b4bc-850b4a528e47","Path":"C:\\ProgramData\\docker\\windowsfilter\\198b115847b18df970d90b8f853a2dd6fa28273ab2c7a2a7490761caf5eb9849"},{"ID":"60cfd27f-fb57-532a-a0f5-3a5d81c51ce7","Path":"C:\\ProgramData\\docker\\windowsfil...
C:\Program Files\Docker\docker.exe failed with return code: 1
```

**Comment by vijayma** [comment]
The Hosted VS2017 image is primarily for running VS2017 builds. Since 1709 is a server core, we cannot install VS on it. So, there is no plan at this point to support another pool of VSTS agents with 1709. You should be able to set up a private agent on 1709.

**Comment by bryanmacfarlane** [comment]
This is also not an issue with one of the tasks in this repo (what these issues are tracking).

**Comment by dazhao-msft** [comment]
@bryanmacfarlane @chrisrpatterson what is the recommended way to build 1709 based images with VSTS CI pipeline then?

**Comment by AceHack** [comment]
@vijayma @bryanmacfarlane 1709 is also a Windows 10 Desktop version as well, please support building 1709 nanoserver based docker images, this is a big limitation of the hosted agents.
