### ISSUE TITLE
Automated Test case association in MTM

### ISSUE THREAD

**Issue by indu09** [Microsoft/vsts-tasks#5713]
we are using TFS as source control now and planning to move to git hub. So I would like to know how can we map test methods to test cases in TFS and also how to create build definition to be pulled from MTM to for automated runs?

**Comment by vimegh** [comment]
@indu09 For Associating Test Case To TestMethod please refer  "Associate Test Case" Section of https://docs.microsoft.com/en-us/vsts/build-release/test/associate-automated-test-with-test-case 

Do you mean automatic migration of MTM definition to TFS? I dont think that is supported as of now. @PBoraMSFT Can you please help here.

**Comment by vimegh** [comment]
@indu09  Were you able to associate Test Cases. Please let us know, if you are still facing any problem.

**Comment by acesiddhu** [comment]
Closing this because of no response. @indu09 please create a GitHub issue if you have any issues
