### ISSUE TITLE
After upgrade to .Net 4.6 Visual Studio Test task/step fails when VSTest version is set to Visual Studio 2015

### ISSUE THREAD

**Issue by TheSchmoe** [Microsoft/vsts-tasks#572]
I just upgraded all of the projects in my solution to point to .Net 4.6 (There is a web app, some class libraries, a database project, etc.). I have a CI build set up in Visual Studio Online which was building successfully prior to the upgrade. This build definition runs Debug, Staging, and Production builds and the build definition is comprised of two steps:
1. Visual Studio Build
2. Visual Studio Test
Prior to this framework upgrade, everything was building fine. I upgraded all of the projects to target .Net 4.6 and built everything locally and it all worked great too. I could run the tests and got green across the board. Now, when I checked my code in it kicked off the CI build, and I got the following error/s on the "Visual Studio Test" step (taken from the logs, dates replaced with hyphens on each line for brevity):

- Starting test execution, please wait...
- Warning: Using Isolation mode to run tests as required by effective Platform:X86 and .Net Framework:Framework35 settings for test run. Use the /inIsolation parameter to suppress this warning.
- ##[error]Error: Executor process exited.
- ##[error]
- ##[error]Error: There was no endpoint listening at net.pipe://{My build server name here}/TestExecutor/4892 that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.
- ##[error]
- ##[error]VSTest Test Run failed with exit code: 1
- ##[warning]No results found to publish.

The Visual Studio Build step passes for all three configurations, and the Test step only fails for Debug because it cannot find any tests for the other two configurations. Additionally, my builds are running off of an Azure VM that I stood up to act as a build server, and when I run the CI build using the Hosted build controller the Test step passes.  Again, the build and test steps were passing using VSTest version VS-2015 prior to the .Net 4.6 upgrade.

I got my tests to pass if I queued a build and pointed it to the hosted build controller.  Looking at the machine capabilities, it looks like the hosted controller is using VSTest version VS-2013.  So I tried and was able to get my CI build to work by changing the VSTest version to VS-2013.  I'm not sure if this is a VSTest issue or a VSO issue.

**Comment by atinb** [comment]
@TheSchmoe 
Can you take the command line for vstest.console,exe from the build logs for Visual Studio Test task and run it locally using VS2015 and see if it passes?  Thanks!

**Comment by cottsay** [comment]
I was having this same issue. When I manually ran the command from a prompt on the same machine on which the agent was failing, it prompted me to install .NET Framework 3.5. I went into the feature manager and installed it, and the tests now run correctly.

I was also having problems uploading artifacts to the server before installing .NET Framework 3.5.

Please add .NET Framework 3.5 to the prerequisites [1] for running a VSO agent.

Thanks,

--scott

[1] https://msdn.microsoft.com/en-us/Library/vs/alm/Build/agents/windows

**Comment by bryanmacfarlane** [comment]
This should have been fixed awhile ago on the hosted pool.  re-open if still an issue
