### ISSUE TITLE
Advanced-named groups in tasks are ignoring the isExpanded property

### ISSUE THREAD

**Issue by BiribiriJaNai** [Microsoft/vsts-tasks#5727]
## Environment
- Server - VSTS    
    - all existing accounts I guess (so far, I experienced this behavior on 5 different accounts).

## Issue Description
Built-in and custom tasks having a group with `"displayName": "Advanced"` are always collapsed in the build editor, ignoring the `"isExpanded": true`.
Easily reproducible by following these steps:
- Create a build definition
- On the 'Phase 1' agent phase, click '+' and add some tasks (CocoaPods, JenkinsQueueJob are good examples).
- Click on each task and notice that the 'Advanced' group is collapsed.

You can check the code of these two task:
- [CocoaPods](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/CocoaPods/task.json)
- [JenkinsQueueJob](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/JenkinsQueueJob/task.json)

I also tried this with a custom task. Whatever the name of the group, if I set the `displayName` property to `Advanced`, it will appear collapsed.
Is this by design or a bug?

**Comment by yaananth** [comment]
It sounds like the new editor is not honoring the property.
Created internal [bug ](https://mseng.visualstudio.com/VSOnline/_workitems/edit/1120552)for tracking.
Thanks for reporting @BiribiriJaNai !
