### ISSUE TITLE
Where is nuget-task-common

### ISSUE THREAD

**Issue by galvesribeiro** [Microsoft/vsts-tasks#5734]
Hello!

We are building a custom task for our company to use on our build process in VSTS. I've followed the sample tasks here in particular Docker and the .Net CLI ones.

As part of our process, we need to build either nuget packages and containers images and publish them to our VSTS Feed and Azure Container registry accordingly. 

Looking the `pushcommand.ts`(and on multiple other places) I've checking references to a module called `nuget-task-common` which allow us to authenticate on VSTS Feed and get credentials to publish packages on it. The problem is that this module isn't anywhere in the repo.

Where can we get it? If it is closed source (which is sad since it make the sample impossible to build and follow) how can we authenticate with VSTS feed in order to publish nuget packages to it? 

The same happens with Docker task. There is a `ContainerConnection` and `ACRAuthenticationTokenProvider` which is supposed to hold the credentials to ACR but it is on `docker-common` module. How can we use it?

I would appreciate any help.

Thank you!

**Comment by jotaylo** [comment]
The source for nuget-task-common is in this repo: https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/Common/nuget-task-common

**Comment by galvesribeiro** [comment]
Thanks!
