### ISSUE TITLE
ServiceFabricUpdateManifests Task always fails to find the ApplicationManifest.xml

### ISSUE THREAD

**Issue by jcleavel** [Microsoft/vsts-tasks#5736]
The new version of the VSTS ServiceFabricUpdateManifests task can never find the `ApplicationManifest.xml` file when trying to compare the current build to a previous build's artifacts.

The issue appears to be here:
The previous build's artifacts are downloaded into a folder in the `$(Agent.WorkFolder)\tmp\` directory:
Ex. `C:\agent\_work\tmp\`

https://github.com/Microsoft/vsts-tasks/blob/a641ccf39643408c33fcd288dd1e371dc3981fcf/Tasks/ServiceFabricUpdateManifests/Get-VstsBuild.psm1#L63

Whereas, the next step attempts to compare this directory to the new build's by trimming characters from the previous build artifact's directory path equal to the length of the path for `$(Build.SourcesDirectory)`.
Ex.

```
$(Build.SourcesDirectory)            => C:\agent\_work\1\s
Previous Build Artifact Directory => C:\agent\_work\tmp\applicationpackage

!!TRIM!!

Result => \applicationpackage
```

You can see this operation here:
https://github.com/Microsoft/vsts-tasks/blob/2c02c93bb7899f53d2b07a8487a13ccb4f776010/Tasks/ServiceFabricUpdateManifests/Update-ApplicationVersions.psm1#L59

This will always cause failures because the relative paths will never compare correctly.

**Comment by kuvinodms** [comment]
Hi Nathan,
I can see that Jason Ricke has updated the related code in PR https://github.com/Microsoft/vsts-tasks/pull/5287 which is causing this issue. Please have a look at it and update.

**Comment by NCarlsonMSFT** [comment]
The task is working for my own builds. I think you are experiencing the same issue as in #5592 

The issue we found in that case is that the task always assumes the $(build.artifactstagingdirectory) folder will be published as the artifact and can't handle a sub-folder. Are you publishing some other folder as your artifact?

FYI: I am planning a fix around the bad path assumption, but I won't be able to get it out for a few weeks.

**Comment by jcleavel** [comment]
Yeah, that's definitely the issue.

I'm not really in any hurry for a fix, to be honest. Based on the new "Download Build Artifacts" task that is in preview, it looks like you folks are starting to move in the direction of encouraging selective download of build artifacts.

I like the way that my builds are setup currently, so I can wait a few weeks for a more durable fix.

**Comment by bishal-pdMSFT** [comment]
> FYI: I am planning a fix around the bad path assumption, but I won't be able to get it out for a few weeks.

@NCarlsonMSFT , is this among your next planned items?

**Comment by NCarlsonMSFT** [comment]
Yes, this is currently on my plate.

**Comment by jcleavel** [comment]
Awesome, thanks folks!
