### ISSUE TITLE
Publish Build Artifacts with single file causes error when using a file share as publish location

### ISSUE THREAD

**Issue by ElmerBlues** [Microsoft/vsts-tasks#5738]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS 
- Agent - Hosted

## Issue Description

How to reproducte: 
Add '**Publish Build Artifacts**' task to a build. I choose for '**Path to publish**' a specific file from my build, for instance: 

$(Build.SourcesDirectory)/mybuild.msi 

For '**Artifact publish location**' I choose '**Visual Studio Team Services/TFS**'. Publishing of the msi works perfectly!

Now when I choose (same build) in the '**Artifact publish location**' the value '**a file share**' and with that a proper '**File share path**' I get the following error when publishing:

### Error logs

2017-10-31T06:50:42.9295926Z 2017/10/31 07:50:42 ERROR 123 (0x0000007B) Accessing Source Directory D:\_vso\_work\26\s\mybuild.msi\
2017-10-31T06:50:42.9295926Z The filename, directory name, or volume label syntax is incorrect.
2017-10-31T06:50:42.9295926Z 
2017-10-31T06:50:42.9295926Z ##[debug]robocopy exit code '16'
2017-10-31T06:50:42.9452179Z ##[error]Publishing build artifacts failed with an error: powershell.exe failed with return code: 1

**Comment by AlexRukhlin** [comment]
Hi,

The task "Publish Build Artifacts" copying files to a file share, requires a folder as the "Path to publish" input value. You're  specifying a file path: $(Build.SourcesDirectory)/mybuild.msi.

You can stage the artifact file before you publish it. Add one more task before your "Publish Build Artifacts" one that will copy your MSI file to the $(build.artifactstagingdirectory) folder and the publish the latter.
```
Task: Copy Files
Source Folder: $(build.sourcesdirectory)
Contents: mybuild.msi
Target Folder: $(build.artifactstagingdirectory)
```
```
Task: Publish Build Artifacts
Path to publish: $(build.artifactstagingdirectory)
...
```
Alex

**Comment by ElmerBlues** [comment]
Hi Alex,

Thank you for your reaction. 

I do know how to workaround it, but it is strange that when chosing 'File share', a perfectly running task is sudden causing an error just because you change the 'artifact publish location'. It shouldn't make a difference where your artifact publish location is: on Visual Studio Team Services/TFS or a custom chosen location. That shouldn't create an error, period.

And do mind you can selecting a file (instead of a folder) when clicking the 3 dots next to 'Path to publish'. It's only saying that wildcards is not supported, not a saying that filenames are not supported when using File Share..

In my opinion this is plain wrong.

**Comment by smartin34** [comment]
Dear all,

we are creating a .zip file from our build outputs and want to publish this .zip into a separate build artifact called "zipped_drop". Unfortunately we spend a lot of time to create a working build configuration just because of this bug.
The task (robocopy behind) always handles the "Path to Publish" as a folder, no matter whether you specify a file path.
It's explanation also says "folder or file path to publish".

It just makes things complicated if you have to workaround with additional folders you actually don't need, just to get it work as it actually should.

In my opinion this must be fixed asap.

**Comment by madhurig** [comment]
A fix for this issue (7cf7ed1d4a14fbb7af30a6b5738fc93a5fc15a4c) has been deployed to all accounts in VSTS. Please let us know if you still see a problem.

**Comment by RomanMik** [comment]
Any clue when this will be available for on-premise version?

**Comment by madhurig** [comment]
@RomanMik: It will be in the next feature update for TFS 2018, we don't have a timeline yet.

**Comment by milbrandt** [comment]
Unfortunately, I had this issue today with task version Publish Pipeline Artifacts 1.199.0

**Comment by mvonballmo** [comment]
As of today on Azure DevOps Services, although the [documentation for the task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-pipeline-artifact-v1?view=azure-pipelines#inputs) continues to say that `targetPath`,

> Specifies the path of the file or directory to publish.

It doesn't seem to support a single file, instead always treating the `targetPath` as a folder.

![image_2024-01-05_143830970](https://github.com/microsoft/azure-pipelines-tasks/assets/1214927/7b42c046-06f2-42a1-9282-e37b460aa32f)

I suppose I will use the `.artifactsignore` file.
