### ISSUE TITLE
403 Forbidden on Azure App Deploy From VSTS

### ISSUE THREAD

**Issue by mewt666** [Microsoft/vsts-tasks#5739]
I have VSTS configured with two Azure account endpoints, one for dev/test/qa environments and a second for production. While deployment to the former succeeds, the latter fails with a 403 forbidden error. 

I verified the SPN successfully (as given in #5458) but deployment is still failing. I created a new app within the Azure account and this shows up in the selection list in VSTS, however deployment fails just the same. 

![image](https://user-images.githubusercontent.com/3087944/32219391-54fc3cba-be2e-11e7-95cd-a5a4f5766732.png)

I confirmed permissions for the Azure AD authentication app and they are identical between accounts.

**Comment by vincentdass** [comment]
@mewt666 , Can you please share the debug logs for the release? (set `system.debug` to `true` and re-run the release). This will provide some more data on the issue.

**Comment by vincentdass** [comment]
@mewt666 ,  closing this thread as there is no response.
Feel free to re-open the thread if required with Debug logs.

**Comment by Abhay5104** [comment]
Hi,
i am using shell script with az command (az.webapp deployment source config-zip ) to deploy service on azure.
script is executed using shell.exe task on VSTS.
it gives 403 error event though service is up and running.
i am able to run the script with local machine and deployment is successful.

How can i resolve the issue ?

**Comment by Ajay-MS** [comment]
Since task failed with status code 403, it states that server refused for authentication.

 As you mentioned you are using shell script task, either you need to add an additional step for authentication or you should use **azure cli** task if you want to use same command ( az.webapp deployment source config-zip ) with authentication. 

Also, you can use app service deploy task for deployment to app service.

**Comment by Abhay5104** [comment]
Thanks Ajay for reply.

I am having az login command with service principal and there are other
task like group create, plan create , web app create and creation of
deployment slot creation.
Only command for zip deployment is failing.
PS: if I try to deploy to production slot then it's working fine.
Note : I have web app with Linux OS and php 7.0 runtime stack

Issue is when I run this script on VSTS agent machine.

Regards,
Abhay

**Comment by hiyadav** [comment]
@Abhay5104 
Are you using the NodeJs Application used in this link => .
As it is missing "web.config" file required by IIS. Also do check if you application is NodeJs based, that it has the web.config.

**Comment by UnreachableCode** [comment]
I was just having this issue after a few months of successfully building piplines for develop/master branches in debug/release modes. I'm not sure what caused it to suddently stop working, but I went and got an up to date token from App Center for my organisation and added it to my existing App Center service connection in Azure and now everything is working again for my 2 original pipelines and the new one I've added.
