### ISSUE TITLE
Windows Machine File Copy 2.0.0 Copy Files in Parallel: The term 'Get-VstsLocString' is not recognized

### ISSUE THREAD

**Issue by Mibe8** [Microsoft/vsts-tasks#5753]
**## Environment**
VSTS
Private Agent 
Windows Server 2008 R2
Agent version 2.123.0

**## Issue Description**
When I use version 2.* from the Windows Machine File Copy task, enter multiple machines and select Copy Files in Parallel failed the task fails.

![copytasks](https://user-images.githubusercontent.com/33321036/32328701-1656bb26-bfdb-11e7-9ec9-2cd9c676b819.png)

The copy itself succeeds. It looks like some references get lost when Powershell Executes the RoboCopyJob from Start-Job instead of Invoke Command.

**### Error logs**
##[error]The term 'Get-VstsLocString' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by rokmicrosoft** [comment]
@Mibe8 We have already investigated this issue but able to release it in next release. Till then can you please downgrade the task version (1.x) and queue your release.

**Comment by Mibe8** [comment]
Sure, but I couldn't find a similar issue, so I tought I report it.

Does this also apply for the PowerShell on Target Machines task? I see similar behaviour when running it in parallel, with another error message:

The term 'Get-ParsedSessionVariables' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by rokmicrosoft** [comment]
Yes this issue is also with  PowerShell on Target Machines task.

**Comment by niadak** [comment]
We have fixed the issue and the fix will be available in next release cycle(ETA 3 weeks).
