### ISSUE TITLE
DotNetCoreCli does not respect arguments when running a "custom" command.

### ISSUE THREAD

**Issue by tonyferrell** [Microsoft/vsts-tasks#5757]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS
- Agent - Private (but doesn't appear to be related)

## Issue Description

[Include task name(s), screenshots and any other relevant details]
I am attempting to provide some custom arguments to the DotNetCoreCli task, but it appears that my custom arguments are lost.
### Error logs
I added `-r win10-x64` as a custom argument, but the task shows the command run as 
```
D:\agent1\_work\_tool\dncs\2.0.0\x64\dotnet.exe restore D:\agent1\_work\31\s\CertificateIssuerService\CertificateIssuer.Service.csproj --configfile D:\agent1\_work\31\Nuget\tempNuGet_59482.config --verbosity Detailed
```

(notice my custom arguments are lost)

**Comment by Miista** [comment]
I have exactly the same problem. I am trying to invoke a "dotnet pack" with `--include-source` and `--include-symbols` but the arguments are ignored when the command is invoked.

**Comment by robbratton** [comment]
Here's my test information:

# Arguments from the config page for the .Net Core command with custom selected:
--no-build --include-symbols --include-source /p:Version=$(GitVersion.NuGetVersionV2) --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)

# Arguments in debug output:
2017-12-04T18:52:37.6792409Z ##[debug]arguments=--no-build --include-symbols --include-source /p:Version=GitVersion.NuGetVersionV2 --configuration Debug --output d:\a\1\a

# Actual command which was run:
2017-12-04T18:52:37.8102271Z [command]"C:\Program Files\dotnet\dotnet.exe" pack d:\a\1\s\Upmc.DevTools.Common.Tests\Upmc.DevTools.Common.Tests.csproj --output d:\a\1\a --no-build /p:Configuration=Debug /p:PackageVersion=0.1.0-unstable0016 --verbosity Detailed

_Please ignore the GitVersion stuff. That's not working yet and not important to this comment._

![image](https://user-images.githubusercontent.com/2131818/33571236-6f337f46-d8fd-11e7-9ed0-3574dca8a401.png)

**Comment by keithrob** [comment]
@tonyferrell, @Miista , @robbratton ,
This problem has been fixed in the hosted version of Visual Studio (i.e. *.visualstudio.com) and will be fixed in the upcoming TFS2018U2.  
Keith
