### ISSUE TITLE
Service Fabric Compose Deploy build task does not use the new upgrade commands

### ISSUE THREAD

**Issue by brandmo** [Microsoft/vsts-tasks#5760]
Hi there,

v2.8/6.0 included new functionality to allow Compose Deploy apps to be upgraded rather than deleting and deploying new versions.

See https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-docker-compose
Start-ServiceFabricComposeDeploymentUpgrade
Get-ServiceFabricComposeDeploymentUpgrade

The Service Fabric Compose Deploy build task in VSTS doesn't yet take advantage of this, so existing deployments are still deleted and replaced rather than upgraded.

**Comment by brandmo** [comment]
Hi there, any new on this?

**Comment by NCarlsonMSFT** [comment]
I am working on a fix, but won't be able to get a PR out till after the new year.
