### ISSUE TITLE
Unable to follow steps in the "How to Contribute" guide

### ISSUE THREAD

**Issue by tonyferrell** [Microsoft/vsts-tasks#5769]
## Issue Description
I am attempting to follow the [how to contribute](https://github.com/Microsoft/vsts-tasks/blob/master/docs/contribute.md) guide, but when I run

```
npm install
npm run build
```
I get an error 

I am running npm and node versions 5.5.1 (maybe I need to install an older version?)
```
>npm node -v && npm -v
5.5.1
5.5.1
```
Any idea what I'm doing wrong here?

### Error logs

```> npm install E:\github\vsts-tasks\_build\Tasks\Common\java-common
,,npm ERR! code ENOLOCAL
npm ERR! Could not install from "..\..\_build\Tasks\Common\codecoverage-tools" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<username>\AppData\Roaming\npm-cache\_logs\2017-11-03T17_20_53_946Z-debug.log

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Agent.Tasks@0.5.0 build: `node make.js build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Agent.Tasks@0.5.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<username>\AppData\Roaming\npm-cache\_logs\2017-11-03T17_20_53_996Z-debug.log```

**Comment by bryanmacfarlane** [comment]
does it work with node 6 LTS?  We can update docs ....

**Comment by tonyferrell** [comment]
I honestly thought I installed the latest LTS from nodejs.org - but looking at the version above, that doesn't match up. I will reinstall and see if that changes anything.

**Comment by hubertusgr** [comment]
I am also running into this issue! The master branch seems to work but i can not build the latest release branch (m126?)

**Comment by hubertusgr** [comment]
Downgrading npm to the version 4.x worked!


running this command npm install -g npm@4

**Comment by hubertusgr** [comment]
Ok it is still failing for me:
------------------------------------------------------------
Building: Docker
------------------------------------------------------------


Building module E:\VSTSTasks\vsts-tasks-releases-m126\Tasks\Common\docker-common


> npm install

> tsc --outDir E:\VSTSTasks\vsts-tasks-releases-m126\_build\Tasks\Common\docker-common --rootDir E:\VSTSTasks\vsts-tasks-releases-m126\Tasks\Common\docker-common

> copying module resources
copying *.ps1
copying *.psd1
copying *.psm1
copying *.sh
copying *.txt
copying icon.png
copying icon.svg
copying module.json
copying node_modules
copying package.json
copying Strings
copying task.json
copying task.loc.json
copying Tests

> npm install E:\VSTSTasks\vsts-tasks-releases-m126\_build\Tasks\Common\docker-common

> npm install

> tsc --outDir E:\VSTSTasks\vsts-tasks-releases-m126\_build\Tasks\Docker --rootDir E:\VSTSTasks\vsts-tasks-releases-m126\Tasks\Docker
,Tests/TestShared.ts(1,21): error TS2307: Cannot find module 'vsts-task-lib'.
node_modules/docker-common/containerconnection.d.ts(1,21): error TS2307: Cannot find module 'vsts-task-lib/toolrunner'.
utils.ts(2,21): error TS2307: Cannot find module 'vsts-task-lib/task'.
Tests/L0.ts(3,22): error TS2307: Cannot find module 'vsts-task-lib/mock-test'.
Tests/L0.ts(4,21): error TS2307: Cannot find module 'vsts-task-lib'.
Tests/TestSetup.ts(1,21): error TS2307: Cannot find module 'vsts-task-lib/mock-answer'.
Tests/TestSetup.ts(2,23): error TS2307: Cannot find module 'vsts-task-lib/mock-run'.
container.ts(4,21): error TS2307: Cannot find module 'vsts-task-lib/task'.
containerbuild.ts(4,21): error TS2307: Cannot find module 'vsts-task-lib/task'.
containercommand.ts(3,21): error TS2307: Cannot find module 'vsts-task-lib/task'.
containerpush.ts(4,21): error TS2307: Cannot find module 'vsts-task-lib/task'.
containerrun.ts(4,21): error TS2307: Cannot find module 'vsts-task-lib/task'.
containertag.ts(4,21): error TS2307: Cannot find module 'vsts-task-lib/task'.
,
,,
[15:17:37] 'build' errored after 4.45 min
[15:17:37] Error: Missing error message
    at new PluginError (E:\VSTSTasks\vsts-tasks-releases-m126\node_modules\gulp-util\lib\PluginError.js:73:28)
    at make (E:\VSTSTasks\vsts-tasks-releases-m126\gulpfile.js:17:12)
    at Gulp.<anonymous> (E:\VSTSTasks\vsts-tasks-releases-m126\gulpfile.js:25:5)
    at module.exports (E:\VSTSTasks\vsts-tasks-releases-m126\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (E:\VSTSTasks\vsts-tasks-releases-m126\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (E:\VSTSTasks\vsts-tasks-releases-m126\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (E:\VSTSTasks\vsts-tasks-releases-m126\node_modules\orchestrator\index.js:134:8)
    at C:\Users\hubertusg.ADOS\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

E:\VSTSTasks\vsts-tasks-releases-m126>

**Comment by hubertusgr** [comment]
The Node version I am using is the latest LTS version, I will try to downgrade to the LTS version 6 and check if it works then.

**Comment by kuvinodms** [comment]
Any update on this issue, I'm facing the same!

**Comment by stephenmichaelf** [comment]
@hubertusgr I just ran it with node 6.12.0 and npm 3.10.10 and it worked.

Let me know if it works when you try version 6 LTS.

**Comment by stephenmichaelf** [comment]
@kuvinodms Can you try the same?

**Comment by hubertusgr** [comment]
I could finally get it to work on my mac where I rolled back to node 6 LTS. (on my windows machine the tasks would not build, no matter which node and npm i tried)
But seriously you should probably upgrade the build mechanism to work with a node and npm version wich is still supported as the current LTS version is version 8 afaik.

**Comment by kuvinodms** [comment]
npm install -g npm@4
This worked for me!

**Comment by shaneholder** [comment]
I can confirm that on Windows 10 I was able to build and run tests on master using node v4.8.6 and npm 3.10.10.

**Comment by stephenmichaelf** [comment]
@hubertusgr I believe this is still supported as LTS according to the Node page.

Going to close this issue, please reopen if anyone has troubles. Thanks!

**Comment by shaneholder** [comment]
I would actually suggest that a min ver, max ver be added to the contribution guide, at least until the higher version npm's/nodes are supported.
