### ISSUE TITLE
Run shell inline on remote machine, with docker-compose fails the build on regular docker-compose output

### ISSUE THREAD

**Issue by hkalyana** [Microsoft/vsts-tasks#5776]
## Environment
- Server - VSTS 
    
  

## Issue Description

I'm running a docker-compose command on a remote server using the remote shell script task, and it looks like very line docker-compose output to the console is tagged as an error by the Shell script Task in VSTS. The operation happens correctly inside docker and my container is also getting created but release is getting failed.

### Error logs

![image 3b2df64e5fa18dfe](https://user-images.githubusercontent.com/15196021/32438690-71070dbc-c311-11e7-87d9-6c13647d11ca.jpg)

**Comment by bryanmacfarlane** [comment]
This repo doesn't contain a remote shell script task.  That task should have an option like the shell script task in this repo whether stderr output should be treated as an error.  docker compose writes status to stderr (like git does).
