### ISSUE TITLE
[Release Task] IIS Web App Deploy : XML Substitution broken

### ISSUE THREAD

**Issue by KuehneThomas** [Microsoft/vsts-tasks#5777]
## Environment
- VSTS
- Agent: Private on Windows Server 2012 R2 Standard

## Issue Description

Since 2017/11/03 the XML variable substitution is broken in version 0.0.27 of the IISWebAppDeploymentOnMachineGroup task. No variables are substituted anymore (at least when used within a release definition).

### Workaround

Use the old task version 0.0.25 instead of 0.0.27 released on 2017/11/03. Delete the new folder and manually rename the old folder in _work\_tasks\IISWebAppDeploymentOnMachineGroup_1b467810-6725-4b6d-accd-886174c09bba.

**Comment by vincentdass** [comment]
@KuehneThomas , apologies for the inconvenience.
Currently, we are working on finding the root cause of the issue.

**Comment by KuehneThomas** [comment]
Which logs do you need? I recognized that many log files contain sensitive information and thus, need to be redacted manually.

**Comment by vincentdass** [comment]
@KuehneThomas , we identifed the root cause and resolved the issue.
The issue will be hotfixed, which will take a day or two.
In the meantime, You can unblock yourself by removing comments in config files.

**Comment by vincentdass** [comment]
@KuehneThomas , The issue is hot-fixed. Can you please re-run the release?

**Comment by KuehneThomas** [comment]
Unfortunately, our build server did not download a new version of the task (=no substitution in the release).

**Comment by vincentdass** [comment]
@KuehneThomas , apologies. the hotfix is not completed for all the regions.
Will update the thread once it is done.

**Comment by Jacob-McKay** [comment]
Our releases magically started to do botched deploys recently when using variable substitution.  We found that removing comments from our web.config resolved the issue.  (The comments have existed in the web.config for many months and many successful deploys)

**Comment by vincentdass** [comment]
@KuehneThomas , @Jacob-McKay , we have hot-fixed the issue.
Please re-run the release for the updated task (3.3.25 version)

**Comment by KuehneThomas** [comment]
Confirmed, the issue has been fixed.

Thanks a lot!
