### ISSUE TITLE
NuGet task and Visual Studio Build task use different wildcard standards

### ISSUE THREAD

**Issue by azchohfi** [Microsoft/vsts-tasks#5778]
## Environment
VSTS account: chohfims
(Can't share more details)

- Agent: Private
Windows 10 (16299)
Agent Version: 2.123.0

## Issue Description

NuGet task and Visual Studio Build task use different wildcard standards. I created a build process parameter to share a big wildcard with this 2 tasks and I just can't do that. They use different standards.

**Comment by jotaylo** [comment]
Which version of the NuGet task are you using? 
Are you talking about trying to push multiple nuget packages using a wildcard like folder\**\folder1\*.csproj? This is supported in the new NuGet VSTS task, however it is case sensitive. If you're trying to do something else, can you please let me know what you're trying, and can you give me an idea of what your wildcard looks like?

**Comment by azchohfi** [comment]
No. Just regular nuget restore. If I want to build 10 solutions/projects from a set of 15, and I want to use a wildcard with exclusion, I need to write the wildcard expression twice. they can`t be shared with a parameter. NuGet task uses the new standard 

> **/*sln;!DontBuildThis/DontBuildThis.sln

and Visual Studio Build Task uses the old one 
> **/*sln;-:DontBuildThis/DontBuildThis.sln

**Comment by jotaylo** [comment]
If you add the build variable “NuGet.UseLegacyFindFiles” and set the value to "true" it should revert the NuGet task to use the legacy file matching behaviour.

**Comment by azchohfi** [comment]
Good to know! Is the VSBuild Task going to support the new standard anytime soon?
