### ISSUE TITLE
Run Functional Tests Task - Unexpected Error Occured

### ISSUE THREAD

**Issue by laserrea** [Microsoft/vsts-tasks#5790]
## Environment
- Server - TFS on-premises
    -TFS 2017
-Visual Studio 2017 on QA's local machine
-SpecFlow 2.2.1
-NUnit 3.8.0.0
-Selenium 3.6.0

- Agent - Private: 
Agent Version 2017
Windows Server 2012

## Issue Description
The tests all run successfully on a local machine via Visual Studio. They also run successfully using vstest.console.exe on the remote server. 

Our current setup is we are using TFS 2017 to create builds as part of our CI process. For our UI tests, we need to run the test agents as a process and not a service, as we want to be able to interact with the UI and have the Selenium webdriver open a browser window on the remote server and perform the tests. We have a build server that takes care of the TFS builds, and we have a remote server that we are attempting to run the tests on.  

The build runs successfully, until it reaches the functional test task. This is where the build process then fails. The error is: 

```
Test run is aborted. Logging details of the run logs.
DistributedTests: New test run created.
Test Run queued for Project Collection Build Service (TEAM FOUNDATION).
DistributedTests: Test discovery started.
DistributedTests: Test Run Discovery Aborted . Test run id : 5629
DistributedTests: UnExpected error occured during test execution. Try again.
DistributedTests: Error : NUnit Adapter 3.8.0.0: Test discovery complete
DistributedTests: Test run aborted. Test run id: 5629
```

```
System.Exception: The test run was aborted, failing the task.
PowerShell script completed with 1 errors.
```

### Error logs
![build steps and functional test task properties](https://user-images.githubusercontent.com/33460553/32505039-d2cdab38-c3a6-11e7-8e64-04bec61d5335.jpg)
[1_Build.txt](https://github.com/Microsoft/vsts-tasks/files/1450810/1_Build.txt)
[DTAExecutionHost.exe.log](https://github.com/Microsoft/vsts-tasks/files/1450814/DTAExecutionHost.exe.log)
[Integration_9_5.runsettings.txt](https://github.com/Microsoft/vsts-tasks/files/1450816/Integration_9_5.runsettings.txt)

**Comment by gcmvanloon** [comment]
Had the exact same thing today. Seems the "Run Functional Tests" task scans the filesystem for test adapters and uses the first adapter it finds. We had both nuget packages included in our project  (specrun.runner and nunit3 test adapter).
The functional test task decided to go for nunit but couldn't find any tests which results in the abort.
After we had removed nunit3 test adapter from our packages.config and made sure no nunit test adapter is copied to the test environment the the functional test task finds the specrun.runner adapter and all is fine.
The reason you were able to run vstest.console succesfully on the remote server is that you specify your test adapter specifically using the `/testadapter` argument.
Make sure no other test adapters than the one you want to use can be found by the run functional test task or you risk using the wrong one.

**Comment by prawalagarwal** [comment]
@laserrea We will continue on the resolution for your issue @devops alias. Closing this.
