### ISSUE TITLE
SQLDacPacDeploymentOnMachineGroup has an incorrect tooltip for the exclusive lock property

### ISSUE THREAD

**Issue by simonsabin** [Microsoft/vsts-tasks#5791]
## Environment
VSTS

## Issue Description

SQLDacPacDeploymentOnMachineGroup has an incorrect tooltip for the exclusive lock property. It refers to running in a transaction.
 
![image](https://user-images.githubusercontent.com/1209963/32514126-f82a7f6c-c3f3-11e7-9e28-ea8fe2385569.png)

**Comment by simonsabin** [comment]
I've created a PR for this https://github.com/Microsoft/vsts-tasks/pull/5687

**Comment by bryanmacfarlane** [comment]
Muthu, please review.

**Comment by kmkumaran** [comment]
@simonsabin - I have left comment in the PR.

**Comment by kmkumaran** [comment]
@simonsabin - Thanks for the contribution. I have merged your PR.
