### ISSUE TITLE
Question: Any plans for an Azure Application Gateway task?

### ISSUE THREAD

**Issue by CodedBeard** [Microsoft/vsts-tasks#5812]
Before I go writing one myself, just thought I'd ask if there are any plans for an Azure application gateway task?

Here's a brief description of the use case:
We are currently migrating various legacy sites, to run as containers on Service Fabric. The build and release of these solutions is fully automated via VSTS with the one exception, that if a new container is added to the solution, then an Azure Admin must manually update the application gateway with the new path rule mappings etc.

What I'm thinking, is that a vsts task could use the information in the docker-compose files, to automate this procedure, so that new projects will be automatically mapped, without having to involve manual steps.

**Comment by chrisrpatterson** [comment]
@CodedBeard  we have a generic Azure PowerShell and Azure CLI task that would be a good place to start.

**Comment by RoopeshNair** [comment]
We do have plans to add Application Gateway feature, however, it is fairly low on our backlog (>6 months).

**Comment by CodedBeard** [comment]
Thanks @RoopeshNair, I'll have a go at making one myself in that case.
