### ISSUE TITLE
jenkins tfs plugin receives null as a commit id when triggered via jenkins service hook "code pushed"

### ISSUE THREAD

**Issue by morgwai** [Microsoft/vsts-tasks#5814]
## Environment
Server: VSTS
account name: morgwai@2clicksolutions.onmicrosoft.com
team project name: Morgwai-Test-Agile
trigger Sent at: Thursday, November 9, 2017 12:06:49 PM

## Issue Description

I am unable to determine if it's wrong request parsing on jenkins-plugin side or wrong request from vsts side: I will fill this bug for both.

### Request:

Method: POST
URI: https://devmaster.saigon.2clicksolutions.com/jenkins/team-build/build/tfs-test
HTTP Version: 1.1
Headers:
{
  Authorization: Basic ********
  Jenkins-Crumb: 56b5bdc1c5d6932f31811dc03211a29d
  Content-Type: application/x-www-form-urlencoded
}
Content:
json=%7B%22team-event%22%3A%7B%22id%22%3A%22483b5e54-dc12-429e-a5be-6bc575cec1f8%22%2C%22eventType%22%3A%22git.push%22%2C%22publisherId%22%3A%22tfs%22%2C%22message%22%3A%7B%22text%22%3A%22Piotr+Morgwai+Kotarbinski+pushed+updates+to+Morgwai-Test-Agile%3Amaster%5Cr%5Cn(https%3A%2F%2F2cs.visualstudio.com%2F_git%2FMorgwai-Test-Agile%2F%23version%3DGBmaster)%22%2C%22html%22%3A%22Piotr+Morgwai+Kotarbinski+pushed+updates+to+%3Ca+href%3D%5C%22https%3A%2F%2F2cs.visualstudio.com%2F_git%2FMorgwai-Test-Agile%2F%5C%22%3EMorgwai-Test-Agile%3C%2Fa%3E%3A%3Ca+href%3D%5C%22https%3A%2F%2F2cs.visualstudio.com%2F_git%2FMorgwai-Test-Agile%2F%23version%3DGBmaster%5C%22%3Emaster%3C%2Fa%3E%22%2C%22markdown%22%3A%22Piotr+Morgwai+Kotarbinski+pushed+updates+to+%5BMorgwai-Test-Agile%5D(https%3A%2F%2F2cs.visualstudio.com%2F_git%2FMorgwai-Test-Agile%2F)%3A%5Bmaster%5D(https%3A%2F%2F2cs.visualstudio.com%2F_git%2FMorgwai-Test-Agile%2F%23version%3DGBmaster)%22%7D%2C%22detailedMessage%22%3A%7B%22text%22%3A%22Piotr+Morgwai+Kotarbinski+pushed+a+commit+to+Morgwai-Test-Agile%3Amaster%5Cr%5Cn+-+Merged+PR+1110%3A+README%3A+point+1+614d5383+(https%3A%2F%2F2cs.visualstudio.com%2F_git%2FMorgwai-Test-Agile%2Fcommit%2F614d5383a3953bee58c997215e65aed570863461)%22%2C%22html%22%3A%22Piotr+Morgwai+Kotarbinski+pushed+a+commit+to+%3Ca+href%3D%5C%22https%3A%2F%2F2cs.visualstudio.com%2F_git%2FMorgwai-Test-Agile%2F%5C%22%3EMorgwai-Test-Agile%3C%2Fa%3E%3A%3Ca+href%3D%5C%22https%3A%2F%2F2cs.visualstudio.com%2F_git%2FMorgwai-Test-Agile%2F%23version%3DGBmaster%5C%22%3Emaster%3C%2Fa%3E%5Cr%5Cn%3Cul%3E%5Cr%5Cn%3Cli%3EMerged+PR+1110%3A+README%3A+point+1+%3Ca+href%3D%5C%22https%3A%2F%2F2cs.visualstudio.com%2F_git%2FMorgwai-Test-Agile%2Fcommit%2F614d5383a3953bee58c997215e65aed570863461%5C%22%3E614d5383%3C%2Fa%3E%3C%2Fli%3E%5Cr%5Cn%3C%2Ful%3E%22%2C%22markdown%22%3A%22Piotr+Morgwai+Kotarbinski+pushed+a+commit+to+%5BMorgwai-Test-Agile%5D(https%3A%2F%2F2cs.visualstudio.com%2F_git%2FMorgwai-Test-Agile%2F)%3A%5Bmaster%5D(https%3A%2F%2F2cs.visualstudio.com%2F_git%2FMorgwai-Test-Agile%2F%23version%3DGBmaster)%5Cr%5Cn*+Merged+PR+1110%3A+README%3A+point+1+%5B614d5383%5D(https%3A%2F%2F2cs.visualstudio.com%2F_git%2FMorgwai-Test-Agile%2Fcommit%2F614d5383a3953bee58c997215e65aed570863461)%22%7D%2C%22resource%22%3A%7B%22refUpdates%22%3A%5B%7B%22name%22%3A%22refs%2Fheads%2Fmaster%22%2C%22oldObjectId%22%3A%223ecf42cbeb5389bcf7f2aa49beb4a2afd79782a5%22%2C%22newObjectId%22%3A%22614d5383a3953bee58c997215e65aed570863461%22%7D%5D%2C%22repository%22%3A%7B%22id%22%3A%22925d17e0-57a2-40b2-bfc9-411649b92be1%22%2C%22name%22%3A%22Morgwai-Test-Agile%22%2C%22url%22%3A%22https%3A%2F%2F2cs.visualstudio.com%2F_apis%2Fgit%2Frepositories%2F925d17e0-57a2-40b2-bfc9-411649b92be1%22%2C%22project%22%3A%7B%22id%22%3A%227481b0ff-3729-44fb-b442-1bf2d4c0be6b%22%2C%22name%22%3A%22Morgwai-Test-Agile%22%2C%22url%22%3A%22https%3A%2F%2F2cs.visualstudio.com%2F_apis%2Fprojects%2F7481b0ff-3729-44fb-b442-1bf2d4c0be6b%22%2C%22state%22%3A%22wellFormed%22%2C%22visibility%22%3A%22unchanged%22%7D%2C%22defaultBranch%22%3A%22refs%2Fheads%2Fmaster%22%2C%22remoteUrl%22%3A%22https%3A%2F%2F2cs.visualstudio.com%2F_git%2FMorgwai-Test-Agile%22%7D%2C%22pushedBy%22%3A%7B%22id%22%3A%228249ce35-01a7-49cd-80dc-369b8748ab2f%22%2C%22displayName%22%3A%22Piotr+Morgwai+Kotarbinski%22%2C%22uniqueName%22%3A%22morgwai%402clicksolutions.onmicrosoft.com%22%2C%22url%22%3A%22https%3A%2F%2Fapp.vssps.visualstudio.com%2FA2c3c55c6-a65c-4cf4-a068-7769a5b13a3b%2F_apis%2FIdentities%2F8249ce35-01a7-49cd-80dc-369b8748ab2f%22%2C%22imageUrl%22%3A%22https%3A%2F%2F2cs.visualstudio.com%2F_api%2F_common%2FidentityImage%3Fid%3D8249ce35-01a7-49cd-80dc-369b8748ab2f%26t%3D00000000-0000-0000-a0e6-ea706624d508%22%7D%2C%22pushId%22%3A16535%2C%22date%22%3A%222017-11-09T12%3A06%3A33.0024639Z%22%2C%22url%22%3A%22https%3A%2F%2F2cs.visualstudio.com%2F_apis%2Fgit%2Frepositories%2F925d17e0-57a2-40b2-bfc9-411649b92be1%2Fpushes%2F16535%22%2C%22_links%22%3A%7B%22self%22%3A%7B%22href%22%3A%22https%3A%2F%2F2cs.visualstudio.com%2F_apis%2Fgit%2Frepositories%2F925d17e0-57a2-40b2-bfc9-411649b92be1%2Fpushes%2F16535%22%7D%2C%22repository%22%3A%7B%22href%22%3A%22https%3A%2F%2F2cs.visualstudio.com%2F_apis%2Fgit%2Frepositories%2F925d17e0-57a2-40b2-bfc9-411649b92be1%22%7D%2C%22commits%22%3A%7B%22href%22%3A%22https%3A%2F%2F2cs.visualstudio.com%2F_apis%2Fgit%2Frepositories%2F925d17e0-57a2-40b2-bfc9-411649b92be1%2Fpushes%2F16535%2Fcommits%22%7D%2C%22pusher%22%3A%7B%22href%22%3A%22https%3A%2F%2Fapp.vssps.visualstudio.com%2FA2c3c55c6-a65c-4cf4-a068-7769a5b13a3b%2F_apis%2FIdentities%2F8249ce35-01a7-49cd-80dc-369b8748ab2f%22%7D%2C%22refs%22%3A%7B%22href%22%3A%22https%3A%2F%2F2cs.visualstudio.com%2F_apis%2Fgit%2Frepositories%2F925d17e0-57a2-40b2-bfc9-411649b92be1%2Frefs%22%7D%7D%7D%2C%22resourceVersion%22%3A%221.0%22%2C%22resourceContainers%22%3A%7B%22collection%22%3A%7B%22id%22%3A%22e49602b6-8469-48d0-95a5-4477cb406699%22%2C%22baseUrl%22%3A%22https%3A%2F%2F2cs.visualstudio.com%2F%22%7D%2C%22account%22%3A%7B%22id%22%3A%222c3c55c6-a65c-4cf4-a068-7769a5b13a3b%22%2C%22baseUrl%22%3A%22https%3A%2F%2F2cs.visualstudio.com%2F%22%7D%2C%22project%22%3A%7B%22id%22%3A%227481b0ff-3729-44fb-b442-1bf2d4c0be6b%22%2C%22baseUrl%22%3A%22https%3A%2F%2F2cs.visualstudio.com%2F%22%7D%7D%2C%22createdDate%22%3A%222017-11-09T12%3A06%3A37.0099899Z%22%7D%7D

### Response:

Status Code: 201
Reason Phrase: Created
HTTP Version: 1.1
Headers:
{
  X-Content-Type-Options: nosniff
  Date: Thu, 09 Nov 2017 12:06:50 GMT
  Server: Jetty(9.4.z-SNAPSHOT)
  Content-Length: 82
  Content-Type: application/json; charset=utf-8
}

### Event:

    {
    "id": "483b5e54-dc12-429e-a5be-6bc575cec1f8",
    "eventType": "git.push",
    "publisherId": "tfs",
    "message": {
        "text": "Piotr Morgwai Kotarbinski pushed updates to Morgwai-Test-Agile:master\r\n(https://2cs.visualstudio.com/_git/Morgwai-Test-Agile/#version=GBmaster)",
        "html": "Piotr Morgwai Kotarbinski pushed updates to <a href=\"https://2cs.visualstudio.com/_git/Morgwai-Test-Agile/\">Morgwai-Test-Agile</a>:<a href=\"https://2cs.visualstudio.com/_git/Morgwai-Test-Agile/#version=GBmaster\">master</a>",
        "markdown": "Piotr Morgwai Kotarbinski pushed updates to [Morgwai-Test-Agile](https://2cs.visualstudio.com/_git/Morgwai-Test-Agile/):[master](https://2cs.visualstudio.com/_git/Morgwai-Test-Agile/#version=GBmaster)"
    },
    "detailedMessage": {
        "text": "Piotr Morgwai Kotarbinski pushed a commit to Morgwai-Test-Agile:master\r\n - Merged PR 1110: README: point 1 614d5383 (https://2cs.visualstudio.com/_git/Morgwai-Test-Agile/commit/614d5383a3953bee58c997215e65aed570863461)",
        "html": "Piotr Morgwai Kotarbinski pushed a commit to <a href=\"https://2cs.visualstudio.com/_git/Morgwai-Test-Agile/\">Morgwai-Test-Agile</a>:<a href=\"https://2cs.visualstudio.com/_git/Morgwai-Test-Agile/#version=GBmaster\">master</a>\r\n<ul>\r\n<li>Merged PR 1110: README: point 1 <a href=\"https://2cs.visualstudio.com/_git/Morgwai-Test-Agile/commit/614d5383a3953bee58c997215e65aed570863461\">614d5383</a></li>\r\n</ul>",
        "markdown": "Piotr Morgwai Kotarbinski pushed a commit to [Morgwai-Test-Agile](https://2cs.visualstudio.com/_git/Morgwai-Test-Agile/):[master](https://2cs.visualstudio.com/_git/Morgwai-Test-Agile/#version=GBmaster)\r\n* Merged PR 1110: README: point 1 [614d5383](https://2cs.visualstudio.com/_git/Morgwai-Test-Agile/commit/614d5383a3953bee58c997215e65aed570863461)"
    },
    "resource": {
        "refUpdates": [
            {
                "name": "refs/heads/master",
                "oldObjectId": "3ecf42cbeb5389bcf7f2aa49beb4a2afd79782a5",
                "newObjectId": "614d5383a3953bee58c997215e65aed570863461"
            }
        ],
        "repository": {
            "id": "925d17e0-57a2-40b2-bfc9-411649b92be1",
            "name": "Morgwai-Test-Agile",
            "url": "https://2cs.visualstudio.com/_apis/git/repositories/925d17e0-57a2-40b2-bfc9-411649b92be1",
            "project": {
                "id": "7481b0ff-3729-44fb-b442-1bf2d4c0be6b",
                "name": "Morgwai-Test-Agile",
                "url": "https://2cs.visualstudio.com/_apis/projects/7481b0ff-3729-44fb-b442-1bf2d4c0be6b",
                "state": "wellFormed",
                "visibility": "unchanged"
            },
            "defaultBranch": "refs/heads/master",
            "remoteUrl": "https://2cs.visualstudio.com/_git/Morgwai-Test-Agile"
        },
        "pushedBy": {
            "id": "8249ce35-01a7-49cd-80dc-369b8748ab2f",
            "displayName": "Piotr Morgwai Kotarbinski",
            "uniqueName": "morgwai@2clicksolutions.onmicrosoft.com",
            "url": "https://app.vssps.visualstudio.com/A2c3c55c6-a65c-4cf4-a068-7769a5b13a3b/_apis/Identities/8249ce35-01a7-49cd-80dc-369b8748ab2f",
            "imageUrl": "https://2cs.visualstudio.com/_api/_common/identityImage?id=8249ce35-01a7-49cd-80dc-369b8748ab2f&t=00000000-0000-0000-a0e6-ea706624d508"
        },
        "pushId": 16535,
        "date": "2017-11-09T12:06:33.0024639Z",
        "url": "https://2cs.visualstudio.com/_apis/git/repositories/925d17e0-57a2-40b2-bfc9-411649b92be1/pushes/16535",
        "_links": {
            "self": {
                "href": "https://2cs.visualstudio.com/_apis/git/repositories/925d17e0-57a2-40b2-bfc9-411649b92be1/pushes/16535"
            },
            "repository": {
                "href": "https://2cs.visualstudio.com/_apis/git/repositories/925d17e0-57a2-40b2-bfc9-411649b92be1"
            },
            "commits": {
                "href": "https://2cs.visualstudio.com/_apis/git/repositories/925d17e0-57a2-40b2-bfc9-411649b92be1/pushes/16535/commits"
            },
            "pusher": {
                "href": "https://app.vssps.visualstudio.com/A2c3c55c6-a65c-4cf4-a068-7769a5b13a3b/_apis/Identities/8249ce35-01a7-49cd-80dc-369b8748ab2f"
            },
            "refs": {
                "href": "https://2cs.visualstudio.com/_apis/git/repositories/925d17e0-57a2-40b2-bfc9-411649b92be1/refs"
            }
        }
    },
    "resourceVersion": "1.0",
    "resourceContainers": {
        "collection": {
            "id": "e49602b6-8469-48d0-95a5-4477cb406699",
            "baseUrl": "https://2cs.visualstudio.com/"
        },
        "account": {
            "id": "2c3c55c6-a65c-4cf4-a068-7769a5b13a3b",
            "baseUrl": "https://2cs.visualstudio.com/"
        },
        "project": {
            "id": "7481b0ff-3729-44fb-b442-1bf2d4c0be6b",
            "baseUrl": "https://2cs.visualstudio.com/"
        }
    },
    "createdDate": "2017-11-09T12:06:37.009Z"
    }

### jenkins console output:

> Started by user Piotr Morgwai Kotarbinski
> Building on master in workspace /var/lib/jenkins/workspace/tfs-test
>  > git rev-parse --is-inside-work-tree # timeout=10
> Fetching changes from the remote Git repository
>  > git config remote.tfs.url https://2cs.visualstudio.com/_git/Morgwai-Test-Agile # timeout=10
> Fetching upstream changes from https://2cs.visualstudio.com/_git/Morgwai-Test-Agile
>  > git --version # timeout=10
> using GIT_ASKPASS to set credentials tfs token
>  > git fetch --tags --progress https://2cs.visualstudio.com/_git/Morgwai-Test-Agile +refs/heads/*:refs/remotes/tfs/* +refs/pull/*:refs/remotes/tfs-pull/*
>  > git rev-parse null^{commit} # timeout=10
> FATAL: Command "git rev-parse null^{commit}" returned status code 128:
> stdout: null^{commit}
> 
> stderr: fatal: ambiguous argument 'null^{commit}': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> 
> hudson.plugins.git.GitException: Command "git rev-parse null^{commit}" returned status code 128:
> stdout: null^{commit}
> 
> stderr: fatal: ambiguous argument 'null^{commit}': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'
> 
> 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1970)
> 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1938)
> 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1934)
> 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1572)
> 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommand(CliGitAPIImpl.java:1584)
> 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.revParse(CliGitAPIImpl.java:769)
> 	at hudson.plugins.git.GitAPI.revParse(GitAPI.java:316)
> 	at hudson.plugins.git.RevisionParameterAction.toRevision(RevisionParameterAction.java:98)
> 	at hudson.plugins.git.GitSCM.determineRevisionToBuild(GitSCM.java:1007)
> 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1124)
> 	at hudson.scm.SCM.checkout(SCM.java:495)
> 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1212)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:566)
> 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
> 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:491)
> 	at hudson.model.Run.execute(Run.java:1737)
> 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
> 	at hudson.model.ResourceController.execute(ResourceController.java:97)
> 	at hudson.model.Executor.run(Executor.java:421)

**Comment by morgwai** [comment]
an interesting detail is that when I test the trigger it works correctly and build on Jenkins succeeds:
![codepushedtest](https://user-images.githubusercontent.com/1413602/32611927-786534be-c599-11e7-9dd9-be5e8fd77a62.png)

**Comment by jpricketMSFT** [comment]
I don't think this bug is related to the jenkins tasks, so this isn't a great spot for it. But we did see it. I will try this out today and try to update the issue with my results.

**Comment by morgwai** [comment]
Thanks for your reply, Jason!
Would you be able to recommend a better place where I could file this bug (and 5813) to get better reception? I'm new to TFS/VSTS and couldn't figure out a better place myself.

Thanks!

**Comment by jpricketMSFT** [comment]
The Jenkins tfs-plugin repo is here: https://github.com/jenkinsci/tfs-plugin 
But all Jenkins plugin issues are tracked in Jira. You can see the tfs-plugin issues here:
https://issues.jenkins-ci.org/browse/JENKINS-47047?jql=project%20%3D%20JENKINS%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20component%20%3D%20%27tfs-plugin%27

But to be honest, this repository is way more active than the tfs-plugin repo. So, I am not surprised to see issues pop up here where the tasks live.

Thanks for providing all the detailed information. Hopefully, we can address the issues soon.

**Comment by morgwai** [comment]
yeah, as I wrote in the initial post I intended to file a bug in jenkins Jira also. I couldn't do it earlier because of connection problems, but [here it is finally](https://issues.jenkins-ci.org/browse/JENKINS-47925).

Thanks for looking into this! :)

**Comment by jpricketMSFT** [comment]
This is issue is being tracked in Jira now (see link above). So, I am closing the issue here.

**Comment by minherz** [comment]
@morgwai can you elaborate about Jenkins job configuration? I try using pipeline job and cannot get access to the payload in any form.
