### ISSUE TITLE
.NET Framework 4.7.1 not available on the Hosted (VS2017) build

### ISSUE THREAD

**Issue by cilerler** [Microsoft/vsts-tasks#5816]
When will you roll .NET Framework 4.7.1?

## Environment
VSTS

## Issue Description

Visual Studio Build

### Error logs
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\amd64\Microsoft.Common.CurrentVersion.targets(1122,5): Error MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.7.1" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
```

[reference](https://developercommunity.visualstudio.com/content/problem/135243/net-framework-471-not-available-on-the-hosted-vs20.html)

**Comment by Mike-EEE** [comment]
FWIW, also reported here:
https://developercommunity.visualstudio.com/content/problem/135243/net-framework-471-not-available-on-the-hosted-vs20.html

**Comment by bryanmacfarlane** [comment]
Not a task issue.  We will track via the developer community issue.
