### ISSUE TITLE
Inline SQL Script doesn't work on 2017 Hosted Agent

### ISSUE THREAD

**Issue by jrr** [Microsoft/vsts-tasks#5817]
We're using the _Azure SQL Database Deployment_ task's "Inline SQL Script" in a few build definitions.

https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/SqlAzureDacpacDeployment/README.md

This worked on the "Hosted" queue, but fails on the "Hosted 2017" queue:

```
==============================================================================
Task         : Azure SQL Database Deployment
Description  : Deploy Azure SQL DB using DACPAC or run scripts using SQLCMD
Version      : 1.1.23
Author       : Microsoft Corporation
Help         : [More Information](https://aka.ms/sqlazuredeployreadme)
==============================================================================
tempFile= d:\a\_temp\tmp6EE1.tmp
Invoke-Sqlcmd -ServerInstance (snip) -Inputfile "d:\a\_temp\tmp6EE1.tmp" -QueryTimeout 600 -ConnectionTimeout 120
SQL Powershell Module is not installed on your agent machine. Please follow steps given below to execute this task
1. Install PowershellTools & SharedManagementObjects(dependency), from https://www.microsoft.com/en-us/download/details.aspx?id=52676 (2016)
2. Restart agent machine after installing tools to register Module path updates
3. Run Import-Module SQLPS on your agent Powershell prompt. (This step is not required on Powershell 3.0 enabled machines)
The term 'Invoke-Sqlcmd' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
******************************************************************************
```

**Comment by rokmicrosoft** [comment]
@jrr 
On Hosted VS 2017 pool SQL client tools are missing.  

Invoke-SqlCmd cmdlet is not included as part of Windows Powershell, but instead it is of sqlps(SQL Server PowerShell Host). So we need to install client tool for it in VS 17 hosted agent. 

I will suggest you to try with Hosted agent pool till issue will be fixed. 

Thanks,
Roshan Kumar

**Comment by ggirard07** [comment]
Any updates about that?

I tried the workaround of using the Hosted agent queue, but the version of AzurePS is too old and missing cmdlet updates I need.

**Comment by jrr** [comment]
@ggirard07 while we wait for this, we're using `sqlcmd.exe` directly from a _Command Line_ task. It can be found on the 2017 hosted agents in `C:\Program Files\Microsoft SQL Server\110\Tools\Binn`; you can add it to `$PATH` with a _Batch Script_ task (with _Modify Environment_).

Gross, huh? I hope we can remove this hack soon!

**Comment by ggirard07** [comment]
@jrr thanks for the tip.
Is there any reason why you don't directly reference the the `sqlcmd.exe` instead of adding it to the path?

**Comment by Izzmo** [comment]
My solution was to split my release (or build) into 2 agent phases as a workaround.

**Comment by bryanmacfarlane** [comment]
@Izzmo - that shouldn't be necessary correct?  Are you splitting into phases because you're adding to the path?  If your script just declares the path and references it directly as @ggirard07 mentioned, wouldn't that be the simplest workaround?

**Comment by Izzmo** [comment]
@bryanmacfarlane Sorry I posted this in haste. Let me explain a little better.

My situation is that I needed to have a VS2017 agent and call out to Azure to create a Azure SQL server. Since the CLI doesn't support cross-subscription database copies, I need to run a inline SQL command to do the copy. _With the 2017 agent, it doesn't have the SQL tools installed apparently._ BUT, with the regular Hosted agents, it is installed but the Azure CLI tools are not.. ugh.

So, I have a two-phase setup where I'm running my tasks on VS 2017 and then a second phase on a regular Hosted agent for the SQL task.

**Comment by ggirard07** [comment]
2 phases releases wasn't  possible for me as cross phases variables are not supported it, except with yaml.

I was able to reference `sqlcmd.exe` directly by using the path provided by @jrr.
My script is executed properly and firewall seems to not be an issue finally...

**Comment by rajatagrawal-dev** [comment]
The required SQL powershell modules have been installed in Hosted VS2017 agents.

**Comment by rajatagrawal-dev** [comment]
Please reopen in case you still face this issue.

**Comment by ggirard07** [comment]
do you have the agent version including it?

**Comment by rajatagrawal-dev** [comment]
Hosted pools have the latest versions only. You can check it by going to the agent capabilities. I think it is 2.126.0.

**Comment by tank104** [comment]
We are stilling having this issue with Hosted Agent  2.131.0 .  We can't use this:
Import-Module SQLPS

**Comment by KrishnaAdityaB** [comment]
@tank104  can you try using SqlServer module instead?

I verified that SQLPS module is available on Hosted VS2017 agent versioned 2.131.0.
I believe, in your case, the error was not thrown with the line 'Import-Module SQLPS'. It might be a command that you are using after this. 
Apparently, there is a known issue with SQLPS module - [Refer](https://stackoverflow.com/questions/47890288/sqlascmdlets-was-not-loaded-because-no-valid-module-file-was-found-in-any-module)

Anyway, SQLPS module is not updated anymore. SqlServer module can be used instead. [Refer](https://docs.microsoft.com/en-us/sql/powershell/download-sql-server-ps-module?view=sql-server-2017).
You can use this module on Hosted VS2017 agent using below script.
```
Write-Host "installing modules: start"
Install-Module -Name SqlServer -Force -AllowClobber
Write-Host "installing modules: end"

Write-Host "getting modules list: start"
Get-Module SqlServer -ListAvailable
Write-Host "getting modules list: end"

Write-Host "listing commands: start"
Import-Module -Name SqlServer
Get-Command -Module SqlServer
Write-Host "listing commands: end"
```

**Comment by tank104** [comment]
Thanks I will try that shortly and get back to you.

**Comment by tank104** [comment]
That worked thanks - although the "Install-Module -Name SqlServer -Force -AllowClobber" takes quite a while.  Will that have to run each time?

**Comment by Izzmo** [comment]
@tank104 I run into this from time to time (seems like every time I restart my PC).

After you install it once, it goes pretty fast, even if it says the module isn't available.

**Comment by KrishnaAdityaB** [comment]
@tank104 Yes, you have to run it each time if you are using Hosted Agent Pool. In Hosted Agent Pool, for each run, the agents are freshly spin up from base image.

**Comment by KrishnaAdityaB** [comment]
@Izzmo You seems to use private agent. On private agents, you need not run this each time.
