### ISSUE TITLE
Using 1.* version of NPM Task cause pointing to depreciated version of npm/3.10.10

### ISSUE THREAD

**Issue by imaterek** [Microsoft/vsts-tasks#5827]
## Troubleshooting
The NPM version has been upgraded to 5.4.2 (VMs restarted). 
For version 1.* there is taken old version of NPM: 3.10.10. 
For version 0.* there is taken the valid one that is 5.4.2,

## Environment
- Server - VSTS
- Agent - Private, both: WS 2012 R2 and WS 2016, Agent Version: 2.120.2.

### Output logs
From 1.*:
"npm config ls -l" to show all defaults.
[command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files\nodejs\npm.cmd" -v"
3.10.10

From 0.* (proper):
C:\Program Files\nodejs\npm.cmd config list
; cli configs
user-agent = "npm/5.4.2 node/v6.10.0 win32 x64"
; "npm config ls -l" to show all defaults.
C:\Program Files\nodejs\npm.cmd -v
5.4.2

**Comment by keithrob** [comment]
@imaterek, 
You should use the "Node Tool Installer" ahead of the NPM step in your build to pick the version of NPM that you want to use.  The tool installer will fetch the appropriate version and subsequent steps will use it.
Keith
