### ISSUE TITLE
Ability to tag repository upon successful build

### ISSUE THREAD

**Issue by cilerler** [Microsoft/vsts-tasks#5829]
## Environment
VSTS Hosted 2017

## Issue Description
Right now, we can only tag if the repository is on VSTS.  
Please provide a mechanism for GitHub too.

Thanks in advance 🤗

**Comment by bryanmacfarlane** [comment]
Not an issue with one of the tasks in this repo.  Create an issue in developer community

**Comment by cilerler** [comment]
@bryanmacfarlane what do you mean it is not a task issue?  Place I marked with red rectangle is not available in GitHub repositories (2) but VSTS (1).  Are you sure, this should be an community issue?  If not please re-open it.

![image](https://user-images.githubusercontent.com/385958/32726826-6254c296-c848-11e7-9b7c-844390760bae.png)

**Comment by bryanmacfarlane** [comment]
Tagging sources is a service side action.  

The issues in this repo track issues with tasks in this repo.  One of these https://github.com/Microsoft/vsts-tasks/tree/master/Tasks

**Comment by cilerler** [comment]
Incase anyone wants to upvote this request [click here](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/32238553-ability-to-tag-label-repository-upon-successful-bu)
