### ISSUE TITLE
Set Azure Subscription as variable failure in VSTS

### ISSUE THREAD

**Issue by PaulConwayArk** [Microsoft/vsts-tasks#5830]
## Environment
VSTS -Releases

## Issue Description
I would like to set subscriptions & app services as variables in the AzureRmWebAppDeployment task, as I would like to use the Muli-Config feature VSTS has implemented to deploy to multiple environments.

I have placed the respective variables in both the Azure Subscription & App Service name but with no success. I have tried both the ID's and the name's and I am getting the same error. When looking through the logs of the deploy I can see the variables that I am passing are getting that far but are failing as can be seen in the image.

![image](https://user-images.githubusercontent.com/15887801/32662423-669adaac-c622-11e7-9597-ba399f6ad95c.png)

Is there any reason why this is failing or any workaround to get it to work?

Thanks in advance!

**Comment by niadak** [comment]
@PaulConwayArk , Can you please create a Azure ARM Service endpoint with your azure subscription and use the service endpoint name as variable? You can go to the manage link near Azure Subscription task input to create a service endpoint. I am assuming you are providing your Azure Subscription name as variable.

![image](https://user-images.githubusercontent.com/11937515/32819042-0296f210-c9ed-11e7-8cea-00348914e746.png)

**Comment by PaulConwayArk** [comment]
Hi @niadak ,

Thanks very much for getting back to me. I have created a service endpoint as mentioned but Now I am getting a new error.
![image](https://user-images.githubusercontent.com/15887801/32886005-3a003796-cab7-11e7-9769-525bd7690f6f.png)

Any recommendations on what causes this issue? I have turn my app offline and renamed any locked files on deployments but still with no success. Here is what my deployment task looks like.

![image](https://user-images.githubusercontent.com/15887801/32886620-251f229a-cab9-11e7-9b85-46c9bb099d1b.png)

Any suggestion would be most welcome,
Thanks!

**Comment by niadak** [comment]
Can you please share the debug logs to RM_Customer_Queries@microsoft.com? On the Variables tab, add system.debug and set it to true and run the release to generate debug logs

**Comment by niadak** [comment]
@PaulConwayArk , Thanks for reaching out to us over email.

We don’t support variable for service endpoint input in task. We are planning to support the scenario using process parameter feature which will be available in future.

**Comment by rajatagrawal-dev** [comment]
Closing this as the process variables feature is under development and will be available in near future.

**Comment by mkhan2016** [comment]
@niadak can we get an update on this please?

**Comment by bobbonham** [comment]
surprising this isn't here. I'll just hard code the endpoint name 20 times, no big deal :/

**Comment by RoopeshNair** [comment]
Supporting for variables in endpoints has the downside of losing traceability. You can however, override an endpoint data using task logging command `##vso[task.setendpoint]value`

For more details refer to [agent logging command](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md)

**Comment by berzns** [comment]
There is a [uservoice](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/17338603-allow-service-connections-to-be-parameterized-in-t) for this.

@RoopeshNair Can you please elaborate?
According to the documentation the syntax has to be as below:
##vso[task.setendpoint id=000-0000-0000;field=authParameter;key=AccessToken]testvalue 

I'm not sure what values I should use in the syntax. What is the ID and Key used in this syntax? ID of the Service endpoint configured in VSTS? What is the Key? Token From AAD when we us SPN for authentication?
Thanks!

**Comment by RoopeshNair** [comment]
You can get the keys for the AzureRm endpoint inputs by querying the endpoint type:
https://{accountName}.visualstudio.com/_apis/serviceendpoint/types?type=AzureRm

The API is documented here:
https://docs.microsoft.com/en-us/rest/api/vsts/serviceendpoint/types/list

id in the command should be set to the endpoint's id (GUID).

subscriptionId & subscriptionName are the keys in AzureRm endpoint's data dictionary.,
servicePrincipalId, servicePrincipalKey, tenantId are the keys in AzureRm endpoint's authorization parameters.

You can try updating the values for these fields using the command.

You would need to invoke 1 command to update 1 field. For e.g. to update servicePrincipalId & servicePrinicipalKey - you need these two commands:
##vso[[task.setendpoint id=<endpoint's id>;field=authParameter;key=servicePrincipalId]
##vso[[task.setendpoint id=<endpoint's id>;field=authParameter;key=servicePrincipalKey]

Here's the sequence of steps just to clarify inorder to update fields of an endpoint AzureEndpoint1 (say) used in a release:

- Create a custom task, UpdateAzureServiceEndpoint (say)
- Take the endpoint to update (AzureEndpoint1 in this case) as an input. Note that the value of this input is the value that would have to be passed for the "id" in the command.
- Take the new values to update as input. This is not required if the task would be able to compute the new values.
- From within UpdateAureServiceEndpoint task, invoke the command(s) to update the value of the fields.
- Hope that clarifies.

**Comment by KZeronimo** [comment]
@RoopeshNair - I've been looking at this issue and would like to ask you for some more specifics - a screenshot or two would be helpful

Ideally, we could run this task once at the top of a pipeline and the remaining tasks that require Azure Subscription as input would be satisfied

**Comment by leo-leong** [comment]
@RoopeshNair task.setendpoint looks to be the command to update the key/url of an endpoint. How is this relevant to changing the service connection from within a task in a given task group?

**Comment by flouwers** [comment]
Any news about the availability of usage of variables for service endpoint ?

Meanwhile, I'm trying to use @RoopeshNair suggested commands (to be used in an inline Powershell task). But I get an error about invalid endpoint ID.
However, I can confirm this is the ID that I see through the REST API.

`2019-02-15T15:00:12.2661001Z ##[error]Unable to process command '##vso[task.setendpoint id=********-****-****-****-************;field=authParameter;key=servicePrincipalId]***' successfully. Please reference documentation (http://go.microsoft.com/fwlink/?LinkId=817296)
2019-02-15T15:00:12.2673810Z ##[error]Invalid endpoint id.`
