### ISSUE TITLE
Default Template for PBI - TFS 2017

### ISSUE THREAD

**Issue by vinaysandela** [Microsoft/vsts-tasks#5844]
Hi, 

I was trying to customize the PBI Template for my project on TFS 2017 and have forgot to save the default-one. 
I have made some changes and doesn't want them. Want to go back to the default one, which was existing on the project. 

Is there anyway, that i can get that? Thanks

**Comment by chrisrpatterson** [comment]
This repo is for vsts build and release tasks.  You should provide your feedback on the developer community site https://developercommunity.visualstudio.com/spaces/21/index.html.
