### ISSUE TITLE
Agentless task: Invoke REST API - Timeout question

### ISSUE THREAD

**Issue by mrducnguyen** [Microsoft/vsts-tasks#5876]
Hi,

I'm having trouble setting up this task. I implemented a REST API to help with our releases. This is a long running task, about 30 seconds normally, but sometimes it's quicker.

I have setup my Agentless Invoke REST API as following

<img width="858" alt="invokerestapi" src="https://user-images.githubusercontent.com/4490596/32876006-d5299104-caee-11e7-836d-ecea8cc533b5.png">

My builds keep failing at this step, Invoke REST API task always timed out at **20 seconds** regardless how much time I put into the Timeout option...

Sometime when the Release API runs in less than 20 seconds then my builds were good.

I have tried to enable Wait for Completion, but that option always behave like this: the task will wait for exactly the amount of time set in the Timeout option, then failed with Timeout Exception, regardless of the REST API call response was successfully received.

Right now I'm looking at writing my own Powershell script to to this task, but I really want to use what was available.

Thanks,

**Comment by pjquirk** [comment]
I believe your assessment is correct.  The REST API call retrieves a timeout value from the system that defaults to 20 seconds, and is not configurable nor really related to the timeout shown in the GUI here.  If/when the REST request times out, the "done" event is never fired so the task will always wait until the timeout shown in the GUI, and then fail because it never got the "done" event.

**Comment by bryanmacfarlane** [comment]
Not an issue with one of the tasks in this repo (what the issues are tracking):  https://github.com/Microsoft/vsts-tasks/tree/master/Tasks

If you're having an issue with the service, you can create something at developer community.

**Comment by bansalaseem** [comment]
Since it is talking about this task, https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/InvokeRestApi, I am reopening the issue.

**Comment by bansalaseem** [comment]
If your task is taking longer than 20 seconds, then you should consider calling back VSTS using the code snippet shared [here](https://blogs.msdn.microsoft.com/aseemb/2017/12/18/async-http-agentless-task/)

**Comment by mrducnguyen** [comment]
Thanks for your information.

I will need to call back to VSTS from our environment using PHP, I guess I can only use the JSON REST API. Can you link me to the REST APIs equivalent to the .NET library used in your snippet?

Much appreciate!

**Comment by mrducnguyen** [comment]
@bansalaseem  I have tried to 'reverse engineer' the package you linked in your blog post, I've reached to getting the resource using resource locator, but then sub-sequence calls always returned 500 Internal Server error from VSTS.

I also tried both this [https://github.com/Microsoft/vsts-rm-extensions/tree/master/ServerTaskHelper](library) and your code snippet with values on our VSTS task (extract from requestb.in), which returned the same 500 error.

Any ideas with this error?

Here's my Controller

```csharp
public ActionResult SendLog([FromBody] List<string> messages)
{
    BuildTaskProperties taskProperties;
    taskProperties = GetTaskProperties(Request.Headers);

    string hubName = "release";
    VssConnection connection = new VssConnection(new Uri(taskProperties.VstsUrl), new VssBasicCredential("username", taskProperties.AuthToken));
    var taskClient = connection.GetClient<TaskHttpClient>();

    taskClient.AppendTimelineRecordFeedAsync(
        taskProperties.ProjectId, 
        hubName, 
        taskProperties.PlanId, 
        taskProperties.TimelineId, 
        taskProperties.JobId, 
        new VssJsonCollectionWrapper<IEnumerable<string>>(messages)
    ).SyncResult(); //always throw VssResponseException - Internal Server Error

    // Send task completion event
    taskClient.RaisePlanEventAsync(
        taskProperties.ProjectId, 
        hubName, 
        taskProperties.PlanId, 
        new TaskCompletedEvent(taskProperties.JobId, taskProperties.JobId, TaskResult.Succeeded)
    ).SyncResult();

    return new JsonResult(new {
        message = String.Format("I received [{0}] messages: {1}", messages.Count, String.Join(", ", messages)),
        taskProperties
    });
}

private static BuildTaskProperties GetTaskProperties(IHeaderDictionary headerDictionary)
{
    var taskProperties = new BuildTaskProperties();

    taskProperties.GetType().GetProperties()
        .Where(pi => headerDictionary.ContainsKey(pi.Name))
        .ToList().ForEach(pi => {
            if (pi.PropertyType.Equals(typeof(Guid))) {
                pi.SetValue(taskProperties, Guid.Parse(headerDictionary[pi.Name]), null);
            } else {
                pi.SetValue(taskProperties, headerDictionary[pi.Name].ToString(), null);
            }
        });

    return taskProperties;
}
```

`BuildTaskProperties` is just a simple model

```csharp
public class BuildTaskProperties
{
    public Guid JobId {
        get; set;
    }

    public Guid PlanId {
        get;set;
    }

    public Guid TimelineId {
        get; set;
    }

    public Guid ProjectId {
        get;set;
    }

    public string VstsUrl {
        get;set;
    }

    public string AuthToken {
        get;set;
    }
}
```

And this is my project reference

```xml
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.3"/>
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="5.2.4-preview1"/>
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.2.4-preview1"/>
    <PackageReference Include="Microsoft.TeamFoundation.DistributedTask.Common.Contracts" Version="16.118.0-preview"/>
    <PackageReference Include="Microsoft.TeamFoundation.DistributedTask.WebApi" Version="15.127.0-preview"/>
    <PackageReference Include="Microsoft.VisualStudio.Services.Client" Version="16.118.0-preview"/>
    <PackageReference Include="Microsoft.VisualStudio.Services.Release.Client" Version="15.127.0-preview"/>
    <PackageReference Include="System-Web-Helpers.dll" Version="1.0.1"/>
```

**Comment by bansalaseem** [comment]
suresh, can you please take a look at the code?

**Comment by sureshtadisetty** [comment]
@mrducnguyen, request you to also paste Headers you've defined for this failing Invoke REST API task in your ReleaseDefinition.
Also, do you see any error detail other than Internal Server Error?

**Comment by bansalaseem** [comment]
Since @mrducnguyen has not come back, I am marking the issue as closed.

**Comment by mrducnguyen** [comment]
Hi, sorry for my late response

@sureshtadisetty not really sure what you mean by Headers. What I did was just copy/paste sample codes from the provided GitHub, testing against a simple Invoke REST API Task configured as a step in my build. Also, there is no additional error message apart from "Internal Server error"

I long have switched to PowerShell script to invoke my REST API, even use a loop to wait for server release process result, so it's all good for me now.

Also, I think the default "20 second timeout" including the time to set-up the task, which leaves the real-working part, i.e. the real invocation of the REST API, [much] less than 20 seconds to wait for a response. It's just a "smoke" observation of the task, not basing on concrete code investigation so I could be wrong.
