### ISSUE TITLE
Error on WebDeploy to isolated ASE in Azure

### ISSUE THREAD

**Issue by youngcm2** [Microsoft/vsts-tasks#5883]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises? VSTS
    
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private:  Private
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
      Private
Agent.OS | Windows_NT
Agent.OSVersion | 10.0.14393
Agent.Version | 2.120.2

## Issue Description

##[warning]Error: Hostname/IP doesn't match certificate's altnames:

It will work when I deploy it again. I have the switch -allowUntrusted in the additional arguments.

### Error logs

##[warning]Error: Hostname/IP doesn't match certificate's altnames:
I am unable to give the full logs in public.

**Comment by niadak** [comment]
Hi youngcm2, Can you please share the debug logs to RM_Customer_Queries@microsoft.com? On the Variables tab, add system.debug and set it to true and run the release to generate debug logs

**Comment by niadak** [comment]
Hi youngcm2,If you dont want to use  -allowUntrusted option, we have to install a ASE certificate on the agent machine to make it worked. Please follow the steps in below link to create and install a ASE certificate.
https://docs.microsoft.com/en-us/azure/app-service/environment/app-service-environment-with-internal-load-balancer

https://docs.microsoft.com/en-us/azure/app-service/environment/create-ilb-ase

**Comment by rajatagrawal-dev** [comment]
Hi @youngcm2 
If you are still facing the issue please send the debug logs to  RM_Customer_Queries@microsoft.com

**Comment by rajatagrawal-dev** [comment]
Please reopen if you face the issue again.

**Comment by davidlbyrne** [comment]
I am facing this same issue with a self signed cert. Can you please help?

**Comment by vincentdass** [comment]
Closing the issue as the recommendation is provided in logs and there is no response from customer.
**Summary**
When Self-signed certificate is used for App Services configured under App Service Environment, App Services tasks fails with SSL error. The recommendation is to install appropriate certificate from CA in the agent machine.
However , if  you want to ignore SSL error, set variable `VSTS_ARM_REST_IGNORE_SSL_ERRORS` to `true` and pass `-allowUntrusted` in additional arguments of `Web Deploy` option.
[[Reference]](https://blogs.msdn.microsoft.com/mihansen/2018/01/04/continuous-deployment-with-vststfs-and-app-service-environment-ase/)
