### ISSUE TITLE
Try to change RunDistributedTests to run all tests on all machines

### ISSUE THREAD

**Issue by LokiMidgard** [Microsoft/vsts-tasks#5888]
We try to run all our test on multiple machines in parrallel.
Currently the task Run Functional Tests only supports partitionating the tests on different machines.

You can use a comma seperated list of machines and the test will run on those. If you have two machines and 10 tests, 5 will be run on one machine and 5 on the other.

We looked into the PowerShell script and found this code

```posh
          Invoke-RunDistributedTests -TestMachineGroup $testMachineGroup -SourceFilter "*.dll" -TestCaseFilter $testFilterCriteria -RunSettingsPath $runSettingsFile -Platform $platform -Configuration $configuration -CodeCoverageEnabled $codeCoverageEnabled -TestRunParams $overrideRunParams -TestDropLocation $dropLocation -Connection $connection -TestConfiguration $testConfigurations -AutMachineGroup $autMachineGroup -UnregisterTestAgentScriptLocation $unregisterTestAgentScriptLocation -TestRunTitle $testRunTitle -TestSelection $testSelection -TestPlan $testPlanId -TestSuites $testSuites -TestConfig $testConfigurationId -TaskContext $distributedTaskContext -CheckTestAgentCompatScriptLocation $checkTaCompatScriptLocation -CustomSlicingEnabled $customSlicingEnabledFlag
```

This method get the comma seperated list of machines and starts the tests.

The idea now was to write our own task that instead of calling Invoke-RunDistributedTests with all machines, call it only with one machine but multiple times:

```posh
            $machines=  $testMachineGroup.Split(',');
            foreach ($currentTestMachineGroup in $machines) {
                Invoke-RunDistributedTests -TestMachineGroup $currentTestMachineGroup -SourceFilter "*.dll" -TestCaseFilter $testFilterCriteria -RunSettingsPath $runSettingsFile -Platform $platform -Configuration $configuration -CodeCoverageEnabled $codeCoverageEnabled -TestRunParams $overrideRunParams -TestDropLocation $dropLocation -Connection $connection -TestConfiguration $testConfigurations -AutMachineGroup $autMachineGroup -UnregisterTestAgentScriptLocation $unregisterTestAgentScriptLocation -TestRunTitle $testRunTitle -TestSelection $testSelection -TestPlan $testPlanId -TestSuites $testSuites -TestConfig $testConfigurationId -TaskContext $distributedTaskContext -CheckTestAgentCompatScriptLocation $checkTaCompatScriptLocation -CustomSlicingEnabled $customSlicingEnabledFlag
            }
```
however this does not work.

Testing around with the parameter we found out, that if we call the cmdlet only once with one machine, it still use all machines listed from the task. We also tried to overide the parameter hardcoded in the ps script. But this also didn't change the behavior.

If we set the variable machines in the task to ```Outlook2010,Outlook2013``` (both machine names)
and the first line the script is ```$testMachineGroup = 'Outlook2013'```  then the tests will still be executed on ```Outlook2010```. But if we change the variable in the task to ```Outlook2013``` it will only execute on Outlook2013.

We don't understand where the cmdlet finds the list of machines.

The build agent runs on a Windows Server 2016, the original version of the Functional Test Run was 1.0.52. The machines running the tests are Windows 7. We are using a on-premise TFS of 2017

**Comment by nigurr** [comment]
@LokiMidgard Hi, Currently it's not possible to extend the Distribution logic. We are addressing some of the custom distribution options and they are being added to VsTest task.
Please refer this blog for more information: https://blogs.msdn.microsoft.com/devops/2017/03/26/vstest-task-dons-a-new-avatar-testing-with-unified-agents-and-phases/#FAQ
