### ISSUE TITLE
docker-compose task non-zero exit code does not report as failed

### ISSUE THREAD

**Issue by jhgoodwin** [Microsoft/vsts-tasks#5891]
## Troubleshooting
Checked for alternate preview version of the docker-compose command vsts task, but did not see any.
Tried both docker-compose execute command "up" and also the "run services" (which maps to up). Both have the same issue.

## Environment
- Server - `VSTS`
    - account name: `metabolondev`
    - team project name: `Aperture`
    - build definition name/build number: `Aperture - CI / 757`

- Agent - Private:
    - Created using docker command:
```
docker run -d --restart always --name vsts_default_a1 -e VSTS_ACCOUNT=metabolondev -e VSTS_TOKEN=**** -e VSTS_AGENT=a1 -e VSTS_POOL=Default -e USER=root -e VSTS_WORK=/var/vsts --log-opt max-size=5m -v /var/run/docker.sock:/var/run/docker.sock -v /var/vsts:/var/vsts microsoft/vsts-agent:ubuntu-16.04-docker-17.03.0-ce-standard
```

## Issue Description

Docker-Compose task:
![image](https://user-images.githubusercontent.com/2154552/32954782-12487dd2-cb82-11e7-9acb-82f957c2295a.png)

Nothing fancy, just trying to run:
```docker-compose -f ./docker-compose.ci.build.yaml up```

Content of that file is:

```version: '2'

services:
  ci-build:
    image: node:8.9.1
    volumes:
      - .:/root/src
      - ${HOME}/.cache:/usr/local/share/.cache
    environment:
      - CI=1
      - USER=${USER}
    working_dir: /root/src
    command: /bin/bash -c "yarn install && yarn lint && yarn test:cover && yarn build"
```
![screenshot from 2017-11-17 10-30-27](https://user-images.githubusercontent.com/2154552/32954976-9dfafba2-cb82-11e7-95c4-e3a6bafa57c7.png)

My problem is the circled parts. Note that the build task failed on the `Install / Test / Build` in the output, but that it did not mark the task as error, and did not stop, but continued to the next task, where it failed due to missing files expected to be generated from the prior step.

Please ignore for now, the control/color codes not being interpreted.

### Error logs

See above.

**Comment by jhgoodwin** [comment]
Not sure if it helps, but I found what I *think* is the code that would need to be changed, but at first glance, it is not obvious to me why it does not return an error:
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Common/docker-common/containerconnection.ts
Ultimately, all the tasks seem to execute through the execCommand found on line 39

**Comment by jhgoodwin** [comment]
Also, it may be worth noting that testing locally, I am able to make this work as expected:
```docker-compose -f docker-compose.ci.build.yml up && echo "Working" || echo "Not working"```
The same scenario shown in my bug report will return from bash as "Not working".

**Comment by jikuma** [comment]
Thanks @jhgoodwin for bringing this up. I am looking into it.

**Comment by jikuma** [comment]
@jhgoodwin Can you share the build log for Install / Test / Build step. Ensure that you set syste.debugger variable as true.
Meanwhile you can use --exit-code-from option of up command.
docker-compose -f ./docker-compose.ci.build.yaml up --exit-code-from ci-build

![image](https://user-images.githubusercontent.com/23053847/33257980-1e7863c0-d37e-11e7-8f2e-30a8b4889a79.png)

**Comment by jhgoodwin** [comment]
Hi @jikuma I have attached a re-run of the build using the original docker-compose argument of just "up", then added per your suggestion, --exit-code-from which did solve the problem.

It just seems strange that the exit code from the docker-compose appears to be non-zero, yet it did not fail.
[With_Exit_From_4_Install  Test  Build.txt](https://github.com/Microsoft/vsts-tasks/files/1507259/With_Exit_From_4_Install.Test.Build.txt)
[No_Exit_From_4_Install  Test  Build.txt](https://github.com/Microsoft/vsts-tasks/files/1507260/No_Exit_From_4_Install.Test.Build.txt)

**Comment by jikuma** [comment]
Docker-compose process does not exit with an error exit code if one of the containers fails. I tried docker-compose up && echo "Working" || echo "Not working". It always printed "Working". Irrespective of container exit code.

This is the reason  --exit-code-from was introduced.
