### ISSUE TITLE
The 2016 feature pack link is dead, please update the README

### ISSUE THREAD

**Issue by marcelloromani** [Microsoft/vsts-tasks#5915]
Context:
https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/SqlAzureDacpacDeployment

The README file links to
https://www.microsoft.com/en-us/download/details.aspx?id=52676

which returns 404.

The feature pack has probably been superseded by the 2017 version, here:

https://www.microsoft.com/en-us/download/details.aspx?id=55992

Update: the 2016 link seems to be working now. Go figure.

**Comment by daveVSTS** [comment]
Sorry it was busted, glad its working now!  Thanks for reporting it and following up.
