### ISSUE TITLE
Nuget Installer/Retore not working behind proxy

### ISSUE THREAD

**Issue by igorguga** [Microsoft/vsts-tasks#5916]
Hi guys,

I'm trying to run a private VSTS build agent behind a proxy, and I'm getting the following error in Nuget Installer and also in Nuget restore tasks:

Error: connect ECONNREFUSED 191.234.179.224:443

The issue [#869](https://github.com/Microsoft/vsts-agent/issues/869) described the same problem, and was closed. But I'm still experiencing the same problem. 

I've configured a .proxy file for the agent, as described [here](https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-windows#qa). After that, the Get Sources task worked, but the Nuget tasks don't. The documentation highlights that the proxy will only work for the agent infrastructure. So I tried to configure a [nuget.config](https://docs.microsoft.com/en-us/nuget/schema/nuget-config-file) file, with proxy information and put it besides the nuget.exe in tools directory in the agent folder, but I got the same error again.  

Have this issue been fixed? Are there any workarounds?

**Comment by igorguga** [comment]
Hi, I've successfully make it run after I created a system environment variable "http_proxy".
Is this the recommended solution?

**Comment by keithrob** [comment]
Assuming you set that variable on the NuGet build step, it would be passed to nuget.exe which would use it.  However, I'm curious how your agent talks back to the mothership without you configuring it to use your corporate proxy as defined [here](https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/proxy?tabs=windows).

If you follow [these](https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/proxy?tabs=windows) instructions you shouldn't need to do http_proxy.

**Comment by RoadTrain** [comment]
@keithrob What if proxy is only required to access external websites, like nuget.org?
TFS server, on the other hand, is accessible without proxy in the intranet.
What is the recommended way to set proxy creds for the task?
Setting VSTS_HTTP_PROXY, VSTS_HTTP_PROXY_USERNAME and VSTS_HTTP_PROXY_PASSWORD variables?

**Comment by keithrob** [comment]
@RoadTrain ,
Can you try setting a build step specific variable, http_proxy or https_proxy, for the tool installer?  
Keith

**Comment by amritathakur** [comment]
@igorguga Did you just add "http_proxy" variable in the environment variable? I was getting "ERR:tunneling socket could not be established, statusCode=407" before setting the environment variable. After setting http_proxy, I get this error "ERR:tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 8080 8080:80"
The proxy looks fine as the Get source task completes successfully and it fails in NuGet Tool Installer task. 
Any clue what's missing here? 
![image](https://user-images.githubusercontent.com/16161298/40144562-31239218-59b3-11e8-973b-d6f16a88acc3.png)

**Comment by nilaybhima** [comment]
I am having the same issue as @amritathakur. Anyone managed to resolve this?
