### ISSUE TITLE
Powershell on Target Machines not failing on write error or ##vso[task.logissue type=error]

### ISSUE THREAD

**Issue by Onefox** [Microsoft/vsts-tasks#5920]
The Build task does not fail when it should.

This is the powershell code:
https://pastebin.com/njhMFwAp

Is there another way to make the Release Task Fail?

## Environment
- VSTS Release process

- Agent Private:
 Windows 2012 R2 

## Issue Description

Powershell on Target Machines Version 2.*

### Error logs
https://pastebin.com/eUFiW0jb

**Comment by niadak** [comment]
@Onefox , Can you please try Write-Error 'Error Message test1.' instead of Write-Verbose "##vso[task.logissue type=error] Error Message test1". For me the task is failing with Write-Error.

**Comment by Onefox** [comment]
Hi @niadak  i tried
```powershell
Write-Verbose "##vso[task.logissue type=error] Error Message test1"
Write-Error "##vso[task.logissue type=error] Error Message test2"
Write-Error "Error Message test3"
```

But only the Verbose command is getting printed to the vsts log as before. All other lines are not displaied and the build task ist still not failing.

**Comment by niadak** [comment]
I guess $ErrorActionPreference is set to "SilentlyContinue" in your script. Can you please add $ErrorActionPreference = "Stop" in the script and try again?

**Comment by Onefox** [comment]
I changed it to:
```powershell
$ErrorActionPreference="Stop"
Write-Verbose "##vso[task.logissue type=error] Error Message test1"
Write-Error "##vso[task.logissue type=error] Error Message test2"
Write-Error "Error Message test3"
```

Without success...

**Comment by niadak** [comment]
@Onefox , I am not sure why adding $ErrorActionPreference="Stop" is not working, may be there are some other global policy is overwriting the settings.

Can you please try throw "Error Message test3"? This should unblock you.

**Comment by Onefox** [comment]
I changed it to:
```powershell
$ErrorActionPreference="Stop"
Write-Verbose "##vso[task.logissue type=error] Error Message test1"
Write-Error "##vso[task.logissue type=error] Error Message test2"
Write-Error "Error Message test3"
throw "Error Message test4"
```
again without success.

A little bit about the the total process.
I have two Powershell on target machine scripts running. 
Deploy and Undeploy.
![Release Tasks](https://i.imgur.com/ngQrcFe.png)


The deployment fails, because Undeployment didn't finish in the first place...

**Comment by rajatagrawal-dev** [comment]
@Onefox I tried a similar setup as yours with 2 powershell on target machine tasks. The first task contained the script in your previous post and the second task was just a normal hello world task. For me the release failed on the first task, as it should. The second did not get executed.

Can you share the debug logs of your release? To get the debug logs just add a variable _system.debug_ and set its value to _true_ and then queue another release. That should give you the debug logs.\

**Comment by Onefox** [comment]
Here is the full log:
https://pastebin.com/ax4tzaCw
I removed some personal information.

I will also try out the setup you have tried.

**Comment by Onefox** [comment]
There was a try catch some where that only used write-output.... after fixing that the task failed as expected....
Thanks for your time.
