### ISSUE TITLE
Updating to Node JS LTS (8.9.1) makes unit tests fail

### ISSUE THREAD

**Issue by BiribiriJaNai** [Microsoft/vsts-tasks#5921]
## Environment
- Server: None
- Agent: None
- Development environment: 
  - OS: Windows Server 2016 DataCenter 64bits (Azure VM, up to date)
  - Node JS: 8.9.1 LTS
  - npm: 5.5.1
  - VSCode: 1.18.1

## Issue Description
When upgrading to Node JS latest LTS, unit tests are failing due to a Node JS warning, messing up MockTestRunner's stderr and stdout.

## Repro steps
 - clone this repo
 - set the environment variable TASK_TEST_TRACE to 1
- run `npm install`
- run `node make.js build --task AndroidSigning` (as an example)
- run `node make.js test --task AndroidSigning` 

### Workaround
There are some workarounds, but I don't think they are viable in the long run.
 - Downgrade Node to a 6.X version
 - Set the environment variable NODE_NO_WARNINGS to 1

### Error logs
```
##vso[task.debug]agent.TempDirectory=undefined
##vso[task.debug]agent.workFolder=undefined
##vso[task.debug]loading inputs and endpoints
##vso[task.debug]loading INPUT_FILES
##vso[task.debug]loading INPUT_JARSIGN
##vso[task.debug]loading INPUT_ZIPALIGN
##vso[task.debug]loading VSTS_TASKVARIABLE_KEYSTORE_FILE_PATH
##vso[task.debug]loaded 4
##vso[task.debug]Agent.ProxyUrl=undefined
##vso[task.debug]Agent.CAInfo=undefined
##vso[task.debug]Agent.ClientCert=undefined
##vso[task.debug]files=/some/fake.apk
##vso[task.debug]jarsign=false
##vso[task.debug]zipalign=false
##vso[task.debug]looking up mock answers for "findMatch", key '"/some/fake.apk"'
##vso[task.debug]found mock response

STDERR: (node:7424) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7424) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7424) Warning: Use Cipheriv for counter mode of aes-256-ctr
(node:7424) Warning: Use Cipheriv for counter mode of aes-256-ctr
```

**Comment by bryanmacfarlane** [comment]
The android signing task uses the node handler.  The node handler maps to node 6.x which the agent carries.  The agent will never run this task with node 8.  When we support node 8 for tasks, it will be a node 8 handler and the agent will map it properly.
