### ISSUE TITLE
.NET Core Task - Clean up 'Publish test results' to prevent duplicate test results in VSTS

### ISSUE THREAD

**Issue by mikejonestechno** [Microsoft/vsts-tasks#5924]
# dotnet Core Task v2.* (Preview) 
Use "test" command with "Publish test results" check box enabled.
This appends `--logger trx --results-directory $(Agent.TempDirectory)` to the command line arguments.
However the output .TRX files hang around after the results are published to VSTS causing duplicate results when the Task is used more than once.

### Repro Steps
Add a dotnet Core v2.* (Preview) Task
Command = test
Projects = `**/*xUnitTest*.csproj`
Publish test results = enabled

Add a **second** dotnet Core v2.* (Preview) Task
Command = test
Projects = `**/*xIntegrationTest*.csproj`
Publish test results = enabled

### Expected Result
The results of both Tasks are published to VSTS

### Actual Result
The results of both Tasks are published to VSTS but results of the first Task are duplicated in VSTS.

### Action
The publish to VSTS matches all .TRX files in temp directory resulting in duplication when the Task is used more than once.

Deleting the temp .TRX files immediately after publishing them to VTS should solve this issue. 

Alternatively use  `--results-directory $(Agent.TempDirectory)/<uniquefoldername>` so that the publish to VSTS step only publishes the newly created TRX files, ignoring previously generated TRX files in other folders.

**Comment by mikejonestechno** [comment]
@nigurr Please could you help me with this. I think it would be one line code change but am not familiar with the code.

**Comment by nigurr** [comment]
@mikejonestechno 
There are two ways to resolve the issue. 
1. Clean up `Agent.TempDirectory` - before calling the Test command to make sure there are no previous TRX files exists - https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/DotNetCoreCLI/dotnetcore.ts#L95
2. Add an explicit powershell task/cmd task to clean up this folder after dotnet task so that subsequent task don't publish the duplicate trx - temporary workaround.

**Comment by mikejonestechno** [comment]
Thanks nigurr, I might try the temporary workaround so that our builds continue. 

I have not contributed to vsts-tasks before and not confident with the code or even how to check changes work locally. I'm happy to help if I can but I would need a lot of help to get started!

**Comment by nigurr** [comment]
@mikejonestechno https://github.com/Microsoft/vsts-tasks/blob/master/docs/contribute.md is a great place to start. We love to get feedback on getting started and improve this for contributions

**Comment by nigurr** [comment]
Creating a bug to track internally and will be fixed soon. Closing this thread

**Comment by NelsonLamprecht** [comment]
Any status? Hit this today...
