### ISSUE TITLE
Offline test agent deployment error

### ISSUE THREAD

**Issue by darkcite** [Microsoft/vsts-tasks#5927]
## Environment
-    TFS 2017 U2
-    Windows on agent machine: Windows server 2012R2 (with internet access)
-    Windows on target test agent deployment machine: Windows server 2012R2 (no internet access)
-    Agent Version: 2.117.2

## Issue Description

I'm creating a clean VM with Windows server 2012R2 using a default iso downloaded from my MSDN subscription then trying to deploy test agent from offline installer and then run tests on it. Within the first attempt to deploy it I'm getting an error from the first log. If I'll rerun deploy test agent step again it will be completed successfully but then test execution will fail with the error as it is in the DTA logs attached.
I've tried to use offline installer created as described in https://aka.ms/testagentlocation and also created by the direct execution of Start-OfflineProcess from https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/DeployVisualStudioTestAgent/CreateOfflineTestAgent.ps1 and for all cases I've got the same result.

### Error logs
[4_Deploy TestAgent on GASAPP01DV (1).log](https://github.com/Microsoft/vsts-tasks/files/1505936/4_Deploy.TestAgent.on.GASAPP01DV.1.log)

[4_Deploy TestAgent on GASAPP01DV (2).log](https://github.com/Microsoft/vsts-tasks/files/1505931/4_Deploy.TestAgent.on.GASAPP01DV.2.log)

[DTAExecutionHost.exe.log](https://github.com/Microsoft/vsts-tasks/files/1505937/DTAExecutionHost.exe.log)

**Comment by nigurr** [comment]
@darkcite Hi, sorry for the trouble. 
We suggest you to use this script for TFS 2017 Update 2 - https://github.com/Microsoft/vsts-tasks/tree/releases/dev15tfsu3/Tasks/DeployVisualStudioTestAgent/CreateOfflineTestAgent.ps1
It's documented/blogged here: https://blogs.msdn.microsoft.com/devops/2017/05/05/using-visual-studio-agent-deployment-task-on-machines-not-connected-to-the-internet/

**Comment by darkcite** [comment]
@nigurr Hi, sorry but it didn't help, issue is still the same
