### ISSUE TITLE
Unable to use logging command in Powershell on VSTS release task

### ISSUE THREAD

**Issue by sufyannisar** [Microsoft/vsts-tasks#5940]
According to [Logging Commands](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md) I should be able to log details on VSTS details window.

But when I use `Write-Host` in Posershell, the Release fails with error:

> A command that prompts the user failed because the host program or the command type does not support user interaction. Try a host program that supports user interaction, such as the Windows PowerShell Console or Windows PowerShell ISE, and remove prompt-related commands from command types that do not support user interaction, such as Windows PowerShell workflows.

I am using [ PowerShellOnTargetMachines Using File](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/PowerShellOnTargetMachines)

**Comment by niadak** [comment]
We dont support Write-Host in PowerShellOnTargetMachines task. Please use Write-Verbose -Verbose "your log" for logging.

Let us know if you need anymore help.

**Comment by rajatagrawal-dev** [comment]
I am assuming you are able to get unblocked by using Write-Verbose -Verbose. Please feel free to reopen the issue if you need any help on this.

**Comment by rajatagrawal-dev** [comment]
@sufyannisar You can also try using Write-Output "your logs" to display your logs.

**Comment by ankushjain358** [comment]
I was also getting the same issue. But below code worked for me.

`Write-Output "##vso[task.logissue type=warning;]  Error in installing window service"`
