### ISSUE TITLE
Task:RunLoadTest Error copying files to test run

### ISSUE THREAD

**Issue by KyoofuTest** [Microsoft/vsts-tasks#5949]
## Troubleshooting
When running a load test using the "Cloud Load Test Task" only files and directories found in the selected "load test file"-path is copied to the test run. It should be files and directories in the "Load test files folder".
e.g. 
Load test files folder = project root
load test file = file.loadtest
project root --> webtests --> file.webtest
                   --> loadtest --> file.loadtest
Only the file file.loadtest is copied to the testrun!

## Environment
- Server - VSTS 
- Agent - Hosted 

## Issue Description
When running a load test using the "Cloud Load Test Task" only files and directories found in the selected "load test file" is copied to the test run. It should be files and directories in the "Load test files" folder.
e.g. 
Load test files folder = project root
load test file = file.loadtest
project root --> webtests --> file.webtest
                   --> loadtest --> file.loadtest
Only the file file.loadtest is copied to the testrun!

The error exists in the "ValidateFiles" function in the CltTasksUtility.ps1 in the RunLoadTest task.
On **line190**: $global:ScopedTestDrop = $file.Directory.FullName; 
- The global drop folder is changed from the folder specified in the  "Load test files folder" setting to the directory path of the load test file.

Since the validation is run before the "UploadTestDrop" function that is initiated with the $global:ScopedTestDrop parameter the uploading folder is wrong, see Start-CloudLoadTest.ps1 **line:91** and **line: 127**

Suggest either using a local variable in the "ValidateFiles" or use the $TestDrop parameter when calling  "UploadTestDrop" instead of using $global:ScopedTestDrop.

### Error logs

[Insert error from the logs here]

**Comment by prawalagarwal** [comment]
@KyoofuTest Thanks for reaching out. We are looking at the issue and will update this thread soon.

**Comment by prawalagarwal** [comment]
@KyoofuTest We looked at the code and this is by design. This is also clearly indicated by a log (line: 193 CltTasksUtility.ps1). The drop folder will always be the folder where load test file is found. Anything inside this folder is recursively copied. Please reopen if your issue is not resolved.
