### ISSUE TITLE
Unable to deploy test agent with error "Cannot create a file when that file already exists."

### ISSUE THREAD

**Issue by skushubar** [Microsoft/vsts-tasks#5957]
Running a release using a private agent running against VSTS.

Account: aptmetrics
Team Project; APTMetrics
Release Definition: APTMetrics-CI
Release Number: 11.2.5.51-2 => 11.2.5.55-1
Agent: DevTfs01
Agent Version: 2.120.2
Agent OS: Windows Server 2008 R2

Releases started failing on 2017-11-28 with the error "Cannot create a file when that file already exists."
Logs: [11_Deploy TestAgent on devdemo02.log](https://github.com/Microsoft/vsts-tasks/files/1522673/11_Deploy.TestAgent.on.devdemo02.log)

I am unaware of any changes that would have affected the agent.  The log does not give much information to go on.  I am not sure how to proceed.

**Comment by nigurr** [comment]
@skushubar Can you please clean up C:\TestAgent directory from TestAgent machine and try running the build once?

**Comment by skushubar** [comment]
@nigurr I cleared the directory and the release failed with the same error "Cannot create a file when that file already exists".

**Comment by nigurr** [comment]
@skushubar can you please drop us mail devops_tools at microsoft dot com

**Comment by eFlores824** [comment]
What was the cause of the issue? I'm experience the EXACT same issue with my build. The task 'TestAgentConfiguration' is throwing the exact same error for me
