### ISSUE TITLE
How should I pass the template path to  'Azure Resource Group Deployment' task?

### ISSUE THREAD

**Issue by xerespm** [Microsoft/vsts-tasks#5968]
## Environment

- Server: VSTS
- Agent: Hosted

## Issue Description

I want that link some ARM templates in an Azure Resource Group Deployment task,
and I don't like that some URI paths are hard-coded.

```json:parent.azuredeploy.json
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "template": {
            "type": "string"
        }
    },
    "resources": [
        {
            "apiVersion": "2017-05-10",
            "name": "linkedTemplate",
            "type": "Microsoft.Resources/deployments",
            "properties": {
                "mode": "Incremental",
                "templateLink": {
                    "uri": "[uri(parameters('template'), 'child.azuredeployment.json')]",
                    "contentVersion": "1.0.0.0"
                }
            }
        }
    ]
}
```

and I set 'Override template parameters' as bellows.

`-template $(Build.Repository.LocalPath)\parent.azuredeploy.json`.

Hmm..., What should I do?

### Error logs

```
2017-12-04T10:26:05.9189184Z ##[error]BadRequest: {
  "error": {
    "code": "InvalidTemplate",
    "message": "Unable to process template language expressions for resource '/subscriptions/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/resourceGroups/network-hub-spoke/providers/Microsoft.Resources/deployments/linkedTemplate' at line '1' and column '204'. 'The template language function 'uri' expects its first argument to be a uri string. The provided value is 'd:\\a\\1\\s\\parent.azuredeploy.json'. Please see https://aka.ms/arm-template-expressions/#uri for usage details.'"
  }
} undefined
```

**Comment by ds-ms** [comment]
@xerespm As of now, there is no provision for linking a template from a local path using this task (i.e. in your case `$(Build.Repository.LocalPath)\parent.azuredeploy.json`; which would map to `C:\<path_to_agent>\<path_to_downloaded_repository>\parent.azuredeploy.json`)

So, when the template reaches Azure for deployment, the value of the "uri" would be a local path, which is not accessible from Azure. 

Also, if you see the [link](https://aka.ms/arm-template-expressions/#uri), the uri expected is supposed to be reachable from Azure i.e., it should point to a public blob storage or some publicly (or privately with some access keys in the URL) accessible storage or repository.

**Comment by sachinma** [comment]
@xerespm if you don't want to hard-code the URL in the file, you can add a new task (PS or Azure PS) which first uploads the linked template to a blob; form the right URL and update the override param with that URL.

**Comment by xerespm** [comment]
@ds-ms @sachinma Thank you for following me. I’ll give privately repository a try.
