### ISSUE TITLE
Does the Task support stopping multiple webapp / worker role

### ISSUE THREAD

**Issue by sameeradh** [Microsoft/vsts-tasks#5975]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Error logs

[Insert error from the logs here]

**Comment by rajatagrawal-dev** [comment]
@sameeradh Can you provide more details like which task you are using and what you want it to do?

**Comment by sameeradh** [comment]
I am stopping and starting the Web App.  But as a app service name, I am only allowed to enter one app service. Is there any facility where i can enter more than one app service in the same  task
