### ISSUE TITLE
[NuGet Push] Cannot configure NuGet Service endpoint using ApiKey for feed requiring authentication

### ISSUE THREAD

**Issue by xavierdecoster** [Microsoft/vsts-tasks#5979]
## Environment
- Server - VSTS

## Issue Description

When configuring a VSTS Service connection of type NuGet to use an ApiKey, the connection is verified using a GET request to the endpoint **without any authentication**.

For private feeds (e.g. on MyGet), that doesn't work. The feed is secured, and HTTP GET requests without proper authentication, will return a HTTP 401 Unauthenticated result.

This effectively blocks people from saving the VSTS service connection, and the only work-around is to temporarily make the feed public, save the configuration on VSTS, then make the feed private again.
That's obviously not ideal.

### Error logs

See this requestb.in that illustrates the Verify Connection call: https://requestb.in/rche05rc?inspect#1d18lf

![image](https://user-images.githubusercontent.com/880728/33651281-82503330-da65-11e7-8f84-81e0ff59726b.png)

Screenshot of user experience:

![image](https://user-images.githubusercontent.com/880728/33652303-2a701578-da69-11e7-9059-5ac18c066b17.png)

**Comment by g2petter** [comment]
👍 

This is relatively annoying, and part of the reason why we are sticking with the deprecated _NuGet Command_ build task

**Comment by xavierdecoster** [comment]
@bryanmacfarlane @alexmullans any ideas? can you please redirect as needed or help us reach out to anyone to resolve this?

**Comment by jascam** [comment]
@xavierdecoster, We are looking into this issue however while we do that can you try clicking the Ok button on the connection?  Verify connection is only supposed to be for you to test with and it should not block creating the endpoint.

**Comment by alexmullans** [comment]
There's a fix for this rolling out in the current deployment; we've disabled the connection verifier for now until we can make some improvements to it.

/cc @jascam

**Comment by xavierdecoster** [comment]
@jascam looks like clicking _OK_ without clicking _Verify Connection_ does save the apikey! Did not think it would. Thing is, once clicking the verify button, it fails, and there's no way to save it as such without closing and reopening the dialog.

@alexmullans thanks for the fast turn-around!
