### ISSUE TITLE
VSTest version 2 task not distributing tests

### ISSUE THREAD

**Issue by sramssh** [Microsoft/vsts-tasks#5981]
Hi, I had created below issue. It was closed as not a bug. But my issue is still not resolved

https://developercommunity.visualstudio.com/content/problem/161220/vstest-version-2-task-not-distributing-tests.html

I tried specifying the batch size as 50 as mentioned in the above issue. Now the tests are not getting run. Log shows "Test run '664' is in 'InProgress' state." and it does not seem to run any tests. I have set system.debug = true and see this in the logs

2017-12-06T06:08:34.4962285Z ##[debug]TestExecutionServiceCommandQueueListener.DispatchAsync : Queue not found. Delaying for 6000 milliseconds. 2017-12-06T06:08:40.5173569Z ##[debug]TestExecutionServiceCommandQueueListener.DispatchAsync : Getting Command for Test Agent 176

This is currently blocking us from running our tests, any help here is much appreciated. I can email all the logs too. Please provide an email address to send those

Thank you!

**Comment by prawalagarwal** [comment]
@sramssh Thank you for reaching out. Please send us your logs to devops_tools@microsoft.com with system.debug set as 'true' and we will help you resolve the issue.

**Comment by prawalagarwal** [comment]
@sramssh I noticed that your ticket was not closed on developer community and CSS is still working on it. They will reach out to you. Please re open this issue if it is not resolved there.
