### ISSUE TITLE
Cannot specify resource group without also using deployment slots

### ISSUE THREAD

**Issue by CarsonTolleshaug** [Microsoft/vsts-tasks#5984]
The "Azure App Service Deploy" task does not allow the user to specify the resource group of the app unless "Deploy to slot" is checked.

I have two app services which have the same name, but are in two separate resource groups on the same subscription. As far as I can tell, there is currently no way for me to use the Azure App Service Deploy task to deploy code to both services, meaning I will have to resort to using a custom powershell task or other hack-ish solution.

For what it's worth, the app services are in two separate ASEs as well.

Am I missing something? If not can you please consider changing the task/UI to allow for this?

Thanks,
Carson

**Comment by vincentdass** [comment]
@CarsonTolleshaug , thanks for reporting the issue.
Can you try selecting the required resource group and type slot as "**production**" as a workaround?

Will update the thread on the latest info, if any.

**Comment by CarsonTolleshaug** [comment]
Thanks Vincent, yes that works. We ended up just using deployment slot anyway though which solved our issue.
