### ISSUE TITLE
issue with referencing the keyvault certificate secret. 

### ISSUE THREAD

**Issue by boklyn** [Microsoft/vsts-tasks#5985]
## Environment
VSTS
- Agent - Hosted
## Issue Description
So in your read me you advise to have a previous  keyvault task to pull the secrets and in the subsequent task you document to reference the secret as $([SecretName]) with the following code
$kvSecretBytes = [System.Convert]::FromBase64String($(PfxSecret)), where I assume that the secret name holding the certificate is PfxSecret. I copied word for word your sample code and when I do I get the error 
##[error]The term 'vstsdevopscert' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
In my particular case my certificate secret name is vstsdevopscert. So I try the other way of referencing environment variables using $env:vstsdevopscert. This seems to have avoided triggering the error but I now get the following error
2017-12-06T22:06:38.8077819Z ##[error]Exception calling "Import" with "3" argument(s): "The parameter is incorrect.
I am thinking that the variable holding vstsdevopscert is either not containing the full bytes from the conversion process due to the fact that the pulled cert is either corrupted or pulling something that is not a cert. 
Is this a bug with your VSTS task. 
### Error logs

[Insert error from the logs here]

**Comment by lovakumar** [comment]
@boklyn what you have done is right and only change that you need to do is pass $(PfxSecret) as parameter to the script and use that parameter inside your script. Do not reference $(PfxSecret) directly inside the script. In VSTS tasks secret parameters are not available to the script directly, they must be passed explicitly to the task as parameters. Please let us know if that doesn't work.

**Comment by boklyn** [comment]
sorry it took so long but yes that worked. Any chance you can update the description to indicate that because sometimes that is not obvious to others.
