### ISSUE TITLE
New IIS website for each branch

### ISSUE THREAD

**Issue by miltoncamara** [Microsoft/vsts-tasks#5989]
Is possible to create a New Website in my Virtual Machine for each branch generated?

**Comment by ArieHein** [comment]
yes, I assume you want to use only one IIS server to hostall websites (for various branches)
you can either go same website name but different ports or one website with different root folders per branch.

**Comment by miltoncamara** [comment]
Hello @ArieHein yes, is it, for each branch I create, once I finish the development, a new website will be created in my IIS, with a new address, and then released for the QA team to test! But I did not want to create a new release with each new branch .... I would like maybe a Powershell that would do it for me ...

**Comment by expeepit** [comment]
How exactly do you do this in IIS please ?  How do you tell IIS which branch of a repo to use ??

Thanks!

**Comment by bryanmacfarlane** [comment]
This is not an issue with one of the tasks in this repo (what these issues are tracking).
