### ISSUE TITLE
Cannot rebuild JenkinsDownloadArtifact task

### ISSUE THREAD

**Issue by omeshp** [Microsoft/vsts-tasks#5992]
## Issue Description

While trying to rebuild JenkinsDownloadArtifacts task using `node make.js build --task JenkinsDownloadArtifacts` it fails with the below error
![image](https://user-images.githubusercontent.com/11783897/33753338-bf913e9e-dc0c-11e7-8dd6-fdaf904de472.png)

I have to do git clean -xdf before I can rebuild the task again.

**Comment by kelliejos** [comment]
Which version of node and npm are you currently using? We have seen this error when using an unsupported node version.  Try installing node v6 and rebuilding the task. For windows machines you can use this tool to install specific versions of node: https://github.com/coreybutler/nvm-windows.

**Comment by omeshp** [comment]
@kelliejos I am on node v8.7.0 and npm 5.4.2, I will try out with v6.

**Comment by bryanmacfarlane** [comment]
Even though the agent carries node 6, we should be able to build and dev with node 8+.   We should figure out the error.  All that said, were about to redo the engineering in this repo.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hiyadav** [comment]
@omeshp i tired building this task multiple times in node version 6 and 8 and wasn't able to repro this. Could this be some other issue ?
Do you know which changes got cleaned up when you ran git clean -xdf ?

**Comment by omeshp** [comment]
@hiyadav I just tried it with cloning the repo from scratch with below commands and it is reproducing
[logs.txt](https://github.com/Microsoft/vsts-tasks/files/1555609/logs.txt)

Here is the output of git status:
C:\random\vsts-tasks>git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   Tasks/Common/azure-arm-rest/Strings/resources.resjson/en-US/resources.resjson
        modified:   Tasks/Common/azure-arm-rest/package.json
        modified:   Tasks/Common/azure-blobstorage-artifactProvider/Strings/resources.resjson/en-US/resources.resjson
        modified:   Tasks/Common/azure-blobstorage-artifactProvider/package.json
        modified:   Tasks/JenkinsDownloadArtifacts/Strings/resources.resjson/en-US/resources.resjson
        modified:   Tasks/JenkinsDownloadArtifacts/package.json
        modified:   Tasks/JenkinsDownloadArtifacts/task.loc.json
        modified:   package.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        Tasks/Common/azure-arm-rest/package-lock.json
        Tasks/Common/azure-blobstorage-artifactProvider/package-lock.json
        Tasks/JenkinsDownloadArtifacts/package-lock.json
        package-lock.json

**Comment by hiyadav** [comment]
Hey @omeshp, 
Yeah i get it now, i had disabled creation of package-loc.json, hence the issue was not occuring for me.
For now can you trying doing so ? => npm config set package-lock false
I'll meanwhile figure how to resolve it permanently.

**Comment by hiyadav** [comment]
@ericsciple @bryanmacfarlane  
While trying repro this error, i figured out that this failure occurs for more that one task. EG: ANT etc are also failing with the same error. 
Should this be taken care of in build system or by individually ?

**Comment by sachinma** [comment]
@hiyadav can you open an issue for ANT and did this resolve for the Jenkins task?

**Comment by hiyadav** [comment]
@sachinma  I did not work on this further given that this occurs for multiple tasks when using Node>=8. Looked like a engineering side change as it looked like that we needed to change the way we build tasks with latest node version.
It is anyways fixed now on a Repository level by checking in package.json files.
