### ISSUE TITLE
Need a means to "Sync" target directory to source (as per minimatch) tree - AND keep the file modification timestamps

### ISSUE THREAD

**Issue by DynConcepts** [Microsoft/vsts-tasks#5996]
This is needed so that there can be downstream incremental operations.  I have looked at this task and do not see a way to do so. I have looked at other tasks [OOB & Marketplace] with no luck either.

What is the recommended approach to achieving this goal???

**Comment by ArieHein** [comment]
use robocopy with the mirror flag and you can also set different flags for file properties

**Comment by DynConcepts** [comment]
ArieHein - I have considered that, but have been unable to figure out how to get the functionality of "minimatch" (which is supported by the Copy Files task)....

The most common example is collecting the "/bin/{config}" portions of the "s" directory into the "a" Directory....

**Comment by brcrista** [comment]
I'm not sure I understand what you are trying to do.  Can you give a sample directory structure before and after running this build step?

**Comment by brcrista** [comment]
It sounds like you are trying to do an incremental build.  Are you using a hosted agent or a private agent?

Hosted agents get recycled after every run, so if you are using hosted agents you will have to build clean every time.  If you need to be able to build incrementally, you will need to use a private agent and set Clean=False on the MSBuild task.  Reference: https://docs.microsoft.com/en-us/vsts/build-release/tasks/build/visual-studio-build

(FYI: Your artifact staging directory is just going to be a temporary directory on your build agent.  It's not expected to be persisted from build to build.  Reference: https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/artifacts.  In particular: "The directory referenced by `Build.ArtifactStagingDirectory` is cleaned up after each build.")

**Comment by DynConcepts** [comment]
Private agents [in fact it is TFS and not even VSTS, so everything is “private”]

And I am aware of the FYI. My expectation is for it to be rebuilt  (by virtue of having a task or tasks that copy the files) in an IDENTICAL fashion. Not with different modified timestamps if the timestamps of the files under the Sources (“s”) directory have not changed!

**Comment by brcrista** [comment]
What happens when you set Clean=False on the “Visual Studio Build” task?

Not cleaning will leave the ‘bin’ directories under “Sources” as they were before.  Projects with ‘bin’ output newer than the source files will not get built again; the contents of the ‘bin’ folder should get copied straight to the staging directory.  You shouldn’t need a separate task for copying these files.

**Comment by DynConcepts** [comment]
You are correct that with clean=False the bin directories remain intact.  However you need to use a task to update the staging folder. Just look at a DEFAULT Visual Studio Build (specifically the next to last Task). T

[cid:image001.png@01D372A0.D9D5FD10]

**Comment by brcrista** [comment]
Ok, I think I get it now: you want to do an incremental build, but have all the same timestamps on the build output files as if they were just built clean.

MSBuild has a "touch" task that will update timestamps: https://docs.microsoft.com/en-us/visualstudio/msbuild/touch-task.  Set this up to run in each project on the files in the output directory after the project has been built.

Note that this is just plain old MSBuild scripting, so you will get the same behavior whether you are building in VSTS or locally on a dev box.

**Comment by DynConcepts** [comment]
Brian,

No, it is the opposite. I do *NOT* want the output files “touched”.   I have the old timestamps in the source directory, and what the same timestamps in the target directory after the copy as in the source.

Digging into the task, it is the "tl.copy(...)" that is causing me problems.

**Comment by brcrista** [comment]
Ah, I agree that is odd behavior.  I will look into this more tomorrow.

**Comment by brcrista** [comment]
I investigated this and the current behavior of the Copy Files task is by design.  We will note the feature request for a task that can run arbitrary commands with minimatch-style globbing.  For current releases, the way to achieve this is "the long way" -- writing a CMD / PowerShell script to find the 'bin' directories and using Robocopy to copy the files.
