### ISSUE TITLE
CodedUI tests[Run functional test] task on TFS on-premise getting aborted while executing on multiple build def 

### ISSUE THREAD

**Issue by AjayPrasad** [Microsoft/vsts-tasks#6008]
## Environment
- Server - TFS on-premises?
    
    - Version : 14.102.25423.0
    
- Agent - Hosted or Private: 
    
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
     Windows 7

## Issue Description

Multiple different builds[for ex. 5] are queued simultaneously with the same pool of machines[for ex 3] configured to them.

Expectation : We would expect that from the total 5 builds triggered, 3 of them would be assigned to the machines available in pool & rest 2 will be in queue. Whenever any of the first 3                                                      assigned machines becomes free, one of the build in queue will be moved to that particular machine & so on...

Current Behavior : From the 5 builds triggered, 1st build will be allotted to machine 1, 2nd build will check the availability of machine 1 [ideally as machine 1 is already occupied with 1st build, 2nd                                      build should ignore 1st machine & check availability of 2nd machine in pool]. But currently, 2nd build will abort 1st build on machine 1 & start 2nd build on machine 1.This continues for all the triggered builds & finally 1st, 2nd, 3rd, 4th builds will be aborted & 5th build would be successfully completed on machine 1.

**Comment by nigurr** [comment]
Hi,

Currently we don't support running same machines against multiple build definitions. 
Please share your ideas/feature requests here@ https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services
