### ISSUE TITLE
Unable to achieve Distributed runs in RFT step of TFS on-premise

### ISSUE THREAD

**Issue by AjayPrasad** [Microsoft/vsts-tasks#6037]
## Environment
- Server - TFS on-premises
    
    Version : 14.102.25423.0
    
- Agent - Private
    
    - OS of the Machine running agent : Windows NT
    - Agent Version : 1.95.3

## Issue Description
I'm seeing 2 issues while trying to do concurrent runs/parallel runs in TFS 2015 on-premise

1. When pool of machines are given to a particular build definition with 1 test assembly, CodedUI tests 
    inside that assembly are not divided among the pool of machines.

2. I queued 2 build definitions which have the RFT step enabled with same pool of machines. Instead of 
    executing each of those builds on separate machines available in pool,One build definition RFT step is 
    aborting the other build definition.

I searched online & i see that the only way we can achieve this is by having multiple test assemblies. But i wanted to know if we have any option other than this.

It would be really helpful if someone can let me know, if there is a way to achieve concurrent runs of 
codedUI tests in TFS on-premise 2015.

If its not supported in 2015, what would be the version i should update TFS to for getting this done?

Thanks,
Ajay

**Comment by bryanmacfarlane** [comment]
Can you clarify what you mean by "RFT step"?

**Comment by acesiddhu** [comment]
@bryanmacfarlane RFT is Run functional test task.

**Comment by prawalagarwal** [comment]
@AjayPrasad Thanks for reaching out. RFT does not parallelize at assembly level. You need to split your tests in multiple assemblies if you wish to run these tests in parallel. There have been a lot of changes since TFS 2015 and we no longer recommend using RFT task starting TFS 2018.

TFS 2018 introduced different batching options and VsTest task V2 can now be used in place of RFT.

For your second issue, do you mean the test agent pool?

**Comment by AjayPrasad** [comment]
Thanks @prawalagarwal for the info. 

yes, on the second issue i meant Agent pool.

**Comment by prawalagarwal** [comment]
@AjayPrasad Please use different pools with different set of machines. Using different pools with same machines and same pool may cause aborts. Please reopen if you have further queries.

**Comment by AjayPrasad** [comment]
@prawalagarwal Can you suggest me best way to achieve Concurrent runs in TFS 2015 along with documentation if you have.

**Comment by prawalagarwal** [comment]
@AjayPrasad RFT is the only way for TFS 2015.

**Comment by AjayPrasad** [comment]
@prawalagarwal What are the options do i have if i upgrade TFS to latest versions?
My requirement is to execute builds in parallel on the machines i have in my lab. These builds should automatically pick the idle machine from the pool and start executing tests on it.

**Comment by prawalagarwal** [comment]
@AjayPrasad  Here is a [blog](https://blogs.msdn.microsoft.com/devops/2017/03/26/vstest-task-dons-a-new-avatar-testing-with-unified-agents-and-phases/) for your reference. You can reach out to us at devops_tools[AT]microsoft[DOT]com for more details.

**Comment by AjayPrasad** [comment]
Thanks @prawalagarwal
