### ISSUE TITLE
Download Build Artifacts (Preview) - System.DefaultWorkingDirectory not cleared on release if "Skip download of artifacts" checked for agent phase

### ISSUE THREAD

**Issue by ian-a-anderson** [Microsoft/vsts-tasks#6043]
## Environment
- Server - VSTS
- Agent - Private: Windows Server 2016 Datacenter

## Issue Description

We have a release definition that is using the new [Download Build Artifacts (Preview)](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/DownloadBuildArtifacts) task to selectively download a single folder of a larger linked artifact. In order to avoid downloading the full artifact list from the linked artifact, we check "Skip download of artifacts" at the Agent phase level of configuration for the release. However, checking this box also appears to skip cleanup of the $(System.DefaultWorkingDirectory) on each successive run of the release. This results in the task downloading folder contents on top of the existing files (and skipping any deletes). 

If this is expected behavior then it seems like the cleanup of $(System.DefaultWorkingDirectory) and $(System.ArtifactsDirectory) should be controllable via a separate checkbox, so that this can be configured independently of the "Skip download of artifacts" option.

**Comment by omeshp** [comment]
We don't cleanup up $(System.ArtifactsDirectory) since the task can be used multiple times to download different artifacts into artifacts directory. What you are looking for is downloading partial artifacts feature in release, work for it is underway and should be available soon. Having an option to clean directory might help to then.

**Comment by bryanmacfarlane** [comment]
it could be part of job level cleanup.  we support tasks having wrapper scripts (pre / post job)

**Comment by ian-a-anderson** [comment]
I can understand why the Task itself doesn't perform cleanup automatically, for the reasons @omeshp  mentioned. It's just confusing that cleanup is tied to the "Skip artifact download" checkbox since checking that box is one of the main use-cases for this task (selectively pulling partial artifacts). I have a workaround for this by adding a Delete Files task at the beginning of my job, but that seems like an extra step that could be alleviated with another Agent-level setting.

Also, this brings up the question... how does this work on Hosted Agents? I assume those must always clean the work directory before each job run for security reasons. Is that just a difference in how the Private agents function (giving more control over the process)?

**Comment by GitHubSriramB** [comment]
@ian-a-anderson - Hosted agent gets reimaged for every deployment. So the work directory is always clean before artifact download begins. You are right, not deleting the artifacts folder in case of private agent is to give more control over the process to customers using private agent.
