### ISSUE TITLE
Missing code coverage report file

### ISSUE THREAD

**Issue by NickHarvey2** [Microsoft/vsts-tasks#6044]
## Environment
We are using TFS on-prem, version 15.117.26714.0 on Windows Server 2012 R2, and visual studio test agent version 15.5.27130.2003

## Issue Description
When running our tests remotely using the [Run Functional Tests Task](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/RunDistributedTests), with code coverage enabled, the coverage is calculated and visible within TFS, but the coverage report files are not in the location I would expect them (i.e. not in $(Build.Repository.LocalPath)\TestResults, as they are with the regular Visual Studio Test task). Presumably the coverage report is being generated somewhere, since it is visible on the build after completion, but I haven't been able to find the file itself.

This is a problem because our organization uses SonarQube to measure and track code quality, and with the coverage report not being in the specified location, that metric isn't making it into our SQ report.

There are no errors that I can see in the build log, just a missing code coverage report in SonarQube

**Comment by nigurr** [comment]
@NickHarvey2 Run Functional Test [RFT] task runs on different machines and they publish the TRX/coverage files to Test run from those machines. 
So these files don't present in the build agent machine.

We suggest you following solution
1. After RFT task, please write powershell script to get Test run attachments against current build
2. Download the attachments to specific folder in Build agent machine and pass the same folder to Sonar qube task.

Thanks for your feedback/suggestions.
