### ISSUE TITLE
Custom tasks are getting created without name and when included in Release then releases are getting failed.

### ISSUE THREAD

**Issue by html5SharePoint** [Microsoft/vsts-tasks#6051]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises? TFS
    
    - If using TFS on-premises, provide the version: TFS 2015 update 3
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

Created custom task using powershell script. Task is getting uploaded to TFS. but when included in the build and release looks attached in the screen, without default name provided in task.json attached and the error during the release.

Task.json
{

    "id": "EA59D05C-5BEE-4295-A5E6-17DFA2C49C7D",

    "name": "ChangeControlEntryOnPremises",

    "friendlyName": "Change Control Entry: On-Premises",

    "description": "Makes change control entry on the production change site",

    "helpMarkDown": "",

    "category": "Utility",

    "author": "Kulkarni, Prateek",

    "version": {

        "Major": 1,

        "Minor": 1,

        "Patch": 0

    },

### Error logs

2017-12-15T20:07:04.0737469Z ##[error]Context name can not be null or empty.

9 
2017-12-15T20:07:04.0737469Z ##[error]Parameter name: name
![customtask](https://user-images.githubusercontent.com/4385143/34061222-d991cb74-e1ac-11e7-8c62-75c72469ad3e.jpg)
![customtask](https://user-images.githubusercontent.com/4385143/34061229-e072673c-e1ac-11e7-86a6-4e3b03090613.jpg)

[Insert error from the logs here]

**Comment by bryanmacfarlane** [comment]
This isn't an issue with the tasks in this repo which is what this repo is for.

https://github.com/Microsoft/vsts-tasks/tree/master/Tasks

If you're having an issue with the RM web UI designer, you can create an issue developer community.
