### ISSUE TITLE
Azure App Service Deployment: ARM aborts sometimes with error 500

### ISSUE THREAD

**Issue by dei79** [Microsoft/vsts-tasks#6054]
## Environment
VSTS: I'm using a VSTS tenant, account name , team project etc. can be shared in private.
Agent: Using a private agent running on Ubuntu Linux in a Docker Container (official image). Agent version  is 2.124.0.

## Issue Description
From time to time the Azure App Service Deployment task ends up with error 500 when deploying via Kudu RestAPI. The task is using "Take App Offline" to prevent write locks but this does not help. 

### Error logs
2017-12-17T22:06:09.5517030Z Got connection details for Azure App Service:'dev-ac-v2-worker-dedicated'
2017-12-17T22:06:11.9189650Z Deploying web package : /vsts/agent/_work/4/a/ac.worker.controller.zip at virtual path (physical path) : / (/site/wwwroot)
2017-12-17T22:06:24.8846570Z ##[error]Failed to deploy web package to App Service.
2017-12-17T22:06:24.8927690Z ##[error]Error: Failed to deploy App Service package using kudu service : Error: Failed request: (500)

**Comment by vincentdass** [comment]
@dei79 , is the release passing after a retry attempt?
Is the error code always 500?

**Comment by dei79** [comment]
@vincentdass yes when I retry the build it's working. Normally what happens: 

* Several builds in a row a re working good
* When my page is in operation for a couple hours the first build fails and the 2nd is going through 

And yes the error is always 500 and I have the symptom at all Azure App Services on different Service Plans

**Comment by vincentdass** [comment]
@dei79 , Can you please share the deployment template to `RM_CUSTOMER_QUERIES@MICROSOFT.COM` ?
Also set variable `system.debug` to `true` in your release defintion and share the logs from the new release.

**Comment by dei79** [comment]
@vincentdass thanks I did and added all the required information. Let me know when you need addition details.

**Comment by dei79** [comment]
@vincentdass forgot to say after a failed deployment the service stucks in error 503 but when I re-deploy after that everything works well ok.

**Comment by vincentdass** [comment]
@dei79 , thanks for the logs. The problem here is the FILE_IN_USE error where the resources are locked by some DLL / EXE. Adding a app_offline.html should have resolved the issue but since the task starts the deployment without any time delay, app_offline has no effect. Adding a retry with considerable retry interval should resolve this issue. Marking the thread as enhancement.

**Comment by vincentdass** [comment]
This issue is resolved and the fix will be available in upcoming deployment.
