### ISSUE TITLE
VSTest: Publish fails if '[' or ']' are used in run title,

### ISSUE THREAD

**Issue by JohannesDrexler** [Microsoft/vsts-tasks#6055]
## Environment
- Server - VSTS or TFS on-premises?
    
    VSTS

- Agent - Hosted or Private: 

    Private agent, windowsServer 2016, agent version: 2.126.0

## Issue Description

If the title of a test run contains '[' or ']' or both VSTest-Task will not publish the results and write the following warning: "Failed to publish test results: The given path's format is not supported.".
When i set system.debug to true the problem was obvious. The '##vso[results.publish'-command was cut and half the command was used as trx-path. See logs below:

### Error logs

[6_Test Assemblies test.dll;-obj.txt](https://github.com/Microsoft/vsts-tasks/files/1567219/6_Test.Assemblies.test.dll.-obj.txt)

Lines: 2242 -> 2250

**Comment by ShreyasRmsft** [comment]
Hi @JohannesDrexler, this is a known issue and we'll be fixing it in the coming releases but until then please avoid using '[' or ']' in the test case title.
