### ISSUE TITLE
Make Cordova application build in VSTS

### ISSUE THREAD

**Issue by kant2002** [Microsoft/vsts-tasks#6059]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS and likely TFS on-premises due to nature of error.
Account: codevision.visualstudio.com
Team Project: SmsRequest
Build definition: SmsRequest-Cordova-VSTS-issue

- Agent - Hosted or Private: 
Could be reproduced both on Hosted and Private agents
Private Agent is Windows 10:

## Issue Description
Task VSBuild
I try to run build of Cordova Application build using Apache Cordova Tools. By default the build fails with cryptic error.

The build is actually working using Visual Studio, but not from command line.

I managed to find that issue is in the Apache Cordova Tools, MSBuild files where they expect that `InstanceId` MSbuild property to be set during the build. You could see that I manually specify that property from command line in my build description now.

I have suggestion that this variable could be reasonable easy set by VSBuild task since, instance id is very likely already calculated. If VSBuild would set this property automatically that make usage of Cordova from Visual Studio pleasant experience when doing CI and CD.

### Error logs

(EnsureNodeJsRequirementsAreAtCorrectVersion target) -> 
MSBUILD : cordova-build error BLDErr_Build_ExceptionLookingForNode: Unable to determine location of Node.js installation. Exception: Could not load file or assembly 'Microsoft.VisualStudio.Setup.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by madhurig** [comment]
Please checkout the Cordova Build extension for VSTS: https://github.com/Microsoft/vsts-cordova-tasks

Thanks,
Madhuri
