### ISSUE TITLE
Run Functional Tests - Unable to discover NodeJS tests

### ISSUE THREAD

**Issue by ozyx** [Microsoft/vsts-tasks#6075]
## Environment
- Server
    - TFS2017 OnPremise v15.117.27024.0

- Agent
    - Windows 10 Fall Creators Update
    - TFS 2017 Agent

## Issue Description

Tests are not being discovered when trying to run NodeJS tests distributed across multiple machines. I am using NodeJS Tools for Visual Studio 2015 test adapter (v1.3.1). The location of the test adapter assemblies has been specified in a `*.testsettings` file as described [here](https://msdn.microsoft.com/en-us/library/jj635153.aspx). I've increased the trace level for the TestDiscovery and have included the logs.

I was previously able to get this to work using the same TFS and NodeJS Tools Test Adapter versions, but with a different machine which had Windows Server 2008. All other things constant.

Please let me know if you need any more information.

### Error logs

[5_Run Tests .njsproj on LKFTAUILESS1.txt](https://github.com/Microsoft/vsts-tasks/files/1572861/5_Run.Tests.njsproj.on.LKFTAUILESS1.txt)
[vstest.discoveryengine.x86.TpTrace.log](https://github.com/Microsoft/vsts-tasks/files/1572863/vstest.discoveryengine.x86.TpTrace.log)
[Integration.testsettings.txt](https://github.com/Microsoft/vsts-tasks/files/1572865/Integration.testsettings.txt)

**Comment by ozyx** [comment]
Update:

I was able to fix the issue by following the same steps detailed in issue #5854

**Comment by ShreyasRmsft** [comment]
Hi @ozyx,
We are no longer supporting the RFT task and recommend that you switch to using the VsTest task which does everything RFT did and much more.

If you are running this via Releases then distribution via VsTest task is readily available.

If you are on Build then there is a preview feature which needs to be enabled to run vstest task in distributed mode which can be found in the preview features pane of your vsts account. This will be enabled by default after a few weeks.

![image](https://user-images.githubusercontent.com/25194518/34354758-867716ee-ea56-11e7-8529-59c3fc6e8f5f.png)

You can go through these for help on distribution via VsTest task:

https://blogs.msdn.microsoft.com/devops/2017/03/26/vstest-task-dons-a-new-avatar-testing-with-unified-agents-and-phases/ 

https://blogs.msdn.microsoft.com/devops/2017/11/14/test-batching-options-with-vstest-task/

Let me know if you need any further assistance.

**Comment by fforjan** [comment]
To give a bit more context, this is for a TFS 2017 OnPrem instance, not from Visual Studio Team Service.

We've just completed our TFS 2017 migration and we are at least 1 year away before any TFS 2018 migration.

My understanding is the previous feature will be for Visual Studio Team service ?

**Comment by ShreyasRmsft** [comment]
@fforjan Yes you are right. However in the latest update of TFS 2017 you'll be able to use parallelization via the VsTest task in **Releases**, this is enabled by default. Are you guys running these tests on Builds or Releases?

**Comment by fforjan** [comment]
@ShreyasRmsft 
At the moment only on Builds, but we have some ideas to use Releases.
We have more a desktop oriented application and I'm still struggling to find a right example for Release with such type of application but we would like to experiment

**Comment by ShreyasRmsft** [comment]
@fforjan Shall I close the issue? We are planning on deprecating Run Functional tests and are urging customers to move to VsTest V2. Builds with phases (what you need to run tests in parallel in Builds) will be available in tfs 2018 update 2. This is already in preview on VSTS at the moment.

**Comment by fforjan** [comment]
@ShreyasRmsft  I'm not sure to understand what does 'urging customers to move to VsTest V2' mean for us.

Us in that case is using TFS 2017 update 3 ?

**Comment by ShreyasRmsft** [comment]
@fforjan Just means that **if possible** do move to VsTest V2. The code for RFT is frozen and fixes for only major blocking issues will be made. (assuming no workaround exists).
