### ISSUE TITLE
Download Build Artifacts (Preview) not able to get latest build of a specific build definition

### ISSUE THREAD

**Issue by gertvdh** [Microsoft/vsts-tasks#6076]
## Environment
- Server - VSTS 

## Issue Description

with the build task "Download Build Artifacts (Preview)" it's not possible to automatically get the latest build for a specific build definition if option "specific build" is used. It would be nice if this could be possible

![image](https://user-images.githubusercontent.com/24321244/34174222-7eabddf4-e4f8-11e7-8333-e001aafedae9.png)

so instead of hard choosing a build number, <latest version>

**Comment by GitHubSriramB** [comment]
@gertvdh - Thanks for the feedback. We will consider how to surface option to choose latest build in the task.

**Comment by GitHubSriramB** [comment]
We'll use this PR to continue discussion on this.
