### ISSUE TITLE
Callback for Azure Function Completion Setting Does Not Work/unclear how to use

### ISSUE THREAD

**Issue by hrboyceiii** [Microsoft/vsts-tasks#6080]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    VSTS
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
    incyclelabs.visualstudio.com
    dp-devops
    "New Release Definition"/Releases 4+

- Agent - Hosted or Private: 
    - If using Hosted agent, provide agent queue name:
    Hosted VS2017/Agentless Tasks & Gates

## Issue Description

I'm trying to use the Azure Function task and configure it for callback completion notifications.  Problem is that there isn't any documentation on how to achieve this.  The documentation on the task indicates to update the Task Timeline Record(s) to signal completion. My attempt at doing this was to look at the both the Release Management and Distributed Task REST API clients (nuget packages) and see if there was a call or 3 that would provide that capability.  RM API doesn't seem to have it.  DistributedTask API has a GetTimeline method, however, calling it with the agent provided values of System_TIMELINEID, System_PlanID, Release_DeploymentPhaseID fails with an "Internal Server Error" returned from the API.

I'm passing System_AccessToken in the request body along with the other values as well; I've verified the Token works by using the RM APIs to retrieve the release ID and that returns successfully. 

I've also noticed that the values for TimelineID and PlanID are the same; should they be?  I've also tried calling GetPlan but that too fails with "Internal Server Error".

Is there any guidance that can be provided or recommendations on troubleshooting these scenarios?

Thank you

### Error logs

[Insert error from the logs here]

**Comment by hrboyceiii** [comment]
I've done some additional testing and it seems like this may be an authentication/authorization issue.

If I create a new instance using either MS.VS.Services.RM.ReleaseHttpClient or TaskHttpClient and pass in the Uri and VssOAuthAccessTokenCredentials object, I get a successful response from GetReleaseAsync.  TaskHttpClient throws Internal Server Error.

I noticed from looking at the Vsts-Agent repo that the agents connect differently, using VssConnection object to connect and then get an instance of the TaskHttpClient.  However, when I call ConnectAsync on VssConnection prior to GetClient<T>() with the access token, I get the following error:

`Error converting value "Microsoft.TeamFoundation.ServiceIdentity;17c19fa8-73c4-43a6-92ca-31235ca81474:Build:6769cc76-8bf6-4035-a079-bccab51920b9" to type 'Microsoft.VisualStudio.Services.Identity.IdentityDescriptor'. Path 'authenticatedUser.descriptor', line 1, position 201.`

Inner exception:
`Could not cast or convert from System.String to Microsoft.VisualStudio.Services.Identity.IdentityDescriptor.`

Not sure if that is helpful or not.

Using the latest versions of packages (15.112.1-preview)

**Comment by bansalaseem** [comment]
Can you please try the steps mentioned here?

https://blogs.msdn.microsoft.com/aseemb/2017/12/18/async-http-agentless-task/

**Comment by hrboyceiii** [comment]
Thank you @bansalaseem for replying.

I looked at the code both in the blog post and the git repo and, at least for the connection part, it looks the same as my code:

`var credential = new VssBasicCredential("username", data.AccessToken);
VssConnection cn = new VssConnection(new Uri("https://incyclelabs.vsrm.visualstudio.com"), credential);
using (var taskClient = cn.GetClient<TaskHttpClient>())
{
	//use task client
}`

However, that code throws the exception above "Error converting value "Microsoft.TeamFoundation.ServiceIdentity;17c19fa8-73c4-43a6-92ca-31235ca81474:Build:6769cc76-8bf6-4035-a079-bccab51920b9" to type 'Microsoft.VisualStudio.Services.Identity.IdentityDescriptor'. Path 'authenticatedUser.descriptor', line 1, position 201."

I'm going to pull down the vsts-rm-extensions repo sample and try running it locally to see if it works and validate I'm not missing something in my code.  I hope to post back later today.  Thank you again.

**Comment by hrboyceiii** [comment]
I may have found the issue.

It appears that `15.112.1-preview` packages have/had an issue with processing the tokens supplied by the agent(s).  If I went to the latest versions of `Microsoft.VisualStudio.Services.Client` and `Release.Client` (15.126.0-preview) but keep `DistributedTask.Client` at `15.112.1-preview` everything works.

I would've thought (preferred?) to keep the versions aligned but that doesn't seem to work.  The sample provided by @bansalaseem uses the same approach.

Is this the correct way of handling these version differences?

Thank you

**Comment by bansalaseem** [comment]
@sureshtadisetty, can you please take a look at it?

**Comment by sureshtadisetty** [comment]
@hrboyceiii good if it's working for you.
IdentityDescriptor converter is a known issue, in Azure Functions, please refer to this link for the recommended workaround: https://developercommunity.visualstudio.com/content/problem/117356/problem-using-vsts-c-client-library-vssconnection.html

**Comment by bansalaseem** [comment]
Suresh has shared the workaround to come out of this and the right fix is owned by azure function team which is outside of this repo. So I am marking this issue closed.
