### ISSUE TITLE
Powershell: execute function with Script Filename

### ISSUE THREAD

**Issue by marceloavf** [Microsoft/vsts-tasks#6081]
## Environment
- Server - VSTS:
    **Account name:** precisaosistemas
    **Team project Name:** InovaFarmaNotificacoes
    **Release name:** Master_Release

- Agent - Private: 
    Windows Server 2016 Standard

## Issue Description

How can I run a function of a .ps1 file with powershell in VSTS. 
I don't want to create a file for each function and repeat the code in many of them, when I try to run a specific function I receive this error bellow

### Error logs

```
2017-12-20T16:59:17.6176978Z ##[command]. 'C:\agent\_work\r1\a\Master\InovaFarmaNotificacoes\config\release\gitHubHelper.ps1 ; ModifyRelease "v1.19.3" $True $False' 
2017-12-20T16:59:18.3557394Z ##[error]. : O termo 'C:\agent\_work\r1\a\Master\InovaFarmaNotificacoes\config\release\gitHubHelper.ps1 ; ModifyRelease 
"v1.19.3" $True $False' não é reconhecido como nome de cmdlet, função, arquivo de script ou programa operável. 
Verifique a grafia do nome ou, se um caminho tiver sido incluído, veja se o caminho está correto e tente novamente.
No linha:1 caractere:3
+ . 'C:\agent\_work\r1\a\Master\InovaFarmaNotificacoes\config\release\g ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\agent\_work\...3" $True $False:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 

2017-12-20T16:59:18.4547454Z ##[error]Process completed with exit code 0 and had 1 error(s) written to the error stream.
```

**Comment by daveVSTS** [comment]
This post should guide you:
https://social.msdn.microsoft.com/Forums/en-US/24630cf3-d04c-4813-b102-3c275ba81e46/tfs-2017-how-to-call-a-function-in-a-powershell-script-and-pass-parameters?forum=tfsbuild

**Comment by daveVSTS** [comment]
More details, you can use the inline script option to invoke your powershell function, assuming your ps1 file is checked in at the root of your repo, use this as your inline function:

$(Build.SourcesDirectory)\MyFile.ps1 MyFunction
