### ISSUE TITLE
Allow Azure SQL Database Deployment task to deploy to an ElasticPool

### ISSUE THREAD

**Issue by marcelloromani** [Microsoft/vsts-tasks#6083]
## Environment
VSTS

## Issue Description
I am deploying a database schema using a Dacpac file and an Azure SQL DB deployment task.

The database is created with pricing tier S0.
On the same server there is one Elastic Pool configured, and I'd like the database created by the deployment task to appear within that EP.

**Comment by marcelloromani** [comment]
As a workaround, an empty database with the desired name can be created inside the Elastic Pool via the Azure Portal.
The Azure SQL DB deployment task will then correctly instantiate the schema on that database.

**Comment by Ajay-MS** [comment]
@marcelloromani 

Thanks for posting workaround on the thread.  

**Scenario 1**
If you have already existing database in elastic pool, using Azure SQL Dacpac deployment you can directly deploy to database in elastic pool. 

**Scenario 2**
If database doesn't exists in elastic pool, by default it creates db with performance level S0. Using argument _DatabaseServiceObjective_, you can specify performance level like S1, S2 etc but currently creation of db in elastic pool is not supported via SQLPackage.exe 

I am following up with SQL team regarding  this, till then please follow same workaround as you  have suggested. 

**Workaround**
So possible workaround as you suggested is to create empty database in elastic pool via Azure portal and then deploy schema using Azure SQL Dacpac deployment task.

**Comment by chshrikh** [comment]
closing this as issue got resolved with workaround. Team is following for the correct fix

**Comment by boga5** [comment]
Hi
Is this feature ready?
It's been 1 and a half year almost and there are no comments or any updates about this feature!

I need to deploy the DB to an Elastic Pool using SQLPackage.exe

I'm recreating the databases and using DatabaseServiceObjective to specify my tier.
I would like to deploy my recreated DBs into a SQL Pool.

I cannot use the workaround mentioned here by @marcelloromani

**Comment by PedroC88** [comment]
Same here, the workarounds don't work for me because the names of the databases are dynamic so I can't create them before hand.

This ticket should be properly solved and shouldn't be closed.

**Comment by arjoh** [comment]
I found this issue by Googling, but this still does not seem to be natively supported. I'm using SSDT and I'm using the following PreDeployment script to add the database to the correct pool immediately after creation. It's not pretty but it supports dynamic database names (by using SqlCmd variables):
```
:setvar ServerName "servername"
:setvar SqlElasticPool "elasticpoolname"

if @@SERVERNAME = '$(ServerName)'
begin
	print concat('Adding [$(DatabaseName)] to SQL Elastic Pool [$(SqlElasticPool)] on server [$(ServerName)]')
end

if @@SERVERNAME = 'servername' -- No begin/end here or the operation will time out!!
	exec sp_executesql N'ALTER DATABASE [$(DatabaseName)] MODIFY ( SERVICE_OBJECTIVE = ELASTIC_POOL (name = [$(SqlElasticPool)] ))'
```
