### ISSUE TITLE
Download Build Artifacts - use of artifacts cache

### ISSUE THREAD

**Issue by gertvdh** [Microsoft/vsts-tasks#6085]
## Environment
- Server - VSTS 
    
    
## Issue Description

It might be interesting to have some kind of local build server file cache where artifacts are downloaded so that the next time a download should be done, it can be retrieved from the cache instead of downloading the version all over again. Similar like NuGet packages are downloaded

**Comment by bryanmacfarlane** [comment]
This is on our backlog.  There is an artifact service that will even support binary (file level) and block level dedupe and caching.  

Closing this since it's in our plans and we're not tracking service backlog features here (just tasks)

**Comment by abergs** [comment]
@bryanmacfarlane Any update on this cache? :)
