### ISSUE TITLE
XCode task doesn't pass archivePath parameter

### ISSUE THREAD

**Issue by nholling** [Microsoft/vsts-tasks#609]
I'm using the XCode build task to build my IOS App.  The build output I want is an xcarchive file.  I'm using the action archive. To create the xcarchive file when building the archive action, you need to pass the -archivePath parameter to xcodebuild.

If I execute the xcodebuild command with the archive action and the archivePath parameter from the command line, the xcarchive file does get created as expect.

The Apple documentation says the following about the archivePath parameter:

Excerpt from: https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/xcodebuild.1.html

> -archivePath xcarchivepath
>          Specifies the path for the archive produced by the archive action, or specifies the archive that
           should be exported when -exportArchive is passed.

I will try to make a pull request with a fix in the next few days.

**Comment by tonyblues** [comment]
I found if I don't pass the -archivePath parameter to the xcodebuild task, the archive file will be generated to the default location (Users\agentUserName\Library\Developer\Xcode\Archives\...).
But if I pass the -archivePath parameter, the build agent can actually generate an .xcarchive file at the specified location. However, sadly the size of this archive file is zero... :(

**Comment by bryanmacfarlane** [comment]
Madhuri, is this foxed now with the rollout of the revamped task?

**Comment by madhurig** [comment]
Addressed in PR: https://github.com/Microsoft/vsts-tasks/pull/2701

**Comment by DavidStaheli** [comment]
@bryanmacfarlane and @madhurig, since PR #2701 is merged, is it safe to close this issue?

**Comment by madhurig** [comment]
@DavidStaheli: I will close the issue once the changes are deployed to Team Services.

**Comment by madhurig** [comment]
Fix has been merged and will be deployed to Team Services starting Oct 16th and should roll out to all accounts in about a week.

**Comment by AshwinKovil1995** [comment]
Still having this issue with Xcode@5
