### ISSUE TITLE
Error: Service principal authentication is not supported in version '5.1.1' of the Azure module.

### ISSUE THREAD

**Issue by InteXX** [Microsoft/vsts-tasks#6095]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    TFS
    - If using TFS on-premises, provide the version: 
    2018
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    Private
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
    Server 2016 Standard, v2.117.2

## Issue Description
SPN authentication is not supported. It appears SPN authentication has been deprecated, thereby invalidating this task. Note line 2368 in the attached log file.

[Include task name(s), screenshots and any other relevant details]
Azure PowerShell script

### Error logs
[16_Azure PowerShell script FilePath.txt](https://github.com/Microsoft/vsts-tasks/files/1584453/16_Azure.PowerShell.script.FilePath.txt)

[Insert error from the logs here]
Line #2368: Service principal authentication is not supported in version '5.1.1' of the Azure module.

**Comment by arjgupta** [comment]
@InteXX , with Service Principal, the task tries to import to AzureRm module, and if not found ( which is the case for you), it tries to import azure module and work with it. And since azure module stopped supporting service principal, that is why you are getting this error. Please run this command from an admin powershell prompt on your agent machine:
Install-Module -Name AzureRm -RequiredVersion 5.1.1

**Comment by InteXX** [comment]
That seems to have worked, but I haven't tested all scenarios yet.

Since, as you say, Azure modules no longer support SPN authentication, is this task soon destined for deprecation?

**Comment by InteXX** [comment]
@arjgupta — Azure File Copy worked, but I'm now getting this error with the Azure Powershell build step:

>No valid combination of account information found.
Could not get the storage context. Please pass in a storage context or set the current storage context.

I'm not sure what to make of this. Do you have any suggestion?

**Comment by arjgupta** [comment]
Hi @InteXX , for using AzureRM cmdlets, you have to use Azure Resource Manager endpoint, which is based on service principal, and for using Azure module cmdlets, you have to create an Azure Classic endpoint using certificate.

**Comment by arjgupta** [comment]
@InteXX, for more details on endpoint, you can refer to the endpoint documentation [here](https://docs.microsoft.com/en-us/vsts/build-release/concepts/library/service-endpoints#sep-azure-classic)

**Comment by InteXX** [comment]
@arjgupta — This is interesting; thank you for the additional detail.

To answer your other question, however, these errors are occurring before the sequence is reaching my code. In other words, they're being caused by the Azure Powershell build step itself.

I'll collect and submit the log as you request.

**Comment by InteXX** [comment]
@arjgupta — "...these errors are occurring before the sequence is reaching my code." Pardon me, that's not correct.

I'm debugging my code now. I'll report my results asap.

**Comment by InteXX** [comment]
@arjgupta — My script is attempting to use Azure Classic cmdlets with an Azure Resource Manager endpoint. Thus the errors.

I'll work next week on retrofitting my script. Thank you for your assistance and clarification.
