### ISSUE TITLE
Could you suggest best approach for automating Kendo UI with Selenium c#

### ISSUE THREAD

**Issue by Cva2904** [Microsoft/vsts-tasks#6098]
Dear Team,

looking for best approach for automating Kendo UI with Selenium c#.

thanks in advance for your suggestions.

Kind regard!
Siva. A

**Comment by PBoraMSFT** [comment]
@Cva2904 - this is not the right forum to seek guidance and advice. It is meant for reporting any issues you may encounter with running the tasks in VSTS / TFS CI/CD pipelines.
Please post your queries in Stackoverflow at [https://stackoverflow.com/questions/tagged/vsts]
