### ISSUE TITLE
Windows Machine File Copy Tasks fails / No update to V2

### ISSUE THREAD

**Issue by PArpagaus** [Microsoft/vsts-tasks#6105]
## Troubleshooting
It is not possible to execute the build task "Windows Machine File Copy", even not after upgrading to TFS Version 2018. The Build Task is only available in Version 1, in Version 2 the problem would be solved I think. 

## Environment
- TFS onprem in Version "16.122.27102.1"
- Agent in Version  2.126.0 on Windows Server 2012 R2

## Issue Description
The Build Task "Windows Machine File Copy" fails with the following error message:
 System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

 System.Management.Automation.ParameterBindingException: Cannot bind parameter 'TaskContext'. Cannot convert the "Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.PSHostTaskContext" value of type "Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.PSHostTaskContext" to type "Microsoft.TeamFoundation.DistributedTask.Agent.Interfaces.ITaskContext". ---> System.Management.Automation.PSInvalidCastException: Cannot convert the "Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.PSHostTaskContext" value of type "Microsoft.TeamFoundation.DistributedTask.Handlers.LegacyVSTSPowerShellHost.PSHostTaskContext" to type "Microsoft.TeamFoundation.DistributedTask.Agent.Interfaces.ITaskContext".

 System.Management.Automation.CommandNotFoundException: The 'Register-Environment' command was found in the module 'Microsoft.TeamFoundation.DistributedTask.Task.DevTestLabs', but the module could not be loaded. For more information, run 'Import-Module Microsoft.TeamFoundation.DistributedTask.Task.DevTestLabs'. ---> System.Management.Automation.CmdletInvocationException: Could not load file or assembly 'Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
 
 System.Management.Automation.CommandNotFoundException: The 'Get-EnvironmentResources' command was found in the module 'Microsoft.TeamFoundation.DistributedTask.Task.DevTestLabs', but the module could not be loaded. For more information, run 'Import-Module Microsoft.TeamFoundation.DistributedTask.Task.DevTestLabs'. ---> System.Management.Automation.CmdletInvocationException: Could not load file or assembly 'Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Services.WebApi, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
 
 System.Management.Automation.RuntimeException: No machine exists under environment: 'sv80.weroSoft.net' for deployment ---> System.Management.Automation.RuntimeException: No machine exists under environment: 'sv80.weroSoft.net' for deployment
 
 LegacyVSTSPowerShellHost.exe completed with return code: -1.
[tasklog_8.log](https://github.com/Microsoft/vsts-tasks/files/1589042/tasklog_8.log)

### Error logs

[Insert error from the logs here]

**Comment by arjgupta** [comment]
@PArpagaus , line 191 in your log says, that it cannot find the machine name that you provided as input. Can you please check whether the machine exists or not and verify the name once

**Comment by PArpagaus** [comment]
The machine 'sv80.werosoft.net' exists, the same release definition has worked with the old build agent V1.

**Comment by PArpagaus** [comment]
I have the same problem with the task "PowerShell on Target Machine"!
[tasklog_4.log](https://github.com/Microsoft/vsts-tasks/files/1589865/tasklog_4.log)

**Comment by arjgupta** [comment]
@PArpagaus , I would like to setup a skype call to debug this issue. Can you send the details, along with logs for the case when the task was succeeding with agent v1 to RM_Customer_Queries@microsoft.com

**Comment by PArpagaus** [comment]
After installing a new agent V2 on my developer machine all mentioned tasks work fine. In the two logs of the agents I found the following difference:

Agent with error:
2017-12-27T20:28:29.7435262Z ##[debug]Loading module from path 'C**:\Windows\system32\WindowsPowerShell\v1.0**\Modules\Microsoft.TeamFoundation.DistributedTask.Task.DevTestLabs\Microsoft.TeamFoundation.DistributedTask.Task.DevTestLabs.dll'.

Agent which works:
2017-12-28T19:23:12.2158638Z ##[debug]Loading module from path "**D:\Temp\Agent99-Arp\externals\vstshost**\Microsoft.TeamFoundation.DistributedTask.Task.DevTestLabs\Microsoft.TeamFoundation.DistributedTask.Task.DevTestLabs.psm1".

I looks like the installed agent on my build server uses wrong module paths. How can I change or verify this path?

**Comment by arjgupta** [comment]
The issue was caused due to some TeamFoundating modules being present in the c:/windows/system32/windowspowershell/modules path, and so instead of the modules getting picked up from the agent directory itself, they were getting loaded from there. Removing the modules resolved the issue.

**Comment by ehakdem** [comment]
we were using the version 1.* of the windows machine file copy in our release definitions before upgrading to azuredevops.  when we upgraded releases started to fail. we changed the version of the windows machine file copy to 2.* and the problem is gone.
