### ISSUE TITLE
Json Substitution Does not work if value is null

### ISSUE THREAD

**Issue by neurospeech** [Microsoft/vsts-tasks#6109]
## Environment
- Server - VSTS 
    
## Issue Description
When a json value in appsettings.json contains null, it cannot be replaced by JSON substitution.

Example,

appsettings.json in SCM
```json
      {
            "CDN": null
      }
```

JSON Variable in RELEASE defintion

CDN   =   cdn.somewhere.com    

After deployment CDN value remains `null` in deployed appsettings.json.

But when set as an empty string,

appsettings.json in SCM
```json
      {
            "CDN": ""
      }
```

After deployment CDN value is replaced to `cdn.somewhere.com` correctly in deployed appsettings.json.

**Comment by vincentdass** [comment]
@neurospeech , thanks for reporting the issue. It's a genuine issue and will be addressed.

**Comment by neurospeech** [comment]
@vincentdass One more thing, the issue exists even for IIS Web Deployment, not only Azure App Service.

**Comment by vincentdass** [comment]
@neurospeech , yes, the substitution logic is shared across IIS deploy and App Service Deploy task.

**Comment by vincentdass** [comment]
The Issue is resolved and the fix will be available in upcoming deployment.
