### ISSUE TITLE
Escaping double quotes in npm task arguments

### ISSUE THREAD

**Issue by ameyagholkar** [Microsoft/vsts-tasks#6117]
### Task
`npm` (https://docs.microsoft.com/en-us/vsts/build-release/tasks/package/npm)

### Version
0.*
1.*

### Description
The `npm` task does not handle escaped double quotes in the arguments as expected. Here's i'm trying to execute -

```
npm run myTask -- --users='{"foo":"bar"}' 
```

If I run this using `npm` vsts task (version 0.* & 1.*), what I see executing in the console logs is this --

```
[command]/usr/local/bin/npm run myTask -- --users='{foo:bar}'
```

For reference, if I run the same task on my mac via the terminal, I see this in my execution logs --
```
npm run myTask -- --users={\"foo\":\"bar\"}
```

It looks like adding single quotes isn't consistent with how `npm` works outside the context of VSTS? Is this by design? If yes, why?

The only way I've found to ensure that I can pass a valid json is -
- escaping the double quotes in the JSON string beforehand
- surround the escaped JSON string with `" "`
```
npm run myTask -- --users="{\"foo\":\"bar\"}"
```

**Comment by bryanmacfarlane** [comment]
The arguments option in the task lib (all tasks use) requires escaping double quotes as you did here:
```
npm run myTask -- --users="{\"foo\":\"bar\"}"
```

It follows traditional unix style quoting and escaping via the shell

It doesn't support the javascript style single and double quotes for constants (and the json and npm are javascript).

We could add support for single quotes potentially.  We would have to think about compat.  If we do, it would have to be via an ask in the vsts-task-lib repo.

**Comment by alexmullans** [comment]
@bryanmacfarlane I think I'd rather just document this behavior in the npm task docs and the help tooltip in the task itself - WDYT?

**Comment by bryanmacfarlane** [comment]
Sure.

**Comment by ameyagholkar** [comment]
Thanks for the quick feedback, guys 👍
