### ISSUE TITLE
MsBuild.exe does not exist at '/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/msbuild/15.0/bin/xbuild.exe'.

### ISSUE THREAD

**Issue by eorengo** [Microsoft/vsts-tasks#6118]
## Environment
- Server - TFS 2017.2
- Agent - Private: OSX 10.11 Agent 2.122.0

## Issue Description

I tried to build the project https://github.com/adventworks/xamarin-sample as is described at https://docs.microsoft.com/en-us/vsts/build-release/apps/mobile/xamarin?tabs=vsts. After a day and a workaround, I could make it for the Android version in a Windows agent. Now, I am trying to build the iOS version in a Mac agent.
I found /Library/Frameworks/Mono.framework/Versions/Current/bin/ as the Xbuild path.
The solution seems to need some nuget packages:

![image](https://user-images.githubusercontent.com/5365475/34446999-977ccfe6-ecbe-11e7-9d63-6003f098dd09.png)

So, I added a "NuGet restore" task to downloaded them as I did in the Android Build Definition.
After a while, I could find the following path to get the Mac version of Nuget:
/Library/Frameworks/Mono.framework/Versions/Current/bin/nuget
But it seems that Nuget restore task cannot find the right path to the xbuild or msbuild or msbuild.exe.
Any workaround for this? Thanks

![image](https://user-images.githubusercontent.com/5365475/34446935-291e4d86-ecbe-11e7-8e9e-4bc060eb0528.png)

**Comment by madhurig** [comment]
@eorengo: What version of Xamarin/VS for Mac do you have installed on your macOS build machine? You can try setting the build tool to be "msbuild" and not specify any path to xbuild or msbuild.

Thanks,
Madhuri

**Comment by madhurig** [comment]
@pspill: Can you help @eorengo with the NuGet task issue?

**Comment by eorengo** [comment]
Hi guys,
Sorry to bother. I was wondering if it is possible to prepare a Xamarin iOS build server for TFS2017.2 and how. I tried to follow https://docs.microsoft.com/en-us/vsts/build-release/apps/mobile/xamarin?tabs=vsts but it does not work. Thanks.

**Comment by pspill** [comment]
+ DRI

**Comment by keithrob** [comment]
@eorengo is this still a problem for you?

**Comment by eorengo** [comment]
Hi @keithrob 
No. I had to add custom configuration in the nuget and build steps. The documentation wasn't really helpful but I made it work.
Thanks

**Comment by Ankurmutha** [comment]
What solution or workaround for this issue?

**Comment by eorengo** [comment]
You have to specify a path for NuGet restore and Build Xamarin steps (Advanced). Usually at /Library/Frameworks/Mono.framework/Versions/...
Good luck.
