### ISSUE TITLE
XML variable substitution for applicationSettings

### ISSUE THREAD

**Issue by xingyu217** [Microsoft/vsts-tasks#6134]
```
<applicationSettings>
        <Tools.Instrumentation.Properties.Settings>
            <setting name="LogLevel" serializeAs="String">
                <value>DEBUG</value>
            </setting>
            <setting name="AppName" serializeAs="String">
                <value>MyApp</value>
            </setting>
            <setting name="Port" serializeAs="String">
                <!--value>33333</value-->
                <value>0</value>
            </setting>
        </Tools.Instrumentation.Properties.Settings>
  </applicationSettings>
 <connectionStrings>
    <add name="DefaultConnection" connectionString="Data SourceXXX" providerName="System.Data.SqlClient" />
  </connectionStrings>
```
Variables:
AppName: UpdatedApp
DefaultConnection: XXX

The XML variable substitution doesn't work for applicationSettings, but works fine for connectionString. 
Log:
##[debug]Processing substitution for xml node : applicationSettings
##[debug]Processing substitution for xml node : appSettings
##[debug]Processing substitution for xml node : connectionStrings

So, there isn't the related log after processing applicationSettings, should contains the log like Updating value for key=....

**Comment by vincentdass** [comment]
#6024
This issue is fixed with the above PR and the fix will be available in upcoming deployment.
