### ISSUE TITLE
Unable to explicitly clone private git repo or add as submodule

### ISSUE THREAD

**Issue by sebandraos** [Microsoft/vsts-tasks#6145]
## Environment
- Server - VSTS:  
   
 - If using VSTS, provide the account name, team project name, build definition name/build number: 
https://hal-robotics.visualstudio.com/HAL - HAL.BuildTests

- Agent - Hosted: 
    
    - If using Hosted agent, provide agent queue name: Hosted VS2017

## Issue Description

Inline Powershell Task attempting to add a submodule to the current repository or clone another repository fails if the repository being cloned is private.
I have just two tasks of interest in the definition: Get Sources and the Inline Powershell Script. The former accesses a private repo on github and gets the sources without issue. The powershell script then endeavours to clone another repo, which contains some build specific utilities, but fails. See logs below.
The build definition has "Allow scripts to access OAuth token" enabled and the host repo and repo being cloned have the same access restrictions i.e. if I can access one I should be entitled to access the other. I have tried a number of different approaches, all of which worked with a public repo hosted on the github and owned by the same organisation (XXX redacts real repo names):

#### 1. Add Submodule Relative Path
```
git submodule add ../XXX.git
```
##### Error Logs
```
[error]Cloning into 'D:/a/1/s/XXX'...
/usr/bin/bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error
fatal: clone of 'https://github.com/XXX/XXX.git' into submodule path 'D:/a/1/s/XXX' failed

[error]Process completed with exit code 128 and had 1 error(s) written to the error stream.
```
#### 2. Add Submodule Explicit Path no Auth
```
git submodule add https://github.com/XXX/XXX.git
```
##### Error Logs
```
Cloning into 'D:/a/1/s/XXX'...
/usr/bin/bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error
fatal: clone of 'https://github.com/XXX/XXX.git' into submodule path 'D:/a/1/s/XXX' failed

[error]Process completed with exit code 128 and had 1 error(s) written to the error stream.
```
#### 3. Add Submodule Explicit Path OAuth Token
```
git submodule add https://$(System.AccessToken)@github.com/XXX/XXX.git
```
##### Error Logs
```
[error]Cloning into 'D:/a/1/s/XXX'...
fatal: unable to access 'https://********@github.com/XXX/XXX.git/': The requested URL returned error: 400
fatal: clone of 'https://********@github.com/XXX/XXX.git' into submodule path 'D:/a/1/s/XXX' failed

2018-01-04T13:33:24.2826617Z ##[error]Process completed with exit code 128 and had 1 error(s) written to the error stream.
```
#### 4. Add Submodule Explicit Path OAuth w/ Username
```
git submodule add https://OAuth:$(System.AccessToken)@github.com/XXX/XXX.git
```
##### Error Logs
```
[error]Cloning into 'D:/a/1/s/XXX'...
fatal: unable to access 'https://OAuth:********@github.com/XXX/XXX.git/': The requested URL returned error: 400
fatal: clone of 'https://OAuth:********@github.com/XXX/XXX.git' into submodule path 'D:/a/1/s/XXX' failed

[error]Process completed with exit code 128 and had 1 error(s) written to the error stream.
```
#### 5. Clone Explicit Path OAuth
```
git submodule add https://OAuth:$(System.AccessToken)@github.com/XXX/XXX.git
```
##### Error Logs
```
[error]Cloning into 'XXX'...
fatal: unable to access 'https://OAuth:********@github.com/XXX/XXX.git/': The requested URL returned error: 400

[error]Process completed with exit code 128 and had 1 error(s) written to the error stream.
```

I'm hoping that I have missed the point somewhere but it seems that one if not all of the above options should have worked. Thanks in advance for any assistance.

**Comment by bryanmacfarlane** [comment]
The system access token is a token for accessing resources in the VSTS account.  This doesn't appear to be an issue with one of the tasks in this repo - instead with a custom ps script.  You will need to get a token from github and automate getting into into the config (and devs will need to do the same - use a credential provider).

**Comment by sebandraos** [comment]
Thanks @bryanmacfarlane . You are absolutely right. I had indeed missed the actual role of the token and had assumed that it was the token used to Get Sources regardless of where those sources were. I have now tested with a GitHub PAT and everything is working as expected. Thanks again.
