### ISSUE TITLE
VsTest does not find TestAgent installationPath when installed from vs_testagent.exe

### ISSUE THREAD

**Issue by bryanlikes** [Microsoft/vsts-tasks#6146]
the vswhere search in **function getVSTestConsole15Path()** requires "Microsoft.VisualStudio.PackageGroup.TestTools.Core" which is not found for a vs_testagent.exe only install.

I am using the 2017 vs_testagent.exe install as part of the microsoft/dotnet-framework-build docker container.  The vsts task is searching for test agent using Test platform version "Visual Studio 2017".

I would propose the fallback pattern of "-product Microsoft.VisualStudio.Product.TestAgent" which is available.  When I manually specify the vstest.console.exe found in the installation path, I have run into no issues.

**Comment by cltshivash** [comment]
@bryanlikes There's a new TestPlatform tools installer that brings in the Test Platform without needing a VS/Test Agent installation. You can choose the tools installer option in vstest task to use the platform brought in by the tools installer. Will that help your scenario?

**Comment by bryanlikes** [comment]
I ended up just forking the microsoft docker image and I'm installing the tools using the vs bootstrap installer and specifying the component ID of the testing tools: "Microsoft.VisualStudio.Component.TestTools.Core".  Now vswhere can locate the install dir of vstest.console.exe with no problem.
