### ISSUE TITLE
TFS File not found dotnetcore.js

### ISSUE THREAD

**Issue by mkonars** [Microsoft/vsts-tasks#6147]
## Environment
TFS 2017
Private Agent on Windows Server 2016    

## Issue Description

Hi, our build is failing because the following file is not found:

##[error]File not found: 'C:\agent1\_work\_tasks\DotNetCoreCLI_5541a522-603c-47ad-91fc-a4b1d163081b\0.4.1\dotnetcore.js'

and inside this folder there is typescript file dotnetcore.ts, but no js file

Could you help?

**Comment by bryanmacfarlane** [comment]
Did you upload that task from this repo to your on-prem server?  If so, did you build it?  (it looks like you uploaded source - not the built task).

**Comment by mkonars** [comment]
I've got an answer from our administrator that there was a script running, which has removed too many files. I don't quite understand it, but for now I am closing the issue as it works fine.
