### ISSUE TITLE
PublishSymbols - SymbolsFolder should relative to the build folder

### ISSUE THREAD

**Issue by baywet** [Microsoft/vsts-tasks#615]
Hi,
If you leave it empty it'll be pointing to $(agent.builddirectory)/s/ but as soon as you start typing something it's pointing by default to C:\Windows\System32.
If the entry is not a full path it'd be nice if it could be relative to $(agent.builddirectory) by default (without us needing to add the variable).
I can't think of a scenario where you'd want to index something outside of your build directory.
Thanks!

**Comment by ericsciple** [comment]
Thanks. I'll look into this. At the very minimum the tooltip could be more helpful and give an example.

**Comment by bryanmacfarlane** [comment]
@ericsciple - should we add to tooltip?

**Comment by bryanmacfarlane** [comment]
bump to fix

**Comment by bryanmacfarlane** [comment]
let's fix tooltip for 2017 qu2

**Comment by ericsciple** [comment]
@sprendermsft fyi

**Comment by ericsciple** [comment]
OK, I can't change the default at this point or will break compat (not worth it in this case i dont think). The 2.x version of the task can change the behavior. The current behavior is a bit bizarre.

I think at this point the best we can do in the 1.x version is add examples. Explaining the quirky behavior is probably too complex for the markdown.

**Comment by ericsciple** [comment]
PR https://github.com/Microsoft/vsts-tasks/pull/3925
