### ISSUE TITLE
Download Artifacts in Release Managment continues even cleanup failed

### ISSUE THREAD

**Issue by lukas-ais** [Microsoft/vsts-tasks#6152]
I'm using the on-premise version of TFS (version 2017 U2) with private agents.

When running a release definition sometimes the download of artifacts shows an IOException on cleanup. The process continues without further notice, so I'm not able to identify the item which could not be cleaned, e.g. because any process is accessing file or folder.
How to stop deployment to identify issue? I would like to be sure that the artifact is deployed correctly.

Here is the relevant output:

```
******************************************************************************
Starting: Download Artifacts
******************************************************************************
Downloading artifact
Cleaning artifacts directory: C:\VstsAgent\_work\r1\a
Failed to cleanup Release's artifact directory 'C:\VstsAgent\_work\r1\a' with an exception System.IO.IOException: The directory is not empty
   at System.IO.Win32FileSystem.RemoveDirectoryHelper(String fullPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Win32FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Microsoft.VisualStudio.Services.Agent.Util.IOUtil.DeleteDirectory(String path, Boolean contentsOnly, Boolean continueOnContentDeleteError, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.ReleaseJobExtension.<>c__DisplayClass30_0.<CleanUpArtifactsFolder>b__1()
   at Microsoft.VisualStudio.Services.Agent.Worker.Release.RetryExecutor.Execute(Action action). Retrying the cleanup of Release artifact directory.
Cleaning artifacts directory: C:\VstsAgent\_work\r1\a
Cleaned artifacts directory: C:\VstsAgent\_work\r1\a
Starting artifacts download...
Downloading linked artifact VAC 5.X Dev of type Build...
Ensuring artifact folder C:\VstsAgent\_work\r1\a\VAC 5.X Dev exists and is clean.

**Comment by omeshp** [comment]
@lukas-ais We retry cleanup on failure, from the logs it looks like first cleanup attempt failed but subsequent one passed so the release will pass.

**Comment by GitHubSriramB** [comment]
@lukas-ais - let us know if you have any further queries. closing this issue for now.

**Comment by aivendor** [comment]
any new comments? I met same problem here.

**Comment by omeshp** [comment]
@aivendor Are you releases failing? Can you attach release logs?

**Comment by lukas-ais** [comment]
@omeshp You are right. It seems to be a retry.
I think the messages could be improved to understand the activities.
I would like to contribute. But I'm unable to identify the relevant code section. You you take me there?

**Comment by aivendor** [comment]
@omeshp You can check my release log here.
[releasefailure.txt](https://github.com/Microsoft/vsts-tasks/files/1663484/releasefailure.txt)
