### ISSUE TITLE
Azure Powershell "Could not load file or assembly" - update powershell version

### ISSUE THREAD

**Issue by matslo** [Microsoft/vsts-tasks#6169]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS
   
- Agent - Hosted VS2017

## Issue Description

 The VSTS task "Azure PowerShell" is using version 5.0.0 as latest installed version. This version have errors when loading assemblies. Can you updated the latest version to be 5.0.1 or 5.1.1?

### Error logs
[error]Could not load file or assembly 'Microsoft.Data.Services.Client, Version=5.6.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

**Comment by onionhammer** [comment]
I'm seeing something very similar, but with `System.Spatial`

```
2018-01-09T17:41:43.6040657Z ##[error]Could not load file or assembly 'System.Spatial, Version=5.8.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified. HTTP Status Code: 200 - HTTP Error Message: OK
```

**Comment by arjgupta** [comment]
@matslo , we have updated the hosted vs 2017 pool agent with azure powershell v 5.1.1. closing this issue.
