### ISSUE TITLE
How to authenticate the user with OTP (one time password) validation using Coded UI c#

### ISSUE THREAD

**Issue by Cva2904** [Microsoft/vsts-tasks#6172]
Hi All,

I do have a requirement to authenticate the user with OTP validation instead of user id and password option in my web Application. I'm using html pages with C# and Coded to test this.

I searched lot of things but couldn't able to get corresponding related info. If any one of you had faced the same requirement, kindly let me know what to do in order to get resolve this issue.

Thanks!!!

**Comment by daveVSTS** [comment]
You will likely get better tracking posting on stackoverflow.  Issues not directly related to tasks are not likely to get traction in this repository's issues.

**Comment by Cva2904** [comment]
I have resolved the issue. 
Thanks!
Siva. A
