### ISSUE TITLE
Add option to not run az clear at end of Azure CLI VSTS Task

### ISSUE THREAD

**Issue by mikermesh** [Microsoft/vsts-tasks#6176]
We are using the Azure CLI task to grab an access token to be used in a subsequent task. However, it looks like the Azure CLI step is executing the az clear command which clears out the token at the end of that task. We were able to get around this by creating two Powershell tasks to issue the az login command as a Service Principal and a second to run the az clear command. We would prefer to use the Azure CLI task as it runs as a service endpoint which obscures the credentials. Is there an option to prevent the az clear from running?

**Comment by sachinma** [comment]
We can consider adding it to the advanced section. Adding @RoopeshNair  for his opinion here.
However, as a work-around after you have generated the token, consider saving it in secret variable. Will this approach variable. You can use echo "##vso[task.setvariable <>=<>;issecret=true;]" to do it.

**Comment by RoopeshNair** [comment]
Using task output variables is the right approach. Let us know if it isn't working for you

**Comment by weznagwama** [comment]
@sachinma how would you then use this variable in subsequent steps?

**Comment by sachinma** [comment]
Any variable set with ##vso[task.setvariable ..] will be available to next set of tasks same as any other build/release variable.

**Comment by RoopeshNair** [comment]
secret variables have to be explicitly passed as an argument to the next step.

**Comment by weznagwama** [comment]
so output a variable with the value `az account get-access-token` should suffice

**Comment by alan-marcinkowski** [comment]
I'm not sure I see the value in passing the secret value. If I have a subsequent task such as a maven task, how would the maven task leverage that variable to effectively "az login"?

**Comment by emrekara37** [comment]
Hi,Is there any progress on this issue?

**Comment by cesarqdt** [comment]
Will there be an option to disable `az clear`? I need to use the kubeconfig downloaded to the agent, and I'm unable to do it with the `az clear`
