### ISSUE TITLE
Cannot reference ARM linked templates / nested templates in private Github repo without workaround

### ISSUE THREAD

**Issue by rswe** [Microsoft/vsts-tasks#6194]
## Issue Description:
In github, you can get the raw content url and attach a token to  azuredeploy.json uri.  How the access token is secured is most probably with CI CD tools.                     
But you can do that only with  azure storage, to my knowledge. ARM engine is only capable of url  authorization. it won't pass any username, tokens,

investigation shows there is no way to use a URL and github available authentication mechanisms to authenticate/reference a linked template in private github repo, without a workaround, an Azure Function being the simplest option:
https://blog.tyang.org/2017/05/19/deploying-arm-templates-with-artifacts-located-in-a-private-github-repository/
https://stackoverflow.com/questions/46644690/azure-arm-templates-linked-templates-with-vsts-git
https://social.msdn.microsoft.com/Forums/Windows/en-US/54876f00-4bf4-4d84-81af-e7a1128ac6f7/linking-arm-templates-in-private-github-repo?forum=windowsazurewebsitespreview

## Environment
VSTS
Agent - Hosted: agent queue name: inherited
Azure Resource Group Deployment task version 2.*
Task Name: Azure Deployment:Create Or Update Resource Group
Action: Create or update resource group
Template location: Linked artifact (Github private repo e.g both template & param)

Is it feasible to make a change to allow URL only access to templates in a private repo rather than using a workaround?
thanks

**Comment by rswe** [comment]
The only non-code workaround I can think of is 
1) (if possible) create a private SAS token controlled artifacts Azure blob location (in a VSTS task if possible?)
2) have Github push any changes => artifacts blob location.
Then the ARM template could reference the linked templates via URL + SAS token.
But I don't know if 1 & 2 as feasible/recommended?

**Comment by oclgithubdeployuser1** [comment]
FYI the Azure Function proxy workaround https://blog.tyang.org/2017/05/19/deploying-arm-templates-with-artifacts-located-in-a-private-github-repository/ requires a Github Personal Access Token, which does not work with 'public_repo, repo:invite, repo:status, repo_deployment' privs. It additionally requires 'repo: full control of private repos' privs, meaning that the deployment solution can delete the source from all repos that the github dummy deployment user (created for just deployments rather than using a named user). So not an ideal workaround.

**Comment by rswe** [comment]
FYI the Azure Function proxy workaround https://blog.tyang.org/2017/05/19/deploying-arm-templates-with-artifacts-located-in-a-private-github-repository/ requires a Github Personal Access Token, which does not work with 'public_repo, repo:invite, repo:status, repo_deployment' privs. It additionally requires 'repo: full control of private repos' privs, meaning that the deployment solution can delete the source from all repos that the github dummy deployment user (created for just deployments rather than using a named user). So not an ideal workaround.

**Comment by sachinma** [comment]
HI @rswe , you can use "Azure File Copy" Task along with "Azure Resource group" task to achieve this using built-in tasks. You can upload files to an azure blob storage using Azure File Copy task. The task also outputs the Shared access token. This way you don't need to manage the update of the file content into azure blob outside of your release process. You release will take care both.

As an example, you can define two new variables (storageAccountName and sasToken) in your Arm template and then form the uri property of the linked template as follows. sasToken variable can be updated by the Azure File Copy task.

"uri":"[concat('https://',  parameters('storageAccountName') '.blob.core.windows.net/templates/WebAppLinked.json', parameters('sasToken'))]",

**Comment by RoopeshNair** [comment]
The URLs should be publicly available and should accept URL authorization for ARM deployments. It is not a limitation in ARM task of VSTS.
