### ISSUE TITLE
allow test url/id created by Publish Test Results task to be used in a later task

### ISSUE THREAD

**Issue by rohit21agrawal** [Microsoft/vsts-tasks#6197]
the publish test result task creates a run id and generates a url , but there is no way to retrieve this url or id. an easy option would be set an environment variable with the test run title as key and the id as the value (just one of the many possible options to do it). 

if you can point me in the right direction, i would be willing to do a PR too.

**Comment by vinodjo** [comment]
Thanks for you suggestion Rohit. I have added the request to our backlog, however at this stage it is relatively lower in our priority. In the interim, with the build id you can create build uri and use the API(s) below to get the run information for a build.
https://www.visualstudio.com/en-us/docs/integrate/api/test/runs#get-a-list-of-test-runs
