### ISSUE TITLE
[IISWebAppDeploymentOnMachineGroup] readme appears to be outdated

### ISSUE THREAD

**Issue by jshepler** [Microsoft/vsts-tasks#6207]
https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/IISWebAppDeploymentOnMachineGroup

Missing information about xml transforms and variable substitution options.

References "machine groups" instead of "deployment groups".

**Comment by chshrikh** [comment]
@RoopeshNair

**Comment by Ajay-MS** [comment]
@jshepler 

Thanks for your feedback. Have updated documentation.

**Comment by jshepler** [comment]
In the section on deployment groups, there's a link to instructions for downloading/installing the agent - the link is wrong.
