### ISSUE TITLE
[IISWebAppDeploymentOnMachineGroup] not clear on how xml transformations are expected to be used

### ISSUE THREAD

**Issue by jshepler** [Microsoft/vsts-tasks#6208]
According to the help popup on the xml transformation option, "The config transforms will be run for *.Release.config and *.<EnvironmentName>.config on the *.config file."

However, the transform files aren't available at the time the release is running. The build applies the transform and doesn't include the files (e.g. web.sandbox.config) in the output or package. I don't know how to get those transform files included in the artifacts, they're not done by default and it's not obvious how one would do so.

**Comment by vincentdass** [comment]
You can refer to this [doc](https://docs.microsoft.com/en-us/vsts/build-release/tasks/transforms-variable-substitution#xmltransform).

**Comment by vincentdass** [comment]
Closing the thread, as there is no action item from team required.

**Comment by jshepler** [comment]
You linked to an article, great, but that's not discoverable from the task. At the very least, the info popup for that option in the task should link to the article. Maybe even include it in the tasks's readme, https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/IISWebAppDeploymentOnMachineGroup

**Comment by vincentdass** [comment]
sure, will do it.
