### ISSUE TITLE
Visual Studio Test Agent deployed on vm aborts Test Execution  on remote VM after 6 hrs of execution

### ISSUE THREAD

**Issue by Manvibha** [Microsoft/vsts-tasks#6214]
Hi, 

I have automation builds configured to execute GUI based selenium test suite to execute on Azure VM. 
From last 3 days , I am seeing that after 6 hrs of execution , test agent aborts test execution and no clue why it is doing so. 

I have Test agent deployed via build on Azure windows 10 box. It discovered tests and initializing  test execution and tests were executed. However,  after 6 hrs of execution , test execution is aborted and no test results are published other than aborted for all test scripts. 

Below is the extract from DTAExecutionHost.exe.log 
============================================================
 ProcessId=9564
    ThreadId=37
    DateTime=2018-01-12T09:52:09.7578351Z
    Timestamp=1045366673797
DTAExecutionHost.exe Information: 0 : ExecutionTaskStateModel.ListenerCommandReceived : Requesting a stop on Stop command.
    ProcessId=9564
    ThreadId=37
    DateTime=2018-01-12T09:52:09.7578351Z
    Timestamp=1045366675137
DTAExecutionHost.exe Information: 0 : TestExecutionServiceCommandQueueListener.DispatchAsync : Stop listening on Stop command.
    ProcessId=9564
    ThreadId=37
    DateTime=2018-01-12T09:52:09.7578351Z
    Timestamp=1045366676867
DTAExecutionHost.exe Information: 0 : DefaultTestRunEvenHandler.CancelAsync : Run tests have been cancelled
    ProcessId=9564
    ThreadId=31
    DateTime=2018-01-12T09:52:09.7588394Z
    Timestamp=1045366684875
DTAExecutionHost.exe Information: 0 : ExecutionHost.UnregisterFromServer : Agent is unregistering from server.
    ProcessId=9564
    ThreadId=31
    DateTime=2018-01-12T09:52:09.7648345Z
    Timestamp=1045366747533
Web method running: [https://itron.visualstudio.com/_apis/test/Agents/19300] (DELETE)19300[test] E2EId: 0664e71d-d46f-4f38-bb83-7c8cfb176695
Web method response: [https://itron.visualstudio.com/_apis/test/Agents/19300] (DELETE)19300[test] E2EId: 0664e71d-d46f-4f38-bb83-7c8cfb176695, ActivityId: 8ff0249a-fe23-4e83-b9e7-809e32c6bb3e 64 ms
DTAExecutionHost.exe Information: 0 : ##########################################################################
    ProcessId=9564
    ThreadId=1
    DateTime=2018-01-12T09:52:09.8307494Z
    Timestamp=1045367399093
=================================================
Extract from build task 
===========================================
2018-01-12T09:52:27.6816310Z ##[warning]DistributedTests: Test run is aborted. Logging details of the run logs.
2018-01-12T09:52:28.0179121Z ##[warning]DistributedTests: New test run created.
2018-01-12T09:52:28.0179121Z Test Run queued for Project Collection Build Service (itron).
2018-01-12T09:52:28.0179121Z 
2018-01-12T09:52:28.0179121Z ##[warning]DistributedTests: Test discovery started.
2018-01-12T09:52:28.0179121Z ##[warning]DistributedTests: Test Run Discovery Completed . Test run id : 120946
2018-01-12T09:52:28.0179121Z ##[warning]DistributedTests: 78 test cases discovered.
2018-01-12T09:52:28.0179121Z ##[warning]DistributedTests: Test execution started. Test run id : 120946
2018-01-12T09:52:28.0179121Z ##[warning]DistributedTests: Test run timed out. Time out : 21600000 ms. Test run id : 120946
2018-01-12T09:52:28.0179121Z ##[warning]DistributedTests: Test run aborted. Test run id: 120946
2018-01-12T09:52:28.0199370Z ##[error]System.Exception: The test run was aborted, failing the task.
2018-01-12T09:52:28.0625721Z ##[error]PowerShell script completed with 1 errors
=======================================================

**Comment by abhishkk** [comment]
@Manvibha 
RFT task has internal timeout of 6 hours. You can override this timeout by adding timeout in testsettings.

Please add following in testsettings:
`<?xml version="1.0" encoding="utf-8"?>`
`<TestSettings name="TestSettings1" id="2ac68d7c-6e7e-4862-a377-e32c0d3f698d" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">`
`  <Execution>`
`    <Timeouts runTimeout="200000000" />`
`  </Execution>`
`</TestSettings>`

Here timeout value is in milliseconds.

**Comment by abhishkk** [comment]
Closing this issue. Let us know if issue is unresolved.

**Comment by Manvibha** [comment]
Thanks, I checked that option. However, I do not use Testsettings for my execution, shouldn't this be independent of such settings? 

regards,
@Manvibha ~Mahendra

**Comment by abhishkk** [comment]
@Manvibha Sadly for longer running tests (more than 6 hours), overriding timeout is possible from testsettings only.

**Comment by varnk** [comment]
This is a poor solution.  I have a similar problem.  You cannot use .testsettings file if you are executing tests using Test Plan for Test Selection.  I absolutely need to increase this timeout.  There has got to be a better way to do this or else this needs fixed ASAP!

**Comment by ShreyasRmsft** [comment]
It is possible to override the 6 hour timeout via runsettings for the vstest distributed flow in vsts now. DTA RFT is no longer supported and the task had been deprecated.

Please move to the vstest task for any fixes.
