### ISSUE TITLE
VSTS linux build agent does not terminate child commands on cancel

### ISSUE THREAD

**Issue by williambernardet** [Microsoft/vsts-tasks#6218]
## Environment
Currently using TFS2017.2 with agent 2.117.2 on Linux Ubuntu

## Issue Description

When executing a command on a Linux VSTS agent, tasks do not handle properly signal propagation. So when cancelling a build, the agent sends a SIGINT to the NodeJS process executing the task (https://github.com/Microsoft/vsts-agent/blob/v2.117.1/src/Microsoft.VisualStudio.Services.Agent/ProcessInvoker.cs), but the NodeJS task itself is not handling propagation. (e.g ShellScript or mainly any task using toolRunner)

**Scenario**
===========

Here is an example of the processes running during the build:

    21614 ?        S      0:00 /bin/bash /home/surfadmin/myagent/runsvc.sh
    21620 ?        Sl     0:00  \_ ./externals/node/bin/node ./bin/AgentService.js
    21631 ?        SLl    6:57      \_ /home/surfadmin/myagent/bin/Agent.Listener run
     4549 ?        SLl    0:03          \_ /home/surfadmin/myagent/bin/Agent.Worker spawnclient 156 162
     4617 ?        Sl     0:00              \_ /home/surfadmin/myagent/externals/node/bin/node /home/surfadmin/myagent/_work/
     4624 ?        SLl    0:01                  \_ /usr/bin/powershell -File /home/surfadmin/myagent/_work/8/s/Cancel-Test.ps
     4662 ?        S      0:00                      \_ /bin/sleep 1
 
 
After cancellation, the powershell subprocess is detached from the tree and continue to run:

    21614 ?        S      0:00 /bin/bash /home/surfadmin/myagent/runsvc.sh
    21620 ?        Sl     0:00  \_ ./externals/node/bin/node ./bin/AgentService.js
    21631 ?        SLl    6:57      \_ /home/surfadmin/myagent/bin/Agent.Listener run
    17536 ?        Ssl    0:21 rsyslogd
     4624 ?        SLl    0:02 /usr/bin/powershell -File /home/surfadmin/myagent/_work/8/s/Cancel-Test.ps1 -Count 600
     4751 ?        S      0:00  \_ /bin/sleep 1
 
From the agent log you can see

    [2018-01-11 19:35:07Z INFO StepsRunner] Cancel current running step.
    [2018-01-11 19:35:07Z INFO ProcessInvoker] Sending SIGINT to process 4617.
    [2018-01-11 19:35:07Z INFO ProcessInvoker] Successfully send SIGINT to process 4617.
    [2018-01-11 19:35:07Z INFO ProcessInvoker] Waiting for process exit or 10 seconds after SIGINT signal fired.
    [2018-01-11 19:35:07Z INFO ProcessInvoker] Finished process with exit code 130, and elapsed time 00:00:29.4454607.
    [2018-01-11 19:35:08Z ERR  StepsRunner] Caught cancellation exception from step: System.OperationCanceledException: ...

which means node process has been killed properly. Issue is that the JS task should handle the signal (e.g: process.on('SIGINT',...)) to propagate the signal to its child.
Based on feedback I did test 2.126.0 agent with process.clean, but as it seems to use SIGKILL, so powershell just dies without executing the cleanup procedure in the finally clause.
With windows build similar script behaves correctly and you can see the "Finally closing..." message on the console meaning the process has been gracefully ended.

**Script used for testing**

    [CmdletBinding()]
    param(
        [int]$Count = 20
    )
    Process {
        Try {
            while ($Count) {
                Write-Host "wait..."
                sleep 1
                $Count--;
            }
        } catch {
            Write-Host "Caught: $_.Exception.Message"
        } finally {
            Write-Host "Finally closing..."
        }
    }

### Error logs

[Insert error from the logs here]

**Comment by bryanmacfarlane** [comment]
Should log this issue in the vsts-task-lib repo

**Comment by williambernardet** [comment]
Created new issue: https://github.com/Microsoft/vsts-task-lib/issues/306
