### ISSUE TITLE
##vso[task.uploadsummary]  - Upload HTML file with javascript -  doesnt work

### ISSUE THREAD

**Issue by manjunath6681** [Microsoft/vsts-tasks#6223]
Using TFS 2017 on Prem
Agent runs on windows 7 Enterprise machine

Description : 
  My requirement is to upload an HTML summary file to summary tab of TFS release at the end of my release. This file would display the MSIs and the versions installed in all servers like a summary.
I want to use a button to Toggle between hiding and showing the HTML content for which i have a small javascript(inthe same file under <script> tag which must be triggered on click of the button.

I have created a html file with javascript but the file was named with .md extension and i use the command ##vso[task.uploadsummary]  to upload the file.

Issue : 
   though the file is successfully uploaded and is visible in the summary Tab of the release, the button`s onclick function never gets triggered I suspect this is due to the file extension. is there a way to make it work ?

**Comment by bryanmacfarlane** [comment]
That's for simple markdown additions to summary.

For scenarios like this, you can create an extension.  Here's a sample:
https://github.com/Microsoft/vsts-extension-samples/tree/master/build-results-enhancer
