### ISSUE TITLE
Task not showing on vsts task list

### ISSUE THREAD

**Issue by christophearg** [Microsoft/vsts-tasks#6226]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
   I'm using VSTS: ercg.visualstudio.com DriverPortal project. I'm trying to create a release for deploying to azure, but this task does not appear on the list of tasks. Is there a prerequisite? Or a way to manually add this task to the vsts release task lists?

**Comment by GitHubSriramB** [comment]
@christophearg - which task are you trying to add?

**Comment by christophearg** [comment]
I'm trying to add an Azure App Service Deployment task

**Comment by GitHubSriramB** [comment]
@christophearg - Sorry for the delay. Is this issue still happening for you?

**Comment by GitHubSriramB** [comment]
@christophearg - pl. let us know if this issue is still not resolved for you. For now I am closing this issue.
