### ISSUE TITLE
AzureFileCopy fails when prefix ends in 0

### ISSUE THREAD

**Issue by lehne** [Microsoft/vsts-tasks#6227]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS 

- Agent - Hosted or Private: 
    Private- Windows

## Issue Description

When we use prefix that ends in 0, for example "myproduct/folder/1.0.7.0", the task fails with the error message below. The upload works when we change the folder to 1.0.7.1. We are uploading to Azure Blob resource manager subscription with block blob of about 130Mb. The error message is also empty when this happens.

### Error logs

Upload to container: 'software' in storage account: 'myaccount' with blob prefix: 'myproduct/folder/1.0.7.0' failed with error: '' For more info please refer to https://aka.ms/azurefilecopyreadme

**Comment by pavanadepu2** [comment]
@lehne, I tried the same scenario, it is working fine for me. I am able to upload the file to a blob prefix of "myproduct/folder/1.0.7.0". Can you email the debug logs to RM_Customer_Queries@microsoft.com to analyze the issue further.

**Comment by lehne** [comment]
That is very strange. We were using a variable in place of the version number. Perhaps that was the problem. Are the debug logs just the log printout?

**Comment by sachinma** [comment]
You can define a variable in the release with the name "system.debug" and have its value set to true. After that next time when the task runs, it would be have debug logs. You can go to the logs section in the release and look at the task logs there.

**Comment by pavanadepu2** [comment]
@lehne, did you get a chance to collect the debug logs. Please share the debug logs to analyze the issue further.

**Comment by asranja** [comment]
@lehne ping !

**Comment by chshrikh** [comment]
closing this. If issue is still there, please share debug logs to RM_Customer_Queries@microsoft.com to analyze the issue further.
