### ISSUE TITLE
SonarQube Analysis - Javascript

### ISSUE THREAD

**Issue by RDalziel** [Microsoft/vsts-tasks#623]
What's the best way to do Javascript analysis with the current VSO Task? it seems to have recently changes to an MSBuild Analysis by default? (Or at least, i've noticed my javascript is not analysed anymore).

Is the intention here to have a separate task to handle different analysis types?

**Comment by bgavrilMS** [comment]
+ @duncanpMS

Hi @RDalziel - do you use any build engine? We currently support MsBuild and also the Maven task will soon have support for SonarQube analysis. 

For pure JavaScript analysis, SonarSource have documented http://docs.sonarqube.org/display/PLUG/JavaScript+Plugin - you should be able to kick off the analysis using a CMD task, after you have installed the sonar-runner and have created a sonar.properties file.

**Comment by RDalziel** [comment]
I have a repository with both MSBuild and Projects and a javascript project. On the earlier versions, my javascript would get picked up in the analysis, now i can't seem to get it to run on the Javascript. I've added a sonarqube analysis xml to the root folder of the javascript project. On finishing analysis i get the following error:

"
Starting task: Finish the analysis and upload the results to SonarQube
******************************************************************************
Executing the powershell script: E:\BuildVNextAgents\Agent3\tasks\SonarQubePostTest\1.0.28\SonarQubePostTest.ps1
No ProjectInfo.xml files were found. Possible causes: you specified an invalid build configuration or the custom MSBuild analysis targets were not imported.
Post-processing failed. Exit code: 1
Default properties file was not found at E:\BuildVNextAgents\Agent3\tasks\SonarQubePreBuild\1.0.28\MSBuild.SonarQube.Runner-1.0.1\SonarQube.Analysis.xml
Post-processing started.
09:24:59.73  WARNING: Failed to find the code coverage command line tool. Possible cause: Visual Studio is not installed, or the installed version does not support code coverage.
Generation of the sonar-properties file failed. Unable to complete SonarQube analysis.
09:24:59.746  Creating a summary markdown file...
Unexpected exit code received from batch file: 1"

**Comment by duncanpMS** [comment]
This looks like bug [SONARMSBRU-130](https://jira.sonarsource.com/browse/SONARMSBRU-130), which was fixed in 1.0.1. Do you have the latest version of the C# plugin installed on your SonarQube server?
Are you using a hosted build agent or on-premise build agent, and if you are using an on-premise build agent has the configuration of the machine changed recently (e.g. set up an new agent machine or changed the edition of VS installed on the machine)?

**Comment by RDalziel** [comment]
I've recently spun up new build servers recently and attempted to automate the creation of these machines with DSC - This resulted in me using this chocolatey package for VS - 

https://chocolatey.org/packages/VisualStudio2015Enterprise/14.0.23107.0

I should say, there doesn't appear to be any issues with the c# analysis. It's only Javascript which is causing issues at the moment. My aim is just to point sonarqube at my Javascript files as well as an LCOV coverage results file and have them represented in Sonarqube.

**Comment by duncanpMS** [comment]
So you had the analysis working on a previous build agent? Do you still have that build agent, and does analysis still work on that machine?
The way the MSBuild Runner decides which files to analyse has not changed. It looks in the MSBuild project for a specific list of ItemGroup types, and passes the files listed in those ItemGroups to the sonar-runner for analysis. JavaScript files in ASP.Net applications are included in the list of files to be analysed.

**Comment by RDalziel** [comment]
Was just testing this on the old agent - I do seem to get a little further, however it errors on this project with the following:

" No analysable projects were found but some duplicate project IDs were found. Possible cause: you are building multiple configurations (e.g. DEBUG|x86 and RELEASE|x64) at the same time, which is not supported by the SonarQube integration. Please build and analyse each configuration individually."

Ideally the Project Files wouldn't matter and i could tell SonarQube to analyse Javascript files in a specific folder. Is it absolutely required to have a project file looking at the files?

**Comment by duncanpMS** [comment]
It is if you are using the MSBuild Runner.

These sound like configuration issues, not product bugs. Support queries are handled on stackoverflow (tag questions with "sonarqube").

The simplest way to check that you can analyse everything you want to is using the command line. The instructions are [here](https://github.com/SonarSource/sonar-.net-documentation/blob/master/doc/analyze-from-the-command-line.md). If you know that the projects can be analysed, then you can focus on working out what is different about the setup on your agent machines.

**Comment by RDalziel** [comment]
Thanks @duncanpMS i'll dig a little deeper here and see if i can replicate the issue outside of the build task. I do realise it is a bit configuration heavy.

**Comment by bryanmacfarlane** [comment]
Any updates here?  @RDalziel  ?

**Comment by RDalziel** [comment]
Apologies bryan, fairly disconnected from this at the moment. However i may come back to javascript & typescript analysis soon.

**Comment by bgavrilMS** [comment]
Please reopen the issue if you still have problems. As Duncan noted, general SonarQube queries are better addressed on Stackoverflow as the SonarQube engineers monitor questions there.
