### ISSUE TITLE
Deploy an Azure Web virtual application

### ISSUE THREAD

**Issue by phatcher** [Microsoft/vsts-tasks#624]
How can I deploy a virtual application - as far as I can tell the Azure Web App Deployment task can't do it as it uses Publish-AzureWebSiteProject which can't handle virtual applications

**Comment by chrisrpatterson** [comment]
What do you mean virtual application? I am not familiar with that feature of azure web apps.

Sent from my Windows Phone
________________________________

**Comment by phatcher** [comment]
Like on IIS you can have virtual applications, i.e. one web site can support multiple applications each in their own directory. The azure version is slightly more limited in that they share an app pool but that's ok for my scenario as we'd get resilience from scaling instances.
The advantage from a development perspective is that you can keep code separation between different projects; I'm using it for a project where I have a REST API and an MVC app and it forces me to dog food the REST API in the MVC app since I have no access to the database etc.
A good coverage is found in http://blogs.msdn.com/b/tomholl/archive/2014/09/22/deploying-multiple-virtual-directories-to-a-single-azure-website.aspx

**Comment by phatcher** [comment]
Here's a little poweshell script which uses WebDeploy to deploy a virtual application, I can do it more formally if the fix to Publish-AzureWebSiteProject will take a while
-------------------------------------------------------------------------
param(
    [Parameter(mandatory=$true)][string]$Name,
    [Parameter(mandatory=$true)][string]$App,
    [Parameter(mandatory=$true)][string]$Package,
    [Parameter(mandatory=$true)][string]$userName,
    [Parameter(mandatory=$true)][string]$password
)

$MSDeployKey = 'HKLM:\SOFTWARE\Microsoft\IIS Extensions\MSDeploy\3' 
if(!(Test-Path $MSDeployKey)) { 
    throw "Could not find MSDeploy. Use Web Platform Installer to install the 'Web Deployment Tool' and re-run this command" 
} 

$InstallPath = (Get-ItemProperty $MSDeployKey).InstallPath 
if(!$InstallPath -or !(Test-Path $InstallPath)) { 
    throw "Could not find MSDeploy. Use Web Platform Installer to install the 'Web Deployment Tool' and re-run this command" 
} 

$msdeploy = Join-Path $InstallPath "msdeploy.exe" 
if(!(Test-Path $MSDeploy)) { 
    throw "Could not find MSDeploy. Use Web Platform Installer to install the 'Web Deployment Tool' and re-run this command" 
} 

$publishUrl ="https://$Name.scm.azurewebsites.net:443/msdeploy.axd?site-name=$Name"
$webApp     ="$Name\$App"

Write-Host "Deploying package to $publishUrl for app $($App)"

$arguments = 
    "-source:package='$package'",
    "-dest:auto,computerName='$publishUrl',userName='$userName',password='$password',authType='Basic',includeAcls='False'",
    "-setParam:name='IIS", "Web", "Application", ("Name',value='" + $webApp + "'"),
    "-verb:sync",
    "-allowUntrusted"

Write-Host $arguments

. $msdeploy $arguments

**Comment by roniga** [comment]
Hi phatcher,
    Can you check if IISWebAppDeployment task would suit your needs?
https://github.com/Microsoft/vso-agent-tasks/tree/master/Tasks/IISWebAppDeployment

**Comment by phatcher** [comment]
If I read it correctly, it seems more focused around deploying to VMs rather than the Azure AppService, but I'll have a play with it this weekend.
Fixing Publish-AzureWebSiteProject to take an app name would be the best result I think.

**Comment by dustinbrooks** [comment]
Just chiming in for my need to also be able to use the Azure Web App Deployment step to deploy to a virtual directory under a webapp.

Going to use 2 separate webapps for now

**Comment by phatcher** [comment]
@dustinbrooks, the poweshell script I wrote works fine BTW, so you can have virtual apps if you want, you just have to have configured them before hand as it can't create them as part of the publish

**Comment by chungvinhkhang** [comment]
@phatcher: hello, i tried your above ps, it ran but after completed, it removed the virtual app directory if existed and do nothing if not. are there anything i've missed?

**Comment by glaidler** [comment]
Any update on this being available out of the box? (thx for script @phatcher btw)

**Comment by glaidler** [comment]
Hi @phatcher - I know this script is just to help out, but I'm useless at powershell and I'm getting:

Unrecognized argument '"-source:package='C:\a\c85d97647\Standard Build\drop\api\api\obj\Release\Package\harbour.api.zip'"'. All arguments must begin with "-".

Any pointers?

G

**Comment by phatcher** [comment]
@glaidler I'd try putting an echo to see the entire command and then debugging the Powershell in ISE to see if something is mis-quoted etc
I'll re-deploy my project a bit later on and see if I can find anything helpful

**Comment by glaidler** [comment]
spoke too soon.  Powershell commands with spaces is fundamentally painful.

**Comment by phatcher** [comment]
Well my one gets a Hanselman #WorksOnMyMachine tag - did about 4 deploys yesterday and they all worked fine - sorry for your pain :-)

**Comment by rschiefer** [comment]
Thanks to @phatcher and his PowerShell script I have created a VSTS/TFS deploy task for deploying an MSDeploy package.  It can be used for advanced MSDeploy package deployments, including virtual app deployments to Azure.  

http://dotnetcatch.com/2016/03/22/vsts-release-custom-deploy-task-to-deploy-virtual-applications-to-azure/

**Comment by yaananth** [comment]
@rschiefer  thanks for putting those together, adding muthu FYI @kmkumaran , since we place to start working on new tasks supporting behaviors.

**Comment by rschiefer** [comment]
@yaananth cool, let me know if there is anything I can do to help!

**Comment by kmkumaran** [comment]
Thanks @yaananth @rschiefer.

**Comment by phatcher** [comment]
@glaidler  - found the issues, it's to do with spaces in the package path which requires a fairly funky solution to get around Powershell -> Cmd escaping...

```
$arguments = 
    "-source:package=""$packageFile""",
    "-dest:auto,computerName='$publishUrl',userName='$userName',password='$password',authType='Basic',includeAcls='False'",
    "-setParamFile:""$parametersFile""",
    "-setParam:name='IIS", "Web", "Application", ("Name',value='" + $webApp + "'"),
    "-verb:sync",
    "-allowUntrusted"

Write-Host $arguments

$msdeployCmd = Get-Command $msdeploy
$command = "& `$msdeployCmd --% $arguments"
$sb = $ExecutionContext.InvokeCommand.NewScriptBlock($command)

Write-Host $command

try
{
    . $sb
}
catch 
{
    exit 1
}

```

I've also packaged up this task and an equivalent IIS WebDeploy one (the MS one requires admin rights rather than just WebDeploy rights) and they are available on https://github.com/phatcher/Meerkat.Tasks

**Comment by mvvsubbu** [comment]
We have addressed this using AzureRM Web App Deployment task ( https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/AzureRmWebAppDeployment ) for ASP.NET 4 web sites created ARM portal.

**Comment by glaidler** [comment]
@phatcher thanks! didn't get notified about your response.

@mvvsubbu - how do I get access to this AzureRM Web App Deployment task?  my vsts account is harbourassist.visualstudio.com

**Comment by mvvsubbu** [comment]
This task is public available, display name of the task is "Azure App Service Deployment: ARM"
