### ISSUE TITLE
"Bind address needs a port" error when running Docker-Compose as agent on Linux Host

### ISSUE THREAD

**Issue by pageflex** [Microsoft/vsts-tasks#6254]
## Environment
- Server - VSTS
    - Pageflex-pando-dev.visualstudio.com / Teamcity.DocumentReleaseNotes 

- Agent - Private / Docker Azure Linux  

## Issue Description
Docker-Compose build runs successfully when sshed in as the docker-machine default user, but when running as vsts agent, it fails with a port bind error.

**Failure**
![image](https://user-images.githubusercontent.com/35233719/35112270-255a8fa4-fc43-11e7-8ddf-e5a11c39b0ba.png)

### Error logs
[_diag.zip](https://github.com/Microsoft/vsts-tasks/files/1643845/_diag.zip)
[logs_14.zip](https://github.com/Microsoft/vsts-tasks/files/1643849/logs_14.zip)

**Comment by jikuma** [comment]
You are running docker client and docker host on a separate machine, but the client is not able to connect to docker host.
It seems that server URL in Docker host endpoint is not correctly set. Is this your server url : https://pf-docker-host.centralus.cloudapp.azure.com/
It should contain the port number where Docker host is running. By default it is 2376. You can refer [https://docs.docker.com/machine/reference/env/](here) how to specify Docker host url
e.g. tcp://192.168.99.101:2376

**Comment by pageflex** [comment]
Actually, I think they are on the same machine. I'm not using a "hosted" task, but a task set to a private docker host that i deployed to azure.

I read the documentation you linked. I ran the command it asked me through docker-machine from my local machine. The commands I ran were windows centric.

![image](https://user-images.githubusercontent.com/35233719/35158419-9c5d16c6-fcfc-11e7-925a-b4d077269c0e.png)

 even editting the .bashrc on the linux azure docker host had no effect to vsts. Same errors. 

I tried setting them in the extra environment variables as well, and the exports that were generated locally were for my local machine and did't work, especially around the tls and cert path.

I then tried to just set the DOCKER_HOST to various settings, here's with the url (log 20)

![image](https://user-images.githubusercontent.com/35233719/35158466-c870ae6c-fcfc-11e7-89ae-d504b1b4933f.png)

generated the following error: 

"Invalid bind address protocol: {0}".format(addr)
2018-01-19T14:34:39.9173072Z ##[error]docker.errors.DockerException: Invalid bind address protocol: "https://pf-docker-host.centralus.cloudapp.azure.com:2376"


When I set it to the IP address (log 19):

![image](https://user-images.githubusercontent.com/35233719/35158644-5c037f1a-fcfd-11e7-8457-44e0e454d70a.png)

Generated the following error:

Invalid bind address protocol: "https://52.176.45.116:2376"

I then tried to go into the docker host service definition. Originally it was set like this:

![image](https://user-images.githubusercontent.com/35233719/35158705-9170fd8a-fcfd-11e7-9ccd-61a242a8541b.png)

There's a bug in that interface, if you try and change the url of an already created entry, it fails saying missing cert (even if you paste in your information).

Fine, I went and deleted it and added a new one.

![image](https://user-images.githubusercontent.com/35233719/35158868-0aed8016-fcfe-11e7-89c1-a0c5016dfd4a.png)

Made sure it was in the right queue:

![image](https://user-images.githubusercontent.com/35233719/35158881-151e4d18-fcfe-11e7-94f3-f0e1ca28eb39.png)

I run the build again, and this time it's a different error (log 22): 

2018-01-19T15:16:29.5767239Z ##[debug]Processed: ##vso[task.issue type=error;]Unhandled: Endpoint not present: a7bcd574-345b-4a67-aa69-955144e2607f
2018-01-19T15:16:29.5946687Z ##[debug]Processed: ##vso[task.complete result=Failed;]Unhandled: Endpoint not present: a7bcd574-345b-4a67-aa69-955144e2607f

So now I'm thoroughly confused. Ideas?

[logs_18.zip](https://github.com/Microsoft/vsts-tasks/files/1647102/logs_18.zip)
[logs_19.zip](https://github.com/Microsoft/vsts-tasks/files/1647103/logs_19.zip)
[logs_20.zip](https://github.com/Microsoft/vsts-tasks/files/1647104/logs_20.zip)
[logs_22.zip](https://github.com/Microsoft/vsts-tasks/files/1647105/logs_22.zip)

**Comment by jikuma** [comment]
You have deleted the old endpoint used in the task and created a new endpoint. You need to change docker host endpoint value in the task also.
![image](https://user-images.githubusercontent.com/23053847/35159536-92c9262c-fd60-11e7-9a17-40ccf0654ebb.png)

**Comment by pageflex** [comment]
Okay. Kinda fixed it. Set the host name in the service definition to the IP address and port. Build is successful, but when it tries the second task which is to push to the ACR, it errors out (log 24).

/usr/bin/docker -H https://52.176.45.116:2376 --tls --tlscacert='.dockercerts/ca.pem' --tlscert='.dockercerts/cert.pem' --tlskey='.dockercerts/key.pem' push pageflexacr.azurecr.io/raneto-linux:latest
invalid argument "https://52.176.45.116:2376" for "-H, --host" flag: Invalid bind address format: https://52.176.45.116:2376
rc:1
success:false
invalid argument "https://52.176.45.116:2376" for "-H, --host" flag: Invalid bind address format: https://52.176.45.116:2376
Processed: ##vso[task.issue type=error;]invalid argument "https://52.176.45.116:2376" for "-H, --host" flag: Invalid bind address format: https://52.176.45.116:2376
task result: Failed
/usr/bin/docker failed with return code: 1

[logs_24.zip](https://github.com/Microsoft/vsts-tasks/files/1647412/logs_24.zip)

**Comment by pageflex** [comment]
I think the last part is related to this issue: https://github.com/docker/docker-py/issues/894

**Comment by pageflex** [comment]
Any updates on this issue?

**Comment by jikuma** [comment]
Did you tried setting server url as  "tcp://52.176.45.116:2376".
If you using DOCKER HOST endpoint you dont need to specify  DOCKER_HOST variable.

**Comment by pageflex** [comment]
I'm not using DOCKER_HOST variable at all. the VSTS is defining everything. the Host is registered as a service with VSTS. I then define my build. The tasks use the host registration to extrapolate. The only half works with the host registered as I have registered it (the sub-task is using Docker-Compose). The ACR push is not working (because it is using Docker).

The Host definition in VSTS is attached above and all the logs that I have are attached in logs_24.zip

**Comment by jikuma** [comment]
Can you try setting server URL in Docker Host endpoint used in task as "tcp://52.176.45.116:2376" instead of https://52.176.45.116:2376. Let me know the outcome.

**Comment by pageflex** [comment]
yes. This finally works with tcp:// defined, but I don't feel it should be closed. A) None of the tutorials state that you must use tcp and show https. Docker-Compose works with https but docker commands do not. Since the definition is with VSTS and you can mix and match sub-tasks, I feel that it would be a better user experience if the scripts should deal with the transformation of the service end point to what the sub-task expects.
