### ISSUE TITLE
ARM Deploy: Cannot read property 'artifacts' of undefined

### ISSUE THREAD

**Issue by Tadimsky** [Microsoft/vsts-tasks#6255]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS 
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
https://intentional.visualstudio.com/intent/Apps/_apps/hub/ms.vss-releaseManagement-web.cd-workflow-hub?definitionId=7&_a=definition-tasks&environmentId=11

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted VS 2017 

## Issue Description

I'm using `Azure Resource Group Deployment` v2.* and am trying to edit the `Override template parameters` in the new grid view.
When I open that view I see the following error:
![image](https://user-images.githubusercontent.com/1149244/35124834-5f6164b6-fc5c-11e7-9a60-ad84eda4ffda.png)

Looks similar to #5372 but nothing happened there.

### Error logs
Can't tell how to capture Debug Logs based on the link provided at the top.

**Comment by Tadimsky** [comment]
@sachinma any ideas on this?

**Comment by sachinma** [comment]
I think the reason for this is that you have use ** in the path. For us to be able to download the file and show the parameter name in the grid, we require the full path of the files. You can use ... button near the template file input to select the exact file path. That should resolve this.

Adding @hililh to work on improving the message here

**Comment by sachinma** [comment]
Adding @ds-ms as well

**Comment by Tadimsky** [comment]
Ah, ok I'll try it with the absolute path. Surely we can change the Task to use `Resolve-Path` or something like that in order to find the file? I'd rather not specify it absolutely as the drop name, build name, etc can change.

**Comment by sachinma** [comment]
@ds-ms can you fix the error message in this case.

**Comment by ds-ms** [comment]
Fix has been merged. Should reach all rings in 1-2 weeks.
