### ISSUE TITLE
Local IIS

### ISSUE THREAD

**Issue by louislewis2** [Microsoft/vsts-tasks#6259]
## Environment

- Server - VSTS
- Agent - Hosted 
    
## Issue Description

I was tasked to change a build system from another online service, to now use VSTS.
The migration process so far was great, however I am now at the part where I need to deploy
an ASP.NET Core application to a local instance of IIS running on the build server, I used to 
simply publish the project and then xcopy it to the IIS directory, after that I then run integration tests.

Is IIS available?
If yes, how do I find the path to it?
if no, can it be installed using powershell?

**Comment by ArieHein** [comment]
For IIS you need to install it physically on the build server.
Theres IISExpress that can also be used
Most IIS servers, if they weren't changed, will have a interpub\wwwroot folder in one of the drives (c: by default)
you can indeed install IIS using PowerShell, simple search in your favorite search engine will assist you with those details.

**Comment by pavanadepu2** [comment]
Yes IIS is available on Hosted Agent. The default path of IIS is  $env:SystemDrive\inetpub\wwwroot.

**Comment by chshrikh** [comment]
@louislewis2 please feel free to reopen, if you have not got unlocked
