### ISSUE TITLE
Kubernetes: No way to specify namespace for secret 

### ISSUE THREAD

**Issue by JonnyMattsson** [Microsoft/vsts-tasks#6262]
## Environment
VSTS

## Issue Description

Adding a secret name in the kubernetes task will create a secret in Default namespace. There is no way to add a namespace. 

Would it be possible to add an argument textbox just like it works for the kubernetes commands?

**Comment by bansalaseem** [comment]
Thanks for reporting it Jonny. Anumita has fixed it with this change. https://github.com/Microsoft/vsts-tasks/commit/2578ff7ea912d61484abe80934469bd378221203#diff-db1dda39c429340ad0813720f945bf31
