### ISSUE TITLE
Test execution in TFS 2017 agent is hanged when running the test cases  

### ISSUE THREAD

**Issue by r123aryan** [Microsoft/vsts-tasks#6265]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Error logs

[Insert error from the logs here]

**Comment by acesiddhu** [comment]
@r123aryan can you add more details here?as  asked in environment section?

**Comment by acesiddhu** [comment]
also enable system.debug = true and share logs for the same.

**Comment by acesiddhu** [comment]
Closing the issue. please re open the issue with details.
