### ISSUE TITLE
How to use gulp inside an extension

### ISSUE THREAD

**Issue by marceloavf** [Microsoft/vsts-tasks#6266]
## Environment
- VSTS
precisaosistemas/InovaFarmaAPI/InovaFarama API

- Agent Private: 
**Windows Server 2016 Standard**
**Agent version** 2.124.0

## Issue Description

How can I use gulp inside and Javascript extension without need to carry it with the extension, it will save some and installation time.

Link to the extension: https://github.com/marceloavf/github-tools-vsts

**Comment by ericsciple** [comment]
You can use [tl.which](https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/vsts-task-lib.md#taskwhich) to find it in the PATH or use the [vsts-task-tool-lib](https://github.com/Microsoft/vsts-task-tool-lib) to download and cache it on the fly. As a reference example, I believe the nuget task in this repo will download specific version of nuget and cache it using the tool lib. Also the node tool task in this repo. The task lib repo is a better place for task author questions.

**Comment by ericsciple** [comment]
Note that if you go the tool-task-lib route, the solution will not work for internet-disconnected scenarios.
