### ISSUE TITLE
How to get Endpoint API Token from GitHub Services

### ISSUE THREAD

**Issue by marceloavf** [Microsoft/vsts-tasks#6271]
## Environment
- VSTS
precisaosistemas/InovaFarmaAPI/InovaFarama API

- Agent Private: 
**Windows Server 2016 Standard**
**Agent version** 2.124.0

## Issue Description

How can I get the token from GitHub Endpoint connection inside javascript ?

That's the code I'm already using: 

```js
const tl = require('vsts-task-lib/task');

// Endpoint
const githubEndpoint = tl.getInput('githubEndpoint');
const githubEndpointToken = tl.getEndpointAuthorization(githubEndpoint);
```

But it returns 401 error

Link to the extension: https://github.com/marceloavf/github-tools-vsts

**Comment by madhurig** [comment]
Can you try
const githubEndpointToken = tl.getEndpointAuthorizationParameter(githubEndpoint, 'AccessToken');

Thanks,
Madhuri
