### ISSUE TITLE
Cannot publish results to TFS

### ISSUE THREAD

**Issue by Tigerforce328** [Microsoft/vsts-tasks#6276]
## Environment
- TFS on-premises, version: 15.117.26714.0  
- Private agent: Windows_NT. Agent version: 2.117.2

## Issue Description
Task name: Run Functional Tests
Task was run about 6 hours. It has results on Agent machine. But, test status on TFS is "Aborted" without any information such as executed machine, run duration... It seems that the results status do not return to TFS

### Error logs
[lgvn15095-vm1_DTAExecutionHost.exe.log](https://github.com/Microsoft/vsts-tasks/files/1658878/lgvn15095-vm1_DTAExecutionHost.exe.log)

[Insert error from the logs here]

**Comment by Tigerforce328** [comment]
Hi,
Any update on this issue? It still happens. I'd like to add more information:
The issue only happens with the "big" test suites. If we run a few tests, it works fine. If we run the full test suites (122 tests. Duration is about 6 hours. The result size is about 200 Mb). The results CANNOT publish to TFS. All test status on TFS are ABORTED although the local results are exist.
We attach the log file today also.

We are looking for your support,

Thanks,
[lgvn15095-vm1_DTAExecutionHost.exe (2).log](https://github.com/Microsoft/vsts-tasks/files/1666479/lgvn15095-vm1_DTAExecutionHost.exe.2.log)

**Comment by abhishkk** [comment]
@Tigerforce328 
RFT task has internal timeout of 6 hours. You can override this timeout by adding timeout in testsettings.

Please add following in testsettings:
`<?xml version="1.0" encoding="utf-8"?>  
<TestSettings name="TestSettings1" id="2ac68d7c-6e7e-4862-a377-e32c0d3f698d" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <Execution>
    <Timeouts runTimeout="200000000" />
  </Execution>
</TestSettings>`

Here timeout value is in milliseconds.

**Comment by abhishkk** [comment]
Closing this issue. Let us know if issue is unresolved.

**Comment by Tigerforce328** [comment]
Thanks abhishkk for this information.
However, in this context, I use the "runsettings" file. Can I put the "timeout" setting in this file also.
I attach my "runsettings" file for your reference.

Thanks,
[RunSetting1.zip](https://github.com/Microsoft/vsts-tasks/files/1676255/RunSetting1.zip)

**Comment by abhishkk** [comment]
@Tigerforce328 Sorry but you can add timeout from testsettings only.

**Comment by Tigerforce328** [comment]
So, is there any solution for my case? I need to run some tests on vNext (by RFT task) that take more than 6 hours to finish.
I think other users might meet this case also.
Do you have any idea?

Thanks

**Comment by abhishkk** [comment]
Sorry but for long running tests taking more than 6 hours, overriding timeout via testsettings is the only option currently.
