### ISSUE TITLE
Deployment target provisioning

### ISSUE THREAD

**Issue by sujitks** [Microsoft/vsts-tasks#6281]
## Environment
- VSTS

- Agent - Hosted or Private: 
    
    Private

## Issue Description
We have requirement to provision deploy target and remove as per the demand
We want to provision new deployment targets and delete them when not needed. I have searched lots of the documentation but could not see any way to remove a target from the deployment group. This is causing issue when we try to recreate deployment targets with same name.

**Comment by ArieHein** [comment]
@sujitks Try this:
https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-windows#replace-an-agent

**Comment by KrishnaAdityaB** [comment]
@sujitks I am assuming the solution by @ArieHein worked for you.
If for some reason (like the machines from which deployment targets were configured, are no more available) you want a REST API to delete the targets -

```
DELETE
https://{account}.visualstudio.com/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/targets/{targetId}
```
I am closing this. Please open if you need further help.
