### ISSUE TITLE
Azure Resource Group Deployment - How to pass subscription as a variable

### ISSUE THREAD

**Issue by Teodelas** [Microsoft/vsts-tasks#6284]
In a Resource Group Deployment task, I need to be able to pass the subscription / service connection information as a VSTS Build variable.  When I tried to pass the subscription ID, I got the error: 
##[error]Required: 'fed7f475-6055-4e3c-8529-c1345df70589' service endpoint URL

What format should the service endpoint be in?  

If you need additional info, I'm a MSFT FTE and my alias is teodelas.

**Comment by sachinma** [comment]
Subscription information is only read from service connection and service connection object cannot be passed as build variable. Can you explain why do you need to pass the service connection as build variable to help me understand your scenario better?

**Comment by Teodelas** [comment]
I need a way to have a single release definition (ARM template) that can be deployed to multiple subscriptions.

**Comment by sachinma** [comment]
Currently service endpoints are not supported as a build/release variable. Adding @GitHubSriramB for comments on whether that can be done or taken as a feature ask

**Comment by cschertz** [comment]
Just want to second this request.   In our case the issue is trying to avoid maintaining different build definitions for different azure environments  China and Germany where separate AAD and Sub is required.

**Comment by jpwarner-gh** [comment]
Yes, having this option would help with significantly reducing the number of definitions we need to create/maintain. Our definitions are comprised mostly of Azure PowerShell tasks for deploying ARM templates as well as Service Fabric apps to various test clusters in different subscriptions.

**Comment by GitHubSriramB** [comment]
@Teodelas - we currently support updating endpoint details within a task using the following command:
##vso[task.setendpoint]value 

Detailed command documentation can be found here:
https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md

With this command, you could author a custom task that takes an endpoint that exists & update fields of the endpoint specific to the deployment & subsequent in the deployment can use the updated endpoint.

Would this work for you?

**Comment by Teodelas** [comment]
This may work.  Could you provide any more information on the values I would need to provide?  The examples in the documentation seem to show that I need to pass additional information:
##vso[task.setendpoint id=000-0000-0000;field=authParameter;key=AccessToken]testvalue
##vso[task.setendpoint id=000-0000-0000;field=dataParameter;key=userVariable]testvalue

The Azure Resource Manager endpoint takes:
Connection name, Subscription ID, Subscription Name, Service Principal Client ID, Service Principal Key, and Tenant ID. But those are just the displaynames.

Teo

**Comment by GitHubSriramB** [comment]
You can get the keys for the AzureRm endpoint inputs by querying the endpoint type:
https://{accountName}.visualstudio.com/_apis/serviceendpoint/types?type=AzureRm

The API is documented here:
https://docs.microsoft.com/en-us/rest/api/vsts/serviceendpoint/types/list

subscriptionId & subscriptionName are the keys in AzureRm endpoint's data dictionary.,
servicePrincipalId, servicePrincipalKey, tenantId are the keys in AzureRm endpoint's authorization parameters.

You can try updating the values for these fields using the command (you would need to invoke 1 command to update 1 field).

**Comment by cschertzmsft** [comment]
Not quite sure why service endpoints not being supported as a variable is in issue.   
Ultimately   Get-VstsEndpoint is called with the string name of the service endpoint to get the endpoint back.    

Seems like it would be relatively easy to enable an advanced mode in this task that allows the name of the service endpoint to be passed directly. 

Personally i would make this update myself but the VSTS instance to which i have access does not allow for the install of tasks.    So no way to test or use even if i made the update.

**Comment by GitHubSriramB** [comment]
@cschertzmsft -

Get-VstsEndpoint takes endpoint Id as a parameter (although the parameter name is -Name, the value to be passed is endpoint id). Typically tasks will pass value of the inputs corresponding to service endpoint as the value for the -Name parameter.

Allowing task input corresponding to a service endpoint to take a variable implies we support endpoint as a first class variable type. Currently we only support variable values to be only strings. 

You should be able to install custom tasks on to your VSTS account using tfx-cli:
https://www.npmjs.com/package/tfx-cli

**Comment by sebbrochet** [comment]
@Teodelas , @cschertz  very surprised by your use case where you require subscription info during build phase, especially to deploy an ARM template that will use the **current** subscription at deployment time. In devops practices, you build only one time a generic artefact that can be configured for a specific environment/subscription at deployment time.
In my current project we've many environments, each one using a dedicated subscription and we're also targeting Mooncake without the need to use a subscription at build time (speaking of Mooncake, you can now use the same ARM template to deploy in both stock Azure and Mooncake).

**Comment by cschertzmsft** [comment]
The issue is for supporting CI not CD or devops.     Specifically handling deployment for testing scenarios during CI and not having to maintain multiple build defs for separate subs.
