### ISSUE TITLE
AzureResourceGroupDeployment not using the TFS Build Agent environment variables for the proxy

### ISSUE THREAD

**Issue by mwildenb** [Microsoft/vsts-tasks#6286]
We are using the "AzureResourceGroupDeployment" task for azure deployments. The task is used on a build agent behind a corporate firewall. The agent does not use the environment variables set for the internet proxy (HTTP_PROXY, HTTPS_PROXY, NO_PROXY). Is there any way to force the Tasks to use the Proxy for the Azure endpoints? 
 
ENVIRONMENT
- TFS2017 - Update 2
Agent:
- Windows Server 2012 R2, Build Agent TFS2017 (Agent Version 2.123)

LOG:
2018-01-18T12:11:23.6450614Z ##[debug]project=null
2018-01-18T12:11:23.6606920Z Checking if the following resource group exists: EmptyGroup.
2018-01-18T12:11:23.6919617Z ##[debug]Requesting for Auth Token: https://login.windows.net/********/oauth2/token/
2018-01-18T12:11:24.0044784Z ##[debug]{"code":"ECONNRESET"}
2018-01-18T12:11:24.0044784Z ##[debug]task result: Failed
2018-01-18T12:11:24.0200704Z ##[error]Failed to check the resource group status. Error: tunneling socket could not be established, cause=write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:794:

**Comment by mwildenb** [comment]
Thanks for reviewing. Are you aware of any work around for this issue?

**Comment by mwildenb** [comment]
Okay, after some troubleshooting I found that the .PROXY is not configured correctly. It will take some additional testing if this will resolve the issue. 

The following post helped for configuring the agents:
https://github.com/Microsoft/vsts-agent/blob/61b82a80f224e444932e1a830ca49276872f3c54/docs/start/proxyconfig.md

**Comment by chshrikh** [comment]
@mwildenb are you got unblocked with this ?

**Comment by mwildenb** [comment]
Still stuck in limbo. 

reconfiguring the agents was not the solution. We have another scenario which is working correctly:
- VsTs Build ==>  On-Prem build agent (behind the proxy) -- works like a charm
- TFT build  ==> On-Prem build agent (also behind the proxy) -- does bypass the proxy

I have tested the TFS configuration with 
•TFS2017 - Update 2
•TFS2018 

Seems like the VsTs AzureResourceGroupDeployment task via VsTs is a newer version as the TFS version

Question:
- Can I manually upgrade the VsTs Tasks for TFS?
- is there any other option working around the proxy?

**Comment by mwildenb** [comment]
Okay, after chatting with dev-ers I found the solution. An old version of the VsTs task (2.2.8) was causing the problems. After some testing with the correct .proxy configuration:
https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/proxy?tabs=windows#tabpanel_7ufbwiC3ad_windows
