### ISSUE TITLE
vsts-npm-auth EPERM: operation not permitted erro

### ISSUE THREAD

**Issue by Storm9562** [Microsoft/vsts-tasks#6292]
## Issue Description
I am trying to upload a npm package to VSTS. However everytime I run "npm publish" I get an error. I'm really not sure if the issue lies with the vsts-npm-auth or if i'm doing something wrong. So I apologise in advance.

I will take you through the steps...(I initially follow the steps in the pic)

![capture123](https://user-images.githubusercontent.com/31470504/35445902-10de2e46-02ab-11e8-9f13-27da4dfa66b0.PNG)

1. I add the feed to my .npmrc ( C:\Users\myuserName\.npmrc )
2. I run the command and install vsts-npm-auth. This installs fine.
3. I run the command `vsts-npm-auth -config C:\Users\myuserName\.npmrc` which returns "already have credentials for etc....(It says that because I ran the command previously and it worked.)
4. I run `npm init` and follow through the steps to create a package.json
5. Now I want to upload that package to VSTS so I run `npm publish` and get the following error

![image](https://user-images.githubusercontent.com/31470504/35446315-37777656-02ac-11e8-8439-d368040c14c8.png)

I've tried downgrading/upgrading the version of npm I am using but that did not help. 

I have attached the package.json in the zip file -->
[files.zip](https://github.com/Microsoft/vsts-tasks/files/1668177/files.zip)
 
I am able to upload the package if I add the credentials manually to the .npmrc file but this is not something i want to be doing. I would like to use the vsts-npm-auth. Eventually we want alot of users to use it at my company aswell.

![capture12345](https://user-images.githubusercontent.com/31470504/35446600-26115e3a-02ad-11e8-9eae-fae36b58f223.PNG)

Thank you

## Environment
VSTS

### Supporting Information
- node -v = 8.6.0
- npm -v = 5.3
- I am using a corporate proxy

- My .npmrc contains the following (located at C:\Users\myuserName\.npmrc)
`strict-ssl=false
proxy=http://DOMAIN%5CUSERNAME:PASSWORD@PROXYIP:PORT/
registry=https://MYVSTS.pkgs.visualstudio.com/_packaging/MYVSTSTestFeed/npm/registry/
always-auth=true`

**Comment by keithrob** [comment]
@Storm9562,
The problem here is almost certainly your corporate proxy.  To verify this, I would recommend you try this from a system that is not behind the corporate proxy.

**Comment by Storm9562** [comment]
i think so. Closed.
