### ISSUE TITLE
Test Results show all tests passing when using an ordered test when tests are actually failing

### ISSUE THREAD

**Issue by johnwhoffman** [Microsoft/vsts-tasks#6293]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

 TFS on-premises-2017
Private Agent- Server2012R2
Version 2.122.1

We use the run functional test task to execute an ordered test.
The run summary and test results show 1/1 tests passing but the trx file shows a failed test .

We are migrating from labdefaulttemplate11.xaml to a release definition. 
The xaml builds would correctly report a failed test

<Counters total="18" executed="9" passed="8" failed="1" error="0" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" completed="0" inProgress="0" pending="0" />

[tfsservice_G1TTEST1 2018-01-26 08_17_00.txt](https://github.com/Microsoft/vsts-tasks/files/1668830/tfsservice_G1TTEST1.2018-01-26.08_17_00.txt)

**Comment by acesiddhu** [comment]
@johnwhoffman Ordered test in Run functional test task is not supported out of the box. Check for workarounds https://blogs.msdn.microsoft.com/allendm/2016/08/09/executing-ordered-tests-on-remote-machines-using-run-functional-tests-task/

**Comment by acesiddhu** [comment]
hope the above blog helps. Closing the issue
