### ISSUE TITLE
Visual Studio test task fails to rerun failed tests when data driven testing is implemented for test automation

### ISSUE THREAD

**Issue by Manvibha** [Microsoft/vsts-tasks#6294]
Hi, 

Issue: 
I have configured Release definitions to run GUI test automation using Visual Studio Test task and have set "Rerun failed tests" to true i,e checkbox is checked. 
I am executing GUI test automation scripts and have designed for data driven testing which executed same test method for multiple iterations. 

Behavior: 
Once test method is executed which is having 5 iterations. Lets assume that 3 iterations are passed and 2 iterations fails. Visual Studio test task fails to execute those 2 iterations again since it is not able to find those test methods in the dll provided. 
Ex: test method name "Test_Login" with 5 iterations of data 

when looked at Logs below is the log messages 

---------------------------------------------------------------------------------------------------------------
2018-01-26T18:02:08.7983542Z **************** Rerunning failed tests for Test run 132242 *********************
2018-01-26T18:02:08.7983542Z Max attempts: 1; Current attempt: 1; Failed test cases threshold: 60; 
2018-01-26T18:02:08.7983542Z [command]C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe @c:\Agent\_work\_temp\tmpCA08.tmp
2018-01-26T18:02:08.9858760Z Microsoft (R) Test Execution Command Line Tool Version 14.0.25463.0
2018-01-26T18:02:08.9858760Z Copyright (c) Microsoft Corporation.  All rights reserved.
2018-01-26T18:02:08.9858760Z vstest.console.exe /TestCaseFilter:"FullyQualifiedName=Automation.Test_Login (Data Row 3)|FullyQualifiedName=Automation.Test_Login (Data Row 4)
2018-01-26T18:02:09.1733274Z Starting test execution, please wait...
2018-01-26T18:02:11.0950769Z ##[error]Error: Incorrect format for TestCaseFilter Error: Invalid Condition 'Data Row 3'. Specify the correct format and try again. Note that the incorrect format can lead to no test getting executed.
2018-01-26T18:02:11.1731966Z Warning: No test is available in c:\Agent\_work\r1\a\SeleniumTestAutomation\Automation..dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
2018-01-26T18:02:11.2357175Z Information: Additionally, you can try specifying '/UseVsixExtensions' command if the test discoverer & executor is installed on the machine as vsix extensions and your installation supports vsix extensions. Example: vstest.console.exe myTests.dll /UseVsixExtensions:true
--------------------------------------------------------------------------------------------------------------

I see task is trying to find the test method name along with data row x and hence it is not able to find and fails to re-run the failed test method. 

I am sure, this is something that end user does not have control and seems to be a bug in Visual Studio Test task. 
Can you please let me know if there is workaround. 

Thanks,
Mahendra

**Comment by janpieterz** [comment]
Encountering this too, don't think it has to do with data driven testing, just switching a normal unit test project to retry on failure and getting this.

Pretty annoying, it succeeds because of this, resulting in succeeding builds that should have failed.

**Comment by ganesp** [comment]
@Manvibha , @janpieterz 
Rerun for data driven tests is not supported at present. 
It is on the backlog and fairly high on the priority list.
Also, this limitation is called out in the release notes here: [Identify flaky tests](https://docs.microsoft.com/en-us/vsts/release-notes/2017/dec-11-vsts#identify-flaky-tests)

**Comment by janpieterz** [comment]
@ganesp Do xunit tests with autofixture and automoq qualify as data driven unit tests?

**Comment by acesiddhu** [comment]
@janpieterz can you share a sample for that?

**Comment by janpieterz** [comment]
Sure, for example this post highlights one:
https://stackoverflow.com/questions/36607786/in-xunit-shouldly-automoq-autofixture-can-we-pass-in-a-type-using-inlineautomoq

I've never realised there'd be a considerable difference between normal tests and this.

**Comment by mayankbansal018** [comment]
@onovotny, can you please help us with [this](https://github.com/Microsoft/vsts-tasks/issues/6294#issuecomment-362178871)

**Comment by onovotny** [comment]
I'm not sure how the rerunning logic works, but long as pre-enumeration is enabled, each method in a theory should be individually runnable. You can do it from the test explorer window too; you don't have to run the whole group each time.

**Comment by mayankbansal018** [comment]
@onovotny re-running doesn't currently work for data driven tests. The question was specifically that whether _"xunit tests with autofixture and automoq qualify as data driven unit tests?"_

**Comment by onovotny** [comment]
@mayankbansal018 I have no idea how to answer that.

**Comment by mayankbansal018** [comment]
Thanks @onovotny , I'll investigate this then.

**Comment by acesiddhu** [comment]
@janpieterz in short all the testcases who name contains comma, => or special character are not supported in re run today (as these names are passed to vstest.console.exe as arguments) and because they have comma and special characters the argument parsing goes for a toss.

we have a backlog item to get this fixed.

**Comment by Manvibha** [comment]
Is this fixed or still in backlog ? I see this thread closed!

**Comment by acesiddhu** [comment]
@Manvibha we have this in backlog which we are tracking internally. we will keep this thread posted once we complete that

**Comment by acesiddhu** [comment]
Tagging @nigurr and @PBoraMSFT

**Comment by mathewkuruvila** [comment]
@acesiddhu @nigurr @PBoraMSFT 

Is the backlog item for this issue fixed ?? Any help will be appreciated

**Comment by woudevdj** [comment]
Any news on the status of this issue? 

Most of our tests are data-driven (abstract scenario's in specflow using Nunit as unit-test framework) so rerun failed tests doesn't work most of the time, but is badly needed!

Abstract specflow scenario's have the following fully qualified name (indeed containing special characters): 

`/TestCaseFilter:"FullyQualifiedName=<Namespace>.Features.<FeatureName>.<ScenarioName>_(\"Arg1\"\,\"Arg2\"\,\"\"\,\"Arg3\"\,null)"`

Is this something that will be fixed by the backlog item too??

**Comment by nigurr** [comment]
Hi,

Mitigation step: https://github.com/Microsoft/vsts-tasks/issues/7545#issuecomment-403024781
We still don't have tentative timelines, however it can work (mitigation) with the mentioned solution without an issue.

**Comment by mathewkuruvila** [comment]
@nigurr The solution will retry the failed test cases. But retry for data provider based test cases is not working fine properly. It will mark a test case as passed, even if it has some failures. And it won't retry again.

**Comment by nigurr** [comment]
@mathewkuruvila can you please file new bug and share the sample, we will look into this.

**Comment by swasser** [comment]
> @Manvibha we have this in backlog which we are tracking internally. we will keep this thread posted once we complete that

@acesiddhu Any updates on when the internally tracked issue will be resolved?
We use the workaround with batching, but this creates a strange side-effect, when we log messages to output during test execution.
We use NUnit, and the following code logs a warning (instead of an info) during test execution:
`TestContext.Progress.WriteLine("Info message goes here");`
Without batching, the message is logged as info (as expected).

**Comment by acesiddhu** [comment]
@nigurr ?

**Comment by vlad-zuga** [comment]
Any updates on this?

**Comment by Manvibha** [comment]
Is there any update on this?
