### ISSUE TITLE
Run tests in parallel with vsts-task and Selenium Grid

### ISSUE THREAD

**Issue by azarj** [Microsoft/vsts-tasks#6306]
Hello,

I'm using TFS on-premises.
I have an agent installed on a machine with 2 processors.
I use a build definition to run selenium webdriver tests in parallel over a Selenium Grid setup. The step to run the tests is Visual Studio Test version 1.

The problem is that no matter the number of nodes on Selenium Grid, only 2 tests will run at a time (the tests are sent, randomly,  to all the nodes, but maximum 2 at a time).

Is there a setting that i'm missing or is there a limitation of the vsts-task to send only 2 dll's (equal with the number of processors of the host agent machine) to the selenium grid?

**Comment by cltshivash** [comment]
@azarj Currently there's a limitation on the parallelism possible with vstest runner. It is limited to the number of processors.

**Comment by DiMaReCas** [comment]
I'm new working with the tfs, I'm trying to run tests from tfs in selenium grid, but I don't know if this is possible.
