### ISSUE TITLE
hostedMac Preview failed Error: Failed which: Not found mono: null

### ISSUE THREAD

**Issue by bradyguy** [Microsoft/vsts-tasks#6328]
Error getting iOS Xamarin project to build.  Mono not found.
## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
 thrivehealthcarellc.visualstudio.com 
orangeburst
ios_dev_daily_ipa
 #1.1.0.2803 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:
 Hosted macOS Preview
    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

![image](https://user-images.githubusercontent.com/10744104/35646641-672565ec-0695-11e8-9813-c9e9d41acd80.png)

### Error logs
[logs_2803.zip](https://github.com/Microsoft/vsts-tasks/files/1683257/logs_2803.zip)

2018-01-31T20:29:45.9161830Z ==============================================================================
2018-01-31T20:29:47.2439070Z Detected NuGet version 3.5.0.1938 / 3.5.0
2018-01-31T20:29:47.2522270Z SYSTEMVSSCONNECTION exists true
2018-01-31T20:29:47.2664920Z ##[error]Error: Failed which: Not found mono: null
2018-01-31T20:29:47.2704440Z ##[error]Packages failed to install

**Comment by AlexRukhlin** [comment]
Hi @bradyguy ,

Thanks for reporting the issue. To investigate it, we need more information.
Could you please run the build with the `system.debug` build variable set to `true` and provide us with the failed build logs?

Thanks,
Alex

**Comment by AlexRukhlin** [comment]
Also, we'd like to know:

1. Which (if any) build definition template have you used creating your definition?
2. Which (enabled) tasks are used by your definition - in order?

Thanks,
Alex

**Comment by madhurig** [comment]
@bradyguy : 
Can you please try selecting the version of Mono you want to use as referenced [here](https://docs.microsoft.com/en-us/vsts/build-release/concepts/agents/hosted#q--a) and see if it helps?

**Comment by bradyguy** [comment]
@AlexRukhlin  I took over this build from another team working on the build.  There are a number of task in the build definition see screen shot.  system.debug set to true and logs attached.

I started a new build definition, used the xamarin template and it appears to build correctly when I check the use iOS Simulator box.  Could be that as I get this new definition working using the template I may be able to get a working version in place.  

Thanks for your help.
@madhurig the failure is happening on the nuget task.  Does this mono selection script go before the nuget task?

Thanks for your help

![image](https://user-images.githubusercontent.com/10744104/35746384-3971af5c-080c-11e8-9201-2d6f2fb76060.png)

[logs_2813.zip](https://github.com/Microsoft/vsts-tasks/files/1690219/logs_2813.zip)

![image](https://user-images.githubusercontent.com/10744104/35746325-0a76fa7c-080c-11e8-9394-220608ba8924.png)

**Comment by bradyguy** [comment]
@AlexRukhlin using the Xamarin build template I get the following error when I deselect the build with iOS simulator checkbox. 

Xamarin.iOS task failed with error Error: /Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild failed with return code: 1. For guidance on setting up the build definition, see https://go.microsoft.com/fwlink/?LinkId=760847.

I am looking at this article and suspect it's related to the configuration file that needs to be updated.

**Comment by madhurig** [comment]
@bradyguy: It looks like you are using NuGet 3.5 which is the tool having trouble finding mono. Can you try updating to a newer version of NuGet and see if it helps? There is a task that allows you to download a newer version of NuGet during your build: https://docs.microsoft.com/en-us/vsts/build-release/tasks/tool/nuget 

Thanks,
Madhuri

**Comment by bradyguy** [comment]
I finally got this working.  I switched over to use the new Xamarin build template.  It take a day or two to get all the properties, variables, etc. figured out but in the end using the new build template worked just fine.  Thanks for everyone's help.
