### ISSUE TITLE
Boolean parameter not being loaded from parameters file during deployment

### ISSUE THREAD

**Issue by philshur** [Microsoft/vsts-tasks#6339]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
1id, Starling, AccountSupervisor/20180126.7

- Agent - Hosted or Private: 
    
    -  Hosted agent, queue name: Account Supervisor-26.01.2018-2 / Prod-staging ID: 27667

## Issue Description

VSTS is failing to pass a boolean parameter set in the parameters file.

### Error logs

2018-02-01T09:49:19.5729653Z There were errors in your deployment. Error code: InvalidTemplate.
2018-02-01T09:49:19.5734728Z ##[error]Deployment template validation failed: 'The value for the template parameter 'ignoreSslErrors' at line '1' and column '5221' is not provided. Please see https://aka.ms/arm-deploy/#parameter-file for usage details.'.
2018-02-01T09:49:19.5739072Z ##[error]Task failed while creating or updating the template deployment.
[tasklog_12.log](https://github.com/Microsoft/vsts-tasks/files/1685518/tasklog_12.log)

**Comment by boevink** [comment]
We also have this issue. Templates and parameter files are not changed and worked with version 2.2.17 of this task.
This week the task was upgraded to version 2.129.3 and we are not able to deploy these templates anymore.

**Comment by boevink** [comment]
Issue only occurs if the bool parameter has a value of false.
In case of a value of true, the task runs successfully.

This is caused by sanitizeParameters:
`if (!!parameters[key].value) {`
[ResourceGroup.ts line 382](https://github.com/Microsoft/vsts-tasks/blob/fdc3d7ddbd2a598df2939fa7de8fdb65c040ee5b/Tasks/AzureResourceGroupDeployment/operations/ResourceGroup.ts#L382)

In case of a param value of false, this if-statement always evaluates to false.

**Comment by ds-ms** [comment]
@boevink thanks for identifying the problem correctly, I've raised a PR to fix it. The fix should be rolled out by tomorrow.

**Comment by ds-ms** [comment]
https://github.com/Microsoft/vsts-tasks/pull/6349

**Comment by ds-ms** [comment]
This has been rolled out.
