### ISSUE TITLE
Cannot override default Docker memory limit

### ISSUE THREAD

**Issue by heaths** [Microsoft/vsts-tasks#6342]
## Issue Description

For some workloads, the default memory limit for Docker `build` and `run` tasks of 1GB is not enough. It would be nice to override this in those tasks (perhaps "hidden away" under the **Advanced** section). Error handling could be delegated to Docker itself that will fail if not enough memory is available below the set limit.

**Comment by jikuma** [comment]
You can always use 'Run Docker command' in such cases and specify your command. Docker task UI is already complex and we don't want to unnecessarily make it more complex for the user. Adding @azooinmyluggage to check the feasibility.

**Comment by heaths** [comment]
Which is why I put it in the advanced section. You already expose just about everything else available for the build command. I am using the "run command" in the meantime, but why have any higher level tasks like "build" or "run"? They provide abstraction and some validation and make it easier to use especially for people that don't know Docker well. This seems like a good fit and will make it easier for our internal ops to maintain.
