### ISSUE TITLE
vsts customized variable max char size?

### ISSUE THREAD

**Issue by GuofuZhong** [Microsoft/vsts-tasks#6358]
I want to pass 2-5KB string to a customized variable.

**Comment by bryanmacfarlane** [comment]
Did you try it and have an issue?

**Comment by GuofuZhong** [comment]
@bryanmacfarlane  trying now. but I cannot find this info on the document

**Comment by bryanmacfarlane** [comment]
There is no known limitation on a single input / variable.  There is however a .net limitation of 65K on the total environment block.  But that only is a limitation for tasks written with the powershell handler.  

https://github.com/Microsoft/vsts-task-lib/issues/228

If you write your tasks in typescript (preferred, cross plat etc...) there is no known limitation.

Reactivate if you find some limitation that we're not aware of.

**Comment by GuofuZhong** [comment]
@bryanmacfarlane Thanks!
