### ISSUE TITLE
Document agent versions delivered with OnPrem TFS

### ISSUE THREAD

**Issue by pascalberger** [Microsoft/vsts-tasks#636]
It would be helpful to have somewhere documented which agent version was delivered with which OnPrem TFS version.

**Comment by bryanmacfarlane** [comment]
Agreed!

**Comment by pascalberger** [comment]
I also have created a PR (#635) which would also help with this as it begins documenting which logging commands are available from which agent version (and therefore which OnPrem TFS version) on.

**Comment by bryanmacfarlane** [comment]
OK - I accepted it.  I'm about to redo that but that's a good add.  I don't like the formatting/layout of it ...

**Comment by pascalberger** [comment]
Thanks!

Feel free to redo :smile: Formatting is generally not ideal on this page for viewing in GitHub since the table need horizontal scrolling. A list based view or something similar might be more readable.

**Comment by pascalberger** [comment]
@bryanmacfarlane But #653 does not fix this issue. This issue is about which agent version was delivered with which TFS On-Prem version (the PR was for documenting which logging command was available in which agent version). Therefore this shouldn't be closed yet.

**Comment by bryanmacfarlane** [comment]
Good point.  I wish the .net agent was open sourced - that's where I would document.  In absense of that, we will document here under the premise of minimumAgentVersion.

I also want the doc to talk about the agent update process and which branch to get patches for tasks.

**Comment by pascalberger** [comment]
+1 for open sourcing the .net agent :wink:

**Comment by bryanmacfarlane** [comment]
Next month we start on a single core CLR agent :)  It will be open sourced

**Comment by PreetSangha** [comment]
Thanks @bryanmacfarlane. I look forward to that. In the mean time may I ask if I can take the VSO version and install it on an on premises server or agent. If so is there anywhere this is documented.

**Comment by chrisrpatterson** [comment]
No, the on-premises server will be updated with Update 1 and the normal on-premises update cycle.

**Comment by bryanmacfarlane** [comment]
Catching up on this old issue.

The agent is now open sourced and no longer delivered with an on-prem server.  It is the 2.x agent. 
 You can download from:

https://github.com/Microsoft/vsts-agent

Starting with TFS 2017 and forward the download button points to a specific version, but you are free to go grab latest from github releases.

[TFS2017 pointed to 2.105.7](https://github.com/Microsoft/vsts-agent/blob/releases/dev15rtm/src/Microsoft.VisualStudio.Services.Agent/Constants.cs#L41)

[TFS2017 QU1 pointed to 2.112.0](https://github.com/Microsoft/vsts-agent/blob/releases/dev15u1rtm/src/Microsoft.VisualStudio.Services.Agent/Constants.cs#L42)

[TFS2017 QU2 points to 2.117.1](https://github.com/Microsoft/vsts-agent/blob/releases/dev15u2rc2/src/Microsoft.VisualStudio.Services.Agent/Constants.cs#L41)

So if you go to that contants.cs file, you can switch release branches and see what version if needed.  But as I said above, you can grab latest from github.  We maintain API compat.
