### ISSUE TITLE
Step with "Always Run" does not run if previous step fails

### ISSUE THREAD

**Issue by GuofuZhong** [Microsoft/vsts-tasks#6361]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
https://msasg.visualstudio.com/Bing_Ads/AdsUCM/_release?definitionId=740&_a=release-summary&releaseId=44561&source=ReleaseExplorer 

- Agent - Hosted or Private: 
    

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
 WIN 2016 
  2.124.0

## Issue Description

We have one task group, it could always run when build fail.
https://msasg.visualstudio.com/Bing_Ads/AdsUCM/_taskgroups?_a=properties&taskGroupId=2ba41946-8425-454f-865a-dd5366fa4acb

When I include it in release.
https://msasg.visualstudio.com/Bing_Ads/AdsUCM/_apps/hub/ms.vss-releaseManagement-web.hub-explorer?releaseId=44549&definitionId=443&_a=release-logs
It is skipped, it is expected behavior?
Could you take a look if there is LSR happened?

Here is a simplified example:
https://msasg.visualstudio.com/Bing_Ads/AdsUCM/_release?definitionId=740&_a=release-summary&releaseId=44561&source=ReleaseExplorer
with always run option.
Trigger ICM is skipped.
### Error logs
skipped task

**Comment by GuofuZhong** [comment]
I have found that re-create this task group. It will work. (but in task group, always run isn’t selected.)
This is latest VSO break the backward compatible.

Thanks,
Guofu

**Comment by bansalaseem** [comment]
Here Vikranth had worked with GuifuZhong, explained that if a task group task contains a condition property, then that take precedence over "always run" and also explained that in the new task group UI, you can change the task conditions. It worked with that guidance, so I am closing this issue.
