### ISSUE TITLE
Test cases not executed in the order specified in the Test Suite

### ISSUE THREAD

**Issue by johnwhoffman** [Microsoft/vsts-tasks#6381]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server -  TFS 2017 on-premises
- Agent -  Private: SERVER2012R2
## Issue Description

We are replacing xaml BDTs with ordered tests  with a Run Functional Test Task in a release build.

The test plan contains one test suite with 13 test cases that need to run in the order specified in the test suite.

The resulting trx file shows the test cases being executed out of order.

How do we control the order of the test case execution?

**Comment by acesiddhu** [comment]
@johnwhoffman order of test case is not guaranteed when you use test plan test suite. to maintain order you need to use ordered tests instead.

**Comment by johnwhoffman** [comment]
ordered tests are not supported and the result reporting is not what you want.
We have a heavy investment in ordered integration tests that we need to find a way to support as we migrate away from.

**Comment by acesiddhu** [comment]
@johnwhoffman we officially never supported running automated tests in an order even in XAML BDT world (check https://blogs.msdn.microsoft.com/vstsqualitytools/2009/11/20/order-test-cases/ ). OrderedTest with limitations around reporting is the only way

**Comment by cltshivash** [comment]
@PBoraMSFT fyi. @johnwhoffman We are working to fix the results that we report for the ordered test so as to reflect the right details. To execute tests in a specific order, ordered test is the recommended option.

**Comment by johnwhoffman** [comment]
That would be fantastic. 
How will I know when the fix is available?
Will you update this post ?

Thanks for the update.
