### ISSUE TITLE
AzureFileCopy Set SAS Token timeout

### ISSUE THREAD

**Issue by nicholasqms** [Microsoft/vsts-tasks#6382]
## Environment
- Server - VSTS

- Agent - Hosted or Private: 
-Private - Windows, 

## Issue Description

AzureFileCopy does not provide the ability to set the token timeout for the SAS generated, when usign blob storage.

On file "AzureFileCopy.ps1", such parameter is set as: 
```
# Constants
$defaultSasTokenTimeOutInHours = 4
```
And later used on: 
```
$storageContainerSaSToken = New-AzureStorageContainerSASToken -Container $containerName -Context $storageContext -Permission r -ExpiryTime (Get-Date).AddHours($defaultSasTokenTimeOutInHours)
        Write-Host "##vso[task.setvariable variable=$outputStorageContainerSASToken;]$storageContainerSasToken"
``` 
So all blobs copied to the storage get the token access timeout set to 4 hours.

It would be useful if in the task parameter setting, we could set the desired timeout for the file SAS token, and then if nothing is set, use the default.

I could provide a fix for this issue, if found to be really helpful to the community.

**Comment by RoopeshNair** [comment]
We appreciate your offer to help. We are currently working on few features that warrants major version revision of the Azure File Copy task. (~2-3 months). 

We would be glad to accept your PRs on the newer revision. Looking forward to it.
