### ISSUE TITLE
Azure SQL Database Deployment task failure

### ISSUE THREAD

**Issue by GuofuZhong** [Microsoft/vsts-tasks#6383]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?

    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
Accoutn Name:msasg
Project Name:Bing_Ads
ReleaseDefinition:UCM - [A/B/C/T] - [Dev]
Release: Release-1541660-1

- Agent - Hosted or Private: 
  
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
 OS:win 2016
Agent Version:129.0

## Issue Description

Azure SQL Database Deployment task failure with error:
2018-02-08T10:40:08.6976900Z ##[error]System.Management.Automation.RuntimeException: Not able to fetch token for tenant Id ********.

### Error logs
https://msasg.visualstudio.com/Bing_Ads/AdsUCM/_release?releaseId=45534&_a=release-logs

**Comment by asranja** [comment]
The error shows up when you are trying to fetch the ARM access token using your SPN credentials. It is possible that there was a network timeout issue or the SPN credentials expired. Can you go to the ARM endpoint used in the task and click on Verify Connection to make sure the SPN is valid.

Please share the debug logs with us if you still face issue after validating SPN credentials. To get the debug logs, set the variable system.debug to true and redeploy. If you are not comfortable sharing the logs here, you can send it to the alias RM_Customer_Queries at microsoft dot com.

**Comment by chshrikh** [comment]
@GuofuZhong I am seeing you latest deployment with this release are passing, are you got unblocked on this

**Comment by GuofuZhong** [comment]
@chshrikh yes. I update our agent version from 129 to 129.1, it seem fixed this issue...
