### ISSUE TITLE
Please add a possiblity to run powershell task V2 remotely 

### ISSUE THREAD

**Issue by sqlenders** [Microsoft/vsts-tasks#6393]
## Troubleshooting
It would be nice if we could run powershells script remote like 
scriptname C:\scripts\myscript.ps1
servers : domain1\server1; domain2\server2
username : (somename from a variable)
password : (password from variable) 

Note C:\scripts points to the local drive of the server, not of the agent. 

## Environment
- Server - VSTS or TFS on-premises?
VSTS only
- Agent - Hosted or Private: 
Private agent 
Current agent version: '2.119.1'
Microsoft Windows Server 2012R2 6.3.9600

## Issue Description
See above

**Comment by brcrista** [comment]
Have a look at the "PowerShell on Target Machines" task.
https://docs.microsoft.com/en-us/vsts/build-release/tasks/deploy/powershell-on-target-machines
