### ISSUE TITLE
Custom task versioning

### ISSUE THREAD

**Issue by lukewis** [Microsoft/vsts-tasks#6397]
## Envrionment

Using vsts with a private agent (running macOS).

## Issue Description

I've read through other issues like #2131, but I still can't wrap my brain around how to test new versions of a task.  In particular, I have a task that is listed as private and I want to upload and test major, minor, and patch releases, but for the life of me I can't get my build definitions to pickup the new versions.  I even broke down and incremented the major version from 0 to 1, but it won't show up in the version dropdown when editing the build definition.  Could someone post the workflow required to ensure a build definition uses the latest version of a task?

**Comment by lukewis** [comment]
[This page](https://docs.microsoft.com/en-us/vsts/extend/publish/overview) also says that "The updated version of your extension is automatically installed to accounts that have it already installed", but that doesn't seem to be the case?  I've uninstalled and reinstalled the extension in my account.  I've also deleted and re-added the affected task to no avail.  It still only shows version "0.*" as being available, but "1.*" is nowhere to be seen.  I do however, see the 1.0 version on https://marketplace.visualstudio.com/manage.

**Comment by lukewis** [comment]
I think I figured this out.  My problems were twofold:

1. I failed to realize that the VSIX version is different than the TASK version.  I was updating the VSIX version but leaving the task version static.
2. There is a delay (timing seems indeterminant?) between when the extension is published and when builds start picking up the new version (I think this is what @bryanmacfarlane alluded to #2131.

**Comment by bryanmacfarlane** [comment]
You have to bump the version of your task in the task.json.  Not just the extension.  An extension can carry multiple tasks each independentantly versioned.

Also the task is installed into the build system async in the background so wait and refresh browser.  Also kickoff a build.  If it failed for some reason kicking off the build forces it to re-evalute

This should be closed and asked on the vsts-task-lib repo for authoring.
