### ISSUE TITLE
VSTS agents often exit with -1 after upgrading to 129.0 version

### ISSUE THREAD

**Issue by MShankwu** [Microsoft/vsts-tasks#6403]
## Troubleshooting
https://msasg.visualstudio.com/Bing_Ads/AdsUCM/_build/index?buildId=1549795&_a=summary 
https://msasg.visualstudio.com/Bing_Ads/AdsUCM/_build/index?buildId=1543973&_a=summary 
https://msasg.visualstudio.com/Bing_Ads/AdsUCM/_build/index?buildId=1533821&_a=summary 
https://msasg.visualstudio.com/Bing_Ads/AdsUCM/_build/index?buildId=1557086&_a=summary 
https://msasg.visualstudio.com/Bing_Ads/AdsUCM/_build/index?buildId=1547304&_a=summary 
https://msasg.visualstudio.com/Bing_Ads/AdsUCM/_build/index?buildId=1530476&_a=summaryhttps://msasg.visualstudio.com/Bing_Ads/AdsUCM/_build/index?buildId=1554713&_a=summaryhttps://msasg.visualstudio.com/Bing_Ads/AdsUCM/_build/index?buildId=1522103&_a=summary

## Environment
- Agent - private  OS : Windows Server 2016 Agent Version : 129.0

## Issue Description

It's strange that we meet this issue after upgrading our agents to the new version (129.0), we often find the task exist with -1 code and no other useful logs.

**Comment by bryanmacfarlane** [comment]
@MShankwu - do you run SxS multiple agents on the same machine / OS?  If so, you need to pickup 129.1.

**Comment by GuofuZhong** [comment]
@bryanmacfarlane  yes. we are running multiple agents on the same machine

**Comment by GuofuZhong** [comment]
@bryanmacfarlane Update all agents button cannot upgrade to 129.1?

**Comment by ericsciple** [comment]
set a variable process.clean=false on your definitions or install the agent manually. its on the releases tab.

multiple agents on the same machine have a problem with 2.129.0.

**Comment by ericsciple** [comment]
the 2.129.1 agent hasn't reached your deployment ring yet, but can be downloaded from the releases tab on this repo.

**Comment by GuofuZhong** [comment]
@ericsciple  Thank you for your explanation. when could it ship to our deployment ring? Do you have any ETA for this?

**Comment by ericsciple** [comment]
hopefully tomorrow, or wed. until then, set the variable on your definitions, or manually install from the download link on the releases tab.

**Comment by GuofuZhong** [comment]
Thank you, @ericsciple. we will follow up.

**Comment by bryanmacfarlane** [comment]
@GuofuZhong - note that "reaching your ring means" we update an url in your backend to point to 129.1.  As eric noted, you can download.  But that would mean manually updating (downloading, disabling agents) instead of pressing the update pool link which automates the agent to follow the url in the backend.   Variable probably the best way to validate that's the issue.

**Comment by GuofuZhong** [comment]
ok. we will apply variable to all build def.
