### ISSUE TITLE
Upload files to storage container fails with empty error, impossible to debug

### ISSUE THREAD

**Issue by johnib** [Microsoft/vsts-tasks#6405]
Getting the following error:

> Upload to container:   'mycontainer' in storage account: 'mystorageaccount' with blob prefix:   'myprefix' failed with error: '' For more info please refer to https://aka.ms/azurefilecopyreadme

it happened all of a sudden, previous builds were passing.
since today -- all of my builds fail executing this step.

I'm not sure what information I may provide you with in addition.

**Comment by chshrikh** [comment]
@johnib are you got unblocked here?

**Comment by chshrikh** [comment]
@johnib please feel free to close this if you are still facing an issue, and share the debug logs
