### ISSUE TITLE
NPM private feed. What is correct url format?

### ISSUE THREAD

**Issue by JonnyMattsson** [Microsoft/vsts-tasks#6411]
## Environment
VSTS

## Issue Description

We have a private feed that is accessible from "https://ourproject.myget.org/F/subcategory/auth/abc123.....456/npm/"

What is the correct format for the url in the npm service endpoint configuration and the .npmrc file?
It works fine if I have the full path including the token in both urls. But I would like to have the .npmrc file without any token. I have tried  with "https://ourproject.myget.org/F/subcategory" and  "https://ourproject.myget.org/F/subcategory/npm" but the npm task fails due to unauthorization.
The token should be taken from the npm service endpoint, right?

**Comment by alexmullans** [comment]
@JonnyMattsson You can get the feed URL from https://www.myget.org/feed/Details/[your feed], I believe. Should look roughly like https://www.myget.org/F/amullans/npm/. 

Put that exact URL both in your .npmrc and in the npm Service Endpoint (https://[your account].visualstudio.com/[your project]/_admin/_services?_a=resources).

**Comment by JonnyMattsson** [comment]
@alexmullans  I tried that but it didnt work.
I have attached two outputs. One with the format you suggested and one where the token is included in the .npmrc file.

Suggested format:
[npmwithoutauth.txt](https://github.com/Microsoft/vsts-tasks/files/1722919/npmwithoutauth.txt)

With token
[npmwithauth.txt](https://github.com/Microsoft/vsts-tasks/files/1722918/npmwithauth.txt)

**Comment by keithrob** [comment]
This will be fixed by [this PR](https://github.com/Microsoft/vsts-tasks/pull/6440).  In the meantime you should be able to use basic auth in a service endpoint with myget.
