### ISSUE TITLE
Suddenly getting error (##[error]Unable to deserialize the response.)

### ISSUE THREAD

**Issue by allanmoller** [Microsoft/vsts-tasks#6423]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
-VSTS
-Agent Private: 

## Issue Description

Out of the blue iam getting the following error, havnt changed anything lately.

2018-02-13T15:11:35.7482038Z ##[error]Unable to deserialize the response.
2018-02-13T15:11:35.9200724Z ##[error]There was an error with the service principal used for the deployment.
2018-02-13T15:11:36.0138248Z ##[section]Finishing: Azure PowerShell script: FilePath

**Comment by asranja** [comment]
Can you point out the cmdlet which is throwing the error ? Additionally, you can set the variable "system.debug" to "true" and redeploy to get detailed error, if any.

**Comment by asranja** [comment]
What is the version of Azure PowerShell on your private agent ?

**Comment by chshrikh** [comment]
@allanmoller are you got unblocked here ? What is the version of Azure PowerShell on your private agent ?

**Comment by chshrikh** [comment]
@allanmoller any update here

**Comment by allanmoller** [comment]
Ya sry for late reply, it is being investigated believe it is an onprem FW, tried doing a login-azurermaccount from VM hosting private agent which was disallowed :-) so basically its a FW towards azure tenant.
