### ISSUE TITLE
nuget/dotnet restore does not pick up nuget.config inside solution directory

### ISSUE THREAD

**Issue by wertzui** [Microsoft/vsts-tasks#6430]
## Environment
- Server - VSTS 
account name: adremes.visualstudio.com
build definition name: exchange CI
build number: Build 20180213.10 (id: 2588)

- Agent - Private: 
OS: Windows Server 2012 6.3.9600
Agent: 2.129.0

## Issue Description
We upgraded our nuget and dotnet Tasks from 0.* to 2.*
Using the old Version the tasks would automatically pick up any nuget.config file that was inside the same folder as the solution currently restored.
Using the new version these config files are no longer picket up, either a feed has to be specified manually (we are using multiple feeds), or you have to provide a path to one nuget.config that will be used for all solutions (each solution should use its own nuget.config).

### Error logs

The build log shows this warning

> ##[warning]No package sources were found in the NuGet.config file at C:\buildAgents\agent01\_work\2\Nuget\tempNuGet_2588.config

**Comment by keithrob** [comment]
@wertzui ,
If your repo is structured like this you should create a build step per-solution.

Also, we are working on a feature that will allow you to upstream feeds to each other (i.e. FeedA pulls packages from FeedB).  This would allow you to simplify your nuget.configs with a single feed.

Keith
