### ISSUE TITLE
Azure App Service Deploy must support setting Runtime Stack to .NET Core 2.0

### ISSUE THREAD

**Issue by rudibech** [Microsoft/vsts-tasks#6436]
## Environment
Private agent running on Windows Server 2016 connected to VSTS.
    
## Issue Description

I am trying to deploy a netcore 2.0 web application to App Service on Linux using the task Azure App Service Deploy like this:
![image](https://user-images.githubusercontent.com/1752038/36204349-44b56920-118b-11e8-8951-3a02da08fa5f.png)

I need to set Runtime Stack to ".NET Core 2.0":
![image](https://user-images.githubusercontent.com/1752038/36204560-fbee9738-118b-11e8-8e66-39c24662437f.png)

This is currently not possible (see screenshot above). I have added a pull request (#6435) to resolve this issue.

**Comment by vincentdass** [comment]
@rudibech , thanks for reaching out (+ PR).
I have added a minor comment on the PR.

**Comment by vincentdass** [comment]
@rudibech , planned to hotfix the changes. #6441.
This should be available in 1-2 weeks.

**Comment by vincentdass** [comment]
Fix is Deployed. You can select 'Core 2.0' in Runtime stack.

**Comment by rudibech** [comment]
Thank you so much! :) 

We now have the same issue for .Net Core 2.1. Do you have any plans for fixing that @vincentdass? The code for the task has changed a bit, and I am not sure where you get the list of values from now. 

I am aware that we can not select .NET Core 2.1 as Runtime for the App Service yet, but my understanding is that it should be available really soon.

**Comment by vincentdass** [comment]
@rudibech , we changed the static list to dynamic list in 4.* task version.
please change your task version to 4.* and select your preferred run-time stack.
