### ISSUE TITLE
Task fails with mesg - "VSTest Version information: null"

### ISSUE THREAD

**Issue by swiec** [Microsoft/vsts-tasks#6442]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
    - TFS on-premises version: 15.117.27024.0
    
- Agent - Private: 
   - Windows Server 2016, agent version: 2.124.0

## Issue Description

Task fails with mesg - "VSTest Version information: null"

### Error logs
[Worker_20180215-104357-utc.log](https://github.com/Microsoft/vsts-tasks/files/1727436/Worker_20180215-104357-utc.log)

tfs debug log dump: 

******************************************************************************
Task         : Visual Studio Test
Description  : Run tests with Visual Studio test runner
Version      : 2.0.55
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkId=835764)
******************************************************************************
agent.workFolder=C:\agent10\_w
loading inputs and endpoints
loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
loading INPUT_CODECOVERAGEENABLED
loading INPUT_PUBLISHRUNATTACHMENTS
loading INPUT_RUNALLTESTSAFTERXBUILDS
loading INPUT_RUNINPARALLEL
loading INPUT_RUNONLYIMPACTEDTESTS
loading INPUT_RUNSETTINGSFILE
loading INPUT_RUNTESTSINISOLATION
loading INPUT_SEARCHFOLDER
loading INPUT_TCMTESTRUN
loading INPUT_TESTASSEMBLYVER2
loading INPUT_TESTSELECTOR
loading INPUT_UITESTS
loading INPUT_VSTESTLOCATION
loading INPUT_VSTESTLOCATIONMETHOD
loading INPUT_VSTESTVERSION
loading SECRET_MACHINEPASSWORD
loaded 19
System.DefaultWorkingDirectory=C:\agent10\_w\6\s
check path : C:\agent10\_w\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.0.55\task.json
set resource file to: C:\agent10\_w\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.0.55\task.json
system.culture=en-US
System.ParallelExecutionType=undefined
Value of ParallelExecutionType :undefined
testSelector=testAssemblies
Value of Test Selector :testAssemblies
Run the tests locally using vstest.console.exe
******************************************************************************
testSelector=testAssemblies
Test selector : Test assemblies
testAssemblyVer2=**\*test*.dll
!**\obj\**
Sii.SiilQA.Core.dll
Test assemblies : **\*test*.dll,!**\obj\**,Sii.SiilQA.Core.dll
testFiltercriteria=null
Test filter criteria : null
searchFolder=C:\siilqadeploy\siilqa_bin
Search folder : C:\siilqadeploy\siilqa_bin
runSettingsFile=C:\agent10\_w\6\s
Run settings file : C:\agent10\_w\6\s
overrideTestrunParameters=null
runInParallel=False
Run in parallel : false
runTestsInIsolation=False
Run in isolation : false
runOnlyImpactedTests=False
runAllTestsAfterXBuilds=50
tia.filelevel=undefined
build.sourcesdirectory=C:\agent10\_w\6\s
TIA_IncludePathFilters=undefined
tia.useNewCollector=undefined
Build.Reason=Manual
tia.isPrFlow=undefined
tia.useTestCaseFilterInResponseFile=undefined
release.releaseUri=undefined
pathtoCustomTestAdapters=null
Path to custom adapters : null
otherConsoleOptions=null
Other console options : null
codeCoverageEnabled=False
Code coverage enabled : false
configuration=null
platform=null
testRunTitle=null
vstestLocationMethod=location
vsTestLocation=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe
vstest.console.exe, specified location : C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe
uiTests=true
vs15Helper=undefined
wmic arg: ["datafile","where","name='C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2017\\\\Enterprise\\\\Common7\\\\IDE\\\\CommonExtensions\\\\Microsoft\\\\TestWindow\\\\vstest.console.exe'","get","Version","/Value"]
exec tool: wmic
Arguments:
datafile
where
name='C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe'
get
Version
/Value
wmic datafile where "name='C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe'" get Version /Value
VSTest Version information: null
task result: Failed
TypeError: Cannot read property 'split' of null
Processed: ##vso[task.issue type=error;]TypeError: Cannot read property 'split' of null
Processed: ##vso[task.complete result=Failed;]TypeError: Cannot read property 'split' of null

**Comment by swiec** [comment]
running wmic command from cmd works well, and returns version

**Comment by acesiddhu** [comment]
@swiec what is the output of wmic command?

**Comment by swiec** [comment]
OK, problem solved. 
The cause was that on Windows Server 2016 wmic.exe is located in "C:\Windows\System32\wbem\WMIC.exe" which is not by default added to PATH system variable. 
Adding this value to PATH, solves problem. 
Additionally, screenshot from wmic result command, as asked, attached below (executed from cmd, thats why double slashes are needed)
![wmicresult](https://user-images.githubusercontent.com/2485271/36303054-075e598e-130b-11e8-9e5b-707a857b847b.png)

@acesiddhu Thanks for assistance.

**Comment by swiec** [comment]
Well tbh, above solution is more like workaround. It should work out of the box imho.

**Comment by acesiddhu** [comment]
thanks for letting us know @swiec . never knew about that. will file a bug internally and track that. closing this issue
