### ISSUE TITLE
vstest task cannot search for test assemblies outside of $(System.DefaultWorkingDirectory)

### ISSUE THREAD

**Issue by acm74** [Microsoft/vsts-tasks#6443]
we have a complicated build process that packages test assemblies together with a suite of applications for Coded UI testing.  With the (now deprecated) run functional test task, we could point to the already included test assemblies to execute coded UI tests.  The VS Test (v2) task seems to be locked to the system.defaultworkingdirectory location, and there does not seem to be a way to point to an alternative location. 
I have also tried to copy test assemblies into system.defaultworkingdirectory, but appears to fail silently, as there is no evidence of any extra files appearing in this location.
Is there a way to point this task to an alternative location (as the run functional test task allowed), or is there a workaround that would allow the vstest task to discover our test assemblies?

**Comment by acesiddhu** [comment]
@acm74 which version of vstest task are you using?

**Comment by acm74** [comment]
@acesiddhu we are using v2.

**Comment by acesiddhu** [comment]
@acm74 you can do something like this and it will work. change value of search folder.
![image](https://user-images.githubusercontent.com/1168823/36268790-77b3a5ae-129d-11e8-9db7-64f531dd92c1.png)

**Comment by acm74** [comment]
with previous attempts to change the search folder I could see that the search folder was being appended to the system.defaultworkingdirectory (e.g. D:\a\r1\a\c:\temp).  I am trying with your suggestions now.

**Comment by acm74** [comment]
after using your suggested settings for test assemblies and search folder, the task fails with:
"Error: Search folder: 'c:\CodedUITests' should be a directory and it should exist."
I can confirm that the application suite was copied correctly in C:\CodedUITests

**Comment by acesiddhu** [comment]
it works for me. are you on vsts or tfs? if tfs which version of tfs

**Comment by acm74** [comment]
vsts. It certainly hasn't worked for me, for the past 2 days. :(

**Comment by acesiddhu** [comment]
can you share the whole release logs with system.debug true

**Comment by acm74** [comment]
[ReleaseLogs_299.zip](https://github.com/Microsoft/vsts-tasks/files/1728650/ReleaseLogs_299.zip)
this is the latest...

**Comment by acesiddhu** [comment]
are you running this on hosted pool. how do you get the test dlls on the test agent machine? is that part of same phase where test task exists?

**Comment by acm74** [comment]
this is run on a hosted agent queue.  The test assemblies are bundled together our application suite as part of our build output.  That is why I wanted to be able to point the vstest task to what we already have existing.  

I can copy files to the default working directory (D:\a\....) from C:\CodedUITests, but the agent still cannot find them.  
I have experimented with modifying our build to provide test assemblies separately (so that the download artifacts task can get access to them), but it seems that I will have to use the test platform installer task first (I thought that v2 of the vstest task was supposed to handle all of this internally).

**Comment by acesiddhu** [comment]
add a cmd line task before vstest task and do dir c:\codeduitests does it list the files? that error means that there are no dlls and I want to rule that out

**Comment by acm74** [comment]
running that now.  I can log into the VMs afterwards and see that files are deployed to C:\CodedUITests.  Should I be expecting something different during execution of a release?

**Comment by acm74** [comment]
ok - this release failed because of some errors when it was unpacking the zip file of the build output.  I will have to try again. This will have to be tomorrow unfortunately.  If there are other things you think I should try, please post them here and I will follow up as soon as I can in the morning.  Thanks for your help so far :)

**Comment by acm74** [comment]
trying to get a directory listing failed, logging into one of the VM's I can see that the directory exists and is populated correctly....

2018-02-15T19:51:40.9577286Z ##[debug]Working directory: 'D:\a\r1\a'
2018-02-15T19:51:40.9577731Z ##[debug]Fail on standard error: 'False'
2018-02-15T19:51:40.9577854Z ##[debug]Modify environment: 'False'
2018-02-15T19:51:40.9578020Z ##[debug]C:\Windows\system32\cmd.exe /c ""dir C:\CodedUITests" "
2018-02-15T19:51:40.9578170Z ##[command]"dir C:\CodedUITests" 
2018-02-15T19:51:40.9836225Z The filename, directory name, or volume label syntax is incorrect.
2018-02-15T19:51:44.3487058Z ##[error]Process completed with exit code 1.

**Comment by acm74** [comment]
tried again... logs show that there is no c:\codeduitests. Logging in to a VM shows the build output is deployed correctly and available.  I can't understand why the test agent cannot see this.

2018-02-16T09:16:51.2312021Z ##[debug]Working directory: 'D:\a\r1\a'
2018-02-16T09:16:51.2312605Z ##[debug]Fail on standard error: 'False'
2018-02-16T09:16:51.2313456Z ##[debug]Modify environment: 'False'
2018-02-16T09:16:51.2313809Z ##[debug]C:\Windows\system32\cmd.exe /c "dir C:\CodedUITests"
2018-02-16T09:16:51.2314129Z ##[command]dir C:\CodedUITests
2018-02-16T09:16:51.2416250Z  Volume in drive C has no label.
2018-02-16T09:16:51.2416592Z File Not Found
2018-02-16T09:16:51.2417168Z  Volume Serial Number is 78C2-210A
2018-02-16T09:16:51.2417529Z 
2018-02-16T09:16:51.2417830Z  Directory of C:\
2018-02-16T09:16:51.2418145Z 
2018-02-16T09:16:51.9103501Z ##[error]Process completed with exit code 1.
2018-02-16T09:16:51.9113024Z ##[debug]System.Exception: Process completed with exit code 1.

![vm_buildcopied](https://user-images.githubusercontent.com/36503947/36301196-49626a70-1304-11e8-8309-f953f2a22e7f.PNG)

**Comment by acm74** [comment]
ok - I've figured this out (and it's my mistake).  I had misunderstood how agents were to be used, and a hosted agent was trying to run the tests, instead of the agent on the VM.  I'm past this, and now onto the next issue.  Thanks for your help - it gave me the clue to figure out what I had done wrong.

**Comment by nagaju** [comment]
I am running into same issue now. I am receiving below error. 
##[error]Error: Path to custom adapters 'D:\a\1\s\Packages' should be a directory and it should exist.
Any pointers?
