### ISSUE TITLE
Format for Specifiying additional properties on SonarQube VSTS Extension

### ISSUE THREAD

**Issue by scriptmonkey69** [Microsoft/vsts-tasks#6450]
Do I need to specify /D: in front of each key value pair and also have each key value pair on a new line?

As the documentation in the VSTS Extension just references key value pair, but I keep finding examples that reference /D: format

**Comment by peppi-scaleforce** [comment]
And connected question if I may: I am using 

/d:sonar.github.pullRequest=$(System.PullRequest.PullRequestId) 

also tried:

/d:sonar.github.pullRequest=$(SYSTEM_PULLREQUEST_PULLREQUESTID)

but both doesn't work. Can you help with that variable please?

**Comment by peppi-scaleforce** [comment]
Just for information: fixed my problem using powershell parsing Env:BUILD_SOURCEBRANCH.

The param SYSTEM_PULLREQUEST_PULLREQUESTID was returning wrong number with github.

**Comment by ericsciple** [comment]
@scriptmonkey69 you should reach out to Sonar folks for information about using their tasks. The agent prints an information block about each task at the beginning of the task log. It should have a link where to get more information from the author.

**Comment by ericsciple** [comment]
@peppi-scaleforce apart from the Sonar issue, are you saying there is a general issue with the pull request variables when using GitHub? Are you using VSTS or on-premises TFS?

**Comment by scriptmonkey69** [comment]
My problem was resolved by using the following command to import the Test Coverage data from the VNext build

sonar.cs.vscoveragexml.reportsPaths=**/*.coveragexml

No need for the /D: in the version 4 extension, also need to place the extra properties on separate lines.

**Comment by peppi-scaleforce** [comment]
@ericsciple 
VSTS. 

Here are my variables:

SYSTEM_PULLREQUEST_PULLREQUESTID: 169686735
SYSTEM_PULLREQUEST_SOURCEBRANCH: feature/AddTests
SYSTEM_PULLREQUEST_TARGETBRANCH: develop
BUILD_SOURCEBRANCH: refs/pull/169/merge

My real PR number is: 169

Thanks.

**Comment by ericsciple** [comment]
@peppi-scaleforce thank you for the details. I've forwarded this info along to the appropriate team. I honestly don't know whether this is the expected behavior.

**Comment by pjquirk** [comment]
@peppi-scaleforce Thanks again for the feedback! we've added a task to our backlog to expose the PR number more directly.
