### ISSUE TITLE
Not able to execute generictest from testhub since source filter is always set to *.dll and not able to change it to generictest through any options

### ISSUE THREAD

**Issue by buynowcoupons** [Microsoft/vsts-tasks#6459]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Error logs

[Insert error from the logs here]

**Comment by pjquirk** [comment]
This project is for issues with [tasks](https://docs.microsoft.com/en-us/vsts/build-release/concepts/process/tasks) in VSTS.  Questions or bug reports about the Test Hub should be directed to [Developer Community](https://developercommunity.visualstudio.com/spaces/22/index.html).
