### ISSUE TITLE
Support TAEF as a vsts-task

### ISSUE THREAD

**Issue by minghan** [Microsoft/vsts-tasks#6460]
Hi,

Is it possible to support TAEF as a tesrunner similar to VSTest? Our team heavily relies on using TAEF for our testing infrastructure and TAEF offers more advanced capabilities compared to VSTest. Although we are able to run TAEF through a cmd script, the lack of TAEF support is blocking us from leveraging all the goodness that comes with VSTS (such as being able to track test history, etc on VSTS).

Thanks,
Ming Han

**Comment by acesiddhu** [comment]
@minghan we will take this thread on devops_tools AT Microsoft DOT com where you have already send a mail. Closing this issue

**Comment by Nirmal4G** [comment]
Any status on this? Seems like TAEF is not supported by `VSTest` task. Is it under a different name or is it not supported?
