### ISSUE TITLE
Feature: Add docker login, docker pull, and docker retag commands

### ISSUE THREAD

**Issue by ppanyukov** [Microsoft/vsts-tasks#6480]
(Not sure this is the right place to ask for new features?)

In Docker task, we can do: build image, push image etc.

What we are missing some very important things.

- docker login: is ability to simply login to the registry;
- docker pull: to force pull an image;
- docker retag: tag source image with new tag;

---

# Docker login

We need this as we have scripts and steps in the build/release which use docker directly, such as `docker pull` for example. For these steps to work we have to authenticate first. Currently there isn't a way, except through some hacking.

# Docker pull

Some tasks we run need to ensure the latest image is pulled. Currently we do this using inline bash. This would be OK in general, but: 

- the absence of `docker login` task makes it more difficult than necessary.
- we run into issue with image names due to case-normalization the current docker tasks do.

# Docker retag

We often propagate images from one registry to another. This requires:

- `docker pull source_tag`
- `docker tag source_tag target_tag`
- `docker push target_tag`

We currently have to use hacky bash for this.

See above about absence of `docker pull` and `docker login` which makes it difficult.

The biggest problem however is the case-normalisation.

We use build IDs and build names as image names. When we use VSTS docker tags, these convert everything to lower case: e.g. `BuildName = MyCoolBuild` would be converted to `Tag = mycoolbuild`.

Now, our bash scripts recieve `BuildName` vars as-is. We have to have additional steps to convert that to lower case.

Everything combined, this retagging using bash is quite painful and hacky. Would be nice to have the VSTS task for this, with `SourceRegistry, SourceTag` and `TargetRegistry, TargetTag` arguments or something similar.

**Comment by andrew-gordon** [comment]
Hi @ppanyukov 

I'm trying to execute 'docker login' inside a VSTS task but I'm getting the error "Cannot perform an interactive login from a non TTY device".  You mentioned there is a way with some hacking. How did you manage to achieve that?  Thanks.

**Comment by azooinmyluggage** [comment]
Please do let us know if you are still facing the issue or have any other feedback.

**Comment by leonpw** [comment]
To fool the VSTS task in having an interactive login, you can do the following:

echo "password" | docker login --username username --password-stdin docker.registry:123


I do not recommend this method!
