### ISSUE TITLE
npm install and custom task - scoped registry configuration

### ISSUE THREAD

**Issue by aarondandy** [Microsoft/vsts-tasks#6491]
## Environment

npm task version: 1.0.10

## Issue Description

The "install" and "custom" variants of the npm task allow us to specify credentials in VSTS to use when authenticating to a registry which is helpful but a bit more control over the npmrc could go a long way for us. The issue we are running into is being unable within the VSTS npm task to configure a registry for a scope which we often configure on workstations to allow developers to auth as they wish. We would like to be able to configure the npm task so that packages within the `@contoso` scope can be retrieved from `https://contoso.myget.org/F/npm/npm/` . It would be nice if we could provide a list of repositories for scopes in the same UI section where we also can configure registry credentials or somehow associate scopes with an npm registry credential entry.

## Workaround

To work around this limitation without conflicting with workstation configuration we add a powershell task to our VSTS builds:

```powershell
Out-File -InputObject '@contoso:registry=https://contoso.myget.org/F/npm/npm/' -FilePath '.npmrc' -Encoding ASCII
```

**Comment by keithrob** [comment]
@aarondandy ,
Have you tried[1]?

[1]
![image](https://user-images.githubusercontent.com/908203/37991123-2fe77a2c-31bd-11e8-8585-260d5d721a49.png)

**Comment by aarondandy** [comment]
It is a bit unrelated to this issue, but yes I have, for other reasons. The core of this GitHub issue is to allow us to configure registries for scopes within the VSTS UI itself, without needing an .npmrc file that will conflict among different developers.

**Comment by keithrob** [comment]
@aarondandy ,
I'm not groking "an .npmrc file that will conflict among different developers".  Can you give me a specific example?

**Comment by aarondandy** [comment]
Sure. If you commit an .npmrc file to source control it will take effect on each developers workstation. If each developer uses the same url to access the repository this may be acceptable, but I would still prefer to manage these scopes at a system level. If different developers want to use different urls for that scope it causes issues as the repository npmrc overrides the system. An example of this is when one developer may want to configure their system to use a myget preauthenticated url while another developer wishes to use a token saved to their user npmrc. The developer using a machine configured with a preauthenticated url will have there system attempt to use the basic url and fail to authenticate.

**Comment by aarondandy** [comment]
Another thought I had that may resonate with more users outside my specific case and make the issue much simpler:

I don't want to commit .npmrc to my repository. Instead I would like to manage those settings on each developers machine and within vsts's existing storage for feeds. This would replicate what I am doing with my simple powershell script. Even something as simple as letting us set the base npmrc content before the temporary npmrc file is generated would be at least helpful.

**Comment by keithrob** [comment]
Re: "If different developers want to use different urls for that scope it..."
I think you are suggesting that developerA has...
@w00t:registry=https://example.com/...

and developerB has...
@w00t:registry=https://notexample.com/...

If so that sounds dangerous and a recipe for builds that aren't reproducible.  Or recommendation is that you do check in your .npmrc into your repo with the registr(y|ies) that you actually need to build your project.  This .npmrc should **not** have credentials checked in.  On each developer's workstation they should add credentials for each registry listed in their project's .npmrc in $HOME/.npmrc.  When the developer runs npm, npm will inspect the project's .npmrc, search backwards, and find for the registries in $HOME/.npmrc.

This recommendation is documented [here](https://docs.microsoft.com/en-us/vsts/package/get-started-npm?view=vsts#step-3-set-up-your-npmrc).

**Comment by aarondandy** [comment]
Well you don't have to like it :p It's what I want though.

**Comment by keithrob** [comment]
@aarondandy,
I don't believe we will ever solve this problem in the way that you want.  However, we are introducing the concept of upstreaming that will allow you to manage dependencies at the feed level.  You will be able to upstream your feeds to other feeds within your account (i.e. FeedA fetches packages from FeedB) and to unauthenticated public registries.

**Comment by aarondandy** [comment]
My workaround has me moving, I'm just thinking that something as simple as a text box allowing me to inject whatever awful things I want into the node tasks would go a long way. Just to avoid my `Out-File`
