### ISSUE TITLE
VSTest task picks up SSDT folder and breaks Code Coverage

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-tasks#6495]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- TFS
- Agent Private: 
    
## Issue Description

See: https://stackoverflow.com/questions/48914786/change-the-location-of-vstest-console-in-tfs-2017-build

In TFS Test Task I know that I can manually set the location of vstest.console.exe via:

path to console

this is less than an ideal solution though since, as I update my build server, this location may become invalid. The problem that I have run into is that if I select 'Version' my build server ends up using the vstest.console at this location:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\ SQL\Common7\IDE\CommonExtensions\Microsoft\TestWindow
```
I am guessing that this SQL Folder is the SQL Server Data Tools folder that is installed on the build server. This folder location isn't generally a problem, vstest runs my unit tests and reports back on them, however it doesn't produce a code coverage report. I initially thought that this was due to an improper configuration of the builds, however after verifying that the build was setup correctly and that the server had all of the necessary dependencies I started looking for other causes. I opened up the .trx file from one of the builds and noticed that the DataCollector logged a message that it couldn't find CodeCoverage.exe. After some more troubleshooting I pointed my build to the location of the vstest.console shown in the image above and everything (tests, code coverage) ran fine. This leads me to believe that vstest expects the path: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Team Tools\Dynamic Code Coverage Tools` to exist relative to where it is run from and that directory (Dynamic Code Coverage Tools) does not exist inside the SQL folder.

Is there a way to change the path that TFS uses when the 'Version' checkbox is checked?

**Comment by vimegh** [comment]
VsTest task uses vswhere.exe in order to determine the latest version of VS installed. Can you try to run vswhwere.exe and check which version of VS is installed at  C:\Program Files (x86)\Microsoft Visual Studio\2017\ SQL folder and is it higher than other versions. Also is that not an enterprise installation. 

You will be able to find vswhere.exe in agent working folder as per VSTest task version eg. 
C:\Temp\Agents\127Agent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.3.19\vswhere.exe

**Comment by nigurr** [comment]
Hi,

This is fixed in later versions to pick the VS product with test tools installed. However if you have multiple VS family products with test tools package, we will pick the latest one. 
Only way to override this behavior is to use custom location. Thanks for your support
