### ISSUE TITLE
Download Build Artifacts (Preview) - latest build from a branch

### ISSUE THREAD

**Issue by drewkg** [Microsoft/vsts-tasks#6496]
Just looking at the Download Build Artifacts (Preview) VSTS build task.  However being able to download a nominated build is very limiting, would it be possible to download the latest build from a branch (or by tag / build name)  

This way I could say give me the latest build from master, but not a feature branch or give me the least *-prod build.

**Comment by GitHubSriramB** [comment]
This enhancement is being considered. Here's the relevant PR:
https://github.com/Microsoft/vsts-tasks/pull/6356
