### ISSUE TITLE
[Question] Share Service Endpoints between Projects?

### ISSUE THREAD

**Issue by MikahB** [Microsoft/vsts-tasks#6512]
As stated [here](https://docs.microsoft.com/en-us/vsts/build-release/concepts/library/service-endpoints):

> Service endpoints are created at project scope. An endpoint created in one project is not visible in another team project.

We are building out several applications using a microservices architecture.  We're using Kubernetes on Azure for container orchestration, and in VSTS it seems we have two options:

1. Use a single VSTS Project to Build/Release all microservices that use that Kubernetes cluster, thereby sharing the relevant Service Endpoint, or
2. Use individual projects for each microservice (which feels more right) but duplicate the Kubernetes Service Endpoint in every project

Am I missing a better option, or is that really it?  It would be great to be able to set up Account-Level Service Endpoints then share with individual projects, but maybe there is something better already.

**Comment by GitHubSriramB** [comment]
@MikahB - we currently support service endpoints only at a Team Project scope. We will be supporting service endpoints at other scopes in future. Apologies for the inconvenience.

**Comment by MikahB** [comment]
No problem @GitHubSriramB  - just wanted to be sure I wasn't missing something obvious.  Appreciate the response and look forward to future feature additions!

**Comment by kilasuit** [comment]
@GitHubSriramB - is there a timeline for this coming at the instance level as opposed to being only scoped at the team project level?
