### ISSUE TITLE
VSTS builds are stuck, waiting for available agents

### ISSUE THREAD

**Issue by MShankwu** [Microsoft/vsts-tasks#6537]
## Troubleshooting
https://msasg.visualstudio.com/Bing_Ads/UCM%20Team/_build/index?context=allDefinitions&path=%5CUCM&definitionId=3004&_a=completed

## Issue Description
VSTS builds are stuck, waiting for available agents

**Comment by bryanmacfarlane** [comment]
Closing.  Not an issue with the tasks in this repo.
