### ISSUE TITLE
Code coverage  breaks Unit Tests

### ISSUE THREAD

**Issue by Poseideon** [Microsoft/vsts-tasks#6552]
## Environment
- Server - TFS on-premises 
    
    - TFS on-premises:  2017 Update 3
    
- Agent - Hosted or Private: 
    
    - Private agent hosted on OS Windows 2012 R2 and the agent version: 2.126

## Issue Description
When using Visual Studio Test task (ver 2) to execute unit tests and integrate that with SonarQube 6.2, unit tests fail for the following configuration in the VS Test task - 

1. 
Code Coverage - Enabled
Test Platform - Visual Studio 2017
More than half the test cases fail with error message - 
Failed to resolve profiler path from COR_PROFILER_PATH and COR_PROFILER environment variables

2. 
Code Coverage - Enabled
Test Platform - Visual Studio 2015
Handful of test cases fail while executing shim code. It's almost like shim code is being ignored and test code is calling the actual external assembly. One of the error message was 
Error CS0115: 'StubDSA.HashData(Stream, HashAlgorithmName)': no suitable method found

Note that TFS build server has both VS 2015 and VS 2017. The unit test code compiles on local machine and on build server via VS 2015 and VS 2017 just fine. It stops working when Code Coverage is enabled and executed via the build definition.

Thanks!

**Comment by prawalagarwal** [comment]
@Poseideon Hi, Are you still facing this issue? Can you reach out to devops_tools[at]microsoft[dot]com with your build logs with some more details about your scenario? Thanks

**Comment by prawalagarwal** [comment]
Closing this. Please re-open if you are still facing this issue.
