### ISSUE TITLE
XCode: "custom destination platform" option is always used if set regardless which item is selected from the dropdown

### ISSUE THREAD

**Issue by yacaovsnc** [Microsoft/vsts-tasks#6557]
## Issue Description

1. Create a build with an 'Xcode build' phase
2. Enter a string in the "Custom destination platform" box
3. Switch to a different item on the Destination platform drop down
4. Save and queue the build

The previous entered "custom desitination platform" still ends up being sent to the xcodebuild agent. It should not as it is fairly confusing to track down why that's still happening.

It seems this is the [bug](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Xcode/xcode.ts#L95).  We always honor what's set in "custom destination platform" field.

**Comment by madhurig** [comment]
Closing since this is being tracked on https://developercommunity.visualstudio.com/content/problem/193958/xcode-entering-a-custom-destination-and-then-chang.html
