### ISSUE TITLE
Enable to select multiple feeds in NuGet restore task Feed(s) I select here

### ISSUE THREAD

**Issue by lvsezhufu** [Microsoft/vsts-tasks#6561]
For now, we can only select only one feed from Feed(s) I select here option (NuGet restore task).

![11](https://user-images.githubusercontent.com/23092306/36773830-84359910-1c96-11e8-930f-7bb7ba7135f8.png)

It should be more reasonable that we can select multiple feeds instead of only one feed. Just like we can select multiple feeds from outside:

![11](https://user-images.githubusercontent.com/23092306/36773980-2393f8da-1c97-11e8-93b0-14e529f48f6c.png)

**Comment by alexmullans** [comment]
Thanks for the feedback @lvsezhufu. We originally designed the task this way because we wanted to encourage people using multiple feeds to check in a NuGet.config with all the feeds needed. This enables each engineer who checks out the codebase to be immediately successful, rather than needing to add multiple feeds to the NuGet Package Manager configuration first.

In your scenario, how would you expect engineers on their dev machines to configure both 1stFeed and 2ndFeed?

**Comment by lvsezhufu** [comment]
@alexmullans The scenario to select multiple feeds is that the dependencies are located in different feeds. In order to download all the referred packages, we need to select multiple feeds.

**Comment by Vossekop** [comment]
Will the task at least consider each solution's individual nuget.config if we leave the "Path to NuGet.config" blank?

**Comment by keithrob** [comment]
@lvsezhufu and @Vossekop ,
I am closing this issue.  There is a new feature coming out soon that will allow you to upstream Feeds to each other.  Upstreaming is a much better way to solve this problem than the solution that is being proposed here.

**Comment by Vossekop** [comment]
@keithrob actually, I find the solution you provided before to be the better one (use Nuget.config files at the solution level). And maybe it was a bit unclear in my previous message, but it was a genuine question: Does the task consider each solution's individual nuget.config if the path is left blank?

Don't get me wrong, I do very much like the upstream feeds to become more flexible than they are now.

**Comment by keithrob** [comment]
It does not consider the individual nuget.config if there is one adjacent to a .sln.  Assuming you've wildcarded .sln files, the task will find them all and run restore on [each one at a time](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/NuGetCommand/nugetrestore.ts#L180).

We could probably fix this behavior by CDing to the directory containing the .sln and running nuget.exe from there, but that isn't on the near term plan.

**Comment by gabrielkunkel** [comment]
My 2 cents is let people list multiple feeds, separated by semi-colons. I'm in a case where the streams cannot be combined and I can't just add a nuget.config file. Best idea is whatever makes things possible. More options > less options. This limitation will require me to use Jenkins today.

**Comment by malavvvakharia** [comment]
It is not working with semicolons right now. So If I have to use multiple feeds I need to use nuguet.config file? 

Below is not working:

1st option:

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'ProjectName/Feed1'
    includeNuGetOrg: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'ProjectName/Feed2'
    includeNuGetOrg: true

2nd option:

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'ProjectName/Feed1;ProjectName/Feed2'
    includeNuGetOrg: true
