### ISSUE TITLE
Give access to GitHub pullrequest number (instead of id)

### ISSUE THREAD

**Issue by henryju** [Microsoft/vsts-tasks#6564]
When building a GitHub pullrequest, the GitHub PR ID is available in the variable `SYSTEM_PULLREQUEST_PULLREQUESTID`. But this is pretty useless, since [GitHub REST API](https://developer.github.com/v3/pulls/#get-a-single-pull-request) use the PR _number_ as identifier. If not too late, I would suggest to return the GitHub PR number in variable `SYSTEM_PULLREQUEST_PULLREQUESTID`. And if you think it's too late, could you consider adding a new variable with this information?

**Comment by madhurig** [comment]
We added a new variable SYSTEM_PULLREQUEST_PULLREQUESTNUMBER. It has been merged into the daily release branch and should be available in production in a couple of days. 

Thanks,
Madhuri

**Comment by madhurig** [comment]
@henryju: This has been deployed, let us know if you are able to use the new variable  SYSTEM_PULLREQUEST_PULLREQUESTNUMBER.

**Comment by henryju** [comment]
@madhurig I confirm it works! Don't forget to update this page https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/build/variables?tabs=batch#predefined-variables Would be also interesting to track the version of TFS for which it will be supported (same for all other variables BTW).

**Comment by madhurig** [comment]
@henryju : I have a PR (internal repo) for the doc change. I agree it would be useful to track which version the variables are available on. I will pass on the feedback to our docs team.

Thanks,
Madhuri

**Comment by chris31389** [comment]
@madhurig any chance you can add the PR number to the PR Release Pipeline?

**Comment by madhurig** [comment]
@chris31389 - please open a new issue for release. @Lovakumar - FYI.
