### ISSUE TITLE
Error when updating properties of a newly created slot

### ISSUE THREAD

**Issue by youngcm2** [Microsoft/vsts-tasks#6566]
We have a process that is failing about 10% of the time.

We create a new slot

`az webapp deployment slot create --name AppServiceName --resource-group ResourceGroupName --slot predeploy-dev --configuration-source AppServiceName `

This returns JSON which show it is created.

We then try to update the resource and get failures sometimes other times it runs great. A redeploy is always successful.

`az resource update --name predeploy-dev --resource-group ResourceGroupName --namespace Microsoft.Web --parent sites/AppServiceName --resource-type slots --set properties.clientAffinityEnabled=false`

> ERROR: Operation failed with status: 'Not Found'. Details: 404 Client Error: Not Found for url: https://management.azure.com/subscriptions/************************/resourcegroups/ResourceGroupName/providers/Microsoft.Web/sites/AppServiceName/slots/predeploy-dev?api-version=2016-08-01
> [command]C:\Windows\system32\cmd.exe /D /S /C ""C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin\az.cmd" account clear"
> ##[error]Script failed with error: Error: C:\Users\VSSADM~1\AppData\Local\Temp\azureclitaskscript1519426409955.bat failed with return code: 1

**Comment by hiyadav** [comment]
In this case when you go and check the web app, is the slot actually created ?
It looks like Azure is still creating the slot in the background or somehow the data has not been updated in Azure App Service, so you can add retry around the update resource statement or wait for a few seconds before that call is made.
Hope this helps.

**Comment by sachinma** [comment]
@youngcm2 were you able to resolve the issue?

**Comment by sachinma** [comment]
@youngcm2 closing this issue. Please reopen if you face this again.
