### ISSUE TITLE
Feature Request - Add support for uploading third-party unit test and code coverage results to VSO.

### ISSUE THREAD

**Issue by dmccaffery** [Microsoft/vsts-tasks#657]
For those of us creating cross-platform applications, we rely on many different unit test and code coverage results, like OpenCover (CLR), and Mocha (JS). I'm not expecting VSO agents to automatically consume all of the variant formats that are out there, but it would be great if there was an API endpoint and a VSO task that could publish results in a pre-defined format and allow third party tools to emit that format, or create transforms to support it.

**Comment by chrisrpatterson** [comment]
There already is.  The Publish Test Results task will publish from a variety of formats like Nunit, Junit, xUnit and Trx.

**Comment by dmccaffery** [comment]
Agreed for unit test results; this was more geared toward code coverage results. My apologies for the confusion -- not sleeping much these days trying to keep up with DNX. :)

**Comment by gopinathch** [comment]
Hello Deavon,
We are currently working on adding code coverage support for DNX apps. We are also adding a Publish Code Coverage task with Jacoco and Cobertura formats - we have extensibility for other formats as a backlog, we are still looking at the right way of exposing it as a REST API.

**Comment by dmccaffery** [comment]
@gopinathch This is awesome news! I thought it would be further off in the distance than this, so I'm happy to hear this. It's obviously not a blocking issue. It would just be nice to be able to collect and see everything in one place, instead of having to look at a build in AppVeyor, a build in Travis, and a report in Coveralls, as an example. VSO / TFS is staged to be the perfect blend of everything one needs.

**Comment by bryanmacfarlane** [comment]
@atinb ?

**Comment by atinb** [comment]
The Publish Code Coverage task has been shipped and can be used to upload Jacoco and Cobertura formats.

**Comment by nanivijay** [comment]
![snip_20160708232151](https://cloud.githubusercontent.com/assets/5945591/16706469/ca1c2082-4562-11e6-8436-21a5c370b935.png)
![image](https://cloud.githubusercontent.com/assets/5945591/16706476/f5874314-4562-11e6-88a9-8b33ca630cd1.png)
I gave the cobertura.xml in the publish code coverage task.I am getting the attached error message.

**Comment by gopinathch** [comment]
Atin, can you look into this?

Sent from my Windows Phone
________________________________

**Comment by atinb** [comment]
@nanivijay 
Are you specifying the files in the Report Directory field? Can you attach a screenshot of the settings in your Publish task? Thanks!

**Comment by nanivijay** [comment]
![image](https://cloud.githubusercontent.com/assets/5945591/16709044/5df4daea-45ba-11e6-8633-4548464bdb3d.png)

Which files/directory  i need to give in the report directory path. I have only the opencover.xml after running the open cover and then converted it into coberura.xml using https://github.com/danielpalme/OpenCoverToCoberturaConverter

**Comment by atinb** [comment]
Other than the Summary file, there is an reports directory created with HTML files. You have to point to that directory in the Report Directory field. Thanks!

**Comment by nanivijay** [comment]
i generated the html reports using reportgenerator https://github.com/danielpalme/ReportGenerator

Still no luck :( 

![image](https://cloud.githubusercontent.com/assets/5945591/16714414/009ffccc-4677-11e6-9445-0d7f699ec83a.png)

**Comment by nanivijay** [comment]
I am using opencover to generate the codecoverage xml(https://github.com/OpenCover/opencover) for asp.net 5 DNX application. After that i am using Reportgenerator to generate the htmls.(https://github.com/danielpalme/ReportGenerator) .VSTS supports **Cobertura** in the publish task so i converted the opencover coverage xml to Cobertura using https://github.com/danielpalme/OpenCoverToCoberturaConverter.

Please let me know if you need more information.
