### ISSUE TITLE
Is there any way to know from a custom build task if the agent running the task is hosted or private?

### ISSUE THREAD

**Issue by jsalado** [Microsoft/vsts-tasks#6582]
## Environment
VSTS, javiersalado.visualstudio.com

- Agent - Hosted or Private: 
    
Both. All OS

## Issue Description
I have created a custom build task that needs to know if it is running on a hosted or a private agent, because on the hosted agent it needs to download and install a specific tool.

Right, now I'm using the Agent.Name variable and looking for the word 'Hosted' in it. This is not very reliable if the name can be changed.

Any other more reliable way?

Thanks,
J.

**Comment by bryanmacfarlane** [comment]
No.  It's sort of an anti pattern.  A hosted agent is just an azure VM with our agent application on it - no different than if someone acquired an azure VM and installed our agent on it.

What are you really after?  What's the scenario or problem you're trying to solve?

**Comment by jsalado** [comment]
Hi Bryan,

understood. It makes sense.

When my build tatask runs on hosted agents, the first thing it has to do is install the analyzer, whereas is the agent is private it maybe already installed. So my approach has been to check if agent is hosted (looking into the agent name, very unreliable) and decide what to do next.

I guess I have to change my strategy and don't differentiate agents by hosted or private (an agent is an agent, right?) and just try to find out if my analyzer is pre installed or not and take from there...

Thanks,
J.

**Comment by bryanmacfarlane** [comment]
Yeah - that was going to be my recommendation.  Toggle on whether installed.  Thanks!
