### ISSUE TITLE
Error loading AzureRM 5.1.1 in Azure Powershell Task

### ISSUE THREAD

**Issue by jasonshsoftware** [Microsoft/vsts-tasks#6585]
## Environment
VSTS: 
https://richardsinstitute.visualstudio.com/ETMRichardsInstitute.org/_release?releaseId=80

Hosted Agent:
Hosted VS2017

## Issue Description
Receiving an error when using Azure Powershell Task in a release definition. It is set to run a file source with variable arguments. The version is set to use latest. My last successful deployment was 2/22/18. Here is the output log:

> 2018-03-01T14:16:54.6876609Z ==============================================================================
> 2018-03-01T14:16:54.6877456Z Task         : Azure PowerShell
> 2018-03-01T14:16:54.6878253Z Description  : Run a PowerShell script within an Azure environment
> 2018-03-01T14:16:54.6879013Z Version      : 2.0.5
> 2018-03-01T14:16:54.6879688Z Author       : Microsoft Corporation
> 2018-03-01T14:16:54.6880636Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613749)
> 2018-03-01T14:16:54.6881581Z ==============================================================================
> 2018-03-01T14:17:02.4565989Z ##[command]Import-Module -Name C:\Modules\azurerm_5.1.1\AzureRM\5.1.1\AzureRM.psd1 -Global
> 2018-03-01T14:17:06.5773173Z ##[error]The following error occurred while loading the extended type data file: Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": The TypeConverter was ignored because it already occurs.
> Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.Abstractions.IAzureContextContainer": The member SerializationDepth is already present.
> Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache": The member PropertySerializationSet is already present.
> Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache": The member SerializationMethod is already present.
> Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache": The member PropertySerializationSet is already present.
> Error in TypeData "Microsoft.Azure.Commands.Common.Authentication.AuthenticationStoreTokenCache": The member SerializationMethod is already present.
> Error in TypeData "Microsoft.Azure.Commands.Profile.Models.PSAzureContext": The member SerializationDepth is already present.
> Error in TypeData "Microsoft.Azure.Commands.Profile.Models.PSAzureProfile": The member SerializationDepth is already present.
>

**Comment by joe45sp** [comment]
I'm getting the same exact issue. Will try specifying the version number for now.

**Comment by jasonshsoftware** [comment]
Excellent. I'll give that a try. Thanks!

**Comment by chshrikh** [comment]
this has been fixed.

**Comment by joe45sp** [comment]
@chshrikh Is it possible to put some automated testing in place to prevent this from happening again?

**Comment by chshrikh** [comment]
@joe45sp , yes we are already on it to catch these kind of issue with automation. Thansk
