### ISSUE TITLE
dotnet build task fails for .NET Core 2 project

### ISSUE THREAD

**Issue by baldswede** [Microsoft/vsts-tasks#6587]
Hi, I have just started setting up a build for a dotnet Core 2 project. The project builds fine using the command line locally (dotnet build [ProjectName].csproj). But in VSTS the command fails.

My local dotnet version is 2.1.4. NuGet restore and other tasks before the dotnet build command are successful in VSTS.

I have enabled verbose logging, which throws the following error:

> 2018-03-02T06:22:04.6010833Z ##[error]Error: C:\Program Files\dotnet\dotnet.exe failed. spawn C:\Program Files\dotnet\dotnet.exe ENOENT
> 2018-03-02T06:22:04.6028662Z ##[debug]Processed: ##vso[task.issue type=error;]Error: C:\Program Files\dotnet\dotnet.exe failed. spawn C:\Program Files\dotnet\dotnet.exe ENOENT
> 2018-03-02T06:22:04.6029115Z ##[debug]task result: Failed
> 2018-03-02T06:22:04.6030026Z ##[error]Dotnet command failed with non-zero exit code on the following projects : D:\a\1\s\src\VolvoLive\VolvoLive.csproj
> 2018-03-02T06:22:04.6030559Z ##[debug]Processed: ##vso[task.issue type=error;]Dotnet command failed with non-zero exit code on the following projects : D:\a\1\s\src\VolvoLive\VolvoLive.csproj
> 2018-03-02T06:22:04.6031709Z ##[debug]Processed: ##vso[task.complete result=Failed;]Dotnet command failed with non-zero exit code on the following projects : D:\a\1\s\src\VolvoLive\VolvoLive.csproj
> 2018-03-02T06:22:04.6032340Z ##[debug]rc:-4058
> 2018-03-02T06:22:04.6032684Z ##[debug]success:false

VSTS account name: vccsp
team project name: VolvoCarsLive
build definition name: VCL Dev Deploy CI
build number: 20180302.2
agent queue name: Hosted VS2017

Logs: [logs_1736.zip](https://github.com/Microsoft/vsts-tasks/files/1773926/logs_1736.zip)

**Comment by baldswede** [comment]
Solved it myself

**Comment by Geekays** [comment]
Can you elaborate the resolution? I am too facing similar issue.

**Comment by baldswede** [comment]
I just cleared the "Working directory" field. Before I had set it to the subfolder containing the .csproj file which was incorrect. The working directory should be the root.

**Comment by paultechguy** [comment]
Same problem.  Just to elaborate on baldswede solution (which clearing this field worked), the working directory is the VSTS Build field:

![image](https://user-images.githubusercontent.com/9164881/45911871-1a7f4700-bdd6-11e8-98c6-dfade3477952.png)

**Comment by BennyBread** [comment]
Had the same Problem. Clearing the "Working directory" solved the problem.

**Comment by InspiringCode** [comment]
I had the same issue with a .NET 6 yaml-pipeline, and the problem was, that I tried to use a file matching pattern (`**/MyProject`) for the `workingDirectory` attribute. When replacing it with `$(Build.SourcesDirectory)/src//MyProject` it worked!
