### ISSUE TITLE
Windows Machine File Copy v2 admin login not resolving $env:computername\svcUser

### ISSUE THREAD

**Issue by jdshkolnik** [Microsoft/vsts-tasks#6642]
## Environment
- Server: VSTS, Deloitte-FinTech, Solvas, Forecast_pre, release id 243

- Agent: Private, Windows 2008 R2, 2.123.0

## Issue Description

I create local machine accounts with same name and password. That way, a single task can copy to multiple machines with same login/password. In the v1 of the file copy task, I'd put `$env:computername\svcUser` for admin login and it'd resolve for each machine name in the list of machines. It breaks in v2 and then works if I revert to v1.

### Error logs

> ##[debug]Evaluating condition for step: 'Copy files to servers'
> ##[debug]Evaluating: succeeded()
> ##[debug]Evaluating succeeded:
> ##[debug]=> (Boolean) True
> ##[debug]Expanded: True
> ##[debug]Result: True
> ##[section]Starting: Copy files to servers
> ==============================================================================
> Task         : Windows Machine File Copy
> Description  : Copy files to remote machine(s)
> Version      : 2.0.3
> Author       : Microsoft Corporation
> Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=627415)
> ==============================================================================
> ##[debug]VstsTaskSdk 0.8.2 commit 
> ##[debug]Entering I:\Agent\NA-Cooperative-VSTS\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.0.3\WindowsMachineFileCopy.ps1.
> ##[debug]INPUT_MACHINENAMES: 'srvr49v\Deploy,srvr75v\Deploy'
> ##[debug]INPUT_ADMINUSERNAME: '$env:computername\svcUser'
> ##[debug]INPUT_ADMINPASSWORD: 'RMServicePW1!'
> ##[debug]INPUT_SOURCEPATH: 'I:\Agent\NA-Cooperative-VSTS\_work\r12\a\Codebase_ci'
> ##[debug]INPUT_TARGETPATH: 'NA\2.1.1-beta.253+22_20180308.1_QA'
> ##[debug]INPUT_ADDITIONALARGUMENTS (empty)
> ##[debug]INPUT_CLEANTARGETBEFORECOPY: 'true'
> ##[debug]INPUT_COPYFILESINPARALLEL: 'true'
> ##[debug]Loading resource strings from: I:\Agent\NA-Cooperative-VSTS\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.0.3/Task.json
> ##[debug]Loaded 10 strings.
> ##[debug]SYSTEM_CULTURE: 'en-US'
> ##[debug]Loading resource strings from: I:\Agent\NA-Cooperative-VSTS\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.0.3\Strings\resources.resjson\en-US\resources.resjson
> ##[debug]Loaded 10 strings.
> Copy started for - srvr49v\Deploy
> VERBOSE: Exporting function 'New-PSWorkflowSession'.
> VERBOSE: Exporting alias 'nwsn'.
> Copy started for - srvr75v\Deploy
> WARNING: VstsTaskSdk is designed for use with powershell.exe (ConsoleHost). 
> Output may be different when used with other hosts.
> ##[debug]System.Management.Automation.RemoteException: Copying failed for resource : srvr49v\Deploy
> ##[debug]Failed to connect to the path \\srvr49v\Deploy with the user $env:computername\svcUser for copying.System error 67 has occurred. 
> ##[debug] The network name cannot be found.
> ##[debug] 
> ##[debug]
> ##[debug]Leaving I:\Agent\NA-Cooperative-VSTS\_work\_tasks\WindowsMachineFileCopy_731004d4-1d66-4f70-8c05-638018b22210\2.0.3\WindowsMachineFileCopy.ps1.
> ##[debug]Caught exception from task script.
> ##[debug]Error record:
> ##[debug]Copying failed for resource : srvr49v\Deploy
> ##[debug]Failed to connect to the path \\srvr49v\Deploy with the user $env:computername\svcUser for copying.System error 67 has occurred. 
> ##[debug] The network name cannot be found.
> ##[debug] 
> ##[debug]
> ##[debug]    + CategoryInfo          : OperationStopped: (Copying failed ... be found.    
> ##[debug] 
> ##[debug]:String) [], RuntimeException
> ##[debug]    + FullyQualifiedErrorId : Copying failed for resource : srvr49v\Deploy    
> ##[debug]    Failed to connect to the path \\srvr49v\Deploy with the user $env:comp    utername\svcUser for copying.System error 67 has occurred. 
> ##[debug] The network name cannot be found.
> ##[debug] 
> ##[debug]
> ##[debug] 
> ##[debug]Script stack trace:
> ##[debug]at ThrowError, <No file>: line 45
> ##[debug]at <ScriptBlock>, <No file>: line 197
> ##[debug]Exception:
> ##[debug]System.Management.Automation.RemoteException: Copying failed for resource : srvr49v\Deploy
> ##[debug]Failed to connect to the path \\srvr49v\Deploy with the user $env:computername\svcUser for copying.System error 67 has occurred. 
> ##[debug] The network name cannot be found.

**Comment by chshrikh** [comment]
@jdshkolnik sorry for the inconvenience. Could you please share the full debug logs. 
You can mail it to RM_Customer_Queries at microsoft dot com

**Comment by jdshkolnik** [comment]
What else do you need? Have you tried setting up the scenario I described?

**Comment by chshrikh** [comment]
@jdshkolnik I am not able to get the target path "NA\2.1.1-beta.253+22_20180308.1_QA", where you want to copy the files. this should be a full path of target folder on your target machines - srvr49v\Deploy,srvr75v\Deploy like i:\Dest\NA\2.1.1-beta.253+22_20180308.1_QA or any local network existing share path like- \\NA\2.1.1-beta.253+22_20180308.1_QA.

**Comment by jdshkolnik** [comment]
@chshrikh I'm just using system variables: `$(System.TeamProject)\$(Release.ReleaseName)_$(Release.EnvironmentName)`

I provide two machine names comma-delimited (as specified above.) which resolve to:

srvr49v\Deploy\NA\2.1.1-beta.253+22_20180308.1_QA
srvr75v\Deploy\NA\2.1.1-beta.253+22_20180308.1_QA

To re-create this on your end, specify a remote machine where you create a local user account and then provide the credentials as I did: $env:computername\svcUser

**Comment by chshrikh** [comment]
@jdshkolnik I trying to reproduce at my end.

**Comment by rokmicrosoft** [comment]
@jdshkolnik  Can you please suggest suitable time and contact so we can arrange the call ?

**Comment by rokmicrosoft** [comment]
@jdshkolnik I am closing this one .If you still face any issue feel free to contact us or you can reopen this one.
