### ISSUE TITLE
AzureMysqlDeployment: use Agent.Tempdirectory instead of $env:temp

### ISSUE THREAD

**Issue by bishal-pdMSFT** [Microsoft/vsts-tasks#6661]
$env:temp can breach max path length constraint. it is better to use Agent.TempDirectory variable which is available in agent >= 2.115.0

**Comment by rokmicrosoft** [comment]
@bishal-pdMSFT  Are you talking about this [one ](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureMysqlDeployment/Window-MysqlCli-Installer.ps1#L30)  Agent is not installing mysql client but it need to be manually installed by user. So This is independent from agent and task.

**Comment by bishal-pdMSFT** [comment]
So, this script is not run in task? If so, you can close this issue

**Comment by rokmicrosoft** [comment]
It is not running in task. So I am closing this one.
