### ISSUE TITLE
Feature: Shell script (bash) pass arguments for inline script

### ISSUE THREAD

**Issue by dhanvi** [Microsoft/vsts-tasks#6662]
It would be a nice feature to be able to pass arguments to inline bash script, so that we can access the secret variables

**Comment by bryanmacfarlane** [comment]
inline script tasks support envvar blocks but you have to use yaml.  there's backlog work to add in the UI.  We moved away from encouraging cli args for secrets because in some OSes, cli invocations are logged.  v2 inline tasks encourage a more secure pattern.

eric can point to docs

**Comment by bryanmacfarlane** [comment]
https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-bash.md#environment-variables

**Comment by bryanmacfarlane** [comment]
answered above

**Comment by dhanvi** [comment]
@bryanmacfarlane can we please keep this issues open as backlog ? so that we can follow up the progress here.

My understanding is that yaml is only supported at the build level not at release side (please correct me if I am wrong)

**Comment by bryanmacfarlane** [comment]
That's a service issue (designer) and not a task issue but sure.  I'll will re-open and close when designer implements.  BTW, that's being worked on this sprint.

**Comment by ericsciple** [comment]
The envvar grid change for designer definitions is rolling out with the M135 deployment which will likely finish rolling out to all scale units by the end of next week.
