### ISSUE TITLE
Feature: Option to transform secret variables as plain text variables for a particular task 

### ISSUE THREAD

**Issue by dhanvi** [Microsoft/vsts-tasks#6663]
There are certain tasks where we can't pass the VSTS variables as arguments (the task doesn't support it) but it would be nice for the task be able to access secret variable.

**Comment by dhanvi** [comment]
@chrisrpatterson For example `docker stack deploy` we can't pass environment variables as arguments (https://github.com/docker/cli/issues/939) and would love to pass sensitive information via secrets. Currently we don't have a way to do the same.


As a work around I am using the below script to convert secret variables to plain text variables for the tasks

``` bash
#!/usr/bin/env bash
if (( "$#" < 2 )); then
 echo "Script is expecting minimum number of 2 arguments"
 exit 1
fi
echo "More than 2 arguments are present"
if (( "$#"%2 != 0 )); then
 echo "Script is expecting even number of arguments"
 exit 1
fi
echo "Even number of arguments are present"
args=("$@")
for (( i=0;i<$#;i+=2 ))
do
 echo ${args[$i]} ${args[$((i+1))]}
 echo "##vso[task.setvariable variable=${args[$i]}]${args[$((i+1))]}"
done
```

**Comment by chrisrpatterson** [comment]
I still don't understand what is going on here.  You can use $(VarName) even for secret variables in any task input.  Not sure how moving them to plain text changes that.

**Comment by bryanmacfarlane** [comment]
Please re-open if Chris' suggestion of using $(VarName) doesn't work

**Comment by dhanvi** [comment]
@chrisrpatterson  @bryanmacfarlane 

We heavily use `docker stack deploy` by giving it the docker-compose file (which contains which variables to use)
For example `docker stack deploy -c compose-file.yml` and the compose file looks as below
```
version: "3"
services:
  ubuntu:
    image: ubuntu
    environment:
      - SECRET=${SECRET}
      - NOT-SECRET=${NOT-SECRET}
    networks:
      default:
networks:
  default:
```



docker stack deploy doesn't uses lets us pass the environment variables as arguments https://github.com/docker/cli/issues/939 for example `docker stack deploy -c file.yml -e name=value`

Now how do I pass the secret variable to the Docker task ?

As a workaround I was creating a second plain text variable which has the same value as secret text variable and passing the plain text variable in the docker compose file. (Refer script above)

**Comment by dhanvi** [comment]
@chrisrpatterson @bryanmacfarlane could you please reply to my above comment
