### ISSUE TITLE
Visual Studio Test task against a testPlan failed to find MSTest V2 netcoreapp2 test associated to a Test Case

### ISSUE THREAD

**Issue by GregoryOtt** [Microsoft/vsts-tasks#6674]
Is it a supported scenario?

## Environment

- TFS on-premises, provide the version: 16.122.27409.2 (Tfs2018.Update1)
- Private agent: 2.129.0 with VS 2017 15.6.1 (Windows Server 2016 Std - 10.0.14393 N/A Build 14393)
- Visual Studio Test Agent Deployment: 2.1.23 / Visual Studio Tests: 2.1.14

### Context
- Deploying the Visual Studio Test Agent on the build agent through the VS Test Agent Deployment task.
- Running netcoreapp2.0 librairy tests through Visual Studio Test task pointing to a test plan/test suite.
- Referencing runsettings file below with TargetFrameworkersion
````
<RunSettings>
  <RunConfiguration>
    <TargetFrameworkersion>.NETCoreApp,Version=v2.0</TargetFrameworkersion>
    <TestAdaptersPaths>W:\Temp\XXXXTifTests\</TestAdaptersPaths>
  </RunConfiguration>
</RunSettings>
````
- Here is a screen shot of the build
![image](https://user-images.githubusercontent.com/4428998/37301986-7c3fd57a-262a-11e8-9218-07e47085522f.png)
- Here is the build definition in the Json format: [buildDefintion.txt](https://github.com/Microsoft/vsts-tasks/files/1804056/buildDefintion.txt)
- The `XXXX.XXXX.IntegrationTests.dll` contains a MSTest V2 extension of type [RFC 003](https://github.com/Microsoft/testfx-docs/blob/master/RFCs/003-Customize-Running-Tests.md#rfc-003--framework-extensibility-for-custom-test-execution) defined in `XXXX.XXXX.IntegrationTests.Core.TestCaseAssociationExtension.TestCaseTestMethodAttribute`
- The Test Case is associated with a unit test. To do so, I've used the PS snippet below
````
$sha1Crypto = new-object System.Security.Cryptography.SHA1CryptoServiceProvider
[Byte[]] $bytes = New-Object Byte[] 16
[Array]::Copy($sha1Crypto.ComputeHash([System.Text.Encoding]::Unicode.GetBytes($testName)), $bytes, $bytes.Length)
$automationGuid = New-Object -TypeName Guid -ArgumentList @(, $bytes)
$tp.CreateTmiTestImplementation($testName, $AUTOMATION_TYPE, $AUTOMATION_STORAGE_NAME, $automationGuid)
````
- Everything seems to be ok in the Test Case
![image](https://user-images.githubusercontent.com/4428998/37302908-22feea34-262d-11e8-9cb9-eb7a727c5db4.png)
- Test run successfully when using 'test assemblies'

### Expected behavior
Test is ran

### Actual behavior
No test found
> One or more errors occurred.--->No test assemblies found on the test machine matching the source filter criteria or no tests discovered matching test filter criteria. Verify that test assemblies are present on the machine and test filter criteria is correct`

### Error logs
[5_VsTest - testPlan.txt](https://github.com/Microsoft/vsts-tasks/files/1804045/5_VsTest.-.testPlan.txt)

**Comment by prawalagarwal** [comment]
@GregoryOtt  This is currently not supported scenario.
Test plan/Test suite and automated test cases association is available only for MsTest based tests.

Please use uservoice to request for new features/feedback. Thank you
`[This is currently not supported scenario.
Test plan/Test suite and automated test cases association is available only for MsTest based tests.

Please use uservoice to request for new features/feedback. Thank you
https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services](https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services)`

**Comment by GregoryOtt** [comment]
@prawalagarwal thx for the answer.
Could you please update the [documentation of the VSTest Task](/Microsoft/vsts-tasks/blob/master/Tasks/VsTest/README.md) to list explicitly supported/unsupported scenarios?

**Comment by prawalagarwal** [comment]
@GregoryOtt Sure we will raise the request with our team.
@PBoraMSFT
