### ISSUE TITLE
Unexpected behavior of Azure virtual application with VSTS Release pipeline

### ISSUE THREAD

**Issue by william726** [Microsoft/vsts-tasks#6679]
I set up a virtual application /sio for one of my Azure app service.
![image](https://user-images.githubusercontent.com/5792666/37347462-436b5bc4-26a8-11e8-8eb4-6e8c2434619b.png)

In the VSTS Release pipeline Azure App Service Deploy task, I fill the virtual application field with /sio, the same that I set in Azure.
![image](https://user-images.githubusercontent.com/5792666/37347704-d2afbea6-26a8-11e8-8e03-85af42c586b3.png)

I expect the sio.war file should be deployed to /site/wwwroot/webapps. After the release, however, it was deployed to /site/webapps/sio/sio.war.

I checked the deployment task log, it ran this command
`C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -verb:sync -source:contentPath='D:\a\r1\a\Sio-Rest-Release\drop\target\sio.war' -dest:contentPath='/site/webapps/sio/sio.war'`

I am curious why the dest:contentPath is /site/webapps/sio/sio.war, instead of /site/wwwroot/webapps.

**Comment by vincentdass** [comment]
@william726 , thanks for reporting the issue.
Currently, we are in process of redesigning the JAVA support. I am not sure about the JAVA support for Virtual application. 
The current design for JAVA is, given a `ANY_NAME.WAR` file, it is copied to `/site/wwwroot/webapps/ANY_NAME.WAR`. Though destination path is specified as `/site/webapps`, it is copied to `site/wwwroot/webapps`. Need to debug on this behavior.

If your end goal is to deploy `sio.war` to `/site/wwwroot/webapps`, you can skip the virtual application part.

**Comment by Ajay-MS** [comment]
@william726 

Are you unblocked on this issue with @vincentdass suggestion?

**Comment by william726** [comment]
@vincentdass @Ajay-MS 
Thanks for the suggestion! I have another questions. You mentioned `ANY_NAME.WAR` file will be copied to `/site/wwwroot/webapps/ANY_NAME.WAR`, how about ANOTHER.JAR file? Will it be copied to `/site/wwwroot/ANOTHER.JAR`?

Another question, I know VSTS Release pipeline Azure App Service Deploy task can only deploy one file at a time. Let say I would like to deploy five files to Azure, how can I optimize the release pipeline? I can think of two solutions.
1. Set up five Azure App Service Deploy tasks and each task deploys one file to Azure.
2. Zip all five files and deploy that zip file to Azure.

**Comment by vincentdass** [comment]
@william726 , 
Similar to `ANY_NAME.WAR` , `ANOTHER.JAR` will be copied to `site/wwwroot/webapps/ANOTHER.JAR` and not to `site/wwwroot/ANOTHER.JAR`.

Yes, you can deploy multiple WAR files using single / multiple tasks. your both solutions works in this case. 
For the second option, you might want to configure virtual application (physical path to `site/wwwroot/webapps`).

**Comment by vincentdass** [comment]
@william726 , Closing the issue as the above recommendation resolves the issue.
