### ISSUE TITLE
VSTS build using Hosted VS2017 cannot build Docker image

### ISSUE THREAD

**Issue by rsteenks** [Microsoft/vsts-tasks#6701]
We are running a build definition using then Hosted VS2017 agent queue. In one of the build steps a docker image is being build. Everything went well until March 6, but since March 7 this build step fails with the message: Failed which: Not found docker: null

It occurs to me that Docker isn't installed anymore in the image that is being used. To check this, I have added a buildstep to retrieve the PATH of the image which looks like this:

E:\vsts-agent-win7-x64-2.105.4\externals\vstsom;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\Administrator.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft Team Foundation Server 2015 Power Tools\;C:\Program Files\Microsoft\Web Platform Installer\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\dotnet\;E:\vsts-agent-win7-x64-2.105.4\bin;E:\vsts-agent-win7-x64-2.105.4\bin

and I cannot find a reference to Docker in it.

Thank you for all the help.

**Comment by jikuma** [comment]
Can you share your account name? I can see that Hosted VS2017 has docker installed on it. 
<accountname>.visualstudio.com

**Comment by rsteenks** [comment]
my accountname is: rsteenks@batenburgtechniek.onmicrosoft.com

**Comment by jikuma** [comment]
hey @rsteenks I was asking for your vsts account name accountname.**visualstudio.com**

**Comment by jikuma** [comment]
I verified that docker is installed in the VS2017 MMS image used in scale unit of hoogendoorn-growthmanagement.visualstudio.com.

**Comment by rsteenks** [comment]
Ok, I guess I've configured something wrong then. 

Can you explain how I can use the VS2017 MMS image in my build definition?

**Comment by jikuma** [comment]
@rsteenks can you verify once again that you are using Hosted VS2017 agent.

**Comment by rsteenks** [comment]
Hereby a screenshot:
![image](https://user-images.githubusercontent.com/6428689/37458208-961e7fa2-2844-11e8-9ce5-182cae78e766.png)

**Comment by jikuma** [comment]
Thanks @rsteenks for sharing the screenshot. We are looking into the issue

**Comment by bryanmacfarlane** [comment]
@jikuma investigating

**Comment by jikuma** [comment]
Hey @rsteenks can you try with a Build definition with only powershell task printing Path variable. Path value you specified is a lot different from what it should be. Especially presence of E folder in Path variable.

**Comment by rsteenks** [comment]
I've created a new build definition and the path looks like this:

C:\agents\2.129.1\externals\vstsom;C:\Program Files\dotnet;C:\mysql-5.7.21-winx64\bin;C:\Program Files\Java\jdk1.8.0_162\bin;C:\npm\prefix;C:\Go1.9.3\bin;C:\Program Files\Git\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\Scripts;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64;C:\Program Files\Microsoft MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\ProgramData\Chocolatey\bin;C:\Program Files\Docker;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\110\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\130\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\Git\cmd;C:\Program Files (x86)\Subversion\bin;C:\Program Files\nodejs\;C:\Program Files\CMake\bin;C:\Users\VssAdministrator\AppData\Local\Microsoft\WindowsApps

I can see that this looks different than the path from the failing build.

**Comment by rsteenks** [comment]
I 've created a new build definition from scratch and used the Hosted VS2017 agent queue and everything seems to work ok now.
It looks like that the failing build is using the wrong build agent somehow. I wil close this issue, because everything works for me, but it still looks like a bug tom me.
