### ISSUE TITLE
How to persist Variables created using task.setvariable command across environments or throughout the release

### ISSUE THREAD

**Issue by manjunath6681** [Microsoft/vsts-tasks#6702]
## Environment
TFs 2018 on prem

- Agent - Hosted or Private: 
private agent runs on windows 7

## Issue Description

I create custom variables using Write-Host "##vso[task.setvariable variable=sauce]crushed tomatoes" but this is available only in that environment where it is created and not in the subsequent environments.

how can i persist and use these variables throughout the release ? this is a must have feature for any tool to create variables with release scope.

thanks,
Manjunath

**Comment by bansalaseem** [comment]
You cannot pass variables using setvariable from 1 environment to another. But you can invoke RM rest APIs to update the release to set a variable from environment 1 and that variable should be available in environment 2 once the environment 2 starts. Here is a sample on how you can update a release and do let us know in case it does not work for you. 

https://blogs.msdn.microsoft.com/aseemb/2016/05/23/how-to-update-release-level-variables-using-rm-rest-apis/
