### ISSUE TITLE
Gulp  failed with error code 1

### ISSUE THREAD

**Issue by garfbradaz** [Microsoft/vsts-tasks#6722]
## Environment
- Server - TFS
    
    - Account Name: Dark Blue Sheep (https://dbsheep.visualstudio.com/)
    - Build Definition Name: MyPos Portal-ASP.NET Core-CI-Dev-Minifcation

- Agent - Hosted: 
    
    - Hosted 2017

## Issue Description

I'm trying to integrate **Gulp**  to minify and bundle our JS/CSS assets. I'm getting the following error though:

**2018-03-18T17:55:28.0821135Z ##[error]Gulp failed with error: C:\npm\prefix\gulp.cmd failed with return code: 1**

Now I have seen in a previous #3660 that this was reported, but I have tried the suggestions but to no avail. Am I missing something?

![image](https://user-images.githubusercontent.com/959766/37569383-7b90090c-2ad9-11e8-9dfd-1913b22eb3d2.png)

Here is the above config options:

### npm custom (install gulp)
![image](https://user-images.githubusercontent.com/959766/37569399-9b6a85cc-2ad9-11e8-86dc-191e5cd0dc05.png)

### npm custom (install gulp cli)
![image](https://user-images.githubusercontent.com/959766/37569415-ccd53f6c-2ad9-11e8-912d-e9091a99e36a.png)

### npm install
![image](https://user-images.githubusercontent.com/959766/37569425-ddb79bf4-2ad9-11e8-80fa-e20e6d005f59.png)

### Building & Minification (Where the error occurs)
![image](https://user-images.githubusercontent.com/959766/37569436-07d2146e-2ada-11e8-84a2-1908f49594ab.png)

### Error logs

Shows where it errors:

![image](https://user-images.githubusercontent.com/959766/37569438-1e34695a-2ada-11e8-84bc-5721e3f2384c.png)

Full Error Log:

```
2018-03-18T17:55:25.9110420Z [command]C:\npm\prefix\gulp.cmd --gulpfile D:\a\1\s\PosPortal.Web
2018-03-18T17:55:28.0581667Z [17:55:28] Local gulp not found in D:\a\1\s
2018-03-18T17:55:28.0582030Z [17:55:28] Try running: npm install gulp
2018-03-18T17:55:28.0821135Z ##[error]Gulp failed with error: C:\npm\prefix\gulp.cmd failed with return code: 1
2018-03-18T17:55:28.0846584Z ##[section]Finishing: Bundling & Minification
```

**Comment by bryanmacfarlane** [comment]
gulp is returning 1 (a failure).  The task just runs gulp (which runs your script).

**Comment by scottboehmer** [comment]
What is the file path for the gulp script file that you are trying to run? From the screenshots above, it appears that the gulp task is being given a directory rather than the file path in the Gulp File Path input.

**Comment by garfbradaz** [comment]
@bryanmacfarlane  / @scottboehmer 👍 

I was being an absolute ninny! Thank you! I changed the following:

![image](https://user-images.githubusercontent.com/959766/37679215-319abd60-2c78-11e8-9a23-068db2d3a03b.png)

- Changed the directory to point to the gulfile.js instead of just the directory it lived it.

- Also I changed the default taskname to "min" and forgot to reference that in the TFS build.

Sorry for wasting your time guys but thank you for a speedy reply.

**Comment by bryanmacfarlane** [comment]
np :)

**Comment by jameshowe** [comment]
I'm just all of a sudden started to hit this very same issue - the task was setup when I created from the Azure Portal as part of the Quick Start web app process and I've not edited anything on there.

Things I've tried that haven't helped:

- Rolled back the Node version from 10.15.3 to an earlier version of Node where the build worked
- Switched the agent from Hosted VS2017 to Hosted Ubuntu 1604
- Switched the version of the Gulp task from v0 to v1 (Preview)
- Disable "Publish to Azure Pipelines/TFS" option

I can run the command locally and the Gulp task runs fine with no errors. Things I've yet to try:

- Rollback the latest change in the repo (I can't see anything in particular that would break Gulp, and the fact it runs locally on master suggests it is something related to the Agent)
- Use my local machine as an Agent
