### ISSUE TITLE
Nuget Restore intermittently fails with Nuget 4.6.0

### ISSUE THREAD

**Issue by EP01** [Microsoft/vsts-tasks#6729]
## Environment
- Server - TFS on-premises
    
    - If using TFS on-premises, provide the version: 16.122.27409.2 (2018 Update 1)

- Agent - Private

    - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2012 R2 running Agent version 2.129.0

## Issue Description

We have a "Use Nuget 4.x" task in all of our build scripts. Since the release of Nuget 4.6.0 the Nuget Restore step has been intermittently failing with the following error:

```
2018-03-19T11:35:49.7745320Z Installed:
2018-03-19T11:35:49.7757972Z     156 package(s) to packages.config projects
2018-03-19T11:35:49.8229756Z ##[error]Error: C:\BuildAgent\Stable\Build_2.129.0_s1\_work\_tool\NuGet\4.6.0\x64\nuget.exe failed with return code: 1
2018-03-19T11:35:49.8230906Z ##[error]Packages failed to restore
```

The strange thing is that this is only happening for one of our projects, it may be to do with the amount of packages that this project uses, as the rest are significantly less. Also, sometimes it just works, if I just queue another build or two.

### Update

This may be an issue with the build agent or the specific project as I am now able to reproduce with Nuget 4.5.1. Also, using the current pre-release version of the agent (2.131.0) I have yet to see an occurrence.

### Update 2

Seen with pre-release agent as well.

**Comment by bryanmacfarlane** [comment]
The agent application has no notion of nuget and versions.  It's just running the task which just runs nuget.exe.  If you specify a nuget version, the task downloads nuget just in time.

This looks like a nuget issue

**Comment by keithrob** [comment]
@EP01,
Bryan is correct.  Once the task spawns nuget.exe all subsequent processing is generally handled by the exe, and is not functionally different than if you were to manually run the command yourself.  The only notable exceptions to this are push and restore operations which require auth.  For those, there is a small hook from the task to inject credentials into nuget.exe for those tasks.

I would recommend you open an issue on the nuget forum and explain the details of your project and which nuget.exe versions you have tried.
Keith

**Comment by EP01** [comment]
@keithrob 
Will do, thanks very much!
