### ISSUE TITLE
Install an Apple Certificate Task fails : Wrong default-keychain

### ISSUE THREAD

**Issue by Fizcko** [Microsoft/vsts-tasks#6732]
## Environment

TFS on-premises : TFS 2018 On-Premise (Version 16.122.27102.1)
Private agent : v2.129.0 on macOS High Sierra (10.13.3 Build 17D102)
Task Install Apple Certificate : 0.122.1

## Issue Description & Error logs

When use task "Install an Apple Certificate" on "Default Keychain" the task always fail  :

> [command]/usr/bin/security default-keychain
>      "/Library/Keychains/System.keychain"
> [command]/usr/bin/security unlock-keychain -p ********** /Library/Keychains/System.keychain
> The user name or passphrase you entered is not correct.
> [error]Error: /usr/bin/security failed with return code: 51

_**The password is correct, i even try with the root password -> same results.**_

In the logs the is a strange debug information :

> [command]/usr/bin/security default-keychain
> 	"/Library/Keychains/System.keychain"

But if i do the same command with the same user who is running the agent :

> tfsagent$ /usr/bin/security default-keychain
>     "/Users/tfsagent/Library/Keychains/iosbuild.keychain-DB-db"

If i try to use "Temporary Keychain" : 

> [command]/usr/bin/security list-keychain -d user
>     "/Library/Keychains/System.keychain"
> ##[debug]rc:0
> ##[debug]success:true
> ##[warning]Can\'t find loc string for key: TempKeychainSetupFailed
> ##[debug]Processed: ##vso[task.issue type=warning;]Can\'t find loc string for key: TempKeychainSetupFailed

If i try to use "Custom Keychain" : 

> [command]/usr/bin/security unlock-keychain -p ********** /Users/tfsagent/Library/Keychains/iosbuild.keychain-DB-db
> security: SecKeychainUnlock /Users/tfsagent/Library/Keychains/iosbuild.keychain-DB-db: The user name or passphrase you entered is not correct.
> ##[error]Error: /usr/bin/security failed with return code: 51

Is there something to do before use this task ?

My goal is to install certificate & Provisioning Profile to start an Xcode build.

Regards

**Comment by Fizcko** [comment]
Hi @hashtagchris. I found the solution.

It was a problem regarding the Mac agent service configuration.

I add to the .plist running by launchctl the following setting :

```
<key>SessionCreate</key>
<true/>
```
And now the default keystore is correct :

> [command]/usr/bin/security default-keychain
>      "/Users/tfsagent/Library/Keychains/iosbuild.keychain-DB-db"

**Comment by madhurig** [comment]
@Fizcko : Thanks for providing the update. If the agent service does not have permissions to setup or install in the keychains, the task will fail as you saw. I see the error messages were not showing up right. We will check that. 

Thanks,
Madhuri

**Comment by Fizcko** [comment]
@madhurig It'is not really a question of permissions because i didn't change anything about the rights of the user.

It's the normal comportment of a Mac service. But it should documented on the mac agent installation guide.

**Comment by Fizcko** [comment]
Anyway, the issue can be closed :)

**Comment by madhurig** [comment]
Thanks @Fizcko. We don't document how to setup mac services/daemon's but link to the macOS docs.
