### ISSUE TITLE
Github endpoint stop retrieving repositories

### ISSUE THREAD

**Issue by marceloavf** [Microsoft/vsts-tasks#6734]
## Environment
- Server - **VSTS**

## Issue Description
I was using GitHub endpoint to get token and list all repositories to the user, but since some days ago it stopped listing the repositories, the rest still works fine.

One solution to this should have a way to allow pick and write in this input type `pickList`, but I don't find any information about it.

![image](https://user-images.githubusercontent.com/5435657/37614940-ca4d106a-2b8a-11e8-951c-fed3c33d7710.png)

This is the code that list the repositories in the task.json:
```json
"inputs": [
    {
      "name": "githubEndpoint",
      "type": "connectedService:github",
      "label": "GitHub Connection",
      "defaultValue": "",
      "required": true,
      "helpMarkDown":
        "Select the service endpoint for your GitHub connection. <br>To create one, click the Manage link and create a new service endpoint."
    },
    {
      "name": "githubRepository",
      "type": "pickList",
      "label": "Repository",
      "defaultValue": "",
      "helpMarkDown":
        "Name of the GitHub repository. <br>If empty, it will be extracted from <strong>package.json</strong> (the repository.url field).",
      "properties": {
        "DisableManageLink": "True"
      }
    },
]
```
This is the part of the code that list the repositories, when I run it under Postman I get all repositories, but it's not working anymore inside VSTS
```json
"sourceDefinitions": [
    {
      "target": "githubRepository",
      "endpoint":
        "/$(system.teamProject)/_apis/sourceProviders/GitHub/repositories?serviceEndpointId=$(githubEndpoint)",
      "selector": "jsonpath:$.value[*].id",
      "keySelector": "jsonpath:$.value[*].id",
      "authKey": "tfs:teamfoundation"
    }
  ],
```

When I try to change selector to `jsonpath:$.repositories` it returns:
![image](https://user-images.githubusercontent.com/5435657/37617045-a49d6a8a-2b90-11e8-9f3a-3edc4050f572.png)

**Comment by GitHubSriramB** [comment]
@marceloavf 

Can you try using the following?
"selector": "jsonpath:$.repositories[*].name"
"keySelector": "jsonpath:$.repositories[*].id"

Not sure if the sourceProviders/GitHub/repositories API previously was returning different value. @madhurig?

Also, dataSourceBindings is preferred over sourceDefinitions. We will not be enhancing sourceDefinitions & but it will be supported for compat reasons.

This blog should clarify how dataSourceBindings is used:
https://blogs.msdn.microsoft.com/sriramb/2016/09/15/service-endpoints-data-sources/

**Comment by lkillgore** [comment]
Hi @marceloavf and @GitHubSriramB!

I apologize for the inconvenience; we did recently change what is returned by this call.  The updated API documentation is [here](https://docs.microsoft.com/en-us/rest/api/vsts/build/source%20providers/list%20repositories#sourcerepository).  The new API returns [SourceRepositories](https://docs.microsoft.com/en-us/rest/api/vsts/build/source%20providers/list%20repositories#sourcerepositories) with the original API's results in the `repositories` field in the `SourceRepositories`.

So, to get the same behavior you should change your selector to look something like this:
```
"selector": "jsonpath:$.repositories.value[*].name"
"keySelector": "jsonpath:$.repositories.value[*].id"
```

This API is currently in preview, and we realized that we needed to make some adjustments some of which may be relevant to you.  Firstly, for users who have access to many repositories the call to this method can take 20-30 seconds to retrieve all the values, so we added support for paging.  Additionally, as we cap the repositories returned to 2000, paging support allows integrators to get the total result.  And, you may also notice the addition of `resultSet` in the API, which limits the results to the repositories most relevant to the current user.

Again, I apologize for any inconvenience, and please let me know if you need any further help.

Thanks!

**Comment by elranu** [comment]
Hi,
     @lkillgore  I'm having the same issue to list branches. Can you tell me please the `selector` and the `keyselector` I should use to list branches. I do not find the doc here: https://docs.microsoft.com/en-us/rest/api/azure/devops/build/source%20providers/list%20branches?view=azure-devops-rest-5.0

Thanks in advanced
