### ISSUE TITLE
Firewall Rules for 'Publish Test Results' task

### ISSUE THREAD

**Issue by GavinAlb** [Microsoft/vsts-tasks#6743]
## Environment
VSTS Online

- Agent
Private Agent
Version: vsts-agent-win-x64-2.126.0
OS: Windows server 2016

## Issue Description
We are having trouble running the 'Publish Test Results' tasks under version 1.* and 2.*. Both are coming up with the same error '##[warning]Failed to publish test results: The underlying connection was closed: An unexpected error occurred on a send.'

We run a very restricted corporate firewall here at our business . All external access needs to be specified, else it is denied. 
I've ran this using my machine at home (which does not have a firewall) and the process works perfectly.

Can I please have the list of firewall targets required to upload VSTS test results. Using the microsoft documentation lists the following, which we have exposed and are able to download artifacts and run the agents on-prem without issue (This is how we are running our on-prem deployments).

## Current exposed firewall rules
https://{account}.visualstudio.com
https://{account}.vsrm.visualstudio.com
https://{account}.pkgs.visualstudio.com
https://{account}.vssps.visualstudio.com
https://login.microsoftonline.com
https://app.vssps.visualstudio.com 
https://vstsagentpackage.azureedge.net

This is based on the documentation at:
https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/_shared/v2/qa-firewall
https://docs.microsoft.com/en-us/vsts/build-release/actions/agents/v2-windows#im-running-a-firewall-and-my-code-is-in-vsts-what-urls-does-the-agent-need-to-communicate-with

### Error logs

2018-03-20T05:47:49.0098428Z Preparing task execution handler.
2018-03-20T05:47:49.4561882Z Executing the powershell script: C:\vsts\agent\_work\_tasks\PublishTestResults_0b0f01ed-7dde-43ff-9cbb-e48954daf9b1\1.0.36\PublishTestResults.ps1
2018-03-20T05:47:49.7943974Z Publishing Test Results...
2018-03-20T05:48:33.9509541Z ##[warning]Failed to publish test results: The underlying connection was closed: An unexpected error occurred on a send.
2018-03-20T05:48:33.9672667Z ##[section]Finishing: Publish Test Results "$(System.DefaultWorkingDirectory)\*.xml"

**Comment by madhurig** [comment]
Are you able to publish test results using the "VSTest" task?

**Comment by GavinAlb** [comment]
Hi Madhurig,

I'm unable to test that as I am unable to run the full VS install on the host to satisfy the vstest requirement, we are using VSTS cloud for that. This use case is running postman API tests which publish the result as a junit file, then the publish result step is meant to upload the result. (Again, this works fine without the firewall in the way).

I ran a wireshark trace on it and found the address 168.62.105.45 which resolves to 'app.vsaex.visualstudio.com'. This url isnt documented anywhere as a firewall requirement. We added this to our exception list and its still not working.

**Comment by madhurig** [comment]
@GavinAlb: Please send us the diagnostic logs from the build agent along with debug logs from your build.   You can email them to me if you don't want to post here: madhurig at microsoft dot com.

This issue doesn't seem specific to this task. I would expect this to happen with any agent communication up to the server e.g. publishing build artifacts as well.

Thanks,
Madhuri

**Comment by GavinAlb** [comment]
Hi Madhurig,

I believe I've found the issue, but it looks to be highlighting an inconsistency issue in the way VSTS process's the upload task in the Release pipeline vs the Build pipeline. 

We have been running this via the Release pipeline and not the Build pipeline do to the need for us to run API tests on an internal system, once we generate the artifact in the build phase we then deploy to an internal system and run our API tests over that, this is all in the Release phase. 

The release pipeline does not have the option to run with diagnostics like the build pipeline does. I setup a quick pipeline in the 'Build' section in order to fetch these diagnostics for you and the process worked without issue. VSTS was able to successfully upload my results file. 

I then re-ran the process via the 'Release' section and it failed.  Using your documentation at https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting?view=vsts I was able to turn on diagnostic information in the release pipeline, I then looked through the logs in the private agent directory and found the below error which would perfectly explain why this process is resulting in the connection closed error (our firewall is blocking the attempt).

**_Error_**
{ Exception = System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The connection with the server was terminated abnormally
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.RendezvousAwaitable`1.GetResult()
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext()
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.DiagnosticsHandler.<SendAsync>d__2.MoveNext(), Request = Method: GET, RequestUri: 'https://tfsprodeausu7.visualstudio.com/A06f6033e-d0c5-41de-892b-b010b7fdd5f9/_apis/connectionData?connectOptions=1&lastChangeId=-1&lastChangeId64=-1', Version: 1.1, Content: <null>, Headers:

This highlights that the url 'https://tfsprodeausu7.visualstudio.com' is being used but this is not within your documentation for firewall requirements in on-prem environments.

Given that this url has a 7 in it, I can only assume that this is some kind of dynamic url based on load presumably talking to the Azure Datacenter in APAC.

Can you please clarify if this is the only url that is being used, and that I can add this url into my firewall to allow the process to continue, or is this url dynamic and changing, thereby not feesable to add to our firewall.

Thanks for the assistance so far. Hopefully this will be the last piece of the puzzle.

Also, as requested I've emailed you our log files to assist.

**Comment by madhurig** [comment]
@GavinAlb: Glad you found the issue and have it working. The url 'https://tfsprodeausu7.visualstudio.com' is not a dynamic URL and is not likely to change for your account. I am not sure if there is a documented list of all URLs in the service that you can whitelist or if that is even possible since we deploy to new datacenters and new services regularly. We generally whitelist *.visualstudio.com. You can file a ticket here: https://www.visualstudio.com/team-services/support/ if you want to follow up further on it. 

@stephenmichaelf and @bryanmacfarlane for feedback on run with diagnostics. This is a new feature we are starting out with Build. Good to hear it worked well there. We will note the request to make it available in Release. 

Thanks,
Madhuri

**Comment by GavinAlb** [comment]
We have added 'https://tfsprodeausu7.visualstudio.com/' to our firewall and have successfully processed a test result.

Closing issue.
