### ISSUE TITLE
service fabric task should show more detailed information during upgrade

### ISSUE THREAD

**Issue by bishal-pdMSFT** [Microsoft/vsts-tasks#6755]
Currently we only show status:
`2018-03-21T02:28:02.3386067Z Waiting for upgrade...

2018-03-21T02:28:05.3678345Z Waiting for upgrade...

2018-03-21T02:28:08.3979253Z Waiting for upgrade...

2018-03-21T02:28:11.4302030Z Unregistering other unused versions for the application type...

2018-03-21T02:28:12.1372526Z ##[error]Upgrade was rolled back.
`
It should show more details about UD completed/remaining, unhealthy evaluations etc. 
Evaluate what should be shown and cross-check with SF team

**Comment by bishal-pdMSFT** [comment]
@Tadimsky we are working on this currently. Expect it to start rolling out to prod next week. Do you need this on priority?

**Comment by Tadimsky** [comment]
@bishal-pdMSFT this is great news! looking forward to the improvements. Not super urgent but would be nice to have soon as it makes VSTS much more useful.

**Comment by kuvinodms** [comment]
This fix should roll out in next few days for all the customers
