### ISSUE TITLE
Function App deployment should default to webdeploy

### ISSUE THREAD

**Issue by paulbatum** [Microsoft/vsts-tasks#6759]
Hi there, I work on Azure Functions. I would like to propose that when a user selects an app type of `Function App`, webdeploy should be the default deployment method.

![image](https://user-images.githubusercontent.com/10663/37724169-65f1572a-2ced-11e8-8ac6-d25a752a2f65.png)

The main reason for this is that zip based deployment does not put a consumption function app into a consistent state. An action is required to "sync triggers", and if this is not done then the app will not scale properly. When deploying through webdeploy, this step happens automatically.

See here for an example of a customer running into this issue:
https://github.com/Azure/azure-functions-host/issues/2499#issuecomment-374880833

Bonus points for:
1. If the user opts out of webdeploy, ideally the task would manually call sync triggers. This would be useful in cases where the agent is linux based and webdeploy cannot be used. This action is documented [here](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/syncfunctiontriggers). Here is a quick example of the sync triggers action being called:
https://github.com/davidebbo/AzureWebsitesSamples/blob/61c7b330e83750cd4092625d082340d69f3a54ec/PowerShell/HelperFunctions.ps1#L362-L367
2. Defaulting to `Remove additional files at destination` to enabled. This way, if a user deletes the code for a function from their function app which is deployed through this task, the function will actually be deleted, which is probably what they intended.

**Comment by davidebbo** [comment]
I know there is a lot of confusion around this, but the best thing you should be using is the [zipdeploy API](https://blogs.msdn.microsoft.com/appserviceteam/2017/10/16/zip-push-deployment-for-web-apps-functions-and-webjobs/).

As for Consumption Linux, it doesn't support any of those (zip, zipdeploy, WebDeploy), so we'll need to come up with alternative (mostly a different discussion).

**Comment by paulbatum** [comment]
David just explained this to me, and I now agree with him. I think instead of making webdeploy the default, it would make more sense for the "zip" based default to use the "zipdeploy" API he linked. 

@kmkumaran @vincentdass is there already a issue tracking switching over to the "zipdeploy" API? If so we can probably close this..

**Comment by RoopeshNair** [comment]
zipdeploy support is in progress.

**Comment by Ruud-cb** [comment]
I come here from https://github.com/Azure/azure-functions-host/issues/2697 where I am a bit confused if I should use zipdeploy or webdeploy now? It has already been 2 years ago but currently still experiencing issues that are described in the referenced issue.

**Comment by kdubau** [comment]
Agreed with @Ruud-cb .. still having this issue and the documentation is unclear.
