### ISSUE TITLE
Cloud Load Test behind Firewall

### ISSUE THREAD

**Issue by smadala** [Microsoft/vsts-tasks#6772]
_From @lloydmonteiro on March 22, 2018 7:11_

## Description
I followed this article https://blogs.msdn.microsoft.com/devops/2016/08/22/use-cloud-load-agents-on-your-infrastructure/ and successfully am able to run Load Tests using Cloud on my own machines behind Firewall. It is running fine on VisualStudio and VSTS Portal

Now I want this to also run using VSTS Release TASK and to that end I add the Cloud Load Test task. I also installed the AzurePS on the VM which initially vsts was complaining that deployment group is not provisioned.

## Steps to reproduce
I am not able to understand how the CLT in Release Pipeline mode works with "Self-Provisioned Agents" or use my RIG as I don't see an option anywhere to do that?

## Expected behavior
Option to set the "Load test rig" 

## Actual behavior
Don't know how to run CLT using Self provisioned Rig in release pipeline. Can you confirm is this supported in release pipeline? 
It is supported from VSTS IDE and VSTS Portal, however in release pipeline, CLT task??

_Copied from original issue: Microsoft/vstest#1492_

**Comment by ShreyasRmsft** [comment]
@lloydmonteiro you can provide the details of the self provisioned rig in the load test file in Visual Studio

 Check the Using Visual Studio Enterprise IDE 
 section of the following link https://blogs.msdn.microsoft.com/devops/2016/08/22/use-cloud-load-agents-on-your-infrastructure/ 

Currently this can only be done via the IDE and the provision for this is missing in the task UI.

**Comment by ShreyasRmsft** [comment]
@lloydmonteiro closing the issue. Please re-open if this doesn't work or if you need additional assistance.

**Comment by lloydmonteiro** [comment]
when would this feature be available then?

**Comment by ShreyasRmsft** [comment]
Looping in @PBoraMSFT for queries on feature availability.

**Comment by ShreyasRmsft** [comment]
@lloydmonteiro you can create the load test file from Visual Studio IDE then use the same load test file in the Task. It should pick up the private rig. The provision for specifying the rig is not available in the task UI but you can still run the load test from the task using the private rig but you just have to author/modify your load test file in the IDE. Hope I made it clearer.

**Comment by lloydmonteiro** [comment]
so use the same CLoud Load Task but author and modify load test in IDE. Let me try it out and get back to you.
