### ISSUE TITLE
Selective artifact download bug

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-tasks#6775]
## Environment
- Server - VSTS
- Agent - Hosted

## Issue Description

I think there is a bug with the selective artifact downloads.

I have a release definition which has 10 artifacts.  9 of them come from builds in VSTS.  1 of them comes from an on-premise TFS build.  We are using the **TFS Artifacts for Release Management** addon to get this to work (https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.vss-services-externaltfs).

I have multiple phases in one of my environment definitions.  I do not want the on-premise artifact to be downloaded in this phase.  When I go into the phase properties and then into the "Artifact Download" section, unselecting the specific artifact does not stop it from being downloaded.

This only seems to be an issue with the "External TFS" artifact.  Unchecking the other artifacts appears to work as expected.

Furthermore, the "Skip artifact download" checkbox appears to have been removed, so I am stuck now.

I really hope this makes sense.

**Comment by lovakumar** [comment]
Hi Greg,

We just verified this scenario on our local deployment and it works as expected. Can you please share your VSTS account and release definition name so that we can take a look at it in the back end to see what's causing this issue.

**Comment by gregpakes** [comment]
@lovakumar

vsts account is “iSAMS”.  There is only one release in the project called iSAMS. It should be obvious.

**Comment by lovakumar** [comment]
@gregpakes I just saw your release definition named iSAMS and found that all of the artifacts linked to the release definition are of type Build. I could not find any custom/external tfs artifact. I see "Download Artifacts - External Build" named task in one of the phase. If you are looking for a way to skip this artifact, first add this external tfs build as artifact source to release definition and then you would be able to select/unselect in phase properties. Post that you can remove "Download Artifacts - External Build" task completely.

If I am looking at a latest release definition copy which don't have the changes you mentioned above then give us the release id for behavior was not as expected.

**Comment by gregpakes** [comment]
@lovakumar 

Apologies - I removed it whilst fiddling.  I'll put it back into a reproducible state and will let you know.

**Comment by gregpakes** [comment]
@lovakumar 

I have put it back - It doesn't work again.

**Comment by lovakumar** [comment]
@gregpakes We have identified the issue and coming up with a fix. Will let you know once the fix is rolled out for you.

**Comment by lovakumar** [comment]
@gregpakes We have enabled a feature (on isams) to download external tfs artifact using task (instead of agent plugin). This should mitigate the issue that you were facing. Can you please re-try your configuration and let us know if that solves the problem.

**Comment by gregpakes** [comment]
@lovakumar 

I have tested this.  Works perfectly!

Fantastic service!
