### ISSUE TITLE
Service fabric deploy task 'Create-DiffPackage' include unapproved verbs 

### ISSUE THREAD

**Issue by xingyu217** [Microsoft/vsts-tasks#6778]
With Service fabric application deployment task, it has the warning:

> ##[warning]The names of some imported commands from the module 'Create-DiffPackage' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
> 2018-01-31T19:40:27.4353187Z ##[debug]Processed: ##vso[task.logissue type=warning]The names of some imported commands from the module 'Create-DiffPackage' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.

It's better to deal with this warning.

**Comment by bishal-pdMSFT** [comment]
@BinWuMSFT can you please take care of this.

**Comment by kuvinodms** [comment]
@bishal-pdMSFT 
Fix has been merged with master
