### ISSUE TITLE
Deployment Gate doesn't evaluate/exapand Variable 

### ISSUE THREAD

**Issue by rmarinho** [Microsoft/vsts-tasks#6782]
## Environment
- Server - VSTS
  - devdiv account  
 - https://devdiv.visualstudio.com/DevDiv/Xamarin%20Forms/_apps/hub/ms.vss-releaseManagement-web.hub-explorer?releaseId=87244&definitionId=567&_a=release-logs

- Agent - Hosted or Private: 
    
    - Hosted

## Issue Description

I m using the Gates feature to check a REST endpoint value. My issue is when the gate is calling the rest endpoint it doesn't replace/evaluate my variable.
On  the field "Url suffix and parameters" I set `XamarinForms/Xamarin.Forms.ControlGallery.iOS/test_runs/$(AppCenterTestRunId)/state` where I hope *AppCenterTestRunId* is a Guid that is set in a previous task that runs on my environment.

The thing is when the Gate is evaluated my variable is still empty. I can confirm that my variable was set on my task, because I print the variables after (and before the post deployment gate) and I see that 
AppCenterTestRunId has a new guid. But when it evaluates I only get this:

```
2018-03-23T11:52:35.7529542Z GET https://api.appcenter.ms/v0.1/apps/XamarinForms/Xamarin.Forms.ControlGallery.iOS/test_runs//state
				Response Code: 0
				Response: An error was encountered while processing request. Exception: 
```
[Include task name(s), screenshots and any other relevant details]

Rest API task on Pre and Post deployment gates

I also tried this by running after my environment as post deployment gate, and in my next environment on the pipeline as a pre deployment gate but I had the same issue. 

### Error logs

2018-03-23T11:52:35.7529542Z GET https://api.appcenter.ms/v0.1/apps/XamarinForms/Xamarin.Forms.ControlGallery.iOS/test_runs//state
				Response Code: 0
				Response: An error was encountered while processing request. Exception: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /v0.1/apps/XamarinForms/Xamarin.Forms.ControlGallery.iOS/test_runs//state</pre>
</body>
</html>

Exception Message: The remote server returned an error: (404) Not Found. (type WebException)
				Evaluation of expression 'or(eq(root['exit_code'], 0), eq(root['exit_code'], 1))' failed.

**Comment by rmarinho** [comment]
I have tried used the same approach just with the Rest API task in a agenteless phase and have the same issue.

**Comment by vithati** [comment]
Output varaibles across phases and environments are not supported presently. And server task and gates does not support output varaibles with in phase also. Because of this previous task vairables are not replaced in present task.

**Comment by rmarinho** [comment]
Why was it closed? I know it's not supported but should be something to implement ?

**Comment by vithati** [comment]
Server task output variable support is in backlog. Output variable support outside of evnironment i will discuss with PM.

**Comment by bryanmacfarlane** [comment]
Also note that the issues in this repo are for tracking bugs in the tasks (in this repo - /Tasks).  For service feature asks, developer community is also a good place.
