### ISSUE TITLE
Definitive guide for node API access

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-tasks#6793]
Is there a definitive guide for connecting to the VSTS API in a build/release task.

I have looked at a bunch of tasks in github and they all seem to do it differently.

For example:

- Tasks in this repo seem to use the variable **SYSTEMVSSCONNECTION**
- Other private repos seem to use **SYSTEM.ACCESSTOKEN**, which requires the "Allow scripts to access OAuth token" to be enabled.
- Others seem to make direct HTTP calls to the endpoints and builds everything up manually.

Am I right in thinking that the **SYSTEMVSSCONNECTION** is only available to tasks in this repo?  If we are writing our own tasks, we need to use the **SYSTEM.ACCESSTOKEN** option?

Is there a definitive guide for this?  I have looked and looked, but can't find anything.

**Comment by bryanmacfarlane** [comment]
not an issue with task in this repo.  seems like an issue for vsts-task-lib

**Comment by gregpakes** [comment]
It would still be nice to know why you have chosen to use **SYSTEMVSSCONNECTION** in this repo, rather than **SYSTEM.ACCESSTOKEN**.  You must have some insight on that.

**Comment by bryanmacfarlane** [comment]
vsts-task-lib is the repo for that.  This repo is for the in the box tasks (/Tasks)
