### ISSUE TITLE
VsTest running coded ui tests throws file not found exception

### ISSUE THREAD

**Issue by acm74** [Microsoft/vsts-tasks#6807]
I am running VsTest task as part of a VSTS release definition.  When starting execution of a coded ui test, qtagent32_40.exe will attempt to load dependent assemblies and fail (throwing the file not found exception).  

Enabling fusion logging shows that the appbase for qtagent32_40.exe has been set to a different directory (a temp directory), and the required files (e.g. UiaComWrapper.dll) are in the same directory as qtagent32_40.exe but are no longer accessible.
![cuit_filenotfound](https://user-images.githubusercontent.com/36503947/37956731-705877fc-31ac-11e8-8926-1baea122490e.PNG)

**Comment by acesiddhu** [comment]
@acm74 looks like you coded ui test project is build with VS 2015 and you are using vs test platform tools installer. you need to build the coded ui test project with VS 2017 instead for vstest platform tools to work.

**Comment by acm74** [comment]
@acesiddhu thanks for the quick reply.  I will produce a new vs2017 build and test again.

**Comment by acm74** [comment]
@acesiddhu I have a test run that has been going for over an hour now - it looks like things are working now.  Thanks very much for your help.
