### ISSUE TITLE
Custom Task & Inline Code Annotations

### ISSUE THREAD

**Issue by sheldonhull** [Microsoft/vsts-tasks#6817]
## Environment
- Server - VSTS or TFS on-premises?
    - If using TFS on-premises, provide the version: 
    Version 15.117.26615.0

- Agent - Hosted or Private: 
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Windows 2016 , agent version 2.124.0

## Issue Description
This question might need to be in a different repo, if so please point me towards it since it's a mix of task + tfs schema question. 

I've got a build task that runs a code analysis task that provides me back xml with file, line, and offset coordinates of a matched issue from the triggering changeset. I was thinking that it would be awesome if I could have those issues inserted into the Code Comments (web based) in TFS so that inline code annotations would show up on the changeset from the build agent on flagged issues and thus could be easily reviewed, commented/resolved, etc. 

So far, no luck on finding anyway to reference the associated file and the coordinates in the file when I've reviewed `CodeReview.tbl_Discussion` or the associated tables. 

Do you have any points or a better resource I should point this towards if not appropriate in the custom task area?

**Comment by bryanmacfarlane** [comment]
not an issue with the /tasks in this repo.  reactivate and specify the task
