### ISSUE TITLE
VSTS not detecting updated custom task using --rev-version

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-tasks#6818]
I feel like this should be simple, but I'm struggling.

- I am writing a custom release task.  
- I have published (privately) to the marketplace and shared with my vsts account.
- I have used the task in a release pipeline.
- I then go and make a change to the task and re-package it.  I use the --rev-version parameter and it correctly revs the 3rd part of the version number for the extension.
- I then update the extension in the marketplace, through the web interface.

This all works fine (the marketplace verifies and accepts the updated extension).  But the task within the extension that is available to me within my VSTS instance is not updating.

Am I doing something wrong?  How do I get it to use the updated task?

I have tried removing the task from the pipleline and re-adding it.  I have hit the "refresh" button above the task list.  I have tried creating a new release.  Everything still uses the old task.

The only way I can get this to work is to uninstall the extension and then reinstall it.

**Update** - Even uninstalling and reinstalling the extension does not always work either.

**Comment by gregpakes** [comment]
It seems that the version for the task needs to be incremented as well for this to work.

I was totally unable to find this in the documentation and the inclusion of "--rev-version" only goes to further this confusion.

**Comment by bryanmacfarlane** [comment]
Yes, an extension can carry multiple build tasks, each having their own version.

It's covered in the last section in the step by step on creating tasks:
https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/stepbystep.md#publish-install-publish

**Comment by bryanmacfarlane** [comment]
Closing since this repo is for issues with the /Tasks in this repo.  the vsts-task-lib repo has the lib and info on writing tasks.  If there's more clarification needed, issues there is good.
