### ISSUE TITLE
CopyFilesOverSSH to Win32-OpenSSH errors

### ISSUE THREAD

**Issue by kuzkok** [Microsoft/vsts-tasks#6826]
## Environment
- Server - TFS on-premises 2017 15.112.26307.0
- Agent - Private WinServer 2k8r2 2.124.0    

## Issue Description

On remote Windows Server installed [Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH) version 7.6

1. Not work checkbox "Clean target folder" such as run command "rm -rf *" that not present on windows
2. After copy all files failed with error "read ECONNRESET", but other ssh copy software works properly (<https://github.com/PowerShell/Win32-OpenSSH/issues/1064>)

#### 1
[error]Не удалось очистить целевую папку на удаленном компьютере. Выход из команды rm -rf "C:\Distr\prod"/* с кодом 1.
[error]Не обработано: read ECONNRESET
#### 2
Завершено копирование файлов на удаленный компьютер (скопировано файлов: 786).
[error]Не обработано: read ECONNRESET

**Comment by yacaovsnc** [comment]
Do you have sufficient permission to delete contents from `C:\Distr\prod`?  

Can you please attach your build log with `system.debug` set to true?

**Comment by kuzkok** [comment]
Yes user that connected have persmission for delete from this folder. Reason for first error is not permission - it is windows machine, Win32-OpenSSH default shell is "cmd.exe" it know nothing about rm command.

![default](https://user-images.githubusercontent.com/829195/38148189-d56f6c62-346e-11e8-80a0-9a922948f10b.png)


[debug.log](https://github.com/Microsoft/vsts-tasks/files/1864363/debug.log)

**Comment by kuzkok** [comment]
As a proposal for delete issue may be checkbox "Override clean command" and textbox for it

![default](https://user-images.githubusercontent.com/829195/38148677-e84e6d72-3470-11e8-83e6-68f8253a16b7.png)

**Comment by brcrista** [comment]
I don't think we need to change the task.  If you want to clean the target directory, just use a separate SSH command to run the command line you want.

SSH / SCP is more traditionally used in the Linux world.  If you are copying files to a Windows machine, I would recommend a [different task](https://docs.microsoft.com/en-us/vsts/build-release/tasks/deploy/windows-machine-file-copy?view=vsts).

**Comment by kuzkok** [comment]
What about second error?

**Comment by brcrista** [comment]
From the link you posted that looks like it may be a common issue when trying to copy to an Win32-OpenSSH target.  However, this task was written and tested for macOS and Linux.  That was a documentation bug and I've submitted a fix for our docs.  Can you use this task to copy the files to your Windows machine?  https://docs.microsoft.com/en-us/vsts/build-release/tasks/deploy/windows-machine-file-copy?view=vsts

**Comment by kuzkok** [comment]
It is issue with vsts-task to Win32-OpenSSH, other SCP over SSH software works properly(Filezilla, I check for bitviseSSH). 
I can use suggested task, but I have some target machines with different OS'es (windows, linux) and want to have similar steps in release definition for all.
