### ISSUE TITLE
Deploy to Kubernetes creates ACR secret in wrong namespace

### ISSUE THREAD

**Issue by tlycken** [Microsoft/vsts-tasks#6827]
When supplying a namespace other than `default` (e.g. `test`) for the deployment of a k8s service to AKS, the subsequent deploy fails, because the secret used to pull images is still created in the `default` namespace, and thus not available for the newly deployed service to use when pulling images.

**Comment by Anumita** [comment]
This was a feature request recently and we have already made the fix. The fix will be available in a few weeks. 
If you are unable to wait for a few weeks and would like to know an alternative to create the secret in a namespace other than the default, do let us know.

**Comment by tlycken** [comment]
@Anumita Thanks! Did an issue search but couldn't find anything about this, so great to know it's coming :) In the meantime, I created the secret manually in the correct namespace using `kubectl`.

**Comment by bansalaseem** [comment]
@tlycken there is no issue for it in GitHub but you can search for PRs and will know that the feature is there.
