### ISSUE TITLE
Artifact Publishing very slow

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-tasks#6830]
> I have published this over here too, I'll delete whichever one is not appropriate.
> https://github.com/Microsoft/vsts-agent/issues/1480

I am using VSTS with the hosted agent.

Artifact publishing is very slow.  Cloning the repo, which is much larger than the artifacts that need publishing takes about 3-4 mins.  Publishing the artifacts is taking **23 minutes**.

Here are the details:

- 23k files in the final artifacts that need publishing
- I've seen that people suggest zipping it up, then publishing.  We have tried this before, but the zipping process takes longer than the publishing.  Then I also need to unzip them in the release process.
- I am publishing to the Server, not to a file share.
- I am using a hosted agent.

I've read on some forums that it takes a long time because it only does 4 files at a time.  

Is there any way to speed this up?

**Comment by gregpakes** [comment]
I've figured a decent work around for this.  The publish now takes 28 seconds.

I use the following task [Artifact Compressor](https://marketplace.visualstudio.com/items?itemName=roshkovski.2B9619D5-7BE9-4ED7-BF10-707CB17F657A) which allows you to create a zip file with **no compression**.  This obviously solves the problem described above where the compression takes too long.

Publishing the single zip archive is much faster.

This has taken 30 mins off my build time, halving it!

**Comment by bryanmacfarlane** [comment]
Closing this one since tracking the other one

**Comment by xyz92** [comment]
@gregpakes I'm facing the same issue in my build. So, can we get rid of publish artifacts step from the build and use articats compressor step instead? Please let me know.

**Comment by gregpakes** [comment]
@xyz92 The solution is over here: https://github.com/microsoft/azure-pipelines-agent/issues/1480

**Comment by xyz92** [comment]
thank you @gregpakes
