### ISSUE TITLE
LinkAssemblies task failed unexpectedly issue

### ISSUE THREAD

**Issue by anobik** [Microsoft/vsts-tasks#6834]
Hi,

I have been googling around with the issue for quite some time but no success.

The current error says:

Severity	Code	Description	Project	File	Line	Suppression State
Error		The "LinkAssemblies" task failed unexpectedly.
Mono.Linker.MarkException: Error processing method: 'System.Linq.ParallelQuery`1<TCastTo> System.Linq.ParallelQuery::Cast()' in assembly: 'System.Core.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Void System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute::.ctor()
   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
   at Mono.Linker.Steps.MarkStep.MarkCustomAttribute(CustomAttribute ca)
   at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessEntireQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()

OS: Windows Server 2012 R2

VS Version:
![image](https://user-images.githubusercontent.com/3693669/38087470-d7f9b11c-3375-11e8-8cfa-c9fc13e9f9a0.png)

Android Version:

![image](https://user-images.githubusercontent.com/3693669/38087597-50f5725e-3376-11e8-9b4a-01e29b665976.png)

**Comment by madhurig** [comment]
@anobik: You are getting this error in Visual Studio. This is not related to VSTS tasks or the Hosted build VMs. Please search for resolution in https://bugzilla.xamarin.com/ or https://forums.xamarin.com/categories/visual-studio

Thanks,
Madhuri

**Comment by anobik** [comment]
@madhurig  I'll be sharing error screen shots from VSTS task / hosted build also. Please reopen the issue.

Both of the places issue is coming.

Thanks,
Anobik

**Comment by madhurig** [comment]
@anobik: If the build is failing on your developer machine, there is a configuration issue or bug in your project. We wouldn't expect it to work in VSTS builds. Did you try turning off linking in your project?

**Comment by anobik** [comment]
@madhurig 

The screen shot is from VS in build machine running in Windows server 2012. There's no issue with Dev box. Also we need to link the sdk so cannot turn linking off. 

Please suggest.

**Comment by anobik** [comment]
@madhurig

Also if you can advice. Should I add a new issue referring to this issue since this is closed ?

**Comment by madhurig** [comment]
@anobik : You can use this issue if VSTS build continues to fail after your local build works.

**Comment by anobik** [comment]
@madhurig

Please let me know all the details required.

My local build works fine. The only difference is in dot net framework version.

If you need I'll provide a screen shot of the same. 

Build machine : 4.6.2
Local machine: 4.7

**Comment by madhurig** [comment]
This is the information we request on new issues:

## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 


- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Error logs

[Insert error from the logs here]

**Comment by anobik** [comment]
Give me some time. Will revert back with all possible details.

**Comment by anobik** [comment]
We are using a private agent running on Windows Server 2012.

Here's a screenshot

![image](https://user-images.githubusercontent.com/3693669/38135146-29c4484a-3434-11e8-8f35-5aa49433e27e.png)


Following is the build definition, copied directly from batch file

"C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe" /t:restore "Android.sln"

"C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe" /nologo Android.sln" /p:SkipInvalidConfigurations=true   /p:VisualStudioVersion=15.0 /p:Configuration="ObRelease" /p:Platform="Any CPU"  /p:GenerateProjectSpecificOutputFolder=False


I have put to build would attach the log once finished.

**Comment by anobik** [comment]
Here's the build log

[1_Build.txt](https://github.com/Microsoft/vsts-tasks/files/1863458/1_Build.txt)

**Comment by madhurig** [comment]
@anobik : Your logs looks very different from current VSTS build logs. Please provide this additional information about your environment.

1. Server - Are you using VSTS or TFS? If you are using VSTS, what account/teamproject/build definition? If using TFS, what version of TFS?

2. Agent: You said you are using a private agent on Windows Sever 2012. What is the agent version? 
You can get full build logs from your build and send them to us. 

3. Are you using the Xamarin Android task? It looks like you have some script that invokes VSBuild.

If you run these commands from a command line manually on the private agent machine, do they succeed or fail? If they fail, there is some dependency not installed on your private agent. You will need to investigate the missing dependency and install it. Make sure you have latest updates of VS and Xamarin.

C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe" /t:restore "Android.sln"

"C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/MSBuild.exe" /nologo Android.sln" /p:SkipInvalidConfigurations=true /p:VisualStudioVersion=15.0 /p:Configuration="ObRelease" /p:Platform="Any CPU" /p:GenerateProjectSpecificOutputFolder=False

Thanks,
Madhuri

**Comment by anobik** [comment]
[logs_36226.zip](https://github.com/Microsoft/vsts-tasks/files/1879341/logs_36226.zip)

I have attached the logs from the tfs build agent.

**Comment by madhurig** [comment]
@anobik: The error seems to suggest you don't have some Android SDK version you are targeting from the project installed on your build server or you are not targeting the right version of Java.

Are you using the Xamarin Android task? There is an option on the Xamarin Android task to target Java 8. 

Based on the logs you are not using VSTS and are on a very old version of the agent. Can you try upgrading your agent to a newer version to get better logging. 



Thanks,
Madhuri

**Comment by anobik** [comment]
Yes we are using xamarin Android task. For upgrading i need to check with some other people. Meanwhile I'll try checking all the Android platforms in the project and the server.

**Comment by anobik** [comment]
Have run into another problem, it shows javac.exe error cannot find symbol

![image](https://user-images.githubusercontent.com/3693669/38468783-6bcf2e90-3b68-11e8-924d-f9c060b3f10c.png)
[1_Build.txt](https://github.com/Microsoft/vsts-tasks/files/1887543/1_Build.txt)


Heres the new Log.

**Comment by anobik** [comment]
Current TFS ersion

Microsoft Visual Studio Team Foundation Server
Version 14.102.25423.0

© Microsoft Corporation. All rights reserved.

**Comment by madhurig** [comment]
It looks like you are using TFS 2015 Update 3 and trying to build a Xamarin Android app in Visual Studio 2017. I am not sure what the javac error is but new versions of Xamarin require using Java 8. Please ensure you have Java 8 installed and if you have multiple Java versions installed on the agent, you can pass an additional msbuild argument to the Xamarin Android task to pick the right version of Java.

/p:JavaSdkDirectory=<Java8_SDK_DIR>

**Comment by madhurig** [comment]
@anobik : Have you resolved your issue? As far as I can tell, it is a dependency installation issue on your build server.

**Comment by madhurig** [comment]
Closing since we are pretty sure this is a dependency installation issue on the build server and the thread has not had updates in a month.

**Comment by madhurig** [comment]
@anobik: I am sorry none of the suggestions helped. For further support on xamarin toolset reach out at https://forums.xamarin.com/ or open bugs on https://bugzilla.xamarin.com/.

Thanks,
Madhuri
