### ISSUE TITLE
[ServiceFabricDeploy] Enable diff by default and "Use diff" input should be moved to upgrade group

### ISSUE THREAD

**Issue by bishal-pdMSFT** [Microsoft/vsts-tasks#6836]

**Comment by kuvinodms** [comment]
Fix has been merged with master where we've moved UseDiff to Upgrade section and not enabling it by default.

**Comment by bishal-pdMSFT** [comment]
@kuvinodms  please create separate issue to track enabling diff by default in task

**Comment by kuvinodms** [comment]
@bishal-pdMSFT 
Create the new issue #7390 
Feel free to update the same if you want to involve enabling Compression or enabling SkipUpgradeSameTypeAndVersion with the same issue
