### ISSUE TITLE
##[error]Unable to locate executable file: 'pwsh'. on macOS

### ISSUE THREAD

**Issue by FrancoisM** [Microsoft/vsts-tasks#6843]
As my ios build fails on Hosted macOS whereas it builds on my mac (see [there](https://github.com/aspnet/SignalR/issues/1770)) I'm trying to use my mac as a private agent.
My build definition requires powershell so I installed it on the mac. I downladed a tar file that I extracted and then I added the path to the folder containing pwsh into PATH:
- I went into /etc/paths.d and added a file called pwsh with the correct folder path in there .
- I also did export PATH=$PATH:/myfolderpath into a terminal

Note that I changed the file permisions to be -rwxrwxrwx@.
When I type 'pwsh' from anywhere (including the _work folder of my agent) powershell starts and says 'PowerShell v 6.0.2'

However, as mentioned in the title, when running my build definition I got the following error:

> ##[error]Unable to locate executable file: 'pwsh'. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

**Comment by yacaovsnc** [comment]
Did you restart your agent after you make those changes?  Is your agent running as a service?  Is your agent running in the same terminal that you exported the PATH env var?

**Comment by FrancoisM** [comment]
1°) I didn't restart the machine or the agent (will give a try)
2°) My agent is not running as a service (I called ./run.sh)
3°) My agent is not running on the same terminal in which I exported pwsh in PATH

**Comment by yacaovsnc** [comment]
You need to export that variable in the same terminal your agent is running for it to take effect, and you need to make sure you first modify the variable, then start the agent.  Otherwise the process won't pick up env var changes.

**Comment by yacaovsnc** [comment]
@FrancoisM is this still an issue?  Did you get powershell to run on your private agent? :)

**Comment by FrancoisM** [comment]
Haven't tried yet. On my todo list to test and report here. Thanks for the follow up.

**Comment by FrancoisM** [comment]
I exported the powershell folder path to PATH on a teminal window. I then started `pwsh` on that same window then did `./run.sh` and pushed an `echo "hello world"` powershell task to vsts to run on my private mac os agent and it succeeded. Tks :-).
