### ISSUE TITLE
TFS Artifacts for Release Management

### ISSUE THREAD

**Issue by gregpakes** [Microsoft/vsts-tasks#6845]
I'm not sure if this is the correct repo for this, but I am wondering if the source for the following extension is available on github [TFS Artifacts for Release Management](https://marketplace.visualstudio.com/items?itemName=ms-vscs-rm.vss-services-externaltfs)?

I find this extension really useful but the lack of the ability to set a default version for deployment makes it unusable for me.  I would like to see if it's possible for me to add this feature.

**Comment by brcrista** [comment]
The GitHub repo is at the bottom of the page you linked, under FAQs: https://github.com/Microsoft/vsts-rm-extensions/issues
