### ISSUE TITLE
VSTS task "Update Service Fabric Manifests" doesn't update docker image version

### ISSUE THREAD

**Issue by Kalaicompute** [Microsoft/vsts-tasks#6856]
I am using VSTS build to be able to build and push docker image of .net core service and deploy that in Service Fabric Cluster using VSTS release definition. In the build definition, I apply VSTS build number as version of docker image using "Docker-compose" build image task and added the "Update Service Fabric Manifests" task with update type "Docker image settings" thinking it will update the ServiceManifest.xml file with docker image name and it's version in <ImageName> element under <ContainerHost> element. But, it updates only docker image name, not the version. Is that by design? I am trying to implement build definition to be able to deploy the particular docker image version in service fabric cluster. Please clarify.

Thanks in advance.

**Comment by bishal-pdMSFT** [comment]
@Kalaicompute you should use sfproj build task to create docker image and then docker task to push images instead of docker-compose task. Infact, there is a build definition template which you can use:
![image](https://user-images.githubusercontent.com/7830141/38270462-1a84c74a-37a1-11e8-839d-5da3390d8335.png)
Let me know if this works for you.

**Comment by Kalaicompute** [comment]
@bishal-pdMSFT thanks for the response. Actually, that didn't help me. It behaves the same as it was with my previous implementation. Just to make it clear, I am explaining further about what I am intending to do.

Here is the CodePackage element in ServiceManifest.xml in the source repo.
`<CodePackage Name="Code" Version="1.0">
    <EntryPoint>
      <ContainerHost>
        <ImageName>ecpoc.azurecr.io/l2o/benefitsfd</ImageName>
      </ContainerHost>
    </EntryPoint>
    <EnvironmentVariables>
      <EnvironmentVariable Name="ASPNETCORE_URLS" Value=""/>
      <EnvironmentVariable Name="ASPNETCORE_ENVIRONMENT" Value=""/>
    </EnvironmentVariables>    
  </CodePackage>`

When I commit a code change, CI build kicks in and generates the docker image with version tag, say 20180404.4. That said, I am expecting below CodePackage element to be able to deploy this particular container image version.
`<CodePackage Name="Code" Version="1.0.20180404.4">
    <EntryPoint>
      <ContainerHost>
        <ImageName>ecpoc.azurecr.io/l2o/benefitsfd:20180404.4</ImageName>
      </ContainerHost>
    </EntryPoint>
    <EnvironmentVariables>
      <EnvironmentVariable Name="ASPNETCORE_URLS" Value=""/>
      <EnvironmentVariable Name="ASPNETCORE_ENVIRONMENT" Value=""/>
    </EnvironmentVariables>    
  </CodePackage>`

But, what I am getting is,
`<CodePackage Name="Code" Version="1.0.20180404.4">
    <EntryPoint>
      <ContainerHost>
        <ImageName>ecpoc.azurecr.io/l2o/benefitsfd</ImageName>
      </ContainerHost>
    </EntryPoint>
    <EnvironmentVariables>
      <EnvironmentVariable Name="ASPNETCORE_URLS" Value=""/>
      <EnvironmentVariable Name="ASPNETCORE_ENVIRONMENT" Value=""/>
    </EnvironmentVariables>    
  </CodePackage>`

It only updates CodePackage Version, not updates container image tag. So, using this ServiceManifest.xml in VSTS release definition always deploys the container image marked as Latest, not the particular image version. I would appreciate if could let me know if this doable.

Thanks.

**Comment by bishal-pdMSFT** [comment]
Can you please provide debug logs for your build. Add a variable named `system.debug` with value `true` to build definition and create a new release. Then get logs,

**Comment by Kalaicompute** [comment]
Sure, here you go! Thanks for the response again.

[logs_8998085.zip](https://github.com/Microsoft/vsts-tasks/files/1896706/logs_8998085.zip)

Thanks.

**Comment by bishal-pdMSFT** [comment]
@Kalaicompute , there are two issues I can see:

1. You should add a task to build sfproj project. You are only building dot net core project. In sfproj build, you should add `BuiltDockerImagesFilePath` argument
![image](https://user-images.githubusercontent.com/7830141/38598184-05bbd758-3d79-11e8-9cce-dbcd494e9172.png)

2. You should use 'Push Images' action in docker push task rather than 'push an image'. This will let you specify image file path specified above
![image](https://user-images.githubusercontent.com/7830141/38598335-92647cd2-3d79-11e8-85b9-aafc1742d550.png)

**Comment by Kalaicompute** [comment]
@bishal-pdMSFT Thanks again for checking the logs and suggesting solution. I added build task to build sfproj project. But, it fails with below error.

##[error]src\BenefitsFD.App\BenefitsFD.App.sfproj(43,5): Error : Unable to find the '..\..\packages\Microsoft.VisualStudio.Azure.Fabric.MSBuild.1.6.6\build\Microsoft.VisualStudio.Azure.Fabric.Application.props' file. Please restore the 'Microsoft.VisualStudio.Azure.Fabric.MSBuild' Nuget package.

[Logs are here](https://github.com/Microsoft/vsts-tasks/files/2011127/logs_9755606.zip)

Could you please suggest troubleshooting steps for this issue?

Thanks in advance,
Kalai.

**Comment by bishal-pdMSFT** [comment]
Do you have nuget.org as source in restore task?

![image](https://user-images.githubusercontent.com/7830141/40159519-4ac5d35c-59c7-11e8-8ca6-ac9587e62b86.png)

**Comment by bishal-pdMSFT** [comment]
Also, could you check that your project has Microsoft.VisualStudio.Azure.Fabric.MSBuild mentioned as a nuget dependency? Did you create the project using VS? You can try updating VS and then updating the project.

**Comment by bishal-pdMSFT** [comment]
@Kalaicompute sfproj build will create a text file with created image names and there is a "Update manifest" task which will update image version in manifest file. Can you please share your build logs?

@mthalman-msft / @NCarlsonMSFT can you please help us with steps for creating a hybrid application through VS?

**Comment by Kalaicompute** [comment]
@bishal-pdMSFT I too see that building sfproj is creating a text file with image name, but that has the default container image tag "dev" that I have in my source code. Can I expect it to be updated with build number by this(sfproj) build task or some other build task? Please find below the logs and let me if I have some bugs in build configuration.

[logs_9866224.zip](https://github.com/Microsoft/vsts-tasks/files/2033301/logs_9866224.zip)

**Comment by NCarlsonMSFT** [comment]
@Kalaicompute The Update Manifests task is supposed to update your image name with the digest of your built image. However it appears to have a bug with the recently introduced dev tag. I'll try and take a look tomorrow at fixing the logic.

One workaround for unblocking your CI/CD would be to remove the dev tag. But that unfortunately would break local debugging as Service Fabric does not allow for an image name without a tag or digest.

**Comment by kuvinodms** [comment]
This fix should roll out in next few days for all the customers

**Comment by Kalaicompute** [comment]
Thanks everyone!

**Comment by shreyajain0208** [comment]
@Kalaicompute Hi, I am facing this same issue. Could you please help me how it got resolved or what is the other way round. Thanks in advance!
