### ISSUE TITLE
Does this support recorded/coded webtests?

### ISSUE THREAD

**Issue by svc76** [Microsoft/vsts-tasks#6861]
Does this test task support recorded or coded webtests? When i try to use these, i get an error with "No test assemblies found". Is there any other alternative to this?

Thanks

**Comment by kaadhina** [comment]
@svc76  The Visual studio test task does support these tests. Can you make sure the test assemblies filter and search folder is specified correctly?
If it still does not work, please turn on verbose logging by setting build variable system.debug=true and collect the logs and share with us to take a look.

**Comment by acesiddhu** [comment]
@svc76 also what version of VS are you using?

**Comment by svc76** [comment]
I'm using VS 2015 to author the tests. I I have attached my logs with this reply. Please let me know what is going wrong.
[Release80_Logs_345.zip](https://github.com/Microsoft/vsts-tasks/files/1882419/Release80_Logs_345.zip)

**Comment by ganesp** [comment]
@svc76
There are two scenarios you can run into this issue: 
**Scenario1**
Web test/CodedWebTest/OrderedTest associated from VS2017 will work when executed on VS2017/VSTest platform installer.
Any other VS version and combination is NOT supported.

**Scenario2**
Following steps can lead to the issue you are seeing:
1)  Create a project with webtest1.webtest  [webtest1 has guid X as identifier]
2)  Associate the webtest1.webtest with a test case
3)  Delete the webtest1.webtest and add a new webtest with the same name [webtest1 has guid Y as identifier]
4)  Generate the build
5)  Run the tests on demand (using the build from #4)
6)  As the identifier for the web tests (the one which is associated with the test case and the other which was re-created in #3) are different, it fails to discover the test

**Comment by ganesp** [comment]
@svc76 
Please confirm if you scenario falls into one of the above two. 
If yes, we can proceed with closing this issue.

**Comment by abhishkk** [comment]
@svc76 
We are closing this issue for now. Please comment if you any further queries to re-open the issue.
