### ISSUE TITLE
Select members as build task input?

### ISSUE THREAD

**Issue by chrismbarr** [Microsoft/vsts-tasks#6865]
I am in the beginning steps of creating a new build task that (ideally) would look for certain things in the code submitted in a PR, and then pull in additional members as required PR reviewers depending on what it found.

In the `task.json` file where I set up the inputs for the task UI, I don't see a way to select TFS members from a list, it seems to [only have a few types](https://github.com/Microsoft/vsts-tasks/blob/2ca85b3a2f19b65fa866aee12e5d1fe3150c7012/Tasks/DownloadBuildArtifacts/vso-node-api/interfaces/BuildInterfaces.ts#L608-L616): `string`, `boolean`, `stringList`, `radio`, `pickList`, `multiLine`, and `branchFilter`

Is it possible add a "typeahead" list of TFS members as a build task input, similar to how PR reviewers are selected? Like this _(some org info redacted)_:

![User/Group Selector on a TFS Pull Request](https://user-images.githubusercontent.com/463685/38258069-931b3026-372f-11e8-9fb8-d9e4bf49d26f.png)

If not, is there a way to add this somehow?  Right now the only fallback I know of it to make this a list of member GUID's that must be manually looked up.  It will get the job done, but it's not pretty.

----

Ideally, I think it would be useful to have 2 new input types:
 - `memberSelect` for selecting a single member
 - `multiMemberSelect` for selecting 1 or more members

**Comment by bryanmacfarlane** [comment]
Not an issue with tasks in this repo.

to answer the question - there is no input type of user.  Task inputs are very generic (string, bool, list) and are meant to be stand alone.

On a side note, perhaps you would want the task to compute who those reviewers should be (perhaps based on commit history to the affected folders etc.).

Feedback would be a more appropriate place to request

https://developercommunity.visualstudio.com/spaces/21/index.html

**Comment by chrismbarr** [comment]
Good to know, thanks.  For anyone in the future that may be looking for this, I opened a request here: https://developercommunity.visualstudio.com/content/problem/228665/suggestionidea-select-members-as-build-task-input.html
