### ISSUE TITLE
Bake immutable image task with managed disks

### ISSUE THREAD

**Issue by lenisha** [Microsoft/vsts-tasks#6876]
Hi,
Vsts bake immutable image task currently does not support packer template that stores image in managed disks.
Could it be enhanced please

**Comment by bryanmacfarlane** [comment]
Which task is this?  Here's the list: https://github.com/Microsoft/vsts-tasks/tree/master/Tasks

**Comment by bryanmacfarlane** [comment]
request to reopen after clarifying more.

**Comment by maniSbindra** [comment]
I Believe this is the VSTS Packer Task.

**Comment by sachinma** [comment]
@azooinmyluggage  to consider this request in the backlog

**Comment by maniSbindra** [comment]
Started working on a PR for this. However current Version of packer on the hosted agents is 0.12.3, which does not support configurations for managed disk images. Following error is received is received
 
```sh
2018-05-03T17:03:15.0907988Z * unknown configuration key: "managed_image_name"
2018-05-03T17:03:15.0908210Z * unknown configuration key: "managed_image_resource_group_name"
2018-05-03T17:03:15.1207332Z ##[error]Packer validate command failed. This could happen if task does not support packer version.
```
Would you be able to share the timeline to upgrade the packer versison?

**Comment by sachinma** [comment]
This is merged in master.
