### ISSUE TITLE
Azure Resource Group Deployment Task Fails on AzureChina Cloud 

### ISSUE THREAD

**Issue by irajbalakrish** [Microsoft/vsts-tasks#6896]
## Problem Statement

 Azure Resource Group Deployment Task Fails When Targeting a Subscription in AzureChina Cloud

## Environment

**VSTS Environment**

1. agrifirm.visualstudio.com
2. eCommerce - Website Agrifirm.com NL
3. CI-master-release-definition
4. Release-CI-master-build-definition_1.1.18095.01-agrifirmchina-1

Hosted Agent Queue Name 
    
   **Hosted**

## Issue Description

Azure Resource Group Deployment Task Fails When Targeting Azure China Subscription

![error log](https://user-images.githubusercontent.com/17502477/38419967-9645a216-39a2-11e8-8099-7248bcf38117.png)

**Comment by Ajay-MS** [comment]
Can you verify your SPN via below mentioned steps 

1.  Using Azure RM endpoint dialouge
![image](https://user-images.githubusercontent.com/16772764/38496455-3dbe2cd2-3c1b-11e8-913d-69ac3b995bfa.png)

2. Using PowerShell script. 
```
$servicePrincipalId = "<ServicePrincipalID>"
$servicePrincipalKey = "<servicePrincipalKey>"
$tenantId = "<tenantId>"
$azureSubscriptionId = "<azureSubscriptionId>" 

$securePassword = ConvertTo-SecureString $servicePrincipalKey -AsPlainText -Force
$psCredential = New-Object System.Management.Automation.PSCredential ($servicePrincipalId, $securePassword)

Write-Verbose "Add-AzureRMAccount Started" -Verbose
$azureAccount = Add-AzureRMAccount -ServicePrincipal -Tenant $tenantId -Credential $psCredential -EnvironmentName AzureChinaCloud
$azureAccount
Write-Verbose "Add-AzureRMAccount Completed" -Verbose

Write-Verbose "Select-AzureRMSubscription Started" -Verbose
$newSubscription = Select-AzureRMSubscription -SubscriptionId $azureSubscriptionId -TenantId $tenantId
$newSubscription
Write-Verbose "Select-AzureRMSubscription Completed" -Verbose
```

**Comment by irajbalakrish** [comment]
I already did and it appears fine. I see the problem only in ARM Task. The App Service Deployment Task just runs fine
![capture](https://user-images.githubusercontent.com/17502477/38497044-fbee5950-3bff-11e8-9cef-c1b8b8c8e52a.PNG)

**Comment by irajbalakrish** [comment]
r.balakrishnan@agrifirm.com
+31610405650
We can talk now 👍

**Comment by Ajay-MS** [comment]
@irajbalakrish 

Posting observation during the call for future reference. 

1.  SPN was scoped to a resource group. When Azure RG task is executed with difference RG it's failing with 403 unauthorized. 
2.   In case of 403 error, error object doesn't contain a message and it's getting printed as an object in logs. ( We have to fix [this code for logging error](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzureResourceGroupDeployment/operations/Utils.ts#L11) from our end )
3.   If a resource type mentioned in the template doesn't exist in the cloud. In VSTS, we got an error and fail on it but visual studio got the same error but it doesn't fail on error.  ( Will discuss on this with the team)

**Comment by Ajay-MS** [comment]
@irajbalakrish 

Apologize for the delay in response to the thread 

As per discussion with the team, If you select "Continue on error" then Azure RG task will create all other resources except one that doesn't exist in the Azure Cloud. Can you please verify same behavior.

Added @ds-ms  any queries regarding Azure RG task.

**Comment by ds-ms** [comment]
@irajbalakrish are you still facing this issue?

**Comment by irajbalakrish** [comment]
**The situation is fixed** The outcome of the investigation is mentioned by Ajay in the prev thread

**Comment by ds-ms** [comment]
Closing the issue then.
