### ISSUE TITLE
Visual Studio Test and custom logger

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vsts-tasks#6897]
## Environment
- Server - TFS 2018

## Issue Description

In Visual Studio Test task I'm trying to run my tests using a custom logger. How do I pass in the value of it? I tried 'Override test run parameters' setting, but I had no luck. No matter what, the logger is always tfx (check log).

### Error logs

2018-04-06T13:33:34.6035661Z [command]"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" E:\1\_work\12\s\CICD-SpecflowTests\bin\Debug\CICD-SpecflowTests.dll /Settings:C:\Users\EU60FB~1.RDW\AppData\Local\Temp\1aa75f80-399f-11e8-b4a9-63ac9254f3ac.runsettings /logger:trx

**Comment by abhishkk** [comment]
@mmajcica Can you please share entire build logs? Please enable verbose logging to get detailed logs (set system.debug variable as true).

**Comment by mmajcica** [comment]
@abhishkk I set the parameter 'Other console options' on my task to '/Logger:MsTestTrxLogger'and the following is what is executed (from log):

`"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" E:\4\_work\4\s\Test\LICWID_WRR\bin\debug\LICWID_WRR.dll /TestCaseFilter:TestCategory=smoke_test&TestCategory!=wip /logger:trx /Logger:MsTestTrxLogger`

As you can see the logger parameter is added twice. It would be nice that we could choose our on logger implementation and not be forced to use trx logger (as the trx logger doesn't produce a trx file that is 100% same as the trx file created by mstest).

**Comment by abhishkk** [comment]
@mmajcica You can choose your own logger implementation and add it via other console options. Multiple loggers works fine with test platform. 

Adding trx logger by vstest will not create any issues as your logger will continue to work perfectly fine.

**Comment by mmajcica** [comment]
@abhishea it does as two trx files are created, then both are uploaded in the build so that the test run results having 2x test then it actually does.

**Comment by mmajcica** [comment]
@abhishkk Many tools do relay on the trx file. In case of the test run with MsTest the resulting trx is different then if run with VsTest with trx logger.
Differences between the two TRX outputs are small but are preventing tools such as SpecFlow report generator to correctly process trx file.
The differences are:

1. //TestRun/TestDefinitions/UnitTest/TestMethod/@className renders not the fully qualified name, but just the namespace.

1. The TestDescriptionAttribute is not rendered, but should be in //TestRun/TestDefinitions/UnitTest/Description.

1. TestPropertyAttributes are not rendered, but should be in //TestRun/TestDefinitions/UnitTest/Properties.

I'll try reporting this to vstest team as that would be the best solution if fixed.

Thanks

**Comment by abhishkk** [comment]
@mmajcica Sure. Our team also owns test platform (vstest). Please raise an issue there and we will check the possibilities of trx changes which you are suggesting. Please provide the sample project, sample trx as well along with the issue.
