### ISSUE TITLE
VSTest task should fail, if zero tests were run

### ISSUE THREAD

**Issue by NenoLoje** [Microsoft/vsts-tasks#6900]
Right now, if the VSTest task fails to discover any tests, it will still report success. It's hard to spot those problems when the build shows green.

It would be great to get an option to:
  [X] Fail when no tests have been run.

Thanks,
--Neno

**Comment by nigurr** [comment]
This is in our backlog. We currently don't have any tentative timelines to share.
Thanks for sharing the feedback.
