### ISSUE TITLE
Task build script can't restore external dependencies

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vsts-tasks#6926]
In case the developer's machine is behind a corporate proxy, build script will fail as the module used called 'sync-request' is not supporting calls over a proxy.

**Comment by bryanmacfarlane** [comment]
which task in this repo is this?  what build script are you referring to?  (/Tasks)

**Comment by bryanmacfarlane** [comment]
Thanks for clarifying.  We're not going to make our build script proxy aware.  I'm surprised a module doesn't support the typical HTTP_PROXY set of envvars.

We don't support distributing custom built tasks - we open sourced for troubleshooting, diagnosing issues and being reference examples on how to write tasks.  We are also going to create built zips of the tasks soon.
