### ISSUE TITLE
vstest tests not executing and test slice not timing out

### ISSUE THREAD

**Issue by acm74** [Microsoft/vsts-tasks#6932]
I am using a release definition to run coded UI tests on multiple virtual machines.  I am testing a small subset of our full test suite, 40 tests across 9 VMs (with each VM having an interactive test agent).

During test runs I am consistently seeing that 1 agent does not execute tests, despite the logs indicating that they have found the tests on the machine.  The release will continue (without executing any further tests) indefinitely unless I cancel it.

I have attached the logs from the effected VM from the latest test run. So far I cannot find any further evidence on the VM of what might be happening (or not happening).  So far I have not found anything suspicious on any of the other VMs, nor can I identify anything else of interest in the VSTS release logs.

[r108_vm7_vstestlog.log](https://github.com/Microsoft/vsts-tasks/files/1894761/r108_vm7_vstestlog.log)

**Comment by abhishkk** [comment]
@acm74 Can you share build logs (set system.debug=true) to debug into this issue further.

**Comment by acm74** [comment]
@abhishkk here are the entire logs for the release.  Did you want logs for the builds as well?
[R108_logs.zip](https://github.com/Microsoft/vsts-tasks/files/1907771/R108_logs.zip)

**Comment by abhishkk** [comment]
@acm74 We checked into the logs and found that in Agent 5 was hung.
TestPlatform seems not be responding or crashed while executing tests.

Can you please answer following:
1. Was this an one off incident? OR is it happening in every test run?
2. If it happens in every test run, please check in logs that out of 40 which 10 test didn't got executed (I see 30 tests were run successfully.) Run only those 10 tests again and share the logs.
3. Is it always happening in the machine where agent 5 was running?

**Comment by acm74** [comment]
I can answer some of your questions now, and the rest on Monday when I can consult my notes in the office.

This is not a one-off incident.  I have observed this in 5 test runs.  It is a different agent/VM in each test run, and only 1 agent/VM per test run.

The latest test run (which was just a few hours ago had slightly different results).  In this last test run, the run was able to complete.  One agent/VM was declared sick by VSTS and was not included in the test execution phase, and 3 tests were not executed.  I have not had time to check, but I believe that the tests not executed, were distributed to the agent/VM that was sick.


On Monday I will do the following:

- run the failing tests from the 5 test runs I have mentioned in this email

- recreate the latest test run

- I will check the logs for agent 5, to try and understand what happened


I will update you with a status and logs as soon as they are available.


Thanks in for all your help. 😊

________________________________

**Comment by acm74** [comment]
@abhishkk I have the same 6 tests not being run across 4 test runs, and 3 of the 6 not being run in the last test run.  The tests are fairly stable in our old test environment.  As far as I can tell the agent never attempts to execute the tests, but I have not found anything in the logs to indicate why this may be the case.  Is there somewhere else I can look?

**Comment by acm74** [comment]
I will try this in the next day or so.  Unfortunately I have had other high priority tasks, which have prevented me from returning to this.

**Comment by acm74** [comment]
I cannot attempt this at the moment, because the vstest platform installer task is failing.  I have created a separate issue for this.

**Comment by abhishkk** [comment]
@acm74  Can you share the issue link?

**Comment by acm74** [comment]
https://developercommunity.visualstudio.com/content/problem/236047/vstest-platform-installer-task-failing.html?childToView=236119#comment-236119

vstest platform installer task failing - Developer Community<https://developercommunity.visualstudio.com/content/problem/236047/vstest-platform-installer-task-failing.html?childToView=236119#comment-236119>
developercommunity.visualstudio.com
Developer Community for Visual Studio Product family




________________________________

**Comment by abhishkk** [comment]
You can report issue at https://github.com/Microsoft/vsts-tasks/issues for vstest platform installer task as well.

**Comment by acm74** [comment]
ok, will do in the morning

________________________________

**Comment by ShreyasRmsft** [comment]
@acm74 

This has nothing to do with the task itself. Your agent is unable to access the .taskkey file.
Simplest solution is to first try and delete the .taskkey file and try again. The agent should re-create this file.
Also the reason it is not able to access is because the file is archived. Un-archive this file and prevent the file from being archived in the future.

**Comment by acm74** [comment]
@ShreyasRmsft thanks for confirming my suspicions. Deleting the file allowed for the release to continue.  It doesn't answer why the file got into this state.  Which is apparently a bigger problem than just this single file.

@abhishkk The vstest task is not executing tests.  37 out of 40 tests have the error "Failed to initialize the unit test extension 'urn:CodedUITest': A unit test extension is not registered for the following attribute: Microsoft.VisualStudio.TestTools.UITesting.CodedUITestAttribute."
The logs shows that vstest cannot access 2 files (access denied): 
LegacyTypes.testtype
ManualTests.testtype
ManualTests.testtype
in the folder 
C:\VSTSAgent\A1\_work\_tool\VsTest\15.7.0\x64\tools\net451\Common7\IDE\Extensions\TestPlatform\

All 3 files are set as archived, I'm guessing this is the source of the errors.  The problem I have now is that I have a task (vstest platform installer), which is supposed to be self-contained, which now leaves the system in an unusable state.

How do I get a working system now?

**Comment by acm74** [comment]
[vstestplaformarchived.txt](https://github.com/Microsoft/vsts-tasks/files/1927544/vstestplaformarchived.txt)
@ShreyasRmsft  @abhishkk apparently most of the files in the vstest platform are archived.... I'm sure this is not intended behavior.

**Comment by ShreyasRmsft** [comment]
@acm74 can you please delete all the archived files and try again. Also please ensure there is not utility or software on your machine that is archiving all the file.

**Comment by acm74** [comment]
@ShreyasRmsft there is certainly no utility nor configuration that I have set that could be archiving files.  I removed the test platform and created a new release.  Now I am not seeing those access denied errors with the test platform.  But I do get this with the target applications - where it seems every file has the archive attribute set.

**Comment by acm74** [comment]
@ShreyasRmsft @abhishkk removing the archive attribute from our applications removed that direct error, but when our tests attempt to start our application, we get the following error
AMS Server is not started. Exception: System.UnauthorizedAccessException: Access to the path 'C:\CodedUITests\AMS Server\WorkBridge.Framework.Server.Shell.Host.exe.config' is denied.

**Comment by abhishkk** [comment]
@acm74 Can you check if your agents are started with admin privilege?

**Comment by acm74** [comment]
the agents have administrator rights.


I think the last failure that came up was because windows update had blocked the screen with an update message.  I've got another release going now and I'll try to confirm this when I get to the office.  If you have any tips about dealing with windows update, I'd be very happy for them.

________________________________

**Comment by acm74** [comment]
windows update wasn't the ultimately reason for this, although it could prove to be an issue later on.  

The interactive agent runs as a user who is a member of the local administrators group.  I can see that the UnauthorizedAccessException is occurring when we attempt to update the application config file.  The config file has read and execute permissions for users, and full control for administrators.  I'm guessing if I reset the permissions I will clear the exception.  This is what I will check next

**Comment by acm74** [comment]
Resetting file permissions worked.  Unfortunately for me, windows update is still a problem and we can't interact with the desktop while windows update is showing it's update dialog.

With respect to the file attributes and permissions, I would really appreciate any insight you might have into the cause of this.  While I can reset attributes and permissions, it does feel like a hack.  Currently we unpack our suite of applications into a new directory (c:\codeduitests), would it make a difference to change this to somewhere under the agent's default working directory?

**Comment by acm74** [comment]
@abhishkk @ShreyasRmsft I have an interim solution for windows update, and have been able to create a test run (with the same tests failing to execute).

I will be on vacation from today, returning to work 1/5/2018.  Thanks for all your help so far, it has been very much appreciated.

**Comment by abhishkk** [comment]
> While I can reset attributes and permissions, it does feel like a hack. Currently we unpack our suite of applications into a new directory (c:\codeduitests), would it make a difference to change this to somewhere under the agent's default working directory?

If you are downloading your suite of applications from internet, can you check whether the zip is blocked? Check [this](https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/) example for more info.

**Comment by acm74** [comment]
this is most definitely not solved!  I am seeing the same behavior over a range of different test suites.  These are tests that have been successfully executing in MTM environments for a number of years. Please re-open this issue.

**Comment by acm74** [comment]
@abhishkk thanks for re-opening this so quickly.  One of your colleagues suggested that issues could be caused by the test method being linked to multiple test cases (see https://developercommunity.visualstudio.com/comments/242508/view.html).  Do you have any insight into why this may be a problem?

**Comment by abhishkk** [comment]
@acm74 Same test method associated to multiple test cases can either cause hang or below error:
`System.ArgumentException: An item with the same key has already been added.`

The fix for this issue is required both in vsts task side and VS side. Task side is already fixed. VS side fix will be available in 15.8 preview 2 (around 30th May). This VS side fix will also be available as [VS platform tools installer](https://docs.microsoft.com/en-us/vsts/release-notes/2017/nov-28-vsts#test) package soon.

**Comment by acm74** [comment]
@abhishkk thanks for the explanation.  This may be the cause (or a cause) of our issues.  I will have to investigate further.  Just to clarify - 1 test method to > 1 test case causes intermittent failures (as opposed to failing every time)?

**Comment by acm74** [comment]
@abhishkk I can see that it took 6 hours for my test run to time out.  Is this an absolute time limit for a test run, or is it a timeout from no test execution activity?  Even with a test lab of 99 VMs I am expecting a full test run to take 6 hours, possibly longer.

**Comment by abhishkk** [comment]
@acm74 With latest task side changes in (but not VS side fixes in), hang should not occur. You should only get `System.ArgumentException: An item with the same key has already been added.`

Can you share the latest logs with debug true to look into why the hang is occurring?

**Comment by acm74** [comment]
R25, R26 - full test run, no tests executed
[R25Logs.zip](https://github.com/Microsoft/vsts-tasks/files/1976368/R25Logs.zip)
[R26Logs.zip](https://github.com/Microsoft/vsts-tasks/files/1976369/R26Logs.zip)

**Comment by acm74** [comment]
@abhishkk can we work around the problem by changing duplicate test cases to a closed state?  Or could we remove the associated automation from the duplicate test cases?

**Comment by nigurr** [comment]
@acm74 can we have skype call to debug this issue? please send your skype id on devops_tools at microsoft dot com

**Comment by acm74** [comment]
@nigurr I just tried to send you my skype/skype for business id's, but the email was blocked at that address.  I have just made my email address visible in my profile - please contact me directly

**Comment by nigurr** [comment]
@acm74 we have received your details and will contact you through email. Closing this issue here.
