### ISSUE TITLE
Unable to get FQDN for all resources in ResourceGroup

### ISSUE THREAD

**Issue by Farzad-Jalali** [Microsoft/vsts-tasks#6934]
## Environment
I'm using **VSTS**

account name:  
poupart.visualstudio.com

team project name:
TFS.Internal

 build definition name:
TFS.Internal - InternalApp -CI

build number
2810

I'm  using Hosted agent, the agent queue name:
Hosted VS2017 2

https://poupart.visualstudio.com/TFS.Internal/TFS.Internal%20Team/_build/index?buildId=2810&_a=summary&tab=details

## Issue Description
I'm a building my solution with build in VSTS ten in the final part I need to copy the result in an Azure VM, so I'm using the "Azure File Copy" v 1.0 
I can see it successfully copied the file into a storage account, but when it tries to copy from storage account into VM, it gets the below error:

 **_##[error]Unable to get FQDN for all resources in ResourceGroup : 'RG-VM-PRD-1-FTP-1'_**

I'm getting this error:
Unable to get FQDN for all resources in ResourceGroup : 'RG-VM-PRD-1-FILESERVER-1'

screenshot:
![image](https://user-images.githubusercontent.com/3695669/38566755-55c7cd1c-3cdc-11e8-9ae3-e54b5433c2aa.png)

### Error logs
I enabled the logs , here is the full logs.
[Insert error from the logs here]

[AzureVMCopy_logs_2810.zip](https://github.com/Microsoft/vsts-tasks/files/1895215/AzureVMCopy_logs_2810.zip)

**Comment by rokmicrosoft** [comment]
@Farzad-Jalali  Is your agent box ip is white-listed for target box ?  It is possible to have a Skype call to debug it further ? You may share your details at RM_Customer_Queries at Microsoft dot com
