### ISSUE TITLE
ServiceFabric tasks to accept a variable for the endpoint name

### ISSUE THREAD

**Issue by steve-hawkins** [Microsoft/vsts-tasks#6935]
## Environment
- Server - VSTS
- Agent - Hosted
    - queue name: Hosted VS2017

## Issue Description

I'm experiencing this issue on all Service Fabric tasks, but example below is for the ServiceFabricPowerShell task used in a VSTS Release definition

I have a requirement to specify the Cluster Connection as a variable, imagine an environment refresh release definition deploying over 60 service fabric applications and having to manually via the Web UI up date all Cluster Connections when you clone a new environment...

image below shows the variable in use on the task

![image](https://user-images.githubusercontent.com/7125740/38570952-037f2824-3ce7-11e8-9ec0-6222e90791cd.png)

I have tried specifying the name and id of the service endpoint, but both produce the error below

### Error logs

```
2018-04-10T16:23:53.6613710Z ==============================================================================
Task         : Service Fabric PowerShell
Description  : Run a PowerShell script within the context of an Azure Service Fabric cluster connection.
Version      : 1.0.7
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=841538)
==============================================================================
##[error]Required: '[REDACTED]' service endpoint URL
```

### Investigation

As far as the current source I cannot explain why the cluster name provided as a variable fails

[Tasks/ServiceFabricPowerShell/task.json](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/ServiceFabricPowerShell/task.json)

```
        {
            "name": "serviceConnectionName",
            "aliases": [
                "clusterConnection"
            ],
            "type": "connectedService:servicefabric",
            "label": "Cluster Connection",
            "defaultValue": "",
            "required": true,
            "helpMarkDown": "Azure Service Fabric cluster which will have an established connection when executing the specified PowerShell script."
        },
```

[Tasks/ServiceFabricPowerShell/ServiceFabricPowerShell.ps1](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/ServiceFabricPowerShell/ServiceFabricPowerShell.ps1)

`$serviceConnectionName = Get-VstsInput -Name serviceConnectionName -Require`

`$connectedServiceEndpoint = Get-VstsEndpoint -Name $serviceConnectionName -Require`

**Comment by steve-hawkins** [comment]
@sachinma any news you have on this would be great

might be a bit of a stretch, but I wanted to ask about yaml for release definitions.  I noticed on the API documentation that [PipelineProcessType](https://docs.microsoft.com/en-us/rest/api/vsts/release/definitions/get#PipelineProcessTypes) for GET Release Definitions has designer and yaml now.  If I can move to yaml files for my release definitions as well as the build definitions that might negate this issue, at least for me.

**Comment by sachinma** [comment]
We do not support having Service endpoints declared as variables. Adding @GitHubSriramB  to comment on how best to solve this scenario

**Comment by GitHubSriramB** [comment]
@steve-hawkins - are all the cluster connections for which you want to create a variable used within same environment?

**Comment by GitHubSriramB** [comment]
@steve-hawkins - cluster connections used within same environment can reuse the same endpoint if it is promoted as a process parameter. Although there is no UI experience to do this, it is possible to use RM REST APIs to do this. Here's a blog that explains how this can be achieved:
http://blog.repsaj.nl/index.php/2018/04/vsts-using-process-parameters-in-release-definitions/

**Comment by GitHubSriramB** [comment]
Closing this issue for now. In case additional help is required, pl. let us know.
