### ISSUE TITLE
Is there a way to get the warning number of a build in VSTS with Powershell?

### ISSUE THREAD

**Issue by ngphung** [Microsoft/vsts-tasks#6945]
## Context
I want to get the number of warning of a build in VSTS and doing actions (force the build to fail, send slack message, etc...) if the count is over a threshold I've defined.

## Question
I wonder if it is possible to get the number of warning raised in a build in VSTS?

The number of warning is in the log generated by VSTS and I can see the number of warning but I don't know how I can get this number for my use.

I looked at logging command but seem not doing what I want.

I want to count the number of warning raised in a build in VSTS online and send a slack message if the number is over a threshold I've defined.

Thanks for you help
Phung

**Comment by MireilleHanna** [comment]
that's not possible today unfortunately

**Comment by ngphung** [comment]
Thanks for your feedback MireilleHanna.
I am going to add that idea in Visual Studio UserVoice. Maybe one day... :)

**Comment by bryanmacfarlane** [comment]
user voice or developer community is a good place to create
