### ISSUE TITLE
App Service Deploy task fails due to incorrect isMSDeployPackage implementation

### ISSUE THREAD

**Issue by BasLijten** [Microsoft/vsts-tasks#6946]
The vsts task "Azure App Service deploy" fails when a correct web deploy package has been provided. The error _"Error: Source (Manifest) and destination (ContentPath) are not compatible for the given operation"_ will show up due to the following (generated) msdeploy command:  
```msdeploy -verb:sync -source:package=package.zip -dest:ContentPath=”azure-site...”```

The function below checks whether or not the provided web deployment package is valid:
https://github.com/Microsoft/vsts-tasks/blob/81285d649ed7ed744ef107af55175b9e128a0c04/Tasks/Common/webdeployment-common/utility.ts#L151

It fails when there is no parameters.xml or systeminfo.xml. Due to its implementation, this check is case sensitive: when there is a SystemInfo.xml instead of systeminfo.xml, the function returns false and the command as shown above will bug out.

The proposed solution is to at least include "SystemInfo.xml", but preferably make this check case-insensitive. 

a temporary workaround is to create a new msdeploy package. In my case, this leads to extra work, as this package has been provided by a 3rd party.

**Comment by KrishnaAdityaB** [comment]
@arjgupta you added this logic with this PR https://github.com/Microsoft/vsts-tasks/pull/3549/files#diff-a2b5b3ac78f6bfd42fd129f5a0d20787

Any reason why you went with only 2 case-sensitive cases?
Can I make this case insensitive?

**Comment by KrishnaAdityaB** [comment]
I will raise a PR with case insensitive check next week.

**Comment by vincentdass** [comment]
The issue is resolved and the fix will be available in upcoming deployment.
