### ISSUE TITLE
Azure SQL DACPAC Task Does Not Add Agent IP To Firewall

### ISSUE THREAD

**Issue by brushwood24** [Microsoft/vsts-tasks#6948]
Using the Azure SQL Database Deployment VSTS task, we have "Specify Firewall Rules Using" set to AutoDetect but the setting doesn't do anything.  The ip of our build agent is not added to the Azure SQL firewall and the task fails.

**Comment by asranja** [comment]
@brushwood24 Are you using private agent or hosted agent ? Can you share the logs after setting the variable "system.debug" to "true". If you are not comfortable sharing the logs here, you can send it to RM_Customer_Queries at microsoft dot com.

**Comment by brushwood24** [comment]
Email sent

**Comment by rokmicrosoft** [comment]
@brushwood24 Now it works as expected I am closing this issue. If you face this issue again please feel free to contact us at RM_Customer_Queries at microsoft dot com.
