### ISSUE TITLE
Ant Task not working in TFS 2018 - Not found ant: null

### ISSUE THREAD

**Issue by anvog** [Microsoft/vsts-tasks#6960]
The build returns the following output when executed with _system.debug=true_.

> 2018-04-12T08:48:41.8766583Z ##[debug]Absolute path for pathSegments: D:\Agents\TFS18\1\bin/ant = D:\Agents\TFS18\1\bin\ant
2018-04-12T08:48:41.8766583Z ##[debug]Absolute path for pathSegments: D:\Agents\TFS18\1\bin/ant = D:\Agents\TFS18\1\bin\ant
2018-04-12T08:48:41.8766583Z ##[debug]check path : null
2018-04-12T08:48:41.8922835Z ##[debug]Failed which: Not found ant: null
2018-04-12T08:48:41.8922835Z Error: Failed which: Not found ant: null

I don't know why _D:\Agents\TFS18\1\bin\ant_ is used as path, we haven't specified this path in the task anywhere.

In the ant-task the "_Set ANT_HOME Path_" is set to the ant folder (C:\Program Files\apache-ant-1.10.1).

The system variable "_ANT_HOME_" (C:\Program Files\apache-ant-1.10.1) is set and the PATH points to "_%ANT_HOME%\bin_" on the machine executing the agent.

However, this should not matter due to the setting in the ant-task.

We are using Microsoft Visual Studio Team Foundation Server
Version 16.122.27409.2. We use an agent created with this version.

The BuildDefinition was imported from our old Microsoft Visual Studio Team Foundation Server
Version 14.114.26403.0.

**Comment by kelliejos** [comment]
@anvog Can you share the full build logs (set system.debug=true) to help us debug into this issue further?

**Comment by madhurig** [comment]
@anvog: There is an issue in the task that you are running into. If multiple paths for "ant" are found in the PATH, the behavior is to pick the first one. That is where "D:\Agents\TFS18\1\bin\ant" is coming from. ANT_HOME specified in the task should take precedence and it is not. The issue exists in current version of the task in VSTS as well. We will look into a fix and provide a version that you can upload to your TFS server. 

Thanks,
Madhuri

**Comment by madhurig** [comment]
@vinaysandela @anvog : On further investigation it looks like there is an issue with ant setup on your agent. 
If you notice the log, there is no ant.bat found, all the paths detected are folders/directories, not an "executable" tool. Please run "where ant" on your agent from a command prompt and please check if there is an ant.bat installed on the server correctly. If it is, please let us know which version of ant it is.

Thanks,
Madhuri

**Comment by joshmgross** [comment]
Closing this issue to clean up the backlog. Reopen this if the issue presents itself again.

**Comment by kulsandesh** [comment]
I am getting this error when I run build pipeline in azure 
##[error]Error: Not found antBuildFile: /home/vsts/work/1/s/build.xml

please suggest
thanks 
Sandesh
