### ISSUE TITLE
Help text for the version information in DotNetCoreInstaller task is not appropriate

### ISSUE THREAD

**Issue by sachinma** [Microsoft/vsts-tasks#6967]
•	The tooltip for the version field points to the CSV with the released versions, and the first two columns there read ‘version-runtime’ and ‘version-sdk’
•	Those version strings are not the ones to use and fail if doing so!
•	Instead the version from the macOS runtime or SDK (depending on use case) column has to be taken and only the version part taken from the string, e.g.
 
dotnet-sdk-2.1.300-preview2-008530-osx-x64.tar.gz is inside the column ‘sdk-mac-x64’, the correct version string for the tool runner on VSTS is ‘2.1.300-preview2-008530’

**Comment by ds-ms** [comment]
Duplicate issue. Following up here: https://github.com/Microsoft/vsts-tasks/issues/7032
