### ISSUE TITLE
Variable substitution not working for nested JSON tokens

### ISSUE THREAD

**Issue by vigneshmsft** [Microsoft/vsts-tasks#6986]
I originally raised this issue in vsts-agent but was asked to raise it here.

I have the below JSON schema in my appsettings.json
![image](https://user-images.githubusercontent.com/10269434/38724140-2f4ef5cc-3efb-11e8-89f2-43e1670d5ca9.png)

and the below variable in my release variable set in VSTS

![image](https://user-images.githubusercontent.com/10269434/38724229-7a32d612-3efb-11e8-8f1d-a1b921cd6fbc.png)

If you are unable to view the image, I have values set for
Api.Income.url & Api.PersonalInformation.url in release scope.

But once the deployment is complete, I can only see the variable getting substituted for
Api.PersonalInformation.url and not the next element.

Is this is a bug or am I doing something wrong?

Also I would like to access the variables in the sameway as I do it from code,
for example in code I would access these variables using the path
["Api:Income:Url"], ["Api:PersonalInformation.Url"] and this is also case insensitive
and this also allows me to have a dot(.) in the JSON token
for example I could have the below structure

![image](https://user-images.githubusercontent.com/10269434/38724624-b6da2f56-3efc-11e8-8ef2-e1873d986956.png)

But this won't work with VSTS variable substitution as VSTS looks at dot (.) as an element separator.

Thanks

**Comment by vincentdass** [comment]
@vigneshmsft , this issue is not repro-able from my side.
![image](https://user-images.githubusercontent.com/20121508/38792496-de19b184-416a-11e8-9e1d-b29988999e2e.png)
![image](https://user-images.githubusercontent.com/20121508/38792511-ea2d7a8c-416a-11e8-99bd-4ad9f47b07b5.png)

Also, you can substitute attributes that contains dot (.) characters using the same variables that we set above.
![image](https://user-images.githubusercontent.com/20121508/38792544-1cbb0d5c-416b-11e8-8ab9-0c2038bdf64b.png)

Please share the debug logs (set `system.debug` to `true` and rerun the release) to `RM_Customer_Queries@Microsoft.com`

**Comment by vigneshmsft** [comment]
Thanks @vincentdass , can you also try reproducing with the entire JSON schema like I have?

```
`{
  "Version": "Local",
  "Logging": {
    "LogPath": "logPath",
    "InstrumentationKey": "myinstrumentationKey",
    "IncludeScopes": false
  },
  "Database": {
    "MyDatabaseName": {
      "connectionString": "OldDatabaseConnectionString"
    }
  },
  "ServiceBus": {
    "connectionString": "serviceBusConnectionString"
  },
  "Api": {
    "Income": {
      "url": "",
      "nextToken":  "" 
    },
    "Expenditure": {
      "url": "",
      "nextToken": ""
    }
  }
}`
```

**Comment by vincentdass** [comment]
@vigneshmsft ,I have tried the above JSON and it works well with JSON substitution.
Can you please share the logs to `RM_Customer_Queries@Microsoft.com` to debug?

**Comment by vigneshmsft** [comment]
I have sent the Release logs to the provided email address.
Also if it helps I have the variables in two scopes
one for '`Release`' (which would apply to all environments) 
and one for '`Production`' (assuming specific environment scope would override the '`Release`' scope)

Thanks

**Comment by vigneshmsft** [comment]
Thanks Vincent for pointing I had a output variable named `Api.Income.Url` 
and which conflicted with `Api.Income.url`.
The substitutions are working after I removed the output variable.
