### ISSUE TITLE
Jenkins JenkinsQueueJob: build is kicked off correctly but is stuck in polling indefinetly 

### ISSUE THREAD

**Issue by vijaytripathi** [Microsoft/vsts-tasks#6990]
## Environment
- Server - VSTS
    
## Issue Description
Jenkins QueueJob step in VSTS build definition kicks off Jenkins job correctly, but this job is long running job for almost 20-30 hours. During polling it stops showing any output and on cancelling vsts task throws below error, suggesting it lost access to Jenkins in middle of run. Is there some kind of setting need to be enabled on vsts/jenkins side to have long connection or this could be some other issue

Also on Jenkins side this job eventually completes its pipeline in 24 hours 

**VSTS Job details:**
Simple 2 step to show all environment variable and trigger jenkins job with some parametes and wait for it to complete

**Jenkins Job Details**:
This is scripted pipeline calling other pipeline job.

### Error logs
**Error on cancelling after 15 hours** 

2018-04-12T03:32:46.1705005Z HttpResponse.statusCode=401
2018-04-12T03:32:46.1705005Z HttpResponse.statusMessage=Invalid password/token for user: ********
2018-04-12T03:32:46.1705005Z HttpResponse=

2018-04-12T21:50:49.7704160Z ##[error]The operation was canceled.
2018-04-12T21:50:49.7704160Z ##[section]Finishing

**Comment by kelliejos** [comment]
@vijaytripathi Can you share build logs (set system.debug=true) to help us debug into this issue further? Also, can you check if the timeout is set to 0 in the task? You can find it in the Control Options section of the task. Setting the timeout to 0 will specify an infinite timeout for the task.

![image](https://user-images.githubusercontent.com/31480321/38829896-8e55162a-4188-11e8-90b4-3bbcc269cc64.png)

**Comment by joshmgross** [comment]
Closing this issue to clean up the backlog. Reopen this if the issue presents itself again.
