### ISSUE TITLE
DownloadBuildArtifacts: improve error message for loc.messages.BuildArtifactNotFound

### ISSUE THREAD

**Issue by NenoLoje** [Microsoft/vsts-tasks#6991]
The following error message could be improved:

`"loc.messages.BuildArtifactNotFound": "Artifact %s not found for build %s"`

Found in file: [vsts-tasks/Tasks/DownloadBuildArtifacts/Strings/resources.resjson/en-US/resources.resjson](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/DownloadBuildArtifacts/Strings/resources.resjson/en-US/resources.resjson) 

__Background__:
Often the error message appears in a multi-phase build or release definition, where the dependencies between the phases have not been defined correctly (which the user must do explicitly).

__Suggestion__:
Maybe add a hint to the error message to double-check the dependencies between the phases (e.g. *"are the dependencies between phases set correctly?"*).

Thanks,
--Neno

**Comment by GitHubSriramB** [comment]
@NenoLoje - good suggestion. We will take up this improvement shortly.

**Comment by GitHubSriramB** [comment]
Since this is a Build scenario, @madhurig - could you take a look at this suggestion?

**Comment by bryanmacfarlane** [comment]
That suggestion should probably be created @ developer community.  The issues in this repo are for the tasks (/Tasks) in this repo.

**Comment by bryanmacfarlane** [comment]
I thought you were suggesting us analyzing the graph service side and warning (and why Sriram suggested build look at it).

Re-opening and moving back to Sriram since it's the same task used in build and release.

**Comment by madhurig** [comment]
I think the feedback here is about using the task in Build. This is new guidance for downloading artifacts produced by a different phase of the build. Users have to set that up on their own in Build since we don't inject the tasks and could be making mistakes. I will follow up on this.
