### ISSUE TITLE
Purpose of make.json

### ISSUE THREAD

**Issue by atlastodor** [Microsoft/vsts-tasks#6992]
This may not be the correct place to ask this question, but I couldn't find any sources on this.

What is the purpose of make.json and how to use it?

I am writing a custom build task, where the PowerShell script will need to access additional assemblies. I am having problems referencing those, especially the binding redirects that are normally given in the .config file. I've seen some tasks (PublishSymbols) that have make.config with assembly references.

Are there examples on how to use make.json, or is this the wrong path? 

PS: Running on TFS 2018 Update 2, on premise.

**Comment by bryanmacfarlane** [comment]
This is a whitelist file for our build scripts in this repo (make.js).  The make.js script is just a wrapper over tsc.  It isn't related to specific powershell concepts or anything runtime of a task.

**Comment by atlastodor** [comment]
Thanks. 
Could you give me a hint on how to tweak Powershell to respect the .config file for .Net and reference the correct external assemblies?

**Comment by bryanmacfarlane** [comment]
you may want to ask that in the vsts-task-lib repo.  I'll have @ericsciple look at it.
