### ISSUE TITLE
Test not found when rerun in VsTest on VSTS

### ISSUE THREAD

**Issue by holgoloid** [Microsoft/vsts-tasks#7003]
### Task: Visual Studio Test

When using the "Rerun failed tests" option the rerun can't find the failed test. 
The logs look like this: 

```
**************** Rerunning failed tests for Test run 4951 *********************
Max attempts: 3; Current attempt: 1; Failed test cases threshold: 30; Failed test cases max limit: 0
[command]C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe @C:\TestAgents\1\_work\_temp\tmpF076.tmp
Microsoft (R) Test Execution Command Line Tool Version 15.0.26929.2
Copyright (c) Microsoft Corporation.  All rights reserved.
vstest.console.exe /TestCaseFilter:"FullyQualifiedName=Easyfy.Commerce.Web.TestsUI.CheckoutTests.Easyfy.Commerce.Web.TestsUI.CheckoutTests.AddToBasket"
"C:\TestAgents\1\_work\r4\a\uitests\Easyfy.Commerce.WebTestsUI.dll"
/logger:"trx"
/TestAdapterPath:"C:\TestAgents\1\_work\r4\a"
Starting test execution, please wait...
Information: [xUnit.net 00:00:00.6904083]   Discovering: Easyfy.Commerce.WebTestsUI
Information: [xUnit.net 00:00:01.1349037]   Discovered:  Easyfy.Commerce.WebTestsUI
Information: [xUnit.net 00:00:01.1473315]   Starting:    Easyfy.Commerce.WebTestsUI
Information: [xUnit.net 00:00:01.1998463]   Finished:    Easyfy.Commerce.WebTestsUI
Warning: No test is available in C:\TestAgents\1\_work\r4\a\uitests\Easyfy.Commerce.WebTestsUI.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
Information: Additionally, you can try specifying '/UseVsixExtensions' command if the test discoverer & executor is installed on the machine as vsix extensions and your installation supports vsix extensions. Example: vstest.console.exe myTests.dll /UseVsixExtensions:true
**************** Completed test execution *********************
```

All tests are found in the initial run and all pass except AddToBasket in this example. 
We suspect that the problem is the /TestCaseFilter which seems to have the namespace (Easyfy.Commerce.Web.TestsUI.CheckoutTests) added twice. 
We tested this by running the test locally with /TestCaseFilter:"FullyQualifiedName=**Easyfy.Commerce.Web.TestsUI.CheckoutTests.AddToBasket**" and the test was found. 

The tests are Selenium tests run with XUnit on a local server.

[Complete test run log: rerun-test-not-found.txt](https://github.com/Microsoft/vsts-tasks/files/1916488/rerun-test-not-found.txt)

**Comment by nigurr** [comment]
@holgoloid sorry for delayed response. Can you please let us know what type of tests are these (datadriven?)

**Comment by holgoloid** [comment]
No worries!
The tests are simple Selenium C# tests without any data inputs or connections. 
AddToBasket from the example above looks like this:

```
namespace Easyfy.Commerce.Web.TestsUI {
  public class CheckoutTests : UITestClass {
    [Fact, UITest]
    public async Task AddToBasket() {    
      // Go to some pages, click some buttons.. 
    }
  }
}
```

UITest is a custom attribute.

**Comment by nigurr** [comment]
@holgoloid can you please share the TRX after first run?

**Comment by holgoloid** [comment]
Sure, the trx doesn't seem to be saved from the run in the logs above but I ran a new deployment, deliberately failed the same test and got the same behaviour. 
Here is the trx: 
[AgentRunner_EASYBUILD 2018-05-07 15_48_19.zip](https://github.com/Microsoft/vsts-tasks/files/1980107/AgentRunner_EASYBUILD.2018-05-07.15_48_19.zip)

**Comment by nigurr** [comment]
@holgoloid thanks for sharing information. It's confirmed as bug, fix is committed and we will roll out this fix within 2-3 weeks.
