### ISSUE TITLE
Service Fabric deploy broken if Application Type is still registered

### ISSUE THREAD

**Issue by nforysinski** [Microsoft/vsts-tasks#7028]
## Environment
- Server - VSTS
    
  Account Name: mongoose-r
  Team Project Name: sms
  Release Definition: service-fabric-dev (ID: 15)
  Example build number: service fabric dev - 673 (ID: 2678)
 
- Agent - Hosted
   Name: Hosted Agent

## Issue Description

Service fabric app deploy version 1.7.5

We created a repeatable task group with a single task for deploying service fabric apps. They all share the same general setup and configuration. All of them fail with the same error (see error logs below). 

The general steps to reproduce are:

1. Deploy an app to a fresh service fabric server cluster with no existing application types registered
2. See that the app is deployed and working under its associated application type
3. Delete the app, but dont unregister the application type
4. Run the deploy again and see it fail

### Error logs

`
2018-04-19T19:59:01.0498928Z Successfully connected to cluster.
2018-04-19T19:59:01.1202649Z Searching for path: D:\a\r1\a\**\drop\...\Dev.xml
2018-04-19T19:59:01.3225545Z Found path: D:\a\r1\a\service-fabric-dev\drop\...\Dev.xml
2018-04-19T19:59:01.3233143Z Overriding application parameter file specified in publish profile with 'D:\a\r1\a\service-fabric-dev\drop\...\Dev.xml' specified in the VSTS task.
2018-04-19T19:59:01.3249986Z Overriding upgrade settings specified in publish profile with the settings specified in the VSTS Task.
2018-04-19T19:59:04.5358410Z ##[error]A parameter cannot be found that matches parameter name 'ApplicationTypeName'.
2018-04-19T19:59:04.6007338Z ##[section]Finishing: Deploy Service Fabric Application
`

**Comment by kuvinodms** [comment]
@nforysinski Unable to repro the failure scenario by following the steps mentioned by you.
Please share your task's debug logs.

**Comment by nforysinski** [comment]
@kuvinodms got an email I can mail you the full log zip with all associated tasks?

**Comment by kuvinodms** [comment]
Yes, please mail it to kuvinod@microsoft.com

**Comment by nforysinski** [comment]
@kuvinodms just emailed the logs to you. let me know if you need anything else.

**Comment by kuvinodms** [comment]
Got the mail. Expect an update on it by tomorrow EOD.

**Comment by kuvinodms** [comment]
@nforysinski 
Please add following debug variable in your release definition and re-initiate the release. Forward/attach the generated logs.

Name - system.debug
Value - true

**Comment by NickDarvey** [comment]
We're also seeing this.

(I'd love to give you these logs but when I'm downloading it I get a: `"typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000`)

**Comment by NickDarvey** [comment]
I think it was [this issue](https://developercommunity.visualstudio.com/content/problem/204067/vsts-service-fabric-deployment-task-171-error.html). 
@nforysinski have you tried using Hosted VS2017 as your agent?

**Comment by kuvinodms** [comment]
@NickDarvey Thanks for providing the issue link and your debug logs.
I was going through your logs and have 1 thing to confirm. Did you delete the application before triggering the release?

**Comment by nforysinski** [comment]
@NickDarvey we changed to Hosted VS2017 yesterday and everything went fine this morning. I don't yet have a failing log with System.Debug turned on, so I am watching that carefully.

@kuvinodms I can't speak for @NickDarvey but I can say we definitely we did not delete the application as we expected the non-upgrade deployment task to take care of that.

**Comment by bishal-pdMSFT** [comment]
@NickDarvey @nforysinski Service fabric tasks will most probably run into problems with Hosted agent pool - as the installed SF SDK (on which the task takes dependency) is quite old.
I would strongly recommend using Hosted VS2017 pool which gets updated often. Please let us know if you see same issue with Hosted VS2017.

**Comment by kuvinodms** [comment]
Feel free to reopen if you still face this issue.
