### ISSUE TITLE
"Azure Service Fabric Application with Docker Support" template does not create BuiltDockerImages.txt

### ISSUE THREAD

**Issue by OguzPastirmaci** [Microsoft/vsts-tasks#7030]
## Environment
- Server - VSTS or TFS on-premises?
    VSTS
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
oguzp-msft, ***, oguzp-SF-Test, #20180420.1

- Agent - Hosted or Private: 
    Both hosted and private has the same issue.
    - If using Hosted agent, provide agent queue name:
Hosted VS2017
    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Windows 10, 2.131.0
## Issue Description
When using the "Azure Service Fabric Application with Docker Support" template, Tag Images job fails with the below error in error logs.

**Msbuild arguments in SF build job:** /t:Package /p:PackageLocation=$(build.artifactstagingdirectory)\applicationpackage;BuiltDockerImagesFilePath=$(build.artifactstagingdirectory)\BuiltDockerImages.txt

**Image Names Path in Tag Image job:** $(build.artifactstagingdirectory)\BuiltDockerImages.txt

### Error logs

2018-04-19T23:10:38.5670291Z ##[error]Unhandled: Not found imageNamesPath: C:\agent\_work\2\a\BuiltDockerImages.txt

**Comment by odaibert** [comment]
I have the same issue here.

**Comment by NCarlsonMSFT** [comment]
Are you using a project that was created using the preview tools: https://blogs.msdn.microsoft.com/azureservicefabric/2017/10/12/visual-studio-2017-service-fabric-tools-2-0-preview/
If not then your project will not be configured to create the correct assets.

**Comment by NCarlsonMSFT** [comment]
FYI the tooling corresponding to this build definition is now available in the VS 2017 Preview Channel: https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-preview-relnotes#SFTools

If you create a project using this new experience that should work with the "Azure Service Fabric Application with Docker Support" template

**Comment by bishal-pdMSFT** [comment]
@NCarlsonMSFT is https://blogs.msdn.microsoft.com/azureservicefabric/2017/10/12/visual-studio-2017-service-fabric-tools-2-0-preview/ a preview version of https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-preview-relnotes#SFTools ?

**Comment by NCarlsonMSFT** [comment]
@bishal-pdMSFT yes, the tools in https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-preview-relnotes#SFTools are the latest version of the feature, now available in the standard Visual Studio preview channel.

**Comment by sachinma** [comment]
closing this issue. Please reopen if this doesn't work with the recommended VS version.
