### ISSUE TITLE
Azure subscription parameter should allow variables

### ISSUE THREAD

**Issue by joe45sp** [Microsoft/vsts-tasks#7042]
Hi, I am making heavy use of task groups and having to create a separate task group per Azure subscription really defeats the purpose of task groups. Is there a way for you guys to quickly allow this setting to have variables instead of hardcoding the Azure subscription? An example task that this is used in is: Azure Resource Group Deployment Task

**Comment by KrishnaAdityaB** [comment]
@RoopeshNair @kmkumaran @GitHubSriramB

**Comment by RoopeshNair** [comment]
You don’t have to create multiple task groups for each subscription. You can parametrize the subscription field and use the same task group across definitions. Note, you will have to use the subscription drop-down in the definitions, (variables not supported in the build/release definition for the subscription field)

1)	In the task group where Azure RM subscription is specified and enter $(mysubscription) in the Azure Subscription field in the Azure Powershell or any Azure task.
 
![image](https://user-images.githubusercontent.com/1370480/39246045-125f7484-48b3-11e8-99c2-9194b1561af6.png)

2)	Now you will it added as a parameter and you will see in the parameter list.
3)	Once it is available as a parameter you can configure different value in each environment.

**Comment by KrishnaAdityaB** [comment]
I misunderstood the question - I thought the ask was to parameterize Service Endpoint input in task. But the ask was to do it in task-groups.
As Roopesh mentioned, it is available already. Removing the _enhancement_ and _feature request_ tags. And closing the thread.

**Comment by joe45sp** [comment]
@KrishnaAdityaB @RoopeshNair @kmkumaran @GitHubSriramB this might have worked at some point, but it is not working for me at all. Here is the result:

<img width="812" alt="screen shot 2018-06-14 at 1 08 58 am" src="https://user-images.githubusercontent.com/564767/41392644-ee9ac36c-6f6f-11e8-8d9c-23989354b526.png">
<img width="264" alt="screen shot 2018-06-14 at 1 10 12 am" src="https://user-images.githubusercontent.com/564767/41392645-eea785de-6f6f-11e8-9366-cc6f514c37f4.png">

Please let me know as quickly as possible as we need to push to production asap and doesn't make sense to create another task group just to do this.

**Comment by sorosoro2** [comment]
@joe45sp , Is this specific to this task group, or are you facing this issue, in other task groups as well?

Can you share the json of the task group with me? It will be right hand side of the latest revision under your history tab

**Comment by RoopeshNair** [comment]
@joe45sp - you need to set the value for the endpoint from the task input, you can't pass a variable. 
Just to re-iterate, Task group accepts variables for endpoint, task doesn't accept. Hope it helps

**Comment by joe45sp** [comment]
@RoopeshNair can you please provide an example on how to do this with screenshots? The only way I know how to add variables to a task group is by setting a variable inside of a task in the task group itself. Here is the example article I found on how to to this and this doesn't work for me. Other than this, I have found now detailed examples on how to do this. [https://colinsalmcorner.com/post/tip-creating-task-groups-with-azure-service-endpoint-parameters](url)

**Comment by joe45sp** [comment]
@RoopeshNair @kmkumaran @KrishnaAdityaB @GitHubSriramB please respond quickly, as I need to hit production today and need this working. If one of you can either provide detailed examples with screenshots on how to to this, or do a screen share with me to walk me through it, that would be awesome. In @RoopeshNair example above, he specifically shows that you can put a variable for the Azure Subscription field:

In the task group where Azure RM subscription is specified, enter $(mysubscription) in the Azure Subscription field in the Azure Powershell or any Azure task.
image
![aaaaa](https://user-images.githubusercontent.com/564767/41411394-b5926bd4-6faa-11e8-995c-2af1e6745254.png)
Now you will see in the parameter list for the task group
In the build/release definition, you can specify different values using the subscription drop-down

**Comment by RoopeshNair** [comment]
@joe45sp  - can you please save, clear browser cache and try again?

**Comment by sorosoro2** [comment]
@joe45sp , please share the json on the right hand side of your latest revision from history, if possible
