### ISSUE TITLE
Running automated test cases with the same test method via Release

### ISSUE THREAD

**Issue by RoyRosenberg** [Microsoft/vsts-tasks#7050]
Hello,
I Hope I’m in the right repo…

## Description
>We use TFS 2018.1 on premise
When [running automated test cases](https://docs.microsoft.com/en-us/vsts/build-release/test/run-automated-tests-from-test-hub?view=vsts) when each test case is associated with test method, the tests run as expected.
We need the ability to associate the same test-method to multiple test cases, in this case when selecting and invoking multiple test cases from the test hub, the release is started but fails with this error: 
**RunMessage : An exception occurred while invoking executor 'executor://mstestadapter/v1': An item with the same key has already been added**

## Steps to reproduce
> It is very simple to reproduce just:
•	Create a unit test project and create single test method (i.e. TestMethod01)
•	Create a build definition to build the test project
•	Open multiple test cases in VS and associate the test cases to TestMethod01, click save
•	In web access, under test, set the test plan to use the appropriate release definition and build definition
•	From the test hub, select single (automated) test case and click run. In this case a release is being triggered and the test should run because the test run contains single test case
•	From the test hub select multiple test case with the ctrl key and click run, in this case the release will fail with the above message 

## Expected behavior
> Visual Studio Test task should be able to run the same test method 

10x!!
Roy

**Comment by abhishkk** [comment]
@RoyRosenberg We are able to repro this issue. We are working on the fix which is required both on VS side and task side.

**Comment by Viktoryath** [comment]
Hi, 
We're facing the same issue also, when will you apply a fix? This feature is important for us and we just upgraded our TFS to 2018.1 for that...
Thank you,
Victoria

**Comment by nigurr** [comment]
Hi,

Sorry for the trouble. We identified the issue and fixed the bug. We will be sharing the hot-fix soon so that it can unblock your test runs.
To mitigate this issue, if you have duplicated test cases associated to same test method, please remove one of them as automated.
