### ISSUE TITLE
MSB4019 - Sdk.props was not found

### ISSUE THREAD

**Issue by dev4fams** [Microsoft/vsts-tasks#7057]
## Troubleshooting
Build process fails with **MSB4019**.  The solution contains a .Net Standard 2.0 project and the rest of the projects are .Net Framework 4.7

## Environment
VSTS Online 

- Agent - Private: 
Using a Private Host but appears to work under the Hosted VS2017.  Company requires I use the private host for security concerns.

## Issue Description
Tasks included

- .Net Core Tool Installer, 2.1.105
- NuGet Tool Installer >=4.6.2
- NuGet Restore
- MSBuild

**Comment by bryanmacfarlane** [comment]
This is an issue with your private machine and the tools installed.

I assume when it works on hosted vs2017, those same tasks are involved.  The difference being the configuration and installation of the tools on that private machine.

The logs show exactly what command lines we run so you can repro on that private machine.

Fortunately the process we use to generate the image is open sourced:

https://github.com/Microsoft/vsts-image-generation

You can use it to build your own VM and/or troubleshoot.
