### ISSUE TITLE
Azure function failed to deploy with the error ERROR_CONNECTION_TERMINATED

### ISSUE THREAD

**Issue by njangir2** [Microsoft/vsts-tasks#7060]
## Environment
Visual Studio 
## Issue Description
I am trying to deploy the azure function using visual studio and getting the error: Web deployment task failed (Complete error logs are given below).
I have followed all the steps mentioned in the article http://techgenix.com/video-publish-azure-functions-azure-using-visual-studio-tools-azure-functions/ but still facing the issue.
Please help me as I have spent a lot of time on this issue and didn't get any solution.
### Error logs

1>------ Build started: Project: TestFunction, Configuration: Release Any CPU ------
1>TestFunction -> C:\Repo\TestFunction\TestFunction\bin\Release\net461\bin\TestFunction.dll
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
  Publish Started
  TestFunction -> C:\Repo\TestFunction\TestFunction\bin\Release\net461\bin\TestFunction.dll
  TestFunction -> C:\Repo\TestFunction\TestFunction\obj\Release\net461\PubTmp\Out\
C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : Web deployment task failed. (Web Deploy experienced a connection problem with the server and had to terminate the connection.  Contact your server administrator if the problem persists.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CONNECTION_TERMINATED.) [C:\Repo\TestFunction\TestFunction\TestFunction.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error :  [C:\Repo\TestFunction\TestFunction\TestFunction.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : Web Deploy experienced a connection problem with the server and had to terminate the connection.  Contact your server administrator if the problem persists.  Learn more at: http://go.microsoft.com/fwlink/?LinkId=221672#ERROR_CONNECTION_TERMINATED. [C:\Repo\TestFunction\TestFunction\TestFunction.csproj]
C:\Program Files\dotnet\sdk\2.1.300-preview1-008174\Sdks\Microsoft.NET.Sdk.Publish\build\netstandard1.0\PublishTargets\Microsoft.NET.Sdk.Publish.MSDeploy.targets(139,5): error : Root element is missing. [C:\Repo\TestFunction\TestFunction\TestFunction.csproj]
  Publish failed to deploy.

**Comment by vincentdass** [comment]
Please open a thread [here](https://developercommunity.visualstudio.com/spaces/8/index.html) for VS related issues.
