### ISSUE TITLE
SqlAzureDacpacDeployment allow override with Additional SqlPackage.exe Arguments

### ISSUE THREAD

**Issue by aaronhoffman** [Microsoft/vsts-tasks#7068]
## Enhancement request

Enable the SqlAzureDacpacDeployment task to be more flexible by allowing the default SqlPackage.exe arguments to be overridden.

Example: I would like to override the `/Action:` parameter to be `DeployReport` or `Script` ([more info](https://docs.microsoft.com/en-us/vsts/build-release/apps/cd/sql-server-actions?view=vsts))

However, at this time, it will always be set to `Publish`:
https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/SqlAzureDacpacDeployment/Utility.ps1#L181

If you provide an `/Action:` parameter in the `Additional SqlPackage.exe Arguments` variable, it will just be appended to the command [here](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/SqlAzureDacpacDeployment/Utility.ps1#L227) and the Release/command will fail with a `Duplicate 'Action' argument` exception.

**Comment by Ajay-MS** [comment]
@aaronhoffman 

Thanks for your feedback request. We already have a story to support other actions apart from publish. Though I am not sure about timelines yet. Will let you know regarding that.

**Comment by Ajay-MS** [comment]
@aaronhoffman 

@asranja  has raised [PR - Support all actions of SQL Package.exe](https://github.com/Microsoft/vsts-tasks/pull/7216) for the above-mentioned feature. This feature will be available approx after 3 weeks after PR being merged to master.
