### ISSUE TITLE
Can't release to a webapp that has letters å, ä, ö

### ISSUE THREAD

**Issue by KrishnaAdityaB** [Microsoft/vsts-tasks#7080]
set up a webapp name 'göm-mig-från-omvärlden'. 
All works fine and we can navigate to it (göm-mig-från-omvärlden.azurewebsites.net). 

But when we try to make a release from VSTS it state that the resource 'göm-mig-från-omvärlden' does not exist.

It seems our Azure webapp task does not handle the special characters.

**Comment by vincentdass** [comment]
fixed in M134. the fix will be available in next deployment.
