### ISSUE TITLE
No CMake or Ninja Tool Installer

### ISSUE THREAD

**Issue by schultetwin1** [Microsoft/vsts-tasks#7108]
Currently there is a go, java, node, nuget, and VsTestPlatform tool installer in this repo. I'd love to see a [cmake](https://cmake.org/) and [ninja ](https://ninja-build.org/) tool installer as well. If I build out the tool installer tasks and tests for cmake and ninja, would it make sense to put those tasks here? Or would it be preferred for me to create a new extension.

**Comment by brcrista** [comment]
Is there any reason to be able to choose a version of CMake or Ninja at build time?  That's the story behind tool installers.  (My impression is there's no benefit -- you always want the latest version.)

We already have a CMake task, and the hosted agents have CMake installed.  If you are running a private agent, just install CMake yourself and use the task.  With Ninja, you can likewise install it, add it to PATH, and call it from the command line in later steps.

**Comment by schultetwin1** [comment]
I had a different view of what tool installers will be used for. From the [website](https://docs.microsoft.com/en-us/vsts/build-release/concepts/process/tasks?view=vsts#tool-installers) describing tool installers, they mention one benefit of tool installers as:

>Install a tool or runtime on the fly (even on hosted agents) just in time for your CI build.

That was the main benefit I saw when I first read about tool installers. Having nuget as tool installer is a good example of this.

For CMake, you would no longer need to have cmake on your hosted agents, and those administering private agents do not need to worry about installing cmake or maintaining cmake installations. 

For ninja, this provides a convenient way to get Ninja in your path on hosted agents without needing to write custom scripts (which would be fairly trivial with the package managers on Linux or Mac, but not as trivial on Windows). On private agents, it takes a burden of the admins of the agents of keeping ninja up to date.

All that being said, I understand not wanting to oversee a multitude of different tool installer tasks that ship by default with VSTS. I could place the ninja and cmake tool installers in a separate extension.

**Comment by bryanmacfarlane** [comment]
Yeah, an extension would be great.  That's why we also created the vsts-task-toollib so others can create.  Shouldn't be too hard to create.  You can create issues on that repo if you bump into a problem.

Closing off suggestion.  Thanks!
