### ISSUE TITLE
Code Coverage is wrong due to pdbs being picked up outside the build work folder

### ISSUE THREAD

**Issue by Rutix** [Microsoft/vsts-tasks#7118]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
TFS on-premises
    
    - If using TFS on-premises, provide the version: 
Team Foundation Server 2017 Update 3

- Agent - Hosted or Private: 
Private

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
vsts-agent-win7-x64-2.117.2

## Issue Description

We run code coverage on all our builds. We are getting weird measures when the build server has also build the nuget package the current project is using.
Reproduction scenario:
- Make a library solution with for example as output a nuget package.
- build this on the build server and let it publish the nuget package.
- Make a new solution with a new build definition which uses the nuget package.
- Run the build definition on the same build server as previous build definition.
- The code coverage ends up lower then the one run locally in visual studio.
- Open the code coverage results file and see it has added the .dlls of the nuget package and therefore counts that to the total measure.

**Screenshots:**
_This build is run on the build server which also build some of the dependencies:_
![image](https://user-images.githubusercontent.com/241452/39516651-d87a8e0c-4dfd-11e8-8dfa-d27f901faa74.png)
![image](https://user-images.githubusercontent.com/241452/39517034-fa2c2078-4dfe-11e8-8246-58a3f54d90bb.png)

_This is run on a new build server:_
![image](https://user-images.githubusercontent.com/241452/39516527-77a3b57c-4dfd-11e8-9d0d-7f4e9be1b84d.png)
![image](https://user-images.githubusercontent.com/241452/39516999-dd495e12-4dfe-11e8-910e-629f5d69b760.png)

While analyzing this we found this post:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/077ca57a-690f-4511-9bf3-1e58213966ad/code-coverage-including-build-dlls?forum=tfsbuild

This kinda describes the problem. The proposed solution is not desirable though because we want to keep the PDB's.

### Error logs
No error logs needed I think

**Comment by nigurr** [comment]
@Rutix 
Sorry for delay.
Can you please share the VsTest task configuration screenshot and the list of dlls present after the source code is built from Build/Release agent machine?

This can occur when we keep default Test Assembly path in VsTest v2 ("**\*test*.dll") and some framework adapter dlls present in the test assembly folder which are matching the search pattern.

**Comment by Rutix** [comment]
@nigurr 
Here is the screenshot of the task. Couldn't fit it fully on it so if you need a part which is not on it let me know.
The screenshots I made of the build server are the ones of the bin folder of the library and webapi. If you want to have the dll list of the bin folder of the test projects please let me know.
![screenshot-test-task](https://user-images.githubusercontent.com/241452/40612821-4f87ecfa-627c-11e8-9204-5c0df6d86b71.png)
![werkgever-cv-listdlls](https://user-images.githubusercontent.com/241452/40612827-5307078a-627c-11e8-82dc-c6e5b43100f9.png)
![webapi-dll-list](https://user-images.githubusercontent.com/241452/40612828-533229e2-627c-11e8-92e3-52cd388efd35.png)

**Comment by nigurr** [comment]
@Rutix can you strengthen the Test assembly pattern

`**\release\*test*.dll`

This filter makes sure that we are picking only test assemblies specific to your built assemblies.
If you have any common namespace in assemblies, you can use similar pattern 
`**\release\*Werkgever*.dll`

**Comment by Rutix** [comment]
@nigurr I strengthened the Test assembly pattern but that didn't solve the problem. It still gives wrong readings. For some reason it still finds .pdbs outside the agent/_work/<id> folder of that build definition. I assume when determing the code coverage it looks for .pdbs for all referenced .dlls and for some reason the search is going outside it's own agent/_work/<id> folder.

**Comment by mayankbansal018** [comment]
@Rutix can you please use runsettings to configure what modules you want coverage for.
Please follow https://msdn.microsoft.com/en-us/library/jj159530.aspx
Under the "ModulePaths" "Include" you can specify for what modules you are looking coverage info.

**Comment by Rutix** [comment]
@mayankbansal018 : I know of that option but that option is undesirable since it introduces another error prone option. In my opinion the default shouldn't look outside it's folder when searching for PDBs. Especially when Visual Studio does this right and thirdparty tools like SonarQube also do it right. Only the report in TFS is wrong.

**Comment by nigurr** [comment]
@Rutix one suggestion is don't publish your pdbs along with dll or publish them as separate package so that you can keep track of them. this should fix the issue. AFAIK, this is the only solution which we can suggest now

**Comment by Rutix** [comment]
Hi @nigurr . But we aren't publishing the pdb's along with the dll in that build definition.

It's like this:
**BuildDefinition 1** -> builds on the build server and ends up in: /_work/**1**/*
**BuildDefinition 2** -> builds on the build server and ends up in: /_work/**2**/*

Both build definitions only generate pdbs for their own project.

If **BuildDefinition 2** references dll's which were build in **BuildDefinition 1** and we enable code coverage in 
**BuildDefinition 2**, it finds the PDBs in /_work/**1**/* (which was generated by **builddefinition 1**). It goes outside it's own /_work/**2**/* folder. And that's not correct afaik, or atleast it's very unexpected behavior.

We don't really need a solution at this very moment (since we can work around it like @mayankbansal018 suggested) but it should be looked at and be fixed in a later version in my opinion. Right?

**Comment by ShreyasRmsft** [comment]
@Rutix what do you mean by BuildDefinition 2 references dll's which were build in BuildDefinition 1? 

Is BuildDefinition 2 freshly building these dlls again? It seems wrong to me if its re-using dlls built by another build definition. If it's building the same dlls again or fetching them via nuget then its fine but any other way doesn't seem right. Can you please clarify this?

**Comment by Rutix** [comment]
@ShreyasRmsft what I mean by references is that BuildDefinition 1 generates a nuget packages (not containing the PDBs) and that the code build by BuildDefinition 2 uses that nuget package. Does this clarify your question?

**Comment by ShreyasRmsft** [comment]
@Rutix so the problem here is that when the binaries that go into the nugget package are built the location to the corresponding pdbs are hardcoded onto the built dlls.

Now when these dlls are later used on the same machine CLR automatically tries to load them from the location hardcoded onto the dlls.

**Comment by ShreyasRmsft** [comment]
@Rutix there is another option wherein in the code you can add the exclude code coverage attribute https://msdn.microsoft.com/en-us/library/system.diagnostics.codeanalysis.excludefromcodecoverageattribute(v=vs.110).aspx

**Comment by Rutix** [comment]
@ShreyasRmsft The cleanup was kind of undesirable because we might have to debug the dlls when a consumer reports a problem with a specific nuget package. 

https://msdn.microsoft.com/en-us/library/hsa130k8.aspx <-- this seems to be a C++ option and we are building C# projects. Is there a same thing for .NET projects?

https://msdn.microsoft.com/en-us/library/system.diagnostics.codeanalysis.excludefromcodecoverageattribute(v=vs.110).aspx <--- we already use this but it would be weird to require our consumers to do this on every call to a library. And we can't add it in the library itself since we use CodeCoverage and unittests there too.

How do other MS (or MS itself) solve this? It doesn't seem an uncommon scenario in my opinion.

**Comment by ShreyasRmsft** [comment]
@Rutix wait how do customers get the pdbs for the nuget packages you publish? Wherever they get it from should be your primary source of getting the pdbs for debugging (or a local build) and the ones on the build agent machine. This is something we do atleast, we never depend on the ones present on the build agent machines.

**Comment by ShreyasRmsft** [comment]
@Rutix the recommended way (and the safest) is to use the runsettings to specify what you want coverage on (you can use regex here). Note: don't use the exclude filter but use the include filter to cover what you want.

**Comment by ShreyasRmsft** [comment]
@Rutix cleaning up the previous build should also be something you should be able to do. Just upload the pdbs as artifacts to vsts.

**Comment by Rutix** [comment]
@ShreyasRmsft Thanks for the suggestions. I will try those this week and discuss them with the team.

**Comment by ShreyasRmsft** [comment]
@Rutix closing the issue with the workarounds and recommendation provided on the intended way to limit the scope of the modules to be covered.

Please re-open if you end up getting more queries or run into any other problems later down the line.
