### ISSUE TITLE
Unable to execute .cmd file in post build event command line

### ISSUE THREAD

**Issue by sandeep571** [Microsoft/vsts-tasks#7130]
In my uitest project am able to execute .cmd file manually with RunAsAdmin but not with user mode and also tried by givien admin permission to user but not succeeded. From the TFS build process I need to execute .cmd file after build process. can any one help on this...
      file is there at specified path where i checked with verify cmds, but while executing from the location it says....."The system cannot find the file specified"..
Following is the error am getting..
 
Program 'runtests.cmd' failed to run: The system cannot find the file specifiedAt line:1 char:1 + . 'C:\agent_work\1\s\Testproject\runtests.cmd' + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~. At line:1 char:1 + . 'C:\agent_work\1\s\Testproject\runtests.cmd' + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : ResourceUnavailable: (:) [], ApplicationFailedException + FullyQualifiedErrorId : NativeCommandFailed

**Comment by bryanmacfarlane** [comment]
Not an issue with a CI/CD task in this repo.  You might want to follow up on developer community
