### ISSUE TITLE
Pattern mismatch error message does not display when creating Service Endpoint

### ISSUE THREAD

**Issue by scott-lin** [Microsoft/vsts-tasks#7143]
Please redirect me if this isn't the right area to file this issue.

## Environment
**VSTS**
**Account** - pyewpyew
**Project** - VstsExtensionTesting
**Release Definition Name** - TestRelease

**Agent** - Not applicable since task doesn't need to run to repro this issue.

## Issue Description

My release task requires a custom Service Endpoint which I have defined a definition for in my extension manifest. When creating a new endpoint in the VSTS UI, the user must provide a username, which is validated with a pattern that accepts strings of e-mail address or UUID format. I have validated the pattern enforces these requirements, however, when the pattern is not matched, I do not see the `patternMismatchErrorMessage` displayed on the UI (even after submitting with the OK button).

Here is a screenshot of an invalid username that violates my pattern. I was expecting to see my error message somewhere telling me why the value is not acceptable.

![image](https://user-images.githubusercontent.com/31644762/39650354-a4b7d73c-4f9c-11e8-9326-3d12ca9e7801.png)

Here is my input descriptor definition for this username field, which is attempting to augment the `ms.vss-endpoint.endpoint-auth-scheme-basic` authentication scheme type. I referred to [InputValidation documentation](https://docs.microsoft.com/en-us/rest/api/vsts/serviceendpoint/types/list#inputvalidation) for coming up with the `validation` object below.

```
{
    "type": "ms.vss-endpoint.endpoint-auth-scheme-basic",
    "displayName": "User or Client Credentials",
    "inputDescriptors": [
        {
            "id": "username",
            "name": "Username",
            "description": "Name of the user account (e-mail address) or identifier of client application (UUID).",
            "inputMode": "textbox",
            "isConfidential": false,
            "validation": {
                "isRequired": true,
                "dataType": "string",
                "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89ABab][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$|^(?:[a-z0-9!#$%&'*+\\/=?^_`{|}~-]+(?:\\.[a-z0-9!#$%&'*+\\/=?^_`{|}~-]+)*|\\\"(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21\\x23-\\x5b\\x5d-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])*\\\")@(?:(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?|\\[(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?|[a-z0-9-]*[a-z0-9]:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x21-\\x5a\\x53-\\x7f]|\\\\[\\x01-\\x09\\x0b\\x0c\\x0e-\\x7f])+)\\])$",
                "patternMismatchErrorMessage": "Value must be an e-mail address when using user credentials, or UUID when using client credentials."
            }
        },
        {
            "id": "password",
            "name": "Password",
            "description": "Password for the account above.",
            "inputMode": "passwordbox",
            "isConfidential": true,
            "validation": {
                "dataType": "string",
                "isRequired": true
            }
        }
    ]
}
```

Let me know if more details are required. Thanks.

**Comment by GitHubSriramB** [comment]
@scott-lin - we will investigate if this is an issue with service endpoint UI/API. Thanks for letting us know.

**Comment by gykuma** [comment]
Hey Scott, thanks for the feedback. The issue was in Service endpoint UI. The fix will roll out with next deployment.
