### ISSUE TITLE
Will VSTS kubectl task support patch command?

### ISSUE THREAD

**Issue by william726** [Microsoft/vsts-tasks#7151]
## Environment
- Server - VSTS or TFS on-premises?
    VSTS

- Agent - Hosted or Private: 
    Hosted Linux Preview

## Issue Description
Now the VSTS kubectl task offered by Microsoft only supports limited number of kubectl commands. Say I would like to use the patch command to update fields of the resource. Other than using third party developed VSTS task, is there a way to use the Microsoft kubectl task and be able to use the patch command, or will the next version of the task to support this?

**Comment by pjquirk** [comment]
The "Deploy to Kubernetes" task allows you to type in a command.  Have you tried doing this or are you seeing issues with this?

**Comment by bansalaseem** [comment]
As @pjquirk has replied, I am closing this issue
