### ISSUE TITLE
Running Rapise Test in Release Pipeline in VSTS

### ISSUE THREAD

**Issue by kontodos** [Microsoft/vsts-tasks#7153]
## Environment
I'm using VSTS, Hosted Agent

## Issue Description
My Test execution stops at "Starting test execution, please wait..." until it execution time out is reached.

### Error logs
No errors are shown.

![image](https://user-images.githubusercontent.com/7445712/39748376-82199b5e-52e2-11e8-866c-b3d2eb5a38ec.png)

**Comment by nigurr** [comment]
@kontodos Is it consistently happening? Can you please let us know if you can run the same tests using private agents?

**Comment by ShreyasRmsft** [comment]
@kontodos any updates here?

**Comment by prawalagarwal** [comment]
Closing this issue. Please reopen if you have more information. You can also reach out to us at devops_tools@microsoft.com
