### ISSUE TITLE
Adding GoogleServicesJson json to Android is breaking the XamariniOS Build Task.

### ISSUE THREAD

**Issue by RVoiseyFirstApp** [Microsoft/vsts-tasks#7156]
## Environment
- Server - VSTS
- Account Name: RobVoisey
- Team Account Name: biotaware
- Watchie-Xamarin.iOS-Dev-CI
- Build number 1160

## Issue Description

We have an application build with Xamarin Forms with two projects for Droid and iOS. Recently we added Firebase + push notifications to the Android project which meant including the GoogleServicesJson json tag in the project file which now looks like:

    <ItemGroup>
        <GoogleServicesJson Include="google-services.json" />
    </ItemGroup>

Both iOS and Android build on our local machines however the iOS build does not build on VSTS using the XamariniOS Build task (Android does).

If we commented out the above tag it builds without problem.

    <ItemGroup>
        
    </ItemGroup>

### Error logs

    Xamarin.iOS task failed with error Error: /Library/Frameworks/Mono.framework/Versions/Current/Commands/xbuild failed with return code: 1. For guidance on setting up the build definition, see https://go.microsoft.com/fwlink/?LinkId=760847.

    Errors:
    /Users/vsts/agent/2.133.3/work/1/s/Watchie.sln (default targets) ->
    (Build target) ->
    /Users/vsts/agent/2.133.3/work/1/s/Droid/Watchie.Droid.csproj (default targets) ->
    /Users/vsts/agent/2.133.3/work/1/s/packages/Xamarin.GooglePlayServices.Basement.60.1142.1/build/MonoAndroid80/Xamarin.GooglePlayServices.Basement.targets (SetupGoogleServicesJson target) ->
        : error : Error initializing task ConvertToAbsolutePath: Not registered task ConvertToAbsolutePath.
        8 Warning(s)
        1 Error(s)

**Comment by megraham** [comment]
I'm seeing a similar issue when building from the command line via xbuild. I switch from GCM to FCM, and that brought along some other nuget packages needed.

NugetPackages/Xamarin.GooglePlayServices.Basement.60.1142.1/build/MonoAndroid80/Xamarin.GooglePlayServices.Basement.targets (SetupGoogleServicesJson target) ->
					: error : Error initializing task ConvertToAbsolutePath: Not registered task ConvertToAbsolutePath.

**Comment by megraham** [comment]
I just cleaned my project and used msbuild in place of xbuild and everything built without errors. Installed the app on things are working so far. Any reason why xbuild wouldn't work, whereas msbuild does? I know it's going to be deprecated, but that might mean qualifying a new tool for some industries. :(

**Comment by madhurig** [comment]
@RVoiseyFirstApp: Can you please try switching to "msbuild"?

xbuild is the build tool for XamarinStudio which is being replaced by "Visual Studio for Mac". If you are using "VS for Mac" in your development environment, you should switch to "msbuild". We left xbuild as the default for backcompat but in the latest version of Xamarin iOS task we have removed "xbuild".

@megraham: Thank you for posting your solution. The Xamarin team and community will be better equipped to answer your question on why your build fails with xbuild. You can post it here if you want to follow up: https://forums.xamarin.com/ 

Thanks,
Madhuri

**Comment by joshmgross** [comment]
Closing this issue to clean up the backlog. Reopen this if the issue presents itself again.
