### ISSUE TITLE
Please re-open #4722:  AzureRmWebAppDeployment not using Kudu to deploy on windows machine 

### ISSUE THREAD

**Issue by makhdumi** [Microsoft/vsts-tasks#7166]
Please re-open https://github.com/Microsoft/vsts-tasks/issues/4722. It appears that @vincentdass misunderstood the issue.

https://github.com/Microsoft/vsts-tasks/issues/4722 describes the problem where WebDeploy is always forced if the build agent is running on Windows.

I specifically don't want to use WebDeploy AKA msdeploy.exe because it's extremely slow and has certain bugs that cause it to consistently fail. I need to use the Kudu REST API on Windows.

[The code](https://github.com/Microsoft/vsts-tasks/blob/e20703b13943ac39538476965d9698983de521fc/Tasks/Common/webdeployment-common/utility.ts#L65), as described in the issue, should be using `&&` not `||`. This appears to be an actual bug.

[The code](https://github.com/Microsoft/vsts-tasks/blob/e20703b13943ac39538476965d9698983de521fc/Tasks/Common/webdeployment-common/utility.ts#L65) is currently:
```
export function canUseWebDeploy(useWebDeploy: boolean) {
    var win = tl.osType().match(/^Win/);
    return (useWebDeploy || win);
}
```

It should be this:
```
export function canUseWebDeploy(useWebDeploy: boolean) {
    var win = tl.osType().match(/^Win/);
    return (useWebDeploy && win);
}
```

**Comment by makhdumi** [comment]
@SumiranAgg would it be possible to explain why you don't support using Kudu on Windows? Is it because of `WebPublish` in msbuild creates .zip packages - that they aren't structured normally and compatible with Kudu's .zip deploy REST methods?

It'd be kind of annoying if that was the case, since it'd be assuming that any package/folder is generated by WebPublish/MSDeploy.

Instead, for now, would it be possible to only accept directories for the package, and fail if it's a .zip (automatically assuming it wa generated for msdeploy)?

**Comment by SumiranAgg** [comment]
@makhdumi There are multiple reasons why we default to web deploy on Windows. One you have identified correctly, the msbuild package structure is incompatible with kudu zip API. The other reason was that zip API would fail for a large zip, since we have a rest call timeout of 240 sec. 

Instead, now we are working on adding support for zipDeploy API on windows as well (already present for Linux), which has better performance that zip API.

**Comment by makhdumi** [comment]
Got it, thanks!
