### ISSUE TITLE
XML variable substitution for appSettings using dot and underscore

### ISSUE THREAD

**Issue by OskarKlintrot** [Microsoft/vsts-tasks#7179]
## Environment
- Server - VSTS

- Agent - Hosted
    
    - If using Hosted agent, provide agent queue name: 143

## Issue Description

Using `.` in `name` in `connectionStrings` works just fine but it doesn't seem to be working at all for `key` in `appSettings`. When changing it to `_` it works occasionally.

The reason for using `.` in the `key` is to get the naming consistent when using env var. Something like this on VSTS:
```
Name: Build.RequestedFor
Value: $(Build.RequestedFor)
```
and in `appSettings`:
```xml
<add key="Build.RequestedFor" value=""/>
```

**Comment by bryanmacfarlane** [comment]
What task is this referring to?  (/Tasks)

**Comment by vincentdass** [comment]
@OskarKlintrot , currently Build / Release variables are [not supported](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Common/webdeployment-common/variableutility.ts#L4)  (skipped) for XML / JSON variable substitution.  You can provide a secondary variable that maps to the primary release variable and use the same for substitution.

![image](https://user-images.githubusercontent.com/20121508/39954396-69a01aec-55dc-11e8-95f3-ca62a4ff43d3.png)

**Comment by vincentdass** [comment]
@OskarKlintrot , Can you please share the screenshot of Variable Group & the Web.config file that you are trying to modify to `RM_Customer_Queries@Microsoft.com`
Ideally, variables are case-insensitive in Release but it is case-sensitive in variable substitution.

**Comment by OskarKlintrot** [comment]
Sorry, I have already thrown stuff away. I need to switch to JSON for various reasons and I notices that I had some issues there as well. When I used `Build.BuildNumber` as a name to replace this JSON:
```json
{
  "Build.BuildNumber": null
}
```
it won't work. If I change the name to `PrefixBuild.BuildNumber` it will work but not if I change it to `Build.PrefixBuildNumber`. I hope that gives you more to go on.

**Comment by vincentdass** [comment]
@OskarKlintrot , its because we ignore the variables that [starts like Release/Environment variables](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/Common/webdeployment-common/variableutility.ts#L4). It is hard to have the list of built-in variables so, we check using the prefix.

**Comment by OskarKlintrot** [comment]
I see, that explains the behavior.

**Comment by vincentdass** [comment]
@OskarKlintrot , I hope the issue is resolved. Will update the helpmarkdown with required help.
