### ISSUE TITLE
Service fabric upgrade will fail after one hour when AAD access token expires. Should have a refresh logic

### ISSUE THREAD

**Issue by bishal-pdMSFT** [Microsoft/vsts-tasks#7185]
Cx issue:
=================
Hey,
I've noticed an issue that when an upgrade takes a long time, VSTS gives me the following error:
2018-05-10T20:42:23.0504914Z ##[error]The specified credentials are invalid.

If I look at the cluster, the upgrade is still running along just fine so it looks like it's just something wrong with VSTS.
The next deployment will then kick off but fail due to there already being a running upgrade.

More logs here: https://intentional.visualstudio.com/intent/_release?releaseId=1090&_a=release-logs

Anyone know what's going on? Maybe the VSTS task is not refreshing the AAD token?

Thanks!
Jonno

**Comment by zingaroo** [comment]
I experienced the same problem which led to one of the nodes being stuck at "RollingForwardInProgress". What is the recommended way to make the node/cluster get out of this state?

**Comment by kuvinodms** [comment]
@zingaroo 
The ServiceFabricDeploy task has no control over the cluster's node and its state post initiating the Service Fabric Application Upgrade process other than polling the upgrade status and surfacing it once done.

**Comment by zingaroo** [comment]
I understand that. My question was more regarding a general recommended way since this bug created some problems for us, but I will post that in another forum instead.

**Comment by bishal-pdMSFT** [comment]
PR #7436

**Comment by kuvinodms** [comment]
Fix has been merged. Will close down the issue once fix will get merge to all the customers.

**Comment by kuvinodms** [comment]
PR for the fix: #7961
