### ISSUE TITLE
PublishTestResults task stripping test result data

### ISSUE THREAD

**Issue by josefblaha** [Microsoft/vsts-tasks#7189]
## Environment
VSTS

## Issue Description
When my test result XML contains test result with outcome "Inconclusive", VSTS shows it as "Not executed on Agent" on the test results page, and strips away the detailed information (error message and stack trace), which is available in the result file.

[run.xml.zip](https://github.com/Microsoft/vsts-tasks/files/2000593/run.zip)

![test result page](https://user-images.githubusercontent.com/13222165/39996939-75efa9ce-5781-11e8-9e2c-e086471e02a3.PNG)

When the outcome is "Failed", the result is shown correctly including detailed info.

Is there way to customize this "test result normalization"? Or at least is there a documentation of the results transformations, and their rationale?

**Comment by vinodjo** [comment]
Historically publish results only supported Passed, Failed and Not Executed tests. However we acknowledge the need to support other states as well. We have made a change to fix reporting of the "Inconclusive" state, which will be available in approx. 6 weeks (VSTS). We need to look at this at multiple level (Platform, Reporting etc.) and hence adding this to our backlog to provide a comprehensive and consistent representation of the other test states.

**Comment by josefblaha** [comment]
Does it mean that "Inconclusive" state will be reported correctly first, followed by other possible states? What about the error details (message & stack trace)?
