### ISSUE TITLE
jdk demands issues

### ISSUE THREAD

**Issue by NetTecture** [Microsoft/vsts-tasks#7195]
Gradle sets a demand "java". Nice. Perfect.

Installing the Xamarin Payload installs the jdk. It is available under the capabilities:

jdk | C:\Program Files\Java\jdk1.8.0_172
jdk_8 | C:\Program Files (x86)\Java\jdk1.8.0_172
jdk_8_x64 | C:\Program Files\Java\jdk1.8.0_172

just not java. Why introduce yet another capability that is redundant? If the Java tool would look for jdk as capability - whow, no need to install the tool when Xamarin is available.

Similar for node.

npm puts up a demand for.... npm. The Node.js tools installer does not satisfy it, so I am let installing Node.js manually just to satisfy that demand.

2 occasions where it looks like the left hand does not know what the right is doing and prefers to not actually look at the codebase or existing infrastructure. This can be done better.

**Comment by yacaovsnc** [comment]
Only speaking for Gradle, it doesn't require `jdk`.  It only needs the JRE to run.  So the demand is appropriate.

**Comment by NetTecture** [comment]
Ok, nice. Let's ignore that it is as usefull asa plane parked in the desert (i.e. anything doing java will actually most likely need a JDK) - why do I have to play around with environment variables to fullfill that when I have a jdk installed? jdk is a superset of jre and quite obviously one is installed, but hey, let's make it as painfull as possible for anyone maintaining build servers because - the left hand really prefers not to talk to the right hand so there is no coordination at all. Get it.

**Comment by yacaovsnc** [comment]
> why do I have to play around with environment variables to fullfill that when I have a jdk installed? jdk is a superset of jre and quite obviously one is installed, but hey, let's make it as painfull as possible for anyone maintaining build servers 

That's certainly not the goal.  :-)  I think you have identified an issue with our [Java capability provider](https://github.com/Microsoft/vsts-agent/blob/f7e9a7ee42d0c30f0d31d449bb51d95bd6e9e0fb/src/Misc/layoutbin/powershell/Add-JavaCapabilities.ps1).  The Java Runtime Environment key is not set in this case.  The goal is to discover those required demands automatically.  Certainly you are not expected to set an env var just for this.

**Comment by NetTecture** [comment]
Thanks. So, let's hope that fix makes it into a release soonish for the agent. Yeah, looks like someone jsut did not make the correlation that an installed dk actually also is a jre and as such java should be set, too. I really look forward to that update - for now, I keep the java related builds on a hosted agent.

Does not solve the NPM issue - which is the other such issue ;)

**Comment by bryanmacfarlane** [comment]
create a separate issue for npm.  focusing this issue so it's actionable.

**Comment by yacaovsnc** [comment]
I've submitted a [fix ](https://github.com/Microsoft/vsts-agent/pull/1560)already, and it should be in next release. Also you can set custom user capabilities on the agent to bypass any demand issues.
