### ISSUE TITLE
Release variable Release.EnvironmentName does not work.

### ISSUE THREAD

**Issue by AlexHimself** [Microsoft/vsts-tasks#7196]
## Environment
- Server - VSTS (Inherited)
- Agent - N/A

## Issue Description
Release variable `Release.EnvironmentName` does not work. Per [this link](https://docs.microsoft.com/en-us/vsts/build-release/concepts/definitions/release/variables?view=vsts&tabs=batch), it is a valid release variable.

I think this is probably more a documentation problem though because I'm assuming the variable is only active for whatever environment you are releasing to.

![image](https://user-images.githubusercontent.com/10466466/40020286-4c0b6656-5787-11e8-9571-470f8d506e22.png)

**Comment by dabasn** [comment]
As you correctly pointed out, EnvironmentName is a valid variable but it works only in the context of the environment currently deployed.
For example, if you add a powershell task with the script using $(Release.EnvironmentName), it will get replaced with the name of the environment on which this task is running.
Release creation doesn't have environment context so it isn't expected to work in release name mask

**Comment by bansalaseem** [comment]
That's correct explanation @dabasn.
