### ISSUE TITLE
Script - task setVariable - 'testValueWithQuote' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by FrancoisM** [Microsoft/vsts-tasks#7203]
I have two identical tasks:
```
- script: "echo ##vso[task.setvariable variable=firstPassword;isOutput=true]$(firstPassword)"
    name: setvar
- script: "echo ##vso[task.setvariable variable=secondPassword;isOutput=true]$(secondPassword)"
    name: setvar2
```

The first one runs fine. The second one fails with error:

> '[value of secondPassword]' is not recognized as an internal or external command

The only difference I can see is that the secondPassword value has a quote (") in it.

**Comment by ericsciple** [comment]
are you running on Windows or Linux? if Linux then the script is run using bash, so you would need to use bash quoting rules. I think the following would work:
```
- script: "echo '##vso[task.setvariable variable=secondPassword;isOutput=true]$(secondPassword)'"
    name: setvar2
```

**Comment by ericsciple** [comment]
btw I think you would want to set `issecret=true` to register the new variable as a secret. if you are not passing the value across phases, then do not set isoutput=true.

**Comment by FrancoisM** [comment]
It's running on an hosted windows machine.
I do set these variables to be passed accross phases. Tks for 'issecret=true'.

**Comment by ericsciple** [comment]
ok, I think you might have an ampersand in your password ;)

on windows it might be easier to solve escaping by using powershell

the following would completely avoid escaping problems:
```
- powershell: |
    write-host @"
    ##vso[task.setvariable variable=secondPassword;isOutput=true]$(secondPassword)
    "@
  name: setvar2
```

**Comment by FrancoisM** [comment]
Btw the issue may not be the site inside my password. Indeed, in the log, in the fire, it does show the whole password. It's not like the whole command was cut when it encountered the quote.
Also, how can I run that command / script on my own machine to try to understand its behavior?

**Comment by FrancoisM** [comment]
the powershell here-string worked. Tks!
