### ISSUE TITLE
Task Group: Saved Changes Revert Without Operation

### ISSUE THREAD

**Issue by yiqzhou** [Microsoft/vsts-tasks#7206]
## Environment
- Server - VSTS
    Account name: msasg.visualstudio.com
    Team project name: Bing_Ads
    Task Group: https://msasg.visualstudio.com/DefaultCollection/Bing_Ads/_taskgroup/29da9933-9348-4a1b-9d89-79aa8cb008ba?view=tasks

## Issue Description
I made changes to the task group and saved them:
![image](https://user-images.githubusercontent.com/29744299/40059943-f6597250-5887-11e8-888f-a952c1baa908.png)
![image](https://user-images.githubusercontent.com/29744299/40059963-02d61f6a-5888-11e8-89d2-45e80cd270bc.png)
But if I click any of the tasks after saving, the definition becomes:
![image](https://user-images.githubusercontent.com/29744299/40060278-cdd4f7b8-5888-11e8-9985-2514e7712130.png)

**Comment by sorosoro2** [comment]
@yiqzhou , it looks like there was some issue while saving your task group. On the server side, the task group that you are referring to does not have  UCM-DownloadSpecifiedBuildPartialDrop -> drop-folders-to-download set to $(drop-folder-to-dowload). So whenever the client is recomputing the list of parameters, this is getting excluded

I went and checked the history where you added this 
![image](https://user-images.githubusercontent.com/26616790/42503753-23a80c4e-8457-11e8-9e02-de312c05acf3.png)

Here the parameter is added, but I couldn't find a corresponding change in the task input. This image is from the same revision 
![image](https://user-images.githubusercontent.com/26616790/42503821-4c6750c2-8457-11e8-96c4-dcd96a48f02f.png)

I don't know clearly why the save operation misbehaved as such, but can you update the task group once again with the changes and save? I think that should resolve your problem

**Comment by madhuv-msft** [comment]
@yiqzhou would you follow suggestion of @sorosoro2 and see if that fixes the problem?

**Comment by bansalaseem** [comment]
Resolving this issue because of no response.
