### ISSUE TITLE
Uploading a Markdown (*.md) file from a release to a location?

### ISSUE THREAD

**Issue by AlexHimself** [Microsoft/vsts-tasks#7210]
## Environment
- Server - VSTS (inherited)
- Agent - Private

## Issue Description
I am trying to create a dashboard that shows a Markdown (*.md) file with custom status/information relating to various releases.  It lets me choose a specific markdown file.

During the release process, I can't figure out anyway from the Agent to update/communicate with that file using any of the available [commands defined here](https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md).

Is there any way to produce a *.md file that can ultimately land on a dashboard? Ideally via PowerShell.

Right now I'm looking at the VSTS API's with a PAT to create/upload a file at the end of a release with a little bit of friendly user-display info.

**Comment by GitHubSriramB** [comment]
@AlexHimself - you could use ##vso[task.uploadfile] command to upload your MD file into the release.

Pl. refer to the command documentation here:
https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md

You could then create your dashboard widget that could retrieve the MD file from release and render it. We will be updating RM client here in a week:
https://github.com/Microsoft/vss-web-extension-sdk/blob/master/typings/rmo.d.ts

After which you should be able to call GetReleaseTaskAttachmentContent to get the file that you uploaded.

**Comment by GitHubSriramB** [comment]
@AlexHimself - in case you want to display the content of the MD file in release summary page, you can use the following command:
##vso[task.uploadsummary]
