### ISSUE TITLE
Distributed Tests: Test run 'XXX' is in 'InProgress' state for 'Run Functional Tests' task

### ISSUE THREAD

**Issue by msathya20** [Microsoft/vsts-tasks#7219]
Hi, I have a build running coded UI tests in a distributed environment.Tests were running perfectly, once we upgraded to TFS 2017 Update3 RTM we have weird issue I see that 'Run Functional Tests task' is not able to run the tests. In the console log I see only this message "Distributed Tests: Test run 'XXX' is in 'InProgress' state", I see the same message for hours and hours until I cancel the build.But some times tests are running perfectly, but some times are not executing. I have attached the screen shot. 
Please provide your  inputs on how to triage this issue?.
![vnextissue](https://user-images.githubusercontent.com/39302306/40117748-6e5137f4-5935-11e8-962c-c972ea8c68fc.png)

**Comment by bangaruchary** [comment]
Hi.. Me too facing the same issue. 
-- Chary

**Comment by ShreyasRmsft** [comment]
@msathya20 can you please provide the DTAExecutionHost logs and the build logs with system.debug set to true and also log into the test machines when this happens and see if an error dialog or something is blocking the tests from continuing on the machine.

**Comment by ShreyasRmsft** [comment]
@bangaruchary please follow the above steps and share the logs, we'll look into this.

**Comment by bangaruchary** [comment]
Hi Shreyas
Please find DTAExecution log attached for your analysis.  
We have TFS2017.Up3 server (Recently migrated this collection from TFS2015.3 to latest, since then we are observing this issue.)
Test agent and build agent are different machines configured with same account.
Test Agent has VS2013 and TestAgent 13 installed.
Lab Network Service and Labe Agent Service both are running on Test Agent.
[DTAExecutionHost.exe.log](https://github.com/Microsoft/vsts-tasks/files/2022441/DTAExecutionHost.exe.log)

-Chary

**Comment by ShreyasRmsft** [comment]
@bangaruchary we have deprecated DTA RFT task and are asking people to move to the VsTest v2 task.

In tfs 2017 Update 3, the VsTest task has the same distribution capability as DTA in the Release pipeline.
And all our bug fixes and improvements after 2017 Update 3 went into only the VsTest task as we deprecated DTA RFT as there were known limitations with it..

By looking at your build definition it seems like it'll be easy to convert it to run the same tests in the Release pipeline wherein you can use the VsTest v2 task. The VsTest V2 task is more resilient and has better logging and should fix your issue (if not fix will atleast help us get to the RCA). Our hands are tied when it comes to fixing bugs in RFT DTA as it is deprecated and the codebase is frozen.

Try running the tests in the release pipeline and if you need any help in this let me know and I can assist you.

**Comment by msathya20** [comment]
Hi All,

Sorry for the delay..

I have configured VsTest V2 task in my build definition. builds are succeeded, but tests are not executing in VM. I have tried command line execution by using vstest.console.exe, tests are executing perfectly in local Machine. While executing build in  VMs i am getting below  warning message.
"No test assembiles found matching the pattern:**\WinEmbedded.dll"
I have changed couple of patterns but no luck. 
Can you please provide the resolution for this issue??
![vstest](https://user-images.githubusercontent.com/39302306/40408700-0ff0c3e0-5e86-11e8-99ef-bfee2090bf28.PNG)

Best Regards,
Sathya

**Comment by ShreyasRmsft** [comment]
@msathya20 can you send screen shots of your build definition showing clearly all the options in the vstest task and also the copy files tasks that copy your dlls.

After this set system.debug=true (if you haven't already) and send us the build logs zip file.

I believe its a simple matter of your dlls being in a different folder from where the vstest task is looking for it.

Your search folder input should point to the folder in which your dlls are present on the VM. 

The debug logs zip should enable me to point out the search folder and pattern you should be using to run your tests.

**Comment by msathya20** [comment]
Hi Shreyas,

I have attached build definition step by step screen shots and log files.
[VSTest.zip](https://github.com/Microsoft/vsts-tasks/files/2030241/VSTest.zip)

Can you please check and provide the solution for avoiding this issue??

Best Regards,
Sathya

**Comment by ShreyasRmsft** [comment]
Hi @msathya20 

So couple of things you need to know/do. 

1) With VsTest task you no longer need another test agent machine. Tests run on the same machine on which you have your build agent.

2) Remove all the copy tasks you have.

3) Change the search folder input in the vstest task to $(System.DefaultWorkingDirectory)

This should get your tests running.

**Comment by ShreyasRmsft** [comment]
@msathya20 okay here are the steps:

Your build definition will simply build the dlls and then upload them as artifacts. (you can use the default template for building .NET apps it already has the build and upload artifact steps)

You can remove the vstest task from the build definition

Setup vsts-build agents on the VMs you want to run the tests on.

Create a new Release definition that downloads the artifacts (binaries) uploaded by the build and uses the VsTest task to run the tests. This release definition should use the agent pool that contains the agents running on the VMs you want to run the tests on.

You build definition now simply builds binaries and uploads -> this should run on the agent pool containing the agent where you want to build.

https://blogs.msdn.microsoft.com/devops/2017/03/26/vstest-task-dons-a-new-avatar-testing-with-unified-agents-and-phases/


But may I know why the tests need to run on those VMs specifically. Also why don't you simply build the binaries that VM and run the tests there itself. That should be waaay simpler. All you'd need to do is setup a vsts-agent on your VM and use that to run the same definition as described in previous to previous post. (Unless you don't want to install VS on those VMs in which case you won't be able to build there.)

**Comment by ShreyasRmsft** [comment]
@msathya20 can we have a quick call? Send a mail to devops_tools@microsoft.com with you skype id and I'll reply with a convenient time to have the call. We can resolve this speedily.

**Comment by msathya20** [comment]
Hi Shreyas,

I sent mail to specified mail address,,but it seems mail was not delivered. Please find the Skype Id below and let us know your free time for a discussion.
ID- msathya20@gmail.com

Regards,
Sathya.M

**Comment by ShreyasRmsft** [comment]
Had a call and was able to get the test running.

**Comment by prawalagarwal** [comment]
Closing this thread. Please reopen if you are still facing issues.
