### ISSUE TITLE
VSTS - Azure File Copy - WinRM cannot complete the operation

### ISSUE THREAD

**Issue by haniamr** [Microsoft/vsts-tasks#7227]
## Environment
- VSTS
- Agent: Hosted VS2017 

## Error

> WinRM cannot complete the operation. Verify that the specified computer name is valid, that the computer is accessible over the network, and that a firewall exception for the WinRM service is enabled and allows access from this computer. By default, the WinRM firewall exception for public profiles limits access to remote computers within the same local subnet. For more information, see the about_Remote_Troubleshooting Help topic.To fix WinRM connection related issues, select the 'Enable Copy Prerequisites' option in the task. If set already, and the target Virtual Machines are backed by a Load balancer, ensure Inbound NAT rules are configured for target port (5986). Applicable only for ARM VMs. For more info please refer to https://aka.ms/azurefilecopyreadme

## Issue Description
Getting this error when using "Azure File Copy" to copy a file to a DevTest VM. I tried checking "Enable Copy Prerequisites" but it didn't solve the issue. 

To eliminate any WinRM configuration-related issues, I can successfully initiate a remote PS session to the VM:
```
$so = New-PsSessionOption –SkipCACheck -SkipCNCheck
Enter-PSSession -ComputerName {FQDN} -Credential {UserName} -UseSSL -SessionOption $so -Port 5986
```

"Azure File Copy" was working a couple of days ago, but started not to all of a sudden. Could that be a regression from a recent update?

**Comment by rajatagrawal-dev** [comment]
Hi @haniamr 
Is the failure consistent or intermittent?
Can you set a variable in your release definition _system.debug_ and set its value to _true_? This will give you more detailed logs. Please share that with us.
Also, please share your vsts account name.

**Comment by haniamr** [comment]
Hi @rajatagrawal-dev 

The failure is consistent for 2 days now. Sure, I can share the logs but where? The log file contains the password, machine FQDN, and a bunch of other sensitive data so I won't be able to attach it here.

**Comment by rajatagrawal-dev** [comment]
Please send the details to RM_Customer_Queries [at] microsoft [dot] com. Also mention this github issue's reference in the mail.

**Comment by haniamr** [comment]
Sure, done.

**Comment by rajatagrawal-dev** [comment]
@haniamr Were you able to establish WinRM connection from hosted agents?

**Comment by haniamr** [comment]
If I understand your question correctly, then no I couldn't establish a WinRM connection using the hosted agents, although as discussed offline the task works when I set up a private agent on my personal machine.

**Comment by SumiranAgg** [comment]
Not enough information to debug hence closing the issue. please feel free to reopen if required.

**Comment by bhushang19** [comment]
Not sure why this is closed when issue still exists with hosted agents. does anyone know how to resolve this error?
