### ISSUE TITLE
XCode Code Signing Error

### ISSUE THREAD

**Issue by erikadanis81** [Microsoft/vsts-tasks#7228]
The XCode task (5.* preview) now contains some extra parameters which causes the following error:

❌  Code Signing Error: "sampleapp-ios-swift" requires a provisioning profile. Select a provisioning profile for the "Release" build configuration in the project editor.

The additional parameters that i believe are causing an issue:
**PROVISIONING_PROFILE= PROVISIONING_PROFILE_SPECIFIER=**

The full erroneous command:
/usr/bin/xcodebuild -sdk iphoneos -configuration Release -workspace /Users/vsts/agent/2.133.3/work/1/s/sampleapp-ios-swift.xcworkspace -scheme sampleapp-ios-swift build CODE_SIGN_STYLE=Manual **PROVISIONING_PROFILE= PROVISIONING_PROFILE_SPECIFIER=** | /usr/local/bin/xcpretty -r junit --no-color

By downgrading to version 4.* resolves the issue.

**Comment by joshmgross** [comment]
Closing this issue to clean up the backlog. Reopen this if the issue presents itself again.
