### ISSUE TITLE
Port old XAML BuildTaskActivities to VSTS task

### ISSUE THREAD

**Issue by fmanea** [Microsoft/vsts-tasks#7233]
Hello,

Another day, another problem.

Is there a way to port C# .dll custom BuildTaskActivities to VSTS?

They are basicly some classes that inherited CodeActivity, and they were instantiated and used inside XAML.

I tried to use a powerShell task, in which I added the assembly with the .dll that resulted from the building of the Task Activities. The problem with this is that they have a protected "Execute" member function, that can't be reached from inside powerShell.

Another option that I saw, was to add it to build.proj with this kind of ussage:
```<UsingTask TaskName="myTaskName" AssemblyFile="MyAssemblyFile.dll" />```

Is there another way of porting this old functionality from XAML to VSTS 2017?

Best regards,
Flavian

**Comment by bryanmacfarlane** [comment]
The issues in this repo is for the tasks in this repo.  (/Tasks).  That sounds like a question for developer community.

**Comment by fmanea** [comment]
Where can I access the developer community?
