### ISSUE TITLE
Download build artifacts fails with error #Self signed certificates in chain

### ISSUE THREAD

**Issue by SandipKumarKundu** [Microsoft/vsts-tasks#7238]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

[Include task name(s), screenshots and any other relevant details]

### Error logs

[Insert error from the logs here]

**Comment by omeshp** [comment]
Can you try out the steps mentioned in https://github.com/Microsoft/vsts-agent/issues/1396 and check if that resolves the issue.

**Comment by omeshp** [comment]
@SandipKumarKundu Did the steps mentioned in above issue help?

**Comment by omeshp** [comment]
Closing this issue since there is no response. @SandipKumarKundu Please reopen if you are still facing this issue.
