### ISSUE TITLE
Help link on Deployment Script Type is a 404

### ISSUE THREAD

**Issue by DarqueWarrior** [Microsoft/vsts-tasks#7256]
## Environment

- Server - VSTS
   - AzureRMWebAppDeploymentV4 task

- Agent - Hosted or Private: 
   - N/A

## Issue Description

The help link in the tooltip for the Deployment Script Type is a 404

### Error logs

N/A

**Comment by bryanmacfarlane** [comment]
release needs to update the fwlink

**Comment by rokmicrosoft** [comment]
Duplicate of same [issue](https://github.com/Microsoft/vsts-tasks/issues/7220)
