### ISSUE TITLE
Service Endpoint with Token retrieved via User/Password post

### ISSUE THREAD

**Issue by pinkfloydx33** [Microsoft/vsts-tasks#7263]
My goal is to set up a custom Service Endpoint that we can use in some of our custom build/release tasks. Before I get too far down the rabbit hole I'm trying to determine if what I want is even possible. The endpoint I am trying to hit is an internal API that requires a token for its requests. The token itself is retrieved via an HTTP POST with user/password credentials. The token is then used for all GET requests to the API. The token expires after a day.

I'm trying to figure out if its somehow possible to combine `ms.vss-endpoint.endpoint-auth-scheme-token` and `ms.vss-endpoint.endpoint-auth-scheme-basic`. In my ideal world, we'd set up the Service connection with the user name and password and VSTS would be responsible for posting the creds to retrieve the token and then using the token for all requests.  While the API is internal, we can't currently modify it (its owned elsewhere within the company).  Is this something that is possible or am I out of luck here?

**Comment by omeshp** [comment]
Yes, it is possible you will have to use `ms.vss-endpoint.endpoint-auth-scheme-basic` authentication scheme and use a helper method to get the value of token used for header. Below is the example:
```
"authenticationSchemes": [
    {
        "type": "ms.vss-endpoint.endpoint-auth-scheme-basic",
        "headers": [{"name": "Authorization", "value": "JWT {{ #getTokenUsingBasicAuth { 'username' : 'endpoint.username', 'password' : 'endpoint.password', 'resultSelector' : 'jsonpath:$.token', 'method':'post', 'authServerUrl':'endpoint.url\/v2\/users\/login\/', 'body' : {'username' : 'endpoint.username', 'password' : 'endpoint.password'} } }}"}]
    }
]
```

**Comment by pinkfloydx33** [comment]
@omeshp  Thank you; How/where do I define the helper method? I naively thought that it was enough to just paste the above into the vss-extension for my service endpoint (along with the missing inputDescriptors). Needless to say, it doesn't work. Inspecting the console/chrome network inspector I get the following message:

```
eventId: 3000
innerException:null
message: "Helper '#getTokenUsingBasicAuth' not found for expression '#getTokenUsingBasicAuth { 'username' : 'endpoint.username', 'password' : 'endpoint.password', 'resultSelector' : 'jsonpath:$.access_token', 'method':'post', 'authServerUrl':'endpoint.url/api/token/', 'body' : {'username' : 'endpoint.username', 'password' : 'endpoint.password'} }'"
typeKey: "MustacheExpressionInvalidException"
typeName: "Microsoft.VisualStudio.Services.WebApi.MustacheExpressionInvalidException, Microsoft.VisualStudio.Services.WebApi"
```

Obviously this tells me that I need to define the helper method _somewhere_. Try as I may, I can't seem to find any documentation that would indicate how/where to create such a function nor how it gets included with my extension. I assume some JavaScript would be involved? Suppose I did have that code; what mechanism do I use to include it with the extension/make it available to the above template? (Do I need to include it as a contribution? Or something else entirely?)

I'm obviously pretty green at this so if I'm missing something fairly obviously, I apologize. Thanks.

**Comment by omeshp** [comment]
@pinkfloydx33 can you share your extension code? Also are you sure you didn't miss the space before #getTokenUsingBasicAuth can you try getTokenUsingBasicAuth without #.

These helpers are in-build. We currently don't have any documentation around them but we are working on it.

**Comment by pinkfloydx33** [comment]
I tried without the `#` before the method name and I now get this message:
```
message: "Helper 'getTokenUsingBasicAuth' not found for expression 'getTokenUsingBasicAuth { 'username' : 'endpoint.username', 'password' : 'endpoint.password', 'resultSelector' : 'jsonpath:$.access_token', 'method':'post', 'authServerUrl':'endpoint.url/api/token/', 'body' : {'username' : 'endpoint.username', 'password' : 'endpoint.password'} }'"
typeKey: "MustacheExpressionInvalidException"
typeName: "Microsoft.VisualStudio.Services.WebApi.MustacheExpressionInvalidException, Microsoft.VisualStudio.Services.WebApi"
```

I've attached my vss-extension.json and my task.json (with some items redacted); Note that its currently just a dummy testing task/extension while I'm trying to work this out. [vss-extension.zip](https://github.com/Microsoft/vsts-tasks/files/2031403/vss-extension.zip)

**Comment by omeshp** [comment]
@pinkfloydx33 Are you trying your extension in VSTS or is it for onprem?

**Comment by omeshp** [comment]
@pinkfloydx33 Yeah that is right, this handler was added recently. 
@jikuma Is the handler available for Update 2?

**Comment by pinkfloydx33** [comment]
@omeshp Were you able to find out if this has made it into Update 2? Thanks!

**Comment by omeshp** [comment]
@pinkfloydx33 Yes the helper is available in TFS 2018 Update 2.

**Comment by pinkfloydx33** [comment]
@omeshp  We installed Update 2 over the weekend. I can see that the helper is available, but something about it is not working for me.

Originally, my 'authServerUrl' had the following value 'endpoint.url\/api\/token\/' . The response I was receiving (via Chrome network tools) was a 404 not found. I figured out that this was due to the extra slash after token (our API doesn't like it). I replaced the authServerUrl with 'endpoint.url\/api\/token' and now I get a 400 error (I also tried replacing \/ with simple forward slashes, ie 'endpoint.url/api/token' but receive the same error). Any ideas what might be causing this?

```
$id:"1"
errorCode: 0
eventId: 0
innerException: null
message: "The remote server returned an error: (400) Bad Request."
typeKey: "WebException"
typeName: "System.Net.WebException, System"
```

I verified via postman that my endpoint is correct at that the /api/token  path on that endpoint properly accepts the username and password I have entered in the task (status 200, with token). The API will return a 400 Bad Request when the username or password is invalid, so I think it might be related to that? Unfortunately I don't know the best way to track this down. Can you please verify that my vss.extension is set up correctly? I've attached a text file with the contribution's value. [EndpointContribution.txt](https://github.com/Microsoft/vsts-tasks/files/2068836/EndpointContribution.txt)

You'll see that I have two authentication Schemes (the one I'm debugging and one where I'm providing the token directly). The one Where I provide the token directly works (and my extension can properly query it). This schema will be removed once I get the user/pass version working.

Using wireshark, it looks like the body of the request is being sent as a JSON object with username/password key/value pairs and NOT as x-www-form-urlencoded.  It looks like our API only accepts the latter (I verified by constructing a similar request in PostMan, and I receive the 400 error). 

Is it possible to force the helper method to use this format rather than sending a JSON object like it appears to be doing?  If not, I suppose I'm finally out of luck. 

Any insight you have will be appreciated.

**Comment by omeshp** [comment]
@pinkfloydx33 we currently only support sending json payload for fetching the token.

What's the validity of this token? Can it be generated at endpoint creation time and saved with the endpoint?

**Comment by GitHubSriramB** [comment]
@pinkfloydx33  - we will track the improvement to getTokenUsingBasicAuth in our backlog. 

Another option is to create a service endpoint UI contribution, generate the token within that UI and save it with endpoint.

In case you are interested in this option, pl. let us know.

**Comment by pinkfloydx33** [comment]
@GitHubSriramB  I would be interested in that. How would I go about setting that up?

**Comment by pinkfloydx33** [comment]
@GitHubSriramB @omeshp Thank you for your help on this. In the meantime we are looking to write a sort-of pass-thru API that we can use instead. We already need it for something else so it shouldn't be a big deal to modify to fit our needs for this. I'll monitor the issue, just in case. 

Is there any documentation on these "hidden" helper functions yet? I assume this is not the only one. 

Thanks again!

**Comment by GitHubSriramB** [comment]
We will add documentation for the helper functions. Tracking it with an issue.

**Comment by knowds** [comment]
@GitHubSriramB , I had been able to implement getTokenUsingBasicAuth and use the generated token in subsequent REST API calls. However, as mentioned , would be interested in this option "Another option is to create a service endpoint UI contribution, generate the token within that UI and save it with endpoint.". I want to save the token to be used/passed in node js or powershell scripts for final task execution. Please confirm as to how can we achieve the same.
