### ISSUE TITLE
Variables in Azure SQL Database Deployment

### ISSUE THREAD

**Issue by maikvandergaag** [Microsoft/vsts-tasks#7271]
## Environment

Using VSTS online: msftplayground.visualstudio.com
Project name: Visual Studio Team Services
Agent: Hosted 2017
  
## Issue Description
When using the task: "Azure SQL Database Deployment" we can not specify the server name and database as variables. For some reason it tries to connect to the database including the variable name:

Unable to connect to master or target server "$(sqldataname)". You must have a user with the same password in master or target server "$(sqldataname)". Azure SQL Dacpac task failed. Checkout how to troubleshoot failures https://aka.ms/sqlazuredeployreadme#troubleshooting. | Unable to connect to master or target server '$(sqldataname)'. You must have a user with the same password in master or target server '$(sqldataname)'.

Unable to connect to master or target server '$(sqldataname)'. You must have a user with the same password in master or target server '$(sqldataname)'.

**Comment by vincentdass** [comment]
@maikvandergaag , Please ensure that there is no typo in variable name. One more reason is the variable is scoped for different environment.
Can you please share the debug logs for the release? (set `system.debug` to `true` and rerun the release). You can also share the logs privately to `RM_Customer_Queries@Microsoft.com`.

**Comment by maikvandergaag** [comment]
Hi Vincent, I had to give a training last week will try it tomorrow.

**Comment by maikvandergaag** [comment]
Is it correct that all variables need to be "Release" scoped?

**Comment by vincentdass** [comment]
@maikvandergaag , Having the variables in Release scope should be fine.
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/pipelines/troubleshooting?view=vsts#build-and-release-logs
 You can also share the logs privately to RM_Customer_Queries@Microsoft.com.

**Comment by niadak** [comment]
@maikvandergaag  Did you get a chance to try the variable in Release scope? Are you still blocked?

**Comment by maikvandergaag** [comment]
Sorry I have been very busy I will try it right away. Be back in 5 min

**Comment by maikvandergaag** [comment]
I works with release scoped variables. Why is that and will specific environment variables be supported in new releases?

**Comment by niadak** [comment]
Good to know it is working for you.

Specific environment variables should also work if the corresponding task is in correct environment. Please try and let us know if environment scoped variables are not working as expected.

**Comment by SumiranAgg** [comment]
@maikvandergaag Did you get a chance to scope the variable to correct Environment?

**Comment by SumiranAgg** [comment]
Closing the issue as no more customer condition. please reopen if still blocked.

**Comment by reubster** [comment]
Just been having this issue. 

It went away when I enable system.debug = true. 

bit weird.
