### ISSUE TITLE
task.json inputs type and value based on another input

### ISSUE THREAD

**Issue by william726** [Microsoft/vsts-tasks#7274]
I have two questions about developing custom VSTS task, mainly about the settings in task.json.

1. Is there any input field type which shows a string and not editable?
2. Is there a way to set a input field value based on the value of other input field?

I ask these two questions because, for instance, in a task which clones Azure SQL database, users will enter the source database name. For the new cloned database, it should always has the suffix "_clone" append to the end of the source database name. e.g. "projectSqlDb" and "projectSqlDb_clone". This logic should be taken care in the task and users should not be able to change the new cloned database name. But at the same time I would like to show the name of the "projectSqlDb_clone" to let users know what the task is trying to do.

I tried the settings of the inputs object below. **SqlDatabaseName** gets the values from Azure API and a database name can be picked. I tried to get the defaultValue of **NewSqlDatabaseName** from **SqlDatabaseName** using "$(SqlDatabaseName)_clone" but there is no luck. Exact wordings of "$(SqlDatabaseName)_clone" is being shown in the task.

And I also tried to add "EditableOptions": "False" to a string type but it doesn't work either. Would like to know if there is another type can suit my need.

```
    {
      "name": "SqlDatabaseName",
      "type": "pickList",
      "label": "Source Azure SQL Database name",
      "defaultValue": "",
      "required": true,
      "helpMarkDown": "Enter the name of an existing SQL Database"
    },
    {
      "name": "NewSqlDatabaseName",
      "type": "string",
      "label": "New Azure SQL Database name",
      "defaultValue": "$(SqlDatabaseName)_clone",
      "required": true,
      "properties": {
        "EditableOptions": "False"
      },
      "helpMarkDown": "The new SQL Database to be cloned"
    }
```

**Comment by bryanmacfarlane** [comment]
I don't believe that's supported.

Another option is to make NewSqlDatabaseName required false and description says optional clone database name.  if not supplied will be (name)_clone.  At runtime, you can set to (name)_clone.  You could even query existing database names and set (name)_clone2 etc...  You would want to set that name as an output variable if you want the name it was cloned to.  That output could be mapped to an input of another task downstream.

**Comment by bryanmacfarlane** [comment]
since not an issue with tasks in this repo, if the suggestion above is not sufficient, please log an issue in the vsts-task-lib repo

**Comment by william726** [comment]
Hi @bryanmacfarlane, you mentioned "You would want to set that name as an output variable if you want the name it was cloned to. That output could be mapped to an input of another task downstream."

Do you have an example how to set the name as output variable? Should it be done in task.json or ts/ps1 file? If you can point me to an example task it would be awesome.
