### ISSUE TITLE
test task: support for uwp and remote machine 

### ISSUE THREAD

**Issue by jashif** [Microsoft/vsts-tasks#7277]
Hi 

We are using visual studio test agent for running out automated test and it seems you have deprecated that task. is there any timeline when we have test task on remote machine. and support for uwp.  We are using appium for our crossplatform app , it would be so grateful to have the support for remote machine and uwp apps.

**Comment by ShreyasRmsft** [comment]
@jashif can you please provide more details as to whether you are an on-prem user or a vsts user. Please provide screenshots of you definition so we can understand and help with a solution.

**Comment by jashif** [comment]
Hi
Am a on premise user. Right now the solution I added is I created a agent which runs as a interactive mode.

Then I created a release definition which has test task to run the ui test.. if the below setup is fine ?

[cid:image002.png@01D3F33E.79C0B270]


This definition will run on a dedicated test agent server. I hope this way is correct ?. also i want to connect to test from test plan .


For that i created a defintion from test plan

[cid:image006.png@01D3F33E.79C0B270]



So that i can run my function test which is written in appium.

[cid:image009.png@01D3F33E.79C0B270]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10


I have to downgrade the mstest version from 2 to 1 , in order to associate test case to test. The latest version is not supporting the association of test case.


Regards
Jashif.

**Comment by jashif** [comment]
![definition1](https://user-images.githubusercontent.com/1052953/40970773-e916b4f6-68bb-11e8-8274-9aaa0bf98e4c.PNG)
![definition2](https://user-images.githubusercontent.com/1052953/40970774-e933e81e-68bb-11e8-87d1-d3ca0ab24e6f.PNG)
![definition3](https://user-images.githubusercontent.com/1052953/40970775-e9537472-68bb-11e8-8ca8-d663b23cae5a.PNG)

**Comment by ShreyasRmsft** [comment]
@jashif any updates here? Did you drop a mail to devops_tools@microsoft.com?

**Comment by jashif** [comment]
I have send to the mail, but It replied saying only email id’s from Microsoft can send email to the provided address.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ShreyasRmsft** [comment]
@jashif can you tell me the subject of the mail? It generally says that but the mail does get sent. I'll take a look.

**Comment by jashif** [comment]
This was the subject, I got error from postmaster@microsoft.com<mailto:postmaster@microsoft.com> saying not delivered.

FW: [Microsoft/vsts-tasks] test task: support for uwp and remote machine (#7277)

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by kaadhina** [comment]
@jashif Thanks for the response offline. As per the mail, I understand you are unblocked. I'm closing this issue for now. Please re-open when needed.
