### ISSUE TITLE
DownloadBuildArtifacts url construction bug

### ISSUE THREAD

**Issue by jdanyow** [Microsoft/vsts-tasks#7280]
![image](https://user-images.githubusercontent.com/1306747/40457736-eb38cc24-5eac-11e8-8a2a-8b74c4293742.png)

Bug is here:
https://github.com/Microsoft/vsts-tasks/blob/1157d25599ca492ae63c5ac4e9ecf435dc3494de/Tasks/DownloadBuildArtifactsV0/main.ts#L236

Could use `url.resolve(...)` or `path.posix.join(...)` possibly

**Comment by bryanmacfarlane** [comment]
path.join should also work

**Comment by omeshp** [comment]
@jdanyow Is this affecting download, we sanitize urls before downloading.

**Comment by omeshp** [comment]
The above suggestions don't work for us, that's the reason we went with handling multiple slashes in the artifact engine.

```
> path.join("https://some/something", "/some/some")
'https:\\some\\something\\some\\some'
> path.posix.join("https://some/something", "/some/some")
'https:/some/something/some/some'
> url.resolve("https://some/something", "/some/some")
'https://some/some/some'
```

Closing this issue since it doesn't affect the download.
