### ISSUE TITLE
Cannot run multi-configuration build with Test Plan in VSTS

### ISSUE THREAD

**Issue by JoshPearce91** [Microsoft/vsts-tasks#7283]
Hi,

We have a build setup to run against multi-configurations, and a Visual Studio Test task where the tests are selected using a Test Plan. The build is expected to run for each configuration defined, where the tests are executed every run.

![image](https://user-images.githubusercontent.com/39563571/40474149-26afe9e8-5f36-11e8-879f-bd3925a846bc.png)

![image](https://user-images.githubusercontent.com/39563571/40474190-48ff97fa-5f36-11e8-9bd6-18f063f13eda.png)

The first iteration of the build is successful, and the tests are executed; however, any proceeding iteration will not execute any tests as the two iterations share the same Test Run ID, which is already in the state complete after the first iteration.

**First iteration:**
![image](https://user-images.githubusercontent.com/39563571/40475977-d0fd4a40-5f3a-11e8-8f91-e20007c6c691.png)

**Second iteration:**
![image](https://user-images.githubusercontent.com/39563571/40475060-76515386-5f38-11e8-9c7d-1e30e109f3d3.png)

Running the same build against the test assemblies (instead of the test plan) will generate separate Test Run IDs for each iteration, and so does not encounter this problem.

Please let me know if you require any more details. Thanks.

**Comment by prawalagarwal** [comment]
Hi @JoshPearce91,

Thanks for reporting the issue! Please provide your TFS version if you are on premise user. Also please send your run logs to devops_tools@microsoft.com

I could not reproduce the issue on VSTS and TFS 2018.

**Comment by JoshPearce91** [comment]
Hi @prawalagarwal,

We use VSTS. I have sent the logs to the email address provided, referencing the issue number in the email header.

Thanks.

**Comment by JoshPearce91** [comment]
@prawalagarwal I just received a response to my email, stating it could not be delivered to the following groups: vstlmtcm@microsoft.com, vs_atpm@microsoft.com. Is this an issue, or will you still be able to receive the email?

**Comment by prawalagarwal** [comment]
@JoshPearce91 We received the logs. Will update the thread after analyzing.

**Comment by ShreyasRmsft** [comment]
@JoshPearce91 can you check of the preview feature Build With Multiple Queues is on or not for you vsts account?

It can be found in the profile drop down. select preview features for this account instead of for this user

![image](https://user-images.githubusercontent.com/25194518/40824070-54d43a4e-6590-11e8-95af-e32fd6db6d42.png)

**Comment by ShreyasRmsft** [comment]
@JoshPearce91 any updates?

**Comment by JoshPearce91** [comment]
Hi @ShreyasRmsft this is currently turned off in our instance.

![image](https://user-images.githubusercontent.com/39563571/40913920-2eadfd40-67ee-11e8-9091-35b8cfe37963.png)

**Comment by ShreyasRmsft** [comment]
@JoshPearce91 This is necessary for multi config to work in the build pipeline. 

Can you please turn it on and try your build?

**Comment by JoshPearce91** [comment]
Thanks for the suggestion @ShreyasRmsft, I'll get our site admin to enable the feature and then I'll update you with the result.

**Comment by JoshPearce91** [comment]
The issue has been fixed by turning on "Build with multiple queues", thanks for the suggestion @ShreyasRmsft.
