### ISSUE TITLE
Feature request: Associate output variables with "Command Line" (CmdLineV2) task

### ISSUE THREAD

**Issue by TheTeraByte** [Microsoft/vsts-tasks#7293]
## Environment
- Server - VSTS
- Agent - Hosted    
    - If using Hosted agent, provide agent queue name: Hosted Linux Preview

## Issue Description

I want to use the "Command Line" task to output the contents of my version file into [an output variable](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/outputvariable.md), which I can then use in a downstream task.

However, it seems that the "Command Line" task doesn't support the output variables functionality yet. Is this feature planned and is there a tentative timeline?

![image](https://user-images.githubusercontent.com/2552672/40511218-e4a86d5e-5f53-11e8-89e1-bc461248c9cd.png)

**Comment by TheTeraByte** [comment]
Thanks for the tip, @ericsciple. However, it seems that command substitution doesn't work in the "Command Line" task. So the value of the variable is set to `$(cat myfile.txt)` instead of the contents of `myfile.txt`. Do you know of any workaround for that?

**Comment by TheTeraByte** [comment]
I ended up using the "Shell Script" task in conjunction with the `##vso` command to get this to work. I still think that the output variable feature in the "Command Line" task would be simpler and less error prone.

**Comment by ericsciple** [comment]
The command line v2 task runs your inline script using bash when running on Linux/macOS, so command substitution should be working. Based on the initial screenshot I assumed you were using Linux/macOS. Is that a correct assumption? Did you use single quotes instead of double quotes?
