### ISSUE TITLE
##[warning]No test result files matching C:\agent3\_work\23\s\**\TEST-*.xml were found, so publishing JUnit test results is being skipped.

### ISSUE THREAD

**Issue by Solution143** [Microsoft/vsts-tasks#7301]
I am trying to use TFS 2018 for CI process while using Maven project! Somehow, it's skipping Junit test and the build is passing without the execution of the Junit test. Can somone please help me out with that?

**Comment by kelliejos** [comment]
@Solution143 : From the error it looks like your test results are not in the directory expected by the Maven task.  Have you tried specifying the exact filename and path for the test results? Another option that may work for you is to try using the PublishTestResults task after the Maven task to publish your test results to TFS. Thanks!

**Comment by joshmgross** [comment]
Closing this issue to clean up the backlog. Reopen this if the issue presents itself again.
