### ISSUE TITLE
Add data source to Azure RM endpoint

### ISSUE THREAD

**Issue by Dev13u28** [Microsoft/vsts-tasks#7302]
Can we add datasource to the existing Data Sources defined by Azure RM Service EndPoint : 
{VisualStudioaccount}/defaultcollection/_apis/distributedtask/serviceendpointtypes?type=AzureRM ?

Or Can we define variables in Task.json ? My requirement is to get azure location of a rsg and get corresponding VMSizes available in the location without creating a new input of selecting Azure Location. Rest API call to resource group can give me the location , i dont want to bind the location to a Input control and make subsequent call for getting vmsizes.

@GitHubSriramB

**Comment by GitHubSriramB** [comment]
@MireilleHanna - Azure RM service endpoint is part of an internal extension & so would not be possible for customers to add data sources to it.

However customers can create data source bindings where the URL can be specified inline without having to refer to a data source. Here is a task that defines the URL inline:
https://github.com/Microsoft/vsts-tasks/blob/dabc382bcc98750676c3f1a79c17f39c7fe47e26/Tasks/AzureMonitorV0/task.json

We will update documentation we have to include how this can be achieved:
https://github.com/Microsoft/vsts-rm-extensions/blob/master/docs/authoring/endpoints/dataSources.md

We currently don't support variables in task.json to store location of the resource group. We will consider adding this support going forward.

**Comment by GitHubSriramB** [comment]
Documentation is updated here.
