### ISSUE TITLE
[Service fabric deploy] Skip same application type and version should happen before Test-ServiceFabricApplicationPackage

### ISSUE THREAD

**Issue by bishal-pdMSFT** [Microsoft/vsts-tasks#7307]
Mail thread for this issue:

Doug,

I checked the two artifacts and don't see any difference. Hence diff logic is working fine.
However, SF still reports that code has changed. This must be happening as you have enabled compression for deployment. You can disable compression and this error should go away.

Note: You have also enabled "Skip upgrade for same app type and version" and this should have skipped upgrade ideally. But these is a bug because of which it is first trying to test the application package before deciding to skip upgrade. We will fix that bug.

Thanks,
Bishal

Sent from Outlook

**Comment by kuvinodms** [comment]
@bishal-pdMSFT 
Hotfixed the issue for Ring0 and Ring1. Soon it will be deployed to other rings.
