### ISSUE TITLE
Run Functional Test on Test Agent not picking up Nunit tests

### ISSUE THREAD

**Issue by yaffa7** [Microsoft/vsts-tasks#7317]
## Environment
- Server - Visual Studio Team Services 2015 on premise
- Agent - Private - Visual Studio Test controller + agent 2013
  
## Issue Description

I am trying to run Nunit tests on a test agent using the Run Functional tests task on the VSTS release configuration. I am building the artifacts on a build process that is working fine. 

My release configuration is :
1) Windows Machine copy [Build drop artifact location] =>[ $(LabMachinename)] (SUCCESS)
2) Visual studio Test Agent Deployment (SUCCESS)
Machine: `$(LabMachineName)`
Test Agent Location:  `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\QTAgentService.exe`
3)Run Functional Tests (FAILURE)
Machines: `$(LabMachineName)`
Test Drop Location: `$(DropFolder)\TestFramework\bin\$(BuildConfiguration)`
Test Selection: `Test Assembly`
Test Assembly: `$(DropFolder)\TestFramework\bin\$(BuildConfiguration)\WebCustomizationTests.dll`
Run Settings File: `$(Builddrop)\DEV.runsettings`

It doesn't seem like the Run Functional Tests task is picking up the custom Nunit Adapter .dll (`NUnit3.TestAdapter.dll`) even though it is specified in the .runsettings file and the task is indeed using the file (see  logs). These tests work locally when running Vstest and are picking up the adapter, but the VSTS task does not.

DEV.runsettings

```xml
<?xml version="1.0" encoding="utf-8"?>
<RunSettings>
  <!-- Configurations that affect the Test Framework -->
  <RunConfiguration>
    <MaxCpuCount>1</MaxCpuCount>
    <!-- Path relative to solution directory -->
    <ResultsDirectory>.\TestResults</ResultsDirectory>

    <!-- [x86] | x64    
      - You can also change it from menu Test, Test Settings, Default Processor Architecture -->
    <TargetPlatform>x86</TargetPlatform>

    <!-- Framework35 | [Framework40] | Framework45 -->
    <TargetFrameworkVersion>Framework45</TargetFrameworkVersion>

    <!-- Path to Test Adapters -->
    <TestAdaptersPaths>%SystemDrive%/Build_Output/WebCustomizationTests/TestFramework/bin/DEV</TestAdaptersPaths>
  </RunConfiguration>
</RunSettings>
```
### Error logs
Run Tests $(DropFolder)\TestFramework\bin\$(BuildConfiguration)\WebCustomizationTests.dll on $(LabMachineName) log
``` text
2018-05-29T19:39:02.8933301Z Executing the powershell script: D:\Pool-B Work\AgentB-1\agent\tasks\RunVisualStudioTestsusingTestAgent\1.0.28\RunDistributedTests.ps1
2018-05-29T19:39:03.0961379Z DistributedTests: Environment WinRm Protocol HTTP.
2018-05-29T19:39:03.0961379Z DistributedTests: Run Settings File Path : D:\Pool-B Work\AgentB-1\agent\_work\b9a534779\[BUILD PROJECT]\drop\WCFTestFramework\DEV.runsettings
2018-05-29T19:39:03.1897415Z DistributedTests: Creating run for selected test assemblies with following parameters
2018-05-29T19:39:03.1897415Z DistributedTests: SourceFilter: d:\Build_Output\WebCustomizationTests\TestFramework\bin\DEV\WebCustomizationTests.dll TestCaseFilter: 
2018-05-29T19:39:03.1897415Z DistributedTests: Run title: WebCustomization Tests - DEV
2018-05-29T19:39:03.1897415Z DistributedTests: is automated: True
2018-05-29T19:39:03.1897415Z DistributedTests: test settings id : 7811
2018-05-29T19:39:03.1897415Z DistributedTests: build location: d:\Build_Output\WebCustomizationTests\TestFramework\bin\DEV
2018-05-29T19:39:03.1897415Z DistributedTests: build id: 67287
2018-05-29T19:39:03.1897415Z DistributedTests: test configuration mapping: 
2018-05-29T19:39:03.3145463Z DistributedTests: Test Run with Id 19752 Queued
2018-05-29T19:39:03.3457475Z DistributedTests: Test run '19752' is in 'InProgress' state.
2018-05-29T19:39:13.3613327Z DistributedTests: Test run '19752' is in 'InProgress' state.
2018-05-29T19:39:23.3925185Z DistributedTests: Test run '19752' is in 'Aborted' state.
2018-05-29T19:39:33.4081037Z ##[warning]DistributedTests: Test run is aborted. Logging details of the run logs.
2018-05-29T19:39:33.4237043Z ##[warning]DistributedTests: New test run created.
2018-05-29T19:39:33.4237043Z ##[warning]Test Run queued for Project Collection Build Service (TEAM FOUNDATION).
2018-05-29T19:39:33.4237043Z ##[warning]DistributedTests: Test discovery started.
2018-05-29T19:39:33.4237043Z ##[warning]DistributedTests: Test Run Discovery Aborted . Test run id : 19752
2018-05-29T19:39:33.4237043Z ##[warning]DistributedTests: UnExpected error occured during test execution. Try again.
2018-05-29T19:39:33.4237043Z ##[warning]DistributedTests: Error : No tests were discovered from the specified test sources
2018-05-29T19:39:33.4237043Z ##[warning]DistributedTests: Test run aborted. Test run id: 19752
2018-05-29T19:39:33.4393049Z ##[error]The test run was aborted, failing the task.
 

```
 The entire solution, including packages and sln. are being copied to the agent 

Any help would be appreciated

**Comment by yaffa7** [comment]
@nigurr @kaadhina

**Comment by prawalagarwal** [comment]
@yaffa7 
You mentioned your agent as Private - Visual Studio Test controller + agent 2013, but RFT does not support Agent2013. But this is contradicted by 
Test Agent Location: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\QTAgentService.exe
which seems to be pointing to the correct location (ie VS 2015).

Also, please note that we require adapters to be present in the "packages" folder next to the test dlls. For eg in your case nunit adapters should be present at $(DropFolder)\TestFramework\bin\$(BuildConfiguration)\pacakages

**Comment by yaffa7** [comment]
Hi, thanks for the update. After some research it seems like even though the folder is Visual Studio 2015, the installer available for download came with the test agent and the test controller of 2013. Link  https://docs.microsoft.com/en-us/visualstudio/test/lab-management/install-configure-test-agents

![image](https://user-images.githubusercontent.com/9054709/40739756-de60d63c-63fb-11e8-9075-b0d27c57672a.png)

So it seems like VS2015 and 2013 test agent should be compatible. Ill try putting the packages folder along with the test dlls.

**Comment by yaffa7** [comment]
Tried to run functional tests with the folder configuration you suggested of putting the packages folder in the same folder as the test dll.

![image](https://user-images.githubusercontent.com/9054709/40741848-752b821a-6401-11e8-92ee-070cc3b1e390.png)

But im still getting the same error as above in the RFT task

**Comment by nigurr** [comment]
@yaffa7 Can you please create an empty solution (.sln) file and place it in `\bin\DEV\` folder and `\bin\DEV\packages\` folder?
Sorry for the trouble. These issues are fixed in later versions of TFS 2017 Update 3.

**Comment by yaffa7** [comment]
Thank you for the input. Eventually we will look to upgrade to 2017.

In the meantime im running the tests through a powershell script on our test agent (via the Run Powershell on Remote Machine task). The tests are being executed and finish running, but the tasks seems to stall and block the release from being completed.

Here is the log from these steps

```
******************************************************************************
Starting task: Deploy TestAgent on $(LabMachineName)
******************************************************************************
Executing the powershell script: D:\Pool-B Work\AgentB-3\agent\tasks\DeployVisualStudioTestAgent\1.0.25\DeployTestAgent.ps1
DistributedTests: Starting to deploy and configure test agent on test machines.
DistributedTests: Inputs provided are:
DistributedTests: Username: $(Username)
DistributedTests: Use HTTP Port: True
DistributedTests: Run as process: False
DistributedTests: Login Automatically: False
DistributedTests: Disable Screen saver: False
DistributedTests: Agent location: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\QTAgentService.exe
DistributedTests: Update test agent: False
DistributedTests: Run test agent as DataCollection only : False
DistributedTests: Path to script that installs test agent on remote machine: D:\Pool-B Work\AgentB-3\agent\tasks\DeployVisualStudioTestAgent\1.0.25\TestAgentInstall.ps1
DistributedTests: Path to script that configures test agent on remote machine: D:\Pool-B Work\AgentB-3\agent\tasks\DeployVisualStudioTestAgent\1.0.25\TestAgentConfiguration.ps1
DistributedTests: Path to script that downloads test agent on azure remote machines : D:\Pool-B Work\AgentB-3\agent\tasks\DeployVisualStudioTestAgent\1.0.25\DownloadTestAgent.ps1
DistributedTests: Path to script that checks if test agent is installed on remote machine: D:\Pool-B Work\AgentB-3\agent\tasks\DeployVisualStudioTestAgent\1.0.25\CheckTestAgentInstallation.ps1
DistributedTests: Path to script that checks if test agent is already running on remote machine: D:\Pool-B Work\AgentB-3\agent\tasks\DeployVisualStudioTestAgent\1.0.25\VerifyTestMachinesAreInUse.ps1
DistributedTests: Task 'VerifyTestMachinesAreInUse' on machine '[LABMACHINE]' is being run
DistributedTests: Task 'VerifyTestMachinesAreInUse' on machine '[LABMACHINE]' completed.
DistributedTests: You may be using machine '[LABMACHINE]' across one or more concurrent builds. This is currently not supported. Use an unique machine per build definition and ensure there are no concurrent builds In Progress from any given build definition using a machine.
DistributedTests: Task 'CheckTestAgentInstallation' on machine '[LABMACHINE]' is being run
DistributedTests: Task 'CheckTestAgentInstallation' on machine '[LABMACHINE]' completed.
DistributedTests: Update test agent is disabled. Skipping test agent updates.
DistributedTests: Task 'ConfigureTestAgent' on machine '[LABMACHINE]' is being run
DistributedTests: Task 'ConfigureTestAgent' on machine '[LABMACHINE]' completed.
DistributedTests: Testagents are configured and ready to run tests, make sure you use the 'Visual Studio Test using Test Agent' task in the Build Definition after this task.
******************************************************************************
Finishing task: DeployVisualStudioTestAgent
******************************************************************************
Skipping task RunVisualStudioTestsusingTestAgent as it is disabled in the definition
******************************************************************************
Starting task: Run Web Customization Tests
******************************************************************************
Executing the powershell script: D:\Pool-B Work\AgentB-3\agent\tasks\PowerShellOnTargetMachines\1.0.31\PowerShellOnTargetMachines.ps1
Deployment started for machine: '[LABMACHINE]'
Worker Worker-40eb3277-e717-44d7-b8a6-6e793faef7ba finished running job 40eb3277-e717-44d7-b8a6-6e793faef7ba
******************************************************************************
Finishing Release
******************************************************************************
```

However this step never finishes, and no other steps are run afterward

![image](https://user-images.githubusercontent.com/9054709/40812902-1219b15a-64ed-11e8-9519-a83a6ff7a683.png)


Do you know whats preventing `PowerShellOnTargetMachines.ps1` to not finish? Here is the powershell script that is being ran by it:

```powershell
nunit3-console D:\Build_Output\WebCustomizationTests\TestFramework\bin\DEV\WebCustomizationTests.dll --where "cat=~1.1" --noresult
```

This script runs and exits fine when ran locally on the labmachine

**Comment by yaffa7** [comment]
Alright. This article helped me solve this issue http://www.codewrecks.com/blog/index.php/2016/06/04/running-unit-tests-on-different-machine-during-tfs-2015-build/

The solution was to add the contents of the Nunit3 unit test adapter to the extensions folder the test agent uses for running function test `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\Extensions`

After doing that the task ran normally and picked up the unit tests.

This issue may be closed.

**Comment by prawalagarwal** [comment]
Thanks for reporting back on the closure.

**Comment by ShreyasRmsft** [comment]
@yaffa7 can you have the dlls inside the packages folder in the DEV folder itself? It might not be recursively looking.
