### ISSUE TITLE
[Enable Continuous Monitoring] Add the capability to use a different Azure subscription for the App Insights resource

### ISSUE THREAD

**Issue by poveilleux** [Microsoft/vsts-tasks#7326]
Hi,

When I was looking to enable Continuous Monitoring on my App Services, I noticed the Application Insights resource has to be in the same Azure subscription than the App Service resource. I have a scenario where those 2 resources (Application Insights and App Service) are in two separate Azure subscriptions. Would it be possible to add a "Application Insights Azure subscription" parameter to the task in order to support this use case?

Thank you

**Comment by imalokagrawal** [comment]
Thank you for your suggestion! We haven't heard this request from our other customers. 
Please add your request or vote for this feature on the Visual Studio UserVoice site (https://visualstudio.uservoice.com), which is our main forum for product suggestions. 

Continuous Monitoring option in Azure App Service manage task mainly does 2 things:
1. Add application insights extension to Azure web app
2. Add application insights instrumentation key in app settings of Azure web app.

As a workaround, you can perform these 2 steps using ARM or PowerShell task.

**Comment by kmkumaran** [comment]
Closing this based on @imalokagrawal comments, since we will track this based on Visual Studio UserVoice response.
