### ISSUE TITLE
VSTS - Service Fabric Deployment Upgrade Timeout

### ISSUE THREAD

**Issue by OnlyHicki** [Microsoft/vsts-tasks#7330]
We're working with VSTS using Hosted VS2017 - Following Microsoft documentation for the Upgrade Settings for the Service Fabric Application Deployment task, we have stumbled upon the issue of a timeout during the registration of the application (See screenshot).

![image](https://user-images.githubusercontent.com/28600686/40728016-1994fd4e-6421-11e8-80d8-fd9b9540a4d0.png)

The task Upgrade Settings are:

Upgrade Mode: **Monitored**
Failure Action: **Rollback**
Upgrade Replica Set Check Timeout:
Replica Quorum Timeout:
Timeout:
Force Restart: **False**
Health Check Retry Timeout: **600**
Health Check Wait Duration: **0**
Health Check Stable Duration: **120**
Upgrade Domain Timeout: **3600**
Consider Warnings as Errors: **False**
Default Service Type Health Policy: **0,0,0**
Max Percent Unhealthy Deployed Applications: **0**
Upgrade Timeout: **3600**
Service Type Health Policy Map:

**The cluster is in Azure and is on 6.2.274.9494 fabric version.**

I can't see from the documentation or the logs what we have done incorrectly. Please advise.

**Comment by bishal-pdMSFT** [comment]
@OnlyHicki if your application package is large in size, if can result in timeout while registering the package. You can increase default register timeout in task
![image](https://user-images.githubusercontent.com/7830141/40781622-370e0d6e-64fa-11e8-9fed-e115a4a83c4a.png)

**Comment by OnlyHicki** [comment]
Can't believe I missed that! 🙈
