### ISSUE TITLE
VSTS Release - Phase with partially succeeded install to deployment group Succeeds overall

### ISSUE THREAD

**Issue by JeffRausch** [Microsoft/vsts-tasks#7333]
## Environment
VSTS - ReleaseId 242    
Private Agent - Windows server 2016

## Issue Description
We have a release Phase that's installing to a deployment group with two machines.  It succeeded on one but failed on the other.  The issue is that the phase was marked as "Partially Succeeded" and the install carried on like the phase succeeded.  We need to mark the release as failed if any phase is not fully successful.

![image](https://user-images.githubusercontent.com/1424692/40746712-c14ad47e-6420-11e8-9220-4e2bc2551079.png)

**Comment by vincentdass** [comment]
Can you try using custom phase condition with condition value `eq(variables['Agent.JobStatus'], 'Succeeded')`. The next phase will be executed only if previous phase is succeeded.

![image](https://user-images.githubusercontent.com/20121508/40885915-070da9a8-674d-11e8-8161-acb5177034bc.png)

**Comment by JeffRausch** [comment]
Aah, that does work.  I was checking that variable inside the phases run after and it always showed "Succeeded" but apparently the value of that variable is set differently for the tasks running inside the phase.

That should fix the issue I'm seeing then.  
Thanks!

**Comment by JeffRausch** [comment]
I'm requesting that this issue be reopened.  
When I have the following check on a phase, that phase is always skipped, even if it's the first phase or all phases before it are successful.
`eq(variables['Agent.JobStatus'],'Succeeded')`
But in a task inside a phase if I check that value (as a Custom Condition or inside a script) I get the correct value and can fail the process.  So what I'm currently having to do is have a powershell task as the first task inside every single phase.  In that I'm checking the value of "$env:AGENT_JOBSTATUS" and if it's "PartiallySucceeded" I'm setting the vso "task.complete result=failed" and then throwing an exception from the script so it bombs out the release.  

Is there a different variable that needs to be checked at the Phase level or why would it always be skipping the phase when I'm checking that one?

**Comment by JeffRausch** [comment]
I just did another test with this.  It looks like the "Agent.JobStatus" variable is always empty at the phase level.  When I added a condition with `eq(variables['Agent.JobStatus'],'')` then that phase ran.  

I also tried setting the Task.Complete value in powershell using `Write-Host "##vso[task.complete result=Failed;]DONE"`.  This causes the current phase to be marked as failed but then it continues on and other phases still have the Agent.JobStatus variable empty and that value inside tasks in other phases still shows as "Succeeded".
So from what I can tell the "Agent.JobStatus" value can only be set and read from tasks within the same Phase.  If that's the case then I assume the "Run this phase" condition must be checking something else.

**Comment by JeffRausch** [comment]
More testing.  I created a deployment group with two targets.  In the first phase I caused one target to fail using the following powershell command: 
`if ($env:COMPUTERNAME -ieq "b-qaweb01"){
  Write-Host "##vso[task.complete result=Failed;]DONE"
}`
This caused that phase to have a status of "PartiallySucceeded".  The following phases still had "Agent.JobStatus" as empty and the phase ran if it was set to "Only when all previous phases have succeeded".

So I'm back to square one... if a phase partially succeeds there's no way for me to fail the whole release.

**Comment by niadak** [comment]
@JeffRausch , You are right, "Agent.JobStatus"  value is persistent with in a phase and not across phases. I will check with my team and get back to you on how to achieve your scenario.

**Comment by JeffRausch** [comment]
Hello,
Is there any update with this?  We're waiting to move our full release process over until I can get this resolved.  If there's no other way then the only thing I can think of would be to store off an external variable somewhere that can be checked at the beginning of all phases but this is far from ideal.  Is there is some type of hidden variable that the phases are checking that I could also check in the phase condition?  Just wondering how the phase conditions currently work if they're not able to check the Agent.JobStatus variable.

Thanks!

**Comment by niadak** [comment]
@JeffRausch , Sorry for late response. Today it is not possible to update a variable value in one phase and use it in next phase. We are tracking this feature. Refer to https://github.com/Microsoft/vsts-tasks/issues/4743 

For your scenario, you can try the below as work around:
 Use Agent less phase (Manual Intervention task) between both the phase and resume\reject the release manually based on previous phase state. Refer to below doc for more details on Manual Intervention task

https://blogs.msdn.microsoft.com/aseemb/2016/09/18/how-to-use-manual-intervention-task-in-release-management/

**Comment by niadak** [comment]
@JeffRausch , If you want the work flow to be completly automated and dont want to use Manual intervention, you need to store the variable in Azure Key Vault or other persistent store and access it across phases. This is what you have already mentioned.

**Comment by SumiranAgg** [comment]
@JeffRausch Did any of the workarounds work for you or are you still blocked on this?

**Comment by JeffRausch** [comment]
Yes.  Looking at the issue you referenced above someone mentioned using tags on the release.  I was able to successfully tag the release when a phase fails and then at the beginning of the next phase (which is only run on a single machine) I'm checking for that tag and then failing out again.  So this is a successful workaround for now.  
I'll close this and watch for feature #4743 to be implemented.  Although that feature talks about variables between agents, I'm hoping that a simple way to fail a PartiallySucceeded release becomes available in the future.
Thanks!
