### ISSUE TITLE
Azure File Copy failing in Release

### ISSUE THREAD

**Issue by PradeepKumarMunirathinam** [Microsoft/vsts-tasks#7338]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
     VSTS Server
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
    Account Name = <>
   Team Project Name = <>
   Build Number = 10116
  Release Name = <>
   Release Number = 177
 
- Agent - Hosted or Private: 
      Issue is with both Hosted and Private
    
    - If using Hosted agent, provide agent queue name:
      Agent Queue Name = Hosted
    - If using private agent, provide the OS of the machine running the agent and the agent version:      
         Agent.OS= Windows_NT
         Agent.OSVersion | 6.3.9600
         Agent.Version | 2.124.0
         AzurePS | 5.0.1

## Issue Description

I am Running a task in VSTS to copy folder from Local Git into Azure Blob Storage Account.
The Azure File Copy task works fine when i run the task from Build.
But when i configure the same task in Release , it fails.

I have tried the Scenario with VSTS Hosted agent and Private agent.
In both the case i am getting the same result.

[Include task name(s), screenshots and any other relevant details]

### Error logs
[tasklog_4.log](https://github.com/Microsoft/vsts-tasks/files/2075752/tasklog_4.log)

I have attached the error/debug log in the above link.
Kindly revert as soon as possible.

**Comment by vincentdass** [comment]
@PradeepKumarMunirathinam , Can you try reducing the file path of the agent: (say `C:\agent\vsts-agent-win7-x64-2.124.0` to `C:\A`) and retry the deployment . We identified this as a genuine issue and added it to backlog.

**Comment by PradeepKumarMunirathinam** [comment]
Hi @vincentdass.
As mentioned in the logs, i made the directory length less than 260 characters. And reran the task in my release and my release got succeed.

Thanks for you suggestion.

**Comment by rajatagrawal-dev** [comment]
I am not able to reproduce this error. I tried with the exact paths mentioned in the logs and even longer paths with no repro. If you face this issue please let us know.
