### ISSUE TITLE
"The environment block used to start a process cannot be longer than 65535 bytes" Azure RM Web App Deploy

### ISSUE THREAD

**Issue by edtheshed** [Microsoft/vsts-tasks#7341]
## Issue
Our Release used to get this error, and is now getting it again on one of the web app deploy tasks:

```
Add-Type : The environment block used to start a process cannot be longer than 65535 bytes.  Your environment block is 
2018-05-31T10:37:38.4679579Z 67051 bytes long.  Remove some environment variables and try again.
2018-05-31T10:37:38.4687668Z At C:\Build\vsts-agent-1\_work\_tasks\AzureRMWebAppDeployment_497d490f-eea7-4f2b-ab94-48d9c1acdcb1\1.0.19\ps_modules\Vs
2018-05-31T10:37:38.4803680Z tsTaskSdk\LongPathFunctions.ps1:212 char:1
```
Unfortunately we have a large amount of variables for app config. Can't really do much about that... We had this error before and after reading https://github.com/Microsoft/vsts-task-lib/issues/228 we had upgraded the agent to the latest.

## Environment
VSTS account: solidsoftreply-emvs.visualstudio.com
National Blueprint System
NBS Application - Prod
build 106
private agent running 2012 r2, agent version 2.131.0

**Comment by vincentdass** [comment]
@edtheshed , Currently, the selected task is in 1.* task version. Can you please update the task version to 3.* or 4.* and retry the deployment?

**Comment by edtheshed** [comment]
yep looks like that was it! thanks very much for your help
