### ISSUE TITLE
Update Download Build Artifacts task to set a DowloadedArtifactBuildNumber variable

### ISSUE THREAD

**Issue by cosminstirbu** [Microsoft/vsts-tasks#7352]
Hello,

We have a build definition that runs our nightly acceptance tests suite (we run them nightly because they are end to end and they take a few hours to run).

This build definition uses a "schedule trigger" and it uses the Download Build Artifacts task to download the artifacts from the latest build of a different build definition.

We'd like to keep in sync the build number of the artifact source build with the build number of the acceptance tests build - however it doesn't seem that there is a way to know what was the build number of the artifact source build.

For "completed triggers", we're using Build.TriggeredBy.BuildNumber variable, and we would like a similar variable that is injected / set by the Download Build Artifacts.

Thank you,
Cosmin

**Comment by GitHubSriramB** [comment]
@cosminstirbu - We currently support taking latest build from a build definition as input to the download build artifact task and log the build that is used. However we don't output this build as a variable from the task. If we add output variable (say DownloadBuildArtifacts.BuildNumber) would that suffice?

**Comment by cosminstirbu** [comment]
Hi @GitHubSriramB,

Yes, we would use this output variable to set the build number of the acceptance test suits build.

So a DownloadBuildArtifacts.BuildNumber or something similar would be exactly what we need (not sure if we want to make it even more complex and take into account several Download Build Artifacts tasks, have them output some sort of unique variable - but for now having a single variable that will probably be overridden if there are several tasks should be fine).

Thank you,
Cosmin

**Comment by GitHubSriramB** [comment]
@cosminstirbu - we will add support for this output variable and let you know.

**Comment by cosminstirbu** [comment]
Hello,

It seems that this ticket was closed.
Were the changes deployed as well?

Thank you,
Cosmin

**Comment by gykuma** [comment]
Hi @cosminstirbu ,

The changes will be deployed in 2-3 weeks.

Thanks,
Gyan
