### ISSUE TITLE
Set Azure Storage Emulator Task as an Environment Variable

### ISSUE THREAD

**Issue by LukeBillo** [Microsoft/vsts-tasks#7363]
Apologies if this is the wrong place to raise this - wasn't entirely sure where to raise this issue. Feel free to direct me elsewhere if so.

I have a build job on VSTS for simply building a solution that uses Azure table storage, and wanted to run integration tests that the Azure storage emulator. To do this, I found that Azure storage emulator is already installed on a hard-coded path and ran it from this installation directory. See the image below:

![VSTS build pipeline](https://i.imgur.com/VGmAtSd.png)

This doesn't look particularly elegant, and was wondering if it's possible to add the executable to an environment variable or add it to the PATH?

**Comment by chrisrpatterson** [comment]
@LukeBillo this does not seem like an issue specific to a task.  It is more like a feature request for the hosted pools.  Please close this issue open one in the microsoft/vsts-image-generation repo.
