### ISSUE TITLE
InstallSSHKey is unable to access secure file that definitely exists

### ISSUE THREAD

**Issue by willmorgan** [Microsoft/vsts-tasks#7378]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
Account name: digital-identification
Project name: digital-identification
Build definition name: admin-api
Build number: #1104

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name: Hosted VS2017

## Issue Description

InstallSSHKey@0 seems to be unable to access the secure file. I've granted the Hosted VS2017 agent access to the secure file in question, but I see this:

> Phase : Step input sshKeySecureFile references secure file idmee_machine_vsts_201805.key which could not be found. The secure file does not exist or has not been authorized for use.

I've tried various configurations, file names, tried adding extensions, granting global access, to no avail.

### Error logs

Phase : Step input sshKeySecureFile references secure file idmee_machine_vsts_201805.key which could not be found. The secure file does not exist or has not been authorized for use.

**Comment by brcrista** [comment]
I tested this and it is working fine for me.  Can you run with System.Debug=true and send us the full log file for the Install SSH Key step?  Also, how did you upload your private key?

**Comment by willmorgan** [comment]
Hi @brcrista, it seems that it might be due to the fact I'm doing this on a feature branch and that my default branch's `.vsts-ci.yml` doesn't reference the secureFile:

https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-authz.md

**Comment by brcrista** [comment]
Ok, that is helpful information.  Are you able to clone the build definition and set the default branch to your feature branch to see if that fixes the issue?

**Comment by brcrista** [comment]
Or, I don't think you can clone YAML definitions.  But create a new definition, etc.

**Comment by ericsciple** [comment]
We have a better resource authorization experience coming in one to two sprints.

A workaround that covers most cases is, navigate to the build definition in the web, switch the default branch to your branch, save, revert back to your desired default branch, save again.  The act of saving the definition loads the file (from the default branch) and authorizes discovered resources.

**Comment by willmorgan** [comment]
Thanks guys.

We've had to set up our own npm registry to workaround this issue, which has been a bit of a time sink for us - but if we encounter another requirement where we need to reference secure files on feature branch builds then we'll try those steps above.

**Comment by tlindsay42** [comment]
Just ran into this issue again after replacing a SSH key 😢

**Comment by tlindsay42** [comment]
The workaround fixed it

**Comment by brcrista** [comment]
You mean you set up your own npm registry?  I think I'm missing how NPM ties in here.

**Comment by brcrista** [comment]
Reopening as it seems this is still happening to people

**Comment by tlindsay42** [comment]
Sorry for not being clear @brcrista.  I had an existing job with a InstallSSHKey@0 task that was working fine, but when I replaced the SSH private key secure file a few days ago, the task started failing until I came across this issue and implemented @ericsciple's workaround of switching the branch in the build pipeline > save > restore the desired branch > save > trigger manual build.

**Comment by brcrista** [comment]
Ok, thanks @tlindsay42 .  In that case, this is a known issue with our resource authorization that we are working to fix.  I'll mark this as closed again.

**Comment by Gingonic** [comment]
Still happening

**Comment by brcrista** [comment]
@Gingonic does the workaround posted above fix it for you?
