### ISSUE TITLE
DotNet Core - Publish - Deletes output folder causing Publish Artifact task to fail

### ISSUE THREAD

**Issue by wahyuen** [Microsoft/vsts-tasks#7389]
## Environment
- Server - VSTS

- Agent - Hosted 2017
## Issue Description

Currently attempting to use the new DotNet core build template for a DotNet Core 2.1.0 WebAPI project. It appears that the default template causes issues in how it zips the output up and subsequently deletes the output folder. This causes issues with the default template in the downstream task of Publish Artefact as it can no longer find the location of the artefact itself.

I would not have expected this to be default behaviour for users attempting to use the template out of the box.

### Workaround

Able to workaround by modifying the output directory in the Publish task to write to a subfolder. This then causes the zip to be placed 1 level up from this new subfolder, which is where the default location is for the subsequent Publish Artefact task.

ie. `--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)\artifact`

### Error logs

> 2018-06-07T02:24:17.8506421Z ##[debug]Zip Source: D:\a\1\a
2018-06-07T02:24:17.8508196Z ##[debug]Zip arguments: Source: D:\a\1\a , target: D:\a\1\a.zip
2018-06-07T02:24:18.0627450Z ##[debug]Successfully created archive D:\a\1\a.zip
2018-06-07T02:24:18.0628182Z ##[debug]rm -rf D:\a\1\a
2018-06-07T02:24:18.0629813Z ##[debug]removing directory

> 2018-06-07T02:24:18.3032197Z ##[debug]PathtoPublish=D:\a\1\a
2018-06-07T02:24:18.3032581Z ##[debug]check path : D:\a\1\a
2018-06-07T02:24:18.3051731Z ##[debug]task result: Failed
2018-06-07T02:24:18.3052522Z ##[error]Publishing build artifacts failed with an error: Not found PathtoPublish: D:\a\1\a

**Comment by sachinma** [comment]
Are you using the template without any change? Could it be that you have un-set "Add project name to publish path" field. I am not able to repro this with the default template. If possible, can you share the complete debug logs (here or send them to RM_Customer_queries@microsoft.com).

**Comment by wahyuen** [comment]
The only thing I've unchecked from the default template is the `Publish Web Projects' field (WebAPI project). I can confirm the `Add project name to publish path` is still set. 

I've emailed through the full logs to the above email address :)

**Comment by sachinma** [comment]
I looked at the logs, and I think I understand the issue. This is when you pass "Path to project(s)" as empty - then we are not able to publish individual projects to separate sub-folders. You can use the same pattern as you have in other tasks "**/*.csproj" or the path to the project that you want to publish and then things should work fine. 

The current work-around you have to put an artifacts sub-directory is not the optimal solution, since if you have multiple webApi projects - their published output will conflict with each other.

In the meantime, I will look at how best to fix this in the task code.

**Comment by ds-ms** [comment]
This issue has been fixed, will be rolled out in a few weeks! :)
