### ISSUE TITLE
BDT Workflow

### ISSUE THREAD

**Issue by SWarnberg** [Microsoft/vsts-tasks#7403]
Hi,

I'm trying to figure out how to use the new VSTest task in a BDT workflow, using DevTestLab. Previously we've successfully used the Deploy Test Agent and Run Functional Test tasks on target VM's, but since they are now deprecated, I wonder how we're supposed to use this task an remote machines?

I had the following workflow with VSTS Release Management in mind:  

1. Create VM with **Azure DevTest Labs Tasks**.
2. Deploy release artifacts, start services etc.
3. Run Coded UI tests.
4. Delete VM.

But as I understand, this task need to be executed on the agent. However, build machines can't run UI tests and I don't want to install build agents on 20 different test machines. It simply feels wrong.
I was thinking about configuring an agent on the DevTest VM to a deployment group. But that also gives problems; when you delete the VM, it will remain in the deployment group.

Please advice. Has anyone figured out a good workflow for above using this task?

**Comment by kaadhina** [comment]
@SWarnberg 
The build agent machines can run UI tests and the steps you have mentioned above is the recommended approach if you want to dynamically create VMs, run tests and delete them.
However, if dynamic creation of VMs is not necessary, you may create a pool of build agents and use them to run the tests.
Here is a [link](https://blogs.msdn.microsoft.com/devops/2017/03/26/vstest-task-dons-a-new-avatar-testing-with-unified-agents-and-phases/#FAQ) that explains how the vstest task works.

Please do let us know if you face any issues or have more questions while moving to the new task.

**Comment by SWarnberg** [comment]
Hmm, that didn't really solve my question. Can you elaborate on how to setup a release workflow, and in which phases each task will execute in?
The problem with the steps I mentioned is that they execute on the Agent phase on the build machine, and the VSTest task can't execute remotely on the newly created VM.

**Comment by kaadhina** [comment]
Sure.
Firstly, if the dynamic creation is not mandatory, I will recommend setting up a pool of agents and using it to run the tests, as mentioned in the link. In that case you will just have one phase where you will have the test task.
If it is mandatory, you can setup one phase where you can create the machines, setup build agents on them and configure them to run against a particular pool. You can then setup another phase to run against that pool, where you can have the test task.

**Comment by PBoraMSFT** [comment]
@SWarnberg - I will be happy to chat with you to go over your workflow and get you setup. Can you send me a mail at pbora AT microsoft DOT com?

**Comment by SWarnberg** [comment]
Thanks. I may contact you when we come to that phase. Right now I'm setting up the VM templates in DevTestLab to be used by the workflow, which is why I want to understand ahead what the requirements will be.
As I understand, either an agent pool or a deployment group is needed, where the test vm should be added. I'm leaning against the deployment group option. I'm also reconsidering to have a fixed set of vm's that are started and stopped during the workflow instead of creating and deleting.
However, I'm not sure I see the true benefit of using this task instead of the old RFT task. I think this pretty much complicates things instead of making it easier.

**Comment by ShreyasRmsft** [comment]
@SWarnberg can we close this issue? You can open a support ticket or another issue when you get to the stage when you are trying this out.

**Comment by SWarnberg** [comment]
@ShreyasRmsft sure. Even though I think it's a bit drastic to "deprecate" the RFT task, I have a fair idea on how you think these tasks should be set up.
