### ISSUE TITLE
[Azure SQL Database Deployment] task fails when SQL server name provided with "tcp:" prefix

### ISSUE THREAD

**Issue by vineetmimrot** [Microsoft/vsts-tasks#7424]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
VSTS

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
Windows

## Issue Description
As per the task documentation, it supports server name input same as SSMS. But SSMS also allows to provide input database server name in format of "_tcp:FabrikamSQL.database.windows.net, 1433_", though while providing the similar input to the task it fails with error _unable to connect to the server_. Please check this. Also as per the [MSDN definition of connection string](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlconnection.connectionstring(v=vs.110).aspx) "_Data Source must use the TCP format or the Named Pipes format_." 

_Azure SQL Server Name*: The connection string for the Azure SQL Server and the format is same as that is followed in SQL Server Management Studio. For example, FabrikamSQL.database.windows.net, 1433 or FabrikamSQL.database.windows.net are both valid Azure SQL Server names._

[Include task name(s), screenshots and any other relevant details]

### Error logs

[Insert error from the logs here]

**Comment by Ajay-MS** [comment]
@vineetmimrot 

Task should work fine with tcp: perfix

**Syntax**
tcp:\<sqlservername>.database.windows.net,1433

I have just tried with above mentioned format. 

**Task Input**
![image](https://user-images.githubusercontent.com/16772764/41334362-fef0e52e-6f02-11e8-800f-070dcbf15114.png)

**Task Logs**
```
2018-06-13T06:35:00.7071580Z ##[debug]Executing : "C:\Program Files\Microsoft SQL Server\140\DAC\bin\SqlPackage.exe" /SourceFile:"D:\a\r1\a\MyFirstProject-CI\drop\AzureSQLDB.dacpac" /Action:Publish /TargetServerName:"tcp:ajya2.database.windows.net,1433" /TargetDatabaseName:"Testdb4" /TargetUser:"ajay12" /TargetPassword:"********" /p:AllowIncompatiblePlatform=true /TargetTimeout:120
2018-06-13T06:35:01.1140515Z Publishing to database 'Testdb4' on server 'tcp:ajya2.database.windows.net,1433'.
2018-06-13T06:35:01.8394371Z Initializing deployment (Start)
2018-06-13T06:35:06.9069314Z Initializing deployment (Complete)
2018-06-13T06:35:06.9740719Z Analyzing deployment plan (Start)
2018-06-13T06:35:06.9880463Z Analyzing deployment plan (Complete)
2018-06-13T06:35:06.9880792Z Updating database (Start)
2018-06-13T06:35:07.6738382Z Update complete.
2018-06-13T06:35:07.7834947Z Updating database (Complete)
2018-06-13T06:35:07.7851535Z Successfully published database.
2018-06-13T06:35:07.7995646Z ##[debug]No Firewall Rule was added
2018-06-13T06:35:07.8062268Z ##[debug]Leaving script DeploySqlAzure.ps1
```

Can you please share debug logs for your task where it is failing.

**Comment by vineetmimrot** [comment]
PFA logs:
[ReleaseLogs_2.zip](https://github.com/Microsoft/vsts-tasks/files/2101052/ReleaseLogs_2.zip)

![image](https://user-images.githubusercontent.com/4174297/41395243-979807a4-6fca-11e8-85b0-11f2793a1c36.png)

Following are my observations:
1. If I remove "tcp:" from the server name then it works out.
2. If "tcp:" is present in the server name and if I remove "@<server-name>" from the username then also it works out.
From the logs I can see that even if "@<server_name>" present in the username, your code again appends it, in case "tcp:" is present in the server name .

**Comment by Ajay-MS** [comment]
@vineetmimrot 

We will fix this scenario soon. 

But  assuming you are not blocked on this issue as there are following options 
1. If SQL server name is being provided with TCP: prefix then provide username directly instead of <username>@<servername>
2.  Provide server name with TCP: prefix if username is being provided in <username>@<server name> format.

**Comment by Ajay-MS** [comment]
@vineetmimrot 

We have fixed this issue. 
PR - [SQL username fix](https://github.com/Microsoft/vsts-tasks/pull/7632)
