### ISSUE TITLE
Helm deploy, Value File, vsts variable substitution

### ISSUE THREAD

**Issue by davidwmartines** [Microsoft/vsts-tasks#7427]
How can I use the VSTS variables in the Value File used in the "**Package and deploy Helm charts (Preview)**" task?   I tried using a value file artifact (external to the chart) containing `KEY: $(some-var)`, but just got the literal "$(some-var)".

**Comment by dendle** [comment]
I have the same issue when supplying the "destination" input to the helm "package" command.

Looking at the code, the input type is set to string, wheres the helm CLI is expecting a path:
https://github.com/kubernetes/helm/blob/master/docs/helm/helm_package.md
Shouldnt the input be set to type "filePath"?

Cheers,
Matt

**Comment by vithati** [comment]
@davidwmartines, "Package and deploy Helm charts" task install and upgrade commands have 'Set values' input to override the Value file values, you can use same. you can define key=$(some-var) in 'Set values' input or  you can add --set key=$(some-var) in arguments. 

![image](https://user-images.githubusercontent.com/19663618/42864962-d020eeb2-8a85-11e8-823b-4128f88463b4.png)

**Comment by vithati** [comment]
@dendle, "destination" input you can specify absolute filepath like  "C:\agent\helm" or you can use release environment variables in "destination" input. also. ex:-$(SYSTEM.ARTIFACTSDIRECTORY)\ . Can you specify what error are you seeing?

**Comment by dendle** [comment]
Hello @vithati 
In the build logs, the default variable is not substituted - I see the command being passed *exactly* what is in the destination field.

Here is the error:

> Error: Failed to save: GetFileAttributesEx $(Build.ArtifactStagingDirectory): The system cannot find the file specified.

Also, the tooltip help for that input says "Specify values in a YAML file or a URL." - this seems wrong given your helpful explanation.

Thanks,
Matt

**Comment by vithati** [comment]
Hi @dendle, I have used $(Build.ArtifactStagingDirectory) in task in build defintion, it working for me. How are you specifying environment varaible $(Build.ArtifactStagingDirectory) in task. Can you share your task screenshot? I will change tooltip info.
![image](https://user-images.githubusercontent.com/19663618/42985143-c7f937d8-8c0d-11e8-9460-8d3298ce8bd2.png)

**Comment by dendle** [comment]
I just used the default value as-is, and substitution did not work.

I also just tried what you have shown, where you add a subfolder to the varible, with the same results:
2018-07-24T11:04:23.5489170Z [command]C:\hostedtoolcache\windows\helm\2.8.2\x64\windows-amd64\helm.exe package --dependency-update --save --destination $(Build.ArtifactStagingDirectory)/Dendlebot-chart "D:\a\r1\a\_Dendlebot-Docker container-CI\Dendlebot-chart"

Screenshot below:
![vstsissue](https://user-images.githubusercontent.com/3049643/43134484-1e788dc8-8f3a-11e8-8f8b-fafaced479b8.PNG)

**Comment by dendle** [comment]
Does it matter which preview features (in VSTS) I have turned on?

![vstspreview](https://user-images.githubusercontent.com/3049643/43134567-580b4dc8-8f3a-11e8-928b-da01e5ce56e5.PNG)

**Comment by dendle** [comment]
Hi vihati

When i read your post it just dawned on me; i am using this in a **release** and not a **build**.

Can you test again in a release setting please? I am really hoping you replicate the issue!

I will do as you have asked and post accordingly.

Thanks!

**Comment by dendle** [comment]
Yeah - it works in a build setting.

Probably because the variable is only defined in build and not release - sorry!

Also, my assumption was that if the directory was not there it would create it - although this does not appear to happen.  There also doesn't appear to be a "Make Dir" task?

Thanks for your help!

**Comment by vithati** [comment]
@dendle, $(Build.ArtifactStagingDirectory) not avaiable in 'Release', because of that it didn't work. You can find availble predefined varaible for 'Release' here https://docs.microsoft.com/en-us/vsts/pipelines/release/variables?view=vsts&tabs=batch You can use other task like powershell, bash task to create dir.

**Comment by dendle** [comment]
Thanks for your help vihati

**Comment by guythetechie** [comment]
@vihati How does this work for secret release variables? key=$(some-var) doesn't seem to work if some-var is a secret variable. The task runs, but the actual value of some-var isn't passed. Thanks!

**Comment by guythetechie** [comment]
Please disregard previous post, it was a mistake in my configuration. Thanks!
