### ISSUE TITLE
how can I config 'Visual Studio Test' task in order to run tests under elevated privilege?

### ISSUE THREAD

**Issue by Liphi** [Microsoft/vsts-tasks#7431]
Hi, for my vsts build definition (https://onedrive.visualstudio.com/Security/ODSP%20Protect/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=2062), I wanna config the 'Visual Studio Test' task to run tests under admin account with elevated privilege because several tests require elevated admin privilege. Is it supported? If no, which task template should I use?

**Comment by ShreyasRmsft** [comment]
@Liphi all you have to do is configure your vsts-agent with the same admin credentials and the task will run using those

**Comment by ShreyasRmsft** [comment]
@Liphi lemme know if you need anymore help/clarification and do let me know if this solves your issue.

**Comment by Liphi** [comment]
We’re using the hosted build agents provided by VSTS (running on their infrastructure, not ours) so we don’t have the necessary admin credentials to configure this.
Any other solution?

**Comment by bryanmacfarlane** [comment]
builds in the hosted pool run as admin

**Comment by Liphi** [comment]
Then may I know why my test throws access denied error when it tries to register an NT service ? It works on my dev box when I run the test with elevated Visual Studio.

**Comment by Liphi** [comment]
We're already using Hosted VS2017 as the 'Agent queue'.

**Comment by ShreyasRmsft** [comment]
@Liphi can you use the powershell task to try and register an NT service? If this also fails then the agent on the Hosted pools clearly does not have this permission and no task will be able to achieve registering an NT service. But if the powershell task can accomplish this with a simple script the we can further see why it's not happening via the test code.

Can you get back to me on this?

**Comment by ShreyasRmsft** [comment]
@Liphi any updates here?

**Comment by ShreyasRmsft** [comment]
@Liphi closing due to no response. Please re-open if you have more info/updates for us.
