### ISSUE TITLE
Can't copy file to Azure Blob Storage

### ISSUE THREAD

**Issue by VinKamat** [Microsoft/vsts-tasks#7432]
What are the other pre-requisites for private agent such that Azure tasks are run properly? I've installed Azure PS (v6.2.1) and AzureRM modules however still can't **copy a file** to **Azure Blob Storage.** 

This works fine if I use the Hosted VS2017 agent.

Log from the task:

2018-06-11T19:28:23.4792254Z ##[section]Starting: AzureBlob File Copy - README.md
2018-06-11T19:28:23.5140067Z ==============================================================================
2018-06-11T19:28:23.5140740Z Task         : Azure File Copy
2018-06-11T19:28:23.5141068Z Description  : Copy files to Azure blob or VM(s)
2018-06-11T19:28:23.5141434Z Version      : 1.0.115
2018-06-11T19:28:23.5141759Z Author       : Microsoft Corporation
2018-06-11T19:28:23.5142203Z Help         : [More Information](https://aka.ms/azurefilecopyreadme)
2018-06-11T19:28:23.5142640Z ==============================================================================
2018-06-11T19:28:27.1311142Z Added TLS 1.2 in session.
2018-06-11T19:28:27.8562122Z **##[error]Requested registry access is not allowed.**
2018-06-11T19:28:27.9075691Z ##[section]Finishing: AzureBlob File Copy - README.md

**Comment by bryanmacfarlane** [comment]
@kmkumaran 

Note that there isn't a requirement to run private agents as admin.

**Comment by niadak** [comment]
@VinKamat , Can you please share the debug log with us?
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

You can email us the logs to RM_Customer_Queries@microsoft.com

**Comment by VinKamat** [comment]
@niadak  Here it is:

Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\AzureRM\6.2.1\AzureRM.psm1'.
Entering Get-SdkVersion.
Leaving Get-SdkVersion.
Leaving Import-FromModulePath.
Leaving Import-AzureModule.
Leaving Initialize-Azure.
Caught exception from task script.
Error record:
Get-ItemProperty : Requested registry access is not allowed.
At C:\agent\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.115\ps_modules\VstsAzureHelpers_\ImportFunctions.ps1:188 char:34
+ $installedApplications = Get-ItemProperty -Path $regKey
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : PermissionDenied: (HKEY_LOCAL_MACH...all\QualysAgent:String) [Get-ItemProperty], Securit yException
+ FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.GetItemPropertyCommand
Script stack trace:
at Get-SdkVersion, C:\agent\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.115\ps_modules\VstsAzureHelpers_\ImportFunctions.ps1: line 188
at Import-FromModulePath, C:\agent\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.115\ps_modules\VstsAzureHelpers_\ImportFunctions.ps1: line 94
at Import-AzureModule, C:\agent\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.115\ps_modules\VstsAzureHelpers_\ImportFunctions.ps1: line 40
at Initialize-Azure, C:\agent\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.115\ps_modules\VstsAzureHelpers_\VstsAzureHelpers_.psm1: line 51
at <ScriptBlock>, C:\agent\_work\_tasks\AzureFileCopy_eb72cb01-a7e5-427b-a8a1-1b31ccac8a43\1.0.115\AzureFileCopy.ps1: line 55
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 22
at <ScriptBlock>, <No file>: line 18
at <ScriptBlock>, <No file>: line 1
Exception:
System.Security.SecurityException: Requested registry access is not allowed.
at System.ThrowHelper.ThrowSecurityException(ExceptionResource resource)
at Microsoft.Win32.RegistryKey.OpenSubKey(String name, Boolean writable)
at Microsoft.PowerShell.Commands.RegistryWrapper.OpenSubKey(String name, Boolean writable)
at Microsoft.PowerShell.Commands.RegistryProvider.GetRegkeyForPath(String path, Boolean writeAccess)
at Microsoft.PowerShell.Commands.RegistryProvider.GetRegkeyForPathWriteIfError(String path, Boolean writeAccess)
The Zone of the assembly that failed was:
MyComputer
Requested registry access is not allowed.
Processed: ##vso[task.logissue type=error]Requested registry access is not allowed.
Processed: ##vso[task.complete result=Failed]

**Comment by niadak** [comment]
@VinKamat , It will be great if you can share the complete debug logs with us. 
I have tried the scenario with AzurePS V6.2.1 and it is working for me.
You can email us the logs to RM_Customer_Queries@microsoft.com.

**Comment by VinKamat** [comment]
@niadak sent the logs to the email address, let me know what you find. Thanks.

**Comment by niadak** [comment]
@VinKamat Thanks for sharing the logs with us. Can you check if the agent is running with non-admin account ? If so, can you configure the agent with admin account and try?

**Comment by rajatagrawal-dev** [comment]
@VinKamat As discussed, the task requires that the agent be configured with credentials that has read access to registry. By default, NT Authority/Network Service account has these permissions. For some reason, NT Authority/Network Service on your VM is not able to that, but you were able to run the task using admin credentials.

You can try and create a new user on your VM and try to configure it to have read access on registry. You can also try to create a new VM to see if you still see the same behaviour, because I tried on Windows server 2016 datacenter VM and it worked for me with default settings.

**Comment by rajatagrawal-dev** [comment]
Closing this issue as this is not a task issue but rather a infra/permissions issue. 
@VinKamat Please use our RM_Customer_Queries mail thread if you need further assistance regarding this.
