### ISSUE TITLE
Azure File Copy - unable to copy to folder within a container

### ISSUE THREAD

**Issue by hairydawgy** [Microsoft/vsts-tasks#7442]
I have created an Azure File Copy Task in VSTS building with the Hosted VS2017 agent.  My connection type is Azure Classic and my Destination Type is Azure Blob.   I have specified the container name and I am able to copy a file to the root of the container; however, I need to copy the file to a folder within the container.  I have attempted to specify the path in the container name field, but this failed (invalid characters in container name).  I also attempted to specify the destination (Dest) as an argument, but this failed as well: [ERROR] The syntax of the command is incorrect. The "Dest" parameter was specified multiple times.

Is it possible to use this task to copy to a folder within the container?

**Comment by niadak** [comment]
Can you provide blob prefix value in the task and try? It will create a folder with the blob prefix name and copy the files under it.

![image](https://user-images.githubusercontent.com/11937515/41450720-23bcbde4-7087-11e8-99f2-42a65354507e.png)

**Comment by hairydawgy** [comment]
@niadak  that worked!  Thank you.  I suggest updating the tooltip as it wasn't obvious that adding a blob prefix related to virtual folders.
