### ISSUE TITLE
Release gate doesn't support TaskCompleteEvent for "Invoke REST API" task

### ISSUE THREAD

**Issue by boydc2014** [Microsoft/vsts-tasks#7446]
## Environment
VSTS: 
https://msasg.visualstudio.com/Bing_and_IPG/Official%20Account%20Team/_releaseProgress?releaseId=72307&_a=release-pipeline-progress

## Issue Description

I created a pre-deployment release gate, with one task "Invoke REST API", and set the success method to "Callback". Then my service receive a call with projectID, jobID, taskID, auth, etc. 

When my service done it's work and trying to update the status using the following code:

```
taskClient.RaisePlanEventAsync(projectid, hubName, planid, new TaskCompletedEvent(jobid, taskid, TaskResult.Canceled)).SyncResult();
```
BTW: set taskid = jobid, or set jobid = lastHttpTaskTimeId wouldn't work

it has an exception saying "'The orchestration session 0040fec8fc7d45a98b9f45242d5bdeda_f09026d860b74579ae21f0891d4f16f9_36642e1dbdbd4ffeaa3388277731454d not found for hub Gates."

I used the same code to update an agentless phase sucessfullly, looks like their are some differences between agentless phase and release gate, even with the same kind of task.

**Comment by bansalaseem** [comment]
The async mode does not work with gates. Can you please share more details about your gate?

**Comment by boydc2014** [comment]
Thanks @bansalaseem for confirm, so maybe we should restrict the options of complete criteria for a REST API task result.

Our gate is just simple running some heavy performance test after we deploy our code to INT env, by calling an API to our own testing service, when the testing service is done, report the result back to gate. Then gate passed, then deploy to PROD.

**Comment by brechtvan** [comment]
I recieve this error after using this several months already in production.. Has something changed to VSTS? My release pipeline is broken now...

taskClient.RaisePlanEventAsync(command.ProjectId, hubName, command.PlanId, new TaskCompletedEvent(command.JobId, taskInstanceId, TaskResult.Succeeded)).SyncResult();

**Comment by bansalaseem** [comment]
@brechtvan What error are you observing?

**Comment by brechtvan** [comment]
Hi,

@bansalaseem 
![image](https://user-images.githubusercontent.com/31763421/42689631-6cc83100-86a1-11e8-8de2-a4f18d1053be.png)

I have the above deployment process. I deploy to deployment slot, start an Azure function that executes tests against the deployment slot and reports back to VSTS. If all good swap the slot to production. Then execute the same tests on the production slot. This has worked for quite some time, but on 2018-07-05 this stopped working. Without any changes on my side. The error I recieve is the following:

_Exception while executing function: TestLiveEnvironment The orchestration session f08f2868a06b418e83d1ac3d65759bd2_f2677e0ee2344bf29cc3077d0c7e58ea_f2677e0ee2344bf29cc3077d0c7e58ea not found for hub Release._

Failing code: taskClient.RaisePlanEventAsync(command.ProjectId, hubName, command.PlanId, new TaskCompletedEvent(command.JobId, taskInstanceId, TaskResult.Succeeded)).SyncResult();

**Comment by sureshtadisetty** [comment]
@boydc2014 Please try change jobId = taskId and taskId = Guid.Empty, for Gates only.

**Comment by madhuv-msft** [comment]
@boydc2014 would you check @sureshtadisetty suggestion?

**Comment by bansalaseem** [comment]
Resolving this issue because of no response.

**Comment by getvivekv** [comment]
Hi @sureshtadisetty I do not think this is working. Just got this error when trying to setup a gate

https://orgName.vsrm.visualstudio.com/0743fde1-7465-47b2-8226-0c3b84142d6e/_apis/distributedtask/hubs/gates/plans/44eea82e-db9c-44b1-a46b-3bd1820b9296/events?api-version=2.0-preview.1

{"name":"TaskCompleted","result":"succeeded","jobId":"7031c3e2-1099-4464-982a-5e6c5ca776d2","taskId":"1f9ce5cc-fab2-4a62-a756-f3d36b11bb6c"}


The error
{"$id":"1","innerException":null,"message":"The orchestration session 44eea82edb9c44b1a46b3bd1820b9296_7031c3e210994464982a5e6c5ca776d2_1f9ce5ccfab24a62a756f3d36b11bb6c not found for hub Gates.","typeName":"Microsoft.VisualStudio.Services.Orchestration.Server.OrchestrationSessionNotFoundException, Microsoft.VisualStudio.Services.Orchestration.Server, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a","typeKey":"OrchestrationSessionNotFoundException","errorCode":0,"eventId":3000}
