### ISSUE TITLE
Getting Publish-UpgradedServiceFabricApplication : Upgrade was Rolled back error when adding resource governance configuration in applicationmanifest.xml file

### ISSUE THREAD

**Issue by Rakesh201180** [Microsoft/vsts-tasks#7447]
We are deploying our application to azure service fabric cluster using VSTS and Octopus build
After adding resource governance parameters. 

```
<Policies>
      <ContainerHostPolicies CodePackageRef="Code" Isolation="default">
        <RepositoryCredentials AccountName="#{ContainerRegistry_AccountName}" Password="#{ContainerRegistry_Password}" PasswordEncrypted="false"/>
        <NetworkConfig NetworkType="Open"/>
      </ContainerHostPolicies>
      <ServicePackageResourceGovernancePolicy CpuCores="1"/>
      <ResourceGovernancePolicy CodePackageRef="Code" CpuShares="1024" MemoryReservationInMB="1024" />
    </Policies>
```
We are getting below error during build.

**Publish-UpgradedServiceFabricApplication : Upgrade was Rolled back.**

Please let us know if any issue is there related to configuration.

we are following below link for configuration

https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-resource-governance

Thanks
Rakesh

**Comment by Rakesh201180** [comment]
Any update on this

**Comment by bishal-pdMSFT** [comment]
@Rakesh201180 I believe the right place for this issue is https://github.com/Azure/service-fabric-issues/issues. Why do you think this is a VSTS task issue?

**Comment by Rakesh201180** [comment]
I raised same in sf issue,closing that
