### ISSUE TITLE
Getting xml parse error after adding HealthConfig in ApplicationManifest.xml

### ISSUE THREAD

**Issue by Rakesh201180** [Microsoft/vsts-tasks#7448]
Hi Team,
We are deploying our application to service fabric using VSTS and Octopus build. 
For HealthCheck Configuration we are defining Below Configuration in applicationManifest file.

```
  <ServiceManifestImport>
    <ServiceManifestRef ServiceManifestName="KxPkgPkg" ServiceManifestVersion="1.0.0" />
    
    <ConfigOverrides />
    <Policies>
      <ContainerHostPolicies CodePackageRef="Code" Isolation="default">
        <RepositoryCredentials AccountName="#{ContainerRegistry_AccountName}" Password="#{ContainerRegistry_Password}" PasswordEncrypted="false"/>
        <NetworkConfig NetworkType="Open"/>
        <HealthConfig IncludeDockerHealthStatusInSystemHealthReport="true" RestartContainerOnUnhealthyDockerHealthStatus="false"/>        
      </ContainerHostPolicies>
     
    </Policies>
    
  </ServiceManifestImport>
```
without **HealthConfig**  build is working fine but when we add 

` <HealthConfig IncludeDockerHealthStatusInSystemHealthReport="true" RestartContainerOnUnhealthyDockerHealthStatus="false"/> `

its showing error in during ServiceFabric deployment step in VSTS build.

Test-ServiceFabricApplicationPackage : Exception while parsing XML file: C:\Users\app-octopus3prd-srv\AppData\Local\Tem 
June 12th 2018 09:45:35Error
p\TestApplicationPackage_11461034170457\irwollel.hjo\staging\ApplicationManifest.xml 
June 12th 2018 09:45:35Error
FileName: C:\Users\app-octopus3prd-srv\AppData\Local\Temp\TestApplicationPackage_11461034170457\irwollel.hjo\staging\Ap 
June 12th 2018 09:45:35Error
plicationManifest.xml 
June 12th 2018 09:45:35Error
At C:\Program Files\Microsoft SDKs\Service  
June 12th 2018 09:45:35Error
Fabric\Tools\PSModule\ServiceFabricSDK\Publish-UpgradedServiceFabricApplication.ps1:135 char:38 
June 12th 2018 09:45:35Error
+ ... nSuccess = (Test-ServiceFabricApplicationPackage $AppPkgPathToUse -Im ... 
June 12th 2018 09:45:35Error
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
June 12th 2018 09:45:35Error
    + CategoryInfo          : InvalidOperation: (:) [Test-ServiceFabricApplicationPackage], FabricImageBuilderValidati  
June 12th 2018 09:45:35Error
   onException 
June 12th 2018 09:45:35Error
    + FullyQualifiedErrorId : TestApplicationPackageErrorId,Microsoft.ServiceFabric.Powershell.TestApplicationPackage 
June 12th 2018 09:45:35Error
 
June 12th 2018 09:45:35Error
Script 'D:\OctopusInstances\Application1\Work\20180612041522-6462-46\staging\DeployToServiceFabric.ps1' returned non-zero exit code: 1 
June 12th 2018 09:45:35Error
Running rollback conventions... 
June 12th 2018 09:45:35Error
Script 'D:\OctopusInstances\Application1\Work\20180612041522-6462-46\staging\DeployToServiceFabric.ps1' returned non-zero exit code: 1 
June 12th 2018 09:45:35Fatal
The remote script failed with exit code 1 
June 12th 2018 09:45:35Fatal
The action Deploy Service Fabric Application on the Octopus Server failed 

Please suggest on this.

Thanks
Rakesh

**Comment by bishal-pdMSFT** [comment]
HealthConfig seems to be a recent feature. And the task might be using an older SDK which results in error. Are you using HostedVS2017 agent or private agent?

**Comment by Rakesh201180** [comment]
We are using private agent

**Comment by bishal-pdMSFT** [comment]
@Rakesh201180 is this resolved? Should we close this issue?
