### ISSUE TITLE
Visual Studio Test task - Published test run link only in logs

### ISSUE THREAD

**Issue by fmanea** [Microsoft/vsts-tasks#7455]
## Issue Description
When running Visual studio test task, i can see in the logs that it published the test results:
```2018-06-12T12:56:53.6252551Z Published Test Run : http://tfs-2013-...```

I want to be able to take the link to where it was published and parse it to another task that sends and email to some custom users.
As this information is not available in any environment variable from the build (we have a powershell task that shows all the environment variable gci env:* | sort-object name), how can we parse that information from the logs to a new task?

**Comment by ShreyasRmsft** [comment]
@fmanea you can use a simple powershell script to get [environment variables containing the build/release id](https://docs.microsoft.com/en-us/vsts/pipelines/build/variables?view=vsts&tabs=batch#buildbuildid) of the ongoing build or release and use the [vsts rest apis ](https://docs.microsoft.com/en-us/rest/api/vsts/test/?view=vsts-rest-5.0) to get test runs associated with the current build or release.

Let me know if this was helpful.

Also may I know what information you want from the test run? There may be an easier way to get the information you need to take a decision whether or not to send the mail.

**Comment by fmanea** [comment]
Hello,
Basically I would need the runId from be able to construct my own link to add it to the email 
```2018-06-15T11:30:41.3061285Z Published Test Run : http://tfsLink:8080/tfs/DefaultCollection_2010/GamingX/_TestManagement/Runs#runId=642009&_a=runCharts```
But this runId is nowhere to be found.

I don't need to take a decision upon it, I only need the link.
On that link we can find a sumarry of the finished tests along with an attachement with the .trx file of the tests.

**Comment by ShreyasRmsft** [comment]
@fmanea using the apis mentioned above is the only way to get this done. The link has samples to get the build id and release id. Once you have these use the test management apis to get the test run associated with the build or release. Then you can construct the link. Please follow the docs on the apis, closing the issue here.

**Comment by joshuasumanth** [comment]
this is not useful . The API just gives the list of all the variables 

We don't find one variable which can be used to get the test Run..

**Comment by ShreyasRmsft** [comment]
@joshuasumanth you will get all test runs associated with the specified build or release.
Please paste a sample of the call you are making.

**Comment by joshuasumanth** [comment]
GET https://{accountName}.vsrm.visualstudio.com/{project}/_apis/release/releases/{releaseId}?approvalFilters={approvalFilters}&propertyFilters={propertyFilters}&$expand={$expand}&$topGateRecords={$topGateRecords}&api-version=5.0-preview.8

using this to get the Release inormation to get the Test run ID created

**Comment by ShreyasRmsft** [comment]
you should be using a test management api to get the test run. The above will get you unnecessary release details

in a powershell script try to obtain the release id https://docs.microsoft.com/en-us/vsts/pipelines/build/variables?view=vsts&tabs=batch#buildbuildid

and then use the test management api to get associated test run

**Comment by joshuasumanth** [comment]
can you please share the URL for the Test Management API

**Comment by nigurr** [comment]
@joshuasumanth Please refer documentation https://docs.microsoft.com/en-us/rest/api/vsts/?view=vsts-rest-5.0

Users can write simple powershell/bash scripts to access APIs and the documentation outlines all the information required.

**Comment by nigurr** [comment]
@joshuasumanth https://{youraccount}.visualstudio.com/DevDiv/_apis/test/ResultSummaryByRelease?releaseId=${releaseId}&releaseEnvId={EnvId}
I do see that this API is not listed, sorry for the inconvenience. 
I will be taking it up internally with product team about the API documentation.

**Comment by joshuasumanth** [comment]
@nigurr  I am not getting the following 

{"aggregatedResultsAnalysis":{"previousContext":{"contextType":0,"build":null,"release":null},"totalTests":42,"duration":"00:00:01.2740000","resultsByOutcome":{"Passed":{"outcome":"passed","count":42,"duration":"00:00:01.2730000"}},"runSummaryByState":{"Completed":{"state":"completed","runsCount":1,"resultsByOutcome":{"Passed":{"outcome":"passed","count":42,"duration":"00:00:01.2730000"}}}},"runSummaryByOutcome":{"Passed":{"runsCount":1}}},"testResultsContext":{"contextType":"release","build":null,"release":{"id":3767,"name":null,"environmentId":11584,"environmentName":null,"definitionId":0,"environmentDefinitionId":0,"environmentDefinitionName":null}},"teamProject":{"id":{"My Project ID "},"name":{my Project name},"state":"unchanged","visibility":"unchanged"}}

but I do not have the Test Run ID

**Comment by Abdul-waseem123** [comment]
This worked for me:
https://{youraccount}.visualstudio.com/{project}/_apis/test/resultdetailsbyrelease?releaseId={releaseId}&releaseEnvId={envId}&publishContext=CD&groupBy=TestRun

**Comment by chandrakammara** [comment]
Thanks Abdul-waseem123, it worked for me too :)
https://{youraccount}.visualstudio.com/{project}/_apis/test/resultdetailsbyrelease?releaseId={releaseId}&releaseEnvId={envId}&publishContext=CD&groupBy=TestRun

Below is the powershell script .. you can use in a Azure pipeline task to get the Test Runid :  Just fill the emailid, PAT token, account name and projectname in the url. 

powershell script:
$username = "optional email id"
$token = "<enter you PAT token here>"
$instance = "optional email id .visualstudio.com"

#create auth header to use for REST calls
$accessToken = ("{0}:{1}" -f $username,$token)
$accessToken = [System.Text.Encoding]::UTF8.GetBytes($accessToken)
$accessToken = [System.Convert]::ToBase64String($accessToken)
$headers = @{Authorization=("Basic {0}" -f $accessToken)}

$testRunIdRecord = Invoke-RestMethod -Uri "https://{youraccount}.visualstudio.com/{project}/_apis/test/resultdetailsbyrelease?releaseId=$(Release.ReleaseId)&releaseEnvId=$(Release.EnvironmentId)&publishContext=CD&groupBy=TestRun" -Headers $headers -Method Get
$results = $($testRunIdRecord | ConvertTo-Json -Depth 100)

$jsonobj = ConvertFrom-Json -inputObject $results
$run = $jsonobj.resultsForGroup[0].groupByValue.id

#below variable run will give the run id
echo $run

#and you can set as a pipeline variable
Write-Host "##vso[task.setvariable variable=runids]$run"
##powershell script end

#use your Test run id pipeline variable in another task as $runids

that is it .. enjoy :)
