### ISSUE TITLE
Updating VSTest task to v2 causes elasticsearch tests to fail

### ISSUE THREAD

**Issue by roizentner** [Microsoft/vsts-tasks#7457]
## Environment
- Server - VSTS
- Agent - Private
- Agent OS: Windows
- Agent version: 2.134.2

## Issue Description
Hi,
I've been going through my old build definitions, updating the VSTest task from v1 to v2.
Everything was going great until I updated a task that runs Elasticsearch tests.
The failing tests include the use of https://github.com/poulfoged/Elasticsearch-Inside
All the tests which involve Elasticsearch Aggregations fail, whereas other Elasticsearch tests succeed.

I can't seem to understand why updating the VSTest task version causes this behavior.

Here's the code snippet which causes the failure:
```c#
IExpressionBuilder expressionBuilder = mExpressionFactory.CreateBuilder(scope);
           ISearchResponse<ElasticItem> response = await ReadClient
                .SearchAsync<ElasticItem>(s => s
                    .Source(false)
                    .Size(0)
                    .Query(q => q
                        .Bool(b => b
                            .Filter(bf => bf
                                .DateRange(dr => dr
                                    .Field(f => f.StartTime)
                                    .GreaterThanOrEquals(range.Item1)
                                    .LessThanOrEquals(range.Item2)))))
                    .Aggregations(a => a
                        .DateHistogram(INTERVALS, t => t
                            .Field(i => i.StartTime)
                            .Interval((DateInterval)interval)
                            .ExtendedBounds(range.Item1, range.Item2)
                            .Aggregations(ia => ia
                                .Sum(SUM1, ms => ms.Field(expressionBuilder.Sum1Expression))
                                .Sum(SUM2, ms => ms.Field(expressionBuilder.Sum2Expression)))))
                ).ConfigureAwait(false);
```

### Error logs
Test method ElasticSearch.Tests.GetRange_RootYearInterval_ValidResult threw exception: 
Elasticsearch.Net.UnexpectedElasticsearchClientException: Collection is read-only. ---> System.NotSupportedException: Collection is read-only.

**Comment by ShreyasRmsft** [comment]
@roizentner it might not be the task per se. The v2 version uses the new Microsoft.TestPlatform (TPv2). This could be causing the issue.

Can you send me build logs (with system.debug=true) from the older builds where this test was passing and also from the newer builds where this is failing.

**Comment by roizentner** [comment]
Hi @ShreyasRmsft, and thanks for responding so quickly.
Your request for build logs (with system.debug=true) made me curious so I started checking them myself.

First of all, I was a bit inaccurate in my initial post regarding the update of the VStest task to v2. I actually replaced my explicit v1 task with a task group that had v2. **That's when the tests started failing**.

After endless runs with little tweaks, I've narrowed it down to the root cause:
The v2 task I am using has a slightly different value in the "_Test assemblies_" parameter.
The difference is I added the following exclusion pattern: `!**\Microsoft*.dll`
This caused the task to exclude **Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll** from the list of assemblies.
Since my tests are not in this assembly, I thought it would save time to exclude all assemblies but the one where my test is.
Then I tried a different approach:
Instead of having the following patterns:
```
**\*test*.dll
!**\Microsoft*.dll
```
I tried using a more specific include pattern: `**\*ElasticSearch*test*.dll` and it worked (the tests passed).

I'd love getting an explanation for this behavior.

**Comment by ShreyasRmsft** [comment]
@roizentner in the V2 task we changed the assembly filtering technique to use Minimatch patterns.
This was a breaking change (along with many more changes) hence the major version bump up to 2.

I'm still not very sure why it caused the tests to fail. It might be due to loading of other dlls which messed with either globals or loaded different versions of some assemblies etc. Without either having a sample repro or the source code its difficult to say why the tests failed. Ideally the source filter shouldn't be causing issues like this. Let me know if you need anything else and if i can close the issue.

**Comment by roizentner** [comment]
@ShreyasRmsft, let me share the different logs.

Keep in mind: The only tests the match the TestCaseFilter crtieria are in `"D:\bld\s\Fabrikam.Solution\ElasticSearch.Tests\bin\x64\Release\ElasticSearch.Tests.dll"`
The logs might shed more light on the issue:

**Scenario 1 - Tests failed**
Test assemblies : `**\*test*.dll,!**\obj\**,!**\Microsoft*.dll`
Command:
`vstest.console.exe`
`"D:\bld\s\Fabrikam.Solution\Api.Tests\bin\x64\Release\WebAPITests.dll"
"D:\bld\s\Fabrikam.Solution\ElasticSearch.Tests\bin\x64\Release\ElasticSearch.Tests.dll"
"D:\bld\s\Fabrikam.Solution\Model.Tests\bin\x64\Release\Model.Tests.dll"
"D:\bld\s\Fabrikam.Solution\Fabrikam.Analysis.ElasticSearch.Tests\bin\x64\Release\Fabrikam.Analysis.ElasticSearch.Tests.dll"
"D:\bld\s\Fabrikam.Solution\Fabrikam.Analysis.Tests\bin\x64\Release\Fabrikam.Analysis.Tests.dll"
/TestCaseFilter:"TestCategory=Elastic"
/InIsolation
/logger:"trx"
/Platform:X64`

**Scenario 2 - Tests passed**
Test assemblies : `**\*test*.dll,!**\obj\**`
Command:
`vstest.console.exe`
`"D:\bld\s\Fabrikam.Solution\Api.Tests\bin\x64\Release\WebAPITests.dll"
"D:\bld\s\Fabrikam.Solution\Api.Tests\bin\x64\Release\Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll"
"D:\bld\s\Fabrikam.Solution\ElasticSearch.Tests\bin\x64\Release\ElasticSearch.Tests.dll"
"D:\bld\s\Fabrikam.Solution\ElasticSearch.Tests\bin\x64\Release\Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll"
"D:\bld\s\Fabrikam.Solution\Model.Tests\bin\x64\Release\Model.Tests.dll"
"D:\bld\s\Fabrikam.Solution\Fabrikam.Analysis.ElasticSearch.Tests\bin\x64\Release\Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll"
"D:\bld\s\Fabrikam.Solution\Fabrikam.Analysis.ElasticSearch.Tests\bin\x64\Release\Fabrikam.Analysis.ElasticSearch.Tests.dll"
"D:\bld\s\Fabrikam.Solution\Fabrikam.Analysis.Tests\bin\x64\Release\Microsoft.VisualStudio.QualityTools.UnitTestFramework.dll"
"D:\bld\s\Fabrikam.Solution\Fabrikam.Analysis.Tests\bin\x64\Release\Fabrikam.Analysis.Tests.dll"
/TestCaseFilter:"TestCategory=Elastic"
/InIsolation
/logger:"trx"
/Platform:X64`

**Scenario 3 - Tests passed**
Test assemblies : `**\*ElasticSearch*test*.dll,!**\obj\**`
Command:
`vstest.console.exe`
`"D:\bld\s\Fabrikam.Solution\ElasticSearch.Tests\bin\x64\Release\ElasticSearch.Tests.dll"
"D:\bld\s\Fabrikam.Solution\Fabrikam.Analysis.ElasticSearch.Tests\bin\x64\Release\Fabrikam.Analysis.ElasticSearch.Tests.dll"
/TestCaseFilter:"TestCategory=Elastic"
/InIsolation
/logger:"trx"
/Platform:X64`

**Comment by ShreyasRmsft** [comment]
@roizentner I have a few hunches now after seeing this.

Can you provide the complete build logs with system.debug=true. Please upload the entire zip file that gets attached to the build. Or send it to devops_tools@microsoft.com and reply here with the subject of the mail and i can try and validate my hunches.

**Comment by roizentner** [comment]
@ShreyasRmsft I've just sent an email with the subject: **Logs for vsts-tasks issue #7457**
Let me know if you received it, because I got the following reply:

Your message couldn't be delivered to multiple recipients.
The groups only accept messages from people in their organization or on their allowed senders list, and your email address isn't on the lists.
Sender not allowed
Couldn't deliver to the following groups:
vstlmtcm@microsoft.com, vs_atpm@microsoft.com

If you did get the email, I'm hoping to hear from you with good news 👍

**Comment by ShreyasRmsft** [comment]
@roizentner got it. Will take a look.

**Comment by ShreyasRmsft** [comment]
@roizentner all 3 log files you sent indicate that the tests passed. Can you check if you sent the correct logs?

Also Scenario 1 with Test assemblies : **\*test*.dll,!**\obj\**,!**\Microsoft*.dll actually passed according to the logs you sent.

**Comment by ShreyasRmsft** [comment]
@roizentner Seems to me like its a test issue only. Is the repro consistent? 

If it is indeed consistent with what inputs (list all inputs please) does it fail consistently and pass consistently?

If with the same inputs its passes and fails then it is definitely a test issue.

**Comment by ShreyasRmsft** [comment]
What I noticed was when these are the sources passed it fails
2018-06-19T10:07:16.0501276Z "D:\bld2-Big2\27\s\repo\Fabrikam.Solution\Product.Api.Tests\bin\x64\Release\Product.WebAPITests.dll"
2018-06-19T10:07:16.0501560Z "D:\bld2-Big2\27\s\repo\Fabrikam.Solution\Product.ElasticSearch.Tests\bin\x64\Release\Product.ElasticSearch.Tests.dll"
2018-06-19T10:07:16.0501859Z "D:\bld2-Big2\27\s\repo\Fabrikam.Solution\Product.Model.Tests\bin\x64\Release\Product.Model.Tests.dll"
2018-06-19T10:07:16.0502257Z "D:\bld2-Big2\27\s\repo\Fabrikam.Solution\Fabrikam.Analysis.ElasticSearch.Tests\bin\x64\Release\Fabrikam.Analysis.ElasticSearch.Tests.dll"
2018-06-19T10:07:16.0503168Z "D:\bld2-Big2\27\s\repo\Fabrikam.Solution\Fabrikam.Analysis.Tests\bin\x64\Release\Fabrikam.Analysis.Tests.dll"

When more sources are passed like this it passes:

2018-06-18T13:28:46.2547511Z "D:\agent\27\s\repo\Fabrikam.Solution\Api.Tests\bin\x64\Release\WebAPITests.dll"
2018-06-18T13:28:46.2547792Z "D:\agent\27\s\repo\Fabrikam.Solution\Api.Tests\bin\x64\Release\Fabrikam.Tests.dll"
2018-06-18T13:28:46.2548082Z "D:\agent\27\s\repo\Fabrikam.Solution\ElasticSearch.Tests\bin\x64\Release\ElasticSearch.Tests.dll"
2018-06-18T13:28:46.2548338Z "D:\agent\27\s\repo\Fabrikam.Solution\ElasticSearch.Tests\bin\x64\Release\Fabrikam.Tests.dll"
2018-06-18T13:28:46.2548606Z "D:\agent\27\s\repo\Fabrikam.Solution\Model.Tests\bin\x64\Release\Model.Tests.dll"
2018-06-18T13:28:46.2548853Z "D:\agent\27\s\repo\Fabrikam.Solution\Model.Tests\bin\x64\Release\Fabrikam.Tests.dll"
2018-06-18T13:28:46.2549103Z "D:\agent\27\s\repo\Fabrikam.Solution\Fabrikam.Analysis.ElasticSearch.Tests\bin\x64\Release\Fabrikam.Tests.dll"
2018-06-18T13:28:46.2549508Z "D:\agent\27\s\repo\Fabrikam.Solution\Fabrikam.Analysis.ElasticSearch.Tests\bin\x64\Release\Fabrikam.Analysis.ElasticSearch.Tests.dll"
2018-06-18T13:28:46.2549801Z "D:\agent\27\s\repo\Fabrikam.Solution\Fabrikam.Analysis.Tests\bin\x64\Release\Fabrikam.Tests.dll"
2018-06-18T13:28:46.2550170Z "D:\agent\27\s\repo\Fabrikam.Solution\Fabrikam.Analysis.Tests\bin\x64\Release\Fabrikam.Analysis.Tests.dll"

In which dll is your test present in? Are you sure its not present in any other dll listed above?

**Comment by roizentner** [comment]
The test is in "ElasticSearch.Tests.dll" only.
I'm beginning to believe the issue is caused by something on my side, following the little tweaks I tried when running the tests during our investigation.
It is definitely affected by the patterns I use in the test assemblies. I'll talk to the developers and try to get more info from them.
This issue can be closed...
