### ISSUE TITLE
PowerShell v2 task to have option to run PowerShell Core on Windows as well

### ISSUE THREAD

**Issue by bergmeister** [Microsoft/vsts-tasks#7461]
If the PowerShell v2 task runs on Linux/Mac it uses PowerShell Core automatically but on Windows, it uses Windows PowerShell.
There should be something like a checkbox available to `Run using PowerShell Core` that makes it use PowerShell Core on Windows and the value of this checkbox gets ignored on other systems.

**Comment by bryanmacfarlane** [comment]
What issue does it cause to have it run by PowerShell on windows?

**Comment by bergmeister** [comment]
Apart from the fact that PowerShell Core is twice as fast, it has also an improved engine and new capabilities such as e.g. cross platform remoting.
Calling pwsh.exe from Windows PowerShell  is not a pleasure due to various problems and therefore solutions to command line parsing. It is annoying having to escape stuff or having to encode the command.

**Comment by bryanmacfarlane** [comment]
I'll leave this open and have someone dig into it.

**Comment by SteveL-MSFT** [comment]
If a user is authoring a cross platform PowerShell script (doing builds, running tests) across Linux, Windows, and macOS.  Currently they have to special case Windows PowerShell because there have been breaking changes and new capabilities we've taken in PowerShell Core.  What @bergmeister is saying is to have PowerShell Core as an option on Windows which runs happily side-by-side with Windows PowerShell with no conflict so that a single script can work across all three platforms.

**Comment by SteveL-MSFT** [comment]
I should mention that adding PSCore6 to the Windows image can be as simple as using the .zip we publish and updating the system PATH env var so that `pwsh` is found.

**Comment by oughton** [comment]
Doesn't the change [here](https://github.com/Microsoft/vsts-tasks/pull/6175/files) mean that PowerShell Core is preferred if present on the Windows Agent in version 2 of the task?

**Comment by ericsciple** [comment]
No that is the version that runs on Linux/macOS.

If you are on Windows it will always go to PowerShell.exe, it will only look for pwsh on Mac and Linux.

We have discussed adding a bool “pwsh: true” to enable Windows users to require pwsh. Does that sound good?

**Comment by oughton** [comment]
Ah right. @ericsciple that would work great for us!

**Comment by bergmeister** [comment]
Yes, and possibly another field `pwsh-preview` for all platforms because that is the name of the preview binaries, correct me if I am wrong @stevel-msft

**Comment by bergmeister** [comment]
@ericsciple Any updates on this?

**Comment by felixfbecker** [comment]
Is there a workaround in the meantime? Is `pwsh` installed on the Windows agents, so that we can run `pwsh -c` manually? I have a C# cmdlet that only runs on PowerShell Core because a dependency requires .NET Core 2.1 and can't target .NET Standard 2.0 (nor .NET Framework).

**Comment by bergmeister** [comment]
@felixfbecker Yes, you can call `pwsh -command` or `pwsh -file` from any task that takes a command line option or just from Windows PowerShell.

**Comment by rusticMire** [comment]
`- task: PowerShell@2`
  `inputs:`
    `#targetType: 'inline'`
    `script: '# Write your powershell commands here.'`
    `pwsh: true`

Setting `pwsh` as `true` enables Powershell Core
