### ISSUE TITLE
Service Fabric Deployment Tasks should be using -Async option during Registration of applications

### ISSUE THREAD

**Issue by masnider** [Microsoft/vsts-tasks#7466]
This API call should be made using the -Async flag. This allows the timeout to be mainly about delivering the command to the platform, allowing the actual work of registering an application type to proceed asynchronously in the background.

https://github.com/Microsoft/vsts-tasks/blob/d2f14192c3a1270b3cad81127c4812738bdfbb5c/Tasks/ServiceFabricDeployV1/ServiceFabricSDK/Publish-NewServiceFabricApplication.ps1#L312-L322

Upgrade has the same issue. 

https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/ServiceFabricDeployV1/ServiceFabricSDK/Publish-UpgradedServiceFabricApplication.ps1#L290-L300

Perhaps the common code could also be factored out?

The code then has to check to be sure that the registration is successful before proceeding to create any instances of the application type. I'm sure there's a better way to do it than polling, perhaps as a background PS Job. The basics with polling would look like this

https://github.com/Azure-Samples/service-fabric-dotnet-data-aggregation/blob/master/HealthMetricsApplication/Scripts/HealthMetricsDeployment.ps1#L130-L143

**Comment by masnider** [comment]
@oanapl fyi

**Comment by bishal-pdMSFT** [comment]
Thanks @masnider for bringing this up. We are already are aware of this and have a tracking issue for this. https://github.com/Microsoft/vsts-tasks/issues/6833 and we plan to start working on that in this/next sprint.

**Comment by bishal-pdMSFT** [comment]
PR #7631

**Comment by bishal-pdMSFT** [comment]
This is done now.
