### ISSUE TITLE
Xcode PackageApplication Tool Removed from Xcode 7

### ISSUE THREAD

**Issue by H2OBorne** [Microsoft/vsts-tasks#747]
When using the Xcode Package iOS task, the packing script calls [code]xcrun -sdk $sdk PackageApplication[/code]

Unfortunately, this has been removed in Xcode 7, and the preferred way is to use `xcbuild` making use of the `-exportArchive` option.

See https://forums.developer.apple.com/thread/19832 and http://stackoverflow.com/questions/32763288/ios-builds-ipa-creation-no-longer-works-from-the-command-line/32845990#32845990 for more information.

Hopefully I can get to this next week, once the other build problems are sorted out. I assume it requires a relatively small change to the GenerateIpa script.

**Comment by bryanmacfarlane** [comment]
Good catch.  Thanks for reporting this.  Looking forward to a PR :)

**Comment by Chuxel** [comment]
Technically it's not removed, it's just that the --sign and --embed flags no longer work without adding a reference to a .plist file that will get your app rejected from the store.  Further, the --embed flag does nothing without the --sign flag.  So, you can generate an ipa with PackageApplication but you can't resign or change the provisioning profile with the command any longer.  That said, this suggestion is a great one for future proofing if Xcode 7+ is detected.

**Comment by bryanmacfarlane** [comment]
It this addressed in the new revamped xcode task?

**Comment by madhurig** [comment]
The xcode task is still using PackageApplication, updating to --exportArchive will require additional user inputs. It is on my list to do but need to review the design along with other changes we need to make like xcpretty support.

**Comment by madhurig** [comment]
Addressed in PR: https://github.com/Microsoft/vsts-tasks/pull/2701

**Comment by madhurig** [comment]
Fix has been merged and will be deployed to Team Services starting Oct 16th and should roll out to all accounts in about a week.
