### ISSUE TITLE
Azure Web App Deploy: Invalid config when packaging and deploy multiple netcore webs

### ISSUE THREAD

**Issue by phatcher** [Microsoft/vsts-tasks#7471]
## Environment
- Server - VSTS 
- Agent - Hosted 2017

## Issue Description

Build a solution containing multiple webs which I need to deploy into Azure as a main web and virtual applications.

Problem I am hitting is invalid web.config in the virtual applications as they contain the asp.net core handler (see [IIS Configuration of sub-applications](https://docs.microsoft.com/en-gb/aspnet/core/host-and-deploy/iis/index?view=aspnetcore-2.1&tabs=aspnetcore2x#sub-application-configuration)

Looking for advice as to the best way to fix this...

1. Perform some web.config transform as part of the packaging (see also https://github.com/aspnet/websdk/issues/115)
2. Perform some transform as part of the publish

I'd prefer option 2 as to me whether it's a virtual application is a deployment rather than a build issue

It would be really nice if the Azure Web App Deploy task could take care of this since it knows it's deploying a virtual application.

I'd also suggest documenting this requirement somewhere more prominently since tracking this down has taken quite a while and the behaviour is quite different to standard .NET Framework deployments.

**Comment by vincentdass** [comment]
@phatcher , Can you try `XML transformation`  in App Service Deploy task to transform your web.config as required?
![image](https://user-images.githubusercontent.com/20121508/41462504-b5e4ba5e-70b0-11e8-9c9c-a3008cb142c8.png)
More info [here](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/transforms-variable-substitution?view=vsts#xmltransform).

**Comment by phatcher** [comment]
@vincentdass I tried a web.Release.config like this...

```
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
    <system.webServer>
        <handlers>
            <add name="aspNetCore" path="*" verb="" xdt:Transform="Remove" xdt:Locator="XPath(system.webServer/handlers[@name='aspNetCore'])" />
        </handlers>
    </system.webServer>
</configuration>
```
but it didn't work

**Comment by vincentdass** [comment]
@phatcher , Can you try the following config & Transform file:
Config File: **Web.config**

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <aspNetCore processPath="dotnet" 
      arguments="main.dll" 
      stdoutLogEnabled="false" 
      stdoutLogFile=".\logs\stdout" />
  </system.webServer>
</configuration>
```

**Transform file: Web.Release.config**

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <remove name="aspNetCore" />
    </handlers>
  </system.webServer>
</configuration>
```

**Comment by vincentdass** [comment]
@phatcher , transform files are not removed after transformation, so they are deployed along with config file. 

Can you try the following transform file instead:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration xmlns:xdt="http://schemas.microsoft.com/XML-Document-Transform">
    <system.webServer>
        <handlers>
            <add name="aspNetCore" xdt:Transform="Remove" />
        </handlers>
    </system.webServer>
</configuration>
```

verified with config file:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <system.webServer>
        <handlers>
            <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
        </handlers>
        <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" />
    </system.webServer>
</configuration>
```

You can verify it online [here](https://webconfigtransformationtester.apphb.com/).

**Comment by phatcher** [comment]
@vincentdass Thanks that one worked!

So it's basically using the standard web.config transform syntax?

And just to confirm, for a specified environment transform to work a web.XXX.config file must exist matching the VSTS environment e.g. if you have an Staging environment you must have a web.Staging.config if you want to have specific work to happen?

**Comment by vincentdass** [comment]
@phatcher , yes, you are correct, additionally, `Web.Release.config` is applied prior to` Web.< Env Name >.config`
