### ISSUE TITLE
Can't edit any field of a new build definition

### ISSUE THREAD

**Issue by EzraBrooks** [Microsoft/vsts-tasks#7487]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
    - If using TFS on-premises, provide the version: 
    
    - If using VSTS, provide the account name, team project name, build definition name/build number: 
The account name is fastcase-inc.

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 

## Issue Description

I'm trying to create a build definition in VSTS and I can't edit any fields or save it. I'm the account owner, so I'm assuming it's not a permissions error?

### Error logs

It doesn't log any errors to console in the browser. Tried it in Safari, Firefox, and Chrome. I'm on macOS 10.13.

**Comment by bryanmacfarlane** [comment]
There was a bug that only got to one scale unit and it's rolling out.  I think the workaround is ctrl-s

If you don't see it fixed soon, then developer community is a better option.  This repo and issues is for the in the box tasks (/Tasks)
