### ISSUE TITLE
Dotnet Core Task V2: Command Test: If no projects found it doesn't state the pattern that was searched for

### ISSUE THREAD

**Issue by chvollm** [Microsoft/vsts-tasks#7489]
## Environment
VSTS

- Agent - Hosted 

## Issue Description
Dotnet Core Task in version 2. Command test.
If no projects are found, it only states that nothing is found.

> ##[warning]Project file(s) matching the specified pattern were not found.

I think it would help if the pattern would get mentioned so you can see if a typo was made or you can see other issues without opening the build definition, e.g.

##[warning]Project file(s) matching the specified pattern '*UnitTets' were not found.

**Comment by bishal-pdMSFT** [comment]
This is same pattern followed by most of the VSTS tasks. It is not difficult to switch to "edit" view and look the task inputs.
@sachinma @ds-ms What's your opinion?

**Comment by vineetmimrot** [comment]
Does not seem important enough to me.

**Comment by maxoizs** [comment]
it could be helpful it shows how it run the command, or how it did consume the directory path.
