### ISSUE TITLE
Trigger build on tag creation.

### ISSUE THREAD

**Issue by viniciusjarina** [Microsoft/vsts-tasks#7490]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
    VSTS - Codefoco - Team/Project BlueMaze

- Agent - Hosted or Private: 
    
    - Hosted: BlueMaze-MazeCreator.iOS/Desktop

## Issue Description

VSTS allow the integration with Github WebHook, but it only handles the `push` payload. But even the `Branch or tag creation` is set VSTS doesn´t trigger any build.

![screen shot 2018-06-15 at 12 54 16](https://user-images.githubusercontent.com/926868/41477741-9cde224e-709b-11e8-9e6f-a1d53b1dbc39.png)

I´ve tried to add `refs/heads/`  on branch filter, but didn´t help.

I used to trigger a build from tag creation (using Jenkins) and automatically build a NuGet package and push it to nuget.org, but this isn´t possible with VSTS.

Since VSTS already handle the Github Webhook, should´t be a problem to handle different payloads.

Thank you.

**Comment by bryanmacfarlane** [comment]
You may want to go to developer community.  This repo is for issues with the in the box tasks (/Tasks).   Triggering is a service issue.
