### ISSUE TITLE
failed to install .NET Core runtime 2.0.7

### ISSUE THREAD

**Issue by morshilo** [Microsoft/vsts-tasks#7493]
### Error logs

Starting: Use .NET Core runtime 2.0.7
******************************************************************************
==============================================================================
Task         : .NET Core Tool Installer
Description  : Acquires a specific version of .NET Core from internet or the tools cache and adds it to the PATH. Use this task to change the version of .NET Core used in subsequent tasks.
Version      : 0.1.8
Author       : Microsoft Corporation
Help         : [More Information](https://go.microsoft.com/fwlink/?linkid=853651)
==============================================================================
Tool to install: .NET Core runtime version 2.0.7.
Checking if a cached copy exists for this version...
Cache does not contains this particular .NET Core. Will be downloaded and installed.
Getting URLs to download .NET Core runtime version: 2.0.7.
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "& 'D:\a\_tasks\DotNetCoreInstaller_b0ce7256-7898-45d3-9cb5-176b752bfea6\0.1.8\externals\install-dotnet.ps1' -Version 2.0.7 -DryRun -SharedRuntime"
dotnet-install: Payload URLs:
dotnet-install: Primary - https://dotnetcli.azureedge.net/dotnet/Runtime/2.0.7/dotnet-runtime-2.0.7-win-x64.zip
dotnet-install: Legacy - https://dotnetcli.azureedge.net/dotnet/Runtime/2.0.7/dotnet-win-x64.2.0.7.zip
dotnet-install: Repeatable invocation: .\install-dotnet.ps1 -Version 2.0.7 -Channel LTS -Architecture x64 -InstallDir <auto>
Downloading .NET Core package from primary URL: https://dotnetcli.azureedge.net/dotnet/Runtime/2.0.7/dotnet-runtime-2.0.7-win-x64.zip
Downloading: https://dotnetcli.azureedge.net/dotnet/Runtime/2.0.7/dotnet-runtime-2.0.7-win-x64.zip
Failed to download .NET Core package using primary URL. Error: Error: Unexpected HTTP response: 404.
Downloading .NET Core package from legacy URL: https://dotnetcli.azureedge.net/dotnet/Runtime/2.0.7/dotnet-win-x64.2.0.7.zip
Downloading: https://dotnetcli.azureedge.net/dotnet/Runtime/2.0.7/dotnet-win-x64.2.0.7.zip
******************************************************************************
Starting: Post Job Cleanup
******************************************************************************
Cleaning any cached credential from repository: Over.AI Core (Git)
git remote set-url origin https://overai.visualstudio.com/Over.AI%20Core/_git/Over.AI%20Core
git remote set-url --push origin https://overai.visualstudio.com/Over.AI%20Core/_git/Over.AI%20Core
******************************************************************************
Finishing: Post Job Cleanup
******************************************************************************
Failed to download .NET Core package using legacy URL as well. Error: Error: Unexpected HTTP response: 404.
Failed to download .NET Core package. Please ensure that .NET Core runtime of version 2.0.7 exists. Check out: https://github.com/dotnet/core/blob/master/release-notes/releases.csv

**Comment by MinhThienDX** [comment]
I have the same issue, mine is **Failed to download .NET Core package. Please ensure that .NET Core sdk of version 2.1.300 exists. Check out: https://github.com/dotnet/core/blob/master/release-notes/releases.csv**
It was working fine yesterday.

**Comment by bishal-pdMSFT** [comment]
@morshilo @MinhThienDX The download URLs for dotnet core packages mentioned in [releases.csv](https://github.com/dotnet/core/blob/master/release-notes/releases.csv) are not working. We have created a [issue ](https://github.com/dotnet/core/issues/1701) on dotnet team for this.

**Comment by MinhThienDX** [comment]
@morshilo The underlying issue has been fixed here https://github.com/dotnet/dotnet-docker/issues/599#issuecomment-398074526
Is everything okay now?

**Comment by morshilo** [comment]
@MinhThienDX @bishal-pdMSFT thank you! i just managed to run the command successfully.
the issue has been fixed.
