### ISSUE TITLE
Unable to run the automated tests in TFS 2018

### ISSUE THREAD

**Issue by Selvaraj1989** [Microsoft/vsts-tasks#7498]
## Environment
- Server - TFS 2018.2  
- Agent - Private: OS : Window Server 2016 and Agent Version : 2.131.0

## Issue Description

I am configuring my test plan based on steps given here https://docs.microsoft.com/en-us/vsts/test/run-automated-tests-from-test-hub?view=vsts. When i tried to run, it thrown some exception which i attached in the error logs.

Kindly help me in resolving this issue.

Thanks
Selvaraj C

### Error logs
[VsTestLogs.txt](https://github.com/Microsoft/vsts-tasks/files/2110795/VsTestLogs.txt)

[Insert error from the logs here]

**Comment by kaadhina** [comment]
Please set variable system.debug = true in the release definition and start another run, and please share the full logs. You may choose to send them over by email to [devops_tools@microsoft.com] as well.

**Comment by Selvaraj1989** [comment]
I have already enabled the system.debug=true and attached the logs here.
[VsTestLogs.txt](https://github.com/Microsoft/vsts-tasks/files/2111433/VsTestLogs.txt)

**Comment by ShreyasRmsft** [comment]
@Selvaraj1989 please attach the entire zip file containing all the logs

**Comment by Selvaraj1989** [comment]
Hi,

Attached the entire logs for VsTest task.

[3_Test run for Test plans.log](https://github.com/Microsoft/vsts-tasks/files/2115015/3_Test.run.for.Test.plans.log)

**Comment by kaadhina** [comment]
We need some more info to narrow down further. Here are a few more things that will help. Can you please get these

1. Enable fiddler traces on your build agent machine and send us the logs for the create test run call. Here is a sample of the call you should capture:
![image](https://user-images.githubusercontent.com/11773114/41596564-589dab04-73e8-11e8-9c99-bd087ebb87af.png)

2. Get us the response by running the API  https://docs.microsoft.com/en-us/rest/api/vsts/clt/test%20runs/get%20test%20runs?view=vsts-rest-4.1

3. I see that you are on TFS onprem, can you also collect event viewer logs from the server machine?

**Comment by Selvaraj1989** [comment]
Hi, 

currently, my project's IT team is looking into this issue. I will update here if the issue get resolved.

Thank you 
Selvaraj C

**Comment by kaadhina** [comment]
@Selvaraj1989 Are you unblocked on this?

**Comment by kaadhina** [comment]
I'm closing this for now. Feel free to reopen / open new issues if any.
