### ISSUE TITLE
Release based on Azure Container Registry image triggers twice, once for latest and once for specific version

### ISSUE THREAD

**Issue by comdw** [Microsoft/vsts-tasks#7501]
In VSTS I'm building a release pipeline for a project that pushes docker images to ACR during CI builds.  The push is set to tag both the specific version and 'latest' as is standard practice.  My release artifact is set to automatically trigger but each time there is a CI build, two releases are triggered, one for the specific version and one for 'latest'.

I can understand why this is happening, but how do I setup my release pipeline to ignore the 'latest' tag? I want to use the versioned image to do my deployment.  Am I missing something or this scenario isn't supported yet (I see a message about artifact filters not being supported for ACR in the pre-deployment conditions).

**Comment by nphmuller** [comment]
I've worked around this before by setting my VSTS build as my release artifact source instead of ACR.
My docker image tag was generated by the buildid (my.azurecr.io/myapp:{buildid}), so I could use the build id during my release to deploy the proper container image.

Hope it helps. :)

**Comment by bansalaseem** [comment]
@comdw , @vithati was able to reproduce the issue. The right fix for this is to provide filter support in the release definition similar to the one which we have for build artifacts. @azooinmyluggage Can you please add it to the backlog and let us know when you want to schedule it?

ACR artifact => ![image](https://user-images.githubusercontent.com/22289943/42861956-107b03f4-8a7b-11e8-9c85-c622300a17bf.png)

Build artifact => ![image](https://user-images.githubusercontent.com/22289943/42861997-317ff168-8a7b-11e8-824e-a924965ad284.png)

**Comment by ajinkya599** [comment]
We have added support for regular expression based tag filter in ACR artifact auto-trigger using which you can specify for what tag patterns should the release be triggered. This will be rolled out in our next deployment.

**Comment by cicorias** [comment]
When is next deployment date? Guess is fine

**Comment by ajinkya599** [comment]
@cicorias It will take around 3-4 weeks to make this available.

**Comment by cwiederspan** [comment]
Any update on when this might roll out?

**Comment by bansalaseem** [comment]
We have rolled the feature out to our stage 0 customers and can enable it on your account so that you can try it out and give feedback. @cwiederspan and @cicorias, can you please share your azure devops account names?

**Comment by cicorias** [comment]
Dwrdev

**Comment by ajinkya599** [comment]
@cicorias - We have enabled the feature on your account. Please try it out and share your feedback :)

**Comment by theharleyquin** [comment]
If there is no timeline for a GA rollout - what is the process for opt-in for this? I'm also facing a business need where I would like to filter on the ACR docker tag.
