### ISSUE TITLE
Kubernetes task does not use specified version

### ISSUE THREAD

**Issue by fredgate** [Microsoft/vsts-tasks#7515]
## Environment
- Server - VSTS

- Agent
  - Private queue
  - Agent version 2.134.2
  - Image docker provided by microsoft
 
## Issue Description

I have a release with a kubernetes task (version  0.1.21) configured to use version 1.7.0 of kubectl.
But when a release is executed, the task use a globally installed kubectl which is version 1.10.3.

I looked at the source code of the task and the problem is that when a global version of kubectl is present, the required version is not checked.
The problem is in file https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/KubernetesV0/src/clusterconnection.ts
In the constructor the global kubectl is searched : 
```
constructor() {
        this.kubectlPath = tl.which("kubectl", false);
        this.userDir = utils.getNewUserDirPath();
}

```
And in the initialize method, the requested version is checked only if global version does not exist :
```
private async initialize(): Promise<void> {
        if(!this.kubectlPath || !fs.existsSync(this.kubectlPath))
        {
            return this.getKubectl().then((kubectlpath)=> {
                this.kubectlPath = kubectlpath;
            });
        }
}
```

If I removed the globally installed kubectl program on the agent, then the task works correctly by downloading and installing a local kubectl.

**Comment by bansalaseem** [comment]
@Anumita, Can you please fix this?
