### ISSUE TITLE
VSTS Visual Studio Test 2.0 task deletes trx files after execution of tests

### ISSUE THREAD

**Issue by Hnarisetty** [Microsoft/vsts-tasks#7517]
Hello,
VSTS Visual Studio Test v2.0 task deletes trx files after execution of tests. But I still need them for processing. I saw somebody recommended to  "downloading the trx files from run attachments  " ..Is there a way to download those files on to agent machine itself using powershell scripts?

**Comment by cltshivash** [comment]
The trx generated by the test task would be available as a run attachment. If you can explain your need in detail it can help us provide a better response
