### ISSUE TITLE
TIA task not picking up the relevant tests

### ISSUE THREAD

**Issue by strosu** [Microsoft/vsts-tasks#7539]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
 - using vsts

- Agent - Hosted or Private: 
        - If using private agent, provide the OS of the machine running the agent and the agent version: Windows Server 2016

## Issue Description

@acesiddhu managed to reproduce the problem. In reference to https://github.com/Microsoft/vsts-tasks/issues/7387#issuecomment-398676203, we've created a new definition in order to exclude any noise from PRs etc. 

My first build with the new definition included the TIA changes and had all the tests ran on it. I've then changed one of our controllers, that should have broken roughly half the tests. The file was picked up as changed when comparing to the baseline, but no tests were run whatsoever. This reproduced on the 2nd commit, making more breaking changes with the same behavior. It picked up the 2 different files, but again decided to not run any tests (although plenty of them should have been impacted). 

I've also tried looking for the reference to the .zip file you mentioned in your comment, but couldn't find any in the logs. I'll email the logs to devops_tools@microsoft.com like it was mentioned in the previous issue. Just as a sanity check, can you please confirm the .runsettings is correct? Our tests are simply sending http requests to a website deployed locally in IIS.

```
<?xml version="1.0" encoding="utf-8"?>
<!-- File name extension must be .runsettings -->
<RunSettings>
  <DataCollectionRunSettings>
    <DataCollectors>
      <!-- This is the TestImpact data collector.-->
      <DataCollector uri="datacollector://microsoft/TestImpact/1.0" assemblyQualifiedName="Microsoft.VisualStudio.TraceCollector.TestImpactDataCollector, Microsoft.VisualStudio.TraceCollector, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" friendlyName="Test Impact">
        <Configuration>
          <!-- enable IIS data collection-->
          <InstrumentIIS>True</InstrumentIIS>
          <!-- file level data collection -->
          <ImpactLevel>file</ImpactLevel>
          <!-- any job agent related executable or any other service that the test is using needs to be profiled. -->
          <!--ServicesToInstrument>
            <Name>TeamFoundationSshService</Name>
          </ServicesToInstrument-->
        </Configuration>
      </DataCollector>
    </DataCollectors>
  </DataCollectionRunSettings>
</RunSettings>
```

Thanks a lot for the help!

### Error logs

[Insert error from the logs here]

**Comment by ShreyasRmsft** [comment]
@strosu can you set system.debug = true and see if you get the TestImpact.zip file and send it over too.

**Comment by acesiddhu** [comment]
@strosu closing this issue. Please create a new issue if you have a repro and logs.
