### ISSUE TITLE
Helm and K8s Tasks: Error loading k8s config, even though endpoint is Verified

### ISSUE THREAD

**Issue by colindembovsky** [Microsoft/vsts-tasks#7546]
## Environment
- Server - VSTS
- Agent - Private
    - Running in k8s cluster from `microsoft/vsts-agent:latest` image

## Issue Description

We have created a K8s endpoint in Services (pointing to an ACS cluster, not an AKS cluster) and when we click Verify, the endpoint is verified. However, when running k8s or helm tasks, we receive this error:

```
Error: could not get Kubernetes config for context "": Error loading config file "/vsts/agent/_work/_temp/helmTask/1529444038094/config": v1.Config: Contexts: []v1.NamedContext: Clusters: []v1.NamedCluster: v1.NamedCluster: Name: Cluster: v1.Cluster: Server: CertificateAuthorityData: decode base64: illegal base64 data at input byte 47, error found in #10 byte of ...|tLS0tCg==","server":|..., bigger context ...|Uk55a1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0 tLS0tCg=="
```

It appears that the tasks are unable to load the temp config for some reason.

We do have Azure AD authentication enabled in the K8s cluster - personal kubeconfigs include tokens.

**Comment by vithati** [comment]
If you are still facing issue. Can you add system.debug with true varaible in release and rerun the task. Share the debug logs.

**Comment by vithati** [comment]
@colindembovsky,  are you still facing issue? if yes, can you please share the release logs?

**Comment by vithati** [comment]
@colindembovsky, I am closing the issue. Please reopen, if you are still facing the issue.
