### ISSUE TITLE
Test result files with commas in their filenames cause PublishTestResultsV2 to fail

### ISSUE THREAD

**Issue by ryanmagani** [Microsoft/vsts-tasks#7551]
## Environment:
- Server (VSTS)
- Agent: either hosted or private, machine running Windows 10

## Issue Description

- Task name: Publish Test Results aka PublishTestResultsV2
- Task settings: default settings

Repro steps:
1. Make an empty git repository
2. Add a file named "TEST-file,name.xml" to the repository. (The file can be left empty)
3. Make a VSTS Build definition
4. Add "Publish Test Results" to the build definition. Don't change any of the default settings
5. Queue the build

Expected:
The build task finds the file

Actual:
The "Publish Test Results" step gives the following warning:
##[warning]Failed to publish test results: Could not find file '[...]\TEST-file'.

Workaround:
Replaced commas with a different character (specifically tildas ~)

Task settings:
![image](https://user-images.githubusercontent.com/8617169/41797163-dfbde9aa-761d-11e8-8f66-04f3f5642f1b.png)

File used for testing:
![image](https://user-images.githubusercontent.com/8617169/41797188-faf54d4e-761d-11e8-8f0d-4124686e1fdf.png)

**Comment by stephenmichaelf** [comment]
@pagangil Can you take a look at this?

**Comment by pondelknimojdan** [comment]
Hi. 
There is also problem with commas in "Search folder". 
Example:
My serch folder is : "C:\Agent01\_work\r1\a\iC build test projects**,** backup source test DB\iCTestAssemblies\CodedUITestProject". Publish Test Results (V2) task fails while serching for test results in serch folder : "C:\Agent01\_work\r1\a\iC build test projects".
![capture](https://user-images.githubusercontent.com/41009636/42455700-4240a4aa-8393-11e8-8c13-21b88fe8059e.PNG)

**Comment by saurabhsuniljain** [comment]
We are working on the fix for this. For now, to unblock yourself, can you remove the comma from the filename?

**Comment by ryanmagani** [comment]
@saurabhsuniljain I have a workaround already (noted in the original post): I've replaced my commas with tildas

**Comment by dpksinghal** [comment]
Thanks @ryanmagani We are closing this thread.

**Comment by kushaga** [comment]
Hi , @ryanmagani , is the issue still occurring, if yes  , can you please share the trx file and the task log by turning on debug mode.

**Comment by ryanmagani** [comment]
Hi @kushaga, I've changed jobs and no longer have access to VSTS. I'll forward this to someone on my previous team to confirm.
