### ISSUE TITLE
Windows Machine File Copy Task with an UNC Share for source cannot be used with a local user

### ISSUE THREAD

**Issue by FrenchTastic** [Microsoft/vsts-tasks#7558]
## Environment
 TFS On-Premises (Version 16.122.27102.1)
 Hosted Agents :  Agent.Version | 2.105.6

## Issue Description

Hi, 

I'm trying to use the Windows Machine File Copy Task on TFS On-Premise (Version 16.122.27102.1).
I encountered an issue with this task when providing an UNC Path for the Source Directory.

Like decribed on this link (https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/windows-machine-file-copy?view=vsts) I though that was ok to add an UNC for the directory source.

For example :

Source : \\mypath
Machines :  Destination-machine
Admin Login : destination-admin
Password : password
Destination Folder:  D:\Sample

The only way to access for my agent to this share, is to add the NETWORK SERVICE account (of my Agents) to this share... I have multiple agents that can access to this, so I will need to add the network service of each agent, and the NETWORK SERVICE account can be easily "hijack".
The files that i need to copy are the appsettings with my connection strings.

Is this the only way to make this task working with network share ? 

This is not what I want, I want to be able to specify that "destination-admin" can access to this share.
Is this possible ? 

I tried a workaround, that is not great at all and error prone : Mounting and unmounting after the task, the network share via a "net use" command for this specific user.

Thanks !!

**Comment by niadak** [comment]
@FrenchTastic , One possible solution is configure the agents as some other account which has the access to the share. You can go to task manager and update the user account of the service start with vstsagent.

**Comment by FrenchTastic** [comment]
Thanks for your answer.

This can be a solution,but with have a different user for production files and for our develop/integration environment, and the same agent can be used for develop or production.
So I will forced to set soecific vsts agent for specific environments (I did not check if it's possible, and I do not know if it's a great idea).

But I'll look into your solution and thank you again for your help.

**Comment by niadak** [comment]
@FrenchTastic , It is possible to set specific vsts agent for specific environments. We can add a custom capability in the agents and a custom demand in the agent phase to filter out the specific agent.

![image](https://user-images.githubusercontent.com/11937515/42080397-39e84146-7ba0-11e8-8b25-e86a19f89bcc.png)


![image](https://user-images.githubusercontent.com/11937515/42080237-a6341f06-7b9f-11e8-8c2b-9e8e1ae68cd4.png)

Alternatively  you can use different agent queues for different environments.

**Comment by SumiranAgg** [comment]
Closing the issue as no further customer communication. Please reopen if still blocked.
