### ISSUE TITLE
PublishCoverageTask can't deal with two coverage results

### ISSUE THREAD

**Issue by totkeks** [Microsoft/vsts-tasks#7562]
## Environment
- Server - VSTS
- Agent - Private

## Issue Description

I have an angular application structured in two pieces, the application and a library. I have unit tests in both of them, meaning karma junit generates two cobertura-coverage.xml and two html coverage results.

First I tried to use a wildcard for the path, but this only seems to be intended for auto generated path names you don't know upfront. It gave an error, that it found two files and selected the first.

Then I tried to use two Publish Coverage Tasks, but this just overwrote the first task results.

It would be great if the task could use the wildcard pattern to include multiple results and somehow merge them. Or VSTS could support upload of multiple coverage results. I don't know which one would be the better workflow.

**Comment by kaadhina** [comment]
@totkeks Thank you for your feedback! We do not support merging of coverage data for cobertura, and this is not in the immediate plans. You may vote for it here if the request exists or create one : https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services
