### ISSUE TITLE
VsTestV2 on TFS 2017 U3: Wrong Visual Studio version selected

### ISSUE THREAD

**Issue by tompatib** [Microsoft/vsts-tasks#7566]
Hi,

I'm using TFS 2017 U3 with Build Agent 2.112.1. I have installed VS Professional 15.7.4 on build servers, also I have Build Tools installed (I had to go for VS Pro due to the VsTest for 2017 was not supported in Build Tools). Lately I have updated the Build Tools to the same 15.7.4 version and since my VsTest tasks started to fail with the message: 

> VisualStudio version selected for test execution : 15.0
[command]powershell -NonInteractive -ExecutionPolicy Unrestricted -file 
> D:\TfsBuildAgent\_work\_tasks\VSTest_ef087383-ee5e-42c7-9a53-ab56c98420f9\2.0.55\vs15Helper.ps1
> Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"
>    C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools</S>
> Objs
> [command]wmic datafile where "name='C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\Common7\\IDE\\CommonExtensions\\Microsoft\\TestWindow\\vstest.console.exe'" get Version /Value
> No Instance(s) Available.

![1](https://user-images.githubusercontent.com/16067575/41909311-ff5eb272-7946-11e8-8908-3cf88a997640.png)

After some troubleshooting it turned out that the vswhere.exe gives back the correct location of VS, selecting the Professional one but the vs15Helper.ps1 takes the first one when found more for the same version and due to the path the Build Tools is preferred but that doesn't have the vstest.console.exe.

![2](https://user-images.githubusercontent.com/16067575/41909327-09aa5358-7947-11e8-8efc-f6dd091c5b43.png)
![3](https://user-images.githubusercontent.com/16067575/41909335-0d65ffd8-7947-11e8-8eb2-7931f6e72242.png)

I think this should somehow considered, for now I have excluded the Build Tools from the PS file as it won't support it:

```

return $instances |

            Where-Object { $_.Version.Major -eq 15 -and $_.Path -notlike "*BuildTools"} |

            Sort-Object -Descending -Property Version |

            Select-Object -First 1 
``` 
![4](https://user-images.githubusercontent.com/16067575/41909342-14161110-7947-11e8-8db6-f73d6eb27fad.png)

Thanks,
Tibor Tompa

**Comment by kaadhina** [comment]
Thank you for reporting this! We have since moved away from this logic to find vstest, and depend only on vswhere in the latest releases.
Apart from the workaround you already have in place, another workaround is to re-install VS Pro (which has vstest workload). Since the script will list and pick up the latest installed, the right one will get picked up.
