### ISSUE TITLE
 Visual Studio Test task - Only one test .dll was processed when Multiple .dll Tests parsed

### ISSUE THREAD

**Issue by fmanea** [Microsoft/vsts-tasks#7570]
## Environment
- Server - VSTS or TFS on-premises?
VSTS private server
- Agent - Hosted or Private: 
OS: Windows Server 2016 -
Agent version: v2.112.0

## Issue Description

If multiple .dll tests are added into  "Test Assemblies" build step, it finds all of them and runs it in this way:

```
2018-06-19T12:23:20.4150501Z ##[debug]   workingFolder = d:\Builds\7\s
2018-06-19T12:23:20.4150501Z ##[debug]   filename = C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe
2018-06-19T12:23:20.4150501Z ##[debug]   arguments = "d:\Builds\7\s\tests\DefaultTest.dll" "d:\Builds\7\s\tests\UnitTests.dll" "d:\Builds\7\s\tests\UnitTestsNative.dll"  /logger:trx
```

But it only outputs/performs the tests from only one .dll (the first one, in my case: DefaultTest.dll. The other ones are skipped in some way.

How can I fix this issue?

**Comment by kaadhina** [comment]
What framework are these tests? Do you have the necessary test adapters in place?
Is there a test filter that is ignoring the other tests?

Can you please enable debug logs (set system.debug = true) and send us the logs? You may also choose to mail them to devops_tools@microsoft.com

**Comment by kaadhina** [comment]
You've mentioned you are on VSTS, please move to VsTest version 2 (which has a lot of improvements and fixes), seems like you are on v1.

Which framework are these tests of? mstest/xunit/etc?

Please send the full logs if possible.

**Comment by fmanea** [comment]
The framework is mstest, I will send the full logs, after testing the version 2. (if it doesn't succeed)

**Comment by fmanea** [comment]
The logs will take a while to be delivered, because we have to filter out paths and test names because of Non disclosure agreement.

**Comment by fmanea** [comment]
Hello,
After further debugging, there is no issue on the vsts task part.
I have used two agents (one on Windows 7 and one on windows server 2016) with the same build definition. On one it is working, and on the other is not

After using directly vstest.console.exe utility on one of the test assemblies .dll, on one platform it finds the tests and completes them and on the other it gives me this error:
 ```
Warning: No test is available in PathToDll\UnitTests.dll. Make sure that installed test discoverers & executors, platform & framework version settings are appropriate and try again.
```

So there are some problems on my Windows server 2016 side.

I see that both have Command Line Tool Version 14.0.25420.1, but now I don't know what package to reinstall on the Visual Studio side, in order to discover the tests.

**Comment by kaadhina** [comment]
Are these cpp tests, if so do you have the workload "Desktop development with C++" installed in visual studio?

You can run vstest.console.exe with /diag flag on the machine with the issue and send us the logs

**Comment by fmanea** [comment]
Yes, we had that component missing, after adding it, everything was fine. Thank you for your help! I will close the ticket now,
Have a great day!
