### ISSUE TITLE
How to update vsts-tasks

### ISSUE THREAD

**Issue by LokiMidgard** [Microsoft/vsts-tasks#7571]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
TFS on-premise 2018
Private Agent on Windows Server 2016 (agent version v2.134.2)

## Issue Description

I had the same Problem as in #7050. In the issue it is said that the problem is fixed in a new version.  
I feel dumb to ask this, but how do I update the vsts-tasks? I know how to update the agent (downloading the new version) but this does not seem to have used the new tasks.

**Comment by bryanmacfarlane** [comment]
Tasks are released with the product (VSTS sprint or on-prem release).  We have a mechanism for the product team to hand out a patch of a task but that's in reaction to a specific issue.

**Comment by bryanmacfarlane** [comment]
Closing since question is answered.
