### ISSUE TITLE
Not able to deploy via VSTS

### ISSUE THREAD

**Issue by Jyoti492** [Microsoft/vsts-tasks#7574]
While deploying through VSTS I am getting the error as below. This works for some deployment but some are failed and that is weird. I checked the powershell version as well on the server with which the deployment is happening but no luck. Is there any setting which needs to be modified to get it working ??

Need the resolution to resolve it asap. Kindly help

Cannot process argument transformation on parameter 'website'. Cannot convert the "Microsoft.Azure.Management.WebSites.Models.Site" value of type "Microsoft.Azure.Management.WebSites.Models.Site" to type "Microsoft.Azure.Management.WebSites.Models.Site".

**Comment by bryanmacfarlane** [comment]
What task is this?

**Comment by Jyoti492** [comment]
this is a web deploy task to azure

**Comment by bryanmacfarlane** [comment]
Please include the full log for that task

**Comment by SumiranAgg** [comment]
@Jyoti492 Can you please share the debug logs for the release? (set system.debug to true and rerun the release). You can also share the logs privately to RM_Customer_Queries@Microsoft.com.

**Comment by Jyoti492** [comment]
Hi Team , i deployed a content on Azure Website using VSTS. Now I found the solution for this . Its the 6.x.x version of AzureRM that has a problem , i uninstalled it and installed the 5.x.x version of it and the issue got resolved. So this issue can be closed now.

**Comment by SumiranAgg** [comment]
Thanks @Jyoti492 for letting us know. Please feel free to reopen the issue if required.
