### ISSUE TITLE
AzureFileCopy + AzureResourceGroupDeploymentV2: "Unexpected token ﻿ in JSON at position 0"

### ISSUE THREAD

**Issue by arcotek-ltd** [Microsoft/vsts-tasks#7576]
## Environment
    - VSTS
    - Account: {Contact me - this is a public forum}
    - Team: KCA
    - Build: KCA.Azure.Automation / 2188
    - Release: BL.KLAiM.1.WEB.API-UserTest/Release-8

- Agent - Hosted or Private: 
    (Tried VS2017 and private)
    - If using Hosted agent, provide agent queue name: default

    - If using private agent, provide the OS of the machine running the agent and the agent version: Server 2016

## Issue Description

When running Azure Resource Group Deployment (V2), the task fails with:
`
##[error]Error: Ensure the Template file ( '"Unexpected token �﻿ in JSON at position 0"' ) is valid. Task failed while parsing with following error: %s
`
(U+FFFD � REPLACEMENT CHARACTER used to replace an unknown, unrecognised or unrepresentable character).

The template file is uploaded using an Azure File Copy job in one Git repo and the deployment is a release task in a different Git repo, therefore I have to set `Template location` to `URL of file`. However, as a test, if I run the deployment task from the template's repo, and set `Template location` to `Linked artifact`, the deployment succeeds, therefore, I believe the issue might be with the AZ file copy task as opposed to the deployment, however, if I use PowersShell `New-AzureRmResourceGroupDeployment` and set `-TemplateFile "https://mysa.blob.core.windows.net/dev/Automation.AZRM/Deployment/Kca/Base.Deploy.json?somesastoken"`, (the same file upload by AZ file copy task), PowerShell succeeds.

If I "inspect" the file thus:
```
$TemplateFile = "https://mysa.blob.core.windows.net/dev/Automation.AZRM/Deployment/Kca/Base.Deploy.json?somesastoken"
$content = Invoke-WebRequest -Uri $TemplateFile
$content.RawContent
```

I get:

```
HTTP/1.1 200 OK
Content-MD5: SNoEwhf6sDGrWpRluiInzA==
x-ms-request-id: 1e2099f6-701e-006a-4895-0de065000000
x-ms-version: 2017-07-29
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
x-ms-server-encrypted: true
Access-Control-Expose-Headers: x-ms-request-id,Server,x-ms-version,Content-Type,Last-Modified,ETag,Content-MD5,x-ms-lease-status,x-ms-lease-state,x-ms-blob-type,x-ms-server-encrypted,Accept-Ranges
Access-Control-Allow-Origin: *
Accept-Ranges: bytes
Content-Length: 2289
Content-Type: application/json
Date: Tue, 26 Jun 2018 21:33:47 GMT
ETag: "0x8D5DB9E7820F539"
Last-Modified: Tue, 26 Jun 2018 19:53:20 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0

ï»¿{
    "$schema": "http://schema.management.azure.com/schemas/2014-04-01-preview/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
  "parameters": {
    "webAppName": {
      "type": "string"
    },
````

Notice `ï»¿` at the beginning of the actual template?

Via the portal, if I drill down to the file in the SA and use the "embedded" storage explorer, to edit the file, the `ï»¿` are not shown. However, if I delete `{` and type a new `{`, intellisense creates the closing `}`, which I delete and then rerun the above PowerShell, the `ï»¿` character has gone and the deployment task works.

Finally, in an effort to resolve this myself, I noticed the content type was not `application/json`, so, in the AZ copy file task, under `Optional Arguments (for uploading files to blob)` I added `/SetContentType:application/json, /Y,/Z, /V, /S` which you can see from the above PowerShell output has set content type to `application/json`. This only replaces `ï»¿` with some equally wired characters.

I have tried version 1 and 2 of AZ copy task, however, I can only use version 2 of deploy task. 

I assume it is an issue with node.js, as PowerShell seems to ignore these odd characters.

### Error logs

`
2018-06-25T19:29:29.9250874Z ##[section]Starting: Azure Deployment:Create Or Update Resource Group action on RG-S01-D-DEV-DEPLOYTEST
2018-06-25T19:29:29.9257905Z ==============================================================================
2018-06-25T19:29:29.9258165Z Task         : Azure Resource Group Deployment
2018-06-25T19:29:29.9258450Z Description  : Deploy an Azure resource manager (ARM) template to a resource group. You can also start, stop, delete, deallocate all Virtual Machines (VM) in a resource group
2018-06-25T19:29:29.9258702Z Version      : 2.134.1
2018-06-25T19:29:29.9258896Z Author       : Microsoft Corporation
2018-06-25T19:29:29.9259093Z Help         : [More Information](https://aka.ms/argtaskreadme)
2018-06-25T19:29:29.9259326Z ==============================================================================
2018-06-25T19:29:31.4742731Z Checking if the following resource group exists: RG-S01-D-DEV-DEPLOYTEST.
2018-06-25T19:29:31.4743225Z Resource group exists: true.
2018-06-25T19:29:31.4743430Z Creating deployment parameters.
2018-06-25T19:29:31.4807394Z ##[error]Error: Ensure the Template file ( '"Unexpected token ﻿ in JSON at position 0"' ) is valid. Task failed while parsing with following error: %s
2018-06-25T19:29:31.4831206Z ##[section]Finishing: Azure Deployment:Create Or Update Resource Group action on RG-S01-D-DEV-DEPLOYTEST
`

**Comment by arcotek-ltd** [comment]
Also reported: https://developercommunity.visualstudio.com/content/problem/281457/azure-resource-group-deployment-task-21341-reports.html

**Comment by arcotek-ltd** [comment]
Hi @niadak, 

Just to let you know, @sachinma replied to a comment I added to an old developercommunity ticket asking for logs:  [https://developercommunity.visualstudio.com/content/problem/109162/azure-resource-group-deployment-task-226-reports-i.html?childToView=281898#comment-281898](https://developercommunity.visualstudio.com/content/problem/109162/azure-resource-group-deployment-task-226-reports-i.html?childToView=281898#comment-281898), which I have now sent.

I've updated my developercommunity ticket as well as here.

**Comment by arcotek-ltd** [comment]
@niadak, Why are you closing it? Have you pushed a fix already?

For others who come across this issue, as a workaround until MS fix the issue, I found a helpful Visual Studio extension called [File Fix Encoding](https://marketplace.visualstudio.com/items?itemName=SergeyVlasov.FixFileEncoding).

Apparently, VisualStudio adds a Byte Order Marker (BOM) to every UTF-8 file, except htm & html. This is what the Node.JS version of the VSTS task doesn't like. The extension removes the BOM. The instructions aren't obvious, but you need to add the file extensions you want the BOM removed from. 

1. Install extension, 
2. Re-Launch VS 2017, 
3. Go to Tools > Options > Fix File Encoding. 
4. Change `\.(htm|html)$` to `\.(htm|html|json)$` or replace / add whatever file extension you need.

The extension seems a little buggy with VS 2017 (15.7.4), causing mine to "not respond" when touching an existing JSON file. However, from the extension's good reviews, I guess it's safe to assume Microsoft have moved the goal posts and the extension's developer has to play catch-up.

HTH

**Comment by bryanmacfarlane** [comment]
@niadak - if you load a files bytes and then pass it straight to json parse, you will see this if there's a BOM.  You can strip.   But I also thing that using require(relativePath) will handle BOMs for you.  It's a common bug we had in other tasks and the old node agent.

**Comment by niadak** [comment]
@arcotek-ltd , Thanks for following up on this. I guess I missed that this [DeveloperComunity](https://developercommunity.visualstudio.com/content/problem/109162/azure-resource-group-deployment-task-226-reports-i.html?childToView=281898#comment-281898) issue is an older one and because it is marked as fixed I closed this issue.

We acknowledge this as a active bug on our side as @sachinma has mentioned and will fix it.

**Comment by ds-ms** [comment]
The issue has been fixed for Azure RG task, it should reach all customers by the end of this sprint (i.e. within 3 weeks).
