### ISSUE TITLE
VsTest2 and Test Case ordering

### ISSUE THREAD

**Issue by jburman** [Microsoft/vsts-tasks#7580]
## Environment
- Server - TFS 2018
- Agent - Win 7 x64 - vsts-agent-win7-x64-2.122.2 

## Issue Description
Scenario: We have a Release with a VsTest task configured to select tests via Test run and we have multiple UI tests that then run. It appears to run tests in the order that the methods are defined in the test classes regardless of the Order defined on the Test Cases. It would be very useful to at least have an option to force them to run in the order that the Test Cases are ordered. Are there any other options?

**Comment by abhishkk** [comment]
@jburman 
Ordering of tests is support via OrderedTest. Please check https://msdn.microsoft.com/en-us/library/ms182631.aspx to more about how to create an OrderedTest.

**Comment by abhishkk** [comment]
@jburman Closing this issue. In case of any followup questions, please comment here to re-open the issue.

**Comment by jburman** [comment]
Hi, thanks for responding.
Our goal is to let support team re-order the tests in the test suite and not have to change the code. So I do not think Ordered Test will solve it.

Running the test suite against a Release does not produce the expected behavior as it is ignoring the ordering defined in the test suite.

**Comment by abhishkk** [comment]
@jburman Test suite doesn't guarantee ordering of tests. Only possible way to do so today is Ordered Test.
Ideally two tests should not have dependency on each other. But there are scenarios in CodedUI where a particular tests ordering makes a scenario to validate. In that it is recommended to use ordered test.
