### ISSUE TITLE
Nuget task not considering NO_PROXY list

### ISSUE THREAD

**Issue by mmajcica** [Microsoft/vsts-tasks#7582]
Nuget task in the common library is considering the proxy settings and it is preparing the execution environment with those in mind. It however doesn't take care of the NO_PROXY list.

The change to be effective it will require also that the nuget.exe external tool does get updated to at least version 3.4.2. More details about it here https://github.com/NuGet/Home/issues/1671

**Comment by keithrob** [comment]
Duplicate of #6252
