### ISSUE TITLE
Add pull request user friendly branch name variables

### ISSUE THREAD

**Issue by henryju** [Microsoft/vsts-tasks#7591]
For non pull request builds, there are two variables:
* Build.SourceBranch (for example refs/heads/master)
* Build.SourceBranchName (for example master)

For pull requests there are only the "techincal" ones:
* System.PullRequest.SourceBranch
* System.PullRequest.TargetBranch

Could you please add their "*Name" counterpart?
* System.PullRequest.SourceBranchName
* System.PullRequest.TargetBranchName

Note that currently my workaround is to remove the refs/heads/ prefix, but I'm not sure it works in all situations).

**Comment by bryanmacfarlane** [comment]
Service side request - not an issue with tasks in this repo.  Request on developer community.

**Comment by henryju** [comment]
https://developercommunity.visualstudio.com/content/problem/321581/feature-request-add-pull-request-user-friendly-bra.html

**Comment by henryju** [comment]
https://github.com/microsoft/azure-pipelines-tasks/issues/11225
