### ISSUE TITLE
Add build variable to know if the current branch is the default one

### ISSUE THREAD

**Issue by henryju** [Microsoft/vsts-tasks#7592]
Many ALM (TfsGit, GitHub, Bitbucket Cloud) have a concept of main/default branch. Our task need to do some special behavior depending if the current branch is the default.

My proposal is to introduce a new variable 'System.Branch.IsDefault' that would be 'true' when the current branch is the default.

I don't need that today, but for completeness, you could also provide the same for PR:
* System.PullRequest.TargetBranch.IsDefault

My current workaround (that works only for TfsGit) is to do a REST API call to get the default branch name, and compare with current branch name. See https://github.com/SonarSource/sonar-scanner-vsts/blob/957dfd3a6352d4a3c0004aedf77e73b0787f4a26/common/ts/prepare-task.ts#L103

**Comment by bryanmacfarlane** [comment]
Service side request - not an issue with tasks in this repo.  Request on developer community.

**Comment by henryju** [comment]
https://developercommunity.visualstudio.com/content/problem/321583/feature-request-add-a-build-variable-to-know-if-th.html
