### ISSUE TITLE
No retry on transient error - Service Fabric Deployment task

### ISSUE THREAD

**Issue by Leo-Mepham** [Microsoft/vsts-tasks#7597]
We have is an intermittent error on the service fabric deployment task.

We have multiple CD pipelines deploying releases of different service fabric applications, and some of these will occasionally fail on the "Deploy Service Fabric Application" VSTS Task.

We are using VSTS, with private build agents (Windows Datacenter 2016, latest version)

The error message is "Could not ping any of the provided Service Fabric gateway endpoints."

The error is transient, in that when we notice the failure we can re-deploy the release and there is usually no problem.

The SF cluster is spread across 3 VM scale sets, with 1 scale set being a dedicated 5-node scale set for the SF management services.

Is it possible to get the task to retry on transient errors like this?

**Comment by bishal-pdMSFT** [comment]
@Leo-Mepham can you please provide following details:

- What is the service fabric SDK version installed on your private agents?
- What is the location of your SF cluster? Is it happening only for one cluster or multiple clusters across regions?
- Can you please provide full error log for the task(preferentially debug logs)

**Comment by Leo-Mepham** [comment]
Hi @bishal-pdMSFT 

Service Fabric SDK version on private agents is 3.1.274.9494
Location of SF cluster is West Europe, we have two clusters there, both display intermittent error, quite rarely
I don't have debug logs, is it correct that I need to add a variable to the release pipeline of "system.debug" set to "true"?

**Comment by sachinma** [comment]
@Leo-Mepham  We have observed issues with connectivity with the error message you encountered with SDK version 3.1 We are working with Service fabric team to investiagte this further.

We are also working on addding retry in the task. See #7607 and #7588

**Comment by Leo-Mepham** [comment]
Thanks @sachinma for now I have made a modified version of the task with a simple try/catch/sleep loop and this has worked for us. It is still rare and intermittent, and I have yet to see it retry more than once.

**Comment by bishal-pdMSFT** [comment]
@Leo-Mepham this issue has been fixed. Closing the issue. If you still same error, please re-activate this issue.
