### ISSUE TITLE
IIS Web App Manage task fails

### ISSUE THREAD

**Issue by Prashanth-PS** [Microsoft/vsts-tasks#7599]
##[command]"netsh" http add sslcert hostnameport=ta-devvstsr-01:443 certhash=******** appid={c4a4f6a3-10a5-4fb6-977b-f1df3672ba33} certstorename=MY
SSL Certificate add failed, Error: 1312
A specified logon session does not exist. It may already have been terminated.

The deployment task 'IIS Web App Manage' is failing with the above error, please let me know the soluton for this ASAP

**Comment by SumiranAgg** [comment]
Thanks @pragupta-ms for reporting this issue. 
Can you set a variable in your release definition system.debug and set its value to true? This will give you more detailed logs. Please send the details to RM_Customer_Queries [at] microsoft [dot] com. Also mention this github issue's reference in the mail.

**Comment by SumiranAgg** [comment]
Closing since data not enough for investigation and no further customer communication. Please feel free to reopen if still blocked.

**Comment by Andrei-** [comment]
I just hit this issue last week, the difference between a successful deploy and a failed one is that the "IIS Web App Manage" task is now, for some reason, trying to add ssl certificate on hosting server. Any idea why?

![ghub error](https://user-images.githubusercontent.com/6005180/98375132-004e6480-2042-11eb-99f3-7a0482d189af.JPG)

**Comment by JoshuaRHolden** [comment]
This was happening a bunch to me, turned out I copied and pasted the thumbprint in from the certificate, when i copied it in it included a hidden character, make sure you sanitise the string if copying and pasting (or manually type it in.

**Comment by Andrei-** [comment]
Oh yes, forgot about this post, but in my case it was because the customer has updated ssl certificates on the target server and the thumbprint was no longer valid in the release pipeline settings. Took me some (irritating) hours to find the problem.
