### ISSUE TITLE
Override Template Parameters not working for securestring on V2 (not fixed yet)

### ISSUE THREAD

**Issue by devedse** [Microsoft/vsts-tasks#7622]
#5372 

As I can't reopen this issue I would like to make a new one informing all that this is not fixed yet. I added a detailed post to the issue mentioned above here describing how to reproduce the issue we're facing.

**Comment by ds-ms** [comment]
@devedse The task is based on node, so PS commands like `ConvertTo-SecureString` are not recognized in this context, hence the major version change. 
We have added this in the release notes: 
![image](https://user-images.githubusercontent.com/25762922/42259403-ec7c1ed2-7f7d-11e8-8ed7-26a777b3897a.png)

The task now treats `(ConvertTo-SecureString '$(artifactsLocationSasToken)' -AsPlainText -Force)` as string where you have expected it to convert `$(artifactsLocationSasToken)` to a secure string. We have added help texts for secure strings explicitly in the pop up which opens when you click on `...` next to Override template parameters.

**Comment by devedse** [comment]
Ok, to summarize this would be the solution then?:

![image](https://user-images.githubusercontent.com/2350015/42269901-c0f76abc-7f7f-11e8-9371-7234f359c2b4.png)

**Comment by ds-ms** [comment]
Yes, that is correct. 👍

**Comment by devedse** [comment]
Another followup question. Is there a way to expose this issue to VSTS or Azure when the deployment fails? As the only error that you'll get back is a 403 without any context.

**Comment by ds-ms** [comment]
You can send your queries to RM_Customer_Queries@microsoft.com, the required team would be engaged based on your query eventually.

**Comment by devedse** [comment]
Sent them an email, let's we'll see an answer soon 😄

**Comment by devedse** [comment]
I got a response from the RM_Customer_Queries@microsoft.com team with the request to create a UserVoice post:
https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services/suggestions/34745740-deploying-with-arm-msdeploy-doesn-t-give-detaile
