### ISSUE TITLE
Azure File Copy (V1 and V2): "Container Name" help Markdown mentions a default, but the setting is required

### ISSUE THREAD

**Issue by brcrista** [Microsoft/vsts-tasks#7623]
This help text is not correct:

![image](https://user-images.githubusercontent.com/33549821/42236303-8e087dc4-7ec8-11e8-8054-c08b8b3988a0.png)

The [official documentation](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/deploy/azure-file-copy?view=vsts) explains this correctly: 

![image](https://user-images.githubusercontent.com/33549821/42236458-e5384890-7ec8-11e8-889b-7a1f9b4a5241.png)

**Comment by rajatagrawal-dev** [comment]
@brcrista Thanks for reporting this. We'll update the help text soon in both - version 1 and version 2, of the task.

**Comment by SumiranAgg** [comment]
@brcrista Thanks for your feedback.
We will rollout the fix soon. It should be deployed on all rings in the next few days.
