### ISSUE TITLE
Run VsTest task with console logger instead of trx

### ISSUE THREAD

**Issue by rhughesjr** [Microsoft/vsts-tasks#764]
I'm trying to debug a test that is hanging on our build server.

I'd like to run the tests using the /logger:Console flag:
![image](https://cloud.githubusercontent.com/assets/2052033/10999081/aa87ee50-845f-11e5-9106-d323f37b1741.png)

However, when the test is executed, it still has /logger:trx appended tothe end of the command line, which supercedes the Console option.

It would be great if the "Other console options" field was applied with logic to avoid duplicate flags like this.

**Comment by atinb** [comment]
All console output for failing tests is now uploaded to the server as test attachments. Does that help with your scenario? Thanks!

**Comment by rhughesjr** [comment]
Yes, I think that would help. We are no longer having the issue so I can't confirm for sure.
Also, what do you mean by, "now"? As of which TFS version? Or, is it something we can patch manually?

**Comment by atinb** [comment]
Its live on VSTS. It will be in the next version of TFS.
Thanks!
