### ISSUE TITLE
Visual Studio Test task is cancled after a little less then one hour

### ISSUE THREAD

**Issue by LokiMidgard** [Microsoft/vsts-tasks#7643]
## Environment
TFS 2018 with private agent version 2.134.2 on Windows 7

## Issue Description

I have a build that executes a `Visual Studio Test` task in a multiconfiguration phase. The test will be cancled after the build runs for around one houre.  With
```
2018-07-06T07:59:30.8845710Z ##[debug]Re-evaluate condition on job cancellation for step: 'VsTest - testPlan'.
2018-07-06T07:59:31.1658246Z ##[error]The operation was canceled.
```
Currently while it is a multiconfiguration phase, I only test with one agent.

What condition will be evaluated that cancels the task? I did not set a timeout (default is 0 equals infinit)

Also the test run under Tests will still set as in process and the result of tests that already run will not be published.

### Error logs
[vsts-vstest.log](https://github.com/Microsoft/vsts-tasks/files/2169644/vsts-vstest.log)

**Comment by bryanmacfarlane** [comment]
There's two timeouts - one at the job/phase and one at the step.  check both.

**Comment by LokiMidgard** [comment]
Thanks for the tip.

It was the timeout of the complete build under the options of the build defintion. Default is 60 minuts. I set it to 660 minuts. I think I will know next week.

**Comment by abhishkk** [comment]
@LokiMidgard Is the issue resolved after increasing build timeout?

**Comment by LokiMidgard** [comment]
We'll the tests still don't finish, but that seems to be another issue.

**Comment by abhishkk** [comment]
@LokiMidgard Whats the new issue which you are facing?

**Comment by LokiMidgard** [comment]
I was away and not working on the Project, so I will start to investigate. It could be that its just an error in our tests. On TFS 2010 the test normaly took little more then 3 hours and if everything goes south it takes 4 hours. The build timouted after 6.3 hours. So chances are high that the bug is this time in our code. But I will open another issue if I find anything.

I opend #7701 but I'm not sure if you would call it a bug or just an inconvenients.
