### ISSUE TITLE
[YAML] Auto Release to "GitHub Release" 

### ISSUE THREAD

**Issue by guolinke** [Microsoft/vsts-tasks#7645]
Both Travis and Appveory support to release back to github: https://docs.travis-ci.com/user/deployment/releases/

However, I cannot find this feature in vsts-ci, from the document.
Is this feature available ?

Although there are few github extensions said support "GitHub Releas" in market place, but I don't how to use them in yaml build.

**Comment by ericsciple** [comment]
[Here](https://github.com/Microsoft/vsts-agent/blob/master/docs/preview/yamlgettingstarted-tasks.md) is the doc for referencing tasks from a yaml file. The View Yaml link from a designer definition would be the best way to get the yaml file started.

**Comment by guolinke** [comment]
How can I get the task name and version from a extension ? 
For example, like this one: https://marketplace.visualstudio.com/items?itemName=jakobehn.jakobehn-vsts-github-tasks . There are almost no documents about how to use it.
