### ISSUE TITLE
Get-AzureStorageContainer - Fails on VSTS but works locally

### ISSUE THREAD

**Issue by grik001** [Microsoft/vsts-tasks#7646]
Hi,

I am attempting to use Get-AzureStorageContainer but it keeps failing on VSTS when using a Powershell Task. This works locally, but I keep getting a 403 on VSTS.

**Comment by bryanmacfarlane** [comment]
Have you tried the azure powershell task plus a service endpoint so credentials flow?

**Comment by grik001** [comment]
Hi Bryan, 

Thanks for your reply :) 

I can only do this using SasToken. So I will have to stick with the normal power shell task. Is this a known issue?

**Comment by SumiranAgg** [comment]
Can you share a sample script that is failing? We would like to know how you are using SASToken with Get-AzureStorageAccount.

**Comment by grik001** [comment]
Hi, I have stopped using this command and started querying the API directly but for reference purposes:

$ctx = New-AzureStorageContext -StorageAccountName "coditstgweinvictusstore" -SasToken ""
$containers = Get-AzureStorageContainer -Context $ctx

**Comment by rajatagrawal-dev** [comment]
@grik001 I tried to reproduce your scenario but it worked for me, both locally and using VSTS. You can try to debug this further if you like by seeing exactly which command is failing. Enabling debug logs by adding a variable _system.debug_ with value as _true_ in your release definition might help you with this.

**Comment by rajatagrawal-dev** [comment]
Closing this. Please reopen if required.
