### ISSUE TITLE
Uploading entire folders in FTP Upload Task

### ISSUE THREAD

**Issue by jrmcdona** [Microsoft/vsts-tasks#7647]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
    
VSTS
https://microsoft.visualstudio.com/Xbox.Ambassadors/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=27996

- Agent - Hosted or Private: 
    
Agent, OSX

## Issue Description
Is there a way to FTP a folder? Or just files?

In my build output I have an "assets" folder and I want the entire folder copied to the App service.  I also want all the files in the root build output folder to get copied over.
### Error logs

[Insert error from the logs here]

**Comment by yacaovsnc** [comment]
You can do this to achieve the desired outcome:
![image](https://user-images.githubusercontent.com/10119737/42453638-57e20b88-835b-11e8-81bc-54813790c609.png)

You can upload everything in a folder and preserve the file structure.

**Comment by joshmgross** [comment]
Closing this issue. If solution doesn't work, please reply and reopen the issue.

**Comment by JaimeBulaGooten** [comment]
This solves the issue! Confirmed
