### ISSUE TITLE
Can't install PowerShell module within Azure CLI task

### ISSUE THREAD

**Issue by justinyoo** [Microsoft/vsts-tasks#7655]
Hi, Team.

I'd like to use Azure CLI task to run a test PowerShell script as it's basically run in the PowerShell console. However, I'm not able to install extra PowerShell module like Pester in it. When I tried to install it, it threw errors like:

```
2018-07-08T04:39:45.1691947Z D:\a\1\s>Install-PackageProvider -Name NuGet -Force -Scope CurrentUser 
2018-07-08T04:39:45.1693577Z 'Install-PackageProvider' is not recognized as an internal or external command,
2018-07-08T04:39:45.1694409Z operable program or batch file.
2018-07-08T04:39:45.1715559Z 
2018-07-08T04:39:45.1716321Z D:\a\1\s>Install-Module -Name Pester -Force -Scope CurrentUser 
2018-07-08T04:39:45.1732925Z 'Install-Module' is not recognized as an internal or external command,
2018-07-08T04:39:45.1735415Z operable program or batch file.
```

* `Install-PackageProvider` is not recognized ...
* `Install-Module` is not recognized ...

As a workaround, I have to use the PowerShell task, and install Pester and Azure CLI during the task run. Is there anything that I missed when using the Azure CLI task?

Cheers,

**Comment by bryanmacfarlane** [comment]
I'll let the azure powershell owners speak to and investigate why it doesn't work.  However, I wanted to point out that it's probably desirable to have install scripts/tasks separate from the tasks that consume them and do the work (rather than a workaround).

**Comment by justinyoo** [comment]
@bryanmacfarlane Yes, that's what I currently do, using the PowerShell task - to install Pester and Azure CLI.

**Comment by justinyoo** [comment]
@bryanmacfarlane To be clear, the Azure PowerShell task is fine, while the Azure CLI task has this issue.

**Comment by bryanmacfarlane** [comment]
@justinyoo - thanks for the clarification

**Comment by sachinma** [comment]
@justinyoo Azure CLI does not invoke the script with PowerShell exe. So to execute PowerShell commands/scripts, you will have to invoke them with PowerShell.exe.
e..g PowerShell.exe -file <>
or PowerShell.exe <command>

**Comment by justinyoo** [comment]
@sachinma ORLY? Let me try it and get back to you. If this applies to my case, that would be ideal.

**Comment by bishal-pdMSFT** [comment]
@justinyoo any update on this?

**Comment by justinyoo** [comment]
@sachinma @bishal-pdMSFT Oh, sorry. Forgot to update. Yes, it works all the cases below:

```powershell
PowerShell Invoke-PackageProvider ...
PowerShell Invoke-Module ...
PowerShell -file [my-file.ps1] -parameter1 value1 -parameter2 value2 ...
```

Therefore, I can now remove one task that installing Azure CLI, which reduces the total CI time.

Thanks!
