### ISSUE TITLE
Artifact From Custom Task

### ISSUE THREAD

**Issue by devanshujoshi** [Microsoft/vsts-tasks#7656]
Hi , 
I am writing a custom VSTS Task for deployment on Azure. My task is to make rest calls to ARM api , and based on the input provided in the task , I have to create a ARM parameter file during task's execution and publish that as a artifact to release pipeline.
I am struggling to create a json file for as a build artifact.
Code is as below : 
         $policyFolder = "$(Build.ArtifactStagingDirectory)\$policyName"
          if (!(Test-Path $policyFolder -PathType Container)) {
              New-Item -ItemType Directory -Force -Path $policyFolder
           }
        $assignmentfile=$policyFolder +'\assignment.json'
        $json | Out-File -LiteralPath $assignmentfile -Force
The task is giving error as Build.ArtifactStagingDirectory is not recognised as a valid cmdlet.
##[error]The term 'Build.ArtifactStagingDirectory' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

In the next task I am trying to publish the json file as artifact from Artifact Staging Directory.

Is there a way to create a file during the task execution? And publish that as artifact for release.
Why I am getting the error for Build.ArtifactStagingDirectory , as it is a environment variable , and it should be avaiable during execution?

**Comment by GitHubSriramB** [comment]
@devanshujoshi - It is possible to publish artifact from Build & use that within Release. You can use "Publish Build Artifacts" task to do this. 

Build.ArtifactStagingDirectory variable is not available within Release. Are you using this task in Build or Release?

**Comment by JohannesDrexler** [comment]
If this is a customTask and no powershell-inline you can't access $(Build.ArtifactStagingDirectory) like that in your script. Theses build.X variables are available as environment-variables for the powershell script of your custom task with the "." replaced with "_". 
So instead of
`$policyFolder = "$(Build.ArtifactStagingDirectory)$policyName"`
you would do this
`$policyFolder = Join-Path $env:BUILD_ARTIFACTSDIRECTORY $policyName`
(I used join-path here because i am unsure if you need a '\' between them or not so this should handle the pathbuilding)

**Comment by brunomartinspro** [comment]
> If this is a customTask and no powershell-inline you can't access $(Build.ArtifactStagingDirectory) like that in your script. Theses build.X variables are available as environment-variables for the powershell script of your custom task with the "." replaced with "_".
> So instead of
> `$policyFolder = "$(Build.ArtifactStagingDirectory)$policyName"`
> you would do this
> `$policyFolder = Join-Path $env:BUILD_ARTIFACTSDIRECTORY $policyName`
> (I used join-path here because i am unsure if you need a '' between them or not so this should handle the pathbuilding)

List of all Env variables
https://gist.github.com/heiswayi/1599e46b64e857f23fc2b9a0fb5c0c3c
