### ISSUE TITLE
VSTS code: Kusto code highlighter

### ISSUE THREAD

**Issue by Theelepel** [Microsoft/vsts-tasks#7670]
Hi,

My customer and I use a lot of Kusto. We noticed that there is no Kusto Code highlighter within VSTS code.

We would like something like this:
https://marketplace.visualstudio.com/items?itemName=josin.kusto-syntax-highlighting

I noticed that 
https://analytics.applicationinsights.io/
uses Monaco in the query editor.
And in the config:
https://applicationanalytics.azureedge.net/common.js?_b=4d21b
you can choose Kusto as language.

Can code highlighting for Kusto be enabled?

**Comment by bryanmacfarlane** [comment]
These issues are for tracking issues with the tasks (/tasks) in this repo.  Reactivate if I misunderstood but specifiy the task you're having an issue with.
