### ISSUE TITLE
Azure SQL Publish displays plain text password for ADMIN user

### ISSUE THREAD

**Issue by argrithmag** [Microsoft/vsts-tasks#7673]
## Troubleshooting
N/A

## Environment
- VSTS

## Issue Description

Azure SQL Publish requires Admin Username/Password, but does not mask the password.  Anyone signed in can see the admin's password.

![image](https://user-images.githubusercontent.com/1087256/42520193-4d121830-842b-11e8-9d46-c84693098548.png)

### Error logs

[Insert error from the logs here]

**Comment by SumiranAgg** [comment]
@argrithmag You can use secure variables for this. Click on the variables tab in your release Definition. Add a new variable and click on lock icon next to the value. 
![image](https://user-images.githubusercontent.com/8316321/42537869-c5972d4e-84b3-11e8-927d-9736d40e3c6b.png)

Use can use this variable in your task as $(password).

**Comment by SumiranAgg** [comment]
Closing since no further customer communication. Feel free to reopen if this issue is not resolved.
