### ISSUE TITLE
Build Machine Image

### ISSUE THREAD

**Issue by whytoe** [Microsoft/vsts-tasks#7676]
## Issue Description

Build Machine Image Task is failing due to a old version of Packer
The Version 0.12.3 being used was released according to the Hashicorp Changelog on March 1, 2017

Packer is currently at version 0.12.3

The current version of Packer is 1.2.4

Can this be updated in the Build Machine Image VSTS Task?

Current Packer Version
![image](https://user-images.githubusercontent.com/12265878/42534640-2e2fbe7e-845b-11e8-93c3-d3d643c92bf0.png)

Current VSTS Build Agent
![image](https://user-images.githubusercontent.com/12265878/42534675-567da24c-845b-11e8-98a9-c9121e45e323.png)

### Error logs

Errors validating build 'azure-arm'. 5 error(s) occurred:
* unknown configuration key: "build_resource_group_name"
* unknown configuration key: "custom_managed_image_name"
* unknown configuration key: "custom_managed_image_resource_group_name"
* unknown configuration key: "managed_image_name"
* unknown configuration key: "managed_image_resource_group_name"

**Comment by bishal-pdMSFT** [comment]
@whytoe are you using custom packer template or auto-generated one? If using custom template, you have to ensure that your template is valid and you are supplying all necessary variables.

**Comment by whytoe** [comment]
Yes I am using a custom template

**Comment by bishal-pdMSFT** [comment]
Then it is not a task issue. Ensure that you are providing correct variable values through "Template parameters" input

**Comment by bishal-pdMSFT** [comment]
Please re-open if you feel otherwise

**Comment by whytoe** [comment]
No the actual issue @bishal-pdMSFT is the Version of Packer in the task, it is an old version of Packer

**Comment by bishal-pdMSFT** [comment]
A PR is already out there for updating packer version in task. However currently we are evaluating best approach to update, hence it will take some time to merge that PR.

**Comment by whytoe** [comment]
@bishal-pdMSFT The current version is really old, over a year. How long is some time?

**Comment by bishal-pdMSFT** [comment]
I will update you mid next week.

**Comment by whytoe** [comment]
Thanks alot!

**Comment by whytoe** [comment]
@bishal-pdMSFT Its mid week :)
Do you have any update?

**Comment by bishal-pdMSFT** [comment]
Yes, we will go ahead with the PR - once the author has resolved all comments. We will bump up the major version of task so that not to break anyone using current packer version.

**Comment by whytoe** [comment]
@bishal-pdMSFT Do you have a PR reference number? so i can follow that?
