### ISSUE TITLE
Azure Powershell task fails on AzureRM 6.4.0 when switching between tenants

### ISSUE THREAD

**Issue by EwanNoble** [Microsoft/vsts-tasks#7689]
## Environment
- Server - VSTS or TFS on-premises?
VSTS    

- Agent - Hosted or Private: 
Private
Agent.OSVersion  10.0.14393
Agent.Version 2.134.2

## Issue Description

Task Name: Azure Powershell (version 2)

Today we upgraded to AzureRM powershell module version 6.4.0 from 5.7.0, one of the breaking changes is to do with context autosaving https://docs.microsoft.com/en-us/powershell/azure/migration-guide.6.0.0?view=azurermps-6.4.0#general-breaking-changes

Azure Powershell worked fine with 6.4.0 on our dev/test environment tenant, when we then tried to deploy to our Production tenant the following error appeared:
```
Add-AzureRMAccount -ServicePrincipal -Tenant *** -Credential System.Management.Automation.PSCredential -Environment AzureCloud
Select-AzureRMSubscription -SubscriptionId *** -TenantId ***
```
`[error]Please provide a valid tenant or a valid subscription.
`

After running "Disable-AzureRmContextAutosave" on our build server the issue was resolved. Can this be handled better or worked around by the VSTS task?

**Comment by SumiranAgg** [comment]
@EwanNoble We are working with azure PS team to get a resolution. https://github.com/Azure/azure-powershell/issues/6680
In the meanwhile we are adding a workaround. We will Clear-AzureRmContext before logging in Azure again. As such only one context will be in memory when connection is made.

**Comment by SumiranAgg** [comment]
Closing the issue since fix has been deployed. Please feel free to reopen if required.
