### ISSUE TITLE
Coverage uploaded, but not displayed

### ISSUE THREAD

**Issue by 4c74356b41** [Microsoft/vsts-tasks#7703]
## Environment
VSTS
Private agent

## Issue Description
coverage published but not visible (partially)

### Error logs
No errors.
timeline tab shows this:
![image](https://user-images.githubusercontent.com/16194643/42621408-5e25e60a-85c6-11e8-8eca-ebf94b185ff0.png)

coverage tabs shows error
![image](https://user-images.githubusercontent.com/16194643/42621414-64b2ba2a-85c6-11e8-8be5-736e4da40113.png)

**Comment by 4c74356b41** [comment]
ok, i should probably add we are using gcovr to generate coverage. when we were generating HTML reports nothing were displayed at all. when we switched to xml reports only this is being displayed.

**Comment by nigurr** [comment]
@4c74356b41 Currently this feature is not yet available. We are currently working on this.
Thanks for your feedback. Please do share your ideas/feature requests here: https://visualstudio.uservoice.com/forums/330519-visual-studio-team-services

**Comment by 4c74356b41** [comment]
@nigurr
