### ISSUE TITLE
Azure PowerShell task: Insufficient privileges to complete the operation

### ISSUE THREAD

**Issue by Jaffacakes82** [Microsoft/vsts-tasks#7710]
## Environment
- Server - VSTS
    - https://nhsidev.visualstudio.com
    - NCIP
    - build-develop
    - 0.8.0-unstable.19 

- Agent - Private
    - Windows Server 2016
    - 2.134.2

## Issue Description
I have an Azure PowerShell task _(Azure PowerShell script: InlineScript)_ that executes a very simple inline script `Get-AzureRmADServicePrincipal -SearchString "<name-of-app>"`. The task results in an error stating: Insufficient privileges to complete the operation.

I have granted the Service Principal used to connect to the Azure subscription from VSTS the following permission:
![image](https://user-images.githubusercontent.com/4850159/42640440-3946db2c-85ea-11e8-9f18-dc11ae47afa7.png)

With no success. Are there other permissions that need adding to the Service Principal?

### Error logs
![image](https://user-images.githubusercontent.com/4850159/42640482-4d7b4fba-85ea-11e8-8b9e-8ebea632b11c.png)

Thanks in advance for your help.

**Comment by SumiranAgg** [comment]
@Jaffacakes82 The azure powershell task, logs into azure account using -ServicePrincipal as authorization scheme. Our understanding is you cannot access other Service Principals unless your selected service principal has appropriate permissions or you login as user.
One workaround could be, you login as user (only possible if you do not use multiple factor authentication) through a normal powershell task. 
In the meanwhile, we will check on any permissions that could be provided to make this work.

**Comment by SumiranAgg** [comment]
@Jaffacakes82 You can add permissions to your app in ADD. In the portal go to your app, settings, Required Permissions. Click on Add, select API and select permission. Can you try with permssions as under:
For API Windows Azure Active Directory:
![image](https://user-images.githubusercontent.com/8316321/42745929-f73c1600-88f2-11e8-95a8-3a59c60def49.png)
For API Microsoft Graph:
![image](https://user-images.githubusercontent.com/8316321/42745957-1643879a-88f3-11e8-8ce4-0af2304bcd12.png)
For trial you can provide all permissions instead of only those in screenshot.
Also few of these permissions can only be provided if you are an Admin.

**Comment by Jaffacakes82** [comment]
@SumiranAgg thanks for your response, I will try and add some of these permissions and let you know how it goes.

Please can you confirm my understanding that the Azure PowerShell task attempts to login as the Service Principal created in Azure AD that gets added when creating a service endpoint from a VSTS project to an Azure subscription?

**Comment by SumiranAgg** [comment]
@Jaffacakes82 Yes that is correct. Also you might have multiple service endpoints in your VSTS project. The task logs-in with the service endpoint you select in the task under "Azure Subscription".

**Comment by Jaffacakes82** [comment]
@SumiranAgg thanks for the clarification. Can you also clarify what the delegated permissions does? For example, If I am a Global Administrator in the directory, does that delegate those same permissions to the Service Principal?

**Comment by SumiranAgg** [comment]
@Jaffacakes82 Just for my understanding, did you add permissions to the app corresponding to service principal used in the task? You can find your add by using the service principal ID in search field for "App Registrations" in AAD.

**Comment by SumiranAgg** [comment]
@Jaffacakes82 I recreated the scenario and It worked with only below permissions for me:
![image](https://user-images.githubusercontent.com/8316321/42819332-dd344ecc-89f0-11e8-9592-51d3e5b32517.png)

**Comment by SumiranAgg** [comment]
Please use this document for reference: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications#configure-a-client-application-to-access-web-apis

**Comment by Jaffacakes82** [comment]
Very strange, it still doesn't work for me.

I have reverted to using a service account in our Azure AD to grant the key vault access as opposed to the VSTS service principal and this has resolved my issue.

**Comment by rajatagrawal-dev** [comment]
@Jaffacakes82 Glad that you were able to resolve it.
Please reopen if you get blocked with this again.

**Comment by craigmpeters** [comment]
Can this be re-opened please as having the exact same issue, and not able to revert to key vault access to do what I am doing.
