### ISSUE TITLE
Service Fabric Application Deployment task fails with "AADSTS50079: The user is required to use multi-factor authentication."

### ISSUE THREAD

**Issue by brianholley** [Microsoft/vsts-tasks#7714]
## Environment
- Server - VSTS 
- Agent - Hosted 2017

## Issue Description

Running the "Service Fabric Application Deployment" task using AAD credentials

Our AAD tenant normally requires multi-factor authentication for all users, but this task was working successfully until today with no apparent change we can find on our part.

Ideally we'd be using a service principal for these deployment tasks, but that's not supported in Service Fabric Cluster service endpoint connections.

### Error logs

2018-07-12T18:41:23.4868682Z ##[error]An error occurred attempting to acquire an Azure Active Directory token. Ensure that your service endpoint is configured properly with valid credentials. Error message: Exception calling "AcquireToken" with "3" argument(s): "AADSTS50079: The user is required to use multi-factor authentication.

Trace ID: 910b9587-36f3-4ab2-af93-4731246d0000
Correlation ID: 44b21c73-1200-4969-bd7d-c78b99d2f7ef
Timestamp: 2018-07-12 18:41:22Z

**Comment by rupreetg** [comment]
I faced similar issue but resolved it using certificate based authentication instead of using AAD Authentication in the service endpoint configuration. I am able to deploy the packages successfully.

**Comment by bishal-pdMSFT** [comment]
@brianholley From the e-mail thread for issue, I believe you are un-blocked now after using certificates for authentication. @rupreetg has also suggested same. Should we close issue in that case?

**Comment by bishal-pdMSFT** [comment]
Closing this. Please re-activate if you don't agree.
