### ISSUE TITLE
Release Definition Visual Studio Test task v2.* Not finding testing framework when installed with VSTEST Platform installer

### ISSUE THREAD

**Issue by tbielejeski** [Microsoft/vsts-tasks#7730]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?  On premises
    
    - If using TFS on-premises, provide the version: 
    2017 update 3  
    - If using VSTS, provide the account name, team project name, build definition name/build number: 

- Agent - Hosted or Private:  Private
    
    - If using Hosted agent, provide agent queue name:

    - If using private agent, provide the OS of the machine running the agent and the agent version: 
version 2.133.3  Windows 2016

## Issue Description

When using the Release pipeline with  the VStest Platform Installer task installing the latest framework version.  When the VSTEST task run after it can not find the framework the prior task installed

Looks like the VStest Platform Installer task sets a variable to the path of the product and the VSTEST  task uses that variable but seems to not match the search criteria . 

Looking at the task code is ilooking for \Microsoft.IntelliTrace.ProfilerProxy.dll and that is not part of the installed dlls

### Error logs

[Insert error from the logs here]
[ReleaseLogs_1710.zip](https://github.com/Microsoft/vsts-tasks/files/2193504/ReleaseLogs_1710.zip)

**Comment by nigurr** [comment]
@tbielejeski 

From the logs, you seem to set `Select test platform using = Specific Location`.
This won't work with 'Tools installer`. Please configure your VsTest task with below values
`Select test platform using = Version`
`Test platform version = Installed by Tools Installer`

**Comment by nigurr** [comment]
Closing the issue as there's no further update. Please feel free to reach us in case of any issue
