### ISSUE TITLE
Azure Powershell Task lacks Select-AzureRmContext

### ISSUE THREAD

**Issue by mkosieradzki** [Microsoft/vsts-tasks#7732]
I have noticed, after recently upgrading AzureRM module, that Azure Powershell Task uses wrong credentials. I mean it correctly: 
1. adds account, 
2. it correctly selects subscription

but then it forgets to select an appropriate context and effectively tasks are executing using a random account available on this machine.

I believe that Azure Powershell task should call Select-AzureRmContext to ensure Service Principal account is used.

**Comment by SumiranAgg** [comment]
@mkosieradzki With the new Azure powershell verion >6, a breaking change has been introduced regarding auto save of ARM context. There is an isssue on github for the same: https://github.com/Azure/azure-powershell/issues/6680
We will get back to you soon on our resolution plan.

**Comment by SumiranAgg** [comment]
@mkosieradzki As a workaround we will Clear-AzureRmContext before logging in. This will ensure only relevant context is used for calls henceforth.

**Comment by SumiranAgg** [comment]
Closing the issue since fix has been deployed. Please feel free to reopen if required.
