### ISSUE TITLE
JUnit XML reports not getting published in CI builds when a test fails

### ISSUE THREAD

**Issue by brcrista** [Microsoft/vsts-tasks#7758]
See, for example, [this build](https://mseng.visualstudio.com/VSOnline/_build/results?buildId=6709304&view=logs).

I think we need to mark the test steps as "continue on error" now so we still publish on failures.

**Comment by brcrista** [comment]
@nigurr @stephenmichaelf

**Comment by stephenmichaelf** [comment]
Thanks Brian. @nigurr Could you take a look?

**Comment by dpksinghal** [comment]
@brcrista => there was an issue in the publish test results task and it is fixed now. Are you still seeing the issue? Please re-activate this if that is the case. 
https://github.com/Microsoft/vsts-agent/pull/1736

**Comment by brcrista** [comment]
Thanks -- looks fixed.
