### ISSUE TITLE
Display Code Coverage

### ISSUE THREAD

**Issue by binoperez** [Microsoft/vsts-tasks#7760]
Hello is there a way to display or render the code coverage file instead of just having a download link and opening the coverage file manually in Visual Studio? 

![image](https://user-images.githubusercontent.com/25294018/42844609-227d7cbe-89d9-11e8-93ca-1597a05aff70.png)

**Comment by nigurr** [comment]
Please refer this thread: https://github.com/Microsoft/vsts-tasks/issues/7703

Currently we don't have support for this. We are actively working on this feature to enable this experience.
However we don't have specific timelines to share at this moment.
