### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by RichardWangCN** [Microsoft/vsts-tasks#7761]
Hi,
We are using TFS 2017 and want to add Jenkins as service endpoint.
I got connection failed, error screenshot as follow:
Could anyone please give me some advices for this issue? 
Thanks. 

## Environment
- Server - VSTS or TFS on-premises?
      - If using TFS on-premises, provide the version: Version 15.117.27414.0

### Error logs
Failed to query service endpoint api: https://jaas.xxx:44439/api/json?tree=jobs[name,displayName]. Error Message: The request was aborted: Could not create SSL/TLS secure channel.. 
Note: Verification may fail if the URL is not accessible from Team Foundation Server. However it might still be valid and accessible from the agent that executes Build/Release. 

![jenkins](https://user-images.githubusercontent.com/41352971/42868722-9b13c120-8aa5-11e8-97f8-f921552575cf.jpg)

Richard

**Comment by GitHubSriramB** [comment]
@RichardWangCN - this is not the right place to raise issues related to Jenkins endpoints. Please report this issue in https://developercommunity.visualstudio.com/spaces/21/index.html
