### ISSUE TITLE
Unified Agent Pool

### ISSUE THREAD

**Issue by IbrahimUmar** [Microsoft/vsts-tasks#7770]
Hi Guys
                  I want to ask:

What is the installation requirement for Unified Agent Machine?

Does it need Visual Studio to compile the code or not. Visual Studio Test V2 required the machine where VS installed or not?

**Comment by bryanmacfarlane** [comment]
Covered here:

http://chamindac.blogspot.com/2017/12/running-ui-tests-with-unified-agent.html

reactivate if needed.
