### ISSUE TITLE
Update Service Fabric Manifests cannot find ServiceManifest.xml file

### ISSUE THREAD

**Issue by whozDougie** [Microsoft/vsts-tasks#7782]
## Environment
- Server - VSTS
- Agent - Hosted VS2017
- Service Fabric Service Project is using Microsoft.VisualStudio.Azure.Fabric.MSBuild 1.6.6 NuGet package
- On .net framework 4.7.1

## Issue Description
I am trying to build, package and deploy in a service fabric application, and have started with the "Azure Service Fabric Deployment" template and added a few other tasks/dependencies for our solution (as a test) to get the whole solution compiling and building.

I've tested packaging the service fabric application on a local computer using Visual Studio 2017 as well as via MSBuild in the command line. The packages would be created correctly with all files created as expected (Including the ServiceManifest.xml file in the correct path).

**The issue is the "Update Service Fabric Manifest" task in the VSTS Build Definition for the service application is complaining about not being able to find the ServiceManifest.xml file:**

> 2018-07-19T09:28:31.4619434Z ##[error]Cannot find path 'D:\a\3\a\applicationpackage\xxxxxx.xxxxxx.FabricServicePkg\ServiceManifest.xml' because it does not exist.

I'm have tried all sorts of things including changing version of the Fabric MSBuild, checking if the local MS Build parameters for packaging the service fabric package works, but with no luck. If anyone can give a hint of some sort that would be most appreciated!  

[Include task name(s), screenshots and any other relevant details]
The configuration used for the Update Service Fabric Manifest task:
![image](https://user-images.githubusercontent.com/11555622/42938145-9bd9e176-8b94-11e8-832a-2f4840f82204.png)

 

### Error logs
![image](https://user-images.githubusercontent.com/11555622/42937864-acad44a8-8b93-11e8-9aa1-73b2c5a03add.png)

**Comment by hiyadav** [comment]
@whozDougie I noticed that there is a "Delete files" task in the BD before Update Service Manifest task. Are you sure, if that task is not deleting the ServiceManifest file ?
You can see if the generated build artifacts contain the ServiceManifest file.
You can do this two ways
1. If the Agent is private you can go and access the artifacts directly.
2. If you are using hosted agent, you would need the BD to succeed. To do that you can temporarily disable all tasks after "delete files" task except publish artifacts task and then download and explore the generated Artifacts. (precautionarily you can disable any Release Triggers related to this BD)

**Comment by whozDougie** [comment]
@hiyadav Thanks for responding. 

I don't believe it is deleting the ServiceManifest file as the parameters specify for it to delete **\*.pdb files (as per the template).
![image](https://user-images.githubusercontent.com/11555622/43078055-a058e02c-8ecc-11e8-9e42-288e976a0c6f.png)

In case you were wondering, the copy files task copies **\*.pdb files, and it isn't able to find any either:
![image](https://user-images.githubusercontent.com/11555622/43078136-e599223c-8ecc-11e8-8164-191fabd56ced.png)

**Comment by hiyadav** [comment]
It seems that .sfproj is not able to package the application properly. 
@NCarlsonMSFT  can you help here ?

**Comment by NCarlsonMSFT** [comment]
Could you add the flag /verbosity:diag to your package step? That will give more information about why the package task is behaving the way it is.

Another thing that may be useful for diagnostics would be to upload your output folder as an artifact after the solution build, but before the package. That would check fi something strange is happening on the initial build.

Lastly does your solution use any projects whose build architecture is not x64? That sometimes causes issues. If possible, build all of your projects as x64. If not, ensure that the default architecture of your projects is the architecture you want built.

**Comment by whozDougie** [comment]
I will give that last point a shot. Will try to compile everything in x64. At the moment, the dependencies are compiling with "Any CPU".

Will post shortly - appreciate your help on this.

**Comment by whozDougie** [comment]
Hi @NCarlsonMSFT ,

Thanks for giving us those hints. Here are the results of the attempt:
1. Added /verbosity:diag to the package step and have attached the log.
[Packagelog.txt](https://github.com/Microsoft/vsts-tasks/files/2231591/Packagelog.txt)
2. Configured uploading the output of the build, checked the artifacts and can confirm all binaries were built correctly.
3. Ran a Build with the DB on VS Host 2017 in x64, and it appears it has made no difference to the Packaging task output: it only packaged the ApplicationManifest.xml file.

Hope this will help in the investigation.

Thanks. In parallel, we are testing with a brand new Service Fabric solution. Will let you know how we go with that.

Kinds Regards,
Doug

**Comment by NCarlsonMSFT** [comment]
Looking at your log it seems like your project does not reference any services (line 1621):
2018-07-26T00:42:48.2860543Z Target "GetServiceProjectReferences" skipped, due to false condition; ( '@(ProjectReference)' != '' ) was evaluated as ( '' != '' ).

Where are you expecting the service manifests to come from?

**Comment by whozDougie** [comment]
The project is actually defined in the sfproj file.

  <ItemGroup>
    <ProjectReference Include="$(SolutionDir)\******.******.FabricService\******.******.FabricService.csproj" />
  </ItemGroup>

Is that build parameter meant to be defined somewhere in the build tasks?

**Comment by NCarlsonMSFT** [comment]
Looking at your project file, I can't think of why it would not have any references to your ProjectReference in the log. Are you absolutely sure the project in the comment is the one being built? We've run into issues in the past where after upgrade the old project got added in a backup folder and that was accidentally built instead of the true project.

One other thing to try would be to add an extra build task using the /pp:<file name> flag. This will run the preprocessor on the project and generate the full msbuild file that would be builf and save it to <file name>. Looking at that file may explain why the ProjectReference is not being honored.

**Comment by dikhakha** [comment]
@whozDougie did you get a chance to try out what @NCarlsonMSFT suggested above ?

**Comment by dikhakha** [comment]
@whozDougie are you still facing this issue ?

**Comment by ranganathg** [comment]
@whozDougie - I am closing the issue. Feel free to re-open if you need more help.

**Comment by rgovardhms** [comment]
@whozDougie - I am closing the issue. Feel free to re-open if you need more help.
