### ISSUE TITLE
Azure File Copy: Specifying a target folder does not work as expected

### ISSUE THREAD

**Issue by NenoLoje** [Microsoft/vsts-tasks#7786]
Environment:
- VSTS
- Azure File Copy task v2 (preview)

### The Problem
I want to copy a file to an **Azure Blob storage**, into a **subfolder**.

### What I tried
When adding the folder name into the **Container Name** parameter like this: `Container/Foldername`, that does indeed seem to work - however, it changes Foldername to all lower case.

This is a problem as Azure blog storage is case sensitive - so I ended up with a new folder with different casing than the intended one.

### Expected
- Either some other way to specify the target folder,
- The **Container Name** parameter should not be changed to all lower case. (While this actually is expected for container names, it's not appropriate for folder names).

Any other ideas on how to specify the blob target folder?

**Comment by rajatagrawal-dev** [comment]
@NenoLoje In the Contianer Name parameter, specify only the container name like this: `Container`.
Just after Container Name, there is another parameter called Blob Prefix. Specify your folder names in that parameter like this: `Foldername1/Foldername2`.

We have updated the help string for these inputs which will give similar explanation as above. It will be available in the upcoming patches to the task.

**Comment by NenoLoje** [comment]
Awesome - thanks exactly what I was looking for. It's a bit weird having to look for **Blob Prefix** to enter the folder name, but it works as expected!

Thanks, @rajatagrawal-dev

**Comment by NenoLoje** [comment]
@rajatagrawal-dev While this approach seems to work well for named Blob containers, it does not seem to work great in combination with `$root` as the container name. **Any idea how to workaround this?**

The AzCopy error from the log shows that the path looks like:

> https://<azure-storage-account>.blob.core.windows.net//Foldername

Note the two forward slashes (`//`).

**Comment by rajatagrawal-dev** [comment]
@NenoLoje $root container cannot contain folders inside it. This is by design from Azure.

**Comment by NenoLoje** [comment]
That explains it. Thanks, @rajatagrawal-dev !
