### ISSUE TITLE
AzureFileCopyV2: Access is denied

### ISSUE THREAD

**Issue by AlbertQM** [Microsoft/vsts-tasks#7789]
## Environment
VSTS
Agent: HostedVS2017
Azure VM (Windows 10) is running inside a DevTest Lab.
    
## Issue Description
I'm trying to copy some files to a VM hosted on Azure.
The first part of the task (copying files to a blob) works perfectly:

```
2018-07-19T14:24:53.0383831Z Total files transferred: 1
2018-07-19T14:24:53.0384118Z Transfer successfully:   1
2018-07-19T14:24:53.0384551Z Transfer skipped:        0
2018-07-19T14:24:53.0384961Z Transfer failed:         0
2018-07-19T14:24:53.0385234Z Elapsed time:            00.00:00:03
2018-07-19T14:24:53.0502992Z Uploaded files successfully from source path: 'path' to storage account: 'account' in container: 'container' with blob prefix: ''

```

The AzureFileCopyV2 task returns this error:

```
2018-07-19T14:24:56.3425319Z [Azure Call]Getting the custom script extension 'WinRMCustomScriptExtension' for vm 'xxx'
2018-07-19T14:24:57.1837818Z [Azure Call]Got the custom script extension 'WinRMCustomScriptExtension' for vm 'xxx'
2018-07-19T14:24:57.1935748Z [Azure Call]Getting the status for vm 'xxx'
2018-07-19T14:24:57.7473337Z [Azure Call]Got the status for vm 'xxx'
2018-07-19T14:24:59.5153887Z Copy started for machine: 'xxx.uksouth.cloudapp.azure.com:5986'
2018-07-19T14:26:35.0040439Z ##[error]The remote session query failed for xxx.uksouth.cloudapp.azure.com with the following error message: Access is denied.

```

I've been trying to solve this issue for quite a while, here's what I've done:

- Added an inbound security net rule to open port 5986 via Azure dashboard on the appropriate NSG.

- Configured Winrm on the VM 'xxx' by running `winrm qc` which now returns:

```

WinRM service is already running on this machine.
WinRM is already set up for remote management on this computer.

```

- Enabled PSRemoting (`Enable-PSRemoting –force`)

- Set trusted hosts (`Set-Item WSMan:localhost\client\trustedhosts -value` and `winrm set winrm/config/client '@{TrustedHosts=""}'`)

- Added a listener (`winrm create winrm/config/Listener?Address=*+Transport=HTTPS '@{Hostname="xxx.uksouth.cloudapp.azure.com";CertificateThumbprint="thumbprint"}'`
) making sure I have the right certificate/thumbprint.

To double check, `WinRM e winrm/config/listener`:

```
Listener
    Address = *
    Transport = HTTPS
    Port = 5986
    Hostname = xxx.uksouth.cloudapp.azure.com
    Enabled = true
    URLPrefix = wsman
    CertificateThumbprint = thumbprint
    ListeningOn =

```

- Set connection to public (`Set-NetConnectionProfile -InterfaceAlias Ethernet -NetworkCategory Public`)

- tried using `domain\user` or `user` for the credentials

- Created a firewall rule (`New-NetFirewallRule -Name "WinRM HTTPS" -DisplayName "WinRM HTTPS" -Enabled True -Profile "Any" -Action "Allow" -Direction "Inbound" -LocalPort 5986 -Protocol "TCP" `)

- Added administrator to `Remote Management Users`, `Remote Desktop Users` groups

- Created a new account and assigned to the above groups (And also `Administrators`) and tried using these credentials

- From `Local Group Policy Editor > Configuration\Administrative Templates\Windows Components\Windows Remote Management (WinRM)\WinRM Service`, allowed Remote Server Management, added TrustedHosts and IP filters.

- Gave the right permissions to the accounts using:
`Set-PSSessionConfiguration -Name Microsoft.PowerShell -showSecurityDescriptorUI`

- Set up a Windows 7 x64 Enterprise edition VM; same result: Access is denied.

And perhaps more that I can't think of at the moment.

This might help:
If I try running this

```

$cimSessionOption = New-CimSessionOption -Protocol Wsman; $cimSessionOption.CertCACheck = $false; $cimSessionOption.UseSsl = $true
$PlainPassword = “”
$securePassword = ConvertTo-SecureString $PlainPassword -AsPlainText -Force
$cred = New-Object System.Management.Automation.PSCredential(‘user’, $securePassword)
$cimSession = New-CimSession -ComputerName xxx.uksouth.cloudapp.azure.com -SessionOption $cimSessionOption -Credential $cred -Port 5986

```
I get:

```

New-CimSession : Access is denied.
At line:5 char:15
+ ... imSession = New-CimSession -ComputerName xxx.uksouth.cloud ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [New-CimSession], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070005,Microsoft.Management.Infrastructure.CimCmdlets.NewCimSessionCommand
    + PSComputerName        : xxx.uksouth.cloudapp.azure.com

```

**Comment by AlbertQM** [comment]
I've finally found the problem.

I was generating the VMs password by using 1password generator.
Apparently, Windows 7 can't take an overly complicated password. I would be able to create the VM via Azure but it wouldn't let me RDP (Getting a credentials error, tried a couple of times with different auto-generated passwords). 

With the same auto-generated passwords, Windows 10 would let me RDP. However, the same password was giving that "Access is denied" when used from AzureFileCopyV2 task.

**Comment by rajatagrawal-dev** [comment]
@AlbertQM Can you share one of the sample passwords for which the AzureFileCopyV2 task is giving you an error? We'll try and fix it.

**Comment by rajatagrawal-dev** [comment]
@AlbertQM Just to clarify, is your task still failing or the "Access is denied" error was only on Windows 7?

**Comment by AlbertQM** [comment]
To make everything more clear:

I'm using AzureFileCopy to copy files to a Windows 10 machine.

The Windows 7 machine was created just to see if this 'Access is denied' problem was OS related; I was checking this by simply trying to establish a Cim-Session rather than using the Windows 7 machine in the VSTS pipeline.


To answer your question, an auto-generated password would look like:

`fF}uBiLKwZjeAg.BJNb=PY+jNAviji[8ABj`

With this password, only Windows 7 was having troubles. I could create a VM on Azure but when trying to connect via RDP it fired a credential error. (This issue is totally unrelated to the VSTS task)

Regarding the task and the `Access is denied`, I was trying to copy files to a Windows 10 machine.
I set up a variable `password` in the pipeline and then I was using `(ConvertTo-SecureString -String '$(password)' -AsPlainText -Force)` in the AzureFileCopy task to invoke it, without any luck.

**Comment by rajatagrawal-dev** [comment]
@AlbertQM I did not completely understand your scenario. Where exactly are you using the command `(ConvertTo-SecureString -String '$(password)' -AsPlainText -Force)` in the AzureFileCopy task?
You only need to specify `$(password)` in the password field.
