### ISSUE TITLE
Docker push VSTS task always try to push latest tag even if 'include latest tag' is unchecked

### ISSUE THREAD

**Issue by timmydo** [Microsoft/vsts-tasks#7791]
## Environment
- Server - VSTS: https://microsoft.visualstudio.com/Universal%20Store/_build/index?buildId=10935317&_a=summary
    

- Agent - Hosted or Private: 
    
    - Linux hosted agent. Seems to happen regardless of agent.

## Issue Description

Yaml for build def:

```
queue:
  name: Hosted Linux Preview
  condition: succeededOrFailed()
[snip]
- bash: . 'docker/linux/run-tests.sh' 
  displayName: Run tests

- bash: . 'docker/linux/build-images.sh' 'linux-$(Build.BuildNumber)' 
  displayName: Build images

- task: Docker@0
  displayName: Push images
  inputs:
    azureSubscription: 'snip'
    azureContainerRegistry: 'snip'
    action: 'Push images'
    imageNamesPath: 'docker/linux/image-names.txt'
    additionalImageTags: |
     linux-$(Build.BuildNumber)
     linux-latest
```

"Include latest tag" is *unchecked*

### Error logs

```
2018-07-19T17:20:13.6543232Z [command]/usr/local/bin/docker push [snip]/platform:latest
2018-07-19T17:20:13.6701637Z The push refers to repository [snip]
2018-07-19T17:20:13.9567195Z tag does not exist: snip/platform:latest
2018-07-19T17:20:13.9726380Z ##[error]tag does not exist: snip/platform:latest
2018-07-19T17:20:13.9794050Z ##[error]/usr/local/bin/docker failed with return code: 1
```

**Comment by timmydo** [comment]
ok, I might be misunderstanding how this is supposed to work. I don't have a tag in the image names file because the tags are generated at build time. So if it is trying to push the image names from my text file, then it's using the latest tag by default and causing this error?

**Comment by vithati** [comment]
@timmydo, Yes, this is due to image names sepcified without tag in file.  if image names in files are not specified with tags then docker task will push latest tag image along with additional tag images.

**Comment by timmydo** [comment]
In that case maybe you could not push the default tag from the image file when I have 'include latest tag' unchecked? It is slightly confusing

**Comment by andreacassioli** [comment]
I agree with @timmydo : the `include latest tag` behaviour it's pretty unusual to me. I do not see a reason why latest should be pushed if no tags are in the tag file. Why not just push tags from the file and the additional list, and if both are empty then just either fail or silently push no tag at all?

**Comment by bansalaseem** [comment]
Closing this issue as the fix is merged into latest code.

**Comment by youfoundkris** [comment]
Is this also fixed for the docker-compose tasks of build/push?

**Comment by vithati** [comment]
@youfoundkris, In docker-compose task, we fixed includeLatestTag issue https://github.com/Microsoft/azure-pipelines-tasks/pull/8458. If you want to push latest tag image along with other tagged image, enable includeLatestTag checkbox.

**Comment by youfoundkris** [comment]
@vithati When I uncheck the includeLatestTag checkbox, there is still an image pushed with the tag latest. I probably misunderstand the feature.

Can you explain it?

**Comment by youfoundkris** [comment]
@vithati thanks for explaining!
