### ISSUE TITLE
Helm installer fails to get latest info from github

### ISSUE THREAD

**Issue by vcorr** [Microsoft/vsts-tasks#7794]
## Environment
- Server - VSTS
- Agent - Private (linux) 

## Issue Description
Helm tool installer (Preview)

### Error logs
Cannot get the latest Helm info from https://api.github.com/repos/kubernetes/helm/releases/latest. Error Error: Failed to download file status code: 301. Using default Helm version v2.8.2.

This results in using whatever old helm version may be available. If the check mark "check for latest" is removed, then the installer does find latest (2.9.1) version just fine.

This problem to appear started yesterday without any changes in the build pipeline.

**Comment by mathieu-benoit** [comment]
FYI @vithati @Anumita @vcorr, I just submitted this PR #7859 to fix that.

**Comment by bansalaseem** [comment]
@mathieu-benoit can you please complete your PR?

**Comment by mathieu-benoit** [comment]
@bansalaseem , I'm not able to do that by myself, I don't have access to this action.

**Comment by vithati** [comment]
@mathieu-benoit, i will push the changes.
