### ISSUE TITLE
Visual Studio test Task in agent phase not distributing test. Executing on same agent again and again. TFS2018

### ISSUE THREAD

**Issue by IbrahimUmar** [Microsoft/vsts-tasks#7800]
Hi Guys
           I have tfs 2018: I want to run My 10 thousand tests on 5 agents distributedly/Parallel:

What i have done:

Created a release definition where in Agent phase , Selected EXECUTE ON MULTIPLE AGENTS and given 5 Agents as MAXIMUM Number of agents.
Then created a Visual Studio test V2 and Selected RUN TESTS IN PARALLEL ON MULTICORE MACHINE.

When i release the definition , It Created 5 tabs:

Agent 1 of 5
Agent 2 of 5
Agent 3 of 5
Agent 4 of 5
Agent 5 of 5

What the system is doing:
It is using a single agent (Agent machine) and Executing all tests on the single machine in five phases one by one.

Question:

Why the tests are not distributing and executing on 5 different agents even they are online and selected.
Why it is executing with single agent and replicating all tests? and dicing this replication into 5 phases. in all five phases , same agent is being used.

Kindly help me where i am wrong.

**Comment by nigurr** [comment]
@IbrahimUmar 
Can you please share your Release configuration (screenshots) and can you please let us know how many agents are active when the release is started.

**Comment by nigurr** [comment]
Closing this issue as there's not enough information. Please feel free to re-open/reach us in case of any issues
