### ISSUE TITLE
all the tests run but no results getting published under test tab

### ISSUE THREAD

**Issue by malikmahak91** [Microsoft/vsts-tasks#7806]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
 VSTS

- Agent - Hosted or Private: 
    
    - If using Hosted agent, provide agent queue name:Agent: Hosted VS2017 2

## Issue Description
The test gets canceled because it keeps on running for 60 minutes although all the test have been executed.
![image](https://user-images.githubusercontent.com/33269089/43075651-5e26af54-8e4f-11e8-80d7-6c479bcf5ea3.png)

### Error logs
018-07-20T18:54:25.9636593Z Results File: D:\a\1\s\TestResults\VssAdministrator_factoryvm-az244_2018-07-20_18_49_55.trx
2018-07-20T18:54:25.9661696Z Total tests: 89. Passed: 84. Failed: 5. Skipped: 0.
2018-07-20T18:54:25.9667441Z Test Run Failed.
2018-07-20T18:54:25.9673664Z Test execution time: 5.2243 Minutes
2018-07-20T19:33:26.3432652Z ##[error]The operation was canceled.

**Comment by brcrista** [comment]
Possibly related to #7727

**Comment by nigurr** [comment]
Can you please check if there are any background processes are being spawn up in test code? Similar issue: https://github.com/Microsoft/vsts-task-lib/issues/389

**Comment by acesiddhu** [comment]
@malikmahak91 closing the issue. please reopen if you are still facing the issue
