### ISSUE TITLE
Correct way to authenticate a VSTS poweshell task

### ISSUE THREAD

**Issue by phatcher** [Microsoft/vsts-tasks#7808]
I'm writing a task that uses Invoke-AzureRmResourceAction however, when run I get an error message 
`Invoke-AzureRmResourceAction : Run Login-AzureRmAccount to login`

What's the correct way to get an authentication token so that I can invoke this?

**Comment by rylewell-msft** [comment]
Instead of using the PowerShell task, use the Azure PowerShell task, which injects the needed credentials into the current PowerShell session before running your script

**Comment by rajatagrawal-dev** [comment]
If you are writing a task, the best way to authenticate to Azure Resource Manager (ARM) will be to give an input in the task to select an ARM endpoint. Please see our [Azure Powershell task](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/AzurePowerShellV3/task.json#L59) to see how we are doing it.

**Comment by phatcher** [comment]
@rajatagrawal-dev  Thanks I'll give it a go

**Comment by rajatagrawal-dev** [comment]
Closing this. Please reopen or create new for further questions.

**Comment by MuhammadBilalYar** [comment]
I am using Azure PowerShell (v5) but still facing **Run Login-AzureRmAccount to login.** error

Here are my configurations
![image](https://user-images.githubusercontent.com/24404964/147050452-9ef4bb6d-8144-41b6-a65f-b02cbc2d28d8.png)
