### ISSUE TITLE
vsts docker run command drops double quotes

### ISSUE THREAD

**Issue by andreacassioli** [Microsoft/vsts-tasks#7810]
## Environment
- VSTS
    
- Agent - Hosted or Private: 
    Hosted - Linux

## Issue Description

I am using docker run task to execute a one liner script in a container just build in the pipeline. The iea is to execute:

``
docker run -t  my-container sh -c "ls *.Test/*.csproj | xargs -L1 dotnet test -c Release --logger:trx -r ../../test_out"
``

So I set up a docker run task and pass `sh -c "ls *.Test/*.csproj | xargs -L1 dotnet test -c Release --logger:trx -r ../../test_out"` in the field `Command`.

To my surprise, the double quotes disappear and there fore the actual command executed by the agent is (from the task output)

``
docker run -t  my-container sh -c ls *.Test/*.csproj | xargs -L1 dotnet test -c Release --logger:trx -r ../../test_out
``

This can not work: the pipe breaks the command in bash and indeed I get an error.
I have also tried to:
- use double-double quotes, i.e. `""`, no way
- escape quotes, i.e. `\"`, but it seems to only work at the end of the command
- surround the command with single quote as well but no way again

Is the command string somehow processed?

**Comment by vithati** [comment]
@andreacassioli, In task logs it is not showing quotes but if you specify sh -c "ls *.Test/*.csproj | xargs -L1 dotnet test -c Release --logger:trx -r ../../test_out" in docker task run 'command' input, it executes "ls *.Test/*.csproj | xargs -L1 dotnet test -c Release --logger:trx -r ../../test_out" command in docker container even quotes not visible in logs. Can you share task log?

**Comment by andreacassioli** [comment]
I had to find a workaround in the meantime, so I have to setup a new pipeline to reproduce the issue. But the output  log is what I pasted in the first message.

BTW: if the log does not show exactly what is executed, including quotes, then it is clearly at least a bug in the log!

**Comment by vithati** [comment]
I see only for linux agent logs quotes are not visible. Windows agent printing logs with quotes. I will check why quotes not showing in linux agent logs.  As i said in my previous comment, logs not showing quotes but command sh -c "ls .Test/.csproj | xargs -L1 dotnet test -c Release --logger:trx -r ../../test_out" executes in docker container and it should not fail due to quotes issue.  Can you try docker run task and share the log, if it fails.

**Comment by vithati** [comment]
Task logging comes from vsts-task-lib file.  I have opened bug https://github.com/Microsoft/vsts-task-lib/issues/383 . Closing this bug.
