### ISSUE TITLE
VsTest > VSO - Published result test count is incorrect- not matching with log file count

### ISSUE THREAD

**Issue by iPiyushPatel** [Microsoft/vsts-tasks#7815]
## Description
While running Unit Tests on VM using VsTest build step (screenshot below), published total test run count is different than what is show in log file (which is correct, screenshot below). 

![image](https://user-images.githubusercontent.com/5212585/43114736-0ae2298e-8f1e-11e8-8aba-830edbb891a7.png)

![build_log](https://user-images.githubusercontent.com/5212585/43114748-1aab8ebe-8f1e-11e8-8a19-708c369030c1.png)

## Steps to reproduce
I'm using VsTest V2. 

## Expected behavior
It should publish correct test run count. in this case, it should say 120.

## Actual behavior
Test run count is incorrect, it says 109

## Environment
VsTest V2

Let me know if any other info required.

**Comment by iPiyushPatel** [comment]
In fact, I've figured out the issue. Let me explain. In our solution, we publish Test Logs back to VSO (code snippet below ). I noticed that if log file name is > 70+ (approx) then it doesn't export all results to VSO correctly. 

![image](https://user-images.githubusercontent.com/5212585/43373735-408d10b2-93c9-11e8-9514-bd9f20fad63f.png)

Now,I've restricted log file name size to max 70 and everything looks as expected.

Is this the known issue ? Please advice.

**Comment by dpksinghal** [comment]
@pagangil to take a look.

**Comment by pagangil** [comment]
@iPiyushPatel Is it possible for you to share the trx file you're trying to publish. 
Also where is the code which you've posted from (`TestContext.AddResultFile(Log.LogPath`) and what it is trying to do?

**Comment by iPiyushPatel** [comment]
Hey @pagangil - 
I don't have trx file which as this issue got resolve when I limited log file name to <70 chars.  Regarding code : 
TestContext.AddResultFile(Log.LogPath);

Here - Log.Logpath = log file path. [Official link.](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.testtools.unittesting.testcontext.addresultfile.aspx)

To Replicate locally:

        `[TestMethod]
        public void LogFileIssue()
        {

            TestContext.AddResultFile("valid log filename > 70 chars");
           
        }`

Run this test via VSO > Build. It will pass ;however, no log files will be attached to tests as it's size > 70 chars. 

This is the best idea I've regarding bug. Let me know if I can still provide more info.

Thanks,

**Comment by pagangil** [comment]
@iPiyushPatel I tried to reproduce this issue on my end. I had a large name for the log file (> 70 characters) and a deep folder hierarchy too but I'm seeing the correct number of results being published.

Can you please provide the following details for me to debug this issue further?
- Server (VSTS or TFS on-premise): 
- Agent (Hosted or private): 
- Agent version: 
- VsTest task version used:
- The trx file if possible (it will be available as attachments in Test run):
If providing trx file is not possible, can you please confirm if the trx file contains correct amount of test results? This way we'll get to know if the bug is in creation of trx file or while publishing test results after reading the trx file.

**Comment by iPiyushPatel** [comment]
Hey @pagangil , 

Thanks for looking into it.

Here are my answers : 

1. VSTS - oh no - Azure DevOps :)
2. Private
3. Agent Details : 
![image](https://user-images.githubusercontent.com/5212585/45660340-d8c07900-bb15-11e8-9e8d-a9237dcfd093.png)
4. 2.* : 
![image](https://user-images.githubusercontent.com/5212585/45660367-fd1c5580-bb15-11e8-949e-e95cc0f2a659.png)
5. No it wasn't containing all results. Trx had also less number of results.

Thanks,

**Comment by pagangil** [comment]
@iPiyushPatel I tried on the newer version of agent and the bug wasn't reproducing there. Few things:
1. I guess you already checked that the complete file path was not exceeding windows file path limit of 260 characters.
2. Can you please try upgrading your agent or use a hosted agent. I haven't tried this issue on the older version but it works fine on the newer version of the agent.
- I guess you already have a workaround of limiting the number of characters.

Thanks

**Comment by iPiyushPatel** [comment]
Thanks @pagangil for looking into it. 
1. That's unlikely that it was exceeding 260 char limit.
2. I've updated agents but will test again with removing condition to limit chars.

Thanks again for investigating.

**Comment by abhishkk** [comment]
@iPiyushPatel Is this issue resolved?

**Comment by abhishkk** [comment]
@iPiyushPatel Closing the issue. Please re-open in case issue is not resolved.
