### ISSUE TITLE
Cloud-based Apache JMeter Load Test from build task

### ISSUE THREAD

**Issue by SreenivasReddyS** [Microsoft/vsts-tasks#7827]
we are running load test from VSTS build using Cloud-based Apache JMeter Load Test, but here for duration i can able to select value upto 300 sec only, i want to run test for 15mins. is that possible?

**Comment by SreenivasReddyS** [comment]
Could you please confirm, is this fix will be for my subscription/project only or is that for others also?

**Comment by cltshivash** [comment]
This will be applicable for all VSTS accounts

**Comment by kovaliovsg** [comment]
Hello, what is the maximum supported amount of JMeter Agents in VSTS ? In the task I can choose between 1 and 5, but if I customize the task I can specify even more. My question what is the maximum number I can specify ?

**Comment by cltshivash** [comment]
We support upto 25 agents per run and 50 concurrent agents per account.
