### ISSUE TITLE
Cannot get vsts test case id, parameters, or test configuration from test context for an automated test

### ISSUE THREAD

**Issue by davoodharun** [Microsoft/vsts-tasks#7829]
## Issue Description
I've successfully set up automated testing by associating VSTS test cases with Visual Studio NUnit tests using this method: https://docs.microsoft.com/en-us/vsts/test/associate-automated-test-with-test-case?view=vsts

I want to be able pass test case parameters from the VSTS test case to the Visual Studio test. The only way I am to do this is by hard coding the VSTS test case ID within my Visual Studio test so I can use the VSTS REST API to get the parameters of a specific test case. This is not ideal. Is there work being done to include the vsts test case id, parameters, or even test configuration for a Visual Studio test with associated VSTS automation? This is very problematic when trying to associate multiple VSTS test cases (with different parameters) to one Visual Studio test.

**Comment by acesiddhu** [comment]
@davoodharun Associating Nunit test are not supported. See the from the link which you added in your question.

"NOTE: At present you cannot use this procedure to associate MSTest V2 tests or tests written in **NUnit** and XUnit. Adding this capability is planned for a future release. "

**Comment by acesiddhu** [comment]
@davoodharun I am closing the issue. this is not a supported scenario today/

**Comment by davoodharun** [comment]
@acesiddhu thanks for your response. If you use MSTest V2 will you be able to grab VSTS test case id, parameters, configuration from the associated test? Although NUnit is not supported, I am still able to associate NUnit tests to VSTS and run them directly from VSTS. Is it just that NUnit tests are not fully compatible?

**Comment by acesiddhu** [comment]
@davoodharun mstest will work fine. Prachi has linked a nunit issue because of which these properties r not getting populated in nunit test case.
