### ISSUE TITLE
Azure file copy: clean path before copying

### ISSUE THREAD

**Issue by fleed** [Microsoft/vsts-tasks#7842]
Is there an option to cleanup a specified path on Azure storage blobs before copying new files?

**Comment by rajatagrawal-dev** [comment]
@fleed Azure File Copy uses [AzCopy](https://docs.microsoft.com/en-us/azure/storage/common/storage-use-azcopy) to handle blob upload. There doesn't seem to be any option to delete blobs. 

You can add an Azure Powershell task before your Azure File Copy task and call something like Remove-AzureStorageBlob (see [documentation here](https://docs.microsoft.com/en-us/powershell/module/azure.storage/remove-azurestorageblob?view=azurermps-5.7.0)).

**Comment by fleed** [comment]
Thank you @rajatagrawal-dev . I submitted the idea to the AzCopy team.
