### ISSUE TITLE
Publish Test Results: Clarification on metadata linkage

### ISSUE THREAD

**Issue by tabeth** [Microsoft/vsts-tasks#7852]
## Environment
- Server - VSTS or TFS on-premises?
 **VSTS**
 
- If using VSTS, provide the account name, team project name, build definition name/build number: 
 **I'd rather not publicly make this information available. I can provide through private channel if necessary**

- Agent - Hosted or Private: 
    **Hosted**

- If using Hosted agent, provide agent queue name:
    **Hosted Linux Preview**

## Issue Description
Could more clarification on how metadata is linked from the XML to VSTS be provided? For example, in the below example the `duration` field is populated below (in the XML), yet not in VSTS. In addition, it also seems that a `test-suite` `type` of `Assembly` is needed otherwise things do not function properly. 

Ideally an exhaustive schema on your end could be given that way we can make sure we provide a proper XML file. Though the NUnit3 documentation is linked in the task page, it seems that the way the information is parsed doesn't correspond 100%.

Two specific questions I have are:
1. How is "Failing since" populated? Using a minimal XML like the one shown below could it be explained? Does VSTS simply save the metadata from the results and that date manifests itself in "Failing since"? 

2. Ditto for "Failing build". 

Task Name: **Test: Publish Test Results**

Valid XML (a slight variant of a working example):

```xml
<test-run result="Passed" total="2" passed="2" failed="0" inconclusive="0" skipped="0" asserts="2" engine-version="3.6.1.0" clr-version="4.0.30319.42000" start-time="2017-07-05 13:25:23Z" end-time="2017-07-05 13:25:25Z" duration="61">
  <command-line><![CDATA[nunit3-console.exe  nunit-v2-result-writer.tests.dll]]></command-line>
	<test-suite type="Assembly" id="node - Example Tests" name="Example Tests" fullname="Example Tests" classname="Example Tests" testcasecount="11" runstate="Runnable" result="Passed" label="unspecified" site="unspecified" start-time="2018-07-26 18:30:10Z" end-time="2018-07-26 18:30:10Z" duration="32" total="11" passed="11"  asserts="11">
		<test-case id="0-1" name="Example functions as intended" fullname="Example functions as intended" methodname="undefined" classname="unspecified" runstate="unspecified" seed="null" result="Passed" label="unspecified" site="Test" start-time="2018-07-26 18:30:10Z" end-time="2018-07-26 18:30:10Z" duration="15" asserts="1"/>
    <environment framework-version="3.5.0.0" clr-version="2.0.50727.8784" os-version="Microsoft Windows NT 10.0.15063.0" platform="Win32NT" cwd="C:\NUnit" machine-name="LLATINOV-JG0453" user="LLatinov" user-domain="JUSTGIVING01" culture="en-GB" uiculture="en-US" os-architecture="x64" />
		<settings></settings>
	</test-suite>
</test-run>

```

**Comment by divais** [comment]
Hi,

For "Failing Since" & "Failing Build" properties we look at past execution of that test and update these fields based on that. These fields are not mapped from the XML.

**Comment by tabeth** [comment]
Thansk @divais for the response. Could you also elaborate on how `duration` is populated?

**Comment by pagangil** [comment]
@tabeth The duration for test results is calculated as the difference between `end-time` and `start-time` of the test result.
In the example xml given by you:
`<test-case id="0-1" name="Example functions as intended" fullname="Example functions as intended" methodname="undefined" classname="unspecified" runstate="unspecified" seed="null" result="Passed" label="unspecified" site="Test" start-time="2018-07-26 18:30:10Z" end-time="2018-07-26 18:30:10Z" duration="15" asserts="1"/>`, the duration for the test result will be `2018-07-26 18:30:10Z - 2018-07-26 18:30:10Z` i.e. `0`

**Comment by tabeth** [comment]
Thanks for the reply @pagangil. In other words, it's not necessary to include `duration` yourself, as it is not read (since VSTS calculates the duration itself)?

**Comment by pagangil** [comment]
Yes @tabeth , I hope this clarifies your doubt

**Comment by tabeth** [comment]
It does. Thanks for the answers. I'll go ahead and close this now.
