### ISSUE TITLE
Task PowershellV2 has not arguments field when inline is selected as type

### ISSUE THREAD

**Issue by Tom-Dunstan** [Microsoft/vsts-tasks#7853]

**Comment by JohannesDrexler** [comment]
The scriptblock is checked for variables so you don't need an argumentsfield. You can write
`write-host "$(myMessage)"`
where myMessage is a variable from your build or release

**Comment by JohannesDrexler** [comment]
If your variable is scret you need to map it in the "Environment Variables" section of the task. Lets assume you map the scret variable  $(myMessage) to 'MYMESSAGE' you can then access it like
`$secretvalue = $env:MYMESSAGE`
Note that the variable my get replaced in the console output (which makes sense for secet variables) if you are trying to display it's value.  The script will still use the resolved value

**Comment by bryanmacfarlane** [comment]
I believe @JohannesDrexler is correct.

**Comment by ericsciple** [comment]
Secret variables are masked in the logs as `***`

Here is a document describing working with [secret variables](https://github.com/Microsoft/vsts-agent/blob/31217c9497cc31ba8807cc01408c4a36ffb7c4ad/docs/preview/yamlgettingstarted-secretvariables.md). The first section has examples that illustrate the masking behavior. The second section recommends best practice to map a secret variable into your script.
