### ISSUE TITLE
Assigning empty/null value to VSTS variable

### ISSUE THREAD

**Issue by gbrueckl** [Microsoft/vsts-tasks#7865]
## Troubleshooting
not relevant

## Environment
VSTS
general issue

Hosted Agent

## Issue Description

when setting a VSTS variable via PowerShell and the variable value is $null (maybe also if it is empty/""), the VSTS variable does not get created
In my case this was due to an issue with my PowerShell script but it would have been much easier for me to spot the error if I get a warning that I am trying to assigning a $null/empty to a VSTS variable 

### Error logs
none

**Comment by gbrueckl** [comment]
I am doing this via ##vso echo

**Comment by bryanmacfarlane** [comment]
should probably create this issues in the vsts-agent repo

**Comment by gbrueckl** [comment]
can you move it there?
