### ISSUE TITLE
Ant fail task

### ISSUE THREAD

**Issue by Kasperki** [Microsoft/vsts-tasks#7869]
## Issue Description

When running ant targets which calls Fail Task.
```
<fail message="Something wrong here."/>
```

We get generic error: 
❌Error: /usr/bin/ant failed with return code: 1

Is it possible to get: 
Error: Something wrong here.

## Example
![alt text](https://i.imgur.com/J9ElgmM.png "Example")

**Comment by brcrista** [comment]
That isn't the build log, that's just the build summary.  It's doing the right thing, which is reporting that the `ant` process failed.

Check your build logs.  I would expect the message to be there.

**Comment by Kasperki** [comment]
So this is the expected behavior? I know that I can see the message from build log. But in my opinion I should see the defined message in summary like: Error: /usr/bin/ant failed: Something wrong here.

We have big ant targets with multiple fail conditions. So it would be much more useful to be able to see the fail message in the summary than to crawl through the logs.

We have targets like unit tests, that have the <fail> condition and Continue on Error so we can make Partially succeeded builds. It would be really useful to see our own message saying problem was in unit tests and not somewhere else, because that is most of the case the problem and the build it self is ok,

We also get these errors in the summary mail.
We have people who are not so technical but can deploy new environment for testing, and if they get in mail Error: /usr/bin/ant failed with return code: 1vs Error: /usr/bin/ant failed: Environment Configuration not found. They would know to fix the environment field.

But if it is not doable I understand and you can close this.

**Comment by brcrista** [comment]
Well, think about it -- how would this work, in general?  Consider any failure that Ant could produce.  We could say "anything written to stderr gets reported in the build summary," but that would usually be way too much information -- that's what the logs are for.  We could say "the first line that gets written to stderr gets reported in the build summary."  That may work in this case but I'm not sure it will produce the right information in every case.

I think it's fair feedback, and I would like to see a smart error message here as well.  We have many tasks that essentially prepare arguments and call into command-line tools, and this the way they have all worked for a while.  But I can run it by some people and see what they think.

**Comment by brcrista** [comment]
Thanks for the feedback.  We've added this to our backlog.
