### ISSUE TITLE
Dollar signs ($) not supported during file copy

### ISSUE THREAD

**Issue by alexpilon666** [Microsoft/vsts-tasks#7874]
## Environment
- Server - VSTS or TFS on-premises?
VSTS - sidlee.visualstudio.com
Project Name: SidLee_Kinship
Build Definition Name/number: _SidLee_Kinship-CI #544

- Agent - Hosted or Private: 
    
Hosted: Hosted

## Issue Description

Cannot upload to container containing a dollar sign ($) in it.
This is problematic, because the new Static Website functionality requires content to be in the `$web` container, but VSTS (or the underlying Powershell function used by VSTS) doesn't seem to support this yet.

### Error logs

2018-07-30T14:54:52.6238097Z ##[error]Upload to container: '$web' in storage account: 'kinshipweb' with blob prefix: '' failed with error: 'Azure Storage container names can only contain lowercase alpha-numeric characters or hyphens

**Comment by rajatagrawal-dev** [comment]
@alexpilon666 This support is underway. The deployment for this has already started and should be available to all accounts in the next couple of days. 

Please track #7611 for future updates regarding this.
