### ISSUE TITLE
Misleading help text Azure App Service Deploy

### ISSUE THREAD

**Issue by DeluxZ** [Microsoft/vsts-tasks#7888]
## Environment
- Server: VSTS
- Agent: Hosted

## Issue Description
I was trying to prevent our WebJob from being deleted when we did a deployment of our WebApp. After a quick search on Google I noticed there is a checkbox "Exclude files from the App_Data folder" I had to check. But after reading the help text from the "Exclude files from the App_Data folder" and the help text from the "Remove additional files at destination" I saw a small typo in the text.

The help text from the "Remove additional fiels at destination" says:
`Select the option to delete files on the Azure App Service that have no matching files in the App Service package or folder. Note: This will also remove all files related to any extension installed on this Azure App Service. To prevent this, select 'Exclude files from App_Data folder' checkbox.`

But the help text from the "Exclude files from the App_data folder" says:
`Select the option to prevent files in the App_Data folder from being deployed to the Azure App Service.`
Where "being deployed" should be "being deleted" (?)

**Comment by DeluxZ** [comment]
I can't assign a label but the category of the task is **Deploy**

**Comment by SumiranAgg** [comment]
@DeluxZ Thanks for reporting the issue. We have reviewed your PR. Please address the comments before merging.

**Comment by SumiranAgg** [comment]
@DeluxZ Merged to master. Thanks for contributing. :)
Fix will be rolled out with next deployment. Closing the issue.
