### ISSUE TITLE
Issue in connecting to Azure AAD through power shell task in vso

### ISSUE THREAD

**Issue by Sudheer-Yalamarthi** [Microsoft/vsts-tasks#7950]
**issue**
We want to automate app registration in AAD and include one azure power shell task in vsts. With user credentials  we are able to connect but when we tried to connect with service principle account it is giving invalid user type. 
Is there any another approach to connect to AAD other than user credentials?

**Below is the script we are using to connect.**

$TenantId = "XYS"
$securePassword=ConvertTo-SecureString -String 'password' -AsPlainText -Force
$secureCredential=New-Object System.Management.Automation.PSCredential('serviceprincipename',$securePassword)
Connect-AzureAD -TenantId $TenantId -Credential $secureCredential

**Error Details**

Connect-AzureAD -TenantId $TenantId -Credential $secureCredential
Connect-AzureAD : One or more errors occurred.: unknown_user_type: Unknown User Type
At line:5 char:1
+ Connect-AzureAD -TenantId $TenantId -Credential $secureCredential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-AzureAD], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Connect-AzureAD,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD
 
Connect-AzureAD : One or more errors occurred.
At line:5 char:1
+ Connect-AzureAD -TenantId $TenantId -Credential $secureCredential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-AzureAD], AggregateException
    + FullyQualifiedErrorId : Connect-AzureAD,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD
 
Connect-AzureAD : unknown_user_type: Unknown User Type
At line:5 char:1
+ Connect-AzureAD -TenantId $TenantId -Credential $secureCredential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : AuthenticationError: (:) [Connect-AzureAD], AdalException
    + FullyQualifiedErrorId : Connect-AzureAD,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD
 
Connect-AzureAD : One or more errors occurred.: unknown_user_type: Unknown User Type
At line:5 char:1
+ Connect-AzureAD -TenantId $TenantId -Credential $secureCredential
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-AzureAD], AadAuthenticationFailedException
    + FullyQualifiedErrorId : Microsoft.Open.Azure.AD.CommonLibrary.AadAuthenticationFailedException,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD

**Comment by arjgupta** [comment]
@Sudheer-Yalamarthi , the correct pattern for passing service principal details to the connect-azuread cmdlet is to pass the service principal id as the value of the 'ApplicationId' input. if you do not know the application id you can use the 'Get-AzureRmADServicePrincipal' cmdlet to get the service principal.  You can follow the documentation [here](https://docs.microsoft.com/en-us/powershell/module/azuread/connect-azuread?view=azureadps-2.0) for more info. This is not a task issue. I am closing this. Reopen if you face any issues with the task.
