### ISSUE TITLE
VsTestv2 -> No test assemblies found when using environment variable

### ISSUE THREAD

**Issue by matsovef** [Microsoft/vsts-tasks#7953]
## Environment
TFS on-premises: Version 2018 Update 2
Private agent on Windows Server 2016 and version 2.131.0

## Issue Description
Running Visual Studio Test task, version 2.3.28 using locally vstest.console.exe

In the VsTestv1 version we could use an environment variable to specify the test assemblies to process. In a step prior to VsTest a powershell script set the TestAssemblys environment variable to a string containing comma separated paths to test assemblies and then in the vstest task itself we only input the environment variable as source for 'Test assemblies' .

Now in VsTestv2 it seems like it cannot handle a comma separated list of test assemblies on a single line in the task definition for 'Test assemblies'. We always gets the the following warning:
`2018-08-07T12:05:43.3158857Z ##[warning]No test assemblies found matching the pattern: PRI.Solvency.Business.Tests\bin\Release\PRI.Solvency.Business.Tests.dll,PRI.Solvency.DataAccess.Tests\bin\Release\PRI.Solvency.DataAccess.Tests.dll,PRI.Solvency.Entities.Tests\bin\Release\PRI.Solvency.Entities.Tests.dll,PRI.Solvency.FileAccess.Tests\bin\Release\PRI.Solvency.FileAccess.Tests.dll,PRI.Solvency.Integration.Tests\bin\Release\PRI.Solvency.Integration.Tests.dll,PRI.Solvency.Web.Services.Tests\bin\Release\PRI.Solvency.Web.Services.Tests.dll,PRI.Solvency.Web.UI.Tests\bin\Release\PRI.Solvency.Web.UI.Tests.dll`

If we ourselves write each above test dll into 'Test assemblies' on a separate line then VsTestv2 successfully runs all test assemblies. The drawback with this is that one must update the VsTest task in TFS every time you add another test assembly.
We cannot use matching pattern since there is no way to exclude test assemblies used by other test assemblies.

In the VsTestv2 task why is there no support to specify multiple test assemblies (having no patterns) on a single line where each test assembly is separated by a delimiter like comma?

**Comment by nigurr** [comment]
@matsovef 

You can set multi-line variable as mentioned below and consume in VsTest v2 task
`$tests = "**\*test*.dll%0D%0A!**\*TestAdapter.dll%0D%0A!**\obj\**"

Write-Host "##vso[task.setvariable variable=TestAssemblies;]$tests" 
`

**Comment by nigurr** [comment]
@matsovef closing this issue with above solution. Please feel free to reach us in case if you are still facing issue.
