### ISSUE TITLE
VSTestV2 --> Re-run failed test not working in new version 2.138.11

### ISSUE THREAD

**Issue by somasekhar18** [Microsoft/vsts-tasks#7960]
## Environment
VSTS  Account: msdata
Team Project: Azure Data Factory
Build Definition: Data Factory - Gated, Build No: 20180803.7

- Agent - Private
Agent OSVersion:6.3.9600
Agent.Version 2.124.0

## Issue Description
We have VSTest task in build pipelines that runs E2E tests with "re-run failed test" enabled. The task started failing to initial test execution with rerun option from past 5 days. If we disable the rerun option, the task successfully runs the test. 

The feature works fine in VsTest task with version 2.137.*  But the task has been upgraded in our VSO account which is not in our control.
[VSTest_Log.txt](https://github.com/Microsoft/vsts-tasks/files/2268547/VSTest_Log.txt)

Is this some bug in the new version? Could you please unblock with the issue.

### Error logs

[Insert error from the logs here]
[VSTest_Log.txt](https://github.com/Microsoft/vsts-tasks/files/2268548/VSTest_Log.txt)

**Comment by nigurr** [comment]
We are rolling out the hot fix for the same.
This can be mitigated by adding "Visual Studio Test Platform Installer" task before "VsTest task" and selecting Test platform version as "Installed by Tools installer". We recommend going this route as this gets latest test platform bug fixes/features

**Comment by sailro** [comment]
Same everything is broken after 2.137.8.

Is it possible to instruct the VSTS agent to stick on a specific task version ?

**Comment by nigurr** [comment]
@sailro, we are pushing hotfix. To mitigate, you can change to Custom Batch size in advanced execution options. Extremely sorry for the inconvenience. We will be driving hot fix by tonight

**Comment by nigurr** [comment]
@sailro @somasekhar18 This is fixed and rolled out 4 days ago. Can you please confirm that everything is working fine now?

**Comment by sailro** [comment]
@nigurr yes, seems to work now. Thanks!

**Comment by acesiddhu** [comment]
closing the issue. Thanks @sailro for confirming
