### ISSUE TITLE
Phase condition does not work like task condition

### ISSUE THREAD

**Issue by StefanKoell** [Microsoft/vsts-tasks#7963]
## Environment
VSTS
https://royalapplications.visualstudio.com/Royal%20Applications/_build/results?buildId=192&_a=summary&view=logs
Build 20180808.17    

- Agent - Private: 
Windows Server 2016
Microsoft Windows [Version 10.0.14393]
C:\agent>bin\Agent.Listener.exe --version
2.136.1

## Issue Description
Working with several agent phases in VSTS and trying to use a custom condition on the phase itself to only run when a specific text is in the commit message. For this, I'm using the following condition:
and(succeeded(), contains(variables['build.sourceVersionMessage'], '[win]'))

The phase is always skipped but if I use the same condition on the individual tasks, it's working fine. This seems to be a bug on the phase condition evaluation.

### Error logs
no errors can be found in the logs and no information why the phase has been skipped can be found either

**Comment by bryanmacfarlane** [comment]
Service issue.  Not an issue with with the tasks in this repo.  

Note that some variables are realized JIT agent side.  Phase conditions are evaluated service side before it goes to the agent.

If that doesn't answer your question, you may want to log an issue in vsts-agent repo
