### ISSUE TITLE
PowerShell Task: Inconsistent Behavior

### ISSUE THREAD

**Issue by Midacts** [Microsoft/vsts-tasks#7974]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
- Server - VSTS or TFS on-premises?
**TFS on prem**
    
    - If using TFS on-premises, provide the version: 
    **16.122.27102.1**

- Agent - Hosted or Private: 
**Private**

   - If using private agent, provide the OS of the machine running the agent and the agent version: 
   **Windows 2012 R2**

## Issue Description

I have several TFS 2018 builds that use the **PowerShell task**. This task it calling a Build.ps1 file in our repo.
I am getting inconsistent results meaning if I have BuildAgentX and have a build run, it could throw errors that I do not get if I log in locally on the same build agent with the same service account and run the same build.ps1 file.

Are you guys calling powershell.exe with some specific switches that might be causing these inconsistencies?

**Comment by bryanmacfarlane** [comment]
We call it the same everytime.  Here's the args:

https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/PowerShellV2/powershell.ts#L79

There's no repro here so I'm not sure how to take action.  However, answered the answered how we call powershell so closing.  Reactive if you get details or a repro.
