### ISSUE TITLE
New PowerShell on Target Machines 3 has no option to select a subset of machines

### ISSUE THREAD

**Issue by meastp** [Microsoft/vsts-tasks#7985]
## Issue Description

I tried to migrate to the new PowerShell on Target Machines Task (3.* preview) from #6789

However, I use tags on the virtual machines to run the script on a subset of the VMs. Are tags deprecated? How should I select a subset of machines with this new version?

**Comment by rajatagrawal-dev** [comment]
@meastp Which tags are you referring to? How did you specify tags in PowerShell on Target Machines Task 2.* ?

**Comment by meastp** [comment]
@rajatagrawal-dev Advanced Options -> Select Machines By -> Tags (you can also choose machine names instead of tags) and used Filter Criteria to specifi which tags.

**Comment by arjgupta** [comment]
@meastp , yes the tags input is deprecated. v3 only supports specifying ip's or fqdn's.
