### ISSUE TITLE
Task.UploadSummary causes Test Results panel to change positiion

### ISSUE THREAD

**Issue by varnk** [Microsoft/vsts-tasks#8011]
## Environment
- Server - TFS on-premises
    
    - If using TFS on-premises, provide the version: 14.102.25423.0
    
- Agent - Private: 
    
    - OS = Windows 7.  Agent Version = 1.95.3

## Issue Description

We are using ##vso[task.uploadsummary] to upload custom summary info to our build results Summary page.  The Build Details results page shows the custom markdown file correctly, but the Test Results panel location has moved from the top of the page to the bottom of the page (after Associated Changes).  This is not desirable.  Is there a way that we can upload a markdown file without it causing the Test Results section from changing its position?

**Comment by bryanmacfarlane** [comment]
Not a task issue from this repo.  Please report on developer community
