### ISSUE TITLE
[Deploy to Kubernetes]: kubectl delete -o throws an error unless modified from default settings

### ISSUE THREAD

**Issue by damienwebdev** [Microsoft/vsts-tasks#8053]
## Environment
- Server - VSTS
- Hosted Agent Docker Image running in an AKS cluster

## Issue Description
The default `[Deploy to Kubernetes] v1.*` task breaks when using the `delete` version of the task due to `kubectl delete` not allowing the `-o=json` flag.

You can see the Throw statement k8s [here](https://github.com/kubernetes/kubernetes/blob/64eb015471adb5cd8feebe7941f74f44e2ab67b3/pkg/kubectl/cmd/delete.go#L199) 

### Error logs
```
2018-08-16T17:01:33.4295355Z ##[error]error: Unexpected -o output mode: json. We only support '-o name'.
2018-08-16T17:01:33.4349545Z ##[error]See 'kubectl delete -h' for help and examples.
2018-08-16T17:01:33.4462909Z ##[error]/vsts/agent/_work/_tool/kubectl/1.10.1/x64/kubectl failed with return code: 1
```

### Suggestion
When the user changes to the `kubectl delete` version of the `[Deploy to Kubernetes] v1.*` set the `Output Path` flag to `name` instead of `json`.

**Comment by Anumita** [comment]
Thanks for reporting this issue! We have fixed this issue and should reach you in a few weeks.

**Comment by severisv** [comment]
Is there a workaround for this?

**Comment by Zimmergren** [comment]
Hey @Anumita, do you have an ETA for when this will be rolled out across tenants? 
I've got this exact issue using a brand new incarnation of Azure DevOps and trying to delete and create kube deployments. 

Would be happy to learn more about when it'll be expected to reach us, or if there's any workarounds we can do meanwhile?

Thanks,
Tobias

**Comment by Anumita** [comment]
The fix should reach you in another week or two. Meanwhile as a work around you can change the value of the OutputFormat field in the Advanced Section of the task. By default the value of this field is json , but the field is editable.

**Comment by Zimmergren** [comment]
Thanks @Anumita, confirmed and works!
Cheers 👍

**Comment by ephill** [comment]
I think there was a regression here. Early this morning my k8s delete tasks that were previously working started spitting out `kubectl delete secret foo -o json` commands which of course throw an error because `-o json` is not supported. Previous builds had no output specified for these delete commands. I changed the advanced settings to use `-o name` as suggested above but noted that "name" was not an option in the dropdown though Azure DevOps allowed me to specify it anyway.

**Comment by Anumita** [comment]
Hi @ephill , thanks for the information. There is a regression for delete command as it was removed from the list of commands that don't support -o json/yaml list. Will raise a fix for this and let you know the eta for the fix . Regarding the output format field, the filed is an editable field hence you can add "name" to it.

**Comment by cjbush** [comment]
We also just noticed this when we went to deploy. Thanks for the workaround 😄
