### ISSUE TITLE
Get Sources - Bitbucket Cloud OAuth connection - fatal: could not read Username ...

### ISSUE THREAD

**Issue by seanbriceland** [Microsoft/vsts-tasks#8063]
## Environment
Account Name & URL: https://pointman-hq.visualstudio.com
Build Definition: ALL that use our bitbucket cloud OAuth Service connection
Build Number: All since August 13th @ 2:51 EDT

OS of the machine:
Hosted (WIN) 2.116.0 (multiple builds)
Hosted Linux Preview 2.116.0 (multiple builds)

## Issue Description

Task Name: Get Sources 
Using Bitbucket Cloud OAuth connection, cannot clone any of our repositories for many builds.

Here is the VSTS script that is run to clone the repository:

```bash
git init
git remote add origin https://bitbucket.org//project/srsv3_frontend
git config gc.auto 0
git config --get-all http.https://bitbucket.org//project/repo_name.extraheader
git config --get-all http.proxy

# git command that causes the error:
git -c http.extraheader="AUTHORIZATION: basic ***" fetch --tags --prune --progress --no-recurse-submodules --depth=1 origin
```

### Error logs

```bash
Git fetch failed with exit code 128
fatal: could not read Username for 'https://bitbucket.org': terminal prompts disabled
```

**Comment by lkillgore** [comment]
Hi @seanbriceland, thank you for letting us know about this.  We have a fix rolling out now.  I expect your account will receive the fix soon (probably the next day or two).

I apologize for the inconvenience.

**Comment by mbn-dk** [comment]
We are experiencing the exact same issue.
Please advice when done.

**Comment by martinpolivka** [comment]
We are also experiencing the issue. Can we get an update, please?

**Comment by lkillgore** [comment]
Hi @mbn-dk and @martinpolivka, the ETA is still the same (~today).  As a workaround, you can use 'username / password' for authentication instead of OAuth until then.  When did you first notice the issue happening for you?  Also, what are your account names?

**Comment by mbn-dk** [comment]
Hi @lkillgore ,
We first noticed it today. On vsts we are: https://vstssiteattention.visualstudio.com 
Thanks,

**Comment by lkillgore** [comment]
Thanks, @mbn-dk.  It appears that your account should have the bits with the fix now.  Could you please verify whether that's the case or not?

**Comment by martinpolivka** [comment]
Hi @lkillgore ,
I think all builds are failing from yesterday evening.
Our account name is https://summitmedia.visualstudio.com/.
Thanks.

**Comment by lkillgore** [comment]
Hi @martinpolivka, it looks like your account has the updated bits now too.  Could you please check whether it's fixed?

**Comment by mbn-dk** [comment]
Thank you @lkillgore  - working now

**Comment by martinpolivka** [comment]
It works for us as well. Thanks @lkillgor.

**Comment by lkillgore** [comment]
Thanks for letting me know!  And, again, sorry for the inconvenience.

**Comment by jburbach** [comment]
This seems to be happening again.

**Comment by stephenmichaelf** [comment]
@jburbach Is the agent hosted or on prem? Can you email debug logs to:

stfrance at microsoft dot com

**Comment by praneetloke** [comment]
I just encountered this issue with one of my pipelines. I hadn't used my pipeline build for quite some time now. I just used it to run a CI build and it failed with this exact problem. Any suggestions on what might be the problem?

**Comment by jburbach** [comment]
I did as well on Friday. For now we switched our connection from oauth to use a username and password and it seems to work. The bitbucket oauth integrations seems to be pretty flakey.

**Comment by praneetloke** [comment]
> For now we switched our connection from oauth to use a username and password and it seems to work. 

Same here.

**Comment by brcrista** [comment]
This is a known issue and we're rolling out a fix.  Sorry for the inconvenience.  Switching to username / password should work as a workaround.  Feedback thread is here: https://developercommunity.visualstudio.com/content/problem/529542/bitbucket-checkout-error-could-not-read-username.html
