### ISSUE TITLE
Azure Powershell task v3.0 inline script has maxlength set to 500

### ISSUE THREAD

**Issue by onlyutkarsh** [Microsoft/vsts-tasks#8078]
## Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

## Environment
VSTS

- Agent - Hosted

## Issue Description

The Azure Powershell task has a text box for inline script set to 500 which is very limiting. Please consider it to 5000 minimum.

![image](https://user-images.githubusercontent.com/2685029/44363163-3f248e00-a4bb-11e8-9382-20fbd33f503b.png)

### Error logs

Cannot type after 500 characters.

**Comment by Ajay-MS** [comment]
@onlyutkarsh 

Thanks for raising concern. We have fixed this issue will be deployed within the next 2 weeks.
