### ISSUE TITLE
Unit Tests are stuck until build reaches timeout

### ISSUE THREAD

**Issue by roizentner** [Microsoft/vsts-tasks#8084]
​Hi,

We are using VSTS and private Windows agents.
We just experienced this strange issue! Here's an excerpt of the build log:

```
2018-08-20T14:21:31.9936333Z Passed   AddedHtmlIframeTest
2018-08-20T19:07:50.9703389Z ##[debug]Re-evaluate condition on job cancellation for step: 'Run Unit Tests'.
2018-08-20T19:07:51.0148772Z ##[error]The operation was canceled.
2018-08-20T19:07:51.0171377Z ##[debug]System.OperationCanceledException: The operation was canceled.
```
As you can see, it seems that the subsequent test ran for almost 5 hours until it reached the build timeout.
Since the test name is written to the log only after it passes/fails, we have no indication of which test got stuck. We found no other indication as to what could cause this test to get stuck.

Note that this is happening during a gated check-in build and it is consistently reproducible so this is currently blocking us from checking in code (unless we temporarily disable the gated check-in trigger).

Please advise.
​Thanks.

**Comment by gelomarc** [comment]
Hi @roizentner , did you manage to solve this issue? It seems that I have some issue.

**Comment by roizentner** [comment]
@gelomarc, it was the test's fault. It was changed without my knowledge and I was too quick to open this issue.
