### ISSUE TITLE
Docker Task: Cannot parameterize Azure Container Registry in VSTS task group

### ISSUE THREAD

**Issue by AlexRamey** [Microsoft/vsts-tasks#8091]
VSTS

In the task group, the specific ACR is a drop down. I'd like to use a variable $(ACRName)

## Issue Description

![screen shot 2018-08-21 at 2 16 42 pm](https://user-images.githubusercontent.com/6226193/44420837-0634f980-a54d-11e8-83e6-dd20d180b027.png)

**Comment by vithati** [comment]
@AlexRamey, "Azure Container Registry" input is editable dropdown, you can specify varaible also. 
Example:-
I have sepecified varaible in "mydoc" taskgroup docker task (In below screenshot-1). And I used this "mydoc" taskgroup in release pipeline (screenshot-2). I have add release variable 'azurerepo' with value "test.azurecr.io" and sepecified 'azurerepo' value in 'myrepo' parameter.  Can you try varaible in ACR input and let me know if you face any error.
1)
![image](https://user-images.githubusercontent.com/19663618/45681280-be5cbe80-bb5a-11e8-9ab4-011d602b1380.png)

2) 
![image](https://user-images.githubusercontent.com/19663618/45681421-201d2880-bb5b-11e8-92fe-a11415b85a77.png)

**Comment by vithati** [comment]
@AlexRamey, If you face any issue. Reopen the issue.
