### ISSUE TITLE
Fail fast when "Code Coverage Enabled" is ticked but VS Community is installed

### ISSUE THREAD

**Issue by dbolkensteyn** [Microsoft/vsts-tasks#811]
**Task: Visual Studio Test**

VS Community edition does not support code coverage, so I'd expect the build to fail if the "Code Coverage Enabled" checkbox has been ticked and the build agent does not have the capability to actually collect code coverage.

**Comment by atinb** [comment]
Thanks for the suggestion. Added to backlog.
