### ISSUE TITLE
Retrieve secure file GUID from VSTS frontend

### ISSUE THREAD

**Issue by techyian** [Microsoft/vsts-tasks#8112]
Hi,

Is it possible to get the GUID for a stored secure file from anywhere in VSTS easily? I would have expected this to be available in the "Library" area where the files are stored, but the only place I can see so far where it's retrievable is via "Link Settings".

I am automating Xamarin builds using the VSTS REST API, and for iOS I need to specify a provisioning profile filename. My understanding is that I can make use of the "INPUT_PROVPROFILESECUREFILE" environment variable that's used by the "Install an Apple provisioning profile" build task and this should hopefully pick up the secure file I need. The issue I'm running into is that I need the secure file GUID and not the filename itself. I don't mind storing this in the database if necessary, it just seems to be a bit illusive so far how to retrieve it easily.

**Comment by JohannesDrexler** [comment]
The id is not displayed in the frontend but if you open the WebDeveloperTools of a browser of your choice, go to library->secureFiles and open/reload the page there is a request named 'securefiles' that returns a json containing the list of securefiles and their ids.
I'd like to see the ids of some objects in the frontend too.

**Comment by techyian** [comment]
Thanks @JohannesDrexler, can confirm this returns the data I'm looking for. 

+1 for getting this in the front end.
