### ISSUE TITLE
Visual Studio Test task isn't generating code coverage for xUnit

### ISSUE THREAD

**Issue by jasonbert** [Microsoft/vsts-tasks#8113]
## Environment
VSTS - unable to provide account due to privacy restrictions

- Agent - Hosted or Private: 
    
Private
10.0.14393
Azure Windows Server 2016 Datacenter

## Issue Description

**Task:** Visual Studio Test
**Issue:** code coverage file is empty after running xUnit tests

* Unit tests run, produce results (trx file) and publish them to VSTS without issue
* Code coverage file is created, but contains no data
* If I run the command the task is using from a command prompt the code coverage file is correctly populated with results

**Command Run By Task:** [command]"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" @C:\VSTS\agents\dp-sitecore\agent-01\_work\_temp\0ec34221-a61d-11e8-8b14-df0fad7a6635.txt

**Contents of .txt file:**

"C:\VSTS\agents\dp-sitecore\agent-01\_work\2\s\Source\Feature\Authentication\tests\bin\Debug\Obfuscated.Authentication.Tests.dll"
_<... More binaries listed ...>_
"C:\VSTS\agents\dp-sitecore\agent-01\_work\2\s\Source\Foundation\Users\tests\bin\Debug\Obfuscated.Users.Tests.dll"
/EnableCodeCoverage
/InIsolation
/logger:"trx"
/TestAdapterPath:"C:\VSTS\agents\dp-sitecore\agent-01\_work\2\s\Source"
/diag:"C:\VSTS\agents\dp-sitecore\agent-01\_work\_temp\8d729900-a612-11e8-85fc-5f27b65d8975.txt"

The only difference I can see between my manual approach and the task is a reference to the Microsoft Coverage Collection Tool in the logs. When I run the command manually, this isn't mentioned at all.

![image](https://user-images.githubusercontent.com/2347572/44474543-d4926000-a62a-11e8-946b-eed46dd0fdf5.png)

Had to do an image as it has some odd characters preventing text copy/paste.

### Error logs

No errors reported.

**Comment by singhsarab** [comment]
> When trying manually to run via commandline, are you running on the same machine ?

Let's try to collect some more information.
Try analyzing *.coverage file generated, follow the instructions here
https://github.com/danielpalme/ReportGenerator/wiki/Visual-Studio-Coverage-Tools#codecoverageexe

Also, please enable debug logs (set system.debug as true in build variables)

**Comment by singhsarab** [comment]
@jasonbert Gentle ping.
Also if it is a private agent, can you please share the event logs as well ?

**Comment by ShreyasRmsft** [comment]
@jasonbert are you using the VsTestPlatform tool installer task along with the VsTest task? As @singhsarab has requested can you please send over the logs with system.debug=true as an attachment here or send a mail to devops_tools@microsoft.com with the logs as well as a screenshot of your build definition.

**Comment by ShreyasRmsft** [comment]
@jasonbert closing this due to no response. Please re-open the issue with the request details if you are still facing the issue.

**Comment by jasonbert** [comment]
Apologies for not getting back to this sooner, as requested I've sent an email with the information. I'm not sure how to get the event logs for the agent however.

**Comment by ShreyasRmsft** [comment]
@jasonbert we have received the logs, will get back to you on this.

**Comment by ShreyasRmsft** [comment]
@jasonbert the log file appears to be truncated. The last few lines i see are as follows

`2018-09-20T10:12:21.7040641Z /EnableCodeCoverage
2018-09-20T10:12:21.7040848Z /InIsolation
2018-09-20T10:12:21.7041036Z /logger:"trx"
2018-09-20T10:12:21.7041288Z /TestAdapterPath:"C:\VSTS\agents\dp-sitecore\agent-01\_work\10\s\Source"
2018-09-20T10:12:21.7041578Z /diag:"C:\VSTS\agents\dp-sitecore\agent-01\_work\_temp\92a57d40-bcbd-11e8-b36f-35274bd5e892.txt"
2018-09-20T10:12:21.7802464Z Starting test execution, please wait...
2018-09-20T10:12:21.7811176Z Logging Vstest Diagnostics in file: C:\VSTS\agents\dp-sitecore\agent-01\_work\_temp\92a57d40-bcbd-11e8-b36f-35274bd5e892.txt
2018-09-20T10:12:25.1902470Z M`

Can you confirm if this is it or are there more logs after this?

**Comment by ShreyasRmsft** [comment]
@jasonbert please upload the zip file containing the entire set of logs for the build, not just one file. There are additional files we upload pertaining to the test platform.

**Comment by abhishkk** [comment]
@jasonbert Can you please share the info asked by Shreyas?

**Comment by abhishkk** [comment]
@jasonbert Closing the issue due to no response. Please re-open to followup along with info asked by Shreyas.

**Comment by jasonbert** [comment]
@ShreyasRmsft perhaps I'm being dense, but where do I find the log files? I don't see an option in VSTS to download them, nor do I see any folder in the agent with logs.

**Comment by abhishkk** [comment]
@jasonbert Closing the issue due to no response. Please re-open to followup along with info asked.

**Comment by jasonbert** [comment]
@abhishkk as I said in my original post, there are no errors and yes the files generated is empty :). I'll send along the empty file along with the code coverage that's generated when I run the exact same command in a prompt.

**Comment by KevinCust** [comment]
Any resolution to this? I experienced the same behavior back in October and want to get it working in the new year. Came back to check on the status and appears to be closed without resolution?

**Comment by ShreyasRmsft** [comment]
@KevinCust please provide the entire zip file containing debug logs for the build where this has ocurred. Send the empty coveragge file along with the code coverage that's generated when you run the tests with code coverage locally. We will take a look. I will re-open the issue on receiving all the requested files.
