### ISSUE TITLE
Cocopods: "cocoapods" demand requred even though it’s not a valid demand for the xplat agent

### ISSUE THREAD

**Issue by Chuxel** [Microsoft/vsts-tasks#813]
Repro:
 
1. Install cocoapods on a Mac - MacInCloud instances have it installed 
2. Add and configure a Cocoapods Install Task to a VSO Build Def
3. Queue build with Mac agent
 
Expected: Runs the command
Actual: Can't find an agent
 
The cocoapods demand in task.json should be removed and replaced with a good error message speaking to where Cocopods can be installed from if the "pod" command is not found.

**Comment by bryanmacfarlane** [comment]
I'm on it

**Comment by Chuxel** [comment]
Bump on this one - I notice the cocoapods task still requires a cocoapods demand, but the xplat agent doesn't support it.

I know I saw this on the dogfooding DL as well. Is this expected to be fixed already?

**Comment by madhurig** [comment]
Demand was removed several months back, so closing the issue: https://github.com/Microsoft/vsts-tasks/commit/1c6e617ad8fd1d4ba9ddaf55f3ddc8f8f8254ce1
