### ISSUE TITLE
Command Line task: Use of quotes, escapes in Arguments do not seem to get handled properly

### ISSUE THREAD

**Issue by Chuxel** [Microsoft/vsts-tasks#814]
The Command Line Task does not properly handle quotes and in some cases escaping. (It does a simple split on space.)
 
Repro:
 
1. Add Command Line Task to a VSO Build Def
2. Command: kilall
3. Arguments: "iOS Simulator"
4. Run on a mac agent (may need to add "sh" as a demand)
 
Expected: Any simulators running on the Mac Host will stop
Actual: Error message on parsing due to the simplistic nature of the split being done

Note: Found on Mac but should be restested on Windows as well.

**Comment by bryanmacfarlane** [comment]
I'm investigating.  We added support in vso-task-lib to simply pass to .arg but I guess that task is still doing a split.

Will fix today

**Comment by Chuxel** [comment]
To be clear, is "getDelimitedInput" getting enhanced?  The problem is that what we probably need to do to parse args input like this is use minimist.

**Comment by bryanmacfarlane** [comment]
You're not supposed to use .getDelimitedInput. See the comments in vso-task-lib

You should just call .arg with the string args - it will split properly on double quotes. See the shellscript task

**Comment by bryanmacfarlane** [comment]
Confirmed fixed in 91
