### ISSUE TITLE
Breaking change from vstest 15.7.2 to 15.8.0

### ISSUE THREAD

**Issue by phatcher** [Microsoft/vsts-tasks#8159]
## Environment
VSTS
VS2017 Hosted Agent

## Issue Description
My build started breaking on Friday, it appears that the test console was silently updated from 15.7.2 to 15.8.0 even though the agent version and the MS Test task version have not changed.  I thought initially that it was my code changes that caused the issue but eliminated that by re-queuing a previous successful commit (see below). All tests execute correctly locally.

There seems to be two issues...

1. The test console is not obeying the TestCategory restrictions leading to integration tests being run as part of the CI build
2. Test execution/paths being changed so that tests fail to find the SqlSpatial140.dll even though this is in the test directory and there's initialisation code to load this assembly

### Successful run
![image](https://user-images.githubusercontent.com/192778/44676868-553acd00-aa2c-11e8-8fa8-58e0c55e2a5e.png)
### Unsuccessful run, same commit, same build pipeline
![image](https://user-images.githubusercontent.com/192778/44676921-78fe1300-aa2c-11e8-81a2-1b242deabd9a.png)
### Test step configuration
![image](https://user-images.githubusercontent.com/192778/44676659-ce85f000-aa2b-11e8-897e-e9bcfe786404.png)

I'm getting the same issue with Release Management test steps as well.

### Error logs
Can send but don't want to post logs publicly

**Comment by singhsarab** [comment]
@phatcher Can you please send the logs to devops_tools@microsoft.com
I'll take a look and get back to you.

**Comment by singhsarab** [comment]
@phatcher I am sorry, but I haven't received the logs yet.

**Comment by phatcher** [comment]
@singhsarab Sent another link - let me know if you get it

**Comment by singhsarab** [comment]
@phatcher I havent received the logs :(
 Is there any other way, we can get the logs?

**Comment by phatcher** [comment]
@singhsarab Did you receive any email from me...

1. If I send the full logs they get blocked as too large
2. If I send with a OneDrive link they get blocked as too large
3. Send with DropBox link doesn't seem to get through

Please check you spam box :-)

Suggestions?

I can try to trim them down, but that rather missed the point I think

**Comment by ShreyasRmsft** [comment]
@phatcher can you double confirm if you have been sending it to devops_tools@microsoft.com?

Also can you try sending a mail without an attachment to see if it's an issue with attachments or you're unable to even reach the mail id?

Let us know once you've done this and if you are still unable to send over logs we'll see if there are any alternatives we can resort to.

**Comment by phatcher** [comment]
@ShreyasRmsft  Test email sent - I'm sure I've managed to send you guys logs in the past

![image](https://user-images.githubusercontent.com/192778/44973575-ef32d600-af54-11e8-8a14-c4bb107af83f.png)

**Comment by phatcher** [comment]
Ok latest one was block at your mail server...

[http://products.office.com/en-us/CMSImages/Office365Logo_Orange.png?version=b8d100a9-0a8b-8e6a-88e1-ef488fee0470]
Your message couldn't be delivered to multiple recipients.

The groups only accept messages from people in their organization or on their allowed senders list, and your email address isn't on the lists.

paulh   Office 365      Groups
Sender          Action Required


Sender not allowed

Couldn't deliver to the following groups:
vs_atpm@microsoft.com, vstlmtcm@microsoft.com

**Comment by ShreyasRmsft** [comment]
@phatcher that is a standard reply you get when you try to send a mail to that id. It's always been the case.

In fact just now i sent a mail from my personal mail account to the id and was able to see it appear within a minute. Is it possible for you give the logs here on GitHub? With sensitive info redacted if you so wish.

**Comment by ShreyasRmsft** [comment]
PS: we only need the logs for the VsTest task. You needn't send the log files of the other tasks

**Comment by ShreyasRmsft** [comment]
@phatcher found the mails in the Junk folder. They were getting redirected there for some reason. We have received the logs and will take a look

**Comment by phatcher** [comment]
@ShreyasRmsft Thanks, I think some of the issues are do to with the netcore shim packages being incorrectly referenced from the net framework projects, but the most important is why the test category filter is not obeyed - the rest I am working around by upgrading package/assembly versions

**Comment by ShreyasRmsft** [comment]
@phatcher I created a sample NUnit test project with 4 tests.

Using latest NUnit adapter and latest test platform.

And ran tests with testcategory!=a&testcategory!=b and it ran the 4th test which doesn't fall into this category. So it isn't broken. However i would like you try this project with a bunch of testcategory filters to see if it runs fine on your hosted pool.

(@phatcher you can acquire the latest testplatform by using the [vstest platform tool installer task](https://docs.microsoft.com/en-us/vsts/release-notes/2017/nov-28-vsts#test))


[NunitTestCategory.zip](https://github.com/Microsoft/vsts-tasks/files/2360412/NunitTestCategory.zip)

**Comment by phatcher** [comment]
@ShreyasRmsft Looking at your code, which runs successfully for me, I checked the logs again and I think I've identified the issue.

We have two test steps, one for managed tests, the other for a C++ client and the problem is associated with the C++ test step.

1. The test specification on C++ step was defined incorrectly with no filter, but because it had a custom test adapter path, it previously only picked up the C++ tests.
2. With the latest test runner, it found all of the test assemblies/adapters and so executed the tests including the integration tests.

I've fixed that and additionally updated all of our code to just net471 and the latest test framework my remaining issue now is a problem resolving an assembly e.g.
```
2018-09-07T14:35:29.3622750Z Data collection : Logging DataCollector Diagnostics in file: D:\a\_temp\3352b450-b2ab-11e8-9b5f-7521f8d1e7c7.datacollector.18-09-07_14-35-21_28119_6.txt
2018-09-07T14:35:29.3625093Z Data collection : Logging DataCollector Diagnostics in file: D:\a\_temp\3352b450-b2ab-11e8-9b5f-7521f8d1e7c7.datacollector.18-09-07_14-35-21_28119_5.txt
2018-09-07T14:35:36.2561862Z Logging TestHost Diagnostics in file: D:\a\_temp\3352b450-b2ab-11e8-9b5f-7521f8d1e7c7.host.18-09-07_14-35-29_36339_5.txt
2018-09-07T14:35:36.6275189Z Logging TestHost Diagnostics in file: D:\a\_temp\3352b450-b2ab-11e8-9b5f-7521f8d1e7c7.host.18-09-07_14-35-29_36339_6.txt
2018-09-07T14:35:39.4918641Z Error initializing RunSettings. Default settings will be used
2018-09-07T14:35:39.4919936Z Error initializing RunSettings. Default settings will be used
2018-09-07T14:35:39.4920277Z System.IO.FileNotFoundException: Could not load file or assembly 'System.Xml.XPath.XmlDocument, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
2018-09-07T14:35:39.4920628Z File name: 'System.Xml.XPath.XmlDocument, Version=4.0.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
2018-09-07T14:35:39.4921683Z    at NUnit.VisualStudio.TestAdapter.AdapterSettings.Load(String settingsXml)
2018-09-07T14:35:39.4922003Z    at NUnit.VisualStudio.TestAdapter.AdapterSettings.Load(IDiscoveryContext context) in D:\repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\AdapterSettings.cs:line 171
2018-09-07T14:35:39.4922362Z    at NUnit.VisualStudio.TestAdapter.NUnitTestAdapter.Initialize(IDiscoveryContext context, IMessageLogger messageLogger) in D:\repos\nunit\nunit3-vs-adapter\src\NUnitTestAdapter\NUnitTestAdapter.cs:line 131
```

**Comment by ShreyasRmsft** [comment]
@phatcher can you provide the entire set of debug logs again for this issue? 

Also can you enable fusion logs and see where this dll is trying to be loaded from and what version of the dll is present? 

Also there's a chance your assembly config file may not be getting honored when the tests run in the vstest.console.exe process. Please add the following to your runsettings file to prevent app domain disabling. This ensures the users dll config file is used.

```
<RunSettings>
    <RunConfiguration>
        <DisableAppDomain>False</DisableAppDomain>
    </RunConfiguration>
</RunSettings>
```

**Comment by phatcher** [comment]
@ShreyasRmsft I've forwarded the latest logs and I will enable the two settings and get back to you.

**Comment by ShreyasRmsft** [comment]
@phatcher didn't receive your mail again? :(

Is it possible to add them here on github?

**Comment by ShreyasRmsft** [comment]
You can redact sensitive data.

**Comment by abhishkk** [comment]
@phatcher Closing this issue due to no response. Please re-open to follow-up on this issue (with the logs as asked by Shreyas)
