### ISSUE TITLE
Improvement: Xcode and Xcode Package tasks should use -exportArchive if Xcode version found is 7 or later

### ISSUE THREAD

**Issue by Chuxel** [Microsoft/vsts-tasks#816]
Xcode 7 switched how packages should be generated slightly.  While the existing PackageApplication feature works if the --sign and --embed commands are omitted, at some point it's possible this will be dropped by apple in favor of the new -exportArchive flag.

With Xcode 7+, we should now:

- build an archive with xcodebuild archive
- create the .ipa with xcodebuild -exportArchive

Further, it would be a good idea to include some of the same features in the Xcode Build task in the package task for this purpose.  PackageApplication is in use now as it is backwards compatible to older versions of Xcode.

See http://stackoverflow.com/questions/32763288/ios-builds-ipa-creation-no-longer-works-from-the-command-line/32845990#32845990

**Comment by madhurig** [comment]
https://github.com/Microsoft/vsts-tasks/pull/2701

**Comment by madhurig** [comment]
Fix has been merged and will be deployed to Team Services starting Oct 16th and should roll out to all accounts in about a week.
