### ISSUE TITLE
Build Error for MacOS hosted agent

### ISSUE THREAD

**Issue by Gold14388** [Microsoft/vsts-tasks#8162]
## Environment
- Server - VSTS or TFS on-premises?
    
   VSTS

- Agent - Hosted or Private: 
    
  MacOS (agent manually hosted on macbook)

## Issue Description
I have an agent hosted on MacOS for building Xamarin.iOS related project. I am getting below mentioned error.
##[Error 1]
**_No agent found in pool Default which satisfies the specified demands:
     xcode
     Xamarin.iOS
     Cmd
     Agent.Version -gtVersion 2.116.0_**

**Comment by JohannesDrexler** [comment]
The cmd-demand comes from your last task in the builddefinition. This task is supposed to run on windows only. You might want to use "Command Line" (v2) which executes on the systems default shell.

**Comment by Gold14388** [comment]
Thank you Johannes. After removing the batch task from build definition, The build does works well. I was using it for running git command as  .ipa file generated by build needs to be pushed to github.
