### ISSUE TITLE
How to update vsts-tasks in on-premise environments 

### ISSUE THREAD

**Issue by judavi** [Microsoft/vsts-tasks#8203]
Troubleshooting
Checkout how to troubleshoot failures and collect debug logs: https://docs.microsoft.com/en-us/vsts/build-release/actions/troubleshooting

Environment
TFS on-premise 2017-Update3
Private Agent on Windows Server 2016 

Issue Description
We have a similar issues as in #4684. In the issue it is said that the problem is fixed in a new version PR: #5622. 
So how do I update the vsts-tasks to the latest version? 

Also I saw in #7571 there is mechanism from the product team to apply updates but how I can update the tasks in the on-premise environment ?

**Comment by bryanmacfarlane** [comment]
answered.  let us know if you need anything clarified.
