### ISSUE TITLE
Azure Powershell Script: This input does not support more than 500 characters. The pasted content has been clipped.

### ISSUE THREAD

**Issue by trailmax** [Microsoft/vsts-tasks#8209]
I'm configuring release steps for VSTS Hosted 2017 agent (don't think this matters greatly here). I'm using Azure Powershell Script step and I'm trying to do inline PS script rather than a PS-file. When I'm pasting  my script into the inline window, I'm getting an error 
> This input does not support more than 500 characters. The pasted content has been clipped.

![image](https://user-images.githubusercontent.com/3606356/44882786-c25c9580-acac-11e8-8b62-c930369f1b77.png)

500 chars for PS script? That's not even scratching the surface. 

I'm sure this is some sort of misunderstanding, otherwise there is no point in providing this inline script, only just to let me type my parameters.

**Comment by bryanmacfarlane** [comment]
This is a dupe of https://github.com/Microsoft/vsts-tasks/issues/4272

In latest vsts versions (should be in latest tfs 2018) it's 5000

https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/PowerShellV2/task.json#L73

**Comment by trailmax** [comment]
@bryanmacfarlane I suspected there was an issue for that, but could not find given the keywords. 
How can I get the latest version of the task when on VSTS? I see version selector for the task - I'm on 3.*. Anything else I should do to get 5000-limit?

**Comment by bryanmacfarlane** [comment]
Ohhh - I was looking at the powershell task.  I took a look at the azurepowershell task and it looks like they bumped it 9 days ago:

https://github.com/Microsoft/vsts-tasks/blame/master/Tasks/AzurePowerShellV3/task.json#L103

**Comment by bryanmacfarlane** [comment]
That means it will show up on VSTS in 2 - 4 weeks (updates roll)

**Comment by bryanmacfarlane** [comment]
@kmkumaran team owns.

**Comment by trailmax** [comment]
@bryanmacfarlane I see, I'll just create a script file instead
Thanks for your help and your time!
