### ISSUE TITLE
Git push to bitbucket is not triggering build in VSTS

### ISSUE THREAD

**Issue by vaclav-dvorak** [Microsoft/vsts-tasks#8216]
## Environment
Account name: summitmedia.visualstudio.com
Project name: Automotive
Build definition name: https://summitmedia.visualstudio.com/Automotive/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=122&view=Tab_Triggers

## Issue Description
We are using "Enable continuous integration" in our build definitions with connection with our bitbucket cloud repositories using OAuth connection. This stopped working few days ago. Webhook seems to be created in bitbucket and it is sending data to. However builds are not reacting to it.
sidenote: hooks that seemed to be working have `api-version=4.1-preview` but new ones have `api-version=5.0-preview` not sure if that can be the cause.

## Error logs
Response from https://summitmedia.visualstudio.com/_apis/public/hooks/externalEvents?publisherId=bitbucket&channelId=foo-bar&api-version=5.0-preview
HTTP status: 200
Elapsed time: 647ms
Request time: 2 hours ago (Friday, August 31st 2018, 2:07:28 pm)
Headers:
Content-Length | 992
Expires | -1
X-Content-Type-Options | nosniff
Content-Encoding | gzip
Set-Cookie | VstsSession=%7B%22PersistentSessionId%22%3A%228b3652fb-2da6-4b7c-ba86-5c09fe3e5d3c%22%2C%22PendingAuthenticationSessionId%22%3A%2200000000-0000-0000-0000-000000000000%22%2C%22CurrentAuthenticationSessionId%22%3A%2200000000-0000-0000-0000-000000000000%22%7D; domain=.visualstudio.com; expires=Wed, 30-Aug-2023 12:07:27 GMT; path=/; secure; HttpOnly
X-TFS-ProcessId | 0b8989a6-8b96-439c-9f4e-ef4d23d1695b
Strict-Transport-Security | max-age=31536000; includeSubDomains
Vary | Accept-Encoding
X-Powered-By | ASP.NET
X-AspNet-Version | 4.0.30319
X-TFS-Session | a0bd145e-0239-4aee-aeb1-29a9397059c9
ActivityId | a0bd145e-0239-4aee-aeb1-29a9397059c9
Pragma | no-cache
Cache-Control | no-cache, no-store, must-revalidate
Date | Fri, 31 Aug 2018 12:07:27 GMT
P3P | CP="CAO DSP COR ADMa DEV CONo TELo CUR PSA PSD TAI IVDo OUR SAMi BUS DEM NAV STA UNI COM INT PHY ONL FIN PUR LOC CNT"
Content-Type | application/json; charset=utf-8; api-version=5.0-preview.1
X-MSEdge-Ref | Ref A: 190418C8E0624413A262E470CE82BB36 Ref B: BL2EDGE1018 Ref C: 2018-08-31T12:07:28Z
X-VSS-E2EID | a0bd145e-0239-4aee-aeb1-29a9397059c9

**Comment by bryanmacfarlane** [comment]
Looks to be a service issue (not tasks which is this repo).  I'll forward this to devs but you might want to create an issue on developer community
