### ISSUE TITLE
VSTS: Azure Powershell 3.* Inline Script missing Script Arguments

### ISSUE THREAD

**Issue by joshuapetryk** [Microsoft/vsts-tasks#8239]
On VSTS - self hosted agent (Azure VM w\ Windows Server 2016 Datacenter)

The Azure Powershell 3.* task seems to be missing the Script Arguments box if Inline Script is selected. Compare this to the 2.* version of the task.

We can't pass variables into inline scripts without this.

**Comment by arjgupta** [comment]
@joshuapetryk , you can pass the variables using the $(variable_name) pattern in the inline script directly.

**Comment by joshuapetryk** [comment]
This doesn't work in Release Management. I tried putting varibles in the script directly but they were not expanding during a release.
________________________________

**Comment by arjgupta** [comment]
@joshuapetryk , can you share the inline script you are trying to use variable in ?
I tried using a simple script like this:
`Write-Host "$(var1)"`
And I had set the "var1" as a variable in the variables tab for my release. The script output had the substituted value.

**Comment by joshuapetryk** [comment]
Okay I just tried again and this started working - not sure what was going wrong before.

**Comment by hintbw** [comment]
@arjgupta - I appreciate the response here - the instructions provided in the task do not reflect your guidance though and that still feels like it could be updated in the task. I can open another issue if needed, but it would be nice for the documentation provided as you are filling out the task directed you to do what you are indicating to do.
