### ISSUE TITLE
VSTS -> Build and Release -> Release: Stuck on loading screen

### ISSUE THREAD

**Issue by KevinHaisol** [Microsoft/vsts-tasks#8243]
## Troubleshooting
Tried using IE, Firefox, and Chrome and got the same issue.

## Environment
- Server: VSTS   
- Agent: N/A
## Issue Description
When clicking on Build and Release -> Release, the screen never loads and is stuck on the loading screen.  I've tried the new release preview feature but that doesn't work either.

![image](https://user-images.githubusercontent.com/25829792/45036802-ae9d9000-b01a-11e8-836a-95b94f1eb5bc.png)

### Error logs
No errors just doesn't load.  Here is debug console output.
![image](https://user-images.githubusercontent.com/25829792/45037043-4a2f0080-b01b-11e8-8aba-43394692cf21.png)

**Comment by gencay** [comment]
The `503` seems to be related to the Azure outage. Check out [this page for live updates](https://blogs.msdn.microsoft.com/vsoservice/?p=17405)

**Comment by bansalaseem** [comment]
It should be working for you as the outage got resolved 10 days back or so.
