### ISSUE TITLE
Unable to publish standard console output results/details of .trx file in VSTS Test Hub

### ISSUE THREAD

**Issue by Sibaram57** [Microsoft/vsts-tasks#8246]
We are using "System.Diagonestics.Trace.WriteLine("User Message")" command  to capture the standard console output results/details in to .trx file in VSTS. We are successfully captured the standard console ouput details in to  .trx test result file. However, we are unable to publish this standard console output details to VSTS Test hub after executing release tasks "Visual studio test" and "Publish test result". We can see test results only in the form of pass or fail in VSTS Test hub for each test case.
Could you please assist in publishing the standard console output results in VSTS Test Hub

**Comment by abhishkk** [comment]
@Sibaram57 
For failed test, VSTS test hub shows output and stack trace. For passed tests, output is not shown in test hub

![image](https://user-images.githubusercontent.com/32157767/46201044-d4c00280-c330-11e8-887a-5d127bc8b200.png)

**Comment by abhishkk** [comment]
Closing this issue. Please re-open if you need further assistance.
