### ISSUE TITLE
SSH task - use VSTS variables

### ISSUE THREAD

**Issue by tilumi** [Microsoft/vsts-tasks#8247]
## Environment
- VSTS 
    account: luyan@microsoft.com
    Team: IP Engineering
     Pipeline: spark-aggregator

## Issue Description

Exactly the same as: [https://github.com/Microsoft/vsts-tasks/issues/3073](https://github.com/Microsoft/vsts-tasks/issues/3073)

Variable read as empty even use the syntax "$(VARIABLE_NAME)"

**Comment by vmitchell85** [comment]
@tilumi Did you resolve your issue? I'm having problems as well and cannot seem to find good documentation on using variables in SSH tasks

**Comment by vmitchell85** [comment]
If anyone is also having issues... you must reference the variables in your Task commands using uppercase as well even though [this doc](https://docs.microsoft.com/en-us/azure/devops/pipelines/release/variables?view=vsts&tabs=shell) seems to indicate otherwise.

**Comment by rycornell** [comment]
@vmitchell85 I also notice that you're using dots instead of underscores in the variable name.  That's what fixed it for me.  Thanks.
