### ISSUE TITLE
VM Size APIs

### ISSUE THREAD

**Issue by darshankumarys** [Microsoft/vsts-tasks#8263]
We are using VSTS to provision VMs and in need of VM Sizes APIs to get data disk types and max data disk count. Unfortunately we didn't find any APIs for VM Sizes, by when they will be released ?
By then, can you suggest alternate process to fetch VM size properties in VSTS task.json

**Comment by kmkumaran** [comment]
If you are provisioning VMs using custom script, you can make use of Azure APIs for fetch VM related properties.
https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/list

**Comment by darshankumarys** [comment]
@kmkumaran did you get chance to look into my query?

**Comment by kmkumaran** [comment]
@darshankumarys - 
You can do a GET on specific VM to get more properties using https://docs.microsoft.com/en-us/rest/api/compute/virtualmachines/get. 

I presume you also are asking how these calls be made from VSTS extension which you own. Is that right? If so, you can enhance your task to use your own datasourcebindings if that is already not defined in endpoint. You can refer https://github.com/Microsoft/vsts-rm-extensions/blob/master/docs/authoring/endpoints/dataSources.md#defining-url-inline-within-datasourcebinding for more details on that.

**Comment by kmkumaran** [comment]
@darshankumarys, I am marking this thread closed. Fell free to get back if you have more queries on this.
