### ISSUE TITLE
Visual Studio Test task failing with "Failure attempting to call the restapis" error

### ISSUE THREAD

**Issue by NDDeveloper13** [Microsoft/vsts-tasks#8270]
I have the following setup:
- Agent version 2.139.1
- Test agents are Win10 OS.
- On-Premise TFS 2018 Update 2

I have a release definition with the following steps:
- VsTest Platform Installer
- Copy Test Assemblies - copies assemblies from a drop location to the agent
- Visual Studio Test - runs tests from a test plan

Upon creating a release, the first 2 steps succeed; however, I get the following error for the Visual Studio Test step (full log is here [TestReleaseLog.txt](https://github.com/Microsoft/vsts-tasks/files/2361963/TestReleaseLog.txt)):
##[error]Failure attempting to call the restapis. Method: System.Threading.Tasks.Task <.ctor>b__0(), Exception: System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host

I have tried configuring the agent with the following authentication types, but all result in the same error:
- PAT
- Integrated
- Negotiate

**From the Agent log:**
[2018-09-07 16:55:00Z INFO RSAEncryptedFileKeyManager] Loading RSA key parameters from file C:\agent.credentials_rsaparams
[2018-09-07 16:55:00Z INFO MessageListener] VssConnection created
[2018-09-07 16:55:00Z INFO Terminal] WRITE LINE: Connecting to the server.
[2018-09-07 16:55:00Z INFO MessageListener] Attempt to create session.
[2018-09-07 16:55:00Z INFO MessageListener] Connecting to the Agent Server...
[2018-09-07 16:55:00Z INFO VisualStudioServices] Starting operation Location.GetConnectionData
[2018-09-07 16:55:00Z WARN VisualStudioServices] Authentication failed with status code 401.
Date: Fri, 07 Sep 2018 16:55:00 GMT
P3P: CP="Do you need this info?"
Server: Microsoft-IIS/10.0
WWW-Authenticate: Bearer, Basic realm="https://mytfs.com/tfs/", Negotiate, NTLM
X-TFS-ProcessId: 3bc595a3-4014-4acc-bc86-b6a35c9dc627
ActivityId: 48ccba6b-2558-4fe6-8670-b6ab8d5786af
X-TFS-Session: 1c637d2f-64e4-48ae-aa3b-004969880ad6
X-VSS-E2EID: 00baf5d9-17bf-4240-a510-c53b5932b81d
X-FRAME-OPTIONS: SAMEORIGIN
X-TFS-SoapException: %3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22utf-8%22%3F%3E%3Csoap%3AEnvelope%20xmlns%3Asoap%3D%22http%3A%2F%2Fwww.w3.org%2F2003%2F05%2Fsoap-envelope%22%3E%3Csoap%3ABody%3E%3Csoap%3AFault%3E%3Csoap%3ACode%3E%3Csoap%3AValue%3Esoap%3AReceiver%3C%2Fsoap%3AValue%3E%3Csoap%3ASubcode%3E%3Csoap%3AValue%3EUnauthorizedRequestException%3C%2Fsoap%3AValue%3E%3C%2Fsoap%3ASubcode%3E%3C%2Fsoap%3ACode%3E%3Csoap%3AReason%3E%3Csoap%3AText%20xml%3Alang%3D%22en%22%3ETF400813%3A%20Resource%20not%20available%20for%20anonymous%20access.%20Client%20authentication%20required.%3C%2Fsoap%3AText%3E%3C%2Fsoap%3AReason%3E%3C%2Fsoap%3AFault%3E%3C%2Fsoap%3ABody%3E%3C%2Fsoap%3AEnvelope%3E
X-TFS-ServiceError: TF400813%3A%20Resource%20not%20available%20for%20anonymous%20access.%20Client%20authentication%20required.
X-Powered-By: ASP.NET
Lfs-Authenticate: NTLM
X-Content-Type-Options: nosniff

How do I get around this?

**Comment by ShreyasRmsft** [comment]
Needless to say but just confirming, this is a constant repro (ie. it happens all the time)? Can you provide logs with system.debug set to true in the variables section?

**Comment by NDDeveloper13** [comment]
The agent is a virtual machine with no proxy.

Yes, the error is consistent and happens every time. In addition to trying 2 different users and 3 different authentication types, I have also tried with and without a test settings file. 

Here are the debug logs:
[TestReleaseDebugLogs.txt](https://github.com/Microsoft/vsts-tasks/files/2367200/TestReleaseDebugLogs.txt)

**Comment by ShreyasRmsft** [comment]
@NDDeveloper13 hmmm it could be a firewall or network issue. To rule certain things out is it possible to setup a vsts-agent on a physical machine and try the same build?

If it is failing only from the VM then we can be sure it's something to with the firewall config or network issue with the VM.

**Comment by NDDeveloper13** [comment]
I tried a physical machine and I got the same result. I first tried version 2.131.0 which is what TFS downloads when going to the TFS agent pools page. I then used version 2.139.1. Both of those versions, I got the same error regarding Failure attempting to call the restapis.

Are there settings that our tfs admin should look into?

**Comment by NDDeveloper13** [comment]
Anything on this? Is there something else I can look into?

**Comment by ShreyasRmsft** [comment]
@NDDeveloper13 this is the first we're hearing of this. One thing that can help is trying to capture the network traces of the request going from the agent when it attempts to contact the tfs service. Can you collect the networks dumps/traces?

**Comment by ShreyasRmsft** [comment]
@NDDeveloper13 taking a look at the fiddler traces should help with figuring out why the calls are failing

**Comment by NDDeveloper13** [comment]
The Fiddler trace (below) reveals that it can't even establish a connection, so I am unable to see which rest API it is trying to hit. Note that the first 2 tasks in the job finished successfully, so it's something specific with the Visual Studio Test task. 

We are looking into that right now. I have the tfs admin taking a look to see if he can find a setting that's off or something. If you have ideas of which setting(s) to look at, that would be helpful.

**Fiddler trace:**
HTTP/1.1 200 Connection Established
FiddlerGateway: Direct
StartTime: 13:04:51.119
Connection: close

fiddler.network.https> HTTPS handshake to devtfs.naucountry.com (for #13) failed. System.IO.IOException Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. < An existing connection was forcibly closed by the remote host

**Comment by ShreyasRmsft** [comment]
Both of the below tasks do not talk to tfs so their success is not indicative of successful communication with tfs.

VsTest Platform Installer
Copy Test Assemblies - copies assemblies from a drop location to the agent



Use some task like publish artifacts (publish test results etc. )or some other task that talks to tfs to confirm whether other  tasks are able to talk to tfs

**Comment by NDDeveloper13** [comment]
Our dev tfs server that I was doing my research on has been reverted to TFS 2017, so I gave a few things a try. I have tried a few different combinations and have narrowed it down to being a vsts agent issue. In the screen shot of my release history, you can see the detail comments to see which versions I tried. It appears that something changed between vsts agent 2.117.2 and 2.120.0, causing this issue. Once our dev tfs server gets upgraded to TFS 2018 again, I can try TFS 2018 out with vsts agent 2.117.2; although I'm not sure if that combination is supported?

![image](https://user-images.githubusercontent.com/43071948/45932436-9649d280-bf41-11e8-8b1f-8104bf141c31.png)

**Comment by ShreyasRmsft** [comment]
@NDDeveloper13 that's interesting turn of events. We'll get back to you on this. Will have to get a setup of the various combinations you have mentioned and give a shot at debugging from our end to see what's going wrong

**Comment by NDDeveloper13** [comment]
I just realized that the releases aren't in version order and discovered 2.119.0 and 2.119.1 which I hadn't tested with yet. Testing out both of these versions, the test ran (but failed due to unrelated issues), so that narrows it down even further for you. Something changed between vsts agent 2.119.1 and 2.120.0 causing the issue that I am seeing.

**Comment by ShreyasRmsft** [comment]
@NDDeveloper13 on 2.140 does it run fine?

**Comment by ShreyasRmsft** [comment]
@NDDeveloper13 is it possible to share the network traces with us?

**Comment by NDDeveloper13** [comment]
I'm working on getting approval to send these to you. If approved, is there a secure email I could send them to? 

I have been working with the 2.117.2 version to move forward with our update but I have now run into another issue, and I'm not sure if it's due to me using 2.117.2 or if it's an unrelated issue.

When running a data driven test, the test fails with the following error:
The unit test adapter failed to connect to the data source or to read the data. Could not load file or assembly 'Microsoft.TeamFoundation.TestManagement.Controller or one of its dependencies. The system cannot find the file specified.

In the VS Test Platform Installer task, I have it set to install version 15.8.0. I have the variable for Test.TestCaseAccessToken set up as described here:
https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2018-update1#testpipeline

Is this due to me using 2.117.2 or is this an unrelated issue that I need to open a different issue for?

**Comment by abhishkk** [comment]
@NDDeveloper13 

> Is this due to me using 2.117.2 or is this an unrelated issue that I need to open a different issue for?

This is due to using 2.117.2. This is a known issue and is resolved in latest version. You need latest VS version(15.9)  as well for it to work. 15.9 RTM will be public next month. Currently 15.9 preview is available.

> If approved, is there a secure email I could send them to?

You can send it to devops_tools@microsoft.com

**Comment by NDDeveloper13** [comment]
I sent an email to you as well as devops_tools. It looks like I'm not authorized to send emails to devops_tools, so hopefully you got it and can forward it onto the appropriate people. Let me know if you didn't receive it or if you need anything further.

**Comment by NDDeveloper13** [comment]
I sent another email with an updated list of files that contains logs and Fiddler sessions for both the working (2.117.2) and non-working (2.140.2) agents. The data appears to point to the very first http request coming from DTAExecutionHost. 

Please confirm that you got the email.

**Comment by NDDeveloper13** [comment]
We discovered that when we change Fiddler to use TLS 1.2 (instead of 1.0) against agent 2.140.2, the request works and the test runs. 

With that information, looking at the 2.140.2 agent Fiddler trace, the DTAExecutionHost is using TLS 1.0. The old agent that works (2.117.2) only uses HTTP and not HTTPS which explains why 2.117.2 doesn't have the issue.

Is there a reason why the DTAExecutionHost is using TLS 1.0 while other components (agent.worker, agent.listener) are using TLS 1.2? It appears that the TestExecutionHost is also using TLS 1.0, while it used to use HTTP with agent 2.117.2, so that application will cause the same issues.

**Comment by ShreyasRmsft** [comment]
@NDDeveloper13 the DTAExecutionHost.exe and TestExecutionHost.exe are both compiled against .Net 4.5 where the default is TLS 1.0.

Having .Net 4.6 or above should be an immediate workaround as stated in this [post](https://blogs.perficient.com/2016/04/28/tsl-1-2-and-net-support/)

.Net 4.6 uses TLS 1.2 by default.

Also what .Net framework version do you have installed on your machines?

If having .Net 4.6 or above is not possible then there is a registry hack mentioned in the following [post](https://stackoverflow.com/questions/28286086/default-securityprotocol-in-net-4-5) that is also worth a shot.

**Comment by NDDeveloper13** [comment]
We have .Net 4.7.1 installed:
![image](https://user-images.githubusercontent.com/43071948/46745791-60ac2580-cc73-11e8-8587-4254e3d50edd.png)

I added an inline PowerShell script to my release definition to update the registry as suggested by the provided link:
New-ItemProperty -path 'HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319' -name 'SchUseStrongCrypto' -value 1 -PropertyType 'DWord' -Force | Out-Null
New-ItemProperty -path 'HKLM:\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319' -name 'SchUseStrongCrypto' -value 1 -PropertyType 'DWord' -Force | Out-Null

The test is now able to pick up and run. So I believe that solves this issue. However, I still continue to get the following error and I am using the VsTest Platform Installer to install the latest pre-release (15.9.0):
The unit test adapter failed to connect to the data source or to read the data. Could not load file or assembly 'Microsoft.TeamFoundation.TestManagement.Controller or one of its dependencies. The system cannot find the file specified.

Do I also need to compile my solution with my test assemblies in 15.9?

**Comment by abhishkk** [comment]
@NDDeveloper13 Closing this issue. Will follow new issue raised on that issue.
