### ISSUE TITLE
Azure App Service Deploy: Can't change which service connection is used

### ISSUE THREAD

**Issue by phatcher** [Microsoft/vsts-tasks#8297]
We moved from a PAYG subscription to an EA one, which means I need to update the service connection used for deployments...

![image](https://user-images.githubusercontent.com/192778/45422948-af24cf00-b689-11e8-9eab-6a71e7b9ecc1.png)

The system won't let me update the existing service connection, presumably because it was authorised in a different AD.  I've successfully created a new service connection,  but I can't pick it in the deploy parameters .

If I create a new App Service Deploy task, the new service connection appears there, but that would mean re-creating every deployment task which is error prone.

Is there a better way?

**Comment by vincentdass** [comment]
@phatcher , Azure subscription is linked to process parameters.
Click on the Environment name and that will show the process parameters.
Then u can change the Azure subscription.
![image](https://user-images.githubusercontent.com/20121508/45424150-3c304e00-b6b3-11e8-9680-c35e1dcc10af.png)

**Comment by phatcher** [comment]
@vincentdass Thanks for that, I have to re-enter the resource group/slot settings, but that's to be expected.

Might be an idea to put another link on the Azure App Deploy that points you at the Deployment process parameters page, e.g. Update vs Manage - I haven't had to touch this for ~9 months or so which is why I forgot.

**Comment by phatcher** [comment]
Slightly odd, modifying a different pipeline that was created ~2.5 years ago and this one doesn't have any environment process parameters, but the Azure App Service deploy parameters shows refresh circles...

![image](https://user-images.githubusercontent.com/192778/45428404-1433f100-b699-11e8-8b90-36a2781fdf7c.png)

**Comment by phatcher** [comment]
@vincentdass Thanks for the update
