### ISSUE TITLE
vsts release deploy to kubernetes. Container registry throws 400 with inner exception

### ISSUE THREAD

**Issue by audunfr** [Microsoft/vsts-tasks#8298]
## Environment
- Server - VSTS Linux Hosted 

## Issue Description

1) Add a "Deploy to kubernetes" task and configure it with Azure resource manager. 
2) Expand "secrets" and enter Container registry type, Azure subscription, and try to get a list of azure container registry. 

The action fetching the list for the Azure container registry dropdown is failing with a inner exception of:
{"$id":"1","innerException":null,"message":"Neither service connection id nor service connection details is present. Provide any one of them.","typeName":"Microsoft.TeamFoundation.DistributedTask.WebApi.InvalidServiceEndpointRequestException, Microsoft.TeamFoundation.DistributedTask.WebApi","typeKey":"InvalidServiceEndpointRequestException","errorCode":0,"eventId":3000}

All fields available in the UI is filled out, the registry is used in the build pipe to push the docker container image. 

### Error logs
POST to https://seamlessno.visualstudio.com/579487ca-9a4e-4149-92a1-90aed12ad374/_apis/serviceendpoint/endpointproxy?endpointId=azureSubscriptionEndpoint2

Response > 
{"$id":"1","innerException":null,"message":"Neither service connection id nor service connection details is present. Provide any one of them.","typeName":"Microsoft.TeamFoundation.DistributedTask.WebApi.InvalidServiceEndpointRequestException, Microsoft.TeamFoundation.DistributedTask.WebApi","typeKey":"InvalidServiceEndpointRequestException","errorCode":0,"eventId":3000}

If adding the kubernete cluster as a Kubernetes service connection i can select correct Azure Container Registry, but i then have an error in kubernetes about not being able to fetch image due to credential errors.

**Comment by audunfr** [comment]
Wonderfull @bansalaseem. Do you know when it will be live at dev.azure.com or the old vsts portal (probarly the same though)?

**Comment by bansalaseem** [comment]
It should be live on dev.azure.com now.
