### ISSUE TITLE
Finding list of projects referring to different solution

### ISSUE THREAD

**Issue by AJreddy89** [Microsoft/vsts-tasks#8307]
We have different nodes of our architecture to reuse same code base. So, is there any way to find the list of projects that refer to a different solution.

SOLUTION A ; PROJ A
SOLUTION B; PROJ B

PROJ A have a project reference to PROJ B

This is more like a question rather than an issue. If someone could help me out, it would be very helpful.

**Comment by bryanmacfarlane** [comment]
This repo is for reporting issues with the tasks in the repo (/Tasks)
