### ISSUE TITLE
Code Coverage incorrect when NuGet packages contain pdb's

### ISSUE THREAD

**Issue by SartriX** [Microsoft/vsts-tasks#8316]
## Environment
- VSTS
- Project with nUnit testcases

## Issue Description
VS 2017 Enterprise 15.8.3 reports a total code coverage of 92.97% while VSTS build of the same project reports a coverage of 48.60%
The difference in the coverage files is the inclusion of foreign nuget packages into the results, where the criteria to have them included seem to be:
- Touched by unittest
- .pdb present

My assumption would be that both give (nearly) the same result, and certainly would not differ in the affected files to calculate over.

### VS result (correct)
![image](https://user-images.githubusercontent.com/23340190/45555382-f3a29d00-b838-11e8-9661-cd36cc0f8af4.png)

### VSTS result (incorrect)
Coverage file loaded from build into VS for display
![image](https://user-images.githubusercontent.com/23340190/45555402-fe5d3200-b838-11e8-8433-56153e323c62.png)

**Comment by ShreyasRmsft** [comment]
@SartriX you will have to add these to the exclusion filter in the runsettings to prevent code coverage from being calculated for these.

Ideally the platform will not try to understand which is a user dll and which is not. you will have to include/exclude these in the runsettings

**Comment by abhishkk** [comment]
@SartriX Is this issue resolved?

**Comment by SartriX** [comment]
I consider the suggested solution a workaround.

It brings a lot of overhead though, since the build-definitions are maintained by a smaller crew. Consider a workplace where not all developers have the same priviliges and checkin policies apply. It'll create the followng process:
- a developer decides to require an additional nuget package and is added to the solution
- builds will (partially) fail, due to policy on drop in coverage
- developer needs to contact another developer with correct priviliges to update the exclusions
- meanwhile developer is stranded, because pullrequest won't make it through a succesful build
Worst part of it: since VS does it fine, the developer has no cue up front that he's going to create an issue

From a product quality point of view I would find it unacceptable to have differences between VS and VSTS default behaviour.

Ideally, the platform should only determine coverage on code which has source. Having a .dll or a .pdb is insufficient for the determination.

**Comment by abhishkk** [comment]
@SartriX 
Can you share following info with us at devops_tools@microsoft.com? Please mention issue link in the mail.

VSTS info:
1. Set `system.debug` variable with value `true`
2. Share diagnostics logs and code coverage file.

VS info:
1. Close VS instances.
2. Uncomment `system.diagnostics` element in `vstest.console.exe.config`. This will set debug mode to true. Read comments in `vstest.console.exe.config` to do this correctly. You can find this file at location similar to `%\Program Files (x86)%\Microsoft Visual Studio\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe.config`
3. Start VS and run the tests with code coverage
4. Share diagnostics logs and code coverage file.

**Comment by abhishkk** [comment]
@SartriX Can you please share info asked above?

**Comment by abhishkk** [comment]
@SartriX Closing this issue due to no response. Please re-open to follow-up (along with the info asked above.)
