### ISSUE TITLE
DotNetCoreInstallerV0 task has a grammar mistake

### ISSUE THREAD

**Issue by akunaatrium** [Microsoft/vsts-tasks#8332]
If it doesn't find the requested version of .NET Core from the cache, it says this:

"Cache does not contains this particular .NET Core. Will be downloaded and installed."

The "contains" should be replaced with "contain", but while we are at it, I would suggest to replace the whole string with the following, but since I am no linguist, feel free to ignore the suggestion:

"The cache does not contain the requested version of .NET Core. Downloading and installing it now."

**Comment by hiyadav** [comment]
Thanks akunaatrium for the suggestion, we shall update the string.

**Comment by hiyadav** [comment]
We have merged the PR for this, hence closing the issue now.
