### ISSUE TITLE
Service Endpoints issue with if statements YAML build

### ISSUE THREAD

**Issue by andrewsuiter** [Microsoft/vsts-tasks#8343]
I'm am having issues with deploying to multiple branches.  When I attempt to run the build to 'master' the connection is not recognized.  Here is the message upon queue. 

"Step  input azureSubscription references service connection PRODKEYVAULTCONN which could not be found. The service connection does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz"

All service endpoints have the correct access.  If I take away the conditions and only use the PRODKEYVAULTCONN this works perfect.  As soon as I add 3 If statements it fails. 

I perfected the yamlauthz work around and that did not work. 

steps:
  - ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}:
    - task: AzureKeyVault@1
      displayName: 'Dev Key Vault Key'
      inputs:
        azureSubscription: 'DEVKEYVAULTCONN'
        KeyVaultName: 'devkeyvaultname'
        SecretsFilter: '*'

  - ${{ if eq(variables['Build.SourceBranchName'], 'release') }}:
    - task: AzureKeyVault@1
      displayName: 'Test Key Vault Key'
      inputs:
        azureSubscription: 'TESTKEYVAULTCONN'
        KeyVaultName: 'testkeyvaultname'
        SecretsFilter: '*'

  - ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    - task: AzureKeyVault@1
      displayName: 'Prod Key Vault Key'
      inputs:
        azureSubscription: 'PRODKEYVAULTCONN'
        KeyVaultName: 'prodkeyvaultname'
        SecretsFilter: '*'

**Comment by bryanmacfarlane** [comment]
This repo is for issues with the in the box tasks (/Tasks).  You can create an issue / question and tag yaml in the azure-pipelines-agent repo
