### ISSUE TITLE
Azure PowerShell VSTS task might use incorrect Azure Resource Manager endpoint (not selected) if it has access to the same Azure Subscription

### ISSUE THREAD

**Issue by arbitertl** [Microsoft/vsts-tasks#8347]
## Environment
- Server - VSTS (can't specify account name etc. because of NDA, but it's not account specific)
- Agent - Private (Windows, version 2.140.0)

## Issue Description

We're using several Service Endpoints for Azure Resource Manager that are using the same subscription, however some of them are scoped to resource group, some has access (Contributor) for the whole subscription.

**When specifying "Azure Subscription" (actually Azure Resource Manager Endpoints - service principal, not subscription) in Azure PowerShell task it might pick the wrong endpoint (not the one specified) if that agent previously used different endpoint for the same Azure Subscription (actual subscription, not task field value).**

Currently we're using work around: adding VSTS PowerShell task executing:
`Get-AzureRmContext -ListAvailable | Remove-AzureRmContext -Verbose -Force`

**Comment by SumiranAgg** [comment]
@arbitertl We have fixed this issue in Azure powershell version 3.*
In which version are you facing this problem?

**Comment by arbitertl** [comment]
We were using version 2. Ok, good to know it's fixed. I'll try 3.*
