### ISSUE TITLE
Use Python: Agent running as network service no access to %APPDATA%

### ISSUE THREAD

**Issue by riezebosch** [Microsoft/vsts-tasks#8372]
Is there a good reason (or is it common) to store the user script in the `APPDATA` folder? Because we're having troubles when the agent is running as `Network Service` and it has no permissions on (its own?) folder.

https://github.com/Microsoft/vsts-tasks/blob/558907c9daba652200a163c44c83a47165357491/Tasks/UsePythonVersionV0/usepythonversion.ts#L78-L79

The logs for prepending the environment variable in the `Use Python` task.
```
2018-09-19T08:59:11.2254324Z Prepending PATH environment variable with directory: C:\hostedtoolcache\windows\Python\3.6.4\x64
2018-09-19T08:59:11.2257036Z Prepending PATH environment variable with directory: C:\hostedtoolcache\windows\Python\3.6.4\x64\Scripts
2018-09-19T08:59:11.2258363Z Prepending PATH environment variable with directory: C:\Windows\ServiceProfiles\NetworkService\AppData\Roaming\Python\Python36\Scripts
```

The logs when running `tox`
```
018-09-19T09:02:46.4264273Z PermissionError: [Errno 13] Permission denied: 'C:\\Windows\\SERVIC~2\\NETWOR~1\\AppData\\Local\\Temp\\tmpdridq6ya'
2
```

**Comment by brcrista** [comment]
@riezebosch that's where Pip installs command-line executables on Windows when you Pip install with the `--user` flag, so it needs to be added to `PATH`.

Can you give details on what you are doing with Tox?

**Comment by riezebosch** [comment]
I'll close it for now because the problem also arises when the TMP folder is remapped to another folder (`$(agent.tempdirectory)` for example) on which the build service account definitely has permissions on.
