### ISSUE TITLE
Publish Code Coverage Results: coverage.py Cobertura xml not displaying result

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [Microsoft/vsts-tasks#8376]
Using Azure DevOps

## Issue Description

```&view=codecoverage-tab```
Error message
```
Code coverage data cannot be displayed. Please verify that a valid directory containing code coverage files, including an index.html was used to publish data.
```

### Task logs
```
2018-09-20T18:21:24.1776880Z ##[section]Starting: Publish code coverage from $(System.DefaultWorkingDirectory)/**/coverage.xml
2018-09-20T18:21:24.1913796Z ==============================================================================
2018-09-20T18:21:24.1931112Z Task         : Publish Code Coverage Results
2018-09-20T18:21:24.1947780Z Description  : Publish Cobertura or JaCoCo code coverage results from a build
2018-09-20T18:21:24.1965544Z Version      : 1.139.0
2018-09-20T18:21:24.1982934Z Author       : Microsoft Corporation
2018-09-20T18:21:24.2001218Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=626485)
2018-09-20T18:21:24.2019569Z ==============================================================================
2018-09-20T18:21:26.9037822Z Reading code coverage summary from '/home/vsts/work/1/s/coverage.xml'
2018-09-20T18:21:27.0160754Z ##[section]Async Command Start: Publish code coverage
2018-09-20T18:21:27.0179363Z Publishing coverage summary data to TFS server.
2018-09-20T18:21:27.0197668Z  Lines- 2804 of 6777 covered.
2018-09-20T18:21:27.0217477Z  Branches- 0 of 0 covered.
2018-09-20T18:21:27.5243160Z Modifying Cobertura Index file
2018-09-20T18:21:27.5262744Z Publishing code coverage files to TFS server.
2018-09-20T18:21:27.5282332Z Uploading 1 files
2018-09-20T18:21:27.6041098Z File upload succeed.
2018-09-20T18:21:27.6060859Z Published '/tmp/Code Coverage Report_857678' as artifact 'Code Coverage Report_857678'
2018-09-20T18:21:27.6086468Z ##[section]Async Command End: Publish code coverage
2018-09-20T18:21:27.6169492Z ##[section]Finishing: Publish code coverage from $(System.DefaultWorkingDirectory)/**/coverage.xml
```

## Troubleshooting
Lesson learned with other cloud providers:
It will be nice if you can provide open-source solutions, so we debug our self the problem, find the error message on GitHub and understand the reason of the message, not like old style black box software.

People are trying different hacks to make the XML compatible with Azure DevOps:
 1. https://github.com/dazfuller/PyUnitTestTask/blob/master/src/reportgen.ts
 1. https://github.com/Microsoft/vsts-tasks/issues/2186#issuecomment-316074078

Tested both hacks without success, maybe is time to make something that it is working without losing the time of the developers to display coverage results that are working perfectly well in Coveralls.io, CircleCI, etc. more Python-friendly coverage environment :)

**Comment by abhishkk** [comment]
Closing the issue. Please re-open in case you are still facing issues after uploading index.html file.

**Comment by VelizarVESSELINOV** [comment]
@abhishkk managed to upload the `index.html` as an artifact, but I fill far away from the power that you are claiming of the tool:
```
2018-10-09T01:34:44.8254402Z Uploading 1 files
2018-10-09T01:34:44.8254445Z Uploading 1 files
2018-10-09T01:34:45.0237820Z File upload succeed.
2018-10-09T01:34:45.0237904Z File upload succeed.
2018-10-09T01:34:45.0237936Z Published '/tmp/Code Coverage Report_879180' as artifact 'Code Coverage Report_879180'
2018-10-09T01:34:45.0238127Z Published '/tmp/Code Coverage Files_879180' as artifact 'Code Coverage Files_879180'
```
What it is needed to make the index.html or the multiple .html, js, cs files to be displayed?

```
steps:
- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage from $(System.DefaultWorkingDirectory)/**/coverage.xml'
  inputs:
    codeCoverageTool: Cobertura

    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'

    reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov/'

    additionalCodeCoverageFiles: '$(System.DefaultWorkingDirectory)/**/htmlcov/index.html'

```

**Comment by stephanebachelier** [comment]
I had the same issue with running code coverage on a Javascript project with `nyc`. 
First my configuration in `azure-pipelines.yaml` was : 

```
- script: |
    ./node_modules/.bin/nyc --reporter=cobertura report
  displayName: 'Build code coverage report'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
  displayName: 'Publish code coverage results'
```

<img width="601" alt="screenshot 2018-11-26 at 10 54 59" src="https://user-images.githubusercontent.com/172615/49006825-3d2d3380-f16a-11e8-8131-659d75cee2ed.png">

I've updated the configuration to provide also an `index.html`, as I've read it should be present to display a summary on the `Coverage` tab.

Basically I've added the `--reporter=html` to the script that build the code coverage: 

```
- script: |
    ./node_modules/.bin/nyc --reporter=cobertura --reporter=html report
  displayName: 'Build code coverage report'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
  displayName: 'Publish code coverage results'
```


The default output displays the summary but it's really awful :

<img width="690" alt="screenshot 2018-11-26 at 10 54 27" src="https://user-images.githubusercontent.com/172615/49006859-559d4e00-f16a-11e8-9a21-6851a8f24798.png">

I've eventually understood that all assets are removed (css, scripts, ...).
I've added a new step to inline all CSS into final `index.html` file and it looks better ! 

```
- script: |
    ./node_modules/.bin/nyc --reporter=cobertura --reporter=html report
    ./node_modules/.bin/juice coverage/index.html coverage/index.html # fix ADO rendering
  displayName: 'Build code coverage report'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
  displayName: 'Publish code coverage results'
```

<img width="1348" alt="screenshot 2018-11-26 at 11 10 04" src="https://user-images.githubusercontent.com/172615/49008019-22a88980-f16d-11e8-8e39-b4ba85761507.png">

**Comment by anishkny** [comment]
Ugh. This is unacceptable sorry. Going to have to go with https://coveralls.io/ for now until the dev experience is improved.

**Comment by Tob0t** [comment]
@stephanebachelier Thank you for the detailed explanation, that worked for me :)
However, as soon as you navigate into a file you have the same problem again with external css .. you could write a script which is recursively traversing all html files and transforms then, but this would be just a workaround..

Couldn't Azure implemented an option to use external css and js files? @abhishkk

**Comment by 7jpsan** [comment]
> I had the same issue with running code coverage on a Javascript project with `nyc`. First my configuration in `azure-pipelines.yaml` was :
> 
> ```
> - script: |
>     ./node_modules/.bin/nyc --reporter=cobertura report
>   displayName: 'Build code coverage report'
> 
> - task: PublishCodeCoverageResults@1
>   inputs:
>     codeCoverageTool: 'cobertura'
>     summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
>     reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
>   displayName: 'Publish code coverage results'
> ```
> 
> <img alt="screenshot 2018-11-26 at 10 54 59" width="601" src="https://user-images.githubusercontent.com/172615/49006825-3d2d3380-f16a-11e8-8131-659d75cee2ed.png">
> 
> I've updated the configuration to provide also an `index.html`, as I've read it should be present to display a summary on the `Coverage` tab.
> 
> Basically I've added the `--reporter=html` to the script that build the code coverage:
> 
> ```
> - script: |
>     ./node_modules/.bin/nyc --reporter=cobertura --reporter=html report
>   displayName: 'Build code coverage report'
> 
> - task: PublishCodeCoverageResults@1
>   inputs:
>     codeCoverageTool: 'cobertura'
>     summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
>     reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
>   displayName: 'Publish code coverage results'
> ```
> 
> The default output displays the summary but it's really awful :
> 
> <img alt="screenshot 2018-11-26 at 10 54 27" width="690" src="https://user-images.githubusercontent.com/172615/49006859-559d4e00-f16a-11e8-9a21-6851a8f24798.png">
> 
> I've eventually understood that all assets are removed (css, scripts, ...). I've added a new step to inline all CSS into final `index.html` file and it looks better !
> 
> ```
> - script: |
>     ./node_modules/.bin/nyc --reporter=cobertura --reporter=html report
>     ./node_modules/.bin/juice coverage/index.html coverage/index.html # fix ADO rendering
>   displayName: 'Build code coverage report'
> 
> - task: PublishCodeCoverageResults@1
>   inputs:
>     codeCoverageTool: 'cobertura'
>     summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
>     reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
>   displayName: 'Publish code coverage results'
> ```
> 
> <img alt="screenshot_2018-11-26_at_11_10_04" width="1348" src="https://user-images.githubusercontent.com/172615/49008425-1244de80-f16e-11e8-8e31-ffd48a51186f.png">

Thanks! That saved my eyes! As @Tob0t mentioned, I had to traverse the html report files with: 

`"test:coverage:inline-styles": "find ./coverage -name '*.html' -exec npx juice {} {} \\;",`

Added the step in the pipeline before publishing and it worked. Yes, a workaround, but at least one that works while/if they fix it or we move on to another pipeline...
