### ISSUE TITLE
Looking to make use of Powershell Core (pwsh) in tasks over PowerShell

### ISSUE THREAD

**Issue by kilasuit** [Microsoft/vsts-tasks#8386]
## Environment
VSTS 

- Agent - Hosted or Private: 
Mixed of Hosted and Private & multi OS
Private will be Server 2016 and have PowerShell Core installed

## Issue Description

Ideally want to be able to make use of the changes added in #7913 to enable use of PowerShell Core in build tasks over using PowerShell.

There is currently no option to allow me to pick it to use pwsh in the PowerShell Task UI

cc @bergmeister

**Comment by bergmeister** [comment]
@kilasuit As far as I can tell, an agent currently checks out version `2.136.0` of the `PowerShellV2` task and by looking into it, it does not have the updated script of the master branch in it, therefore I can only conclude that this task still has not been published to the marketplace yet, which is why we do not see the option in the UI yet. Thanks for raising this again.

**Comment by ShreyasRmsft** [comment]
@bergmeister @kilasuit releases/M140 branch has the changes you need: https://github.com/Microsoft/vsts-tasks/tree/releases/m140/Tasks/PowerShellV2 

The deployments for 140 has started. It will take some time to be completed for all accounts.

**Comment by kilasuit** [comment]
@ShreyasRmsft thanks for the update. Do you have any idea as to the maxium amount of time this may be to end up seeing this in our AzDO tenants?

**Comment by ericsciple** [comment]
140 is scheduled to reach the last set of accounts today

**Comment by bergmeister** [comment]
Thanks for the update. I can't see the update yet but will wait and confirm once it has

**Comment by bergmeister** [comment]
@ericsciple Any update on the rollout of 2.140? The PowerShell versions in my accounts are still on 2.136

**Comment by ericsciple** [comment]
What is the account name? I think there is one scale unit in the last deployment ring that did not get updated...

**Comment by ericsciple** [comment]
@bergmeister sorry something got missed. Although the changes for the powershell task is in releases/m140 branch, they did not get propagated to the deployment manifest files.

M141 includes the changes. M141 is on Rings 0-2, and rolling to ring 3 tomorrow. We typically progress 1 ring every day or so. So I wouldn't expect the changes to hit your account before Thursday or Friday.

If you want the change sooner, you can checkout the releases/m141 branch, build the powershell task and upload it to your account using TFX.

**Comment by bergmeister** [comment]
@kilasuit @xenalite
I see the option now in my Azure DevOps instances

**Comment by kilasuit** [comment]
Can confirm this is in mine as well
