### ISSUE TITLE
File exists but pipeline step says, "Invalid file path '...\setEnvironmentVariables.p1'. A path to a .ps1 file is required."

### ISSUE THREAD

**Issue by nikolay-advolodkin** [Microsoft/vsts-tasks#8413]
## Environment
- Server - Azure Pipelines
provide the account name: nikolayadvolodkin
team project name: SauceExamples
build definition name: simple-selenium
build number: 20180925.8

- Agent: 
Hosted agent, agent queue name:  Hosted VS2017

## Issue Description
Azure Pipeline says "Invalid file path 'D:\a\1\s\SimpleTests\SimpleTests\setEnvironmentVariables.p1'. A path to a .ps1 file is required."

However, this file is obviously present and can be seen [here](https://github.com/nikolay-advolodkin/simple-selenium/blob/master/SimpleTests/SimpleTests/setEnvironmentVariables.p1) and also I chose it using the UI provided by the Powershell task from [here](https://screencast.com/t/ru1iBBaVBY3). 

Error Screenshot - https://screencast.com/t/BmLxlgZRup

### Task logs

[log_10_181.zip](https://github.com/Microsoft/vsts-tasks/files/2416081/log_10_181.zip)

### Error logs
"Invalid file path 'D:\a\1\s\SimpleTests\SimpleTests\setEnvironmentVariables.p1'. A path to a .ps1 file is required."
Error Screenshot - https://screencast.com/t/BmLxlgZRup

**Comment by JohannesDrexler** [comment]
The file needs to have an ps1-extension, not a p1. 
rename your file and update the builddefinition then it should work

**Comment by nikolay-advolodkin** [comment]
Haha, durrr, that would make sense :(

**Comment by buminda** [comment]
Thanks...it worekd. .I was trying with ps extension :(

**Comment by sheteshruti** [comment]
In my case, My file name ends with extension .ps1 yet it fails with the same error : ##[error]Invalid file path 'C:\agent\_work\5s\test-migration.ps1'. A path to a .ps1 file is required.

**Comment by JohannesDrexler** [comment]
@sheteshruti "C:\agent_work\5s\" is not a valid path, it should be "C:\agent_work\5\s\". "5" is the local workspace for the pipeline process (a local id given for each project/pipeline in an agents work directory) and "s" is the subdirectory where the repository is downloaded to.
