### ISSUE TITLE
Feature Request: Windows File Copy => Use managed credentials

### ISSUE THREAD

**Issue by kylelaverty** [Microsoft/vsts-tasks#8437]
## Description
It would be great if this task could make use of the inbuilt Azure credentials system so the password did not have to be managed in the task.

Alternatively, it would be better if the password field was obfuscated like the secure variables.

**Comment by kmkumaran** [comment]
Windows File copy Task is generic and not tied to Azure. It can also be used to copy to any stand alone VMs or Machines backed by AAD or workgroup. 
If you are looking for Azure specific copy task you would want to look at "Azure File Copy" task. 

With regard to password field, you can make use of variables.
![image](https://user-images.githubusercontent.com/11780076/46186149-b0e1ca00-c2fa-11e8-88dc-7a3d6873ef06.png)

You can then refer those variables as $(variableName) in the password field.

**Comment by kylelaverty** [comment]
@kmkumaran Thank you for the feedback about the variables. For the credentials I was thinking something like what the AWS tasks do.
![image](https://user-images.githubusercontent.com/12103001/46227219-89a3f080-c32c-11e8-89f0-aa682b27d83c.png)
You configure a credential, save it in the central store and then can use it in many tasks without retying. Even across deployments and between deployment and release.

**Comment by RoopeshNair** [comment]
@kylelaverty  - you can do that with variable groups. Define the credentials as variables in a variable group and refer to it in the task.
