### ISSUE TITLE
ExtractFilesV1 task - where is 7z.exe?

### ISSUE THREAD

**Issue by MSP-Greg** [Microsoft/vsts-tasks#8451]
So, while wrestling with a PS script to install a few prereq's, I came across the following line in the [typescript file](https://github.com/Microsoft/vsts-tasks/blob/master/Tasks/ExtractFilesV1/extractfilestask.ts#L21) here:

```ts
var winSevenZipLocation: string = path.join(__dirname, '7zip/7z.exe');
```

I would like to use 7z.  It would seem that there's a task wrapping it.  But, I want to run it from a script that isn't often updated, and would add quite a bit to the yml file.

Maybe you could also tell use where it is?  Some other CI services set an env variable 7z to it's full path.  I don't really need (or want) a task/dsl to use it.

## Environment
- Server - Azure Pipelines

**Comment by bryanmacfarlane** [comment]
This task packages 7z in the task and is downloaded with the task (__dirname).  So adhoc scripts can't use assets internal to that task.  You are free to check it in or download it yourself.

**Comment by bryanmacfarlane** [comment]
answered the question.  let us know if it's not clear and we can reactivate.

**Comment by bryanmacfarlane** [comment]
hosted images: https://github.com/Microsoft/azure-pipelines-image-generation
