### ISSUE TITLE
VSTS Task to install DotNet Core SDK failing for 2.1.403

### ISSUE THREAD

**Issue by NetTecture** [Microsoft/vsts-tasks#8472]
2018-10-02T18:20:40.4342027Z ##[warning]Could not download installation package from this URL: https://dotnetcli.blob.core.windows.net/dotnet/Sdk/2.1.403/https://download.visualstudio.microsoft.com/download/pr/28820b2a-0aec-4c24-a271-a14bcb3e2686/5e0ad8ae32f1497e8d0cace2447b9e01/dotnet-sdk-2.1.403-win-x64.zip Error: {}
2018-10-02T18:20:40.4368746Z ##[error]Failed to download package for installation
2018-10-02T18:20:40.4533485Z ##[section]Finishing: Use .NET Core sdk 2.1.403

But it should be there:

https://www.microsoft.com/net/download

shows 2.1.403 as download.

**Comment by luchenatwork** [comment]
According to release json file: https://github.com/dotnet/core/blob/master/release-notes/releases.json.
The 2.1.403 SDK section has full download URL instead of just file name which is different from previous release version.

**Comment by luchenatwork** [comment]
Issue submitted to .NET Core group
https://github.com/dotnet/core/issues/1973

**Comment by bishal-pdMSFT** [comment]
@NetTecture I have created a new issue dotnet/core#1977. We will also be handling this from our side.

**Comment by NetTecture** [comment]
Please. This is now day 2 we can not run modern builds on the agents because we ant to check upgrades to the current SDK. This also need to be tested - can not be that this is an unstable part.

**Comment by NetTecture** [comment]
And now it has another days passed and we STILL can not build using the current framework.

**Comment by bishal-pdMSFT** [comment]
@NetTecture we are working on this and the fix will soon be rolled out, but this is not a very high priority item for us as this issue appears only for one version of .net core. I would suggest you to take some work-around in the meanwhile: either use a different version or if you really need this particular version, then use a private agent having this installed. it might take a couple of days for us to do a safe roll out of the fix.

**Comment by NetTecture** [comment]
Here is what you said: We are microsoft. We do not support our own product in the current version. We gladly take your money (for private agents), though, so you are not able to build it because - lack of competence and we consider you not building not important because we get paid anyway. Something like that correct? Does your manager know how you sabotage Azure DevOps?

Damn, low priority? Anyone on your team on drugs? What about your low priority pays my team's loss of income? And "use a private agent" - seriously? This is one advice I would personally FIRE you for incompetence. There are reasons we use private agents, they do not go just because you are not able to actually support current dotnet versions. WHOW. AMAZING. In the past I was used to this level of competence and customer service from Oracle. Customer oriented companies run different. What happened to the Microsoft of Steve?

We are rolling back for now. Let's try the CURRENT framework again on monday and see whether your company considers supporting it then...

**Comment by cyberprune** [comment]
This is now a blocker for us too and is stopping our pipelines from building since the latest version has been rolled out. This should be a high priority item, as it's now blocking our team from deploying new versions of the software and we do not wish to manually hard code all of the framework versions in each project.

**Comment by bishal-pdMSFT** [comment]
We have started rolling out hotfix for this issue. It should reach all customers by tomorrow.

**Comment by kant2002** [comment]
Thanks, a lot!!!

**Comment by luchenatwork** [comment]
@bishal-pdMSFT Thank you and VSTS team for the quick fix.

The dotnet team should really be blamed with this breaking changes.  How could they not knowing to notify the other internal Microsoft team?

**Comment by pedrodon** [comment]
How do I know that the fix is there?  My cloud VSTS build is still failing at the SDK install task

**Comment by bishal-pdMSFT** [comment]
The fix has been rolled out completely. You can retry the task.

**Comment by pedrodon** [comment]
It works, thank you!

**Comment by kant2002** [comment]
@bishal-pdMSFT thanks!
