### ISSUE TITLE
Browse and upload a local file as part of VSTS build task

### ISSUE THREAD

**Issue by knowds** [Microsoft/vsts-tasks#8512]
As part of VSTS custom build task, we need to allow users to browse and select a local file . This file in turn needs to be uploaded to our server using a REST API. This works when the file is source controlled in github using filepath type in task.json. However, this is a generated file and will not be source controlled. Hence we need an option wherein user should be able to select any file on his machine for upload.

**Comment by bryanmacfarlane** [comment]
This isn't an issue with one of the tasks in this repo (/Tasks).  It's also a service side issue (new web UI) .  You can create something in developer community.
