### ISSUE TITLE
"Visual Studio Build" build step that actually invokes devenv.com instead of msbuild?

### ISSUE THREAD

**Issue by jmacnett** [Microsoft/vsts-tasks#946]
I discovered today that the "Visual Studio Build" build step, contrary to the name, is actually launching an instance of MSBuild, vs what it sounds like (running via devenv.com).  This is a huge disappointment, as I was very excited to *not* have to hand-roll that part of the process for my SSRS and dbproj builds. 

 Are there any plans to make an actual visual studio build, or should I break out powershell again?

**Comment by mmajcica** [comment]
Same here. Seems there is no build task that supports building via devenv.exe. That will be beneficial in case of our SSIS projects that are not supported via MSBuild.

**Comment by chrisrpatterson** [comment]
That is not something we are working on right now, but it is something that we would take a pull request for.

**Comment by mmajcica** [comment]
Hi @chrisrpatterson I would like to contribute, and I do know my way around in order to so. I do see as options a choice to build, clean, rebuild. Arguments like SolutionName, project name and project configuration. Also a choice to choose the version of Visual Studio. What should be the name of such a build task?

**Comment by jmacnett** [comment]
@mmajcica I've got a functional one in place on our local TFS instance.  If you haven't already submitted one, I can create a pull request for my variant today.

**Comment by mmajcica** [comment]
@jmacnett I haven't even started. If you share you code, I'll be grateful. Cheers

**Comment by jmacnett** [comment]
it's in as a pull request now

**Comment by embix** [comment]
That would be helpful for our .vdproj setup projects - less fiddling around with custom powershell scripts.

**Comment by rrober07** [comment]
Will this vso-agent-tasks be available for TFS 2015 update 2 on premise?

**Comment by bryanmacfarlane** [comment]
what's in QU2 is the releases/m95 branch in this repo.

**Comment by bryanmacfarlane** [comment]
Consider for QU3? @chrisrpatterson

**Comment by rrober07** [comment]
are we still looking at QU3?

**Comment by bryanmacfarlane** [comment]
Copying to our backlog.  Not tracking as an issue.  We will add this option.

**Comment by rrober07** [comment]
where can I get this update ... we are wanting to implement

**Comment by schwaizi** [comment]
You can try extension below until fix deployed

@[SSIS Build & Deploy](https://marketplace.visualstudio.com/items?itemName=TG.VSTS-SSIS)

**Comment by mmajcica** [comment]
Are there any updates on building SSRS and SSIS projects (a non MSBuild projects)?

**Comment by ericsciple** [comment]
@vijayma

**Comment by ericsciple** [comment]
@mmajcica i think we have a slightly different plan now, that will enable what you are looking for. I'll ping @vijayma offline to comment.

**Comment by psandhu79** [comment]
We also require this to build with Intel fortran any update on when we can use devenv ?

**Comment by vijayma** [comment]
This work is not scheduled yet. Sorry. You should be able to write a custom task meanwhile.

**Comment by NullReferenceError** [comment]
Also would like to be able to do this to build older versions of rptproj files.  Do others work around this by using the Command Line step and manually invoking "devenv.exe"?

**Comment by onooka** [comment]
How can I to pass password as a command line devenv interface in project SSIS with EncryptAllWithPassword ProtectionLevel

**Comment by DynConcepts** [comment]
And as far as I can tell, still not in Azure DevOps many years later (or have I missed something)?
