### ISSUE TITLE
Publish Build Artifacts task - The definition for the task does not have a handler that matches any supported by this agent.

### ISSUE THREAD

**Issue by jdrake3** [Microsoft/vsts-tasks#948]
Using the Build tab in Visual Studio Team Services, including the Publish Build Artifacts task in the Build causes it to fail with the following error:

The definition for the task does not have a handler that matches any supported by this agent. Supported handlers: AzurePowerShell, AzurePowerShellHandler, PowerShell, PowerShellHandler, PowerShellExe, PowerShellExeHandler, Process, ProcessHandler

See: http://stackoverflow.com/questions/33917308/vso-vsts-error-when-using-publish-build-artifacts-on-the-host-agent and https://connect.microsoft.com/VisualStudio/feedback/details/2059436 for additional information.

The work around described in the SO answer works, the based on the closed issue here about Two Publish Tasks, we should not be using the Copy version of the task.

**Comment by TingluoHuang** [comment]
This is temporally issue with hosted agent, since we are hitting issue when updates host agent.
We are still working on it.

**Comment by JamesInDenver** [comment]
Generally speaking, will the Windows agent run node tasks?  Or are we expected to write each task twice?  I'm seeing the same error on a Windows build machine with a task that only has a node script (no powershell).  The build agent does have "node.js" as a system capability.

**Comment by gravufo** [comment]
Bump, i'd like to know this as well. Trying to run a Node-only task on a windows agent throws the same error even though node.js is installed.

**Comment by chrisrpatterson** [comment]
What is the agent version? Node tasks on windows are only supported past 1.92.

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Wed, Jan 27, 2016 at 6:31 AM -0800, "Christian Artin" <notifications@github.com<mailto:notifications@github.com>> wrote:


Bump, i'd like to know this as well. Trying to run a Node-only task on a windows agent throws the same error even though node.js is installed.

-

**Comment by gravufo** [comment]
Thanks for the fast reply. You're right, my agent is version 1.89.1. I'm using On-Premise TFS, is there a way to get the newest Windows agents?

**Comment by chrisrpatterson** [comment]
Not until tfs update 2.

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Wed, Jan 27, 2016 at 6:31 AM -0800, "Christian Artin" <notifications@github.com<mailto:notifications@github.com>> wrote:


Bump, i'd like to know this as well. Trying to run a Node-only task on a windows agent throws the same error even though node.js is installed.

-

**Comment by gravufo** [comment]
Sounds good. Thanks a lot for the info!

**Comment by bryanmacfarlane** [comment]
@gravufo 

>>  my agent is version 1.89.1

The publish build artifacts task demands agent version 91 
"minimumAgentVersion": "1.91.0",

The server should have rejected you trying to upload a task that requires a future agent (which it does not deliver).  Curious if you were able to try and use that task.  It should have never gotten uploaded and thus never sent to an agent.

**Comment by gravufo** [comment]
@bryanmacfarlane I was uploading a custom task, not the publish build artifact task! I didn't know about the agent version requirement for Node tasks, hence why I didn't set it that high. Anyway, I'll just temporarily write a PowerShell script to do the same thing, but I'm looking forward to only supporting one script instead of two :)

Thanks!

**Comment by bryanmacfarlane** [comment]
Ahh - cool.  Then the right thing for you to do is require minimum agent version of 91 :) Thanks
