### ISSUE TITLE
Enhancement: Support multiple provisioning profiles in the Xcode Build task

### ISSUE THREAD

**Issue by Chuxel** [Microsoft/vsts-tasks#964]
Even when generating one ipa/app there are situations where you'll need to use multiple provisioning profiles with the same build. In particular, creating things like [file provider and document provider extensions](https://developer.apple.com/app-extensions/) require [different provisioning profiles](http://stackoverflow.com/questions/25329510/ios8-extension-needs-own-provisioning-profile).

The current Xcode Build task works with this scenario if the profiles are installed on the machine but not for the file reference version. To help reduce setup, it would be simple to instead switch to a list and support installing multiple provisioning profiles in the task.

Since the Xcode Build task determines the UUID of the provisioning profile to use for signing automatically, we won't be able to have the task itself install multiple certs, but we can easily create an "Install Provisioning Profile" task to do so to ease maintenance.

**Comment by madhurig** [comment]
The plan is to have a separate task to install provisioning profiles on the build machine and not complicate the Xcode task to do the installation.

**Comment by madhurig** [comment]
We are tracking this on our internal backlog.

**Comment by abdullah007001** [comment]
Following up on same topic, may i know if this has been addressed by Microsoft?
https://github.com/microsoft/azure-pipelines-tasks/issues/13776
https://github.com/microsoft/azure-pipelines-tasks/issues/8811

**Comment by JohnHSE** [comment]
@madhurig we are experiencing the same issue, the 2nd provisioning profile always replaces the first. Why is this closed when it doesn't work?
