### ISSUE TITLE
Unclear error message now that Publish Build artifact no longer supports wildcards

### ISSUE THREAD

**Issue by jessehouwing** [Microsoft/vsts-tasks#996]
Another breaking change in the Publish Build artifact seems to be that it no longer supports wildcards.

We have an artifact that has a generated version number in the name and the only way I found I could publish this, is to place it in a folder with a fixed name, then publish the folder. In the past we used `$(Build.StagingDirectory)\$(Build.Configuration)\Update*.zip`.

This now results in an ugly error telling me that there are illegal characters in the path and not telling me which path, nor which characters.

This configuration:
![image](https://cloud.githubusercontent.com/assets/4173387/11914158/684950fc-a678-11e5-901d-b53f6ad9840c.png)

Results in:
![image](https://cloud.githubusercontent.com/assets/4173387/11914155/541a8c9a-a678-11e5-833e-4747928cb20d.png)

In the past there was a Copy Root + Contents field instead of path, which accepted wildcards:

![image](https://cloud.githubusercontent.com/assets/4173387/11914169/a99a0902-a678-11e5-932c-ad315f03a617.png)

**Expected behavior**
Validation of the path variable in the UI. Plus a better error message telling me which exact text caused the error in question, preferably also telling me which characters it doesn't like.

**Comment by TingluoHuang** [comment]
In the help markdown for 'Path to Publish' parameter, we document that it suppose to be a fully qualified path or relative path relative to the repo root. 
I will add a wildcards not support as additional information. 
I will provide better error message on failure.

The scenario of using 'Publish build artifact' is I just want to publish that one folder/file.

Thanks for report.

**Comment by jessehouwing** [comment]
Ahh, I now see the other "Copy and Publish Build Artifacts" task. They got me confused. maybe name them "Publish build artifacts" and "Publish build artifact", that way they appear net to each other and cause less confusion.

Thanks for adding a better message, having a hint from the tooltip or help page to point to "the other task" may be helpful. That way people are sure to find the alternative one.

If you can detect "illegal characters" as part of the validation, I'd add that too, since it saved a debug build. My biggest issue with Build 2015 right now is that to get every linked up and corrected I'm running way too many builds due to these kind of "stupid mistakes".

I'll raise a separate issue for that.

**Comment by bryanmacfarlane** [comment]
This isn't a breaking change.  Publish was a new task.  Copy and Publish was split in two.  Copy and Publish is still around as is.  Copy supports all the mini match patterns.  You use that to copy into an artifacts folder (or multiple of them) and then publish that folder.  That's why it supports one.
